function test_structure_aware_consistency()
% TEST_STRUCTURE_AWARE_CONSISTENCY - Regression tests for structure-aware decoupled weighting

clc;
setPath;

fprintf('Test 1: spatial branch downweights posterior outlier\n');
[gaWeights, ~, debug] = computeAdaptiveFusionWeights( ...
    buildSpatialOutlierDistributions(), cell(3, 1), buildModelConfig(), 1, struct(), struct());
fprintf('  spatial weights:   %s\n', mat2str(debug.gaSpatialWeights, 4));
fprintf('  existence weights: %s\n', mat2str(debug.gaExistenceWeights, 4));
assert(debug.gaSpatialWeights(3) < debug.gaSpatialWeights(1));
assert(debug.gaSpatialWeights(3) < debug.gaSpatialWeights(2));
assert(numel(gaWeights) == 3);

fprintf('Test 2: existence branch downweights existence-disagreement outlier\n');
[~, ~, debug] = computeAdaptiveFusionWeights( ...
    buildExistenceOutlierDistributions(), cell(3, 1), buildModelConfig(), 1, struct(), struct());
fprintf('  spatial weights:   %s\n', mat2str(debug.gaSpatialWeights, 4));
fprintf('  existence weights: %s\n', mat2str(debug.gaExistenceWeights, 4));
assert(debug.gaExistenceWeights(3) < debug.gaExistenceWeights(1));
assert(debug.gaExistenceWeights(3) < debug.gaExistenceWeights(2));

fprintf('All structure-aware consistency tests passed.\n');
end

function model = buildModelConfig()
model = struct();
model.numberOfSensors = 3;
model.xDimension = 4;
model.gaSensorWeights = ones(1, 3) / 3;
model.aaSensorWeights = ones(1, 3) / 3;
model.gaSpatialWeights = model.gaSensorWeights;
model.aaSpatialWeights = model.aaSensorWeights;
model.gaExistenceWeights = model.gaSensorWeights;
model.aaExistenceWeights = model.aaSensorWeights;
model.gaSpatialStructurePrior = ones(1, 3);
model.gaExistenceStructurePrior = ones(1, 3);
model.gaTopologyWeights = ones(1, 3);
model.aaTopologyWeights = ones(1, 3);
model.adaptiveFusion = struct( ...
    'enabled', true, ...
    'useCovariance', false, ...
    'useLinkQuality', false, ...
    'useNIS', false, ...
    'useHistory', false, ...
    'useCardinalityConsensus', false, ...
    'useExistenceConfidence', true, ...
    'existenceConfidenceMinScore', 0.85, ...
    'existenceConfidencePower', 2.0, ...
    'useDecoupledKla', true, ...
    'useStructureAwareKla', true, ...
    'spatialDecouplingStrength', 0.5, ...
    'existenceDecouplingStrength', 0.75, ...
    'spatialStructureStrength', 0.35, ...
    'existenceStructureStrength', 0.85, ...
    'spatialConsistencyScale', 0.8, ...
    'existenceConsistencyScale', 3.0, ...
    'spatialConsistencyMinScore', 0.2, ...
    'existenceConsistencyMinScore', 0.2, ...
    'structureReliabilityPower', 0.0, ...
    'emaAlpha', 0.0, ...
    'spatialEmaAlpha', 0.0, ...
    'existenceEmaAlpha', 0.0, ...
    'minWeight', 0.0, ...
    'spatialMinWeight', 0.0, ...
    'existenceMinWeight', 0.0);
end

function distributions = buildSpatialOutlierDistributions()
distributions = cell(1, 3);
distributions{1} = buildObjectArray([0, 0; 10, 0], [0.95, 0.15]);
distributions{2} = buildObjectArray([0.4, 0.2; 10.3, -0.1], [0.93, 0.12]);
distributions{3} = buildObjectArray([45, 0; 65, 0], [0.94, 0.14]);
end

function distributions = buildExistenceOutlierDistributions()
distributions = cell(1, 3);
distributions{1} = buildObjectArray([0, 0; 10, 0], [0.95, 0.10]);
distributions{2} = buildObjectArray([0.2, -0.1; 10.1, 0.1], [0.92, 0.12]);
distributions{3} = buildObjectArray([0.1, 0; 10.2, -0.2], [0.12, 0.92]);
end

function objects = buildObjectArray(positionArray, existenceArray)
numObjects = size(positionArray, 1);
template = struct( ...
    'r', 0.0, ...
    'numberOfGmComponents', 1, ...
    'w', 1, ...
    'mu', {{}}, ...
    'Sigma', {{}});
objects = repmat(template, 1, numObjects);
for idx = 1:numObjects
    state = [positionArray(idx, 1); positionArray(idx, 2); 0; 0];
    sigma = diag([4, 4, 1, 1]);
    objects(idx).r = existenceArray(idx);
    objects(idx).mu = {state};
    objects(idx).Sigma = {sigma};
end
end
