function test_reviewer_baseline_adaptations()
% TEST_REVIEWER_BASELINE_ADAPTATIONS - Unit tests for the two explicitly
% adapted comparison methods requested by Reviewer 2.

clc;
setPath;

fprintf('Test 1: Zheng-style adaptation keeps spatial/existence subdensity weights separate\n');
model = buildModel('zhengStyleLmb');
model.adaptiveFusion.emaAlpha = 1;
model.adaptiveFusion.minWeight = 0.30;
distributions = {
    buildObject([0; 0; 0; 0], diag([1, 1, 2, 2]), 0.95), ...
    buildObject([0; 0; 0; 0], diag([9, 9, 2, 2]), 0.50), ...
    buildObject([0; 0; 0; 0], diag([4, 4, 2, 2]), 0.80)};
previousWeights = struct('ga', [0, 1, 0], 'aa', [0, 1, 0]);
[~, ~, debug] = computeAdaptiveFusionWeights( ...
    distributions, cell(3, 1), model, 1, struct(), previousWeights);
spatialWeights = debug.gaSpatialTargetWiseWeights(1, :);
existenceWeights = debug.gaExistenceTargetWiseWeights(1, :);
fprintf('  spatial target weights:   %s\n', mat2str(spatialWeights, 4));
fprintf('  existence target weights: %s\n', mat2str(existenceWeights, 4));
assert(spatialWeights(1) > spatialWeights(3));
assert(spatialWeights(3) > spatialWeights(2));
assert(existenceWeights(1) > existenceWeights(3));
assert(existenceWeights(3) > existenceWeights(2));
assert(max(abs(spatialWeights - existenceWeights)) > 1e-3);
expectedSpatialScores = [1 / (trace(diag([1, 1])) + eps), ...
    1 / (trace(diag([9, 9])) + eps), ...
    1 / (trace(diag([4, 4])) + eps)];
expectedSpatialWeights = expectedSpatialScores / sum(expectedSpatialScores);
assert(max(abs(spatialWeights - expectedSpatialWeights)) < 1e-12);
assert(min(spatialWeights) < model.adaptiveFusion.minWeight);
assert(max(abs(spatialWeights - previousWeights.ga)) > 0.5);
assert(strcmp(debug.adaptationOf, 'Zheng2026DistributedWeightedRFS'));
assert(~debug.isExactSourceImplementation);

fprintf('Test 2: Gao-style local-trust adaptation downweights a label-aligned outlier\n');
model = buildModel('gaoStyleResilient');
model.localReceiverSensorIndex = 1;
model.gaTopologyWeights = ones(1, 3) / 3;
distributions = {
    buildObject([0; 0; 0; 0], eye(4), 0.90), ...
    buildObject([0.2; -0.1; 0; 0], eye(4), 0.88), ...
    buildObject([20; 20; 0; 0], eye(4), 0.20)};
[~, ~, debug] = computeAdaptiveFusionWeights( ...
    distributions, cell(3, 1), model, 1, struct(), struct());
targetWeights = debug.gaSpatialTargetWiseWeights(1, :);
fprintf('  local-trust target weights: %s\n', mat2str(targetWeights, 4));
assert(targetWeights(1) > targetWeights(3));
assert(targetWeights(2) > targetWeights(3));
assert(debug.localTrustCredibility(1, 2) > debug.localTrustCredibility(1, 3));
assert(debug.referenceSensorIdx == 1);
assert(~debug.gaoHardReject);
assert(strcmp(debug.adaptationOf, 'Gao2023ResilientLMB'));
assert(~debug.isExactSourceImplementation);

fprintf('Reviewer-baseline adaptation tests passed.\n');
end

function model = buildModel(method)
model = struct();
model.numberOfSensors = 3;
model.xDimension = 4;
model.gaSensorWeights = ones(1, 3) / 3;
model.aaSensorWeights = model.gaSensorWeights;
model.gaTopologyWeights = model.gaSensorWeights;
model.adaptiveFusion = struct( ...
    'enabled', true, ...
    'method', method, ...
    'useCovariance', false, ...
    'useLinkQuality', false, ...
    'emaAlpha', 0, ...
    'minWeight', 0, ...
    'zhengSpatialPrecisionPower', 1, ...
    'zhengExistenceMarginPower', 1, ...
    'zhengExistenceMinScore', 0.05, ...
    'gaoDistanceScale', 2, ...
    'gaoMinCredibility', 0.01, ...
    'gaoSpatialDistancePower', 1, ...
    'gaoExistenceDistancePower', 1, ...
    'gaoHardReject', false);
end

function object = buildObject(meanState, covariance, existenceProbability)
object = struct( ...
    'birthLocation', 1, ...
    'birthTime', 1, ...
    'r', existenceProbability, ...
    'numberOfGmComponents', 1, ...
    'w', 1, ...
    'mu', {{meanState}}, ...
    'Sigma', {{covariance}}, ...
    'trajectoryLength', 0, ...
    'trajectory', [], ...
    'timestamps', []);
end
