function FormationB4V45CausalRoutePreflightTest()
% FORMATIONB4V45CAUSALROUTEPREFLIGHTTEST Short smoke and negative checks.

smoke = FormationB4V45CausalRoutePreflight(struct( ...
    'presets', {{'m24-formation-fov', 'x36-formation-fov'}}, ...
    'seeds', 41, 'timeIndices', 1:4, 'progressEvery', 4));
assert(smoke.caseCount == 2);
assert(smoke.allStructuralChecksPassed);
assert(~smoke.allCasesFullHorizonCovered);
assert(~smoke.full32CasePreflightPassed);
assert(smoke.routeReceivesCurrentPageOnly);
assert(~smoke.posteriorUsed && ~smoke.truthUsed && ...
    ~smoke.measurementUsed && ~smoke.futurePagePassedToRoute && ...
    ~smoke.realizedDeliveryUniformsUsed && ...
    ~smoke.trackingOutcomeScored && ...
    ~smoke.trackingOutcomeAuthorized && ...
    ~smoke.validationClaimAllowed && smoke.developmentEvidenceOnly);
for caseIdx = 1:numel(smoke.cases)
    item = smoke.cases(caseIdx);
    assert(item.structuralChecksPassed);
    assert(item.rollingWindowCount == 1);
    assert(item.alignedCycleCount == 1);
    assert(abs(item.everyAlignedCycleSavingFraction - 3 / 8) < 1e-12);
end
assertLegacySmokeRouteHashesUnchanged(smoke);
testCausalBaseGraphContracts();
expectInvalidNoncontiguousTimes();

expectFailure('uniform-field', ...
    'FormationB4V45Preflight:RouteInputBoundary');
expectFailure('future-page', ...
    'FormationB4V45Preflight:RouteInputBoundary');
expectFailure('negative-weight', ...
    'FormationB4V45Preflight:FusionWeightViolation');
expectFailure('non-subset', ...
    'FormationB4V45Preflight:SubsetViolation');
expectFailure('zero-weight-edge', ...
    'FormationB4V45Preflight:FusionWeightSupportViolation');
expectKnownX36CrossingInfeasibility();
fprintf('PASS: FormationB4V45 causal-route preflight tests\n');
end

function assertLegacySmokeRouteHashesUnchanged(smoke)
% Test-only oracle: legacy full-plan graph is isolated here and is never
% supplied to FormationB4V45CausalRoutePreflight's executable route path.
for caseIdx = 1:numel(smoke.cases)
    current = smoke.cases(caseIdx);
    config = buildDynamicTopologyScenarioConfig(current.presetName);
    rng(current.seed, 'twister');
    [trajectories, metadata] = ...
        generateMultiFormationTrajectories(config);
    legacy = buildDynamicTopologyGraphs(config, trajectories);
    [pDrop, ~] = buildDynamicTopologyLinkSchedule(config, legacy);
    for localIdx = 1:numel(current.auditedTimes)
        time = current.auditedTimes(localIdx);
        context = buildTestContext(config, metadata, legacy, ...
            pDrop, time, legacy.staticAdjacency);
        [syncAdjacency, syncWeights, syncDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule(context, ...
                dutyOptionsForTest('synchronized'));
        [formationAdjacency, formationWeights] = ...
            buildIndexEquivariantResidualDutyCycleSchedule(context, ...
                dutyOptionsForTest('formation-staggered'));
        phase = mod(time - 1, 4) + 1;
        assert(strcmp(testRouteHash(syncDetails.referenceAdjacency, ...
            syncDetails.referenceFusionWeights), ...
            current.referencePageCanonicalSha256ByTime{localIdx}));
        assert(strcmp(testRouteHash(syncAdjacency(:, :, phase), ...
            syncWeights(:, :, phase)), ...
            current.syncB4PageCanonicalSha256ByTime{localIdx}));
        assert(strcmp(testRouteHash(formationAdjacency(:, :, phase), ...
            formationWeights(:, :, phase)), ...
            current.formationB4PageCanonicalSha256ByTime{localIdx}));
    end
end
end

function context = buildTestContext(config, metadata, graph, ...
        pDrop, time, baseAdjacency)
nodeCount = config.numberOfSensors;
context = struct();
context.localPosteriorBySensor = cell(1, nodeCount);
context.model = struct('dynamicTopologyScenario', struct( ...
    'config', struct('sensorGroupIds', config.sensorGroupIds), ...
    'staticAdjacency', logical(baseAdjacency)));
context.baseAdjacency = logical(baseAdjacency);
context.physicalAdjacency = logical( ...
    graph.physicalAdjacency(:, :, time));
context.positions = graph.positions(:, :, time);
context.sensorPhysicalUids = metadata.sensorPhysicalUids;
context.formationPhysicalUidsBySensor = ...
    metadata.formationPhysicalUidsBySensor;
context.commConfig = struct('pDropByEdge', pDrop(:, :, time));
context.currentTime = time;
context.directedMessageBudget = 2 * nodeCount;
end

function options = dutyOptionsForTest(pattern)
options = struct('period', 4, 'dutyLayer', 'all', ...
    'phasePattern', pattern, 'activeResidualWeight', 0.20, ...
    'dominantWeight', 0.70, 'referenceResidualWeight', 0.05);
end

function value = testRouteHash(adjacency, weights)
value = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), 'fusionWeights', weights));
end

function testCausalBaseGraphContracts()
% Legacy static graphs appear only as test oracles for the registered
% formation-pair contract and t=1 route-hash non-drift assertion.
protocol = getFormationIndexEquivariantRouteV43DevelopmentProtocol();
for presetIdx = 1:numel(protocol.registeredPresets)
    presetName = protocol.registeredPresets{presetIdx};
    config = buildDynamicTopologyScenarioConfig(presetName);
    rng(41, 'twister');
    [trajectories, metadata] = ...
        generateMultiFormationTrajectories(config);
    legacy = buildDynamicTopologyGraphs(config, trajectories);
    registry = FormationB4V45BuildCausalRegisteredBaseGraph( ...
        config.formationBackboneMode, config.sensorGroupIds, ...
        metadata.sensorPhysicalUids, ...
        metadata.formationPhysicalUidsBySensor, ...
        legacy.positions(:, :, 1), ...
        legacy.physicalAdjacency(:, :, 1));
    assert(isequal(registry.formationAdjacency, ...
        collapseLegacyByPhysicalUid(legacy.staticAdjacency, ...
            metadata.formationPhysicalUidsBySensor, ...
            registry.formationPhysicalUids)));
    [pDrop, ~] = buildDynamicTopologyLinkSchedule(config, legacy);
    legacyContext = buildTestContext(config, metadata, legacy, ...
        pDrop, 1, legacy.staticAdjacency);
    causalContext = buildTestContext(config, metadata, legacy, ...
        pDrop, 1, registry.baseAdjacency);
    for pattern = {'synchronized', 'formation-staggered'}
        [legacyAdjacency, legacyWeights, legacyDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                legacyContext, dutyOptionsForTest(pattern{1}));
        [causalAdjacency, causalWeights, causalDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                causalContext, dutyOptionsForTest(pattern{1}));
        assert(isequal(legacyAdjacency, causalAdjacency));
        assert(isequal(legacyWeights, causalWeights));
        assert(isequal(legacyDetails.referenceAdjacency, ...
            causalDetails.referenceAdjacency));
        assert(isequal(legacyDetails.referenceFusionWeights, ...
            causalDetails.referenceFusionWeights));
    end
    if strcmp(config.formationBackboneMode, 'formation-ring')
        assert(strcmp(registry.selectionMode, ...
            'registered-group-order-uid-ring'));
        assert(~registry.initialGeometryUsed && ...
            ~registry.initialPhysicalPageUsed);
    else
        assert(strcmp(registry.selectionMode, ...
            't1-physical-minimum-distance-uid-tiebroken-mst'));
        assert(registry.initialGeometryUsed && ...
            registry.initialPhysicalPageUsed);
    end
    assert(~registry.futureGeometryUsed && ...
        ~registry.futurePhysicalPageUsed && ...
        ~registry.linkProbabilityUsed && ~registry.posteriorUsed && ...
        ~registry.truthUsed && ~registry.measurementUsed && ...
        ~registry.realizedDeliveryUniformsUsed && ...
        registry.sensorArrayPermutationEquivarianceDesigned && ...
        ~registry.formationNumericLabelEquivarianceClaimed);

    order = config.numberOfSensors:-1:1;
    permuted = FormationB4V45BuildCausalRegisteredBaseGraph( ...
        config.formationBackboneMode, config.sensorGroupIds(order), ...
        metadata.sensorPhysicalUids(order), ...
        metadata.formationPhysicalUidsBySensor(order), ...
        legacy.positions(:, order, 1), ...
        legacy.physicalAdjacency(order, order, 1));
    restored = false(config.numberOfSensors);
    restored(order, order) = permuted.baseAdjacency;
    assert(isequal(restored, registry.baseAdjacency));
    assert(isequal(permuted.formationPairPhysicalUids, ...
        registry.formationPairPhysicalUids));
    assert(isequal(permuted.formationGroupLabelPairs, ...
        registry.formationGroupLabelPairs));
    assert(strcmp(permuted.canonicalSha256, ...
        registry.canonicalSha256));
    assert(~strcmp(permuted.executionViewCanonicalSha256, ...
        registry.executionViewCanonicalSha256));
    if presetIdx == 1
        expectInvalidUidInputs(config, metadata, legacy);
    end
end
end

function expectInvalidUidInputs(config, metadata, graph)
invalidSensorUids = metadata.sensorPhysicalUids;
invalidSensorUids(1) = 0;
expectBaseGraphInputFailure(config, invalidSensorUids, ...
    metadata.formationPhysicalUidsBySensor, graph);
invalidFormationUids = metadata.formationPhysicalUidsBySensor;
invalidFormationUids(1) = invalidFormationUids(1) + 0.5;
expectBaseGraphInputFailure(config, metadata.sensorPhysicalUids, ...
    invalidFormationUids, graph);
end

function expectBaseGraphInputFailure(config, sensorUids, ...
        formationUids, graph)
failed = false;
try
    FormationB4V45BuildCausalRegisteredBaseGraph( ...
        config.formationBackboneMode, config.sensorGroupIds, ...
        sensorUids, formationUids, graph.positions(:, :, 1), ...
        graph.physicalAdjacency(:, :, 1));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V45BaseGraph:InvalidInput');
end
assert(failed);
end

function collapsed = collapseLegacyByPhysicalUid( ...
        adjacency, uidBySensor, sortedUids)
collapsed = false(numel(sortedUids));
for receiverIdx = 1:numel(sortedUids)
    receivers = uidBySensor == sortedUids(receiverIdx);
    for senderIdx = 1:numel(sortedUids)
        senders = uidBySensor == sortedUids(senderIdx);
        collapsed(receiverIdx, senderIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
collapsed(1:numel(sortedUids)+1:end) = false;
end

function expectInvalidNoncontiguousTimes()
failed = false;
try
    FormationB4V45CausalRoutePreflight(struct( ...
        'presets', {{'m24-formation-fov'}}, 'seeds', 41, ...
        'timeIndices', [1, 2, 4, 5]));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V45Preflight:InvalidOptions') && ...
        ~isempty(strfind(errorInfo.message, 'strictly contiguous'));
end
assert(failed);
end

function expectKnownX36CrossingInfeasibility()
failed = false;
try
    FormationB4V45CausalRoutePreflight(struct( ...
        'presets', {{'x36-formation-fov-crossing'}}, ...
        'seeds', 41, 'timeIndices', 158, 'progressEvery', 1));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V45Preflight:FailedClosed') && ...
        ~isempty(strfind(errorInfo.message, ...
            'preset=x36-formation-fov-crossing')) && ...
        ~isempty(strfind(errorInfo.message, 'seed=41')) && ...
        ~isempty(strfind(errorInfo.message, 'time=158')) && ...
        ~isempty(strfind(errorInfo.message, ...
            'IndexEquivariantFormationRoute:NoCrossAssignment'));
end
assert(failed);
end

function expectFailure(tamperMode, expectedCause)
failed = false;
try
    FormationB4V45CausalRoutePreflight(struct( ...
        'presets', {{'m24-formation-fov'}}, 'seeds', 41, ...
        'timeIndices', 1:4, 'progressEvery', 4, ...
        'testTamperMode', tamperMode));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V45Preflight:FailedClosed') && ...
        ~isempty(strfind(errorInfo.message, expectedCause)) && ...
        ~isempty(strfind(errorInfo.message, ...
            'preset=m24-formation-fov')) && ...
        ~isempty(strfind(errorInfo.message, 'seed=41')) && ...
        ~isempty(strfind(errorInfo.message, 'time=1'));
end
assert(failed);
end
