function FormationB4V46CausalRepairPreflightTest()
% FORMATIONB4V46CAUSALREPAIRPREFLIGHTTEST Structural positive/negative gates.

protocol = getFormationCausalMinimalEditV46Protocol();
noOp = FormationB4V46CausalRepairPreflight(struct( ...
    'presets', {{'m24-formation-fov'}}, 'seeds', 41, ...
    'timeIndices', 1:4, 'progressEvery', 4));
assert(noOp.caseCount == 1 && noOp.allStructuralChecksPassed);
assert(~noOp.allCasesFullHorizonCovered && ...
    ~noOp.full32CasePreflightPassed);
assert(noOp.requiredFull32CaseCount == 32);
assert(isequal(noOp.arms, protocol.primaryArms));
assert(numel(noOp.arms) == 2 && ...
    ~any(cellfun(@(value) ~isempty(strfind(lower(value), ...
        'formation-staggered')), noOp.arms)));
assert(noOp.routeReceivesCurrentPageOnly && ...
    noOp.registeredBaseImmutableAcrossEpisode && ...
    noOp.dynamicMatrixProductAuditPerformed && ...
    noOp.fullV43RouteCompositionPassed);
assert(strcmp(noOp.projectionCertificateScope, ...
    'cross-backbone-connectivity-and-distinct-receiver-matching-only'));
assertBoundaryFlags(noOp);

noOpCase = noOp.cases(1);
assert(noOpCase.structuralChecksPassed);
assert(noOpCase.projectionBackboneCertificatePassed && ...
    noOpCase.fullV43RouteCompositionPassed);
assert(noOpCase.repairPageCount == 0 && isnan(noOpCase.firstRepairTime));
assert(all(noOpCase.projectionRegisteredRemovalCountByTime == 0));
assert(all(noOpCase.projectionNonregisteredAdditionCountByTime == 0));
assert(noOpCase.noOpPagesExactlyPreservedRegisteredBase);
assert(isequal(noOpCase.referenceMessageCountByTime, ...
    48 * ones(1, 4)));
assert(isequal(noOpCase.syncB4MessageCountByTime, [48, 24, 24, 24]));
assert(noOpCase.rollingWindowCount == 1 && ...
    noOpCase.alignedCycleCount == 1);
assert(abs(noOpCase.everyAlignedCycleSavingFraction - 3 / 8) < 1e-12);
assertMatrixProductAudit(noOpCase);
assert(abs(noOpCase.rollingB4MatrixProductDobrushinByWindow(1) - 1) ...
    < 1e-12);
assertProjectionHashes(noOpCase, 4);

crossing = FormationB4V46CausalRepairPreflight(struct( ...
    'presets', {{'x36-formation-fov-crossing'}}, 'seeds', 41, ...
    'timeIndices', 157:160, 'progressEvery', 4));
assert(crossing.allStructuralChecksPassed && ...
    ~crossing.full32CasePreflightPassed);
crossingCase = crossing.cases(1);
assert(crossingCase.structuralChecksPassed);
assert(isequal(crossingCase.auditedTimes, 157:160));
assert(isequal(crossingCase.referenceMessageCountByTime, ...
    72 * ones(1, 4)));
assert(isequal(crossingCase.syncB4MessageCountByTime, [72, 36, 36, 36]));
assert(isequal(crossingCase.projectionRegisteredRemovalCountByTime, ...
    [0, 1, 2, 3]));
assert(isequal(crossingCase.projectionNonregisteredAdditionCountByTime, ...
    [0, 1, 2, 3]));
assert(size(crossingCase.removedRegisteredPairPhysicalUidsByTime{2}, 1) ...
    == 1);
assert(size(crossingCase.addedNonregisteredPairPhysicalUidsByTime{2}, 1) ...
    == 1);
assert(crossingCase.repairPageCount == 3 && ...
    crossingCase.firstRepairTime == 158);
assert(crossingCase.rollingWindowCount == 1 && ...
    crossingCase.alignedCycleCount == 1);
assert(abs(crossingCase.everyAlignedCycleSavingFraction - 3 / 8) < 1e-12);
assert(all(crossingCase.projectionTopologyCandidateCountByTime >= 1));
assert(all(crossingCase.projectionReceiverAssignmentCandidateCountByTime ...
    >= 1));
assert(all(crossingCase.projectionWorkUnitCountByTime >= ...
    crossingCase.projectionTopologyCandidateCountByTime));
assertMatrixProductAudit(crossingCase);
assert(abs(crossingCase.rollingB4MatrixProductDobrushinByWindow(1) - 1) ...
    < 1e-12);
assertProjectionHashes(crossingCase, 4);

expectInvalidNoncontiguousTimes();
expectFailure('uniform-field', ...
    'FormationB4V46Preflight:RouteInputBoundary');
expectFailure('future-page', ...
    'FormationB4V46Preflight:RouteInputBoundary');
expectFailure('projection-certificate', ...
    'FormationB4V46Preflight:ProjectionCertificateHash');
expectFailure('negative-weight', ...
    'FormationB4V46Preflight:FusionWeightViolation');
expectFailure('zero-weight-edge', ...
    'FormationB4V46Preflight:FusionWeightSupportViolation');
expectFailure('non-subset', ...
    'FormationB4V46Preflight:SubsetViolation');
expectFailure('projection-no-feasible', ...
    'CausalFormationProjection:NoFeasibleBackbone');
fprintf('PASS: FormationB4V46 causal-repair preflight tests\n');
end

function assertBoundaryFlags(value)
assert(~value.posteriorUsed && ~value.truthUsed && ...
    ~value.measurementUsed && ...
    ~value.futurePagePassedToProjectionOrRoute && ...
    ~value.realizedDeliveryUniformsUsed && ...
    ~value.trackingOutcomeScored && ...
    ~value.trackingOutcomeAuthorized && ...
    ~value.validationClaimAllowed && value.developmentEvidenceOnly);
end

function assertMatrixProductAudit(item)
assert(strcmp(item.rollingB4MatrixProductMultiplicationOrder, ...
    'P(t:t-3)=W(t)*W(t-1)*W(t-2)*W(t-3)'));
assert(strcmp(item.rollingB4MatrixProductCentering, [ ...
    'spectral=H*P*H;row-dispersion=P-mean(P,1);', ...
    'H=I-ones(N)/N']));
assert(item.dynamicMatrixProductAuditPerformed);
assert(numel(item.rollingB4MatrixProductCanonicalSha256ByWindow) == ...
    item.rollingWindowCount);
assert(numel(item.rollingB4MatrixProductDobrushinByWindow) == ...
    item.rollingWindowCount);
assert(all(item.rollingB4MatrixProductDobrushinByWindow >= -1e-12 & ...
    item.rollingB4MatrixProductDobrushinByWindow <= 1 + 1e-12));
assert(all(isfinite( ...
    item.rollingB4MatrixProductCenteredSpectralNormByWindow)));
assert(all(item.rollingB4MatrixProductCenteredSpectralNormByWindow >= 0));
assert(all(isfinite( ...
    item.rollingB4MatrixProductMaximumCenteredRowL2ByWindow)));
assert(all(item.rollingB4MatrixProductMaximumCenteredRowL2ByWindow >= 0));
assert(isfinite(item.worstRollingB4MatrixProductDobrushin));
assert(isfinite(item.medianRollingB4MatrixProductDobrushin));
assert(isfinite(item.worstRollingB4MatrixProductCenteredSpectralNorm));
assert(isfinite(item.medianRollingB4MatrixProductCenteredSpectralNorm));
assert(isfinite(item.worstRollingB4MatrixProductMaximumCenteredRowL2));
assert(isfinite(item.medianRollingB4MatrixProductMaximumCenteredRowL2));
for idx = 1:item.rollingWindowCount
    assertSha256(item.rollingB4MatrixProductCanonicalSha256ByWindow{idx});
end
end

function assertProjectionHashes(item, expectedCount)
hashFields = {'currentPageInputCanonicalSha256ByTime', ...
    'projectedBaseCanonicalSha256ByTime', ...
    'projectionEditCanonicalSha256ByTime', ...
    'selectedProjectionCandidateCanonicalSha256ByTime', ...
    'projectionCertificateCanonicalSha256ByTime', ...
    'referencePageCanonicalSha256ByTime', ...
    'syncB4PageCanonicalSha256ByTime'};
for fieldIdx = 1:numel(hashFields)
    values = item.(hashFields{fieldIdx});
    assert(numel(values) == expectedCount);
    for valueIdx = 1:numel(values)
        assertSha256(values{valueIdx});
    end
end
end

function assertSha256(value)
assert(ischar(value) && numel(value) == 64 && ...
    all(ismember(lower(value), '0123456789abcdef')));
end

function expectInvalidNoncontiguousTimes()
failed = false;
try
    FormationB4V46CausalRepairPreflight(struct( ...
        'presets', {{'m24-formation-fov'}}, 'seeds', 41, ...
        'timeIndices', [1, 2, 4, 5]));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V46Preflight:InvalidOptions') && ...
        ~isempty(strfind(errorInfo.message, 'strictly contiguous'));
end
assert(failed);
end

function expectFailure(tamperMode, expectedCause)
failed = false;
try
    FormationB4V46CausalRepairPreflight(struct( ...
        'presets', {{'m24-formation-fov'}}, 'seeds', 41, ...
        'timeIndices', 1, 'progressEvery', 1, ...
        'testTamperMode', tamperMode));
catch errorInfo
    failed = strcmp(errorInfo.identifier, ...
        'FormationB4V46Preflight:FailedClosed') && ...
        ~isempty(strfind(errorInfo.message, expectedCause)) && ...
        ~isempty(strfind(errorInfo.message, ...
            'preset=m24-formation-fov')) && ...
        ~isempty(strfind(errorInfo.message, 'seed=41')) && ...
        ~isempty(strfind(errorInfo.message, 'time=1'));
end
assert(failed);
end
