function test_adaptive_label_boundary_entry_v115()
% TESTADAPTIVELABELBOUNDARYENTRYV115 Protocol and authorization.

protocol = getAdaptiveLabelBoundaryEntryV115Protocol();
assert(protocol.boundaryFormationId == 6);
assert(protocol.boundarySourceSensorId == 27);
assert(protocol.boundaryReceiverSensorId == 32);
assert(protocol.labelEntryStartPage == 5);
assert(numel(protocol.candidateActionNames) == 3);
assert(numel(protocol.candidatePayloadModes) == 3);
for pageIdx = 1:protocol.horizonSteps
    assert(ismember(6, ...
        protocol.labelEntryFormationIdsByTime{pageIdx}) == ...
        (pageIdx >= protocol.labelEntryStartPage));
    assert(all(ismember( ...
        protocol.baseProtectionFormationIdsByTime{pageIdx}, ...
        protocol.labelEntryFormationIdsByTime{pageIdx})));
end

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildAdaptiveLabelBoundaryEntryV115ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.candidateActionNames{1}, true);
assert(isAdaptiveLabelBoundaryEntryV115ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.labelEntryFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            protocol.candidatePayloadModes{1}, ...
        'receiverSafeBoundaryLabelFormationId', ...
            protocol.boundaryFormationId));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig.receiverSafeBoundaryLabelFormationId = 5;
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
assert(nargin('runAdaptiveLabelBoundaryEntryV115X36T72') == 1);
fprintf('test_adaptive_label_boundary_entry_v115 passed\n');
end
