function test_lineage_isolated_relay_v135()
% TEST_LINEAGE_ISOLATED_RELAY_V135 Payload and permit boundaries.

protocol = getLineageIsolatedRelayV135Protocol();
assert(strcmp(protocol.runtimePayloadMode, ...
    'lineage-relay-full-working-abstention'));
assert(~protocol.wireContract.auxiliaryPayloadAllowed);
assert(~protocol.wireContract.workingStateTransmitted);
assert(protocol.wireContract.messageCountRelativeToReference == 1);

object = makeObject();
posteriors = {object, object, object};
crossResidual = false(3);
crossResidual(3, 1) = true;
crossResidual(1, 3) = true;
model = struct( ...
    'xDimension', 4, ...
    'existenceThreshold', 0.01, ...
    'dynamicTopologyScenario', struct( ...
        'config', struct('sensorGroupIds', [1, 1, 2])));
config = struct( ...
    'receiverSafeFormationConditionedTimes', 1, ...
    'receiverSafeFormationConditionedSchedule', {{[1, 2]}}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', {{[0, 1]}}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.runtimePayloadMode, ...
    'receiverSafeExternalPositiveSupportThreshold', 0.2, ...
    'receiverSafeFormationConditionedHighExistenceThreshold', 0.5, ...
    'payloadExistenceThreshold', 0.01);
plan = buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct(), struct()}, ...
    model, config, 1);
assert(plan.abstainFromFusionEdgeMask(3, 1));
assert(plan.fusionTrustFactorByReceiverSender(3, 1) == 0);
assert(plan.eventTypeByReceiverSender(3, 1) == 2);
assert(numel(plan.payloadByReceiverSender{1, 3}) == 1);
assert(plan.payloadByReceiverSender{1, 3}.numberOfGmComponents == 2);
assert(plan.totalControlSynopsisBytes == 0);
assert(plan.totalSelectedPayloadBytes == plan.totalBaselineFullBytes);

caseInfo = protocol.scaleCases(strcmp( ...
    {protocol.scaleCases.scaleName}, 'M24'));
bank = buildSetTrustSequenceCandidatesV134( ...
    [4, 2, 1, 3], caseInfo.formationCycleDiameter, ...
    caseInfo.recoveryTailSteps);
actionSpec = bank.actions(protocol.screen.m24ActionIndex);
context = buildLineageIsolatedRelayV135ExecutionContext( ...
    caseInfo.presetName, protocol.pilotSeed, 'candidate', 95, ...
    'fixed-counter-clockwise', actionSpec);
runtimeModel = struct( ...
    'numberOfSensors', caseInfo.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', caseInfo.presetName, ...
        'seed', protocol.pilotSeed, ...
        'config', struct( ...
            'formationCount', caseInfo.expectedFormationCount)));
returnTimes = context.currentTime + (0:(context.horizonSteps - 1));
requestConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyPolicyName', protocol.outcomePolicyName, ...
    'v135ReferenceCarrierMode', 'fixed-counter-clockwise', ...
    'topologyPolicyHistoryDepth', 2, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicySensorObservationEnabled', true, ...
    'receiverSafeLabelFusionEnabled', true, ...
    'receiverSafeLabelFusionMode', ...
        'formation-supported-label-plan', ...
    'receiverSafeExternalActiveTimes', returnTimes, ...
    'receiverSafeFormationConditionedTimes', returnTimes, ...
    'receiverSafeFormationConditionedSchedule', ...
        {actionSpec.formationIdsByTime}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {actionSpec.trustFactorsByTime}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.runtimePayloadMode, ...
    'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
    'lineageIsolatedRelayEnabled', true, ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'useStaleNeighborCache', false));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones( ...
            1, caseInfo.expectedNodeCount), ...
    'triggerConfig', requestConfig);
authorization = validateLineageIsolatedRelayV135Execution( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.validationClaimAllowed);

request.triggerConfig.lineageIsolatedRelayEnabled = false;
assertErrorId(@() validateLineageIsolatedRelayV135Execution( ...
    runtimeModel, context, request), ...
    'LineageRelayV135:InvalidRuntimeRequest');
fprintf('PASS: V135 lineage-isolated relay contract\n');
end

function object = makeObject()
object = struct( ...
    'birthTime', 1, ...
    'birthLocation', 1, ...
    'r', 0.9, ...
    'numberOfGmComponents', 2, ...
    'w', [0.4, 0.6], ...
    'mu', {{zeros(4, 1), ones(4, 1)}}, ...
    'Sigma', {{eye(4), 2 * eye(4)}}, ...
    'detectionAssociationMass', 0.8);
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end
