function test_reference_anchored_burst_role_schedule_v144()
% TEST_REFERENCE_ANCHORED_BURST_ROLE_SCHEDULE_V144 Frozen cadence boundary.

protocol = getReferenceAnchoredBurstRoleScheduleV144Protocol();
assert(protocol.roleSchedule.periodPages == 4);
assert(protocol.roleSchedule.referencePhaseOffset == 0);
assert(protocol.roleSchedule.maximumReferenceAgePages == 3);
assert(abs(protocol.roleSchedule.workingPageFraction - 0.75) < 1e-12);
assert(protocol.roleSchedule.onePayloadPerAttemptedEdge);
assert(~protocol.roleSchedule.auxiliaryPayloadAllowed);
assert(protocol.screen.requireZeroAuxiliaryPayload);
assert(protocol.screen.requireNoAttemptedByteIncrease);
assert(protocol.finiteTimeMixingPreflight.nextLongerBurstRejected);
assert(protocol.finiteTimeMixingPreflight. ...
    m24TerminalMaximumRowTotalVariation <= ...
        protocol.finiteTimeMixingPreflight. ...
            maximumTerminalRowTotalVariation);
assert(protocol.finiteTimeMixingPreflight. ...
    x36TerminalMaximumRowTotalVariation <= ...
        protocol.finiteTimeMixingPreflight. ...
            maximumTerminalRowTotalVariation);

selectorConfig = struct( ...
    'lineageRelayRoleMultiplexedSinglePayloadEnabled', true, ...
    'lineageRelayRoleMultiplexedAnchorTime', 10, ...
    'lineageRelayRoleMultiplexedPeriodPages', 4, ...
    'lineageRelayRoleMultiplexedReferencePhaseOffset', 0);
groups = [1, 1, 2, 2];
expectedLocalRoles = {'reference', 'working', 'working', 'working', ...
    'reference'};
for pageIdx = 1:numel(expectedLocalRoles)
    [role, details] = selectRoleMultiplexedSinglePayloadV143( ...
        selectorConfig, groups, 1, 2, 9 + pageIdx, true);
    assert(strcmp(role, expectedLocalRoles{pageIdx}));
    assert(details.referencePhase == strcmp(role, 'reference'));
end
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 1, 3, 12, true);
assert(strcmp(role, 'reference'));
assert(~details.intraFormation);
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 3, 4, 12, false);
assert(strcmp(role, 'reference'));
assert(~details.receiverProtected);

caseInfo = protocol.scaleCases(strcmp( ...
    {protocol.scaleCases.scaleName}, 'M24'));
bank = buildSetTrustSequenceCandidatesV134( ...
    [4, 2, 1, 3], caseInfo.formationCycleDiameter, ...
    caseInfo.recoveryTailSteps);
actionSpec = bank.actions(protocol.screen.m24ActionIndex);
context = buildReferenceAnchoredBurstRoleScheduleV144ExecutionContext( ...
    caseInfo.presetName, protocol.pilotSeed, 'candidate', 95, ...
    'fixed-counter-clockwise', actionSpec);
assert(isReferenceAnchoredBurstRoleScheduleV144ExecutionContext(context));
assert(context.roleMultiplexingEnabled);
assert(context.rolePeriodPages == 4);
assert(context.singlePayloadWireEnforced);
assert(~context.exactStaticStateFallbackClaimAllowed);

runtimeModel = struct( ...
    'numberOfSensors', caseInfo.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', caseInfo.presetName, ...
        'seed', protocol.pilotSeed, ...
        'config', struct( ...
            'formationCount', caseInfo.expectedFormationCount)));
returnTimes = context.currentTime + (0:(context.horizonSteps - 1));
requestConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyPolicyName', protocol.outcomePolicyName, ...
    'v135ReferenceCarrierMode', 'fixed-counter-clockwise', ...
    'topologyPolicyHistoryDepth', 2, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicySensorObservationEnabled', true, ...
    'receiverSafeLabelFusionEnabled', true, ...
    'receiverSafeLabelFusionMode', ...
        'formation-supported-label-plan', ...
    'receiverSafeExternalActiveTimes', returnTimes, ...
    'receiverSafeFormationConditionedTimes', returnTimes, ...
    'receiverSafeFormationConditionedSchedule', ...
        {actionSpec.formationIdsByTime}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {actionSpec.trustFactorsByTime}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.runtimePayloadMode, ...
    'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
    'receiverSafeEvidenceOptions', ...
        protocol.labelReadout.evidenceOptions, ...
    'lineageIsolatedRelayEnabled', true, ...
    'lineageRelayIntraFormationWorkingPayloadEnabled', true, ...
    'lineageRelayPredictiveEvidenceFallbackEnabled', false, ...
    'lineageRelayPredictiveEvidenceReadoutOnlyEnabled', true, ...
    'lineageRelayPredictiveEvidenceMinimumLogScoreMargin', ...
        protocol.predictiveEvidence.minimumMargin, ...
    'lineageRelayPostFusionLabelReadoutEnabled', true, ...
    'lineageRelayRoleMultiplexedSinglePayloadEnabled', true, ...
    'lineageRelayRoleMultiplexedAnchorTime', context.currentTime, ...
    'lineageRelayRoleMultiplexedPeriodPages', ...
        protocol.roleSchedule.periodPages, ...
    'lineageRelayRoleMultiplexedReferencePhaseOffset', ...
        protocol.roleSchedule.referencePhaseOffset, ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'useStaleNeighborCache', false));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones( ...
            1, caseInfo.expectedNodeCount), ...
    'triggerConfig', requestConfig);
authorization = ...
    validateReferenceAnchoredBurstRoleScheduleV144Execution( ...
        runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.validationClaimAllowed);

request.triggerConfig.lineageRelayRoleMultiplexedPeriodPages = 2;
assertErrorId(@() ...
    validateReferenceAnchoredBurstRoleScheduleV144Execution( ...
        runtimeModel, context, request), ...
    'ReferenceAnchoredBurstV144:InvalidRuntimeRequest');
fprintf('PASS: V144 reference-anchored burst role schedule contract\n');
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end

