function test_formation_index_equivariant_route_v43_gate()
protocol = getFormationIndexEquivariantRouteV43DevelopmentProtocol();
cases = buildPassingCases(protocol);
execution = struct('registeredBatchComplete', true, ...
    'cleanSourceEvidence', buildCleanEvidence(true), ...
    'postHocExecutableFreezeEvidence', buildPostHocEvidence(false));

gate = evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
    cases, execution, protocol);
assert(gate.routeReferenceAdvanceCriteriaPassed);
assert(~gate.routeReferenceAdvancePassed);
assert(gate.m24NonCrossingCaseCount == 12);
assert(gate.x36NonCrossingCaseCount == 12);

auditedExecution = execution;
auditedExecution.postHocExecutableFreezeEvidence = ...
    buildPostHocEvidence(true);
audited = evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
    cases, auditedExecution, protocol);
assert(audited.routeReferenceAdvancePassed);

dirtyExecution = execution;
dirtyExecution.cleanSourceEvidence = buildCleanEvidence(false);
assertNotCriteria(cases, dirtyExecution, protocol);

missingCases = cases(1:end-1);
missingExecution = execution;
missingExecution.registeredBatchComplete = false;
assertNotCriteria(missingCases, missingExecution, protocol);

changed = cases;
changed(1).fusionWeightsMatched = false;
assertNotCriteria(changed, execution, protocol);
changed = cases;
changed(1).registeredInputIdentityMatched = false;
assertNotCriteria(changed, execution, protocol);
changed = cases;
changed(1).futureOutcomeUsed = true;
assertNotCriteria(changed, execution, protocol);

fake = cases;
fake(1).inputCanonicalSha256 = repmat('0', 1, 64);
assertErrorId(@() ...
    evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
        fake, execution, protocol), ...
    'FormationIndexEquivariantV43Gate:BatchIdentityMismatch');
duplicate = cases;
duplicate(2).caseId = duplicate(1).caseId;
assertErrorId(@() ...
    evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
        duplicate, execution, protocol), ...
    'FormationIndexEquivariantV43Gate:DuplicateCase');
reordered = cases([2, 1, 3:end]);
assertErrorId(@() ...
    evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
        reordered, execution, protocol), ...
    'FormationIndexEquivariantV43Gate:BatchIdentityMismatch');
truthy = execution;
truthy.registeredBatchComplete = 2;
assertErrorId(@() ...
    evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
        cases, truthy, protocol), ...
    'FormationIndexEquivariantV43Gate:InvalidBoolean');
truthy = execution;
truthy.cleanSourceEvidence.requireCleanGit = 2;
assertErrorId(@() ...
    evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
        cases, truthy, protocol), ...
    'FormationIndexEquivariantV43Gate:InvalidBoolean');

% Crossing remains in the per-case non-degradation gates, but does not
% influence either scale-family median.
crossing = cellfun(@(name) ~isempty(strfind(name, 'crossing')), ...
    {cases.presetName}); %#ok<STREMP>
changed = cases;
for idx = find(crossing)
    changed(idx).legacyTargetHorizon = 100;
    changed(idx).v43TargetHorizon = 90;
    changed(idx).targetHorizonRatio = 0.90;
end
crossingGate = evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
    changed, execution, protocol);
assert(crossingGate.scaleMedianTargetHorizonRatioGatePassed);
assert(crossingGate.routeReferenceAdvanceCriteriaPassed);

changed = cases;
m24NonCrossing = cellfun(@(name) strncmp(name, 'm24-', 4) && ...
    isempty(strfind(name, 'crossing')), {cases.presetName}); %#ok<STREMP>
for idx = find(m24NonCrossing)
    changed(idx).targetHorizonRatio = 0.60;
end
assertNotCriteria(changed, execution, protocol);
fprintf('PASS: v43 aggregate gate tests\n');
end

function cases = buildPassingCases(protocol)
template = struct('caseId', '', 'presetName', '', 'sceneRole', '', ...
    'seed', NaN, 'currentTime', NaN, 'nodeCount', NaN, ...
    'formationCount', NaN, 'inputCanonicalSha256', '', ...
    'physicalUidRegistryCanonicalSha256', '', ...
    'legacyTargetHorizon', 10, ...
    'v43TargetHorizon', 4, 'targetHorizonRatio', 0.40, ...
    'fixedHorizonFactorDelta', -0.10, ...
    'sameDirectedMessageBudget', true, ...
    'sameCrossFormationMessageBudget', true, ...
    'fusionWeightsMatched', true, 'protocolWeightsMatched', true, ...
    'registeredInputIdentityMatched', true, ...
    'sparseFallbackContractPassed', true, ...
    'executionBoundaryVerified', true, 'posteriorUsed', false, ...
    'truthUsed', false, 'measurementUsed', false, ...
    'futureOutcomeUsed', false, ...
    'realizedDeliveryUniformsUsed', false, ...
    'trackingOutcomeScored', false, ...
    'trackingOutcomeAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true);
cases = repmat(template, 1, numel(protocol.registeredCases));
for caseIdx = 1:numel(cases)
    registered = protocol.registeredCases(caseIdx);
    cases(caseIdx).caseId = registered.caseId;
    cases(caseIdx).presetName = registered.presetName;
    cases(caseIdx).sceneRole = registered.sceneRole;
    cases(caseIdx).seed = registered.seed;
    cases(caseIdx).currentTime = registered.currentTime;
    cases(caseIdx).nodeCount = registered.nodeCount;
    cases(caseIdx).formationCount = registered.formationCount;
    cases(caseIdx).inputCanonicalSha256 = ...
        registered.inputCanonicalSha256;
    cases(caseIdx).physicalUidRegistryCanonicalSha256 = ...
        registered.physicalUidRegistryCanonicalSha256;
end
end

function evidence = buildCleanEvidence(passed)
evidence = struct( ...
    'contractVersion', ...
        'formation-index-equivariant-route-v43-clean-source-evidence-v1', ...
    'requireCleanGit', logical(passed), ...
    'initialGitDirty', false, 'endingGitDirty', false, ...
    'generationCommitStable', logical(passed), ...
    'executableManifestStable', logical(passed), ...
    'pathResolutionPassed', logical(passed), ...
    'allEntriesTrackedByHead', logical(passed), ...
    'allWorkingFilesMatchHead', logical(passed));
end

function evidence = buildPostHocEvidence(passed)
passed = logical(passed);
evidence = struct( ...
    'contractVersion', ...
        ['formation-index-equivariant-route-v43-', ...
         'posthoc-freeze-evidence-v1'], ...
    'generationCommitPinned', passed, ...
    'protocolShaMatched', passed, ...
    'resultCanonicalShaRecomputed', passed, ...
    'executableManifestShaPinned', passed, ...
    'artifactFilesShaPinned', passed, ...
    'independentAuditCommitted', passed, ...
    'auditSourceClean', passed);
end

function assertNotCriteria(cases, execution, protocol)
gate = evaluateFormationIndexEquivariantRouteV43DevelopmentGate( ...
    cases, execution, protocol);
assert(~gate.routeReferenceAdvanceCriteriaPassed);
assert(~gate.routeReferenceAdvancePassed);
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end
