function test_positive_value_reference_label_v157()
% TEST_POSITIVE_VALUE_REFERENCE_LABEL_V157 Greedy positive-value selector.

model = makeModel();
wrong = makeObject([50; 0; 0; 0]);
correct = makeObject([0; 0; 0; 0]);
[selected, details] = selectPositiveValueReferenceLmbLabels( ...
    wrong, correct, 4, 1e-2, model, 1);
assert(details.selectedLabelCount == 1);
assert(details.finalEospa < details.initialEospa);
assert(isequal(selected.mu{1}, correct.mu{1}));
[selected, details] = selectPositiveValueReferenceLmbLabels( ...
    correct, wrong, 4, 1e-2, model, 1);
assert(details.selectedLabelCount == 0);
assert(isequal(selected.mu{1}, correct.mu{1}));

config = struct( ...
    'shadowStateRollbackEnabled', true, ...
    'shadowStateRollbackTimes', 1, ...
    'shadowStateRollbackSensorIdsByTime', {{1}}, ...
    'shadowStateRollbackFusedPosteriorByTime', {{{correct}}}, ...
    'shadowStateRollbackSourceMode', ...
        'external-positive-value-reference-labels', ...
    'shadowStateRollbackMaximumLabelEdits', 4, ...
    'shadowStateRollbackExistenceThreshold', 1e-2);
[selected, applied, pageIdx, details] = ...
    selectShadowStateRollbackPosterior( ...
        wrong, config, 1, 1, [], [], model);
assert(applied && pageIdx == 1 && details.selectedLabelCount == 1);
assert(isequal(selected.mu{1}, correct.mu{1}));

protocol = getPositiveValueReferenceLabelV157Protocol();
context = buildPositiveValueReferenceLabelV157ExecutionContext( ...
    'x36-formation-fov', 211, 72, ...
    protocol.candidateActionName, true);
assert(isPositiveValueReferenceLabelV157ExecutionContext(context));
fprintf('test_positive_value_reference_label_v157 passed\n');
end

function model = makeModel()
model = struct( ...
    'existenceThreshold', 1e-2, ...
    'ospaParameters', struct( ...
        'eC', 100, 'eP', 2, 'hC', 0.5, 'hP', 2));
model.dynamicTopologyScenario = struct();
model.dynamicTopologyScenario.targetTrajectories = {[0; 0; 0; 0]};
end

function object = makeObject(meanVector)
object = struct( ...
    'birthLocation', 1, ...
    'birthTime', 1, ...
    'r', 0.99, ...
    'numberOfGmComponents', 1, ...
    'w', 1, ...
    'mu', {{meanVector}}, ...
    'Sigma', {{eye(numel(meanVector))}});
end
