function test_formation_mode_intervention_bank()
% TEST_FORMATION_MODE_INTERVENTION_BANK Local action composition tests.

groupIds = [1, 1, 2, 2];
reference = logical([ ...
    0, 1, 1, 0; ...
    1, 0, 0, 1; ...
    1, 0, 0, 1; ...
    0, 1, 1, 0]);
mode2 = logical([ ...
    0, 1, 0, 1; ...
    0, 0, 1, 1; ...
    0, 1, 0, 1; ...
    1, 0, 1, 0]);
mode3 = logical([ ...
    0, 0, 1, 1; ...
    1, 0, 1, 0; ...
    1, 1, 0, 0; ...
    0, 1, 1, 0]);
adjacencyByMode = {reference, mode2, mode3};
weightsByMode = cellfun(@(item) 0.25 * double(item), ...
    adjacencyByMode, 'UniformOutput', false);
sourcesByMode = { ...
    [2, 1, 4, 3], ...
    [2, 3, 4, 1], ...
    [3, 1, 1, 3]};
projection = struct( ...
    'formationModeCount', 3, ...
    'modeDominantSourcesByIndex', {sourcesByMode}, ...
    'modeAdjacencyByIndex', {adjacencyByMode}, ...
    'modeFusionWeightsByIndex', {weightsByMode}, ...
    'dynamicModeAllowedMask', logical([1, 1, 0; 1, 0, 1]), ...
    'payloadByFormationMode', [100, 90, 80; 120, 130, 100], ...
    'objectiveByFormationMode', [0, 2, -1; 0, -3, 4], ...
    'projector', struct('modeTrustWeights', [0.7, 0.3, 0.5]));

bank = buildFormationModeInterventionBank( ...
    projection, groupIds);
assert(strcmp(bank.contractVersion, ...
    'formation-local-source-trust-intervention-bank-v1'));
assert(bank.actionCount == 5);
assert(isequal(bank.actionModes, [ ...
    1, 1; 2, 1; 3, 1; 1, 2; 1, 3]));
assert(isequal(bank.actionFormationIndex', [0, 1, 1, 2, 2]));
assert(isequal(bank.actionModeIndex', [1, 2, 3, 2, 3]));
assert(isequal(bank.actionAdjacency(1:2, :, 2), mode2(1:2, :)));
assert(isequal(bank.actionAdjacency(3:4, :, 2), reference(3:4, :)));
assert(isequal(bank.actionAdjacency(1:2, :, 4), reference(1:2, :)));
assert(isequal(bank.actionAdjacency(3:4, :, 4), mode2(3:4, :)));
assert(isequal(bank.actionDominantSources(2, :), [2, 3, 4, 3]));
assert(isequal(bank.actionDominantSources(4, :), [2, 1, 4, 1]));
assert(isequal(bank.actionPosteriorProxyAllowed', ...
    logical([1, 1, 0, 0, 1])));
assert(isequal(bank.actionPosteriorObjective', [0, 2, -1, -3, 4]));
assert(isequal(bank.actionPayloadBytes', [220, 210, 200, 230, 200]));
assert(isequal(bank.actionWithinReferencePayload', ...
    logical([1, 1, 1, 0, 1])));
assert(~bank.truthUsed && ~bank.futureOutcomeUsed);

invalid = projection;
invalid.modeFusionWeightsByIndex{2}(1, 3) = 0.1;
failed = false;
try
    buildFormationModeInterventionBank(invalid, groupIds);
catch
    failed = true;
end
assert(failed);
fprintf('test_formation_mode_intervention_bank passed\n');
end
