function test_influence_cone_carrier_v113()
% TEST_INFLUENCECONECARRIERV113 Protocol and authorization contract.

protocol = getInfluenceConeCarrierV113Protocol();
assert(strcmp(protocol.primaryReferenceOrientation, ...
    'counter-clockwise'));
assert(strcmp(protocol.alternativeReferenceOrientation, 'clockwise'));
assert(isequal(protocol.safeFormationIds, [2, 3, 4, 5]));
assert(all(cellfun(@(ids) ~any(ismember(ids, [1, 6])), ...
    protocol.protectionFormationIdsByTime)));

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));

fullContext = buildInfluenceConeCarrierV113ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.clockwiseFullActionName, false);
assert(isInfluenceConeCarrierV113ExecutionContext(fullContext));
fullRequest = buildRequest( ...
    protocol, entry, fullContext, false, ...
    repmat({zeros(1, 0)}, 1, protocol.horizonSteps), ...
    'reference-full-payload');
fullAuthorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, fullContext, fullRequest);
assert(fullAuthorization.trackingOutcomeScoringAuthorized);

actionContext = buildInfluenceConeCarrierV113ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.clockwiseAbstentionActionName, true);
actionRequest = buildRequest( ...
    protocol, entry, actionContext, true, ...
    protocol.protectionFormationIdsByTime, 'abstention-only');
actionAuthorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, actionContext, actionRequest);
assert(actionAuthorization.trackingOutcomeScoringAuthorized);
assert(strcmp(actionAuthorization.protocolId, protocol.id));

actionRequest.triggerConfig. ...
    receiverSafeFormationConditionedPayloadMode = 'control-only';
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, actionContext, actionRequest);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
assert(nargin('runInfluenceConeCarrierV113X36T72') == 1);
end

function request = buildRequest( ...
        protocol, entry, context, enabled, schedule, payloadMode)
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', logical(enabled), ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', {schedule}, ...
        'receiverSafeFormationConditionedPayloadMode', payloadMode));
end
