function test_time_expanded_carrier_switch_v120()
% TEST_TIMEEXPANDEDCARRIERSWITCHV120 Protocol and authorization.

protocol = getTimeExpandedCarrierSwitchV120Protocol();
assert(protocol.switchAfterPageIndex == 4 && protocol.switchTime == 76);
assert(strcmp(protocol.bankVariant, ...
    'time-expanded-carrier-switch-v120'));
v119 = getTimeExpandedDualPathV119Protocol();
assert(isequal(protocol.protectionFormationIdsByTime, ...
    v119.protectionFormationIdsByTime));

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildTimeExpandedCarrierSwitchV120ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.cwToCcwSequenceName, true);
assert(isTimeExpandedCarrierSwitchV120ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.protectionFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));
assert(nargin('runTimeExpandedCarrierSwitchV120X36T72') == 1);
fprintf('test_time_expanded_carrier_switch_v120 passed\n');
end
