function test_formation_b4_v45_filter_runtime_semantics()
% End-to-end V45 directed runtime and observable-UID contract regression.

global formationB4V45FilterRuntimeTestState;
cleanup = onCleanup(@clearTestState); %#ok<NASGU>
[model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig, identity] = buildSyntheticCase();
nodeCount = model.numberOfSensors;
timeCount = size(measurements, 2);

formationB4V45FilterRuntimeTestState = struct( ...
    'capturedContext', {cell(1, timeCount)}, ...
    'capturedAdjacency', {cell(1, timeCount)}, ...
    'capturedDetails', {cell(1, timeCount)});
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig);

expectedMessageCounts = [2 * nodeCount, nodeCount, ...
    nodeCount, nodeCount];
assert(isequal(reshape(diagnostics.topologyDirectedMessageCount, 1, []), ...
    expectedMessageCounts));
for currentTime = 1:timeCount
    context = formationB4V45FilterRuntimeTestState. ...
        capturedContext{currentTime};
    adjacency = formationB4V45FilterRuntimeTestState. ...
        capturedAdjacency{currentTime};
    details = formationB4V45FilterRuntimeTestState. ...
        capturedDetails{currentTime};
    contract = context.observableInputContract;

    assert(isfield(context.triggerConfig, 'topologyDirectedEnabled'));
    assert(islogical(context.triggerConfig.topologyDirectedEnabled) && ...
        isscalar(context.triggerConfig.topologyDirectedEnabled) && ...
        context.triggerConfig.topologyDirectedEnabled);
    assert(strcmp(contract.contractVersion, ...
        'topology-policy-observable-input-v3-physical-uid'));
    assert(contract.enforced && contract.passed && ...
        contract.physicalIdentityPresent && ...
        contract.physicalIdentitySchemaRestricted && ...
        contract.targetTruthAbsent && contract.linkUniformsAbsent && ...
        contract.futurePDropPagesAbsent);
    assert(isequal(context.sensorPhysicalUids, ...
        identity.sensorPhysicalUids));
    assert(isequal(context.formationPhysicalUidsBySensor, ...
        identity.formationPhysicalUidsBySensor));
    assert(strcmp(context.physicalIdentityRegistryCanonicalSha256, ...
        identity.canonicalSha256));
    assert(strcmp(contract.physicalIdentityRegistryCanonicalSha256, ...
        identity.canonicalSha256));
    assert(isequal(diagnostics. ...
        topologyPolicyObservableInputContract{currentTime}, contract));

    % The filter diagnostics use sender rows / receiver columns, whereas
    % the policy and its weights use receiver rows / sender columns.
    assert(isequal(logical(diagnostics. ...
        topologyActiveEdge(:, :, currentTime)), adjacency'));
    actualWeights = diagnostics. ...
        topologyPolicyFusionWeightMatrix{currentTime};
    assert(max(abs(actualWeights(:) - ...
        details.fusionWeightMatrix(:))) <= 1e-12);
    assert(nnz(adjacency) == expectedMessageCounts(currentTime));
    assert(details.currentMessageCount == ...
        expectedMessageCounts(currentTime));
    assert(nnz(diagnostics.attempted(:, :, currentTime)) == ...
        expectedMessageCounts(currentTime));
end

% A false directed flag must be rejected by the V45 wrapper before the
% filter can silently symmetrize its directed route.
undirectedConfig = triggerConfig;
undirectedConfig.topologyDirectedEnabled = false;
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, undirectedConfig), ...
    'FormationB4V45:InvalidDirectedRuntime');

fprintf('PASS: FormationB4V45 filter runtime semantics tests\n');
end

function [adjacency, details] = captureSynchronizedPolicy(context)
global formationB4V45FilterRuntimeTestState;
[adjacency, details] = ...
    selectFormationB4V45SynchronizedRuntimePolicy(context);
currentTime = context.currentTime;
formationB4V45FilterRuntimeTestState.capturedContext{currentTime} = ...
    context;
formationB4V45FilterRuntimeTestState.capturedAdjacency{currentTime} = ...
    adjacency;
formationB4V45FilterRuntimeTestState.capturedDetails{currentTime} = details;
end

function [model, measurements, sensorTrajectories, neighborMap, ...
        commConfig, triggerConfig, identity] = buildSyntheticCase()
nodeCount = 6;
timeCount = 4;
model = generateMultisensorModel( ...
    nodeCount, zeros(1, nodeCount), 0.9 * ones(1, nodeCount), ...
    3 * ones(1, nodeCount), 'GA', 'LBP');
model.simulationLength = timeCount;
model.sensorCommRange = inf;

sceneConfig = struct();
sceneConfig.formationCount = 2;
sceneConfig.sensorsPerFormation = 3;
sceneConfig.numberOfSensors = nodeCount;
sceneConfig.sensorCenterWaypoints = {[-20; 0], [20; 0]};
sceneConfig.sensorGroupIds = [1, 1, 1, 2, 2, 2];
identity = buildDynamicTopologyPhysicalIdentityRegistry(sceneConfig);
sceneConfig.sensorPhysicalUids = identity.sensorPhysicalUids;
sceneConfig.formationPhysicalUidsBySensor = ...
    identity.formationPhysicalUidsBySensor;
sceneConfig.sensorLocalRoleUidsByFormation = ...
    identity.sensorLocalRoleUidsByFormation;
sceneConfig.physicalIdentityRegistryCanonicalSha256 = ...
    identity.canonicalSha256;
sensorMetadata = struct( ...
    'sensorPhysicalUids', identity.sensorPhysicalUids, ...
    'formationPhysicalUidsBySensor', ...
        identity.formationPhysicalUidsBySensor, ...
    'physicalIdentityRegistryCanonicalSha256', ...
        identity.canonicalSha256);
model.dynamicTopologyScenario = struct( ...
    'config', sceneConfig, 'sensor', sensorMetadata);

positions = [ ...
    -24, -18, -18, 16, 22, 22; ...
      0,   4,  -4,  0,  4, -4];
sensorTrajectories = cell(1, nodeCount);
for sensorIdx = 1:nodeCount
    sensorTrajectories{sensorIdx} = [ ...
        repmat(positions(:, sensorIdx), 1, timeCount); ...
        zeros(2, timeCount)];
end
measurements = repmat({{}}, nodeCount, timeCount);

baseAdjacency = false(nodeCount);
baseEdges = [1, 2; 2, 3; 3, 1; 4, 5; 5, 6; 6, 4; 1, 4];
for edgeIdx = 1:size(baseEdges, 1)
    left = baseEdges(edgeIdx, 1);
    right = baseEdges(edgeIdx, 2);
    baseAdjacency(left, right) = true;
    baseAdjacency(right, left) = true;
end
neighborMap = cell(1, nodeCount);
for receiverIdx = 1:nodeCount
    neighborMap{receiverIdx} = unique([ ...
        receiverIdx, find(baseAdjacency(receiverIdx, :))]);
end

commConfig = struct( ...
    'forceDelivery', true, ...
    'pDropByEdge', zeros(nodeCount, nodeCount, timeCount), ...
    'linkUniforms', 0.5 * ones(nodeCount, nodeCount, timeCount));
triggerConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'dynamicTopologyEnabled', true, ...
    'dynamicTopologyEdgeBudget', nodeCount, ...
    'topologyDirectedEnabled', true, ...
    'topologyDirectedMessageBudget', 2 * nodeCount, ...
    'topologyPolicyFcn', @captureSynchronizedPolicy, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicyPhysicalIdentityEnabled', true, ...
    'topologyPolicyName', 'formation-b4-v45-sync-runtime-test'));
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end

function clearTestState()
global formationB4V45FilterRuntimeTestState;
formationB4V45FilterRuntimeTestState = [];
end
