function test_influence_cone_boundary_shield_v114()
% TEST_INFLUENCECONEBOUNDARYSHIELDV114 Protocol and authorization.

protocol = getInfluenceConeBoundaryShieldV114Protocol();
assert(protocol.boundaryFormationId == 6);
assert(protocol.boundarySourceSensorId == 27);
assert(protocol.boundaryReceiverSensorId == 32);
assert(protocol.arrivalPageIndex == 6);
assert(protocol.earlyPageIndex == 5);
for pageIdx = 1:protocol.horizonSteps
    expectedArrival = pageIdx >= protocol.arrivalPageIndex;
    expectedEarly = pageIdx >= protocol.earlyPageIndex;
    assert(ismember(6, ...
        protocol.arrivalShieldFormationIdsByTime{pageIdx}) == ...
        expectedArrival);
    assert(ismember(6, ...
        protocol.earlyShieldFormationIdsByTime{pageIdx}) == ...
        expectedEarly);
    assert(all(ismember( ...
        protocol.baseProtectionFormationIdsByTime{pageIdx}, ...
        protocol.arrivalShieldFormationIdsByTime{pageIdx})));
end

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildInfluenceConeBoundaryShieldV114ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.arrivalShieldActionName, true);
assert(isInfluenceConeBoundaryShieldV114ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.arrivalShieldFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig.receiverSafeFormationConditionedPayloadMode = ...
    'control-only';
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
assert(nargin('runInfluenceConeBoundaryShieldV114X36T72') == 1);
end
