function test_formation_b4_v46_offline_source_provenance_registry()
% The accepted forty-case provenance remains offline and non-authorizing.

registry = getFormationB4V46OfflineSourceProvenanceRegistry();
core = getFormationB4V46TrackingSourceRegistry();

expectedTopLevelFields = { ...
    'id', 'contractVersion', 'coreRegistryId', ...
    'coreRegistryCanonicalSha256', 'structuralProtocolId', ...
    'structuralProtocolCanonicalSha256', ...
    'discoveryGenerationGitCommit', 'discoveryArtifactFileSha256', ...
    'discoveryRunMetadataCanonicalSha256', ...
    'discoveryCanonicalSha256', ...
    'sourceFreezeCandidateCanonicalSha256', ...
    'discoveryContractVersion', 'sourceFingerprintContractVersion', ...
    'runtimeFilterProjectionContractVersion', ...
    'sourceEnvelopeContractVersion', ...
    'discoveryRecordContractVersion', ...
    'canonicalSerializationFunction', 'runtimeEngine', ...
    'runtimeVersion', 'caseOrdering', 'caseCount', ...
    'fullRegistryCovered', 'candidateOnly', ...
    'independentAcceptanceCompleted', ...
    'sourceInputFingerprintsFrozen', ...
    'truthBearingSourceCommitmentsPresent', ...
    'offlineProvenanceAuditOnly', 'eligibleAsPermitDependency', ...
    'runtimeExecutionAuthorityProduced', ...
    'runtimeOnlyAcceptanceRequiredForPermit', ...
    'sourceArtifactPublicationAuthorized', ...
    'filterExecutionAuthorized', 'stateEstimateOutputAuthorized', ...
    'trackingOutcomeScoringAuthorized', 'armSelectionAuthorized', ...
    'developmentAdvanceDecisionAuthorized', ...
    'confirmationTrackingAuthorized', 'validationClaimAllowed', ...
    'runnerSelfAuthorizationAllowed', ...
    'confirmationTruthSecrecyGuaranteed', ...
    'confirmationTrackingOutcomeUnopened', 'entries', ...
    'evidenceBoundary', 'canonicalSha256'};
assert(isequal(sort(fieldnames(registry)), ...
    sort(expectedTopLevelFields(:))));
assert(strcmp(registry.contractVersion, ...
    'formation-b4-v46-offline-source-provenance-registry-v1'));
assert(strcmp(registry.coreRegistryCanonicalSha256, ...
    core.canonicalSha256));
assert(registry.caseCount == 40 && registry.fullRegistryCovered);
assert(~registry.candidateOnly);
assert(registry.independentAcceptanceCompleted);
assert(registry.sourceInputFingerprintsFrozen);
assert(registry.truthBearingSourceCommitmentsPresent);
assert(registry.offlineProvenanceAuditOnly);
assert(~registry.eligibleAsPermitDependency);
assert(~registry.runtimeExecutionAuthorityProduced);
assert(registry.runtimeOnlyAcceptanceRequiredForPermit);
assert(~registry.sourceArtifactPublicationAuthorized);
assert(~registry.filterExecutionAuthorized);
assert(~registry.stateEstimateOutputAuthorized);
assert(~registry.trackingOutcomeScoringAuthorized);
assert(~registry.armSelectionAuthorized);
assert(~registry.developmentAdvanceDecisionAuthorized);
assert(~registry.confirmationTrackingAuthorized);
assert(~registry.validationClaimAllowed);
assert(~registry.runnerSelfAuthorizationAllowed);
assert(~registry.confirmationTruthSecrecyGuaranteed);
assert(registry.confirmationTrackingOutcomeUnopened);
assert(strcmp(registry.discoveryGenerationGitCommit, ...
    'c2488e8076617c9aefc12b9401e20dc3857b35b2'));
assert(strcmp(registry.discoveryArtifactFileSha256, ...
    '87f82cfa14634f967ddda03fdc4d35ac84658f1a6b469948f3dd93aa986d644f'));
assert(strcmp(registry.discoveryRunMetadataCanonicalSha256, ...
    '2305a2689bcbf8c06fe0bedf987b8f74464622d3de5ac6a5aa347f017f9ac196'));
assert(strcmp(registry.discoveryCanonicalSha256, ...
    '65af8911e175d18e5d29e58b63c0de82e0de6dee309c9ce51eb08ffd151b932a'));
assert(strcmp(registry.sourceFreezeCandidateCanonicalSha256, ...
    '2458536c40353d2ce41c128c398000415ff7b4a7b2daa78ed577605631862a06'));

entries = registry.entries;
assert(isequal(sort(fieldnames(entries)), sort({ ...
    'caseOrdinal'; 'caseId'; 'coreCaseCanonicalSha256'; ...
    'seedRole'; 'fullSourceFingerprintCanonicalSha256'; ...
    'runtimeFilterProjectionCanonicalSha256'; ...
    'sourceEnvelopeCanonicalSha256'; ...
    'discoveryRecordCanonicalSha256'})));
assert(numel(entries) == core.caseCount);
assert(isequal([entries.caseOrdinal], 1:core.caseCount));
assert(isequal({entries.caseId}, {core.cases.id}));
assert(isequal({entries.coreCaseCanonicalSha256}, ...
    {core.cases.caseCanonicalSha256}));
assert(isequal({entries.seedRole}, {core.cases.seedRole}));
assert(nnz(strcmp({entries.seedRole}, 'development-sentinel')) == 8);
assert(nnz(strcmp({entries.seedRole}, 'confirmation')) == 32);
hashFields = { ...
    'coreCaseCanonicalSha256', ...
    'fullSourceFingerprintCanonicalSha256', ...
    'runtimeFilterProjectionCanonicalSha256', ...
    'sourceEnvelopeCanonicalSha256', ...
    'discoveryRecordCanonicalSha256'};
for entryIdx = 1:numel(entries)
    for fieldIdx = 1:numel(hashFields)
        assert(isSha256(entries(entryIdx).(hashFields{fieldIdx})));
    end
end
assert(strcmp(computeCanonicalValueSha256( ...
    rmfield(registry, 'canonicalSha256')), ...
    registry.canonicalSha256));

tampered = registry;
tampered.entries(1).fullSourceFingerprintCanonicalSha256 = ...
    repmat('0', 1, 64);
assert(~strcmp(computeCanonicalValueSha256( ...
    rmfield(tampered, 'canonicalSha256')), ...
    registry.canonicalSha256));

fprintf('PASS: V46 accepted offline provenance registry tests\n');
end

function valid = isSha256(value)
valid = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end
