function test_formation_index_equivariant_residual_duty_cycle_v44_rebuild()
% Independent spot reconstruction plus nested-tamper negative checks.

protocol = ...
    getFormationIndexEquivariantResidualDutyCycleV44Protocol();
path = fullfile('RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v44', 'residual_duty_cycle_development_v1', ...
    'FORMATION_RESIDUAL_DUTY_CYCLE_V44_DEVELOPMENT_V1.mat');
loaded = load(path, 'result');
frozen = loaded.result;
caseItem = frozen.cases(1);
definition = protocol.candidates(10);
record = caseItem.candidates(10);

[context, metadata] = ...
    buildFormationIndexEquivariantGeometryDevelopmentContext( ...
        caseItem.presetName, caseItem.seed);
assert(strcmp(metadata.inputCanonicalSha256, ...
    caseItem.inputCanonicalSha256));
assert(strcmp(metadata.physicalUidAssignmentCanonicalSha256, ...
    caseItem.physicalUidRegistryCanonicalSha256));
[referenceAdjacency, referenceDetails] = ...
    selectIndexEquivariantFormationBackbonePolicy(context, struct( ...
        'dominantWeight', protocol.dominantWeight, ...
        'residualWeight', protocol.referenceResidualWeight));
options = struct('period', definition.period, ...
    'dutyLayer', definition.dutyLayer, ...
    'phasePattern', definition.phasePattern, ...
    'activeResidualWeight', definition.activeResidualWeight, ...
    'dominantWeight', protocol.dominantWeight, ...
    'referenceResidualWeight', protocol.referenceResidualWeight);
[adjacency, weights, details] = ...
    buildIndexEquivariantResidualDutyCycleSchedule(context, options);
assert(strcmp(computeCanonicalValueSha256(struct( ...
    'adjacencySequence', logical(adjacency), ...
    'fusionWeightSequence', weights)), ...
    record.routeSequenceCanonicalSha256));
assert(isequal(details.messageCountsByPhase, ...
    record.messageCountsByPhase));
assert(details.messagesPerPeriod == record.messagesPerPeriod);
assert(abs(details.messageSavingFractionPerPeriod - ...
    record.messageSavingFractionPerPeriod) < 1e-12);
assert(isequal(any(adjacency, 3), referenceAdjacency));
assert(strcmp(computeCanonicalValueSha256(struct( ...
    'adjacency', logical(referenceAdjacency), ...
    'fusionWeights', referenceDetails.fusionWeightMatrix)), ...
    caseItem.referenceRouteCanonicalSha256));

reliability = 1 - context.commConfig.pDropByEdge';
profile = computePeriodicReliableKlaMeanSquareHorizonProfile( ...
    adjacency, weights, reliability, caseItem.maximumHorizon, struct( ...
        'missingNeighborWeightMode', ...
            protocol.missingNeighborWeightMode, ...
        'maximumIncomingCount', protocol.maximumIncomingCount, ...
        'targetSquaredFactors', ...
            protocol.targetSquaredContractionFactor));
targetH = reshape(profile.firstTargetHorizonByStartPhase(:, 1), 1, []);
assert(isequal(targetH, record.targetHorizonByStartPhase));
recomputedTargetRatios = nan(1, definition.period);
for phaseIdx = 1:definition.period
    targetMessages = profile.cumulativeMessagesByStartPhaseAndHorizon( ...
        phaseIdx, targetH(phaseIdx) + 1);
    recomputedTargetRatios(phaseIdx) = targetMessages / ...
        caseItem.referenceAttemptedMessagesToTarget;
    assert(targetMessages == record.targetMessagesByStartPhase(phaseIdx));
    assert(abs(recomputedTargetRatios(phaseIdx) - ...
        record.targetMessageRatioByStartPhase(phaseIdx)) < 1e-12);
end

assertNestedCanonicalHashes(frozen.cases);
tampered = frozen;
tampered.cases(1).sceneRole = 'forged-role';
tampered.cases(1).canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(tampered.cases(1), 'canonicalSha256'));
tampered.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(tampered, 'canonicalSha256'));
assert(~strcmp(tampered.canonicalSha256, frozen.canonicalSha256));
assert(~strcmp(tampered.cases(1).sceneRole, ...
    protocol.registeredCases(1).sceneRole));

tampered = frozen;
tampered.cases(1).candidates(10). ...
    targetMessageRatioByStartPhase(1) = ...
    tampered.cases(1).candidates(10). ...
        targetMessageRatioByStartPhase(1) + 0.01;
tampered.cases(1).candidates(10).canonicalSha256 = ...
    computeCanonicalValueSha256(rmfield( ...
        tampered.cases(1).candidates(10), 'canonicalSha256'));
tampered.cases(1).canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(tampered.cases(1), 'canonicalSha256'));
tampered.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(tampered, 'canonicalSha256'));
assert(~strcmp(tampered.canonicalSha256, frozen.canonicalSha256));
assert(~isequal(tampered.cases(1).candidates(10). ...
    targetMessageRatioByStartPhase, recomputedTargetRatios));

forged = evaluateFormationIndexEquivariantResidualDutyCycleV44Gate( ...
    frozen.cases, struct('officialCleanSourcePassed', true, ...
        'postHocExecutableFreezeAuditPassed', true), protocol);
assert(~forged.postHocExecutableFreezeAuditPassed);
assert(~forged.routeDevelopmentAdvancePassed);
fprintf('PASS: V44 rebuild spot-check and tamper tests\n');
end

function assertNestedCanonicalHashes(cases)
for caseIdx = 1:numel(cases)
    item = cases(caseIdx);
    assert(strcmp(computeCanonicalValueSha256( ...
        rmfield(item, 'canonicalSha256')), item.canonicalSha256));
    for candidateIdx = 1:numel(item.candidates)
        candidate = item.candidates(candidateIdx);
        assert(strcmp(computeCanonicalValueSha256( ...
            rmfield(candidate, 'canonicalSha256')), ...
            candidate.canonicalSha256));
    end
end
end
