function test_set_trust_sequence_v134()
% TEST_SET_TRUST_SEQUENCE_V134 Action bank and full-posterior semantics.

ranked = [4, 2, 1, 3];
protocol = getSetTrustSequenceV134Protocol();
assert(strcmp(protocol.payloadMode, 'full-posterior-trust'));
assert(protocol.preLearningGate.minimumPairedMeanEospGainFraction == 0.05);
assert(protocol.preLearningGate.requireBothScales);
assert(protocol.reportingPolicy.failedCandidatesRepositoryOnly);
assert(~protocol.gnnAuthorized);
m24 = protocol.scaleCases(strcmp({protocol.scaleCases.scaleName}, 'M24'));
x36 = protocol.scaleCases(strcmp({protocol.scaleCases.scaleName}, 'X36'));
assert(m24.horizonSteps == 6 && x36.horizonSteps == 8);

bank = buildSetTrustSequenceCandidatesV134( ...
    ranked, m24.formationCycleDiameter, ...
    struct('returnRamp', protocol.returnRamp));
assert(strcmp(bank.contractVersion, ...
    'v134-set-trust-sequence-bank-v1'));
assert(bank.horizonSteps == 6);
assert(bank.actionCount == 1 + 2 * numel(ranked));
assert(strcmp(bank.actions(1).scheduleKind, 'reference'));
assert(isempty(bank.actions(1).formationSet));

persistentAction = bank.actions(2);
tapered = bank.actions(3);
assert(isequal(persistentAction.formationSet, 4));
assert(all(cellfun(@(x) isequal(x, 4), ...
    persistentAction.formationIdsByTime)));
assert(all(cellfun(@(x) isequal(x, 0), ...
    persistentAction.trustFactorsByTime)));
assert(~persistentAction.returnsToFullTrust);
assert(isequal(cell2mat(tapered.trustFactorsByTime), ...
    [0, 0, 0, 0.25, 0.50, 1.00]));
assert(tapered.returnsToFullTrust);
assert(isequal(bank.actions(9).formationSet, ranked));

remapped = buildSetTrustSequenceCandidatesV134([8, 6, 5, 7], 3);
assert(isequal(remapped.actions(7).formationSet, [8, 6, 5]));
assert(isequal(remapped.actions(7).trustFactorsByTime, ...
    bank.actions(7).trustFactorsByTime));

weights = [0.5, 0.2, 0.3];
details = struct( ...
    'sourceIndices', [1, 2, 3], ...
    'isStale', [false, false, false], ...
    'formationTrustFactor', [1, 1, 0.25]);
attenuated = applyFormationConditionedFullPosteriorTrustV134( ...
    weights, details, 'renormalize');
assert(max(abs(attenuated - [0.5, 0.2, 0.075])) <= 1e-12);
selfWeighted = applyFormationConditionedFullPosteriorTrustV134( ...
    weights, details, 'self');
assert(max(abs(selfWeighted - [0.725, 0.2, 0.075])) <= 1e-12);

object = makeObject();
posteriors = {object, object, object};
crossResidual = false(3);
crossResidual(3, 1) = true;
crossResidual(1, 3) = true;
model = struct( ...
    'xDimension', 4, ...
    'existenceThreshold', 0.01, ...
    'dynamicTopologyScenario', struct( ...
        'config', struct('sensorGroupIds', [1, 1, 2])));
config = struct( ...
    'receiverSafeFormationConditionedTimes', 1, ...
    'receiverSafeFormationConditionedSchedule', {{[1, 2]}}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {{[0.5, 0]}}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        'full-posterior-trust', ...
    'receiverSafeExternalPositiveSupportThreshold', 0.2, ...
    'receiverSafeFormationConditionedHighExistenceThreshold', 0.5, ...
    'payloadExistenceThreshold', 0.01);
plan = buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct(), struct()}, ...
    model, config, 1);
positiveTrustPayload = plan.payloadByReceiverSender{1, 3};
assert(numel(positiveTrustPayload) == 1);
assert(positiveTrustPayload.numberOfGmComponents == 2);
assert(plan.eventTypeByReceiverSender(3, 1) == 2);
assert(~plan.abstainFromFusionEdgeMask(3, 1));
assert(plan.abstainFromFusionEdgeMask(1, 3));
assert(plan.fusionTrustFactorByReceiverSender(3, 1) == 0.5);
assert(plan.fusionTrustFactorByReceiverSender(1, 3) == 0);
assert(isempty(plan.payloadByReceiverSender{3, 1}));
assert(plan.usesFullSenderPosteriors);
assert(plan.totalControlSynopsisBytes > 0);
assert(plan.totalSelectedPayloadBytes > 0);

candidate = bank.actions(3);
anchorTime = 95;
execution = buildSetTrustSequenceV134ExecutionContext( ...
    'm24-formation-fov', protocol.pilotSeed, ...
    'candidate-continuation', anchorTime, ...
    'fixed-clockwise', candidate);
assert(isSetTrustSequenceV134ExecutionContext(execution));
runtimeModel = struct( ...
    'numberOfSensors', 24, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', 'm24-formation-fov', ...
        'seed', protocol.pilotSeed, ...
        'config', struct('formationCount', 4)));
returnTimes = anchorTime + (0:(m24.horizonSteps - 1));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', returnTimes(end), ...
    'sensorTrajectoryTimeCounts', ...
        returnTimes(end) * ones(1, 24), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'v134ReferenceCarrierMode', 'fixed-clockwise', ...
        'topologyPolicyHistoryDepth', 2, ...
        'topologyPolicyObservableContextOnly', true, ...
        'topologyPolicySensorObservationEnabled', true, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', returnTimes, ...
        'receiverSafeFormationConditionedTimes', returnTimes, ...
        'receiverSafeFormationConditionedSchedule', ...
            {candidate.formationIdsByTime}, ...
        'receiverSafeFormationConditionedTrustFactorsByTime', ...
            {candidate.trustFactorsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            protocol.payloadMode, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, execution, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig. ...
    receiverSafeFormationConditionedTrustFactorsByTime{end}(:) = 0.75;
failedClosed = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, execution, request);
catch errorInfo
    failedClosed = strcmp(errorInfo.identifier, ...
        'V134SetTrustExecution:InvalidRuntimeRequest');
end
assert(failedClosed);

referenceOutcome = struct( ...
    'eospaBySensorTime', 10 * ones(4, 6), ...
    'attemptedBytesByTime', 100 * ones(1, 6));
candidateOutcome = struct( ...
    'eospaBySensorTime', 9 * ones(4, 6), ...
    'attemptedBytesByTime', [20, 20, 20, 100, 100, 100]);
metrics = scoreSetTrustSequenceHeadroomV134( ...
    referenceOutcome, candidateOutcome, [1, 1, 2, 2], 3, protocol);
assert(abs(metrics.meanGainFraction - 0.1) <= 1e-12);
assert(abs(metrics.matureGainFraction - 0.1) <= 1e-12);
assert(isequal(metrics.matureColumns, 4:6));
assert(metrics.minimumSensorGainFraction > 0);
assert(metrics.minimumFormationGainFraction > 0);
assert(metrics.minimumMatureSensorGainFraction > 0);
assert(metrics.minimumMatureFormationGainFraction > 0);
assert(abs(metrics.attemptedByteSavingFraction - 0.4) <= 1e-12);
assert(metrics.passesPreLearningGate);

candidateOutcome.eospaBySensorTime(1, 4:6) = 12;
matureLocalRegression = scoreSetTrustSequenceHeadroomV134( ...
    referenceOutcome, candidateOutcome, [1, 1, 2, 2], 3, protocol);
assert(matureLocalRegression.meanGainFraction > 0.05);
assert(matureLocalRegression.minimumMatureSensorGainFraction < 0);
assert(~matureLocalRegression.passesSensorGate);
assert(~matureLocalRegression.passesPreLearningGate);

fprintf('PASS: V134 set--trust sequence contract\n');
end

function object = makeObject()
object = struct( ...
    'birthTime', 1, ...
    'birthLocation', 1, ...
    'r', 0.9, ...
    'numberOfGmComponents', 2, ...
    'w', [0.4, 0.6], ...
    'mu', {{zeros(4, 1), ones(4, 1)}}, ...
    'Sigma', {{eye(4), 2 * eye(4)}}, ...
    'detectionAssociationMass', 0.8);
end
