function test_formation_b4_v46_runtime_filter_model_sanitization()
% Runtime model is truth-stripped and remains execution-sealed.

registry = getFormationB4V46TrackingSourceRegistry();
caseContract = registry.cases(1);
initialRngState = rng();
restoreRng = onCleanup(@() rng(initialRngState));
inputs = generateDynamicTopologyScenarioInputs( ...
    caseContract.presetName, caseContract.seed);
runtimeModel = sanitizeFormationB4V46RuntimeFilterModel( ...
    inputs.model, caseContract, registry);

poisoned = inputs.model;
poisoned.explicitTargetTrajectories{1}(:) = 9.1e8;
poisoned.dynamicTopologyScenario.targetTrajectories{1}(:) = -8.2e8;
poisoned.dynamicTopologyScenario.target.birthTimes(:) = 777;
poisoned.targetBirthStates(:) = 6.3e8;
poisoned.targetFormationCenter(:) = -5.4e8;
poisoned.targetFormationVelocity(:) = 4.5e8;
poisoned.birthParameters(1).trajectory(:) = 3.6e8;
poisoned.birthParameters(1).timestamps(:) = 99;
poisoned.birthParameters(1).associationEntropy = 2.7e8;
poisoned.hypotheses.mu = {1.8e8};
poisoned.trajectory = struct( ...
    'birthLocation', 1, 'birthTime', 1, ...
    'trajectory', 7.7e8, 'trajectoryLength', 1, ...
    'timestamps', 1);
poisoned.birthTrajectory(1).trajectory(:) = -9.9e8;
poisonedRuntime = sanitizeFormationB4V46RuntimeFilterModel( ...
    poisoned, caseContract, registry);
assert(isequaln(poisonedRuntime, runtimeModel));
assert(strcmp(computeCanonicalValueSha256(poisonedRuntime), ...
    computeCanonicalValueSha256(runtimeModel)));

priorChanged = inputs.model;
priorChanged.birthParameters(1).mu{1}(1) = ...
    priorChanged.birthParameters(1).mu{1}(1) + 1e-6;
changedRuntime = sanitizeFormationB4V46RuntimeFilterModel( ...
    priorChanged, caseContract, registry);
assert(~isequaln(changedRuntime, runtimeModel));
assert(~strcmp(changedRuntime.formationB4V46RuntimeSourceEnvelope. ...
        registeredBirthPriorCanonicalSha256, ...
    runtimeModel.formationB4V46RuntimeSourceEnvelope. ...
        registeredBirthPriorCanonicalSha256));

extraBirthField = inputs.model;
[extraBirthField.birthParameters.futureTruth] = deal(1);
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraBirthField, caseContract, registry), ...
    'FormationB4V46RuntimeModel:BirthSchemaDrift');
extraQualityField = inputs.model;
extraQualityField.sensorQuality.futureTruth = 1;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraQualityField, caseContract, registry), ...
    'FormationB4V46RuntimeModel:SensorQualityDrift');
changedConfig = inputs.model;
changedConfig.dynamicTopologyScenario.config.targetRoutes{1}(1) = ...
    changedConfig.dynamicTopologyScenario.config.targetRoutes{1}(1) + 1;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    changedConfig, caseContract, registry), ...
    'FormationB4V46RuntimeModel:SourceCaseDrift');
extraHeading = inputs.model;
extraHeading.sensorFovHeadingRad(:, end + 1) = 0;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraHeading, caseContract, registry), ...
    'FormationB4V46RuntimeModel:FilterModelDrift');
extraDetection = inputs.model;
extraDetection.detectionProbability(end + 1) = 0.5;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraDetection, caseContract, registry), ...
    'FormationB4V46RuntimeModel:FilterModelDrift');
extraClutter = inputs.model;
extraClutter.clutterRate(end + 1) = 123;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraClutter, caseContract, registry), ...
    'FormationB4V46RuntimeModel:FilterModelDrift');
extraTransition = inputs.model;
extraTransition.A(end + 1, :) = 0;
assertErrorId(@() sanitizeFormationB4V46RuntimeFilterModel( ...
    extraTransition, caseContract, registry), ...
    'FormationB4V46RuntimeModel:FilterModelDrift');

assert(~isfield(runtimeModel, 'explicitTargetTrajectories'));
assert(~isfield(runtimeModel, 'hypotheses'));
assert(~isfield(runtimeModel, 'trajectory'));
assert(~isfield(runtimeModel, 'birthTrajectory'));
assert(~isfield(runtimeModel, 'rB'));
assert(~isfield(runtimeModel, 'muB'));
assert(~isfield(runtimeModel, 'SigmaB'));
assert(~isfield(runtimeModel, 'ospaParameters'));
assert(~isfield(runtimeModel.dynamicTopologyScenario, 'target'));
assert(~isfield(runtimeModel.dynamicTopologyScenario, ...
    'targetTrajectories'));
assert(~isfield(runtimeModel.dynamicTopologyScenario.config, ...
    'targetRoutes'));
assert(~isfield(runtimeModel.dynamicTopologyScenario.config, ...
    'targetDeathTimesByGroup'));
assert(runtimeModel.formationB4V46RuntimeSourceEnvelope. ...
    targetTrajectoryRealizationAbsent);
assert(runtimeModel.formationB4V46RuntimeSourceEnvelope. ...
    registeredBirthPriorRetained);
assert(all([runtimeModel.birthParameters.trajectoryLength] == 0));
assert(all(cellfun(@(value) all(isnan(value(:))), ...
    {runtimeModel.birthParameters.trajectory})));
assert(all(cellfun(@(value) all(value(:) == 0), ...
    {runtimeModel.birthParameters.timestamps})));

protocol = getFormationCausalMinimalEditV46Protocol();
triggerConfig = buildFormationB4V46FixedTriggerConfig( ...
    protocol.primaryArms{1}, caseContract.numberOfSensors);
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    inputs.model, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');
fakeContext = struct('contractVersion', 'forged-v46-permit');
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, triggerConfig, fakeContext), ...
    'FormationBundleSourcePermit:ExecutionContextDrift');

downgradedRuntime = rmfield(runtimeModel, ...
    'formationB4V46RuntimeSourceEnvelope');
downgradedRuntime.dynamicTopologyScenario.presetName = 'renamed';
downgradedRuntime.dynamicTopologyScenario.seed = 1;
downgradedRuntime.dynamicTopologyScenario.config.presetName = 'renamed';
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    downgradedRuntime, inputs.measurements, ...
    inputs.sensorTrajectories, inputs.neighborMap, ...
    inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');
rangeDrifted = downgradedRuntime;
rangeDrifted.sensorFovRange(1) = 299;
rangeDrifted.sensorFovHalfAngleDeg(2) = 59;
rangeDrifted.sensorMotionEnabled = false;
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    rangeDrifted, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');
scenarioRemoved = rmfield(downgradedRuntime, ...
    'dynamicTopologyScenario');
scenarioRemoved.sensorTrajectories = inputs.sensorTrajectories;
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    scenarioRemoved, inputs.measurements, [], inputs.neighborMap, ...
    inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');
renamedRaw = inputs.model;
renamedRaw.dynamicTopologyScenario.presetName = 'renamed';
renamedRaw.dynamicTopologyScenario.seed = 1;
renamedRaw.dynamicTopologyScenario.config.presetName = 'renamed';
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    renamedRaw, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, triggerConfig), ...
    'FormationB4V46TrackingPermit:ExecutionSealed');

% Numeric storage-class drift must not turn the semantic 24/36-sensor V46
% signature into a legacy model.
classDriftRequest = struct( ...
    'sensorTrajectoryTimeCounts', ones(1, 24));
for sensorCount = {uint8(24), single(24)}
    classDriftModel = struct( ...
        'numberOfSensors', sensorCount{1}, ...
        'sensorMotionEnabled', true, ...
        'birthTimeByLocation', 1);
    assertErrorId(@() ...
        assertDynamicTopologyTrackingOutcomeAuthorized( ...
            classDriftModel, struct(), classDriftRequest), ...
        'FormationB4V46TrackingPermit:ExecutionSealed');
end

clear restoreRng;
finalRngState = rng();
assert(isequaln(finalRngState, initialRngState));
fprintf('PASS: V46 sanitized runtime model sealed-boundary tests\n');
end

function assertErrorId(callback, expectedIdentifier)
failed = false;
actualIdentifier = '';
try
    callback();
catch errorInfo
    actualIdentifier = errorInfo.identifier;
    failed = strcmp(actualIdentifier, expectedIdentifier);
end
assert(failed, 'Expected %s, received %s.', ...
    expectedIdentifier, actualIdentifier);
end
