function test_finite_duration_abstention_v112()
% TEST_FINITEDURATIONABSTENTIONV112 Schedule and authorization contract.

protocol = getFiniteDurationAbstentionV112Protocol();
assert(isequal(protocol.candidateDurations, [3, 4, 5, 6]));
assert(numel(protocol.candidateActionNames) == 4);
for duration = protocol.candidateDurations
    schedule = protocol.baseProtectionFormationIdsByTime;
    schedule((duration + 1):end) = repmat( ...
        {zeros(1, 0)}, 1, protocol.horizonSteps - duration);
    assert(all(cellfun(@isempty, schedule((duration + 1):end))));
    assert(~isempty(schedule{duration}));
end

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildFiniteDurationAbstentionV112ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.candidateActionNames{1}, true);
assert(isFiniteDurationAbstentionV112ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
schedule = protocol.baseProtectionFormationIdsByTime;
schedule(4:end) = repmat({zeros(1, 0)}, 1, 5);
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', {schedule}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));
end
