function testFormationB4V48LaggedWindowStructuralProbe()
% Causal sync and posthoc sync comparators must remain distinct.

result = runFormationB4V48LaggedWindowStructuralProbe(struct( ...
    'presets', {{'m24-formation-fov'}}, ...
    'seeds', 41, 'maximumCoordinateSweeps', 0));
assert(result.caseCount == 1);
item = result.cases(1);
assert(item.candidateSamePosteriorMessageBudget);
assert(item.candidateSensorUnionStrong);
assert(item.candidateFormationUnionStrong);
assert(abs(item.candidateRealizedSquaredFactor - ...
    item.causalSyncRealizedSquaredFactor) < 1e-12);
assert(abs(item.realizedRelativeSquaredFactorImprovementVsCausalSync) ...
    < 1e-12);
assert(item.posthocBestSyncRealizedSquaredFactor <= ...
    item.causalSyncRealizedSquaredFactor + 1e-12);
assert(item.posthocBestSyncRealizedSquaredFactor == ...
    min(item.posthocSyncRealizedSquaredFactorByPulsePhase));
assert(~item.posteriorUsed && ~item.truthUsed && ...
    ~item.measurementUsed && ~item.futurePageUsedByPolicy);
assert(~result.validationClaimAllowed && ...
    result.developmentEvidenceOnly);
fprintf('PASS: FormationB4V48 lagged-window structural probe tests\n');
end
