function test_output_aligned_label_effective_oracle_v150()
% TEST_OUTPUT_ALIGNED_LABEL_EFFECTIVE_ORACLE_V150 Registered H=8 boundary.

protocol = getOutputAlignedLabelEffectiveOracleV150Protocol();
for caseIdx = 1:numel(protocol.cases)
    entry = protocol.cases(caseIdx);
    context = ...
        buildOutputAlignedLabelEffectiveOracleV150ExecutionContext( ...
            entry.presetName, entry.seed, entry.currentTime, ...
            'omit-r1-s2-l1-1', true);
    assert(isOutputAlignedLabelEffectiveOracleV150ExecutionContext(context));
    runtimeModel = struct( ...
        'numberOfSensors', entry.expectedNodeCount, ...
        'dynamicTopologyScenario', struct( ...
            'presetName', entry.presetName, ...
            'seed', entry.seed, ...
            'config', struct( ...
                'formationCount', entry.expectedFormationCount)));
    request = struct( ...
        'contractVersion', ...
            'dynamic-topology-filter-authorization-request-v1', ...
        'operation', 'filter-execution', ...
        'measurementTimeCount', context.measurementTimeCount, ...
        'sensorTrajectoryTimeCounts', ...
            context.measurementTimeCount * ...
                ones(1, entry.expectedNodeCount), ...
        'triggerConfig', struct( ...
            'topologyPolicyName', protocol.policyName, ...
            'topologyPolicyHistoryDepth', 2, ...
            'receiverSafeLabelFusionEnabled', true, ...
            'receiverSafeLabelFusionMode', 'external-label-plan', ...
            'receiverSafeExternalActiveTimes', entry.currentTime, ...
            'receiverSafeExternalDropLabelsByReceiverSender', ...
                {cell(entry.expectedNodeCount)}, ...
            'receiverSafeExternalExplicitOmissionEnabled', true, ...
            'receiverSafeExternalPositiveSupportOmissionAllowed', true));
    authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
    assert(authorization.trackingOutcomeScoringAuthorized);
    assert(authorization.developmentEvidenceOnly);

    request.triggerConfig. ...
        receiverSafeExternalExplicitOmissionEnabled = false;
    rejected = false;
    try
        assertDynamicTopologyTrackingOutcomeAuthorized( ...
            runtimeModel, context, request);
    catch errorInfo
        rejected = strcmp(errorInfo.identifier, ...
            'OutputAlignedLabelOracleV150:InvalidRuntimeRequest');
    end
    assert(rejected);
end

fprintf('test_output_aligned_label_effective_oracle_v150 passed\n');
end
