function test_counterfactual_regret_gate_v133_teacher()
% TEST_COUNTERFACTUAL_REGRET_GATE_V133_TEACHER Permit, labels and features.

protocol = getCounterfactualRegretGateV133Protocol();
assert(protocol.routeExecutionAuthorized);
assert(protocol.trackingOutcomeScoringAuthorized);
assert(protocol.modelTrainingAuthorized);

context = buildCounterfactualRegretGateV133ExecutionContext( ...
    'm24-formation-fov', protocol.developmentSeeds(1), ...
    'development', 'candidate-continuation', 75, ...
    'fixed-clockwise', 2);
assert(isCounterfactualRegretGateV133ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', 24, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', 'm24-formation-fov', ...
        'seed', protocol.developmentSeeds(1), ...
        'config', struct('formationCount', 4)));
request = buildRequest(context, protocol, 24);
authorization = validateCounterfactualRegretGateV133Execution( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.groundTruthAccessAuthorized);
request.triggerConfig.receiverSafeFormationConditionedPayloadMode = ...
    'control-only';
rejected = false;
try
    validateCounterfactualRegretGateV133Execution( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'CounterfactualRegretV133:InvalidRuntimeRequest');
end
assert(rejected);
baselineContext = buildCounterfactualRegretGateV133ExecutionContext( ...
    'm24-formation-fov', protocol.developmentSeeds(1), ...
    'development', 'baseline-selection', 160, ...
    'fixed-counter-clockwise', 0);
baselineRequest = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', 160, ...
    'sensorTrajectoryTimeCounts', 160 * ones(1, 24), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'v133ReferenceCarrierMode', 'fixed-counter-clockwise', ...
        'topologyPolicyHistoryDepth', 2, ...
        'topologyPolicyObservableContextOnly', true, ...
        'topologyPolicySensorObservationEnabled', true, ...
        'receiverSafeLabelFusionEnabled', false));
baselineAuthorization = ...
    validateCounterfactualRegretGateV133Execution( ...
        runtimeModel, baselineContext, baselineRequest);
assert(baselineAuthorization.trackingOutcomeScoringAuthorized);

groupIds = [1, 1, 2, 2];
adjacency = logical([ ...
    0, 0, 0, 1; ...
    1, 0, 0, 0; ...
    0, 1, 0, 0; ...
    0, 0, 1, 0]);
reference = syntheticOutcome(zeros(4, 4), [1, 1, 1, 1], 100);
candidate = syntheticOutcome([ ...
    0, 0, 0, 0; ...
    0, 0, 0, 0; ...
    0, 0.2, 0.2, 0.2; ...
    0, 0.1, 0.1, 0.1], [1, 1, 1, 1.1], 80);
label = buildCounterfactualRegretTeacherLabelV133( ...
    reference, candidate, groupIds, 1, adjacency, protocol);
assert(label.harmful);
assert(~label.safeAction);
assert(label.componentRegret(1) > 0);
assert(label.componentRegret(6) > 0);
assert(label.attemptedByteSavingPercent == 20);

[observable, route, weights, groups] = buildFeatureCase();
formationId = groups(find(any( ...
    route & (groups(:) ~= groups(:)'), 2), 1));
features = extractCounterfactualRegretFeaturesV133( ...
    observable, route, weights, groups, formationId, protocol);
assert(~features.truthUsed && ~features.futureOutcomeUsed);
assert(~features.seedIdentifierUsed && ~features.absoluteTimeUsed);
assert(~features.fixedFormationIdentifierUsed);
assert(any(strcmp(features.names, 'exact_task_risk_change')));
assert(any(strcmp(features.names, ...
    'downstream_hop_distance_max')));
assert(all(isfinite(features.values)));
modelSpec = getCounterfactualRegretGateV133ModelSpec();
assert(all(ismember(modelSpec.featureNames, features.names)));

fprintf('PASS: V133 teacher permit, label and feature contracts\n');
end

function request = buildRequest(context, protocol, nodeCount)
config = struct( ...
    'topologyPolicyName', protocol.outcomePolicyName, ...
    'v133ReferenceCarrierMode', context.referenceCarrierMode, ...
    'topologyPolicyHistoryDepth', 2, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicySensorObservationEnabled', true, ...
    'receiverSafeLabelFusionEnabled', true, ...
    'receiverSafeLabelFusionMode', ...
        'formation-supported-label-plan', ...
    'receiverSafeExternalActiveTimes', context.currentTime, ...
    'receiverSafeFormationConditionedTimes', context.currentTime, ...
    'receiverSafeFormationConditionedSchedule', ...
        {{context.protectedFormationId}}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.actionContract.payloadMode, ...
    'receiverSafeFormationConditionedOnlinePolicyEnabled', false);
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones(1, nodeCount), ...
    'triggerConfig', config);
end

function outcome = syntheticOutcome(delta, consensus, attemptedBytes)
outcome = struct( ...
    'eospaBySensorTime', 10 + delta, ...
    'posteriorConsensusByTime', consensus, ...
    'attemptedBytesByTime', ...
        attemptedBytes / size(delta, 2) * ones(1, size(delta, 2)));
end

function [context, adjacency, weights, groupIds] = buildFeatureCase()
sensorCount = 4;
currentTime = 3;
groupIds = [1, 1, 2, 2];
model = generateMultisensorModel( ...
    sensorCount, zeros(1, sensorCount), ...
    0.9 * ones(1, sensorCount), ...
    2 * ones(1, sensorCount), 'GA', 'LBP');
model.sensorMotionEnabled = true;
model.sensorFovEnabled = true;
model.sensorFovHalfAngleDeg = 60 * ones(1, sensorCount);
model.sensorFovRange = 150 * ones(1, sensorCount);
model.sensorFovHeadingRad = zeros(sensorCount, currentTime);
model.sensorTrajectories = cell(1, sensorCount);
positions = [0, 10, 20, 30; 0, 0, 0, 0];
for sensorIdx = 1:sensorCount
    model.sensorTrajectories{sensorIdx} = repmat( ...
        [positions(:, sensorIdx); 1; 0], 1, currentTime);
end
model.sensorQuality = struct('enabled', false);
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', groupIds));
model = attachCurrentObservableSensorGeometry( ...
    model, positions, currentTime, sensorCount);

posteriors = cell(1, sensorCount);
for sensorIdx = 1:sensorCount
    object = model.birthParameters(1);
    object.birthTime = 1;
    object.birthLocation = 1;
    object.r = 0.65 + 0.05 * sensorIdx;
    object.numberOfGmComponents = 1;
    object.w = 1;
    object.mu = {[15 + sensorIdx; 2 * sensorIdx; 0; 0]};
    object.Sigma = {diag([4, 5, 1, 1])};
    object.associationEntropy = 0.1 * sensorIdx;
    object.detectionAssociationMass = 0.8;
    posteriors{sensorIdx} = object;
end
triggerConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyPolicySensorObservationEnabled', true, ...
    'missingNeighborWeightMode', 'renormalize', ...
    'missingLabelFusionMode', 'fov-aware-censored'));
full = struct( ...
    'localPosteriorBySensor', {posteriors}, ...
    'model', model, ...
    'commConfig', struct('pDropByEdge', ...
        0.1 * ones(sensorCount)), ...
    'triggerConfig', triggerConfig, ...
    'currentTime', currentTime, ...
    'previousAdjacency', false(sensorCount), ...
    'previousAdjacencyHistory', false(sensorCount, sensorCount, 2), ...
    'previousAdjacencyHistoryCount', 2, ...
    'previousAdjacencyHistoryTimes', [1, 2], ...
    'previousAdjacencyHistoryConvention', ...
        'receiver-row-sender-column-directed-oldest-to-newest', ...
    'previousAdjacencyHistorySource', ...
        'selected-validated-topology', ...
    'baseAdjacency', true(sensorCount) & ~eye(sensorCount), ...
    'physicalAdjacency', true(sensorCount) & ~eye(sensorCount), ...
    'edgeScores', zeros(sensorCount), ...
    'edgeBudget', 6, ...
    'directedMessageBudget', 8, ...
    'positions', positions, ...
    'localInnovationHistory', 0.2 * ones(sensorCount, 3), ...
    'localAssociationConfidenceHistory', ...
        0.8 * ones(sensorCount, 3), ...
    'localNisNormHistory', ones(sensorCount, 3), ...
    'localNisDeviationHistory', 0.1 * ones(sensorCount, 3), ...
    'localUpdateHistoryTimes', 1:3, ...
    'previousDeliveryHistory', false(sensorCount, sensorCount, 2), ...
    'previousDeliveryHistoryCount', 2, ...
    'previousDeliveryHistoryTimes', [1, 2], ...
    'previousDeliveryHistoryConvention', ...
        ['receiver-row-sender-column-directed-oldest-to-newest-', ...
         'successful-deliveries'], ...
    'previousDeliveryHistorySource', ...
        'filter-runtime-past-delivery-acknowledgments');
context = buildObservableTopologyPolicyContext(full);
adjacency = logical([ ...
    0, 1, 0, 0; ...
    1, 0, 0, 0; ...
    0, 1, 0, 1; ...
    0, 0, 1, 0]);
weights = zeros(sensorCount);
weights(adjacency) = 0.2;
weights(1:sensorCount+1:end) = 1 - sum(weights, 2)';
end
