function test_network_budget_reallocated_multi_source_v95()
% TEST_NETWORKBUDGETREALLOCATEDMULTISOURCEV95 Frozen sender-budget invariant.

protocol = getNetworkBudgetReallocatedMultiSourceV95Protocol();
assert(strcmp(protocol.receiverMode, 'fov-aware-censored'));
assert(numel(protocol.cases) == 2);
assert(isequal([protocol.cases.requiredTokenCount], [2, 3]));
assert(isequal([protocol.cases.horizonSteps], [5, 7]));
assert(strcmp(protocol.outcomePolicyName, ...
    'network-budget-reallocated-multi-source-v95-v1'));

entry = protocol.cases(1);
referenceSequence = ones(1, entry.horizonSteps);
context = ...
    buildNetworkBudgetReallocatedMultiSourceV95ExecutionContext( ...
        entry.presetName, entry.seed, entry.currentTime, ...
        'matched-static', referenceSequence);
assert(isNetworkBudgetReallocatedMultiSourceV95ExecutionContext(context));
assert(isequal(context.actionSequenceIndices, referenceSequence));
model = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount, ...
            'sceneStyle', 'braided-handover')));
request = struct( ...
    'contractVersion', 'dynamic-topology-filter-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'topologyDirectedMessageBudget', ...
            2 * entry.expectedNodeCount, ...
        'missingLabelFusionMode', protocol.receiverMode));
authorization = ...
    validateNetworkBudgetReallocatedMultiSourceV95Execution( ...
        model, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(authorization.armOrdinal == 1);
fixedCandidateSequence = 3 * ones(1, entry.horizonSteps);
context = ...
    buildNetworkBudgetReallocatedMultiSourceV95ExecutionContext( ...
        entry.presetName, entry.seed, entry.currentTime, ...
        'fixed-candidate', fixedCandidateSequence);
assert(isequal(context.actionSequenceIndices, fixedCandidateSequence));
request.measurementTimeCount = context.measurementTimeCount;
request.sensorTrajectoryTimeCounts(:) = context.measurementTimeCount;
authorization = ...
    validateNetworkBudgetReallocatedMultiSourceV95Execution( ...
        model, context, request);
assert(authorization.armOrdinal == 4);
invalidRejected = false;
try
    buildNetworkBudgetReallocatedMultiSourceV95ExecutionContext( ...
        entry.presetName, entry.seed, entry.currentTime, ...
        'invalid', [3, 2, ones(1, entry.horizonSteps - 2)]);
catch
    invalidRejected = true;
end
assert(invalidRejected);

nodeCount = 6;
groupIds = [1, 1, 2, 2, 3, 3];
referenceAdjacency = false(nodeCount);
referenceWeights = zeros(nodeCount);
dominant = [2, 1, 4, 3, 6, 5];
residual = [3, 4, 5, 6, 1, 2];
for receiver = 1:nodeCount
    referenceAdjacency(receiver, dominant(receiver)) = true;
    referenceAdjacency(receiver, residual(receiver)) = true;
    referenceWeights(receiver, receiver) = 0.25;
    referenceWeights(receiver, dominant(receiver)) = 0.70;
    referenceWeights(receiver, residual(receiver)) = 0.05;
end
physical = referenceAdjacency | referenceAdjacency';
physical(1, 4) = true;
physical(4, 1) = true;
physical(3, 1) = true;
physical(1, 3) = true;
candidateTemplate = struct( ...
    'targetReceiverIdx', NaN, 'donorReceiverIdx', NaN, ...
    'senderIdx', NaN, 'targetFormationId', NaN, ...
    'sourceFormationId', NaN, 'targetNoveltyFraction', NaN, ...
    'donorUniqueFraction', NaN, 'netUtilityFraction', NaN);
candidates = repmat(candidateTemplate, 1, 2);
candidates(1) = struct( ...
    'targetReceiverIdx', 1, 'donorReceiverIdx', 2, ...
    'senderIdx', 4, 'targetFormationId', 1, ...
    'sourceFormationId', 2, 'targetNoveltyFraction', 0.08, ...
    'donorUniqueFraction', 0.01, 'netUtilityFraction', 0.07);
candidates(2) = struct( ...
    'targetReceiverIdx', 3, 'donorReceiverIdx', 5, ...
    'senderIdx', 1, 'targetFormationId', 2, ...
    'sourceFormationId', 1, 'targetNoveltyFraction', 0.06, ...
    'donorUniqueFraction', 0.01, 'netUtilityFraction', 0.05);
projection = projectSenderBudgetReallocationV95( ...
    candidates, referenceAdjacency, referenceWeights, physical, ...
    groupIds, struct('requiredTokenCount', 2));
assert(projection.feasible);
assert(projection.selectedTokenCount == 2);
assert(projection.referenceMessageCount == 12);
assert(projection.donorOnlyMessageCount == 10);
assert(projection.candidateMessageCount == 12);
assert(projection.senderMessageParityPassed);
assert(isequal(sum(projection.candidateAdjacency, 1), ...
    sum(referenceAdjacency, 1)));
assert(all(abs(sum(projection.candidateWeights, 2) - 1) < 1e-12));
assert(all(abs(sum(projection.donorOnlyWeights, 2) - 1) < 1e-12));
assert(projection.candidateWeights(1, 1) == 0.20);
assert(projection.candidateWeights(2, 2) == 0.30);
end
