function testFormationB4V49TimeVaryingB4StructuralReplay()
% Current-page cycle policy and posthoc four-page structural replay contract.

result = runFormationB4V49TimeVaryingB4StructuralReplay(struct( ...
    'presets', {{'m24-formation-fov-convoy'}}, ...
    'seeds', 41, 'windowMode', 'focus-start'));
repeat = runFormationB4V49TimeVaryingB4StructuralReplay(struct( ...
    'presets', {{'m24-formation-fov-convoy'}}, ...
    'seeds', 41, 'windowMode', 'focus-start'));
assert(result.caseCount == 1 && result.windowCount == 1);
assert(strcmp(result.canonicalSha256, repeat.canonicalSha256));
assert(result.wallClockTimingExcludedFromCanonicalSha256);
assert(result.cycleSelectedWindowCount == 1);
assert(result.posthocPositiveWindowCount == 1 && ...
    result.posthocNegativeWindowCount == 0);
assert(result.posthocNoWorseAllWindowFraction == 1 && ...
    result.posthocNoWorseSelectedWindowFraction == 1);
assert(result.planningPositivePosthocNegativeWindowCount == 0);
assert(result.allSameDirectedPosteriorMessageCount);
assert(result.allBurstSensorStrongConnected && ...
    result.allBurstFormationStrongConnected);
assert(result.currentBurstPageUsedByPolicy && ...
    ~result.futurePagesUsedByPolicy && ...
    result.futurePagesUsedByPosthocAudit);
assert(~result.posteriorUsed && ~result.truthUsed && ...
    ~result.measurementUsed && ...
    ~result.realizedDeliveryUniformsUsed && ...
    ~result.trackingOutcomeScored);
assert(~result.routeDisseminationImplemented && ...
    ~result.atomicCommitImplemented && ...
    ~result.sameTotalByteClaimAllowed && ...
    ~result.timeVaryingNoWorseCertified && ...
    ~result.posthocPointwiseDominanceClaimAllowed && ...
    result.independentDirectedDeliveryAssumed && ...
    ~result.validationClaimAllowed && ...
    result.developmentEvidenceOnly);

item = result.cases(1);
window = item.windows(1);
assert(item.wallClockTimingExcludedFromCanonicalSha256 && ...
    window.wallClockTimingExcludedFromCanonicalSha256);
assert(window.cycleSelected && ...
    ~window.selectedUsedIncumbentFallback);
assert(strcmp(window.selectedFallbackReason, 'none'));
assert(window.planningRelativeImprovement > 0.01 && ...
    window.posthocTimeVaryingRelativeImprovement > 0.01);
assert(window.sameDirectedPosteriorMessageCount);
assert(isequal(window.incumbentMessageCountByPhase, ...
    [2 * item.nodeCount, item.nodeCount, item.nodeCount, item.nodeCount]));
assert(isequal(window.candidateMessageCountByPhase, ...
    [2 * item.nodeCount, item.nodeCount, item.nodeCount, item.nodeCount]));
assert(~window.formationPairSetChangedFromPreviousWindow);
assert(~window.cycleToCycleFormationPairSetChangedFromPreviousWindow);
assert(~window.cycleFallbackTransitionFromPreviousWindow);
assert(window.formationPairSymmetricDifferenceCount == 0);
assert(window.crossResidualGatewaySymmetricDifferenceCount == 0);
assert(all(window.selectedFormationPairPhysicalUidTable(:, 1) < ...
    window.selectedFormationPairPhysicalUidTable(:, 2)));
assert(window.totalCertificateEvaluationCount == 4);
assert(window.windowStartAlignedToAbsoluteB4PhaseOne);
assert(window.currentBurstPageUsedByPolicy && ...
    ~window.futurePagesUsedByPolicy && ...
    window.futurePagesUsedByPosthocAudit && ...
    window.cycleUsedOnBurstPageOnly);
assert(~window.posteriorUsed && ~window.truthUsed && ...
    ~window.measurementUsed && ...
    ~window.realizedDeliveryUniformsUsed && ...
    ~window.trackingOutcomeScored && ...
    ~window.sameTotalByteClaimAllowed && ...
    ~window.timeVaryingNoWorseCertified && ...
    ~window.posthocPointwiseDominanceClaimAllowed && ...
    window.independentDirectedDeliveryAssumed && ...
    window.developmentEvidenceOnly);

radial = runFormationB4V49TimeVaryingB4StructuralReplay(struct( ...
    'presets', {{'m24-formation-fov', 'x36-formation-fov'}}, ...
    'seeds', 41, 'windowMode', 'focus-start'));
assert(isequal(radial.cases(1).windowStarts, 57));
assert(isequal(radial.cases(2).windowStarts, 53));
m24RadialWindow = radial.cases(1).windows(1);
x36RadialWindow = radial.cases(2).windows(1);
assert(m24RadialWindow.windowStartAlignedToAbsoluteB4PhaseOne);
assert(x36RadialWindow.windowStartAlignedToAbsoluteB4PhaseOne);
assert(radial.allSameDirectedPosteriorMessageCount);

fprintf('PASS: FormationB4V49 time-varying B4 structural replay tests\n');
end
