function test_alternative_source_v118()
% TEST_ALTERNATIVE_SOURCE_V118 Rewire invariants and authorization.

protocol = getAlternativeSourceV118Protocol();
assert(isequal(protocol.candidateSourceSensorIds, [25, 26, 28, 29, 30]));
assert(protocol.originalSourceSensorId == 27);
assert(protocol.receiverSensorId == 32);
assert(protocol.connectivityRepairSourceSensorId == 25);
assert(protocol.connectivityRepairReceiverSensorId == 26);
assert(numel(protocol.candidateActionNames) == 5);

[baseAdjacency, baseWeights, baseDetails] = syntheticCarrier();
[candidateAdjacency, candidateWeights, details] = ...
    rewireInfluenceConeSourceV118( ...
        baseAdjacency, baseWeights, baseDetails, 3, 5, 6, 1, 5);
assert(~candidateAdjacency(6, 3) && candidateAdjacency(6, 5));
assert(~candidateAdjacency(5, 1) && candidateAdjacency(5, 3));
assert(abs(candidateWeights(6, 5) - 0.05) <= 1e-12);
assert(max(abs(sum(candidateWeights, 2) - 1)) <= 1e-12);
assert(nnz(candidateAdjacency) == nnz(baseAdjacency));
assert(max(abs(sort(candidateWeights(candidateWeights > 0)) - ...
    sort(baseWeights(baseWeights > 0)))) <= 1e-12);
assert(details.v118SourceRewire.messageParityPassed);
assert(details.v118SourceRewire.strongConnectivityPassed);
assert(details.v118SourceRewire.repairSourceId == 1);
assert(details.v118SourceRewire.repairReceiverId == 5);

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildAlternativeSourceV118ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.candidateActionNames{1}, true);
assert(isAlternativeSourceV118ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.sourceFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));
request.triggerConfig.receiverSafeFormationConditionedPayloadMode = ...
    'control-only';
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
assert(nargin('runAlternativeSourceV118X36T72') == 1);
fprintf('test_alternative_source_v118 passed\n');
end

function [adjacency, weights, details] = syntheticCarrier()
nodeCount = 6;
weights = zeros(nodeCount);
residual = false(nodeCount);
for receiver = 1:nodeCount
    dominantSource = mod(receiver, nodeCount) + 1;
    residualSource = mod(receiver + 1, nodeCount) + 1;
    weights(receiver, receiver) = 0.25;
    weights(receiver, dominantSource) = 0.70;
    weights(receiver, residualSource) = 0.05;
    residual(receiver, residualSource) = true;
end
residual(6, 2) = false;
weights(6, 2) = 0;
residual(6, 3) = true;
weights(6, 3) = 0.05;
adjacency = weights > 0;
details = struct( ...
    'residualAdjacency', residual, ...
    'fusionWeightMatrix', weights, ...
    'messageCount', nnz(adjacency), ...
    'selectedSourcesByReceiver', ...
        {arrayfun(@(receiver) find(adjacency(receiver, :)), ...
            1:nodeCount, 'UniformOutput', false)});
end
