function test_outward_reference_carrier_v125()
% TEST_OUTWARD_REFERENCE_CARRIER_V125 Protocol, payload and authorization.

protocol = getOutwardReferenceCarrierV125Protocol();
v124 = getF6ReferenceRowCompositionV124Protocol();
assert(isequal(protocol.graphChoiceByFormationPage, ...
    v124.graphChoiceByFormationPage));
assert(isequal(protocol.payloadFormationIdsByPage, ...
    v124.payloadFormationIdsByPage));
assert(isequal(protocol.carrierTimes, 72:79));
assert(protocol.carrierSenderSensorId == 27);
assert(protocol.carrierReceiverSensorId == 32);

objects = repmat(struct( ...
    'r', 0.9, 'numberOfGmComponents', 1), 1, 2);
objects(2).r = 0.01;
config = struct( ...
    'outwardReferenceCarrierEnabled', true, ...
    'outwardReferenceCarrierTimes', 72, ...
    'outwardReferenceCarrierSenderIds', 27, ...
    'outwardReferenceCarrierReceiverIds', 32, ...
    'outwardReferenceCarrierPosteriorByTime', {{objects}}, ...
    'payloadExistenceThreshold', 0.1);
[payload, applied, pageIdx] = ...
    selectOutwardReferenceCarrierPayload( ...
        struct([]), config, 27, 32, 72, 2, false);
assert(applied && pageIdx == 1 && numel(payload) == 1);
[~, applied] = selectOutwardReferenceCarrierPayload( ...
    struct([]), config, 26, 32, 72, 2, false);
assert(~applied);

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildOutwardReferenceCarrierV125ExecutionContext( ...
    entry.presetName, entry.seed, 72, ...
    protocol.candidateSequenceName, true);
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.payloadFormationIdsByPage}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only', ...
        'outwardReferenceCarrierEnabled', true, ...
        'outwardReferenceCarrierTimes', 72:79, ...
        'outwardReferenceCarrierSenderIds', 27 * ones(1, 8), ...
        'outwardReferenceCarrierReceiverIds', 32 * ones(1, 8), ...
        'outwardReferenceCarrierPosteriorByTime', ...
            {repmat({objects}, 1, 8)}));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));
fprintf('test_outward_reference_carrier_v125 passed\n');
end
