function test_rolling_safe_causal_option_protocol()
% TEST_ROLLINGSAFECAUSALOPTIONPROTOCOL Freeze paired H=3 semantics.

protocol = getLabelSetSimulatorPolicyProtocol();
assert(protocol.rollingSafeCausalOptionAuthorized);
assert(strcmp(protocol.rollingSafeCausalOptionContractVersion, ...
    'm24-rolling-safe-causal-h3-option-bank-v2'));
assert(strcmp(protocol.rollingSafeCausalOptionEvidenceNamespace, ...
    'rolling_safe_causal_option_sentinel_v2'));
assert(strcmp(protocol.rollingSafeCausalOptionArtifactSuffix, ...
    'option_v2'));
assert(strcmp(protocol.rollingSafeCausalOptionSummaryStem, ...
    'rolling_safe_causal_option_paired_sentinel_m24_v2'));
assert(isequal(size( ...
    protocol.rollingSafeCausalOptionSequences), [8, 3]));
assert(isequal(size( ...
    protocol.rollingSafeCausalOneStepControlSequences), [8, 3]));
assert(numel(protocol.rollingSafeCausalOptionNames) == 8);
assert(numel(protocol.rollingSafeCausalOneStepControlNames) == 8);
assert(isequal(protocol.rollingSafeCausalOptionReferenceSequence, ...
    [24, 24, 24]));
assert(nnz(all(protocol.rollingSafeCausalOptionSequences == ...
    protocol.rollingSafeCausalOptionReferenceSequence, 2)) == 1);
assert(nnz(all(protocol.rollingSafeCausalOneStepControlSequences == ...
    protocol.rollingSafeCausalOptionReferenceSequence, 2)) == 1);
assert(all(ismember( ...
    protocol.rollingSafeCausalOptionSequences(:), ...
    protocol.rollingSafeSparseTruthFreeActionCodes)));
assert(all(ismember( ...
    protocol.rollingSafeCausalOneStepControlSequences(:), ...
    protocol.rollingSafeSparseTruthFreeActionCodes)));
assert(all(protocol.rollingSafeCausalOptionSequences(:, 1) == ...
    protocol.rollingSafeCausalOptionSequences(:, 2)));
assert(all(protocol.rollingSafeCausalOptionSequences(:, 2) == ...
    protocol.rollingSafeCausalOptionSequences(:, 3)));
assert(all(protocol.rollingSafeCausalOneStepControlSequences(2:end, 2) == 24));
assert(all(protocol.rollingSafeCausalOneStepControlSequences(2:end, 3) == 24));
assert(isequal(protocol.rollingSafeCausalOptionSequences(:, 1), ...
    protocol.rollingSafeCausalOneStepControlSequences(:, 1)));
assert(protocol.rollingSafeCausalOptionMessageBudget == ...
    protocol.expectedNodeCount);
assert(protocol. ...
    rollingSafeCausalOptionRequireNoInitialPolicyReportedRepair);
assert(protocol. ...
    rollingSafeCausalOptionMaximumLaterPolicyReportedRepairExcess == 0);
assert(strcmp(protocol.rollingSafeCausalOptionRepairDiagnosticScope, ...
    'policy-reported-repair-not-universal-proposal-to-selected-rewrite'));
assert(protocol.rollingSafeCausalOptionRequireOneStepReserveAudit);
assert(protocol.rollingSafeCausalOptionRequireRestartEquivalence);
assert(isequal( ...
    protocol.rollingSafeCausalOptionExpectedUnavailableErrorIdentifiers, ...
    {'RollingMatching:Infeasible'}));
assert(protocol.rollingSafeCausalOptionCentralizedCoordinatorAssumed);
assert(~protocol.rollingSafeCausalOptionControlMetadataBytesAccounted);
assert(protocol.rollingSafeCausalOptionMinimumIncrementalVsOneStepPercent == 2);
assert(isequal( ...
    protocol.rollingSafeCausalOptionSentinelSeedTimes, ...
    [11, 78; 19, 78; 23, 78; 27, 78]));
assert(isequal( ...
    protocol.rollingSafeCausalOptionSentinelBehaviors, ...
    {'learned', 'ccw', 'ccw', 'learned'}));

sequence = [61, 63, 77];
for relativeTime = 1:3
    [actionCode, returnedRelativeTime] = ...
        resolveRollingSafeActionSequenceCode( ...
            sequence, 78, 77 + relativeTime, 24);
    assert(actionCode == sequence(relativeTime));
    assert(returnedRelativeTime == relativeTime);
end
[fallbackCode, returnedRelativeTime] = ...
    resolveRollingSafeActionSequenceCode( ...
        sequence, 78, 81, 24);
assert(fallbackCode == 24);
assert(returnedRelativeTime == 4);
assertThrows(@() resolveRollingSafeActionSequenceCode( ...
    [-0.4, 24], 78, 78, 24));
assertThrows(@() resolveRollingSafeActionSequenceCode( ...
    [24.2, 24], 78, 78, 24));
assertThrows(@() resolveRollingSafeActionSequenceCode( ...
    [24, 24], 78.2, 78, 24));
assertThrows(@() resolveRollingSafeActionSequenceCode( ...
    'abc', 78, 78, 24));

assert(isequal(requireFiniteBinaryDiagnostic( ...
    [0, 1, true], 3, 'test'), logical([0, 1, 1])));
assertThrows(@() requireFiniteBinaryDiagnostic( ...
    [0, NaN, 1], 3, 'test'));
assertThrows(@() requireFiniteBinaryDiagnostic( ...
    [0, 2, 1], 3, 'test'));
assertThrows(@() requireFiniteBinaryDiagnostic( ...
    [0, 1], 3, 'test'));
expectedError = struct('identifier', 'RollingMatching:Infeasible');
assert(isExpectedRollingSafeOptionUnavailableError( ...
    expectedError, protocol. ...
        rollingSafeCausalOptionExpectedUnavailableErrorIdentifiers));
unexpectedError = struct( ...
    'identifier', 'RollingSafeCausalOption:TruthUse');
assert(~isExpectedRollingSafeOptionUnavailableError( ...
    unexpectedError, protocol. ...
        rollingSafeCausalOptionExpectedUnavailableErrorIdentifiers));

truthFreeDetails = struct( ...
    'truthUsed', false, ...
    'actionSequenceTruthUsed', false, ...
    'groundTruthUsed', false, ...
    'futureOutcomeUsed', false);
assertTruthFreeRollingSafePolicyDetails(truthFreeDetails);
truthUsedDetails = truthFreeDetails;
truthUsedDetails.truthUsed = true;
assertThrows(@() assertTruthFreeRollingSafePolicyDetails( ...
    truthUsedDetails));
truthNaNDetails = truthFreeDetails;
truthNaNDetails.actionSequenceTruthUsed = NaN;
assertThrows(@() assertTruthFreeRollingSafePolicyDetails( ...
    truthNaNDetails));
missingTruthDetails = rmfield(truthFreeDetails, 'truthUsed');
assertThrows(@() assertTruthFreeRollingSafePolicyDetails( ...
    missingTruthDetails));

pairedPersistent = struct( ...
    'optionSequences', protocol.rollingSafeCausalOptionSequences, ...
    'firstActionGraphSha256', ...
        {repmat({repmat('a', 1, 64)}, 1, 8)}, ...
    'firstActionFusionWeightSha256', ...
        {repmat({repmat('b', 1, 64)}, 1, 8)});
pairedOneStep = struct( ...
    'optionSequences', ...
        protocol.rollingSafeCausalOneStepControlSequences, ...
    'firstActionGraphSha256', ...
        {repmat({repmat('a', 1, 64)}, 1, 8)}, ...
    'firstActionFusionWeightSha256', ...
        {repmat({repmat('b', 1, 64)}, 1, 8)});
assertRollingSafeCausalOptionPairedFirstActions( ...
    pairedPersistent, pairedOneStep);
pairedOneStep.firstActionGraphSha256{3} = 'changed';
assertThrows(@() assertRollingSafeCausalOptionPairedFirstActions( ...
    pairedPersistent, pairedOneStep));
pairedOneStep.firstActionGraphSha256{3} = ...
    pairedPersistent.firstActionGraphSha256{3};
pairedOneStep.firstActionFusionWeightSha256{4} = 'not-a-sha';
assertThrows(@() assertRollingSafeCausalOptionPairedFirstActions( ...
    pairedPersistent, pairedOneStep));

for stateIdx = 1:size( ...
        protocol.rollingSafeCausalOptionSentinelSeedTimes, 1)
    seed = protocol. ...
        rollingSafeCausalOptionSentinelSeedTimes(stateIdx, 1);
    behavior = protocol. ...
        rollingSafeCausalOptionSentinelBehaviors{stateIdx};
    path = fullfile( ...
        protocol.rollingSafeCausalOptionSourceDirectory, ...
        sprintf('label_set_%s_return_source_m24_seed%d_v1.mat', ...
            behavior, seed));
    assert(exist(path, 'file') == 2);
    loaded = load(path, 'dataset');
    source = loaded.dataset;
    assert(strcmp(source.protocolId, protocol.id));
    assert(strcmp(source.contractVersion, ...
        protocol.macroActionBehaviorSourceContractVersion));
    assert(strcmp(source.behaviorAction, protocol. ...
        rollingSafeCausalOptionSentinelBehaviorActions{stateIdx}));
    assert(any(source.sourceTimes == 78));
    assert(source.restartReferenceHashesStored);
    assert(~source.featuresUseTruth);
    assert(~source.featuresUseFutureOutcome);
    assert(strcmp(source.presetName, protocol.presetName));
    assert(source.horizonSteps == protocol.returnValueGateHorizon);
    assert(source.behaviorTruthUseCount == 0);
    assert(source.behaviorRepairCount == 0);
    assert(source.behaviorPayloadEmergencyCount == 0);
    assert(source.behaviorInfeasibleCount == 0);
    block = source.blocks([source.blocks.currentTime] == 78);
    assert(numel(block) == 1);
    assert(block.seed == seed);
    assert(strcmp(block.behaviorAction, source.behaviorAction));
    assert(isequal(block.restartReferenceTrace.times, [78, 79, 80]));
    assertDynamicTopologyRestartTraceEqual( ...
        block.restartReferenceTrace, block.restartReferenceTrace);
    changedTrace = block.restartReferenceTrace;
    changedTrace.overallSha256(1) = alternateHex( ...
        changedTrace.overallSha256(1));
    assertThrows(@() assertDynamicTopologyRestartTraceEqual( ...
        block.restartReferenceTrace, changedTrace));
end
assert(exist(protocol.messagePassingInitializationPath, 'file') == 2);
assert(strcmp(computeFileSha256( ...
    protocol.messagePassingInitializationPath), ...
    protocol.messagePassingInitializationSha256));
x = 1; %#ok<NASGU>
savePath = [tempname(), '.mat'];
cleanup = onCleanup(@() deleteIfPresent(savePath)); %#ok<NASGU>
save(savePath, 'x', '-v7');
saved = load(savePath, 'x');
assert(saved.x == 1);
assert(exist('runRollingSafeCausalOptionPreflightM24', 'file') == 2);
assert(exist('summarizeRollingSafeCausalOptionSentinelM24', 'file') == 2);

fprintf('test_rolling_safe_causal_option_protocol passed\n');
end

function assertThrows(action)
threw = false;
try
    action();
catch
    threw = true;
end
assert(threw);
end

function value = alternateHex(value)
if value == '0'
    value = '1';
else
    value = '0';
end
end

function deleteIfPresent(path)
if exist(path, 'file') == 2
    delete(path);
end
end
