function test_formation_backbone_bundle_m24_source_permit()
% TEST_FORMATIONBACKBONEBUNDLEM24SOURCEPERMIT Fail-closed source gate.

protocol = getFormationBackboneBundleM24DevelopmentProtocol();
assert(strcmp(protocol.id, ...
    'formation-backbone-bundle-m24-development-v1'));
assert(strcmp(protocol.canonicalSha256, ...
    '12da780f33a40b8df9a6964eec3f2c4e6145f14078cdcbb1dea9ff309bdb67e3'));
assert(strcmp(protocol.methodSourceCommit, ...
    '5de0aa61a271b6999e8723af3b7378d8c7fd2aa0'));
assert(strcmp(protocol.methodPolicyConfigSha256, ...
    '6c7d049e5169944b6bee0206d790fce224e87e7bd6090ffcad483eb49b07e247'));
assert(protocol.caseCount == 15);
assert(protocol.sourcePermitCount == 15);
assert(isequal(protocol.seeds, [41, 43, 47, 53, 59]));
assert(protocol.filterSeedOffset == 100000);
assert(~protocol.sourcePosteriorAuthorized);
assert(~protocol.sourceStateEstimateOutputAuthorized);
assert(~protocol.executableSourceFrozen);
assert(isempty(protocol.executableSourceCommit));
assert(isempty(protocol.executableSourceManifestSha256));
assert(~protocol.sourceInputFingerprintsFrozen);
assert(~protocol.candidateContinuationAuthorized);
assert(~protocol.pairedTrackingAuthorized);
assert(~protocol.trackingOutcomeScoringAuthorized);
assert(~protocol.groundTruthAccessAuthorized);
assert(~protocol.futureOutcomeAccessAuthorized);
assert(~protocol.validationClaimAllowed);
assert(protocol.developmentEvidenceOnly);
assert(isequal({protocol.scenes.presetName}, { ...
    'm24-formation-fov', ...
    'm24-formation-fov-convoy', ...
    'm24-formation-fov-relay'}));
assert(isequal(vertcat(protocol.scenes.focusWindow), [ ...
    55, 135; 45, 140; 45, 140]));
assert(isequal(vertcat(protocol.scenes.sourceWindow), [ ...
    1, 135; 1, 140; 1, 140]));
assert(isequal({protocol.scenes.configSnapshotSha256}, { ...
    '2c25ad410e645ebbe6ef3b52211a5a52ac99d3438fd9e03653db6f17e152b512', ...
    'ee6244a8baf0fe3b7a7ac34715a10f71c61428a2da942939d834eef2b16685b2', ...
    '902fd9a6b90d1d5eba64512ff4b815dc9a08cba40be1a7f2b3821950eba306de'}));
assert(isequal({protocol.scenes.sceneContractSha256}, { ...
    protocol.scenes(1).configSnapshotSha256, ...
    '666def7dbed41c47b9f29e536a369ef24a52077059429e45e5a41852e4071726', ...
    '49005834d31fcc6c729d546e725e79be7ae1c5b542209ea599a944187a31f2a0'}));
assert(isequal({protocol.scenes.sourceTriggerFingerprintSha256}, { ...
    '10414143efb0ada391ac0a5a71a82ae87e50595abb35625b5dab86a325681a1c', ...
    'e95071e69193fa38004cf1c96f73a66770489e7d2e55f150395aafe48a92bc62', ...
    '708c3a9196e8cd8461c205759828e25d32abd1e501dbe609a2afa71b34947f8e'}));

for caseIdx = 1:numel(protocol.cases)
    caseContract = protocol.cases(caseIdx);
    assert(caseContract.ordinal == caseIdx);
    [model, request, context] = buildValidFixture(caseContract);
    permit = getFormationBackboneBundleM24SourceCasePermit( ...
        caseContract.presetName, caseContract.seed);
    loaded = loadFormationBackboneBundleM24SourceCasePermit(permit.id);
    assert(isequaln(loaded, permit));
    assert(strcmp(context.permitCanonicalSha256, ...
        permit.permitCanonicalSha256));
    assert(~permit.stateEstimateOutputAuthorized);
    assert(isempty(permit.sourceInputFingerprint.canonicalSha256));
    assertErrorId(@() ...
        validateFormationBackboneBundleM24SourceExecution( ...
            model, context, request), ...
        'FormationBundleSourcePermit:SourceFreezePending');
end

testPendingPermitMutationRejection(protocol);
testExactInputFingerprintSensitivity();
testTruthRemoval(protocol.cases(6));
testPublicFilterContextPropagation(protocol.cases(1));
testSceneMetadataAndLegacyBoundaries(protocol.cases(6));
testUnknownRegistryEntries();
testSourceOutputBoundary();
testCriticalRuntimePathsLocked();
testSourceRunnerRemainsSealed();
testPendingCacheBuilderRejected(protocol);
fprintf('PASS: formation-backbone M24 source-permit tests\n');
end

function testPendingPermitMutationRejection(protocol)
caseContract = protocol.cases(6);
[model, request, context] = buildValidFixture(caseContract);

changed = context;
changed.permitCanonicalSha256 = repmat('0', 1, 64);
assertErrorId(@() validateFormationBackboneBundleM24SourceExecution( ...
    model, changed, request), ...
    'FormationBundleSourcePermit:ExecutionContextDrift');

changed = context;
changed.armId = protocol.futureOrderedArmIds{2};
assertErrorId(@() validateFormationBackboneBundleM24SourceExecution( ...
    model, changed, request), ...
    'FormationBundleSourcePermit:ExecutionContextDrift');

changed = context;
changed.action = 'filter-paired-tracking';
assertErrorId(@() assertDynamicTopologyTrackingOutcomeAuthorized( ...
    model, changed, request), ...
    'FormationBundleSourcePermit:PairedTrackingSealed');

changed = context;
changed.capability = 'paired-tracking';
assertErrorId(@() assertDynamicTopologyTrackingOutcomeAuthorized( ...
    model, changed, request), ...
    'FormationBundleSourcePermit:PairedTrackingSealed');

changedRequest = request;
changedRequest.measurementTimeCount = ...
    changedRequest.measurementTimeCount - 1;
assertErrorId(@() validateFormationBackboneBundleM24SourceExecution( ...
    model, context, changedRequest), ...
    'FormationBundleSourcePermit:SourceFreezePending');
end

function testExactInputFingerprintSensitivity()
model = struct('numberOfSensors', 24, 'tag', 'registered');
measurements = repmat({{}}, 24, 3);
trajectories = repmat({zeros(4, 3)}, 1, 24);
neighborMap = repmat({1:24}, 1, 24);
commConfig = struct('pDropByEdge', zeros(24, 24, 3), ...
    'linkUniforms', 0.5 * ones(24, 24, 3));
reference = computeFormationBackboneBundleM24SourceInputFingerprint( ...
    model, measurements, trajectories, neighborMap, commConfig);

changedMeasurements = measurements;
changedMeasurements{1, 1} = {ones(2, 1)};
assertFingerprintChanges(reference, model, changedMeasurements, ...
    trajectories, neighborMap, commConfig);
changedTrajectories = trajectories;
changedTrajectories{1}(1, 1) = 999;
assertFingerprintChanges(reference, model, measurements, ...
    changedTrajectories, neighborMap, commConfig);
changedNeighborMap = neighborMap;
changedNeighborMap{1}(end) = [];
assertFingerprintChanges(reference, model, measurements, ...
    trajectories, changedNeighborMap, commConfig);
changedCommConfig = commConfig;
changedCommConfig.linkUniforms(1, 2, 1) = 0.25;
assertFingerprintChanges(reference, model, measurements, ...
    trajectories, neighborMap, changedCommConfig);
changedModel = model;
changedModel.tag = 'drifted';
assertFingerprintChanges(reference, changedModel, measurements, ...
    trajectories, neighborMap, commConfig);
end

function assertFingerprintChanges(reference, model, measurements, ...
        trajectories, neighborMap, commConfig)
changed = computeFormationBackboneBundleM24SourceInputFingerprint( ...
    model, measurements, trajectories, neighborMap, commConfig);
assert(~strcmp(changed.canonicalSha256, reference.canonicalSha256));
end

function testTruthRemoval(caseContract)
[model, request, context] = buildValidFixture(caseContract);
model.explicitTargetTrajectories = {ones(4, request.measurementTimeCount)};
model.targetTrajectories = model.explicitTargetTrajectories;
model.groundTruth = model.explicitTargetTrajectories;
model.groundTruthRfs = struct('cardinality', ones(1, 2));
model.dynamicTopologyScenario.targetTrajectories = ...
    model.explicitTargetTrajectories;
model.dynamicTopologyScenario.trackingTruth = ...
    model.explicitTargetTrajectories;
stripped = stripDynamicTopologyTargetTruthForSource(model);
assert(~isfield(stripped, 'explicitTargetTrajectories'));
assert(~isfield(stripped, 'targetTrajectories'));
assert(~isfield(stripped, 'groundTruth'));
assert(~isfield(stripped, 'groundTruthRfs'));
assert(~isfield(stripped.dynamicTopologyScenario, ...
    'targetTrajectories'));
assert(~isfield(stripped.dynamicTopologyScenario, 'trackingTruth'));
assertErrorId(@() validateFormationBackboneBundleM24SourceExecution( ...
    stripped, context, request), ...
    'FormationBundleSourcePermit:SourceFreezePending');
end

function testPublicFilterContextPropagation(caseContract)
[model, request, context] = buildValidFixture(caseContract);
context.permitCanonicalSha256 = repmat('f', 1, 64);
measurements = cell(24, request.measurementTimeCount);
sensorTrajectories = model.sensorTrajectories;
neighborMap = repmat({1:24}, 1, 24);
commConfig = struct();
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, request.triggerConfig, context), ...
    'FormationBundleSourcePermit:ExecutionContextDrift');
end

function testSceneMetadataAndLegacyBoundaries(caseContract)
[model, ~, ~] = buildValidFixture(caseContract);
assertErrorId(@() ...
    assertDynamicTopologyTrackingOutcomeAuthorized(model), ...
    'DynamicTopology:TrackingOutcomeNotAuthorized');

stripped = rmfield(model, { ...
    'dynamicTopologyScenario', ...
    'dynamicTopologyTrackingOutcomeGate'});
assertErrorId(@() ...
    assertDynamicTopologyTrackingOutcomeAuthorized(stripped), ...
    'DynamicTopology:IncompleteScenarioMetadata');

legacy = struct('numberOfSensors', 2);
authorization = ...
    assertDynamicTopologyTrackingOutcomeAuthorized(legacy);
assert(strcmp(authorization.mode, 'legacy-compatible'));

legacy.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', [1, 2]));
authorization = ...
    assertDynamicTopologyTrackingOutcomeAuthorized(legacy);
assert(strcmp(authorization.mode, 'legacy-compatible'));
end

function testUnknownRegistryEntries()
assertErrorId(@() ...
    getFormationBackboneBundleM24SourceCasePermit( ...
        'm24-formation-fov-crossing', 41), ...
    'FormationBundleSourcePermit:UnknownCase');
assertErrorId(@() ...
    getFormationBackboneBundleM24SourceCasePermit( ...
        'm24-formation-fov', 42), ...
    'FormationBundleSourcePermit:UnknownCase');
assertErrorId(@() ...
    loadFormationBackboneBundleM24SourceCasePermit( ...
        'unregistered-permit'), ...
    'FormationBundleSourcePermit:UnknownPermit');
assertErrorId(@() ...
    buildFormationBackboneBundleM24SourceTriggerConfig( ...
        'm24-formation-fov-crossing'), ...
    'FormationBundleSourcePermit:UnknownPreset');
end

function testCriticalRuntimePathsLocked()
resolution = ...
    assertFormationBackboneBundleM24CriticalFunctionPaths();
requiredNames = { ...
    'applyFormationBackboneBundleM24SourceOutputBoundary', ...
    'buildObservableTopologyPolicyContext', ...
    'selectRegisteredDirectedRoutingPolicy', ...
    'buildBackbonePreservingResidualRoute'};
assert(all(ismember(requiredNames, resolution.functionNames)));
end

function testSourceOutputBoundary()
estimates = {struct('objects', 1), struct('objects', 2)};
diagnostics = struct('marker', 7);
sourceAuthorization = struct( ...
    'mode', 'registered-case-permit', ...
    'capability', 'source-posterior-only', ...
    'stateEstimateOutputAuthorized', false);
[boundedEstimates, boundedDiagnostics] = ...
    applyFormationBackboneBundleM24SourceOutputBoundary( ...
        estimates, diagnostics, sourceAuthorization);
assert(isempty(boundedEstimates));
assert(boundedDiagnostics.marker == 7);
assert(boundedDiagnostics.sourceStateEstimateOutputSuppressed);

legacyAuthorization = struct( ...
    'mode', 'legacy-compatible', ...
    'stateEstimateOutputAuthorized', true);
[legacyEstimates, legacyDiagnostics] = ...
    applyFormationBackboneBundleM24SourceOutputBoundary( ...
        estimates, diagnostics, legacyAuthorization);
assert(isequaln(legacyEstimates, estimates));
assert(~legacyDiagnostics.sourceStateEstimateOutputSuppressed);

sceneAuthorization = struct( ...
    'mode', 'registered-scene-outcome', ...
    'capability', 'tracking-outcome-authorized', ...
    'stateEstimateOutputAuthorized', true);
[sceneEstimates, sceneDiagnostics] = ...
    applyFormationBackboneBundleM24SourceOutputBoundary( ...
        estimates, diagnostics, sceneAuthorization);
assert(isequaln(sceneEstimates, estimates));
assert(~sceneDiagnostics.sourceStateEstimateOutputSuppressed);

expanded = sourceAuthorization;
expanded.stateEstimateOutputAuthorized = true;
assertErrorId(@() ...
    applyFormationBackboneBundleM24SourceOutputBoundary( ...
        estimates, diagnostics, expanded), ...
    'FormationBundleSourcePermit:OutputBoundaryDrift');
end

function testSourceRunnerRemainsSealed()
probePath = fullfile(tempdir(), ...
    'formation_bundle_m24_source_sealed_test');
if exist(probePath, 'dir') ~= 0
    rmdir(probePath, 's');
end
assertErrorId(@() ...
    runFormationBackboneBundleM24SourcePosteriorPreflight( ...
        probePath), ...
    'FormationBundleSourcePreflight:ProtocolNotFrozen');
assert(exist(probePath, 'dir') == 0);
end

function testPendingCacheBuilderRejected(protocol)
permit = getFormationBackboneBundleM24SourceCasePermit( ...
    protocol.cases(1).presetName, protocol.cases(1).seed);
fabricatedAuthorization = struct( ...
    'permitCanonicalSha256', permit.permitCanonicalSha256, ...
    'trackingOutcomeScoringAuthorized', false, ...
    'groundTruthAccessAuthorized', false, ...
    'futureOutcomeAccessAuthorized', false, ...
    'validationClaimAllowed', false);
fabricatedDiagnostics = struct( ...
    'dynamicTopologyExecutionAuthorization', ...
        fabricatedAuthorization);
fabricatedSource = struct( ...
    'caseId', permit.caseId, ...
    'inputFingerprint', permit.sourceInputFingerprint);
assertErrorId(@() buildFormationBackboneBundleM24SourceCache( ...
    protocol, permit, fabricatedSource, fabricatedDiagnostics), ...
    'FormationBundleSourceCache:SourceFreezePending');
end

function [model, request, context] = buildValidFixture(caseContract)
config = buildDynamicTopologyScenarioConfig(caseContract.presetName);
timeCount = caseContract.sourceWindow(2);
trajectories = cell(1, 24);
for sensorIdx = 1:24
    trajectories{sensorIdx} = zeros(4, timeCount);
end
scenario = struct( ...
    'presetName', caseContract.presetName, ...
    'seed', caseContract.seed, ...
    'config', config);
model = struct( ...
    'numberOfSensors', 24, ...
    'explicitSensorTrajectories', {trajectories}, ...
    'sensorTrajectories', {trajectories}, ...
    'dynamicTopologyScenario', scenario);
if strcmp(caseContract.sceneContractKind, ...
        'formation-fov-multistyle-scene-contract-v5')
    model.dynamicTopologyTrackingOutcomeGate = struct( ...
        'contractVersion', ...
            'dynamic-topology-tracking-outcome-gate-v1', ...
        'required', true, ...
        'sceneContractSha256', caseContract.sceneContractSha256);
end
[triggerConfig, ~] = ...
    buildFormationBackboneBundleM24SourceTriggerConfig( ...
        caseContract.presetName);
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', timeCount, ...
    'sensorTrajectoryTimeCounts', ...
        timeCount * ones(1, 24), ...
    'triggerConfig', triggerConfig, ...
    'inputFingerprint', ...
        computeFormationBackboneBundleM24SourceInputFingerprint( ...
            model, cell(24, timeCount), trajectories, ...
            repmat({1:24}, 1, 24), struct()));
context = ...
    buildFormationBackboneBundleM24SourceExecutionContext( ...
        caseContract.presetName, caseContract.seed);
end

function assertErrorId(callback, expectedIdentifier)
failed = false;
try
    callback();
catch errorInfo
    failed = strcmp(errorInfo.identifier, expectedIdentifier);
end
assert(failed, 'Expected error identifier: %s.', expectedIdentifier);
end
