function test_direct_graph_formation_learning_snapshot_v218()
% TEST_DIRECT_GRAPH_FORMATION_LEARNING_SNAPSHOT_V218 Scale-safe graph export.

groups = [1, 1, 2, 2];
adjacency = false(4);
adjacency(1, 3) = true;
adjacency(2, 4) = true;
adjacency(3, 1) = true;
weights = zeros(4);
weights(1, 3) = 0.2;
weights(2, 4) = 0.4;
weights(3, 1) = 0.6;
details = struct( ...
    'hierarchicalFormationIds', [1, 2], ...
    'hierarchicalWithholdingFeatureContractVersion', 'test-v1', ...
    'hierarchicalWithholdingFeatureNames', {{'a', 'b'}}, ...
    'hierarchicalWithholdingFeaturesByFormation', [1, 2; 3, 4], ...
    'hierarchicalWithholdingPayloadFeatureNames', {{'p'}}, ...
    'hierarchicalWithholdingPayloadFeaturesByFormation', [5; 6], ...
    'hierarchicalWithholdingTruthUsed', false, ...
    'hierarchicalWithholdingFutureInformationUsed', false);
snapshot = buildDirectGraphFormationLearningSnapshotV218( ...
    groups, adjacency, weights, details);
assert(isequal(snapshot.receiverRowSenderColumnAdjacency, ...
    logical([0, 1; 1, 0])));
assert(abs(snapshot.edgeFeatures(1, 2, 1) - 0.5) < 1e-12);
assert(abs(snapshot.edgeFeatures(1, 2, 2) - 0.3) < 1e-12);
assert(abs(snapshot.edgeFeatures(1, 2, 3) - 0.3) < 1e-12);
assert(~snapshot.numericFormationIdentifiersUsedAsFeatures);
fprintf('test_direct_graph_formation_learning_snapshot_v218 passed\n');
end
