function test_dynamic_topology_scenarios()
% TEST_DYNAMIC_TOPOLOGY_SCENARIOS Scenario, safety and KLA reference tests.

testScenarioPresets();
testTeacherSceneDifficultyGates();
testExplicitSensorHeadingGate();
testScalableTopologyCandidatePools();
testTopologyTaskRiskOrdering();
testTeacherLabelExcludesSwitchPenalty();
testContinuationFromLocalPosteriorSnapshot();
testConstraintAwareScreenDecision();
testResidualRoutingBackboneGate();
testContinuationCacheRejectsConfigDrift();
testScheduledBirths();
testTimeVaryingDropAccounting();
testDirectedTopologyExecution();
testDirectedRoutingFeaturesIgnoreTruth();
testKlaCompatibilityOrdering();
testDirectedTeacherDeliveryExpectation();
testDirectedRoutingModelArtifact();
testResidualRoutingModelArtifact();
testAnalyticDirectedRoutingPolicy();
testRegisteredDirectedRoutingControls();
testFormationGatewayRoutingPolicies();
testReliabilityControlIsFixedIndexOnScaledScenarios();
testFixedIndexClosedLoopClone();
testReliabilityQualityRoutingRespondsToPosterior();
testRouteAttributionDiagnostics();
testScaleInvariantActionFeaturesIgnoreTruth();
testConfidenceGatedResidualFallback();
testTopologyScheduleFusion();
testInfeasiblePhysicalGraphFailsClosed();
testMixtureAwareReferenceBoundary();
testD12OracleCallbackSmoke();
fprintf('test_dynamic_topology_scenarios passed\n');
end

function testScenarioPresets()
names = {'r8-legacy', 'd12-handover', ...
    'm24-handover', 'm24-link', 'm24-composite', ...
    'x36-topology', 'x36-joint', 'x36-matched', ...
    'x36-clean-scale', ...
    'd12-hard', 'm24-hard', 'x36-hard'};
expectedSensors = [ ...
    8, 12, 24, 24, 24, 36, 36, 36, 36, 12, 24, 36];
for presetIdx = 1:numel(names)
    rng(7);
    config = buildDynamicTopologyScenarioConfig(names{presetIdx});
    [sensors, ~] = generateMultiFormationTrajectories(config);
    [targets, ~] = generateCorridorTargetTrajectories(config);
    graphs = buildDynamicTopologyGraphs(config, sensors);
    validation = validateDynamicTopologyScenario( ...
        config, sensors, targets, graphs);
    assert(validation.isValid);
    assert(config.numberOfSensors == expectedSensors(presetIdx));
    assert(validation.staticEdgeCount <= config.edgeBudget);
    assert(validation.staticPhysicalViolationCount == 0);
end

rng(7);
config = buildDynamicTopologyScenarioConfig('d12-handover');
[sensors, ~] = generateMultiFormationTrajectories(config);
graphs = buildDynamicTopologyGraphs(config, sensors);
assert(size(graphs.candidateAdjacency, 3) == 48);
for candidateIdx = 1:size(graphs.candidateAdjacency, 3)
    assert(nnz(triu( ...
        graphs.candidateAdjacency(:, :, candidateIdx), 1)) == 14);
end
end

function testTeacherSceneDifficultyGates()
names = { ...
    'd12-hard', 'm24-hard', 'x36-matched', ...
    'x36-clean-scale', 'x36-hard'};
for presetIdx = 1:numel(names)
    rng(17);
    config = buildDynamicTopologyScenarioConfig(names{presetIdx});
    [sensors, ~] = generateMultiFormationTrajectories(config);
    [targets, ~] = generateCorridorTargetTrajectories(config);
    graphs = buildDynamicTopologyGraphs(config, sensors);
    validation = validateDynamicTopologyScenario( ...
        config, sensors, targets, graphs);
    difficulty = validation.difficulty;
    requirements = config.difficultyRequirements;
    assert(difficulty.blackoutFraction <= ...
        requirements.maxBlackoutFraction + 1e-12);
    assert(difficulty.singleFormationFraction >= ...
        requirements.minSingleFormationFraction - 1e-12);
    assert(difficulty.multiFormationFraction >= ...
        requirements.minMultiFormationFraction - 1e-12);
    assert(difficulty.focusHandovers >= ...
        requirements.minFocusHandovers);
    assert(difficulty.focusCloseEncounterTimeFraction >= ...
        requirements.minCrossGroupCloseEncounterFraction - 1e-12);
    assert(difficulty.formationOwnershipEntropy >= ...
        requirements.minFormationOwnershipEntropy - 1e-12);
    assert(difficulty.blockageFocusOverlapFraction >= ...
        requirements.minBlockageFocusOverlapFraction - 1e-12);
end

rng(17);
config = buildDynamicTopologyScenarioConfig( ...
    'd12-hard', struct('fovRange', 40));
[sensors, ~] = generateMultiFormationTrajectories(config);
[targets, ~] = generateCorridorTargetTrajectories(config);
graphs = buildDynamicTopologyGraphs(config, sensors);
failedClosed = false;
try
    validateDynamicTopologyScenario(config, sensors, targets, graphs);
catch errorInfo
    failedClosed = ~isempty(strfind( ...
        errorInfo.message, 'difficulty-blackout')); %#ok<STREMP>
end
assert(failedClosed);
end

function testExplicitSensorHeadingGate()
model = struct();
model.detectionProbability = 0.9;
model.Q = {eye(2)};
model.sensorTrajectories = {zeros(4, 1)};
model.sensorMotionEnabled = true;
model.sensorFovEnabled = true;
model.sensorFovHalfAngleDeg = 30;
model.sensorFovRange = 100;
model.sensorFovHeadingRad = 0;

[forwardPd, ~, forwardInfo] = evaluateSensorQuality( ...
    model, 1, [50; 0; 0; 0], 1);
[sidePd, ~, sideInfo] = evaluateSensorQuality( ...
    model, 1, [0; 50; 0; 0], 1);
assert(forwardPd > 0 && forwardInfo.inFov);
assert(sidePd == 0 && ~sideInfo.inFov);

model.sensorFovHeadingRad = pi / 2;
[rotatedPd, ~, rotatedInfo] = evaluateSensorQuality( ...
    model, 1, [0; 50; 0; 0], 1);
assert(rotatedPd > 0 && rotatedInfo.inFov);
end

function testScalableTopologyCandidatePools()
names = { ...
    'm24-hard', 'x36-matched', 'x36-clean-scale', 'x36-hard'};
for presetIdx = 1:numel(names)
    rng(23);
    config = buildDynamicTopologyScenarioConfig(names{presetIdx});
    [sensors, ~] = generateMultiFormationTrajectories(config);
    graphs = buildDynamicTopologyGraphs(config, sensors);
    context = makeCandidatePoolContext(config, sensors, graphs);
    [candidates, metadata] = ...
        buildDynamicTopologyCandidatePool(context);
    assert(strcmp(metadata.source, 'projected-general'));
    assert(size(candidates, 3) >= 5);
    sameGroup = bsxfun(@eq, ...
        config.sensorGroupIds(:), config.sensorGroupIds(:)');
    for candidateIdx = 1:size(candidates, 3)
        candidate = candidates(:, :, candidateIdx);
        assert(nnz(triu(candidate, 1)) == config.edgeBudget);
        assert(max(sum(candidate, 2)) <= config.maxNodeDegree);
        assert(max(sum(candidate & ~sameGroup, 2)) <= ...
            config.maxInterFormationDegree);
        assert(isConnectedTest(candidate));
    end
    context.previousAdjacency = graphs.staticAdjacency;
    [localCandidates, ~] = ...
        buildDynamicTopologyCandidatePool(context);
    removable = zeros(1, size(localCandidates, 3));
    for candidateIdx = 1:size(localCandidates, 3)
        removable(candidateIdx) = nnz(triu( ...
            context.previousAdjacency & ...
            ~localCandidates(:, :, candidateIdx), 1));
    end
    assert(sum(removable <= ...
        config.maxEdgeReplacementsPerStep) >= 5);
    for policyMode = {'reliability', 'discrepancy'}
        [policyAdjacency, policyDetails] = ...
            selectProjectedTopologyPolicy( ...
                context, policyMode{1});
        assert(policyDetails.validCandidateCount >= 1);
        assert(nnz(triu(policyAdjacency, 1)) == ...
            config.edgeBudget);
        assert(isConnectedTest(policyAdjacency));
    end
end
end

function testTopologyTaskRiskOrdering()
model = generateMultisensorModel( ...
    1, 0, 0.9, 3, 'GA', 'LBP');
model.birthTimeByLocation = 1;
model.dynamicTopologyScenario = struct( ...
    'config', struct( ...
        'targetSpeedLimit', 15, ...
        'ospaPositionCutoff', 100), ...
    'targetTrajectories', {{[zeros(4, 1), zeros(4, 1)]}});
good = makeObject(model, 1, 1, 0.95, ...
    [1; 0; 0; 0], eye(4));
poor = makeObject(model, 1, 1, 0.45, ...
    [80; 60; 8; -8], 100 * eye(4));
goodRisk = evaluateLmbTopologyTaskRisk( ...
    good, model, 1, struct('horizonSteps', 0));
poorRisk = evaluateLmbTopologyTaskRisk( ...
    poor, model, 1, struct('horizonSteps', 0));
assert(goodRisk < poorRisk);
meanRisk = evaluateLmbTopologyTaskRisk( ...
    {good, poor}, model, 1, struct( ...
        'horizonSteps', 0, ...
        'sensorAggregationMode', 'mean'));
riskSensitive = evaluateLmbTopologyTaskRisk( ...
    {good, poor}, model, 1, struct( ...
        'horizonSteps', 0, ...
        'sensorAggregationMode', 'mean-cvar', ...
        'sensorCvarFraction', 0.5, ...
        'sensorCvarWeight', 0.5));
assert(riskSensitive > meanRisk);
end

function testTeacherLabelExcludesSwitchPenalty()
inputs = generateDynamicTopologyScenarioInputs('d12-hard', 19);
timeIdx = 50;
sensorCount = inputs.config.numberOfSensors;
truth = inputs.targetTrajectories{1}(:, timeIdx);
posteriors = cell(1, sensorCount);
for sensorIdx = 1:sensorCount
    shift = [0; 0; 0; 0];
    if mod(sensorIdx, 3) == 0
        shift = [90; -50; 4; -2];
    end
    posteriors{sensorIdx} = makeObject( ...
        inputs.model, ...
        inputs.model.birthTimeByLocation(1), 1, ...
        0.85 - 0.1 * mod(sensorIdx, 2), ...
        truth + shift, (4 + sensorIdx) * eye(4));
end
context = struct();
context.localPosteriorBySensor = posteriors;
context.model = inputs.model;
context.commConfig = inputs.commConfig;
context.currentTime = timeIdx;
context.previousAdjacency = inputs.graphData.staticAdjacency;
context.baseAdjacency = inputs.graphData.staticAdjacency;
context.physicalAdjacency = ...
    inputs.graphData.physicalAdjacency(:, :, timeIdx);
context.edgeScores = double(context.physicalAdjacency);
context.edgeBudget = inputs.config.edgeBudget;
context.positions = zeros(2, sensorCount);
for sensorIdx = 1:sensorCount
    context.positions(:, sensorIdx) = ...
        inputs.sensorTrajectories{sensorIdx}(1:2, timeIdx);
end

zeroPenalty = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyTeacherSwitchPenaltyWeight', 0));
context.triggerConfig = zeroPenalty;
[~, zeroDetails] = ...
    selectCounterfactualTopologyTeacher(context, 'current');
highPenalty = zeroPenalty;
highPenalty.topologyTeacherSwitchPenaltyWeight = 10;
context.triggerConfig = highPenalty;
[~, highDetails] = ...
    selectCounterfactualTopologyTeacher(context, 'current');
finite = isfinite(zeroDetails.candidateTaskRisks) & ...
    isfinite(highDetails.candidateTaskRisks);
assert(any(finite));
assert(max(abs( ...
    zeroDetails.candidateTaskRisks(finite) - ...
    highDetails.candidateTaskRisks(finite))) < 1e-12);
assert(~zeroDetails.labelIncludesSwitchPenalty);
assert(~highDetails.labelIncludesSwitchPenalty);
assert(zeroDetails.taskRiskSpread > 0);

balancedConfig = zeroPenalty;
balancedConfig.topologyTeacherRiskOptions = struct( ...
    'sensorAggregationMode', 'mean-cvar', ...
    'sensorCvarFraction', 0.25, ...
    'sensorCvarWeight', 0.5);
context.triggerConfig = balancedConfig;
[~, balancedDetails] = ...
    selectCounterfactualTopologyTeacher(context, 'current');
balancedFinite = isfinite(balancedDetails.candidateTaskRisks);
assert(any(balancedFinite));
for candidateIdx = find(balancedFinite)
    nodeRisk = balancedDetails.candidateNodeTaskRisks( ...
        candidateIdx, :);
    nodeRisk = nodeRisk(isfinite(nodeRisk));
    tailCount = max(1, ceil(0.25 * numel(nodeRisk)));
    sortedRisk = sort(nodeRisk, 'descend');
    expectedRisk = 0.5 * mean(nodeRisk) + ...
        0.5 * mean(sortedRisk(1:tailCount));
    assert(abs(expectedRisk - ...
        balancedDetails.candidateTaskRisks(candidateIdx)) < 1e-12);
end
sharedFinite = balancedFinite & ...
    isfinite(zeroDetails.candidateTaskRisks);
assert(any(abs( ...
    balancedDetails.candidateTaskRisks(sharedFinite) - ...
    zeroDetails.candidateTaskRisks(sharedFinite)) > 1e-8));

registered = inputs.graphData.candidateAdjacency;
removedFromBase = zeros(1, size(registered, 3));
for candidateIdx = 1:size(registered, 3)
    removedFromBase(candidateIdx) = nnz(triu( ...
        inputs.graphData.staticAdjacency & ...
        ~registered(:, :, candidateIdx), 1));
end
[maximumRemoved, farCandidateIdx] = max(removedFromBase);
assert(maximumRemoved > ...
    inputs.config.maxEdgeReplacementsPerStep);
context.previousAdjacency = registered(:, :, farCandidateIdx);
context.triggerConfig = zeroPenalty;
[~, farDetails] = ...
    selectCounterfactualTopologyTeacher(context, 'current');
assert(isfinite(farDetails.baselineTaskRisk));
assert(~farDetails.selectionValidCandidates( ...
    farDetails.baselineCandidateIndex));
allCandidateConfig = zeroPenalty;
allCandidateConfig.topologyTeacherEvaluateAllCandidates = true;
context.triggerConfig = allCandidateConfig;
[~, allCandidateDetails] = ...
    selectCounterfactualTopologyTeacher(context, 'current');
assert(allCandidateDetails.candidateIndex == ...
    farDetails.candidateIndex);
evaluatedByDefault = isfinite(farDetails.candidateTaskRisks);
assert(max(abs( ...
    farDetails.candidateTaskRisks(evaluatedByDefault) - ...
    allCandidateDetails.candidateTaskRisks(evaluatedByDefault))) < 1e-12);
assert(sum(isfinite(allCandidateDetails.candidateTaskRisks)) > ...
    sum(evaluatedByDefault));

context.previousAdjacency = inputs.graphData.staticAdjacency;
zeroPenalty.topologyTeacherClosedLoopHorizonSteps = 1;
context.triggerConfig = zeroPenalty;
rolloutData = struct( ...
    'measurements', {inputs.measurements}, ...
    'continuationAdjacency', inputs.graphData.staticAdjacency);
[~, zeroClosedDetails] = ...
    selectClosedLoopCounterfactualTopologyTeacher( ...
        context, rolloutData);
highPenalty = zeroPenalty;
highPenalty.topologyTeacherSwitchPenaltyWeight = 10;
context.triggerConfig = highPenalty;
[~, highClosedDetails] = ...
    selectClosedLoopCounterfactualTopologyTeacher( ...
        context, rolloutData);
finiteClosed = isfinite(zeroClosedDetails.candidateTaskRisks) & ...
    isfinite(highClosedDetails.candidateTaskRisks);
assert(any(finiteClosed));
assert(max(abs( ...
    zeroClosedDetails.candidateTaskRisks(finiteClosed) - ...
    highClosedDetails.candidateTaskRisks(finiteClosed))) < 1e-12);
assert(zeroClosedDetails.usesFutureMeasurements);
assert(~zeroClosedDetails.labelIncludesSwitchPenalty);
end

function testContinuationFromLocalPosteriorSnapshot()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
for birthIdx = 1:numel(model.birthParameters)
    model.birthParameters(birthIdx).r = 0.9;
end
measurements = repmat({{}}, 2, 3);
neighborMap = {[1, 2], [1, 2]};
commConfig = struct( ...
    'forceDelivery', true, ...
    'pDropBySensor', [0, 0]);
fullConfig = struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false, ...
    'topologyPosteriorCaptureTimes', 2);
[fullEstimates, fullDiagnostics] = ...
    runEventTriggeredDistributedLmbFilter( ...
        model, measurements, [], neighborMap, ...
        commConfig, fullConfig);
snapshot = ...
    fullDiagnostics.topologyLocalPosteriorSnapshot{2};
assert(numel(snapshot) == 2);

continuationConfig = fullConfig;
continuationConfig.topologyPosteriorCaptureTimes = [];
continuationConfig.filterInitialLocalPosteriorBySensor = snapshot;
continuationConfig.filterInitialLocalPosteriorTime = 2;
continuationConfig.filterInitialPreviousAdjacency = [0, 1; 1, 0];
[continuationEstimates, continuationDiagnostics] = ...
    runEventTriggeredDistributedLmbFilter( ...
        model, measurements, [], neighborMap, ...
        commConfig, continuationConfig);
assert(continuationDiagnostics.usedInitialLocalPosterior);
assert(continuationDiagnostics.continuationStartTime == 2);
assert(isequal( ...
    continuationDiagnostics.continuationPreviousDirectedEdgeMask, ...
    logical([0, 1; 1, 0])));
for sensorIdx = 1:2
    for timeIdx = 2:3
        assert(isequal( ...
            fullEstimates{sensorIdx}.labels{timeIdx}, ...
            continuationEstimates{sensorIdx}.labels{timeIdx}));
        assertStateCellsEqual( ...
            fullEstimates{sensorIdx}.mu{timeIdx}, ...
            continuationEstimates{sensorIdx}.mu{timeIdx});
        assertStateCellsEqual( ...
            fullEstimates{sensorIdx}.Sigma{timeIdx}, ...
            continuationEstimates{sensorIdx}.Sigma{timeIdx});
    end
end
assert(isequal( ...
    fullDiagnostics.topologyActiveEdge(:, :, 2:3), ...
    continuationDiagnostics.topologyActiveEdge(:, :, 2:3)));
fullAttempted = ...
    fullDiagnostics.attemptedPayloadBytes(:, :, 2:3);
continuationAttempted = ...
    continuationDiagnostics.attemptedPayloadBytes(:, :, 2:3);
assert(sum(fullAttempted(:)) == sum(continuationAttempted(:)));
end

function assertStateCellsEqual(left, right)
assert(numel(left) == numel(right));
for idx = 1:numel(left)
    assert(norm(left{idx} - right{idx}, 'fro') < 1e-12);
end
end

function testConstraintAwareScreenDecision()
options = struct( ...
    'maxTimeSteps', 1, ...
    'armNames', {{'robust-static', 'local'}}, ...
    'writeReport', false);
[~, summary] = runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 7, options);
assert(summary.decision.constraintEligibleArmCount == 1);
assert(strcmp( ...
    summary.decision.bestObservedArm, ...
    'All-time geometry static'));
assert(strcmp( ...
    summary.decision.status, ...
    'stop-no-observed-dynamic-gain'));
assert(summary.decision. ...
    minimumPracticalTrackingGainPercent == 5);
end

function testResidualRoutingBackboneGate()
options = struct( ...
    'maxTimeSteps', 1, ...
    'armNames', {{ ...
        'directed-reliability-w50', ...
        'confidence-residual-directed-routing'}}, ...
    'writeReport', false);
[~, summary] = runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 7, options);
readout = summary.decision.residualRouting;
assert(readout.available);
assert(strcmp(summary.decision.status, ...
    'residual-routing-no-incremental-gain'));
assert(readout.exactBackboneMatch);
assert(~readout.passesIncrementalGain);
assert(readout.tailSafeVsBackbone);
assert(readout.withinBackboneAttemptedBytes);
assert(readout.meanOverrideFraction == 0);
assert(isfinite(readout.meanSupportedCandidateFraction));
assert(readout.meanSupportedCandidateFraction >= 0 && ...
    readout.meanSupportedCandidateFraction <= 1);
end

function testContinuationCacheRejectsConfigDrift()
cacheDirectory = tempname();
mkdir(cacheDirectory);
cleanup = onCleanup(@() cleanupDirectory(cacheDirectory)); %#ok<NASGU>
teacherOptions = struct( ...
    'snapshotTimes', 1, ...
    'teacherHorizonSteps', 0, ...
    'closedLoopHorizonSteps', 0, ...
    'behaviorCacheDirectory', cacheDirectory, ...
    'writeReport', false);
runDynamicTopologyTeacherSignalScreen( ...
    'd12-handover', 31, teacherOptions);

continuationOptions = struct( ...
    'maxTimeSteps', 1, ...
    'continuationStartTime', 1, ...
    'armNames', {{'robust-static'}}, ...
    'behaviorCacheDirectory', cacheDirectory, ...
    'writeReport', false);
runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 31, continuationOptions);

continuationOptions.scenarioOverrides = struct( ...
    'measurementNoiseStd', 9);
rejected = false;
try
    runDynamicTopologyOracleGapScreen( ...
        'd12-handover', 31, continuationOptions);
catch errorInfo
    rejected = ~isempty(strfind( ...
        errorInfo.message, ...
        'metadata or posterior snapshot mismatches')); %#ok<STREMP>
end
assert(rejected);

continuationOptions.scenarioOverrides = struct();
continuationOptions.fusionOverrides = struct( ...
    'mixtureAwareTopComponents', 2);
rejected = false;
try
    runDynamicTopologyOracleGapScreen( ...
        'd12-handover', 31, continuationOptions);
catch errorInfo
    rejected = ~isempty(strfind( ...
        errorInfo.message, ...
        'metadata or posterior snapshot mismatches')); %#ok<STREMP>
end
assert(rejected);
end

function cleanupDirectory(path)
if exist(path, 'dir')
    rmdir(path, 's');
end
end

function testScheduledBirths()
inputs = generateDynamicTopologyScenarioInputs('d12-handover', 7);
model = inputs.model;
objects = model.object;
objects = lmbPredictionStep(objects, model, 1);
assert(numel(objects) == 3);
objects = lmbPredictionStep(objects, model, 2);
assert(numel(objects) == 3);
for timeIdx = 3:11
    objects = lmbPredictionStep(objects, model, timeIdx);
end
assert(numel(objects) == 6);
birthTimes = sort([objects.birthTime]);
assert(isequal(birthTimes, [1, 1, 1, 11, 11, 11]));
end

function testTimeVaryingDropAccounting()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
for birthIdx = 1:numel(model.birthParameters)
    model.birthParameters(birthIdx).r = 0.9;
end
measurements = repmat({{}}, 2, 2);
neighborMap = {[1, 2], [1, 2]};
pDrop = zeros(2, 2, 2);
pDrop(:, :, 2) = 1;
commConfig = struct( ...
    'pDropBySensor', [0, 0], ...
    'pDropByEdge', pDrop, ...
    'linkUniforms', 0.5 * ones(2, 2, 2));
triggerConfig = struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false);
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, [], neighborMap, commConfig, triggerConfig);
assert(diagnostics.summary.attemptCount == 4);
assert(diagnostics.summary.deliveryCount == 2);
assert(diagnostics.summary.attemptedPayloadBytes > ...
    diagnostics.summary.payloadBytes);
assert(diagnostics.summary.payloadBytes > 0);
end

function testDirectedTopologyExecution()
model = generateMultisensorModel( ...
    3, [0, 0, 0], [0.9, 0.9, 0.9], [3, 3, 3], ...
    'GA', 'LBP');
for birthIdx = 1:numel(model.birthParameters)
    model.birthParameters(birthIdx).r = 0.9;
end
measurements = repmat({{}}, 3, 1);
neighborMap = {1:3, 1:3, 1:3};
commConfig = struct( ...
    'forceDelivery', true, ...
    'pDropBySensor', [0, 0, 0]);
triggerConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false, ...
    'dynamicTopologyEnabled', true, ...
    'dynamicTopologyEdgeBudget', 2, ...
    'topologyDirectedEnabled', true, ...
    'topologyDirectedMessageBudget', 1, ...
    'topologyPolicyFcn', @fixedDirectedRoutingPolicy));
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, [], neighborMap, ...
    commConfig, triggerConfig);
assert(diagnostics.topologyFeasible(1));
assert(diagnostics.topologyDirectedMessageCount(1) == 1);
active = diagnostics.topologyActiveEdge(:, :, 1);
assert(active(1, 2));
assert(nnz(active) == 1);
attempted = diagnostics.attempted(:, :, 1);
assert(attempted(1, 2));
assert(nnz(attempted) == 1);
assert(abs(diagnostics.fusionWeight(1, 2, 1) - 0.25) < 1e-12);
assert(abs(diagnostics.fusionSelfWeight(2, 1) - 0.75) < 1e-12);
end

function [adjacency, details] = fixedDirectedRoutingPolicy(context)
nodeCount = numel(context.localPosteriorBySensor);
adjacency = false(nodeCount);
adjacency(2, 1) = true;
weights = eye(nodeCount);
weights(2, :) = 0;
weights(2, 1) = 0.25;
weights(2, 2) = 0.75;
details = struct( ...
    'objective', 0, ...
    'selectionSeconds', 0, ...
    'fusionWeightMatrix', weights);
end

function testDirectedRoutingFeaturesIgnoreTruth()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', [1, 2]), ...
    'targetTrajectories', {{100 * ones(4, 2)}});
left = makeObject(model, 1, 1, 0.85, ...
    [0; 0; 0; 0], 2 * eye(4));
right = makeObject(model, 1, 1, 0.65, ...
    [10; 5; 0; 0], 5 * eye(4));
context = struct( ...
    'localPosteriorBySensor', {{left, right}}, ...
    'model', model, ...
    'physicalAdjacency', logical([0, 1; 1, 0]), ...
    'commConfig', struct('pDropByEdge', [0, 0.2; 0.1, 0]), ...
    'currentTime', 1, ...
    'positions', [0, 10; 0, 5]);
[before, namesBefore] = computeDirectedRoutingFeatures(context);
context.model.dynamicTopologyScenario.targetTrajectories = ...
    {-1e9 * ones(4, 2)};
[after, namesAfter] = computeDirectedRoutingFeatures(context);
assert(isequal(namesBefore, namesAfter));
assert(isequaln(before, after));
end

function testKlaCompatibilityOrdering()
model = generateMultisensorModel( ...
    3, [0, 0, 0], [0.9, 0.9, 0.9], [3, 3, 3], 'GA', 'LBP');
reference = makeObject(model, 1, 1, 0.80, ...
    [0; 0; 0; 0], eye(4));
identical = reference;
shifted = makeObject(model, 1, 1, 0.80, ...
    [10; 0; 0; 0], eye(4));
context = struct( ...
    'localPosteriorBySensor', {{reference, shifted, identical}}, ...
    'model', model, ...
    'physicalAdjacency', logical(ones(3) - eye(3)), ...
    'commConfig', struct('pDropByEdge', zeros(3)), ...
    'currentTime', 1);
[scores, details] = computeLmbKlaCompatibilityMatrix( ...
    context, struct('sourceWeight', 0.50));
assert(scores(1, 3) > scores(1, 2));
assert(abs(details.spatialOverlapMatrix(1, 3) - 1) < 1e-10);
assert(details.spatialOverlapMatrix(1, 2) < 1e-3);
assert(details.bernoulliCompatibilityMatrix(1, 3) > ...
    details.bernoulliCompatibilityMatrix(1, 2));
context.directedMessageBudget = 3;
context.triggerConfig = struct();
[adjacency, policyDetails] = selectAnalyticDirectedRoutingPolicy( ...
    context, 'kla-compatibility', struct('sourceWeight', 0.50));
assert(adjacency(1, 3));
assert(~adjacency(1, 2));
assert(abs(policyDetails.fusionWeightMatrix(1, 3) - 0.50) < 1e-12);
end

function testDirectedTeacherDeliveryExpectation()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct( ...
        'targetSpeedLimit', 15, ...
        'ospaPositionCutoff', 100), ...
    'targetTrajectories', {{zeros(4, 1)}});
model.birthTimeByLocation = 1;
poor = makeObject(model, 1, 1, 0.80, ...
    [40; 0; 0; 0], eye(4));
good = makeObject(model, 1, 1, 0.80, ...
    zeros(4, 1), eye(4));
context = struct( ...
    'localPosteriorBySensor', {{poor, good}}, ...
    'model', model, ...
    'physicalAdjacency', logical([0, 1; 1, 0]), ...
    'commConfig', struct('pDropByEdge', [0, 1; 0, 0]), ...
    'triggerConfig', buildMixtureAwareKlaReferenceConfig(), ...
    'currentTime', 1);
options = struct( ...
    'maxMessagesPerReceiver', 1, ...
    'sourceWeightGrid', 0.50, ...
    'deliveryExpectationMode', 'bernoulli-risk');
[~, details] = selectDirectedTaskRoutingTeacher(context, options);
conditional = details.firstStepConditionalRiskByWeight;
expected = details.firstStepExpectedRiskByWeight;
gain = details.firstStepExpectedGainByWeight;
assert(abs(expected(1, 2, 1) - conditional(1, 2, 1)) < 1e-12);
assert(abs(expected(2, 1, 1) - details.nodeRiskBefore(2)) < 1e-12);
assert(abs(gain(2, 1, 1)) < 1e-12);
assert(strcmp(details.deliveryExpectationMode, 'bernoulli-risk'));
assert(~details.expectedDeliveryWeighting);

context.physicalAdjacency = logical([0, 1; 0, 0]);
[~, asymmetric] = ...
    selectDirectedTaskRoutingTeacher(context, options);
asymmetricConditional = ...
    asymmetric.firstStepConditionalRiskByWeight;
assert(isfinite(asymmetricConditional(1, 2, 1)));
assert(isnan(asymmetricConditional(2, 1, 1)));
assert(~asymmetric.adjacencySchedule(2, 1, 1));
end

function testDirectedRoutingModelArtifact()
path = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'models', 'directed_routing_knn_m24_t75.mat');
assert(exist(path, 'file') == 2);
loaded = load(path, 'model', 'trainingSummary');
assert(strcmp(loaded.model.kind, ...
    'receiver-held-out-knn-directed-routing'));
assert(numel(loaded.model.featureNames) == 21);
assert(loaded.model.neighborCount == 40);
assert(abs( ...
    loaded.model.minimumPositiveNeighborFraction - 0.70) < 1e-12);
assert(loaded.trainingSummary.crossValidation. ...
    negativeSelectionFraction == 0);
end

function testResidualRoutingModelArtifact()
path = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'models', 'confidence_gated_residual_m24_t75.mat');
assert(exist(path, 'file') == 2);
loaded = load(path, 'model', 'trainingSummary');
assert(strcmp(loaded.model.kind, ...
    'confidence-gated-residual-directed-kla'));
assert(numel(loaded.model.featureNames) == 32);
assert(numel(loaded.model.trainingDatasetPaths) == 2);
assert(numel(loaded.model.calibrationDatasetPaths) == 1);
assert(abs(loaded.model.confidenceLevel - 0.95) < 1e-12);
assert(strcmp(loaded.model.calibrationMode, 'selected-action'));
assert(strcmp(loaded.model.calibrationUnit, ...
    'scenario-seed-time-block-max'));
assert(loaded.trainingSummary.calibrationBlockCount == 1);
assert(loaded.trainingSummary.calibration. ...
    harmfulOverrideFraction == 0);
assert(loaded.trainingSummary.calibration. ...
    receiverOverrideFraction == 0);
datasetPath = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'cache', 'directed_teacher_v2_m24_hard_seed7_t75.mat');
dataset = load(datasetPath, 'datasetMetadata');
assert(strcmp(dataset.datasetMetadata.teacherLabelVersion, ...
    'joint-action-bernoulli-risk-v3-directed-physical'));
assert(strcmp(dataset.datasetMetadata.physicalAdjacencyConvention, ...
    'receiver-row-sender-column-directed'));
assert(isfield(dataset.datasetMetadata, ...
    'scenarioConfigSnapshot'));
assert(isfield(dataset.datasetMetadata, ...
    'fusionConfigSnapshot'));
overlapRejected = false;
try
    fitConfidenceGatedResidualRoutingModel( ...
        {datasetPath}, {datasetPath});
catch errorInfo
    overlapRejected = ~isempty(strfind( ...
        errorInfo.message, 'must be disjoint')); %#ok<STREMP>
end
assert(overlapRejected);
end

function testAnalyticDirectedRoutingPolicy()
context = struct();
context.localPosteriorBySensor = ...
    {struct([]), struct([]), struct([])};
context.physicalAdjacency = logical(ones(3) - eye(3));
context.commConfig = struct('pDropByEdge', [ ...
    0, 0.1, 0.8; ...
    0.2, 0, 0.1; ...
    0.1, 0.4, 0]);
context.currentTime = 1;
context.directedMessageBudget = 3;
context.triggerConfig = struct();
[adjacency, details] = selectAnalyticDirectedRoutingPolicy( ...
    context, 'reliability', struct('sourceWeight', 0.30));
assert(adjacency(1, 3));
assert(adjacency(2, 1));
assert(adjacency(3, 2));
assert(nnz(adjacency) == 3);
assert(abs(details.fusionWeightMatrix(1, 3) - 0.30) < 1e-12);
assert(abs(details.fusionWeightMatrix(1, 1) - 0.70) < 1e-12);
assert(details.messageCount == 3);

context.directedMessageBudget = 2;
[budgeted, budgetedDetails] = ...
    selectAnalyticDirectedRoutingPolicy( ...
        context, 'reliability', struct('sourceWeight', 0.30));
assert(nnz(budgeted) == 2);
assert(budgetedDetails.messageCount == 2);
end

function testRegisteredDirectedRoutingControls()
model = generateMultisensorModel( ...
    6, zeros(1, 6), 0.9 * ones(1, 6), ...
    3 * ones(1, 6), 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', [1, 1, 1, 2, 2, 2]));
context = struct( ...
    'localPosteriorBySensor', {repmat({struct([])}, 1, 6)}, ...
    'model', model, ...
    'physicalAdjacency', logical(ones(6) - eye(6)), ...
    'commConfig', struct('pDropByEdge', zeros(6)), ...
    'currentTime', 1, ...
    'directedMessageBudget', 6);

[fixedIndex, fixedDetails] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-index-star', ...
        struct('sourceWeight', 0.50));
expected = false(6);
expected(1, 2) = true;
expected(2:3, 1) = true;
expected(4, 5) = true;
expected(5:6, 4) = true;
assert(isequal(fixedIndex, expected));
assert(all(sum(fixedIndex, 2) == 1));
assert(nnz(fixedIndex) == 6);
assert(abs(fixedDetails.fusionWeightMatrix(3, 1) - 0.50) < 1e-12);
assert(~fixedDetails.posteriorUsed);
assert(~fixedDetails.currentLinkReliabilityUsed);

[fixedCycle, ~] = selectRegisteredDirectedRoutingPolicy( ...
    context, 'fixed-balanced-cycle', ...
    struct('sourceWeight', 0.50));
assert(all(sum(fixedCycle, 2) == 1));
assert(all(sum(fixedCycle, 1) == 1));
assert(fixedCycle(1, 2) && fixedCycle(2, 3) && fixedCycle(3, 1));

maps = false(6, 6, 2);
for timeIdx = 1:2
    context.currentTime = timeIdx;
    [maps(:, :, timeIdx), ~] = ...
        selectRegisteredDirectedRoutingPolicy( ...
            context, 'round-robin-balanced', ...
            struct('sourceWeight', 0.50));
    assert(all(sum(maps(:, :, timeIdx), 2) == 1));
    assert(all(sum(maps(:, :, timeIdx), 1) == 1));
end
assert(~isequal(maps(:, :, 1), maps(:, :, 2)));
assert(all(sum(any(maps(1:3, 1:3, :), 3), 2) == 2));
assert(all(sum(any(maps(4:6, 4:6, :), 3), 2) == 2));

context.model.dynamicTopologyScenario.config.sensorGroupIds = ...
    ones(1, 6);
periodMaps = false(6, 6, 6);
for timeIdx = 1:6
    context.currentTime = timeIdx;
    [periodMaps(:, :, timeIdx), ~] = ...
        selectRegisteredDirectedRoutingPolicy( ...
            context, 'round-robin-balanced', ...
            struct('sourceWeight', 0.50));
end
assert(size(unique(reshape( ...
    periodMaps(:, :, 1:5), [], 5)', 'rows'), 1) == 5);
assert(isequal(periodMaps(:, :, 6), periodMaps(:, :, 1)));
assert(all(sum(any(periodMaps(:, :, 1:5), 3), 2) == 5));

context.model.dynamicTopologyScenario.config.sensorGroupIds = ...
    [1, 1, 1, 2, 2, 2];
physicalMaps = false(6, 6, 6);
for timeIdx = 1:6
    context.currentTime = timeIdx;
    [physicalMaps(:, :, timeIdx), physicalDetails] = ...
        selectRegisteredDirectedRoutingPolicy( ...
            context, 'physical-round-robin', ...
            struct('sourceWeight', 0.50));
    assert(all(sum(physicalMaps(:, :, timeIdx), 2) == 1));
    assert(physicalDetails.currentPhysicalActionSetUsed);
    assert(~physicalDetails.posteriorUsed);
    assert(~physicalDetails.currentLinkReliabilityUsed);
end
assert(size(unique(reshape( ...
    physicalMaps(:, :, 1:5), [], 5)', 'rows'), 1) == 5);
assert(isequal(physicalMaps(:, :, 6), physicalMaps(:, :, 1)));
assert(all(sum(any(physicalMaps(:, :, 1:5), 3), 2) == 5));
groupIds = [1, 1, 1, 2, 2, 2];
crossFormation = ...
    bsxfun(@ne, groupIds(:), groupIds(:)');
assert(any(physicalMaps(repmat(crossFormation, 1, 1, 6))));
context.currentTime = 1;
[phaseThree, ~] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'physical-round-robin', ...
        struct('sourceWeight', 0.50, 'phase', 3));
assert(isequal(phaseThree, physicalMaps(:, :, 3)));

context.currentTime = 3;
[physicalBeforeMutation, ~] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'physical-round-robin', ...
        struct('sourceWeight', 0.50));
context.localPosteriorBySensor = repmat( ...
    {struct('r', 0.01, 'associationConfidence', 1)}, 1, 6);
context.commConfig.pDropByEdge = ...
    reshape(linspace(0, 0.99, 36), 6, 6);
[physicalAfterMutation, ~] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'physical-round-robin', ...
        struct('sourceWeight', 0.50));
assert(isequal(physicalBeforeMutation, physicalAfterMutation));

context.physicalAdjacency(1, :) = false;
context.physicalAdjacency(1, [4, 6]) = true;
[restrictedPhysical, ~] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'physical-round-robin', ...
        struct('sourceWeight', 0.50));
assert(nnz(restrictedPhysical(1, :)) == 1);
assert(any(restrictedPhysical(1, [4, 6])));
assert(~any(restrictedPhysical(:) & ...
    ~context.physicalAdjacency(:)));
context.physicalAdjacency = logical(ones(6) - eye(6));

context.model.dynamicTopologyScenario.config.sensorGroupIds = ...
    [1, 1, 1, 2, 2, 2];
context.localPosteriorBySensor = repmat({struct('r', 0.99)}, 1, 6);
context.commConfig.pDropByEdge = 0.9 * (ones(6) - eye(6));
[unchanged, ~] = selectRegisteredDirectedRoutingPolicy( ...
    context, 'fixed-index-star', struct('sourceWeight', 0.50));
assert(isequal(unchanged, fixedIndex));

context.directedMessageBudget = 5;
budgetRejected = false;
try
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-index-star', ...
        struct('sourceWeight', 0.50));
catch errorInfo
    budgetRejected = ~isempty(strfind( ...
        errorInfo.message, 'budget is too small')); %#ok<STREMP>
end
assert(budgetRejected);
context.directedMessageBudget = 6;

context.physicalAdjacency(1, 2) = false;
physicalRejected = false;
try
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-index-star', ...
        struct('sourceWeight', 0.50));
catch errorInfo
    physicalRejected = ~isempty(strfind( ...
        errorInfo.message, 'non-physical route')); %#ok<STREMP>
end
assert(physicalRejected);
context.physicalAdjacency(1, 2) = true;

metadataModel = context.model;
context.model = rmfield(context.model, 'dynamicTopologyScenario');
metadataRejected = false;
try
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-index-star', ...
        struct('sourceWeight', 0.50));
catch errorInfo
    metadataRejected = ~isempty(strfind( ...
        errorInfo.message, 'require explicit')); %#ok<STREMP>
end
assert(metadataRejected);
context.model = metadataModel;
end

function testFormationGatewayRoutingPolicies()
model = generateMultisensorModel( ...
    6, zeros(1, 6), 0.9 * ones(1, 6), ...
    3 * ones(1, 6), 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', [1, 1, 1, 2, 2, 2]));
context = struct( ...
    'localPosteriorBySensor', {repmat({struct([])}, 1, 6)}, ...
    'model', model, ...
    'physicalAdjacency', logical(ones(6) - eye(6)), ...
    'commConfig', struct('pDropByEdge', zeros(6)), ...
    'currentTime', 1, ...
    'directedMessageBudget', 6);

featureNames = { ...
    'link_reliability', 'positive_existence_gain', ...
    'positive_precision_gain', 'negative_existence_gap', ...
    'negative_precision_gap', 'normalized_state_discrepancy', ...
    'active_label_overlap', 'receiver_need'};
features = nan(6, 6, 1, numel(featureNames));
physical = context.physicalAdjacency;
for featureIdx = 1:numel(featureNames)
    slice = zeros(6);
    slice(~physical) = NaN;
    features(:, :, 1, featureIdx) = slice;
end
features(:, :, 1, 1) = 0.9 * double(physical);
features(:, :, 1, 2) = 0.01 * double(physical);
features(:, :, 1, 7) = double(physical);
features(~repmat(physical, 1, 1, 1, numel(featureNames))) = NaN;
features(1, 4, 1, 2) = 0.20;
features(2, 5, 1, 2) = 0.18;
features(4, 1, 1, 2) = 0.15;
featureMetadata = struct( ...
    'sourceWeightGrid', 0.50, 'truthUsed', false);
options = buildFormationGatewayRoutingOptions( ...
    'v1', struct( ...
        'actionFeatures', features, ...
        'actionFeatureNames', {featureNames}, ...
        'actionFeatureMetadata', featureMetadata));
[gateway, gatewayDetails] = ...
    selectFormationGatewayRoutingPolicy(context, options);
assert(all(sum(gateway, 2) == 1));
assert(nnz(gateway) == 6);
assert(gateway(1, 4));
assert(~gateway(2, 5));
assert(gateway(4, 1));
assert(nnz(gatewayDetails.overrideMask) == 2);
assert(abs(gatewayDetails.overrideFraction - 2 / 6) < 1e-12);
assert(gatewayDetails.posteriorUsed);
assert(~gatewayDetails.truthUsed);
assert(gatewayDetails.currentLinkReliabilityUsed);

blockedOptions = options;
blockedOptions.minimumPositiveExistence = 0.25;
[blocked, blockedDetails] = ...
    selectFormationGatewayRoutingPolicy(context, blockedOptions);
[roundRobin, ~] = selectRegisteredDirectedRoutingPolicy( ...
    context, 'round-robin-balanced', ...
    struct('sourceWeight', 0.50, 'phase', 1));
assert(isequal(blocked, roundRobin));
assert(blockedDetails.overrideFraction == 0);

[fixedGateway, fixedDetails] = ...
    selectRegisteredGatewayRoutingPolicy( ...
        context, 'fixed-ring', struct('sourceWeight', 0.50));
assert(all(sum(fixedGateway, 2) == 1));
assert(nnz(fixedGateway) == 6);
assert(nnz(fixedDetails.overrideMask) == 2);
assert(fixedGateway(1, 4) && fixedGateway(4, 1));
assert(~fixedDetails.posteriorUsed);

context.currentTime = 2;
[rotatingGateway, rotatingDetails] = ...
    selectRegisteredGatewayRoutingPolicy( ...
        context, 'rotating-ring', ...
        struct('sourceWeight', 0.50, 'phase', 1));
assert(all(sum(rotatingGateway, 2) == 1));
assert(nnz(rotatingGateway) == 6);
assert(nnz(rotatingDetails.overrideMask) == 2);
assert(~isequal(rotatingGateway, fixedGateway));

context.commConfig.pDropByEdge = 0.8 * double(physical);
context.commConfig.pDropByEdge(2, 6) = 0.01;
context.commConfig.pDropByEdge(5, 3) = 0.02;
[linkGateway, linkDetails] = ...
    selectRegisteredGatewayRoutingPolicy( ...
        context, 'link-aware', struct('sourceWeight', 0.50));
assert(linkGateway(2, 6) && linkGateway(5, 3));
assert(linkDetails.currentLinkReliabilityUsed);
assert(nnz(linkDetails.overrideMask) == 2);
end

function testReliabilityControlIsFixedIndexOnScaledScenarios()
presets = {'m24-hard', 'x36-clean-scale'};
for presetIdx = 1:numel(presets)
    rng(7);
    config = buildDynamicTopologyScenarioConfig(presets{presetIdx});
    [sensorTrajectories, ~] = ...
        generateMultiFormationTrajectories(config);
    graphs = buildDynamicTopologyGraphs(config, sensorTrajectories);
    [pDropByEdge, ~] = ...
        buildDynamicTopologyLinkSchedule(config, graphs);
    model = struct( ...
        'dynamicTopologyScenario', struct('config', config));
    context = struct( ...
        'localPosteriorBySensor', ...
            {repmat({struct([])}, 1, config.numberOfSensors)}, ...
        'model', model, ...
        'physicalAdjacency', false(config.numberOfSensors), ...
        'commConfig', struct('pDropByEdge', pDropByEdge), ...
        'currentTime', 1, ...
        'directedMessageBudget', config.numberOfSensors);
    reference = [];
    for timeIdx = 1:config.simulationLength
        context.currentTime = timeIdx;
        context.physicalAdjacency = ...
            graphs.physicalAdjacency(:, :, timeIdx);
        [reliability, reliabilityDetails] = ...
            selectAnalyticDirectedRoutingPolicy( ...
            context, 'reliability', struct('sourceWeight', 0.50));
        [fixedIndex, fixedDetails] = ...
            selectRegisteredDirectedRoutingPolicy( ...
            context, 'fixed-index-star', ...
            struct('sourceWeight', 0.50));
        assert(isequal(reliability, fixedIndex));
        assert(isequal( ...
            reliabilityDetails.fusionWeightMatrix, ...
            fixedDetails.fusionWeightMatrix));
        if isempty(reference)
            reference = reliability;
        else
            assert(isequal(reliability, reference));
        end
    end
end
end

function testFixedIndexClosedLoopClone()
options = struct( ...
    'maxTimeSteps', 1, ...
    'armNames', {{ ...
        'directed-fixed-index-w50', ...
        'directed-reliability-w50'}}, ...
    'writeReport', false);
[~, summary] = runDynamicTopologyOracleGapScreen( ...
    'm24-hard', 7, options);
fixed = summary.aggregate(1);
reliability = summary.aggregate(2);
assert(isequal( ...
    fixed.focusEospaBySeed, reliability.focusEospaBySeed));
assert(isequal( ...
    fixed.worstSensorEospaBySeed, ...
    reliability.worstSensorEospaBySeed));
assert(isequal( ...
    fixed.attemptedBytesBySeed, ...
    reliability.attemptedBytesBySeed));
assert(isequal( ...
    fixed.deliveredBytesBySeed, ...
    reliability.deliveredBytesBySeed));
assert(isequal( ...
    fixed.meanDirectedMessageCountBySeed, ...
    reliability.meanDirectedMessageCountBySeed));
end

function testReliabilityQualityRoutingRespondsToPosterior()
model = generateMultisensorModel( ...
    3, [0, 0, 0], [0.9, 0.9, 0.9], ...
    [3, 3, 3], 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', [1, 1, 1]));
objects = cell(1, 3);
for sensorIdx = 1:3
    objects{sensorIdx} = makeObject( ...
        model, 1, 1, 0.8, zeros(4, 1), eye(4));
    objects{sensorIdx}.associationConfidence = 0;
end
objects{3}.associationConfidence = 1;
context = struct( ...
    'localPosteriorBySensor', {objects}, ...
    'model', model, ...
    'physicalAdjacency', logical(ones(3) - eye(3)), ...
    'commConfig', struct('pDropByEdge', zeros(3)), ...
    'currentTime', 1, ...
    'positions', zeros(2, 3), ...
    'directedMessageBudget', 3, ...
    'triggerConfig', struct());
[first, firstDetails] = selectAnalyticDirectedRoutingPolicy( ...
    context, 'reliability-quality', struct( ...
        'qualityCoefficient', 0.25, 'sourceWeight', 0.70));
assert(first(1, 3) && first(2, 3));
assert(abs(firstDetails.fusionWeightMatrix(1, 3) - 0.70) < 1e-12);
assert(abs(firstDetails.scoreDetails.qualityCoefficient - 0.25) < 1e-12);

objects{3}.associationConfidence = 0;
objects{2}.associationConfidence = 1;
context.localPosteriorBySensor = objects;
[second, ~] = selectAnalyticDirectedRoutingPolicy( ...
    context, 'reliability-quality', struct( ...
        'qualityCoefficient', 0.25, 'sourceWeight', 0.70));
assert(second(1, 2) && second(3, 2));
assert(~isequal(first, second));
end

function testRouteAttributionDiagnostics()
outputDirectory = tempname();
mkdir(outputDirectory);
cleanup = onCleanup( ...
    @() cleanupDirectory(outputDirectory)); %#ok<NASGU>
options = struct( ...
    'maxTimeSteps', 3, ...
    'armNames', {{ ...
        'directed-fixed-index-w70', ...
        'directed-fixed-cycle-w70', ...
        'directed-round-robin-w70', ...
        'directed-physical-round-robin-p1-w70', ...
        'directed-reliability-quality-c25-w70'}}, ...
    'outputDirectory', outputDirectory, ...
    'writeReport', true);
[reportPath, summary] = runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 7, options);
assert(exist(reportPath, 'file') == 2);
reportText = fileread(reportPath);
assert(~isempty(strfind( ...
    reportText, 'Dynamic-routing attribution readout'))); %#ok<STREMP>
assert(~isempty(strfind( ...
    reportText, 'Action support matched'))); %#ok<STREMP>
fixed = summary.aggregate(1);
rotating = summary.aggregate(3);
physicalRotating = summary.aggregate(4);
assert(fixed.distinctDirectedRouteMapCount == 1);
assert(fixed.withinWindowRouteChangeFraction == 0);
assert(fixed.fractionReceiverTimeDifferentFromFixedIndexMap == 0);
assert(fixed.receiverCoverageFraction == 1);
assert(fixed.meanUniqueSendersPerReceiver == 1);
assert(rotating.distinctDirectedRouteMapCount == 3);
assert(rotating.withinWindowRouteChangeFraction == 1);
assert(rotating.fractionReceiverTimeDifferentFromFixedIndexMap > 0.1);
assert(rotating.receiverCoverageFraction == 1);
assert(rotating.meanUniqueSendersPerReceiver == 3);
assert(physicalRotating.crossFormationMessageFraction > 0);
assert(summary.decision.dynamicAttribution.available);
assert(summary.decision.dynamicAttribution.completeBaselineSet);
assert(summary.decision.dynamicAttribution.weightMatchedControlSet);
assert(summary.decision.dynamicAttribution. ...
    candidateUsesCrossFormation);
assert(summary.decision.dynamicAttribution. ...
    crossFormationControlSet);
assert(summary.decision.dynamicAttribution.actionSupportMatched);
assert(abs( ...
    summary.decision.dynamicAttribution.candidateSourceWeight - ...
    0.70) < 1e-12);
assert(~strcmp( ...
    summary.decision.dynamicAttribution.status, 'unavailable'));

mismatchOptions = struct( ...
    'maxTimeSteps', 1, ...
    'armNames', {{ ...
        'directed-fixed-index-w50', ...
        'directed-fixed-cycle-w50', ...
        'directed-round-robin-w50', ...
        'directed-reliability-quality-c25-w70'}}, ...
    'writeReport', false);
[~, mismatchSummary] = runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 7, mismatchOptions);
assert(mismatchSummary.decision.dynamicAttribution.available);
assert(~mismatchSummary.decision.dynamicAttribution.completeBaselineSet);
assert(~mismatchSummary.decision.dynamicAttribution. ...
    weightMatchedControlSet);
assert(strcmp( ...
    mismatchSummary.decision.dynamicAttribution.status, ...
    'dynamic-attribution-incomplete-controls'));

actionMismatchOptions = struct( ...
    'maxTimeSteps', 3, ...
    'armNames', {{ ...
        'directed-fixed-index-w70', ...
        'directed-fixed-cycle-w70', ...
        'directed-round-robin-w70', ...
        'directed-reliability-quality-c25-w70'}}, ...
    'writeReport', false);
[~, actionMismatchSummary] = runDynamicTopologyOracleGapScreen( ...
    'd12-handover', 7, actionMismatchOptions);
actionMismatch = ...
    actionMismatchSummary.decision.dynamicAttribution;
assert(actionMismatch.available);
assert(actionMismatch.weightMatchedControlSet);
assert(actionMismatch.candidateUsesCrossFormation);
assert(~actionMismatch.crossFormationControlSet);
assert(~actionMismatch.actionSupportMatched);
assert(~actionMismatch.completeBaselineSet);
assert(strcmp(actionMismatch.status, ...
    'dynamic-attribution-incomplete-controls'));

candidateSelectionOptions = struct( ...
    'maxTimeSteps', 1, ...
    'armNames', {{ ...
        'directed-fixed-index-w50', ...
        'directed-fixed-cycle-w50', ...
        'directed-round-robin-w50', ...
        'directed-physical-round-robin-p1-w50', ...
        'directed-reliability-quality-c25-w70', ...
        'directed-reliability-quality-c25-w50'}}, ...
    'writeReport', false);
[~, candidateSelectionSummary] = ...
    runDynamicTopologyOracleGapScreen( ...
        'd12-handover', 7, candidateSelectionOptions);
candidateSelection = ...
    candidateSelectionSummary.decision.dynamicAttribution;
assert(candidateSelection.availableCandidateCount == 2);
assert(candidateSelection.completeControlCandidateCount == 1);
assert(abs(candidateSelection.candidateSourceWeight - 0.50) < 1e-12);
assert(candidateSelection.completeBaselineSet);
end

function testScaleInvariantActionFeaturesIgnoreTruth()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct( ...
        'sensorGroupIds', [1, 2], ...
        'numberOfTargets', 1), ...
    'targetTrajectories', {{100 * ones(4, 2)}});
model.birthTimeByLocation = 1;
left = makeObject(model, 1, 1, 0.85, ...
    [0; 0; 0; 0], 2 * eye(4));
right = makeObject(model, 1, 1, 0.65, ...
    [10; 5; 0; 0], 5 * eye(4));
context = struct( ...
    'localPosteriorBySensor', {{left, right}}, ...
    'model', model, ...
    'physicalAdjacency', logical([0, 1; 1, 0]), ...
    'commConfig', struct('pDropByEdge', [0, 0.2; 0.1, 0]), ...
    'currentTime', 1, ...
    'positions', [0, 10; 0, 5]);
[before, namesBefore, metadata] = ...
    computeScaleInvariantDirectedActionFeatures( ...
        context, [0.30, 0.50, 0.70]);
context.model.dynamicTopologyScenario.targetTrajectories = ...
    {-1e9 * ones(4, 2), 1e9 * ones(4, 2)};
[after, namesAfter] = ...
    computeScaleInvariantDirectedActionFeatures( ...
        context, [0.30, 0.50, 0.70]);
assert(isequal(namesBefore, namesAfter));
assert(isequaln(before, after));
assert(isequal(size(before), [2, 2, 3, 32]));
assert(metadata.targetCapacity == 1);
assert(metadata.scaleInvariantCardinality);
assert(~metadata.truthUsed);
end

function testConfidenceGatedResidualFallback()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
model.dynamicTopologyScenario = struct( ...
    'config', struct( ...
        'sensorGroupIds', [1, 2], ...
        'numberOfTargets', 1));
model.birthTimeByLocation = 1;
left = makeObject(model, 1, 1, 0.85, ...
    [0; 0; 0; 0], 2 * eye(4));
right = makeObject(model, 1, 1, 0.65, ...
    [10; 5; 0; 0], 5 * eye(4));
context = struct( ...
    'localPosteriorBySensor', {{left, right}}, ...
    'model', model, ...
    'physicalAdjacency', logical([0, 1; 1, 0]), ...
    'commConfig', struct('pDropByEdge', [0, 0.2; 0.1, 0]), ...
    'currentTime', 1, ...
    'positions', [0, 10; 0, 5], ...
    'previousAdjacency', false(2), ...
    'directedMessageBudget', 2, ...
    'triggerConfig', struct());
[actionFeatures, featureNames, metadata] = ...
    computeScaleInvariantDirectedActionFeatures( ...
        context, [0.30, 0.50, 0.70]);
featureCount = numel(featureNames);
residualModel = struct( ...
    'kind', 'confidence-gated-residual-directed-kla', ...
    'featureNames', {featureNames}, ...
    'sourceWeightGrid', [0.30, 0.50, 0.70], ...
    'backboneWeight', metadata.backboneWeight, ...
    'featureMean', zeros(1, featureCount), ...
    'featureScale', ones(1, featureCount), ...
    'coefficient', zeros(featureCount, 1), ...
    'intercept', 1, ...
    'overestimateQuantile', 2, ...
    'minimumResidual', 0, ...
    'supportLower', -1e6 * ones(1, featureCount), ...
    'supportUpper', 1e6 * ones(1, featureCount));
[fallback, fallbackDetails] = ...
    selectConfidenceGatedResidualRoutingPolicy( ...
        context, residualModel);
[analytic, analyticDetails] = ...
    selectAnalyticDirectedRoutingPolicy( ...
        context, 'reliability', struct('sourceWeight', 0.50));
assert(isequal(fallback, analytic));
assert(isequal( ...
    fallbackDetails.fusionWeightMatrix, ...
    analyticDetails.fusionWeightMatrix));
assert(fallbackDetails.overrideFraction == 0);

context.directedMessageBudget = 1;
[budgetedFallback, ~] = ...
    selectConfidenceGatedResidualRoutingPolicy( ...
        context, residualModel);
[budgetedAnalytic, ~] = ...
    selectAnalyticDirectedRoutingPolicy( ...
        context, 'reliability', struct('sourceWeight', 0.50));
assert(isequal(budgetedFallback, budgetedAnalytic));

context.directedMessageBudget = 2;
weightFeatureIdx = find(strcmp( ...
    featureNames, 'source_weight'), 1);
residualModel.coefficient(weightFeatureIdx) = 1;
residualModel.intercept = 0;
residualModel.overestimateQuantile = 0;
[overridden, overrideDetails] = ...
    selectConfidenceGatedResidualRoutingPolicy( ...
        context, residualModel);
assert(isequal(overridden, analytic));
assert(all(abs( ...
    overrideDetails.selectedSourceWeightsByReceiver - 0.70) < 1e-12));
assert(overrideDetails.overrideFraction == 1);
assert(isequal(size(actionFeatures), [2, 2, 3, featureCount]));
end

function testTopologyScheduleFusion()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
left = makeObject(model, 1, 1, 0.85, ...
    [0; 0; 0; 0], 2 * eye(4));
right = makeObject(model, 1, 1, 0.70, ...
    [12; -4; 0; 0], 5 * eye(4));
config = buildMixtureAwareKlaReferenceConfig();
[scheduled, details] = fuseLmbNetworkByTopologySchedule( ...
    {left, right}, logical([0, 1; 1, 0]), ...
    model, config, struct('expectedDeliveryWeighting', false));
direct = fuseLmbPosteriorsByLabel( ...
    {left, right}, [2/3, 1/3], model, [2/3, 1/3], ...
    struct('eventType', [0, 2]), config);
assert(details.roundCount == 1);
assert(details.totalDirectedTransmissionCount == 2);
assert(details.totalAttemptedBytes > 0);
assert(abs(scheduled{1}.r - direct.r) < 1e-12);
[scheduledMean, scheduledCovariance] = objectMoments(scheduled{1});
[directMean, directCovariance] = objectMoments(direct);
assert(norm(scheduledMean - directMean) < 1e-12);
assert(norm(scheduledCovariance - directCovariance, 'fro') < 1e-12);
end

function testInfeasiblePhysicalGraphFailsClosed()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
model.sensorCommRange = 1;
measurements = repmat({{}}, 2, 2);
sensorTrajectories = { ...
    repmat([0; 0; 0; 0], 1, 2), ...
    repmat([100; 0; 0; 0], 1, 2)};
neighborMap = {[1, 2], [1, 2]};
commConfig = struct('forceDelivery', true, 'pDropBySensor', [0, 0]);
triggerConfig = struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false, ...
    'dynamicTopologyEnabled', true, ...
    'dynamicTopologyEdgeBudget', 1);
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig);
assert(all(diagnostics.topologyUndirectedEdgeCount == 0));
assert(all(~diagnostics.topologyFeasible));
assert(diagnostics.summary.attemptCount == 0);
end

function testMixtureAwareReferenceBoundary()
model = generateMultisensorModel( ...
    2, [0, 0], [0.9, 0.9], [3, 3], 'GA', 'LBP');
left = makeObject(model, 1, 1, 0.8, ...
    [-2; 0; 0; 0], 2 * eye(4));
right = makeObject(model, 1, 1, 0.8, ...
    [2; 0; 0; 0], 3 * eye(4));
config = buildMixtureAwareKlaReferenceConfig();
details = struct('eventType', [0, 2]);
fused = fuseLmbPosteriorsByLabel( ...
    {left, right}, [0.5, 0.5], model, [0.5, 0.5], ...
    details, config);
expectedCovariance = inv( ...
    0.5 * inv(left.Sigma{1}) + 0.5 * inv(right.Sigma{1}));
expectedMean = expectedCovariance * ( ...
    0.5 * (left.Sigma{1} \ left.mu{1}) + ...
    0.5 * (right.Sigma{1} \ right.mu{1}));
assert(fused.numberOfGmComponents == 1);
assert(norm(fused.mu{1} - expectedMean) < 1e-10);
assert(norm(fused.Sigma{1} - expectedCovariance, 'fro') < 1e-10);

bimodal = makeObject(model, 1, 2, 0.8, ...
    [-8; 0; 0; 0], eye(4));
bimodal.numberOfGmComponents = 2;
bimodal.w = [0.5, 0.5];
bimodal.mu = {[-8; 0; 0; 0], [8; 0; 0; 0]};
bimodal.Sigma = {eye(4), eye(4)};
fixedPoint = fuseLmbPosteriorsByLabel( ...
    {bimodal, bimodal}, [0.5, 0.5], model, [0.5, 0.5], ...
    details, config);
assert(fixedPoint.numberOfGmComponents >= 2);
[meanVector, covariance] = objectMoments(fixedPoint);
[referenceMean, referenceCovariance] = objectMoments(bimodal);
assert(norm(meanVector - referenceMean) < 1e-6);
assert(norm(covariance - referenceCovariance, 'fro') < 1e-3);
assert(abs(fixedPoint.r - bimodal.r) < 1e-3);
end

function testD12OracleCallbackSmoke()
inputs = generateDynamicTopologyScenarioInputs('d12-handover', 13);
inputs.measurements = inputs.measurements(:, 1);
inputs.sensorTrajectories = cellfun( ...
    @(x) x(:, 1), inputs.sensorTrajectories, ...
    'UniformOutput', false);
inputs.commConfig.pDropByEdge = ...
    inputs.commConfig.pDropByEdge(:, :, 1);
inputs.commConfig.linkUniforms = ...
    inputs.commConfig.linkUniforms(:, :, 1);
config = buildMixtureAwareKlaReferenceConfig();
config.dynamicTopologyEnabled = true;
config.dynamicTopologyEdgeBudget = inputs.config.edgeBudget;
config.topologyPolicyName = 'oracle-consensus';
config.topologyPolicyFcn = ...
    @(context) selectD12TopologyPolicy(context, 'oracle-consensus');
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    inputs.model, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, config);
assert(diagnostics.topologyFeasible(1));
assert(diagnostics.topologyUndirectedEdgeCount(1) == ...
    inputs.config.edgeBudget);
assert(isfinite(diagnostics.topologyPolicyCandidateIndex(1)));
assert(isfinite(diagnostics.topologyPolicyObjective(1)));

uncachedConfig = config;
uncachedConfig.topologyOracleFusionCacheEnabled = false;
[~, uncachedDiagnostics] = runEventTriggeredDistributedLmbFilter( ...
    inputs.model, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, uncachedConfig);
assert(uncachedDiagnostics.topologyPolicyCandidateIndex(1) == ...
    diagnostics.topologyPolicyCandidateIndex(1));
assert(abs(uncachedDiagnostics.topologyPolicyObjective(1) - ...
    diagnostics.topologyPolicyObjective(1)) < 1e-10);
end

function object = makeObject(model, birthTime, birthLocation, r, mu, Sigma)
object = model.birthParameters(1);
object.birthTime = birthTime;
object.birthLocation = birthLocation;
object.r = r;
object.numberOfGmComponents = 1;
object.w = 1;
object.mu = {mu};
object.Sigma = {Sigma};
end

function [meanVector, covariance] = objectMoments(object)
weights = reshape(object.w, 1, []);
weights = weights / sum(weights);
meanVector = zeros(size(object.mu{1}));
for componentIdx = 1:object.numberOfGmComponents
    meanVector = meanVector + ...
        weights(componentIdx) * object.mu{componentIdx};
end
covariance = zeros(size(object.Sigma{1}));
for componentIdx = 1:object.numberOfGmComponents
    delta = object.mu{componentIdx} - meanVector;
    covariance = covariance + weights(componentIdx) * ...
        (object.Sigma{componentIdx} + delta * delta');
end
end

function context = makeCandidatePoolContext(config, sensors, graphs)
sensorCount = config.numberOfSensors;
scenario = struct( ...
    'config', config, ...
    'candidateAdjacency', graphs.candidateAdjacency);
context = struct();
context.model = struct( ...
    'dynamicTopologyScenario', scenario, ...
    'xDimension', 4);
context.physicalAdjacency = graphs.physicalAdjacency(:, :, 1);
context.baseAdjacency = graphs.staticAdjacency;
context.previousAdjacency = false(sensorCount);
context.edgeBudget = config.edgeBudget;
context.edgeScores = double(context.physicalAdjacency);
context.positions = zeros(2, sensorCount);
for sensorIdx = 1:sensorCount
    context.positions(:, sensorIdx) = ...
        sensors{sensorIdx}(1:2, 1);
end
context.localPosteriorBySensor = ...
    repmat({struct([])}, 1, sensorCount);
context.commConfig = struct( ...
    'pDropByEdge', zeros(sensorCount));
context.currentTime = 1;
end

function connected = isConnectedTest(adjacency)
nodeCount = size(adjacency, 1);
visited = false(1, nodeCount);
queue = 1;
visited(1) = true;
while ~isempty(queue)
    node = queue(1);
    queue(1) = [];
    neighbors = find(adjacency(node, :) & ~visited);
    visited(neighbors) = true;
    queue = [queue, neighbors]; %#ok<AGROW>
end
connected = all(visited);
end
