function test_opened_safe_formation_v110()
% TEST_OPENEDSAFEFORMATIONV110 Schedule and authorization contract.

protocol = getOpenedSafeFormationV110Protocol();
assert(isequal(protocol.safeFormationIds, [2, 3, 4, 5]));
assert(isequal(protocol.excludedFormationIds, [1, 6]));
assert(all(cellfun(@(ids) ~any(ismember(ids, [1, 6])), ...
    protocol.protectionFormationIdsByTime)));
assert(isequal(protocol.protectionFormationIdsByTime{1}, [2, 4, 5]));
assert(all(cellfun(@(ids) isequal(ids, [2, 3, 4, 5]), ...
    protocol.protectionFormationIdsByTime(2:end))));

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildOpenedSafeFormationV110ExecutionContext( ...
    entry.presetName, entry.seed, 72, protocol.candidateActionName, true);
assert(isOpenedSafeFormationV110ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.protectionFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig.receiverSafeFormationConditionedPayloadMode = ...
    'control-only';
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
end
