function test_explicit_label_abstention_v109()
% TEST_EXPLICITLABELABSTENTIONV109 Plan semantics and authorization.

object = struct( ...
    'birthTime', 1, ...
    'birthLocation', 1, ...
    'r', 0.9, ...
    'numberOfGmComponents', 1, ...
    'w', 1, ...
    'mu', {{zeros(4, 1)}}, ...
    'Sigma', {{eye(4)}}, ...
    'detectionAssociationMass', 0.8);
posteriors = {object, object};
crossResidual = false(2);
crossResidual(2, 1) = true;
model = struct( ...
    'xDimension', 4, ...
    'existenceThreshold', 0.01, ...
    'dynamicTopologyScenario', struct( ...
        'config', struct('sensorGroupIds', [1, 2])));
config = struct( ...
    'receiverSafeFormationConditionedTimes', 1, ...
    'receiverSafeFormationConditionedSchedule', {{1}}, ...
    'receiverSafeFormationConditionedPayloadMode', 'abstention-only', ...
    'receiverSafeExternalPositiveSupportThreshold', 0.2, ...
    'receiverSafeFormationConditionedHighExistenceThreshold', 0.5, ...
    'payloadExistenceThreshold', 0.01);
plan = buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct()}, model, config, 1);
assert(plan.selectiveEdgeMask(2, 1));
assert(plan.abstainFromFusionEdgeMask(2, 1));
assert(isempty(plan.payloadByReceiverSender{1, 2}));
assert(plan.totalControlSynopsisBytes > 0);
assert(plan.totalSelectedPayloadBytes == 0);

protocol = getExplicitLabelAbstentionV109Protocol();
entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildExplicitLabelAbstentionV109ExecutionContext( ...
    entry.presetName, entry.seed, 72, protocol.candidateActionName, true);
assert(isExplicitLabelAbstentionV109ExecutionContext(context));
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.protectionFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'abstention-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig.receiverSafeFormationConditionedPayloadMode = ...
    'control-only';
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
end
