function test_formation_staggered_recovery_x36_outcome_permit()
% TEST_FORMATIONSTAGGEREDRECOVERYX36OUTCOMEPERMIT Exact v3 permit gate.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
originalDirectory = cd(repoRoot);
directoryCleanup = onCleanup( ...
    @() cd(originalDirectory)); %#ok<NASGU>

permit = getFormationStaggeredRecoveryX36OutcomePermit();
payload = rmfield(permit, 'permitCanonicalSha256');
assert(strcmp(permit.permitCanonicalSha256, ...
    computeCanonicalValueSha256(payload)));
assert(strcmp(permit.contractVersion, ...
    'formation-staggered-recovery-x36-outcome-permit-v3'));
assert(strcmp(permit.authorizedRunnerContractVersion, [ ...
    'formation-staggered-recovery-x36-v37-', ...
    'exact-two-arm-runner-v3']));
assert(strcmp(permit.sourceProtocolContractVersion, ...
    'formation-staggered-recovery-x36-source-protocol-v3'));
assert(strcmp(permit.sourceProtocolCanonicalSha256, ...
    '9fee393ca74e2eca3dd69861470c2ee759a332a2bfbff300afae33633a740d19'));
assert(strcmp(permit.preflightSha256, ...
    'f82b531a51df124c7f0342d6c8d77950ba16431b473ad636f39732bcda7b9fde'));
assert(strcmp(permit.preflightReportSha256, ...
    'd3e66375e6e464528c14738fa37d708ef9c1c4bedfeadeaaf30a133eef85aacb'));
assert(strcmp(permit.preflightCompletionMarkerSha256, ...
    'bcdb136ea3a0fea3eeb4fb79db538e5c9b21256beb16e63af61995cf23660aae'));
assert(strcmp(permit.preflightGenerationGitCommit, ...
    'faa6d4e99137fedf9c65c951b0e02d02d6dc3d46'));
assert(strcmp(permit.preflightSourceManifestSha256, ...
    '1127516ddcb5ce0e07a5cf0bd9942153cc2cf08c9f1b76d915aa4318273db2a3'));
assert(strcmp(permit.gateBaseGitCommit, ...
    'c037aa37eec9161e54d1d3dea7a689060a88eb95'));
assert(strcmp(permit.releaseDescriptorContractVersion, [ ...
    'formation-staggered-recovery-x36-', ...
    'outcome-release-descriptor-v1']));
assert(strcmp(permit.releaseTagName, ...
    'x36-v37-v3-outcome-gate-20260803'));
assert(strcmp(permit.releaseRemoteUrl, ...
    'git@github.com:Deeeeex/MULTISENSOR-LMB-FILTERS.git'));
assert(strcmp(permit.releaseBranchRef, ...
    'refs/heads/codex/event-conditioned-h3'));
assert(permit.releaseTagMustBeAnnotated);
assert(permit.releaseTagMustBePublished);
assert(permit.releaseCommitMustDirectlyFollowGate);
assert(permit.releaseCommitMustBePublished);
assert(permit.gitHistoryOverridesForbidden);
assert(isequal(size( ...
    permit.authorizedRuntimeFingerprintSha256ByStateArm), [3, 2]));
assert(all(cellfun(@isSha256, ...
    permit.authorizedRuntimeFingerprintSha256ByStateArm(:))));
assert(permit.authorizedPairCount == 3);
assert(permit.exactArmCountPerPair == 2);
assert(permit.maximumPairedRunCountPerPair == 1);
assert(permit.maximumOfficialAggregateRunCount == 1);
assert(strcmp(permit.outcomeClaimContractVersion, [ ...
    'formation-staggered-recovery-x36-', ...
    'outcome-claim-v1']));
assert(strcmp(permit.outcomeClaimRemoteTagName, ...
    'x36-v37-v3-outcome-consumed-20260803'));
assert(strcmp(permit.outcomeClaimRemoteRef, ...
    ['refs/tags/', permit.outcomeClaimRemoteTagName]));
assert(permit.outcomeClaimRemoteMustBeCreatedAtomically);
assert(permit.outcomeClaimMustCoverAllWorktreesAndClones);
assert(permit.outcomeClaimMustPrecedeTrackingOutcome);
assert(permit.failedClaimConsumesAuthorization);
assert(permit.trackingOutcomeRerunAuthorized);
assert(permit.x36PairedOutcomeRerunAuthorized);
assert(~permit.unrestrictedX36OutcomeOpeningAuthorized);
assert(~permit.overwriteExistingOfficialOutputAuthorized);
assert(~permit.outcomeSelectionOrRankingAuthorized);
assert(~permit.gnnTrainingAuthorized);
assert(~permit.x48OutcomeOpeningAuthorized);
assert(~permit.reservedSeedOpeningAuthorized);
assert(~permit.validationClaimAllowed);
assert(permit.developmentEvidenceOnly);
assert(permit.preflightCompletionMarkerRequired);
assert(permit.authorizedPostPreflightExecutableChangeCount == 6);
assert(isequal(size( ...
    permit.authorizedPostPreflightExecutablePaths), [1, 6]));
assert(any(strcmp(permit.authorizedPostPreflightExecutablePaths, ...
    fullfile('common', ...
        'consumeFormationStaggeredRecoveryX36OutcomePermit.m'))));
assert(permit.authorizedGateCommitChangeCount == 7);
assert(isequal(size(permit.authorizedGateCommitPaths), [1, 7]));
assert(strcmp(permit.authorizedGateCommitPaths{1}, fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'FORMATION_STAGGERED_RECOVERY_X36_V37_DESIGN.md')));

assert(strcmp(computeFileSha256(permit.preflightPath), ...
    permit.preflightSha256));
assert(strcmp(computeFileSha256(permit.preflightReportPath), ...
    permit.preflightReportSha256));
assert(strcmp(computeFileSha256( ...
    permit.preflightCompletionMarkerPath), ...
    permit.preflightCompletionMarkerSha256));
loaded = load(permit.preflightPath, 'preflight');
assert(isfield(loaded, 'preflight'));
preflight = loaded.preflight;
validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    preflight, permit);
assert(strcmp(computeCanonicalValueSha256(preflight.protocol), ...
    permit.sourceProtocolCanonicalSha256));
assert(~preflight.protocol.trackingOutcomeRerunAuthorized);
assert(~preflight.x36PairedOutcomeRerunAuthorized);
assert(preflight.maximumAuthorizedPairCount == 0);
assert(preflight.x36PairedOutcomePermitMayBeMinted);
assert(isequal(preflight.pairedOutcomeEligibilityMask, ...
    true(1, 3)));
assert(isequal(preflight.runtimeFingerprintSha256ByStateArm, ...
    permit.authorizedRuntimeFingerprintSha256ByStateArm));

for pairIdx = 1:permit.authorizedPairCount
    assert(strcmp(computeCanonicalValueSha256( ...
        preflight.pairProposals(pairIdx)), ...
        permit.authorizedPairProposalCanonicalSha256{pairIdx}));
    assert(isequal(preflight.states(pairIdx). ...
        runtimeReplayPassedByArm, true(1, 2)));
    assert(~preflight.states(pairIdx). ...
        runtimeReplays{1}.posteriorUseRequired);
    assert(preflight.states(pairIdx). ...
        runtimeReplays{2}.posteriorUseRequired);
end

invalid = preflight;
invalid.fingerprintDiscoveryMode = true;
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:DirtyPreflightRejected');

invalid = preflight;
invalid.futureLinkUniformsUnavailableToPolicy = false;
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:PreflightBoundaryViolation');

invalid = preflight;
invalid.sourceManifest.sha256{1} = repmat('0', 1, 64);
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:SourceManifestDrift');

invalid = preflight;
invalid.runtimeFingerprintSha256ByStateArm{1, 1} = ...
    repmat('0', 1, 64);
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:PairSetDrift');

invalid = preflight;
invalid.pairProposals = invalid.pairProposals([2, 1, 3]);
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:PairProposalDrift');

invalid = preflight;
invalid.states(1).runtimeReplays{1}.posteriorUseRequired = true;
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:RuntimeReplayDrift');

invalid = preflight;
invalid.states(1).runtimeReplays{2}.oracle = @() 42;
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        invalid, permit), ...
    'X36OutcomePermit:RuntimeReplayDrift');

invalidPermit = permit;
invalidPermit.gnnTrainingAuthorized = true;
invalidPayload = rmfield(invalidPermit, 'permitCanonicalSha256');
invalidPermit.permitCanonicalSha256 = ...
    computeCanonicalValueSha256(invalidPayload);
assertThrowsId(@() ...
    validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        preflight, invalidPermit), ...
    'X36OutcomePermit:PermitScopeDrift');

testAtomicClaim(permit);

gitState = resolveResearchGitState();
if gitState.trackedWorktreeDirty || ...
        ~isempty(gitState.untrackedSourceFiles)
    assertThrowsId(@() ...
        loadFormationStaggeredRecoveryX36OutcomePermit(), ...
        'X36OutcomePermit:DirtySourceRejected');
else
    [descriptorTrackedStatus, ~] = system(sprintf( ...
        'git ls-files --error-unmatch -- ''%s'' >/dev/null 2>&1', ...
        permit.releaseDescriptorPath));
    if exist(permit.releaseDescriptorPath, 'file') ~= 2
        assertThrowsId(@() ...
            loadFormationStaggeredRecoveryX36OutcomePermit(), ...
            'X36OutcomePermit:MissingReleaseDescriptor');
    elseif descriptorTrackedStatus ~= 0
        assertThrowsId(@() ...
            loadFormationStaggeredRecoveryX36OutcomePermit(), ...
            'X36OutcomePermit:UntrackedReleaseDescriptor');
    else
        [loadedPermit, loadedPreflight, releaseDescriptor] = ...
            loadFormationStaggeredRecoveryX36OutcomePermit();
        assert(isequaln(loadedPermit, permit));
        assert(isequaln(loadedPreflight, preflight));
        assert(strcmp(releaseDescriptor.permitCanonicalSha256, ...
            permit.permitCanonicalSha256));
        assert(strcmp(releaseDescriptor.releaseTagName, ...
            permit.releaseTagName));

        probePath = fullfile('tests', ...
            '.x36-outcome-unregistered-executable-probe.p');
        assert(exist(probePath, 'file') == 0, ...
            'The unregistered-executable probe path already exists.');
        probeCleanup = onCleanup(@() deleteIfPresent(probePath));
        probeFile = fopen(probePath, 'w');
        assert(probeFile >= 0, ...
            'Could not create the unregistered-executable probe.');
        probeFileCleanup = onCleanup(@() closeIfOpen(probeFile));
        fwrite(probeFile, 'unregistered executable probe', 'char');
        fclose(probeFile);
        probeFile = -1;
        assertThrowsId(@() ...
            loadFormationStaggeredRecoveryX36OutcomePermit(), ...
            'X36OutcomePermit:UnregisteredExecutableSource');
        clear probeFileCleanup probeCleanup;
        assert(exist(probePath, 'file') == 0, ...
            'The unregistered-executable probe was not cleaned up.');

        visibilityPath = permit. ...
            authorizedPostPreflightExecutablePaths{1};
        [flagStatus, ~] = system(sprintf( ...
            'git update-index --skip-worktree ''%s''', ...
            visibilityPath));
        assert(flagStatus == 0);
        skipCleanup = onCleanup(@() ...
            clearIndexVisibilityFlags(visibilityPath));
        assertThrowsId(@() ...
            loadFormationStaggeredRecoveryX36OutcomePermit(), ...
            'X36OutcomePermit:IndexVisibilityOverrideRejected');
        clear skipCleanup;

        [flagStatus, ~] = system(sprintf( ...
            'git update-index --assume-unchanged ''%s''', ...
            visibilityPath));
        assert(flagStatus == 0);
        assumeCleanup = onCleanup(@() ...
            clearIndexVisibilityFlags(visibilityPath));
        assertThrowsId(@() ...
            loadFormationStaggeredRecoveryX36OutcomePermit(), ...
            'X36OutcomePermit:IndexVisibilityOverrideRejected');
        clear assumeCleanup;
    end
end

fprintf('PASS: v37 X36 v3 exact outcome-permit tests\n');
end

function assertThrowsId(callback, expectedIdentifier)
threw = false;
try
    callback();
catch caught
    threw = true;
    assert(strcmp(caught.identifier, expectedIdentifier), ...
        'Expected %s, got %s.', expectedIdentifier, caught.identifier);
end
assert(threw, 'Expected %s to be thrown.', expectedIdentifier);
end

function testAtomicClaim(permit)
token = computeCanonicalValueSha256(struct( ...
    'tempname', tempname, 'testedAt', datestr(now, 31)));
token = token(1:16);
bareRemotePath = [tempname, '-x36-claim-remote.git'];
[cloneStatus, cloneOutput] = system(sprintf( ...
    'git clone --bare --shared . ''%s'' >/dev/null 2>&1', ...
    bareRemotePath));
assert(cloneStatus == 0, ...
    'Could not create the local bare claim remote: %s', cloneOutput);
bareCleanup = onCleanup(@() ...
    removeDirectoryIfPresent(bareRemotePath));

testPermit = permit;
testPermit.releaseRemoteUrl = bareRemotePath;
testPermit.outcomeClaimCommonDirectoryRelativePath = fullfile( ...
    'codex-outcome-claims', ['test-', token]);
testPermit.outcomeClaimRemoteTagName = ...
    ['x36-v37-v3-outcome-claim-test-', token];
testPermit.outcomeClaimRemoteRef = [ ...
    'refs/tags/', testPermit.outcomeClaimRemoteTagName];
testPayload = rmfield(testPermit, 'permitCanonicalSha256');
testPermit.permitCanonicalSha256 = ...
    computeCanonicalValueSha256(testPayload);
tagCleanup = onCleanup(@() ...
    deleteGitTagIfPresent(testPermit.outcomeClaimRemoteTagName));

testRelease = struct( ...
    'contractVersion', permit.releaseDescriptorContractVersion, ...
    'descriptorCanonicalSha256', repmat('a', 1, 64), ...
    'releaseTagName', permit.releaseTagName, ...
    'releaseTagObjectId', repmat('b', 1, 40), ...
    'gateGitCommit', repmat('c', 1, 40), ...
    'releaseRemoteUrl', bareRemotePath, ...
    'releaseBranchRef', permit.releaseBranchRef, ...
    'remotePublicationRequired', true);
reportPath = [tempname, '.md'];
matPath = [tempname, '.mat'];
completionMarkerPath = [matPath, '.complete'];
[~, generationGitCommit] = system('git rev-parse HEAD');
generationGitCommit = strtrim(generationGitCommit);
rewriteEnvNames = { ...
    'GIT_CONFIG_COUNT', 'GIT_CONFIG_KEY_0', 'GIT_CONFIG_VALUE_0'};
rewriteEnvValues = cellfun(@getenv, rewriteEnvNames, ...
    'UniformOutput', false);
rewriteCleanup = onCleanup(@() ...
    restoreEnvironment(rewriteEnvNames, rewriteEnvValues));
setenv('GIT_CONFIG_COUNT', '1');
setenv('GIT_CONFIG_KEY_0', 'url.fake.insteadof');
setenv('GIT_CONFIG_VALUE_0', testPermit.releaseRemoteUrl);
assertThrowsId(@() ...
    consumeFormationStaggeredRecoveryX36OutcomePermit( ...
        testPermit, testRelease, generationGitCommit, ...
        reportPath, matPath, completionMarkerPath), ...
    'X36OutcomePermit:RemoteUrlRewriteRejected');
clear rewriteCleanup;

[claim, metadataPath] = ...
    consumeFormationStaggeredRecoveryX36OutcomePermit( ...
        testPermit, testRelease, generationGitCommit, ...
        reportPath, matPath, completionMarkerPath);
claimCleanup = onCleanup(@() ...
    removeDirectoryIfPresent(claim.claimDirectory));
assert(exist(claim.claimDirectory, 'dir') == 7);
assert(exist(metadataPath, 'file') == 2);
assert(strcmp(metadataPath, fullfile( ...
    claim.claimDirectory, testPermit.outcomeClaimMetadataFileName)));
assert(claim.remoteClaimCreatedAtomically);
assert(claim.remoteClaimVerifiedAfterPush);
assert(claim.remoteClaimPushPorcelainNewTagConfirmed);
assert(claim.localCommonDirectoryCreatedAtomically);
assert(strcmp(claim.remoteClaimRef, ...
    testPermit.outcomeClaimRemoteRef));
assert(strcmp(claim.remoteClaimTargetCommit, generationGitCommit));
assert(claim.claimConsumedBeforeTrackingOutcome);
assert(claim.failedOrInterruptedRunConsumesAuthorization);
assert(~claim.recoveryRerunAuthorized);
loadedClaim = load(metadataPath, 'claim');
assert(isfield(loadedClaim, 'claim'));
assert(isequaln(loadedClaim.claim, claim));

% A failure after the claim must not make the authorization reusable.
simulatedFailureObserved = false;
try
    error('X36OutcomePermitTest:SimulatedOutcomeFailure', ...
        'Simulated failure after irreversible claim.');
catch caught
    simulatedFailureObserved = strcmp(caught.identifier, ...
        'X36OutcomePermitTest:SimulatedOutcomeFailure');
end
assert(simulatedFailureObserved);
assert(exist(claim.claimDirectory, 'dir') == 7);
assertThrowsId(@() ...
    consumeFormationStaggeredRecoveryX36OutcomePermit( ...
        testPermit, testRelease, generationGitCommit, ...
        reportPath, matPath, completionMarkerPath), ...
    'X36OutcomePermit:AlreadyConsumed');

% Remove only the test mirror and local test tag to emulate a fresh clone.
% The bare remote claim must still reject a second machine-level attempt.
removeDirectoryIfPresent(claim.claimDirectory);
deleteGitTagIfPresent(testPermit.outcomeClaimRemoteTagName);
assertThrowsId(@() ...
    consumeFormationStaggeredRecoveryX36OutcomePermit( ...
        testPermit, testRelease, generationGitCommit, ...
        reportPath, matPath, completionMarkerPath), ...
    'X36OutcomePermit:AlreadyConsumed');
assert(exist(claim.claimDirectory, 'dir') ~= 7);
clear claimCleanup tagCleanup bareCleanup;
end

function result = isSha256(value)
result = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end

function closeIfOpen(fileId)
if fileId >= 0
    try
        fclose(fileId);
    catch
    end
end
end

function deleteIfPresent(path)
if exist(path, 'file') ~= 0
    delete(path);
end
end

function removeDirectoryIfPresent(path)
if exist(path, 'dir') == 7
    rmdir(path, 's');
end
end

function deleteGitTagIfPresent(tagName)
system(sprintf( ...
    'git tag -d ''%s'' >/dev/null 2>&1', tagName));
end

function clearIndexVisibilityFlags(path)
system(sprintf([ ...
    'git update-index --no-skip-worktree ', ...
    '--no-assume-unchanged ''%s'' >/dev/null 2>&1'], path));
end

function restoreEnvironment(names, values)
for idx = 1:numel(names)
    setenv(names{idx}, values{idx});
end
end
