function test_lmb_reference_existence_retention_risk()
% TEST_LMB_REFERENCE_EXISTENCE_RETENTION_RISK Synthetic guard regression.

labels = [1, 1; 1, 2];
reference = { ...
    deterministicDistribution(labels, [0.80, 0.20]), ...
    deterministicDistribution(labels, [0.70, 0.30]), ...
    deterministicDistribution(labels, [0.75, 0.25]), ...
    deterministicDistribution(labels, [0.65, 0.35])};
groupIds = [1, 1, 2, 2];

[identityRisk, identity] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        reference, reference, groupIds);
assert(abs(identityRisk) < 1e-12);
assert(all(abs(identity.expectedCardinalityChange) < 1e-12));
assert(all(identity.minimumSupportedLabelRetentionRatio == 1));
assert(~identity.truthUsed && ~identity.futureOutcomeUsed);

suppressed = reference;
suppressed{2} = deterministicDistribution(labels, [0.20, 0.20]);
[suppressedRisk, suppressedDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        reference, suppressed, groupIds);
assert(suppressedRisk > 0);
assert(suppressedDetails.expectedCardinalityChange(2) < 0);
assert(suppressedDetails.decisionThresholdCrossingCount(2) == 1);
assert(suppressedDetails.minimumSupportedLabelRetentionRatio(2) < 1);
assert(suppressedDetails.formationRisk(1) > 0);
assert(abs(suppressedDetails.formationRisk(2)) < 1e-12);

strengthened = reference;
strengthened{2} = deterministicDistribution(labels, [0.90, 0.30]);
[strengthenedRisk, strengthenedDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        reference, strengthened, groupIds);
assert(abs(strengthenedRisk) < 1e-12);
assert(strengthenedDetails.expectedCardinalityChange(2) > 0);
assert(strengthenedDetails.normalizedExistenceDrift(2) > 0);
assert(strengthenedDetails.decisionThresholdCrossingCount(2) == 0);

uncertainReference = reference;
uncertainCandidate = reference;
uncertainReference{1} = probabilisticDistribution( ...
    labels, [0.75, 0.25], [0.65, 0.15]);
uncertainCandidate{1} = probabilisticDistribution( ...
    labels, [0.70, 0.20], [0.55, 0.10]);
[uncertainRisk, uncertainDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        uncertainReference, uncertainCandidate, groupIds);
assert(uncertainRisk > 0);
assert(abs(uncertainDetails. ...
    expectedReferenceExistenceByReceiver{1}(1) - 0.70) < 1e-12);
assert(abs(uncertainDetails. ...
    expectedCandidateExistenceByReceiver{1}(1) - 0.625) < 1e-12);

fprintf('PASS: LMB reference existence-retention risk tests\n');
end

function distribution = deterministicDistribution(labels, existence)
distribution = struct( ...
    'probability', 1, ...
    'summary', {{summary(labels, existence)}});
end

function distribution = probabilisticDistribution( ...
        labels, firstExistence, secondExistence)
distribution = struct( ...
    'probability', [0.5, 0.5], ...
    'summary', {{ ...
        summary(labels, firstExistence), ...
        summary(labels, secondExistence)}});
end

function value = summary(labels, existence)
value = struct( ...
    'labels', labels, ...
    'existence', reshape(existence, 1, []));
end
