function test_topology_policy_delivery_history_context()
% Past delivery ACKs enter the policy only as a causal attempted-edge subset.

global topologyPolicyDeliveryHistoryTestState;
cleanup = onCleanup(@clearTestState); %#ok<NASGU>
sensorCount = 2;
timeCount = 3;
model = generateMultisensorModel( ...
    sensorCount, zeros(1, sensorCount), ...
    0.9 * ones(1, sensorCount), ...
    3 * ones(1, sensorCount), 'GA', 'LBP');
sceneConfig = struct( ...
    'formationCount', 2, 'sensorsPerFormation', 1, ...
    'sensorCenterWaypoints', {{[0; 0], [10; 0]}}, ...
    'sensorGroupIds', [1, 2]);
identity = buildDynamicTopologyPhysicalIdentityRegistry(sceneConfig);
sceneConfig.sensorPhysicalUids = identity.sensorPhysicalUids;
sceneConfig.formationPhysicalUidsBySensor = ...
    identity.formationPhysicalUidsBySensor;
sceneConfig.sensorLocalRoleUidsByFormation = ...
    identity.sensorLocalRoleUidsByFormation;
sceneConfig.physicalIdentityRegistryCanonicalSha256 = ...
    identity.canonicalSha256;
model.dynamicTopologyScenario = struct('config', sceneConfig);
model.simulationLength = timeCount;

measurements = repmat({{}}, sensorCount, timeCount);
sensorTrajectories = {zeros(4, timeCount), ...
    repmat([10; 0; 0; 0], 1, timeCount)};
neighborMap = {[1, 2], [1, 2]};
pDrop = zeros(sensorCount, sensorCount, timeCount);
uniforms = 0.5 * ones(sensorCount, sensorCount, timeCount);
uniforms(1, 2, 1) = 0.1;
pDrop(1, 2, 1) = 0.2;
commConfig = struct('pDropByEdge', pDrop, ...
    'linkUniforms', uniforms);
triggerConfig = struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false, ...
    'dynamicTopologyEnabled', true, ...
    'dynamicTopologyEdgeBudget', 1, ...
    'topologyDirectedEnabled', true, ...
    'topologyDirectedMessageBudget', 2, ...
    'topologyPolicyFcn', @captureDeliveryHistoryPolicy, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicyPhysicalIdentityEnabled', true, ...
    'topologyPolicyDeliveryHistoryEnabled', true, ...
    'topologyPolicyHistoryDepth', 3);

topologyPolicyDeliveryHistoryTestState = struct( ...
    'captured', {cell(1, timeCount)});
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig);

for currentTime = 1:timeCount
    context = topologyPolicyDeliveryHistoryTestState. ...
        captured{currentTime};
    expectedTimes = 1:(currentTime - 1);
    expected = permute(logical( ...
        diagnostics.delivered(:, :, expectedTimes)), [2, 1, 3]);
    assert(strcmp(context.observableInputContract.contractVersion, ...
        ['topology-policy-observable-input-v4-', ...
         'physical-uid-delivery-history']));
    assert(context.observableInputContract.passed);
    assert(context.observableInputContract.deliveryHistoryPresent);
    assert(context.observableInputContract.pastDeliveryHistoryOnly);
    assert(context.observableInputContract. ...
        deliveryHistoryAlignedToTopologyHistory);
    assert(context.observableInputContract.deliveryHistoryAttemptSubset);
    assert(isequal(context.previousDeliveryHistoryTimes, ...
        expectedTimes));
    assert(isequal(context.previousDeliveryHistory, expected));
    assert(all(~context.previousDeliveryHistory(:) | ...
        context.previousAdjacencyHistory(:)));
end

tampered = topologyPolicyDeliveryHistoryTestState.captured{2};
tampered = rmfield(tampered, 'observableInputContract');
tampered.previousDeliveryHistory(1, 1, 1) = true;
assertErrorId(@() buildObservableTopologyPolicyContext(tampered), ...
    'ObservableTopologyContext:ContractViolation');

incomplete = topologyPolicyDeliveryHistoryTestState.captured{2};
incomplete = rmfield(incomplete, { ...
    'observableInputContract', 'previousDeliveryHistorySource'});
assertErrorId(@() buildObservableTopologyPolicyContext(incomplete), ...
    'ObservableTopologyContext:IncompleteDeliveryHistory');

fprintf('PASS: topology-policy delivery-history context tests\n');
end

function [adjacency, details] = captureDeliveryHistoryPolicy(context)
global topologyPolicyDeliveryHistoryTestState;
topologyPolicyDeliveryHistoryTestState.captured{context.currentTime} = ...
    context;
adjacency = logical([0, 1; 1, 0]);
details = struct('truthUsed', false, 'futureOutcomeUsed', false);
end

function assertErrorId(callback, expectedIdentifier)
actual = '';
try
    callback();
catch errorInfo
    actual = errorInfo.identifier;
end
assert(strcmp(actual, expectedIdentifier), ...
    'Expected %s, received %s.', expectedIdentifier, actual);
end

function clearTestState()
global topologyPolicyDeliveryHistoryTestState;
topologyPolicyDeliveryHistoryTestState = [];
end
