function test_bounded_transfer_runtime_v226()
% TEST_BOUNDEDTRANSFERRUNTIMEV226 One-page receiver-specific integration.

[model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig] = buildSyntheticCase();
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    model, measurements, sensorTrajectories, neighborMap, ...
    commConfig, triggerConfig);

page = diagnostics.budgetRecycledFormationRepairDetails{2};
assert(page.transportDelivered);
assert(page.chargedAttemptedBytes == 560);
assert(page.chargedDeliveredBytes == page.chargedAttemptedBytes);
assert(isequal(page.etaProjectionEvaluatedReceiverIds, [1, 2]));
assert(isequal(page.etaProjectionAllowedReceiverIds, [1, 2]));
assert(isempty(page.etaProjectionRejectedReceiverIds));
assert(page.applyDetails.appliedActionCount == 1);
protocol = getBoundedDominantEdgeTransferV226Protocol();
for receiverIdx = [1, 2]
    detail = page.etaProjectionByReceiver{receiverIdx};
    assert(detail.allowed);
    assert(detail.fullPayloadChargedBeforeProjection);
    assert(~detail.transferFractionReducesPayloadCharge);
    assert(detail.allRegisteredFractionsEvaluated);
    assert(isequal(detail.attemptedTransferFractions, ...
        protocol.transferFractionGrid));
    assert(abs(detail.selectedTransferFraction - 1) <= 1e-12);
    override = detail.routingOverride;
    assert(strcmp(override.mode, ...
        'bounded-dominant-nonself-transfer'));
    assert(abs(override.transferFraction - 1) <= 1e-12);
    assert(override.transferredTopologyWeight > 0);
end
fprintf('test_bounded_transfer_runtime_v226 passed\n');
end

function [model, measurements, sensorTrajectories, neighborMap, ...
        commConfig, triggerConfig] = buildSyntheticCase()
nodeCount = 4;
timeCount = 2;
model = generateMultisensorModel( ...
    nodeCount, zeros(1, nodeCount), 0.9 * ones(1, nodeCount), ...
    3 * ones(1, nodeCount), 'GA', 'LBP');
model.simulationLength = timeCount;
model.sensorCommRange = inf;
model.rB(:) = 0.90;
model.rBLmbm(:) = 0.90;
[model.birthParameters.r] = deal(0.90);

sceneConfig = struct();
sceneConfig.formationCount = 2;
sceneConfig.sensorsPerFormation = 2;
sceneConfig.numberOfSensors = nodeCount;
sceneConfig.sensorCenterWaypoints = {[-10; 0], [10; 0]};
sceneConfig.sensorGroupIds = [1, 1, 2, 2];
identity = buildDynamicTopologyPhysicalIdentityRegistry(sceneConfig);
sceneConfig.sensorPhysicalUids = identity.sensorPhysicalUids;
sceneConfig.formationPhysicalUidsBySensor = ...
    identity.formationPhysicalUidsBySensor;
sceneConfig.sensorLocalRoleUidsByFormation = ...
    identity.sensorLocalRoleUidsByFormation;
sceneConfig.physicalIdentityRegistryCanonicalSha256 = ...
    identity.canonicalSha256;
sensorMetadata = struct( ...
    'sensorPhysicalUids', identity.sensorPhysicalUids, ...
    'formationPhysicalUidsBySensor', ...
        identity.formationPhysicalUidsBySensor, ...
    'physicalIdentityRegistryCanonicalSha256', ...
        identity.canonicalSha256);
model.dynamicTopologyScenario = struct( ...
    'config', sceneConfig, 'sensor', sensorMetadata);

positions = [-12, -8, 8, 12; 0, 0, 0, 0];
sensorTrajectories = cell(1, nodeCount);
for sensorIdx = 1:nodeCount
    sensorTrajectories{sensorIdx} = [ ...
        repmat(positions(:, sensorIdx), 1, timeCount); ...
        zeros(2, timeCount)];
end
measurements = repmat({{}}, nodeCount, timeCount);
neighborMap = cell(1, nodeCount);
for receiverIdx = 1:nodeCount
    neighborMap{receiverIdx} = 1:nodeCount;
end
commConfig = struct( ...
    'forceDelivery', true, ...
    'pDropByEdge', zeros(nodeCount, nodeCount, timeCount), ...
    'linkUniforms', 0.5 * ones(nodeCount, nodeCount, timeCount));
protocol = getBoundedDominantEdgeTransferV226Protocol();
triggerConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'budgetRecycledFormationRepairEnabled', true, ...
    'budgetRecycledFormationRepairTimes', 2, ...
    'budgetRecycledFormationRepairReferenceAttemptedBytes', 1e8, ...
    'budgetRecycledFormationRepairIdealDeliveryTeacherMode', true, ...
    'budgetRecycledFormationRepairMaximumActions', 1, ...
    'budgetRecycledFormationRepairForcedFormationId', 1, ...
    'budgetRecycledFormationRepairForcedSourceId', 4, ...
    'budgetRecycledFormationRepairForcedLabel', [1; 1], ...
    'budgetRecycledFormationRepairTargetFormationId', 1, ...
    'budgetRecycledFormationRepairUpdateMode', ...
        'single-pass-label-kla', ...
    'budgetRecycledFormationRepairSourceWeight', 0.10, ...
    'budgetRecycledFormationRepairInputRouteSynopsisBytes', 0, ...
    'budgetRecycledFormationRepairInputRouteUtilityLowerBound', 1, ...
    'budgetRecycledFormationRepairInputRouteWeightMode', ...
        protocol.inputRouteWeightMode, ...
    'budgetRecycledFormationRepairInputRouteEtaProjectionEnabled', true, ...
    'budgetRecycledFormationRepairInputRouteMinimumMapExistence', ...
        protocol.minimumMapExistence, ...
    'budgetRecycledFormationRepairInputRouteMaximumReferenceLogOddsDrop', ...
        protocol.maximumReferenceLogOddsDrop, ...
    'budgetRecycledFormationRepairInputRouteMaximumReferenceLogOddsIncrease', ...
        protocol.maximumReferenceLogOddsIncrease, ...
    'budgetRecycledFormationRepairInputRouteTransferFractionGrid', ...
        protocol.transferFractionGrid, ...
    'budgetRecycledFormationRepairInputRouteEtaIdentityTolerance', ...
        protocol.identityTolerance));
end
