function test_formation_backbone_bundle_m24_frozen_source_gate()
% TEST_FORMATIONBACKBONEBUNDLEM24FROZENSOURCEGATE Exact-input tamper gate.

protocol = getFormationBackboneBundleM24DevelopmentProtocol();
caseContract = protocol.cases(1);
source = prepareFormationBackboneBundleM24SourceCaseInputs( ...
    caseContract.presetName, caseContract.seed);
assert(isequaln(source.inputFingerprint, ...
    caseContract.sourceInputFingerprint));
[triggerConfig, ~] = ...
    buildFormationBackboneBundleM24SourceTriggerConfig( ...
        caseContract.presetName);
context = ...
    buildFormationBackboneBundleM24SourceExecutionContext( ...
        caseContract.presetName, caseContract.seed);
request = buildRuntimeRequest(source, triggerConfig);
authorization = ...
    validateFormationBackboneBundleM24SourceExecution( ...
        source.model, context, request);
assert(strcmp(authorization.mode, 'registered-case-permit'));
assert(~authorization.stateEstimateOutputAuthorized);
assert(~authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.groundTruthAccessAuthorized);
assert(~authorization.futureOutcomeAccessAuthorized);
assert(~authorization.validationClaimAllowed);

changedMeasurements = source.measurements;
measurementIdx = find(~cellfun(@isempty, changedMeasurements), 1);
assert(~isempty(measurementIdx));
measurementSet = changedMeasurements{measurementIdx};
assert(iscell(measurementSet) && ~isempty(measurementSet));
vectorIdx = find(cellfun( ...
    @(value) isnumeric(value) && ~isempty(value), ...
    measurementSet), 1);
assert(~isempty(vectorIdx));
changedVector = measurementSet{vectorIdx};
changedVector(1) = changedVector(1) + 1e-6;
measurementSet{vectorIdx} = changedVector;
changedMeasurements{measurementIdx} = measurementSet;
assertPublicFilterError(source.model, changedMeasurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    source.commConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');

changedTrajectories = source.sensorTrajectories;
changedTrajectories{1}(1, 1) = ...
    changedTrajectories{1}(1, 1) + 1e-6;
assertPublicFilterError(source.model, source.measurements, ...
    changedTrajectories, source.neighborMap, source.commConfig, ...
    triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');

changedNeighborMap = source.neighborMap;
assert(~isempty(changedNeighborMap{1}));
changedNeighborMap{1}(end) = [];
assertPublicFilterError(source.model, source.measurements, ...
    source.sensorTrajectories, changedNeighborMap, ...
    source.commConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');

changedCommConfig = source.commConfig;
originalUniform = changedCommConfig.linkUniforms(1, 2, 1);
if originalUniform < 0.5
    changedCommConfig.linkUniforms(1, 2, 1) = ...
        originalUniform + 0.25;
else
    changedCommConfig.linkUniforms(1, 2, 1) = ...
        originalUniform - 0.25;
end
assertPublicFilterError(source.model, source.measurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    changedCommConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');

changedModel = source.model;
changedModel.sourceInputTamperProbe = true;
assertPublicFilterError(changedModel, source.measurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    source.commConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');

changedTrigger = triggerConfig;
changedTrigger.topologyDirectedMessageBudget = ...
    changedTrigger.topologyDirectedMessageBudget - 1;
changedRequest = request;
changedRequest.triggerConfig = changedTrigger;
assertErrorId(@() ...
    validateFormationBackboneBundleM24SourceExecution( ...
        source.model, context, changedRequest), ...
    'FormationBundleSourcePermit:TriggerConfigDrift');

shortMeasurements = source.measurements(:, 1:end-1);
assertPublicFilterError(source.model, shortMeasurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    source.commConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:RuntimeWindowDrift');

otherContext = ...
    buildFormationBackboneBundleM24SourceExecutionContext( ...
        caseContract.presetName, protocol.seeds(2));
assertPublicFilterError(source.model, source.measurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    source.commConfig, triggerConfig, otherContext, ...
    'FormationBundleSourcePermit:SourceInputDrift');

truthModel = source.model;
truthModel.groundTruth = {ones(4, caseContract.sourceWindow(2))};
assertPublicFilterError(truthModel, source.measurements, ...
    source.sensorTrajectories, source.neighborMap, ...
    source.commConfig, triggerConfig, context, ...
    'FormationBundleSourcePermit:SourceInputDrift');
assertErrorId(@() ...
    validateFormationBackboneBundleM24SourceExecution( ...
        truthModel, context, request), ...
    'FormationBundleSourcePermit:TargetTruthPresent');

changedCaseModel = source.model;
changedCaseModel.dynamicTopologyScenario.seed = protocol.seeds(2);
assertErrorId(@() ...
    validateFormationBackboneBundleM24SourceExecution( ...
        changedCaseModel, context, request), ...
    'FormationBundleSourcePermit:CaseMismatch');

changedConfigModel = source.model;
changedConfigModel.dynamicTopologyScenario.config.edgeBudget = ...
    changedConfigModel.dynamicTopologyScenario.config.edgeBudget + 1;
assertErrorId(@() ...
    validateFormationBackboneBundleM24SourceExecution( ...
        changedConfigModel, context, request), ...
    'FormationBundleSourcePermit:SceneConfigDrift');

fprintf('PASS: frozen M24 source-input tamper gate tests\n');
end

function request = buildRuntimeRequest(source, triggerConfig)
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', size(source.measurements, 2), ...
    'sensorTrajectoryTimeCounts', ...
        cellfun(@(value) size(value, 2), ...
            source.sensorTrajectories), ...
    'triggerConfig', triggerConfig, ...
    'inputFingerprint', source.inputFingerprint);
end

function assertPublicFilterError(model, measurements, trajectories, ...
        neighborMap, commConfig, triggerConfig, context, expectedIdentifier)
assertErrorId(@() runEventTriggeredDistributedLmbFilter( ...
    model, measurements, trajectories, neighborMap, ...
    commConfig, triggerConfig, context), expectedIdentifier);
end

function assertErrorId(callback, expectedIdentifier)
failed = false;
actualIdentifier = '';
try
    callback();
catch errorInfo
    actualIdentifier = errorInfo.identifier;
    failed = strcmp(actualIdentifier, expectedIdentifier);
end
assert(failed, 'Expected %s, received %s.', ...
    expectedIdentifier, actualIdentifier);
end
