function test_positive_net_addressable_payload_v97()
% TEST_POSITIVE_NETADDRESSABLEPAYLOADV97 Selector and runtime boundary.

metrics = struct( ...
    'groups', [1, 2, 3, 4, 5], ...
    'networkRescueFractionByFormation', ...
        [0.10, 0.30, 0.20, 0.40, 0.05], ...
    'networkUsefulLossFractionByFormation', ...
        [0.01, 0.01, 0.25, 0.10, 0.05], ...
    'singleActionAvailableMask', true(1, 5), ...
    'crossSupportedDownwardCrossingsByFormation', [0, 1, 0, 0, 0]);
selection = selectPositiveNetAddressableRiskSetV97(metrics, struct());
assert(selection.actionEnabled);
assert(abs(selection.totalNetworkRiskFraction - 1.05) < 1e-12);
assert(abs(selection.addressableNetworkRiskFraction - 0.75) < 1e-12);
assert(isequal(selection.addressableBasisFormationIds, [1, 3, 4, 5]));
assert(isequal(selection.selectedFormationIds, [1, 4]));
assert(isequal(selection.nonpositiveNetFormationIds, [3, 5]));
assert(selection.selectedNetworkNetBenefitFraction > 0);
assert(selection.usefulLossToRescueRatio < 1);

protocol = getPositiveNetAddressablePayloadV97Protocol();
assert(numel(protocol.cases) == 2);
assert(strcmp(protocol.receiverMode, 'fov-aware-censored'));
entry = protocol.cases(2);
currentTime = entry.anchorTimes(1);
context = buildPositiveNetAddressablePayloadV97ExecutionContext( ...
    entry.presetName, entry.seed, currentTime, ...
    'v97-positive-net-persistent-f1-f2-f4-f5', true);
assert(isPositiveNetAddressablePayloadV97ExecutionContext(context));

model = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
schedule = { ...
    [1, 2, 4, 5], [1, 2, 4, 5], [1, 2, 4, 5]};
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', ...
            currentTime + (0:(protocol.horizonSteps - 1)), ...
        'receiverSafeFormationConditionedSchedule', {schedule}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'control-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    model, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));
end
