function test_task_risk_input_protection_v92()
% TEST_TASK_RISK_INPUT_PROTECTION_V92 Focused task-risk contract checks.

model = struct();
model.ospaParameters = struct('eC', 5);
low = makeSummary(0.90, eye(2));
high = makeSummary(0.50, 9 * eye(2));
lowDetails = makeNetworkDetails({ ...
    makeDistribution([1], {low}), ...
    makeDistribution([1], {low})});
highDetails = makeNetworkDetails({ ...
    makeDistribution([1], {high}), ...
    makeDistribution([1], {high})});
[lowRisk, lowResult] = computeExpectedLmbPosteriorTaskRiskV92( ...
    lowDetails, [1, 2], model);
[highRisk, highResult] = computeExpectedLmbPosteriorTaskRiskV92( ...
    highDetails, [1, 2], model);
assert(highRisk > lowRisk);
assert(highResult.maximumReceiverRisk > ...
    lowResult.maximumReceiverRisk);
assert(~lowResult.eospaEqualityClaimed);
assert(~lowResult.recursiveTrackingGuaranteeClaimed);

mixed = makeNetworkDetails({ ...
    makeDistribution([0.25, 0.75], {low, high}), ...
    makeDistribution([1], {low})});
[mixedRisk, mixedResult] = ...
    computeExpectedLmbPosteriorTaskRiskV92( ...
        mixed, [1, 2], model, struct( ...
            'receiverTailFraction', 0.5, ...
            'receiverTailWeight', 0.5));
assert(mixedRisk > lowRisk);
assert(mixedResult.expectedReceiverRisk(1) > ...
    mixedResult.expectedReceiverRisk(2));
assert(abs(mixedResult.positionCutoff - 5) < 1e-12);

protocol = getTaskRiskInputProtectionV92Protocol();
assert(strcmp(protocol.receiverMode, 'fov-aware-censored'));
assert(strcmp(protocol.referenceMode, 'current-physical-tree'));
assert(protocol.minimumFullEpisodeMeanGainPercent == 5);
assert(~protocol.routeExecutionAuthorized);
assert(~protocol.trackingOutcomeScoringAuthorized);
fprintf('PASS: V92 task-risk input-protection contract\n');
end

function details = makeNetworkDetails(distributions)
details = struct('receiverDistributions', {distributions});
end

function distribution = makeDistribution(probability, summaries)
distribution = struct( ...
    'probability', probability, ...
    'summary', {summaries});
end

function summary = makeSummary(existence, covariance)
summary = struct( ...
    'labels', [1; 1], ...
    'existence', existence, ...
    'positionMean', zeros(2, 1), ...
    'positionCovariance', reshape(covariance, 2, 2, 1));
end
