function testFormationB4V49TimeVaryingB4StructuralReplay()
% Current-page cycle policy and actual four-page structural replay contract.

result = runFormationB4V49TimeVaryingB4StructuralReplay(struct( ...
    'presets', {{'m24-formation-fov-convoy'}}, ...
    'seeds', 41, 'windowMode', 'focus-start'));
repeat = runFormationB4V49TimeVaryingB4StructuralReplay(struct( ...
    'presets', {{'m24-formation-fov-convoy'}}, ...
    'seeds', 41, 'windowMode', 'focus-start'));
assert(result.caseCount == 1 && result.windowCount == 1);
assert(strcmp(result.canonicalSha256, repeat.canonicalSha256));
assert(result.wallClockTimingExcludedFromCanonicalSha256);
assert(result.cycleSelectedWindowCount == 1);
assert(result.realizedPositiveWindowCount == 1 && ...
    result.realizedNegativeWindowCount == 0);
assert(result.realizedNoWorseWindowFraction == 1);
assert(result.allSamePosteriorMessageBudget);
assert(result.allBurstSensorStrongConnected && ...
    result.allBurstFormationStrongConnected);
assert(result.currentBurstPageUsedByPolicy && ...
    ~result.futurePagesUsedByPolicy && ...
    result.futurePagesUsedByPosthocAudit);
assert(~result.posteriorUsed && ~result.truthUsed && ...
    ~result.measurementUsed && ...
    ~result.realizedDeliveryUniformsUsed && ...
    ~result.trackingOutcomeScored);
assert(~result.routeDisseminationImplemented && ...
    ~result.atomicCommitImplemented && ...
    ~result.sameTotalByteClaimAllowed && ...
    ~result.timeVaryingNoWorseCertified && ...
    ~result.validationClaimAllowed && ...
    result.developmentEvidenceOnly);

item = result.cases(1);
window = item.windows(1);
assert(item.wallClockTimingExcludedFromCanonicalSha256 && ...
    window.wallClockTimingExcludedFromCanonicalSha256);
assert(window.cycleSelected && ...
    ~window.selectedUsedIncumbentFallback);
assert(window.planningRelativeImprovement > 0.01 && ...
    window.realizedRelativeImprovement > 0.01);
assert(window.samePosteriorMessageBudget);
assert(isequal(window.incumbentMessageCountByPhase, ...
    [2 * item.nodeCount, item.nodeCount, item.nodeCount, item.nodeCount]));
assert(isequal(window.candidateMessageCountByPhase, ...
    [2 * item.nodeCount, item.nodeCount, item.nodeCount, item.nodeCount]));
assert(~window.formationCycleChangedFromPreviousWindow);
assert(window.formationCyclePairSymmetricDifferenceCount == 0);
assert(window.crossResidualGatewaySymmetricDifferenceCount == 0);
assert(all(window.selectedCycleFormationPairPhysicalUidTable(:, 1) < ...
    window.selectedCycleFormationPairPhysicalUidTable(:, 2)));
assert(window.currentBurstPageUsedByPolicy && ...
    ~window.futurePagesUsedByPolicy && ...
    window.futurePagesUsedByPosthocAudit && ...
    window.cycleUsedOnBurstPageOnly);
assert(~window.posteriorUsed && ~window.truthUsed && ...
    ~window.measurementUsed && ...
    ~window.realizedDeliveryUniformsUsed && ...
    ~window.trackingOutcomeScored && ...
    ~window.sameTotalByteClaimAllowed && ...
    ~window.timeVaryingNoWorseCertified && ...
    window.developmentEvidenceOnly);

fprintf('PASS: FormationB4V49 time-varying B4 structural replay tests\n');
end
