function test_formation_staggered_recovery_x36_outcome_permit()
% TEST_FORMATIONSTAGGEREDRECOVERYX36OUTCOMEPERMIT Exact v37 permit gate.

assert(nargin('getFormationStaggeredRecoveryX36OutcomePermit') == 0);
assert(nargout('getFormationStaggeredRecoveryX36OutcomePermit') == 1);
assert(nargin('loadFormationStaggeredRecoveryX36OutcomePermit') == 0);
assert(nargout('loadFormationStaggeredRecoveryX36OutcomePermit') == 2);
assert(nargin( ...
    'validateFormationStaggeredRecoveryX36OutcomePreflight') == 2);
assert(nargout( ...
    'validateFormationStaggeredRecoveryX36OutcomePreflight') == 0);

permit = getFormationStaggeredRecoveryX36OutcomePermit();
permitPayload = rmfield(permit, 'permitCanonicalSha256');
assert(strcmp(permit.permitCanonicalSha256, ...
    computeCanonicalValueSha256(permitPayload)));
assert(strcmp(permit.contractVersion, ...
    'formation-staggered-recovery-x36-outcome-permit-v1'));
assert(strcmp(permit.authorizedRunnerContractVersion, [ ...
    'formation-staggered-recovery-x36-v37-', ...
    'exact-two-arm-runner-v1']));
assert(strcmp(permit.sourceProtocolContractVersion, ...
    'formation-staggered-recovery-x36-source-protocol-v2'));
assert(strcmp(permit.sourceProtocolCanonicalSha256, [ ...
    '04c1fae3dcbc72872f5659bc8c502e39f0e1c27122b244be', ...
    '524e84054668e8b6']));
assert(strcmp(permit.preflightSha256, [ ...
    'de3b17cc5f67427f5c530a6d61232c34bde467ca9d3b93e', ...
    'be9dd577610180d64']));
assert(strcmp(permit.preflightGenerationGitCommit, ...
    '57f65d0b860755157a5af7d65be8073bea065574'));
assert(isequal(permit. ...
    authorizedPairProposalCanonicalSha256, { ...
    '689b1655c7e398e978efcb80d8b567897b5374e513e3ac7043c97586130e1c59', ...
    '4850d890465417f7167e782ff02a1b093c9d2f96cfba07714d256b1e4562f1ae', ...
    '1c941e9ff49123899360065f4d0dc2599fc2de07c121f90df60cce7fe9a791cd'}));
assert(permit.authorizedPairCount == 3);
assert(permit.exactArmCountPerPair == 2);
assert(permit.maximumPairedRunCountPerPair == 1);
assert(permit.maximumOfficialAggregateRunCount == 1);
assert(permit.trackingOutcomeRerunAuthorized);
assert(permit.x36PairedOutcomeRerunAuthorized);
assert(~permit.unrestrictedX36OutcomeOpeningAuthorized);
assert(~permit.overwriteExistingOfficialOutputAuthorized);
assert(~permit.outcomeSelectionOrRankingAuthorized);
assert(~permit.gnnTrainingAuthorized);
assert(~permit.x48OutcomeOpeningAuthorized);
assert(~permit.reservedSeedOpeningAuthorized);
assert(~permit.validationClaimAllowed);
assert(permit.developmentEvidenceOnly);

assert(strcmp(computeFileSha256(permit.preflightPath), ...
    permit.preflightSha256));
loaded = load(permit.preflightPath, 'preflight');
assert(isfield(loaded, 'preflight'));
preflight = loaded.preflight;
validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    preflight, permit);
assert(strcmp(computeCanonicalValueSha256(preflight.protocol), ...
    permit.sourceProtocolCanonicalSha256));
assert(~preflight.protocol.trackingOutcomeRerunAuthorized);
assert(~preflight.x36PairedOutcomeRerunAuthorized);
assert(preflight.maximumAuthorizedPairCount == 0);
assert(preflight.x36PairedOutcomePermitMayBeMinted);

invalid = preflight;
invalid.contractVersion = ...
    'formation-staggered-recovery-x36-v37-preflight-v1';
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PreflightContractMismatch');

invalid = preflight;
invalid.matPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v37', 'x36_source', ...
    'revoked_v1_preflight_3465f61', ...
    'FORMATION_STAGGERED_RECOVERY_X36_V37_PREFLIGHT.mat');
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PreflightPathMismatch');

invalid = preflight;
invalid.fingerprintDiscoveryMode = true;
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:DiscoveryArtifactRejected');

invalid = preflight;
invalid.generationTrackedWorktreeDirty = true;
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:DirtyPreflightRejected');
invalid = preflight;
invalid.generationUntrackedSourceFiles = {'common/rogue_source.m'};
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:DirtyPreflightRejected');

invalid = preflight;
invalid.generationGitCommit = ...
    '0000000000000000000000000000000000000000';
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PreflightGenerationDrift');

invalid = preflight;
invalid.protocol.trackingOutcomeRerunAuthorized = true;
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:SourceProtocolDrift');
invalid = preflight;
invalid.x36PairedOutcomeRerunAuthorized = true;
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PreflightAuthorizationMismatch');

for pairIdx = 1:permit.authorizedPairCount
    invalid = preflight;
    invalid.pairProposals(pairIdx). ...
        candidateNominalActionSequenceIndices(end) = 2;
    assertThrowsId( ...
        @() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
            invalid, permit), ...
        'X36OutcomePermit:PairProposalDrift');
end
invalid = preflight;
invalid.pairProposals = invalid.pairProposals([2, 1, 3]);
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PairProposalDrift');
invalid = preflight;
invalid.pairProposals(4) = invalid.pairProposals(3);
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    invalid, permit), ...
    'X36OutcomePermit:PairSetDrift');

invalidPermit = permit;
invalidPermit.validationClaimAllowed = true;
assertThrowsId(@() validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    preflight, invalidPermit), ...
    'X36OutcomePermit:PermitHashDrift');

gitState = resolveResearchGitState();
if gitState.trackedWorktreeDirty || ...
        ~isempty(gitState.untrackedSourceFiles)
    assertThrowsId( ...
        @() loadFormationStaggeredRecoveryX36OutcomePermit(), ...
        'X36OutcomePermit:DirtySourceRejected');
else
    [loadedPermit, loadedPreflight] = ...
        loadFormationStaggeredRecoveryX36OutcomePermit();
    assert(isequaln(loadedPermit, permit));
    assert(isequaln(loadedPreflight, preflight));
end

fprintf('PASS: v37 X36 exact outcome-permit tests\n');
end

function assertThrowsId(callback, expectedIdentifier)
threw = false;
try
    callback();
catch caught
    threw = true;
    if ~strcmp(caught.identifier, expectedIdentifier)
        error('X36OutcomePermitTest:UnexpectedError', ...
            'Expected %s but received %s: %s', ...
            expectedIdentifier, caught.identifier, caught.message);
    end
end
if ~threw
    error('X36OutcomePermitTest:MissingError', ...
        'Expected error %s was not raised.', expectedIdentifier);
end
end
