function test_formation_fov_scenarios()
% TEST_FORMATION_FOV_SCENARIOS Focused realistic-FoV scene contract tests.

presets = { ...
    'm24-formation-fov', ...
    'x36-formation-fov', ...
    'x48-formation-fov'};
expectedSensors = [24, 36, 48];
expectedTargets = [16, 24, 32];
validatedMetrics = repmat(struct(), 1, numel(presets));
configs = cell(1, numel(presets));
sensorSets = cell(1, numel(presets));
targetSets = cell(1, numel(presets));
graphSets = cell(1, numel(presets));

for presetIdx = 1:numel(presets)
    rng(41);
    config = buildDynamicTopologyScenarioConfig(presets{presetIdx});
    configs{presetIdx} = config;
    [sensorTrajectories, ~] = ...
        generateMultiFormationTrajectories(config);
    [targetTrajectories, ~] = ...
        generateCorridorTargetTrajectories(config);
    graphData = buildDynamicTopologyGraphs(config, sensorTrajectories);
    sensorSets{presetIdx} = sensorTrajectories;
    targetSets{presetIdx} = targetTrajectories;
    graphSets{presetIdx} = graphData;
    validation = validateDynamicTopologyScenario( ...
        config, sensorTrajectories, targetTrajectories, graphData);
    assert(validation.isValid);
    assert(config.numberOfSensors == expectedSensors(presetIdx));
    assert(config.numberOfTargets == expectedTargets(presetIdx));
    assert(config.fovHalfAngleDeg == 60);
    assert(config.fovTotalAngleDeg == 120);
    assert(config.fovRange == 300);
    assert(strcmp(config.sensorHardwareProfile, ...
        'formation-shared-120deg-r300-q300-v1'));
    assert(strcmp(config.sensorFovHeadingMode, ...
        'formation-shared-scene-center'));
    assert(validation.staticEdgeCount <= config.edgeBudget);
    assert(validation.staticPhysicalViolationCount == 0);
    assert(validation.difficulty. ...
        focusMeanVisibleTargetsPerSensorTime <= ...
        config.difficultyRequirements. ...
        maxFocusVisibleTargetsPerSensorTime + 1e-12);
    assert(validation.difficulty. ...
        focusMeanVisibleTargetsPerSensorTime / ...
        config.numberOfTargets <= config.difficultyRequirements. ...
        maxFocusVisibleTargetFractionPerSensorTime + 1e-12);

    headings = buildSensorFovHeadingSchedule( ...
        config, sensorTrajectories);
    assert(all(isfinite(headings(:))));
    assertFormationHeadingsShared( ...
        config, sensorTrajectories, headings);
    validatedMetrics(presetIdx) = validation.difficulty;

    scan = scanFormationFovSensingGeometry( ...
        presets{presetIdx}, 41, config.fovRange, ...
        config.sensorQuality.referenceRange);
    assert(strcmp(scan.contractVersion, ...
        'formation-shared-fov-geometry-scan-v2'));
    assertScannerMatchesValidation( ...
        scan.records, validation.difficulty);
end

matchedFields = { ...
    'focusMeanVisibleTargetsPerSensorTime'};
derivedFields = {'focusMeanVisibleSensorCount'};
reference = validatedMetrics(1);
for presetIdx = 2:numel(presets)
    config = configs{presetIdx};
    assert(strcmp(config.scaleControlReferencePreset, ...
        'm24-formation-fov'));
    assert(isequal(config.scaleControlMatchedMetrics, matchedFields));
    assert(isequal(config.scaleControlDerivedMetrics, derivedFields));
    for fieldIdx = 1:numel(matchedFields)
        fieldName = matchedFields{fieldIdx};
        relativeError = abs( ...
            validatedMetrics(presetIdx).(fieldName) / ...
            reference.(fieldName) - 1);
        assert(relativeError <= 0.03);
    end
end
hardwareFields = { ...
    'fovHalfAngleDeg', 'fovTotalAngleDeg', 'fovRange', ...
    'sensorFovHeadingMode', 'sensorFovPointingCenter', ...
    'detectionProbability', 'measurementNoiseStd', ...
    'sensorQuality', 'sensorHardwareProfile', ...
    'observationSpaceLimits', 'clutterRate', ...
    'clutterSpatialProfile'};
for presetIdx = 2:numel(configs)
    for fieldIdx = 1:numel(hardwareFields)
        fieldName = hardwareFields{fieldIdx};
        assert(isequaln(configs{1}.(fieldName), ...
            configs{presetIdx}.(fieldName)));
    end
end
assert(validatedMetrics(1).focusMeanExpectedTargetDetectionCount > ...
    validatedMetrics(2).focusMeanExpectedTargetDetectionCount);
assert(validatedMetrics(2).focusMeanExpectedTargetDetectionCount > ...
    validatedMetrics(3).focusMeanExpectedTargetDetectionCount);

% These geometry-only stress seeds are excluded from tracking claims. They
% guard all three 120-degree scale scenes against thresholds fitted to the
% five calibration seeds.
stressSeeds = [7, 11, 17, 23, 29, 31, 37, 41, 43, ...
    47, 53, 59, 61, 67, 71, 73, 79];
for presetIdx = 1:numel(presets)
    stressScan = scanFormationFovSensingGeometry( ...
        presets{presetIdx}, stressSeeds, configs{presetIdx}.fovRange, ...
        configs{presetIdx}.sensorQuality.referenceRange);
    stressRecords = reshape(stressScan.records, 1, []);
    requirements = configs{presetIdx}.difficultyRequirements;
    assert(max([stressRecords.blackoutFraction]) <= ...
        requirements.maxBlackoutFraction + 1e-12);
    assert(max([stressRecords.focusBlackoutFraction]) <= ...
        requirements.maxFocusBlackoutFraction + 1e-12);
    assert(max([stressRecords.maximumPerTargetBlackoutFraction]) <= ...
        requirements.maxPerTargetBlackoutFraction + 1e-12);
    assert(max([stressRecords.maximumConsecutiveBlackoutSteps]) <= ...
        requirements.maxConsecutiveBlackoutSteps);
    assert(min([stressRecords.singleFormationFraction]) >= ...
        requirements.minSingleFormationFraction - 1e-12);
    assert(min([stressRecords.multiFormationFraction]) >= ...
        requirements.minMultiFormationFraction - 1e-12);
    stressLoads = ...
        [stressRecords.focusMeanVisibleTargetsPerSensorTime];
    assert(max(stressLoads) <= ...
        requirements.maxFocusVisibleTargetsPerSensorTime + 1e-12);
    assert(max(stressLoads) / configs{presetIdx}.numberOfTargets <= ...
        requirements.maxFocusVisibleTargetFractionPerSensorTime + 1e-12);
    assert(min([stressRecords.focusHandovers]) >= ...
        requirements.minFocusHandovers);
end

% Each new gate must fail closed under an impossible requirement; this
% catches future field/comparator wiring errors, not just valid-path drift.
assertDifficultyFailure(configs{1}, sensorSets{1}, targetSets{1}, ...
    graphSets{1}, 'maxFocusBlackoutFraction', -1e-12, ...
    'difficulty-focus-blackout');
assertDifficultyFailure(configs{1}, sensorSets{1}, targetSets{1}, ...
    graphSets{1}, 'maxPerTargetBlackoutFraction', 0, ...
    'difficulty-per-target-blackout');
assertDifficultyFailure(configs{1}, sensorSets{1}, targetSets{1}, ...
    graphSets{1}, 'maxConsecutiveBlackoutSteps', 0, ...
    'difficulty-consecutive-blackout');
assertDifficultyFailure(configs{1}, sensorSets{1}, targetSets{1}, ...
    graphSets{1}, 'maxFocusVisibleTargetFractionPerSensorTime', 0, ...
    'difficulty-sensor-target-load-fraction');

% The hard distance gate is behavioral, not just metadata: removing it must
% make the realistic-FoV scene fail its bounded per-sensor target-load gate.
rng(41);
boundedScan = scanFormationFovSensingGeometry( ...
    'm24-formation-fov', 41, configs{1}.fovRange, ...
    configs{1}.sensorQuality.referenceRange);
unboundedScan = scanFormationFovSensingGeometry( ...
    'm24-formation-fov', 41, 1e6, ...
    configs{1}.sensorQuality.referenceRange);
boundedLoad = boundedScan.records. ...
    focusMeanVisibleTargetsPerSensorTime;
unboundedLoad = unboundedScan.records. ...
    focusMeanVisibleTargetsPerSensorTime;
requirements = configs{1}.difficultyRequirements;
assert(boundedLoad <= ...
    requirements.maxFocusVisibleTargetsPerSensorTime + 1e-12);
assert(boundedLoad / configs{1}.numberOfTargets <= ...
    requirements.maxFocusVisibleTargetFractionPerSensorTime + 1e-12);
assert(unboundedLoad > ...
    requirements.maxFocusVisibleTargetsPerSensorTime);
assert(unboundedLoad / configs{1}.numberOfTargets >= 0.95);
assert(unboundedLoad - boundedLoad >= 2.0);
unboundedConfig = buildDynamicTopologyScenarioConfig( ...
    'm24-formation-fov', struct('fovRange', 1e6));
[unboundedSensors, ~] = ...
    generateMultiFormationTrajectories(unboundedConfig);
[unboundedTargets, ~] = ...
    generateCorridorTargetTrajectories(unboundedConfig);
unboundedGraphs = buildDynamicTopologyGraphs( ...
    unboundedConfig, unboundedSensors);
failedClosed = false;
try
    validateDynamicTopologyScenario(unboundedConfig, ...
        unboundedSensors, unboundedTargets, unboundedGraphs);
catch errorInfo
    failedClosed = ~isempty(strfind( ...
        errorInfo.message, 'difficulty-sensor-target-load')); %#ok<STREMP>
end
assert(failedClosed);

invalidLimits = configs{1}.regionLimits;
invalidLimits(1, :) = [-100, 100];
failedClosed = false;
try
    buildDynamicTopologyScenarioConfig('m24-formation-fov', ...
        struct('observationSpaceLimits', invalidLimits));
catch errorInfo
    failedClosed = ~isempty(strfind( ...
        errorInfo.message, 'must enclose')); %#ok<STREMP>
end
assert(failedClosed);

config = rmfield(configs{3}, 'sensorGroupIds');
failedClosed = false;
try
    buildSensorFovHeadingSchedule(config, sensorSets{3});
catch errorInfo
    failedClosed = ~isempty(strfind( ...
        errorInfo.message, 'sensorGroupIds')); %#ok<STREMP>
end
assert(failedClosed);
fprintf('test_formation_fov_scenarios passed\n');
end

function assertFormationHeadingsShared( ...
        config, sensorTrajectories, headings)
for groupIdx = 1:config.formationCount
    groupSensors = find(config.sensorGroupIds == groupIdx);
    referenceHeading = headings(groupSensors(1), :);
    differences = bsxfun(@minus, ...
        headings(groupSensors, :), referenceHeading);
    wrappedDifferences = atan2(sin(differences), cos(differences));
    assert(max(abs(wrappedDifferences(:))) < 1e-12);

    centerPositions = zeros(2, config.simulationLength);
    for sensorIdx = reshape(groupSensors, 1, [])
        centerPositions = centerPositions + ...
            sensorTrajectories{sensorIdx}(1:2, :);
    end
    centerPositions = centerPositions / numel(groupSensors);
    expectedHeading = atan2( ...
        config.sensorFovPointingCenter(2) - centerPositions(2, :), ...
        config.sensorFovPointingCenter(1) - centerPositions(1, :));
    errorAngle = atan2(sin(referenceHeading - expectedHeading), ...
        cos(referenceHeading - expectedHeading));
    assert(max(abs(errorAngle)) < 1e-12);
end
end

function assertScannerMatchesValidation(scan, validation)
fields = { ...
    'focusMeanVisibleSensorCount', ...
    'focusMeanExpectedTargetDetectionCount', ...
    'focusMeanVisibleTargetsPerSensorTime', ...
    'blackoutFraction', ...
    'focusBlackoutFraction', ...
    'maximumPerTargetBlackoutFraction', ...
    'maximumConsecutiveBlackoutSteps', ...
    'singleFormationFraction', ...
    'multiFormationFraction', ...
    'formationOwnershipEntropy'};
for fieldIdx = 1:numel(fields)
    fieldName = fields{fieldIdx};
    assert(abs(scan.(fieldName) - validation.(fieldName)) < 1e-10);
end
assert(scan.focusHandovers == validation.focusHandovers);
end

function assertDifficultyFailure(config, sensors, targets, graphs, ...
        requirementName, impossibleValue, expectedToken)
config.difficultyRequirements.(requirementName) = impossibleValue;
failedClosed = false;
try
    validateDynamicTopologyScenario(config, sensors, targets, graphs);
catch errorInfo
    failedClosed = ~isempty(strfind( ...
        errorInfo.message, expectedToken)); %#ok<STREMP>
end
assert(failedClosed);
end
