function test_undercount_only_cardinality_augmentation_v141()
% TESTUNDERCOUNTONLYCARDINALITYAUGMENTATIONV141 Frozen one-sided boundary.

r = [0.20, 0.80, 0.60, 0.40];
small = lmbConditionalMapIndices(r, 2);
large = lmbConditionalMapIndices(r, 3);
assert(isequal(small, large(1:numel(small))));

protocol = getUndercountOnlyCardinalityAugmentationV141Protocol();
assert(protocol.predictiveEvidence.minimumMargin == 0);
assert(~protocol.referenceCardinality.existingHybridOutputMutationAllowed);
assert(~protocol.referenceCardinality.truthUsed);
assert(strcmp(protocol.referenceCardinality.insufficientHybridAction, ...
    'preserve-hybrid-output'));
assert(protocol.screen.minimumSensorGainFraction == -1e-4);

caseInfo = protocol.scaleCases(strcmp( ...
    {protocol.scaleCases.scaleName}, 'M24'));
bank = buildSetTrustSequenceCandidatesV134( ...
    [4, 2, 1, 3], caseInfo.formationCycleDiameter, ...
    caseInfo.recoveryTailSteps);
actionSpec = bank.actions(protocol.screen.m24ActionIndex);
context = ...
    buildUndercountOnlyCardinalityAugmentationV141ExecutionContext( ...
        caseInfo.presetName, protocol.pilotSeed, 'candidate', 95, ...
        'fixed-counter-clockwise', actionSpec);
assert(context.postFusionLabelReadoutEnabled);
assert(context.predictiveEvidenceReadoutOnlyEnabled);
assert(context.undercountOnlyCardinalityAugmentationEnabled);
assert(~context.workingStateMutationAllowed);

runtimeModel = struct( ...
    'numberOfSensors', caseInfo.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', caseInfo.presetName, ...
        'seed', protocol.pilotSeed, ...
        'config', struct( ...
            'formationCount', caseInfo.expectedFormationCount)));
returnTimes = context.currentTime + (0:(context.horizonSteps - 1));
requestConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyPolicyName', protocol.outcomePolicyName, ...
    'v135ReferenceCarrierMode', 'fixed-counter-clockwise', ...
    'topologyPolicyHistoryDepth', 2, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicySensorObservationEnabled', true, ...
    'receiverSafeLabelFusionEnabled', true, ...
    'receiverSafeLabelFusionMode', ...
        'formation-supported-label-plan', ...
    'receiverSafeExternalActiveTimes', returnTimes, ...
    'receiverSafeFormationConditionedTimes', returnTimes, ...
    'receiverSafeFormationConditionedSchedule', ...
        {actionSpec.formationIdsByTime}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {actionSpec.trustFactorsByTime}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.runtimePayloadMode, ...
    'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
    'receiverSafeEvidenceOptions', ...
        protocol.labelReadout.evidenceOptions, ...
    'lineageIsolatedRelayEnabled', true, ...
    'lineageRelayIntraFormationWorkingPayloadEnabled', true, ...
    'lineageRelayPredictiveEvidenceFallbackEnabled', false, ...
    'lineageRelayPredictiveEvidenceReadoutOnlyEnabled', true, ...
    'lineageRelayPredictiveEvidenceMinimumLogScoreMargin', ...
        protocol.predictiveEvidence.minimumMargin, ...
    'lineageRelayPostFusionLabelReadoutEnabled', true, ...
    'lineageRelayUndercountOnlyCardinalityAugmentationEnabled', true, ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'useStaleNeighborCache', false));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones( ...
            1, caseInfo.expectedNodeCount), ...
    'triggerConfig', requestConfig);
authorization = ...
    validateUndercountOnlyCardinalityAugmentationV141Execution( ...
        runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.validationClaimAllowed);

request.triggerConfig. ...
    lineageRelayUndercountOnlyCardinalityAugmentationEnabled = false;
assertErrorId(@() ...
    validateUndercountOnlyCardinalityAugmentationV141Execution( ...
        runtimeModel, context, request), ...
    'UndercountOnlyCardinalityV141:InvalidRuntimeRequest');
fprintf('PASS: V141 undercount-only cardinality augmentation contract\n');
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end
