function test_set_trust_sequence_v134()
% TEST_SET_TRUST_SEQUENCE_V134 Action bank and full-posterior semantics.

ranked = [4, 2, 1, 3];
protocol = getSetTrustSequenceV134Protocol();
assert(strcmp(protocol.payloadMode, ...
    'binary-full-posterior-admission'));
assert(strcmp(protocol.runtimePayloadMode, ...
    'binary-full-posterior-admission'));
assert(isequal(protocol.admissionFactors, [0, 1]));
assert(~protocol.intermediateTrustAllowed);
assert(~protocol.learnedFusionWeightAllocationAllowed);
assert(protocol.nominalKlaWeightsFrozen);
assert(strcmp(protocol.nominalKlaWeightMode, 'metropolis'));
assert(~protocol.stalePosteriorSubstitutionAllowed);
assert(protocol.persistentZeroDiagnosticOnly);
assert(~protocol.pilotEvaluatesPersistentZeroCandidates);
assert(protocol.preLearningGate. ...
    minimumPairedInterventionEospGainFraction == 0.05);
assert(protocol.preLearningGate.minimumPairedMeanEospGainFraction == 0);
assert(protocol.preLearningGate.minimumPairedMatureEospGainFraction == 0);
assert(protocol.preLearningGate.requireRecoveryMeanSquareCertificate);
assert(protocol.recoverySquaredContractionTarget == ...
    protocol.preLearningGate.maximumRecoverySquaredContractionFactor);
assert(protocol.preLearningGate.requireBothScales);
assert(protocol.preLearningGate. ...
    requireFullyRestoredGateEligibleAction);
assert(protocol.reportingPolicy.failedCandidatesRepositoryOnly);
assert(~protocol.gnnAuthorized);
assert(~protocol.theoryBoundary.trackingSafetyGuaranteedByCertificateAlone);
m24 = protocol.scaleCases(strcmp({protocol.scaleCases.scaleName}, 'M24'));
x36 = protocol.scaleCases(strcmp({protocol.scaleCases.scaleName}, 'X36'));
assert(m24.recoveryTailSteps == 46 && m24.horizonSteps == 53);
assert(x36.recoveryTailSteps == 70 && x36.horizonSteps == 81);
assert(resolveSetTrustSequenceV134PilotAnchor(m24, protocol) == 95);
assert(resolveSetTrustSequenceV134PilotAnchor(x36, protocol) == 80);

bank = buildSetTrustSequenceCandidatesV134( ...
    ranked, m24.formationCycleDiameter, m24.recoveryTailSteps);
assert(strcmp(bank.contractVersion, ...
    'v134-binary-admission-sequence-bank-v3'));
assert(bank.horizonSteps == 53);
assert(bank.recoveryTailSteps == 46);
assert(bank.actionCount == 1 + 2 * numel(ranked));
assert(nnz([bank.actions.gateEligible]) == numel(ranked));
assert(~bank.intermediateTrustAllowed);
assert(strcmp(bank.actions(1).scheduleKind, 'reference'));
assert(isempty(bank.actions(1).formationSet));

persistentAction = bank.actions(2);
tapered = bank.actions(3);
assert(isequal(persistentAction.formationSet, 4));
assert(all(cellfun(@(x) isequal(x, 4), ...
    persistentAction.formationIdsByTime)));
assert(all(cellfun(@(x) isequal(x, 0), ...
    persistentAction.trustFactorsByTime)));
assert(~persistentAction.returnsToFullTrust);
assert(persistentAction.diagnosticOnly);
assert(~persistentAction.gateEligible);
assert(isequal(cell2mat(tapered.trustFactorsByTime), ...
    [0, 0, 0, ones(1, 50)]));
assert(tapered.returnsToFullTrust);
assert(tapered.gateEligible);
assert(~tapered.diagnosticOnly);
assert(isequal(bank.actions(9).formationSet, ranked));
assert(isequal(vertcat(bank.actions(9).trustFactorsByTime{:}), ...
    [zeros(3, 4); ...
     0, 0, 0, 1; ...
     0, 0, 1, 1; ...
     0, 1, 1, 1; ...
     ones(47, 4)]));

remapped = buildSetTrustSequenceCandidatesV134( ...
    [8, 6, 5, 7], 3, m24.recoveryTailSteps);
assert(isequal(remapped.actions(7).formationSet, [8, 6, 5]));
assert(isequal(remapped.actions(7).trustFactorsByTime, ...
    bank.actions(7).trustFactorsByTime));

weights = [0.5, 0.2, 0.3];
details = struct( ...
    'sourceIndices', [1, 2, 3], ...
    'isStale', [false, false, false], ...
    'formationTrustFactor', [1, 1, 0.25]);
attenuated = applyFormationConditionedFullPosteriorTrustV134( ...
    weights, details, 'renormalize');
assert(max(abs(attenuated - [0.5, 0.2, 0.075])) <= 1e-12);
selfWeighted = applyFormationConditionedFullPosteriorTrustV134( ...
    weights, details, 'self');
assert(max(abs(selfWeighted - [0.725, 0.2, 0.075])) <= 1e-12);

object = makeObject();
posteriors = {object, object, object};
crossResidual = false(3);
crossResidual(3, 1) = true;
crossResidual(1, 3) = true;
model = struct( ...
    'xDimension', 4, ...
    'existenceThreshold', 0.01, ...
    'dynamicTopologyScenario', struct( ...
        'config', struct('sensorGroupIds', [1, 1, 2])));
config = struct( ...
    'receiverSafeFormationConditionedTimes', 1, ...
    'receiverSafeFormationConditionedSchedule', {{[1, 2]}}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {{[0.5, 0]}}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        'full-posterior-trust', ...
    'receiverSafeExternalPositiveSupportThreshold', 0.2, ...
    'receiverSafeFormationConditionedHighExistenceThreshold', 0.5, ...
    'payloadExistenceThreshold', 0.01);
plan = buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct(), struct()}, ...
    model, config, 1);
positiveTrustPayload = plan.payloadByReceiverSender{1, 3};
assert(numel(positiveTrustPayload) == 1);
assert(positiveTrustPayload.numberOfGmComponents == 2);
assert(plan.eventTypeByReceiverSender(3, 1) == 2);
assert(~plan.abstainFromFusionEdgeMask(3, 1));
assert(plan.abstainFromFusionEdgeMask(1, 3));
assert(plan.fusionTrustFactorByReceiverSender(3, 1) == 0.5);
assert(plan.fusionTrustFactorByReceiverSender(1, 3) == 0);
assert(isempty(plan.payloadByReceiverSender{3, 1}));
assert(plan.usesFullSenderPosteriors);
assert(plan.totalControlSynopsisBytes > 0);
assert(plan.totalSelectedPayloadBytes > 0);

binaryConfig = config;
binaryConfig.receiverSafeFormationConditionedPayloadMode = ...
    protocol.runtimePayloadMode;
binaryConfig.receiverSafeFormationConditionedTrustFactorsByTime = ...
    {[1, 0]};
binaryPlan = buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct(), struct()}, ...
    model, binaryConfig, 1);
assert(~binaryPlan.abstainFromFusionEdgeMask(3, 1));
assert(binaryPlan.abstainFromFusionEdgeMask(1, 3));
binaryConfig.receiverSafeFormationConditionedTrustFactorsByTime = ...
    {[0.5, 0]};
assertErrorId(@() buildFormationConditionedSupportedLabelMessagePlan( ...
    posteriors, crossResidual, {struct(), struct(), struct()}, ...
    model, binaryConfig, 1), ...
    'FormationSupportedLabelPlan:InvalidTrustSchedule');

candidate = bank.actions(3);
anchorTime = 95;
execution = buildSetTrustSequenceV134ExecutionContext( ...
    'm24-formation-fov', protocol.pilotSeed, ...
    'candidate-continuation', anchorTime, ...
    'fixed-clockwise', candidate);
assert(isSetTrustSequenceV134ExecutionContext(execution));
runtimeModel = struct( ...
    'numberOfSensors', 24, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', 'm24-formation-fov', ...
        'seed', protocol.pilotSeed, ...
        'config', struct('formationCount', 4)));
returnTimes = anchorTime + (0:(m24.horizonSteps - 1));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', returnTimes(end), ...
    'sensorTrajectoryTimeCounts', ...
        returnTimes(end) * ones(1, 24), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'v134ReferenceCarrierMode', 'fixed-clockwise', ...
        'topologyPolicyHistoryDepth', 2, ...
        'topologyPolicyObservableContextOnly', true, ...
        'topologyPolicySensorObservationEnabled', true, ...
        'fusionWeightMode', protocol.nominalKlaWeightMode, ...
        'useStaleNeighborCache', false, ...
        'missingNeighborWeightMode', ...
            protocol.primaryMissingNeighborWeightMode, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', returnTimes, ...
        'receiverSafeFormationConditionedTimes', returnTimes, ...
        'receiverSafeFormationConditionedSchedule', ...
            {candidate.formationIdsByTime}, ...
        'receiverSafeFormationConditionedTrustFactorsByTime', ...
            {candidate.trustFactorsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            protocol.runtimePayloadMode, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, execution, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig. ...
    receiverSafeFormationConditionedTrustFactorsByTime{end}(:) = 0.75;
failedClosed = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, execution, request);
catch errorInfo
    failedClosed = strcmp(errorInfo.identifier, ...
        'V134SetTrustExecution:InvalidRuntimeRequest');
end
assert(failedClosed);

referenceOutcome = struct( ...
    'eospaBySensorTime', 10 * ones(4, m24.horizonSteps), ...
    'attemptedBytesByTime', 100 * ones(1, m24.horizonSteps));
candidateOutcome = struct( ...
    'eospaBySensorTime', 9 * ones(4, m24.horizonSteps), ...
    'attemptedBytesByTime', ...
        [20, 20, 20, 100 * ones(1, m24.horizonSteps - 3)]);
metrics = scoreSetTrustSequenceHeadroomV134( ...
    referenceOutcome, candidateOutcome, [1, 1, 2, 2], ...
    m24.recoveryTailSteps, ...
    protocol, tapered);
assert(abs(metrics.interventionGainFraction - 0.1) <= 1e-12);
assert(abs(metrics.meanGainFraction - 0.1) <= 1e-12);
assert(abs(metrics.matureGainFraction - 0.1) <= 1e-12);
assert(isequal(metrics.interventionColumns, 1:3));
assert(isequal(metrics.matureColumns, 8:53));
assert(metrics.minimumSensorGainFraction > 0);
assert(metrics.minimumFormationGainFraction > 0);
assert(metrics.minimumMatureSensorGainFraction > 0);
assert(metrics.minimumMatureFormationGainFraction > 0);
assert(abs(metrics.interventionAttemptedByteSavingFraction - 0.8) ...
    <= 1e-12);
assert(abs(metrics.attemptedByteSavingFraction - 240 / 5300) ...
    <= 1e-12);
assert(metrics.passesPreLearningGate);
assert(metrics.actionReturnsToFullTrust);

candidateOutcome.eospaBySensorTime(1, 8:53) = 12;
matureLocalRegression = scoreSetTrustSequenceHeadroomV134( ...
    referenceOutcome, candidateOutcome, [1, 1, 2, 2], ...
    m24.recoveryTailSteps, ...
    protocol, tapered);
assert(matureLocalRegression.interventionGainFraction > 0.05);
assert(matureLocalRegression.minimumMatureSensorGainFraction < 0);
assert(~matureLocalRegression.passesSensorGate);
assert(~matureLocalRegression.passesPreLearningGate);

diagnosticMetrics = scoreSetTrustSequenceHeadroomV134( ...
    referenceOutcome, candidateOutcome, [1, 1, 2, 2], ...
    m24.recoveryTailSteps, ...
    protocol, persistentAction);
assert(diagnosticMetrics.actionDiagnosticOnly);
assert(~diagnosticMetrics.actionGateEligible);
assert(~diagnosticMetrics.passesPreLearningGate);

assertRecoveryCertificate(protocol);

adaptiveRequest = request;
adaptiveRequest.triggerConfig.fusionWeightMode = 'balanced';
assertErrorId(@() assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, execution, adaptiveRequest), ...
    'V134SetTrustExecution:InvalidRuntimeRequest');

fprintf('PASS: V134 binary posterior-admission contract\n');
end

function assertRecoveryCertificate(protocol)
nodeCount = 4;
groupIds = [1, 1, 2, 2];
recoveryTailSteps = 6;
bank = buildSetTrustSequenceCandidatesV134( ...
    [1, 2], 1, recoveryTailSteps);
action = bank.actions(3);
horizon = bank.horizonSteps;
adjacencyPage = logical([ ...
    0, 0, 0, 1; ...
    1, 0, 0, 0; ...
    0, 1, 0, 0; ...
    0, 0, 1, 0]);
adjacency = repmat(adjacencyPage, 1, 1, horizon);
weights = zeros(nodeCount, nodeCount, horizon);
for timeIdx = 1:horizon
    weights(:, :, timeIdx) = 0.5 * ...
        (eye(nodeCount) + double(adjacencyPage));
end
pDrop = zeros(nodeCount, nodeCount, horizon);
controlledPage = adjacencyPage & ...
    (groupIds(:) ~= groupIds(:)');
controlled = repmat(controlledPage, 1, 1, horizon);
certificate = computeSetTrustSequenceV134RecoveryCertificate( ...
    adjacency, weights, pDrop, controlled, groupIds, action, ...
    recoveryTailSteps, protocol);
assert(certificate.passesRecoveryGate);
assert(certificate.referenceAndCandidateTailIdentical);
assert(certificate.candidateSquaredContractionFactor <= 0.90);
assert(~certificate.trackingSafetyGuaranteed);
assert(~certificate.causalDeploymentCertificate);

driftedProtocol = protocol;
driftedProtocol.preLearningGate. ...
    maximumRecoverySquaredContractionFactor = 0.85;
assertErrorId(@() computeSetTrustSequenceV134RecoveryCertificate( ...
    adjacency, weights, pDrop, controlled, groupIds, action, ...
    recoveryTailSteps, driftedProtocol), ...
    'V134RecoveryCertificate:TargetDrift');

badControlled = controlled;
badControlled(1, 2, 1) = true;
assertErrorId(@() computeSetTrustSequenceV134RecoveryCertificate( ...
    adjacency, weights, pDrop, badControlled, groupIds, action, ...
    recoveryTailSteps, protocol), ...
    'V134RecoveryCertificate:ControlledEdgeDrift');
end

function assertErrorId(functionHandle, expectedIdentifier)
failed = false;
try
    functionHandle();
catch errorInfo
    failed = strcmp(errorInfo.identifier, expectedIdentifier);
end
assert(failed);
end

function object = makeObject()
object = struct( ...
    'birthTime', 1, ...
    'birthLocation', 1, ...
    'r', 0.9, ...
    'numberOfGmComponents', 2, ...
    'w', [0.4, 0.6], ...
    'mu', {{zeros(4, 1), ones(4, 1)}}, ...
    'Sigma', {{eye(4), 2 * eye(4)}}, ...
    'detectionAssociationMass', 0.8);
end
