function test_formation_b4_v46_runtime_filter_input_fingerprint()
% Full source commitment projects exactly to the public filter boundary.

registry = getFormationB4V46TrackingSourceRegistry();
caseContract = registry.cases(1);
initialRngState = rng();
restoreRng = onCleanup(@() rng(initialRngState));
inputs = generateDynamicTopologyScenarioInputs( ...
    caseContract.presetName, caseContract.seed);
identity = buildDynamicTopologyPhysicalIdentityRegistry(inputs.config);
[uniforms, metadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        caseContract.deliverySeed, identity.sensorPhysicalUids, ...
        caseContract.simulationLength);
inputs.commConfig.linkUniforms = uniforms;
source = computeFormationB4V46TrackingInputFingerprint( ...
    inputs, identity, metadata, caseContract, registry);
runtimeModel = sanitizeFormationB4V46RuntimeFilterModel( ...
    inputs.model, caseContract, registry);
projected = ...
    projectFormationB4V46RuntimeFilterInputFingerprint(source);
runtime = computeFormationB4V46RuntimeFilterInputFingerprint( ...
    runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
    inputs.neighborMap, inputs.commConfig, source, ...
    caseContract, registry);
boundary = ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, caseContract.ordinal);
assert(isequaln(runtime, projected));
assert(isequaln(boundary, projected));
assert(strcmp(runtime.modelSha256, ...
    computeCanonicalValueSha256(runtimeModel)));
assert(~isfield(runtimeModel, 'explicitTargetTrajectories'));
assert(~isfield(runtimeModel, 'targetBirthStates'));
assert(~isfield(runtimeModel, 'targetFormationEnabled'));
assert(~isfield(runtimeModel, 'explicitSensorTrajectories'));
assert(~isfield(runtimeModel, 'sensorTrajectories'));
assert(~isfield(runtimeModel, 'dynamicTopologyTrackingOutcomeGate'));
assert(~isfield(runtimeModel.dynamicTopologyScenario, 'target'));
assert(~isfield(runtimeModel.dynamicTopologyScenario, ...
    'targetTrajectories'));
assert(~isfield(runtimeModel.dynamicTopologyScenario, ...
    'physicalAdjacency'));
assert(~isfield(runtimeModel.dynamicTopologyScenario.config, ...
    'targetRoutes'));
assert(~isfield(runtimeModel.dynamicTopologyScenario.config, ...
    'targetBirthTimesByGroup'));
assert(all(cellfun(@(value) isequal(size(value), [2, 1]), ...
    runtimeModel.dynamicTopologyScenario.config. ...
        sensorCenterWaypoints)));
assert(runtimeModel.formationB4V46RuntimeSourceEnvelope. ...
    registeredBirthPriorRetained);

truthPoison = inputs;
truthPoison.targetTrajectories{1}(:) = 8.8e8;
truthPoison.model.explicitTargetTrajectories{1}(:) = 8.8e8;
truthPoison.model.dynamicTopologyScenario. ...
    targetTrajectories{1}(:) = 8.8e8;
poisonedSource = computeFormationB4V46TrackingInputFingerprint( ...
    truthPoison, identity, metadata, caseContract, registry);
poisonedProjection = ...
    projectFormationB4V46RuntimeFilterInputFingerprint(poisonedSource);
assert(~strcmp(poisonedSource.canonicalSha256, ...
    source.canonicalSha256));
assert(isequaln(poisonedProjection, projected));

assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprint( ...
        inputs.model, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, source, ...
        caseContract, registry), ...
    'FormationB4V46RuntimeFingerprint:MalformedRuntimeInput');

extra = source;
extra.trackingScore = 1;
assertErrorId(@() ...
    projectFormationB4V46RuntimeFilterInputFingerprint(extra), ...
    'FormationB4V46RuntimeFingerprint:InvalidSource');

changedComm = inputs.commConfig;
changedComm.linkUniforms(1, 2, 1) = ...
    1 - changedComm.linkUniforms(1, 2, 1);
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprint( ...
        runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, changedComm, source, ...
        caseContract, registry), ...
    'FormationB4V46RuntimeFingerprint:DeliveryDrift');

changedMeasurements = inputs.measurements;
nonemptyIdx = find(~cellfun(@isempty, changedMeasurements), 1);
assert(~isempty(nonemptyIdx));
measurementSet = changedMeasurements{nonemptyIdx};
vectorIdx = find(cellfun(@(value) ...
    isnumeric(value) && ~isempty(value), measurementSet), 1);
assert(~isempty(vectorIdx));
measurementSet{vectorIdx}(1) = measurementSet{vectorIdx}(1) + 1e-6;
changedMeasurements{nonemptyIdx} = measurementSet;
changedBoundary = ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        runtimeModel, changedMeasurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, caseContract.ordinal);
assert(~strcmp(changedBoundary.canonicalSha256, ...
    boundary.canonicalSha256));
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprint( ...
        runtimeModel, changedMeasurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, source, ...
        caseContract, registry), ...
    'FormationB4V46RuntimeFingerprint:RuntimeInputDrift');

otherCase = registry.cases(2);
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprint( ...
        runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, source, ...
        otherCase, registry), ...
    'FormationB4V46RuntimeFingerprint:AuthorityDrift');
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, changedComm, caseContract.ordinal), ...
    'FormationB4V46RuntimeBoundary:DeliveryDrift');
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        runtimeModel, inputs.measurements, inputs.sensorTrajectories, ...
        inputs.neighborMap, inputs.commConfig, 0), ...
    'FormationB4V46RuntimeBoundary:UnknownCase');
truthLeakedRuntime = runtimeModel;
truthLeakedRuntime.groundTruth = struct('x', {{[0; 0; 0; 0]}});
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        truthLeakedRuntime, inputs.measurements, ...
        inputs.sensorTrajectories, inputs.neighborMap, ...
        inputs.commConfig, caseContract.ordinal), ...
    'FormationB4V46RuntimeBoundary:CaseDrift');
offlineLeakedRuntime = runtimeModel;
offlineLeakedRuntime.formationB4V46RuntimeSourceEnvelope. ...
    offlineProvenanceCanonicalSha256 = repmat('a', 1, 64);
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        offlineLeakedRuntime, inputs.measurements, ...
        inputs.sensorTrajectories, inputs.neighborMap, ...
        inputs.commConfig, caseContract.ordinal), ...
    'FormationB4V46RuntimeBoundary:CaseDrift');
permitLeakedRuntime = runtimeModel;
permitLeakedRuntime.dynamicTopologyScenario.config.permit = ...
    struct('authorized', true);
assertErrorId(@() ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        permitLeakedRuntime, inputs.measurements, ...
        inputs.sensorTrajectories, inputs.neighborMap, ...
        inputs.commConfig, caseContract.ordinal), ...
    'FormationB4V46RuntimeBoundary:CaseDrift');
clear restoreRng;
finalRngState = rng();
assert(isequaln(finalRngState, initialRngState));
fprintf('PASS: V46 runtime filter-input fingerprint tests\n');
end

function assertErrorId(callback, expectedIdentifier)
failed = false;
actualIdentifier = '';
try
    callback();
catch errorInfo
    actualIdentifier = errorInfo.identifier;
    failed = strcmp(actualIdentifier, expectedIdentifier);
end
assert(failed, 'Expected %s, received %s.', ...
    expectedIdentifier, actualIdentifier);
end
