function test_receiver_domain_normalized_opportunity_v70()
% TEST_RECEIVER_DOMAIN_NORMALIZED_OPPORTUNITY_V70 Scale consistency.

[baseTwo, influenceTwo, controlTwo, transportTwo, groupIdsTwo] = ...
    syntheticState(2);
[baseFour, influenceFour, controlFour, transportFour, groupIdsFour] = ...
    syntheticState(4);
options = struct( ...
    'minimumLocalQuarantineNetFraction', 0.01, ...
    'minimumLocalAlternativeNetFraction', 0.01, ...
    'minimumLocalRobustMarginExposure', 0.10, ...
    'maximumUsefulLossToRescueRatio', 1.0, ...
    'requireZeroSupportedDownwardCrossings', true);

two = computeReceiverDomainNormalizedOpportunityV70( ...
    baseTwo, influenceTwo, controlTwo, transportTwo, ...
    groupIdsTwo, options);
four = computeReceiverDomainNormalizedOpportunityV70( ...
    baseFour, influenceFour, controlFour, transportFour, ...
    groupIdsFour, options);

assert(abs(two.localQuarantineRescueFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(abs(four.localQuarantineRescueFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(abs(two.localQuarantineNetFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(abs(four.localQuarantineNetFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(two.quarantineActionMask(1));
assert(four.quarantineActionMask(1));
assert(abs(two.localAlternativeTransportNetFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(abs(four.localAlternativeTransportNetFractionByFormation(1) - ...
    0.02) < 1e-12);
assert(two.alternativeTransportActionMask(1));
assert(four.alternativeTransportActionMask(1));
assert(abs(baseTwo.totalNetworkRescueFraction - 0.01) < 1e-12);
assert(abs(baseFour.totalNetworkRescueFraction - 0.005) < 1e-12);

baseTwo.crossSupportedDownwardCrossingsByFormation(1) = 1;
blocked = computeReceiverDomainNormalizedOpportunityV70( ...
    baseTwo, influenceTwo, controlTwo, transportTwo, ...
    groupIdsTwo, options);
assert(~blocked.quarantineActionMask(1));

baseTwo.crossSupportedDownwardCrossingsByFormation(1) = 0;
baseTwo.crossSupportedUsefulLossMassByFormation(1) = 0.2;
zeroNet = computeReceiverDomainNormalizedOpportunityV70( ...
    baseTwo, influenceTwo, controlTwo, transportTwo, ...
    groupIdsTwo, options);
assert(~zeroNet.quarantineActionMask(1));
fprintf('test_receiver_domain_normalized_opportunity_v70 passed\n');
end

function [base, influence, control, transport, groupIds] = ...
        syntheticState(formationCount)
sensorsPerFormation = 6;
groups = 1:formationCount;
groupIds = repelem(groups, sensorsPerFormation);
referenceByFormation = 10 * ones(1, formationCount);
rescueMass = zeros(1, formationCount);
rescueMass(1) = 0.2;
usefulLossMass = zeros(1, formationCount);
downward = zeros(1, formationCount);
networkMass = sum(referenceByFormation);

base = struct();
base.groups = groups;
base.singleActionAvailableMask = true(1, formationCount);
base.referenceExistenceMassByFormation = referenceByFormation;
base.receiverSupportedRescueMassByFormation = rescueMass;
base.crossSupportedUsefulLossMassByFormation = usefulLossMass;
base.crossSupportedDownwardCrossingsByFormation = downward;
base.networkReferenceExistenceMass = networkMass;
base.totalNetworkRescueFraction = sum(rescueMass) / networkMass;

influence = struct();
influence.groups = groups;
influence.horizonSteps = 3;
influence.formationReceiverCount = ...
    sensorsPerFormation * ones(1, formationCount);
influence.formationWeightedRobustMarginExposure = ...
    zeros(1, formationCount);
influence.formationWeightedRobustMarginExposure(1) = 2.0;

existenceByReceiver = cell(1, numel(groupIds));
for receiverIdx = 1:numel(groupIds)
    existenceByReceiver{receiverIdx} = ...
        referenceByFormation(groupIds(receiverIdx)) / ...
        sensorsPerFormation;
end
control = struct();
control.referenceScore = struct( ...
    'retentionDetails', struct( ...
        'expectedReferenceExistenceByReceiver', ...
            {existenceByReceiver}));

transport = struct();
transport.networkReferenceExistenceMass = networkMass;
transport.slotRecords = struct( ...
    'bestSafe', true, ...
    'bestNetHeadroomFraction', 0.2 / networkMass, ...
    'bestTransportGainFraction', 0.2 / networkMass, ...
    'bestSupportedHarmFraction', 0, ...
    'receiverIdx', 1);
transport.routeConnectivityProjected = false;
end
