function test_intermittent_light_network_anchor_v131()
% TEST_INTERMITTENTLIGHTNETWORKANCHORV131 Protocol and permit contract.

protocol = getIntermittentLightNetworkAnchorV131Protocol();
v128 = getIndependentLocalAnchorV128Protocol();
assert(isequal(protocol.protectionFormationIdsByTime, ...
    v128.protectionFormationIdsByTime));
assert(isequal(protocol.rollbackFormationIdsByTime, ...
    v128.rollbackFormationIdsByTime));
assert(isequal(protocol.lightNetworkAnchorRefreshTimes, [72, 74, 76, 78]));
assert(protocol.auxiliaryRuntimeIncluded);
assert(~protocol.auxiliaryMemoryQuantified);

config = struct( ...
    'shadowStateRollbackEnabled', true, ...
    'shadowStateRollbackSourceMode', 'light-network-anchor', ...
    'shadowStateRollbackTimes', 76, ...
    'shadowStateRollbackSensorIdsByTime', {{7:12}}, ...
    'shadowStateRollbackFusedPosteriorByTime', {{}});
[posterior, applied, pageIdx] = selectShadowStateRollbackPosterior( ...
    struct('r', 0.1), config, 8, 76, struct('r', 0.7), ...
    struct('r', 0.9));
assert(applied && pageIdx == 1 && posterior.r == 0.9);

entry = protocol.cases(strcmp({protocol.cases.scaleName}, 'X36'));
context = buildIntermittentLightNetworkAnchorV131ExecutionContext( ...
    entry.presetName, entry.seed, 72, protocol.candidateActionName, true);
groupIds = repelem(1:6, 6);
sensorIdsByTime = cellfun(@(formations) ...
    find(ismember(groupIds, formations)), ...
    protocol.rollbackFormationIdsByTime, 'UniformOutput', false);
runtimeModel = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount, ...
            'sensorGroupIds', groupIds)));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', 72:79, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
        'receiverSafeFormationConditionedSchedule', ...
            {protocol.protectionFormationIdsByTime}, ...
        'receiverSafeFormationConditionedPayloadMode', 'control-only', ...
        'shadowStateRollbackEnabled', true, ...
        'shadowStateRollbackSourceMode', 'light-network-anchor', ...
        'shadowStateRollbackTimes', protocol.rollbackTimes, ...
        'shadowStateRollbackSensorIdsByTime', {sensorIdsByTime}, ...
        'shadowStateRollbackFusedPosteriorByTime', {{}}, ...
        'lightNetworkAnchorRefreshTimes', ...
            protocol.lightNetworkAnchorRefreshTimes));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig.lightNetworkAnchorRefreshTimes = 72:79;
rejected = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        runtimeModel, context, request);
catch errorInfo
    rejected = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(rejected);
fprintf('test_intermittent_light_network_anchor_v131 passed\n');
end
