function test_role_multiplexed_single_payload_v143()
% TEST_ROLE_MULTIPLEXED_SINGLE_PAYLOAD_V143 Protocol and role boundaries.

protocol = getRoleMultiplexedSinglePayloadV143Protocol();
assert(protocol.roleSchedule.periodPages == 2);
assert(protocol.roleSchedule.referencePhaseOffset == 0);
assert(protocol.roleSchedule.onePayloadPerAttemptedEdge);
assert(~protocol.roleSchedule.auxiliaryPayloadAllowed);
assert(~protocol.roleSchedule. ...
    workingStateCrossFormationTransmissionAllowed);
assert(protocol.screen.requireZeroAuxiliaryPayload);
assert(protocol.screen.requireNoAttemptedByteIncrease);
assert(protocol.finiteTimeMixingPreflight. ...
    connectivityOnlyEdgeClassSplitRejected);

selectorConfig = struct( ...
    'lineageRelayRoleMultiplexedSinglePayloadEnabled', true, ...
    'lineageRelayRoleMultiplexedAnchorTime', 10, ...
    'lineageRelayRoleMultiplexedPeriodPages', 2, ...
    'lineageRelayRoleMultiplexedReferencePhaseOffset', 0);
groups = [1, 1, 2, 2];
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 1, 2, 10, true);
assert(strcmp(role, 'reference'));
assert(details.referencePhase);
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 1, 2, 11, true);
assert(strcmp(role, 'working'));
assert(details.workingPhase && details.intraFormation);
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 1, 3, 11, true);
assert(strcmp(role, 'reference'));
assert(~details.intraFormation);
[role, details] = selectRoleMultiplexedSinglePayloadV143( ...
    selectorConfig, groups, 3, 4, 11, false);
assert(strcmp(role, 'reference'));
assert(~details.receiverProtected);

caseInfo = protocol.scaleCases(strcmp( ...
    {protocol.scaleCases.scaleName}, 'M24'));
bank = buildSetTrustSequenceCandidatesV134( ...
    [4, 2, 1, 3], caseInfo.formationCycleDiameter, ...
    caseInfo.recoveryTailSteps);
actionSpec = bank.actions(protocol.screen.m24ActionIndex);
context = buildRoleMultiplexedSinglePayloadV143ExecutionContext( ...
    caseInfo.presetName, protocol.pilotSeed, 'candidate', 95, ...
    'fixed-counter-clockwise', actionSpec);
assert(context.roleMultiplexingEnabled);
assert(context.singlePayloadWireEnforced);
assert(~context.exactStaticStateFallbackClaimAllowed);

runtimeModel = struct( ...
    'numberOfSensors', caseInfo.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', caseInfo.presetName, ...
        'seed', protocol.pilotSeed, ...
        'config', struct( ...
            'formationCount', caseInfo.expectedFormationCount)));
returnTimes = context.currentTime + (0:(context.horizonSteps - 1));
requestConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'topologyPolicyName', protocol.outcomePolicyName, ...
    'v135ReferenceCarrierMode', 'fixed-counter-clockwise', ...
    'topologyPolicyHistoryDepth', 2, ...
    'topologyPolicyObservableContextOnly', true, ...
    'topologyPolicySensorObservationEnabled', true, ...
    'receiverSafeLabelFusionEnabled', true, ...
    'receiverSafeLabelFusionMode', ...
        'formation-supported-label-plan', ...
    'receiverSafeExternalActiveTimes', returnTimes, ...
    'receiverSafeFormationConditionedTimes', returnTimes, ...
    'receiverSafeFormationConditionedSchedule', ...
        {actionSpec.formationIdsByTime}, ...
    'receiverSafeFormationConditionedTrustFactorsByTime', ...
        {actionSpec.trustFactorsByTime}, ...
    'receiverSafeFormationConditionedPayloadMode', ...
        protocol.runtimePayloadMode, ...
    'receiverSafeFormationConditionedOnlinePolicyEnabled', false, ...
    'receiverSafeEvidenceOptions', ...
        protocol.labelReadout.evidenceOptions, ...
    'lineageIsolatedRelayEnabled', true, ...
    'lineageRelayIntraFormationWorkingPayloadEnabled', true, ...
    'lineageRelayPredictiveEvidenceFallbackEnabled', false, ...
    'lineageRelayPredictiveEvidenceReadoutOnlyEnabled', true, ...
    'lineageRelayPredictiveEvidenceMinimumLogScoreMargin', ...
        protocol.predictiveEvidence.minimumMargin, ...
    'lineageRelayPostFusionLabelReadoutEnabled', true, ...
    'lineageRelayRoleMultiplexedSinglePayloadEnabled', true, ...
    'lineageRelayRoleMultiplexedAnchorTime', context.currentTime, ...
    'lineageRelayRoleMultiplexedPeriodPages', ...
        protocol.roleSchedule.periodPages, ...
    'lineageRelayRoleMultiplexedReferencePhaseOffset', ...
        protocol.roleSchedule.referencePhaseOffset, ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'useStaleNeighborCache', false));
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ones( ...
            1, caseInfo.expectedNodeCount), ...
    'triggerConfig', requestConfig);
authorization = validateRoleMultiplexedSinglePayloadV143Execution( ...
    runtimeModel, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(~authorization.validationClaimAllowed);

request.triggerConfig. ...
    lineageRelayRoleMultiplexedSinglePayloadEnabled = false;
assertErrorId(@() ...
    validateRoleMultiplexedSinglePayloadV143Execution( ...
        runtimeModel, context, request), ...
    'RoleMultiplexedV143:InvalidRuntimeRequest');
fprintf('PASS: V143 role-multiplexed single-payload contract\n');
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end
