function test_physical_uid_directed_delivery_uniforms()
% Physical-identity, direction, hashing and fail-closed contracts.

testCanonicalMaterializationAndMetadata();
testStoragePermutationPreservesEveryPhysicalLink();
testDirectionSeedAndTimeContracts();
testGlobalRngStateIsUntouched();
testInvalidInputsFailClosed();
fprintf('PASS: physical-UID directed delivery-uniform tests\n');
end

function testCanonicalMaterializationAndMetadata()
seed = 17041;
uids = [70103, 70201, 70101, 70204];
timeCount = 5;
[actual, metadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        seed, uids, timeCount);
[canonical, canonicalMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        seed, sort(uids), timeCount);
expectedCanonical = drawExpectedCanonical(seed, numel(uids), timeCount);

assert(isequal(size(actual), [4, 4, 5]));
assert(all(isfinite(actual(:))));
assert(all(actual(:) >= 0 & actual(:) < 1));
assert(isequal(canonical, expectedCanonical));
assert(strcmp(metadata.contractVersion, ...
    'physical-uid-directed-delivery-uniforms-v1'));
assert(metadata.seed == seed && metadata.timeCount == timeCount);
assert(isequal(metadata.materializedSensorPhysicalUidOrder, uids));
assert(isequal(metadata.canonicalSensorPhysicalUidOrder, sort(uids)));
assert(isequal(metadata.canonicalIndexByMaterializedIndex, ...
    [2, 3, 1, 4]));
assert(isequal(metadata.materializedIndexByCanonicalIndex, ...
    [3, 1, 2, 4]));
assert(strcmp(metadata.directionConvention, ...
    'sender-row-receiver-column-time'));
assert(strcmp(metadata.canonicalTraversalOrder, ...
    'sender-row-fastest-then-receiver-column-then-time'));
assert(metadata.reverseDirectionsUseDistinctStreamPositions);
assert(metadata.globalRngStateRestored);
assert(strcmp(metadata.generator, 'twister'));
assert(strcmp(metadata.generatorContract, ...
    'twister-seeded-canonical-sender-receiver-time-tensor-v1'));
assert(strcmp(metadata.uniformInterval, ...
    'runtime-rand-unit-interval'));
assert(strcmp(metadata.canonicalTensorSha256, ...
    canonicalMetadata.canonicalTensorSha256));
assert(strcmp(metadata.canonicalTensorSha256, ...
    computeCanonicalValueSha256(canonical)));
assert(strcmp(metadata.materializedTensorSha256, ...
    computeCanonicalValueSha256(actual)));
metadataPayload = rmfield(metadata, 'canonicalSha256');
assert(strcmp(metadata.canonicalSha256, ...
    computeCanonicalValueSha256(metadataPayload)));
end

function testStoragePermutationPreservesEveryPhysicalLink()
seed = 22117;
uids = [70304, 70101, 70402, 70203, 70105];
timeCount = 7;
[baseline, baselineMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        seed, uids, timeCount);
newToOld = [3, 5, 1, 4, 2];
[permuted, permutedMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        seed, uids(newToOld), timeCount);

assert(isequal(permuted, ...
    baseline(newToOld, newToOld, :)));
assert(strcmp(baselineMetadata.canonicalTensorSha256, ...
    permutedMetadata.canonicalTensorSha256));
assert(~strcmp(baselineMetadata.materializedTensorSha256, ...
    permutedMetadata.materializedTensorSha256));

for senderIdx = 1:numel(uids)
    senderUid = uids(senderIdx);
    permutedSender = find(uids(newToOld) == senderUid);
    for receiverIdx = 1:numel(uids)
        receiverUid = uids(receiverIdx);
        permutedReceiver = find(uids(newToOld) == receiverUid);
        assert(isequal( ...
            baseline(senderIdx, receiverIdx, :), ...
            permuted(permutedSender, permutedReceiver, :)));
    end
end
end

function testDirectionSeedAndTimeContracts()
uids = [80101, 80102, 80201];
seed = 31009;
[short, shortMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms(seed, uids, 3);
[long, longMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms(seed, uids, 8);
[otherSeed, otherMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms(seed + 1, uids, 3);

assert(isequal(short, long(:, :, 1:3)));
assert(~isequal(short, otherSeed));
assert(~strcmp(shortMetadata.canonicalTensorSha256, ...
    otherMetadata.canonicalTensorSha256));
assert(~strcmp(shortMetadata.canonicalTensorSha256, ...
    longMetadata.canonicalTensorSha256));
assert(~isequal(short(1, 2, :), short(2, 1, :)));
assert(any(reshape(short(1, 2, :) ~= short(2, 1, :), 1, [])));

repeat = materializePhysicalUidDirectedDeliveryUniforms(seed, uids, 3);
assert(isequal(short, repeat));
end

function testGlobalRngStateIsUntouched()
rng(92071, 'twister');
stateBefore = rng();
materializePhysicalUidDirectedDeliveryUniforms( ...
    33013, [90101, 90102, 90201, 90202], 6);
stateAfter = rng();
assert(isequal(stateBefore, stateAfter));

expected = rand(1, 9);
rng(stateBefore);
materializePhysicalUidDirectedDeliveryUniforms( ...
    33013, [90202, 90101, 90201, 90102], 2);
actual = rand(1, 9);
assert(isequal(actual, expected));
end

function testInvalidInputsFailClosed()
validSeed = 7;
validUids = [101, 102, 201];
validTimeCount = 4;
invalidCalls = { ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        NaN, validUids, validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        -1, validUids, validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        1.5, validUids, validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        2^32, validUids, validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, 101, 201], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, NaN, 201], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, 102.5, 201], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, 0, 201], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, 102, flintmax + 2], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, [101, 102; 201, 202], validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, sparse(validUids), validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, uint64(validUids), validTimeCount), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, validUids, 0), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, validUids, 2.5), ...
    @() materializePhysicalUidDirectedDeliveryUniforms( ...
        validSeed, validUids, Inf)};
for callIdx = 1:numel(invalidCalls)
    assertErrorId(invalidCalls{callIdx}, ...
        'PhysicalUidDeliveryUniforms:InvalidContract');
end
end

function expected = drawExpectedCanonical(seed, nodeCount, timeCount)
stateBefore = rng();
restoreState = onCleanup(@() rng(stateBefore));
rng(seed, 'twister');
expected = rand(nodeCount, nodeCount, timeCount);
clear restoreState;
end

function assertErrorId(callable, expectedId)
thrown = false;
try
    callable();
catch errorInfo
    thrown = true;
    assert(strcmp(errorInfo.identifier, expectedId), ...
        'Unexpected error identifier: %s', errorInfo.identifier);
end
assert(thrown, 'Expected error was not thrown.');
end
