function test_observable_one_hop_risk_label_v162()
% TESTOBSERVABLEONEHOPRISKLABELV162 Minimum-risk source and byte ledger.

model = struct( ...
    'xDimension', 4, ...
    'existenceThreshold', 1e-2, ...
    'ospaParameters', struct('eC', 100));
receiver = makeObject(1, 1, 0.50, 100 * eye(4));
bestSource = makeObject(1, 1, 0.90, eye(4));
otherSource = makeObject(1, 1, 0.80, 20 * eye(4));
localPosteriorBySensor = {receiver, bestSource, otherSource};
physicalAdjacency = logical([0, 1, 1; 1, 0, 0; 1, 0, 0]);
directedLinkDelivered = physicalAdjacency;
config = struct( ...
    'observableOneHopRiskLabelEnabled', true, ...
    'observableOneHopRiskLabelTimes', 5, ...
    'observableOneHopRiskLabelSensorIdsByTime', {{1}}, ...
    'observableOneHopRiskLabelMaximumEdits', 1, ...
    'observableOneHopRiskLabelExistenceThreshold', 1e-2, ...
    'observableOneHopRiskLabelMinimumRiskReduction', 0, ...
    'observableOneHopRiskLabelSynopsisHeaderBytes', 16, ...
    'observableOneHopRiskLabelSynopsisBytesPerLabel', 8, ...
    'observableOneHopRiskLabelRequestHeaderBytes', 16, ...
    'observableOneHopRiskLabelRequestBytesPerLabel', 8);

[posterior, details] = selectObservableOneHopRiskLabels( ...
    receiver, localPosteriorBySensor, physicalAdjacency, ...
    directedLinkDelivered, config, 1, 5, model);
assert(details.triggered && details.applied);
assert(details.selectedLabelCount == 1 && details.appliedLabelCount == 1);
assert(isequal(details.selectedSources, 2));
assert(abs(posterior.r - bestSource.r) < 1e-12);
assert(details.attemptedSynopsisBytes == 48);
assert(details.attemptedRequestBytes == 24);
assert(details.attemptedResponseBytes > 0);
assert(details.attemptedTotalBytes == details.deliveredTotalBytes);
assert(~details.truthUsed && ~details.futureInformationUsed);
fprintf('test_observable_one_hop_risk_label_v162 passed\n');
end

function object = makeObject(birthTime, birthLocation, existence, covariance)
object = struct( ...
    'birthTime', birthTime, ...
    'birthLocation', birthLocation, ...
    'r', existence, ...
    'numberOfGmComponents', 1, ...
    'w', 1, ...
    'mu', {{zeros(4, 1)}}, ...
    'Sigma', {{covariance}});
end
