function test_online_positive_net_addressable_payload_v99()
% TEST_ONLINEPOSITIVENETADDRESSABLEPAYLOADV99 Runtime boundary.

protocol = getOnlinePositiveNetAddressablePayloadV99Protocol();
assert(numel(protocol.cases) == 2);
assert(strcmp(protocol.receiverMode, 'fov-aware-censored'));
entry = protocol.cases(2);
currentTime = entry.anchorTimes(1);
actionName = 'v99-online-positive-net-f1-f2-f4-f5';
context = ...
    buildOnlinePositiveNetAddressablePayloadV99ExecutionContext( ...
        entry.presetName, entry.seed, currentTime, actionName, true, true);
assert(isOnlinePositiveNetAddressablePayloadV99ExecutionContext(context));
assert(context.onlineReselectionEnabled);

model = struct( ...
    'numberOfSensors', entry.expectedNodeCount, ...
    'dynamicTopologyScenario', struct( ...
        'presetName', entry.presetName, 'seed', entry.seed, ...
        'config', struct( ...
            'formationCount', entry.expectedFormationCount)));
schedule = { ...
    [1, 2, 4, 5], [1, 2, 4, 5], [1, 2, 4, 5]};
request = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-authorization-request-v1', ...
    'operation', 'filter-execution', ...
    'measurementTimeCount', context.measurementTimeCount, ...
    'sensorTrajectoryTimeCounts', ...
        context.measurementTimeCount * ...
            ones(1, entry.expectedNodeCount), ...
    'triggerConfig', struct( ...
        'topologyPolicyName', protocol.outcomePolicyName, ...
        'topologyPolicyHistoryDepth', 2, ...
        'receiverSafeLabelFusionEnabled', true, ...
        'receiverSafeLabelFusionMode', ...
            'formation-supported-label-plan', ...
        'receiverSafeExternalActiveTimes', ...
            currentTime + (0:(protocol.horizonSteps - 1)), ...
        'receiverSafeFormationConditionedSchedule', {schedule}, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled', true, ...
        'receiverSafeFormationConditionedPayloadMode', ...
            'control-only'));
authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    model, context, request);
assert(authorization.trackingOutcomeScoringAuthorized);
assert(strcmp(authorization.protocolId, protocol.id));

request.triggerConfig. ...
    receiverSafeFormationConditionedOnlinePolicyEnabled = false;
failedClosed = false;
try
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        model, context, request);
catch errorInfo
    failedClosed = strcmp(errorInfo.identifier, ...
        'OnlinePositiveNetV99:InvalidRuntimeRequest');
end
assert(failedClosed);

v100 = getOnlinePositiveNetPropagationV100Protocol();
v100Action = 'v100-online-positive-net-h6-f1-f2-f4-f5';
v100Context = ...
    buildOnlinePositiveNetPropagationV100ExecutionContext( ...
        entry.presetName, entry.seed, currentTime, ...
        v100Action, true, true);
assert(isOnlinePositiveNetPropagationV100ExecutionContext(v100Context));
v100Schedule = repmat({[1, 2, 4, 5]}, 1, v100.horizonSteps);
v100Request = request;
v100Request.measurementTimeCount = ...
    v100Context.measurementTimeCount;
v100Request.sensorTrajectoryTimeCounts = ...
    v100Context.measurementTimeCount * ...
        ones(1, entry.expectedNodeCount);
v100Request.triggerConfig.topologyPolicyName = ...
    v100.outcomePolicyName;
v100Request.triggerConfig.receiverSafeExternalActiveTimes = ...
    currentTime + (0:(v100.horizonSteps - 1));
v100Request.triggerConfig.receiverSafeFormationConditionedSchedule = ...
    v100Schedule;
v100Request.triggerConfig. ...
    receiverSafeFormationConditionedOnlinePolicyEnabled = true;
v100Authorization = assertDynamicTopologyTrackingOutcomeAuthorized( ...
    model, v100Context, v100Request);
assert(strcmp(v100Authorization.protocolId, v100.id));
end
