function plan = buildFormationConditionedSupportedLabelMessagePlan( ...
        localPosteriorBySensor, crossResidualEdgeMask, ...
        updateDiagnostics, model, triggerConfig, currentTime)
% BUILDFORMATIONCONDITIONEDSUPPORTEDLABELMESSAGEPLAN V62 layered payload.
%
% A frozen observable formation schedule selects where cross-formation input
% is restricted.  Within those physical carrier edges, the payload mode uses
% current sender/receiver association support to decide which complete
% Bernoulli Gaussian mixtures remain in the effective per-label graph.

sensorCount = numel(localPosteriorBySensor);
if ~iscell(localPosteriorBySensor) || ...
        ~isequal(size(crossResidualEdgeMask), ...
            [sensorCount, sensorCount]) || ...
        ~iscell(updateDiagnostics) || ...
        numel(updateDiagnostics) ~= sensorCount || ...
        ~isscalar(currentTime) || ~isfinite(currentTime)
    error('FormationSupportedLabelPlan:InvalidInput', ...
        'The posterior, carrier edge mask, diagnostics, or time is invalid.');
end
times = reshape(triggerConfig. ...
    receiverSafeFormationConditionedTimes, 1, []);
schedules = triggerConfig. ...
    receiverSafeFormationConditionedSchedule;
timeIdx = find(times == currentTime, 1);
if isempty(timeIdx) || timeIdx > numel(schedules)
    error('FormationSupportedLabelPlan:ScheduleMissing', ...
        'The current time is absent from the V62 formation schedule.');
end
scheduledFormationIds = reshape(schedules{timeIdx}, 1, []);
groupIds = resolveFormationGroups(model, sensorCount);
payloadMode = lower(strrep(char(triggerConfig. ...
    receiverSafeFormationConditionedPayloadMode), '_', '-'));
supportThreshold = triggerConfig. ...
    receiverSafeExternalPositiveSupportThreshold;
existenceThreshold = triggerConfig. ...
    receiverSafeFormationConditionedHighExistenceThreshold;
activeThreshold = triggerConfig.payloadExistenceThreshold;

crossResidualEdgeMask = logical(crossResidualEdgeMask);
crossResidualEdgeMask(1:sensorCount+1:end) = false;
selectiveEdgeMask = false(sensorCount);
for receiverIdx = 1:sensorCount
    if ismember(groupIds(receiverIdx), scheduledFormationIds)
        selectiveEdgeMask(:, receiverIdx) = ...
            crossResidualEdgeMask(:, receiverIdx);
    end
end

plan = struct();
plan.contractVersion = ...
    'formation-conditioned-supported-label-message-plan-v62-v1';
plan.mode = 'formation-supported-label-plan';
plan.payloadMode = payloadMode;
plan.currentTime = currentTime;
plan.scheduledFormationIds = scheduledFormationIds;
plan.selectiveEdgeMask = selectiveEdgeMask;
plan.payloadByReceiverSender = cell(sensorCount);
plan.synopsisByReceiverSender = cell(sensorCount);
plan.receiverDetails = repmat(makeReceiverDetails(), 1, sensorCount);
plan.activeLabelCountBySender = zeros(1, sensorCount);
plan.usesFullSenderPosteriors = false;
plan.isOnlineDeployable = true;
plan.evidenceLabelInputCounts = struct( ...
    'positiveSupport', 0, ...
    'credibleNegative', 0, ...
    'unsupportedAbsence', 0, ...
    'ambiguous', 0, ...
    'missing', 0);

for receiverIdx = reshape(find(any(selectiveEdgeMask, 1)), 1, [])
    senders = reshape(find(selectiveEdgeMask(:, receiverIdx)), 1, []);
    receiverObjects = activeObjects( ...
        localPosteriorBySensor{receiverIdx}, activeThreshold);
    details = makeReceiverDetails();
    details.receiverIdx = receiverIdx;
    details.senders = senders;
    for localSenderIdx = 1:numel(senders)
        senderIdx = senders(localSenderIdx);
        senderObjects = activeObjects( ...
            localPosteriorBySensor{senderIdx}, activeThreshold);
        keepMask = selectLabels( ...
            senderObjects, receiverObjects, payloadMode, ...
            supportThreshold, existenceThreshold);
        payload = senderObjects(keepMask);
        baselineStats = estimateLmbPayloadSize( ...
            senderObjects, model, 2, updateDiagnostics{senderIdx});
        selectedStats = estimateLmbPayloadSize( ...
            payload, model, 2, updateDiagnostics{senderIdx});
        synopsis = compactSynopsis( ...
            numel(senderObjects), model.xDimension);
        plan.payloadByReceiverSender{receiverIdx, senderIdx} = payload;
        plan.synopsisByReceiverSender{receiverIdx, senderIdx} = synopsis;
        plan.activeLabelCountBySender(senderIdx) = max( ...
            plan.activeLabelCountBySender(senderIdx), ...
            numel(senderObjects));
        plan.evidenceLabelInputCounts = accumulateSupportCounts( ...
            plan.evidenceLabelInputCounts, senderObjects, ...
            supportThreshold);
        details.baselineFullBytesBySender(localSenderIdx) = ...
            baselineStats.estimatedBytes;
        details.controlSynopsisBytesBySender(localSenderIdx) = ...
            synopsis.estimatedBytes;
        details.selectedPayloadBytesBySender(localSenderIdx) = ...
            selectedStats.estimatedBytes;
        details.candidateLabelCount = ...
            details.candidateLabelCount + numel(senderObjects);
        details.selectedLabelCount = ...
            details.selectedLabelCount + nnz(keepMask);
    end
    details.baselineFullBytes = sum(details.baselineFullBytesBySender);
    details.controlSynopsisBytes = sum( ...
        details.controlSynopsisBytesBySender);
    details.selectedPayloadBytes = sum( ...
        details.selectedPayloadBytesBySender);
    details.totalAttemptedBytes = ...
        details.controlSynopsisBytes + details.selectedPayloadBytes;
    details.byteBudget = details.baselineFullBytes;
    details.byteBudgetSatisfied = ...
        details.totalAttemptedBytes <= details.byteBudget + 1e-9;
    plan.receiverDetails(receiverIdx) = details;
end

details = plan.receiverDetails;
plan.totalBaselineFullBytes = sum([details.baselineFullBytes]);
plan.totalControlSynopsisBytes = sum([details.controlSynopsisBytes]);
plan.totalSelectedPayloadBytes = sum([details.selectedPayloadBytes]);
plan.totalAttemptedBytes = sum([details.totalAttemptedBytes]);
plan.totalSelectedLabelCount = sum([details.selectedLabelCount]);
plan.totalCandidateLabelCount = sum([details.candidateLabelCount]);
plan.byteBudgetSatisfied = plan.totalAttemptedBytes <= ...
    plan.totalBaselineFullBytes + 1e-9;
end

function keep = selectLabels( ...
        senderObjects, receiverObjects, mode, supportThreshold, ...
        existenceThreshold)
keep = false(1, numel(senderObjects));
for objectIdx = 1:numel(senderObjects)
    senderObject = senderObjects(objectIdx);
    label = [senderObject.birthTime; senderObject.birthLocation];
    receiverObject = findObject(receiverObjects, label);
    senderSupport = supportOf(senderObject);
    receiverSupport = supportOf(receiverObject);
    switch mode
        case 'control-only'
            keep(objectIdx) = false;
        case 'sender-supported-only'
            keep(objectIdx) = senderSupport >= supportThreshold - 1e-12;
        case 'sender-supported-or-high-existence'
            keep(objectIdx) = ...
                senderSupport >= supportThreshold - 1e-12 || ...
                senderObject.r >= existenceThreshold - 1e-12;
        case 'receiver-need-aware'
            keep(objectIdx) = ...
                senderSupport >= supportThreshold - 1e-12 || ...
                receiverSupport < supportThreshold - 1e-12;
        otherwise
            error('FormationSupportedLabelPlan:UnknownPayloadMode', ...
                'Unknown V62 payload mode: %s.', mode);
    end
end
end

function groups = resolveFormationGroups(model, sensorCount)
if ~isstruct(model) || ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isfield(model.dynamicTopologyScenario, 'config') || ...
        ~isfield(model.dynamicTopologyScenario.config, 'sensorGroupIds')
    error('FormationSupportedLabelPlan:MissingFormationGroups', ...
        'The V62 runtime model lacks formation membership.');
end
groups = reshape( ...
    model.dynamicTopologyScenario.config.sensorGroupIds, 1, []);
if numel(groups) ~= sensorCount
    error('FormationSupportedLabelPlan:InvalidFormationGroups', ...
        'The V62 formation membership does not match the sensor count.');
end
end

function objects = activeObjects(objects, threshold)
if isempty(objects)
    return;
end
objects = objects([objects.r] > threshold & ...
    [objects.numberOfGmComponents] > 0);
end

function object = findObject(objects, label)
object = [];
for objectIdx = 1:numel(objects)
    if objects(objectIdx).birthTime == label(1) && ...
            objects(objectIdx).birthLocation == label(2)
        object = objects(objectIdx);
        return;
    end
end
end

function value = supportOf(object)
value = 0;
if isstruct(object) && isscalar(object) && ...
        isfield(object, 'detectionAssociationMass') && ...
        isscalar(object.detectionAssociationMass) && ...
        isfinite(object.detectionAssociationMass)
    value = min(max(object.detectionAssociationMass, 0), 1);
end
end

function synopsis = compactSynopsis(labelCount, stateDimension)
positionDimension = min(2, stateDimension);
velocityDimension = stateDimension - positionDimension;
positionCovarianceScalars = ...
    positionDimension * (positionDimension + 1) / 2;
floatCount = 5 + stateDimension + ...
    positionCovarianceScalars + velocityDimension;
rawPerLabelBytes = 4 + 4 * floatCount + 2;
perLabelBytes = 4 * ceil(rawPerLabelBytes / 4);
estimatedBytes = 16 + labelCount * perLabelBytes;
synopsis = struct( ...
    'contractVersion', 'lmb-label-control-synopsis-v2-compact-cost', ...
    'labelCount', labelCount, ...
    'estimatedBytes', estimatedBytes, ...
    'scalarCount', estimatedBytes / 8);
end

function counts = accumulateSupportCounts(counts, objects, threshold)
for objectIdx = 1:numel(objects)
    if supportOf(objects(objectIdx)) >= threshold - 1e-12
        counts.positiveSupport = counts.positiveSupport + 1;
    else
        counts.ambiguous = counts.ambiguous + 1;
    end
end
end

function details = makeReceiverDetails()
details = struct( ...
    'receiverIdx', 0, ...
    'senders', [], ...
    'baselineFullBytesBySender', [], ...
    'controlSynopsisBytesBySender', [], ...
    'selectedPayloadBytesBySender', [], ...
    'baselineFullBytes', 0, ...
    'controlSynopsisBytes', 0, ...
    'selectedPayloadBytes', 0, ...
    'totalAttemptedBytes', 0, ...
    'selectedLabelCount', 0, ...
    'candidateLabelCount', 0, ...
    'byteBudget', 0, ...
    'byteBudgetSatisfied', true);
end
