function config = buildMixtureAwareKlaReferenceConfig(overrides)
% BUILDMIXTUREAWAREKLAREFERENCECONFIG Controlled density-preserving path.
%
% This config activates the repository's componentwise powered-GM KLA
% approximation. It preserves multiple spatial modes, but it is not an
% exact closed-form power of an arbitrary Gaussian mixture. Experiments
% using it must retain that numerical-approximation qualification.

if nargin < 1 || isempty(overrides)
    overrides = struct();
end
config = struct( ...
    'eventPolicy', 'alwaysHeavy', ...
    'linkGateEnabled', false, ...
    'forceInitialHeavy', false, ...
    'forceLabelChangeHeavy', false, ...
    'forceStaleHeavy', false, ...
    'payloadExistenceThreshold', 0.01, ...
    'activeExistenceThreshold', 0.01, ...
    'fusionWeightMode', 'metropolis', ...
    'mixtureAwareHeavyFusionEnabled', true, ...
    'mixtureAwareRequireHeavyInput', true, ...
    'mixtureAwareTopComponents', 3, ...
    'mixtureAwareMaxFusedComponents', 8, ...
    'mixtureAwareMaxComponentTuples', 256, ...
    'mixtureAwareMinEntropy', 0, ...
    'mixtureAwareMinComponentCount', 2, ...
    'mixtureAwareMinExistence', 0, ...
    'mixtureAwareMinAssociationAmbiguity', 0, ...
    'mixtureAwareMinDetectionAssociationMass', 0, ...
    'mixtureAwareMaxFusedEntropy', 1, ...
    'mixtureAwareMinFusedDominance', 0, ...
    'mixtureAwareExistenceEtaMode', 'mixtureAware', ...
    'missingLabelFusionMode', 'support-renormalized', ...
    'fovAwareMissingLabelMinimumFovFraction', 0.50, ...
    ['fovAwareMissingLabelMinimumExpected', ...
     'DetectionProbability'], 0.10, ...
    'fovAwareMissingLabelIgnoreStaleAbsence', true, ...
    'mixtureAwareStateExtractionEnabled', true, ...
    'mixtureAwareExtractionMinSeparation', 0, ...
    'mixtureAwareJointExtractionEnabled', false);

fields = fieldnames(overrides);
for fieldIdx = 1:numel(fields)
    config.(fields{fieldIdx}) = overrides.(fields{fieldIdx});
end
end
