function [objects, diagnostics] = ...
        canonicalizeLmbGaussianMixtureRepresentation(objects, options)
% CANONICALIZELMBGAUSSIANMIXTUREREPRESENTATION Merge exact GM copies.
%
% A Gaussian-mixture density is unchanged when bit-identical components
% are replaced by one component whose weight is their sum.  Canonicalizing
% before pruning and component-count truncation prevents arbitrary duplicate
% copies from consuming the mixture budget.  With zero pruning threshold
% and an infinite component cap, the operation is exactly density preserving.

if nargin < 2 || isempty(options)
    options = struct();
end
weightThreshold = getField(options, 'weightThreshold', 0);
maximumComponentCount = getField(options, ...
    'maximumComponentCount', inf);
if ~isscalar(weightThreshold) || ~isfinite(weightThreshold) || ...
        weightThreshold < 0 || ~isscalar(maximumComponentCount) || ...
        isnan(maximumComponentCount) || maximumComponentCount < 1 || ...
        (~isinf(maximumComponentCount) && ...
         maximumComponentCount ~= round(maximumComponentCount))
    error('CanonicalLmbGm:InvalidOptions', ...
        'The GM canonicalization options are malformed.');
end

diagnostics = struct( ...
    'contractVersion', 'canonical-lmb-gm-representation-v1', ...
    'objectCount', numel(objects), ...
    'inputComponentCount', 0, ...
    'identicalCopyCount', 0, ...
    'canonicalComponentCountBeforeReduction', 0, ...
    'prunedComponentCount', 0, ...
    'truncatedComponentCount', 0, ...
    'discardedNormalizedWeightMass', 0, ...
    'outputComponentCount', 0, ...
    'exactDensityPreserved', true);
for objectIdx = 1:numel(objects)
    object = objects(objectIdx);
    componentCount = object.numberOfGmComponents;
    if ~isscalar(componentCount) || ~isfinite(componentCount) || ...
            componentCount < 0 || componentCount ~= round(componentCount) || ...
            numel(object.w) ~= componentCount || ...
            numel(object.mu) ~= componentCount || ...
            numel(object.Sigma) ~= componentCount
        error('CanonicalLmbGm:MalformedObject', ...
            'An LMB object has an inconsistent Gaussian mixture.');
    end
    diagnostics.inputComponentCount = ...
        diagnostics.inputComponentCount + componentCount;
    if componentCount == 0
        continue;
    end

    weights = reshape(object.w, 1, []);
    if any(~isfinite(weights)) || any(weights < 0)
        error('CanonicalLmbGm:InvalidWeights', ...
            'Gaussian-mixture weights must be finite and nonnegative.');
    end
    if sum(weights) <= 0
        error('CanonicalLmbGm:ZeroWeightMixture', ...
            'A nonempty Gaussian mixture has no positive weight.');
    end
    weights = weights / sum(weights);

    representatives = zeros(1, 0);
    canonicalWeights = zeros(1, 0);
    for componentIdx = 1:componentCount
        representativePosition = 0;
        for position = 1:numel(representatives)
            representativeIdx = representatives(position);
            if isequal(object.mu{componentIdx}, ...
                    object.mu{representativeIdx}) && ...
                    isequal(object.Sigma{componentIdx}, ...
                    object.Sigma{representativeIdx})
                representativePosition = position;
                break;
            end
        end
        if representativePosition == 0
            representatives(end + 1) = componentIdx; %#ok<AGROW>
            canonicalWeights(end + 1) = weights(componentIdx); %#ok<AGROW>
        else
            canonicalWeights(representativePosition) = ...
                canonicalWeights(representativePosition) + ...
                weights(componentIdx);
        end
    end
    canonicalCount = numel(representatives);
    diagnostics.identicalCopyCount = ...
        diagnostics.identicalCopyCount + componentCount - canonicalCount;
    diagnostics.canonicalComponentCountBeforeReduction = ...
        diagnostics.canonicalComponentCountBeforeReduction + canonicalCount;

    [~, ordering] = sortrows( ...
        [-reshape(canonicalWeights, [], 1), ...
         reshape(representatives, [], 1)], [1, 2]);
    canonicalWeights = canonicalWeights(ordering);
    representatives = representatives(ordering);

    keep = canonicalWeights > weightThreshold;
    if ~any(keep)
        keep(1) = true;
    end
    diagnostics.prunedComponentCount = ...
        diagnostics.prunedComponentCount + nnz(~keep);
    diagnostics.discardedNormalizedWeightMass = ...
        diagnostics.discardedNormalizedWeightMass + ...
        sum(canonicalWeights(~keep));
    canonicalWeights = canonicalWeights(keep);
    representatives = representatives(keep);
    keepCount = min(numel(representatives), maximumComponentCount);
    diagnostics.truncatedComponentCount = ...
        diagnostics.truncatedComponentCount + ...
        numel(representatives) - keepCount;
    diagnostics.discardedNormalizedWeightMass = ...
        diagnostics.discardedNormalizedWeightMass + ...
        sum(canonicalWeights((keepCount + 1):end));
    canonicalWeights = canonicalWeights(1:keepCount);
    representatives = representatives(1:keepCount);
    canonicalWeights = canonicalWeights / sum(canonicalWeights);

    object.numberOfGmComponents = keepCount;
    object.w = reshape(canonicalWeights, 1, []);
    object.mu = reshape(object.mu(representatives), 1, []);
    object.Sigma = reshape(object.Sigma(representatives), 1, []);
    objects(objectIdx) = object;
    diagnostics.outputComponentCount = ...
        diagnostics.outputComponentCount + keepCount;
end
diagnostics.exactDensityPreserved = ...
    diagnostics.discardedNormalizedWeightMass == 0;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
