function [route, details] = preparePolicyLabelInputRouteV265( ...
        localPosteriorBySensor, physicalAdjacency, directedLinkDelivered, ...
        schedule, model, currentTime, config)
% PREPAREPOLICYLABELINPUTROUTEV265 Resolve and charge one selected label.

sensorCount = numel(localPosteriorBySensor);
route = emptyRoute();
details = emptyDetails();
details.currentTime = currentTime;
if ~isstruct(schedule) || ~isscalar(schedule) || ...
        ~logical(getField(schedule, 'labelShortcutActive', false))
    return;
end
required = {'contractVersion', 'selectedLocalizationLabel', ...
    'labelShortcutSourceSensorId', 'labelShortcutReceiverSensorId', ...
    'labelShortcutSourceWeight'};
validScheduleVersion = isfield(schedule, 'contractVersion') && ...
    ischar(schedule.contractVersion) && ...
    ismember(schedule.contractVersion, { ...
        'label-selective-risk-shortcut-v265-schedule-v1', ...
        'eta-projected-label-trust-v266-schedule-v1'});
if any(~isfield(schedule, required)) || ~validScheduleVersion || ...
        ~iscell(localPosteriorBySensor) || sensorCount < 1 || ...
        ~isequal(size(physicalAdjacency), [sensorCount, sensorCount]) || ...
        ~isequal(size(directedLinkDelivered), [sensorCount, sensorCount])
    error('LabelSelectiveRiskShortcutV265:InvalidRouteSchedule', ...
        'The V265 policy label-route schedule is malformed.');
end
sourceId = schedule.labelShortcutSourceSensorId;
receiverId = schedule.labelShortcutReceiverSensorId;
label = reshape(schedule.selectedLocalizationLabel, [], 1);
sourceWeight = schedule.labelShortcutSourceWeight;
weightMode = getField(schedule, ...
    'labelShortcutWeightMode', 'proportional-share');
if ischar(weightMode)
    weightMode = lower(strrep(weightMode, '_', '-'));
else
    weightMode = '';
end
sourceWeightGrid = reshape(getField(schedule, ...
    'labelShortcutSourceWeightGrid', sourceWeight), 1, []);
if ~validSensorId(sourceId, sensorCount) || ...
        ~validSensorId(receiverId, sensorCount) || sourceId == receiverId || ...
        numel(label) ~= 2 || any(~isfinite(label)) || ...
        any(label ~= round(label)) || any(label < 1) || ...
        ~isscalar(sourceWeight) || ~isfinite(sourceWeight) || ...
        sourceWeight <= 0 || sourceWeight >= 1 || ...
        ~ismember(weightMode, { ...
            'proportional-share', 'bounded-proportional-share'}) || ...
        isempty(sourceWeightGrid) || any(~isfinite(sourceWeightGrid)) || ...
        any(sourceWeightGrid <= 0) || any(sourceWeightGrid >= 1) || ...
        max(sourceWeightGrid) > sourceWeight + 1e-12
    error('LabelSelectiveRiskShortcutV265:InvalidRouteSchedule', ...
        'The V265 source, receiver, label or weight is malformed.');
end

details.scheduled = true;
details.sourceId = sourceId;
details.receiverId = receiverId;
details.label = reshape(label, 2, 1);
details.sourceWeight = sourceWeight;
details.sourceWeightGrid = sourceWeightGrid;
details.weightMode = weightMode;
details.physicalPassed = logical( ...
    physicalAdjacency(receiverId, sourceId));
sourceObject = findLabelObject( ...
    localPosteriorBySensor{sourceId}, label);
details.payloadPresent = ~isempty(sourceObject);
if details.payloadPresent
    payloadStats = estimateLmbPayloadSize( ...
        sourceObject, model, 2, struct());
    details.payloadPresent = payloadStats.objectCount == 1 && ...
        payloadStats.estimatedBytes > 0;
else
    payloadStats = struct('scalarCount', 0, 'estimatedBytes', 0);
end
if details.payloadPresent && details.physicalPassed
    details.attemptedPayloadScalars = payloadStats.scalarCount;
    details.attemptedPayloadBytes = payloadStats.estimatedBytes;
end
details.transportDelivered = details.payloadPresent && ...
    details.physicalPassed && ...
    logical(directedLinkDelivered(sourceId, receiverId));
if details.transportDelivered
    details.deliveredPayloadScalars = payloadStats.scalarCount;
    details.deliveredPayloadBytes = payloadStats.estimatedBytes;
    route.active = true;
    route.currentTime = currentTime;
    route.targetFormationId = getField(schedule, ...
        'selectedLocalizationFormationId', 0);
    route.receiverIds = receiverId;
    route.sourceId = sourceId;
    route.label = reshape(label, 2, 1);
    route.sourceObject = sourceObject;
    route.sourceWeight = sourceWeight;
    route.sourceWeightGrid = sourceWeightGrid;
    route.weightMode = weightMode;
    route.etaProjectionEnabled = logical(config. ...
        topologyPolicyLabelInputRouteEtaProjectionEnabled);
    route.minimumMapExistence = config. ...
        topologyPolicyLabelInputRouteMinimumMapExistence;
    route.maximumReferenceLogOddsDrop = config. ...
        topologyPolicyLabelInputRouteMaximumReferenceLogOddsDrop;
    route.maximumReferenceLogOddsIncrease = config. ...
        topologyPolicyLabelInputRouteMaximumReferenceLogOddsIncrease;
    route.transferFractionGrid = 1;
    route.etaIdentityTolerance = config. ...
        topologyPolicyLabelInputRouteEtaIdentityTolerance;
end
details.etaProjectionEnabled = logical(config. ...
    topologyPolicyLabelInputRouteEtaProjectionEnabled);
details.etaProjectionByReceiver = cell(1, sensorCount);
details.etaProjectionEvaluatedReceiverIds = zeros(1, 0);
details.etaProjectionAllowedReceiverIds = zeros(1, 0);
details.etaProjectionRejectedReceiverIds = zeros(1, 0);
details.routeAttachedReceiverIds = zeros(1, 0);
details.appliedReceiverIds = zeros(1, 0);
end

function object = findLabelObject(objects, label)
object = [];
objects = reshape(objects, 1, []);
for objectIdx = 1:numel(objects)
    candidate = objects(objectIdx);
    if candidate.numberOfGmComponents > 0 && ...
            candidate.birthTime == label(1) && ...
            candidate.birthLocation == label(2)
        object = candidate;
        return;
    end
end
end

function route = emptyRoute()
route = struct( ...
    'active', false, 'currentTime', 0, 'targetFormationId', 0, ...
    'receiverIds', zeros(1, 0), 'sourceId', 0, ...
    'label', zeros(2, 1), 'sourceObject', [], ...
    'sourceWeight', 0, 'sourceWeightGrid', zeros(1, 0), ...
    'weightMode', '', ...
    'etaProjectionEnabled', false, ...
    'minimumMapExistence', 0.50, ...
    'maximumReferenceLogOddsDrop', 0, ...
    'maximumReferenceLogOddsIncrease', Inf, ...
    'transferFractionGrid', 1, ...
    'etaIdentityTolerance', 1e-8);
end

function details = emptyDetails()
details = struct( ...
    'contractVersion', ...
        'policy-label-input-route-page-v265-v1', ...
    'currentTime', 0, 'scheduled', false, ...
    'sourceId', 0, 'receiverId', 0, ...
    'label', zeros(2, 0), 'sourceWeight', 0, ...
    'sourceWeightGrid', zeros(1, 0), 'weightMode', '', ...
    'physicalPassed', false, 'payloadPresent', false, ...
    'transportDelivered', false, ...
    'attemptedPayloadScalars', 0, 'attemptedPayloadBytes', 0, ...
    'deliveredPayloadScalars', 0, 'deliveredPayloadBytes', 0, ...
    'etaProjectionEnabled', false, ...
    'etaProjectionByReceiver', {{}}, ...
    'etaProjectionEvaluatedReceiverIds', zeros(1, 0), ...
    'etaProjectionAllowedReceiverIds', zeros(1, 0), ...
    'etaProjectionRejectedReceiverIds', zeros(1, 0), ...
    'routeAttachedReceiverIds', zeros(1, 0), ...
    'appliedReceiverIds', zeros(1, 0), ...
    'truthUsed', false, 'futureInformationUsed', false, ...
    'centralizedControlSynopsisCostIncluded', false);
end

function valid = validSensorId(value, sensorCount)
valid = isscalar(value) && isnumeric(value) && isfinite(value) && ...
    value == round(value) && value >= 1 && value <= sensorCount;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
