function [route, packetCache, details] = ...
        prepareSourcePreservingLabelPacketRouteV268( ...
            localPosteriorBySensor, physicalAdjacency, ...
            directedLinkDelivered, currentDirectedEdgeMask, schedule, ...
            model, currentTime, packetCache, config)
% PREPARESOURCEPRESERVINGLABELPACKETROUTEV268 Route without relay fusion.
%
% A newly scheduled complete Bernoulli-GM label is transported from its
% source to one relay and cached there without changing the relay LMB.  A
% packet cached on the previous page is predicted to the current time,
% transported from the relay to the target formation, and exposed as one
% source-preserving input to the final receiver's ordinary label-wise KLA.

sensorCount = numel(localPosteriorBySensor);
validateInputs(localPosteriorBySensor, physicalAdjacency, ...
    directedLinkDelivered, currentDirectedEdgeMask, model, currentTime, ...
    packetCache, config);
route = emptyRoute();
details = emptyDetails(sensorCount);
details.currentTime = currentTime;

% Complete at most one previously admitted packet before admitting the
% current page's first hop.  Packets are single-shot: a failed/blocked
% second hop is not retried, so latency and communication are explicit.
if isActivePacket(packetCache)
    [route, secondHop, packetCache] = completeSecondHop( ...
        packetCache, localPosteriorBySensor, physicalAdjacency, ...
        directedLinkDelivered, currentDirectedEdgeMask, model, ...
        currentTime, config);
    details = mergeSecondHop(details, secondHop);
end

if isstruct(schedule) && isscalar(schedule) && ...
        logical(getField(schedule, 'labelShortcutActive', false))
    [packetCache, firstHop] = admitFirstHop( ...
        packetCache, localPosteriorBySensor, physicalAdjacency, ...
        directedLinkDelivered, schedule, model, currentTime, config);
    details = mergeFirstHop(details, firstHop);
end

details.scheduled = details.firstHopScheduled || ...
    details.secondHopScheduled;
details.transportDelivered = details.secondHopDelivered;
details.attemptedPayloadScalars = sum( ...
    details.attemptedPayloadScalarsByEdge(:));
details.attemptedPayloadBytes = sum( ...
    details.attemptedPayloadBytesByEdge(:));
details.deliveredPayloadScalars = sum( ...
    details.deliveredPayloadScalarsByEdge(:));
details.deliveredPayloadBytes = sum( ...
    details.deliveredPayloadBytesByEdge(:));
details.packetCacheActiveAfterPage = isActivePacket(packetCache);
end

function [route, hop, packetCache] = completeSecondHop( ...
        packetCache, localPosteriorBySensor, physicalAdjacency, ...
        directedLinkDelivered, currentDirectedEdgeMask, model, ...
        currentTime, config)
sensorCount = numel(localPosteriorBySensor);
route = emptyRoute();
hop = emptySecondHop(sensorCount);
hop.scheduled = true;
hop.originalSourceId = packetCache.originalSourceId;
hop.senderId = packetCache.relaySensorId;
hop.sourceTime = packetCache.sourceTime;
hop.age = currentTime - packetCache.sourceTime;
hop.label = packetCache.label;
hop.targetFormationId = packetCache.targetFormationId;
hop.sourceWeight = packetCache.sourceWeight;
hop.sourceWeightGrid = packetCache.sourceWeightGrid;
hop.weightMode = packetCache.weightMode;

% Consume the packet irrespective of second-hop outcome.  V268 deliberately
% screens a bounded one-page delay rather than an implicit retry protocol.
packet = packetCache;
packetCache = emptyPacket();
if hop.age < 1 || hop.age > config. ...
        topologyPolicySourcePreservingLabelPacketMaximumAge
    hop.expired = true;
    hop.rejectionReason = 'packet-age-outside-registered-window';
    return;
end

groupIds = reshape(model.dynamicTopologyScenario.config.sensorGroupIds, ...
    1, []);
targetMembers = find(groupIds == packet.targetFormationId);
relayId = packet.relaySensorId;
physicalCandidates = targetMembers(logical( ...
    physicalAdjacency(targetMembers, relayId)));
if isempty(physicalCandidates)
    hop.rejectionReason = 'no-current-physical-second-hop';
    return;
end
beneficiaryMode = getField(config, ...
    'topologyPolicySourcePreservingLabelPacketBeneficiaryMode', ...
    'backbone-first');
[receiverId, receiverExistence, backboneAligned] = selectBeneficiary( ...
    beneficiaryMode, physicalCandidates, relayId, packet.label, ...
    localPosteriorBySensor, currentDirectedEdgeMask);
hop.beneficiaryMode = beneficiaryMode;
hop.receiverExistence = receiverExistence;
hop.backboneAligned = backboneAligned;
hop.receiverId = receiverId;
hop.physicalPassed = true;

predictedObject = predictPacketObject(packet.sourceObject, model, hop.age);
hop.payloadPresent = ~isempty(predictedObject);
if ~hop.payloadPresent
    hop.rejectionReason = 'predicted-packet-payload-empty';
    return;
end
payloadStats = packetPayloadStats(predictedObject, model, config);
hop.attemptedPayloadScalarsByEdge(relayId, receiverId) = ...
    payloadStats.scalarCount;
hop.attemptedPayloadBytesByEdge(relayId, receiverId) = ...
    payloadStats.estimatedBytes;
hop.delivered = logical(directedLinkDelivered(relayId, receiverId));
if ~hop.delivered
    hop.rejectionReason = 'second-hop-transport-drop';
    return;
end
hop.deliveredPayloadScalarsByEdge(relayId, receiverId) = ...
    payloadStats.scalarCount;
hop.deliveredPayloadBytesByEdge(relayId, receiverId) = ...
    payloadStats.estimatedBytes;

route.active = true;
route.currentTime = currentTime;
route.targetFormationId = packet.targetFormationId;
route.receiverIds = receiverId;
route.sourceId = packet.originalSourceId;
route.transportSenderId = relayId;
route.sourceTimestamp = packet.sourceTime;
route.packetAge = hop.age;
route.label = packet.label;
route.sourceObject = predictedObject;
route.sourceWeight = packet.sourceWeight;
route.sourceWeightGrid = packet.sourceWeightGrid;
route.weightMode = packet.weightMode;
route.forceAppendPreservedSource = true;
route.etaProjectionEnabled = logical(config. ...
    topologyPolicyLabelInputRouteEtaProjectionEnabled);
route.minimumMapExistence = config. ...
    topologyPolicyLabelInputRouteMinimumMapExistence;
route.maximumReferenceLogOddsDrop = config. ...
    topologyPolicyLabelInputRouteMaximumReferenceLogOddsDrop;
route.maximumSubMapReferenceLogOddsDrop = config. ...
    topologyPolicyLabelInputRouteMaximumSubMapReferenceLogOddsDrop;
route.maximumReferenceLogOddsIncrease = config. ...
    topologyPolicyLabelInputRouteMaximumReferenceLogOddsIncrease;
route.transferFractionGrid = 1;
route.etaIdentityTolerance = config. ...
    topologyPolicyLabelInputRouteEtaIdentityTolerance;
hop.routeActive = true;
end

function [packetCache, hop] = admitFirstHop( ...
        packetCache, localPosteriorBySensor, physicalAdjacency, ...
        directedLinkDelivered, schedule, model, currentTime, config)
sensorCount = numel(localPosteriorBySensor);
hop = emptyFirstHop(sensorCount);
validateSchedule(schedule, sensorCount);
hop.scheduled = true;
hop.sourceId = schedule.labelShortcutSourceSensorId;
hop.receiverId = schedule.labelShortcutReceiverSensorId;
hop.label = reshape(schedule.selectedLocalizationLabel, 2, 1);
hop.targetFormationId = schedule.selectedLocalizationFormationId;
hop.sourceWeight = schedule.labelShortcutSourceWeight;
hop.sourceWeightGrid = reshape(getField(schedule, ...
    'labelShortcutSourceWeightGrid', hop.sourceWeight), 1, []);
hop.weightMode = lower(strrep(getField(schedule, ...
    'labelShortcutWeightMode', 'bounded-proportional-share'), '_', '-'));
hop.physicalPassed = logical( ...
    physicalAdjacency(hop.receiverId, hop.sourceId));
sourceObject = findLabelObject( ...
    localPosteriorBySensor{hop.sourceId}, hop.label);
hop.payloadPresent = ~isempty(sourceObject);
if hop.payloadPresent
    payloadStats = packetPayloadStats(sourceObject, model, config);
else
    payloadStats = struct('scalarCount', 0, 'estimatedBytes', 0);
end
if hop.payloadPresent && hop.physicalPassed
    hop.attemptedPayloadScalarsByEdge( ...
        hop.sourceId, hop.receiverId) = payloadStats.scalarCount;
    hop.attemptedPayloadBytesByEdge( ...
        hop.sourceId, hop.receiverId) = payloadStats.estimatedBytes;
end
hop.delivered = hop.payloadPresent && hop.physicalPassed && ...
    logical(directedLinkDelivered(hop.sourceId, hop.receiverId));
if ~hop.delivered
    if ~hop.payloadPresent
        hop.rejectionReason = 'first-hop-payload-missing';
    elseif ~hop.physicalPassed
        hop.rejectionReason = 'first-hop-not-physical';
    else
        hop.rejectionReason = 'first-hop-transport-drop';
    end
    return;
end
hop.deliveredPayloadScalarsByEdge( ...
    hop.sourceId, hop.receiverId) = payloadStats.scalarCount;
hop.deliveredPayloadBytesByEdge( ...
    hop.sourceId, hop.receiverId) = payloadStats.estimatedBytes;

% A second-hop completion is processed before this admission, so a cache
% collision would signal an unregistered latency/retry behavior.
if isActivePacket(packetCache)
    error('SourcePreservingLabelPacketV268:PacketCacheCollision', ...
        'The single-slot source-preserving packet cache is occupied.');
end
packetCache = struct( ...
    'contractVersion', 'source-preserving-label-packet-v268-v1', ...
    'active', true, ...
    'sourceTime', currentTime, ...
    'originalSourceId', hop.sourceId, ...
    'relaySensorId', hop.receiverId, ...
    'targetFormationId', hop.targetFormationId, ...
    'label', hop.label, ...
    'sourceObject', sourceObject, ...
    'sourceWeight', hop.sourceWeight, ...
    'sourceWeightGrid', hop.sourceWeightGrid, ...
    'weightMode', hop.weightMode, ...
    'truthUsed', false, ...
    'futureInformationUsed', false);
hop.packetStored = true;
end

function details = mergeFirstHop(details, hop)
details.firstHopScheduled = hop.scheduled;
details.firstHopSourceId = hop.sourceId;
details.firstHopReceiverId = hop.receiverId;
details.firstHopLabel = hop.label;
details.firstHopTargetFormationId = hop.targetFormationId;
details.firstHopPhysicalPassed = hop.physicalPassed;
details.firstHopPayloadPresent = hop.payloadPresent;
details.firstHopDelivered = hop.delivered;
details.firstHopPacketStored = hop.packetStored;
details.firstHopRejectionReason = hop.rejectionReason;
details.attemptedPayloadScalarsByEdge = ...
    details.attemptedPayloadScalarsByEdge + ...
    hop.attemptedPayloadScalarsByEdge;
details.attemptedPayloadBytesByEdge = ...
    details.attemptedPayloadBytesByEdge + ...
    hop.attemptedPayloadBytesByEdge;
details.deliveredPayloadScalarsByEdge = ...
    details.deliveredPayloadScalarsByEdge + ...
    hop.deliveredPayloadScalarsByEdge;
details.deliveredPayloadBytesByEdge = ...
    details.deliveredPayloadBytesByEdge + ...
    hop.deliveredPayloadBytesByEdge;
if ~details.secondHopScheduled
    details.sourceId = hop.sourceId;
    details.receiverId = hop.receiverId;
    details.label = hop.label;
    details.sourceWeight = hop.sourceWeight;
    details.sourceWeightGrid = hop.sourceWeightGrid;
    details.weightMode = hop.weightMode;
end
end

function details = mergeSecondHop(details, hop)
details.secondHopScheduled = hop.scheduled;
details.secondHopOriginalSourceId = hop.originalSourceId;
details.secondHopSenderId = hop.senderId;
details.secondHopReceiverId = hop.receiverId;
details.secondHopSourceTime = hop.sourceTime;
details.secondHopAge = hop.age;
details.secondHopLabel = hop.label;
details.secondHopTargetFormationId = hop.targetFormationId;
details.secondHopPhysicalPassed = hop.physicalPassed;
details.secondHopPayloadPresent = hop.payloadPresent;
details.secondHopBackboneAligned = hop.backboneAligned;
details.secondHopBeneficiaryMode = hop.beneficiaryMode;
details.secondHopReceiverExistence = hop.receiverExistence;
details.secondHopDelivered = hop.delivered;
details.secondHopRouteActive = hop.routeActive;
details.secondHopExpired = hop.expired;
details.secondHopRejectionReason = hop.rejectionReason;
details.attemptedPayloadScalarsByEdge = ...
    details.attemptedPayloadScalarsByEdge + ...
    hop.attemptedPayloadScalarsByEdge;
details.attemptedPayloadBytesByEdge = ...
    details.attemptedPayloadBytesByEdge + ...
    hop.attemptedPayloadBytesByEdge;
details.deliveredPayloadScalarsByEdge = ...
    details.deliveredPayloadScalarsByEdge + ...
    hop.deliveredPayloadScalarsByEdge;
details.deliveredPayloadBytesByEdge = ...
    details.deliveredPayloadBytesByEdge + ...
    hop.deliveredPayloadBytesByEdge;
details.sourceId = hop.senderId;
details.receiverId = hop.receiverId;
details.label = hop.label;
details.sourceWeight = hop.sourceWeight;
details.sourceWeightGrid = hop.sourceWeightGrid;
details.weightMode = hop.weightMode;
end

function stats = packetPayloadStats(object, model, config)
stats = estimateLmbPayloadSize(object, model, 2, struct());
metadataScalars = config. ...
    topologyPolicySourcePreservingLabelPacketMetadataScalars;
stats.scalarCount = stats.scalarCount + metadataScalars;
stats.estimatedBytes = stats.estimatedBytes + 8 * metadataScalars;
end

function [receiverId, existence, backboneAligned] = selectBeneficiary( ...
        mode, candidates, relayId, label, localPosteriorBySensor, ...
        currentDirectedEdgeMask)
backboneMask = logical(currentDirectedEdgeMask(relayId, candidates));
if strcmp(mode, 'backbone-first')
    preferred = candidates(backboneMask);
    if isempty(preferred)
        preferred = candidates;
    end
    receiverId = min(preferred);
else
    existences = -inf(1, numel(candidates));
    for candidateIdx = 1:numel(candidates)
        object = findLabelObject( ...
            localPosteriorBySensor{candidates(candidateIdx)}, label);
        if ~isempty(object) && isfinite(object.r)
            existences(candidateIdx) = object.r;
        end
    end
    rows = [-reshape(existences, [], 1), ...
        -reshape(double(backboneMask), [], 1), ...
        reshape(candidates, [], 1)];
    [~, order] = sortrows(rows, [1, 2, 3]);
    receiverId = candidates(order(1));
end
object = findLabelObject(localPosteriorBySensor{receiverId}, label);
if isempty(object)
    existence = NaN;
else
    existence = object.r;
end
backboneAligned = logical(currentDirectedEdgeMask(relayId, receiverId));
end

function object = predictPacketObject(object, model, age)
for stepIdx = 1:age
    object.r = model.survivalProbability * object.r;
    for componentIdx = 1:object.numberOfGmComponents
        object.mu{componentIdx} = ...
            model.A * object.mu{componentIdx} + model.u;
        object.Sigma{componentIdx} = ...
            model.A * object.Sigma{componentIdx} * model.A' + model.R;
    end
end
if object.numberOfGmComponents < 1 || ...
        object.r <= getField(model, 'existenceThreshold', 0)
    object = [];
end
end

function object = findLabelObject(objects, label)
object = [];
objects = reshape(objects, 1, []);
for objectIdx = 1:numel(objects)
    candidate = objects(objectIdx);
    if candidate.numberOfGmComponents > 0 && ...
            candidate.birthTime == label(1) && ...
            candidate.birthLocation == label(2)
        object = candidate;
        return;
    end
end
end

function validateInputs(localPosteriorBySensor, physicalAdjacency, ...
        directedLinkDelivered, currentDirectedEdgeMask, model, ...
        currentTime, packetCache, config)
sensorCount = numel(localPosteriorBySensor);
valid = iscell(localPosteriorBySensor) && sensorCount >= 1 && ...
    isequal(size(physicalAdjacency), [sensorCount, sensorCount]) && ...
    isequal(size(directedLinkDelivered), [sensorCount, sensorCount]) && ...
    isequal(size(currentDirectedEdgeMask), [sensorCount, sensorCount]) && ...
    isstruct(model) && isscalar(model) && ...
    isfield(model, 'dynamicTopologyScenario') && ...
    isfield(model.dynamicTopologyScenario, 'config') && ...
    isfield(model.dynamicTopologyScenario.config, 'sensorGroupIds') && ...
    numel(model.dynamicTopologyScenario.config.sensorGroupIds) == ...
        sensorCount && ...
    isscalar(currentTime) && isfinite(currentTime) && ...
    currentTime == round(currentTime) && currentTime >= 1 && ...
    (isempty(packetCache) || (isstruct(packetCache) && ...
        isscalar(packetCache))) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, ...
        'topologyPolicySourcePreservingLabelPacketMaximumAge') && ...
    isfield(config, ...
        'topologyPolicySourcePreservingLabelPacketMetadataScalars');
if ~valid
    error('SourcePreservingLabelPacketV268:InvalidInputs', ...
        'The source-preserving label packet inputs are malformed.');
end
end

function validateSchedule(schedule, sensorCount)
required = {'contractVersion', 'selectedLocalizationLabel', ...
    'selectedLocalizationFormationId', ...
    'labelShortcutSourceSensorId', 'labelShortcutReceiverSensorId', ...
    'labelShortcutSourceWeight'};
sourceId = getField(schedule, 'labelShortcutSourceSensorId', 0);
receiverId = getField(schedule, 'labelShortcutReceiverSensorId', 0);
label = reshape(getField(schedule, ...
    'selectedLocalizationLabel', zeros(2, 0)), [], 1);
weight = getField(schedule, 'labelShortcutSourceWeight', 0);
grid = reshape(getField(schedule, ...
    'labelShortcutSourceWeightGrid', weight), 1, []);
valid = all(isfield(schedule, required)) && ...
    ismember(schedule.contractVersion, { ...
        'source-preserving-label-packet-v268-schedule-v1', ...
        'existence-margin-beneficiary-v269-schedule-v1'}) && ...
    validSensorId(sourceId, sensorCount) && ...
    validSensorId(receiverId, sensorCount) && sourceId ~= receiverId && ...
    numel(label) == 2 && all(isfinite(label)) && ...
    all(label == round(label)) && all(label >= 1) && ...
    isscalar(weight) && isfinite(weight) && weight > 0 && weight < 1 && ...
    ~isempty(grid) && all(isfinite(grid)) && ...
    all(grid > 0) && all(grid < 1) && max(grid) <= weight + 1e-12;
if ~valid
    error('SourcePreservingLabelPacketV268:InvalidSchedule', ...
        'The V268 source-preserving label packet schedule is malformed.');
end
end

function route = emptyRoute()
route = struct( ...
    'active', false, 'currentTime', 0, 'targetFormationId', 0, ...
    'receiverIds', zeros(1, 0), 'sourceId', 0, ...
    'transportSenderId', 0, 'sourceTimestamp', 0, 'packetAge', 0, ...
    'label', zeros(2, 1), 'sourceObject', [], ...
    'sourceWeight', 0, 'sourceWeightGrid', zeros(1, 0), ...
    'weightMode', '', 'forceAppendPreservedSource', false, ...
    'etaProjectionEnabled', false, ...
    'minimumMapExistence', 0.50, ...
    'maximumReferenceLogOddsDrop', 0, ...
    'maximumSubMapReferenceLogOddsDrop', 0, ...
    'maximumReferenceLogOddsIncrease', Inf, ...
    'transferFractionGrid', 1, 'etaIdentityTolerance', 1e-8);
end

function packet = emptyPacket()
packet = struct([]);
end

function active = isActivePacket(packet)
active = isstruct(packet) && isscalar(packet) && ...
    isfield(packet, 'active') && logical(packet.active);
end

function details = emptyDetails(sensorCount)
details = struct( ...
    'contractVersion', ...
        'source-preserving-label-packet-page-v268-v1', ...
    'currentTime', 0, 'scheduled', false, ...
    'sourceId', 0, 'receiverId', 0, 'label', zeros(2, 0), ...
    'sourceWeight', 0, 'sourceWeightGrid', zeros(1, 0), ...
    'weightMode', '', 'transportDelivered', false, ...
    'firstHopScheduled', false, 'firstHopSourceId', 0, ...
    'firstHopReceiverId', 0, 'firstHopLabel', zeros(2, 0), ...
    'firstHopTargetFormationId', 0, ...
    'firstHopPhysicalPassed', false, ...
    'firstHopPayloadPresent', false, 'firstHopDelivered', false, ...
    'firstHopPacketStored', false, 'firstHopRejectionReason', '', ...
    'secondHopScheduled', false, 'secondHopOriginalSourceId', 0, ...
    'secondHopSenderId', 0, 'secondHopReceiverId', 0, ...
    'secondHopSourceTime', 0, 'secondHopAge', NaN, ...
    'secondHopLabel', zeros(2, 0), ...
    'secondHopTargetFormationId', 0, ...
    'secondHopPhysicalPassed', false, ...
    'secondHopPayloadPresent', false, ...
    'secondHopBackboneAligned', false, ...
    'secondHopBeneficiaryMode', '', ...
    'secondHopReceiverExistence', NaN, ...
    'secondHopDelivered', false, 'secondHopRouteActive', false, ...
    'secondHopExpired', false, 'secondHopRejectionReason', '', ...
    'packetCacheActiveAfterPage', false, ...
    'attemptedPayloadScalarsByEdge', zeros(sensorCount), ...
    'attemptedPayloadBytesByEdge', zeros(sensorCount), ...
    'deliveredPayloadScalarsByEdge', zeros(sensorCount), ...
    'deliveredPayloadBytesByEdge', zeros(sensorCount), ...
    'attemptedPayloadScalars', 0, 'attemptedPayloadBytes', 0, ...
    'deliveredPayloadScalars', 0, 'deliveredPayloadBytes', 0, ...
    'etaProjectionEnabled', true, ...
    'etaProjectionByReceiver', {cell(1, sensorCount)}, ...
    'etaProjectionEvaluatedReceiverIds', zeros(1, 0), ...
    'etaProjectionAllowedReceiverIds', zeros(1, 0), ...
    'etaProjectionRejectedReceiverIds', zeros(1, 0), ...
    'routeAttachedReceiverIds', zeros(1, 0), ...
    'appliedReceiverIds', zeros(1, 0), ...
    'truthUsed', false, 'futureInformationUsed', false, ...
    'centralizedControlSynopsisCostIncluded', false);
end

function hop = emptyFirstHop(sensorCount)
hop = struct( ...
    'scheduled', false, 'sourceId', 0, 'receiverId', 0, ...
    'label', zeros(2, 0), 'targetFormationId', 0, ...
    'sourceWeight', 0, 'sourceWeightGrid', zeros(1, 0), ...
    'weightMode', '', 'physicalPassed', false, ...
    'payloadPresent', false, 'delivered', false, ...
    'packetStored', false, 'rejectionReason', '', ...
    'attemptedPayloadScalarsByEdge', zeros(sensorCount), ...
    'attemptedPayloadBytesByEdge', zeros(sensorCount), ...
    'deliveredPayloadScalarsByEdge', zeros(sensorCount), ...
    'deliveredPayloadBytesByEdge', zeros(sensorCount));
end

function hop = emptySecondHop(sensorCount)
hop = struct( ...
    'scheduled', false, 'originalSourceId', 0, ...
    'senderId', 0, 'receiverId', 0, 'sourceTime', 0, ...
    'age', NaN, 'label', zeros(2, 0), 'targetFormationId', 0, ...
    'sourceWeight', 0, 'sourceWeightGrid', zeros(1, 0), ...
    'weightMode', '', 'physicalPassed', false, ...
    'payloadPresent', false, 'backboneAligned', false, ...
    'beneficiaryMode', '', 'receiverExistence', NaN, ...
    'delivered', false, 'routeActive', false, 'expired', false, ...
    'rejectionReason', '', ...
    'attemptedPayloadScalarsByEdge', zeros(sensorCount), ...
    'attemptedPayloadBytesByEdge', zeros(sensorCount), ...
    'deliveredPayloadScalarsByEdge', zeros(sensorCount), ...
    'deliveredPayloadBytesByEdge', zeros(sensorCount));
end

function valid = validSensorId(value, sensorCount)
valid = isscalar(value) && isnumeric(value) && isfinite(value) && ...
    value == round(value) && value >= 1 && value <= sensorCount;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
