function [posteriorBySensor, nextCreditState, details] = ...
        selectBudgetRecycledFormationRepairV188( ...
            posteriorBySensor, localPosteriorBySensor, ...
            physicalAdjacency, directedLinkDelivered, sensorGroupIds, ...
            model, currentTime, previousCreditState, ...
            referencePageBytes, basePageBytes, options)
% SELECTBUDGETRECYCLEDFORMATIONREPAIRV188 Execute one causal repair page.

if nargin < 11 || isempty(options)
    options = struct();
end
sensorCount = numel(posteriorBySensor);
idealDeliveryTeacherMode = logical(getField( ...
    options, 'idealDeliveryTeacherMode', false));
maximumActions = getField(options, 'maximumActions', 1);
forcedFormationId = getField(options, 'forcedFormationId', 0);
forcedSourceId = getField(options, 'forcedSourceId', 0);
forcedLabel = getField(options, 'forcedLabel', zeros(2, 1));
targetFormationId = getField(options, 'targetFormationId', 0);
updateMode = getField(options, 'updateMode', 'hard-replacement');
sourceWeight = getField(options, 'sourceWeight', 1);
protocol = getBudgetRecycledFormationRepairV188Protocol();
if ~ischar(updateMode)
    error('BudgetRecycledFormationRepairV188:InvalidUpdateMode', ...
        'The repair update mode must be a character vector.');
end
updateMode = lower(strrep(updateMode, '_', '-'));
if ~iscell(posteriorBySensor) || ...
        ~iscell(localPosteriorBySensor) || ...
        numel(localPosteriorBySensor) ~= sensorCount || ...
        ~isequal(size(physicalAdjacency), [sensorCount, sensorCount]) || ...
        ~isequal(size(directedLinkDelivered), ...
            [sensorCount, sensorCount]) || ...
        ~isscalar(referencePageBytes) || ...
        ~isfinite(referencePageBytes) || referencePageBytes < 0 || ...
        ~isscalar(basePageBytes) || ~isfinite(basePageBytes) || ...
        basePageBytes < 0 || ...
        ~isscalar(maximumActions) || ~isfinite(maximumActions) || ...
        maximumActions < 0 || maximumActions ~= round(maximumActions) || ...
        maximumActions > protocol.maximumRepairFormationsPerPage || ...
        (maximumActions > ...
            protocol.maximumDeployableRepairFormationsPerPage && ...
            ~idealDeliveryTeacherMode) || ...
        ~isscalar(forcedFormationId) || ...
        ~isfinite(forcedFormationId) || forcedFormationId < 0 || ...
        forcedFormationId ~= round(forcedFormationId) || ...
        ~isscalar(targetFormationId) || ...
        ~isfinite(targetFormationId) || targetFormationId < 0 || ...
        targetFormationId ~= round(targetFormationId) || ...
        targetFormationId > max(reshape(sensorGroupIds, 1, [])) || ...
        (forcedFormationId > 0 && ~idealDeliveryTeacherMode) || ...
        ~isscalar(forcedSourceId) || ~isfinite(forcedSourceId) || ...
        forcedSourceId < 0 || forcedSourceId ~= round(forcedSourceId) || ...
        forcedSourceId > sensorCount || ...
        ~isnumeric(forcedLabel) || ...
        ~isequal(size(forcedLabel), [2, 1]) || ...
        any(~isfinite(forcedLabel)) || ...
        any(forcedLabel ~= round(forcedLabel)) || ...
        ((forcedSourceId == 0) ~= all(forcedLabel == 0)) || ...
        (forcedSourceId > 0 && ...
            (~idealDeliveryTeacherMode || forcedFormationId == 0 || ...
             any(forcedLabel < 1))) || ...
        ~ismember(updateMode, { ...
            'hard-replacement', 'label-kla', 'causal-label-kla'}) || ...
        ~isscalar(sourceWeight) || ~isnumeric(sourceWeight) || ...
        ~isfinite(sourceWeight) || sourceWeight <= 0 || ...
        sourceWeight > 1 || ...
        (strcmp(updateMode, 'hard-replacement') && ...
            abs(sourceWeight - 1) > 1e-12) || ...
        (strcmp(updateMode, 'label-kla') && ...
            (~idealDeliveryTeacherMode || sourceWeight >= 1)) || ...
        (strcmp(updateMode, 'causal-label-kla') && ...
            (idealDeliveryTeacherMode || sourceWeight >= 1))
    error('BudgetRecycledFormationRepairV188:InvalidPageInput', ...
        'The recursive V188 page inputs are malformed.');
end
physicalAdjacency = logical(physicalAdjacency);
directedLinkDelivered = logical(directedLinkDelivered);
availableSourceAdjacency = physicalAdjacency;
if ~idealDeliveryTeacherMode
    % Proposal matrices use receiver rows and source columns, while the
    % delivery matrix uses sender rows and receiver columns.
    availableSourceAdjacency = physicalAdjacency & ...
        directedLinkDelivered';
end

synopsisSensorIds = 1:sensorCount;
if targetFormationId > 0
    groupIds = reshape(sensorGroupIds, 1, []);
    targetReceivers = find(groupIds == targetFormationId);
    commonSources = find(all( ...
        availableSourceAdjacency(targetReceivers, :), 1));
    synopsisSensorIds = unique( ...
        [reshape(targetReceivers, 1, []), ...
         reshape(commonSources, 1, [])], 'stable');
end

cache = buildFormationRepairLightSynopsisCacheV188( ...
    posteriorBySensor, localPosteriorBySensor, model, currentTime, ...
    struct('participatingSensorIds', synopsisSensorIds));
admissionNetSavingBytes = max( ...
    referencePageBytes - basePageBytes, 0);
[creditAfterSynopsis, synopsisDecision] = ...
    preflightBudgetRecycledRepairSynopsisV188( ...
        previousCreditState, admissionNetSavingBytes, ...
        cache.totalAttemptedBytes, referencePageBytes);
proposals = repmat(emptyProposalContract(), 1, 0);
proposalDetails = struct();
if synopsisDecision.lightSynopsisAuthorized
    if forcedSourceId > 0
        receiverPresenceThreshold = cache.activeExistenceThreshold;
        if strcmp(updateMode, 'hard-replacement')
            % Support-restoration actions are defined precisely when the
            % selected label is absent at one or more receivers.  Residual
            % KLA keeps the active-support requirement because zero support
            % cannot be resurrected by geometric fusion.
            receiverPresenceThreshold = 0;
        end
        forcedCandidateOptions = struct( ...
            'receiverPresenceThreshold', ...
                receiverPresenceThreshold);
        [candidateBank, bankDetails] = ...
            enumerateFormationCommonLabelRepairCandidatesV190( ...
                cache, availableSourceAdjacency, ...
                sensorGroupIds, forcedCandidateOptions);
        matches = arrayfun(@(candidate) ...
            candidate.formationId == forcedFormationId && ...
            candidate.sourceId == forcedSourceId && ...
            isequal(candidate.label, forcedLabel), candidateBank);
        matchedIndices = find(matches);
        payloadDetails = struct();
        if numel(matchedIndices) == 1
            [proposal, payloadDetails] = ...
                resolveFormationRepairCandidatePayloadV190( ...
                    candidateBank(matchedIndices), ...
                    localPosteriorBySensor, ...
                    availableSourceAdjacency, model, struct());
            if proposal.safetyPassed
                proposals = proposal;
            end
        end
        proposalDetails = struct( ...
            'contractVersion', ...
                'forced-formation-repair-candidate-v190-teacher-v1', ...
            'candidateCount', bankDetails.candidateCount, ...
            'candidateCountByFormation', ...
                bankDetails.candidateCountByFormation, ...
            'forcedFormationId', forcedFormationId, ...
            'forcedSourceId', forcedSourceId, ...
            'forcedLabel', forcedLabel, ...
            'receiverPresenceThreshold', ...
                forcedCandidateOptions.receiverPresenceThreshold, ...
            'matchedCandidateCount', numel(matchedIndices), ...
            'payloadDetails', payloadDetails, ...
            'truthUsed', false, ...
            'futureInformationUsed', false, ...
            'teacherOnly', true);
    else
        [proposals, proposalDetails] = ...
            buildFormationCommonLabelRepairProposalsV188( ...
                cache, localPosteriorBySensor, ...
                availableSourceAdjacency, sensorGroupIds, model, struct());
    end
end
projectionProposals = proposals;
if forcedFormationId > 0
    for proposalIdx = 1:numel(projectionProposals)
        if projectionProposals(proposalIdx).formationId ~= ...
                forcedFormationId
            projectionProposals(proposalIdx).safetyPassed = false;
        end
    end
end
if targetFormationId > 0
    for proposalIdx = 1:numel(projectionProposals)
        if projectionProposals(proposalIdx).formationId ~= ...
                targetFormationId
            projectionProposals(proposalIdx).safetyPassed = false;
        end
    end
end
projection = projectBudgetRecycledRepairActionsV188( ...
    projectionProposals, creditAfterSynopsis, ...
    struct('maximumActions', maximumActions));

selectedIndices = projection.selectedProposalIndices;
transportDelivered = false(1, numel(selectedIndices));
appliedIndices = zeros(1, 0);
for selectedPosition = 1:numel(selectedIndices)
    proposalIdx = selectedIndices(selectedPosition);
    proposal = proposals(proposalIdx);
    delivered = idealDeliveryTeacherMode;
    if ~idealDeliveryTeacherMode
        coordinatorIdx = proposal.receiverIds(1);
        requestDelivered = ...
            directedLinkDelivered(coordinatorIdx, proposal.sourceId);
        responseDelivered = all(directedLinkDelivered( ...
            proposal.sourceId, proposal.receiverIds));
        delivered = requestDelivered && responseDelivered;
    end
    transportDelivered(selectedPosition) = delivered;
    if delivered
        appliedIndices(end + 1) = proposalIdx; %#ok<AGROW>
    end
end
if ismember(updateMode, {'label-kla', 'causal-label-kla'})
    [posteriorBySensor, applyDetails] = ...
        applyFormationCommonLabelKlaRepairV190( ...
            posteriorBySensor, proposals, appliedIndices, model, ...
            struct('sourceWeight', sourceWeight));
else
    [posteriorBySensor, applyDetails] = ...
        applyFormationCommonLabelRepairV188( ...
            posteriorBySensor, proposals, appliedIndices);
end
nextCreditState = projection.nextCreditState;

details = struct();
details.contractVersion = ...
    'budget-recycled-formation-repair-page-v188-v1';
details.currentTime = currentTime;
details.referencePageBytes = referencePageBytes;
details.basePageBytes = basePageBytes;
details.admissionNetSavingBytes = ...
    referencePageBytes - basePageBytes;
details.lightSynopsisBytes = cache.totalAttemptedBytes;
details.synopsisDecision = synopsisDecision;
details.proposalDetails = proposalDetails;
details.proposalCount = numel(proposals);
details.proposals = proposals;
details.projection = projection;
details.forcedFormationId = forcedFormationId;
details.fixedFormationIdentifierUsed = forcedFormationId > 0;
details.forcedSourceId = forcedSourceId;
details.forcedLabel = forcedLabel;
details.targetFormationId = targetFormationId;
details.targetFormationScoped = targetFormationId > 0;
details.synopsisSensorIds = synopsisSensorIds;
details.synopsisSensorCount = numel(synopsisSensorIds);
details.fixedSourceLabelIdentifierUsed = forcedSourceId > 0;
details.forcedCandidateTeacherMode = forcedSourceId > 0;
details.updateMode = updateMode;
details.sourceWeight = sourceWeight;
details.labelKlaTeacherMode = strcmp(updateMode, 'label-kla');
details.causalLabelKlaMode = strcmp(updateMode, 'causal-label-kla');
details.selectedProposalIndices = selectedIndices;
details.transportDelivered = transportDelivered;
details.appliedProposalIndices = appliedIndices;
details.applyDetails = applyDetails;
details.chargedAttemptedBytes = ...
    synopsisDecision.chargedSynopsisBytes + ...
    projection.selectedActionBytes;
details.chargedDeliveredBytes = ...
    synopsisDecision.chargedSynopsisBytes;
for selectedPosition = 1:numel(selectedIndices)
    if transportDelivered(selectedPosition)
        details.chargedDeliveredBytes = ...
            details.chargedDeliveredBytes + ...
            proposals(selectedIndices(selectedPosition)).attemptedBytes;
    end
end
details.certifiedNetSavingBytes = ...
    referencePageBytes - basePageBytes - ...
    details.chargedAttemptedBytes;
details.idealDeliveryTeacherMode = idealDeliveryTeacherMode;
details.truthUsed = false;
details.futureInformationUsed = false;
details.numericLabelIdentifiersUsedAsFeatures = false;
details.numericLabelIdentifiersUsedForTeacherSelection = ...
    forcedSourceId > 0;
details.recursiveStateMutationApplied = ~isempty(appliedIndices);
details.evidenceBoundary = [ ...
    'The page selector uses current local/fused posteriors, current ', ...
    'physical/delivery state and causal communication credit only. ', ...
    'Ideal delivery, when enabled, is a recursive teacher pilot and ', ...
    'not deployable-method evidence.'];
end

function proposal = emptyProposalContract()
proposal = struct( ...
    'formationId', 0, 'receiverIds', zeros(1, 0), ...
    'sourceId', 0, 'label', zeros(2, 1), 'sourceObject', [], ...
    'richSynopsisBytes', 0, 'requestBytes', 0, ...
    'completeResponseBytesPerReceiver', 0, 'responseBytes', 0, ...
    'attemptedBytes', 0, 'estimatedUtilityLowerBound', 0, ...
    'rankingOpportunity', 0, 'minimumRiskReduction', 0, ...
    'minimumReceiverExistence', 0, 'peerConsensus', 0, ...
    'receiverCompatibility', 1, 'commonSourcePassed', false, ...
    'safetyPassed', false, 'rollingConnectivityPassed', false);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
