function [posterior, applied, pageIdx, details] = ...
        selectShadowStateRollbackPosterior( ...
            currentPosterior, config, receiverIdx, currentTime, ...
            localPosterior, independentAnchorPosterior, model)
% SELECTSHADOWSTATEROLLBACKPOSTERIOR Apply a registered node-time rollback.

if nargin < 5
    localPosterior = [];
end
if nargin < 6
    independentAnchorPosterior = [];
end
if nargin < 7
    model = struct();
end

posterior = currentPosterior;
applied = false;
pageIdx = 0;
details = struct( ...
    'selectedLabelCount', 0, ...
    'selectedLabels', zeros(2, 0), ...
    'selectedTombstone', false(1, 0), ...
    'estimatedPayloadBytes', 0);
if ~config.shadowStateRollbackEnabled
    return;
end
pageIdx = find(config.shadowStateRollbackTimes == currentTime, 1);
if isempty(pageIdx) || ...
        ~ismember(receiverIdx, ...
            config.shadowStateRollbackSensorIdsByTime{pageIdx})
    pageIdx = 0;
    return;
end
sourceMode = 'external-fused-posterior';
if isfield(config, 'shadowStateRollbackSourceMode')
    sourceMode = lower(strrep(char( ...
        config.shadowStateRollbackSourceMode), '_', '-'));
end
if strcmp(sourceMode, 'current-local-posterior')
    if nargin < 5 || isempty(localPosterior)
        error('StateRollback:MissingLocalPosterior', ...
            'The current local posterior was not supplied.');
    end
    posterior = localPosterior;
elseif ismember(sourceMode, { ...
        'independent-local-anchor', 'light-network-anchor'})
    if nargin < 6 || isempty(independentAnchorPosterior)
        error('StateRollback:MissingAuxiliaryAnchor', ...
            'The requested auxiliary anchor posterior was not supplied.');
    end
    posterior = independentAnchorPosterior;
elseif ismember(sourceMode, { ...
        'external-fused-posterior', ...
        'external-sparse-reference-labels', ...
        'external-positive-value-reference-labels'})
    page = config.shadowStateRollbackFusedPosteriorByTime{pageIdx};
    if ~iscell(page) || numel(page) < receiverIdx
        error('ShadowStateRollbackV126:MissingShadowPosterior', ...
            'The requested node-time shadow posterior is unavailable.');
    end
    referencePosterior = page{receiverIdx};
    if strcmp(sourceMode, 'external-sparse-reference-labels')
        maximumLabelEdits = config. ...
            shadowStateRollbackMaximumLabelEdits;
        existenceThreshold = 1e-2;
        if isfield(config, 'shadowStateRollbackExistenceThreshold')
            existenceThreshold = config. ...
                shadowStateRollbackExistenceThreshold;
        end
        [posterior, details] = mergeSparseReferenceLmbLabels( ...
            currentPosterior, referencePosterior, ...
            maximumLabelEdits, existenceThreshold);
    elseif strcmp(sourceMode, ...
            'external-positive-value-reference-labels')
        [posterior, details] = ...
            selectPositiveValueReferenceLmbLabels( ...
                currentPosterior, referencePosterior, ...
                config.shadowStateRollbackMaximumLabelEdits, ...
                config.shadowStateRollbackExistenceThreshold, ...
                model, currentTime);
    else
        posterior = referencePosterior;
    end
else
    error('StateRollback:UnsupportedSourceMode', ...
        'The rollback source mode is not registered.');
end
applied = true;
end
