"""Freeze new-seed validation, preserving all earlier generated runners."""
from pathlib import Path
import hashlib
import json

out=Path(__file__).resolve().parent
root=out.parents[1]
v1=(out/'runRobotReunionPilot.m').read_text()
inputs=v1[v1.index('function [model,truth,truthRegions,measurements,uniforms,visibility]=makeInputs'):v1.index('function run=runArm(')]
v3=(out/'runRobotReunionConfirmation.m').read_text()
helpers=v3[v3.index('function run=runArm('):].replace('fuseConfirmedReunionInputs(', 'fuseValidationInputs(')
entry='''function runRobotReunionValidation(firstSeed,lastSeed)
% Generated by make_validation_runner.py. Frozen, all-arm paired validation.
if nargin<1, firstSeed=2901; end
if nargin<2, lastSeed=2920; end
assert(firstSeed>=2901 && lastSeed<=2920 && firstSeed<=lastSeed);
out=fileparts(mfilename('fullpath')); root=fileparts(fileparts(out));
addpath(fullfile(root,'common'),fullfile(root,'lmb'),fullfile(root,'multisensorLmb'), ...
    fullfile(root,'trials','icra_group_tracking'));
names={'split_latebirth','churn_departure','split_no_new'};
arms={'local','fov','lineage','mil','mil_support','recent','lineage_recent','qualified_exist','confirmed_exist'};
for seed=firstSeed:lastSeed
    for sc=1:numel(names)
        scene=buildRobotReunionScene(names{sc});
        rng(seed+200000,'twister'); offset=1.2*(rand(2,scene.N)-.5);
        for n=1:scene.N
            scene.trajectories{n}(1:2,:)=scene.trajectories{n}(1:2,:)+offset(:,n);
            scene.positions(:,n,:)=scene.positions(:,n,:)+reshape(offset(:,n),2,1,1);
        end
        scene.validationOffsets=offset;
        topo=buildGroupPilotTopologies(scene);
        scene.componentCount=topo.componentCount; scene.reconnectionFrames=topo.reconnectionFrames;
        adjacency=topo.adjacency(:,:,:,2);
        assert(all(squeeze(sum(sum(adjacency,1),2))'==2*(scene.N-scene.componentCount)));
        [model,truth,truthRegions,measurements,uniforms,visibility]=makeInputs(scene,seed);
        [model.birthParameters.positiveConfirmation]=deal(false); model.object=model.birthParameters([]);
        cells=cell(1,numel(arms));
        for a=1:numel(arms)
            fprintf('START validation %s seed %d arm %s\\n',names{sc},seed,arms{a});
            cells{a}=runArm(model,truth,measurements,uniforms,scene,adjacency,arms{a},scene.T);
            r=cells{a};
            if a>2
                assert(r.totalWireBytes==cells{2}.totalWireBytes);
                assert(isequal(r.deliveredMessages,cells{2}.deliveredMessages));
            end
            fprintf('DONE OSPA %.6f count %.6f runtime %.2fs\\n', ...
                mean(r.ospa,'all'),mean(r.countError,'all'),r.runtimeSeconds);
        end
        result=struct('protocol','robot-reunion-fusion-v4','scene',scene.name, ...
            'seed',seed,'mode','validation','time',scene.time, ...
            'componentCount',scene.componentCount,'reconnectionFrames',scene.reconnectionFrames, ...
            'truth',{truth},'truthRegions',{truthRegions},'visibility',visibility, ...
            'positions',scene.positions,'validationOffsets',offset,'runs',[cells{:}]);
        prefix=fullfile(out,'results',sprintf('%s_seed%d_validation',scene.name,seed));
        writeJson([prefix,'.json'],result); gzip([prefix,'.json']);
        save([prefix,'.mat'],'result','model','scene','truth','truthRegions', ...
            'measurements','uniforms','adjacency','-v7');
    end
end
fprintf('COMPLETED validation seeds %d--%d\\n',firstSeed,lastSeed);
end

'''
(out/'runRobotReunionValidation.m').write_text(entry+inputs+helpers)
files=[out/'VALIDATION_PROTOCOL.md',out/'fuseValidationInputs.m',out/'runRobotReunionValidation.m',out/'make_validation_runner.py']
files += [out/f for f in ['fuseRobotReunionInputs.m','fuseQualifiedReunionInputs.m','fuseConfirmedReunionInputs.m','buildRobotReunionScene.m']]
files += list((root/'multisensorLmb').glob('*.m')) + list((root/'lmb').glob('*.m')) + list((root/'common').glob('*.m'))
manifest={str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
(out/'validation_source_sha256.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Generated validation runner and froze',len(manifest),'source hashes.')
