"""Derive a cache-only ablation entry point without editing frozen v1 code."""
from pathlib import Path
import hashlib
import json

out = Path(__file__).resolve().parent
root = out.parents[1]
original = (out/'runRobotReunionPilot.m').read_text()
helpers = original[original.index('function run=runArm('):]
needle = "if strcmp(arm,'mil'), cfg.lmbFusionRule='mil-common-label'; end"
assert helpers.count(needle)==1
helpers = helpers.replace(needle, needle + "\n"
    "cfg.missingLabelFusionMode='fov-aware-censored';\n"
    "cfg.untouchedPriorExclusionEnabled=true;")
assert helpers.count('fuseRobotReunionInputs(')==1
helpers = helpers.replace('fuseRobotReunionInputs(', 'fuseQualifiedReunionInputs(')
entry = '''function runRobotReunionExtension()
% Generated by make_extension_runner.py; all stochastic inputs are reused.
out=fileparts(mfilename('fullpath')); root=fileparts(fileparts(out));
addpath(fullfile(root,'common'),fullfile(root,'lmb'),fullfile(root,'multisensorLmb'));
names={'split_latebirth','churn_departure','split_no_new'};
arms={'lineage_recent','qualified_exist'};
for sc=1:numel(names)
    for seed=[2801,2802,2803]
        sourceMat=fullfile(out,'results',sprintf('%s_seed%d_full.mat',names{sc},seed));
        cached=load(sourceMat); cells=cell(1,numel(arms));
        for a=1:numel(arms)
            fprintf('START extension %s seed %d arm %s\\n',names{sc},seed,arms{a});
            cells{a}=runArm(cached.model,cached.truth,cached.measurements,cached.uniforms, ...
                cached.scene,cached.adjacency,arms{a},cached.scene.T);
            r=cells{a};
            assert(r.totalWireBytes==cached.result.runs(2).totalWireBytes);
            assert(isequal(r.deliveredMessages,cached.result.runs(2).deliveredMessages));
            fprintf('DONE OSPA %.6f count %.6f runtime %.2fs\\n', ...
                mean(r.ospa,'all'),mean(r.countError,'all'),r.runtimeSeconds);
        end
        result=cached.result; result.runs=[cells{:}]; result.mode='extension';
        result.protocol='robot-reunion-fusion-v2';
        prefix=fullfile(out,'results',sprintf('%s_seed%d_extension',names{sc},seed));
        writeJson([prefix,'.json'],result); gzip([prefix,'.json']);
        save([prefix,'.mat'],'result','sourceMat','-v7');
    end
end
fprintf('COMPLETED extension\\n');
end

'''
(out/'runRobotReunionExtension.m').write_text(entry+helpers)
files=[out/'EXTENSION_PROTOCOL.md',out/'fuseQualifiedReunionInputs.m',
       out/'runRobotReunionExtension.m',out/'make_extension_runner.py']
files += list((out/'results').glob('*_full.mat'))
manifest={str(f.relative_to(root)): hashlib.sha256(f.read_bytes()).hexdigest() for f in files}
(out/'extension_source_sha256.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Generated cache-only extension and froze',len(manifest),'source/input hashes.')
