function anchor = ...
    assertFormationB4V46DevelopmentPermitActivationFileAnchored()
% ASSERTFORMATIONB4V46DEVELOPMENTPERMITACTIVATIONFILEANCHORED Regular Git blob.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
assertFormationB4V46DevelopmentCriticalFunctionPaths();
relativePath = ...
    'contracts/formation_b4_v46_development_arm_permits.json';
absolutePath = fullfile(repoRoot, ...
    strrep(relativePath, '/', filesep));
[regularStatus, ~] = builtin('system', sprintf( ...
    'test -f %s && test ! -L %s', ...
    shellQuote(absolutePath), shellQuote(absolutePath)));
if regularStatus ~= 0
    error('FormationB4V46DevelopmentPermit:ActivationFileTypeDrift', ...
        'The permit activation must be a regular non-symlink file.');
end
[indexStatus, indexText] = builtin('system', sprintf( ...
    '/usr/bin/git --no-replace-objects -C %s ls-files -s -- %s', ...
    shellQuote(repoRoot), shellQuote(relativePath)));
parts = regexp(strtrim(indexText), ...
    '^([0-9]+) ([0-9a-f]+) [0-9]+\t(.+)$', 'tokens', 'once');
if indexStatus ~= 0 || isempty(parts) || ...
        ~strcmp(parts{1}, '100644') || ...
        ~strcmp(parts{3}, relativePath)
    error('FormationB4V46DevelopmentPermit:ActivationFileTypeDrift', ...
        'The permit activation is not one tracked regular Git blob.');
end
[worktreeStatus, worktreeBlobText] = builtin('system', sprintf( ...
    ['/usr/bin/git --no-replace-objects -C %s ', ...
     'hash-object --no-filters -- %s'], ...
    shellQuote(repoRoot), shellQuote(relativePath)));
worktreeBlobId = strtrim(worktreeBlobText);
if worktreeStatus ~= 0 || ~strcmp(worktreeBlobId, parts{2})
    error('FormationB4V46DevelopmentPermit:ActivationBlobDrift', ...
        'The permit activation bytes differ from the staged Git blob.');
end
anchor = struct();
anchor.contractVersion = ...
    'formation-b4-v46-development-activation-file-anchor-v1';
anchor.relativePath = relativePath;
anchor.fileMode = parts{1};
anchor.gitBlobId = parts{2};
anchor.regularFileVerified = true;
anchor.symlinkRejected = true;
anchor.worktreeMatchesIndexBlob = true;
end

function value = shellQuote(value)
value = ['''', strrep(value, '''', '''"''"'''), ''''];
end
