function assertRollingSafeCausalOptionPairedFirstActions( ...
    persistentPreflight, oneStepPreflight)
% ASSERTROLLINGSAFECAUSALOPTIONPAIREDFIRSTACTIONS Exact paired first action.

requiredFields = { ...
    'optionSequences', 'firstActionGraphSha256', ...
    'firstActionFusionWeightSha256'};
if ~isstruct(persistentPreflight) || ~isstruct(oneStepPreflight) || ...
        ~all(isfield(persistentPreflight, requiredFields)) || ...
        ~all(isfield(oneStepPreflight, requiredFields)) || ...
        ~iscell(persistentPreflight.firstActionGraphSha256) || ...
        ~iscell(oneStepPreflight.firstActionGraphSha256) || ...
        ~iscell(persistentPreflight.firstActionFusionWeightSha256) || ...
        ~iscell(oneStepPreflight.firstActionFusionWeightSha256) || ...
        numel(persistentPreflight.firstActionGraphSha256) ~= ...
            size(persistentPreflight.optionSequences, 1) || ...
        numel(oneStepPreflight.firstActionGraphSha256) ~= ...
            size(oneStepPreflight.optionSequences, 1) || ...
        numel(persistentPreflight.firstActionFusionWeightSha256) ~= ...
            size(persistentPreflight.optionSequences, 1) || ...
        numel(oneStepPreflight.firstActionFusionWeightSha256) ~= ...
            size(oneStepPreflight.optionSequences, 1) || ...
        ~allValidOrEmptySha256( ...
            persistentPreflight.firstActionGraphSha256) || ...
        ~allValidOrEmptySha256( ...
            oneStepPreflight.firstActionGraphSha256) || ...
        ~allValidOrEmptySha256( ...
            persistentPreflight.firstActionFusionWeightSha256) || ...
        ~allValidOrEmptySha256( ...
            oneStepPreflight.firstActionFusionWeightSha256) || ...
        ~isequal( ...
        persistentPreflight.optionSequences(:, 1), ...
        oneStepPreflight.optionSequences(:, 1)) || ...
        ~isequal( ...
            persistentPreflight.firstActionGraphSha256, ...
            oneStepPreflight.firstActionGraphSha256) || ...
        ~isequal( ...
            persistentPreflight.firstActionFusionWeightSha256, ...
            oneStepPreflight.firstActionFusionWeightSha256)
    error('RollingSafeCausalOption:PairedFirstActionMismatch', ...
        ['Persistent and one-step arms do not share exact first-action ', ...
         'graphs and fusion weights.']);
end
end

function valid = allValidOrEmptySha256(values)
valid = true;
for valueIdx = 1:numel(values)
    value = values{valueIdx};
    if isempty(value)
        continue;
    end
    if ~ischar(value) || ...
            isempty(regexp(value, '^[0-9a-f]{64}$', 'once'))
        valid = false;
        return;
    end
end
end
