function assertDynamicTopologyRestartTraceEqual(reference, observed)
% ASSERTDYNAMICTOPOLOGYRESTARTTRACEEQUAL Exact restart replay contract.

fields = { ...
    'contractVersion', ...
    'times', ...
    'estimateSha256', ...
    'selectedTopologySha256', ...
    'fusionWeightSha256', ...
    'attemptedPayloadSha256', ...
    'deliveredPayloadSha256', ...
    'localUpdateSha256', ...
    'messageCountSha256', ...
    'overallSha256'};
for fieldIdx = 1:numel(fields)
    fieldName = fields{fieldIdx};
    if ~isstruct(reference) || ~isstruct(observed) || ...
            ~isfield(reference, fieldName) || ...
            ~isfield(observed, fieldName) || ...
            ~isequal(reference.(fieldName), observed.(fieldName))
        error('RollingSafeCausalOption:RestartMismatch', ...
            'Restart equivalence failed for %s.', fieldName);
    end
end
end
