function resolution = ...
    assertFormationBackboneBundleM24CriticalFunctionPaths()
% ASSERTFORMATIONBACKBONEBUNDLEM24CRITICALFUNCTIONPATHS Reject shadowing.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
functionNames = { ...
    'discoverFormationBackboneBundleM24SourceInputFingerprints', ...
    'runFormationBackboneBundleM24SourcePosteriorPreflight', ...
    'assertFormationBackboneBundleM24CriticalFunctionPaths', ...
    'getFormationBackboneBundleM24DevelopmentProtocol', ...
    'getFormationBackboneBundleM24SourceCasePermit', ...
    'loadFormationBackboneBundleM24SourceCasePermit', ...
    'buildFormationBackboneBundleM24SourceExecutionContext', ...
    'applyFormationBackboneBundleM24SourceOutputBoundary', ...
    'buildFormationBackboneBundleM24SourceCache', ...
    'buildFormationBackboneBundleM24ExecutableSourceManifest', ...
    'validateFormationBackboneBundleM24ExecutableGitState', ...
    'stripDynamicTopologyTargetTruthForSource', ...
    'generateDynamicTopologyScenarioInputs', ...
    'prepareFormationBackboneBundleM24SourceCaseInputs', ...
    'computeFormationBackboneBundleM24SourceInputFingerprint', ...
    'buildFormationBackboneBundleM24SourceTriggerConfig', ...
    'selectFormationBackboneReferenceRuntimePolicy', ...
    'buildObservableTopologyPolicyContext', ...
    'selectFormationBackboneResidualTourPolicy', ...
    'buildRegisteredFormationBackboneResidualTour', ...
    'selectRegisteredDirectedRoutingPolicy', ...
    'buildBackbonePreservingResidualRoute', ...
    'assertDynamicTopologyTrackingOutcomeAuthorized', ...
    'validateFormationBackboneBundleM24SourceExecution', ...
    'runEventTriggeredDistributedLmbFilter', ...
    'computeCanonicalValueSha256'};
relativePaths = { ...
    'RUN/GA/discoverFormationBackboneBundleM24SourceInputFingerprints.m', ...
    'RUN/GA/runFormationBackboneBundleM24SourcePosteriorPreflight.m', ...
    'common/assertFormationBackboneBundleM24CriticalFunctionPaths.m', ...
    'common/getFormationBackboneBundleM24DevelopmentProtocol.m', ...
    'common/getFormationBackboneBundleM24SourceCasePermit.m', ...
    'common/loadFormationBackboneBundleM24SourceCasePermit.m', ...
    'common/buildFormationBackboneBundleM24SourceExecutionContext.m', ...
    'common/applyFormationBackboneBundleM24SourceOutputBoundary.m', ...
    'common/buildFormationBackboneBundleM24SourceCache.m', ...
    'common/buildFormationBackboneBundleM24ExecutableSourceManifest.m', ...
    'common/validateFormationBackboneBundleM24ExecutableGitState.m', ...
    'common/stripDynamicTopologyTargetTruthForSource.m', ...
    'common/generateDynamicTopologyScenarioInputs.m', ...
    'common/prepareFormationBackboneBundleM24SourceCaseInputs.m', ...
    'common/computeFormationBackboneBundleM24SourceInputFingerprint.m', ...
    'common/buildFormationBackboneBundleM24SourceTriggerConfig.m', ...
    'common/selectFormationBackboneReferenceRuntimePolicy.m', ...
    'common/buildObservableTopologyPolicyContext.m', ...
    'common/selectFormationBackboneResidualTourPolicy.m', ...
    'common/buildRegisteredFormationBackboneResidualTour.m', ...
    'common/selectRegisteredDirectedRoutingPolicy.m', ...
    'common/buildBackbonePreservingResidualRoute.m', ...
    'common/assertDynamicTopologyTrackingOutcomeAuthorized.m', ...
    'common/validateFormationBackboneBundleM24SourceExecution.m', ...
    'multisensorLmb/runEventTriggeredDistributedLmbFilter.m', ...
    'common/computeCanonicalValueSha256.m'};
resolvedPaths = cell(size(functionNames));
for functionIdx = 1:numel(functionNames)
    resolvedPaths{functionIdx} = which(functionNames{functionIdx});
    expectedPath = fullfile(repoRoot, ...
        strrep(relativePaths{functionIdx}, '/', filesep));
    if isempty(resolvedPaths{functionIdx}) || ...
            ~strcmp(resolvedPaths{functionIdx}, expectedPath)
        error('FormationBundleSourcePermit:FunctionPathShadowed', ...
            'Critical function %s does not resolve inside this repo.', ...
            functionNames{functionIdx});
    end
end
resolution = struct();
resolution.contractVersion = ...
    'formation-backbone-bundle-m24-critical-path-resolution-v1';
resolution.functionNames = functionNames;
resolution.relativePaths = relativePaths;
resolution.resolvedPaths = resolvedPaths;
resolution.canonicalSha256 = computeCanonicalValueSha256(struct( ...
    'contractVersion', resolution.contractVersion, ...
    'functionNames', {resolution.functionNames}, ...
    'relativePaths', {resolution.relativePaths}));
end
