function assertRollingSafeReferenceSwitchActionRealized( ...
        details, actionCode)
% ASSERTROLLINGSAFEREFERENCESWITCHACTIONREALIZED Reject silent fallback.
%
% Codes 82:87 request a specific diverse alternative.  Their underlying
% selector deliberately returns the base graph when the requested
% alternative is unavailable.  A reference-switch arm must therefore
% fail closed unless the requested alternative was feasible and changed
% the action.  Other registered action families already enforce their own
% exact-action semantics and require no additional check here.

if ~isscalar(actionCode) || ~isfinite(actionCode) || ...
        actionCode ~= round(actionCode)
    error('RollingSafeReferenceSwitch:InvalidActionCode', ...
        'The requested action code must be a finite integer.');
end
if actionCode < 82 || actionCode > 87
    return;
end
requiredFields = { ...
    'diverseObservableAlternativeRequested', ...
    'diverseObservableAlternativeFeasible', ...
    'diverseObservableChangedAction'};
if ~isstruct(details) || ~all(isfield(details, requiredFields))
    error('RollingSafeReferenceSwitch:RequestedActionUnavailable', ...
        'Diverse action code %d lacks realization diagnostics.', ...
        actionCode);
end
if actionCode <= 84
    expectedAlternativeIndex = actionCode - 81;
else
    expectedAlternativeIndex = actionCode - 84;
end
requestedIndex = details.diverseObservableAlternativeRequested;
alternativeFeasible = requireFiniteBinaryDiagnostic( ...
    details.diverseObservableAlternativeFeasible, 1, ...
    'diverseObservableAlternativeFeasible');
changedAction = requireFiniteBinaryDiagnostic( ...
    details.diverseObservableChangedAction, 1, ...
    'diverseObservableChangedAction');
if ~isscalar(requestedIndex) || ~isfinite(requestedIndex) || ...
        requestedIndex ~= expectedAlternativeIndex || ...
        ~logical(alternativeFeasible) || ~logical(changedAction)
    error('RollingSafeReferenceSwitch:RequestedActionUnavailable', ...
        ['Diverse action code %d silently fell back instead of ', ...
         'realizing alternative %d.'], ...
        actionCode, expectedAlternativeIndex);
end
end
