function authorization = ...
    assertDynamicTopologyTrackingOutcomeAuthorized( ...
        model, executionContext, runtimeRequest)
% ASSERTDYNAMICTOPOLOGYTRACKINGOUTCOMEAUTHORIZED Enforce scene outcome gate.
%
% Geometry-calibration scenes may generate truth, measurements and graph
% diagnostics, but they must not reach the tracking filter until a new named
% scene contract explicitly authorizes outcomes.  A separately registered
% case permit may authorize source-posterior filtering without authorizing
% any tracking score.  Legacy models without a protected trace retain their
% historical behavior.

if nargin < 2 || isempty(executionContext)
    executionContext = struct();
end
if nargin < 3 || isempty(runtimeRequest)
    runtimeRequest = struct();
end
if ~isstruct(executionContext) || ~isscalar(executionContext)
    error('FormationBundleSourcePermit:ExecutionContextDrift', ...
        'The dynamic-topology execution context is malformed.');
end
if ~isempty(fieldnames(executionContext))
    if isFormationB4V46DevelopmentExecutionContext(executionContext)
        assertFormationB4V46DevelopmentCriticalFunctionPaths();
        authorization = ...
            validateFormationB4V46DevelopmentArmExecution( ...
                model, executionContext, runtimeRequest);
        return;
    end
    if isFormationB4V49PairedTrackingDevelopmentContext(executionContext)
        authorization = validateFormationB4V49DevelopmentExecution( ...
            model, executionContext, runtimeRequest);
        return;
    end
    if isFormationB4V50PairedTrackingDevelopmentContext(executionContext)
        authorization = validateFormationB4V50DevelopmentExecution( ...
            model, executionContext, runtimeRequest);
        return;
    end
    if isFormationB4V51PairedTrackingDevelopmentContext(executionContext)
        authorization = validateFormationB4V51DevelopmentExecution( ...
            model, executionContext, runtimeRequest);
        return;
    end
    if isFormationB4V52PairedTrackingDevelopmentContext(executionContext)
        authorization = validateFormationB4V52DevelopmentExecution( ...
            model, executionContext, runtimeRequest);
        return;
    end
    assertFormationBackboneBundleM24CriticalFunctionPaths();
    if (isfield(executionContext, 'action') && ...
            strcmp(executionContext.action, ...
                'filter-paired-tracking')) || ...
            (isfield(executionContext, 'capability') && ...
             strcmp(executionContext.capability, 'paired-tracking'))
        error('FormationBundleSourcePermit:PairedTrackingSealed', ...
            'The M24 paired-tracking capability remains sealed.');
    end
    authorization = ...
        validateFormationBackboneBundleM24SourceExecution( ...
            model, executionContext, runtimeRequest);
    return;
end

if isFormationB4V46SealedTrace(model, runtimeRequest)
    error('FormationB4V46TrackingPermit:ExecutionSealed', [ ...
        'A registered V46 source or sanitized runtime model cannot ', ...
        'enter the tracking filter until an exact phase-specific V46 ', ...
        'filter-execution permit is supplied and validated.']);
end

authorization = buildLegacyAuthorization();

if ~isstruct(model) || ~isscalar(model)
    return;
end

hasScenario = isfield(model, 'dynamicTopologyScenario');
hasGateEnvelope = isfield(model, ...
    'dynamicTopologyTrackingOutcomeGate');
hasExplicitDynamicTrace = ...
    isfield(model, 'explicitSensorTrajectories') || ...
    isfield(model, 'sensorTrajectories') || ...
    isfield(model, 'explicitTargetTrajectories');
hasRegisteredFormationRuntimeTrace = ...
    detectRegisteredFormationRuntimeTrace(model, runtimeRequest);
if ~hasScenario && ~hasGateEnvelope
    if hasExplicitDynamicTrace || hasRegisteredFormationRuntimeTrace
        error('DynamicTopology:IncompleteScenarioMetadata', [ ...
            'A model with explicit dynamic trajectories cannot be ', ...
            'treated as legacy after its scenario and gate metadata ', ...
            'have been removed.']);
    end
    return;
end

% A surviving model-level envelope means that deleting the nested scenario
% cannot bypass the gate.  Conversely, malformed scenario metadata is not a
% valid legacy model and therefore fails closed.
if ~hasScenario || ...
        ~isstruct(model.dynamicTopologyScenario) || ...
        ~isscalar(model.dynamicTopologyScenario) || ...
        ~isfield(model.dynamicTopologyScenario, 'config') || ...
        ~isstruct(model.dynamicTopologyScenario.config) || ...
        ~isscalar(model.dynamicTopologyScenario.config)
    rejectTrackingOutcome(struct());
end

config = model.dynamicTopologyScenario.config;
protectedTraceFields = { ...
    'sceneGeometryVersion', 'sceneCalibrationStatus', ...
    'formalValidationAuthorized', 'trackingOutcomeAuthorized', ...
    'sceneContractSha256', 'sceneStyle', ...
    'scaleControlReferencePreset'};
hasProtectedTrace = hasGateEnvelope || ...
    any(isfield(config, protectedTraceFields));
if ~hasProtectedTrace
    if isKnownMultistyleCalibrationPreset(config)
        rejectTrackingOutcome(config);
    end
    % Historical dynamic-topology models predate the multistyle outcome
    % contract.  Their behavior remains unchanged.
    return;
end

prefix = 'formation-fov-multistyle-';
isVersionedMultistyle = ...
    isfield(config, 'sceneGeometryVersion') && ...
    ischar(config.sceneGeometryVersion) && ...
    strncmp(config.sceneGeometryVersion, prefix, numel(prefix));
declaresGate = isfield(config, 'trackingOutcomeAuthorized');

validGateEnvelope = false;
if hasGateEnvelope
    envelope = model.dynamicTopologyTrackingOutcomeGate;
    validGateEnvelope = isstruct(envelope) && isscalar(envelope) && ...
        isfield(envelope, 'contractVersion') && ...
        ischar(envelope.contractVersion) && ...
        strcmp(envelope.contractVersion, ...
            'dynamic-topology-tracking-outcome-gate-v1') && ...
        isfield(envelope, 'required') && ...
        isequal(envelope.required, true) && ...
        isfield(envelope, 'sceneContractSha256') && ...
        ischar(envelope.sceneContractSha256) && ...
        isfield(config, 'sceneContractSha256') && ...
        ischar(config.sceneContractSha256) && ...
        strcmp(envelope.sceneContractSha256, ...
            config.sceneContractSha256);
end

registeredContract = false;
if isVersionedMultistyle && declaresGate && validGateEnvelope
    try
        registeredContract = strcmp( ...
            config.sceneContractSha256, ...
            computeFormationFovMultistyleSceneContractSha256( ...
                config)) && ...
            strcmp(config.sceneContractSha256, ...
                getExpectedFormationFovMultistyleSceneContractSha256( ...
                    config));
    catch
        registeredContract = false;
    end
end
authorized = declaresGate && registeredContract && ...
    isequal(config.trackingOutcomeAuthorized, true);
if ~authorized
    rejectTrackingOutcome(config);
end
authorization.mode = 'registered-scene-outcome';
authorization.capability = 'tracking-outcome-authorized';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = true;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
end

function detected = ...
    isFormationB4V46DevelopmentExecutionContext(executionContext)
detected = isstruct(executionContext) && isscalar(executionContext) && ...
    isfield(executionContext, 'contractVersion') && ...
    ischar(executionContext.contractVersion) && ...
    strcmp(executionContext.contractVersion, ...
        'formation-b4-v46-development-arm-execution-context-v1');
end

function detected = isFormationB4V46SealedTrace(model, runtimeRequest)
detected = false;
if ~isstruct(model) || ~isscalar(model)
    return;
end
if isfield(model, 'formationB4V46RuntimeSourceEnvelope')
    detected = true;
    return;
end
if detectRegisteredFormationRuntimeTrace(model, runtimeRequest)
    detected = true;
    return;
end
if ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isstruct(model.dynamicTopologyScenario) || ...
        ~isscalar(model.dynamicTopologyScenario) || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~ischar(model.dynamicTopologyScenario.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        ~isa(model.dynamicTopologyScenario.seed, 'double') || ...
        ~isscalar(model.dynamicTopologyScenario.seed) || ...
        ~isfinite(model.dynamicTopologyScenario.seed)
    return;
end
registry = getFormationB4V46TrackingSourceRegistry();
detected = any(strcmp({registry.cases.presetName}, ...
        model.dynamicTopologyScenario.presetName) & ...
    [registry.cases.seed] == model.dynamicTopologyScenario.seed);
end

function detected = ...
    detectRegisteredFormationRuntimeTrace(model, runtimeRequest)
detected = false;
if ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~isnumeric(model.numberOfSensors) || ...
        ~isreal(model.numberOfSensors) || ...
        ~isscalar(model.numberOfSensors) || ...
        ~isfinite(model.numberOfSensors) || ...
        ~any(double(model.numberOfSensors) == [24, 36])
    return;
end
sensorCount = double(model.numberOfSensors);
scenarioTrace = isfield(model, 'dynamicTopologyScenario');
embeddedTrajectoryTrace = ...
    isfield(model, 'explicitSensorTrajectories') || ...
    isfield(model, 'sensorTrajectories') || ...
    isfield(model, 'explicitTargetTrajectories');
motionTrace = isfield(model, 'sensorMotionEnabled') && ...
    isequal(model.sensorMotionEnabled, true);
birthScheduleTrace = isfield(model, 'birthTimeByLocation');
runtimeTrajectoryTrace = isstruct(runtimeRequest) && ...
    isscalar(runtimeRequest) && ...
    isfield(runtimeRequest, 'sensorTrajectoryTimeCounts') && ...
    isnumeric(runtimeRequest.sensorTrajectoryTimeCounts) && ...
    numel(runtimeRequest.sensorTrajectoryTimeCounts) == ...
        sensorCount && ...
    any(runtimeRequest.sensorTrajectoryTimeCounts > 0);
detected = scenarioTrace || embeddedTrajectoryTrace || motionTrace || ...
    birthScheduleTrace || runtimeTrajectoryTrace;
end

function known = isKnownMultistyleCalibrationPreset(config)
known = false;
if ~isstruct(config) || ~isscalar(config) || ...
        ~isfield(config, 'presetName') || ...
        ~ischar(config.presetName)
    return;
end
knownPresets = { ...
    'm24-formation-fov-convoy', ...
    'm24-formation-fov-crossing', ...
    'm24-formation-fov-relay', ...
    'x36-formation-fov-convoy', ...
    'x36-formation-fov-crossing', ...
    'x36-formation-fov-relay'};
known = any(strcmp(config.presetName, knownPresets));
end

function authorization = buildLegacyAuthorization()
authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = 'legacy-compatible';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = 'legacy-filter-execution';
authorization.action = 'filter-execution';
authorization.protocolId = '';
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = '';
authorization.seed = NaN;
authorization.sourceWindow = zeros(1, 0);
authorization.armId = '';
authorization.armOrdinal = NaN;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = false;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = false;
end

function rejectTrackingOutcome(config)
presetName = '<unknown>';
if isstruct(config) && isscalar(config) && ...
        isfield(config, 'presetName') && ischar(config.presetName)
    presetName = config.presetName;
end
error('DynamicTopology:TrackingOutcomeNotAuthorized', [ ...
    'Scenario %s is calibration-only or has incomplete outcome-gate ', ...
    'metadata and may not enter the tracking filter. Freeze a new named ', ...
    'scene contract with explicit tracking outcome authorization first.'], ...
    presetName);
end

function authorization = validateFormationB4V49DevelopmentExecution( ...
        model, context, request)
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'presetName', ...
    'seed', 'armId', 'developmentEvidenceOnly'};
if ~isequal(sort(fieldnames(context)), sort(expectedFields(:))) || ...
        ~strcmp(context.capability, 'paired-tracking-development') || ...
        ~strcmp(context.action, 'filter-paired-tracking-development') || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('FormationB4V49Tracking:InvalidContext', ...
        'The V49 paired-tracking development context is malformed.');
end

protocol = getFormationB4V49RuntimeProtocol();
if ~any(strcmp(context.armId, protocol.primaryArms)) || ...
        ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~any(model.numberOfSensors == [24, 36]) || ...
        ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isstruct(model.dynamicTopologyScenario) || ...
        ~isscalar(model.dynamicTopologyScenario) || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~strcmp(model.dynamicTopologyScenario.presetName, ...
            context.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        model.dynamicTopologyScenario.seed ~= context.seed || ...
        isfield(model, 'explicitTargetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'targetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'target')
    error('FormationB4V49Tracking:InvalidRuntimeModel', ...
        'The V49 development model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isequal(sort(fieldnames(request)), ...
            sort(requiredRequestFields(:))) || ...
        ~strcmp(request.operation, 'filter-execution') || ...
        request.measurementTimeCount < 1 || ...
        numel(request.sensorTrajectoryTimeCounts) ~= ...
            model.numberOfSensors || ...
        any(request.sensorTrajectoryTimeCounts ~= ...
            request.measurementTimeCount) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isfield(request.triggerConfig, 'topologyPolicyName')
    error('FormationB4V49Tracking:InvalidRuntimeRequest', ...
        'The V49 development runtime dimensions are inconsistent.');
end
if strcmp(context.armId, protocol.referenceArmId)
    expectedPolicy = 'selectFormationB4V46SynchronizedRuntimePolicy';
else
    expectedPolicy = 'selectFormationB4V49SynchronizedRuntimePolicy';
end
if ~strcmp(request.triggerConfig.topologyPolicyName, expectedPolicy)
    error('FormationB4V49Tracking:WrongArmPolicy', ...
        'The requested tracking arm does not match its topology policy.');
end

authorization = buildLegacyAuthorization();
authorization.mode = 'formation-b4-v49-paired-tracking-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.armId = context.armId;
authorization.armOrdinal = find(strcmp( ...
    context.armId, protocol.primaryArms), 1);
authorization.sourceWindow = [1, request.measurementTimeCount];
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = true;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function authorization = validateFormationB4V50DevelopmentExecution( ...
        model, context, request)
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'presetName', ...
    'seed', 'armId', 'developmentEvidenceOnly'};
if ~isequal(sort(fieldnames(context)), sort(expectedFields(:))) || ...
        ~strcmp(context.capability, ...
            'paired-tracking-development-v50') || ...
        ~strcmp(context.action, ...
            'filter-paired-tracking-development-v50') || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('FormationB4V50Tracking:InvalidContext', ...
        'The V50 paired-tracking context is malformed.');
end

protocol = getFormationB4V50RuntimeProtocol();
if ~any(strcmp(context.armId, protocol.primaryArms)) || ...
        ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~any(model.numberOfSensors == [24, 36]) || ...
        ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~strcmp(model.dynamicTopologyScenario.presetName, ...
            context.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        model.dynamicTopologyScenario.seed ~= context.seed || ...
        isfield(model, 'explicitTargetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'targetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'target')
    error('FormationB4V50Tracking:InvalidRuntimeModel', ...
        'The V50 model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isequal(sort(fieldnames(request)), ...
            sort(requiredRequestFields(:))) || ...
        ~strcmp(request.operation, 'filter-execution') || ...
        request.measurementTimeCount < 1 || ...
        numel(request.sensorTrajectoryTimeCounts) ~= ...
            model.numberOfSensors || ...
        any(request.sensorTrajectoryTimeCounts ~= ...
            request.measurementTimeCount) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isfield(request.triggerConfig, 'topologyPolicyName')
    error('FormationB4V50Tracking:InvalidRuntimeRequest', ...
        'The V50 runtime dimensions are inconsistent.');
end
if strcmp(context.armId, protocol.referenceArmId)
    expectedPolicy = 'selectFormationB4V46SynchronizedRuntimePolicy';
else
    expectedPolicy = 'selectFormationB4V50SynchronizedRuntimePolicy';
end
if ~strcmp(request.triggerConfig.topologyPolicyName, expectedPolicy)
    error('FormationB4V50Tracking:WrongArmPolicy', ...
        'The V50 requested arm does not match its topology policy.');
end

authorization = buildLegacyAuthorization();
authorization.mode = ...
    'formation-b4-v50-paired-tracking-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.armId = context.armId;
authorization.armOrdinal = find(strcmp( ...
    context.armId, protocol.primaryArms), 1);
authorization.sourceWindow = [1, request.measurementTimeCount];
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = true;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function authorization = validateFormationB4V51DevelopmentExecution( ...
        model, context, request)
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'presetName', ...
    'seed', 'armId', 'developmentEvidenceOnly'};
if ~isequal(sort(fieldnames(context)), sort(expectedFields(:))) || ...
        ~strcmp(context.capability, ...
            'paired-tracking-development-v51') || ...
        ~strcmp(context.action, ...
            'filter-paired-tracking-development-v51') || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('FormationB4V51Tracking:InvalidContext', ...
        'The V51 paired-tracking context is malformed.');
end

protocol = getFormationB4V51RuntimeProtocol();
if ~any(strcmp(context.armId, protocol.primaryArms)) || ...
        ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~any(model.numberOfSensors == [24, 36]) || ...
        ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~strcmp(model.dynamicTopologyScenario.presetName, ...
            context.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        model.dynamicTopologyScenario.seed ~= context.seed || ...
        isfield(model, 'explicitTargetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'targetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'target')
    error('FormationB4V51Tracking:InvalidRuntimeModel', ...
        'The V51 model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isequal(sort(fieldnames(request)), ...
            sort(requiredRequestFields(:))) || ...
        ~strcmp(request.operation, 'filter-execution') || ...
        request.measurementTimeCount < 1 || ...
        numel(request.sensorTrajectoryTimeCounts) ~= ...
            model.numberOfSensors || ...
        any(request.sensorTrajectoryTimeCounts ~= ...
            request.measurementTimeCount) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isfield(request.triggerConfig, 'topologyPolicyName') || ...
        ~isfield(request.triggerConfig, 'topologyPolicyHistoryDepth') || ...
        request.triggerConfig.topologyPolicyHistoryDepth < ...
            protocol.pulseHistoryDepth
    error('FormationB4V51Tracking:InvalidRuntimeRequest', ...
        'The V51 runtime dimensions or history depth are inconsistent.');
end
if strcmp(context.armId, protocol.referenceArmId)
    expectedPolicy = 'selectFormationB4V46SynchronizedRuntimePolicy';
else
    expectedPolicy = 'selectFormationB4V51SynchronizedRuntimePolicy';
end
if ~strcmp(request.triggerConfig.topologyPolicyName, expectedPolicy)
    error('FormationB4V51Tracking:WrongArmPolicy', ...
        'The V51 requested arm does not match its topology policy.');
end

authorization = buildLegacyAuthorization();
authorization.mode = ...
    'formation-b4-v51-paired-tracking-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.armId = context.armId;
authorization.armOrdinal = find(strcmp( ...
    context.armId, protocol.primaryArms), 1);
authorization.sourceWindow = [1, request.measurementTimeCount];
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = true;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function authorization = validateFormationB4V52DevelopmentExecution( ...
        model, context, request)
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'presetName', ...
    'seed', 'armId', 'developmentEvidenceOnly'};
if ~isequal(sort(fieldnames(context)), sort(expectedFields(:))) || ...
        ~strcmp(context.capability, ...
            'paired-tracking-development-v52') || ...
        ~strcmp(context.action, ...
            'filter-paired-tracking-development-v52') || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('FormationB4V52Tracking:InvalidContext', ...
        'The V52 paired-tracking context is malformed.');
end

protocol = getFormationB4V52RuntimeProtocol();
if ~any(strcmp(context.armId, protocol.primaryArms)) || ...
        ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~any(model.numberOfSensors == [24, 36]) || ...
        ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~strcmp(model.dynamicTopologyScenario.presetName, ...
            context.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        model.dynamicTopologyScenario.seed ~= context.seed || ...
        isfield(model, 'explicitTargetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'targetTrajectories') || ...
        isfield(model.dynamicTopologyScenario, 'target')
    error('FormationB4V52Tracking:InvalidRuntimeModel', ...
        'The V52 model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isequal(sort(fieldnames(request)), ...
            sort(requiredRequestFields(:))) || ...
        ~strcmp(request.operation, 'filter-execution') || ...
        request.measurementTimeCount < 1 || ...
        numel(request.sensorTrajectoryTimeCounts) ~= ...
            model.numberOfSensors || ...
        any(request.sensorTrajectoryTimeCounts ~= ...
            request.measurementTimeCount) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isfield(request.triggerConfig, 'topologyPolicyName') || ...
        ~isfield(request.triggerConfig, 'topologyPolicyHistoryDepth') || ...
        request.triggerConfig.topologyPolicyHistoryDepth < ...
            protocol.pulseHistoryDepth
    error('FormationB4V52Tracking:InvalidRuntimeRequest', ...
        'The V52 runtime dimensions or history depth are inconsistent.');
end
if strcmp(context.armId, protocol.referenceArmId)
    expectedPolicy = 'selectFormationB4V46SynchronizedRuntimePolicy';
else
    expectedPolicy = 'selectFormationB4V52SynchronizedRuntimePolicy';
end
if ~strcmp(request.triggerConfig.topologyPolicyName, expectedPolicy)
    error('FormationB4V52Tracking:WrongArmPolicy', ...
        'The V52 requested arm does not match its topology policy.');
end

authorization = buildLegacyAuthorization();
authorization.mode = ...
    'formation-b4-v52-paired-tracking-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.armId = context.armId;
authorization.armOrdinal = find(strcmp( ...
    context.armId, protocol.primaryArms), 1);
authorization.sourceWindow = [1, request.measurementTimeCount];
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = true;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
