function model = attachCurrentObservableSensorGeometry( ...
        model, positions, currentTime, sensorCount)
% ATTACHCURRENTOBSERVABLESENSORGEOMETRY Add only the current sensor pose.

if ~isstruct(model) || ~isscalar(model) || ...
        ~isa(positions, 'double') || ~isreal(positions) || ...
        ~isequal(size(positions), [2, sensorCount]) || ...
        any(~isfinite(positions(:))) || ...
        ~isa(currentTime, 'double') || ~isscalar(currentTime) || ...
        ~isfinite(currentTime) || currentTime < 1 || ...
        currentTime ~= round(currentTime)
    error('ObservableTopologyContext:InvalidCurrentSensorPose', ...
        'The current sensor pose request is malformed.');
end

headings = nan(1, sensorCount);
if isfield(model, 'sensorFovHeadingRad') && ...
        isa(model.sensorFovHeadingRad, 'double') && ...
        isreal(model.sensorFovHeadingRad) && ...
        size(model.sensorFovHeadingRad, 1) >= sensorCount && ...
        size(model.sensorFovHeadingRad, 2) >= currentTime
    headings = reshape( ...
        model.sensorFovHeadingRad(1:sensorCount, currentTime), 1, []);
end
missingHeading = ~isfinite(headings);
if any(missingHeading)
    headings(missingHeading) = 0;
    if isfield(model, 'sensorTrajectories') && ...
            iscell(model.sensorTrajectories) && ...
            numel(model.sensorTrajectories) >= sensorCount
        for sensorIdx = find(missingHeading)
            trajectory = model.sensorTrajectories{sensorIdx};
            if isa(trajectory, 'double') && isreal(trajectory) && ...
                    size(trajectory, 1) >= 4 && ...
                    size(trajectory, 2) >= currentTime
                velocity = trajectory(3:4, currentTime);
                if all(isfinite(velocity)) && norm(velocity) > 1e-9
                    headings(sensorIdx) = ...
                        atan2(velocity(2), velocity(1));
                end
            end
        end
    end
end

model.currentSensorPosition = positions;
model.currentSensorFovHeadingRad = headings;
end
