function audit = auditRollingSafeReferenceSwitchAttestation( ...
        attestation, expectedActionCode)
% AUDITROLLINGSAFEREFERENCESWITCHATTESTATION Recompute arm status from raw evidence.

protocol = getLabelSetSimulatorPolicyProtocol();
requiredFields = { ...
    'contractVersion', 'actionCode', 'actionSequenceCode', ...
    'actionSequenceRelativeTime', 'messageCount', 'adjacency', ...
    'physicalAdjacency', 'fusionWeightMatrix', 'sourceWeight', ...
    'selectedSourcesByReceiver', ...
    'nominalProjectionFeasible', 'repairProjectionAttempted', ...
    'repairTriggered', 'payloadEmergencyUsed', ...
    'payloadLimitPassed', 'topologyInfeasible', ...
    'sensorWindowStrongConnected', ...
    'formationWindowStrongConnected', ...
    'successorSensorStrongConnected', ...
    'successorFormationStrongConnected', ...
    'oneStepTopologyReserveChecked', ...
    'oneStepTopologyReservePassed', ...
    'truthUsed', 'actionSequenceTruthUsed', ...
    'diverseObservableAlternativeRequested', ...
    'diverseObservableAlternativeFeasible', ...
    'diverseObservableChangedAction', ...
    'diverseObservableBannedReceiver', ...
    'diverseObservableBannedSender', ...
    'diverseObservableDefaultSelectedSources'};
if ~isstruct(attestation) || ~isscalar(attestation) || ...
        ~all(isfield(attestation, requiredFields)) || ...
        ~strcmp(attestation.contractVersion, ...
            'rolling-safe-reference-switch-raw-attestation-v1')
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation is missing or version-incompatible.');
end
if ~isscalar(expectedActionCode) || ~isfinite(expectedActionCode) || ...
        expectedActionCode ~= round(expectedActionCode) || ...
        attestation.actionCode ~= expectedActionCode || ...
        attestation.actionSequenceCode ~= expectedActionCode || ...
        attestation.actionSequenceRelativeTime ~= 1
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation has a changed action identity.');
end

adjacency = requireBinarySquareMatrix( ...
    attestation.adjacency, 'adjacency');
nodeCount = size(adjacency, 1);
physicalAdjacency = requireBinarySquareMatrix( ...
    attestation.physicalAdjacency, 'physicalAdjacency');
if ~isequal(size(physicalAdjacency), size(adjacency)) || ...
        nodeCount ~= protocol.rollingSafeCausalOptionMessageBudget || ...
        ~isscalar(attestation.messageCount) || ...
        ~isfinite(attestation.messageCount) || ...
        attestation.messageCount ~= round(attestation.messageCount) || ...
        attestation.messageCount ~= nodeCount || ...
        any(diag(adjacency)) || any(sum(adjacency, 2) ~= 1) || ...
        nnz(adjacency) ~= nodeCount || ...
        any(adjacency(:) & ~physicalAdjacency(:))
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation violates its route or budget contract.');
end

binaryFields = { ...
    'nominalProjectionFeasible', 'repairProjectionAttempted', ...
    'repairTriggered', 'payloadEmergencyUsed', ...
    'payloadLimitPassed', 'topologyInfeasible', ...
    'sensorWindowStrongConnected', ...
    'formationWindowStrongConnected', ...
    'successorSensorStrongConnected', ...
    'successorFormationStrongConnected', ...
    'oneStepTopologyReserveChecked', ...
    'oneStepTopologyReservePassed', ...
    'truthUsed', 'actionSequenceTruthUsed'};
flags = struct();
for fieldIdx = 1:numel(binaryFields)
    fieldName = binaryFields{fieldIdx};
    flags.(fieldName) = requireFiniteBinaryDiagnostic( ...
        attestation.(fieldName), 1, fieldName);
end
if flags.truthUsed || flags.actionSequenceTruthUsed
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation reports privileged truth use.');
end

registeredSourceWeight = ...
    protocol.rollingSafeCausalOptionSourceWeight;
selectedSources = reshape( ...
    attestation.selectedSourcesByReceiver, [], 1);
sourceWeight = attestation.sourceWeight;
weights = attestation.fusionWeightMatrix;
if ~isscalar(sourceWeight) || ~isfinite(sourceWeight) || ...
        sourceWeight ~= registeredSourceWeight || ...
        numel(selectedSources) ~= nodeCount || ...
        any(~isfinite(selectedSources)) || ...
        any(selectedSources ~= round(selectedSources)) || ...
        any(selectedSources < 1) || any(selectedSources > nodeCount)
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation changed the source-weight contract.');
end
expectedAdjacency = false(nodeCount);
expectedAdjacency(sub2ind([nodeCount, nodeCount], ...
    (1:nodeCount)', selectedSources)) = true;
expectedWeights = eye(nodeCount);
expectedWeights(1:(nodeCount + 1):end) = 1 - registeredSourceWeight;
expectedWeights(sub2ind([nodeCount, nodeCount], ...
    (1:nodeCount)', selectedSources)) = registeredSourceWeight;
if ~isequal(expectedAdjacency, adjacency) || ...
        ~isnumeric(weights) || ~isreal(weights) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(~isfinite(weights(:))) || any(weights(:) < 0) || ...
        ~isequal(weights, expectedWeights)
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative attestation changed its exact route weights.');
end

assertRollingSafeReferenceSwitchActionRealized( ...
    attestation, expectedActionCode);
if expectedActionCode >= 82 && expectedActionCode <= 87
    defaultSources = reshape(attestation. ...
        diverseObservableDefaultSelectedSources, [], 1);
    bannedReceiver = attestation.diverseObservableBannedReceiver;
    bannedSender = attestation.diverseObservableBannedSender;
    if numel(defaultSources) ~= nodeCount || ...
            any(~isfinite(defaultSources)) || ...
            any(defaultSources ~= round(defaultSources)) || ...
            any(defaultSources < 1) || any(defaultSources > nodeCount) || ...
            ~isscalar(bannedReceiver) || ~isfinite(bannedReceiver) || ...
            bannedReceiver ~= round(bannedReceiver) || ...
            bannedReceiver < 1 || bannedReceiver > nodeCount || ...
            ~isscalar(bannedSender) || ~isfinite(bannedSender) || ...
            bannedSender ~= round(bannedSender) || ...
            bannedSender < 1 || bannedSender > nodeCount
        error('RollingSafeReferenceSwitch:InvalidAttestation', ...
            'Diverse raw realization evidence is invalid.');
    end
    defaultAdjacency = false(nodeCount);
    defaultAdjacency(sub2ind([nodeCount, nodeCount], ...
        (1:nodeCount)', defaultSources)) = true;
    if ~defaultAdjacency(bannedReceiver, bannedSender) || ...
            adjacency(bannedReceiver, bannedSender) || ...
            isequal(adjacency, defaultAdjacency)
        error('RollingSafeReferenceSwitch:InvalidAttestation', ...
            ['Diverse raw evidence does not prove that the requested ', ...
             'default edge was banned and the action changed.']);
    end
end
safetyPassed = flags.payloadLimitPassed && ...
    ~flags.topologyInfeasible && ...
    flags.sensorWindowStrongConnected && ...
    flags.formationWindowStrongConnected && ...
    flags.successorSensorStrongConnected && ...
    flags.successorFormationStrongConnected && ...
    flags.oneStepTopologyReserveChecked && ...
    flags.oneStepTopologyReservePassed;
audit = struct();
audit.available = logical(safetyPassed);
audit.requestedActionRealized = true;
audit.strictNominalFree = logical(safetyPassed && ...
    flags.nominalProjectionFeasible && ...
    ~flags.repairProjectionAttempted && ...
    ~flags.repairTriggered && ...
    ~flags.payloadEmergencyUsed);
audit.nodeCount = nodeCount;
audit.adjacency = adjacency;
audit.physicalAdjacency = physicalAdjacency;
audit.fusionWeightMatrix = weights;
end

function value = requireBinarySquareMatrix(value, fieldName)
if ~(isnumeric(value) || islogical(value)) || ~isreal(value) || ...
        ndims(value) ~= 2 || size(value, 1) ~= size(value, 2) || ...
        isempty(value) || any(~isfinite(value(:))) || ...
        any(value(:) ~= 0 & value(:) ~= 1)
    error('RollingSafeReferenceSwitch:InvalidAttestation', ...
        'Raw alternative %s must be a finite binary square matrix.', ...
        fieldName);
end
value = logical(value);
end
