function features = buildDirectGraphWithholdingFeaturesV215( ...
        context, groupIds, referenceAdjacency, formationGraph)
% BUILDDIRECTGRAPHWITHHOLDINGFEATURESV215 Observable action features.
%
% V214 showed that receiver need alone cannot rank withholding actions:
% need is useful for deciding where to repair, while withholding also
% depends on cross-formation conflict, current payload complexity and the
% risk that later full-payload pages rebound.  This extractor keeps those
% signals separate.  It reads only the current posterior, current graph and
% current reference route; truth, future measurements and future outcomes
% are unavailable by construction.

requiredContext = {'localPosteriorBySensor', 'model'};
requiredGraph = { ...
    'contractVersion', 'formationIds', 'formationCount', ...
    'targetCapacity', 'nodeFeatures', 'nodeFeatureNames', ...
    'edgeFeatures', 'edgeFeatureNames', 'truthUsed', ...
    'futureInformationUsed'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, requiredContext)) || ...
        ~iscell(context.localPosteriorBySensor) || ...
        ~isnumeric(groupIds) || ...
        ~isstruct(formationGraph) || ~isscalar(formationGraph) || ...
        ~all(isfield(formationGraph, requiredGraph)) || ...
        formationGraph.truthUsed || ...
        formationGraph.futureInformationUsed
    error('DirectGraphWithholdingV215:InvalidInput', ...
        'V215 requires one current truth-free formation graph.');
end

nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(groupIds, 1, []);
formationIds = unique(groupIds, 'stable');
formationCount = numel(formationIds);
if numel(groupIds) ~= nodeCount || ...
        ~isequal(size(referenceAdjacency), [nodeCount, nodeCount]) || ...
        formationGraph.formationCount ~= formationCount || ...
        ~isequal(reshape(formationGraph.formationIds, 1, []), ...
            formationIds) || ...
        size(formationGraph.nodeFeatures, 1) ~= formationCount || ...
        size(formationGraph.edgeFeatures, 1) ~= formationCount || ...
        size(formationGraph.edgeFeatures, 2) ~= formationCount
    error('DirectGraphWithholdingV215:DimensionDrift', ...
        'The V215 sensor, formation or route dimensions changed.');
end

referenceAdjacency = logical(referenceAdjacency);
referenceAdjacency(1:nodeCount+1:end) = false;
[sensorPayloadBytes, sensorActiveLabels, ...
    sensorComponentsPerLabel] = sensorPayloadFeatures( ...
        context.localPosteriorBySensor, context.model);
networkPayloadBytes = referencePayloadBytes( ...
    referenceAdjacency, sensorPayloadBytes);

edgeNames = { ...
    'mean_link_reliability', ...
    'mean_normalized_sensor_distance', ...
    'mean_positive_existence_gain', ...
    'mean_negative_existence_gap', ...
    'mean_positive_precision_gain', ...
    'mean_negative_precision_gap', ...
    'mean_normalized_state_discrepancy', ...
    'mean_active_label_overlap', ...
    'mean_node_quality_advantage', ...
    'mean_receiver_need'};
edgeIdx = nameIndices(formationGraph.edgeFeatureNames, edgeNames);
incomingEdgeNames = prefixNames(edgeNames, 'incoming_');
incomingEdgeFeatures = zeros(formationCount, numel(edgeNames));

payloadFeatureNames = { ...
    'receiver_log_full_payload_bytes_mean', ...
    'receiver_log_full_payload_bytes_max', ...
    'receiver_components_per_label_mean', ...
    'receiver_components_per_label_max', ...
    'incoming_log_full_payload_bytes_total', ...
    'incoming_log_full_payload_bytes_per_edge', ...
    'incoming_full_payload_fraction_of_reference', ...
    'incoming_reference_cross_edge_fraction', ...
    'incoming_sender_formation_fraction', ...
    'incoming_sender_active_label_fraction_mean', ...
    'incoming_sender_components_per_label_mean'};
payloadFeatures = zeros(formationCount, numel(payloadFeatureNames));
targetCapacity = max(formationGraph.targetCapacity, 1);

for formationIdx = 1:formationCount
    formationId = formationIds(formationIdx);
    receivers = reshape(find(groupIds == formationId), 1, []);
    outside = reshape(find(groupIds ~= formationId), 1, []);
    crossRoute = referenceAdjacency(receivers, outside);
    [localReceiverIdx, localSenderIdx] = find(crossRoute);
    incomingSenders = outside(localSenderIdx);
    incomingEdgeCount = numel(incomingSenders);
    possibleCrossEdgeCount = numel(receivers) * numel(outside);
    incomingBytes = sum(sensorPayloadBytes(incomingSenders));

    senderFormationIds = groupIds(incomingSenders);
    senderFormationCount = numel(unique( ...
        senderFormationIds, 'stable'));
    if incomingEdgeCount > 0
        for senderFormationIdx = 1:formationCount
            senderFormationId = formationIds(senderFormationIdx);
            weight = nnz(senderFormationIds == senderFormationId);
            if weight == 0
                continue;
            end
            edgeValues = reshape(formationGraph.edgeFeatures( ...
                formationIdx, senderFormationIdx, edgeIdx), 1, []);
            incomingEdgeFeatures(formationIdx, :) = ...
                incomingEdgeFeatures(formationIdx, :) + ...
                weight * edgeValues;
        end
        incomingEdgeFeatures(formationIdx, :) = ...
            incomingEdgeFeatures(formationIdx, :) / incomingEdgeCount;
        senderActiveLabelFraction = mean( ...
            sensorActiveLabels(incomingSenders)) / targetCapacity;
        senderComponentsPerLabel = mean( ...
            sensorComponentsPerLabel(incomingSenders));
    else
        senderActiveLabelFraction = 0;
        senderComponentsPerLabel = 0;
    end

    receiverBytes = sensorPayloadBytes(receivers);
    receiverComponents = sensorComponentsPerLabel(receivers);
    payloadFeatures(formationIdx, :) = [ ...
        log1p(mean(receiverBytes)), ...
        log1p(max(receiverBytes)), ...
        mean(receiverComponents), ...
        max(receiverComponents), ...
        log1p(incomingBytes), ...
        log1p(incomingBytes / max(incomingEdgeCount, 1)), ...
        incomingBytes / max(networkPayloadBytes, 1), ...
        incomingEdgeCount / max(possibleCrossEdgeCount, 1), ...
        senderFormationCount / max(formationCount - 1, 1), ...
        senderActiveLabelFraction, ...
        senderComponentsPerLabel];
end

nodeFeatureNames = prefixNames( ...
    formationGraph.nodeFeatureNames, 'receiver_');
formationFeatureNames = [ ...
    nodeFeatureNames, incomingEdgeNames, payloadFeatureNames];
formationFeatures = [ ...
    formationGraph.nodeFeatures, incomingEdgeFeatures, payloadFeatures];
if any(~isfinite(formationFeatures(:)))
    error('DirectGraphWithholdingV215:NonFiniteFeature', ...
        'The V215 observable feature matrix must be finite.');
end

features = struct();
features.contractVersion = ...
    'direct-graph-withholding-feature-schema-v215-v1';
features.formationIds = formationIds;
features.formationFeatureNames = formationFeatureNames;
features.formationFeatures = formationFeatures;
features.nodeFeatureNames = nodeFeatureNames;
features.nodeFeatures = formationGraph.nodeFeatures;
features.incomingEdgeFeatureNames = incomingEdgeNames;
features.incomingEdgeFeatures = incomingEdgeFeatures;
features.payloadFeatureNames = payloadFeatureNames;
features.payloadFeatures = payloadFeatures;
features.referencePayloadBytesProxy = networkPayloadBytes;
features.sensorPayloadBytesProxy = sensorPayloadBytes;
features.sensorActiveLabelCount = sensorActiveLabels;
features.sensorComponentsPerLabel = sensorComponentsPerLabel;
features.numericFormationIdentifiersUsedAsFeatures = false;
features.truthUsed = false;
features.futureMeasurementsUsed = false;
features.futureOutcomesUsed = false;
end

function [bytes, activeLabels, componentsPerLabel] = ...
        sensorPayloadFeatures(posteriors, model)
sensorCount = numel(posteriors);
bytes = zeros(1, sensorCount);
activeLabels = zeros(1, sensorCount);
componentsPerLabel = zeros(1, sensorCount);
for sensorIdx = 1:sensorCount
    stats = estimateLmbPayloadSize( ...
        posteriors{sensorIdx}, model, 2, struct());
    bytes(sensorIdx) = stats.estimatedBytes;
    activeLabels(sensorIdx) = stats.objectCount;
    componentsPerLabel(sensorIdx) = ...
        stats.componentCount / max(stats.objectCount, 1);
end
end

function bytes = referencePayloadBytes(adjacency, sensorBytes)
[~, senderIndices] = find(adjacency);
bytes = sum(sensorBytes(senderIndices));
end

function indices = nameIndices(names, requested)
indices = zeros(1, numel(requested));
for idx = 1:numel(requested)
    match = find(strcmp(names, requested{idx}));
    if numel(match) ~= 1
        error('DirectGraphWithholdingV215:MissingGraphFeature', ...
            'The V208 formation graph feature schema changed.');
    end
    indices(idx) = match;
end
end

function output = prefixNames(names, prefix)
output = cell(size(names));
for idx = 1:numel(names)
    output{idx} = [prefix, names{idx}];
end
end
