function bank = buildReceiverDomainTransportActionBankV71( ...
        context, options)
% BUILDRECEIVERDOMAINTRANSPORTACTIONBANKV71 Reference/candidate H=3 bank.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getReceiverDomainTransportH3V72Protocol();
v71 = getReceiverDomainTransportProjectionV71Protocol();
caseInfo = resolveCase(context, protocol, options);
expectedFormationIds = getField(options, ...
    'expectedSelectedFormationIds', ...
    caseInfo.expectedSelectedFormationIds);
expectedSlotCount = getField(options, ...
    'expectedSelectedSlotCount', caseInfo.expectedSelectedSlotCount);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
v70 = getReceiverDomainNormalizedOpportunityV70Protocol();
[~, control] = computeFormationRoutingLeverageSignature( ...
    context, groupIds, struct('referenceMode', 'current-physical-tree'));
base = computeNetworkAdditiveFormationRiskV65( ...
    control, context, groupIds, v70.positiveSupportThreshold);
influence = computeInfluenceAwareDecisionBreadthV66( ...
    control, context, groupIds, struct( ...
        'positiveSupportThreshold', v70.positiveSupportThreshold, ...
        'horizonSteps', v70.horizonSteps));
transport = computeAlternativeTransportHeadroomV68( ...
    context, control, groupIds, ...
    getSignedMergeSplitOpportunityV69Protocol());
local = computeReceiverDomainNormalizedOpportunityV70( ...
    base, influence, control, transport, groupIds, v70);
projection = buildReceiverDomainTransportProjectionV71( ...
    context, control, transport, local, groupIds, ...
    getReceiverDomainTransportProjectionV71Protocol());
if projection.referenceFallbackUsed || ...
        ~isequal(projection.selectedFormationIds, ...
            reshape(expectedFormationIds, 1, [])) || ...
        numel(projection.selectedSlotIndices) ~= expectedSlotCount || ...
        ~projection.messageCountParityWithReference || ...
        ~projection.perReceiverMessageCountParityWithReference || ...
        ~projection.perReceiverWeightMultisetParityWithReference || ...
        ~all(projection.selectedRollingB3SensorPass) || ...
        ~all(projection.selectedRollingB3FormationPass)
    error('ReceiverDomainTransportV72:SourceDrift', ...
        'The V71 source action no longer matches its frozen outcome gate.');
end

nodeCount = numel(groupIds);
groups = unique(groupIds, 'stable');
actionCount = 2;
bank = struct();
bank.contractVersion = ...
    'receiver-domain-transport-action-bank-v71-v1';
bank.protocolId = protocol.sourceProtocolId;
bank.referenceMode = 'current-physical-tree';
bank.nodeCount = nodeCount;
bank.formationCount = numel(groups);
bank.groupIds = groupIds;
bank.actionCount = actionCount;
bank.referenceActionIndex = 1;
bank.actionNames = {'reference', projection.selectedActionName};
bank.actionFormationIds = {zeros(1, 0), ...
    projection.selectedFormationIds};
bank.actionSlotIndices = {zeros(1, 0), ...
    projection.selectedSlotIndices};
bank.actionAdjacency = cat(3, ...
    projection.referenceAdjacency, projection.selectedAdjacency);
bank.actionFusionWeights = cat(3, ...
    projection.referenceFusionWeights, ...
    projection.selectedFusionWeights);
bank.actionMessageCounts = [projection.referenceMessageCount, ...
    projection.selectedMessageCount];
bank.actionWithinReferencePayload = [true, true];
bank.actionPosteriorSafetyMask = [true, true];
bank.actionPosteriorProxyAllowed = [true, true];
bank.actionPosteriorObjective = [0, projection.selectedUtilityMass];
bank.actionPredictedNetSavingBytes = [0, NaN];
bank.actionPayloadBytes = [NaN, NaN];
bank.actionFormationIndex = [0, 0];
bank.actionModeIndex = [1, 2];
bank.modeTrustWeights = [0, v71.sourceWeight];
bank.actionRollingB3SensorPass = [ ...
    projection.referenceRollingB3SensorPass; ...
    projection.selectedRollingB3SensorPass];
bank.actionRollingB3FormationPass = [ ...
    projection.referenceRollingB3FormationPass; ...
    projection.selectedRollingB3FormationPass];
bank.safeActionIndices = 1:2;
bank.referenceMessageCount = projection.referenceMessageCount;
bank.selectedMessageCount = projection.selectedMessageCount;
bank.selectedUtilityMass = projection.selectedUtilityMass;
bank.selectedNetworkAverageNetFraction = ...
    projection.selectedNetworkAverageNetFraction;
bank.sourceProjection = projection;
bank.truthUsed = false;
bank.futureOutcomeUsed = false;
bank.openedDevelopmentEvidenceOnly = true;
bank.validationClaimAllowed = false;
end

function caseInfo = resolveCase(context, protocol, options)
requiredFields = {'presetName', 'seed', 'currentTime'};
if ~all(isfield(options, requiredFields)) || ...
        ~ischar(options.presetName) || ...
        ~isscalar(options.seed) || ~isfinite(options.seed) || ...
        ~isscalar(options.currentTime) || ...
        ~isfinite(options.currentTime) || ...
        options.currentTime ~= context.currentTime
    error('ReceiverDomainTransportV72:UnregisteredCase', ...
        'The V71 action bank needs one explicit frozen case identity.');
end
caseIndex = [];
for idx = 1:numel(protocol.cases)
    current = protocol.cases(idx);
    if strcmp(options.presetName, current.presetName) && ...
            options.seed == current.seed && ...
            options.currentTime == current.currentTime
        caseIndex = idx;
        break;
    end
end
if isempty(caseIndex) || ...
        numel(context.localPosteriorBySensor) ~= ...
            protocol.cases(caseIndex).expectedNodeCount
    error('ReceiverDomainTransportV72:UnregisteredCase', ...
        'The V71 action bank is restricted to two frozen V72 cases.');
end
caseInfo = protocol.cases(caseIndex);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
