function config = ...
        buildEventWindowResidualReinforcementV258Config(scenario)
% BUILDEVENTWINDOWRESIDUALREINFORCEMENTV258CONFIG One event residual slot.

protocol = getEventWindowResidualReinforcementV258Protocol();
if ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets) || ...
        ~isfield(scenario, 'numberOfSensors') || ...
        ~isfield(scenario, 'sensorGroupIds')
    error('EventWindowResidualV258:InvalidConfigInput', ...
        'V258 requires the registered temporal M24 scene.');
end
formationCount = numel(unique(scenario.sensorGroupIds));
minimumMessages = scenario.numberOfSensors + 2 * (formationCount - 1);
config = buildCausalMinimumFormationBackboneV242Config(scenario);
config.topologyPolicyName = protocol.policyName;
config.topologyPolicyFcn = ...
    @selectEventWindowResidualReinforcementV258Policy;
config.topologyDirectedMessageBudget = ...
    minimumMessages + protocol.maximumTotalResiduals;
end
