function [adjacency, fusionWeights, details] = ...
    buildBackbonePreservingResidualRoute( ...
        context, dominantAdjacency, residualAdjacency, ...
        dominantWeight, residualWeight)
% BUILDBACKBONEPRESERVINGRESIDUALROUTE Combine dominant and residual inputs.
%
% The dominant route is never replaced. A low-weight residual route is
% added for information-flow safety or cross-formation value. When both
% routes choose the same sender, their weights are combined and only one
% payload is attempted.

nodeCount = numel(context.localPosteriorBySensor);
physical = logical(context.physicalAdjacency);
if ~isequal(size(dominantAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(residualAdjacency), [nodeCount, nodeCount]) || ...
        any(sum(dominantAdjacency, 2) ~= 1) || ...
        any(sum(residualAdjacency, 2) ~= 1) || ...
        any(dominantAdjacency(:) & ~physical(:)) || ...
        any(residualAdjacency(:) & ~physical(:))
    error(['Backbone-preserving routes require one physical dominant ', ...
        'and residual source per receiver.']);
end
if isscalar(residualWeight)
    residualWeights = repmat( ...
        residualWeight, 1, nodeCount);
else
    residualWeights = reshape(residualWeight, 1, []);
end
if ~isscalar(dominantWeight) || ...
        numel(residualWeights) ~= nodeCount || ...
        ~isfinite(dominantWeight) || ...
        any(~isfinite(residualWeights)) || ...
        dominantWeight <= 0 || ...
        any(residualWeights <= 0) || ...
        any(dominantWeight + residualWeights >= 1)
    error(['Backbone-preserving weights must be positive and leave ', ...
        'a positive self weight.']);
end

dominantSources = zeros(1, nodeCount);
residualSources = zeros(1, nodeCount);
adjacency = logical(dominantAdjacency | residualAdjacency);
fusionWeights = zeros(nodeCount);
selfWeights = 1 - dominantWeight - residualWeights;
for receiverIdx = 1:nodeCount
    dominantSources(receiverIdx) = ...
        find(dominantAdjacency(receiverIdx, :), 1);
    residualSources(receiverIdx) = ...
        find(residualAdjacency(receiverIdx, :), 1);
    fusionWeights(receiverIdx, receiverIdx) = ...
        selfWeights(receiverIdx);
    fusionWeights(receiverIdx, ...
        dominantSources(receiverIdx)) = ...
        fusionWeights(receiverIdx, ...
            dominantSources(receiverIdx)) + dominantWeight;
    fusionWeights(receiverIdx, ...
        residualSources(receiverIdx)) = ...
        fusionWeights(receiverIdx, ...
            residualSources(receiverIdx)) + ...
                residualWeights(receiverIdx);
end
positiveAllowed = adjacency | logical(eye(nodeCount));
if any(abs(sum(fusionWeights, 2) - 1) > 1e-12) || ...
        any(fusionWeights(:) < 0) || ...
        any(fusionWeights(:) > 0 & ~positiveAllowed(:))
    error('Backbone-preserving fusion weights are invalid.');
end

details = struct();
details.dominantSourcesByReceiver = dominantSources;
details.residualSourcesByReceiver = residualSources;
details.dominantWeight = dominantWeight;
details.residualWeight = residualWeight;
details.residualWeightsByReceiver = residualWeights;
details.selfWeight = 1 - dominantWeight - residualWeight;
details.selfWeightsByReceiver = selfWeights;
details.duplicateSourceFraction = mean( ...
    dominantSources == residualSources);
details.messageCount = nnz(adjacency);
details.maximumMessagesPerReceiver = ...
    max(sum(adjacency, 2));
details.fusionWeightMatrix = fusionWeights;
end
