function control = buildFormationAlternativeGatewayReconnectControl( ...
        context, options)
% BUILDFORMATIONALTERNATEGATEWAYRECONNECTCONTROL Source-only v32 projector.
%
% The formation-level cycle, dominant route, residual trust, and message
% count remain fixed. A K-best dynamic program proposes alternative sensor
% gateway realizations from current label-wise KLA compatibility. Exact
% one-round disagreement and reference-relative existence retention then
% select a safe route or return the registered reference.

if nargin < 2 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('AlternativeGateway:InvalidOptions', ...
        'The frozen v32 controller does not accept option overrides.');
end
protocol = getFormationAlternativeGatewayProbeProtocol();
nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || ...
        formationCount > protocol.maximumFormationCount || ...
        ~isfield(context, 'previousAdjacencyHistory') || ...
        size(context.previousAdjacencyHistory, 1) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 2) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 3) < 2
    error('AlternativeGateway:InvalidContext', ...
        'Alternative-gateway context is invalid.');
end

policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.residualWeight);
[referenceAdjacency, referenceDetails] = ...
    selectTemporalCrossEdgeSuspensionPolicy( ...
        context, zeros(1, 0), policyOptions);
referenceWeights = referenceDetails.fusionWeightMatrix;
referenceScore = scoreRoute( ...
    context, referenceAdjacency, referenceWeights, ...
    [], groupIds, protocol);
if ~referenceScore.safe || ...
        ~all(referenceDetails.rollingB3SensorPass) || ...
        ~all(referenceDetails.rollingB3FormationPass)
    error('AlternativeGateway:InvalidReference', ...
        'Registered reconnect reference failed its safety gate.');
end
referenceDistributions = ...
    referenceScore.networkDetails.receiverDistributions;
referenceFormationAdjacency = collapseToFormations( ...
    referenceAdjacency, groupIds);

[compatibilityScoreMatrix, compatibilityDetails] = ...
    computeLmbKlaCompatibilityMatrix(context, struct( ...
        'sourceWeight', protocol.compatibilitySourceWeight, ...
        'noveltyWeight', protocol.compatibilityNoveltyWeight, ...
        'precisionPenaltyWeight', ...
            protocol.compatibilityPrecisionPenaltyWeight));
baselineSources = reshape(referenceDetails. ...
    residualBaselinePolicyDetails.selectedSourcesByReceiver, 1, []);
dominantSources = reshape( ...
    referenceDetails.dominantSourcesByReceiver, 1, []);
rankedSelections = enumerateTopKSplicedResidualFormationCycles( ...
    groupIds, baselineSources, dominantSources, ...
    logical(context.physicalAdjacency), ...
    compatibilityScoreMatrix, protocol.formationOrientation, ...
    protocol.maximumGatewayCandidates, ...
    referenceDetails.spliceSelection.cutReceivers, ...
    protocol.maximumGatewayCutChanges);

candidateSelections = rankedSelections([]);
candidateAdjacency = cell(1, 0);
candidateWeights = cell(1, 0);
candidateRouteDetails = cell(1, 0);
candidateScores = cell(1, 0);
candidateImprovement = zeros(1, 0);
candidateSafe = false(1, 0);
candidateEligible = false(1, 0);
candidateRollingB3SensorPass = cell(1, 0);
candidateRollingB3FormationPass = cell(1, 0);
candidateGraphSha256 = cell(1, 0);
for rankedIdx = 1:numel(rankedSelections)
    selection = rankedSelections(rankedIdx);
    [adjacency, weights, routeDetails] = ...
        buildBackbonePreservingResidualRoute( ...
            context, referenceDetails.dominantAdjacency, ...
            selection.residualAdjacency, ...
            protocol.dominantWeight, protocol.residualWeight);
    if isequal(adjacency, referenceAdjacency) && ...
            isequal(weights, referenceWeights)
        continue;
    end
    candidateFormationAdjacency = collapseToFormations( ...
        adjacency, groupIds);
    [sensorPass, formationPass] = rollingB3Pass( ...
        context.previousAdjacencyHistory, ...
        cat(3, adjacency, referenceAdjacency, ...
            referenceAdjacency), groupIds);
    structuralPass = ...
        nnz(adjacency) == nnz(referenceAdjacency) && ...
        isequal(candidateFormationAdjacency, ...
            referenceFormationAdjacency) && ...
        isequal(routeDetails.dominantSourcesByReceiver, ...
            referenceDetails.dominantSourcesByReceiver) && ...
        all(abs(routeDetails.residualWeightsByReceiver - ...
            protocol.residualWeight) <= 1e-12) && ...
        all(sensorPass) && all(formationPass);
    if ~structuralPass
        error('AlternativeGateway:InvalidCandidate', ...
            'A ranked gateway route violates a frozen parity gate.');
    end

    score = scoreRoute( ...
        context, adjacency, weights, ...
        referenceDistributions, groupIds, protocol);
    improvement = disagreementImprovement( ...
        referenceScore.networkRisk, score.networkRisk);
    safe = score.safe && all(sensorPass) && all(formationPass);
    eligible = safe && improvement >= ...
        protocol.minimumDisagreementImprovementFraction - 1e-12;

    candidateIdx = numel(candidateScores) + 1;
    candidateSelections(candidateIdx) = selection;
    candidateAdjacency{candidateIdx} = adjacency;
    candidateWeights{candidateIdx} = weights;
    candidateRouteDetails{candidateIdx} = routeDetails;
    candidateScores{candidateIdx} = score;
    candidateImprovement(candidateIdx) = improvement;
    candidateSafe(candidateIdx) = safe;
    candidateEligible(candidateIdx) = eligible;
    candidateRollingB3SensorPass{candidateIdx} = sensorPass;
    candidateRollingB3FormationPass{candidateIdx} = formationPass;
    candidateGraphSha256{candidateIdx} = computeTextSha256( ...
        sprintf('%d,', selection.residualSourcesByReceiver));
end

eligibleIndices = find(candidateEligible);
if isempty(eligibleIndices)
    selectedCandidateIndex = NaN;
    selectedAdjacency = referenceAdjacency;
    selectedWeights = referenceWeights;
    selectedRouteDetails = referenceDetails;
    selectedScore = referenceScore;
    selectedSensorPass = referenceDetails.rollingB3SensorPass;
    selectedFormationPass = referenceDetails.rollingB3FormationPass;
    selectedActionName = 'reference';
else
    [~, localIdx] = max(candidateImprovement(eligibleIndices));
    selectedCandidateIndex = eligibleIndices(localIdx);
    selectedAdjacency = candidateAdjacency{selectedCandidateIndex};
    selectedWeights = candidateWeights{selectedCandidateIndex};
    selectedRouteDetails = ...
        candidateRouteDetails{selectedCandidateIndex};
    selectedScore = candidateScores{selectedCandidateIndex};
    selectedSensorPass = ...
        candidateRollingB3SensorPass{selectedCandidateIndex};
    selectedFormationPass = ...
        candidateRollingB3FormationPass{selectedCandidateIndex};
    selectedActionName = sprintf( ...
        'label-compatible-gateway-rank-%d', ...
        candidateSelections(selectedCandidateIndex).rank);
end
selectedImprovement = disagreementImprovement( ...
    referenceScore.networkRisk, selectedScore.networkRisk);
weightSupport = selectedAdjacency | logical(eye(nodeCount));
if any(~isfinite(selectedWeights(:))) || ...
        any(selectedWeights(:) < -1e-12) || ...
        any(selectedWeights(:) > 1e-12 & ~weightSupport(:)) || ...
        any(abs(sum(selectedWeights, 2) - 1) > 1e-12) || ...
        nnz(selectedAdjacency) ~= nnz(referenceAdjacency) || ...
        ~isequal(collapseToFormations( ...
            selectedAdjacency, groupIds), ...
            referenceFormationAdjacency) || ...
        ~selectedScore.safe || ...
        ~all(selectedSensorPass) || ~all(selectedFormationPass) || ...
        (~isnan(selectedCandidateIndex) && ...
         selectedImprovement < ...
            protocol.minimumDisagreementImprovementFraction - 1e-12)
    error('AlternativeGateway:InvalidSelection', ...
        'Selected alternative gateway violates a frozen invariant.');
end

evaluatedRouteCount = 1 + numel(candidateScores);
if evaluatedRouteCount > protocol.maximumControlRouteEvaluations
    error('AlternativeGateway:EvaluationBudgetExceeded', ...
        'Alternative-gateway projection exceeded its route budget.');
end
if isempty(candidateGraphSha256)
    candidateBankSha256 = computeTextSha256('empty');
else
    candidateBankSha256 = computeTextSha256( ...
        strjoin(candidateGraphSha256, char(31)));
end

control = struct();
control.contractVersion = ...
    'formation-alternative-gateway-control-v1';
control.protocolId = protocol.id;
control.nodeCount = nodeCount;
control.formationCount = formationCount;
control.groupIds = groupIds;
control.groups = groups;
control.referenceAdjacency = referenceAdjacency;
control.referenceFusionWeights = referenceWeights;
control.referencePolicyDetails = referenceDetails;
control.referenceScore = referenceScore;
control.referenceFormationAdjacency = ...
    referenceFormationAdjacency;
control.compatibilityScoreMatrix = compatibilityScoreMatrix;
control.compatibilityDetails = compatibilityDetails;
control.rankedProposalCount = numel(rankedSelections);
control.rankedSelections = rankedSelections;
control.candidateCount = numel(candidateScores);
control.candidateSelections = candidateSelections;
control.candidateAdjacency = candidateAdjacency;
control.candidateFusionWeights = candidateWeights;
control.candidateRouteDetails = candidateRouteDetails;
control.candidateScores = candidateScores;
control.candidateDisagreementImprovementFraction = ...
    candidateImprovement;
control.candidateSafetyMask = candidateSafe;
control.candidateEligibilityMask = candidateEligible;
control.candidateRollingB3SensorPass = ...
    candidateRollingB3SensorPass;
control.candidateRollingB3FormationPass = ...
    candidateRollingB3FormationPass;
control.candidateGraphSha256 = candidateGraphSha256;
control.candidateBankSha256 = candidateBankSha256;
control.safeCandidateCount = nnz(candidateSafe);
control.eligibleCandidateCount = nnz(candidateEligible);
control.selectedCandidateIndex = selectedCandidateIndex;
control.selectedAdjacency = selectedAdjacency;
control.selectedFusionWeights = selectedWeights;
control.selectedRouteDetails = selectedRouteDetails;
control.selectedScore = selectedScore;
control.selectedDisagreementImprovementFraction = ...
    selectedImprovement;
control.selectedRollingB3SensorPass = selectedSensorPass;
control.selectedRollingB3FormationPass = selectedFormationPass;
control.selectedActionName = selectedActionName;
control.referenceFallbackUsed = isnan(selectedCandidateIndex);
control.referenceMessageCount = nnz(referenceAdjacency);
control.selectedMessageCount = nnz(selectedAdjacency);
control.messageCountParityWithReference = ...
    control.selectedMessageCount == control.referenceMessageCount;
control.formationGraphParityWithReference = isequal( ...
    collapseToFormations(selectedAdjacency, groupIds), ...
    referenceFormationAdjacency);
control.residualWeightParityWithReference = all(abs( ...
    selectedRouteDetails.residualWeightsByReceiver - ...
        protocol.residualWeight) <= 1e-12);
control.evaluatedRouteCount = evaluatedRouteCount;
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.truthUsed = false;
control.futureOutcomeUsed = false;
control.openedDevelopmentEvidenceOnly = true;
control.validationClaimAllowed = false;
end

function score = scoreRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, protocol)
enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, enumerationOptions);
if isempty(referenceDistributions)
    referenceDistributions = networkDetails.receiverDistributions;
end
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        protocol.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        protocol.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        protocol.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        protocol.retentionReceiverTailWeight);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, ...
        groupIds, retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = ...
    retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= protocol. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= protocol. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= protocol. ...
        maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'retentionRisk', retentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function value = disagreementImprovement(referenceRisk, candidateRisk)
value = (referenceRisk - candidateRisk) / max(referenceRisk, eps);
end

function [sensorPass, formationPass] = ...
        rollingB3Pass(previousHistory, sequence, groupIds)
history = logical(previousHistory(:, :, end-1:end));
sensorPass = false(1, size(sequence, 3));
formationPass = false(1, size(sequence, 3));
for stepIdx = 1:size(sequence, 3)
    pages = cat(3, history, sequence(:, :, stepIdx));
    window = any(pages(:, :, max(1, end-2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = sequence(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end
