function context = ...
        buildTemporalObservationSupportedRepairV198ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled, ...
        onlineReselectionEnabled, horizonSteps)
% BUILDTEMPORALOBSERVATIONSUPPORTEDREPAIRV198EXECUTIONCONTEXT Scope V198.

if nargin < 7 || isempty(horizonSteps)
    protocol = getTemporalObservationSupportedRepairV198Protocol();
else
    protocol = getTemporalObservationSupportedRepairV198Protocol( ...
        horizonSteps);
end
context = buildBudgetedObservationSupportedRepairV197ExecutionContext( ...
    presetName, seed, currentTime, actionName, scheduleEnabled, ...
    onlineReselectionEnabled, protocol.horizonSteps);
context.contractVersion = ...
    'temporal-observation-supported-repair-v198-context-v1';
context.capability = ...
    'temporal-observation-supported-repair-v198-development';
context.action = ...
    'filter-temporal-observation-supported-repair-v198-development';
context.protocolId = protocol.id;
context.policyName = protocol.outcomePolicyName;
end
