function options = buildFormationGatewayRoutingOptions( ...
    presetName, overrides)
% BUILDFORMATIONGATEWAYROUTINGOPTIONS Registered gateway-policy settings.

if nargin < 1 || isempty(presetName)
    presetName = 'novelty-gated-v1';
end
if nargin < 2 || isempty(overrides)
    overrides = struct();
end
presetName = lower(strrep(char(presetName), '_', '-'));
switch presetName
    case {'v1', 'novelty-gated-v1'}
        options = struct( ...
            'presetName', 'novelty-gated-v1', ...
            'sourceWeight', 0.50, ...
            'baselinePhase', 1, ...
            'anchorTime', 1, ...
            'positiveExistenceWeight', 1, ...
            'positivePrecisionWeight', 0, ...
            'negativeExistencePenalty', 0, ...
            'negativePrecisionPenalty', 50, ...
            'discrepancyPenalty', 8, ...
            'receiverNeedMultiplier', 0, ...
            'marginThreshold', 0.02, ...
            'minimumPositiveExistence', 0.05, ...
            'maxCrossPerFormation', 1, ...
            'maxCrossSourceLoad', 1, ...
            'switchHysteresis', 0);
    otherwise
        error('Unknown formation-gateway preset: %s', presetName);
end

fields = fieldnames(overrides);
for fieldIdx = 1:numel(fields)
    options.(fields{fieldIdx}) = overrides.(fields{fieldIdx});
end
end
