function context = buildDirectGraphPayloadRepairV214ExecutionContext( ...
        presetName, seed, phase, currentTime, measurementTimeCount, ...
        actionName, scheduleEnabled, repairPlan)
% BUILDDIRECTGRAPHPAYLOADREPAIRV214EXECUTIONCONTEXT Scope V214 runs.

if nargin < 8 || isempty(repairPlan)
    repairPlan = struct();
end
protocol = getDirectGraphPayloadRepairControllerV214Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~ischar(phase) || isempty(phase) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || currentTime < 1 || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount ~= round(measurementTimeCount) || ...
        measurementTimeCount < currentTime || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled)) || ...
        ~isstruct(repairPlan) || ~isscalar(repairPlan)
    error('DirectGraphPayloadRepairV214:InvalidExecutionContext', ...
        'The V214 execution-context input is invalid.');
end

context = struct();
context.contractVersion = ...
    'direct-graph-payload-repair-v214-context-v1';
context.capability = ...
    'direct-graph-payload-repair-v214-development';
context.action = ...
    'filter-direct-graph-payload-repair-v214-development';
context.protocolId = protocol.id;
context.phase = phase;
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = measurementTimeCount;
context.policyName = protocol.base.policyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.budgetRecycledFormationRepairPlan = repairPlan;
context.developmentEvidenceOnly = true;
end
