function probe = buildFormationBackboneConditionalBundleProbe(context)
% BUILDFORMATIONBACKBONECONDITIONALBUNDLEPROBE V40 all-single diagnostic.
%
% This function does not select a runtime action.  It compares every
% formation's v40 conditional-preserving single-bundle intervention with
% the frozen v38 self-return intervention on the same current posterior,
% link probabilities and topology history.

policy = getFormationBackboneConditionalBundlePolicyConfig();
basePolicy = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
if formationCount < 2 || ...
        formationCount > policy.maximumFormationCount
    error('FormationConditionalBundleProbe:InvalidContext', ...
        'The formation partition is outside the registered v40 scope.');
end

[referenceAdjacency, referenceDetails] = ...
    selectTemporalFormationBackboneConditionalInputBundleSuspensionPolicy( ...
        context, zeros(1, 0), struct('policyConfig', policy));
referenceScore = scoreFormationBackboneBundleRoute( ...
    context, referenceAdjacency, referenceDetails.fusionWeightMatrix, ...
    [], groupIds, basePolicy);
if ~referenceScore.safe
    error('FormationConditionalBundleProbe:UnsafeReference', ...
        'The registered reference failed the unchanged hard safety gates.');
end
referenceDistributions = ...
    referenceScore.networkDetails.receiverDistributions;
incrementalReference = struct( ...
    'networkDetails', referenceScore.networkDetails, ...
    'adjacency', referenceAdjacency, ...
    'fusionWeights', referenceDetails.fusionWeightMatrix);
referenceExpectedCardinality = ...
    referenceScore.retentionDetails.expectedReferenceCardinality;

conditional = repmat(emptyRecord(), 1, formationCount);
legacy = repmat(emptyRecord(), 1, formationCount);
for formationIdx = 1:formationCount
    formationId = groups(formationIdx);
    conditional(formationIdx) = evaluateSingle( ...
        context, formationId, formationIdx, groupIds, ...
        referenceDistributions, referenceExpectedCardinality, ...
        referenceScore.networkRisk, basePolicy, incrementalReference, ...
        true);
    legacy(formationIdx) = evaluateSingle( ...
        context, formationId, formationIdx, groupIds, ...
        referenceDistributions, referenceExpectedCardinality, ...
        referenceScore.networkRisk, basePolicy, incrementalReference, ...
        false);
end

probe = struct();
probe.contractVersion = ...
    'formation-backbone-conditional-bundle-mechanism-probe-v1';
probe.policyConfig = policy;
probe.policyConfigSha256 = policy.canonicalSha256;
probe.basePolicyConfigSha256 = basePolicy.canonicalSha256;
probe.groups = groups;
probe.referenceAdjacency = referenceAdjacency;
probe.referenceFusionWeights = referenceDetails.fusionWeightMatrix;
probe.referenceScore = referenceScore;
probe.conditionalSingles = conditional;
probe.legacySingles = legacy;
probe.conditionalAvailableCount = nnz([conditional.available]);
probe.conditionalSafeCount = nnz([conditional.safe]);
probe.conditionalRequestedCount = nnz([conditional.requested]);
probe.conditionalStrictRiskFeasibleSafeCount = nnz( ...
    [conditional.strictRiskFeasible] & [conditional.safe]);
probe.conditionalPositiveProtectionSafeCount = nnz( ...
    [conditional.positiveProtection] & [conditional.safe]);
probe.legacyAvailableCount = nnz([legacy.available]);
probe.legacySafeCount = nnz([legacy.safe]);
probe.legacyRequestedCount = nnz([legacy.requested]);
probe.legacyStrictRiskFeasibleSafeCount = nnz( ...
    [legacy.strictRiskFeasible] & [legacy.safe]);
comparable = [conditional.available] & [legacy.available];
probe.comparableSingleCount = nnz(comparable);
probe.conditionalLowerRiskCount = nnz(comparable & ...
    [conditional.networkRiskChangeFraction] < ...
        [legacy.networkRiskChangeFraction]);
probe.conditionalPreservingInvariantPassed = ...
    all(~[conditional.available] | ...
        [conditional.conditionalWeightInvariantPassed]);
probe.runtimeActionSelected = false;
probe.entryDisagreementGateApplied = false;
probe.entryDisagreementDiagnosticOnly = true;
probe.trackingOutcomeScored = false;
probe.truthUsed = false;
probe.futureOutcomeUsed = false;
end

function record = evaluateSingle( ...
        context, formationId, formationIdx, groupIds, ...
        referenceDistributions, referenceExpectedCardinality, ...
        referenceRisk, policy, incrementalReference, conditionalMode)
record = emptyRecord();
record.formationId = formationId;
try
    if conditionalMode
        [adjacency, details] = ...
            selectTemporalFormationBackboneConditionalInputBundleSuspensionPolicy( ...
                context, formationId);
    else
        [adjacency, details] = ...
            selectTemporalFormationBackboneInputBundleSuspensionPolicy( ...
                context, formationId);
    end
    score = scoreFormationBackboneBundleRoute( ...
        context, adjacency, details.fusionWeightMatrix, ...
        referenceDistributions, groupIds, policy, ...
        incrementalReference);
    members = groupIds == formationId;
    referenceFormationCardinality = mean( ...
        referenceExpectedCardinality(members));
    protectionFraction = score.retentionDetails. ...
        formationMeanCardinalityChange(formationIdx) / max( ...
            referenceFormationCardinality, 1);
    safe = score.safe && ...
        all(details.rollingB3SensorPass) && ...
        all(details.rollingB3FormationPass);
    record.available = true;
    record.safe = safe;
    record.requested = safe && ...
        referenceFormationCardinality >= ...
            policy.minimumReferenceFormationExpectedCardinality && ...
        protectionFraction >= policy.protectionScoreOnFraction - 1e-12;
    record.positiveProtection = protectionFraction > 0;
    record.strictRiskFeasible = score.networkRisk <= referenceRisk;
    record.protectionFraction = protectionFraction;
    record.referenceFormationExpectedCardinality = ...
        referenceFormationCardinality;
    record.networkRisk = score.networkRisk;
    record.networkRiskChangeFraction = ...
        (score.networkRisk - referenceRisk) / max(referenceRisk, eps);
    record.messageSavingCount = details.messageSavingCount;
    record.adjacency = adjacency;
    record.fusionWeights = details.fusionWeightMatrix;
    record.details = details;
    record.score = score;
    if conditionalMode
        record.conditionalWeightInvariantPassed = ...
            verifyConditionalRows(details);
    end
catch errorInfo
    if ~isExpectedUnavailable(errorInfo)
        rethrow(errorInfo);
    end
    record.failureIdentifier = getErrorField(errorInfo, 'identifier');
    record.failureMessage = getErrorField(errorInfo, 'message');
end
end

function passed = verifyConditionalRows(details)
passed = true;
reference = details.referenceFusionWeights;
candidate = details.fusionWeightMatrix;
for edgeIdx = 1:numel(details.suspendedReceivers)
    receiver = details.suspendedReceivers(edgeIdx);
    sender = details.suspendedSenders(edgeIdx);
    expected = reference(receiver, :);
    expected(sender) = 0;
    expected = expected / sum(expected);
    if ~isequaln(candidate(receiver, :), expected)
        passed = false;
        return;
    end
end
end

function record = emptyRecord()
record = struct( ...
    'formationId', nan, ...
    'available', false, ...
    'safe', false, ...
    'requested', false, ...
    'positiveProtection', false, ...
    'strictRiskFeasible', false, ...
    'protectionFraction', nan, ...
    'referenceFormationExpectedCardinality', nan, ...
    'networkRisk', nan, ...
    'networkRiskChangeFraction', nan, ...
    'messageSavingCount', nan, ...
    'conditionalWeightInvariantPassed', false, ...
    'adjacency', [], ...
    'fusionWeights', [], ...
    'details', struct(), ...
    'score', struct(), ...
    'failureIdentifier', '', ...
    'failureMessage', '');
end

function value = isExpectedUnavailable(errorInfo)
identifier = getErrorField(errorInfo, 'identifier');
value = strcmp(identifier, ...
        'FormationBundleSuspension:Infeasible');
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
if isempty(value)
    value = '';
end
end
