function context = ...
        buildFormationCoordinatedPosteriorRepairV185ExecutionContext( ...
            presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDFORMATIONCOORDINATEDPOSTERIORREPAIRV185EXECUTIONCONTEXT Frozen context.

protocol = getFormationCoordinatedPosteriorRepairV185Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('FormationPosteriorRepairV185:InvalidExecutionContext', ...
        'The V185 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'formation-coordinated-posterior-repair-v185-context-v1';
context.capability = ...
    'formation-coordinated-posterior-repair-v185-development';
context.action = ...
    'filter-formation-coordinated-posterior-repair-v185-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
