function context = buildPropagationAwareDwellV101ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDPROPAGATIONAWAREDWELLV101EXECUTIONCONTEXT Frozen H=6 probe.

protocol = getPropagationAwareDwellV101Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('PropagationAwareDwellV101:InvalidExecutionContext', ...
        'The V101 execution-context input is invalid.');
end

context = struct();
context.contractVersion = ...
    'propagation-aware-dwell-v101-context-v1';
context.capability = ...
    'propagation-aware-dwell-v101-development';
context.action = ...
    'filter-propagation-aware-dwell-v101-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
