function [context, metadata] = ...
    buildFormationIndexEquivariantGeometryDevelopmentContext( ...
        presetName, seed)
% BUILDFORMATIONINDEXEQUIVARIANTGEOMETRYDEVELOPMENTCONTEXT V43 input.
%
% This is an explicitly development-only loader: it materializes planned
% sensor and link schedules and then slices the registered focus-start
% page.  The route receives only that current page.  A later runtime
% observable loader must reproduce the same fields without materializing
% future pages before tracking is authorized.

if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isnumeric(seed) || ~isreal(seed) || ...
        ~isfinite(seed) || seed ~= round(seed)
    error('FormationIndexEquivariantContext:InvalidInput', ...
        'The v43 geometry-development inputs are invalid.');
end
rng(seed, 'twister');
config = buildDynamicTopologyScenarioConfig(presetName);
[sensorTrajectories, trajectoryMetadata] = ...
    generateMultiFormationTrajectories(config);
graph = buildDynamicTopologyGraphs(config, sensorTrajectories);
[pDropByEdge, ~] = buildDynamicTopologyLinkSchedule(config, graph);
currentTime = config.focusWindow(1);
nodeCount = config.numberOfSensors;

positions = zeros(2, nodeCount);
for sensorIdx = 1:nodeCount
    positions(:, sensorIdx) = ...
        sensorTrajectories{sensorIdx}(1:2, currentTime);
end
identity = buildDynamicTopologyPhysicalIdentityRegistry(config);
sensorPhysicalUids = trajectoryMetadata.sensorPhysicalUids;
formationPhysicalUidsBySensor = ...
    trajectoryMetadata.formationPhysicalUidsBySensor;
if ~strcmp(identity.canonicalSha256, ...
        trajectoryMetadata.physicalIdentityRegistryCanonicalSha256) || ...
        ~isequal(sensorPhysicalUids, identity.sensorPhysicalUids) || ...
        ~isequal(formationPhysicalUidsBySensor, ...
            identity.formationPhysicalUidsBySensor)
    error('FormationIndexEquivariantContext:IdentityRegistryDrift', ...
        'Trajectory identities disagree with the registered scene.');
end

model = struct();
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', config.sensorGroupIds), ...
    'staticAdjacency', logical(graph.staticAdjacency));
context = struct();
context.localPosteriorBySensor = cell(1, nodeCount);
context.model = model;
context.baseAdjacency = logical(graph.staticAdjacency);
context.physicalAdjacency = logical( ...
    graph.physicalAdjacency(:, :, currentTime));
context.positions = positions;
context.sensorPhysicalUids = sensorPhysicalUids;
context.formationPhysicalUidsBySensor = ...
    formationPhysicalUidsBySensor;
context.currentTime = currentTime;
context.commConfig = struct( ...
    'forceDelivery', config.forceDelivery, ...
    'pDropByEdge', pDropByEdge(:, :, currentTime), ...
    'outageSchedule', getField(config, 'outageSchedule', []), ...
    'deliveryIndependenceAttested', true, ...
    'deliverySampler', [ ...
        'runEventTriggeredDistributedLmbFilter-simulateDelivery-', ...
        'independent-uniform-per-sender-receiver-time']);
context.triggerConfig = buildMixtureAwareKlaReferenceConfig();
context.directedMessageBudget = 2 * nodeCount;
context.auditBoundary = struct( ...
    'contractVersion', ...
        'formation-index-equivariant-development-boundary-v1', ...
    'fullPlannedSensorGeometryMaterialized', true, ...
    'fullPlannedLinkProbabilityScheduleMaterialized', true, ...
    'formalRuntimeObservableBoundaryPassed', false, ...
    'runtimePhysicalUidRegistryIntegrated', false, ...
    'posteriorContentsRead', false, ...
    'truthUsed', false, ...
    'measurementUsed', false, ...
    'futureOutcomeUsed', false, ...
    'realizedDeliveryUniformsUsed', false, ...
    'trackingOutcomeScored', false, ...
    'trackingOutcomeAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true);
[referenceAdjacency, referenceDetails] = ...
    selectIndexEquivariantFormationBackbonePolicy(context);
context.previousAdjacencyHistory = ...
    repmat(referenceAdjacency, 1, 1, 2);

runtimeSemantics = ...
    validateReliableKlaMixingRuntimeSemantics(context.triggerConfig);
communicationSemantics = ...
    validateReliableKlaCommunicationRuntimeSemantics(context.commConfig);
inputPayload = struct( ...
    'presetName', presetName, 'seed', seed, ...
    'currentTime', currentTime, ...
    'sensorGroupIds', config.sensorGroupIds, ...
    'sensorPhysicalUids', sensorPhysicalUids, ...
    'formationPhysicalUidsBySensor', ...
        formationPhysicalUidsBySensor, ...
    'positions', positions, ...
    'baseAdjacency', context.baseAdjacency, ...
    'physicalAdjacency', context.physicalAdjacency, ...
    'pDropByEdge', context.commConfig.pDropByEdge, ...
    'auditBoundary', context.auditBoundary, ...
    'referenceRouteCanonicalSha256', ...
        computeCanonicalValueSha256(struct( ...
            'adjacency', referenceAdjacency, ...
            'weights', referenceDetails.fusionWeightMatrix)), ...
    'runtimeSemanticsCanonicalSha256', ...
        runtimeSemantics.canonicalSha256, ...
    'communicationSemanticsCanonicalSha256', ...
        communicationSemantics.canonicalSha256);

metadata = struct();
metadata.contractVersion = ...
    'formation-index-equivariant-geometry-development-context-v1';
metadata.presetName = presetName;
metadata.seed = seed;
metadata.currentTime = currentTime;
metadata.nodeCount = nodeCount;
metadata.formationCount = config.formationCount;
metadata.sensorGroupIds = config.sensorGroupIds;
metadata.sensorPhysicalUids = sensorPhysicalUids;
metadata.formationPhysicalUidsBySensor = ...
    formationPhysicalUidsBySensor;
metadata.physicalUidAssignmentContract = identity.contractVersion;
metadata.physicalUidAssignmentCanonicalSha256 = ...
    identity.canonicalSha256;
metadata.inputCanonicalSha256 = ...
    computeCanonicalValueSha256(inputPayload);
metadata.referenceRouteCanonicalSha256 = ...
    inputPayload.referenceRouteCanonicalSha256;
metadata.runtimeSemanticsCanonicalSha256 = ...
    runtimeSemantics.canonicalSha256;
metadata.communicationSemanticsCanonicalSha256 = ...
    communicationSemantics.canonicalSha256;
metadata.fullPlannedSensorGeometryMaterialized = true;
metadata.fullPlannedLinkProbabilityScheduleMaterialized = true;
metadata.formalRuntimeObservableBoundaryPassed = false;
metadata.posteriorUsed = false;
metadata.truthUsed = false;
metadata.measurementUsed = false;
metadata.targetTrajectoryGenerated = false;
metadata.realizedDeliveryUniformsUsed = false;
metadata.developmentEvidenceOnly = true;
metadata.auditBoundary = context.auditBoundary;
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
