function context = buildStaticVsDynamicRoutingV91ExecutionContext( ...
        presetName, seed, armId, measurementTimeCount)
% BUILDSTATICVSDYNAMICROUTINGV91EXECUTIONCONTEXT Full-episode gate.

protocol = getStaticVsDynamicRoutingV91Protocol();
if ~ischar(presetName) || ~isrow(presetName) || ...
        ~any(strcmp(presetName, protocol.presets)) || ...
        ~isscalar(seed) || ~isfinite(seed) || ...
        seed ~= protocol.allSeeds || ...
        ~ischar(armId) || ~isrow(armId) || ...
        ~any(strcmp(armId, {protocol.dynamicArmId, ...
            protocol.staticArmId})) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount ~= round(measurementTimeCount)
    error('StaticVsDynamicV91:InvalidExecutionContextInput', ...
        'V91 requires a registered scale, seed, arm and full time axis.');
end
if strcmp(armId, protocol.dynamicArmId)
    policyName = protocol.dynamicPolicyName;
else
    policyName = protocol.staticPolicyName;
end
context = struct();
context.contractVersion = ...
    'static-vs-dynamic-routing-v91-full-episode-context-v1';
context.capability = ...
    'static-vs-dynamic-routing-full-episode-development';
context.action = ...
    'filter-static-vs-dynamic-routing-full-episode-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = armId;
context.measurementTimeCount = measurementTimeCount;
context.policyName = policyName;
context.developmentEvidenceOnly = true;
end
