function manifest = ...
    buildFormationIndexEquivariantRouteV43ExecutableSourceManifest(repoRoot)
% BUILD...MANIFEST Resolve, hash and bind the v43 execution chain to HEAD.

if nargin < 1 || isempty(repoRoot)
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
end
repoRoot = char(repoRoot);
environmentName = 'FORMATION_V43_MANIFEST_GIT_ROOT';
previousValue = getenv(environmentName);
cleanup = onCleanup(@() setenv(environmentName, previousValue)); %#ok<NASGU>
setenv(environmentName, repoRoot);
[status, topLevel] = system([ ...
    'git -C "$FORMATION_V43_MANIFEST_GIT_ROOT" ', ...
    'rev-parse --show-toplevel']);
if status ~= 0 || ~strcmp(strtrim(topLevel), repoRoot)
    error('FormationIndexEquivariantV43Manifest:RepoRoot', ...
        'The v43 executable manifest did not resolve its worktree root.');
end

functionNames = { ...
    'runFormationIndexEquivariantRouteV43DevelopmentBatch', ...
    'getFormationIndexEquivariantRouteV43DevelopmentProtocol', ...
    'buildFormationIndexEquivariantRouteV43ExecutableSourceManifest', ...
    'evaluateFormationIndexEquivariantRouteV43DevelopmentGate', ...
    'buildFormationIndexEquivariantGeometryDevelopmentContext', ...
    'buildDynamicTopologyPhysicalIdentityRegistry', ...
    'buildDynamicTopologyScenarioConfig', ...
    'applyFormationFovSceneStyle', ...
    'computeFormationFovMultistyleSceneContractSha256', ...
    'getExpectedFormationFovMultistyleSceneContractSha256', ...
    'getFormationFovMultistyleAbsoluteDifficultyRequirements', ...
    'generateMultiFormationTrajectories', ...
    'buildDynamicTopologyGraphs', ...
    'buildDynamicTopologyLinkSchedule', ...
    'resolveDynamicTopologyBlockageWindows', ...
    'compareLegacyAndIndexEquivariantFormationRoutes', ...
    'selectFormationBackboneResidualTourPolicy', ...
    'selectRegisteredDirectedRoutingPolicy', ...
    'buildRegisteredFormationBackboneResidualTour', ...
    'buildIndexEquivariantFormationBackboneReference', ...
    'selectIndexEquivariantFormationBackbonePolicy', ...
    'selectTemporalIndexEquivariantFormationInputBundleSuspensionPolicy', ...
    'buildBackbonePreservingResidualRoute', ...
    'buildFormationIndexEquivariantAdaptiveWindowRouteProbe', ...
    'computeStaticReliableKlaMeanSquareHorizonProfile', ...
    'computeReliableKlaWindowMeanSquareContractionCertificate', ...
    'computeExpectedEffectiveMixingPageMoments', ...
    'validateFormationReliableKlaContractionFactor', ...
    'buildMixtureAwareKlaReferenceConfig', ...
    'validateReliableKlaMixingRuntimeSemantics', ...
    'validateReliableKlaCommunicationRuntimeSemantics', ...
    'computeCanonicalValueSha256', 'computeFileSha256', ...
    'computeTextSha256', 'computeBytesSha256'};
relativePaths = { ...
    'RUN/GA/runFormationIndexEquivariantRouteV43DevelopmentBatch.m', ...
    'common/getFormationIndexEquivariantRouteV43DevelopmentProtocol.m', ...
    'common/buildFormationIndexEquivariantRouteV43ExecutableSourceManifest.m', ...
    'common/evaluateFormationIndexEquivariantRouteV43DevelopmentGate.m', ...
    'common/buildFormationIndexEquivariantGeometryDevelopmentContext.m', ...
    'common/buildDynamicTopologyPhysicalIdentityRegistry.m', ...
    'common/buildDynamicTopologyScenarioConfig.m', ...
    'common/applyFormationFovSceneStyle.m', ...
    'common/computeFormationFovMultistyleSceneContractSha256.m', ...
    'common/getExpectedFormationFovMultistyleSceneContractSha256.m', ...
    'common/getFormationFovMultistyleAbsoluteDifficultyRequirements.m', ...
    'common/generateMultiFormationTrajectories.m', ...
    'common/buildDynamicTopologyGraphs.m', ...
    'common/buildDynamicTopologyLinkSchedule.m', ...
    'common/resolveDynamicTopologyBlockageWindows.m', ...
    'common/compareLegacyAndIndexEquivariantFormationRoutes.m', ...
    'common/selectFormationBackboneResidualTourPolicy.m', ...
    'common/selectRegisteredDirectedRoutingPolicy.m', ...
    'common/buildRegisteredFormationBackboneResidualTour.m', ...
    'common/buildIndexEquivariantFormationBackboneReference.m', ...
    'common/selectIndexEquivariantFormationBackbonePolicy.m', ...
    'common/selectTemporalIndexEquivariantFormationInputBundleSuspensionPolicy.m', ...
    'common/buildBackbonePreservingResidualRoute.m', ...
    'common/buildFormationIndexEquivariantAdaptiveWindowRouteProbe.m', ...
    'common/computeStaticReliableKlaMeanSquareHorizonProfile.m', ...
    'common/computeReliableKlaWindowMeanSquareContractionCertificate.m', ...
    'common/computeExpectedEffectiveMixingPageMoments.m', ...
    'common/validateFormationReliableKlaContractionFactor.m', ...
    'multisensorLmb/buildMixtureAwareKlaReferenceConfig.m', ...
    'common/validateReliableKlaMixingRuntimeSemantics.m', ...
    'common/validateReliableKlaCommunicationRuntimeSemantics.m', ...
    'common/computeCanonicalValueSha256.m', ...
    'common/computeFileSha256.m', ...
    'common/computeTextSha256.m', ...
    'common/computeBytesSha256.m'};
if numel(functionNames) ~= numel(relativePaths)
    error('FormationIndexEquivariantV43Manifest:InternalContract', ...
        'The executable manifest registry is inconsistent.');
end

records = repmat(struct('functionName', '', 'relativePath', '', ...
    'resolvedPath', '', 'fileSha256', '', 'trackedByHead', false, ...
    'workingBlobId', '', 'headBlobId', '', ...
    'workingFileMatchesHead', false), 1, numel(functionNames));
for functionIdx = 1:numel(functionNames)
    expectedPath = fullfile(repoRoot, relativePaths{functionIdx});
    resolvedPath = which(functionNames{functionIdx});
    if isempty(resolvedPath) || ~strcmp(resolvedPath, expectedPath) || ...
            exist(expectedPath, 'file') ~= 2
        error('FormationIndexEquivariantV43Manifest:PathShadowing', ...
            'Critical function %s resolved outside the v43 worktree.', ...
            functionNames{functionIdx});
    end
    relativePath = relativePaths{functionIdx};
    trackedStatus = system(sprintf([ ...
        'git -C "$FORMATION_V43_MANIFEST_GIT_ROOT" ', ...
        'ls-files --error-unmatch -- "%s" >/dev/null 2>&1'], ...
        relativePath));
    [workingStatus, workingBlob] = system(sprintf([ ...
        'git -C "$FORMATION_V43_MANIFEST_GIT_ROOT" ', ...
        'hash-object -- "%s"'], relativePath));
    [headStatus, headBlob] = system(sprintf([ ...
        'git -C "$FORMATION_V43_MANIFEST_GIT_ROOT" ', ...
        'rev-parse "HEAD:%s" 2>/dev/null'], relativePath));
    if workingStatus ~= 0
        error('FormationIndexEquivariantV43Manifest:HashFailed', ...
            'Cannot hash executable source %s.', relativePath);
    end
    tracked = trackedStatus == 0 && headStatus == 0;
    workingBlob = strtrim(workingBlob);
    headBlob = strtrim(headBlob);
    records(functionIdx).functionName = functionNames{functionIdx};
    records(functionIdx).relativePath = relativePath;
    records(functionIdx).resolvedPath = resolvedPath;
    records(functionIdx).fileSha256 = computeFileSha256(expectedPath);
    records(functionIdx).trackedByHead = tracked;
    records(functionIdx).workingBlobId = workingBlob;
    records(functionIdx).headBlobId = headBlob;
    records(functionIdx).workingFileMatchesHead = ...
        tracked && strcmp(workingBlob, headBlob);
end

manifest = struct();
manifest.contractVersion = ...
    'formation-index-equivariant-route-v43-executable-manifest-v2';
manifest.repoTopLevelVerified = true;
manifest.pathResolutionPassed = true;
manifest.records = records;
manifest.allEntriesTrackedByHead = all([records.trackedByHead]);
manifest.allWorkingFilesMatchHead = ...
    all([records.workingFileMatchesHead]);
manifest.canonicalSha256 = computeCanonicalValueSha256(manifest);
end
