function config = ...
        buildTemporallyBalancedMinimumBackboneV272Config(scenario)
% BUILDTEMPORALLYBALANCEDMINIMUMBACKBONEV272CONFIG Runtime config.

protocol = getTemporallyBalancedMinimumBackboneV272Protocol();
if ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets)
    error('TemporallyBalancedBackboneV272:InvalidConfigInput', ...
        'V272 requires one registered formation-braid scenario.');
end
config = buildCausalMinimumFormationBackboneV242Config(scenario);
config.topologyPolicyName = protocol.policyName;
config.topologyPolicyFcn = ...
    @selectTemporallyBalancedMinimumBackboneV272Policy;
config.topologyPolicyHistoryDepth = max( ...
    config.topologyPolicyHistoryDepth, protocol.historyDepth);
config.topologyPolicyTemporalGatewayBalanceEnabled = true;
config.topologyPolicyTemporalGatewayHistoryDepth = ...
    protocol.historyDepth;
config.topologyPolicyTemporalGatewayMinimumReliabilityRatio = ...
    protocol.minimumReliabilityRatio;
config.topologyPolicyTemporalGatewayMaximumReliabilityDrop = ...
    protocol.maximumReliabilityDrop;
config.topologyPolicyTemporalGatewayBalanceSenderRoles = ...
    protocol.balanceSenderRoles;
end
