function context = buildIntermittentLightNetworkAnchorV131ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDINTERMITTENTLIGHTNETWORKANCHORV131EXECUTIONCONTEXT Frozen V131 context.

protocol = getIntermittentLightNetworkAnchorV131Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('IntermittentLightNetworkAnchorV131:InvalidExecutionContext', ...
        'The V131 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'intermittent-light-network-anchor-v131-context-v1';
context.capability = ...
    'intermittent-light-network-anchor-v131-development';
context.action = ...
    'filter-intermittent-light-network-anchor-v131-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
