function actions = buildTimeExpandedDualPathV119Actions( ...
        baseAdjacency, baseWeights, baseDetails, physicalAdjacency, protocol)
% BUILDTIMEEXPANDEDDUALPATHV119ACTIONS Paired donor/dual actions.

if nargin < 5 || isempty(protocol)
    protocol = getTimeExpandedDualPathV119Protocol();
end
adjacency = logical(baseAdjacency);
weights = double(baseWeights);
physical = logical(physicalAdjacency);
nodeCount = size(adjacency, 1);
if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        ~isequal(size(physical), [nodeCount, nodeCount]) || ...
        ~isstruct(baseDetails) || ~isscalar(baseDetails) || ...
        ~isfield(baseDetails, 'residualAdjacency')
    error('TimeExpandedDualPathV119:InvalidActionInput', ...
        'The V119 route input is malformed.');
end
residual = logical(baseDetails.residualAdjacency);
pairCount = numel(protocol.sourceFormationIds);
actions = repmat(emptyAction(), 1, 2 * pairCount);
for pairIdx = 1:pairCount
    sender = protocol.donorSourceSensorIds(pairIdx);
    donorReceiver = protocol.donorReceiverSensorIds(pairIdx);
    targetReceiver = protocol.targetReceiverSensorIds(pairIdx);
    sourceWeight = weights(donorReceiver, sender);
    if ~adjacency(donorReceiver, sender) || ...
            ~residual(donorReceiver, sender) || ...
            adjacency(targetReceiver, sender) || ...
            ~physical(targetReceiver, sender) || ...
            abs(sourceWeight - 0.05) > 1e-12 || ...
            weights(targetReceiver, targetReceiver) < ...
                sourceWeight - 1e-12
        error('TimeExpandedDualPathV119:InvalidToken', ...
            'A registered V119 residual token is unavailable.');
    end
    donorAdjacency = adjacency;
    donorWeights = weights;
    donorResidual = residual;
    donorAdjacency(donorReceiver, sender) = false;
    donorWeights(donorReceiver, sender) = 0;
    donorWeights(donorReceiver, donorReceiver) = ...
        donorWeights(donorReceiver, donorReceiver) + sourceWeight;
    donorResidual(donorReceiver, sender) = false;

    dualAdjacency = donorAdjacency;
    dualWeights = donorWeights;
    dualResidual = donorResidual;
    dualAdjacency(targetReceiver, sender) = true;
    dualWeights(targetReceiver, sender) = sourceWeight;
    dualWeights(targetReceiver, targetReceiver) = ...
        dualWeights(targetReceiver, targetReceiver) - sourceWeight;
    dualResidual(targetReceiver, sender) = true;

    donorIdx = 2 * pairIdx - 1;
    dualIdx = donorIdx + 1;
    actions(donorIdx) = makeAction( ...
        protocol.donorOnlyActionNames{pairIdx}, donorAdjacency, ...
        donorWeights, donorResidual, baseDetails, pairIdx, ...
        sender, donorReceiver, 0, sourceWeight, false, adjacency);
    actions(dualIdx) = makeAction( ...
        protocol.dualPathActionNames{pairIdx}, dualAdjacency, ...
        dualWeights, dualResidual, baseDetails, pairIdx, ...
        sender, donorReceiver, targetReceiver, sourceWeight, true, ...
        adjacency);
end
end

function action = makeAction( ...
        name, adjacency, weights, residual, baseDetails, pairIdx, ...
        sender, donorReceiver, targetReceiver, sourceWeight, ...
        dualPath, baseAdjacency)
if max(abs(sum(weights, 2) - 1)) > 1e-12 || ...
        any(weights(:) < -1e-12) || ...
        any(weights(~(adjacency | eye(size(adjacency)) > 0)) > 1e-12)
    error('TimeExpandedDualPathV119:WeightInvariantFailed', ...
        'A V119 action changed the row-stochastic support.');
end
details = baseDetails;
details.fusionWeightMatrix = weights;
details.residualAdjacency = residual;
details.messageCount = nnz(adjacency);
if isfield(details, 'selectedSourcesByReceiver') && ...
        iscell(details.selectedSourcesByReceiver)
    details.selectedSourcesByReceiver{donorReceiver} = ...
        find(adjacency(donorReceiver, :));
    if dualPath
        details.selectedSourcesByReceiver{targetReceiver} = ...
            find(adjacency(targetReceiver, :));
    end
end
details.v119DualPath = struct( ...
    'pairIndex', pairIdx, ...
    'senderId', sender, ...
    'donorReceiverId', donorReceiver, ...
    'targetReceiverId', targetReceiver, ...
    'sourceWeight', sourceWeight, ...
    'dualPathEnabled', logical(dualPath), ...
    'networkMessageParityPassed', ...
        nnz(adjacency) == nnz(baseAdjacency), ...
    'senderMessageParityPassed', isequal( ...
        sum(adjacency, 1), sum(baseAdjacency, 1)), ...
    'rowSumPassed', max(abs(sum(weights, 2) - 1)) <= 1e-12);
action = emptyAction();
action.name = name;
action.adjacency = adjacency;
action.weights = weights;
action.details = details;
action.pairIndex = pairIdx;
action.dualPathEnabled = logical(dualPath);
end

function action = emptyAction()
action = struct('name', '', 'adjacency', false(0), ...
    'weights', zeros(0), 'details', struct(), ...
    'pairIndex', 0, 'dualPathEnabled', false);
end
