function context = buildOutwardReferenceCarrierV125ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDOUTWARDREFERENCECARRIERV125EXECUTIONCONTEXT Frozen V125 context.

protocol = getOutwardReferenceCarrierV125Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('OutwardReferenceCarrierV125:InvalidExecutionContext', ...
        'The V125 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'outward-reference-carrier-v125-context-v1';
context.capability = 'outward-reference-carrier-v125-development';
context.action = 'filter-outward-reference-carrier-v125-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
