function bank = buildTrackingAlignedX36ScheduleActionBank( ...
        context, groupIds, options)
% BUILDTRACKINGALIGNEDX36SCHEDULEACTIONBANK Frozen observable H=3 bank.
%
% The physical reference graph is identical for every arm.  Nonreference
% arms differ only in which formations temporarily stop consuming complete
% cross-formation posteriors.  Formation ranking uses current posterior
% association support and never reads truth, future measurements, or future
% outcomes.

if nargin < 3 || isempty(options)
    options = struct();
end
protocol = getTrackingAlignedX36ScheduleHeadroomV63Protocol();
bankVariant = lower(strrep(char(getField( ...
    options, 'bankVariant', 'top-k-v63')), '_', '-'));
networkAdditiveBank = strcmp(bankVariant, 'network-additive-v65');
addressableRiskBank = strcmp(bankVariant, 'addressable-risk-v96');
positiveNetAddressableBank = strcmp( ...
    bankVariant, 'positive-net-addressable-v97');
onlinePositiveNetBank = strcmp( ...
    bankVariant, 'online-positive-net-addressable-v99');
positiveNetPropagationBank = strcmp( ...
    bankVariant, 'online-positive-net-propagation-v100');
propagationAwareDwellBank = strcmp( ...
    bankVariant, 'propagation-aware-dwell-v101');
shieldBroadcastBank = strcmp(bankVariant, 'shield-broadcast-v102');
maturedHandoffBank = strcmp(bankVariant, 'matured-handoff-v103');
receiverSelectiveBank = strcmp( ...
    bankVariant, 'receiver-selective-handoff-v104');
protectionOnlyH8Bank = strcmp(bankVariant, 'protection-only-h8-v105');
protectionReleaseBank = strcmp( ...
    bankVariant, 'protection-release-oracle-v106');
protectionEarlyReleaseBank = strcmp( ...
    bankVariant, 'protection-early-release-oracle-v107');
signedCompleteLabelBank = strcmp( ...
    bankVariant, 'signed-complete-label-exception-v108');
riskMetricBank = networkAdditiveBank || addressableRiskBank || ...
    positiveNetAddressableBank || onlinePositiveNetBank || ...
    positiveNetPropagationBank || propagationAwareDwellBank || ...
    shieldBroadcastBank || maturedHandoffBank || receiverSelectiveBank || ...
    protectionOnlyH8Bank || protectionReleaseBank || ...
    protectionEarlyReleaseBank || signedCompleteLabelBank;
scheduleHorizonSteps = protocol.horizonSteps;
if positiveNetPropagationBank || propagationAwareDwellBank || ...
        shieldBroadcastBank || maturedHandoffBank || receiverSelectiveBank || ...
        protectionOnlyH8Bank || protectionReleaseBank || ...
        protectionEarlyReleaseBank || signedCompleteLabelBank
    if signedCompleteLabelBank
        propagationProtocol = ...
            getSignedCompleteLabelExceptionV108Protocol();
    elseif protectionEarlyReleaseBank
        propagationProtocol = ...
            getProtectionEarlyReleaseOracleV107Protocol();
    elseif protectionReleaseBank
        propagationProtocol = getProtectionReleaseOracleV106Protocol();
    elseif protectionOnlyH8Bank
        propagationProtocol = getProtectionOnlyH8V105Protocol();
    elseif receiverSelectiveBank
        propagationProtocol = getReceiverSelectiveHandoffV104Protocol();
    elseif maturedHandoffBank
        propagationProtocol = getMaturedHandoffV103Protocol();
    elseif shieldBroadcastBank
        propagationProtocol = getShieldBroadcastV102Protocol();
    elseif propagationAwareDwellBank
        propagationProtocol = getPropagationAwareDwellV101Protocol();
    else
        propagationProtocol = ...
            getOnlinePositiveNetPropagationV100Protocol();
    end
    scheduleHorizonSteps = round(getField(options, ...
        'horizonSteps', ...
        propagationProtocol.horizonSteps));
    if ~isscalar(scheduleHorizonSteps) || ...
            ~isfinite(scheduleHorizonSteps) || ...
            scheduleHorizonSteps < protocol.horizonSteps
        error('OnlinePositiveNetV100:InvalidPropagationHorizon', ...
            'The propagation probe requires an integer horizon >= 3.');
    end
end
groupIds = reshape(groupIds, 1, []);
if ~isstruct(context) || ~isfield(context, 'model') || ...
        ~isfield(context, 'currentTime') || ...
        numel(groupIds) ~= numel(context.localPosteriorBySensor) || ...
        (~riskMetricBank && ( ...
            ~ismember(context.currentTime, protocol.anchorTimes) || ...
            numel(groupIds) ~= protocol.expectedNodeCount || ...
            numel(unique(groupIds, 'stable')) ~= ...
                protocol.expectedFormationCount)) || ...
        (riskMetricBank && ...
            numel(unique(groupIds, 'stable')) < 2)
    error('TrackingAlignedV63:InvalidActionBankInput', ...
        'V63 requires a registered current X36 observable state.');
end

policyProtocol = getFormationIsolateReconnectProbeProtocol();
policyOptions = struct( ...
    'dominantWeight', policyProtocol.dominantWeight, ...
    'residualWeight', policyProtocol.residualWeight);
[referenceAdjacency, referenceDetails] = ...
    selectBackboneResidualSplicedCyclePolicy( ...
        context, 'fixed-counter-clockwise', policyOptions);
referenceWeights = referenceDetails.fusionWeightMatrix;

[signature, control] = ...
    computeFormationRoutingLeverageSignature(context, groupIds);
positiveSupportThreshold = getField(options, ...
    'positiveSupportThreshold', protocol.positiveSupportThreshold);
support = computeObservationSupportedRoutingLeverage( ...
    control, context, groupIds, positiveSupportThreshold);

groups = reshape(control.groups, 1, []);
scores = reshape( ...
    support.singleSupportWeightedRescuedFractionOfReference, 1, []);
available = reshape(control.singleActionAvailableMask, 1, []) & ...
    isfinite(scores);
if nnz(available) < 3
    error('TrackingAlignedV63:InsufficientObservableRanking', ...
        'V63 needs at least three observable formation interventions.');
end
availableIndices = find(available);
rankingTable = [-scores(availableIndices)', groups(availableIndices)'];
[~, localOrder] = sortrows(rankingTable, [1, 2]);
rankedIndices = availableIndices(localOrder);
rankedFormationIds = groups(rankedIndices);
rankedScores = scores(rankedIndices);

legacySchedule = {};
if ~riskMetricBank
    anchorIdx = find(protocol.anchorTimes == context.currentTime, 1);
    legacySchedule = protocol.legacyFormationSchedules{anchorIdx};
end
riskCoverageTargetFraction = NaN;
riskCoverageAchievedFraction = NaN;
riskCoverageFormationIds = zeros(1, 0);
networkRiskMetrics = struct();
networkRiskSelection = struct();
addressableRiskSelection = struct();
positiveNetAddressableSelection = struct();
v102Route = struct();
v103Route = struct();
v104Route = struct();
switch bankVariant
    case 'top-k-v63'
        top1 = rankedFormationIds(1);
        top2 = rankedFormationIds(1:2);
        top3 = rankedFormationIds(1:3);
        schedules = cell(1, 7);
        schedules{1} = {[], [], []};
        schedules{2} = legacySchedule;
        schedules{3} = {top1, top1, top1};
        schedules{4} = {top2, top2, top2};
        schedules{5} = {top3, top3, top3};
        schedules{6} = {top3, top2, top1};
        schedules{7} = {top3, top2, []};
        actionNames = { ...
            'reference-full-payload', ...
            'legacy-v37-schedule', ...
            sprintf('support-top1-persistent-%s', formatIds(top1)), ...
            sprintf('support-top2-persistent-%s', formatIds(top2)), ...
            sprintf('support-top3-persistent-%s', formatIds(top3)), ...
            sprintf('support-nested-3-2-1-%s', formatIds(top3)), ...
            sprintf('support-nested-3-2-0-%s', formatIds(top3))};
        bankContractVersion = ...
            'tracking-aligned-x36-schedule-action-bank-v63-v1';
    case 'risk-coverage-v64'
        riskCoverageTargetFraction = getField(options, ...
            'riskCoverageTargetFraction', 0.80);
        if ~isscalar(riskCoverageTargetFraction) || ...
                ~isfinite(riskCoverageTargetFraction) || ...
                riskCoverageTargetFraction <= 0 || ...
                riskCoverageTargetFraction > 1
            error('TrackingAlignedV64:InvalidRiskCoverageTarget', ...
                'The cumulative risk-coverage target must be in (0,1].');
        end
        positiveScores = max(rankedScores, 0);
        totalScore = sum(positiveScores);
        if totalScore <= eps
            error('TrackingAlignedV64:NoPositiveRiskMass', ...
                'The current state has no positive observable risk mass.');
        end
        coverageCount = find(cumsum(positiveScores) >= ...
            riskCoverageTargetFraction * totalScore - 1e-12, 1);
        riskCoverageFormationIds = ...
            rankedFormationIds(1:coverageCount);
        riskCoverageAchievedFraction = ...
            sum(positiveScores(1:coverageCount)) / totalScore;
        schedules = cell(1, 2);
        schedules{1} = {[], [], []};
        schedules{2} = { ...
            riskCoverageFormationIds, ...
            riskCoverageFormationIds, ...
            riskCoverageFormationIds};
        actionNames = { ...
            'reference-full-payload', ...
            sprintf('risk-coverage-%03d-persistent-%s', ...
                round(100 * riskCoverageTargetFraction), ...
                formatIds(riskCoverageFormationIds))};
        bankContractVersion = ...
            'tracking-aligned-x36-risk-coverage-action-bank-v64-v1';
    case 'network-additive-v65'
        v65 = getNetworkAdditiveFormationRiskV65Protocol();
        networkRiskMetrics = computeNetworkAdditiveFormationRiskV65( ...
            control, context, groupIds, v65.positiveSupportThreshold);
        networkRiskSelection = ...
            selectNetworkAdditiveFormationRiskSetV65( ...
                networkRiskMetrics, v65);
        if networkRiskSelection.actionEnabled
            selected = networkRiskSelection.selectedFormationIds;
            schedules = { ...
                {[], [], []}, ...
                {selected, selected, selected}};
            actionNames = { ...
                'reference-full-payload', ...
                sprintf('network-additive-risk-persistent-%s', ...
                    formatIds(selected))};
        else
            schedules = {{[], [], []}};
            actionNames = {'reference-full-payload'};
        end
        bankContractVersion = ...
            'tracking-aligned-x36-network-additive-action-bank-v65-v1';
    case 'addressable-risk-v96'
        v96 = getAddressableRiskAdaptivePayloadV96Protocol();
        networkRiskMetrics = computeNetworkAdditiveFormationRiskV65( ...
            control, context, groupIds, ...
            v96.positiveSupportThreshold);
        addressableRiskSelection = ...
            selectAddressableFormationRiskSetV96( ...
                networkRiskMetrics, v96);
        if addressableRiskSelection.actionEnabled
            selected = addressableRiskSelection.selectedFormationIds;
            schedules = { ...
                {[], [], []}, ...
                {selected, [], []}, ...
                {selected, selected, selected}};
            actionNames = { ...
                'reference-full-payload', ...
                sprintf('addressable-risk-one-step-%s', ...
                    formatIds(selected)), ...
                sprintf('addressable-risk-persistent-%s', ...
                    formatIds(selected))};
        else
            schedules = {{[], [], []}};
            actionNames = {'reference-full-payload'};
        end
        bankContractVersion = ...
            'addressable-risk-adaptive-payload-action-bank-v96-v1';
    case 'positive-net-addressable-v97'
        v96 = getAddressableRiskAdaptivePayloadV96Protocol();
        v97 = getPositiveNetAddressablePayloadV97Protocol();
        networkRiskMetrics = computeNetworkAdditiveFormationRiskV65( ...
            control, context, groupIds, ...
            v97.positiveSupportThreshold);
        addressableRiskSelection = ...
            selectAddressableFormationRiskSetV96( ...
                networkRiskMetrics, v96);
        positiveNetAddressableSelection = ...
            selectPositiveNetAddressableRiskSetV97( ...
                networkRiskMetrics, v97);
        schedules = {{[], [], []}};
        actionNames = {'reference-full-payload'};
        if addressableRiskSelection.actionEnabled
            selectedV96 = ...
                addressableRiskSelection.selectedFormationIds;
            schedules{end + 1} = ...
                {selectedV96, selectedV96, selectedV96};
            actionNames{end + 1} = sprintf( ...
                'v96-addressable-risk-persistent-%s', ...
                formatIds(selectedV96));
        end
        if positiveNetAddressableSelection.actionEnabled
            selectedV97 = ...
                positiveNetAddressableSelection.selectedFormationIds;
            schedules{end + 1} = ...
                {selectedV97, selectedV97, selectedV97};
            actionNames{end + 1} = sprintf( ...
                'v97-positive-net-persistent-%s', ...
                formatIds(selectedV97));
        end
        bankContractVersion = ...
            'positive-net-addressable-payload-action-bank-v97-v1';
    case 'online-positive-net-addressable-v99'
        v99 = getOnlinePositiveNetAddressablePayloadV99Protocol();
        networkRiskMetrics = computeNetworkAdditiveFormationRiskV65( ...
            control, context, groupIds, ...
            v99.positiveSupportThreshold);
        positiveNetAddressableSelection = ...
            selectPositiveNetAddressableRiskSetV97( ...
                networkRiskMetrics, v99);
        schedules = {{[], [], []}};
        actionNames = {'reference-full-payload'};
        if positiveNetAddressableSelection.actionEnabled
            selected = ...
                positiveNetAddressableSelection.selectedFormationIds;
            fixedSchedule = {selected, selected, selected};
            schedules{end + 1} = fixedSchedule;
            actionNames{end + 1} = sprintf( ...
                'v97-positive-net-persistent-%s', ...
                formatIds(selected));
            schedules{end + 1} = fixedSchedule;
            actionNames{end + 1} = sprintf( ...
                'v99-online-positive-net-%s', ...
                formatIds(selected));
        end
        bankContractVersion = ...
            'online-positive-net-addressable-action-bank-v99-v1';
    case 'online-positive-net-propagation-v100'
        v100 = getOnlinePositiveNetPropagationV100Protocol();
        networkRiskMetrics = computeNetworkAdditiveFormationRiskV65( ...
            control, context, groupIds, ...
            v100.positiveSupportThreshold);
        positiveNetAddressableSelection = ...
            selectPositiveNetAddressableRiskSetV97( ...
                networkRiskMetrics, v100);
        schedules = {repmat({[]}, 1, scheduleHorizonSteps)};
        actionNames = {'reference-full-payload'};
        if positiveNetAddressableSelection.actionEnabled
            selected = ...
                positiveNetAddressableSelection.selectedFormationIds;
            fixedSchedule = repmat( ...
                {selected}, 1, scheduleHorizonSteps);
            schedules{end + 1} = fixedSchedule;
            actionNames{end + 1} = sprintf( ...
                'v97-positive-net-persistent-h%d-%s', ...
                scheduleHorizonSteps, formatIds(selected));
            schedules{end + 1} = fixedSchedule;
            actionNames{end + 1} = sprintf( ...
                'v100-online-positive-net-h%d-%s', ...
                scheduleHorizonSteps, formatIds(selected));
        end
        bankContractVersion = ...
            'online-positive-net-propagation-action-bank-v100-v1';
    case 'propagation-aware-dwell-v101'
        v101 = getPropagationAwareDwellV101Protocol();
        if context.currentTime ~= 72 || scheduleHorizonSteps ~= 6
            error('PropagationAwareDwellV101:UnsupportedAnchor', ...
                'The first V101 probe is frozen at X36 t=72, H=6.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v101.dwellFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v101-propagation-aware-dwell-h6'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v101.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        bankContractVersion = ...
            'propagation-aware-dwell-action-bank-v101-v1';
    case 'shield-broadcast-v102'
        v102 = getShieldBroadcastV102Protocol();
        if context.currentTime ~= 72 || scheduleHorizonSteps ~= 6
            error('ShieldBroadcastV102:UnsupportedAnchor', ...
                'The first V102 probe is frozen at X36 t=72, H=6.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v102.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v102-shield-broadcast-h6'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v102.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        v102Route = buildShieldBroadcastV102RouteSequence( ...
            referenceAdjacency, referenceWeights, referenceDetails, ...
            context.physicalAdjacency, groupIds, ...
            v102.broadcastFormationIdsByTime, struct( ...
                'dominantWeight', v102.dominantWeight, ...
                'residualWeight', v102.residualWeight, ...
                'previousAdjacencyHistory', ...
                    context.previousAdjacencyHistory));
        bankContractVersion = ...
            'shield-broadcast-action-bank-v102-v1';
    case 'matured-handoff-v103'
        v103 = getMaturedHandoffV103Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v103.horizonSteps
            error('MaturedHandoffV103:UnsupportedAnchor', ...
                'The first V103 probe is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v103.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v103-matured-handoff-h8'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v103.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        v103Route = buildShieldBroadcastV102RouteSequence( ...
            referenceAdjacency, referenceWeights, referenceDetails, ...
            context.physicalAdjacency, groupIds, ...
            v103.handoffFormationIdsByTime, struct( ...
                'dominantWeight', v103.dominantWeight, ...
                'residualWeight', v103.residualWeight, ...
                'previousAdjacencyHistory', ...
                    context.previousAdjacencyHistory));
        v103Route.contractVersion = ...
            'matured-handoff-v103-route-sequence-v1';
        bankContractVersion = ...
            'matured-handoff-action-bank-v103-v1';
    case 'receiver-selective-handoff-v104'
        v103 = getMaturedHandoffV103Protocol();
        v104 = getReceiverSelectiveHandoffV104Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v104.horizonSteps
            error('ReceiverSelectiveV104:UnsupportedAnchor', ...
                'The first V104 oracle is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v104.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v104-receiver-selective-handoff-h8'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v104.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        v103Route = buildShieldBroadcastV102RouteSequence( ...
            referenceAdjacency, referenceWeights, referenceDetails, ...
            context.physicalAdjacency, groupIds, ...
            v103.handoffFormationIdsByTime, struct( ...
                'dominantWeight', v103.dominantWeight, ...
                'residualWeight', v103.residualWeight, ...
                'previousAdjacencyHistory', ...
                    context.previousAdjacencyHistory));
        v103Route.contractVersion = ...
            'matured-handoff-v103-route-sequence-v1';
        v104Route = ...
            buildReceiverSelectiveHandoffV104RouteSequence( ...
                referenceAdjacency, referenceWeights, v103Route, ...
                v104.selectedReceiverIdsByTime, ...
                context.physicalAdjacency, groupIds, struct( ...
                    'previousAdjacencyHistory', ...
                        context.previousAdjacencyHistory));
        bankContractVersion = ...
            'receiver-selective-handoff-action-bank-v104-v1';
    case 'protection-only-h8-v105'
        v105 = getProtectionOnlyH8V105Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v105.horizonSteps
            error('ProtectionOnlyV105:UnsupportedAnchor', ...
                'The first V105 attribution is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v105.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v105-protection-only-h8'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v105.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        bankContractVersion = ...
            'protection-only-h8-action-bank-v105-v1';
    case 'protection-release-oracle-v106'
        v106 = getProtectionReleaseOracleV106Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v106.horizonSteps
            error('ProtectionReleaseV106:UnsupportedAnchor', ...
                'The first V106 oracle is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v106.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            'v106-protection-release-oracle-h8'};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v106.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        bankContractVersion = ...
            'protection-release-oracle-action-bank-v106-v1';
    case 'protection-early-release-oracle-v107'
        v107 = getProtectionEarlyReleaseOracleV107Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v107.horizonSteps
            error('ProtectionEarlyReleaseV107:UnsupportedAnchor', ...
                'The first V107 oracle is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v107.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            v107.candidateActionName};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v107.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        bankContractVersion = ...
            'protection-early-release-oracle-action-bank-v107-v1';
    case 'signed-complete-label-exception-v108'
        v108 = getSignedCompleteLabelExceptionV108Protocol();
        if context.currentTime ~= 72 || ...
                scheduleHorizonSteps ~= v108.horizonSteps
            error('SignedCompleteLabelV108:UnsupportedAnchor', ...
                'The first V108 oracle is frozen at X36 t=72, H=8.');
        end
        schedules = { ...
            repmat({[]}, 1, scheduleHorizonSteps), ...
            v108.protectionFormationIdsByTime};
        actionNames = { ...
            'reference-full-payload', ...
            v108.candidateActionName};
        positiveNetAddressableSelection = struct( ...
            'selectedFormationIds', ...
                v108.sourceOnlineFormationIdsByTime{1}, ...
            'actionEnabled', true);
        bankContractVersion = ...
            'signed-complete-label-exception-action-bank-v108-v1';
    otherwise
        error('TrackingAlignedV63:UnknownActionBankVariant', ...
            'The requested X36 schedule-bank variant is not registered.');
end
if signedCompleteLabelBank
    payloadModes = { ...
        'reference-full-payload', ...
        'signed-complete-label-exceptions'};
else
    payloadModes = [ ...
        {'reference-full-payload'}, ...
        repmat({'control-only'}, 1, numel(actionNames) - 1)];
end

actionObjective = zeros(1, numel(actionNames));
actionFormationIds = cell(1, numel(actionNames));
for actionIdx = 1:numel(actionNames)
    actionObjective(actionIdx) = scheduleObjective( ...
        schedules{actionIdx}, groups, scores);
    actionFormationIds{actionIdx} = unique([schedules{actionIdx}{:}], ...
        'stable');
end

bank = struct();
bank.contractVersion = bankContractVersion;
bank.bankVariant = bankVariant;
bank.actionCount = numel(actionNames);
bank.referenceActionIndex = 1;
bank.actionNames = actionNames;
bank.actionPayloadModes = payloadModes;
bank.actionAdjacency = repmat( ...
    logical(referenceAdjacency), 1, 1, bank.actionCount);
bank.actionFusionWeights = repmat( ...
    referenceWeights, 1, 1, bank.actionCount);
bank.actionPosteriorObjective = actionObjective;
bank.actionPosteriorProxyAllowed = true(1, bank.actionCount);
bank.actionWithinReferencePayload = true(1, bank.actionCount);
bank.actionPredictedNetSavingBytes = nan(1, bank.actionCount);
bank.actionFormationIds = actionFormationIds;
bank.formationConditionedTimes = ...
    context.currentTime + (0:(scheduleHorizonSteps - 1));
bank.actionFormationConditionedSchedule = schedules;
if signedCompleteLabelBank
    bank.completeLabelExceptionsByTime = ...
        v108.completeLabelExceptionsByTime;
else
    bank.completeLabelExceptionsByTime = cell(1, 0);
end
bank.positiveSupportThreshold = positiveSupportThreshold;
layeredProtocol = getTrackingAlignedLayeredLabelHeadroomV62Protocol();
bank.highExistenceThreshold = layeredProtocol.highExistenceThreshold;
bank.referenceAdjacency = logical(referenceAdjacency);
bank.referenceFusionWeights = referenceWeights;
bank.referencePolicyDetails = referenceDetails;
bank.v102Route = v102Route;
bank.v103Route = v103Route;
bank.v104Route = v104Route;
bank.routingLeverageSignature = signature;
bank.observationSupportMetrics = support;
bank.rankedFormationIds = rankedFormationIds;
bank.rankedFormationScores = rankedScores;
bank.legacyFormationSchedule = legacySchedule;
bank.riskCoverageTargetFraction = riskCoverageTargetFraction;
bank.riskCoverageAchievedFraction = riskCoverageAchievedFraction;
bank.riskCoverageFormationIds = riskCoverageFormationIds;
bank.networkRiskMetrics = networkRiskMetrics;
bank.networkRiskSelection = networkRiskSelection;
bank.addressableRiskSelection = addressableRiskSelection;
bank.positiveNetAddressableSelection = ...
    positiveNetAddressableSelection;
bank.truthUsed = signedCompleteLabelBank;
bank.futureMeasurementsUsed = signedCompleteLabelBank;
bank.futureOutcomesUsed = signedCompleteLabelBank;
end

function value = scheduleObjective(schedule, groups, scores)
value = 0;
for stepIdx = 1:numel(schedule)
    formationIds = reshape(schedule{stepIdx}, 1, []);
    for formationId = formationIds
        idx = find(groups == formationId, 1);
        if isempty(idx) || ~isfinite(scores(idx))
            error('TrackingAlignedV63:InvalidFormationSchedule', ...
                'A scheduled formation lacks an observable score.');
        end
        value = value + scores(idx);
    end
end
end

function value = formatIds(ids)
tokens = arrayfun(@(id) sprintf('f%d', id), ...
    reshape(ids, 1, []), 'UniformOutput', false);
value = strjoin(tokens, '-');
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
