function [adjacency, details] = ...
    buildFormationB4V45FixedRuntimeArm(context, armId)
% BUILDFORMATIONB4V45FIXEDRUNTIMEARM Select one frozen V45 route page.
%
% Matrices use receiver rows and sender columns.  Only a current observable
% v3 context is accepted; truth, future link pages and realized delivery
% uniforms must be absent before the V43/V44 builders are called.

timerId = tic;
validateRuntimeContext(context);
if ~ischar(armId) || ~isrow(armId)
    error('FormationB4V45:InvalidArm', ...
        'The V45 runtime arm identifier is malformed.');
end

dominantWeight = 0.70;
referenceResidualWeight = 0.05;
activeResidualWeight = 0.20;
period = 4;
currentAbsolutePhase = mod(context.currentTime - 1, period) + 1;

switch armId
    case 'v43-reference-a70-e05'
        armOrdinal = 1;
        mode = 'formation-b4-v45-v43-reference-runtime';
        phasePattern = 'every-step';
        [adjacency, baseDetails] = ...
            selectIndexEquivariantFormationBackbonePolicy( ...
                context, struct( ...
                    'dominantWeight', dominantWeight, ...
                    'residualWeight', referenceResidualWeight));
        fusionWeights = baseDetails.fusionWeightMatrix;
        referenceAdjacency = logical(adjacency);
        referenceMessageCount = nnz(referenceAdjacency);
        messageCountsByPhase = repmat( ...
            referenceMessageCount, 1, period);
        messagesPerPeriod = period * referenceMessageCount;
        messageSavingCountPerPeriod = 0;
        messageSavingFractionPerPeriod = 0;
        residualMassMatchedToReference = true;
        baseContractVersion = baseDetails.contractVersion;
        baseMode = baseDetails.mode;
    case {'v44-sync-all-b4-e20-mc', ...
            'v44-formation-all-b4-e20-mc'}
        if strcmp(armId, 'v44-sync-all-b4-e20-mc')
            armOrdinal = 2;
            mode = 'formation-b4-v45-synchronized-b4-runtime';
            phasePattern = 'synchronized';
        else
            armOrdinal = 3;
            mode = 'formation-b4-v45-formation-staggered-b4-runtime';
            phasePattern = 'formation-staggered';
        end
        [adjacencySequence, fusionWeightSequence, baseDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                context, struct( ...
                    'period', period, ...
                    'dutyLayer', 'all', ...
                    'phasePattern', phasePattern, ...
                    'dominantWeight', dominantWeight, ...
                    'referenceResidualWeight', ...
                        referenceResidualWeight, ...
                    'activeResidualWeight', activeResidualWeight));
        if baseDetails.currentAbsolutePhase ~= currentAbsolutePhase
            error('FormationB4V45:InvalidAction', ...
                'The V44 schedule disagrees with absolute runtime time.');
        end
        adjacency = logical(adjacencySequence( ...
            :, :, currentAbsolutePhase));
        fusionWeights = fusionWeightSequence( ...
            :, :, currentAbsolutePhase);
        referenceAdjacency = logical(baseDetails.referenceAdjacency);
        referenceMessageCount = ...
            baseDetails.referenceMessageCountPerStep;
        messageCountsByPhase = baseDetails.messageCountsByPhase;
        messagesPerPeriod = baseDetails.messagesPerPeriod;
        messageSavingCountPerPeriod = ...
            baseDetails.messageSavingCountPerPeriod;
        messageSavingFractionPerPeriod = ...
            baseDetails.messageSavingFractionPerPeriod;
        residualMassMatchedToReference = ...
            baseDetails.residualMassMatchedToReference;
        baseContractVersion = baseDetails.contractVersion;
        baseMode = baseDetails.mode;
    otherwise
        error('FormationB4V45:InvalidArm', ...
            'Only the three frozen V45 arm identifiers are allowed.');
end

validateRuntimeAction(context, adjacency, fusionWeights, ...
    referenceAdjacency, referenceMessageCount, ...
    messageCountsByPhase, messagesPerPeriod, ...
    messageSavingFractionPerPeriod, armOrdinal, ...
    currentAbsolutePhase);

contract = context.observableInputContract;
details = baseDetails;
details.baseContractVersion = baseContractVersion;
details.baseMode = baseMode;
details.contractVersion = ...
    'formation-b4-v45-fixed-runtime-policy-v1';
details.mode = mode;
details.armId = armId;
details.armOrdinal = armOrdinal;
details.actionName = armId;
details.currentTime = context.currentTime;
details.period = period;
details.currentAbsolutePhase = currentAbsolutePhase;
details.absolutePhaseOrigin = 'simulation-time-one';
details.phaseSelectionUsesCurrentTimeOnly = true;
details.phasePattern = phasePattern;
details.dutyLayer = 'all';
details.dominantWeight = dominantWeight;
details.referenceResidualWeight = referenceResidualWeight;
details.activeResidualWeight = activeResidualWeight;
details.fusionWeightMatrix = fusionWeights;
details.referenceAdjacency = referenceAdjacency;
details.currentAdjacencyIsReferenceSubset = ...
    all(~adjacency(:) | referenceAdjacency(:));
details.currentMessageCount = nnz(adjacency);
details.selectedMessageCount = details.currentMessageCount;
details.referenceMessageCount = referenceMessageCount;
details.referenceMessageCountPerStep = referenceMessageCount;
details.currentToReferenceMessageRatio = ...
    details.currentMessageCount / referenceMessageCount;
details.messageCountsByPhase = messageCountsByPhase;
details.referenceMessagesPerPeriod = ...
    period * referenceMessageCount;
details.messagesPerPeriod = messagesPerPeriod;
details.messageSavingCountPerPeriod = ...
    messageSavingCountPerPeriod;
details.messageSavingFractionPerPeriod = ...
    messageSavingFractionPerPeriod;
details.residualMassMatchedToReference = ...
    residualMassMatchedToReference;
details.runtimeRuleFrozen = true;
details.policyOptionsAccepted = false;
details.observableContextOnly = true;
details.observableInputContractVersion = contract.contractVersion;
details.directedTopologyRuntimeRequired = true;
details.topologyDirectedEnabled = ...
    context.triggerConfig.topologyDirectedEnabled;
details.topologyDirectedMessageBudget = ...
    context.triggerConfig.topologyDirectedMessageBudget;
details.sensorPhysicalUids = context.sensorPhysicalUids;
details.formationPhysicalUidsBySensor = ...
    context.formationPhysicalUidsBySensor;
details.physicalIdentityRegistryCanonicalSha256 = ...
    context.physicalIdentityRegistryCanonicalSha256;
details.targetTruthAbsent = contract.targetTruthAbsent;
details.futurePDropPagesAbsent = contract.futurePDropPagesAbsent;
details.linkUniformsAbsent = contract.linkUniformsAbsent;
details.posteriorUsed = false;
details.currentPosteriorUsed = false;
details.currentLinkReliabilityUsed = true;
details.currentPhysicalActionSetUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.measurementUsed = false;
details.futureMeasurementUsed = false;
details.futureOutcomeUsed = false;
details.realizedDeliveryUniformsUsed = false;
details.trackingOutcomeScored = false;
details.standaloneAttestationAuthority = false;
details.attestationAuthority = ...
    'filter-runtime-resolved-observable-context-only';
details.selectionSeconds = toc(timerId);
end

function validateRuntimeContext(context)
required = {'localPosteriorBySensor', 'currentTime', ...
    'physicalAdjacency', 'sensorPhysicalUids', ...
    'formationPhysicalUidsBySensor', ...
    'physicalIdentityRegistryCanonicalSha256', ...
    'triggerConfig', 'observableInputContract'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ...
        ~isa(context.currentTime, 'double') || ...
        ~isscalar(context.currentTime) || ...
        ~isfinite(context.currentTime) || ...
        context.currentTime < 1 || ...
        context.currentTime ~= round(context.currentTime)
    error('FormationB4V45:InvalidContext', ...
        'The V45 runtime context or absolute time is invalid.');
end

nodeCount = numel(context.localPosteriorBySensor);
sensorUids = reshape(context.sensorPhysicalUids, 1, []);
formationUids = reshape( ...
    context.formationPhysicalUidsBySensor, 1, []);
registrySha = context.physicalIdentityRegistryCanonicalSha256;
if nodeCount < 1 || ...
        ~isa(sensorUids, 'double') || ...
        numel(sensorUids) ~= nodeCount || ...
        any(~isfinite(sensorUids)) || ...
        any(sensorUids < 1) || ...
        any(sensorUids ~= round(sensorUids)) || ...
        numel(unique(sensorUids)) ~= nodeCount || ...
        ~isa(formationUids, 'double') || ...
        numel(formationUids) ~= nodeCount || ...
        any(~isfinite(formationUids)) || ...
        any(formationUids < 1) || ...
        any(formationUids ~= round(formationUids)) || ...
        ~ischar(registrySha) || ~isrow(registrySha) || ...
        numel(registrySha) ~= 64 || ...
        any(~ismember(lower(registrySha), '0123456789abcdef')) || ...
        ~isequal(size(context.physicalAdjacency), ...
            [nodeCount, nodeCount])
    error('FormationB4V45:InvalidContext', ...
        'The V45 physical-identity runtime context is invalid.');
end

triggerConfig = context.triggerConfig;
if ~isstruct(triggerConfig) || ~isscalar(triggerConfig) || ...
        ~isfield(triggerConfig, 'topologyDirectedEnabled') || ...
        ~isfield(triggerConfig, 'topologyDirectedMessageBudget') || ...
        ~islogical(triggerConfig.topologyDirectedEnabled) || ...
        ~isscalar(triggerConfig.topologyDirectedEnabled) || ...
        ~triggerConfig.topologyDirectedEnabled || ...
        ~isa(triggerConfig.topologyDirectedMessageBudget, 'double') || ...
        ~isscalar(triggerConfig.topologyDirectedMessageBudget) || ...
        ~isfinite(triggerConfig.topologyDirectedMessageBudget) || ...
        triggerConfig.topologyDirectedMessageBudget ~= 2 * nodeCount
    error('FormationB4V45:InvalidDirectedRuntime', ...
        ['V45 requires directed topology execution with an exact ', ...
         'two-input-per-receiver message budget.']);
end

contract = context.observableInputContract;
requiredContract = {'contractVersion', 'enforced', 'passed', ...
    'currentTime', 'targetTruthAbsent', 'linkUniformsAbsent', ...
    'futurePDropPagesAbsent', 'physicalIdentityPresent', ...
    'physicalIdentitySchemaRestricted', ...
    'physicalIdentityRegistryCanonicalSha256', ...
    'directedTopologyRuntimeSemanticsPresent', ...
    'topologyDirectedEnabled', ...
    'topologyDirectedMessageBudget'};
if ~isstruct(contract) || ~isscalar(contract) || ...
        ~all(isfield(contract, requiredContract)) || ...
        ~strcmp(contract.contractVersion, ...
            'topology-policy-observable-input-v3-physical-uid') || ...
        ~isTrue(contract.enforced) || ~isTrue(contract.passed) || ...
        contract.currentTime ~= context.currentTime || ...
        ~isTrue(contract.targetTruthAbsent) || ...
        ~isTrue(contract.linkUniformsAbsent) || ...
        ~isTrue(contract.futurePDropPagesAbsent) || ...
        ~isTrue(contract.physicalIdentityPresent) || ...
        ~isTrue(contract.physicalIdentitySchemaRestricted) || ...
        ~isTrue(contract.directedTopologyRuntimeSemanticsPresent) || ...
        ~isTrue(contract.topologyDirectedEnabled) || ...
        contract.topologyDirectedMessageBudget ~= 2 * nodeCount || ...
        ~strcmp(contract.physicalIdentityRegistryCanonicalSha256, ...
            context.physicalIdentityRegistryCanonicalSha256)
    error('FormationB4V45:InvalidObservableBoundary', ...
        ['V45 requires the passed observable v3 contract with ', ...
         'truth, future link pages and delivery uniforms absent.']);
end

observableData = rmfield(context, 'observableInputContract');
if containsForbiddenRuntimeField(observableData)
    error('FormationB4V45:InvalidObservableBoundary', ...
        'A forbidden truth, future or delivery-uniform input is present.');
end
end

function validateRuntimeAction(context, adjacency, weights, ...
        referenceAdjacency, referenceMessageCount, ...
        messageCountsByPhase, messagesPerPeriod, ...
        messageSavingFractionPerPeriod, armOrdinal, ...
        currentAbsolutePhase)
nodeCount = numel(context.localPosteriorBySensor);
physical = logical(context.physicalAdjacency);
weightSupport = adjacency | logical(eye(nodeCount));
positiveOffDiagonalSupport = weights > 1e-12;
positiveOffDiagonalSupport(1:nodeCount+1:end) = false;
expectedCounts = reshape(messageCountsByPhase, 1, []);
if ~islogical(adjacency) || ...
        ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        any(diag(adjacency)) || ...
        any(adjacency(:) & ~physical(:)) || ...
        any(adjacency(:) & ~referenceAdjacency(:)) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(~isfinite(weights(:))) || ...
        any(weights(:) < -1e-12) || ...
        any(weights(:) > 1 + 1e-12) || ...
        any(weights(:) > 1e-12 & ~weightSupport(:)) || ...
        ~isequal(positiveOffDiagonalSupport, adjacency) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        referenceMessageCount ~= nnz(referenceAdjacency) || ...
        numel(expectedCounts) ~= 4 || ...
        any(~isfinite(expectedCounts)) || ...
        any(expectedCounts < nodeCount) || ...
        nnz(adjacency) ~= expectedCounts(currentAbsolutePhase) || ...
        messagesPerPeriod ~= sum(expectedCounts)
    error('FormationB4V45:InvalidAction', ...
        'The selected V45 runtime page violates a hard route invariant.');
end
if armOrdinal == 1
    validArm = isequal(adjacency, referenceAdjacency) && ...
        all(expectedCounts == referenceMessageCount) && ...
        messagesPerPeriod == 4 * referenceMessageCount && ...
        messageSavingFractionPerPeriod == 0;
else
    validArm = referenceMessageCount == 2 * nodeCount && ...
        messagesPerPeriod == 5 * nodeCount && ...
        abs(messageSavingFractionPerPeriod - 3 / 8) <= 1e-12;
end
if ~validArm
    error('FormationB4V45:InvalidAction', ...
        'The selected V45 runtime arm drifted from its frozen rule.');
end
end

function result = containsForbiddenRuntimeField(value)
result = false;
if iscell(value)
    for valueIdx = 1:numel(value)
        if containsForbiddenRuntimeField(value{valueIdx})
            result = true;
            return;
        end
    end
    return;
end
if ~isstruct(value)
    return;
end
names = fieldnames(value);
for valueIdx = 1:numel(value)
    for fieldIdx = 1:numel(names)
        name = names{fieldIdx};
        lowerName = lower(name);
        forbiddenTokens = { ...
            'truth', 'oracle', 'uniform', 'measurement', ...
            'trajectory', 'future', 'outcome'};
        forbidden = false;
        for tokenIdx = 1:numel(forbiddenTokens)
            forbidden = forbidden || ~isempty(strfind( ...
                lowerName, forbiddenTokens{tokenIdx})); %#ok<STREMP>
        end
        if forbidden || containsForbiddenRuntimeField( ...
                value(valueIdx).(name))
            result = true;
            return;
        end
    end
end
end

function result = isTrue(value)
result = islogical(value) && isscalar(value) && value;
end
