function config = buildPartialLabelFusionSemanticsV90TriggerConfig( ...
        armId, nodeCount, receiverMode)
% BUILDPARTIALLABELFUSIONSEMANTICSV90TRIGGERCONFIG One-switch receiver arm.

protocol = getPartialLabelFusionSemanticsV90Protocol();
if nargin ~= 3 || ~ischar(receiverMode) || ~isrow(receiverMode) || ...
        ~any(strcmp(receiverMode, protocol.receiverModes))
    error('PartialLabelFusionV90:InvalidReceiverMode', ...
        'V90 requires one registered missing-label receiver mode.');
end
config = buildRepeatedMultiGatewayHandoverV89TriggerConfig( ...
    armId, nodeCount);
config.missingLabelFusionMode = receiverMode;
config.fovAwareMissingLabelMinimumFovFraction = ...
    protocol.minimumFovFraction;
config.fovAwareMissingLabelMinimumExpectedDetectionProbability = ...
    protocol.minimumExpectedDetectionProbability;
config.fovAwareMissingLabelIgnoreStaleAbsence = ...
    protocol.ignoreStaleAbsence;
end
