function context = ...
        buildOnlinePositiveNetFormationReleaseV191ExecutionContext( ...
            presetName, seed, currentTime, actionName, scheduleEnabled, ...
            onlineReselectionEnabled, releasePlan)
% BUILDONLINEPOSITIVENETFORMATIONRELEASEV191EXECUTIONCONTEXT Dev scope.

base = buildOnlinePositiveNetAddressablePayloadV99ExecutionContext( ...
    presetName, seed, currentTime, actionName, scheduleEnabled, ...
    onlineReselectionEnabled);
protocol = getOnlinePositiveNetFormationReleaseV191Protocol();
if ~isstruct(releasePlan) || ~isscalar(releasePlan)
    error('OnlinePositiveNetReleaseV191:InvalidExecutionContext', ...
        'The release plan must be a scalar structure.');
end
context = base;
context.contractVersion = ...
    'online-positive-net-formation-release-v191-context-v1';
context.capability = ...
    'online-positive-net-formation-release-v191-development';
context.action = ...
    'filter-online-positive-net-formation-release-v191-development';
context.protocolId = protocol.id;
context.onlinePositiveNetFormationReleasePlan = releasePlan;
end
