function context = ...
    buildAddressableRiskAdaptivePayloadV96ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDADDRESSABLERISKADAPTIVEPAYLOADV96EXECUTIONCONTEXT Development scope.

protocol = getAddressableRiskAdaptivePayloadV96Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('AddressableRiskV96:InvalidExecutionContext', ...
        'The V96 execution context input is invalid.');
end

context = struct();
context.contractVersion = ...
    'addressable-risk-adaptive-payload-v96-context-v1';
context.capability = ...
    'addressable-risk-adaptive-payload-v96-development';
context.action = ...
    'filter-addressable-risk-adaptive-payload-v96-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.developmentEvidenceOnly = true;
end
