function control = buildFormationRetentionDebtControl(context, options)
% BUILDFORMATIONRETENTIONDEBTCONTROL Causal v30 hysteretic controller.
%
% Each formation is probed independently by withholding its registered
% cross-formation residual input for one round. The resulting expected
% cardinality protection, normalized by reference expected cardinality,
% is the formation's retention debt. Edges turn off above the registered
% on-threshold and remain off until debt falls below the lower off-threshold.
% A joint subset is then projected through the exact v29 existence and
% rolling-B3 constraints. No target truth or future outcome is used.

if nargin < 2 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('RetentionDebt:InvalidOptions', ...
        'The frozen v30 controller does not accept option overrides.');
end
protocol = getFormationIsolateReconnectProbeProtocol();
nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || ...
        formationCount > protocol.maximumFormationCount || ...
        ~isfield(context, 'previousAdjacencyHistory') || ...
        size(context.previousAdjacencyHistory, 1) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 2) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 3) < 1
    error('RetentionDebt:InvalidControlContext', ...
        'Retention-debt control context is invalid.');
end

policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.residualWeight);
[referenceAdjacency, referencePolicyDetails] = ...
    selectTemporalCrossEdgeSuspensionPolicy( ...
        context, zeros(1, 0), policyOptions);
referenceWeights = referencePolicyDetails.fusionWeightMatrix;
referenceScore = scoreRoute( ...
    context, referenceAdjacency, referenceWeights, ...
    [], groupIds, protocol);
referenceDistributions = ...
    referenceScore.networkDetails.receiverDistributions;
referenceExpectedCardinality = ...
    referenceScore.retentionDetails.expectedReferenceCardinality;
if ~referenceScore.safe
    error('RetentionDebt:InvalidReference', ...
        'The registered reference action failed its own safety gate.');
end

previouslySuspended = detectPreviousSuspensions( ...
    context, groupIds, groups);
debtThresholdByFormation = ...
    protocol.retentionDebtOnFraction * ones(1, formationCount);
debtThresholdByFormation(previouslySuspended) = ...
    protocol.retentionDebtOffFraction;
formationDebtFraction = nan(1, formationCount);
referenceFormationExpectedCardinality = ...
    nan(1, formationCount);
singleSafe = false(1, formationCount);
singleAvailable = false(1, formationCount);
singleScores = cell(1, formationCount);
singleFailureIdentifier = repmat({''}, 1, formationCount);
singleFailureMessage = repmat({''}, 1, formationCount);
for formationIdx = 1:formationCount
    formationId = groups(formationIdx);
    try
        [adjacency, details] = ...
            selectTemporalCrossEdgeSuspensionPolicy( ...
                context, formationId, policyOptions);
        score = scoreRoute( ...
            context, adjacency, details.fusionWeightMatrix, ...
            referenceDistributions, groupIds, protocol);
        score.policyDetails = details;
        singleScores{formationIdx} = score;
        singleAvailable(formationIdx) = true;
        singleSafe(formationIdx) = score.safe && ...
            all(details.rollingB3SensorPass) && ...
            all(details.rollingB3FormationPass);
        members = groupIds == formationId;
        referenceFormationCardinality = mean( ...
            referenceExpectedCardinality(members));
        referenceFormationExpectedCardinality(formationIdx) = ...
            referenceFormationCardinality;
        formationDebtFraction(formationIdx) = ...
            score.retentionDetails. ...
                formationMeanCardinalityChange(formationIdx) / max( ...
                    referenceFormationCardinality, 1);
    catch errorInfo
        if ~isExpectedUnavailable(errorInfo)
            rethrow(errorInfo);
        end
        singleFailureIdentifier{formationIdx} = ...
            getErrorField(errorInfo, 'identifier');
        singleFailureMessage{formationIdx} = ...
            getErrorField(errorInfo, 'message');
    end
end

cardinalityEvidenceMask = ...
    referenceFormationExpectedCardinality >= ...
        protocol.minimumReferenceFormationExpectedCardinality;
requestedMask = singleAvailable & singleSafe & ...
    cardinalityEvidenceMask & ...
    formationDebtFraction >= debtThresholdByFormation - 1e-12;
requestedFormationIds = groups(requestedMask);
selectedFormationIds = requestedFormationIds;
projectionRemovalOrder = zeros(1, 0);
selectedAdjacency = referenceAdjacency;
selectedWeights = referenceWeights;
selectedPolicyDetails = referencePolicyDetails;
selectedScore = referenceScore;
selectedAvailable = true;
selectedSafe = true;
jointEvaluationCount = 0;
while ~isempty(selectedFormationIds)
    jointEvaluationCount = jointEvaluationCount + 1;
    try
        [candidateAdjacency, candidateDetails] = ...
            selectTemporalCrossEdgeSuspensionPolicy( ...
                context, selectedFormationIds, policyOptions);
        candidateScore = scoreRoute( ...
            context, candidateAdjacency, ...
            candidateDetails.fusionWeightMatrix, ...
            referenceDistributions, groupIds, protocol);
        candidateSafe = candidateScore.safe && ...
            all(candidateDetails.rollingB3SensorPass) && ...
            all(candidateDetails.rollingB3FormationPass);
        if candidateSafe
            selectedAdjacency = candidateAdjacency;
            selectedWeights = candidateDetails.fusionWeightMatrix;
            selectedPolicyDetails = candidateDetails;
            selectedScore = candidateScore;
            selectedAvailable = true;
            selectedSafe = true;
            break;
        end
        selectedSafe = false;
    catch errorInfo
        if ~isExpectedUnavailable(errorInfo)
            rethrow(errorInfo);
        end
        selectedAvailable = false;
        selectedSafe = false;
        candidateSafe = false;
    end
    debtIndices = zeros(1, numel(selectedFormationIds));
    for selectedIdx = 1:numel(selectedFormationIds)
        debtIndices(selectedIdx) = find( ...
            groups == selectedFormationIds(selectedIdx), 1);
    end
    [~, removeLocalIdx] = min( ...
        formationDebtFraction(debtIndices));
    projectionRemovalOrder(end + 1) = ...
        selectedFormationIds(removeLocalIdx); %#ok<AGROW>
    selectedFormationIds(removeLocalIdx) = [];
end
if isempty(selectedFormationIds)
    selectedAdjacency = referenceAdjacency;
    selectedWeights = referenceWeights;
    selectedPolicyDetails = referencePolicyDetails;
    selectedScore = referenceScore;
    selectedAvailable = true;
    selectedSafe = true;
end

selectedMessageCount = nnz(selectedAdjacency);
referenceMessageCount = nnz(referenceAdjacency);
selectedWeightSupport = ...
    selectedAdjacency | logical(eye(nodeCount));
if ~selectedAvailable || ~selectedSafe || ...
        any(selectedAdjacency(:) & ...
            ~logical(context.physicalAdjacency(:))) || ...
        selectedMessageCount > referenceMessageCount || ...
        any(~isfinite(selectedWeights(:))) || ...
        any(selectedWeights(:) < -1e-12) || ...
        any(selectedWeights(:) > 1e-12 & ...
            ~selectedWeightSupport(:)) || ...
        any(abs(sum(selectedWeights, 2) - 1) > 1e-12)
    error('RetentionDebt:InvalidSelectedAction', ...
        'Selected retention-debt action violates a hard invariant.');
end

control = struct();
control.contractVersion = ...
    'formation-retention-debt-control-v1';
control.protocolId = protocol.id;
control.nodeCount = nodeCount;
control.formationCount = formationCount;
control.groupIds = groupIds;
control.groups = groups;
control.referenceAdjacency = referenceAdjacency;
control.referenceFusionWeights = referenceWeights;
control.referencePolicyDetails = referencePolicyDetails;
control.referenceScore = referenceScore;
control.previouslySuspendedMask = previouslySuspended;
control.debtThresholdByFormation = ...
    debtThresholdByFormation;
control.formationRetentionDebtFraction = ...
    formationDebtFraction;
control.referenceFormationExpectedCardinality = ...
    referenceFormationExpectedCardinality;
control.cardinalityEvidenceMask = cardinalityEvidenceMask;
control.singleActionAvailableMask = singleAvailable;
control.singleActionSafetyMask = singleSafe;
control.singleActionScores = singleScores;
control.singleFailureIdentifier = singleFailureIdentifier;
control.singleFailureMessage = singleFailureMessage;
control.requestedFormationIds = requestedFormationIds;
control.selectedFormationIds = selectedFormationIds;
control.projectionRemovalOrder = projectionRemovalOrder;
control.selectedAdjacency = selectedAdjacency;
control.selectedFusionWeights = selectedWeights;
control.selectedPolicyDetails = selectedPolicyDetails;
control.selectedScore = selectedScore;
control.selectedActionName = buildActionName( ...
    selectedFormationIds);
control.referenceFallbackUsed = isempty(selectedFormationIds);
control.referenceMessageCount = referenceMessageCount;
control.selectedMessageCount = selectedMessageCount;
control.messageSavingCount = ...
    referenceMessageCount - selectedMessageCount;
control.evaluatedRouteCount = 1 + formationCount + ...
    jointEvaluationCount;
if control.evaluatedRouteCount > ...
        protocol.maximumControlRouteEvaluations
    error('RetentionDebt:EvaluationBudgetExceeded', ...
        'The retention-debt projection exceeded its frozen budget.');
end
control.safeSingleActionCount = nnz(singleSafe);
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.hysteresisEnabled = ...
    protocol.retentionDebtOffFraction < ...
        protocol.retentionDebtOnFraction;
control.selectedRollingB3SensorPass = ...
    selectedPolicyDetails.rollingB3SensorPass;
control.selectedRollingB3FormationPass = ...
    selectedPolicyDetails.rollingB3FormationPass;
control.truthUsed = false;
control.futureOutcomeUsed = false;
control.openedDevelopmentEvidenceOnly = true;
control.validationClaimAllowed = false;
end

function score = scoreRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, protocol)
enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, enumerationOptions);
if isempty(referenceDistributions)
    referenceDistributions = networkDetails.receiverDistributions;
end
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        protocol.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        protocol.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        protocol.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        protocol.retentionReceiverTailWeight);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, ...
        groupIds, retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = ...
    retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= protocol. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= protocol. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= protocol. ...
        maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'retentionRisk', retentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function suspended = detectPreviousSuspensions( ...
        context, groupIds, groups)
previous = logical(context.previousAdjacencyHistory(:, :, end));
suspended = false(1, numel(groups));
for formationIdx = 1:numel(groups)
    receivers = groupIds == groups(formationIdx);
    outsideSenders = groupIds ~= groups(formationIdx);
    suspended(formationIdx) = ...
        ~any(any(previous(receivers, outsideSenders)));
end
end

function name = buildActionName(formationIds)
if isempty(formationIds)
    name = 'reference';
    return;
end
text = sprintf('f%d-', formationIds);
name = ['retention-debt-suspend-', text(1:end-1)];
end

function value = isExpectedUnavailable(errorInfo)
identifier = getErrorField(errorInfo, 'identifier');
value = strcmp(identifier, 'TemporalSuspension:Infeasible') || ...
    strcmp(identifier, 'TemporalSuspension:InvalidCandidate');
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
if isempty(value)
    value = '';
end
end
