function context = ...
    buildFormationB4V53PairedTrackingDevelopmentContext( ...
        presetName, seed, armId)
% BUILDFORMATIONB4V53PAIREDTRACKINGDEVELOPMENTCONTEXT Experiment context.

protocol = getFormationB4V53RuntimeProtocol();
allowedPresets = { ...
    'm24-formation-fov', ...
    'm24-formation-fov-convoy', ...
    'm24-formation-fov-relay', ...
    'm24-formation-fov-crossing', ...
    'm24-formation-fov-merge-split', ...
    'm24-formation-fov-curved-corridor', ...
    'x36-formation-fov', ...
    'x36-formation-fov-convoy', ...
    'x36-formation-fov-relay', ...
    'x36-formation-fov-crossing', ...
    'x36-formation-fov-merge-split', ...
    'x36-formation-fov-curved-corridor'};
if ~ischar(presetName) || ...
        ~any(strcmp(presetName, allowedPresets)) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~ischar(armId) || ~any(strcmp(armId, protocol.primaryArms))
    error('FormationB4V53Tracking:InvalidContextInput', ...
        'A registered M24/X36 preset, seed and V46/V53 arm are required.');
end
context = struct();
context.contractVersion = ...
    'formation-b4-v53-paired-tracking-development-context-v1';
context.capability = 'paired-tracking-development-v53';
context.action = 'filter-paired-tracking-development-v53';
context.presetName = presetName;
context.seed = seed;
context.armId = armId;
context.developmentEvidenceOnly = true;
end
