function bank = buildConflictAwareFormationMixingActionBank( ...
        context, options)
% BUILDCONFLICTAWAREFORMATIONMIXINGACTIONBANK Safe v28 action bank.
%
% Structural candidates scale quadratically in the formation count.  Each
% candidate is scored using current-posterior one-round delivery outcomes,
% then projected through frozen reference-retention and disagreement
% constraints.  Unsafe candidates remain in the diagnostic bank but are
% not executable tracking actions.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getFormationConflictAwareMixingProbeProtocol();
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
nodeCount = numel(context.localPosteriorBySensor);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
pairActionModes = getField(options, ...
    'pairActionModes', protocol.pairActionModes);
includeDampActions = logical(getField(options, ...
    'includeReferenceDampActions', ...
    protocol.includeReferenceDampActions));
scorePosteriorSafety = logical(getField(options, ...
    'scorePosteriorSafety', true));
maximumActionCount = round(getField(options, ...
    'maximumActionCount', protocol.maximumActionCount));
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || ~iscell(pairActionModes) || ...
        isempty(pairActionModes) || maximumActionCount < 1
    error('ConflictMixing:InvalidBankContract', ...
        'Conflict-aware action-bank inputs are invalid.');
end

specifications = buildSpecifications( ...
    groups, pairActionModes, includeDampActions);
if numel(specifications) > maximumActionCount
    error('ConflictMixing:InvalidBankContract', ...
        'Conflict-aware action bank exceeds its scale limit.');
end
policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.residualWeight, ...
    'pairResidualWeight', protocol.pairResidualWeight, ...
    'dampedReferenceWeight', protocol.dampedReferenceWeight);

actionAdjacency = false(nodeCount, nodeCount, 0);
actionFusionWeights = zeros(nodeCount, nodeCount, 0);
actionFormationMixing = zeros(formationCount, formationCount, 0);
actionNames = cell(1, 0);
actionModes = cell(1, 0);
actionFormationIds = cell(1, 0);
actionMessageCounts = zeros(1, 0);
actionCrossMessageCounts = zeros(1, 0);
actionCrossTrust = zeros(1, 0);
actionMixingGap = zeros(1, 0);
actionDetails = cell(1, 0);
attempts = repmat(emptyAttempt(), 1, 0);
keys = cell(1, 0);
for specificationIdx = 1:numel(specifications)
    specification = specifications(specificationIdx);
    attempt = emptyAttempt();
    attempt.specificationIndex = specificationIdx;
    attempt.actionName = specification.name;
    attempt.actionMode = specification.action.mode;
    attempt.actionFormationIds = actionFormationIdsFromSpec( ...
        specification.action);
    try
        [adjacency, details] = ...
            selectConflictAwareFormationMixingPolicy( ...
                context, specification.action, policyOptions);
        if details.projectionFallbackUsed || ...
                ~details.messageCountParityWithReference || ...
                ~details.combinedSensorStrongConnected || ...
                ~details.formationStrongConnected || ...
                details.truthUsed || details.futureOutcomeUsed
            error('ConflictMixing:InvalidCandidate', ...
                'Conflict-aware candidate violated a hard invariant.');
        end
        key = [sprintf('%d,', adjacency(:)), '|', ...
            sprintf('%.17g,', details.fusionWeightMatrix(:))];
        duplicateIdx = find(strcmp(keys, key), 1);
        if ~isempty(duplicateIdx)
            attempt.status = 'duplicate';
            attempt.actionIndex = duplicateIdx;
            attempts(end + 1) = attempt; %#ok<AGROW>
            continue;
        end
        actionIdx = size(actionAdjacency, 3) + 1;
        actionAdjacency(:, :, actionIdx) = logical(adjacency);
        actionFusionWeights(:, :, actionIdx) = ...
            details.fusionWeightMatrix;
        actionFormationMixing(:, :, actionIdx) = ...
            details.formationMixingMatrix;
        actionNames{actionIdx} = specification.name;
        actionModes{actionIdx} = details.actionMode;
        actionFormationIds{actionIdx} = ...
            details.actionFormationIds;
        actionMessageCounts(actionIdx) = nnz(adjacency);
        actionCrossMessageCounts(actionIdx) = ...
            details.crossFormationMessageCount;
        actionCrossTrust(actionIdx) = ...
            details.candidateCrossResidualTrust;
        actionMixingGap(actionIdx) = ...
            details.formationMixingSpectralGapProxy;
        actionDetails{actionIdx} = details;
        keys{actionIdx} = key;
        attempt.status = 'accepted';
        attempt.actionIndex = actionIdx;
    catch errorInfo
        if ~strcmp(getErrorField(errorInfo, 'identifier'), ...
                'ConflictMixing:Infeasible')
            rethrow(errorInfo);
        end
        attempt.status = 'unavailable';
        attempt.failureIdentifier = ...
            getErrorField(errorInfo, 'identifier');
        attempt.failureMessage = ...
            getErrorField(errorInfo, 'message');
    end
    attempts(end + 1) = attempt; %#ok<AGROW>
end

actionCount = size(actionAdjacency, 3);
if actionCount < 1 || ~strcmp(actionModes{1}, 'reference') || ...
        any(actionMessageCounts ~= actionMessageCounts(1)) || ...
        actionCount > maximumActionCount
    error('ConflictMixing:InvalidBankContract', ...
        'Conflict-aware bank failed its global structural contract.');
end

networkDisagreementRisk = nan(1, actionCount);
networkDisagreementDetails = cell(1, actionCount);
retentionRisk = nan(1, actionCount);
retentionDetails = cell(1, actionCount);
minimumFormationCardinalityChange = nan(1, actionCount);
minimumReceiverCardinalityChange = nan(1, actionCount);
minimumSupportedLabelRetentionRatio = nan(1, actionCount);
decisionThresholdCrossingCount = nan(1, actionCount);
maximumExistenceDrift = nan(1, actionCount);
posteriorSafetyMask = false(1, actionCount);
if scorePosteriorSafety
    enumerationOptions = struct( ...
        'maximumIncomingCount', ...
            protocol.maximumIncomingCountForOutcomeEnumeration);
    for actionIdx = 1:actionCount
        [networkDisagreementRisk(actionIdx), ...
            networkDisagreementDetails{actionIdx}] = ...
                computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
                    context, actionAdjacency(:, :, actionIdx), ...
                    actionFusionWeights(:, :, actionIdx), ...
                    enumerationOptions);
    end
    referenceDistributions = networkDisagreementDetails{1}. ...
        receiverDistributions;
    retentionOptions = struct( ...
        'referenceSupportThreshold', ...
            protocol.referenceSupportThreshold, ...
        'decisionExistenceThreshold', ...
            protocol.decisionExistenceThreshold, ...
        'receiverTailFraction', ...
            protocol.retentionReceiverTailFraction, ...
        'receiverTailWeight', ...
            protocol.retentionReceiverTailWeight);
    for actionIdx = 1:actionCount
        [retentionRisk(actionIdx), retentionDetails{actionIdx}] = ...
            computeLmbReferenceExistenceRetentionRisk( ...
                referenceDistributions, ...
                networkDisagreementDetails{actionIdx}. ...
                    receiverDistributions, ...
                groupIds, retentionOptions);
        current = retentionDetails{actionIdx};
        minimumFormationCardinalityChange(actionIdx) = min( ...
            current.formationMeanCardinalityChange);
        minimumReceiverCardinalityChange(actionIdx) = min( ...
            current.expectedCardinalityChange);
        minimumSupportedLabelRetentionRatio(actionIdx) = min( ...
            current.minimumSupportedLabelRetentionRatio);
        decisionThresholdCrossingCount(actionIdx) = sum( ...
            current.decisionThresholdCrossingCount);
        maximumExistenceDrift(actionIdx) = max( ...
            current.normalizedExistenceDrift);
    end
    disagreementLimit = networkDisagreementRisk(1) * ...
        (1 + protocol. ...
            maximumExpectedDisagreementIncreaseFraction);
    posteriorSafetyMask = ...
        retentionRisk <= protocol.maximumRetentionRisk + 1e-12 & ...
        minimumFormationCardinalityChange >= protocol. ...
            minimumFormationMeanCardinalityChange - 1e-12 & ...
        minimumSupportedLabelRetentionRatio >= protocol. ...
            minimumSupportedLabelRetentionRatio - 1e-12 & ...
        decisionThresholdCrossingCount <= protocol. ...
            maximumDecisionThresholdCrossingCount & ...
        networkDisagreementRisk <= disagreementLimit + 1e-12;
    if ~posteriorSafetyMask(1)
        error('ConflictMixing:InvalidBankContract', ...
            'Registered reference failed its own posterior guard.');
    end
else
    posteriorSafetyMask(1) = true;
end

physical = logical(context.physicalAdjacency);
allPhysical = true;
for actionIdx = 1:actionCount
    currentAdjacency = actionAdjacency(:, :, actionIdx);
    allPhysical = allPhysical && ~any( ...
        currentAdjacency(:) & ~physical(:));
end
bank = struct();
bank.contractVersion = ...
    'conflict-aware-formation-mixing-action-bank-v1';
bank.protocolId = protocol.id;
bank.nodeCount = nodeCount;
bank.formationCount = formationCount;
bank.groupIds = groupIds;
bank.actionCount = actionCount;
bank.referenceActionIndex = 1;
bank.actionNames = actionNames;
bank.actionModes = actionModes;
bank.actionFormationIds = actionFormationIds;
bank.actionAdjacency = actionAdjacency;
bank.actionFusionWeights = actionFusionWeights;
bank.actionFormationMixing = actionFormationMixing;
bank.actionMessageCounts = actionMessageCounts;
bank.actionCrossFormationMessageCounts = actionCrossMessageCounts;
bank.actionCrossResidualTrust = actionCrossTrust;
bank.actionFormationMixingSpectralGapProxy = actionMixingGap;
bank.actionDetails = actionDetails;
bank.networkDisagreementRisk = networkDisagreementRisk;
bank.networkDisagreementDetails = networkDisagreementDetails;
bank.retentionRisk = retentionRisk;
bank.retentionDetails = retentionDetails;
bank.minimumFormationCardinalityChange = ...
    minimumFormationCardinalityChange;
bank.minimumReceiverCardinalityChange = ...
    minimumReceiverCardinalityChange;
bank.minimumSupportedLabelRetentionRatio = ...
    minimumSupportedLabelRetentionRatio;
bank.decisionThresholdCrossingCount = ...
    decisionThresholdCrossingCount;
bank.maximumExistenceDrift = maximumExistenceDrift;
bank.posteriorSafetyScored = scorePosteriorSafety;
bank.actionPosteriorSafetyMask = posteriorSafetyMask;
bank.safeActionIndices = find(posteriorSafetyMask);
bank.safeNonreferenceActionCount = nnz(posteriorSafetyMask) - 1;
bank.actionWithinReferencePayload = true(1, actionCount);
bank.actionFormationIndex = zeros(1, actionCount);
bank.actionModeIndex = 1:actionCount;
bank.modeTrustWeights = actionCrossTrust;
bank.actionPosteriorProxyAllowed = posteriorSafetyMask;
bank.actionPosteriorObjective = -retentionRisk;
bank.actionPayloadBytes = nan(1, actionCount);
bank.messageCountParityWithReference = ...
    all(actionMessageCounts == actionMessageCounts(1));
bank.allPhysical = allPhysical;
bank.allCombinedOneStepStrongConnected = all(cellfun( ...
    @(item) item.combinedSensorStrongConnected, actionDetails));
bank.allFormationStrongConnected = all(cellfun( ...
    @(item) item.formationStrongConnected, actionDetails));
bank.truthUsed = any(cellfun( ...
    @(item) item.truthUsed, actionDetails));
bank.futureOutcomeUsed = any(cellfun( ...
    @(item) item.futureOutcomeUsed, actionDetails));
bank.attempts = attempts;
bank.acceptedSpecificationCount = nnz(strcmp( ...
    {attempts.status}, 'accepted'));
bank.duplicateSpecificationCount = nnz(strcmp( ...
    {attempts.status}, 'duplicate'));
bank.unavailableSpecificationCount = nnz(strcmp( ...
    {attempts.status}, 'unavailable'));
bank.openedDevelopmentEvidenceOnly = true;
bank.validationClaimAllowed = false;
end

function specifications = buildSpecifications( ...
        groups, pairActionModes, includeDampActions)
empty = struct('name', '', 'action', struct());
specifications = repmat(empty, 1, 0);
specifications(end + 1) = struct( ...
    'name', 'reference', ...
    'action', struct('mode', 'reference'));
if includeDampActions
    for formationIdx = 1:numel(groups)
        formationId = groups(formationIdx);
        specifications(end + 1) = struct( ...
            'name', sprintf('damp-reference-f%d', formationId), ...
            'action', struct( ...
                'mode', 'damp-reference-edge', ...
                'formationId', formationId)); %#ok<AGROW>
    end
end
for leftIdx = 1:numel(groups)-1
    for rightIdx = leftIdx+1:numel(groups)
        pair = [groups(leftIdx), groups(rightIdx)];
        for modeIdx = 1:numel(pairActionModes)
            mode = lower(strrep(char( ...
                pairActionModes{modeIdx}), '_', '-'));
            specifications(end + 1) = struct( ...
                'name', sprintf('%s-f%d-f%d', ...
                    mode, pair(1), pair(2)), ...
                'action', struct( ...
                    'mode', mode, ...
                    'formationPair', pair)); %#ok<AGROW>
        end
    end
end
end

function ids = actionFormationIdsFromSpec(action)
if isfield(action, 'formationPair')
    ids = reshape(action.formationPair, 1, []);
elseif isfield(action, 'formationId')
    ids = action.formationId;
else
    ids = zeros(1, 0);
end
end

function attempt = emptyAttempt()
attempt = struct( ...
    'specificationIndex', NaN, ...
    'actionName', '', ...
    'actionMode', '', ...
    'actionFormationIds', zeros(1, 0), ...
    'status', '', ...
    'actionIndex', NaN, ...
    'failureIdentifier', '', ...
    'failureMessage', '');
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
