function context = ...
    buildSpatialLabelSupportDebtRoutingV147ObservableContext( ...
        inputs, state, protocol)
% BUILDSPATIALLABELSUPPORTDEBTROUTINGV147OBSERVABLECONTEXT Current-only state.

anchorTime = state.anchorTime;
nodeCount = inputs.config.numberOfSensors;
model = attachCurrentObservableSensorGeometry( ...
    inputs.model, inputs.graphData.positions(:, :, anchorTime), ...
    anchorTime, nodeCount);
triggerConfig = buildMixtureAwareKlaReferenceConfig(struct( ...
    'missingLabelFusionMode', 'fov-aware-censored', ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'topologyPolicySensorObservationEnabled', true));
history = state.history;
previousPolicyHistory = state.previousPolicyHistory;
updateHistory = state.updateHistory;
full = struct( ...
    'localPosteriorBySensor', {state.initialPosteriors}, ...
    'model', model, ...
    'commConfig', inputs.commConfig, ...
    'triggerConfig', triggerConfig, ...
    'currentTime', anchorTime, ...
    'previousAdjacency', latestHistoryPage( ...
        previousPolicyHistory, nodeCount), ...
    'previousAdjacencyHistory', previousPolicyHistory, ...
    'previousAdjacencyHistoryCount', ...
        size(previousPolicyHistory, 3), ...
    'previousAdjacencyHistoryTimes', history.times, ...
    'previousAdjacencyHistoryConvention', ...
        'receiver-row-sender-column-directed-oldest-to-newest', ...
    'previousAdjacencyHistorySource', ...
        'v134-paired-reference-prefix', ...
    'baseAdjacency', inputs.graphData.staticAdjacency, ...
    'physicalAdjacency', logical(inputs.graphData. ...
        physicalAdjacency(:, :, anchorTime)), ...
    'edgeScores', [], ...
    'edgeBudget', inputs.config.edgeBudget, ...
    'directedMessageBudget', 2 * nodeCount, ...
    'positions', inputs.graphData.positions(:, :, anchorTime), ...
    'localInnovationHistory', updateHistory.innovation, ...
    'localAssociationConfidenceHistory', ...
        updateHistory.associationConfidence, ...
    'localNisNormHistory', updateHistory.nisNorm, ...
    'localNisDeviationHistory', updateHistory.nisDeviation, ...
    'localUpdateHistoryTimes', updateHistory.times, ...
    'previousDeliveryHistory', ...
        convertDiagnosticEdgeHistoryToPolicyAdjacencyHistory( ...
            history.deliveredDirectedEdgeHistory), ...
    'previousDeliveryHistoryCount', ...
        size(history.deliveredDirectedEdgeHistory, 3), ...
    'previousDeliveryHistoryTimes', history.times, ...
    'previousDeliveryHistoryConvention', ...
        ['receiver-row-sender-column-directed-', ...
         'oldest-to-newest-successful-deliveries'], ...
    'previousDeliveryHistorySource', ...
        'v134-paired-reference-prefix');
context = buildObservableTopologyPolicyContext(full);
end

function page = latestHistoryPage(history, nodeCount)
page = false(nodeCount);
if ~isempty(history)
    page = logical(history(:, :, end));
end
end
