function [values, names, details] = ...
        buildFormationRepairPropagationFeaturesV211( ...
            proposal, fusedPosteriorBySensor, model, options)
% BUILDFORMATIONREPAIRPROPAGATIONFEATURESV211 Continuous H-step descriptors.
%
% V189 used open-loop position propagation as a binary cutoff.  V211 keeps
% the same causal information boundary but exposes bounded continuous
% distance, velocity, covariance and Mahalanobis descriptors.  They are
% model inputs, never a sufficient safety certificate.

if nargin < 4 || isempty(options)
    options = struct();
end
horizonSteps = getField(options, 'horizonSteps', 3);
positionCutoff = getField(options, 'positionCutoff', ...
    resolvePositionCutoff(model));
receiverSummaryBytes = getField( ...
    options, 'receiverSummaryBytes', 24);
validateInputs(proposal, fusedPosteriorBySensor, model, ...
    horizonSteps, positionCutoff, receiverSummaryBytes);

receiverIds = reshape(proposal.receiverIds, 1, []);
receiverCount = numel(receiverIds);
stateDimension = model.xDimension;
[sourceMean, sourceCovariance] = ...
    momentMatch(proposal.sourceObject, stateDimension);
sourceMeans = zeros(stateDimension, horizonSteps);
sourceCovariances = zeros( ...
    stateDimension, stateDimension, horizonSteps);
sourceMeans(:, 1) = sourceMean;
sourceCovariances(:, :, 1) = sourceCovariance;
for horizonIdx = 2:horizonSteps
    sourceMeans(:, horizonIdx) = ...
        model.A * sourceMeans(:, horizonIdx - 1) + model.u;
    sourceCovariances(:, :, horizonIdx) = propagateCovariance( ...
        sourceCovariances(:, :, horizonIdx - 1), model);
end

distance = NaN(receiverCount, horizonSteps);
receiverTrace = NaN(receiverCount, horizonSteps);
sourceTrace = NaN(1, horizonSteps);
mahalanobis = NaN(receiverCount, horizonSteps);
receiverSpeed = NaN(receiverCount, 1);
relativeSpeed = NaN(receiverCount, 1);
velocityAlignment = 0.5 * ones(receiverCount, 1);
receiverDisplacement = NaN(receiverCount, 1);
for horizonIdx = 1:horizonSteps
    sourceTrace(horizonIdx) = max(trace( ...
        sourceCovariances(1:2, 1:2, horizonIdx)), 0);
end

for receiverPosition = 1:receiverCount
    receiverIdx = receiverIds(receiverPosition);
    receiverObject = findLabelObject( ...
        fusedPosteriorBySensor{receiverIdx}, proposal.label);
    if isempty(receiverObject)
        continue;
    end
    [receiverMean, receiverCovariance] = ...
        momentMatch(receiverObject, stateDimension);
    receiverMeans = zeros(stateDimension, horizonSteps);
    receiverCovariances = zeros( ...
        stateDimension, stateDimension, horizonSteps);
    receiverMeans(:, 1) = receiverMean;
    receiverCovariances(:, :, 1) = receiverCovariance;
    for horizonIdx = 2:horizonSteps
        receiverMeans(:, horizonIdx) = ...
            model.A * receiverMeans(:, horizonIdx - 1) + model.u;
        receiverCovariances(:, :, horizonIdx) = ...
            propagateCovariance( ...
                receiverCovariances(:, :, horizonIdx - 1), model);
    end
    for horizonIdx = 1:horizonSteps
        delta = sourceMeans(1:2, horizonIdx) - ...
            receiverMeans(1:2, horizonIdx);
        distance(receiverPosition, horizonIdx) = norm(delta);
        receiverTrace(receiverPosition, horizonIdx) = max(trace( ...
            receiverCovariances(1:2, 1:2, horizonIdx)), 0);
        combined = regularizeCovariance( ...
            sourceCovariances(1:2, 1:2, horizonIdx) + ...
            receiverCovariances(1:2, 1:2, horizonIdx));
        mahalanobis(receiverPosition, horizonIdx) = ...
            sqrt(max(real(delta' * (combined \ delta)), 0));
    end
    if stateDimension >= 4
        sourceVelocity = sourceMeans(3:4, 1);
        currentReceiverVelocity = receiverMeans(3:4, 1);
        receiverSpeed(receiverPosition) = ...
            norm(currentReceiverVelocity);
        relativeSpeed(receiverPosition) = ...
            norm(sourceVelocity - currentReceiverVelocity);
        denominator = norm(sourceVelocity) * ...
            norm(currentReceiverVelocity);
        if denominator > eps
            cosine = dot(sourceVelocity, ...
                currentReceiverVelocity) / denominator;
            velocityAlignment(receiverPosition) = ...
                min(max(0.5 * (cosine + 1), 0), 1);
        end
    else
        receiverSpeed(receiverPosition) = 0;
        relativeSpeed(receiverPosition) = 0;
    end
    receiverDisplacement(receiverPosition) = norm( ...
        receiverMeans(1:2, end) - receiverMeans(1:2, 1));
end

if any(~isfinite(distance(:))) || ...
        any(~isfinite(receiverTrace(:))) || ...
        any(~isfinite(mahalanobis(:))) || ...
        any(~isfinite(receiverSpeed)) || ...
        any(~isfinite(relativeSpeed)) || ...
        any(~isfinite(receiverDisplacement))
    error('FormationRepairPropagationFeaturesV211:MissingReceiver', ...
        'Every receiver must contain the supported proposal label.');
end

normalizedDistance = distance / positionCutoff;
initialDistance = normalizedDistance(:, 1);
terminalDistance = normalizedDistance(:, end);
distanceSlope = median(terminalDistance - initialDistance);
traceRatio = bsxfun(@rdivide, receiverTrace + eps, ...
    sourceTrace + eps);
logTraceRatio = log(traceRatio);
initialMahalanobis = mahalanobis(:, 1);
terminalMahalanobis = mahalanobis(:, end);
mahalanobisSlope = median( ...
    terminalMahalanobis - initialMahalanobis);
speedScale = positionCutoff / max(horizonSteps - 1, 1);
if stateDimension >= 4
    sourceSpeed = norm(sourceMeans(3:4, 1));
else
    sourceSpeed = 0;
end
sourceDisplacement = norm( ...
    sourceMeans(1:2, end) - sourceMeans(1:2, 1));

names = { ...
    'propagation_distance_initial_median_bounded', ...
    'propagation_distance_initial_maximum_bounded', ...
    'propagation_distance_terminal_median_bounded', ...
    'propagation_distance_terminal_maximum_bounded', ...
    'propagation_distance_horizon_maximum_bounded', ...
    'propagation_distance_slope_median_signed01', ...
    'propagation_receiver_horizon_pass_fraction', ...
    'propagation_all_receivers_horizon_pass', ...
    'propagation_source_position_trace_initial_bounded', ...
    'propagation_source_position_trace_terminal_bounded', ...
    'propagation_receiver_position_trace_initial_median_bounded', ...
    'propagation_receiver_position_trace_terminal_median_bounded', ...
    'propagation_precision_log_ratio_initial_median_signed01', ...
    'propagation_precision_log_ratio_terminal_median_signed01', ...
    'propagation_precision_gain_initial_median_bounded', ...
    'propagation_precision_gain_terminal_median_bounded', ...
    'propagation_mahalanobis_initial_median_bounded', ...
    'propagation_mahalanobis_terminal_median_bounded', ...
    'propagation_mahalanobis_slope_median_signed01', ...
    'propagation_source_speed_bounded', ...
    'propagation_receiver_speed_median_bounded', ...
    'propagation_relative_speed_median_bounded', ...
    'propagation_velocity_alignment_median', ...
    'propagation_source_displacement_bounded', ...
    'propagation_receiver_displacement_median_bounded'};
values = [ ...
    positiveBound(median(initialDistance)), ...
    positiveBound(max(initialDistance)), ...
    positiveBound(median(terminalDistance)), ...
    positiveBound(max(terminalDistance)), ...
    positiveBound(max(normalizedDistance(:))), ...
    signedBound01(distanceSlope), ...
    mean(normalizedDistance(:) <= 1), ...
    double(all(normalizedDistance(:) <= 1)), ...
    positiveBound(sourceTrace(1) / positionCutoff^2), ...
    positiveBound(sourceTrace(end) / positionCutoff^2), ...
    positiveBound(median(receiverTrace(:, 1)) / positionCutoff^2), ...
    positiveBound(median(receiverTrace(:, end)) / positionCutoff^2), ...
    signedBound01(median(logTraceRatio(:, 1))), ...
    signedBound01(median(logTraceRatio(:, end))), ...
    positiveBound(max(median(logTraceRatio(:, 1)), 0)), ...
    positiveBound(max(median(logTraceRatio(:, end)), 0)), ...
    positiveBound(median(initialMahalanobis)), ...
    positiveBound(median(terminalMahalanobis)), ...
    signedBound01(mahalanobisSlope), ...
    positiveBound(sourceSpeed / speedScale), ...
    positiveBound(median(receiverSpeed) / speedScale), ...
    positiveBound(median(relativeSpeed) / speedScale), ...
    median(velocityAlignment), ...
    positiveBound(sourceDisplacement / positionCutoff), ...
    positiveBound(median(receiverDisplacement) / positionCutoff)];
if numel(values) ~= numel(names) || ...
        any(~isfinite(values)) || any(values < 0) || any(values > 1)
    error('FormationRepairPropagationFeaturesV211:FeatureRange', ...
        'Every V211 propagation feature must be finite in [0,1].');
end

details = struct();
details.contractVersion = ...
    'formation-repair-propagation-features-v211-v1';
details.horizonSteps = horizonSteps;
details.positionCutoff = positionCutoff;
details.featureNames = names;
details.positionDistanceByReceiverHorizon = distance;
details.positionMahalanobisByReceiverHorizon = mahalanobis;
details.sourcePositionTraceByHorizon = sourceTrace;
details.receiverPositionTraceByReceiverHorizon = receiverTrace;
details.richSynopsisBytes = proposal.richSynopsisBytes;
details.receiverSummaryBytes = receiverSummaryBytes;
details.receiverSummaryRecordLayout = ...
    'six float32 open-loop propagation summaries';
details.attemptedFeatureBytes = proposal.richSynopsisBytes + ...
    receiverCount * receiverSummaryBytes;
details.sourceMomentOnly = true;
details.receiverMomentsRemainLocal = true;
details.truthUsed = false;
details.futureMeasurementsUsed = false;
details.hardThresholdApplied = false;
details.safetyGuaranteed = false;
details.evidenceBoundary = [ ...
    'V211 propagates current source and receiver moments through the ', ...
    'known motion model without truth or future measurements.  The ', ...
    'bounded descriptors are learned inputs, not a tracking or safety ', ...
    'certificate; their fixed communication cost must be charged if ', ...
    'computed distributively.'];
end

function validateInputs(proposal, fused, model, horizon, cutoff, bytes)
requiredProposal = {'formationId', 'receiverIds', 'sourceId', ...
    'label', 'sourceObject', 'richSynopsisBytes'};
if ~isstruct(proposal) || ~isscalar(proposal) || ...
        ~all(isfield(proposal, requiredProposal)) || ...
        ~iscell(fused) || isempty(proposal.receiverIds) || ...
        any(proposal.receiverIds < 1) || ...
        any(proposal.receiverIds > numel(fused)) || ...
        ~isstruct(model) || ~isscalar(model) || ...
        ~all(isfield(model, {'xDimension', 'A', 'u', 'R'})) || ...
        model.xDimension < 2 || ...
        ~isequal(size(model.A), ...
            [model.xDimension, model.xDimension]) || ...
        numel(model.u) ~= model.xDimension || ...
        ~isequal(size(model.R), ...
            [model.xDimension, model.xDimension]) || ...
        ~isscalar(horizon) || ~isfinite(horizon) || ...
        horizon < 1 || horizon ~= round(horizon) || ...
        ~isscalar(cutoff) || ~isfinite(cutoff) || cutoff <= 0 || ...
        ~isscalar(bytes) || ~isfinite(bytes) || ...
        bytes < 0 || bytes ~= round(bytes)
    error('FormationRepairPropagationFeaturesV211:InvalidInput', ...
        'A supported label proposal and valid propagation model are required.');
end
end

function object = findLabelObject(objects, label)
object = [];
for candidate = reshape(objects, 1, [])
    if candidate.birthTime == label(1) && ...
            candidate.birthLocation == label(2)
        object = candidate;
        return;
    end
end
end

function [meanVector, covariance] = momentMatch(object, dimension)
if isempty(object) || object.numberOfGmComponents < 1 || ...
        numel(object.w) ~= object.numberOfGmComponents
    error('FormationRepairPropagationFeaturesV211:InvalidBernoulli', ...
        'Moment propagation requires a valid Bernoulli GM density.');
end
weights = max(reshape(object.w, 1, []), 0);
weights(~isfinite(weights)) = 0;
if sum(weights) <= 0
    error('FormationRepairPropagationFeaturesV211:InvalidBernoulli', ...
        'The Bernoulli mixture weights have zero mass.');
end
weights = weights / sum(weights);
meanVector = zeros(dimension, 1);
for componentIdx = 1:numel(weights)
    componentMean = reshape(object.mu{componentIdx}, [], 1);
    if numel(componentMean) ~= dimension
        error('FormationRepairPropagationFeaturesV211:DimensionDrift', ...
            'A mixture component has the wrong state dimension.');
    end
    meanVector = meanVector + weights(componentIdx) * componentMean;
end
covariance = zeros(dimension);
for componentIdx = 1:numel(weights)
    componentCovariance = object.Sigma{componentIdx};
    delta = reshape(object.mu{componentIdx}, [], 1) - meanVector;
    covariance = covariance + weights(componentIdx) * ...
        (componentCovariance + delta * delta');
end
covariance = regularizeCovariance(covariance);
end

function covariance = propagateCovariance(covariance, model)
covariance = model.A * covariance * model.A' + model.R;
covariance = regularizeCovariance(covariance);
end

function covariance = regularizeCovariance(covariance)
covariance = (covariance + covariance') / 2;
jitter = 0;
for attempt = 1:8
    [~, flag] = chol(covariance + ...
        jitter * eye(size(covariance)));
    if flag == 0
        covariance = covariance + ...
            jitter * eye(size(covariance));
        return;
    end
    jitter = max(1e-12, 10 * max(jitter, 1e-12));
end
error('FormationRepairPropagationFeaturesV211:Covariance', ...
    'A propagated covariance cannot be regularized.');
end

function value = positiveBound(value)
value = max(value, 0);
value = value / (1 + value);
end

function value = signedBound01(value)
value = 0.5 * (tanh(value) + 1);
end

function value = resolvePositionCutoff(model)
value = NaN;
if isfield(model, 'ospaParameters') && ...
        isstruct(model.ospaParameters) && ...
        isfield(model.ospaParameters, 'eC')
    value = model.ospaParameters.eC;
end
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
