function control = buildFormationStaggeredRecoveryControl(context, options)
% BUILDFORMATIONSTAGGEREDRECOVERYCONTROL Causal v35 debt-aware release.
%
% V30 supplies the incumbent suspension set. Previously suspended inputs
% are then released from lowest to highest current retention debt, but only
% while the retained set covers the registered share of positive debt. The
% first nested route that safely improves one-round disagreement is used;
% otherwise the causal v30 incumbent is retained.

if nargin < 2 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('StaggeredRecovery:InvalidOptions', ...
        'The frozen v35 controller does not accept option overrides.');
end
protocol = getFormationStaggeredRecoveryProbeProtocol();
base = buildFormationRetentionDebtControl(context);
nodeCount = base.nodeCount;
formationCount = base.formationCount;
groups = base.groups;
groupIds = base.groupIds;
if formationCount > protocol.maximumFormationCount
    error('StaggeredRecovery:InvalidContext', ...
        'Formation count exceeds the registered v35 scale.');
end

suspensionAge = detectSuspensionAge( ...
    context, groupIds, groups);
schedule = buildFormationDebtCoverageReleaseSchedule( ...
    groups, base.selectedFormationIds, ...
    base.formationRetentionDebtFraction, suspensionAge, ...
    protocol.minimumSuspensionAgeSteps, ...
    protocol.minimumRetainedDebtCoverageFraction);

candidateCount = schedule.candidateCount;
candidateAdjacency = cell(1, candidateCount);
candidateFusionWeights = cell(1, candidateCount);
candidatePolicyDetails = cell(1, candidateCount);
candidateScores = cell(1, candidateCount);
candidateAvailableMask = false(1, candidateCount);
candidateSafetyMask = false(1, candidateCount);
candidateEligibilityMask = false(1, candidateCount);
candidateDisagreementImprovementFraction = ...
    nan(1, candidateCount);
candidateMessageSavingCount = nan(1, candidateCount);
candidateFailureIdentifier = repmat({''}, 1, candidateCount);
candidateFailureMessage = repmat({''}, 1, candidateCount);
referenceDistributions = ...
    base.referenceScore.networkDetails.receiverDistributions;
incumbentRisk = base.selectedScore.networkRisk;
for candidateIdx = 1:candidateCount
    retained = schedule. ...
        candidateRetainedFormationIds{candidateIdx};
    try
        [adjacency, details] = ...
            selectTemporalCrossEdgeSuspensionPolicy( ...
                context, retained, struct( ...
                    'dominantWeight', protocol.dominantWeight, ...
                    'residualWeight', protocol.residualWeight));
        score = scoreRoute( ...
            context, adjacency, details.fusionWeightMatrix, ...
            referenceDistributions, groupIds, protocol);
        improvement = relativeImprovement( ...
            incumbentRisk, score.networkRisk);
        messageSaving = details.messageSavingCount;
        safe = score.safe && ...
            all(details.rollingB3SensorPass) && ...
            all(details.rollingB3FormationPass);
        eligible = safe && ...
            messageSaving >= protocol.minimumMessageSavingCount && ...
            improvement >= protocol. ...
                minimumIncumbentDisagreementImprovementFraction - 1e-12;
        candidateAdjacency{candidateIdx} = adjacency;
        candidateFusionWeights{candidateIdx} = ...
            details.fusionWeightMatrix;
        candidatePolicyDetails{candidateIdx} = details;
        candidateScores{candidateIdx} = score;
        candidateAvailableMask(candidateIdx) = true;
        candidateSafetyMask(candidateIdx) = safe;
        candidateEligibilityMask(candidateIdx) = eligible;
        candidateDisagreementImprovementFraction(candidateIdx) = ...
            improvement;
        candidateMessageSavingCount(candidateIdx) = messageSaving;
    catch errorInfo
        if ~isExpectedUnavailable(errorInfo)
            rethrow(errorInfo);
        end
        candidateFailureIdentifier{candidateIdx} = ...
            getErrorField(errorInfo, 'identifier');
        candidateFailureMessage{candidateIdx} = ...
            getErrorField(errorInfo, 'message');
    end
end

selectedCandidateIndex = find(candidateEligibilityMask, 1, 'first');
selectedAdjacency = base.selectedAdjacency;
selectedFusionWeights = base.selectedFusionWeights;
selectedPolicyDetails = base.selectedPolicyDetails;
selectedScore = base.selectedScore;
selectedFormationIds = base.selectedFormationIds;
releasedFormationIds = zeros(1, 0);
selectedDebtCoverageFraction = 1;
selectedDisagreementImprovementFraction = 0;
staggeredReleaseUsed = ~isempty(selectedCandidateIndex);
if staggeredReleaseUsed
    selectedAdjacency = candidateAdjacency{selectedCandidateIndex};
    selectedFusionWeights = ...
        candidateFusionWeights{selectedCandidateIndex};
    selectedPolicyDetails = ...
        candidatePolicyDetails{selectedCandidateIndex};
    selectedScore = candidateScores{selectedCandidateIndex};
    selectedFormationIds = schedule. ...
        candidateRetainedFormationIds{selectedCandidateIndex};
    releasedFormationIds = schedule. ...
        candidateReleasedFormationIds{selectedCandidateIndex};
    selectedDebtCoverageFraction = schedule. ...
        candidateRetainedDebtCoverage(selectedCandidateIndex);
    selectedDisagreementImprovementFraction = ...
        candidateDisagreementImprovementFraction( ...
            selectedCandidateIndex);
end

selectedWeightSupport = selectedAdjacency | logical(eye(nodeCount));
selectedMessageCount = nnz(selectedAdjacency);
if ~selectedScore.safe || ...
        any(selectedAdjacency(:) & ...
            ~logical(context.physicalAdjacency(:))) || ...
        selectedMessageCount > base.referenceMessageCount || ...
        any(~isfinite(selectedFusionWeights(:))) || ...
        any(selectedFusionWeights(:) < -1e-12) || ...
        any(selectedFusionWeights(:) > 1e-12 & ...
            ~selectedWeightSupport(:)) || ...
        any(abs(sum(selectedFusionWeights, 2) - 1) > 1e-12) || ...
        (staggeredReleaseUsed && ...
         (selectedDebtCoverageFraction < protocol. ...
            minimumRetainedDebtCoverageFraction - 1e-12 || ...
          selectedDisagreementImprovementFraction < protocol. ...
            minimumIncumbentDisagreementImprovementFraction - 1e-12))
    error('StaggeredRecovery:InvalidSelection', ...
        'Selected staggered-recovery route violates a hard invariant.');
end

evaluatedRouteCount = base.evaluatedRouteCount + candidateCount;
if evaluatedRouteCount > protocol.maximumControlRouteEvaluations
    error('StaggeredRecovery:EvaluationBudgetExceeded', ...
        'Staggered-recovery evaluation exceeded its frozen budget.');
end

control = struct();
control.contractVersion = ...
    'formation-staggered-recovery-control-v1';
control.protocolId = protocol.id;
control.nodeCount = nodeCount;
control.formationCount = formationCount;
control.groupIds = groupIds;
control.groups = groups;
control.baseControl = base;
control.referenceAdjacency = base.referenceAdjacency;
control.referenceFusionWeights = ...
    base.referenceFusionWeights;
control.referencePolicyDetails = ...
    base.referencePolicyDetails;
control.referenceScore = base.referenceScore;
control.incumbentFormationIds = base.selectedFormationIds;
control.incumbentAdjacency = base.selectedAdjacency;
control.incumbentFusionWeights = base.selectedFusionWeights;
control.incumbentPolicyDetails = base.selectedPolicyDetails;
control.incumbentScore = base.selectedScore;
control.suspensionAgeByFormation = suspensionAge;
control.releaseSchedule = schedule;
control.candidateAdjacency = candidateAdjacency;
control.candidateFusionWeights = candidateFusionWeights;
control.candidatePolicyDetails = candidatePolicyDetails;
control.candidateScores = candidateScores;
control.candidateAvailableMask = candidateAvailableMask;
control.candidateSafetyMask = candidateSafetyMask;
control.candidateEligibilityMask = candidateEligibilityMask;
control.candidateDisagreementImprovementFraction = ...
    candidateDisagreementImprovementFraction;
control.candidateMessageSavingCount = ...
    candidateMessageSavingCount;
control.candidateFailureIdentifier = candidateFailureIdentifier;
control.candidateFailureMessage = candidateFailureMessage;
control.selectedCandidateIndex = selectedCandidateIndex;
control.selectedAdjacency = selectedAdjacency;
control.selectedFusionWeights = selectedFusionWeights;
control.selectedPolicyDetails = selectedPolicyDetails;
control.selectedScore = selectedScore;
control.selectedFormationIds = selectedFormationIds;
control.releasedFormationIds = releasedFormationIds;
control.selectedDebtCoverageFraction = ...
    selectedDebtCoverageFraction;
control.selectedDisagreementImprovementFraction = ...
    selectedDisagreementImprovementFraction;
control.selectedActionName = selectedPolicyDetails.actionName;
control.staggeredReleaseUsed = staggeredReleaseUsed;
control.baseFallbackUsed = ~staggeredReleaseUsed;
control.referenceFallbackUsed = isempty(selectedFormationIds);
control.referenceMessageCount = base.referenceMessageCount;
control.selectedMessageCount = selectedMessageCount;
control.messageSavingCount = ...
    base.referenceMessageCount - selectedMessageCount;
control.evaluatedRouteCount = evaluatedRouteCount;
control.safeCandidateCount = nnz(candidateSafetyMask);
control.eligibleCandidateCount = nnz(candidateEligibilityMask);
control.selectedRollingB3SensorPass = ...
    selectedPolicyDetails.rollingB3SensorPass;
control.selectedRollingB3FormationPass = ...
    selectedPolicyDetails.rollingB3FormationPass;
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.truthUsed = false;
control.futureOutcomeUsed = false;
control.openedDevelopmentEvidenceOnly = true;
control.validationClaimAllowed = false;
end

function age = detectSuspensionAge(context, groupIds, groups)
history = logical(context.previousAdjacencyHistory);
age = zeros(1, numel(groups));
for formationIdx = 1:numel(groups)
    receivers = groupIds == groups(formationIdx);
    outsideSenders = groupIds ~= groups(formationIdx);
    for historyIdx = size(history, 3):-1:1
        page = history(:, :, historyIdx);
        if any(any(page(receivers, outsideSenders)))
            break;
        end
        age(formationIdx) = age(formationIdx) + 1;
    end
end
end

function score = scoreRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, protocol)
enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, enumerationOptions);
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        protocol.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        protocol.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        protocol.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        protocol.retentionReceiverTailWeight);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, ...
        groupIds, retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = ...
    retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= protocol. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= protocol. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= protocol. ...
        maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'retentionRisk', retentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function value = relativeImprovement(referenceRisk, candidateRisk)
value = (referenceRisk - candidateRisk) / max(referenceRisk, eps);
end

function value = isExpectedUnavailable(errorInfo)
identifier = getErrorField(errorInfo, 'identifier');
value = strcmp(identifier, 'TemporalSuspension:Infeasible') || ...
    strcmp(identifier, 'TemporalSuspension:InvalidCandidate');
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
if isempty(value)
    value = '';
end
end
