function context = buildAlternatingShieldBroadcastV111ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDALTERNATINGSHIELDBROADCASTV111EXECUTIONCONTEXT Frozen H=8 probe.

protocol = getAlternatingShieldBroadcastV111Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('AlternatingShieldBroadcastV111:InvalidExecutionContext', ...
        'The V111 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'alternating-shield-broadcast-v111-context-v1';
context.capability = ...
    'alternating-shield-broadcast-v111-development';
context.action = ...
    'filter-alternating-shield-broadcast-v111-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
