function context = ...
        buildRiskTriggeredFormationResidualPulseV260ExecutionContext( ...
            presetName, seed, measurementTimeCount, pulseWeight)
% BUILDRISKTRIGGEREDFORMATIONRESIDUALPULSEV260EXECUTIONCONTEXT Dev permit.

protocol = getRiskTriggeredFormationResidualPulseV260Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~ismember(seed, protocol.allowedSeeds) || ...
        measurementTimeCount ~= protocol.continuationEndTime || ...
        ~ismember(pulseWeight, protocol.pulseWeights)
    error('RiskTriggeredPulseV260:InvalidExecutionContextInput', ...
        'V260 requires its registered continuation and pulse weight.');
end
context = struct();
context.contractVersion = ...
    'risk-triggered-formation-residual-pulse-v260-context-v1';
context.capability = ...
    'risk-triggered-formation-residual-pulse-v260-development';
context.action = ...
    'filter-risk-triggered-formation-residual-pulse-v260-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = sprintf('%s-w%02d', ...
    protocol.armIdPrefix, round(100 * pulseWeight));
context.measurementTimeCount = measurementTimeCount;
context.continuationStartTime = protocol.continuationStartTime;
context.pulseWeight = pulseWeight;
context.policyName = protocol.policyName;
context.developmentEvidenceOnly = true;
end
