function [adjacency, details] = ...
    buildFormationB4V49FixedRuntimeArm(context, armId)
% BUILDFORMATIONB4V49FIXEDRUNTIMEARM Execute one graph-only V49 page.
%
% The public observable context may contain a sanitized current posterior
% because it is shared by many topology policies.  V49 immediately reduces
% it to the registered seven-field graph-only route context.  The incumbent
% V46 route is rebuilt with an empty posterior collection of the same size.

timerId = tic;
protocol = getFormationB4V49RuntimeProtocol();
if nargin ~= 2 || ~ischar(armId) || ~isrow(armId) || ...
        ~strcmp(armId, protocol.candidateArmId)
    error('FormationB4V49Runtime:InvalidArm', ...
        'Only the frozen V49 feasible-cycle runtime arm is allowed.');
end
validateRuntimeContext(context, protocol);
[routeContext, routeContextContract] = ...
    buildFormationB4V49GraphOnlyRouteContext(context);

nodeCount = numel(context.localPosteriorBySensor);
incumbentContext = buildGraphOnlyIncumbentContext( ...
    context, routeContext, nodeCount);
[incumbentAdjacency, incumbentDetails] = ...
    buildFormationB4V46FixedRuntimeArm( ...
        incumbentContext, protocol.referenceArmId);
incumbent = struct( ...
    'dominantAdjacency', ...
        logical(incumbentDetails.dominantAdjacency), ...
    'residualAdjacency', ...
        logical(incumbentDetails.residualAdjacency), ...
    'referenceAdjacency', ...
        logical(incumbentDetails.referenceAdjacency), ...
    'referenceFusionWeights', ...
        incumbentDetails.referenceFusionWeights);

phase = mod(context.currentTime - 1, protocol.period) + 1;
selectionPerformed = phase == 1;
selectionCertificate = struct([]);
selectedIsCycle = false;
fallbackReason = 'not-a-burst-page';
selected = incumbent;
if selectionPerformed
    options = struct( ...
        'period', protocol.period, ...
        'dominantWeight', protocol.dominantWeight, ...
        'referenceResidualWeight', ...
            protocol.referenceResidualWeight, ...
        'activeResidualWeight', protocol.activeResidualWeight, ...
        'minimumRelativeImprovementVsIncumbent', ...
            protocol.minimumRelativeImprovementVsIncumbent, ...
        'maximumCanonicalCycleEnumerationCount', ...
            protocol.maximumCanonicalCycleEnumerationCount, ...
        'cycleSelectionMode', protocol.cycleSelectionMode, ...
        'maximumExactProposalEvaluations', ...
            protocol.maximumExactProposalEvaluations, ...
        'pulsePhaseMode', protocol.pulsePhaseMode);
    [selected, selectionDetails] = ...
        selectFormationB4V49CyclePreservingReference( ...
            routeContext, incumbent, options);
    selectionCertificate = rmfield(selectionDetails, { ...
        'selectedReference', 'incumbentReference'});
    selectedIsCycle = selectionDetails. ...
        selectedIsCyclePreservingReference;
    fallbackReason = selectionDetails.selectedFallbackReason;
end

[adjacency, fusionWeights] = materializeRuntimePage( ...
    selected, phase, protocol);
validateRuntimePage(adjacency, fusionWeights, selected, ...
    incumbent, context, phase, protocol);

routeAndWeightHash = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), ...
    'fusionWeightMatrix', fusionWeights));

schedulePayload = struct();
schedulePayload.contractVersion = ...
    'formation-b4-v49-runtime-schedule-v1';
schedulePayload.currentTime = context.currentTime;
schedulePayload.currentAbsolutePhase = phase;
schedulePayload.period = protocol.period;
schedulePayload.cycleSelectionPerformed = selectionPerformed;
schedulePayload.cycleSelected = selectedIsCycle;
schedulePayload.referenceFallbackUsed = ...
    selectionPerformed && ~selectedIsCycle;
schedulePayload.fallbackReason = fallbackReason;
schedulePayload.selectionCertificate = selectionCertificate;
schedulePayload.graphOnlyRouteContextContract = routeContextContract;
schedulePayload.dominantLayerBitwiseEqualsIncumbent = ...
    isequal(selected.dominantAdjacency, ...
        incumbent.dominantAdjacency);
schedulePayload.currentScheduledDirectedEdgeCount = nnz(adjacency);
schedulePayload.expectedScheduledDirectedEdgeCount = ...
    nodeCount * (1 + double(phase == 1));
schedulePayload.scheduledDirectedEdgeCountsByPhase = ...
    nodeCount * [2, 1, 1, 1];
schedulePayload.sameScheduledDirectedEdgeCountVsV46 = true;
schedulePayload.posteriorPresentAtSelector = false;
schedulePayload.posteriorSummaryPresentAtSelector = false;
schedulePayload.futurePagePresentAtSelector = false;
schedulePayload.realizedDeliveryUniformPresentAtSelector = false;
schedulePayload.trackingOutcomeScored = false;
schedulePayload.routeDisseminationImplemented = false;
schedulePayload.atomicCommitImplemented = false;
schedulePayload.sameTotalByteClaimAllowed = false;
schedule = schedulePayload;

formationUids = reshape( ...
    context.formationPhysicalUidsBySensor, 1, []);
crossMask = formationUids(:) ~= formationUids(:)';
details = struct();
details.contractVersion = ...
    'formation-b4-v49-fixed-runtime-policy-v1';
details.mode = 'formation-b4-v49-feasible-cycle-runtime';
details.armId = protocol.candidateArmId;
details.armOrdinal = 2;
details.actionName = protocol.candidateArmId;
details.currentTime = context.currentTime;
details.currentAbsolutePhase = phase;
details.period = protocol.period;
details.objective = NaN;
if selectionPerformed
    details.objective = selectionCertificate. ...
        selectedRelativeImprovementVsIncumbent;
end
details.objectiveDefinition = ...
    'selected-relative-reduction-in-frozen-b4-squared-factor';
details.objectiveSource = ...
    'graph-only-current-page-exact-certificate';
details.candidateIndex = NaN;
details.fusionWeightMatrix = fusionWeights;
details.referenceFusionWeights = ...
    selected.referenceFusionWeights;
details.dominantAdjacency = ...
    logical(selected.dominantAdjacency);
details.residualAdjacency = ...
    logical(selected.residualAdjacency);
details.referenceAdjacency = ...
    logical(selected.referenceAdjacency);
details.scheduleCertificate = schedule;
details.protocolId = protocol.id;
details.observableInputContractVersion = ...
    protocol.observableContractVersion;
details.referenceFallbackUsed = ...
    schedule.referenceFallbackUsed;
details.repairTriggered = incumbentDetails.repairTriggered;
details.fullV43RouteCompositionPassed = true;
details.routeAndWeightCanonicalSha256 = routeAndWeightHash;
details.routeReceivesCurrentPageOnly = true;
details.projectionReceivesCurrentPageOnly = true;
details.graphOnlyRouteContextUsed = true;
details.observableContextOnly = true;
details.policyOptionsAccepted = false;
details.posteriorUsed = false;
details.currentPosteriorUsed = false;
details.posteriorPayloadMetadataUsed = false;
details.posteriorUsedByProjection = false;
details.truthUsedByProjection = false;
details.measurementUsedByProjection = false;
details.futurePageUsedByProjection = false;
details.realizedDeliveryUniformsUsedByProjection = false;
details.currentLinkReliabilityUsed = true;
details.currentPhysicalActionSetUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.measurementUsed = false;
details.futurePageUsed = false;
details.futureOutcomeUsed = false;
details.realizedDeliveryUniformsUsed = false;
details.pastSuccessfulDeliveryUsed = false;
details.crossResidualCount = nnz( ...
    selected.residualAdjacency & crossMask);
details.localResidualCount = nnz( ...
    selected.residualAdjacency & ~crossMask);
details.currentScheduledDirectedEdgeCount = nnz(adjacency);
details.referenceScheduledDirectedEdgeCount = 2 * nodeCount;
details.scheduledDirectedEdgeSavingFraction = ...
    (2 * nodeCount - nnz(adjacency)) / (2 * nodeCount);
% Legacy diagnostics retained for the shared filter output schema.  These
% fields count scheduled edge slots, never outage/gate-adjusted attempts.
details.currentMessageCount = ...
    details.currentScheduledDirectedEdgeCount;
details.referenceMessageCount = ...
    details.referenceScheduledDirectedEdgeCount;
details.messageSavingFraction = ...
    details.scheduledDirectedEdgeSavingFraction;
details.sameScheduledDirectedEdgeCountVsV46 = true;
details.routeDisseminationImplemented = false;
details.atomicCommitImplemented = false;
details.sameTotalByteClaimAllowed = false;
details.trackingOutcomeScored = false;
details.validationClaimAllowed = false;
details.developmentEvidenceOnly = true;
details.incumbentRuntimeAdjacency = ...
    logical(incumbentAdjacency);
details.selectionSeconds = toc(timerId);
end

function incumbent = buildGraphOnlyIncumbentContext( ...
        context, routeContext, nodeCount)
% Rebuild only the inputs that V46's route constructor is allowed to read.
incumbent = struct();
incumbent.localPosteriorBySensor = ...
    cell(size(context.localPosteriorBySensor));
incumbent.model = struct('dynamicTopologyScenario', struct( ...
    'config', struct('sensorGroupIds', ...
        routeContext.sensorGroupIds)));
incumbent.baseAdjacency = logical(context.baseAdjacency);
incumbent.physicalAdjacency = ...
    logical(routeContext.physicalAdjacency);
incumbent.positions = routeContext.positions;
incumbent.sensorPhysicalUids = ...
    routeContext.sensorPhysicalUids;
incumbent.formationPhysicalUidsBySensor = ...
    routeContext.formationPhysicalUidsBySensor;
incumbent.physicalIdentityRegistryCanonicalSha256 = ...
    context.physicalIdentityRegistryCanonicalSha256;
incumbent.commConfig = struct( ...
    'pDropByEdge', routeContext.pDropByEdge);
incumbent.currentTime = routeContext.currentTime;
incumbent.directedMessageBudget = 2 * nodeCount;
incumbent.triggerConfig = struct( ...
    'topologyDirectedEnabled', true, ...
    'topologyDirectedMessageBudget', 2 * nodeCount);
incumbent.observableInputContract = ...
    context.observableInputContract;
end

function validateRuntimeContext(context, protocol)
required = {'localPosteriorBySensor', 'model', 'baseAdjacency', ...
    'physicalAdjacency', 'positions', 'sensorPhysicalUids', ...
    'formationPhysicalUidsBySensor', ...
    'physicalIdentityRegistryCanonicalSha256', 'commConfig', ...
    'triggerConfig', 'observableInputContract', 'currentTime'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ...
        ~iscell(context.localPosteriorBySensor) || ...
        ~isstruct(context.observableInputContract) || ...
        ~isscalar(context.observableInputContract) || ...
        ~isfield(context.observableInputContract, 'passed') || ...
        ~context.observableInputContract.passed || ...
        ~isfield(context.observableInputContract, ...
            'contractVersion') || ...
        ~strcmp(context.observableInputContract.contractVersion, ...
            protocol.observableContractVersion)
    error('FormationB4V49Runtime:InvalidContext', ...
        'The V49 observable runtime context is incomplete.');
end
nodeCount = numel(context.localPosteriorBySensor);
if nodeCount < 1 || ...
        ~isequal(size(context.baseAdjacency), ...
            [nodeCount, nodeCount]) || ...
        ~isequal(size(context.physicalAdjacency), ...
            [nodeCount, nodeCount]) || ...
        ~isequal(size(context.positions), [2, nodeCount]) || ...
        ~isfield(context.triggerConfig, ...
            'topologyDirectedMessageBudget') || ...
        context.triggerConfig.topologyDirectedMessageBudget ~= ...
            2 * nodeCount
    error('FormationB4V49Runtime:InvalidContext', ...
        'The V49 route shape or directed message ceiling drifted.');
end
end

function [adjacency, weights] = ...
        materializeRuntimePage(reference, phase, protocol)
nodeCount = size(reference.referenceAdjacency, 1);
dominant = logical(reference.dominantAdjacency);
residual = false(nodeCount);
if phase == 1
    residual = logical(reference.residualAdjacency);
end
adjacency = dominant | residual;
weights = zeros(nodeCount);
weights(dominant) = protocol.dominantWeight;
weights(residual) = protocol.activeResidualWeight;
weights(1:nodeCount+1:end) = 1 - sum(weights, 2)';
end

function validateRuntimePage(adjacency, weights, selected, ...
        incumbent, context, phase, protocol)
nodeCount = numel(context.sensorPhysicalUids);
dominant = logical(selected.dominantAdjacency);
residual = logical(selected.residualAdjacency);
reference = logical(selected.referenceAdjacency);
positive = weights > 1e-12;
positive(1:nodeCount+1:end) = false;
expectedCount = nodeCount * (1 + double(phase == 1));
if ~islogical(adjacency) || ...
        ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        any(diag(adjacency)) || ...
        any(adjacency(:) & ~logical(context.physicalAdjacency(:))) || ...
        ~isequal(reference, dominant | residual) || ...
        any(dominant(:) & residual(:)) || ...
        ~all(sum(dominant, 2) == 1) || ...
        ~all(sum(residual, 2) == 1) || ...
        ~isequal(dominant, incumbent.dominantAdjacency) || ...
        nnz(reference) ~= 2 * nodeCount || ...
        nnz(adjacency) ~= expectedCount || ...
        ~isequal(positive, adjacency) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        any(weights(:) < -1e-12) || any(weights(:) > 1 + 1e-12) || ...
        any(abs(weights(dominant) - ...
            protocol.dominantWeight) > 1e-12) || ...
        (phase == 1 && any(abs(weights(residual) - ...
            protocol.activeResidualWeight) > 1e-12))
    error('FormationB4V49Runtime:InvalidAction', ...
        'The V49 runtime page violates route, weight, or budget invariants.');
end
end
