function schedule = buildFormationProtectionCoverageReleaseSchedule( ...
        groups, selectedFormationIds, protectionScoreByFormation, ...
        suspensionAgeByFormation, minimumSuspensionAge, ...
        minimumRetainedProtectionCoverage)
% BUILDFORMATIONPROTECTIONCOVERAGERELEASESCHEDULE Causal nested release.

groups = reshape(groups, 1, []);
selectedFormationIds = reshape(selectedFormationIds, 1, []);
protectionScoreByFormation = reshape( ...
    protectionScoreByFormation, 1, []);
suspensionAgeByFormation = reshape( ...
    suspensionAgeByFormation, 1, []);
if isempty(groups) || numel(unique(groups)) ~= numel(groups) || ...
        numel(protectionScoreByFormation) ~= numel(groups) || ...
        numel(suspensionAgeByFormation) ~= numel(groups) || ...
        any(~isfinite(suspensionAgeByFormation)) || ...
        any(suspensionAgeByFormation < 0) || ...
        any(suspensionAgeByFormation ~= ...
            round(suspensionAgeByFormation)) || ...
        numel(unique(selectedFormationIds)) ~= ...
            numel(selectedFormationIds) || ...
        any(~ismember(selectedFormationIds, groups)) || ...
        ~isscalar(minimumSuspensionAge) || ...
        ~isfinite(minimumSuspensionAge) || ...
        minimumSuspensionAge ~= round(minimumSuspensionAge) || ...
        minimumSuspensionAge < 1 || ...
        ~isscalar(minimumRetainedProtectionCoverage) || ...
        ~isfinite(minimumRetainedProtectionCoverage) || ...
        minimumRetainedProtectionCoverage <= 0 || ...
        minimumRetainedProtectionCoverage > 1
    error('ProtectionCoverageRelease:InvalidContract', ...
        'Protection-coverage release inputs are invalid.');
end

selectedMask = ismember(groups, selectedFormationIds);
if any(~isfinite(protectionScoreByFormation(selectedMask)))
    error('ProtectionCoverageRelease:InvalidContract', ...
        'Selected formations need finite protection scores.');
end
positiveProtection = zeros(1, numel(groups));
positiveProtection(selectedMask) = max( ...
    protectionScoreByFormation(selectedMask), 0);
totalSelectedProtection = sum(positiveProtection(selectedMask));
matureMask = selectedMask & ...
    suspensionAgeByFormation >= minimumSuspensionAge;
matureIndices = find(matureMask);
if isempty(matureIndices) || totalSelectedProtection <= eps
    releaseOrder = zeros(1, 0);
else
    ranking = [ ...
        positiveProtection(matureIndices)', groups(matureIndices)'];
    [~, order] = sortrows(ranking, [1, 2]);
    releaseOrder = groups(matureIndices(order));
end

candidateRetainedFormationIds = cell(1, 0);
candidateReleasedFormationIds = cell(1, 0);
candidateRetainedProtectionCoverage = zeros(1, 0);
remaining = selectedFormationIds;
released = zeros(1, 0);
for releaseIdx = 1:numel(releaseOrder)
    released(end + 1) = releaseOrder(releaseIdx); %#ok<AGROW>
    remaining = remaining(~ismember(remaining, released));
    retainedMask = ismember(groups, remaining);
    coverage = sum(positiveProtection(retainedMask)) / ...
        max(totalSelectedProtection, eps);
    if isempty(remaining) || ...
            coverage < minimumRetainedProtectionCoverage - 1e-12
        break;
    end
    candidateRetainedFormationIds{end + 1} = ...
        remaining; %#ok<AGROW>
    candidateReleasedFormationIds{end + 1} = ...
        released; %#ok<AGROW>
    candidateRetainedProtectionCoverage(end + 1) = ...
        coverage; %#ok<AGROW>
end

schedule = struct();
schedule.contractVersion = ...
    'formation-protection-coverage-release-schedule-v1';
schedule.groups = groups;
schedule.selectedFormationIds = selectedFormationIds;
schedule.protectionScoreByFormation = protectionScoreByFormation;
schedule.suspensionAgeByFormation = suspensionAgeByFormation;
schedule.minimumSuspensionAge = minimumSuspensionAge;
schedule.minimumRetainedProtectionCoverage = ...
    minimumRetainedProtectionCoverage;
schedule.totalSelectedPositiveProtection = ...
    totalSelectedProtection;
schedule.matureFormationIds = groups(matureMask);
schedule.releaseOrder = releaseOrder;
schedule.candidateRetainedFormationIds = ...
    candidateRetainedFormationIds;
schedule.candidateReleasedFormationIds = ...
    candidateReleasedFormationIds;
schedule.candidateRetainedProtectionCoverage = ...
    candidateRetainedProtectionCoverage;
schedule.candidateCount = ...
    numel(candidateRetainedFormationIds);
schedule.truthUsed = false;
schedule.futureOutcomeUsed = false;
end
