function bank = buildTemporalCrossEdgeSuspensionActionBank( ...
        context, options)
% BUILDTEMPORALCROSSEDGESUSPENSIONACTIONBANK Frozen v29 subset bank.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getFormationTemporalSuspensionProbeProtocol();
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
nodeCount = numel(context.localPosteriorBySensor);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
scorePosteriorSafety = logical(getField(options, ...
    'scorePosteriorSafety', true));
requestedPosteriorSafetyActionIndices = getField( ...
    options, 'posteriorSafetyActionIndices', []);
maximumActionCount = round(getField(options, ...
    'maximumActionCount', protocol.maximumActionCount));
actionCount = 2^formationCount;
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || actionCount > maximumActionCount
    error('TemporalSuspension:InvalidBankContract', ...
        'Temporal-suspension bank exceeds its registered scale.');
end

if scorePosteriorSafety
    if isempty(requestedPosteriorSafetyActionIndices)
        posteriorSafetyActionIndices = 1:actionCount;
        posteriorSafetyScoringMode = 'full-bank-v1';
    else
        posteriorSafetyActionIndices = validateSafetyActionIndices( ...
            requestedPosteriorSafetyActionIndices, actionCount);
        posteriorSafetyScoringMode = 'explicit-index-subset-v1';
    end
elseif ~isempty(requestedPosteriorSafetyActionIndices)
    error('TemporalSuspension:InvalidBankContract', ...
        ['posteriorSafetyActionIndices cannot be supplied when ', ...
         'posterior safety scoring is disabled.']);
else
    posteriorSafetyActionIndices = zeros(1, 0);
    posteriorSafetyScoringMode = 'disabled-v1';
end
policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.residualWeight);

actionAdjacency = false(nodeCount, nodeCount, actionCount);
actionFusionWeights = zeros(nodeCount, nodeCount, actionCount);
actionNames = cell(1, actionCount);
actionSuspendedFormationIds = cell(1, actionCount);
actionSuspendedCrossEdgeCounts = zeros(1, actionCount);
actionMessageCounts = zeros(1, actionCount);
actionMessageSavingCounts = zeros(1, actionCount);
actionMessageSavingFractions = zeros(1, actionCount);
actionCrossFormationMessageCounts = zeros(1, actionCount);
actionInstantaneousSensorStrong = false(1, actionCount);
actionInstantaneousFormationStrong = false(1, actionCount);
actionRollingB3SensorPass = false(actionCount, ...
    protocol.horizonSteps);
actionRollingB3FormationPass = false(actionCount, ...
    protocol.horizonSteps);
actionDetails = cell(1, actionCount);
keys = cell(1, actionCount);
for actionIdx = 1:actionCount
    maskValue = actionIdx - 1;
    suspended = groups(logical(bitget( ...
        maskValue, 1:formationCount)));
    [adjacency, details] = ...
        selectTemporalCrossEdgeSuspensionPolicy( ...
            context, suspended, policyOptions);
    key = [sprintf('%d,', adjacency(:)), '|', ...
        sprintf('%.17g,', details.fusionWeightMatrix(:))];
    if any(strcmp(keys(1:max(actionIdx - 1, 0)), key))
        error('TemporalSuspension:InvalidBankContract', ...
            'Temporal-suspension subset produced a duplicate action.');
    end
    keys{actionIdx} = key;
    actionAdjacency(:, :, actionIdx) = adjacency;
    actionFusionWeights(:, :, actionIdx) = ...
        details.fusionWeightMatrix;
    actionNames{actionIdx} = details.actionName;
    actionSuspendedFormationIds{actionIdx} = suspended;
    actionSuspendedCrossEdgeCounts(actionIdx) = ...
        details.suspendedCrossEdgeCount;
    actionMessageCounts(actionIdx) = details.messageCount;
    actionMessageSavingCounts(actionIdx) = ...
        details.messageSavingCount;
    actionMessageSavingFractions(actionIdx) = ...
        details.messageSavingFraction;
    actionCrossFormationMessageCounts(actionIdx) = ...
        details.crossFormationMessageCount;
    actionInstantaneousSensorStrong(actionIdx) = ...
        details.instantaneousSensorStrongConnected;
    actionInstantaneousFormationStrong(actionIdx) = ...
        details.instantaneousFormationStrongConnected;
    actionRollingB3SensorPass(actionIdx, :) = ...
        details.rollingB3SensorPass;
    actionRollingB3FormationPass(actionIdx, :) = ...
        details.rollingB3FormationPass;
    actionDetails{actionIdx} = details;
end

networkDisagreementRisk = nan(1, actionCount);
networkDisagreementDetails = cell(1, actionCount);
retentionRisk = nan(1, actionCount);
retentionDetails = cell(1, actionCount);
minimumFormationCardinalityChange = nan(1, actionCount);
minimumReceiverCardinalityChange = nan(1, actionCount);
minimumSupportedLabelRetentionRatio = nan(1, actionCount);
decisionThresholdCrossingCount = nan(1, actionCount);
maximumExistenceDrift = nan(1, actionCount);
posteriorSafetyMask = false(1, actionCount);
posteriorSafetyScoredMask = false(1, actionCount);
if scorePosteriorSafety
    enumerationOptions = struct( ...
        'maximumIncomingCount', ...
            protocol.maximumIncomingCountForOutcomeEnumeration);
    for actionIdx = posteriorSafetyActionIndices
        [networkDisagreementRisk(actionIdx), ...
            networkDisagreementDetails{actionIdx}] = ...
                computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
                    context, actionAdjacency(:, :, actionIdx), ...
                    actionFusionWeights(:, :, actionIdx), ...
                    enumerationOptions);
    end
    referenceDistributions = ...
        networkDisagreementDetails{1}.receiverDistributions;
    retentionOptions = struct( ...
        'referenceSupportThreshold', ...
            protocol.referenceSupportThreshold, ...
        'decisionExistenceThreshold', ...
            protocol.decisionExistenceThreshold, ...
        'receiverTailFraction', ...
            protocol.retentionReceiverTailFraction, ...
        'receiverTailWeight', ...
            protocol.retentionReceiverTailWeight);
    for actionIdx = posteriorSafetyActionIndices
        [retentionRisk(actionIdx), retentionDetails{actionIdx}] = ...
            computeLmbReferenceExistenceRetentionRisk( ...
                referenceDistributions, ...
                networkDisagreementDetails{actionIdx}. ...
                    receiverDistributions, ...
                groupIds, retentionOptions);
        current = retentionDetails{actionIdx};
        minimumFormationCardinalityChange(actionIdx) = min( ...
            current.formationMeanCardinalityChange);
        minimumReceiverCardinalityChange(actionIdx) = min( ...
            current.expectedCardinalityChange);
        minimumSupportedLabelRetentionRatio(actionIdx) = min( ...
            current.minimumSupportedLabelRetentionRatio);
        decisionThresholdCrossingCount(actionIdx) = sum( ...
            current.decisionThresholdCrossingCount);
        maximumExistenceDrift(actionIdx) = max( ...
            current.normalizedExistenceDrift);
    end
    posteriorSafetyMask = ...
        retentionRisk <= protocol.maximumRetentionRisk + 1e-12 & ...
        minimumFormationCardinalityChange >= protocol. ...
            minimumFormationMeanCardinalityChange - 1e-12 & ...
        minimumSupportedLabelRetentionRatio >= protocol. ...
            minimumSupportedLabelRetentionRatio - 1e-12 & ...
        decisionThresholdCrossingCount <= protocol. ...
            maximumDecisionThresholdCrossingCount & ...
        all(actionRollingB3SensorPass, 2)' & ...
        all(actionRollingB3FormationPass, 2)';
    posteriorSafetyScoredMask( ...
        posteriorSafetyActionIndices) = true;
    posteriorSafetyMask(~posteriorSafetyScoredMask) = false;
    if ~posteriorSafetyMask(1)
        error('TemporalSuspension:InvalidBankContract', ...
            'Reference failed the temporal-suspension safety gate.');
    end
else
    posteriorSafetyMask(1) = true;
end

physical = logical(context.physicalAdjacency);
allPhysical = true;
allRowStochastic = true;
for actionIdx = 1:actionCount
    adjacency = actionAdjacency(:, :, actionIdx);
    weights = actionFusionWeights(:, :, actionIdx);
    allPhysical = allPhysical && ...
        ~any(adjacency(:) & ~physical(:));
    allRowStochastic = allRowStochastic && ...
        all(abs(sum(weights, 2) - 1) <= 1e-12) && ...
        all(weights(:) >= -1e-12);
end

bank = struct();
bank.contractVersion = ...
    'temporal-cross-edge-suspension-action-bank-v1';
bank.protocolId = protocol.id;
bank.nodeCount = nodeCount;
bank.formationCount = formationCount;
bank.groupIds = groupIds;
bank.actionCount = actionCount;
bank.referenceActionIndex = 1;
bank.actionNames = actionNames;
bank.actionSuspendedFormationIds = ...
    actionSuspendedFormationIds;
bank.actionAdjacency = actionAdjacency;
bank.actionFusionWeights = actionFusionWeights;
bank.actionSuspendedCrossEdgeCounts = ...
    actionSuspendedCrossEdgeCounts;
bank.actionMessageCounts = actionMessageCounts;
bank.actionMessageSavingCounts = actionMessageSavingCounts;
bank.actionMessageSavingFractions = actionMessageSavingFractions;
bank.actionCrossFormationMessageCounts = ...
    actionCrossFormationMessageCounts;
bank.actionInstantaneousSensorStrongConnected = ...
    actionInstantaneousSensorStrong;
bank.actionInstantaneousFormationStrongConnected = ...
    actionInstantaneousFormationStrong;
bank.actionRollingB3SensorPass = actionRollingB3SensorPass;
bank.actionRollingB3FormationPass = actionRollingB3FormationPass;
bank.actionDetails = actionDetails;
bank.networkDisagreementRisk = networkDisagreementRisk;
bank.networkDisagreementDetails = networkDisagreementDetails;
bank.retentionRisk = retentionRisk;
bank.retentionDetails = retentionDetails;
bank.minimumFormationCardinalityChange = ...
    minimumFormationCardinalityChange;
bank.minimumReceiverCardinalityChange = ...
    minimumReceiverCardinalityChange;
bank.minimumSupportedLabelRetentionRatio = ...
    minimumSupportedLabelRetentionRatio;
bank.decisionThresholdCrossingCount = ...
    decisionThresholdCrossingCount;
bank.maximumExistenceDrift = maximumExistenceDrift;
bank.posteriorSafetyScored = scorePosteriorSafety;
bank.posteriorSafetyScoringMode = posteriorSafetyScoringMode;
bank.posteriorSafetyRequestedActionIndices = ...
    posteriorSafetyActionIndices;
bank.posteriorSafetyScoredMask = posteriorSafetyScoredMask;
bank.actionPosteriorSafetyMask = posteriorSafetyMask;
bank.safeActionIndices = find(posteriorSafetyMask);
bank.safeNonreferenceActionCount = nnz(posteriorSafetyMask) - 1;
bank.actionWithinReferencePayload = ...
    actionMessageCounts <= actionMessageCounts(1);
bank.actionFormationIndex = zeros(1, actionCount);
bank.actionModeIndex = 1:actionCount;
bank.modeTrustWeights = actionMessageSavingFractions;
bank.actionPosteriorProxyAllowed = posteriorSafetyMask;
bank.actionPosteriorObjective = -retentionRisk;
bank.actionPayloadBytes = nan(1, actionCount);
bank.allPhysical = allPhysical;
bank.allRowStochastic = allRowStochastic;
bank.allMessageCountsNoGreaterThanReference = all( ...
    actionMessageCounts <= actionMessageCounts(1));
bank.allRollingB3SensorStrongConnected = all( ...
    actionRollingB3SensorPass(:));
bank.allRollingB3FormationStrongConnected = all( ...
    actionRollingB3FormationPass(:));
bank.oneStepStrongConnectivityRequired = false;
bank.oneStepDisagreementHardGateEnabled = false;
bank.truthUsed = any(cellfun( ...
    @(item) item.truthUsed, actionDetails));
bank.futureOutcomeUsed = any(cellfun( ...
    @(item) item.futureOutcomeUsed, actionDetails));
bank.openedDevelopmentEvidenceOnly = true;
bank.validationClaimAllowed = false;
end

function indices = validateSafetyActionIndices(value, actionCount)
indices = reshape(value, 1, []);
if isempty(indices) || any(~isfinite(indices)) || ...
        any(indices ~= round(indices)) || any(indices < 1) || ...
        any(indices > actionCount) || ...
        numel(unique(indices)) ~= numel(indices) || ...
        indices(1) ~= 1 || nnz(indices == 1) ~= 1
    error('TemporalSuspension:InvalidBankContract', ...
        ['posteriorSafetyActionIndices must be unique in-range ', ...
         'indices beginning with the reference action.']);
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
