function context = ...
        buildRiskFormationLightNetworkAnchorV132ExecutionContext( ...
            presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDRISKFORMATIONLIGHTNETWORKANCHORV132EXECUTIONCONTEXT Frozen V132 context.

protocol = getRiskFormationLightNetworkAnchorV132Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('RiskFormationLightNetworkAnchorV132:InvalidExecutionContext', ...
        'The V132 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'risk-formation-light-network-anchor-v132-context-v1';
context.capability = ...
    'risk-formation-light-network-anchor-v132-development';
context.action = ...
    'filter-risk-formation-light-network-anchor-v132-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
