function control = buildFormationBackboneBundleParetoRiskControl(context)
% BUILDFORMATIONBACKBONEBUNDLEPARETORISKCONTROL V39 finite-bank selector.
%
% V39 keeps the causal v38 proposal family, then solves a deterministic
% reference-constrained communication problem over the distinct routes that
% v38 already evaluated.  The registered reference is always in the bank.
% A sparse route is eligible only when all v38 hard safety checks pass and
% its exact current one-round network disagreement is no larger than the
% reference value.  Among eligible routes, v39 lexicographically maximizes
% message saving, minimizes network disagreement, and minimizes directed
% edge switches relative to the latest selected-topology history page.

policy = getFormationBackboneBundleParetoRiskPolicyConfig();
v38 = buildFormationBackboneBundleStaggeredRecoveryControl(context);
if ~v38.selectionUsesCurrentPosterior || ...
        ~v38.selectionUsesCurrentLinkReliability || ...
        ~v38.selectionUsesSelectedTopologyHistory || ...
        v38.truthUsed || v38.futureOutcomeUsed
    error('FormationBundleParetoRisk:InvalidRuntimeContract', ...
        'The v39 proposal generator is not causally attested.');
end

referenceRisk = v38.referenceScore.networkRisk;
referenceMessageCount = v38.referenceMessageCount;
previousAdjacency = logical( ...
    context.previousAdjacencyHistory(:, :, end));
bank = cell(1, 0);
bank = appendDistinctCandidate(bank, makeCandidate( ...
    'registered-reference', v38.referenceAdjacency, ...
    v38.referenceFusionWeights, v38.referencePolicyDetails, ...
    v38.referenceScore, zeros(1, 0), zeros(1, 0), ...
    referenceRisk, referenceMessageCount, previousAdjacency, ...
    context, policy));

if ~isempty(v38.incumbentFormationIds)
    bank = appendDistinctCandidate(bank, makeCandidate( ...
        'v38-incumbent', v38.incumbentAdjacency, ...
        v38.incumbentFusionWeights, v38.incumbentPolicyDetails, ...
        v38.incumbentScore, v38.incumbentFormationIds, ...
        zeros(1, 0), referenceRisk, referenceMessageCount, ...
        previousAdjacency, context, policy));
end

base = v38.baseControl;
for requestedIdx = 1:numel(base.requestedFormationIds)
    formationId = base.requestedFormationIds(requestedIdx);
    formationIdx = find(base.groups == formationId, 1, 'first');
    if isempty(formationIdx) || ...
            ~base.singleActionAvailableMask(formationIdx) || ...
            ~base.singleActionSafetyMask(formationIdx)
        continue;
    end
    bank = appendDistinctCandidate(bank, makeCandidate( ...
        'requested-safe-single', ...
        base.singleActionAdjacency{formationIdx}, ...
        base.singleActionFusionWeights{formationIdx}, ...
        base.singleActionPolicyDetails{formationIdx}, ...
        base.singleActionScores{formationIdx}, formationId, ...
        zeros(1, 0), referenceRisk, referenceMessageCount, ...
        previousAdjacency, context, policy));
end

for candidateIdx = 1:numel(v38.candidateScores)
    if ~v38.candidateAvailableMask(candidateIdx) || ...
            ~v38.candidateSafetyMask(candidateIdx)
        continue;
    end
    bank = appendDistinctCandidate(bank, makeCandidate( ...
        'safe-staggered-release', ...
        v38.candidateAdjacency{candidateIdx}, ...
        v38.candidateFusionWeights{candidateIdx}, ...
        v38.candidatePolicyDetails{candidateIdx}, ...
        v38.candidateScores{candidateIdx}, ...
        v38.releaseSchedule. ...
            candidateRetainedFormationIds{candidateIdx}, ...
        v38.releaseSchedule. ...
            candidateReleasedFormationIds{candidateIdx}, ...
        referenceRisk, referenceMessageCount, previousAdjacency, ...
        context, policy));
end

previousFormationIds = v38.baseControl.groups( ...
    v38.baseControl.previouslySuspendedMask);
for candidateIdx = 1:numel(bank)
    candidate = bank{candidateIdx};
    candidate.releasedFormationIds = setdiff( ...
        previousFormationIds, candidate.formationIds, 'stable');
    candidate.newlySuspendedFormationIds = setdiff( ...
        candidate.formationIds, previousFormationIds, 'stable');
    bank{candidateIdx} = candidate;
end
messageSavingCount = cellfun(@(candidate) ...
    candidate.messageSavingCount, bank);
networkRisk = cellfun(@(candidate) candidate.score.networkRisk, bank);
switchCount = cellfun(@(candidate) candidate.switchCount, bank);
ordinal = cellfun(@(candidate) candidate.ordinal, bank);
[selectedIdx, selectionDetails] = ...
    selectReferenceConstrainedParetoCandidateIndex( ...
        messageSavingCount, networkRisk, switchCount, ordinal, ...
        referenceRisk, policy.minimumMessageSavingCount);
selected = bank{selectedIdx};
sparseMask = selectionDetails.sparseMask;
riskFeasibleMask = selectionDetails.sparseMask & ...
    selectionDetails.riskConstraintPassedMask;
riskRejectedMask = selectionDetails.riskRejectedSparseMask;
noSparseProposal = ~any(sparseMask);
referenceFallbackUsed = selectedIdx == 1 && any(sparseMask);
if noSparseProposal
    selectionState = 'no-sparse-proposal';
elseif referenceFallbackUsed
    selectionState = 'all-sparse-proposals-risk-rejected';
else
    selectionState = 'sparse-proposal-selected';
end

if selected.score.networkRisk > referenceRisk
    error('FormationBundleParetoRisk:InvalidRuntimeAction', ...
        'The v39 selected route exceeds the reference network risk.');
end

control = struct();
control.contractVersion = ...
    'formation-backbone-bundle-pareto-risk-control-v1';
control.policyConfig = policy;
control.policyConfigSha256 = policy.canonicalSha256;
control.v38Control = v38;
control.candidateBank = bank;
control.candidateBankCanonicalSha256 = candidateBankSha256(bank);
control.selectionDetails = selectionDetails;
control.candidateCount = numel(bank);
control.sparseProposalCount = nnz(sparseMask);
control.referenceRiskFeasibleSparseCount = nnz(riskFeasibleMask);
control.referenceRiskRejectedSparseCount = nnz(riskRejectedMask);
control.selectedCandidateIndex = selectedIdx;
control.selectedCandidate = selected;
control.selectedAdjacency = selected.adjacency;
control.selectedFusionWeights = selected.fusionWeights;
control.selectedPolicyDetails = selected.policyDetails;
control.selectedScore = selected.score;
control.selectedFormationIds = selected.formationIds;
control.releasedFormationIds = selected.releasedFormationIds;
control.newlySuspendedFormationIds = ...
    selected.newlySuspendedFormationIds;
control.selectedProposalSource = selected.source;
control.selectedActionName = selected.actionName;
control.selectedMessageCount = selected.messageCount;
control.selectedMessageSavingCount = selected.messageSavingCount;
control.selectedSwitchCount = selected.switchCount;
control.referenceRisk = referenceRisk;
control.referenceMessageCount = referenceMessageCount;
control.previousFormationIds = previousFormationIds;
control.referenceSelected = selectedIdx == 1;
control.noSparseProposal = noSparseProposal;
control.referenceFallbackUsed = referenceFallbackUsed;
control.selectionState = selectionState;
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.truthUsed = false;
control.futureOutcomeUsed = false;
end

function candidate = makeCandidate( ...
        source, adjacency, fusionWeights, policyDetails, score, ...
        formationIds, releasedFormationIds, referenceRisk, ...
        referenceMessageCount, previousAdjacency, context, policy)
nodeCount = numel(context.localPosteriorBySensor);
adjacency = logical(adjacency);
messageCount = nnz(adjacency);
messageSavingCount = referenceMessageCount - messageCount;
weightSupport = adjacency | logical(eye(nodeCount));
if ~isstruct(policyDetails) || ~isscalar(policyDetails) || ...
        ~isstruct(score) || ~isscalar(score) || ...
        ~isfield(policyDetails, 'actionName') || ...
        ~isfield(policyDetails, 'rollingB3SensorPass') || ...
        ~isfield(policyDetails, 'rollingB3FormationPass') || ...
        ~isfield(score, 'networkRisk') || ...
        ~isscalar(score.networkRisk) || ~isfinite(score.networkRisk) || ...
        ~isfield(score, 'safe') || ~isequal(score.safe, true) || ...
        ~all(policyDetails.rollingB3SensorPass) || ...
        ~all(policyDetails.rollingB3FormationPass) || ...
        ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        any(diag(adjacency)) || ...
        any(adjacency(:) & ~logical(context.physicalAdjacency(:))) || ...
        messageSavingCount < 0 || ...
        ~isequal(size(fusionWeights), [nodeCount, nodeCount]) || ...
        any(~isfinite(fusionWeights(:))) || ...
        any(fusionWeights(:) < 0) || ...
        any(fusionWeights(:) > 0 & ~weightSupport(:)) || ...
        any(abs(sum(fusionWeights, 2) - 1) > 1e-12)
    error('FormationBundleParetoRisk:InvalidProposal', ...
        'A v39 proposal violates its registered hard constraints.');
end
candidate = struct();
candidate.source = source;
candidate.actionName = policyDetails.actionName;
candidate.provenanceSources = {source};
candidate.provenanceActionNames = {policyDetails.actionName};
candidate.provenanceFormationIds = {reshape(formationIds, 1, [])};
candidate.provenanceReleasedFormationIds = { ...
    reshape(releasedFormationIds, 1, [])};
candidate.adjacency = adjacency;
candidate.fusionWeights = fusionWeights;
candidate.policyDetails = policyDetails;
candidate.score = score;
candidate.formationIds = reshape(formationIds, 1, []);
candidate.releasedFormationIds = ...
    reshape(releasedFormationIds, 1, []);
candidate.newlySuspendedFormationIds = zeros(1, 0);
candidate.messageCount = messageCount;
candidate.messageSavingCount = messageSavingCount;
candidate.switchCount = nnz(adjacency ~= previousAdjacency);
candidate.sparse = ...
    messageSavingCount >= policy.minimumMessageSavingCount;
candidate.referenceRiskConstraintPassed = ...
    score.networkRisk <= referenceRisk;
end

function bank = appendDistinctCandidate(bank, candidate)
for candidateIdx = 1:numel(bank)
    incumbent = bank{candidateIdx};
    if isequal(candidate.adjacency, incumbent.adjacency) && ...
            isequaln(candidate.fusionWeights, incumbent.fusionWeights)
        if ~isequaln(candidate.score.networkRisk, ...
                incumbent.score.networkRisk) || ...
                ~isequal(candidate.score.safe, incumbent.score.safe) || ...
                ~isequal(candidate.policyDetails.rollingB3SensorPass, ...
                    incumbent.policyDetails.rollingB3SensorPass) || ...
                ~isequal(candidate.policyDetails.rollingB3FormationPass, ...
                    incumbent.policyDetails.rollingB3FormationPass)
            error('FormationBundleParetoRisk:InconsistentDuplicate', ...
                ['The same v39 route was evaluated with inconsistent ', ...
                'risk or safety metadata.']);
        end
        incumbent.provenanceSources = [ ...
            incumbent.provenanceSources, candidate.provenanceSources];
        incumbent.provenanceActionNames = [ ...
            incumbent.provenanceActionNames, ...
            candidate.provenanceActionNames];
        incumbent.provenanceFormationIds = [ ...
            incumbent.provenanceFormationIds, ...
            candidate.provenanceFormationIds];
        incumbent.provenanceReleasedFormationIds = [ ...
            incumbent.provenanceReleasedFormationIds, ...
            candidate.provenanceReleasedFormationIds];
        bank{candidateIdx} = incumbent;
        return;
    end
end
candidate.ordinal = numel(bank) + 1;
bank{end + 1} = candidate;
end

function sha256 = candidateBankSha256(bank)
payload = cell(1, numel(bank));
for candidateIdx = 1:numel(bank)
    candidate = bank{candidateIdx};
    payload{candidateIdx} = struct( ...
        'ordinal', candidate.ordinal, ...
        'source', candidate.source, ...
        'actionName', candidate.actionName, ...
        'provenanceSources', {candidate.provenanceSources}, ...
        'provenanceActionNames', {candidate.provenanceActionNames}, ...
        'provenanceFormationIds', {candidate.provenanceFormationIds}, ...
        'provenanceReleasedFormationIds', ...
            {candidate.provenanceReleasedFormationIds}, ...
        'adjacency', candidate.adjacency, ...
        'fusionWeights', candidate.fusionWeights, ...
        'formationIds', candidate.formationIds, ...
        'releasedFormationIds', candidate.releasedFormationIds, ...
        'newlySuspendedFormationIds', ...
            candidate.newlySuspendedFormationIds, ...
        'messageCount', candidate.messageCount, ...
        'messageSavingCount', candidate.messageSavingCount, ...
        'switchCount', candidate.switchCount, ...
        'networkRisk', candidate.score.networkRisk, ...
        'sparse', candidate.sparse, ...
        'referenceRiskConstraintPassed', ...
            candidate.referenceRiskConstraintPassed);
end
sha256 = computeCanonicalValueSha256(struct( ...
    'contractVersion', ...
        'formation-backbone-bundle-pareto-candidate-bank-v1', ...
    'candidate', {payload}));
end
