function context = buildUpstreamBoundaryReleaseV122ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDUPSTREAMBOUNDARYRELEASEV122EXECUTIONCONTEXT Frozen V122 context.

protocol = getUpstreamBoundaryReleaseV122Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('UpstreamBoundaryReleaseV122:InvalidExecutionContext', ...
        'The V122 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'upstream-boundary-release-v122-context-v1';
context.capability = 'upstream-boundary-release-v122-development';
context.action = 'filter-upstream-boundary-release-v122-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
