function [context, metadata] = ...
    buildFormationReliableKlaGeometryDevelopmentContext( ...
        presetName, seed)
% BUILDFORMATIONRELIABLEKLAGEOMETRYDEVELOPMENTCONTEXT
% Build a posterior-free structural context from a registered scene.
%
% This helper deliberately materializes the complete planned sensor and
% link-probability schedules before slicing the focus-start page.  It is a
% geometry-only development helper, not a formal runtime-observable loader.

if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isnumeric(seed) || ~isreal(seed) || ...
        ~isfinite(seed) || seed ~= round(seed)
    error('FormationKlaGeometryContext:InvalidInput', ...
        'The geometry-development context inputs are invalid.');
end
rng(seed, 'twister');
config = buildDynamicTopologyScenarioConfig(presetName);
[sensorTrajectories, ~] = ...
    generateMultiFormationTrajectories(config);
graph = buildDynamicTopologyGraphs(config, sensorTrajectories);
[pDropByEdge, ~] = buildDynamicTopologyLinkSchedule(config, graph);
currentTime = config.focusWindow(1);
nodeCount = config.numberOfSensors;

model = struct();
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', config.sensorGroupIds), ...
    'staticAdjacency', graph.staticAdjacency);
context = struct();
context.localPosteriorBySensor = cell(1, nodeCount);
context.model = model;
context.baseAdjacency = logical(graph.staticAdjacency);
context.physicalAdjacency = logical( ...
    graph.physicalAdjacency(:, :, currentTime));
context.currentTime = currentTime;
context.commConfig = struct( ...
    'forceDelivery', config.forceDelivery, ...
    'pDropByEdge', pDropByEdge(:, :, currentTime), ...
    'outageSchedule', getField(config, 'outageSchedule', []), ...
    'deliveryIndependenceAttested', true, ...
    'deliverySampler', [ ...
        'runEventTriggeredDistributedLmbFilter-simulateDelivery-', ...
        'independent-uniform-per-sender-receiver-time']);
context.triggerConfig = buildMixtureAwareKlaReferenceConfig();
context.previousAdjacencyHistory = ...
    buildReferenceHistory(context, nodeCount);
runtimeSemantics = ...
    validateReliableKlaMixingRuntimeSemantics(context.triggerConfig);
communicationSemantics = ...
    validateReliableKlaCommunicationRuntimeSemantics(context.commConfig);

inputPayload = struct( ...
    'presetName', presetName, 'seed', seed, ...
    'currentTime', currentTime, ...
    'sensorGroupIds', config.sensorGroupIds, ...
    'baseAdjacency', context.baseAdjacency, ...
    'physicalAdjacency', context.physicalAdjacency, ...
    'previousAdjacencyHistory', context.previousAdjacencyHistory, ...
    'pDropByEdge', context.commConfig.pDropByEdge, ...
    'runtimeSemanticsCanonicalSha256', ...
        runtimeSemantics.canonicalSha256, ...
    'communicationSemanticsCanonicalSha256', ...
        communicationSemantics.canonicalSha256);
metadata = struct();
metadata.contractVersion = ...
    'formation-reliable-kla-geometry-development-context-v1';
metadata.presetName = presetName;
metadata.seed = seed;
metadata.currentTime = currentTime;
metadata.nodeCount = nodeCount;
metadata.formationCount = config.formationCount;
metadata.sensorGroupIds = config.sensorGroupIds;
metadata.inputCanonicalSha256 = ...
    computeCanonicalValueSha256(inputPayload);
metadata.runtimeSemanticsCanonicalSha256 = ...
    runtimeSemantics.canonicalSha256;
metadata.communicationSemanticsCanonicalSha256 = ...
    communicationSemantics.canonicalSha256;
metadata.fullPlannedSensorGeometryMaterialized = true;
metadata.fullPlannedLinkProbabilityScheduleMaterialized = true;
metadata.formalRuntimeObservableBoundaryPassed = false;
metadata.posteriorUsed = false;
metadata.truthUsed = false;
metadata.measurementUsed = false;
metadata.targetTrajectoryGenerated = false;
metadata.realizedDeliveryUniformsUsed = false;
metadata.developmentEvidenceOnly = true;
end

function history = buildReferenceHistory(context, nodeCount)
routeContext = context;
routeContext.directedMessageBudget = 2 * nodeCount;
[referenceAdjacency, ~] = ...
    selectFormationBackboneResidualTourPolicy(routeContext);
history = repmat(referenceAdjacency, 1, 1, 2);
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
