function context = buildInitialDynamicRouteFreezeV237ExecutionContext( ...
        presetName, seed, measurementTimeCount)
% BUILDINITIALDYNAMICROUTEFREEZEV237EXECUTIONCONTEXT Full episode.

protocol = getInitialDynamicRouteFreezeV237Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~isscalar(seed) || ~ismember(seed, protocol.allowedSeeds) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount < 1 || ...
        measurementTimeCount ~= round(measurementTimeCount)
    error('InitialDynamicRouteFreezeV237:InvalidExecutionContextInput', ...
        'V237 requires a registered scene, seed and time axis.');
end
context = struct();
context.contractVersion = ...
    'initial-dynamic-route-freeze-v237-context-v1';
context.capability = ...
    'initial-dynamic-route-freeze-v237-development';
context.action = ...
    'filter-initial-dynamic-route-freeze-v237-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.splitName = protocol.splitName;
context.armId = protocol.armId;
context.measurementTimeCount = measurementTimeCount;
context.policyName = protocol.policyName;
context.developmentEvidenceOnly = true;
end
