function control = buildFormationGatewayPruningThresholdControl( ...
        context, sourceV32Preflight, options)
% BUILDFORMATIONGATEWAYPRUNINGTHRESHOLDCONTROL Source-only v34 probe.
%
% The three frozen useful-at-0.05 v32 routes are evaluated on a low-weight
% grid to locate label survival below the rejected v33 trust range.

if nargin < 3 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('GatewayPruningThreshold:InvalidOptions', ...
        'The frozen v34 controller does not accept option overrides.');
end
protocol = getFormationGatewayPruningThresholdProtocol();
nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || ...
        formationCount > protocol.maximumFormationCount || ...
        ~isfield(context, 'previousAdjacencyHistory') || ...
        size(context.previousAdjacencyHistory, 3) < 2 || ...
        ~isstruct(sourceV32Preflight) || ...
        ~isfield(sourceV32Preflight, 'gatewayControl')
    error('GatewayPruningThreshold:InvalidContext', ...
        'Gateway pruning-threshold context is invalid.');
end
source = sourceV32Preflight.gatewayControl;
sourceIndices = reshape(protocol.sourceCandidateIndices, 1, []);
if ~strcmp(source.contractVersion, ...
        'formation-alternative-gateway-control-v1') || ...
        source.nodeCount ~= nodeCount || ...
        source.formationCount ~= formationCount || ...
        max(sourceIndices) > source.candidateCount || ...
        ~source.referenceScore.safe || ...
        ~source.referenceFallbackUsed
    error('GatewayPruningThreshold:InvalidSource', ...
        'Frozen v32 source is incompatible with v34.');
end

[referenceAdjacency, referenceDetails] = ...
    selectTemporalCrossEdgeSuspensionPolicy( ...
        context, zeros(1, 0), struct( ...
            'dominantWeight', protocol.dominantWeight, ...
            'residualWeight', protocol.referenceResidualWeight));
referenceWeights = referenceDetails.fusionWeightMatrix;
if ~isequal(referenceAdjacency, source.referenceAdjacency) || ...
        ~isequal(referenceWeights, source.referenceFusionWeights)
    error('GatewayPruningThreshold:ReferenceDrift', ...
        'Current reference route differs from frozen v32.');
end
referenceScore = source.referenceScore;
referenceDistributions = ...
    referenceScore.networkDetails.receiverDistributions;
referenceFormationAdjacency = collapseToFormations( ...
    referenceAdjacency, groupIds);
referenceResidualSources = reshape( ...
    referenceDetails.residualSourcesByReceiver, 1, []);
weightGrid = reshape(protocol.lowResidualWeightGrid, 1, []);
candidateCount = numel(sourceIndices);
levelCount = numel(weightGrid);

routeAdjacency = cell(candidateCount, levelCount);
routeWeights = cell(candidateCount, levelCount);
routeDetails = cell(candidateCount, levelCount);
routeScores = cell(candidateCount, levelCount);
routeImprovement = nan(candidateCount, levelCount);
routeSafe = false(candidateCount, levelCount);
routeUseful = false(candidateCount, levelCount);
routeEligible = false(candidateCount, levelCount);
changedCrossReceivers = cell(1, candidateCount);
for candidateCursor = 1:candidateCount
    sourceCandidateIdx = sourceIndices(candidateCursor);
    selection = source.candidateSelections(sourceCandidateIdx);
    candidateSources = reshape( ...
        selection.residualSourcesByReceiver, 1, []);
    crossMask = groupIds ~= groupIds(candidateSources);
    changed = find(crossMask & ...
        candidateSources ~= referenceResidualSources);
    if numel(changed) ~= 2 || ...
            selection.referenceCutChangeCount ~= 1
        error('GatewayPruningThreshold:InvalidSourceRoute', ...
            'A frozen source route is not a radius-one gateway change.');
    end
    changedCrossReceivers{candidateCursor} = changed;
    for levelIdx = 1:levelCount
        residualWeights = protocol.referenceResidualWeight * ...
            ones(1, nodeCount);
        residualWeights(changed) = weightGrid(levelIdx);
        [adjacency, weights, details] = ...
            buildBackbonePreservingResidualRoute( ...
                context, referenceDetails.dominantAdjacency, ...
                selection.residualAdjacency, ...
                protocol.dominantWeight, residualWeights);
        [sensorPass, formationPass] = rollingB3Pass( ...
            context.previousAdjacencyHistory, ...
            cat(3, adjacency, referenceAdjacency, ...
                referenceAdjacency), groupIds);
        if nnz(adjacency) ~= nnz(referenceAdjacency) || ...
                ~isequal(collapseToFormations( ...
                    adjacency, groupIds), ...
                    referenceFormationAdjacency) || ...
                ~isequal(details.dominantSourcesByReceiver, ...
                    referenceDetails.dominantSourcesByReceiver) || ...
                ~all(sensorPass) || ~all(formationPass)
            error('GatewayPruningThreshold:InvalidCandidate', ...
                'A low-weight gateway route violates a structural gate.');
        end
        score = scoreRoute( ...
            context, adjacency, weights, ...
            referenceDistributions, groupIds, protocol);
        improvement = disagreementImprovement( ...
            referenceScore.networkRisk, score.networkRisk);
        safe = score.safe;
        useful = improvement >= ...
            protocol.minimumDisagreementImprovementFraction - 1e-12;

        routeAdjacency{candidateCursor, levelIdx} = adjacency;
        routeWeights{candidateCursor, levelIdx} = weights;
        details.rollingB3SensorPass = sensorPass;
        details.rollingB3FormationPass = formationPass;
        routeDetails{candidateCursor, levelIdx} = details;
        routeScores{candidateCursor, levelIdx} = score;
        routeImprovement(candidateCursor, levelIdx) = improvement;
        routeSafe(candidateCursor, levelIdx) = safe;
        routeUseful(candidateCursor, levelIdx) = useful;
        routeEligible(candidateCursor, levelIdx) = safe && useful;
    end
end

maximumSafeWeight = nan(1, candidateCount);
minimumUsefulWeight = nan(1, candidateCount);
for candidateCursor = 1:candidateCount
    safeLevels = find(routeSafe(candidateCursor, :));
    usefulLevels = find(routeUseful(candidateCursor, :));
    if ~isempty(safeLevels)
        maximumSafeWeight(candidateCursor) = max( ...
            weightGrid(safeLevels));
    end
    if ~isempty(usefulLevels)
        minimumUsefulWeight(candidateCursor) = min( ...
            weightGrid(usefulLevels));
    end
end

[selectedCandidateCursor, selectedLevelIdx] = ...
    selectEligibleRoute(routeEligible, routeImprovement, ...
        weightGrid, sourceIndices);
if isnan(selectedCandidateCursor)
    selectedSourceCandidateIndex = NaN;
    selectedResidualWeight = NaN;
    selectedAdjacency = referenceAdjacency;
    selectedWeights = referenceWeights;
    selectedDetails = referenceDetails;
    selectedScore = referenceScore;
    selectedActionName = 'reference';
else
    selectedSourceCandidateIndex = ...
        sourceIndices(selectedCandidateCursor);
    selectedResidualWeight = weightGrid(selectedLevelIdx);
    selectedAdjacency = ...
        routeAdjacency{selectedCandidateCursor, selectedLevelIdx};
    selectedWeights = ...
        routeWeights{selectedCandidateCursor, selectedLevelIdx};
    selectedDetails = ...
        routeDetails{selectedCandidateCursor, selectedLevelIdx};
    selectedScore = ...
        routeScores{selectedCandidateCursor, selectedLevelIdx};
    selectedActionName = sprintf( ...
        'gateway-threshold-c%d-w%s', ...
        selectedSourceCandidateIndex, strrep(sprintf('%.5f', ...
            selectedResidualWeight), '.', 'p'));
end
selectedImprovement = disagreementImprovement( ...
    referenceScore.networkRisk, selectedScore.networkRisk);
if nnz(selectedAdjacency) ~= nnz(referenceAdjacency) || ...
        ~isequal(collapseToFormations(selectedAdjacency, groupIds), ...
            referenceFormationAdjacency) || ...
        ~selectedScore.safe || ...
        (~isnan(selectedCandidateCursor) && ...
         selectedImprovement < ...
            protocol.minimumDisagreementImprovementFraction - 1e-12)
    error('GatewayPruningThreshold:InvalidSelection', ...
        'Selected low-weight gateway route violates an invariant.');
end

control = struct();
control.contractVersion = ...
    'formation-gateway-pruning-threshold-control-v1';
control.protocolId = protocol.id;
control.nodeCount = nodeCount;
control.formationCount = formationCount;
control.groupIds = groupIds;
control.groups = groups;
control.referenceAdjacency = referenceAdjacency;
control.referenceFusionWeights = referenceWeights;
control.referencePolicyDetails = referenceDetails;
control.referenceScore = referenceScore;
control.referenceFormationAdjacency = referenceFormationAdjacency;
control.sourceV32CandidateBankSha256 = source.candidateBankSha256;
control.sourceCandidateIndices = sourceIndices;
control.lowResidualWeightGrid = weightGrid;
control.changedCrossReceivers = changedCrossReceivers;
control.routeAdjacency = routeAdjacency;
control.routeFusionWeights = routeWeights;
control.routeDetails = routeDetails;
control.routeScores = routeScores;
control.routeDisagreementImprovementFraction = routeImprovement;
control.routeSafetyMask = routeSafe;
control.routeUsefulnessMask = routeUseful;
control.routeEligibilityMask = routeEligible;
control.safeRouteCount = nnz(routeSafe);
control.usefulRouteCount = nnz(routeUseful);
control.eligibleRouteCount = nnz(routeEligible);
control.maximumSafeWeightByCandidate = maximumSafeWeight;
control.minimumUsefulWeightByCandidate = minimumUsefulWeight;
control.selectedCandidateCursor = selectedCandidateCursor;
control.selectedLevelIndex = selectedLevelIdx;
control.selectedSourceCandidateIndex = selectedSourceCandidateIndex;
control.selectedResidualWeight = selectedResidualWeight;
control.selectedAdjacency = selectedAdjacency;
control.selectedFusionWeights = selectedWeights;
control.selectedRouteDetails = selectedDetails;
control.selectedScore = selectedScore;
control.selectedDisagreementImprovementFraction = ...
    selectedImprovement;
control.selectedActionName = selectedActionName;
control.referenceFallbackUsed = isnan(selectedCandidateCursor);
control.messageCountParityWithReference = ...
    nnz(selectedAdjacency) == nnz(referenceAdjacency);
control.formationGraphParityWithReference = isequal( ...
    collapseToFormations(selectedAdjacency, groupIds), ...
    referenceFormationAdjacency);
control.dominantRouteParityWithReference = isequal( ...
    selectedDetails.dominantSourcesByReceiver, ...
    referenceDetails.dominantSourcesByReceiver);
control.selectedRollingB3SensorPass = getField( ...
    selectedDetails, 'rollingB3SensorPass', ...
    referenceDetails.rollingB3SensorPass);
control.selectedRollingB3FormationPass = getField( ...
    selectedDetails, 'rollingB3FormationPass', ...
    referenceDetails.rollingB3FormationPass);
control.evaluatedRouteCount = candidateCount * levelCount;
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.truthUsed = false;
control.futureOutcomeUsed = false;
control.validationClaimAllowed = false;
end

function [candidateCursor, levelIdx] = selectEligibleRoute( ...
        eligible, improvement, weightGrid, sourceIndices)
candidateCursor = NaN;
levelIdx = NaN;
best = [-inf, -inf, -inf];
for candidate = 1:size(eligible, 1)
    for level = 1:size(eligible, 2)
        if ~eligible(candidate, level)
            continue;
        end
        key = [improvement(candidate, level), ...
            weightGrid(level), -sourceIndices(candidate)];
        if lexicographicallyGreater(key, best)
            best = key;
            candidateCursor = candidate;
            levelIdx = level;
        end
    end
end
end

function value = lexicographicallyGreater(left, right)
value = false;
for idx = 1:numel(left)
    if left(idx) > right(idx) + 1e-12
        value = true;
        return;
    elseif left(idx) < right(idx) - 1e-12
        return;
    end
end
end

function score = scoreRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, protocol)
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, struct( ...
            'maximumIncomingCount', ...
                protocol.maximumIncomingCountForOutcomeEnumeration));
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, groupIds, struct( ...
            'referenceSupportThreshold', ...
                protocol.referenceSupportThreshold, ...
            'decisionExistenceThreshold', ...
                protocol.decisionExistenceThreshold, ...
            'receiverTailFraction', ...
                protocol.retentionReceiverTailFraction, ...
            'receiverTailWeight', ...
                protocol.retentionReceiverTailWeight));
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= ...
        protocol.minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= ...
        protocol.minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= ...
        protocol.maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'retentionRisk', retentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function value = disagreementImprovement(referenceRisk, candidateRisk)
value = (referenceRisk - candidateRisk) / max(referenceRisk, eps);
end

function [sensorPass, formationPass] = ...
        rollingB3Pass(previousHistory, sequence, groupIds)
history = logical(previousHistory(:, :, end-1:end));
sensorPass = false(1, size(sequence, 3));
formationPass = false(1, size(sequence, 3));
for stepIdx = 1:size(sequence, 3)
    pages = cat(3, history, sequence(:, :, stepIdx));
    window = any(pages(:, :, max(1, end-2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = sequence(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
