function context = ...
        buildReferenceAnchoredBurstRoleScheduleV144ExecutionContext( ...
            presetName, seed, phase, currentTime, ...
            referenceCarrierMode, actionSpec)
% BUILDREFERENCEANCHOREDBURSTROLESCHEDULEV144EXECUTIONCONTEXT Permit V144.

protocol = getReferenceAnchoredBurstRoleScheduleV144Protocol();
phase = lower(strrep(char(phase), '_', '-'));
referenceCarrierMode = lower(strrep( ...
    char(referenceCarrierMode), '_', '-'));
caseInfo = resolveCase(protocol, presetName);
anchorTime = resolveSetTrustSequenceV134PilotAnchor(caseInfo, protocol);
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~ismember(seed, protocol.developmentSeeds) || ...
        ~ismember(phase, {'reference', 'candidate'}) || ...
        ~isscalar(currentTime) || currentTime ~= anchorTime || ...
        ~ismember(referenceCarrierMode, protocol.referenceCarrierModes)
    error('ReferenceAnchoredBurstV144:InvalidContext', ...
        'The V144 execution-context request is outside the screen.');
end
actionSpec = validateSetTrustSequenceActionV134( ...
    actionSpec, 'candidate-continuation', caseInfo, protocol);
enabled = strcmp(phase, 'candidate');
context = struct( ...
    'contractVersion', ...
        'reference-anchored-burst-v144-execution-context-v1', ...
    'capability', 'reference-anchored-burst-v144-development', ...
    'action', 'filter-reference-anchored-burst-v144-development', ...
    'protocolId', protocol.id, 'phase', phase, ...
    'presetName', presetName, 'seed', seed, ...
    'currentTime', currentTime, 'horizonSteps', caseInfo.horizonSteps, ...
    'measurementTimeCount', currentTime + caseInfo.horizonSteps - 1, ...
    'policyName', protocol.outcomePolicyName, ...
    'referenceCarrierMode', referenceCarrierMode, ...
    'actionSpec', actionSpec, 'scheduleEnabled', enabled, ...
    'lineageRelayEnabled', enabled, ...
    'intraFormationWorkingPayloadEnabled', enabled, ...
    'roleMultiplexingEnabled', enabled, ...
    'rolePeriodPages', protocol.roleSchedule.periodPages, ...
    'roleReferencePhaseOffset', ...
        protocol.roleSchedule.referencePhaseOffset, ...
    'roleAnchorTime', currentTime, ...
    'singlePayloadWireEnforced', true, ...
    'postFusionLabelReadoutEnabled', enabled, ...
    'predictiveEvidenceReadoutOnlyEnabled', enabled, ...
    'workingStateMutationAllowed', false, ...
    'exactStaticStateFallbackClaimAllowed', false, ...
    'onlineReselectionEnabled', false, ...
    'developmentEvidenceOnly', true);
end

function caseInfo = resolveCase(protocol, presetName)
caseIdx = find(strcmp({protocol.scaleCases.presetName}, presetName), 1);
if isempty(caseIdx)
    error('ReferenceAnchoredBurstV144:InvalidPreset', ...
        'The preset is outside the V144 screen.');
end
caseInfo = protocol.scaleCases(caseIdx);
end

