function context = ...
        buildTemporallyBalancedMinimumBackboneV272ExecutionContext( ...
            presetName, seed, measurementTimeCount, sourceWindowStartTime)
% BUILDTEMPORALLYBALANCEDMINIMUMBACKBONEV272EXECUTIONCONTEXT Dev permit.

if nargin < 4 || isempty(sourceWindowStartTime)
    sourceWindowStartTime = 1;
end
protocol = getTemporallyBalancedMinimumBackboneV272Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~ismember(seed, protocol.allowedSeeds) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount < 1 || ...
        measurementTimeCount ~= round(measurementTimeCount) || ...
        ~isscalar(sourceWindowStartTime) || ...
        ~isfinite(sourceWindowStartTime) || ...
        sourceWindowStartTime < 1 || ...
        sourceWindowStartTime > measurementTimeCount || ...
        sourceWindowStartTime ~= round(sourceWindowStartTime)
    error('TemporallyBalancedBackboneV272:InvalidExecutionContextInput', ...
        'V272 requires a registered scene, seed and source window.');
end
context = struct();
context.contractVersion = ...
    'temporally-balanced-minimum-backbone-v272-context-v1';
context.capability = ...
    'temporally-balanced-minimum-backbone-v272-development';
context.action = ...
    'filter-temporally-balanced-minimum-backbone-v272-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = protocol.armId;
context.measurementTimeCount = measurementTimeCount;
context.sourceWindowStartTime = sourceWindowStartTime;
context.policyName = protocol.policyName;
context.developmentEvidenceOnly = true;
end
