function context = buildSetTrustSequenceV134ExecutionContext( ...
        presetName, seed, phase, currentTime, ...
        referenceCarrierMode, actionSpec)
% BUILDSETTRUSTSEQUENCEV134EXECUTIONCONTEXT Development headroom permit.

protocol = getSetTrustSequenceV134Protocol();
phase = lower(strrep(char(phase), '_', '-'));
referenceCarrierMode = lower(strrep( ...
    char(referenceCarrierMode), '_', '-'));
caseInfo = resolveCase(protocol, presetName);
anchorTime = resolvePilotAnchor(caseInfo, protocol);
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~ismember(seed, protocol.developmentSeeds) || ...
        ~ismember(phase, { ...
            'reference-prefix', 'reference-continuation', ...
            'candidate-continuation'}) || ...
        ~isscalar(currentTime) || currentTime ~= anchorTime || ...
        ~ismember(referenceCarrierMode, protocol.referenceCarrierModes)
    error('V134SetTrustExecution:InvalidContext', ...
        'The V134 execution-context request is outside the protocol.');
end
actionSpec = validateSetTrustSequenceActionV134( ...
    actionSpec, phase, caseInfo, protocol);
scheduleEnabled = strcmp(phase, 'candidate-continuation');
if strcmp(phase, 'reference-prefix')
    measurementTimeCount = currentTime;
else
    measurementTimeCount = currentTime + caseInfo.horizonSteps - 1;
end

context = struct( ...
    'contractVersion', ...
        'set-trust-sequence-v134-execution-context-v1', ...
    'capability', 'set-trust-sequence-v134-headroom', ...
    'action', 'filter-set-trust-sequence-v134-headroom', ...
    'protocolId', protocol.id, ...
    'phase', phase, ...
    'presetName', presetName, ...
    'seed', seed, ...
    'currentTime', currentTime, ...
    'horizonSteps', caseInfo.horizonSteps, ...
    'measurementTimeCount', measurementTimeCount, ...
    'policyName', protocol.outcomePolicyName, ...
    'referenceCarrierMode', referenceCarrierMode, ...
    'actionSpec', actionSpec, ...
    'scheduleEnabled', logical(scheduleEnabled), ...
    'onlineReselectionEnabled', false, ...
    'developmentEvidenceOnly', true);
end

function caseInfo = resolveCase(protocol, presetName)
caseIdx = find(strcmp({protocol.scaleCases.presetName}, presetName), 1);
if isempty(caseIdx)
    error('V134SetTrustExecution:InvalidPreset', ...
        'The preset is outside the V134 scale contract.');
end
caseInfo = protocol.scaleCases(caseIdx);
end

function anchorTime = resolvePilotAnchor(caseInfo, protocol)
config = buildDynamicTopologyScenarioConfig(caseInfo.presetName);
window = reshape(config.focusWindow, 1, []);
anchorTime = round(window(1) + ...
    protocol.pilotAnchorQuantileWithinFocusWindow * ...
        (window(2) - window(1)));
end
