function context = ...
    buildPositiveNetAddressablePayloadV97ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDPOSITIVENETADDRESSABLEPAYLOADV97EXECUTIONCONTEXT Development scope.

protocol = getPositiveNetAddressablePayloadV97Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('PositiveNetAddressableV97:InvalidExecutionContext', ...
        'The V97 execution context input is invalid.');
end

context = struct();
context.contractVersion = ...
    'positive-net-addressable-payload-v97-context-v1';
context.capability = ...
    'positive-net-addressable-payload-v97-development';
context.action = ...
    'filter-positive-net-addressable-payload-v97-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.developmentEvidenceOnly = true;
end
