function [config, details] = ...
    buildFormationB4V53FixedTriggerConfig(armId, nodeCount)
% BUILDFORMATIONB4V53FIXEDTRIGGERCONFIG Register V53 runtime policy.

protocol = getFormationB4V53RuntimeProtocol();
if nargin ~= 2 || ~strcmp(armId, protocol.candidateArmId) || ...
        ~isscalar(nodeCount) || nodeCount < 1 || ...
        nodeCount ~= round(nodeCount)
    error('FormationB4V53TriggerConfig:InvalidInput', ...
        'The V53 arm and a positive sensor count are required.');
end
[config, ~] = buildFormationB4V46FixedTriggerConfig( ...
    protocol.parentRouteArmId, nodeCount);
config.topologyPolicyName = ...
    'selectFormationB4V53SynchronizedRuntimePolicy';
config.topologyPolicyFcn = ...
    @selectFormationB4V53SynchronizedRuntimePolicy;
parentHistoryDepth = 2;
if isfield(config, 'topologyPolicyHistoryDepth') && ...
        ~isempty(config.topologyPolicyHistoryDepth)
    parentHistoryDepth = config.topologyPolicyHistoryDepth;
end
config.topologyPolicyHistoryDepth = max( ...
    parentHistoryDepth, protocol.pulseHistoryDepth);

details = struct();
details.contractVersion = ...
    'formation-b4-v53-fixed-trigger-config-v1';
details.armId = armId;
details.parentArmId = protocol.parentRouteArmId;
details.nodeCount = nodeCount;
details.topologyPolicyHistoryDepth = ...
    config.topologyPolicyHistoryDepth;
end
