function context = ...
        buildEventWindowResidualReinforcementV258ExecutionContext( ...
            presetName, seed, measurementTimeCount)
% BUILDEVENTWINDOWRESIDUALREINFORCEMENTV258EXECUTIONCONTEXT Mechanism run.

protocol = getEventWindowResidualReinforcementV258Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~ismember(seed, protocol.allowedSeeds) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount < protocol.activationWindow(2) || ...
        measurementTimeCount ~= round(measurementTimeCount)
    error('EventWindowResidualV258:InvalidExecutionContextInput', ...
        'V258 requires its registered scene, seed and complete event window.');
end
context = struct();
context.contractVersion = ...
    'event-window-residual-reinforcement-v258-context-v1';
context.capability = ...
    'event-window-residual-reinforcement-v258-mechanism';
context.action = ...
    'filter-event-window-residual-reinforcement-v258-mechanism';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = protocol.armId;
context.measurementTimeCount = measurementTimeCount;
context.policyName = protocol.policyName;
context.mechanismEvidenceOnly = true;
context.developmentEvidenceOnly = true;
end
