function attestation = buildRollingSafeReferenceSwitchAttestation( ...
        adjacency, details, actionCode, physicalAdjacency)
% BUILDROLLINGSAFEREFERENCESWITCHATTESTATION Preserve raw arm evidence.
%
% The stored attestation deliberately contains the raw matrices and safety
% diagnostics needed to re-audit an evaluated arm.  Downstream evidence
% code must derive availability and strict nominal-free status from this
% structure instead of trusting the selector's convenience booleans.

requiredFields = { ...
    'actionSequenceCode', 'actionSequenceRelativeTime', 'messageCount', ...
    'fusionWeightMatrix', 'sourceWeight', ...
    'selectedSourcesByReceiver', ...
    'nominalProjectionFeasible', 'repairProjectionAttempted', ...
    'repairTriggered', 'payloadEmergencyUsed', ...
    'payloadLimitPassed', 'topologyInfeasible', ...
    'sensorWindowStrongConnected', ...
    'formationWindowStrongConnected', ...
    'successorSensorStrongConnected', ...
    'successorFormationStrongConnected', ...
    'oneStepTopologyReserveChecked', ...
    'oneStepTopologyReservePassed', ...
    'truthUsed', 'actionSequenceTruthUsed'};
if ~isstruct(details) || ~all(isfield(details, requiredFields))
    error('RollingSafeReferenceSwitch:InvalidAlternativeDiagnostics', ...
        'Cannot attest an arm with incomplete raw diagnostics.');
end

attestation = struct();
attestation.contractVersion = ...
    'rolling-safe-reference-switch-raw-attestation-v1';
attestation.actionCode = actionCode;
attestation.actionSequenceCode = details.actionSequenceCode;
attestation.actionSequenceRelativeTime = ...
    details.actionSequenceRelativeTime;
attestation.messageCount = details.messageCount;
attestation.adjacency = adjacency;
attestation.physicalAdjacency = physicalAdjacency;
attestation.fusionWeightMatrix = details.fusionWeightMatrix;
attestation.sourceWeight = details.sourceWeight;
attestation.selectedSourcesByReceiver = ...
    details.selectedSourcesByReceiver;
for fieldIdx = 7:numel(requiredFields)
    fieldName = requiredFields{fieldIdx};
    attestation.(fieldName) = details.(fieldName);
end
attestation.diverseObservableAlternativeRequested = getField( ...
    details, 'diverseObservableAlternativeRequested', NaN);
attestation.diverseObservableAlternativeFeasible = getField( ...
    details, 'diverseObservableAlternativeFeasible', NaN);
attestation.diverseObservableChangedAction = getField( ...
    details, 'diverseObservableChangedAction', NaN);
attestation.diverseObservableBannedReceiver = getField( ...
    details, 'diverseObservableBannedReceiver', NaN);
attestation.diverseObservableBannedSender = getField( ...
    details, 'diverseObservableBannedSender', NaN);
attestation.diverseObservableDefaultSelectedSources = getField( ...
    details, 'diverseObservableDefaultSelectedSources', []);
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
