function state = buildPolicyInducedContinuationStateV212( ...
        sourceScreenPath, branchTime, options)
% BUILDPOLICYINDUCEDCONTINUATIONSTATEV212 Extract a causal branch state.
%
% The source screen already captured policy-induced local posteriors and
% executed topology.  V212 carries only the pre-branch posterior and the two
% preceding selected/delivered topology pages into a shorter continuation.

if nargin < 3 || isempty(options)
    options = struct();
end
historyDepth = getField(options, 'historyDepth', 2);
sourceOutcomeIndex = getField(options, 'sourceOutcomeIndex', 0);
if ~ischar(sourceScreenPath) || exist(sourceScreenPath, 'file') ~= 2 || ...
        ~isscalar(branchTime) || ~isfinite(branchTime) || ...
        branchTime < 1 || branchTime ~= round(branchTime) || ...
        ~isscalar(historyDepth) || historyDepth ~= 2 || ...
        ~isscalar(sourceOutcomeIndex) || ...
        ~isfinite(sourceOutcomeIndex) || ...
        sourceOutcomeIndex < 0 || ...
        sourceOutcomeIndex ~= round(sourceOutcomeIndex)
    error('PolicyContinuationStateV212:InvalidRequest', ...
        'A captured screen, integer branch time and two-page history are required.');
end
loaded = load(sourceScreenPath, 'screen');
screen = loaded.screen;
requiredScreen = {'presetName', 'seed', 'currentTime', ...
    'returnTimes', 'cachePath', 'outcomes', 'records', ...
    'sensorGroupIds'};
if ~isstruct(screen) || ~isscalar(screen) || ...
        ~all(isfield(screen, requiredScreen))
    error('PolicyContinuationStateV212:ScreenContract', ...
        'The source screen is malformed.');
end
branchPage = find(screen.returnTimes == branchTime);
if numel(branchPage) ~= 1
    error('PolicyContinuationStateV212:BranchTime', ...
        'The branch time must name exactly one captured page.');
end
if sourceOutcomeIndex == 0
    sourceOutcomeIndex = find(strncmp( ...
        {screen.records.actionName}, ...
        'v99-online-positive-net-', 24));
end
if numel(sourceOutcomeIndex) ~= 1 || ...
        sourceOutcomeIndex < 1 || ...
        sourceOutcomeIndex > numel(screen.outcomes)
    error('PolicyContinuationStateV212:OutcomeIndex', ...
        'The source policy arm must be unique.');
end
outcome = screen.outcomes(sourceOutcomeIndex);
requiredOutcome = {'localPosteriorSnapshotsByTime', ...
    'selectedAdjacency', 'deliveredAdjacency'};
if ~all(isfield(outcome, requiredOutcome)) || ...
        numel(outcome.localPosteriorSnapshotsByTime) < branchPage || ...
        isempty(outcome.localPosteriorSnapshotsByTime{branchPage}) || ...
        size(outcome.selectedAdjacency, 3) < branchPage || ...
        size(outcome.deliveredAdjacency, 3) < branchPage
    error('PolicyContinuationStateV212:MissingCapture', ...
        'The source arm lacks the posterior or topology capture.');
end
if exist(screen.cachePath, 'file') ~= 2
    error('PolicyContinuationStateV212:MissingCache', ...
        'The source screen continuation cache is unavailable.');
end
cacheLoaded = load(screen.cachePath, 'behaviorBundle');
if ~isfield(cacheLoaded, 'behaviorBundle')
    error('PolicyContinuationStateV212:CacheContract', ...
        'The source continuation cache is malformed.');
end
bundle = cacheLoaded.behaviorBundle;
if ~isfield(bundle, 'snapshotTimes') || ...
        ~isscalar(bundle.snapshotTimes) || ...
        ~isfield(bundle, 'preDecisionTopologyHistoryByTime') || ...
        numel(bundle.preDecisionTopologyHistoryByTime) < ...
            screen.currentTime
    error('PolicyContinuationStateV212:CacheContract', ...
        'The source cache lacks its anchor history.');
end
anchorHistory = bundle. ...
    preDecisionTopologyHistoryByTime{screen.currentTime};
if ~all(isfield(anchorHistory, { ...
        'selectedDirectedEdgeHistory', ...
        'deliveredDirectedEdgeHistory', 'times'}))
    error('PolicyContinuationStateV212:CacheHistory', ...
        'The source cache history is incomplete.');
end
selectedPolicy = ...
    convertDiagnosticEdgeHistoryToPolicyAdjacencyHistory( ...
        anchorHistory.selectedDirectedEdgeHistory);
deliveredPolicy = ...
    convertDiagnosticEdgeHistoryToPolicyAdjacencyHistory( ...
        anchorHistory.deliveredDirectedEdgeHistory);
historyTimes = reshape(anchorHistory.times, 1, []);
if branchPage > 1
    selectedPolicy = cat(3, selectedPolicy, ...
        logical(outcome.selectedAdjacency(:, :, 1:branchPage - 1)));
    deliveredPolicy = cat(3, deliveredPolicy, ...
        logical(outcome.deliveredAdjacency(:, :, 1:branchPage - 1)));
    historyTimes = [historyTimes, ...
        reshape(screen.returnTimes(1:branchPage - 1), 1, [])];
end
if size(selectedPolicy, 3) < historyDepth || ...
        size(deliveredPolicy, 3) ~= size(selectedPolicy, 3) || ...
        numel(historyTimes) ~= size(selectedPolicy, 3)
    error('PolicyContinuationStateV212:HistoryDepth', ...
        'The policy-induced source lacks two causal history pages.');
end
keep = (size(selectedPolicy, 3) - historyDepth + 1): ...
    size(selectedPolicy, 3);
selectedPolicy = selectedPolicy(:, :, keep);
deliveredPolicy = deliveredPolicy(:, :, keep);
historyTimes = historyTimes(keep);
expectedTimes = (branchTime - historyDepth):(branchTime - 1);
if ~isequal(historyTimes, expectedTimes)
    error('PolicyContinuationStateV212:HistoryTimes', ...
        'Continuation history must be consecutive and end before the branch.');
end
nodeCount = numel(screen.sensorGroupIds);
if ~isequal(size(selectedPolicy), ...
        [nodeCount, nodeCount, historyDepth]) || ...
        ~isequal(size(deliveredPolicy), ...
            [nodeCount, nodeCount, historyDepth])
    error('PolicyContinuationStateV212:HistoryShape', ...
        'Continuation topology history has the wrong shape.');
end

state = struct();
state.contractVersion = ...
    'policy-induced-continuation-state-v212-v1';
state.presetName = screen.presetName;
state.seed = screen.seed;
state.branchTime = branchTime;
state.localPosteriorBySensor = reshape( ...
    outcome.localPosteriorSnapshotsByTime{branchPage}, 1, []);
state.previousPolicyAdjacencyHistory = selectedPolicy;
state.previousDeliveredPolicyAdjacencyHistory = deliveredPolicy;
state.historyTimes = historyTimes;
state.cachePath = screen.cachePath;
state.cacheAnchorTime = bundle.snapshotTimes;
state.sourceScreenPath = sourceScreenPath;
state.sourceOutcomeIndex = sourceOutcomeIndex;
state.sourceActionName = ...
    screen.records(sourceOutcomeIndex).actionName;
state.sourcePageIndex = branchPage;
state.stateKey = sprintf('%s|arm=%d|page=%d|t=%d', ...
    sourceScreenPath, sourceOutcomeIndex, branchPage, branchTime);
state.historySource = ...
    'policy-induced-screen-continuation-v212';
state.truthUsed = false;
state.futureMeasurementsUsed = false;
state.validationClaimAllowed = false;
state.evidenceBoundary = [ ...
    'V212 extracts a captured pre-branch local posterior and the last ', ...
    'two executed selected/delivered topology pages.  It reads no truth ', ...
    'or future measurement.  Reusing the state for multiple action arms ', ...
    'supports paired development counterfactuals only.'];
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
