function control = buildFormationSafeGatewayTrustBackoffControl( ...
        context, sourceV32Preflight, options)
% BUILDFORMATIONSAFEGATEWAYTRUSTBACKOFFCONTROL Source-only v33 projector.
%
% Frozen v32 routes with sufficient weight-0.05 disagreement headroom are
% replayed at lower trust on only their two changed cross inputs. Exact
% current-state label retention selects a safe weight or restores reference.

if nargin < 3 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('GatewayTrustBackoff:InvalidOptions', ...
        'The frozen v33 controller does not accept option overrides.');
end
protocol = getFormationSafeGatewayTrustBackoffProtocol();
nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
if nodeCount < 2 || numel(groupIds) ~= nodeCount || ...
        formationCount < 2 || ...
        formationCount > protocol.maximumFormationCount || ...
        ~isfield(context, 'previousAdjacencyHistory') || ...
        size(context.previousAdjacencyHistory, 1) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 2) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 3) < 2 || ...
        ~isstruct(sourceV32Preflight) || ...
        ~isfield(sourceV32Preflight, 'gatewayControl')
    error('GatewayTrustBackoff:InvalidContext', ...
        'Gateway trust-backoff context or source is invalid.');
end
source = sourceV32Preflight.gatewayControl;
if ~strcmp(source.contractVersion, ...
        'formation-alternative-gateway-control-v1') || ...
        source.nodeCount ~= nodeCount || ...
        source.formationCount ~= formationCount || ...
        ~source.referenceScore.safe || ...
        ~source.referenceFallbackUsed
    error('GatewayTrustBackoff:InvalidSource', ...
        'Frozen v32 gateway source is incompatible with v33.');
end

policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.referenceResidualWeight);
[referenceAdjacency, referenceDetails] = ...
    selectTemporalCrossEdgeSuspensionPolicy( ...
        context, zeros(1, 0), policyOptions);
referenceWeights = referenceDetails.fusionWeightMatrix;
if ~isequal(referenceAdjacency, source.referenceAdjacency) || ...
        ~isequal(referenceWeights, source.referenceFusionWeights) || ...
        ~all(referenceDetails.rollingB3SensorPass) || ...
        ~all(referenceDetails.rollingB3FormationPass)
    error('GatewayTrustBackoff:ReferenceDrift', ...
        'Current reference route differs from frozen v32.');
end
referenceScore = source.referenceScore;
referenceDistributions = ...
    referenceScore.networkDetails.receiverDistributions;
referenceFormationAdjacency = collapseToFormations( ...
    referenceAdjacency, groupIds);
referenceResidualSources = reshape( ...
    referenceDetails.residualSourcesByReceiver, 1, []);

promisingMask = ...
    source.candidateDisagreementImprovementFraction >= ...
        protocol.minimumDisagreementImprovementFraction - 1e-12;
promisingIndices = find(promisingMask);
if numel(promisingIndices) > ...
        protocol.maximumPromisingGatewayCandidates
    [~, order] = sort( ...
        source.candidateDisagreementImprovementFraction( ...
            promisingIndices), 'descend');
    promisingIndices = promisingIndices(order( ...
        1:protocol.maximumPromisingGatewayCandidates));
end
promisingIndices = reshape(promisingIndices, 1, []);
candidateCount = numel(promisingIndices);
weightGrid = reshape( ...
    protocol.alternativeResidualWeightGrid, 1, []);
levelCount = numel(weightGrid);

routeAdjacency = cell(candidateCount, levelCount);
routeWeights = cell(candidateCount, levelCount);
routeDetails = cell(candidateCount, levelCount);
routeScores = cell(candidateCount, levelCount);
changedCrossReceivers = cell(1, candidateCount);
routeImprovement = nan(candidateCount, levelCount);
routeSafe = false(candidateCount, levelCount);
routeEligible = false(candidateCount, levelCount);
routeRollingSensorPass = cell(candidateCount, levelCount);
routeRollingFormationPass = cell(candidateCount, levelCount);
for candidateCursor = 1:candidateCount
    sourceCandidateIdx = promisingIndices(candidateCursor);
    selection = source.candidateSelections(sourceCandidateIdx);
    candidateSources = reshape( ...
        selection.residualSourcesByReceiver, 1, []);
    candidateCrossMask = groupIds ~= groupIds(candidateSources);
    changed = find(candidateCrossMask & ...
        candidateSources ~= referenceResidualSources);
    if numel(changed) ~= 2 || ...
            selection.referenceCutChangeCount ~= 1
        error('GatewayTrustBackoff:InvalidSourceRoute', ...
            'A v32 trust-region route does not have two changed cross inputs.');
    end
    changedCrossReceivers{candidateCursor} = changed;
    for levelIdx = 1:levelCount
        residualWeights = protocol.referenceResidualWeight * ...
            ones(1, nodeCount);
        residualWeights(changed) = weightGrid(levelIdx);
        [adjacency, weights, details] = ...
            buildBackbonePreservingResidualRoute( ...
                context, referenceDetails.dominantAdjacency, ...
                selection.residualAdjacency, ...
                protocol.dominantWeight, residualWeights);
        [sensorPass, formationPass] = rollingB3Pass( ...
            context.previousAdjacencyHistory, ...
            cat(3, adjacency, referenceAdjacency, ...
                referenceAdjacency), groupIds);
        if nnz(adjacency) ~= nnz(referenceAdjacency) || ...
                ~isequal(collapseToFormations( ...
                    adjacency, groupIds), ...
                    referenceFormationAdjacency) || ...
                ~isequal(details.dominantSourcesByReceiver, ...
                    referenceDetails.dominantSourcesByReceiver) || ...
                any(details.residualWeightsByReceiver > ...
                    protocol.referenceResidualWeight + 1e-12) || ...
                ~all(sensorPass) || ~all(formationPass)
            error('GatewayTrustBackoff:InvalidCandidate', ...
                'A trust-backoff route violates a structural gate.');
        end
        score = scoreRoute( ...
            context, adjacency, weights, ...
            referenceDistributions, groupIds, protocol);
        improvement = disagreementImprovement( ...
            referenceScore.networkRisk, score.networkRisk);
        safe = score.safe && all(sensorPass) && all(formationPass);
        eligible = safe && improvement >= ...
            protocol.minimumDisagreementImprovementFraction - 1e-12;

        routeAdjacency{candidateCursor, levelIdx} = adjacency;
        routeWeights{candidateCursor, levelIdx} = weights;
        routeDetails{candidateCursor, levelIdx} = details;
        routeScores{candidateCursor, levelIdx} = score;
        routeImprovement(candidateCursor, levelIdx) = improvement;
        routeSafe(candidateCursor, levelIdx) = safe;
        routeEligible(candidateCursor, levelIdx) = eligible;
        routeRollingSensorPass{candidateCursor, levelIdx} = sensorPass;
        routeRollingFormationPass{candidateCursor, levelIdx} = ...
            formationPass;
    end
end

maximumSafeWeight = nan(1, candidateCount);
maximumSafeLevelIndex = nan(1, candidateCount);
for candidateCursor = 1:candidateCount
    safeLevels = find(routeSafe(candidateCursor, :));
    if isempty(safeLevels)
        continue;
    end
    [maximumSafeWeight(candidateCursor), localIdx] = max( ...
        weightGrid(safeLevels));
    maximumSafeLevelIndex(candidateCursor) = safeLevels(localIdx);
end

[selectedCandidateCursor, selectedLevelIdx] = ...
    selectEligibleRoute(routeEligible, routeImprovement, ...
        weightGrid, promisingIndices);
if isnan(selectedCandidateCursor)
    selectedSourceCandidateIndex = NaN;
    selectedAlternativeResidualWeight = NaN;
    selectedChangedCrossReceivers = zeros(1, 0);
    selectedAdjacency = referenceAdjacency;
    selectedWeights = referenceWeights;
    selectedRouteDetails = referenceDetails;
    selectedScore = referenceScore;
    selectedSensorPass = referenceDetails.rollingB3SensorPass;
    selectedFormationPass = referenceDetails.rollingB3FormationPass;
    selectedActionName = 'reference';
else
    selectedSourceCandidateIndex = ...
        promisingIndices(selectedCandidateCursor);
    selectedAlternativeResidualWeight = weightGrid(selectedLevelIdx);
    selectedChangedCrossReceivers = ...
        changedCrossReceivers{selectedCandidateCursor};
    selectedAdjacency = ...
        routeAdjacency{selectedCandidateCursor, selectedLevelIdx};
    selectedWeights = ...
        routeWeights{selectedCandidateCursor, selectedLevelIdx};
    selectedRouteDetails = ...
        routeDetails{selectedCandidateCursor, selectedLevelIdx};
    selectedScore = ...
        routeScores{selectedCandidateCursor, selectedLevelIdx};
    selectedSensorPass = ...
        routeRollingSensorPass{selectedCandidateCursor, selectedLevelIdx};
    selectedFormationPass = ...
        routeRollingFormationPass{selectedCandidateCursor, selectedLevelIdx};
    selectedActionName = sprintf( ...
        'safe-gateway-c%d-w%s', ...
        selectedSourceCandidateIndex, strrep(sprintf('%.4f', ...
            selectedAlternativeResidualWeight), '.', 'p'));
end
selectedImprovement = disagreementImprovement( ...
    referenceScore.networkRisk, selectedScore.networkRisk);
weightSupport = selectedAdjacency | logical(eye(nodeCount));
if any(~isfinite(selectedWeights(:))) || ...
        any(selectedWeights(:) < -1e-12) || ...
        any(selectedWeights(:) > 1e-12 & ~weightSupport(:)) || ...
        any(abs(sum(selectedWeights, 2) - 1) > 1e-12) || ...
        nnz(selectedAdjacency) ~= nnz(referenceAdjacency) || ...
        ~isequal(collapseToFormations( ...
            selectedAdjacency, groupIds), ...
            referenceFormationAdjacency) || ...
        ~selectedScore.safe || ...
        ~all(selectedSensorPass) || ~all(selectedFormationPass) || ...
        (~isnan(selectedCandidateCursor) && ...
         (selectedAlternativeResidualWeight > ...
            protocol.maximumAlternativeResidualWeight + 1e-12 || ...
          selectedImprovement < ...
            protocol.minimumDisagreementImprovementFraction - 1e-12))
    error('GatewayTrustBackoff:InvalidSelection', ...
        'Selected gateway trust-backoff route violates an invariant.');
end

evaluatedRouteCount = candidateCount * levelCount;
if evaluatedRouteCount > protocol.maximumControlRouteEvaluations
    error('GatewayTrustBackoff:EvaluationBudgetExceeded', ...
        'Gateway trust-backoff exceeded its route budget.');
end

control = struct();
control.contractVersion = ...
    'formation-safe-gateway-trust-backoff-control-v1';
control.protocolId = protocol.id;
control.nodeCount = nodeCount;
control.formationCount = formationCount;
control.groupIds = groupIds;
control.groups = groups;
control.referenceAdjacency = referenceAdjacency;
control.referenceFusionWeights = referenceWeights;
control.referencePolicyDetails = referenceDetails;
control.referenceScore = referenceScore;
control.referenceScoreReusedFromFrozenV32 = true;
control.referenceFormationAdjacency = referenceFormationAdjacency;
control.sourceV32CandidateBankSha256 = source.candidateBankSha256;
control.sourceV32CandidateImprovementFraction = ...
    source.candidateDisagreementImprovementFraction;
control.promisingSourceCandidateIndices = promisingIndices;
control.promisingCandidateCount = candidateCount;
control.alternativeResidualWeightGrid = weightGrid;
control.changedCrossReceivers = changedCrossReceivers;
control.routeAdjacency = routeAdjacency;
control.routeFusionWeights = routeWeights;
control.routeDetails = routeDetails;
control.routeScores = routeScores;
control.routeDisagreementImprovementFraction = routeImprovement;
control.routeSafetyMask = routeSafe;
control.routeEligibilityMask = routeEligible;
control.routeRollingB3SensorPass = routeRollingSensorPass;
control.routeRollingB3FormationPass = routeRollingFormationPass;
control.safeRouteCount = nnz(routeSafe);
control.eligibleRouteCount = nnz(routeEligible);
control.maximumSafeWeightByCandidate = maximumSafeWeight;
control.maximumSafeLevelIndexByCandidate = ...
    maximumSafeLevelIndex;
control.selectedCandidateCursor = selectedCandidateCursor;
control.selectedLevelIndex = selectedLevelIdx;
control.selectedSourceCandidateIndex = ...
    selectedSourceCandidateIndex;
control.selectedAlternativeResidualWeight = ...
    selectedAlternativeResidualWeight;
control.selectedChangedCrossReceivers = ...
    selectedChangedCrossReceivers;
control.selectedAdjacency = selectedAdjacency;
control.selectedFusionWeights = selectedWeights;
control.selectedRouteDetails = selectedRouteDetails;
control.selectedScore = selectedScore;
control.selectedDisagreementImprovementFraction = ...
    selectedImprovement;
control.selectedRollingB3SensorPass = selectedSensorPass;
control.selectedRollingB3FormationPass = selectedFormationPass;
control.selectedActionName = selectedActionName;
control.referenceFallbackUsed = isnan(selectedCandidateCursor);
control.referenceMessageCount = nnz(referenceAdjacency);
control.selectedMessageCount = nnz(selectedAdjacency);
control.messageCountParityWithReference = ...
    control.selectedMessageCount == control.referenceMessageCount;
control.formationGraphParityWithReference = isequal( ...
    collapseToFormations(selectedAdjacency, groupIds), ...
    referenceFormationAdjacency);
control.dominantRouteParityWithReference = isequal( ...
    selectedRouteDetails.dominantSourcesByReceiver, ...
    referenceDetails.dominantSourcesByReceiver);
control.alternativeTrustNeverExceedsReference = ...
    isnan(selectedAlternativeResidualWeight) || ...
    selectedAlternativeResidualWeight <= ...
        protocol.referenceResidualWeight + 1e-12;
control.evaluatedRouteCount = evaluatedRouteCount;
control.selectionUsesCurrentPosterior = true;
control.selectionUsesCurrentLinkReliability = true;
control.selectionUsesSelectedTopologyHistory = true;
control.truthUsed = false;
control.futureOutcomeUsed = false;
control.openedDevelopmentEvidenceOnly = true;
control.validationClaimAllowed = false;
end

function [candidateCursor, levelIdx] = selectEligibleRoute( ...
        eligible, improvement, weightGrid, sourceIndices)
candidateCursor = NaN;
levelIdx = NaN;
bestKey = [-inf, -inf, -inf];
for currentCandidate = 1:size(eligible, 1)
    for currentLevel = 1:size(eligible, 2)
        if ~eligible(currentCandidate, currentLevel)
            continue;
        end
        key = [ ...
            improvement(currentCandidate, currentLevel), ...
            weightGrid(currentLevel), ...
            -sourceIndices(currentCandidate)];
        if lexicographicallyGreater(key, bestKey)
            bestKey = key;
            candidateCursor = currentCandidate;
            levelIdx = currentLevel;
        end
    end
end
end

function value = lexicographicallyGreater(left, right)
value = false;
for idx = 1:numel(left)
    if left(idx) > right(idx) + 1e-12
        value = true;
        return;
    elseif left(idx) < right(idx) - 1e-12
        return;
    end
end
end

function score = scoreRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, protocol)
enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, enumerationOptions);
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        protocol.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        protocol.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        protocol.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        protocol.retentionReceiverTailWeight);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, ...
        groupIds, retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = ...
    retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= protocol. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= protocol. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= protocol. ...
        maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'retentionRisk', retentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function value = disagreementImprovement(referenceRisk, candidateRisk)
value = (referenceRisk - candidateRisk) / max(referenceRisk, eps);
end

function [sensorPass, formationPass] = ...
        rollingB3Pass(previousHistory, sequence, groupIds)
history = logical(previousHistory(:, :, end-1:end));
sensorPass = false(1, size(sequence, 3));
formationPass = false(1, size(sequence, 3));
for stepIdx = 1:size(sequence, 3)
    pages = cat(3, history, sequence(:, :, stepIdx));
    window = any(pages(:, :, max(1, end-2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = sequence(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end
