function config = buildInitialDynamicRouteFreezeV237Config( ...
        scenario, registration)
% BUILDINITIALDYNAMICROUTEFREEZEV237CONFIG Matched frozen route.

protocol = getInitialDynamicRouteFreezeV237Protocol();
source = getCorrectedStaticRoutingBaselineV227Protocol();
if ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets)
    error('InitialDynamicRouteFreezeV237:InvalidConfigInput', ...
        'V237 requires one registered scale preset.');
end
config = buildCorrectedStaticRoutingBaselineV227Config( ...
    source.dynamicArmId, scenario, struct());
config.topologyPolicyName = protocol.policyName;
config.topologyPolicyFcn = @(context) ...
    selectInitialDynamicRouteFreezeV237Policy(context, registration);
end
