function candidate = ...
    buildFormationB4V46TrackingSourceFreezeCandidate( ...
        discovery, runMetadata)
% BUILDFORMATIONB4V46TRACKINGSOURCEFREEZECANDIDATE Non-authorizing proposal.
%
% A successful discovery may be summarized into a compact candidate, but
% this function cannot freeze inputs or authorize filter execution.  A later
% independent commit must hard-code and audit the accepted hashes.

registry = getFormationB4V46TrackingSourceRegistry();
validateDiscovery(discovery, registry);
validateRunMetadata(runMetadata, discovery, registry);

entries = repmat(emptyEntry(), 1, registry.caseCount);
for caseIdx = 1:registry.caseCount
    record = discovery.records(caseIdx);
    contract = registry.cases(caseIdx);
    validateRecord(record, contract, registry);
    entry = emptyEntry();
    entry.caseOrdinal = contract.ordinal;
    entry.caseId = contract.id;
    entry.coreCaseCanonicalSha256 = ...
        contract.caseCanonicalSha256;
    entry.seedRole = contract.seedRole;
    entry.fullSourceFingerprintCanonicalSha256 = ...
        record.inputFingerprint.canonicalSha256;
    entry.runtimeFilterProjectionCanonicalSha256 = ...
        record.runtimeFilterInputFingerprint.canonicalSha256;
    entry.sourceEnvelopeCanonicalSha256 = ...
        record.sourceEnvelopeCanonicalSha256;
    entry.discoveryRecordCanonicalSha256 = ...
        record.canonicalSha256;
    entries(caseIdx) = entry;
end

payload = struct();
payload.id = ...
    'formation-b4-v46-tracking-source-freeze-candidate-v1';
payload.contractVersion = ...
    'formation-b4-v46-tracking-source-freeze-candidate-v1';
payload.coreRegistryId = registry.id;
payload.coreRegistryCanonicalSha256 = registry.canonicalSha256;
payload.structuralProtocolId = registry.structuralProtocolId;
payload.structuralProtocolCanonicalSha256 = ...
    registry.structuralProtocolCanonicalSha256;
payload.discoveryGenerationGitCommit = ...
    runMetadata.generationGitCommit;
payload.discoveryRunMetadataCanonicalSha256 = ...
    runMetadata.canonicalSha256;
payload.discoveryCanonicalSha256 = discovery.canonicalSha256;
payload.discoveryContractVersion = discovery.contractVersion;
payload.sourceFingerprintContractVersion = ...
    discovery.records(1).inputFingerprint.contractVersion;
payload.runtimeFilterProjectionContractVersion = ...
    discovery.records(1).runtimeFilterInputFingerprint.contractVersion;
payload.sourceEnvelopeContractVersion = ...
    'formation-b4-v46-materialized-tracking-source-envelope-v3';
payload.discoveryRecordContractVersion = ...
    'formation-b4-v46-tracking-source-discovery-record-v1';
payload.canonicalSerializationFunction = ...
    'computeCanonicalValueSha256';
payload.runtimeEngine = discovery.runtimeEngine;
payload.runtimeVersion = discovery.runtimeVersion;
payload.caseOrdering = registry.caseOrdering;
payload.caseCount = registry.caseCount;
payload.fullRegistryCovered = true;
payload.candidateOnly = true;
payload.independentAcceptancePending = true;
payload.sourceInputFingerprintsProposed = true;
payload.sourceInputFingerprintsFrozen = false;
payload.truthBearingSourceCommitmentsPresent = true;
payload.offlineProvenanceAuditOnly = true;
payload.eligibleAsPermitDependency = false;
payload.runtimeExecutionAuthorityProduced = false;
payload.runtimeOnlyAcceptanceRequiredForPermit = true;
payload.sourceArtifactPublicationAuthorized = false;
payload.filterExecutionAuthorized = false;
payload.stateEstimateOutputAuthorized = false;
payload.trackingOutcomeScoringAuthorized = false;
payload.armSelectionAuthorized = false;
payload.developmentAdvanceDecisionAuthorized = false;
payload.confirmationTrackingAuthorized = false;
payload.validationClaimAllowed = false;
payload.runnerSelfAuthorizationAllowed = false;
payload.confirmationTruthSecrecyGuaranteed = false;
payload.confirmationTrackingOutcomeUnopened = true;
payload.entries = entries;
payload.evidenceBoundary = [ ...
    'This object is a deterministic proposal extracted from a complete ', ...
    'hash-only discovery. It does not freeze source inputs, authorize ', ...
    'artifact publication, execute a filter, expose a state estimate, ', ...
    'score tracking, select an arm, open confirmation, or support a ', ...
    'validation claim. It contains commitments to truth-bearing source ', ...
    'objects and is therefore ineligible as a permit dependency. A ', ...
    'separate independently accepted runtime-only case entry is required ', ...
    'before any phase-specific permit may exist.'];
candidate = payload;
candidate.canonicalSha256 = ...
    computeCanonicalValueSha256(payload);
end

function validateRunMetadata(metadata, discovery, registry)
expectedFields = { ...
    'contractVersion', 'generationGitCommit', ...
    'generationGitClean', 'endingGitCommit', 'endingGitClean', ...
    'registryId', 'registryCanonicalSha256', ...
    'discoveryContractVersion', 'discoveryCanonicalSha256', ...
    'caseCount', 'fullRegistryRequested', ...
    'sourceInputFingerprintsFrozen', ...
    'sourceArtifactPublicationAuthorized', 'filterExecuted', ...
    'stateEstimateGenerated', 'trackingOutcomeScored', ...
    'developmentAdvanceDecisionMade', 'confirmationOpened', ...
    'validationClaimAllowed', 'startedAt', 'completedAt', ...
    'elapsedSeconds', 'evidenceBoundary', 'canonicalSha256'};
if ~isstruct(metadata) || ~isscalar(metadata) || ...
        ~exactFields(metadata, expectedFields) || ...
        ~strcmp(metadata.contractVersion, ...
            ['formation-b4-v46-tracking-source-', ...
             'discovery-run-metadata-v1']) || ...
        ~isGitCommit(metadata.generationGitCommit) || ...
        ~strcmp(metadata.endingGitCommit, ...
            metadata.generationGitCommit) || ...
        ~isTrue(metadata.generationGitClean) || ...
        ~isTrue(metadata.endingGitClean) || ...
        ~strcmp(metadata.registryId, registry.id) || ...
        ~strcmp(metadata.registryCanonicalSha256, ...
            registry.canonicalSha256) || ...
        ~strcmp(metadata.discoveryContractVersion, ...
            discovery.contractVersion) || ...
        ~strcmp(metadata.discoveryCanonicalSha256, ...
            discovery.canonicalSha256) || ...
        metadata.caseCount ~= registry.caseCount || ...
        ~isTrue(metadata.fullRegistryRequested) || ...
        ~allFalse(metadata, { ...
            'sourceInputFingerprintsFrozen', ...
            'sourceArtifactPublicationAuthorized', 'filterExecuted', ...
            'stateEstimateGenerated', 'trackingOutcomeScored', ...
            'developmentAdvanceDecisionMade', 'confirmationOpened', ...
            'validationClaimAllowed'}) || ...
        ~ischar(metadata.startedAt) || isempty(metadata.startedAt) || ...
        ~ischar(metadata.completedAt) || isempty(metadata.completedAt) || ...
        ~isa(metadata.elapsedSeconds, 'double') || ...
        ~isreal(metadata.elapsedSeconds) || ...
        ~isscalar(metadata.elapsedSeconds) || ...
        ~isfinite(metadata.elapsedSeconds) || ...
        metadata.elapsedSeconds < 0 || ...
        ~ischar(metadata.evidenceBoundary) || ...
        isempty(metadata.evidenceBoundary) || ...
        ~isSha256(metadata.canonicalSha256) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(metadata, 'canonicalSha256')), ...
            metadata.canonicalSha256)
    error('FormationB4V46TrackingFreeze:RunMetadataDrift', ...
        'The discovery run metadata is not an exact clean-run record.');
end
end

function validateDiscovery(discovery, registry)
expectedFields = { ...
    'contractVersion', 'registryId', 'registryCanonicalSha256', ...
    'presets', 'seeds', 'records', 'caseCount', 'runtimeEngine', ...
    'runtimeVersion', 'fullRegistryRequested', ...
    'sourceInputFingerprintsFrozen', ...
    'sourceArtifactPublicationAuthorized', ...
    'rawSourceObjectsReturned', 'rawTruthReturned', ...
    'rawMeasurementsReturned', 'runtimeFilterModelReturned', ...
    'runtimeTargetTrajectoryRealizationAbsent', ...
    'registeredBirthPriorRetained', 'filterExecuted', ...
    'stateEstimateGenerated', ...
    'sourceGeometryTruthValidationExecuted', ...
    'truthHashedForSealing', ...
    'estimateVsTruthTrackingMetricComputed', ...
    'armComparedOrSelected', 'trackingOutcomeScored', ...
    'developmentAdvanceDecisionMade', 'confirmationOpened', ...
    'validationClaimAllowed', 'developmentEvidenceOnly', ...
    'canonicalSha256'};
if ~isstruct(discovery) || ~isscalar(discovery) || ...
        ~exactFields(discovery, expectedFields) || ...
        ~strcmp(discovery.contractVersion, ...
            ['formation-b4-v46-tracking-source-', ...
             'fingerprint-discovery-v2']) || ...
        ~strcmp(discovery.registryId, registry.id) || ...
        ~strcmp(discovery.registryCanonicalSha256, ...
            registry.canonicalSha256) || ...
        ~isequal(discovery.presets, {registry.scenes.presetName}) || ...
        ~isequal(discovery.seeds, registry.orderedSeeds) || ...
        discovery.caseCount ~= registry.caseCount || ...
        discovery.caseCount ~= 40 || ...
        ~isTrue(discovery.fullRegistryRequested) || ...
        ~allFalse(discovery, { ...
            'sourceInputFingerprintsFrozen', ...
            'sourceArtifactPublicationAuthorized', ...
            'rawSourceObjectsReturned', 'rawTruthReturned', ...
            'rawMeasurementsReturned', 'runtimeFilterModelReturned', ...
            'filterExecuted', 'stateEstimateGenerated', ...
            'estimateVsTruthTrackingMetricComputed', ...
            'armComparedOrSelected', 'trackingOutcomeScored', ...
            'developmentAdvanceDecisionMade', 'confirmationOpened', ...
            'validationClaimAllowed'}) || ...
        ~allTrue(discovery, { ...
            'runtimeTargetTrajectoryRealizationAbsent', ...
            'registeredBirthPriorRetained', ...
            'sourceGeometryTruthValidationExecuted', ...
            'truthHashedForSealing', 'developmentEvidenceOnly'}) || ...
        ~ischar(discovery.runtimeEngine) || ...
        isempty(discovery.runtimeEngine) || ...
        ~ischar(discovery.runtimeVersion) || ...
        isempty(discovery.runtimeVersion) || ...
        ~isSha256(discovery.canonicalSha256) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(discovery, 'canonicalSha256')), ...
            discovery.canonicalSha256) || ...
        ~isstruct(discovery.records) || ...
        ~isequal(size(discovery.records), [1, registry.caseCount])
    error('FormationB4V46TrackingFreeze:DiscoveryDrift', ...
        'The discovery is not the complete non-authorizing registry.');
end
end

function validateRecord(record, contract, registry)
expectedFields = { ...
    'caseId', 'caseOrdinal', 'presetName', 'seed', 'seedRole', ...
    'primaryMatrix', 'stressMatrix', 'deliverySeed', ...
    'inputFingerprint', 'runtimeFilterInputFingerprint', ...
    'runtimeTargetTrajectoryRealizationAbsent', ...
    'registeredBirthPriorRetained', ...
    'sourceGeometryTruthValidationExecuted', ...
    'truthHashedForSealing', 'filterExecuted', ...
    'estimateVsTruthTrackingMetricComputed', ...
    'trackingOutcomeScored', 'sourceEnvelopeCanonicalSha256', ...
    'canonicalSha256'};
if ~isstruct(record) || ~isscalar(record) || ...
        ~exactFields(record, expectedFields) || ...
        ~strcmp(record.caseId, contract.id) || ...
        record.caseOrdinal ~= contract.ordinal || ...
        ~strcmp(record.presetName, contract.presetName) || ...
        record.seed ~= contract.seed || ...
        ~strcmp(record.seedRole, contract.seedRole) || ...
        ~islogical(record.primaryMatrix) || ...
        ~isscalar(record.primaryMatrix) || ...
        ~isequal(record.primaryMatrix, contract.primaryMatrix) || ...
        ~islogical(record.stressMatrix) || ...
        ~isscalar(record.stressMatrix) || ...
        ~isequal(record.stressMatrix, contract.stressMatrix) || ...
        record.deliverySeed ~= contract.deliverySeed || ...
        ~allTrue(record, { ...
            'runtimeTargetTrajectoryRealizationAbsent', ...
            'registeredBirthPriorRetained', ...
            'sourceGeometryTruthValidationExecuted', ...
            'truthHashedForSealing'}) || ...
        ~allFalse(record, { ...
            'filterExecuted', ...
            'estimateVsTruthTrackingMetricComputed', ...
            'trackingOutcomeScored'}) || ...
        ~isSha256(record.sourceEnvelopeCanonicalSha256) || ...
        ~isSha256(record.canonicalSha256)
    error('FormationB4V46TrackingFreeze:RecordDrift', ...
        'Discovery record %d failed its exact audit.', ...
        contract.ordinal);
end

source = record.inputFingerprint;
runtime = record.runtimeFilterInputFingerprint;
sourceHashFields = { ...
    'configSha256', 'sourceModelSha256', ...
    'runtimeFilterModelSha256', ...
    'runtimeFilterBirthPriorSha256', 'measurementsSha256', ...
    'groundTruthSha256', 'groundTruthRfsSha256', ...
    'sensorTrajectoriesSha256', 'targetTrajectoriesSha256', ...
    'neighborMapSha256', 'communicationConfigSha256', ...
    'graphDataSha256', 'linkMetadataSha256', ...
    'validationSha256', 'physicalIdentityRegistrySha256', ...
    'deliveryUniformMetadataSha256', ...
    'deliveryUniformCanonicalTensorSha256', ...
    'deliveryUniformMaterializedTensorSha256', 'canonicalSha256'};
runtimeHashFields = { ...
    'registryCanonicalSha256', 'caseCanonicalSha256', ...
    'runtimeFilterBirthPriorSha256', 'modelSha256', ...
    'measurementsSha256', 'sensorTrajectoriesSha256', ...
    'neighborMapSha256', 'communicationConfigSha256', ...
    'physicalIdentityRegistrySha256', ...
    'deliveryUniformMetadataSha256', ...
    'deliveryUniformCanonicalTensorSha256', ...
    'deliveryUniformMaterializedTensorSha256', 'canonicalSha256'};
if ~isstruct(source) || ~isscalar(source) || ...
        ~allSha256Fields(source, sourceHashFields) || ...
        ~strcmp(source.registryId, registry.id) || ...
        ~strcmp(source.registryCanonicalSha256, ...
            registry.canonicalSha256) || ...
        ~strcmp(source.caseId, contract.id) || ...
        source.caseOrdinal ~= contract.ordinal || ...
        source.seed ~= contract.seed || ...
        ~strcmp(source.seedRole, contract.seedRole) || ...
        ~isequal(source.primaryMatrix, contract.primaryMatrix) || ...
        ~isequal(source.stressMatrix, contract.stressMatrix) || ...
        ~strcmp(source.caseCanonicalSha256, ...
            contract.caseCanonicalSha256) || ...
        ~strcmp(source.configSha256, ...
            contract.configSnapshotSha256) || ...
        ~isstruct(runtime) || ~isscalar(runtime) || ...
        ~allSha256Fields(runtime, runtimeHashFields) || ...
        ~strcmp(runtime.caseId, contract.id) || ...
        runtime.caseOrdinal ~= contract.ordinal || ...
        runtime.seed ~= contract.seed || ...
        ~strcmp(runtime.seedRole, contract.seedRole) || ...
        ~isequal(runtime.primaryMatrix, contract.primaryMatrix) || ...
        ~isequal(runtime.stressMatrix, contract.stressMatrix) || ...
        ~isFalse(runtime.targetTrajectoryRealizationPassedToFilter) || ...
        ~isFalse(runtime.groundTruthPassedToFilter) || ...
        ~isTrue(runtime.registeredBirthPriorRetained) || ...
        ~isequaln( ...
            projectFormationB4V46RuntimeFilterInputFingerprint(source), ...
            runtime) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(record, 'canonicalSha256')), ...
            record.canonicalSha256)
    error('FormationB4V46TrackingFreeze:RecordDrift', ...
        'Discovery record %d failed its exact audit.', ...
        contract.ordinal);
end
end

function valid = allSha256Fields(value, fields)
valid = all(cellfun(@(field) ...
    isfield(value, field) && isSha256(value.(field)), fields));
end

function entry = emptyEntry()
entry = struct( ...
    'caseOrdinal', NaN, 'caseId', '', ...
    'coreCaseCanonicalSha256', '', 'seedRole', '', ...
    'fullSourceFingerprintCanonicalSha256', '', ...
    'runtimeFilterProjectionCanonicalSha256', '', ...
    'sourceEnvelopeCanonicalSha256', '', ...
    'discoveryRecordCanonicalSha256', '');
end

function valid = exactFields(value, fields)
valid = isequal(sort(fieldnames(value)), sort(fields(:)));
end

function valid = allTrue(value, fields)
valid = all(cellfun(@(field) ...
    isfield(value, field) && isTrue(value.(field)), fields));
end

function valid = allFalse(value, fields)
valid = all(cellfun(@(field) ...
    isfield(value, field) && isFalse(value.(field)), fields));
end

function valid = isTrue(value)
valid = islogical(value) && isscalar(value) && value;
end

function valid = isFalse(value)
valid = islogical(value) && isscalar(value) && ~value;
end

function valid = isSha256(value)
valid = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end

function valid = isGitCommit(value)
valid = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{40}$', 'once'));
end
