function context = ...
        buildReceiverRelativeLabelRoleTeacherV149ExecutionContext( ...
            presetName, seed, phase, currentTime, ...
            referenceCarrierMode, actionSpec)
% BUILDRECEIVERRELATIVELABELROLETEACHERV149EXECUTIONCONTEXT Teacher permit.

context = buildLabelRoleMultiplexedSinglePayloadV148ExecutionContext( ...
    presetName, seed, phase, currentTime, referenceCarrierMode, actionSpec);
protocol = getReceiverRelativeLabelRoleTeacherV149Protocol();
enabled = strcmp(context.phase, 'candidate');
context.contractVersion = ...
    'v149-receiver-relative-label-role-teacher-context-v1';
context.capability = ...
    'receiver-relative-label-role-teacher-v149-development';
context.action = ...
    'filter-receiver-relative-label-role-teacher-v149-development';
context.protocolId = protocol.id;
context.policyName = protocol.outcomePolicyName;
context.receiverTeacherEnabled = enabled;
context.referenceCoverRequired = true;
end
