function context = buildLineageIsolatedRelayV135ExecutionContext( ...
        presetName, seed, phase, currentTime, ...
        referenceCarrierMode, actionSpec)
% BUILDLINEAGEISOLATEDRELAYV135EXECUTIONCONTEXT Development-only permit.

protocol = getLineageIsolatedRelayV135Protocol();
phase = lower(strrep(char(phase), '_', '-'));
referenceCarrierMode = lower(strrep( ...
    char(referenceCarrierMode), '_', '-'));
caseInfo = resolveCase(protocol, presetName);
anchorTime = resolveSetTrustSequenceV134PilotAnchor(caseInfo, protocol);
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~ismember(seed, protocol.developmentSeeds) || ...
        ~ismember(phase, {'reference', 'candidate'}) || ...
        ~isscalar(currentTime) || currentTime ~= anchorTime || ...
        ~ismember(referenceCarrierMode, protocol.referenceCarrierModes)
    error('LineageRelayV135:InvalidContext', ...
        'The V135 execution-context request is outside the screen.');
end
actionSpec = validateSetTrustSequenceActionV134( ...
    actionSpec, 'candidate-continuation', caseInfo, protocol);

context = struct( ...
    'contractVersion', ...
        'lineage-isolated-relay-v135-execution-context-v1', ...
    'capability', 'lineage-isolated-relay-v135-development', ...
    'action', 'filter-lineage-isolated-relay-v135-development', ...
    'protocolId', protocol.id, ...
    'phase', phase, ...
    'presetName', presetName, ...
    'seed', seed, ...
    'currentTime', currentTime, ...
    'horizonSteps', caseInfo.horizonSteps, ...
    'measurementTimeCount', currentTime + caseInfo.horizonSteps - 1, ...
    'policyName', protocol.outcomePolicyName, ...
    'referenceCarrierMode', referenceCarrierMode, ...
    'actionSpec', actionSpec, ...
    'scheduleEnabled', strcmp(phase, 'candidate'), ...
    'lineageRelayEnabled', strcmp(phase, 'candidate'), ...
    'onlineReselectionEnabled', false, ...
    'developmentEvidenceOnly', true);
end

function caseInfo = resolveCase(protocol, presetName)
caseIdx = find(strcmp({protocol.scaleCases.presetName}, presetName), 1);
if isempty(caseIdx)
    error('LineageRelayV135:InvalidPreset', ...
        'The preset is outside the V135 screen.');
end
caseInfo = protocol.scaleCases(caseIdx);
end
