function context = ...
    buildObservationSupportedSetSafeV194ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled, ...
        onlineReselectionEnabled)
% BUILDOBSERVATIONSUPPORTEDSETSAFEV194EXECUTIONCONTEXT Development scope.

context = buildOnlinePositiveNetAddressablePayloadV99ExecutionContext( ...
    presetName, seed, currentTime, actionName, scheduleEnabled, ...
    onlineReselectionEnabled);
protocol = getObservationSupportedSetSafeV194Protocol();
context.contractVersion = ...
    'observation-supported-set-safe-v194-context-v1';
context.capability = ...
    'observation-supported-set-safe-v194-development';
context.action = ...
    'filter-observation-supported-set-safe-v194-development';
context.protocolId = protocol.id;
context.policyName = protocol.outcomePolicyName;
end

