function context = ...
        buildIndependentM24GatewayTeacherV252ExecutionContext( ...
            presetName, seed, measurementTimeCount, phase, ...
            anchorTime, candidateIndex)
% BUILDINDEPENDENTM24GATEWAYTEACHERV252EXECUTIONCONTEXT Paired data run.

protocol = getIndependentM24GatewayTeacherV252Protocol();
source = getCausalMinimumFormationBackboneV242Protocol();
action = getCausalGatewayEmbeddingV250Protocol();
validPhase = ischar(phase) && any(strcmp(phase, { ...
    'reference-prefix', 'candidate-reference', 'candidate-action'}));
validCommon = ischar(presetName) && ...
    ismember(presetName, protocol.allowedPresets) && ...
    ismember(seed, protocol.allowedSeeds) && ...
    isscalar(measurementTimeCount) && ...
    isfinite(measurementTimeCount) && ...
    measurementTimeCount >= 1 && ...
    measurementTimeCount == round(measurementTimeCount) && ...
    isscalar(anchorTime) && isfinite(anchorTime) && ...
    isscalar(candidateIndex) && isfinite(candidateIndex) && ...
    candidateIndex == round(candidateIndex);
if ~validPhase || ~validCommon
    error('IndependentM24GatewayTeacherV252:InvalidContextInput', ...
        'V252 requires a registered seed, phase and time axis.');
end

switch phase
    case 'reference-prefix'
        validSpecific = anchorTime == 0 && candidateIndex == 1 && ...
            measurementTimeCount == max(protocol.anchorTimes);
        policyName = source.policyName;
        armId = source.armId;
    case 'candidate-reference'
        validSpecific = ismember(anchorTime, protocol.anchorTimes) && ...
            candidateIndex == 1 && measurementTimeCount == ...
                anchorTime + protocol.horizonSteps - 1;
        policyName = source.policyName;
        armId = source.armId;
    otherwise
        validSpecific = ismember(anchorTime, protocol.anchorTimes) && ...
            candidateIndex >= 2 && ...
            candidateIndex <= protocol.maximumCandidateCount && ...
            measurementTimeCount == ...
                anchorTime + protocol.horizonSteps - 1;
        policyName = action.policyName;
        armId = protocol.armId;
end
if ~validSpecific
    error('IndependentM24GatewayTeacherV252:InvalidContextPhase', ...
        'The V252 phase does not match its anchor or candidate index.');
end

context = struct();
context.contractVersion = ...
    'independent-m24-gateway-teacher-v252-context-v1';
context.capability = ...
    'independent-m24-gateway-teacher-v252-development';
context.action = ...
    'filter-independent-m24-gateway-teacher-v252-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = armId;
context.measurementTimeCount = measurementTimeCount;
context.phase = phase;
context.anchorTime = anchorTime;
context.candidateIndex = candidateIndex;
context.policyName = policyName;
context.developmentEvidenceOnly = true;
end
