function [proposals, details] = ...
        buildFormationCommonLabelRepairProposalsV188( ...
            cache, localPosteriorBySensor, physicalAdjacency, ...
            sensorGroupIds, model, options)
% BUILDFORMATIONCOMMONLABELREPAIRPROPOSALSV188 Build executable actions.
%
% The light synopsis chooses at most one common (source,label) pair for
% each formation.  This builder then resolves that routing key to the
% complete Bernoulli GM object actually held by the source and charges a
% rich synopsis, one request, and one complete response per receiver.  The
% global light-synopsis cost is deliberately excluded because it is paid
% once by preflightBudgetRecycledRepairSynopsisV188 before this function.

if nargin < 6 || isempty(options)
    options = struct();
end
validateInputs( ...
    cache, localPosteriorBySensor, physicalAdjacency, sensorGroupIds);
protocol = getBudgetRecycledFormationRepairV188Protocol();
opportunityOptions = getField( ...
    options, 'opportunityOptions', struct());
if ~isfield(opportunityOptions, 'minimumRiskReductionThreshold')
    opportunityOptions.minimumRiskReductionThreshold = 0;
end
minimumUtilityLowerBound = getField( ...
    options, 'minimumUtilityLowerBound', 0);
rollingConnectivityPassed = getField( ...
    options, 'rollingConnectivityPassed', true);
if ~isscalar(minimumUtilityLowerBound) || ...
        ~isnumeric(minimumUtilityLowerBound) || ...
        ~isfinite(minimumUtilityLowerBound) || ...
        ~validBoolean(rollingConnectivityPassed)
    error('FormationRepairProposalV188:InvalidOptions', ...
        'The proposal threshold or connectivity certificate is invalid.');
end

physicalAdjacency = logical(physicalAdjacency);
groupIds = reshape(sensorGroupIds, 1, []);
opportunity = ...
    computeFormationCommonLabelRepairOpportunityFromSynopsisV188( ...
        cache, physicalAdjacency, groupIds, opportunityOptions);
proposals = repmat(emptyProposal(), 1, 0);
rejectedNoAction = 0;
rejectedNonpositiveUtility = 0;
rejectedMissingPayload = 0;
rejectedPayloadThreshold = 0;
for formationIdx = 1:numel(opportunity.formationIds)
    sourceIdx = opportunity.bestSource(formationIdx);
    label = opportunity.bestLabel(:, formationIdx);
    utilityLowerBound = ...
        opportunity.minimumRiskReduction(formationIdx);
    if sourceIdx == 0 || ~all(isfinite(label)) || ...
            ~isfinite(utilityLowerBound)
        rejectedNoAction = rejectedNoAction + 1;
        continue;
    end
    if utilityLowerBound <= minimumUtilityLowerBound + 1e-15 || ...
            opportunity.opportunity(formationIdx) <= 0
        rejectedNonpositiveUtility = ...
            rejectedNonpositiveUtility + 1;
        continue;
    end
    receivers = find(groupIds == ...
        opportunity.formationIds(formationIdx));
    sourceObject = findLabelObject( ...
        localPosteriorBySensor{sourceIdx}, label);
    if isempty(sourceObject)
        rejectedMissingPayload = rejectedMissingPayload + 1;
        continue;
    end
    responseStats = estimateLmbPayloadSize( ...
        sourceObject, model, 2, struct());
    if responseStats.objectCount ~= 1 || ...
            responseStats.estimatedBytes <= 0
        rejectedPayloadThreshold = rejectedPayloadThreshold + 1;
        continue;
    end
    commonSourcePassed = all( ...
        physicalAdjacency(receivers, sourceIdx));
    proposal = emptyProposal();
    proposal.formationId = ...
        opportunity.formationIds(formationIdx);
    proposal.receiverIds = reshape(receivers, 1, []);
    proposal.sourceId = sourceIdx;
    proposal.label = label;
    proposal.sourceObject = sourceObject;
    proposal.richSynopsisBytes = ...
        protocol.richSynopsisBytesPerShortlistedLabel;
    proposal.requestBytes = protocol.completeLabelRequestBytes;
    proposal.completeResponseBytesPerReceiver = ...
        responseStats.estimatedBytes;
    proposal.responseBytes = numel(receivers) * ...
        responseStats.estimatedBytes;
    proposal.attemptedBytes = proposal.richSynopsisBytes + ...
        proposal.requestBytes + proposal.responseBytes;
    proposal.estimatedUtilityLowerBound = utilityLowerBound;
    proposal.rankingOpportunity = ...
        opportunity.opportunity(formationIdx);
    proposal.minimumRiskReduction = utilityLowerBound;
    proposal.minimumReceiverExistence = ...
        opportunity.minimumReceiverExistence(formationIdx);
    proposal.peerConsensus = ...
        opportunity.bestPeerConsensus(formationIdx);
    proposal.receiverCompatibility = ...
        opportunity.bestReceiverCompatibility(formationIdx);
    proposal.commonSourcePassed = commonSourcePassed;
    proposal.safetyPassed = commonSourcePassed && ...
        utilityLowerBound > minimumUtilityLowerBound;
    proposal.rollingConnectivityPassed = ...
        logical(rollingConnectivityPassed);
    proposals(end + 1) = proposal; %#ok<AGROW>
end

details = struct();
details.contractVersion = ...
    'formation-common-label-repair-proposals-v188-v1';
details.opportunity = opportunity;
details.proposalCount = numel(proposals);
details.rejectedNoAction = rejectedNoAction;
details.rejectedNonpositiveUtility = rejectedNonpositiveUtility;
details.rejectedMissingPayload = rejectedMissingPayload;
details.rejectedPayloadThreshold = rejectedPayloadThreshold;
details.minimumUtilityLowerBound = minimumUtilityLowerBound;
details.lightSynopsisBytesExcluded = true;
details.payloadMode = ...
    protocol.selectedRepairPayloadMode;
details.truthUsed = false;
details.futureInformationUsed = false;
details.numericLabelIdentifiersUsedAsFeatures = false;
details.trackingLossBoundClaimed = false;
end

function validateInputs( ...
        cache, localPosteriorBySensor, physicalAdjacency, sensorGroupIds)
if ~isstruct(cache) || ~isfield(cache, 'contractVersion') || ...
        ~strcmp(cache.contractVersion, ...
        'formation-repair-light-synopsis-cache-v188-v1')
    error('FormationRepairProposalV188:CacheContractDrift', ...
        'A frozen V188 synopsis cache is required.');
end
sensorCount = cache.sensorCount;
groupIds = reshape(sensorGroupIds, 1, []);
if ~iscell(localPosteriorBySensor) || ...
        numel(localPosteriorBySensor) ~= sensorCount || ...
        ~isequal(size(physicalAdjacency), [sensorCount, sensorCount]) || ...
        numel(groupIds) ~= sensorCount || ...
        any(~isfinite(groupIds)) || ...
        any(groupIds ~= round(groupIds)) || any(groupIds < 1)
    error('FormationRepairProposalV188:InvalidInput', ...
        'The executable proposal inputs are malformed.');
end
end

function object = findLabelObject(objects, label)
object = [];
objects = reshape(objects, 1, []);
for objectIdx = 1:numel(objects)
    candidate = objects(objectIdx);
    if candidate.birthTime == label(1) && ...
            candidate.birthLocation == label(2)
        object = candidate;
        return;
    end
end
end

function proposal = emptyProposal()
proposal = struct( ...
    'formationId', 0, ...
    'receiverIds', zeros(1, 0), ...
    'sourceId', 0, ...
    'label', zeros(2, 1), ...
    'sourceObject', [], ...
    'richSynopsisBytes', 0, ...
    'requestBytes', 0, ...
    'completeResponseBytesPerReceiver', 0, ...
    'responseBytes', 0, ...
    'attemptedBytes', 0, ...
    'estimatedUtilityLowerBound', 0, ...
    'rankingOpportunity', 0, ...
    'minimumRiskReduction', 0, ...
    'minimumReceiverExistence', 0, ...
    'peerConsensus', 0, ...
    'receiverCompatibility', 1, ...
    'commonSourcePassed', false, ...
    'safetyPassed', false, ...
    'rollingConnectivityPassed', false);
end

function valid = validBoolean(value)
valid = isscalar(value) && ...
    (islogical(value) || (isnumeric(value) && isfinite(value) && ...
    (value == 0 || value == 1)));
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
