function config = buildCausalMinimumFormationBackboneV242Config(scenario)
% BUILDCAUSALMINIMUMFORMATIONBACKBONEV242CONFIG Sparse dynamic route.

protocol = getCausalMinimumFormationBackboneV242Protocol();
if ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets) || ...
        ~isfield(scenario, 'numberOfSensors') || ...
        ~isfield(scenario, 'sensorGroupIds')
    error('CausalMinimumFormationBackboneV242:InvalidConfigInput', ...
        'V242 requires one registered formation-braid scenario.');
end
formationCount = numel(unique(scenario.sensorGroupIds));
minimumMessageCount = scenario.numberOfSensors + ...
    2 * (formationCount - 1);
config = buildCausalMinimalEditFormationTreeV240Config(scenario);
config.topologyPolicyName = protocol.policyName;
config.topologyPolicyFcn = ...
    @selectCausalMinimumFormationBackboneV242Policy;
config.topologyDirectedMessageBudget = minimumMessageCount;
end
