function [candidateAdjacency, candidateRecords, metadata] = ...
    buildBackboneResidualReturnProposalBank(context, options)
% BUILDBACKBONERESIDUALRETURNPROPOSALBANK Diverse safe first actions.
%
% Candidate construction does not inspect future measurements or returns.
% Most score directions are truth-free. The current-risk score family is
% truth-assisted and is marked as an offline, nondeployable proposal
% source. Every admitted graph preserves the fixed-index dominant route,
% executes without repair, and has the same message count as the matched
% static residual control.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getBackboneResidualReturnHeadroomProtocol();
dominantWeight = getField(options, ...
    'dominantWeight', protocol.dominantWeight);
residualWeight = getField(options, ...
    'residualWeight', protocol.residualWeight);
payloadToleranceFraction = getField(options, ...
    'payloadToleranceFraction', ...
    protocol.payloadToleranceFraction);
nodeCount = numel(context.localPosteriorBySensor);
if context.currentTime ~= protocol.currentTime || ...
        nodeCount ~= 24
    error('Return proposal bank requires the frozen M24 t=75 state.');
end

[staticAdjacency, staticDetails] = ...
    selectBackbonePreservingResidualControl( ...
        context, baseOptions());
expectedMessageCount = nnz(staticAdjacency);
candidateAdjacency = false(nodeCount, nodeCount, 0);
candidateRecords = repmat(emptyRecord(), 1, 0);
graphKeys = cell(1, 0);
attempts = repmat(emptyAttempt(), 1, 0);

addAttempt('static-residual', 'truth-free-control', ...
    false, @() deal(staticAdjacency, staticDetails));
for rootFormation = protocol.scheduledRoots
    for orientationIdx = 1:numel( ...
            protocol.scheduledOrientations)
        orientation = protocol. ...
            scheduledOrientations{orientationIdx};
        for temporalPhase = ...
                protocol.scheduledTemporalPhases
            proposalId = sprintf( ...
                'scheduled-r%d-%s-p%d', ...
                rootFormation, shortOrientation(orientation), ...
                temporalPhase);
            policyOptions = baseOptions();
            policyOptions.rootFormation = rootFormation;
            policyOptions.orientation = orientation;
            policyOptions.temporalPhase = temporalPhase;
            addAttempt(proposalId, ...
                'truth-free-scheduled-control', false, ...
                @() ...
                    selectBackbonePreservingResidualRoutingPolicy( ...
                        context, 'scheduled-burst', ...
                        policyOptions));
        end
    end
end

[registry, registryMetadata] = ...
    getRollingSafeObservableScoreBasisRegistry();
for actionCode = protocol.observableActionCodes
    entryIdx = find([registry.actionCode] == actionCode, 1);
    if isempty(entryIdx)
        error('Missing observable action code %d.', actionCode);
    end
    entry = registry(entryIdx);
    policyOptions = baseOptions();
    policyOptions.edgeScoreFcnReturnsDetails = true;
    policyOptions.edgeScoreFcn = ...
        @(scoreContext, receiverIndices, senderIndices, ...
            baselineSources) ...
            computeRollingSafeObservableBasisScores( ...
                scoreContext, receiverIndices, senderIndices, ...
                baselineSources, entry, residualWeight);
    policyOptions.posteriorUsed = entry.posteriorUsed;
    policyOptions.truthUsed = false;
    policyOptions.currentLinkReliabilityUsed = ...
        entry.currentLinkReliabilityUsed;
    policyOptions.minimumCurrentCrossEdges = ...
        entry.exactCurrentCrossEdgeCount;
    policyOptions.maximumCurrentCrossEdges = ...
        entry.exactCurrentCrossEdgeCount;
    proposalId = sprintf( ...
        'observable-%02d-%s', actionCode, entry.basisId);
    addAttempt(proposalId, 'truth-free-observable-basis', ...
        false, @() ...
            selectBackbonePreservingResidualRoutingPolicy( ...
                context, 'external-scores', policyOptions));
end

addAttempt('posterior-analytic', ...
    'truth-free-posterior-analytic', false, ...
    @() selectBackbonePreservingResidualRoutingPolicy( ...
        context, 'posterior-analytic', baseOptions()));

[receiverIndices, senderIndices] = ...
    enumerateCrossCandidates(context);
[~, residualBaselineDetails] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-balanced-cycle', ...
        struct('sourceWeight', residualWeight, 'phase', 1));
residualBaselineSources = reshape( ...
    residualBaselineDetails.selectedSourcesByReceiver, 1, []);
teacherOptions = struct( ...
    'dominantWeight', dominantWeight, ...
    'residualWeight', residualWeight, ...
    'horizonSteps', 0, ...
    'discountFactor', 0.9);
[teacherScores, teacherDetails] = ...
    computeBackbonePreservingResidualTaskTeacherScores( ...
        context, receiverIndices, senderIndices, ...
        residualBaselineSources, teacherOptions);
scoreMatrix = -inf(nodeCount);
for exampleIdx = 1:numel(receiverIndices)
    scoreMatrix(receiverIndices(exampleIdx), ...
        senderIndices(exampleIdx)) = teacherScores(exampleIdx);
end
teacherBaseOptions = baseOptions();
teacherBaseOptions.edgeScoreMatrix = scoreMatrix;
teacherBaseOptions.posteriorUsed = true;
teacherBaseOptions.truthUsed = true;
teacherBaseOptions.currentLinkReliabilityUsed = true;
addAttempt('truth-current-base', ...
    'offline-truth-current-risk', true, ...
    @() selectBackbonePreservingResidualRoutingPolicy( ...
        context, 'external-scores', teacherBaseOptions));

baseRecordIdx = find(strcmp( ...
    {candidateRecords.proposalId}, ...
    'truth-current-base'), 1);
if ~isempty(baseRecordIdx)
    selectedExamples = reshape(candidateRecords( ...
        baseRecordIdx).policyDetails. ...
        selectedCrossExampleIndices, 1, []);
    banSets = buildBanSets(selectedExamples, ...
        protocol.currentTeacherMaximumBanCount);
    for banIdx = 1:numel(banSets)
        allowed = true(numel(receiverIndices), 1);
        allowed(banSets{banIdx}) = false;
        diverseOptions = teacherBaseOptions;
        diverseOptions.currentAllowedExampleMask = allowed;
        proposalId = sprintf('truth-current-ban-%s', ...
            sprintf('%d-', banSets{banIdx}));
        proposalId(end) = [];
        addAttempt(proposalId, ...
            'offline-truth-current-risk-diverse', true, ...
            @() ...
                selectBackbonePreservingResidualRoutingPolicy( ...
                    context, 'external-scores', ...
                    diverseOptions));
    end
end

metadata = struct();
metadata.contractVersion = ...
    'backbone-residual-return-proposal-bank-v1';
metadata.protocolId = protocol.id;
metadata.generatedAt = datestr(now, 31);
metadata.currentTime = context.currentTime;
metadata.nodeCount = nodeCount;
metadata.dominantWeight = dominantWeight;
metadata.residualWeight = residualWeight;
metadata.payloadToleranceFraction = ...
    payloadToleranceFraction;
metadata.expectedMessageCount = expectedMessageCount;
metadata.distinctCandidateCount = ...
    size(candidateAdjacency, 3);
metadata.maximumDistinctCandidateCount = ...
    protocol.maximumDistinctCandidateCount;
metadata.attemptCount = numel(attempts);
metadata.acceptedCount = nnz(strcmp( ...
    {attempts.status}, 'accepted'));
metadata.duplicateCount = nnz(strcmp( ...
    {attempts.status}, 'duplicate'));
metadata.unavailableCount = nnz(strcmp( ...
    {attempts.status}, 'unavailable'));
metadata.truthAssistedDistinctCount = nnz( ...
    [candidateRecords.offlineProposalTruthUsed]);
metadata.futureOutcomeUsed = false;
metadata.candidateRankingPerformed = false;
metadata.observableRegistrySha256 = ...
    registryMetadata.registrySha256;
metadata.teacherScoreDetails = teacherDetails;
metadata.attempts = attempts;
metadata.deployable = false;

    function optionsOut = baseOptions()
        optionsOut = struct( ...
            'dominantWeight', dominantWeight, ...
            'residualWeight', residualWeight, ...
            'sourceWeight', residualWeight, ...
            'payloadToleranceFraction', ...
                payloadToleranceFraction);
    end

    function addAttempt( ...
            proposalId, family, offlineTruthUsed, policyFcn)
        attempt = emptyAttempt();
        attempt.proposalId = proposalId;
        attempt.family = family;
        attempt.offlineProposalTruthUsed = ...
            offlineTruthUsed;
        try
            [adjacency, details] = policyFcn();
            validateCandidate(adjacency, details);
            graphKey = sprintf('%d,', adjacency(:));
            existingIdx = find(strcmp(graphKeys, graphKey), 1);
            attempt.graphSha256 = computeTextSha256(graphKey);
            if ~isempty(existingIdx)
                attempt.status = 'duplicate';
                attempt.candidateIndex = existingIdx;
                candidateRecords(existingIdx).proposalAliases{end + 1} = ...
                    proposalId;
                candidateRecords(existingIdx).offlineProposalTruthUsed = ...
                    candidateRecords(existingIdx). ...
                        offlineProposalTruthUsed || ...
                    offlineTruthUsed;
                attempts(end + 1) = attempt;
                return;
            end
            if size(candidateAdjacency, 3) >= ...
                    protocol.maximumDistinctCandidateCount
                error('Return proposal bank exceeded its candidate cap.');
            end
            candidateIdx = size(candidateAdjacency, 3) + 1;
            candidateAdjacency(:, :, candidateIdx) = adjacency;
            graphKeys{candidateIdx} = graphKey;
            record = emptyRecord();
            record.candidateIndex = candidateIdx;
            record.proposalId = proposalId;
            record.proposalAliases = {proposalId};
            record.family = family;
            record.graphSha256 = attempt.graphSha256;
            record.offlineProposalTruthUsed = offlineTruthUsed;
            record.futureOutcomeUsed = false;
            record.messageCount = nnz(adjacency);
            record.crossFormationMessageCount = getField( ...
                details, 'crossFormationMessageCount', 0);
            record.policyDetails = details;
            candidateRecords(candidateIdx) = record;
            attempt.status = 'accepted';
            attempt.candidateIndex = candidateIdx;
        catch errorInfo
            if ~isUnavailable(errorInfo)
                rethrow(errorInfo);
            end
            attempt.status = 'unavailable';
            attempt.failureIdentifier = errorInfo.identifier;
            attempt.failureMessage = errorInfo.message;
        end
        attempts(end + 1) = attempt;
    end

    function validateCandidate(adjacency, details)
        if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
                any(adjacency(:) & ...
                    ~logical(context.physicalAdjacency(:))) || ...
                nnz(adjacency) ~= expectedMessageCount || ...
                ~isfield(details, 'fusionWeightMatrix') || ...
                any(abs(sum(details.fusionWeightMatrix, 2) - 1) > ...
                    1e-12) || ...
                logical(getField(details, ...
                    'repairTriggered', false)) || ...
                logical(getField(details, ...
                    'payloadEmergencyUsed', false)) || ...
                logical(getField(details, ...
                    'topologyInfeasible', false))
            error('ReturnProposal:InvalidCandidate', ...
                'Candidate violates route, message, or safety invariants.');
        end
        [dominantAdjacency, ~] = ...
            selectRegisteredDirectedRoutingPolicy( ...
                context, 'fixed-index-star', ...
                struct('sourceWeight', dominantWeight));
        if any(dominantAdjacency(:) & ~adjacency(:))
            error('ReturnProposal:MissingDominantBackbone', ...
                'Candidate deleted a dominant route.');
        end
    end
end

function [receiverIndices, senderIndices] = ...
    enumerateCrossCandidates(context)
[receiverIndices, senderIndices] = ...
    find(logical(context.physicalAdjacency));
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
crossMask = groupIds(receiverIndices) ~= ...
    groupIds(senderIndices);
receiverIndices = receiverIndices(crossMask);
senderIndices = senderIndices(crossMask);
end

function sets = buildBanSets(indices, maximumCount)
indices = unique(reshape(indices, 1, []), 'stable');
sets = cell(1, 0);
for count = 1:min(maximumCount, numel(indices))
    combinations = nchoosek(indices, count);
    for rowIdx = 1:size(combinations, 1)
        sets{end + 1} = combinations(rowIdx, :); %#ok<AGROW>
    end
end
end

function value = shortOrientation(orientation)
if strcmp(orientation, 'clockwise')
    value = 'cw';
else
    value = 'ccw';
end
end

function tf = isUnavailable(errorInfo)
tf = ~isempty(strfind(errorInfo.identifier, ...
    'ObservableBasis:Unavailable')) || ... %#ok<STREMP>
    ~isempty(strfind(errorInfo.message, ...
        'No feasible joint rolling matching')) || ... %#ok<STREMP>
    ~isempty(strfind(errorInfo.message, ...
        'could not realize exact')) || ... %#ok<STREMP>
    ~isempty(strfind(errorInfo.message, ...
        'payload')) || ... %#ok<STREMP>
    ~isempty(strfind(errorInfo.message, ...
        'projection')); %#ok<STREMP>
end

function record = emptyRecord()
record = struct( ...
    'candidateIndex', NaN, ...
    'proposalId', '', ...
    'proposalAliases', {{}}, ...
    'family', '', ...
    'graphSha256', '', ...
    'offlineProposalTruthUsed', false, ...
    'futureOutcomeUsed', false, ...
    'messageCount', NaN, ...
    'crossFormationMessageCount', NaN, ...
    'policyDetails', struct());
end

function attempt = emptyAttempt()
attempt = struct( ...
    'proposalId', '', ...
    'family', '', ...
    'offlineProposalTruthUsed', false, ...
    'status', '', ...
    'candidateIndex', NaN, ...
    'graphSha256', '', ...
    'failureIdentifier', '', ...
    'failureMessage', '');
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
