function bank = buildReceiverDomainTransportActionBankV71( ...
        context, options)
% BUILDRECEIVERDOMAINTRANSPORTACTIONBANKV71 Reference/candidate H=3 bank.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getReceiverDomainTransportH3V72Protocol();
v71 = getReceiverDomainTransportProjectionV71Protocol();
caseInfo = resolveCase(context, protocol, options);
expectedFormationIds = getField(options, ...
    'expectedSelectedFormationIds', ...
    caseInfo.expectedSelectedFormationIds);
expectedSlotCount = getField(options, ...
    'expectedSelectedSlotCount', caseInfo.expectedSelectedSlotCount);
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
v70 = getReceiverDomainNormalizedOpportunityV70Protocol();
[~, control] = computeFormationRoutingLeverageSignature( ...
    context, groupIds, struct('referenceMode', 'current-physical-tree'));
base = computeNetworkAdditiveFormationRiskV65( ...
    control, context, groupIds, v70.positiveSupportThreshold);
influence = computeInfluenceAwareDecisionBreadthV66( ...
    control, context, groupIds, struct( ...
        'positiveSupportThreshold', v70.positiveSupportThreshold, ...
        'horizonSteps', v70.horizonSteps));
transport = computeAlternativeTransportHeadroomV68( ...
    context, control, groupIds, ...
    getSignedMergeSplitOpportunityV69Protocol());
local = computeReceiverDomainNormalizedOpportunityV70( ...
    base, influence, control, transport, groupIds, v70);
projection = buildReceiverDomainTransportProjectionV71( ...
    context, control, transport, local, groupIds, ...
    getReceiverDomainTransportProjectionV71Protocol());
if projection.referenceFallbackUsed || ...
        ~isequal(projection.selectedFormationIds, ...
            reshape(expectedFormationIds, 1, [])) || ...
        numel(projection.selectedSlotIndices) ~= expectedSlotCount || ...
        ~projection.messageCountParityWithReference || ...
        ~projection.perReceiverMessageCountParityWithReference || ...
        ~projection.perReceiverWeightMultisetParityWithReference || ...
        ~all(projection.selectedRollingB3SensorPass) || ...
        ~all(projection.selectedRollingB3FormationPass)
    error('ReceiverDomainTransportV72:SourceDrift', ...
        'The V71 source action no longer matches its frozen outcome gate.');
end

nodeCount = numel(groupIds);
groups = unique(groupIds, 'stable');
candidateTrustWeights = reshape(getField(options, ...
    'candidateTrustWeights', v71.sourceWeight), 1, []);
directSafeFormationIds = reshape(getField(options, ...
    'directSafeFormationIds', projection.selectedFormationIds), 1, []);
selfFundedTrust = logical(getField(options, ...
    'selfFundedTrust', false));
rollingB3DurationSteps = getField(options, ...
    'rollingB3DurationSteps', 1);
rollingB3ActionUse = getField(options, ...
    'rollingB3ActionUse', []);
if isempty(rollingB3ActionUse)
    rollingB3ActionUse = false(1, 3);
    rollingB3ActionUse(1:rollingB3DurationSteps) = true;
else
    rollingB3ActionUse = logical(reshape( ...
        rollingB3ActionUse, 1, []));
end
if isempty(candidateTrustWeights) || ...
        any(~isfinite(candidateTrustWeights)) || ...
        any(candidateTrustWeights < v71.sourceWeight - 1e-12) || ...
        any(candidateTrustWeights >= 0.25 - 1e-12) || ...
        numel(unique(candidateTrustWeights)) ~= ...
            numel(candidateTrustWeights) || ...
        isempty(directSafeFormationIds) || ...
        any(~ismember(directSafeFormationIds, ...
            projection.selectedFormationIds)) || ...
        ~isscalar(rollingB3DurationSteps) || ...
        ~isfinite(rollingB3DurationSteps) || ...
        rollingB3DurationSteps ~= round(rollingB3DurationSteps) || ...
        rollingB3DurationSteps < 1 || rollingB3DurationSteps > 3 || ...
        numel(rollingB3ActionUse) ~= 3 || ...
        ~any(rollingB3ActionUse) || ...
        (~selfFundedTrust && any(abs(candidateTrustWeights - ...
            v71.sourceWeight) > 1e-12))
    error('ReceiverDomainTransportV72:InvalidTrustBank', ...
        'Receiver-domain trust-bank options are invalid.');
end
[candidateAdjacency, candidateWeights, changedReceivers, ...
    selectedSlotIndices, selectedUtilityMass] = ...
        buildFilteredTrustAction(projection, groupIds, ...
            directSafeFormationIds, v71.sourceWeight, ...
            v71.sourceWeight, false);
candidateSequence = repmat( ...
    projection.referenceAdjacency, 1, 1, 3);
for sequenceIdx = find(rollingB3ActionUse)
    candidateSequence(:, :, sequenceIdx) = candidateAdjacency;
end
[candidateSensorPass, candidateFormationPass] = rollingB3Pass( ...
    context.previousAdjacencyHistory, candidateSequence, groupIds);
if ~all(candidateSensorPass) || ~all(candidateFormationPass)
    error('ReceiverDomainTransportV72:UnsafeFilteredRoute', ...
        'The filtered receiver-domain route fails rolling-B3.');
end
actionCount = 1 + numel(candidateTrustWeights);
bank = struct();
if selfFundedTrust
    bank.contractVersion = ...
        'receiver-domain-self-funded-trust-action-bank-v83-v1';
else
    bank.contractVersion = ...
        'receiver-domain-transport-action-bank-v71-v1';
end
bank.protocolId = protocol.sourceProtocolId;
bank.referenceMode = 'current-physical-tree';
bank.nodeCount = nodeCount;
bank.formationCount = numel(groups);
bank.groupIds = groupIds;
bank.actionCount = actionCount;
bank.referenceActionIndex = 1;
bank.actionNames = cell(1, actionCount);
bank.actionNames{1} = 'reference';
bank.actionFormationIds = cell(1, actionCount);
bank.actionFormationIds{1} = zeros(1, 0);
bank.actionSlotIndices = cell(1, actionCount);
bank.actionSlotIndices{1} = zeros(1, 0);
bank.actionAdjacency = repmat( ...
    projection.referenceAdjacency, 1, 1, actionCount);
bank.actionFusionWeights = repmat( ...
    projection.referenceFusionWeights, 1, 1, actionCount);
bank.actionMessageCounts = repmat( ...
    projection.referenceMessageCount, 1, actionCount);
bank.actionWithinReferencePayload = true(1, actionCount);
bank.actionPosteriorSafetyMask = true(1, actionCount);
bank.actionPosteriorProxyAllowed = true(1, actionCount);
bank.actionPosteriorObjective = zeros(1, actionCount);
bank.actionPredictedNetSavingBytes = [0, ...
    NaN(1, actionCount - 1)];
bank.actionPayloadBytes = NaN(1, actionCount);
bank.actionFormationIndex = zeros(1, actionCount);
bank.actionModeIndex = 1:actionCount;
bank.modeTrustWeights = [0, candidateTrustWeights];
bank.actionRollingB3SensorPass = repmat( ...
    projection.referenceRollingB3SensorPass, actionCount, 1);
bank.actionRollingB3FormationPass = repmat( ...
    projection.referenceRollingB3FormationPass, actionCount, 1);
for trustIdx = 1:numel(candidateTrustWeights)
    actionIdx = trustIdx + 1;
    trustWeight = candidateTrustWeights(trustIdx);
    [adjacency, weights, actionReceivers, actionSlots, utilityMass] = ...
        buildFilteredTrustAction(projection, groupIds, ...
            directSafeFormationIds, trustWeight, ...
            v71.sourceWeight, selfFundedTrust);
    if ~isequal(actionReceivers, changedReceivers) || ...
            ~isequal(actionSlots, selectedSlotIndices) || ...
            abs(utilityMass - selectedUtilityMass) > 1e-12
        error('ReceiverDomainTransportV72:TrustBankDrift', ...
            'Trust variants do not share one frozen route.');
    end
    bank.actionNames{actionIdx} = sprintf( ...
        'receiver-domain-route-trust-%02d', ...
        round(100 * trustWeight));
    bank.actionFormationIds{actionIdx} = directSafeFormationIds;
    bank.actionSlotIndices{actionIdx} = selectedSlotIndices;
    bank.actionAdjacency(:, :, actionIdx) = adjacency;
    bank.actionFusionWeights(:, :, actionIdx) = weights;
    bank.actionMessageCounts(actionIdx) = nnz(adjacency);
    bank.actionPosteriorObjective(actionIdx) = ...
        selectedUtilityMass * trustWeight / v71.sourceWeight;
    bank.actionRollingB3SensorPass(actionIdx, :) = ...
        candidateSensorPass;
    bank.actionRollingB3FormationPass(actionIdx, :) = ...
        candidateFormationPass;
end
bank.safeActionIndices = 1:actionCount;
bank.referenceMessageCount = projection.referenceMessageCount;
bank.selectedMessageCount = nnz(candidateAdjacency);
bank.selectedUtilityMass = selectedUtilityMass;
networkMass = projection.selectedUtilityMass / ...
    projection.selectedNetworkAverageNetFraction;
bank.selectedNetworkAverageNetFraction = ...
    selectedUtilityMass / networkMass;
bank.directSafeFormationIds = directSafeFormationIds;
bank.changedReceiverIndices = changedReceivers;
bank.candidateTrustWeights = candidateTrustWeights;
bank.selfFundedTrust = selfFundedTrust;
bank.rollingB3DurationSteps = rollingB3DurationSteps;
bank.rollingB3ActionUse = rollingB3ActionUse;
if selfFundedTrust
    bank.trustFundingSource = 'receiver-self-weight';
else
    bank.trustFundingSource = 'reference-row-weight-multiset';
end
bank.sourceProjection = projection;
bank.truthUsed = false;
bank.futureOutcomeUsed = false;
bank.openedDevelopmentEvidenceOnly = true;
bank.validationClaimAllowed = false;
end

function [adjacency, weights, changedReceivers, selectedSlotIndices, ...
        selectedUtilityMass] = buildFilteredTrustAction( ...
        projection, groupIds, safeFormationIds, trustWeight, ...
        sourceWeight, selfFundedTrust)
referenceAdjacency = logical(projection.referenceAdjacency);
selectedAdjacency = logical(projection.selectedAdjacency);
referenceWeights = projection.referenceFusionWeights;
adjacency = referenceAdjacency;
weights = referenceWeights;
changedReceivers = reshape(find(any( ...
    selectedAdjacency ~= referenceAdjacency, 2)), 1, []);
changedReceivers = changedReceivers(ismember( ...
    groupIds(changedReceivers), safeFormationIds));
if isempty(changedReceivers)
    error('ReceiverDomainTransportV72:EmptyFilteredRoute', ...
        'No receiver remains after direct-safe formation filtering.');
end
for receiverIdx = changedReceivers
    incumbent = reshape(find(referenceAdjacency(receiverIdx, :) & ...
        ~selectedAdjacency(receiverIdx, :)), 1, []);
    candidate = reshape(find(selectedAdjacency(receiverIdx, :) & ...
        ~referenceAdjacency(receiverIdx, :)), 1, []);
    if numel(incumbent) ~= 1 || numel(candidate) ~= 1 || ...
            abs(referenceWeights(receiverIdx, incumbent) - ...
                sourceWeight) > 1e-12 || ...
            groupIds(incumbent) == groupIds(receiverIdx) || ...
            groupIds(candidate) == groupIds(receiverIdx)
        error('ReceiverDomainTransportV72:InvalidFilteredSlot', ...
            'A filtered receiver row is not one residual replacement.');
    end
    adjacency(receiverIdx, incumbent) = false;
    adjacency(receiverIdx, candidate) = true;
    weights(receiverIdx, incumbent) = 0;
    weights(receiverIdx, candidate) = trustWeight;
    if selfFundedTrust
        weights(receiverIdx, receiverIdx) = ...
            referenceWeights(receiverIdx, receiverIdx) - ...
                (trustWeight - sourceWeight);
    end
end
support = adjacency | logical(eye(size(adjacency, 1)));
if any(weights(:) < -1e-12) || ...
        any(weights(:) > 1e-12 & ~support(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        any(weights(sub2ind(size(weights), ...
            changedReceivers, changedReceivers)) <= 0) || ...
        nnz(adjacency) ~= nnz(referenceAdjacency) || ...
        ~isequal(sum(adjacency, 2), sum(referenceAdjacency, 2))
    error('ReceiverDomainTransportV72:InvalidTrustWeights', ...
        'A trust variant violates row, support, or message constraints.');
end
selectedBundles = projection.formationBundles(ismember( ...
    [projection.formationBundles.formationId], safeFormationIds));
selectedSlotIndices = reshape([selectedBundles.slotIndices], 1, []);
selectedUtilityMass = sum([selectedBundles.netMass]);
end

function [sensorPass, formationPass] = ...
        rollingB3Pass(previousHistory, sequence, groupIds)
history = logical(previousHistory(:, :, end-1:end));
sensorPass = false(1, size(sequence, 3));
formationPass = false(1, size(sequence, 3));
for stepIdx = 1:size(sequence, 3)
    pages = cat(3, history, sequence(:, :, stepIdx));
    window = any(pages(:, :, max(1, end-2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = sequence(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function caseInfo = resolveCase(context, protocol, options)
requiredFields = {'presetName', 'seed', 'currentTime'};
if ~all(isfield(options, requiredFields)) || ...
        ~ischar(options.presetName) || ...
        ~isscalar(options.seed) || ~isfinite(options.seed) || ...
        ~isscalar(options.currentTime) || ...
        ~isfinite(options.currentTime) || ...
        options.currentTime ~= context.currentTime
    error('ReceiverDomainTransportV72:UnregisteredCase', ...
        'The V71 action bank needs one explicit frozen case identity.');
end
caseIndex = [];
for idx = 1:numel(protocol.cases)
    current = protocol.cases(idx);
    if strcmp(options.presetName, current.presetName) && ...
            options.seed == current.seed && ...
            options.currentTime == current.currentTime
        caseIndex = idx;
        break;
    end
end
if isempty(caseIndex) || ...
        numel(context.localPosteriorBySensor) ~= ...
            protocol.cases(caseIndex).expectedNodeCount
    error('ReceiverDomainTransportV72:UnregisteredCase', ...
        'The V71 action bank is restricted to two frozen V72 cases.');
end
caseInfo = protocol.cases(caseIndex);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
