function bank = buildBoundedDominantEdgeTransferV226ActionBank( ...
        context, groupIds, options)
% BUILDBOUNDEDDOMINANTEDGETRANSFERV226ACTIONBANK Frozen V226 arm.

if nargin < 3 || isempty(options)
    options = struct();
end
protocol = getBoundedDominantEdgeTransferV226Protocol();
options.inputRouteWeightMode = protocol.inputRouteWeightMode;
options.inputRouteEtaProjectionEnabled = true;
options.inputRouteMinimumMapExistence = getField(options, ...
    'inputRouteMinimumMapExistence', protocol.minimumMapExistence);
options.inputRouteMaximumReferenceLogOddsDrop = getField(options, ...
    'inputRouteMaximumReferenceLogOddsDrop', ...
    protocol.maximumReferenceLogOddsDrop);
options.inputRouteMaximumReferenceLogOddsIncrease = getField(options, ...
    'inputRouteMaximumReferenceLogOddsIncrease', ...
    protocol.maximumReferenceLogOddsIncrease);
options.inputRouteTransferFractionGrid = getField(options, ...
    'inputRouteTransferFractionGrid', protocol.transferFractionGrid);
options.inputRouteEtaIdentityTolerance = getField(options, ...
    'inputRouteEtaIdentityTolerance', protocol.identityTolerance);
bank = buildEtaSafeSemanticInputRoutingV223ActionBank( ...
    context, groupIds, options);

actionIdx = find((1:bank.actionCount) ~= bank.referenceActionIndex);
if numel(actionIdx) ~= 1 || ...
        ~strcmp(bank.inputRouteWeightMode, ...
            protocol.inputRouteWeightMode)
    error('BoundedDominantEdgeTransferV226:CarrierDrift', ...
        'V226 requires exactly one bounded eta-safe routed-label action.');
end
bank.actionNames{actionIdx} = sprintf( ...
    ['v226-bounded-donor-f%d-to-beneficiary-f%d-', ...
     'replace-dominant-nonself-s%d-l%d-%d'], ...
    bank.donorFormationId, bank.beneficiaryFormationId, ...
    bank.semanticShortcutSourceId, ...
    bank.semanticShortcutLabel(1), bank.semanticShortcutLabel(2));
bank.contractVersion = ...
    'bounded-dominant-edge-transfer-action-bank-v226-v1';
bank.bankVariant = 'bounded-dominant-edge-transfer-v226';
bank.protocolId = protocol.id;
bank.semanticFusionMode = protocol.semanticFusionMode;
bank.boundedDominantNonselfTransferEnabled = true;
bank.selfInputReplacementAllowed = false;
bank.totalLabelWeightPreserved = true;
bank.maximumReferenceLogOddsIncrease = ...
    options.inputRouteMaximumReferenceLogOddsIncrease;
bank.transferFractionGrid = ...
    reshape(options.inputRouteTransferFractionGrid, 1, []);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
