function context = buildAdaptiveLabelBoundaryEntryV115ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDADAPTIVELABELBOUNDARYENTRYV115EXECUTIONCONTEXT Frozen V115 context.

protocol = getAdaptiveLabelBoundaryEntryV115Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('AdaptiveLabelBoundaryEntryV115:InvalidExecutionContext', ...
        'The V115 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'adaptive-label-boundary-entry-v115-context-v1';
context.capability = ...
    'adaptive-label-boundary-entry-v115-development';
context.action = ...
    'filter-adaptive-label-boundary-entry-v115-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
