function context = ...
        buildCausalMinimumFormationBackboneV242ExecutionContext( ...
            presetName, seed, measurementTimeCount)
% BUILDCAUSALMINIMUMFORMATIONBACKBONEV242EXECUTIONCONTEXT Development run.

protocol = getCausalMinimumFormationBackboneV242Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~ismember(seed, protocol.allowedSeeds) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount < 1 || ...
        measurementTimeCount ~= round(measurementTimeCount)
    error('CausalMinimumFormationBackboneV242:InvalidExecutionContextInput', ...
        'V242 requires a registered scene, seed and time axis.');
end
context = struct();
context.contractVersion = ...
    'causal-minimum-formation-backbone-v242-context-v1';
context.capability = ...
    'causal-minimum-formation-backbone-v242-development';
context.action = ...
    'filter-causal-minimum-formation-backbone-v242-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = protocol.armId;
context.measurementTimeCount = measurementTimeCount;
context.policyName = protocol.policyName;
context.developmentEvidenceOnly = true;
end
