function context = buildFiniteDurationAbstentionV112ExecutionContext( ...
        presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDFINITEDURATIONABSTENTIONV112EXECUTIONCONTEXT Frozen label screen.

protocol = getFiniteDurationAbstentionV112Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('FiniteDurationAbstentionV112:InvalidExecutionContext', ...
        'The V112 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'finite-duration-abstention-v112-context-v1';
context.capability = ...
    'finite-duration-abstention-v112-development';
context.action = ...
    'filter-finite-duration-abstention-v112-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
