function config = buildRiskTriggeredFormationShortcutV261Config(scenario)
% BUILDRISKTRIGGEREDFORMATIONSHORTCUTV261CONFIG Exact-budget continuation.

protocol = getRiskTriggeredFormationShortcutV261Protocol();
if ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets) || ...
        ~isfield(scenario, 'numberOfSensors') || ...
        ~isfield(scenario, 'sensorGroupIds')
    error('RiskTriggeredShortcutV261:InvalidConfigInput', ...
        'V261 requires its registered M24 formation-braid scene.');
end
formationCount = numel(unique(scenario.sensorGroupIds));
minimumMessages = scenario.numberOfSensors + ...
    2 * (formationCount - 1);
config = buildCausalMinimumFormationBackboneV242Config(scenario);
config.topologyPolicyName = protocol.policyName;
config.topologyPolicyFcn = ...
    @selectRiskTriggeredFormationShortcutV261Policy;
config.topologyDirectedMessageBudget = minimumMessages;
end
