function context = ...
        buildPositiveValueReferenceLabelV157ExecutionContext( ...
            presetName, seed, currentTime, actionName, scheduleEnabled)
% BUILDPOSITIVEVALUEREFERENCELABELV157EXECUTIONCONTEXT Frozen V157 context.

protocol = getPositiveValueReferenceLabelV157Protocol();
if ~ischar(presetName) || isempty(presetName) || ...
        ~isscalar(seed) || ~isfinite(seed) || seed ~= round(seed) || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || ...
        ~ischar(actionName) || isempty(actionName) || ...
        ~isscalar(scheduleEnabled) || ...
        ~(islogical(scheduleEnabled) || isnumeric(scheduleEnabled))
    error('PositiveValueReferenceLabelV157:InvalidExecutionContext', ...
        'The V157 execution-context input is invalid.');
end
context = struct();
context.contractVersion = ...
    'positive-value-reference-label-v157-context-v1';
context.capability = ...
    'positive-value-reference-label-v157-development';
context.action = ...
    'filter-positive-value-reference-label-v157-development';
context.protocolId = protocol.id;
context.phase = 'opened-return';
context.presetName = presetName;
context.seed = seed;
context.currentTime = currentTime;
context.measurementTimeCount = ...
    currentTime + protocol.horizonSteps - 1;
context.policyName = protocol.outcomePolicyName;
context.actionName = actionName;
context.scheduleEnabled = logical(scheduleEnabled);
context.onlineReselectionEnabled = false;
context.developmentEvidenceOnly = true;
end
