function snapshot = buildDirectGraphFormationLearningSnapshotV218( ...
        sensorGroupIds, referenceAdjacency, fusionWeightMatrix, ...
        policyDetails)
% BUILDDIRECTGRAPHFORMATIONLEARNINGSNAPSHOTV218 Export scale-safe graph.
%
% Rows are receiver formations and columns are sender formations.  Numeric
% sensor and formation identifiers are retained only as lookup metadata;
% they are not included in node or edge features.

required = { ...
    'hierarchicalFormationIds', ...
    'hierarchicalWithholdingFeatureContractVersion', ...
    'hierarchicalWithholdingFeatureNames', ...
    'hierarchicalWithholdingFeaturesByFormation', ...
    'hierarchicalWithholdingPayloadFeatureNames', ...
    'hierarchicalWithholdingPayloadFeaturesByFormation', ...
    'hierarchicalWithholdingTruthUsed', ...
    'hierarchicalWithholdingFutureInformationUsed'};
sensorGroupIds = reshape(sensorGroupIds, 1, []);
sensorCount = numel(sensorGroupIds);
if sensorCount < 1 || ...
        ~isequal(size(referenceAdjacency), ...
            [sensorCount, sensorCount]) || ...
        ~isequal(size(fusionWeightMatrix), ...
            [sensorCount, sensorCount]) || ...
        ~isstruct(policyDetails) || ~isscalar(policyDetails) || ...
        any(~isfield(policyDetails, required))
    error('DirectGraphLearningSnapshotV218:InvalidInput', ...
        'A complete observable V215 formation graph is required.');
end
formationIds = unique(sensorGroupIds, 'stable');
if ~isequal(reshape( ...
        policyDetails.hierarchicalFormationIds, 1, []), ...
        formationIds) || ...
        policyDetails.hierarchicalWithholdingTruthUsed || ...
        policyDetails.hierarchicalWithholdingFutureInformationUsed
    error('DirectGraphLearningSnapshotV218:FormationDrift', ...
        'The policy formation graph changed or used forbidden inputs.');
end
nodeFeatureNames = reshape( ...
    policyDetails.hierarchicalWithholdingFeatureNames, 1, []);
nodeFeatures = ...
    policyDetails.hierarchicalWithholdingFeaturesByFormation;
payloadFeatureNames = reshape( ...
    policyDetails.hierarchicalWithholdingPayloadFeatureNames, 1, []);
payloadFeatures = ...
    policyDetails.hierarchicalWithholdingPayloadFeaturesByFormation;
formationCount = numel(formationIds);
if ~isequal(size(nodeFeatures), ...
        [formationCount, numel(nodeFeatureNames)]) || ...
        ~isequal(size(payloadFeatures), ...
        [formationCount, numel(payloadFeatureNames)]) || ...
        any(~isfinite(nodeFeatures(:))) || ...
        any(~isfinite(payloadFeatures(:))) || ...
        any(~isfinite(fusionWeightMatrix(:))) || ...
        any(fusionWeightMatrix(:) < -1e-12)
    error('DirectGraphLearningSnapshotV218:FeatureDrift', ...
        'Formation node or sensor-edge features are malformed.');
end

referenceAdjacency = logical(referenceAdjacency);
edgeFeatureNames = { ...
    'selected_message_fraction_of_possible', ...
    'selected_fusion_mass_per_receiver_sensor', ...
    'mean_selected_edge_fusion_weight'};
edgeFeatures = zeros( ...
    formationCount, formationCount, numel(edgeFeatureNames));
formationAdjacency = false(formationCount);
for receiverRow = 1:formationCount
    receivers = find(sensorGroupIds == formationIds(receiverRow));
    for senderRow = 1:formationCount
        if receiverRow == senderRow
            continue;
        end
        senders = find(sensorGroupIds == formationIds(senderRow));
        selected = referenceAdjacency(receivers, senders);
        weights = fusionWeightMatrix(receivers, senders);
        selectedCount = nnz(selected);
        selectedMass = sum(weights(selected));
        formationAdjacency(receiverRow, senderRow) = ...
            selectedCount > 0;
        edgeFeatures(receiverRow, senderRow, 1) = ...
            selectedCount / numel(selected);
        edgeFeatures(receiverRow, senderRow, 2) = ...
            selectedMass / numel(receivers);
        if selectedCount > 0
            edgeFeatures(receiverRow, senderRow, 3) = ...
                selectedMass / selectedCount;
        end
    end
end
if any(~isfinite(edgeFeatures(:))) || ...
        any(edgeFeatures(:) < -1e-12)
    error('DirectGraphLearningSnapshotV218:EdgeFeatureDrift', ...
        'Formation edge features must be finite and nonnegative.');
end

snapshot = struct();
snapshot.contractVersion = ...
    'direct-graph-formation-learning-snapshot-v218-v1';
snapshot.featureContractVersion = policyDetails. ...
    hierarchicalWithholdingFeatureContractVersion;
snapshot.formationIds = formationIds;
snapshot.formationCount = formationCount;
snapshot.nodeFeatureNames = nodeFeatureNames;
snapshot.nodeFeatures = nodeFeatures;
snapshot.payloadFeatureNames = payloadFeatureNames;
snapshot.payloadFeatures = payloadFeatures;
snapshot.edgeFeatureNames = edgeFeatureNames;
snapshot.edgeFeatures = edgeFeatures;
snapshot.receiverRowSenderColumnAdjacency = formationAdjacency;
snapshot.directionConvention = ...
    'receiver-formation-row-sender-formation-column';
snapshot.sharedParametersAcrossFormationsRequired = true;
snapshot.numericSensorIdentifiersUsedAsFeatures = false;
snapshot.numericFormationIdentifiersUsedAsFeatures = false;
snapshot.truthUsed = false;
snapshot.futureInformationUsed = false;
end
