function config = buildFormationBraidRoutingComparisonV241Config( ...
        armId, scenario, registration)
% BUILDFORMATIONBRAIDROUTINGCOMPARISONV241CONFIG Matched routing arms.

if nargin < 3
    registration = struct();
end
protocol = getFormationBraidRoutingComparisonV241Protocol();
if ~ischar(armId) || ~any(strcmp(armId, protocol.armIds)) || ...
        ~isstruct(scenario) || ~isscalar(scenario) || ...
        ~isfield(scenario, 'presetName') || ...
        ~ismember(scenario.presetName, protocol.allowedPresets)
    error('FormationBraidRoutingV241:InvalidConfigInput', ...
        'V241 requires one registered arm and formation-braid scene.');
end
config = buildCausalMinimalEditFormationTreeV240Config(scenario);
if strcmp(armId, protocol.staticDropoutArmId)
    validateRegistration(registration, scenario.numberOfSensors);
    config.topologyPolicyName = protocol.staticDropoutPolicyName;
    config.topologyPolicyFcn = @(context) ...
        selectFrozenFormationBraidDropoutV241Policy( ...
            context, registration);
elseif strcmp(armId, protocol.alwaysReplanArmId)
    config.topologyPolicyName = protocol.alwaysReplanPolicyName;
    config.topologyPolicyFcn = ...
        @selectAlwaysReplanFormationTreeV241Policy;
else
    config.topologyPolicyName = protocol.causalPolicyName;
    config.topologyPolicyFcn = ...
        @selectCausalMinimalEditFormationTreeV240Policy;
end
end

function validateRegistration(registration, nodeCount)
required = {'contractVersion', 'adjacency', 'fusionWeightMatrix', ...
    'selectionDetails', 'messageCount'};
if ~isstruct(registration) || ~isscalar(registration) || ...
        ~all(isfield(registration, required)) || ...
        ~strcmp(registration.contractVersion, ...
            'formation-braid-v241-initial-route-registration-v1') || ...
        ~isequal(size(registration.adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(registration.fusionWeightMatrix), ...
            [nodeCount, nodeCount]) || ...
        registration.messageCount ~= 2 * nodeCount
    error('FormationBraidRoutingV241:InvalidRegistration', ...
        'The V241 initial route registration is malformed.');
end
end
