function bank = buildDecoupledSemanticShortcutV220ActionBank( ...
        context, groupIds, options)
% BUILDDECOUPLEDSEMANTICSHORTCUTV220ACTIONBANK One donor, one beneficiary.
%
% The V214 carrier retains the registered route and performs the one-page
% full-posterior receiver suspension.  This wrapper changes only the repair
% scope: the complete-label semantic shortcut may target an independently
% selected beneficiary formation.

if nargin < 3 || isempty(options)
    options = struct();
end
protocol = getDecoupledSemanticShortcutV220Protocol();
donorFormationId = getField(options, 'donorFormationId', 0);
beneficiaryFormationId = getField( ...
    options, 'beneficiaryFormationId', 0);
referenceAttemptedBytes = getField( ...
    options, 'referenceAttemptedBytes', NaN);
sourceWeight = getField( ...
    options, 'repairSourceWeight', protocol.repairSourceWeight);
idealDeliveryTeacherMode = logical(getField( ...
    options, 'repairIdealDeliveryTeacherMode', false));
forcedSourceId = getField(options, 'repairForcedSourceId', 0);
forcedLabel = reshape(getField( ...
    options, 'repairForcedLabel', zeros(2, 1)), [], 1);
formationIds = unique(reshape(groupIds, 1, []), 'stable');
sensorCount = numel(groupIds);
forcedTeacher = forcedSourceId > 0;
if ~validFormationId(donorFormationId, formationIds) || ...
        ~validFormationId(beneficiaryFormationId, formationIds) || ...
        ~isscalar(referenceAttemptedBytes) || ...
        ~isnumeric(referenceAttemptedBytes) || ...
        ~isfinite(referenceAttemptedBytes) || ...
        referenceAttemptedBytes <= 0 || ...
        ~isscalar(sourceWeight) || ~isnumeric(sourceWeight) || ...
        ~isfinite(sourceWeight) || sourceWeight <= 0 || ...
        sourceWeight >= 1 || ...
        ~isscalar(forcedSourceId) || ~isnumeric(forcedSourceId) || ...
        ~isfinite(forcedSourceId) || forcedSourceId < 0 || ...
        forcedSourceId ~= round(forcedSourceId) || ...
        forcedSourceId > sensorCount || ...
        numel(forcedLabel) ~= 2 || any(~isfinite(forcedLabel)) || ...
        any(forcedLabel ~= round(forcedLabel)) || ...
        ((forcedSourceId == 0) ~= all(forcedLabel == 0)) || ...
        (idealDeliveryTeacherMode ~= forcedTeacher) || ...
        (forcedTeacher && any(forcedLabel < 1))
    error('DecoupledSemanticShortcutV220:InvalidActionBankInput', ...
        'The donor, beneficiary, credit, or semantic key is malformed.');
end

carrierOptions = struct( ...
    'horizonSteps', protocol.horizonSteps, ...
    'actionMode', protocol.actionMode, ...
    'referenceAttemptedBytes', referenceAttemptedBytes, ...
    'repairSourceWeight', sourceWeight, ...
    'repairIdealDeliveryTeacherMode', idealDeliveryTeacherMode, ...
    'repairForcedSourceId', forcedSourceId, ...
    'repairForcedLabel', forcedLabel, ...
    'formationIds', donorFormationId);
bank = buildDirectGraphPayloadRepairV214ActionBank( ...
    context, groupIds, carrierOptions);
actionIdx = find((1:bank.actionCount) ~= bank.referenceActionIndex);
if numel(actionIdx) ~= 1
    error('DecoupledSemanticShortcutV220:CarrierDrift', ...
        'The V220 carrier must expose exactly one donor action.');
end
repairPlan = bank.actionBudgetRecycledFormationRepairPlans{actionIdx};
repairPlan.targetFormationId = beneficiaryFormationId;
if idealDeliveryTeacherMode
    repairPlan.forcedFormationId = beneficiaryFormationId;
else
    repairPlan.forcedFormationId = 0;
end
bank.actionBudgetRecycledFormationRepairPlans{actionIdx} = repairPlan;
if forcedTeacher
    bank.actionNames{actionIdx} = sprintf( ...
        ['v220-donor-f%d-to-beneficiary-f%d-', ...
         'label-kla-s%d-l%d-%d'], ...
        donorFormationId, beneficiaryFormationId, ...
        forcedSourceId, forcedLabel(1), forcedLabel(2));
else
    bank.actionNames{actionIdx} = sprintf( ...
        'v220-donor-f%d-to-beneficiary-f%d-causal-label-kla', ...
        donorFormationId, beneficiaryFormationId);
end
bank.contractVersion = ...
    'decoupled-semantic-shortcut-action-bank-v220-v1';
bank.bankVariant = 'decoupled-semantic-shortcut-v220';
bank.baseCarrierContractVersion = ...
    'direct-graph-payload-repair-action-bank-v214-v2';
bank.protocolId = protocol.id;
bank.donorFormationId = donorFormationId;
bank.beneficiaryFormationId = beneficiaryFormationId;
bank.donorBeneficiaryDecoupled = ...
    donorFormationId ~= beneficiaryFormationId;
bank.semanticShortcutCompleteMixture = true;
bank.semanticShortcutForcedTeacher = forcedTeacher;
bank.semanticShortcutSourceId = forcedSourceId;
bank.semanticShortcutLabel = reshape(forcedLabel, 2, 1);
bank.truthUsed = false;
bank.futureMeasurementsUsed = false;
bank.futureOutcomesUsed = false;
end

function valid = validFormationId(value, formationIds)
valid = isscalar(value) && isnumeric(value) && isfinite(value) && ...
    value == round(value) && ismember(value, formationIds);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
