function projection = buildReceiverDomainTransportProjectionV71( ...
        context, control, transport, local, groupIds, options)
% BUILDRECEIVERDOMAINTRANSPORTPROJECTIONV71 Executable route projection.
%
% V68 evaluates one sender replacement at one receiver while holding every
% other receiver row fixed. KLA receiver updates are row-separable, so safe
% replacements at distinct receivers compose exactly for the same round.
% V71 bundles those replacements by affected receiver formation, enumerates
% the small formation-level subset bank, and applies the global physical,
% fixed-message, and rolling-connectivity constraints only once.

if nargin < 6 || isempty(options)
    options = getReceiverDomainTransportProjectionV71Protocol();
end
requiredContext = { ...
    'physicalAdjacency', 'previousAdjacencyHistory'};
requiredControl = { ...
    'referenceAdjacency', 'referenceFusionWeights'};
requiredTransport = { ...
    'networkReferenceExistenceMass', 'slotRecords'};
requiredLocal = { ...
    'groups', 'groupIds', ...
    'referenceExistenceMassByFormation', ...
    'alternativeTransportNetMassByFormation', ...
    'localAlternativeTransportNetFractionByFormation', ...
    'alternativePositiveSlotCountByFormation', ...
    'alternativeTransportActionMask', ...
    'preferredActionByFormation'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, requiredContext)) || ...
        ~isstruct(control) || ~isscalar(control) || ...
        ~all(isfield(control, requiredControl)) || ...
        ~isstruct(transport) || ~isscalar(transport) || ...
        ~all(isfield(transport, requiredTransport)) || ...
        ~isstruct(local) || ~isscalar(local) || ...
        ~all(isfield(local, requiredLocal))
    error('ReceiverDomainProjectionV71:InvalidInput', ...
        'V71 requires aligned context, reference, V68, and V70 records.');
end

groupIds = reshape(groupIds, 1, []);
groups = reshape(local.groups, 1, []);
nodeCount = numel(groupIds);
formationCount = numel(groups);
referenceAdjacency = logical(control.referenceAdjacency);
referenceWeights = control.referenceFusionWeights;
physicalAdjacency = logical(context.physicalAdjacency);
if nodeCount < 2 || formationCount < 2 || ...
        ~isequal(groupIds, reshape(local.groupIds, 1, [])) || ...
        ~isequal(groups, unique(groupIds, 'stable')) || ...
        ~isequal(size(referenceAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(referenceWeights), [nodeCount, nodeCount]) || ...
        ~isequal(size(physicalAdjacency), [nodeCount, nodeCount]) || ...
        size(context.previousAdjacencyHistory, 1) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 2) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 3) < 2
    error('ReceiverDomainProjectionV71:DimensionMismatch', ...
        'V71 graph dimensions or formation identities are invalid.');
end

referenceMassByFormation = reshape( ...
    local.referenceExistenceMassByFormation, 1, []);
localNetMass = reshape( ...
    local.alternativeTransportNetMassByFormation, 1, []);
localNetFraction = reshape( ...
    local.localAlternativeTransportNetFractionByFormation, 1, []);
localPositiveSlotCount = reshape( ...
    local.alternativePositiveSlotCountByFormation, 1, []);
transportMask = logical(reshape( ...
    local.alternativeTransportActionMask, 1, []));
preferredAction = reshape(local.preferredActionByFormation, 1, []);
networkMass = transport.networkReferenceExistenceMass;
if any([numel(referenceMassByFormation), numel(localNetMass), ...
        numel(localNetFraction), numel(localPositiveSlotCount), ...
        numel(transportMask), numel(preferredAction)] ~= formationCount) || ...
        any(~isfinite(referenceMassByFormation)) || ...
        any(referenceMassByFormation <= eps) || ...
        ~isscalar(networkMass) || ~isfinite(networkMass) || ...
        networkMass <= eps || ...
        abs(sum(referenceMassByFormation) - networkMass) > ...
            1e-10 * max(networkMass, 1)
    error('ReceiverDomainProjectionV71:InvalidOpportunityMass', ...
        'V71 receiver-domain masses are invalid or misaligned.');
end

validateReferenceRoute(referenceAdjacency, referenceWeights, ...
    physicalAdjacency);
[referenceSensorPass, referenceFormationPass] = rollingB3Pass( ...
    context.previousAdjacencyHistory, repmat( ...
        referenceAdjacency, 1, 1, 1 + options.referenceRecoverySteps), ...
    groupIds);
if ~all(referenceSensorPass) || ~all(referenceFormationPass)
    error('ReceiverDomainProjectionV71:InvalidReference', ...
        'The registered reference fails the frozen rolling-B3 gate.');
end

preferredTransport = false(1, formationCount);
for formationIdx = 1:formationCount
    preferredTransport(formationIdx) = ...
        strcmp(preferredAction{formationIdx}, 'transport');
end
nominatedMask = transportMask & preferredTransport;
nominatedFormationIndices = find(nominatedMask);
if numel(nominatedFormationIndices) > ...
        options.maximumNominatedFormationCount
    error('ReceiverDomainProjectionV71:CandidateBudgetExceeded', ...
        'The nominated formation bank exceeds the frozen exact budget.');
end

bundles = buildFormationBundles( ...
    transport.slotRecords, nominatedFormationIndices, groups, groupIds, ...
    referenceAdjacency, referenceWeights, physicalAdjacency, networkMass, ...
    localNetMass, localNetFraction, localPositiveSlotCount, options);
candidateCount = 2^numel(bundles) - 1;
if candidateCount > options.maximumCandidateBundleEvaluations
    error('ReceiverDomainProjectionV71:CandidateBudgetExceeded', ...
        'The exact formation-subset bank exceeds the frozen route budget.');
end

candidates = repmat(emptyCandidate(), 1, candidateCount);
bestCandidateIndex = NaN;
bestUtilityMass = -inf;
bestFormationIds = zeros(1, 0);
for candidateIdx = 1:candidateCount
    bundleIndices = find(bitget(candidateIdx, 1:numel(bundles)));
    [adjacency, weights, appliedSlots] = applyBundles( ...
        referenceAdjacency, referenceWeights, bundles(bundleIndices), ...
        transport.slotRecords);
    formationIds = [bundles(bundleIndices).formationId];
    utilityMass = sum([bundles(bundleIndices).netMass]);
    route = evaluateRouteStructure( ...
        adjacency, weights, referenceAdjacency, referenceWeights, ...
        physicalAdjacency);
    sequence = cat(3, adjacency, repmat(referenceAdjacency, ...
        1, 1, options.referenceRecoverySteps));
    [sensorPass, formationPass] = rollingB3Pass( ...
        context.previousAdjacencyHistory, sequence, groupIds);
    feasible = route.pass && all(sensorPass) && all(formationPass);
    candidates(candidateIdx) = makeCandidate( ...
        candidateIdx, formationIds, appliedSlots, utilityMass, ...
        networkMass, route, sensorPass, formationPass, feasible);
    if feasible && isBetterCandidate( ...
            utilityMass, formationIds, bestUtilityMass, bestFormationIds)
        bestCandidateIndex = candidateIdx;
        bestUtilityMass = utilityMass;
        bestFormationIds = formationIds;
    end
end

if isnan(bestCandidateIndex)
    selectedAdjacency = referenceAdjacency;
    selectedWeights = referenceWeights;
    selectedFormationIds = zeros(1, 0);
    selectedSlotIndices = zeros(1, 0);
    selectedUtilityMass = 0;
    selectedSensorPass = referenceSensorPass;
    selectedFormationPass = referenceFormationPass;
    selectedRoute = evaluateRouteStructure( ...
        selectedAdjacency, selectedWeights, referenceAdjacency, ...
        referenceWeights, physicalAdjacency);
    selectedActionName = 'reference';
else
    selected = candidates(bestCandidateIndex);
    selectedFormationIds = selected.formationIds;
    selectedSlotIndices = selected.slotIndices;
    [selectedAdjacency, selectedWeights] = applyBundles( ...
        referenceAdjacency, referenceWeights, ...
        bundles(ismember([bundles.formationId], selectedFormationIds)), ...
        transport.slotRecords);
    selectedUtilityMass = selected.utilityMass;
    selectedSensorPass = selected.rollingB3SensorPass;
    selectedFormationPass = selected.rollingB3FormationPass;
    selectedRoute = evaluateRouteStructure( ...
        selectedAdjacency, selectedWeights, referenceAdjacency, ...
        referenceWeights, physicalAdjacency);
    selectedActionName = buildActionName(selectedFormationIds);
end
if ~selectedRoute.pass || ~all(selectedSensorPass) || ...
        ~all(selectedFormationPass)
    error('ReceiverDomainProjectionV71:InvalidSelection', ...
        'The selected V71 route violates a frozen invariant.');
end

projection = struct();
projection.contractVersion = ...
    'receiver-domain-transport-projection-v71-v1';
projection.protocolId = options.id;
projection.nodeCount = nodeCount;
projection.formationCount = formationCount;
projection.groupIds = groupIds;
projection.groups = groups;
projection.referenceAdjacency = referenceAdjacency;
projection.referenceFusionWeights = referenceWeights;
projection.referenceRollingB3SensorPass = referenceSensorPass;
projection.referenceRollingB3FormationPass = referenceFormationPass;
projection.nominatedFormationIds = groups(nominatedMask);
projection.formationBundles = bundles;
projection.candidateCount = candidateCount;
projection.candidates = candidates;
projection.feasibleCandidateCount = nnz([candidates.feasible]);
projection.selectedCandidateIndex = bestCandidateIndex;
projection.selectedFormationIds = selectedFormationIds;
projection.selectedSlotIndices = selectedSlotIndices;
projection.selectedAdjacency = selectedAdjacency;
projection.selectedFusionWeights = selectedWeights;
projection.selectedActionName = selectedActionName;
projection.selectedUtilityMass = selectedUtilityMass;
projection.selectedNetworkAverageNetFraction = ...
    selectedUtilityMass / networkMass;
projection.selectedRouteStructure = selectedRoute;
projection.selectedRollingB3SensorPass = selectedSensorPass;
projection.selectedRollingB3FormationPass = selectedFormationPass;
projection.referenceFallbackUsed = isnan(bestCandidateIndex);
projection.referenceMessageCount = nnz(referenceAdjacency);
projection.selectedMessageCount = nnz(selectedAdjacency);
projection.messageCountParityWithReference = ...
    nnz(selectedAdjacency) == nnz(referenceAdjacency);
projection.perReceiverMessageCountParityWithReference = isequal( ...
    sum(selectedAdjacency, 2), sum(referenceAdjacency, 2));
projection.perReceiverWeightMultisetParityWithReference = ...
    rowWeightMultisetParity(selectedWeights, referenceWeights);
projection.formationGraphParityWithReference = isequal( ...
    collapseToFormations(selectedAdjacency, groupIds), ...
    collapseToFormations(referenceAdjacency, groupIds));
projection.routeConnectivityProjected = true;
projection.messageBudgetProjected = true;
projection.routeConstructed = ~projection.referenceFallbackUsed;
projection.routeExecuted = false;
projection.selectionUsesCurrentPosterior = true;
projection.selectionUsesCurrentLinkReliability = true;
projection.selectionUsesSelectedTopologyHistory = true;
projection.truthUsed = false;
projection.futureMeasurementsUsed = false;
projection.futureLinkOutcomesUsed = false;
projection.futureOutcomesUsed = false;
projection.trackingOutcomeRead = false;
projection.openedDevelopmentEvidenceOnly = true;
projection.validationClaimAllowed = false;
end

function validateReferenceRoute(adjacency, weights, physical)
support = adjacency | logical(eye(size(adjacency, 1)));
if any(adjacency(:) & ~physical(:)) || ...
        any(~isfinite(weights(:))) || any(weights(:) < -1e-12) || ...
        any(weights(:) > 1e-12 & ~support(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12)
    error('ReceiverDomainProjectionV71:InvalidReference', ...
        'The registered reference route is not physical or normalized.');
end
end

function bundles = buildFormationBundles( ...
        slots, nominatedFormationIndices, groups, groupIds, ...
        referenceAdjacency, referenceWeights, physicalAdjacency, ...
        networkMass, localNetMass, localNetFraction, ...
        localPositiveSlotCount, options)
bundles = repmat(emptyBundle(), 1, numel(nominatedFormationIndices));
usedReceivers = false(1, numel(groupIds));
for bundleIdx = 1:numel(nominatedFormationIndices)
    formationIdx = nominatedFormationIndices(bundleIdx);
    formationId = groups(formationIdx);
    slotIndices = zeros(1, 0);
    recomputedMass = 0;
    for slotIdx = 1:numel(slots)
        slot = slots(slotIdx);
        if ~qualifyingSlot(slot)
            continue;
        end
        receiverIdx = slot.receiverIdx;
        if receiverIdx < 1 || receiverIdx > numel(groupIds) || ...
                receiverIdx ~= round(receiverIdx) || ...
                groupIds(receiverIdx) ~= formationId
            continue;
        end
        validateSlot(slot, groupIds, referenceAdjacency, ...
            referenceWeights, physicalAdjacency, options);
        if usedReceivers(receiverIdx)
            error('ReceiverDomainProjectionV71:ReceiverSlotConflict', ...
                'More than one selected residual slot affects a receiver.');
        end
        usedReceivers(receiverIdx) = true;
        slotIndices(end + 1) = slotIdx; %#ok<AGROW>
        recomputedMass = recomputedMass + ...
            networkMass * slot.bestNetHeadroomFraction;
    end
    if isempty(slotIndices) || ...
            numel(slotIndices) ~= localPositiveSlotCount(formationIdx) || ...
            abs(recomputedMass - localNetMass(formationIdx)) > ...
                1e-10 * max(networkMass, 1)
        error('ReceiverDomainProjectionV71:BundleMismatch', ...
            'A V70 nominated formation does not match its V68 slot bundle.');
    end
    bundles(bundleIdx) = struct( ...
        'formationIndex', formationIdx, ...
        'formationId', formationId, ...
        'slotIndices', slotIndices, ...
        'receiverIndices', [slots(slotIndices).receiverIdx], ...
        'netMass', recomputedMass, ...
        'localNetFraction', localNetFraction(formationIdx));
end
end

function value = qualifyingSlot(slot)
value = isfield(slot, 'bestSafe') && slot.bestSafe && ...
    isfield(slot, 'bestNetHeadroomFraction') && ...
    isfinite(slot.bestNetHeadroomFraction) && ...
    slot.bestNetHeadroomFraction > 0;
end

function validateSlot(slot, groupIds, referenceAdjacency, ...
        referenceWeights, physicalAdjacency, options)
required = { ...
    'receiverIdx', 'incumbentSenderIdx', 'sourceWeight', ...
    'bestCandidateSenderIdx', 'bestTransportGainFraction', ...
    'bestSupportedHarmFraction', 'bestNetHeadroomFraction', ...
    'bestDownwardCrossingCount'};
if ~all(isfield(slot, required))
    error('ReceiverDomainProjectionV71:InvalidSlot', ...
        'A nominated V68 slot is incomplete.');
end
receiverIdx = slot.receiverIdx;
incumbent = slot.incumbentSenderIdx;
candidate = slot.bestCandidateSenderIdx;
nodeCount = numel(groupIds);
indices = [receiverIdx, incumbent, candidate];
gain = slot.bestTransportGainFraction;
harm = slot.bestSupportedHarmFraction;
net = slot.bestNetHeadroomFraction;
if any(~isfinite(indices)) || any(indices < 1) || ...
        any(indices > nodeCount) || any(indices ~= round(indices)) || ...
        incumbent == candidate || ...
        groupIds(incumbent) == groupIds(receiverIdx) || ...
        groupIds(candidate) == groupIds(receiverIdx) || ...
        ~referenceAdjacency(receiverIdx, incumbent) || ...
        referenceAdjacency(receiverIdx, candidate) || ...
        ~physicalAdjacency(receiverIdx, candidate) || ...
        abs(referenceWeights(receiverIdx, incumbent) - ...
            slot.sourceWeight) > 1e-12 || ...
        abs(slot.sourceWeight - options.sourceWeight) > 1e-12 || ...
        referenceWeights(receiverIdx, candidate) > 1e-12 || ...
        any(~isfinite([gain, harm, net])) || gain < -1e-12 || ...
        harm < -1e-12 || net <= 0 || harm > gain + 1e-12 || ...
        abs(net - (gain - harm)) > 1e-12 || ...
        (options.requireZeroSupportedDownwardCrossings && ...
            slot.bestDownwardCrossingCount ~= 0)
    error('ReceiverDomainProjectionV71:InvalidSlot', ...
        'A nominated V68 slot violates the compositional safety contract.');
end
end

function [adjacency, weights, appliedSlots] = applyBundles( ...
        referenceAdjacency, referenceWeights, bundles, slots)
adjacency = referenceAdjacency;
weights = referenceWeights;
appliedSlots = zeros(1, 0);
for bundle = reshape(bundles, 1, [])
    for slotIdx = reshape(bundle.slotIndices, 1, [])
        slot = slots(slotIdx);
        receiver = slot.receiverIdx;
        incumbent = slot.incumbentSenderIdx;
        candidate = slot.bestCandidateSenderIdx;
        adjacency(receiver, incumbent) = false;
        adjacency(receiver, candidate) = true;
        weights(receiver, incumbent) = 0;
        weights(receiver, candidate) = slot.sourceWeight;
        appliedSlots(end + 1) = slotIdx; %#ok<AGROW>
    end
end
end

function route = evaluateRouteStructure( ...
        adjacency, weights, referenceAdjacency, referenceWeights, physical)
support = adjacency | logical(eye(size(adjacency, 1)));
route = struct();
route.currentPhysicalityPass = ~any(adjacency(:) & ~physical(:));
route.messageCountParityPass = ...
    nnz(adjacency) == nnz(referenceAdjacency);
route.perReceiverMessageCountParityPass = isequal( ...
    sum(adjacency, 2), sum(referenceAdjacency, 2));
route.perReceiverWeightMultisetParityPass = ...
    rowWeightMultisetParity(weights, referenceWeights);
route.weightSupportPass = ...
    ~any(weights(:) > 1e-12 & ~support(:));
route.finiteNonnegativeWeightPass = ...
    all(isfinite(weights(:))) && all(weights(:) >= -1e-12);
route.rowNormalizationPass = ...
    all(abs(sum(weights, 2) - 1) <= 1e-12);
route.pass = route.currentPhysicalityPass && ...
    route.messageCountParityPass && ...
    route.perReceiverMessageCountParityPass && ...
    route.perReceiverWeightMultisetParityPass && ...
    route.weightSupportPass && ...
    route.finiteNonnegativeWeightPass && ...
    route.rowNormalizationPass;
end

function pass = rowWeightMultisetParity(first, second)
pass = true;
for receiverIdx = 1:size(first, 1)
    firstPositive = sort(first(receiverIdx, first(receiverIdx, :) > 1e-12));
    secondPositive = sort(second(receiverIdx, second(receiverIdx, :) > 1e-12));
    if numel(firstPositive) ~= numel(secondPositive) || ...
            any(abs(firstPositive - secondPositive) > 1e-12)
        pass = false;
        return;
    end
end
end

function candidate = makeCandidate( ...
        index, formationIds, slotIndices, utilityMass, networkMass, ...
        route, sensorPass, formationPass, feasible)
candidate = emptyCandidate();
candidate.index = index;
candidate.formationIds = formationIds;
candidate.slotIndices = slotIndices;
candidate.formationCount = numel(formationIds);
candidate.slotCount = numel(slotIndices);
candidate.utilityMass = utilityMass;
candidate.networkAverageNetFraction = utilityMass / networkMass;
candidate.routeStructure = route;
candidate.rollingB3SensorPass = sensorPass;
candidate.rollingB3FormationPass = formationPass;
candidate.feasible = feasible;
end

function better = isBetterCandidate( ...
        utilityMass, formationIds, bestMass, bestFormationIds)
if ~isfinite(bestMass)
    better = true;
    return;
end
tolerance = 1e-12 * max([abs(utilityMass), abs(bestMass), 1]);
if utilityMass > bestMass + tolerance
    better = true;
elseif abs(utilityMass - bestMass) <= tolerance
    if isempty(bestFormationIds) || ...
            numel(formationIds) < numel(bestFormationIds)
        better = true;
    elseif numel(formationIds) == numel(bestFormationIds)
        better = lexicographicallyLess(formationIds, bestFormationIds);
    else
        better = false;
    end
else
    better = false;
end
end

function less = lexicographicallyLess(first, second)
less = false;
for idx = 1:min(numel(first), numel(second))
    if first(idx) < second(idx)
        less = true;
        return;
    elseif first(idx) > second(idx)
        return;
    end
end
less = numel(first) < numel(second);
end

function name = buildActionName(formationIds)
text = sprintf('f%d-', formationIds);
name = ['receiver-domain-transport-', text(1:end-1)];
end

function [sensorPass, formationPass] = ...
        rollingB3Pass(previousHistory, sequence, groupIds)
history = logical(previousHistory(:, :, end-1:end));
sensorPass = false(1, size(sequence, 3));
formationPass = false(1, size(sequence, 3));
for stepIdx = 1:size(sequence, 3)
    pages = cat(3, history, sequence(:, :, stepIdx));
    window = any(pages(:, :, max(1, end-2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = sequence(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function value = emptyBundle()
value = struct( ...
    'formationIndex', NaN, ...
    'formationId', NaN, ...
    'slotIndices', zeros(1, 0), ...
    'receiverIndices', zeros(1, 0), ...
    'netMass', NaN, ...
    'localNetFraction', NaN);
end

function value = emptyCandidate()
value = struct( ...
    'index', NaN, ...
    'formationIds', zeros(1, 0), ...
    'slotIndices', zeros(1, 0), ...
    'formationCount', 0, ...
    'slotCount', 0, ...
    'utilityMass', NaN, ...
    'networkAverageNetFraction', NaN, ...
    'routeStructure', struct(), ...
    'rollingB3SensorPass', false(1, 0), ...
    'rollingB3FormationPass', false(1, 0), ...
    'feasible', false);
end
