function [adjacency, details] = ...
    buildFormationB4V46FixedRuntimeArm(context, armId)
% BUILDFORMATIONB4V46FIXEDRUNTIMEARM Project then execute one V45 arm.
%
% The causal projection receives exactly seven current-page inputs.  The
% projected formation-pair registry is installed only in a cloned context,
% after which the existing V45 wrapper performs the full observable-v3 and
% exact directed-2N validation without any V46 relaxation.

timerId = tic;
protocol = getFormationCausalMinimalEditV46Protocol();
if ~ischar(armId) || ~isrow(armId) || ...
        ~ismember(armId, protocol.primaryArms)
    error('FormationB4V46:InvalidArm', ...
        'Only the two frozen V46 primary arm identifiers are allowed.');
end
validateProjectionInputsPresent(context);

groupIds = context.model.dynamicTopologyScenario.config.sensorGroupIds;
registeredBaseAdjacency = logical(context.baseAdjacency);
staticAdjacencyPresent = isfield(context.model, ...
    'dynamicTopologyScenario') && ...
    isstruct(context.model.dynamicTopologyScenario) && ...
    isscalar(context.model.dynamicTopologyScenario) && ...
    isfield(context.model.dynamicTopologyScenario, ...
        'staticAdjacency');
if staticAdjacencyPresent
    validateRegisteredStaticConsistency( ...
        context.model.dynamicTopologyScenario.staticAdjacency, ...
        registeredBaseAdjacency);
end
[projectedBaseAdjacency, certificate] = ...
    projectCausalMinimalEditFormationBackbone( ...
        groupIds, context.sensorPhysicalUids, ...
        context.formationPhysicalUidsBySensor, context.positions, ...
        registeredBaseAdjacency, context.physicalAdjacency, ...
        context.commConfig.pDropByEdge);
validateProjectionCertificate(certificate, ...
    context.sensorPhysicalUids, projectedBaseAdjacency);

runtimeContext = context;
runtimeContext.baseAdjacency = logical(projectedBaseAdjacency);
if staticAdjacencyPresent
    runtimeContext.model.dynamicTopologyScenario.staticAdjacency = ...
        logical(projectedBaseAdjacency);
end

switch armId
    case 'v46-repaired-reference-a70-e05'
        armOrdinal = 1;
        parentArmId = 'v43-reference-a70-e05';
        [adjacency, parentDetails] = ...
            selectFormationB4V45ReferenceRuntimePolicy(runtimeContext);
        mode = 'formation-b4-v46-repaired-reference-runtime';
    case 'v46-repaired-sync-all-b4-e20-mc'
        armOrdinal = 2;
        parentArmId = 'v44-sync-all-b4-e20-mc';
        [adjacency, parentDetails] = ...
            selectFormationB4V45SynchronizedRuntimePolicy(runtimeContext);
        mode = 'formation-b4-v46-repaired-synchronized-b4-runtime';
end

if parentDetails.armOrdinal ~= armOrdinal || ...
        ~strcmp(parentDetails.armId, parentArmId) || ...
        parentDetails.topologyDirectedMessageBudget ~= ...
            2 * numel(context.localPosteriorBySensor) || ...
        ~strcmp(parentDetails.observableInputContractVersion, ...
            'topology-policy-observable-input-v3-physical-uid') || ...
        ~isfield(parentDetails, ...
            'residualMassMatchedToReference') || ...
        ~isTrue(parentDetails.residualMassMatchedToReference)
    error('FormationB4V46:ParentRuntimeDrift', ...
        'The reused V45 runtime arm or observable contract drifted.');
end
validateFullV43RouteComposition(context, adjacency, parentDetails);
[parentRouteObjectiveVector, diagnosticsObjective, ...
    objectiveDefinition, objectiveSource] = ...
    resolveDiagnosticsObjective(parentDetails, armOrdinal);

repairTriggered = certificate.registeredRemovalCount > 0 || ...
    certificate.nonregisteredAdditionCount > 0;
registeredBaseHash = computeCanonicalValueSha256( ...
    struct('contractVersion', ...
        'formation-b4-v46-base-execution-view-v1', ...
        'sensorPhysicalUidsByArray', ...
            reshape(context.sensorPhysicalUids, 1, []), ...
        'baseAdjacency', registeredBaseAdjacency));
projectedBaseHash = computeCanonicalValueSha256( ...
    struct('contractVersion', ...
        'formation-b4-v46-base-execution-view-v1', ...
        'sensorPhysicalUidsByArray', ...
            reshape(context.sensorPhysicalUids, 1, []), ...
        'baseAdjacency', logical(projectedBaseAdjacency)));
identityContract = ...
    'formation-b4-v46-formation-pair-identity-v1';
registeredIdentityPayload = struct( ...
    'contractVersion', identityContract, ...
    'pairPhysicalUids', ...
        certificate.registeredPairPhysicalUids);
projectedIdentityPayload = struct( ...
    'contractVersion', identityContract, ...
    'pairPhysicalUids', ...
        certificate.projectedPairPhysicalUids);
routeAndWeightHash = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), ...
    'fusionWeightMatrix', parentDetails.fusionWeightMatrix));

details = rmfield(parentDetails, ...
    'residualMassMatchedToReference');
details.parentContractVersion = parentDetails.contractVersion;
details.parentArmId = parentArmId;
details.parentRouteObjectiveVector = ...
    parentRouteObjectiveVector;
details.parentRouteAndWeightCanonicalSha256 = routeAndWeightHash;
details.contractVersion = ...
    'formation-b4-v46-fixed-runtime-policy-v1';
details.mode = mode;
details.armId = armId;
details.armOrdinal = armOrdinal;
details.actionName = armId;
details.objective = diagnosticsObjective;
details.objectiveDefinition = objectiveDefinition;
details.objectiveSource = objectiveSource;
details.objectiveDiagnosticsScalar = true;
details.objectiveFiniteScalarRequired = armOrdinal == 1;
details.protocolId = protocol.id;
details.protocolCanonicalSha256 = protocol.canonicalSha256;
details.repairTriggered = repairTriggered;
details.projectionCertificate = certificate;
details.projectionCertificateCanonicalSha256 = ...
    certificate.canonicalSha256;
details.projectionCertificateCrossBackboneOnly = true;
details.fullV43RouteCompositionPassed = true;
details.registeredBaseAdjacencyExecutionViewSha256 = ...
    registeredBaseHash;
details.projectedBaseAdjacencyExecutionViewSha256 = ...
    projectedBaseHash;
details.projectionArrayOrderExecutionCanonicalSha256 = ...
    certificate.arrayOrderExecutionCanonicalSha256;
details.registeredBaseGraphPhysicalUidPairs = ...
    certificate.registeredPairPhysicalUids;
details.projectedBaseGraphPhysicalUidPairs = ...
    certificate.projectedPairPhysicalUids;
details.registeredBaseGraphPhysicalUidCanonicalSha256 = ...
    computeCanonicalValueSha256(registeredIdentityPayload);
details.projectedBaseGraphPhysicalUidCanonicalSha256 = ...
    computeCanonicalValueSha256(projectedIdentityPayload);
details.projectedBaseAdjacency = logical(projectedBaseAdjacency);
details.staticAdjacencyWasPresent = staticAdjacencyPresent;
details.staticAdjacencyReplacedWhenPresent = ...
    staticAdjacencyPresent;
details.staticAdjacencyReplacementRuleEnforced = true;
details.baseAdjacencyReplacedInClone = true;
details.originalContextMutated = false;
details.routeAndWeightCanonicalSha256 = routeAndWeightHash;
details.routeReceivesCurrentPageOnly = true;
details.projectionReceivesCurrentPageOnly = true;
details.observableContextOnly = true;
details.policyOptionsAccepted = false;
details.posteriorUsedByProjection = false;
details.truthUsedByProjection = false;
details.measurementUsedByProjection = false;
details.futurePageUsedByProjection = false;
details.realizedDeliveryUniformsUsedByProjection = false;
details.perEdgeMassEquivalenceClaimAllowed = false;
details.dynamicSenderIdentityMayChange = true;
details.receiverPeriodResidualMassMatchedToCurrentReferenceWeight = ...
    true;
details.futureOutcomeUsed = false;
details.trackingOutcomeScored = false;
details.validationClaimAllowed = false;
details.developmentEvidenceOnly = true;
details.parentSelectionSeconds = parentDetails.selectionSeconds;
details.selectionSeconds = toc(timerId);
end

function [parentVector, scalarObjective, definition, source] = ...
        resolveDiagnosticsObjective(parentDetails, armOrdinal)
if armOrdinal == 1
    if ~isfield(parentDetails, 'objective') || ...
            ~isa(parentDetails.objective, 'double') || ...
            ~isreal(parentDetails.objective) || ...
            ~isequal(size(parentDetails.objective), [1, 2]) || ...
            any(~isfinite(parentDetails.objective))
        error('FormationB4V46:ParentRuntimeDrift', ...
            ['The V43 reference objective must be its frozen finite ', ...
             'dominant/residual bottleneck pair.']);
    end
    parentVector = parentDetails.objective;
    scalarObjective = min(parentVector);
    definition = [ ...
        'minimum-of-v43-dominant-and-local-residual-', ...
        'bottleneck-reliability'];
    source = 'v43-reference-objective-vector-minimum';
else
    if isfield(parentDetails, 'objective')
        error('FormationB4V46:ParentRuntimeDrift', ...
            ['The synchronized V45 parent unexpectedly exposed an ', ...
             'unregistered objective schema.']);
    end
    parentVector = zeros(1, 0);
    scalarObjective = NaN;
    definition = ...
        'not-defined-for-synchronized-duty-cycle-parent';
    source = 'not-applicable';
end
if ~isa(scalarObjective, 'double') || ...
        ~isreal(scalarObjective) || ~isscalar(scalarObjective) || ...
        (armOrdinal == 1 && ~isfinite(scalarObjective)) || ...
        (armOrdinal == 2 && ~isnan(scalarObjective))
    error('FormationB4V46:ParentRuntimeDrift', ...
        'The V46 diagnostics objective scalarization failed closed.');
end
end

function validateFullV43RouteComposition(context, adjacency, details)
nodeCount = numel(context.localPosteriorBySensor);
physical = logical(context.physicalAdjacency);
reference = details.referenceAdjacency;
weights = details.fusionWeightMatrix;
positiveOffDiagonal = weights > 1e-12;
positiveOffDiagonal(1:nodeCount+1:end) = false;
if ~islogical(reference) || ...
        ~isequal(size(reference), [nodeCount, nodeCount]) || ...
        any(diag(reference)) || nnz(reference) ~= 2 * nodeCount || ...
        any(reference(:) & ~physical(:)) || ...
        ~isStronglyConnected(reference) || ...
        ~islogical(adjacency) || ...
        ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        any(adjacency(:) & ~physical(:)) || ...
        any(adjacency(:) & ~reference(:)) || ...
        ~isa(weights, 'double') || ~isreal(weights) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(~isfinite(weights(:))) || any(weights(:) < 0) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        ~isequal(positiveOffDiagonal, adjacency)
    error('FormationB4V46:FullRouteCompositionFailed', ...
        ['The projected cross backbone did not compose into the ', ...
         'strict physical strongly connected V43 reference route.']);
end
end

function connected = isStronglyConnected(adjacency)
connected = reachableAll(adjacency) && reachableAll(adjacency');
end

function passed = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
passed = all(visited);
end

function validateRegisteredStaticConsistency(staticAdjacency, ...
        registeredBaseAdjacency)
if ~(islogical(staticAdjacency) || isnumeric(staticAdjacency)) || ...
        ~isreal(staticAdjacency) || ...
        any(~isfinite(staticAdjacency(:))) || ...
        ~isequal(size(staticAdjacency), ...
            size(registeredBaseAdjacency)) || ...
        any(staticAdjacency(:) ~= 0 & staticAdjacency(:) ~= 1) || ...
        ~isequal(logical(staticAdjacency), ...
            registeredBaseAdjacency)
    error('FormationB4V46:StaticBaseMismatch', ...
        ['An existing static adjacency must equal the registered ', ...
         'base adjacency before causal projection.']);
end
end

function validateProjectionInputsPresent(context)
required = {'model', 'localPosteriorBySensor', 'baseAdjacency', ...
    'physicalAdjacency', 'positions', 'commConfig', ...
    'sensorPhysicalUids', 'formationPhysicalUidsBySensor'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ...
        ~isstruct(context.model) || ~isscalar(context.model) || ...
        ~isfield(context.model, 'dynamicTopologyScenario') || ...
        ~isstruct(context.model.dynamicTopologyScenario) || ...
        ~isscalar(context.model.dynamicTopologyScenario) || ...
        ~isfield(context.model.dynamicTopologyScenario, 'config') || ...
        ~isstruct(context.model.dynamicTopologyScenario.config) || ...
        ~isscalar(context.model.dynamicTopologyScenario.config) || ...
        ~isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds') || ...
        ~isstruct(context.commConfig) || ...
        ~isscalar(context.commConfig) || ...
        ~isfield(context.commConfig, 'pDropByEdge')
    error('FormationB4V46:InvalidContext', ...
        'The frozen seven-input projection context is incomplete.');
end
end

function validateProjectionCertificate(certificate, sensorPhysicalUids, ...
        projectedBaseAdjacency)
required = {'contractVersion', 'canonicalSha256', ...
    'arrayOrderExecutionCanonicalSha256', ...
    'currentInputCanonicalSha256', ...
    'registeredRemovalCount', 'nonregisteredAdditionCount', ...
    'forcedRegisteredRemovalCount', ...
    'optionalRegisteredRemovalCount', ...
    'registeredPairPhysicalUids', ...
    'projectedPairPhysicalUids', ...
    'removedRegisteredPairPhysicalUids', ...
    'addedNonregisteredPairPhysicalUids', ...
    'searchCandidateCounts', ...
    'routeInputBoundary', 'registeredBaseGraphUsed', ...
    'currentGeometryUsed', 'currentPhysicalPageUsed', ...
    'currentLinkProbabilityPageUsed', 'futureGeometryUsed', ...
    'futurePhysicalPageUsed', 'posteriorUsed', 'truthUsed', ...
    'measurementUsed', 'realizedDeliveryUniformsUsed', ...
    'runtimeOverridesAccepted', 'scoreFunctionAccepted', ...
    'sensorArrayPermutationEquivarianceDesigned', ...
    'groupNumericRelabelEquivarianceDesigned'};
if ~isstruct(certificate) || ~isscalar(certificate) || ...
        ~all(isfield(certificate, required)) || ...
        ~strcmp(certificate.contractVersion, ...
            'causal-minimal-edit-formation-backbone-projection-v1') || ...
        ~strcmp(certificate.routeInputBoundary, ...
            ['current-page-only-no-runtime-overrides-or-', ...
             'score-functions']) || ...
        ~allTrue(certificate, { ...
            'registeredBaseGraphUsed', 'currentGeometryUsed', ...
            'currentPhysicalPageUsed', ...
            'currentLinkProbabilityPageUsed', ...
            'sensorArrayPermutationEquivarianceDesigned', ...
            'groupNumericRelabelEquivarianceDesigned'}) || ...
        ~allFalse(certificate, { ...
            'futureGeometryUsed', 'futurePhysicalPageUsed', ...
            'posteriorUsed', 'truthUsed', 'measurementUsed', ...
            'realizedDeliveryUniformsUsed', ...
            'runtimeOverridesAccepted', ...
            'scoreFunctionAccepted'}) || ...
        ~isSha256(certificate.canonicalSha256) || ...
        ~isSha256(certificate.currentInputCanonicalSha256) || ...
        ~isSha256(certificate. ...
            arrayOrderExecutionCanonicalSha256)
    error('FormationB4V46:ProjectionBoundaryViolation', ...
        'The causal projection certificate crossed its frozen boundary.');
end

countFields = {'registeredRemovalCount', ...
    'forcedRegisteredRemovalCount', ...
    'optionalRegisteredRemovalCount', ...
    'nonregisteredAdditionCount'};
if ~allNonnegativeIntegerFields(certificate, countFields) || ...
        certificate.registeredRemovalCount ~= ...
            certificate.forcedRegisteredRemovalCount + ...
            certificate.optionalRegisteredRemovalCount || ...
        ~validPhysicalUidPairs( ...
            certificate.registeredPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.projectedPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.removedRegisteredPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.addedNonregisteredPairPhysicalUids) || ...
        certificate.registeredRemovalCount ~= size( ...
            certificate.removedRegisteredPairPhysicalUids, 1) || ...
        certificate.nonregisteredAdditionCount ~= size( ...
            certificate.addedNonregisteredPairPhysicalUids, 1) || ...
        ~isstruct(certificate.searchCandidateCounts) || ...
        ~isscalar(certificate.searchCandidateCounts) || ...
        ~allNonnegativeIntegerFields( ...
            certificate.searchCandidateCounts, ...
            fieldnames(certificate.searchCandidateCounts))
    error('FormationB4V46:InvalidProjectionCertificate', ...
        'The projection certificate count or UID-pair schema is invalid.');
end

canonicalPayload = rmfield(certificate, { ...
    'canonicalSha256', ...
    'arrayOrderExecutionCanonicalSha256'});
actualCanonicalSha256 = ...
    computeCanonicalValueSha256(canonicalPayload);
executionPayload = struct( ...
    'contractVersion', ...
        'causal-minimal-edit-formation-execution-view-v1', ...
    'sensorPhysicalUidsByArray', ...
        reshape(sensorPhysicalUids, 1, []), ...
    'projectedBaseAdjacency', logical(projectedBaseAdjacency));
actualExecutionSha256 = ...
    computeCanonicalValueSha256(executionPayload);
if ~strcmp(actualCanonicalSha256, ...
        certificate.canonicalSha256) || ...
        ~strcmp(actualExecutionSha256, certificate. ...
            arrayOrderExecutionCanonicalSha256)
    error('FormationB4V46:InvalidProjectionCertificate', ...
        'The projection certificate failed canonical self-verification.');
end
end

function valid = allTrue(value, fields)
valid = all(cellfun(@(field) isTrue(value.(field)), fields));
end

function valid = allFalse(value, fields)
valid = all(cellfun(@(field) isFalse(value.(field)), fields));
end

function valid = allNonnegativeIntegerFields(value, fields)
valid = all(cellfun(@(field) ...
    isfield(value, field) && ...
    isa(value.(field), 'double') && ...
    isreal(value.(field)) && isscalar(value.(field)) && ...
    isfinite(value.(field)) && value.(field) >= 0 && ...
    value.(field) == round(value.(field)), fields));
end

function valid = validPhysicalUidPairs(value)
valid = isa(value, 'double') && isreal(value) && ...
    size(value, 2) == 2 && all(isfinite(value(:))) && ...
    all(value(:) >= 1) && all(value(:) == round(value(:))) && ...
    all(value(:, 1) < value(:, 2)) && ...
    isequal(value, sortrows(value, [1, 2]));
end

function valid = isTrue(value)
valid = islogical(value) && isscalar(value) && value;
end

function valid = isFalse(value)
valid = islogical(value) && isscalar(value) && ~value;
end

function valid = isSha256(value)
valid = ischar(value) && isrow(value) && numel(value) == 64 && ...
    all(ismember(lower(value), '0123456789abcdef'));
end
