function [config, fingerprint] = ...
    buildFormationBackboneBundleM24SourceTriggerConfig(presetName)
% BUILDFORMATIONBACKBONEBUNDLEM24SOURCETRIGGERCONFIG Fixed reference source.

registeredPresets = { ...
    'm24-formation-fov', ...
    'm24-formation-fov-convoy', ...
    'm24-formation-fov-relay'};
if ~ischar(presetName) || ~ismember(presetName, registeredPresets)
    error('FormationBundleSourcePermit:UnknownPreset', ...
        'The M24 source trigger preset is not registered.');
end
scene = buildDynamicTopologyScenarioConfig(presetName);
policy = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
config = buildMixtureAwareKlaReferenceConfig();
config.eventPolicy = 'alwaysHeavy';
config.useStaleNeighborCache = false;
config.labelHeartbeatEnabled = false;
config.dynamicTopologyEnabled = true;
config.dynamicTopologyEdgeBudget = scene.edgeBudget;
config.topologyMaxEdgeChangeFraction = inf;
config.topologyDirectedEnabled = true;
config.topologyDirectedMessageBudget = ...
    2 * scene.numberOfSensors;
config.topologyPolicyHistoryDepth = ...
    policy.rollingConnectivityWindowSteps - 1;
config.topologyPolicyObservableContextOnly = true;
config.topologyPolicyName = ...
    'formation-backbone-reference-source-v1';
config.topologyPosteriorCaptureTimes = scene.focusWindow(1);
config.topologyPolicyFcn = ...
    @selectFormationBackboneReferenceRuntimePolicy;

identity = resolveSimpleFunctionIdentity( ...
    config.topologyPolicyFcn, ...
    'selectFormationBackboneReferenceRuntimePolicy');
snapshot = rmfield(config, 'topologyPolicyFcn');
snapshot.topologyPolicyFunction = identity;
fingerprint = struct();
fingerprint.contractVersion = ...
    'formation-backbone-m24-source-trigger-fingerprint-v1';
fingerprint.presetName = presetName;
fingerprint.configSnapshot = snapshot;
fingerprint.canonicalSha256 = ...
    computeCanonicalValueSha256(struct( ...
        'contractVersion', fingerprint.contractVersion, ...
        'presetName', fingerprint.presetName, ...
        'configSnapshot', fingerprint.configSnapshot));
end

function identity = resolveSimpleFunctionIdentity(handle, expectedName)
info = functions(handle);
if ~isstruct(info) || ~isscalar(info) || ...
        ~isfield(info, 'type') || ~strcmp(info.type, 'simple') || ...
        ~strcmp(func2str(handle), expectedName)
    error('FormationBundleSourcePermit:InvalidPolicyHandle', ...
        'The registered source topology policy must be a simple handle.');
end
resolvedPath = which(expectedName);
repoRoot = fileparts(fileparts(mfilename('fullpath')));
expectedDirectory = fullfile(repoRoot, 'common');
if isempty(resolvedPath) || ...
        ~strcmp(fileparts(resolvedPath), expectedDirectory)
    error('FormationBundleSourcePermit:PolicyPathShadowed', ...
        'The source topology policy does not resolve inside this repo.');
end
identity = struct();
identity.functionName = expectedName;
identity.relativePath = fullfile( ...
    'common', [expectedName, '.m']);
identity.rawFileSha256 = computeFileSha256(resolvedPath);
end
