function probe = ...
    buildFormationIndexEquivariantAdaptiveWindowRouteProbe( ...
        context, options)
% BUILDFORMATIONINDEXEQUIVARIANTADAPTIVEWINDOWROUTEPROBE
% Calibrate the v43 physical-UID reference and evaluate one-page incoming
% bundle suspensions followed by reference recovery.

if nargin < 2 || isempty(options)
    options = struct();
end
allowedFields = {'targetSquaredContractionFactor', ...
    'maximumHorizonMultiplier', 'candidateFormationPhysicalUids', ...
    'maximumIncomingCount', 'dominantWeight', 'residualWeight'};
if ~isstruct(options) || ~isscalar(options) || ...
        any(~ismember(fieldnames(options), allowedFields))
    error('FormationIndexEquivariantProbe:InvalidOptions', ...
        'The v43 adaptive-window options are malformed.');
end
validateDevelopmentBoundary(context);
target = getField(options, 'targetSquaredContractionFactor', 0.90);
maximumMultiplier = getField(options, 'maximumHorizonMultiplier', 4);
maximumIncomingCount = getField(options, 'maximumIncomingCount', 2);
dominantWeight = getField(options, 'dominantWeight', 0.70);
residualWeight = getField(options, 'residualWeight', 0.05);
if ~isscalar(target) || ~isfinite(target) || target <= 0 || ...
        target >= 1 || ~isscalar(maximumMultiplier) || ...
        maximumMultiplier < 1 || maximumMultiplier ~= ...
            round(maximumMultiplier) || ...
        ~isscalar(maximumIncomingCount) || ...
        maximumIncomingCount < 1 || maximumIncomingCount ~= ...
            round(maximumIncomingCount)
    error('FormationIndexEquivariantProbe:InvalidOptions', ...
        'The target, horizon multiplier or incoming limit is invalid.');
end

runtime = validateReliableKlaMixingRuntimeSemantics( ...
    context.triggerConfig);
communication = validateReliableKlaCommunicationRuntimeSemantics( ...
    context.commConfig);
[referenceAdjacency, referenceDetails] = ...
    selectIndexEquivariantFormationBackbonePolicy(context, struct( ...
        'dominantWeight', dominantWeight, ...
        'residualWeight', residualWeight));
referenceWeights = referenceDetails.fusionWeightMatrix;
nodeCount = size(referenceAdjacency, 1);
maximumHorizon = maximumMultiplier * (nodeCount - 1);
reliability = 1 - context.commConfig.pDropByEdge';
profile = computeStaticReliableKlaMeanSquareHorizonProfile( ...
    referenceAdjacency, referenceWeights, reliability, ...
    maximumHorizon, struct( ...
        'missingNeighborWeightMode', ...
            runtime.missingNeighborWeightMode, ...
        'maximumIncomingCount', maximumIncomingCount, ...
        'targetSquaredFactors', target));
evaluationHorizon = profile.firstTargetHorizon(1);
calibrationPassed = isfinite(evaluationHorizon);
if ~calibrationPassed
    evaluationHorizon = maximumHorizon;
end
referenceFactor = profile. ...
    worstCaseExpectedSquaredFactorByHorizon(evaluationHorizon + 1);

formationUids = reshape(referenceDetails.formationPhysicalUids, 1, []);
requestedUids = reshape(getField(options, ...
    'candidateFormationPhysicalUids', formationUids), 1, []);
if numel(unique(requestedUids)) ~= numel(requestedUids) || ...
        any(~ismember(requestedUids, formationUids))
    error('FormationIndexEquivariantProbe:InvalidOptions', ...
        'Candidate physical formation UIDs are invalid.');
end

actionCount = 1 + numel(requestedUids);
actions = repmat(emptyAction(), 1, actionCount);
actions(1) = buildAction('reference', NaN, referenceAdjacency, ...
    referenceWeights, referenceDetails, referenceFactor, ...
    referenceFactor, evaluationHorizon);
if calibrationPassed
    for actionIdx = 2:actionCount
        formationUid = requestedUids(actionIdx - 1);
        try
            [adjacency, details] = ...
                selectTemporalIndexEquivariantFormationInputBundleSuspensionPolicy( ...
                    context, formationUid, struct( ...
                        'dominantWeight', dominantWeight, ...
                        'residualWeight', residualWeight));
            factor = evaluateCandidateWindow(adjacency, ...
                details.fusionWeightMatrix, referenceAdjacency, ...
                referenceWeights, reliability, evaluationHorizon, ...
                runtime.missingNeighborWeightMode, maximumIncomingCount);
            actions(actionIdx) = buildAction( ...
                details.actionName, formationUid, adjacency, ...
                details.fusionWeightMatrix, details, factor, ...
                referenceFactor, evaluationHorizon);
        catch errorInfo
            if ~strcmp(errorInfo.identifier, ...
                    'IndexEquivariantBundleSuspension:Infeasible')
                rethrow(errorInfo);
            end
            actions(actionIdx).actionName = sprintf( ...
                'suspend-input-bundle-uid%.0f', formationUid);
            actions(actionIdx).formationPhysicalUid = formationUid;
            actions(actionIdx).available = false;
            actions(actionIdx).failureIdentifier = errorInfo.identifier;
            actions(actionIdx).failureMessage = errorInfo.message;
        end
    end
end

availableCandidates = find([actions(2:end).available]) + 1;
if isempty(availableCandidates)
    leastHarmfulCandidateUid = NaN;
    leastHarmfulCandidateFactorDelta = NaN;
    improvingCandidateCount = 0;
else
    deltas = [actions(availableCandidates).factorDelta];
    leastHarmfulCandidateFactorDelta = min(deltas);
    tiedLocalIndices = find(abs(deltas - ...
        leastHarmfulCandidateFactorDelta) <= 1e-12);
    tiedActionIndices = availableCandidates(tiedLocalIndices);
    tiedUids = [actions(tiedActionIndices).formationPhysicalUid];
    [leastHarmfulCandidateUid, uidTieIdx] = min(tiedUids);
    selectedLeastHarmfulActionIdx = tiedActionIndices(uidTieIdx);
    leastHarmfulCandidateFactorDelta = actions( ...
        selectedLeastHarmfulActionIdx).factorDelta;
    improvingCandidateCount = nnz(deltas < -1e-12);
end
improvementTolerance = 1e-12;
sparseActionAuthorized = isfinite(leastHarmfulCandidateFactorDelta) && ...
    leastHarmfulCandidateFactorDelta < -improvementTolerance;
if sparseActionAuthorized
    selectedActionName = sprintf( ...
        'suspend-input-bundle-uid%.0f', leastHarmfulCandidateUid);
    selectedActionPhysicalFormationUid = leastHarmfulCandidateUid;
else
    selectedActionName = 'reference';
    selectedActionPhysicalFormationUid = NaN;
end

probe = struct();
probe.contractVersion = ...
    'formation-index-equivariant-adaptive-window-route-probe-v1';
probe.nodeCount = nodeCount;
probe.formationCount = numel(formationUids);
probe.formationPhysicalUids = formationUids;
probe.currentTime = context.currentTime;
probe.targetSquaredContractionFactor = target;
probe.maximumHorizonMultiplier = maximumMultiplier;
probe.maximumHorizon = maximumHorizon;
probe.dominantWeight = dominantWeight;
probe.residualWeight = residualWeight;
probe.calibrationPassed = calibrationPassed;
probe.evaluationHorizon = evaluationHorizon;
probe.referenceHorizonProfile = profile;
probe.referenceAdjacency = referenceAdjacency;
probe.referenceFusionWeights = referenceWeights;
probe.referenceSquaredContractionFactor = referenceFactor;
probe.currentReliabilityReceiverSender = reliability;
probe.actions = actions;
probe.availableActionMask = [actions.available];
probe.leastHarmfulCandidatePhysicalFormationUid = ...
    leastHarmfulCandidateUid;
probe.leastHarmfulCandidateFactorDelta = ...
    leastHarmfulCandidateFactorDelta;
probe.improvingCandidateCount = improvingCandidateCount;
probe.improvementTolerance = improvementTolerance;
probe.sparseActionAuthorized = sparseActionAuthorized;
probe.selectedActionName = selectedActionName;
probe.selectedActionPhysicalFormationUid = ...
    selectedActionPhysicalFormationUid;
probe.referenceFallbackUsed = ~sparseActionAuthorized;
probe.runtimeSemantics = runtime;
probe.communicationSemantics = communication;
probe.routePlan = 'candidate-once-then-v43-reference';
probe.referenceRouteIndexEquivarianceDesigned = true;
probe.routeBoundaryVerified = verifyRouteAndActionBoundaries( ...
    referenceDetails, actions);
probe.auditBoundary = context.auditBoundary;
probe.fullPlannedSensorGeometryMaterialized = ...
    context.auditBoundary.fullPlannedSensorGeometryMaterialized;
probe.fullPlannedLinkProbabilityScheduleMaterialized = ...
    context.auditBoundary.fullPlannedLinkProbabilityScheduleMaterialized;
probe.formalRuntimeObservableBoundaryPassed = ...
    context.auditBoundary.formalRuntimeObservableBoundaryPassed;
probe.runtimePhysicalUidRegistryIntegrated = ...
    context.auditBoundary.runtimePhysicalUidRegistryIntegrated;
probe.posteriorContentsRead = false;
probe.truthUsed = false;
probe.measurementUsed = false;
probe.futureOutcomeUsed = false;
probe.realizedDeliveryUniformsUsed = false;
probe.trackingOutcomeScored = false;
probe.trackingOutcomeAuthorized = false;
probe.validationClaimAllowed = false;
probe.developmentEvidenceOnly = true;
probe.auditBoundaryCanonicalSha256 = ...
    computeCanonicalValueSha256(context.auditBoundary);
end

function passed = verifyRouteAndActionBoundaries(referenceDetails, actions)
required = {'posteriorUsed', 'truthUsed', 'measurementUsed', ...
    'futureOutcomeUsed', 'realizedDeliveryUniformsUsed', ...
    'trackingOutcomeScored', 'currentGeometryUsed', ...
    'currentLinkReliabilityUsed', 'currentPhysicalActionSetUsed'};
if ~all(isfield(referenceDetails, required))
    error('FormationIndexEquivariantProbe:BoundaryMissing', ...
        'The reference route omitted required execution-boundary fields.');
end
passed = ~referenceDetails.posteriorUsed && ...
    ~referenceDetails.truthUsed && ~referenceDetails.measurementUsed && ...
    ~referenceDetails.futureOutcomeUsed && ...
    ~referenceDetails.realizedDeliveryUniformsUsed && ...
    ~referenceDetails.trackingOutcomeScored && ...
    referenceDetails.currentGeometryUsed && ...
    referenceDetails.currentLinkReliabilityUsed && ...
    referenceDetails.currentPhysicalActionSetUsed;
available = find([actions.available]);
for actionIdx = available
    passed = passed && actions(actionIdx).currentGeometryUsed && ...
        actions(actionIdx).currentLinkReliabilityUsed && ...
        ~actions(actionIdx).posteriorUsed && ...
        ~actions(actionIdx).truthUsed && ...
        ~actions(actionIdx).futureOutcomeUsed;
end
if ~passed
    error('FormationIndexEquivariantProbe:BoundaryViolation', ...
        'A probe route crossed the registered development boundary.');
end
end

function validateDevelopmentBoundary(context)
if ~isstruct(context) || ~isscalar(context) || ...
        ~isfield(context, 'auditBoundary')
    error('FormationIndexEquivariantProbe:MissingAuditBoundary', ...
        'The v43 probe requires an explicit development boundary.');
end
boundary = context.auditBoundary;
required = {'fullPlannedSensorGeometryMaterialized', ...
    'fullPlannedLinkProbabilityScheduleMaterialized', ...
    'formalRuntimeObservableBoundaryPassed', ...
    'runtimePhysicalUidRegistryIntegrated', ...
    'trackingOutcomeAuthorized', 'validationClaimAllowed', ...
    'developmentEvidenceOnly'};
if ~isstruct(boundary) || ~isscalar(boundary) || ...
        ~all(isfield(boundary, required)) || ...
        ~boundary.fullPlannedSensorGeometryMaterialized || ...
        ~boundary.fullPlannedLinkProbabilityScheduleMaterialized || ...
        boundary.formalRuntimeObservableBoundaryPassed || ...
        boundary.runtimePhysicalUidRegistryIntegrated || ...
        boundary.trackingOutcomeAuthorized || ...
        boundary.validationClaimAllowed || ...
        ~boundary.developmentEvidenceOnly
    error('FormationIndexEquivariantProbe:InvalidAuditBoundary', ...
        'The development-only v43 claim boundary is inconsistent.');
end
end

function factor = evaluateCandidateWindow(candidateAdjacency, ...
        candidateWeights, referenceAdjacency, referenceWeights, ...
        reliability, horizon, missingMode, maximumIncomingCount)
adjacencySequence = repmat(referenceAdjacency, 1, 1, horizon);
weightSequence = repmat(referenceWeights, 1, 1, horizon);
adjacencySequence(:, :, 1) = candidateAdjacency;
weightSequence(:, :, 1) = candidateWeights;
reliabilitySequence = repmat(reliability, 1, 1, horizon);
certificate = ...
    computeReliableKlaWindowMeanSquareContractionCertificate( ...
        adjacencySequence, weightSequence, reliabilitySequence, ...
        struct('missingNeighborWeightMode', missingMode, ...
            'maximumIncomingCount', maximumIncomingCount));
factor = validateFormationReliableKlaContractionFactor( ...
    certificate.worstCaseExpectedSquaredContractionFactor, ...
    'v43-candidate');
end

function action = buildAction(name, formationUid, adjacency, weights, ...
        details, factor, referenceFactor, horizon)
requiredBoundaryFields = {'currentGeometryUsed', ...
    'currentLinkReliabilityUsed', 'posteriorUsed', 'truthUsed', ...
    'futureOutcomeUsed'};
if ~all(isfield(details, requiredBoundaryFields))
    error('FormationIndexEquivariantProbe:BoundaryMissing', ...
        'An action selector omitted required boundary evidence.');
end
formationUidsBySensor = details.construction. ...
    formationPhysicalUidsBySensor;
crossMask = formationUidsBySensor(:) ~= ...
    formationUidsBySensor(:)';
action = emptyAction();
action.actionName = name;
action.formationPhysicalUid = formationUid;
action.available = true;
action.adjacency = logical(adjacency);
action.fusionWeights = weights;
action.routeCanonicalSha256 = computeCanonicalValueSha256( ...
    struct('adjacency', logical(adjacency), 'weights', weights));
action.directedMessageCount = nnz(adjacency);
action.crossFormationMessageCount = nnz(adjacency & crossMask);
action.messageSavingCount = 2 * size(adjacency, 1) - nnz(adjacency);
action.squaredContractionFactor = factor;
action.factorDelta = factor - referenceFactor;
action.factorRatio = factor / referenceFactor;
action.evaluationHorizon = horizon;
action.policyDetailsContractVersion = details.contractVersion;
action.currentGeometryUsed = details.currentGeometryUsed;
action.currentLinkReliabilityUsed = details.currentLinkReliabilityUsed;
action.posteriorUsed = details.posteriorUsed;
action.truthUsed = details.truthUsed;
action.futureOutcomeUsed = details.futureOutcomeUsed;
end

function action = emptyAction()
action = struct('actionName', '', 'formationPhysicalUid', NaN, ...
    'available', false, 'failureIdentifier', '', ...
    'failureMessage', '', 'adjacency', false(0), ...
    'fusionWeights', zeros(0), 'routeCanonicalSha256', '', ...
    'directedMessageCount', NaN, ...
    'crossFormationMessageCount', NaN, ...
    'messageSavingCount', NaN, ...
    'squaredContractionFactor', NaN, 'factorDelta', NaN, ...
    'factorRatio', NaN, 'evaluationHorizon', NaN, ...
    'policyDetailsContractVersion', '', ...
    'currentGeometryUsed', false, ...
    'currentLinkReliabilityUsed', false, ...
    'posteriorUsed', false, 'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
