function bank = buildCounterfactualEdgeRoleBankV146()
% BUILDCOUNTERFACTUALEDGEROLEBANKV146 Frozen rank-equivariant action bank.

patterns = { ...
    'first-rank', ...
    'last-rank', ...
    'odd-ranks', ...
    'even-ranks', ...
    'upper-half', ...
    'lower-half', ...
    'all-ranks'};
actions = repmat(struct( ...
    'index', 0, ...
    'name', '', ...
    'formationRankPattern', '', ...
    'workingPageOffsets', [1, 2, 3, 5], ...
    'maximumConsecutiveWorkingPages', 3, ...
    'initialReferencePageRequired', true, ...
    'onePayloadPerAttemptedEdge', true, ...
    'crossFormationWorkingAllowed', false), 1, numel(patterns));
for actionIdx = 1:numel(patterns)
    actions(actionIdx).index = actionIdx;
    actions(actionIdx).name = [patterns{actionIdx}, '-rwwwrw'];
    actions(actionIdx).formationRankPattern = patterns{actionIdx};
end
bank = struct( ...
    'contractVersion', 'v146-counterfactual-edge-role-bank-v1', ...
    'rankingSource', 'frozen-v134-action-order', ...
    'numericFormationIdUsedAsRank', false, ...
    'allReferenceIncumbentImplicit', true, ...
    'actions', actions);
end
