function context = ...
        buildFormationBraidRoutingComparisonV241ExecutionContext( ...
            presetName, seed, armId, measurementTimeCount)
% BUILDFORMATIONBRAIDROUTINGCOMPARISONV241EXECUTIONCONTEXT Development run.

protocol = getFormationBraidRoutingComparisonV241Protocol();
if ~ischar(presetName) || ...
        ~ismember(presetName, protocol.allowedPresets) || ...
        ~ismember(seed, protocol.allowedSeeds) || ...
        ~ischar(armId) || ~any(strcmp(armId, protocol.armIds)) || ...
        ~isscalar(measurementTimeCount) || ...
        ~isfinite(measurementTimeCount) || ...
        measurementTimeCount < 1 || ...
        measurementTimeCount ~= round(measurementTimeCount)
    error('FormationBraidRoutingV241:InvalidExecutionContextInput', ...
        'V241 requires a registered scene, seed, arm and time axis.');
end
context = struct();
context.contractVersion = ...
    'formation-braid-routing-comparison-v241-context-v1';
context.capability = ...
    'formation-braid-routing-comparison-v241-development';
context.action = ...
    'filter-formation-braid-routing-comparison-v241-development';
context.protocolId = protocol.id;
context.presetName = presetName;
context.seed = seed;
context.armId = armId;
context.measurementTimeCount = measurementTimeCount;
context.policyName = expectedPolicy(armId, protocol);
context.developmentEvidenceOnly = true;
end

function name = expectedPolicy(armId, protocol)
if strcmp(armId, protocol.staticDropoutArmId)
    name = protocol.staticDropoutPolicyName;
elseif strcmp(armId, protocol.alwaysReplanArmId)
    name = protocol.alwaysReplanPolicyName;
else
    name = protocol.causalPolicyName;
end
end
