function [digest, contract] = ...
    computeFormationFovMultistyleSceneContractSha256(config)
% COMPUTEFORMATIONFOVMULTISTYLESCENECONTRACTSHA256 Freeze scene semantics.
%
% The fingerprint covers geometry, traffic, sensing, communication,
% topology and authorization fields.  It intentionally excludes aliases
% such as presetName and excludes its own digest field.

required = { ...
    'sceneGeometryVersion', 'sceneStyle', 'informationFlowStyle', ...
    'sceneCalibrationStatus', 'formalValidationAuthorized', ...
    'trackingOutcomeAuthorized', 'simulationLength', 'samplingPeriod', ...
    'regionLimits', 'observationSpaceLimits', 'formationCount', ...
    'sensorsPerFormation', 'numberOfSensors', 'sensorGroupIds', ...
    'formationRadius', 'formationRadiusJitterFraction', ...
    'formationRotationJitterDeg', 'formationHeadingMode', ...
    'sensorWaypointTimes', 'sensorCenterWaypoints', ...
    'sensorSpeedLimit', 'sensorAccelerationLimit', ...
    'minimumSensorSeparation', 'targetGroupCount', ...
    'targetsPerTargetGroup', 'numberOfTargets', 'targetGroupIds', ...
    'targetRoutes', 'targetBirthTimesByGroup', ...
    'targetDeathTimesByGroup', 'targetCrossTrackSpacing', ...
    'targetSpeedLimit', 'targetAccelerationLimit', ...
    'minimumTargetSeparation', 'minimumSensorTargetSeparation', ...
    'normalizeTargetRouteDuration', ...
    'clutterRate', 'detectionProbability', 'measurementNoiseStd', ...
    'birthProbability', 'birthCovarianceDiagonal', ...
    'survivalProbability', 'ospaPositionCutoff', 'fovRange', ...
    'fovHalfAngleDeg', 'fovTotalAngleDeg', 'sensorFovHeadingMode', ...
    'sensorFovPointingCenter', 'sensorQuality', ...
    'sensorHardwareProfile', 'clutterSpatialProfile', 'commRange', ...
    'linkMode', 'forceDelivery', 'intraFormationDropProbability', ...
    'interFormationDropMinimum', 'interFormationDropScale', ...
    'blockageScheduleMode', 'blockageWindows', ...
    'blockageWindowTimes', 'edgeBudget', ...
    'maxEdgeReplacementsPerStep', 'maxNodeDegree', ...
    'maxInterFormationDegree', 'topologyFamily', ...
    'staticTopologyMode', 'formationBackboneMode', ...
    'attemptedByteToleranceFraction', ...
    'requireStaticPhysicalAllTimes', 'requireGlobalConnectivity', ...
    'useRingIntraFormationBackbone', 'focusWindowName', ...
    'focusWindow', 'difficultyCloseTargetDistance', ...
    'enforceDifficultyRequirements', 'difficultyRequirements', ...
    'scaleControlReferencePreset', 'scaleControlMatchedMetrics', ...
    'scaleControlDerivedMetrics'};
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, required))
    error('FormationFovSceneContract:IncompleteConfig', ...
        'Cannot fingerprint an incomplete multistyle scene config.');
end

contract = struct();
contract.contractVersion = ...
    'formation-fov-multistyle-scene-contract-v5';
for fieldIdx = 1:numel(required)
    fieldName = required{fieldIdx};
    contract.(fieldName) = config.(fieldName);
end
if isfield(config, 'sensorFovFixedHeadingRadByFormation')
    contract.sensorFovFixedHeadingRadByFormation = ...
        config.sensorFovFixedHeadingRadByFormation;
else
    contract.sensorFovFixedHeadingRadByFormation = zeros(1, 0);
end
digest = computeCanonicalValueSha256(contract);
end
