function metrics = computeTimeExpandedEffectiveKlaPathsV87( ...
        context, control, groupIds, caseInfo, options)
% COMPUTETIMEEXPANDEDEFFECTIVEKLAPATHSV87 Current-only two-hop KLA value.

if nargin < 5 || isempty(options)
    options = getTimeExpandedEffectiveKlaGraphV87Protocol();
end
requiredContext = { ...
    'localPosteriorBySensor', 'physicalAdjacency', 'model', ...
    'commConfig', 'currentTime'};
requiredControl = { ...
    'referenceAdjacency', 'referenceFusionWeights', 'referenceScore'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, requiredContext)) || ...
        ~isstruct(control) || ~isscalar(control) || ...
        ~all(isfield(control, requiredControl)) || ...
        ~isstruct(caseInfo) || ~isscalar(caseInfo)
    error('TimeExpandedEffectiveKlaV87:InvalidInput', ...
        'V87 requires one opened current state and frozen V86 source.');
end

posteriors = reshape(context.localPosteriorBySensor, 1, []);
groupIds = reshape(groupIds, 1, []);
nodeCount = numel(posteriors);
referenceAdjacency = logical(control.referenceAdjacency);
referenceWeights = control.referenceFusionWeights;
physical = logical(context.physicalAdjacency);
if numel(groupIds) ~= nodeCount || ...
        ~isequal(size(referenceAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(referenceWeights), [nodeCount, nodeCount]) || ...
        ~isequal(size(physical), [nodeCount, nodeCount])
    error('TimeExpandedEffectiveKlaV87:DimensionMismatch', ...
        'V87 posterior and graph dimensions do not align.');
end

gatewayIdx = caseInfo.receiverIdx;
incumbentIdx = caseInfo.incumbentSenderIdx;
sourceIdx = caseInfo.candidateSenderIdx;
validateSourceEdge( ...
    groupIds, referenceAdjacency, referenceWeights, physical, ...
    gatewayIdx, incumbentIdx, sourceIdx, options.sourceWeight);
receiverFormationId = groupIds(gatewayIdx);
formationMembers = reshape(find( ...
    groupIds == receiverFormationId), 1, []);

referenceGateway = fuseRow( ...
    posteriors, referenceWeights(gatewayIdx, :), gatewayIdx, ...
    context.model, options.fusionConfig);
acquireWeights = referenceWeights(gatewayIdx, :);
acquireWeights(incumbentIdx) = 0;
acquireWeights(sourceIdx) = options.sourceWeight;
acquiredGateway = fuseRow( ...
    posteriors, acquireWeights, gatewayIdx, ...
    context.model, options.fusionConfig);

novelLabels = collectLabels( ...
    posteriors{gatewayIdx}, posteriors{incumbentIdx}, ...
    posteriors{sourceIdx}, referenceGateway, acquiredGateway);
novelEvidence = sourceNovelEvidence( ...
    posteriors{gatewayIdx}, posteriors{incumbentIdx}, ...
    posteriors{sourceIdx}, novelLabels);
firstReliability = linkReliability( ...
    context.commConfig, sourceIdx, gatewayIdx, context.currentTime);
[gatewayGainMass, gatewayHarmMass] = existenceChangeMass( ...
    referenceGateway, acquiredGateway, novelLabels, ...
    novelEvidence, max( ...
        supportByLabel(posteriors{gatewayIdx}, novelLabels), ...
        supportByLabel(posteriors{incumbentIdx}, novelLabels)), ...
    firstReliability);

referenceRoundOne = cell(1, nodeCount);
referenceRoundOne{gatewayIdx} = referenceGateway;
pathRecords = repmat(emptyPathRecord(), 1, 0);
formationMass = receiverFormationReferenceMass( ...
    control, groupIds, receiverFormationId);
positionScale = resolvePositionScale(context.model);
for receiverIdx = formationMembers
    if receiverIdx == gatewayIdx
        continue;
    end
    [candidateWeights, dominantIdx, residualIdx] = ...
        buildBroadcastRow( ...
            referenceAdjacency, referenceWeights, physical, groupIds, ...
            receiverIdx, gatewayIdx, receiverFormationId, options);
    referenceSenders = find(referenceWeights(receiverIdx, :) > 1e-12);
    candidateSenders = find(candidateWeights > 1e-12);
    requiredFirstRound = unique([ ...
        referenceSenders, candidateSenders], 'stable');
    for senderIdx = requiredFirstRound
        if isempty(referenceRoundOne{senderIdx})
            referenceRoundOne{senderIdx} = fuseRow( ...
                posteriors, referenceWeights(senderIdx, :), senderIdx, ...
                context.model, options.fusionConfig);
        end
    end
    candidateRoundOne = referenceRoundOne;
    candidateRoundOne{gatewayIdx} = acquiredGateway;
    referenceDownstream = fuseRow( ...
        referenceRoundOne, referenceWeights(receiverIdx, :), ...
        receiverIdx, context.model, options.fusionConfig);
    candidateDownstream = fuseRow( ...
        candidateRoundOne, candidateWeights, receiverIdx, ...
        context.model, options.fusionConfig);

    labels = collectLabels( ...
        referenceDownstream, candidateDownstream, ...
        posteriors{sourceIdx}, posteriors{receiverIdx}, ...
        posteriors{dominantIdx}, posteriors{residualIdx});
    evidence = sourceNovelEvidence( ...
        posteriors{gatewayIdx}, posteriors{incumbentIdx}, ...
        posteriors{sourceIdx}, labels);
    protectedSupport = max([ ...
        supportByLabel(posteriors{receiverIdx}, labels); ...
        supportByLabel(posteriors{dominantIdx}, labels); ...
        supportByLabel(posteriors{residualIdx}, labels)], [], 1);
    secondReliability = linkReliability( ...
        context.commConfig, gatewayIdx, receiverIdx, ...
        context.currentTime);
    pathReliability = firstReliability * secondReliability;
    [gainMass, harmMass, upward, downward] = ...
        existenceChangeMass( ...
            referenceDownstream, candidateDownstream, labels, ...
            evidence, protectedSupport, pathReliability, ...
            options.positiveSupportThreshold, ...
            options.decisionExistenceThreshold);
    [stateGain, stateHarm] = stateAlignmentMass( ...
        referenceDownstream, candidateDownstream, ...
        posteriors{sourceIdx}, posteriors{receiverIdx}, ...
        posteriors{dominantIdx}, posteriors{residualIdx}, ...
        labels, evidence, protectedSupport, pathReliability, ...
        positionScale, context.model.xDimension);
    existenceNet = (gainMass - harmMass) / formationMass;
    stateNet = (stateGain - stateHarm) / formationMass;
    survival = gainMass / max(gatewayGainMass, eps);
    harmSafe = harmMass <= ...
        options.maximumSupportedHarmRatio * gainMass + 1e-12;
    enabled = gainMass > eps && ...
        existenceNet > ...
            options.minimumDownstreamExistenceNetFraction + 1e-12 && ...
        survival >= options.minimumExistenceSurvivalRatio - 1e-12 && ...
        stateNet >= options.minimumStateAlignmentNetFraction - 1e-12 && ...
        harmSafe && (~options.requireZeroSupportedDownwardCrossings || ...
            downward == 0);
    rankingScore = 0;
    if enabled
        rankingScore = existenceNet * survival + max(stateNet, 0);
    end
    pathRecords(end + 1) = struct( ... %#ok<AGROW>
        'sourceIdx', sourceIdx, ...
        'gatewayIdx', gatewayIdx, ...
        'receiverIdx', receiverIdx, ...
        'receiverFormationId', receiverFormationId, ...
        'displacedDominantSenderIdx', dominantIdx, ...
        'removedResidualSenderIdx', residualIdx, ...
        'firstHopReliability', firstReliability, ...
        'secondHopReliability', secondReliability, ...
        'pathReliability', pathReliability, ...
        'gatewayExistenceGainMass', gatewayGainMass, ...
        'gatewayExistenceHarmMass', gatewayHarmMass, ...
        'downstreamExistenceGainFraction', gainMass / formationMass, ...
        'downstreamExistenceHarmFraction', harmMass / formationMass, ...
        'downstreamExistenceNetFraction', existenceNet, ...
        'existenceSurvivalRatio', survival, ...
        'stateAlignmentGainFraction', stateGain / formationMass, ...
        'stateAlignmentHarmFraction', stateHarm / formationMass, ...
        'stateAlignmentNetFraction', stateNet, ...
        'upwardCrossingCount', upward, ...
        'downwardCrossingCount', downward, ...
        'harmSafe', harmSafe, ...
        'pathEnabled', enabled, ...
        'rankingScore', rankingScore);
end

enabledMask = [pathRecords.pathEnabled];
metrics = struct();
metrics.contractVersion = ...
    'time-expanded-effective-kla-paths-v87-v1';
metrics.sourceIdx = sourceIdx;
metrics.gatewayIdx = gatewayIdx;
metrics.incumbentIdx = incumbentIdx;
metrics.receiverFormationId = receiverFormationId;
metrics.formationMembers = formationMembers;
metrics.referenceExistenceMass = formationMass;
metrics.gatewayExistenceGainFraction = ...
    gatewayGainMass / formationMass;
metrics.gatewayExistenceHarmFraction = ...
    gatewayHarmMass / formationMass;
metrics.pathRecords = pathRecords;
metrics.enabledReceiverIndices = ...
    [pathRecords(enabledMask).receiverIdx];
metrics.enabledPathCount = nnz(enabledMask);
metrics.enabledReceiverCoverageFraction = ...
    nnz(enabledMask) / max(numel(formationMembers) - 1, 1);
metrics.aggregateDownstreamExistenceNetFraction = sum( ...
    [pathRecords(enabledMask).downstreamExistenceNetFraction]);
metrics.aggregateStateAlignmentNetFraction = sum( ...
    [pathRecords(enabledMask).stateAlignmentNetFraction]);
metrics.maximumRankingScore = finiteMax( ...
    [pathRecords(enabledMask).rankingScore]);
metrics.minimumExistenceSurvivalRatio = ...
    options.minimumExistenceSurvivalRatio;
metrics.minimumDownstreamExistenceNetFraction = ...
    options.minimumDownstreamExistenceNetFraction;
metrics.minimumStateAlignmentNetFraction = ...
    options.minimumStateAlignmentNetFraction;
metrics.receiverFusionMode = 'mixture-aware-heavy';
metrics.composedKlaRoundCount = 2;
metrics.routeExecuted = false;
metrics.truthUsed = false;
metrics.futureMeasurementsUsed = false;
metrics.futureOutcomesUsed = false;
end

function fused = fuseRow(posteriors, rowWeights, receiverIdx, model, config)
senders = find(rowWeights > 1e-12);
weights = rowWeights(senders);
receiverPosition = find(senders == receiverIdx, 1);
if isempty(receiverPosition)
    error('TimeExpandedEffectiveKlaV87:MissingReceiverInput', ...
        'Every V87 KLA row must include its receiver posterior first.');
end
order = [receiverPosition, ...
    setdiff(1:numel(senders), receiverPosition, 'stable')];
senders = senders(order);
weights = weights(order);
sources = cell(1, numel(senders));
for sourcePosition = 1:numel(senders)
    sources{sourcePosition} = posteriors{senders(sourcePosition)};
end
details = struct( ...
    'eventType', [0, 2 * ones(1, numel(senders) - 1)]);
fused = fuseLmbPosteriorsByLabel( ...
    sources, weights, model, weights, details, config);
end

function [weights, dominantIdx, residualIdx] = buildBroadcastRow( ...
        adjacency, referenceWeights, physical, groupIds, receiverIdx, ...
        gatewayIdx, formationId, options)
dominantIdx = unique(find( ...
    adjacency(receiverIdx, :) & groupIds == formationId & ...
    abs(referenceWeights(receiverIdx, :) - ...
        options.dominantWeight) <= 1e-12));
residualIdx = unique(find( ...
    adjacency(receiverIdx, :) & ...
    abs(referenceWeights(receiverIdx, :) - ...
        options.sourceWeight) <= 1e-12));
if numel(dominantIdx) ~= 1 || numel(residualIdx) ~= 1 || ...
        dominantIdx == gatewayIdx || ~physical(receiverIdx, gatewayIdx)
    error('TimeExpandedEffectiveKlaV87:BroadcastSlotDrift', ...
        'A V87 downstream row no longer matches the V86 route contract.');
end
weights = referenceWeights(receiverIdx, :);
if residualIdx == gatewayIdx
    weights(dominantIdx) = options.sourceWeight;
    weights(gatewayIdx) = options.dominantWeight;
else
    weights(residualIdx) = 0;
    weights(dominantIdx) = options.sourceWeight;
    weights(gatewayIdx) = options.dominantWeight;
end
if ~rowWeightMultisetParity(weights, referenceWeights(receiverIdx, :))
    error('TimeExpandedEffectiveKlaV87:WeightParityFailure', ...
        'A V87 downstream row changed its weight multiset.');
end
end

function validateSourceEdge( ...
        groupIds, adjacency, weights, physical, receiver, incumbent, ...
        candidate, sourceWeight)
valid = adjacency(receiver, incumbent) && ...
    ~adjacency(receiver, candidate) && physical(receiver, candidate) && ...
    groupIds(receiver) ~= groupIds(incumbent) && ...
    groupIds(receiver) ~= groupIds(candidate) && ...
    groupIds(incumbent) ~= groupIds(candidate) && ...
    abs(weights(receiver, incumbent) - sourceWeight) <= 1e-12 && ...
    weights(receiver, candidate) <= 1e-12;
if ~valid
    error('TimeExpandedEffectiveKlaV87:SourceEdgeDrift', ...
        'The V87 source edge no longer matches the frozen V84 action.');
end
end

function [gain, harm, upwardCount, downwardCount] = ...
        existenceChangeMass( ...
            reference, candidate, labels, novelEvidence, ...
            protectedSupport, reliability, supportThreshold, ...
            decisionThreshold)
if nargin < 7
    supportThreshold = 0.20;
end
if nargin < 8
    decisionThreshold = 0.50;
end
referenceExistence = existenceByLabel(reference, labels);
candidateExistence = existenceByLabel(candidate, labels);
gain = reliability * sum( ...
    max(candidateExistence - referenceExistence, 0) .* novelEvidence);
harm = reliability * sum( ...
    max(referenceExistence - candidateExistence, 0) .* ...
        protectedSupport);
upward = novelEvidence > 0 & ...
    referenceExistence < decisionThreshold & ...
    candidateExistence >= decisionThreshold;
downward = protectedSupport >= supportThreshold - 1e-12 & ...
    referenceExistence >= decisionThreshold & ...
    candidateExistence < decisionThreshold;
upwardCount = nnz(upward);
downwardCount = nnz(downward);
end

function [gain, harm] = stateAlignmentMass( ...
        reference, candidate, source, receiver, dominant, residual, ...
        labels, novelEvidence, protectedSupport, reliability, ...
        positionScale, stateDimension)
gain = 0;
harm = 0;
referenceExistence = existenceByLabel(reference, labels);
candidateExistence = existenceByLabel(candidate, labels);
supportSources = {receiver, dominant, residual};
for labelIdx = 1:size(labels, 2)
    label = labels(:, labelIdx);
    refObject = objectByLabel(reference, label);
    candObject = objectByLabel(candidate, label);
    if isempty(refObject) || isempty(candObject)
        continue;
    end
    refMean = objectMean(refObject, stateDimension);
    candMean = objectMean(candObject, stateDimension);
    existenceWeight = max( ...
        referenceExistence(labelIdx), candidateExistence(labelIdx));
    sourceObject = objectByLabel(source, label);
    if novelEvidence(labelIdx) > 0 && ~isempty(sourceObject)
        sourceMean = objectMean(sourceObject, stateDimension);
        delta = normalizedAlignmentChange( ...
            refMean, candMean, sourceMean, positionScale);
        weight = novelEvidence(labelIdx) * existenceWeight;
        gain = gain + weight * max(delta, 0);
        harm = harm + weight * max(-delta, 0);
    end
    if protectedSupport(labelIdx) > 0
        [anchor, available] = strongestSupportedMean( ...
            supportSources, label, stateDimension);
        if available
            delta = normalizedAlignmentChange( ...
                refMean, candMean, anchor, positionScale);
            weight = protectedSupport(labelIdx) * existenceWeight;
            gain = gain + weight * max(delta, 0);
            harm = harm + weight * max(-delta, 0);
        end
    end
end
gain = reliability * gain;
harm = reliability * harm;
end

function delta = normalizedAlignmentChange( ...
        referenceMean, candidateMean, anchorMean, scale)
referenceDistance = sum((referenceMean(1:2) - anchorMean(1:2)).^2);
candidateDistance = sum((candidateMean(1:2) - anchorMean(1:2)).^2);
delta = (referenceDistance - candidateDistance) / max(scale^2, eps);
end

function [meanVector, available] = strongestSupportedMean( ...
        sources, label, stateDimension)
meanVector = zeros(stateDimension, 1);
available = false;
bestSupport = -inf;
for sourceIdx = 1:numel(sources)
    object = objectByLabel(sources{sourceIdx}, label);
    if isempty(object)
        continue;
    end
    support = clamp01(getField( ...
        object, 'detectionAssociationMass', 0));
    if support > bestSupport
        bestSupport = support;
        meanVector = objectMean(object, stateDimension);
        available = true;
    end
end
end

function evidence = sourceNovelEvidence( ...
        receiver, incumbent, source, labels)
baseline = max( ...
    supportByLabel(receiver, labels), ...
    supportByLabel(incumbent, labels));
sourceSupport = supportByLabel(source, labels);
sourceExistence = existenceByLabel(source, labels);
evidence = max(sourceSupport - baseline, 0) .* sourceExistence;
end

function mass = receiverFormationReferenceMass( ...
        control, groupIds, formationId)
details = control.referenceScore.retentionDetails;
values = details.expectedReferenceExistenceByReceiver;
mass = 0;
for receiverIdx = find(groupIds == formationId)
    mass = mass + sum(max(reshape(values{receiverIdx}, 1, []), 0));
end
if ~isfinite(mass) || mass <= eps
    error('TimeExpandedEffectiveKlaV87:InvalidReferenceMass', ...
        'The receiver formation reference mass is unavailable.');
end
end

function scale = resolvePositionScale(model)
scale = 100;
if isstruct(model) && isfield(model, 'ospaParameters') && ...
        isstruct(model.ospaParameters) && ...
        isfield(model.ospaParameters, 'eC') && ...
        isfinite(model.ospaParameters.eC) && model.ospaParameters.eC > 0
    scale = model.ospaParameters.eC;
end
end

function meanVector = objectMean(object, stateDimension)
weights = reshape(object.w, 1, []);
weights = max(weights, 0);
if isempty(weights) || sum(weights) <= eps
    weights = ones(1, numel(object.mu));
end
weights = weights / sum(weights);
meanVector = zeros(stateDimension, 1);
for componentIdx = 1:numel(weights)
    meanVector = meanVector + weights(componentIdx) * ...
        reshape(object.mu{componentIdx}, [], 1);
end
end

function labels = collectLabels(varargin)
labels = zeros(2, 0);
for inputIdx = 1:nargin
    objects = varargin{inputIdx};
    for objectIdx = 1:numel(objects)
        if objects(objectIdx).numberOfGmComponents <= 0
            continue;
        end
        label = [objects(objectIdx).birthTime; ...
            objects(objectIdx).birthLocation];
        if isempty(labels) || ...
                ~any(all(bsxfun(@eq, labels, label), 1))
            labels(:, end + 1) = label; %#ok<AGROW>
        end
    end
end
end

function values = existenceByLabel(objects, labels)
values = zeros(1, size(labels, 2));
for labelIdx = 1:size(labels, 2)
    object = objectByLabel(objects, labels(:, labelIdx));
    if ~isempty(object)
        values(labelIdx) = clamp01(object.r);
    end
end
end

function values = supportByLabel(objects, labels)
values = zeros(1, size(labels, 2));
for labelIdx = 1:size(labels, 2)
    object = objectByLabel(objects, labels(:, labelIdx));
    if ~isempty(object)
        values(labelIdx) = clamp01(getField( ...
            object, 'detectionAssociationMass', 0));
    end
end
end

function object = objectByLabel(objects, label)
object = [];
for objectIdx = 1:numel(objects)
    if objects(objectIdx).numberOfGmComponents > 0 && ...
            objects(objectIdx).birthTime == label(1) && ...
            objects(objectIdx).birthLocation == label(2)
        object = objects(objectIdx);
        return;
    end
end
end

function pass = rowWeightMultisetParity(first, second)
a = sort(first(first > 1e-12));
b = sort(second(second > 1e-12));
pass = numel(a) == numel(b) && all(abs(a - b) <= 1e-12);
end

function reliability = linkReliability(config, senderIdx, receiverIdx, time)
if isfield(config, 'pDropByEdge') && ~isempty(config.pDropByEdge)
    if ndims(config.pDropByEdge) >= 3
        timeIdx = min(time, size(config.pDropByEdge, 3));
        drop = config.pDropByEdge(senderIdx, receiverIdx, timeIdx);
    else
        drop = config.pDropByEdge(senderIdx, receiverIdx);
    end
else
    drop = getField(config, 'defaultDropProbability', 0);
end
reliability = 1 - clamp01(drop);
end

function value = finiteMax(values)
values = reshape(values, 1, []);
values = values(isfinite(values));
if isempty(values)
    value = 0;
else
    value = max(values);
end
end

function record = emptyPathRecord()
record = struct( ...
    'sourceIdx', NaN, ...
    'gatewayIdx', NaN, ...
    'receiverIdx', NaN, ...
    'receiverFormationId', NaN, ...
    'displacedDominantSenderIdx', NaN, ...
    'removedResidualSenderIdx', NaN, ...
    'firstHopReliability', NaN, ...
    'secondHopReliability', NaN, ...
    'pathReliability', NaN, ...
    'gatewayExistenceGainMass', NaN, ...
    'gatewayExistenceHarmMass', NaN, ...
    'downstreamExistenceGainFraction', NaN, ...
    'downstreamExistenceHarmFraction', NaN, ...
    'downstreamExistenceNetFraction', NaN, ...
    'existenceSurvivalRatio', NaN, ...
    'stateAlignmentGainFraction', NaN, ...
    'stateAlignmentHarmFraction', NaN, ...
    'stateAlignmentNetFraction', NaN, ...
    'upwardCrossingCount', NaN, ...
    'downwardCrossingCount', NaN, ...
    'harmSafe', false, ...
    'pathEnabled', false, ...
    'rankingScore', 0);
end

function value = clamp01(value)
if ~isscalar(value) || ~isfinite(value)
    value = 0;
end
value = min(max(value, 0), 1);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
