function [scores, details] = ...
    computeBackbonePreservingResidualTaskTeacherScores( ...
        context, receiverIndices, senderIndices, ...
        residualBaselineSources, options)
% COMPUTEBACKBONEPRESERVINGRESIDUALTASKTEACHERSCORES Privileged marginal.
%
% Each candidate replaces only the low-weight residual sender. The
% high-weight fixed-index sender remains in every candidate. Link delivery
% is marginalized exactly over the one or two distinct attempted sources
% used by that receiver.

if nargin < 5 || isempty(options)
    options = struct();
end
dominantWeight = getField(options, ...
    'dominantWeight', 0.70);
residualWeightGrid = reshape(getField(options, ...
    'residualWeightGrid', getField(options, ...
        'residualWeight', 0.05)), 1, []);
referenceMode = lower(strrep(char(getField( ...
    options, 'referenceMode', 'dominant-only')), '_', '-'));
referenceResidualWeight = getField(options, ...
    'referenceResidualWeight', residualWeightGrid(1));
requireNonnegativeReferenceAdvantage = logical(getField( ...
    options, 'requireNonnegativeReferenceAdvantage', false));
referenceGuardMode = lower(strrep(char(getField( ...
    options, 'referenceGuardMode', ...
    defaultReferenceGuardMode( ...
        requireNonnegativeReferenceAdvantage))), '_', '-'));
protectedReceiverCount = getField(options, ...
    'protectedReceiverCount', 1);
protectedReceiverFraction = getField(options, ...
    'protectedReceiverFraction', 0.10);
protectionRiskMetric = lower(strrep(char(getField( ...
    options, 'protectionRiskMetric', ...
    'objective-reference')), '_', '-'));
referenceAdvantageTolerance = getField(options, ...
    'referenceAdvantageTolerance', 1e-12);
if dominantWeight <= 0 || ...
        isempty(residualWeightGrid) || ...
        any(~isfinite(residualWeightGrid)) || ...
        any(residualWeightGrid <= 0) || ...
        any(dominantWeight + residualWeightGrid >= 1) || ...
        ~isscalar(referenceResidualWeight) || ...
        ~isfinite(referenceResidualWeight) || ...
        referenceResidualWeight <= 0 || ...
        dominantWeight + referenceResidualWeight >= 1 || ...
        ~isscalar(protectedReceiverCount) || ...
        ~isfinite(protectedReceiverCount) || ...
        protectedReceiverCount < 1 || ...
        mod(protectedReceiverCount, 1) ~= 0 || ...
        ~isscalar(protectedReceiverFraction) || ...
        ~isfinite(protectedReceiverFraction) || ...
        protectedReceiverFraction <= 0 || ...
        protectedReceiverFraction > 1 || ...
        ~isscalar(referenceAdvantageTolerance) || ...
        ~isfinite(referenceAdvantageTolerance) || ...
        referenceAdvantageTolerance < 0
    error('Residual teacher weights are invalid.');
end
if ~any(strcmp(referenceMode, ...
        {'dominant-only', 'matched-static-residual'}))
    error('Unknown residual teacher reference mode: %s.', ...
        referenceMode);
end
if ~any(strcmp(referenceGuardMode, ...
        {'none', 'all-receivers', ...
         'top-risk-receivers', 'top-risk-fraction'}))
    error('Unknown residual teacher reference guard: %s.', ...
        referenceGuardMode);
end
if ~any(strcmp(protectionRiskMetric, ...
        {'objective-reference', 'current-eospa'}))
    error('Unknown residual protection risk metric: %s.', ...
        protectionRiskMetric);
end
nodeCount = numel(context.localPosteriorBySensor);
receiverIndices = reshape(receiverIndices, [], 1);
senderIndices = reshape(senderIndices, [], 1);
residualBaselineSources = ...
    reshape(residualBaselineSources, 1, []);
if numel(receiverIndices) ~= numel(senderIndices) || ...
        numel(residualBaselineSources) ~= nodeCount
    error('Residual teacher action indices are misaligned.');
end
[~, dominantDetails] = ...
    selectRegisteredDirectedRoutingPolicy( ...
        context, 'fixed-index-star', ...
        struct('sourceWeight', dominantWeight));
dominantSources = reshape( ...
    dominantDetails.selectedSourcesByReceiver, 1, []);
riskOptions = getField(options, ...
    'riskOptions', struct());
riskOptions.horizonSteps = getField( ...
    options, 'horizonSteps', 0);
riskOptions.discountFactor = getField( ...
    options, 'discountFactor', 0.9);

baselineRisk = nan(1, nodeCount);
for receiverIdx = 1:nodeCount
    referenceResidualSource = NaN;
    if strcmp(referenceMode, 'matched-static-residual')
        referenceResidualSource = ...
            residualBaselineSources(receiverIdx);
    end
    baselineRisk(receiverIdx) = expectedReceiverRisk( ...
        context, receiverIdx, dominantSources(receiverIdx), ...
        referenceResidualSource, ...
        dominantWeight, referenceResidualWeight, ...
        riskOptions, 'task-surrogate');
end
protectionBaselineRisk = baselineRisk;
if strcmp(protectionRiskMetric, 'current-eospa')
    for receiverIdx = 1:nodeCount
        referenceResidualSource = NaN;
        if strcmp(referenceMode, ...
                'matched-static-residual')
            referenceResidualSource = ...
                residualBaselineSources(receiverIdx);
        end
        protectionBaselineRisk(receiverIdx) = ...
            expectedReceiverRisk( ...
                context, receiverIdx, ...
                dominantSources(receiverIdx), ...
                referenceResidualSource, ...
                dominantWeight, ...
                referenceResidualWeight, ...
                riskOptions, 'current-eospa');
    end
end
protectedReceiverMask = false(1, nodeCount);
switch referenceGuardMode
    case 'none'
        % No hard guard; scores remain the raw reference advantages.
    case 'all-receivers'
        protectedReceiverMask(:) = true;
    case 'top-risk-receivers'
        finiteReceivers = find(isfinite( ...
            protectionBaselineRisk));
        [~, riskOrder] = sort( ...
            protectionBaselineRisk( ...
                finiteReceivers), 'descend');
        protectedReceivers = finiteReceivers( ...
            riskOrder(1:min(protectedReceiverCount, ...
                numel(riskOrder))));
        protectedReceiverMask(protectedReceivers) = true;
    case 'top-risk-fraction'
        finiteReceivers = find(isfinite( ...
            protectionBaselineRisk));
        [~, riskOrder] = sort( ...
            protectionBaselineRisk( ...
                finiteReceivers), 'descend');
        tailCount = max(1, ceil( ...
            protectedReceiverFraction * ...
            numel(riskOrder)));
        protectedReceivers = finiteReceivers( ...
            riskOrder(1:tailCount));
        protectedReceiverMask(protectedReceivers) = true;
end
candidateRiskByWeight = nan( ...
    numel(receiverIndices), numel(residualWeightGrid));
protectionCandidateRiskByWeight = nan( ...
    size(candidateRiskByWeight));
rawScoreByWeight = -inf(size(candidateRiskByWeight));
protectionAdvantageByWeight = ...
    -inf(size(candidateRiskByWeight));
scores = -inf(numel(receiverIndices), 1);
for exampleIdx = 1:numel(receiverIndices)
    receiverIdx = receiverIndices(exampleIdx);
    for weightIdx = 1:numel(residualWeightGrid)
        candidateRiskByWeight(exampleIdx, weightIdx) = ...
            expectedReceiverRisk( ...
                context, receiverIdx, ...
                dominantSources(receiverIdx), ...
                senderIndices(exampleIdx), ...
                dominantWeight, ...
                residualWeightGrid(weightIdx), ...
                riskOptions, 'task-surrogate');
        if isfinite(candidateRiskByWeight( ...
                exampleIdx, weightIdx)) && ...
                isfinite(baselineRisk(receiverIdx))
            rawScoreByWeight(exampleIdx, weightIdx) = ...
                baselineRisk(receiverIdx) - ...
                    candidateRiskByWeight( ...
                        exampleIdx, weightIdx);
        end
        if protectedReceiverMask(receiverIdx)
            if strcmp(protectionRiskMetric, ...
                    'current-eospa')
                protectionCandidateRiskByWeight( ...
                    exampleIdx, weightIdx) = ...
                    expectedReceiverRisk( ...
                        context, receiverIdx, ...
                        dominantSources(receiverIdx), ...
                        senderIndices(exampleIdx), ...
                        dominantWeight, ...
                        residualWeightGrid(weightIdx), ...
                        riskOptions, 'current-eospa');
            else
                protectionCandidateRiskByWeight( ...
                    exampleIdx, weightIdx) = ...
                    candidateRiskByWeight( ...
                        exampleIdx, weightIdx);
            end
            if isfinite(protectionCandidateRiskByWeight( ...
                    exampleIdx, weightIdx)) && ...
                    isfinite(protectionBaselineRisk( ...
                        receiverIdx))
                protectionAdvantageByWeight( ...
                    exampleIdx, weightIdx) = ...
                    protectionBaselineRisk(receiverIdx) - ...
                    protectionCandidateRiskByWeight( ...
                        exampleIdx, weightIdx);
            end
        end
    end
end
referenceSafeWeightMask = ...
    protectionAdvantageByWeight >= ...
        -referenceAdvantageTolerance;
scoreByWeight = rawScoreByWeight;
guardedExampleMask = reshape( ...
    protectedReceiverMask(receiverIndices), [], 1);
guardedWeightMask = repmat( ...
    guardedExampleMask, 1, numel(residualWeightGrid));
if requireNonnegativeReferenceAdvantage
    scoreByWeight(guardedWeightMask & ...
        ~referenceSafeWeightMask) = -inf;
end
[scores, bestWeightIndices] = ...
    max(scoreByWeight, [], 2);
selectedResidualWeight = ...
    residualWeightGrid(bestWeightIndices);
selectedLinearIndices = sub2ind( ...
    size(candidateRiskByWeight), ...
    (1:numel(receiverIndices))', bestWeightIndices);

details = struct();
details.contractVersion = ...
    'backbone-preserving-residual-task-teacher-v3-tail-safe-reference';
details.receiverIndices = receiverIndices;
details.senderIndices = senderIndices;
details.dominantSourcesByReceiver = dominantSources;
details.residualBaselineSourcesByReceiver = ...
    residualBaselineSources;
details.dominantWeight = dominantWeight;
details.residualWeight = residualWeightGrid(1);
details.residualWeightGrid = residualWeightGrid;
details.referenceMode = referenceMode;
details.referenceResidualWeight = ...
    referenceResidualWeight;
details.requireNonnegativeReferenceAdvantage = ...
    requireNonnegativeReferenceAdvantage;
details.referenceGuardMode = referenceGuardMode;
details.protectedReceiverCount = ...
    protectedReceiverCount;
details.protectedReceiverFraction = ...
    protectedReceiverFraction;
details.protectionRiskMetric = ...
    protectionRiskMetric;
details.protectedReceiverMask = ...
    protectedReceiverMask;
details.protectedReceiverIndices = ...
    find(protectedReceiverMask);
details.guardedExampleMask = ...
    guardedExampleMask;
details.referenceAdvantageTolerance = ...
    referenceAdvantageTolerance;
details.selectedResidualWeightByExample = ...
    reshape(selectedResidualWeight, [], 1);
details.bestWeightIndexByExample = ...
    bestWeightIndices;
details.baselineExpectedRiskByReceiver = baselineRisk;
details.protectionBaselineRiskByReceiver = ...
    protectionBaselineRisk;
details.candidateExpectedRisk = ...
    candidateRiskByWeight(selectedLinearIndices);
details.candidateExpectedRiskByWeight = ...
    candidateRiskByWeight;
details.protectionCandidateRiskByWeight = ...
    protectionCandidateRiskByWeight;
details.rawReferenceAdvantageByWeight = ...
    rawScoreByWeight;
details.protectionReferenceAdvantageByWeight = ...
    protectionAdvantageByWeight;
details.referenceSafeWeightMask = ...
    referenceSafeWeightMask;
details.selectedReferenceAdvantageByExample = ...
    protectionAdvantageByWeight( ...
        selectedLinearIndices);
details.selectedReferenceSafeMask = ...
    isfinite(scores) & ...
    details.selectedReferenceAdvantageByExample >= ...
        -referenceAdvantageTolerance;
details.selectedReferenceGuardPassedMask = ...
    ~guardedExampleMask | ...
    details.selectedReferenceSafeMask;
details.residualScoresByWeight = scoreByWeight;
details.residualScores = scores;
details.truthUsed = true;
details.groundTruthUsed = true;
details.posteriorUsed = true;
details.currentLinkReliabilityUsed = true;
details.futureOutcomeUsed = false;
details.deployable = false;
end

function mode = defaultReferenceGuardMode(requireNonnegative)
if requireNonnegative
    mode = 'all-receivers';
else
    mode = 'none';
end
end

function risk = expectedReceiverRisk( ...
        context, receiverIdx, dominantSource, ...
        residualSource, dominantWeight, ...
        residualWeight, riskOptions, riskMetric)
selfWeight = 1 - dominantWeight - residualWeight;
if isfinite(residualSource)
    sources = [dominantSource, residualSource];
    weights = [dominantWeight, residualWeight];
else
    sources = dominantSource;
    weights = dominantWeight;
    selfWeight = 1 - dominantWeight;
end
if isfinite(residualSource) && dominantSource == residualSource
    uniqueSources = dominantSource;
    uniqueWeights = dominantWeight + residualWeight;
else
    uniqueSources = sources;
    uniqueWeights = weights;
end
reliability = zeros(1, numel(uniqueSources));
for sourceIdx = 1:numel(uniqueSources)
    reliability(sourceIdx) = 1 - edgeDrop( ...
        context.commConfig, uniqueSources(sourceIdx), ...
        receiverIdx, context.currentTime);
end

risk = 0;
for maskCode = 0:(2^numel(uniqueSources) - 1)
    delivered = logical(bitget( ...
        maskCode, 1:numel(uniqueSources)));
    probability = prod( ...
        reliability(delivered)) * prod( ...
        1 - reliability(~delivered));
    if probability <= 0
        continue;
    end
    if ~any(delivered)
        candidatePosterior = ...
            context.localPosteriorBySensor{receiverIdx};
    else
        selectedSources = uniqueSources(delivered);
        fusionInputs = [{ ...
            context.localPosteriorBySensor{receiverIdx}}, ...
            context.localPosteriorBySensor(selectedSources)];
        fusionWeights = [selfWeight, ...
            uniqueWeights(delivered)];
        fusionWeights = fusionWeights / sum(fusionWeights);
        fusionDetails = struct( ...
            'eventType', [0, 2 * ones( ...
                1, numel(selectedSources))]);
        candidatePosterior = fuseLmbPosteriorsByLabel( ...
            fusionInputs, fusionWeights, context.model, ...
            fusionWeights, fusionDetails, ...
            context.triggerConfig);
    end
    switch riskMetric
        case 'task-surrogate'
            outcomeRisk = ...
                evaluateLmbTopologyTaskRisk( ...
                    candidatePosterior, context.model, ...
                    context.currentTime, riskOptions);
        case 'current-eospa'
            outcomeRisk = ...
                evaluateLmbTopologyCurrentEospa( ...
                    candidatePosterior, context.model, ...
                    context.currentTime, ...
                    context.triggerConfig);
        otherwise
            error('Unknown expected receiver risk metric: %s.', ...
                riskMetric);
    end
    risk = risk + probability * outcomeRisk;
end
end

function probability = edgeDrop( ...
        config, senderIdx, receiverIdx, currentTime)
if isfield(config, 'pDropByEdge') && ...
        ~isempty(config.pDropByEdge)
    if ndims(config.pDropByEdge) >= 3
        timeIdx = min(currentTime, ...
            size(config.pDropByEdge, 3));
        probability = config.pDropByEdge( ...
            senderIdx, receiverIdx, timeIdx);
    else
        probability = config.pDropByEdge( ...
            senderIdx, receiverIdx);
    end
else
    probability = 0;
end
probability = min(max(probability, 0), 1);
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
