function examples = ...
    computeCvarResidualGraphPolicyExamples(context, options)
% COMPUTECVARRESIDUALGRAPHPOLICYEXAMPLES Truth-free relational features.
%
% Edge rows represent the exact message-count-preserving residual splice
% candidates used by the oracle teacher. A shared edge representation is
% emitted for every registered residual weight. Node rows are
% permutation-equivariant receiver/sender poolings of the reference-weight
% edge features. No target truth or future outcome is read.

if nargin < 2 || isempty(options)
    options = struct();
end
dominantWeight = getField(options, ...
    'dominantWeight', 0.70);
localResidualWeight = getField(options, ...
    'localResidualWeight', 0.05);
residualWeightGrid = reshape(getField(options, ...
    'residualWeightGrid', [0.05, 0.10, 0.20, 0.25]), 1, []);
featureContextMode = lower(strrep(char(getField( ...
    options, 'featureContextMode', 'raw')), '_', '-'));
if ~isscalar(dominantWeight) || ...
        ~isfinite(dominantWeight) || ...
        dominantWeight <= 0 || ...
        isempty(residualWeightGrid) || ...
        any(~isfinite(residualWeightGrid)) || ...
        any(residualWeightGrid <= 0) || ...
        any(dominantWeight + residualWeightGrid >= 1) || ...
        ~any(abs(residualWeightGrid - ...
            localResidualWeight) <= 1e-12)
    error('CVaR residual graph feature weights are invalid.');
end

[receiverIndices, senderIndices, candidateDetails] = ...
    enumerateBackboneResidualSpliceCandidates( ...
        context, struct( ...
            'dominantWeight', dominantWeight, ...
            'residualWeight', localResidualWeight));
nodeCount = candidateDetails.nodeCount;
candidateCount = numel(receiverIndices);
candidateKeys = candidateDetails.candidateEdgeKeys;
weightCount = numel(residualWeightGrid);
edgeFeatures = [];
edgeFeatureNames = {};
referenceEdgeFeatures = [];
referenceNodeEdgeFeatures = [];
referenceNodeReceivers = [];
referenceNodeSenders = [];
upstreamFeatureContractSha256 = cell(1, weightCount);
for weightIdx = 1:weightCount
    residualWeight = residualWeightGrid(weightIdx);
    featureOptions = struct( ...
        'featureContextMode', featureContextMode);
    [allFeatures, currentNames, allReceivers, ...
        allSenders, currentMetadata] = ...
            computeRollingSafeDirectedActionExamples( ...
                context, residualWeight, featureOptions);
    if currentMetadata.truthUsed || ...
            currentMetadata.groundTruthUsed || ...
            currentMetadata.futureOutcomeUsed
        error('Upstream residual graph features used privileged data.');
    end
    upstreamFeatureContractSha256{weightIdx} = ...
        currentMetadata.featureContractSha256;
    allKeys = allReceivers + nodeCount * (allSenders - 1);
    [present, rowIndices] = ismember(candidateKeys, allKeys);
    if any(~present) || ...
            numel(unique(rowIndices)) ~= candidateCount
        error(['Truth-free features do not cover the exact residual ', ...
            'splice candidate set.']);
    end
    currentFeatures = allFeatures(rowIndices, :);
    referenceSenderFlag = double( ...
        senderIndices == reshape( ...
            candidateDetails. ...
                residualBaselineSourcesByReceiver( ...
                    receiverIndices), [], 1));
    actionFeatures = [ ...
        dominantWeight * ones(candidateCount, 1), ...
        localResidualWeight * ones(candidateCount, 1), ...
        (1 - dominantWeight - residualWeight) * ...
            ones(candidateCount, 1), ...
        referenceSenderFlag, ...
        double(abs(residualWeight - ...
            localResidualWeight) <= 1e-12) * ...
            ones(candidateCount, 1)];
    currentFeatures = [currentFeatures, actionFeatures];
    currentNames = [reshape(currentNames, 1, []), { ...
        'dominant_weight', ...
        'local_residual_weight', ...
        'candidate_self_weight', ...
        'reference_residual_sender', ...
        'reference_residual_weight'}];
    if isempty(edgeFeatures)
        edgeFeatures = nan(candidateCount, ...
            weightCount, size(currentFeatures, 2));
        edgeFeatureNames = currentNames;
    elseif ~isequal(edgeFeatureNames, currentNames)
        error('CVaR residual edge feature names changed across weights.');
    end
    edgeFeatures(:, weightIdx, :) = currentFeatures;
    if abs(residualWeight - localResidualWeight) <= 1e-12
        referenceEdgeFeatures = currentFeatures;
        referenceMetadata = currentMetadata;
        referenceNodeEdgeFeatures = [allFeatures, [ ...
            dominantWeight * ones(size(allFeatures, 1), 1), ...
            localResidualWeight * ones(size(allFeatures, 1), 1), ...
            (1 - dominantWeight - residualWeight) * ...
                ones(size(allFeatures, 1), 1), ...
            double(allSenders == reshape( ...
                candidateDetails. ...
                    residualBaselineSourcesByReceiver( ...
                        allReceivers), [], 1)), ...
            ones(size(allFeatures, 1), 1)]];
        referenceNodeReceivers = allReceivers;
        referenceNodeSenders = allSenders;
    end
end
if isempty(referenceEdgeFeatures) || ...
        any(~isfinite(edgeFeatures(:)))
    error('CVaR residual graph edge features are incomplete.');
end

[nodeFeatures, nodeFeatureNames] = poolNodeFeatures( ...
    referenceNodeEdgeFeatures, edgeFeatureNames, ...
    referenceNodeReceivers, referenceNodeSenders, nodeCount, ...
    candidateDetails.groupIds);
[updateFeatures, updateFeatureNames] = ...
    buildUpdateDiagnosticNodeFeatures(context, nodeCount);
nodeFeatures = [nodeFeatures, updateFeatures];
nodeFeatureNames = [nodeFeatureNames, updateFeatureNames];
if any(~isfinite(nodeFeatures(:)))
    error('CVaR residual graph node features contain non-finite values.');
end

examples = struct();
examples.contractVersion = ...
    'cvar-residual-relational-features-v2-update-diagnostics';
examples.edgeFeatures = edgeFeatures;
examples.edgeFeatureNames = edgeFeatureNames;
examples.nodeFeatures = nodeFeatures;
examples.nodeFeatureNames = nodeFeatureNames;
examples.receiverIndices = receiverIndices;
examples.senderIndices = senderIndices;
examples.candidateEdgeKeys = candidateKeys;
examples.residualWeightGrid = residualWeightGrid;
examples.referenceResidualWeight = localResidualWeight;
examples.dominantWeight = dominantWeight;
examples.residualBaselineSourcesByReceiver = ...
    candidateDetails.residualBaselineSourcesByReceiver;
examples.dominantSourcesByReceiver = ...
    candidateDetails.dominantSourcesByReceiver;
examples.groupIds = candidateDetails.groupIds;
examples.physicalAdjacency = ...
    candidateDetails.physicalAdjacency;
examples.featureContextMode = featureContextMode;
examples.referenceEdgeFeatureMetadata = ...
    referenceMetadata;
examples.upstreamFeatureContractSha256 = ...
    upstreamFeatureContractSha256;
examples.nodeCount = nodeCount;
examples.candidateCount = candidateCount;
examples.weightCount = weightCount;
examples.truthUsed = false;
examples.groundTruthUsed = false;
examples.futureOutcomeUsed = false;
examples.posteriorUsed = true;
examples.currentLinkReliabilityUsed = true;
examples.historyUsed = true;
examples.updateDiagnosticsUsed = true;
examples.featureContractSha256 = computeTextSha256(sprintf( ...
    '%s|%s|%s|%s|%.17g|%.17g|%s|%s', ...
    examples.contractVersion, featureContextMode, ...
    strjoin(edgeFeatureNames, char(31)), ...
    strjoin(nodeFeatureNames, char(31)), ...
    dominantWeight, localResidualWeight, ...
    mat2str(residualWeightGrid, 17), ...
    strjoin(upstreamFeatureContractSha256, char(31))));
end

function [features, names] = ...
        buildUpdateDiagnosticNodeFeatures(context, nodeCount)
innovation = validateHistory(context, ...
    'localInnovationHistory', nodeCount, 0);
association = validateHistory(context, ...
    'localAssociationConfidenceHistory', nodeCount, 1);
nisNorm = validateHistory(context, ...
    'localNisNormHistory', nodeCount, NaN);
nisDeviation = validateHistory(context, ...
    'localNisDeviationHistory', nodeCount, NaN);
innovation = min(max(innovation, 0), 1);
association = min(max(association, 0), 1);
nisAvailable = isfinite(nisNorm);
nisNorm(~nisAvailable) = 0;
nisDeviation(~isfinite(nisDeviation)) = 0;
nisNorm = log1p(max(nisNorm, 0));
nisDeviation = log1p(max(nisDeviation, 0));
features = [ ...
    innovation(:, end), ...
    mean(innovation, 2), ...
    max(innovation, [], 2), ...
    innovation(:, end) - innovation(:, 1), ...
    association(:, end), ...
    mean(association, 2), ...
    min(association, [], 2), ...
    association(:, end) - association(:, 1), ...
    nisNorm(:, end), ...
    mean(nisNorm, 2), ...
    max(nisNorm, [], 2), ...
    nisNorm(:, end) - nisNorm(:, 1), ...
    nisDeviation(:, end), ...
    mean(nisDeviation, 2), ...
    max(nisDeviation, [], 2), ...
    mean(nisAvailable, 2)];
names = { ...
    'update_innovation_current', ...
    'update_innovation_mean', ...
    'update_innovation_max', ...
    'update_innovation_trend', ...
    'update_association_current', ...
    'update_association_mean', ...
    'update_association_min', ...
    'update_association_trend', ...
    'update_log_nis_norm_current', ...
    'update_log_nis_norm_mean', ...
    'update_log_nis_norm_max', ...
    'update_log_nis_norm_trend', ...
    'update_log_nis_deviation_current', ...
    'update_log_nis_deviation_mean', ...
    'update_log_nis_deviation_max', ...
    'update_nis_available_fraction'};
end

function history = validateHistory( ...
        context, fieldName, nodeCount, defaultValue)
if ~isfield(context, fieldName) || ...
        isempty(context.(fieldName))
    history = defaultValue * ones(nodeCount, 1);
    return;
end
history = context.(fieldName);
if size(history, 1) ~= nodeCount || ...
        ndims(history) ~= 2
    error('CVaR graph update diagnostic history is invalid.');
end
end

function [nodeFeatures, nodeFeatureNames] = poolNodeFeatures( ...
        edgeFeatures, edgeFeatureNames, receiverIndices, ...
        senderIndices, nodeCount, groupIds)
featureCount = size(edgeFeatures, 2);
nodeFeatures = zeros(nodeCount, 4 * featureCount + 3);
for nodeIdx = 1:nodeCount
    receiverRows = receiverIndices == nodeIdx;
    senderRows = senderIndices == nodeIdx;
    receiverValues = zeros(1, featureCount);
    senderValues = zeros(1, featureCount);
    receiverMax = zeros(1, featureCount);
    senderMax = zeros(1, featureCount);
    if any(receiverRows)
        receiverValues = mean(edgeFeatures(receiverRows, :), 1);
        receiverMax = max(edgeFeatures(receiverRows, :), [], 1);
    end
    if any(senderRows)
        senderValues = mean(edgeFeatures(senderRows, :), 1);
        senderMax = max(edgeFeatures(senderRows, :), [], 1);
    end
    nodeFeatures(nodeIdx, :) = [ ...
        receiverValues, receiverMax, ...
        senderValues, senderMax, ...
        mean(receiverRows), ...
        mean(senderRows), ...
        mean(groupIds == groupIds(nodeIdx))];
end
nodeFeatureNames = cell(1, size(nodeFeatures, 2));
cursor = 0;
prefixes = { ...
    'receiver_mean_', 'receiver_max_', ...
    'sender_mean_', 'sender_max_'};
for prefixIdx = 1:numel(prefixes)
    for featureIdx = 1:numel(edgeFeatureNames)
        cursor = cursor + 1;
        nodeFeatureNames{cursor} = [ ...
            prefixes{prefixIdx}, edgeFeatureNames{featureIdx}];
    end
end
nodeFeatureNames((cursor + 1):(cursor + 3)) = { ...
    'receiver_candidate_fraction', ...
    'sender_candidate_fraction', ...
    'formation_size_fraction'};
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
