function [values, names, details] = ...
        computeObservableOneHopLabelActionFeatures( ...
            receiverObject, sourceObject, peerSourceObjects, model, ...
            receiverIdx, sourceIdx, currentTime, context)
% COMPUTEOBSERVABLEONEHOPLABELACTIONFEATURES Truth-free transfer features.
%
% A row describes one receiver--source--label action. Numeric label keys,
% target truth, future measurements, and alternative-arm outcomes are not
% features. Peer objects are current physical-neighbor posteriors carrying
% the same label; their order has no effect on the returned aggregates.

if nargin < 8 || isempty(context)
    context = struct();
end
base = computeObservableLmbLabelTransferFeatures( ...
    receiverObject, sourceObject, model, receiverIdx, sourceIdx, ...
    currentTime);
peerSourceObjects = reshape(peerSourceObjects, 1, []);
peerCompatibility = zeros(1, 0);
peerRisk = zeros(1, 0);
for peer = peerSourceObjects
    if peer.birthTime == sourceObject.birthTime && ...
            peer.birthLocation == sourceObject.birthLocation && ...
            peer.numberOfGmComponents > 0
        peerRisk(end + 1) = ...
            computeObservableLmbLabelBayesRisk(peer, model); %#ok<AGROW>
        if ~sameObjectState(peer, sourceObject)
            distance = positionMahalanobis(peer, sourceObject);
            peerCompatibility(end + 1) = ...
                exp(-0.5 * min(distance, 100)); %#ok<AGROW>
        end
    end
end
if isempty(peerCompatibility)
    consensusMean = 0;
    consensusMedian = 0;
    consensusMaximum = 0;
    support95 = 0;
    support99 = 0;
else
    consensusMean = mean(peerCompatibility);
    consensusMedian = median(peerCompatibility);
    consensusMaximum = max(peerCompatibility);
    support95 = mean(peerCompatibility >= exp(-0.5 * 5.991));
    support99 = mean(peerCompatibility >= exp(-0.5 * 9.210));
end
sourceRisk = base.sourceBayesRisk;
if isempty(peerRisk)
    lowRiskPercentile = 0;
else
    lowRiskPercentile = mean(peerRisk >= sourceRisk - 1e-12);
end
positionCutoff = resolvePositionCutoff(model);
receiverTrace = base.receiverPositionTrace / positionCutoff^2;
sourceTrace = base.sourcePositionTrace / positionCutoff^2;
spatialCredibility = max(base.compatibility, consensusMean);
sameFormation = double(getField(context, ...
    'receiverFormation', NaN) == getField(context, ...
    'sourceFormation', NaN));
nodeCount = max(getField(context, 'nodeCount', 1), 1);
neighborCount = max(getField(context, 'physicalNeighborCount', 0), 0);
receiverActive = max(getField(context, ...
    'receiverActiveLabelCount', 0), 0);
sourceActive = max(getField(context, 'sourceActiveLabelCount', 0), 0);
formationSize = max(getField(context, 'formationSize', 1), 1);
labelAge = max(currentTime - sourceObject.birthTime, 0) / ...
    max(currentTime, 1);
traceRatio = log((sourceTrace + 1e-12) / ...
    (receiverTrace + 1e-12));

names = { ...
    'receiver_present', ...
    'receiver_existence', ...
    'source_existence', ...
    'receiver_bayes_risk', ...
    'source_bayes_risk', ...
    'risk_reduction', ...
    'receiver_position_trace_normalized', ...
    'source_position_trace_normalized', ...
    'receiver_evidence_quality', ...
    'source_evidence_quality', ...
    'receiver_observation_opportunity', ...
    'source_observation_opportunity', ...
    'existence_gain', ...
    'precision_gain', ...
    'evidence_gap', ...
    'opportunity_gap', ...
    'log_mahalanobis_disagreement', ...
    'receiver_source_compatibility', ...
    'source_quality', ...
    'confidence_disagreement_score', ...
    'handover_rescue_score', ...
    'log_payload_kib', ...
    'peer_count_fraction', ...
    'peer_consensus_mean', ...
    'peer_consensus_median', ...
    'peer_consensus_maximum', ...
    'peer_support_chi2_95', ...
    'peer_support_chi2_99', ...
    'source_low_risk_percentile', ...
    'spatial_credibility', ...
    'same_formation', ...
    'label_age_fraction', ...
    'physical_degree_fraction', ...
    'receiver_active_label_fraction', ...
    'source_active_label_fraction', ...
    'formation_size_fraction', ...
    'log_source_receiver_trace_ratio'};
values = [ ...
    double(base.receiverPresent), ...
    base.receiverExistence, ...
    base.sourceExistence, ...
    base.receiverBayesRisk, ...
    base.sourceBayesRisk, ...
    base.riskReductionScore, ...
    receiverTrace, ...
    sourceTrace, ...
    base.receiverEvidenceQuality, ...
    base.sourceEvidenceQuality, ...
    base.receiverObservationOpportunity, ...
    base.sourceObservationOpportunity, ...
    base.existenceGain, ...
    base.precisionGain, ...
    base.evidenceGap, ...
    base.opportunityGap, ...
    log1p(base.mahalanobisDisagreement), ...
    base.compatibility, ...
    base.sourceQuality, ...
    base.confidenceDisagreementScore, ...
    base.handoverRescueScore, ...
    log1p(base.payloadBytes / 1024), ...
    numel(peerSourceObjects) / nodeCount, ...
    consensusMean, ...
    consensusMedian, ...
    consensusMaximum, ...
    support95, ...
    support99, ...
    lowRiskPercentile, ...
    spatialCredibility, ...
    sameFormation, ...
    labelAge, ...
    neighborCount / max(nodeCount - 1, 1), ...
    receiverActive / nodeCount, ...
    sourceActive / nodeCount, ...
    formationSize / nodeCount, ...
    traceRatio];
if any(~isfinite(values)) || numel(values) ~= numel(names)
    error('ObservableOneHopActionFeatures:InvalidValues', ...
        'The one-hop action feature row is invalid.');
end
details = struct();
details.contractVersion = ...
    'observable-one-hop-label-action-features-v1';
details.peerObjectCount = numel(peerSourceObjects);
details.payloadBytes = base.payloadBytes;
details.truthUsed = false;
details.futureInformationUsed = false;
details.numericLabelIdentifiersUsedAsFeatures = false;
end

function value = sameObjectState(left, right)
value = left.birthTime == right.birthTime && ...
    left.birthLocation == right.birthLocation && ...
    abs(left.r - right.r) <= 1e-14 && ...
    left.numberOfGmComponents == right.numberOfGmComponents;
if value && left.numberOfGmComponents > 0
    value = max(abs(left.mu{1}(:) - right.mu{1}(:))) <= 1e-14;
end
end

function value = positionMahalanobis(left, right)
[leftMean, leftCovariance] = momentMatch(left);
[rightMean, rightCovariance] = momentMatch(right);
dimension = min([2, numel(leftMean), numel(rightMean)]);
delta = leftMean(1:dimension) - rightMean(1:dimension);
covariance = leftCovariance(1:dimension, 1:dimension) + ...
    rightCovariance(1:dimension, 1:dimension);
covariance = regularizeCovariance(covariance);
value = max(real(delta' * (covariance \ delta)), 0);
if ~isfinite(value)
    value = 1e6;
end
end

function [meanVector, covariance] = momentMatch(object)
componentCount = object.numberOfGmComponents;
weights = reshape(object.w, 1, []);
weights(~isfinite(weights)) = 0;
weights = max(weights, 0);
if numel(weights) ~= componentCount || sum(weights) <= 0
    weights = ones(1, componentCount);
end
weights = weights / sum(weights);
stateDimension = numel(object.mu{1});
meanVector = zeros(stateDimension, 1);
for idx = 1:componentCount
    meanVector = meanVector + weights(idx) * object.mu{idx};
end
covariance = zeros(stateDimension);
for idx = 1:componentCount
    delta = object.mu{idx} - meanVector;
    covariance = covariance + weights(idx) * ...
        (object.Sigma{idx} + delta * delta');
end
covariance = regularizeCovariance(covariance);
end

function covariance = regularizeCovariance(covariance)
covariance = (covariance + covariance') / 2;
jitter = 0;
for attempt = 1:8
    [~, flag] = chol(covariance + jitter * eye(size(covariance)));
    if flag == 0
        covariance = covariance + jitter * eye(size(covariance));
        return;
    end
    jitter = max(1e-12, 10 * max(jitter, 1e-12));
end
error('ObservableOneHopActionFeatures:InvalidCovariance', ...
    'A candidate covariance cannot be regularized.');
end

function value = resolvePositionCutoff(model)
value = NaN;
if isfield(model, 'ospaParameters') && ...
        isstruct(model.ospaParameters) && ...
        isfield(model.ospaParameters, 'eC')
    value = model.ospaParameters.eC;
end
if ~isscalar(value) || ~isfinite(value) || value <= 0
    error('ObservableOneHopActionFeatures:MissingCutoff', ...
        'A positive E-OSPA position cutoff is required.');
end
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
