function fingerprint = ...
    computeFormationB4V46TrackingInputFingerprint(inputs, identity, ...
        deliveryMetadata, caseContract, registry)
% COMPUTEFORMATIONB4V46TRACKINGINPUTFINGERPRINT Bind one source object.

requiredInputs = {'seed', 'config', 'model', 'measurements', ...
    'groundTruth', 'groundTruthRfs', 'sensorTrajectories', ...
    'targetTrajectories', 'neighborMap', 'commConfig', 'graphData', ...
    'linkMetadata', 'validation'};
if ~isstruct(inputs) || ~isscalar(inputs) || ...
        ~isequal(sort(fieldnames(inputs)), sort(requiredInputs(:))) || ...
        ~isstruct(identity) || ~isscalar(identity) || ...
        ~isfield(identity, 'canonicalSha256') || ...
        ~isstruct(deliveryMetadata) || ~isscalar(deliveryMetadata) || ...
        ~isfield(deliveryMetadata, 'canonicalSha256') || ...
        ~isstruct(caseContract) || ~isscalar(caseContract) || ...
        ~isstruct(registry) || ~isscalar(registry) || ...
        ~isfield(registry, 'canonicalSha256')
    error('FormationB4V46TrackingSource:MalformedInput', ...
        'The source input fingerprint boundary is malformed.');
end
officialRegistry = getFormationB4V46TrackingSourceRegistry();
validateOwnership(inputs, caseContract, registry, officialRegistry);
validateIdentityAndDelivery(inputs, identity, deliveryMetadata);
validateRegisteredIdentityAndDelivery( ...
    inputs, identity, deliveryMetadata, caseContract);

payload = struct();
payload.contractVersion = ...
    'formation-b4-v46-tracking-source-input-fingerprint-v1';
payload.seed = inputs.seed;
payload.registryId = registry.id;
payload.registryCanonicalSha256 = registry.canonicalSha256;
payload.caseId = caseContract.id;
payload.caseOrdinal = caseContract.ordinal;
payload.caseCanonicalSha256 = caseContract.caseCanonicalSha256;
payload.seedRole = caseContract.seedRole;
payload.primaryMatrix = caseContract.primaryMatrix;
payload.stressMatrix = caseContract.stressMatrix;
payload.configSha256 = computeCanonicalValueSha256(inputs.config);
payload.modelSha256 = computeCanonicalValueSha256(inputs.model);
payload.measurementsSha256 = ...
    computeCanonicalValueSha256(inputs.measurements);
payload.groundTruthSha256 = ...
    computeCanonicalValueSha256(inputs.groundTruth);
payload.groundTruthRfsSha256 = ...
    computeCanonicalValueSha256(inputs.groundTruthRfs);
payload.sensorTrajectoriesSha256 = ...
    computeCanonicalValueSha256(inputs.sensorTrajectories);
payload.targetTrajectoriesSha256 = ...
    computeCanonicalValueSha256(inputs.targetTrajectories);
payload.neighborMapSha256 = ...
    computeCanonicalValueSha256(inputs.neighborMap);
payload.communicationConfigSha256 = ...
    computeCanonicalValueSha256(inputs.commConfig);
payload.graphDataSha256 = computeCanonicalValueSha256(inputs.graphData);
payload.linkMetadataSha256 = ...
    computeCanonicalValueSha256(inputs.linkMetadata);
payload.validationSha256 = ...
    computeCanonicalValueSha256(inputs.validation);
payload.physicalIdentityRegistrySha256 = identity.canonicalSha256;
payload.deliveryUniformMetadataSha256 = ...
    deliveryMetadata.canonicalSha256;
payload.deliveryUniformCanonicalTensorSha256 = ...
    deliveryMetadata.canonicalTensorSha256;
payload.deliveryUniformMaterializedTensorSha256 = ...
    deliveryMetadata.materializedTensorSha256;
fingerprint = payload;
fingerprint.canonicalSha256 = ...
    computeCanonicalValueSha256(payload);
end

function validateOwnership(inputs, caseContract, registry, officialRegistry)
matching = strcmp({registry.cases.id}, caseContract.id) & ...
    [registry.cases.ordinal] == caseContract.ordinal;
officialMatching = strcmp({officialRegistry.cases.id}, caseContract.id) & ...
    [officialRegistry.cases.ordinal] == caseContract.ordinal;
if ~isequaln(registry, officialRegistry) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(registry, 'canonicalSha256')), ...
            registry.canonicalSha256)
    error('FormationB4V46TrackingSource:RegistryAuthorityDrift', ...
        'The caller did not supply the frozen official registry.');
end
if nnz(matching) ~= 1 || nnz(officialMatching) ~= 1 || ...
        ~isequaln(registry.cases(matching), caseContract) || ...
        ~isequaln(officialRegistry.cases(officialMatching), caseContract) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(caseContract, 'caseCanonicalSha256')), ...
            caseContract.caseCanonicalSha256) || ...
        inputs.seed ~= caseContract.seed || ...
        ~strcmp(inputs.config.presetName, caseContract.presetName) || ...
        ~strcmp(computeCanonicalValueSha256(inputs.config), ...
            caseContract.configSnapshotSha256)
    error('FormationB4V46TrackingSource:OwnershipDrift', ...
        'The source input is not owned by the registered case.');
end
end

function validateRegisteredIdentityAndDelivery( ...
        inputs, identity, metadata, caseContract)
expectedIdentity = ...
    buildDynamicTopologyPhysicalIdentityRegistry(inputs.config);
[expectedUniforms, expectedMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        caseContract.deliverySeed, expectedIdentity.sensorPhysicalUids, ...
        caseContract.simulationLength);
if ~isequaln(identity, expectedIdentity) || ...
        ~isequaln(metadata, expectedMetadata) || ...
        ~isequaln(inputs.commConfig.linkUniforms, expectedUniforms)
    error('FormationB4V46TrackingSource:DeliveryMetadataDrift', ...
        ['The physical identity or delivery object is not the exact ', ...
         'registered deterministic materialization.']);
end
end

function validateIdentityAndDelivery(inputs, identity, metadata)
if ~strcmp(computeCanonicalValueSha256( ...
            rmfield(identity, 'canonicalSha256')), ...
        identity.canonicalSha256) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(metadata, 'canonicalSha256')), ...
        metadata.canonicalSha256) || ...
        ~isequal(metadata.materializedSensorPhysicalUidOrder, ...
            identity.sensorPhysicalUids) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            inputs.commConfig.linkUniforms), ...
            metadata.materializedTensorSha256)
    error('FormationB4V46TrackingSource:DeliveryMetadataDrift', ...
        'The identity or materialized delivery metadata is inconsistent.');
end
canonicalOrder = metadata.materializedIndexByCanonicalIndex;
canonicalTensor = inputs.commConfig.linkUniforms( ...
    canonicalOrder, canonicalOrder, :);
if ~strcmp(computeCanonicalValueSha256(canonicalTensor), ...
        metadata.canonicalTensorSha256)
    error('FormationB4V46TrackingSource:DeliveryMetadataDrift', ...
        'The canonical physical-UID delivery tensor is inconsistent.');
end
end
