function graph = computeTrackingAlignedFormationGraphFeatures( ...
        context, bank, groupIds)
% COMPUTETRACKINGALIGNEDFORMATIONGRAPHFEATURES V56 graph inputs.
%
% Builds a formation-level graph and a formation-by-mode feature tensor from
% current observable LMB, geometry, link, and route-history information.  It
% deliberately preserves graph structure instead of pooling a complete
% candidate topology into one row.  Truth, future measurements, future link
% draws, seed IDs, physical sensor IDs, and numeric formation IDs are not
% emitted.

requiredBank = { ...
    'nodeCount', 'formationCount', 'modeCount', 'actionCount', ...
    'referenceActionIndex', 'modeTrustWeights', ...
    'actionFormationIndex', 'actionModeIndex', ...
    'actionAdjacency', 'actionFusionWeights', ...
    'actionDominantSources', 'actionPosteriorProxyAllowed', ...
    'actionPosteriorObjective', 'actionPayloadBytes', ...
    'referencePayloadBytes', 'truthUsed', 'futureOutcomeUsed'};
if ~isstruct(context) || ~isstruct(bank) || ...
        ~all(isfield(bank, requiredBank)) || ...
        bank.truthUsed || bank.futureOutcomeUsed
    error('Tracking-aligned formation-graph input is incomplete.');
end
groupIds = reshape(groupIds, 1, []);
nodeCount = numel(groupIds);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
modeCount = round(bank.modeCount);
if nodeCount ~= bank.nodeCount || ...
        formationCount ~= bank.formationCount || ...
        modeCount < 2 || bank.referenceActionIndex ~= 1 || ...
        ~isequal(size(bank.actionAdjacency), ...
            [nodeCount, nodeCount, bank.actionCount]) || ...
        ~isequal(size(bank.actionFusionWeights), ...
            [nodeCount, nodeCount, bank.actionCount]) || ...
        ~isequal(size(bank.actionDominantSources), ...
            [bank.actionCount, nodeCount]) || ...
        numel(bank.modeTrustWeights) ~= modeCount
    error('Tracking-aligned formation-graph dimensions are invalid.');
end
assertObservableContext(context, nodeCount, groupIds);

[rawEdge, rawEdgeNames, nodeSummary] = ...
    computeDirectedRoutingFeatures(context);
physical = logical(context.physicalAdjacency);
physical(1:nodeCount+1:end) = false;
previous = logical(context.previousAdjacency);
previous(1:nodeCount+1:end) = false;
referenceAdjacency = logical(bank.actionAdjacency(:, :, 1));
referenceAdjacency(1:nodeCount+1:end) = false;
referenceWeights = bank.actionFusionWeights(:, :, 1);
referenceSources = reshape(bank.actionDominantSources(1, :), 1, []);
targetCapacity = max(resolveTargetCapacity(context, nodeSummary), 1);

[nodeFeatures, nodeFeatureNames] = buildNodeFeatures( ...
    nodeSummary, groups, groupIds, physical, previous, ...
    referenceAdjacency, targetCapacity);
[edgeFeatures, edgeFeatureNames, edgeAvailableMask] = ...
    buildEdgeFeatures(rawEdge, rawEdgeNames, groups, groupIds, ...
        physical, previous, referenceAdjacency);
[modeFeatures, modeFeatureNames, modeActionIndex, ...
    modePresentMask, modeWithinReferencePayloadMask] = ...
    buildModeFeatures(bank, groups, groupIds, rawEdge, ...
        rawEdgeNames, physical, previous, referenceAdjacency, ...
        referenceWeights, referenceSources);

if any(~isfinite(nodeFeatures(:))) || ...
        any(~isfinite(edgeFeatures(:))) || ...
        any(~isfinite(modeFeatures(:)))
    error('Tracking-aligned formation-graph features are non-finite.');
end

graph = struct();
graph.contractVersion = ...
    'tracking-aligned-formation-graph-features-v56-v1';
graph.nodeFeatures = nodeFeatures;
graph.nodeFeatureNames = nodeFeatureNames;
graph.edgeFeatures = edgeFeatures;
graph.edgeFeatureNames = edgeFeatureNames;
graph.edgeAvailableMask = edgeAvailableMask;
graph.modeFeatures = modeFeatures;
graph.modeFeatureNames = modeFeatureNames;
graph.modeActionIndex = modeActionIndex;
graph.modePresentMask = modePresentMask;
graph.modeWithinReferencePayloadMask = ...
    modeWithinReferencePayloadMask;
graph.formationCount = formationCount;
graph.modeCount = modeCount;
graph.nodeCount = nodeCount;
graph.targetCapacity = targetCapacity;
graph.sensorPermutationInvariant = true;
graph.formationLabelPermutationEquivariant = true;
graph.scaleNormalized = true;
graph.truthUsed = false;
graph.futureMeasurementsUsed = false;
graph.futureOutcomeUsed = false;
graph.futureLinkDrawUsed = false;
graph.seedIdentifierUsed = false;
graph.sensorIdentifierUsed = false;
graph.formationIdentifierUsed = false;
end

function [features, names] = buildNodeFeatures( ...
        summaries, groups, groupIds, physical, previous, ...
        reference, targetCapacity)
names = { ...
    'bias', 'log_node_count', 'log_formation_count', ...
    'formation_size_fraction', ...
    'expected_cardinality_fraction_mean', ...
    'expected_cardinality_fraction_max', ...
    'cardinality_variance_fraction_mean', ...
    'cardinality_variance_fraction_max', ...
    'position_variance_mean', 'position_variance_max', ...
    'association_confidence_mean', 'association_confidence_min', ...
    'detection_mass_mean', 'detection_mass_max', ...
    'active_label_fraction_mean', 'active_label_fraction_max', ...
    'quality_mean', 'quality_min', 'need_mean', 'need_max', ...
    'physical_in_degree_fraction_mean', ...
    'physical_in_degree_fraction_min', ...
    'reference_cross_source_fraction', ...
    'reference_previous_overlap'};
formationCount = numel(groups);
nodeCount = numel(groupIds);
features = zeros(formationCount, numel(names));
for formationIdx = 1:formationCount
    members = reshape(find(groupIds == groups(formationIdx)), 1, []);
    summaryMatrix = nodeSummaryMatrix( ...
        summaries(members), targetCapacity);
    physicalDegree = sum(physical(members, :), 2) / ...
        max(nodeCount - 1, 1);
    referenceRows = reference(members, :);
    previousRows = previous(members, :);
    crossMask = bsxfun(@ne, ...
        groupIds(members)', groupIds);
    referenceCount = nnz(referenceRows);
    features(formationIdx, :) = [ ...
        1, log1p(nodeCount), log1p(formationCount), ...
        numel(members) / nodeCount, ...
        mean(summaryMatrix(:, 1)), max(summaryMatrix(:, 1)), ...
        mean(summaryMatrix(:, 2)), max(summaryMatrix(:, 2)), ...
        mean(summaryMatrix(:, 3)), max(summaryMatrix(:, 3)), ...
        mean(summaryMatrix(:, 4)), min(summaryMatrix(:, 4)), ...
        mean(summaryMatrix(:, 5)), max(summaryMatrix(:, 5)), ...
        mean(summaryMatrix(:, 6)), max(summaryMatrix(:, 6)), ...
        mean(summaryMatrix(:, 7)), min(summaryMatrix(:, 7)), ...
        mean(summaryMatrix(:, 8)), max(summaryMatrix(:, 8)), ...
        mean(physicalDegree), min(physicalDegree), ...
        nnz(referenceRows & crossMask) / max(referenceCount, 1), ...
        overlapFraction(referenceRows, previousRows)];
end
end

function matrix = nodeSummaryMatrix(summaries, targetCapacity)
matrix = zeros(numel(summaries), 8);
for idx = 1:numel(summaries)
    item = summaries(idx);
    matrix(idx, :) = [ ...
        item.expectedCardinality / targetCapacity, ...
        item.cardinalityVariance / targetCapacity, ...
        item.positionVariance, item.associationConfidence, ...
        item.detectionMass, item.activeLabelCount / targetCapacity, ...
        item.quality, item.need];
end
end

function [features, names, available] = buildEdgeFeatures( ...
        raw, rawNames, groups, groupIds, physical, previous, reference)
semanticNames = { ...
    'link_reliability', 'normalized_sensor_distance', ...
    'positive_existence_gain', 'negative_existence_gap', ...
    'positive_precision_gain', 'negative_precision_gap', ...
    'normalized_state_discrepancy', 'active_label_overlap', ...
    'node_quality_advantage', 'receiver_need'};
semanticIdx = nameIndices(rawNames, semanticNames);
names = { ...
    'bias', 'same_formation', 'physical_support_fraction', ...
    'reference_route_fraction', 'previous_route_fraction'};
names = [names, prefixNames(semanticNames, 'mean_'), ...
    prefixNames(semanticNames, 'minimum_'), ...
    prefixNames(semanticNames, 'maximum_')];
formationCount = numel(groups);
features = zeros(formationCount, formationCount, numel(names));
available = false(formationCount, formationCount);
for receiverFormation = 1:formationCount
    receivers = groupIds == groups(receiverFormation);
    for senderFormation = 1:formationCount
        senders = groupIds == groups(senderFormation);
        possible = receivers' * senders;
        if receiverFormation == senderFormation
            possible(1:size(possible, 1)+1:end) = false;
        end
        possibleCount = nnz(possible);
        selected = possible & physical;
        selectedCount = nnz(selected);
        available(receiverFormation, senderFormation) = ...
            selectedCount > 0;
        if selectedCount > 0
            values = reshapeSelected(raw, selected, semanticIdx);
            means = mean(values, 1);
            minima = min(values, [], 1);
            maxima = max(values, [], 1);
        else
            means = zeros(1, numel(semanticNames));
            minima = means;
            maxima = means;
        end
        features(receiverFormation, senderFormation, :) = [ ...
            1, double(receiverFormation == senderFormation), ...
            selectedCount / max(possibleCount, 1), ...
            nnz(reference & possible) / max(possibleCount, 1), ...
            nnz(previous & possible) / max(possibleCount, 1), ...
            means, minima, maxima];
    end
end
end

function values = reshapeSelected(raw, mask, indices)
values = zeros(nnz(mask), numel(indices));
for featureIdx = 1:numel(indices)
    page = raw(:, :, indices(featureIdx));
    values(:, featureIdx) = page(mask);
end
if any(~isfinite(values(:)))
    error('Physical formation edge has non-finite observable features.');
end
end

function [features, names, actionIndex, present, withinPayload] = ...
        buildModeFeatures(bank, groups, groupIds, raw, rawNames, ...
        physical, previous, referenceAdjacency, ...
        referenceWeights, referenceSources)
names = { ...
    'bias', 'is_reference', 'trust_weight', ...
    'trust_weight_squared', 'posterior_proxy_allowed', ...
    'predicted_payload_saving_fraction', ...
    'asinh_posterior_proxy_objective', ...
    'dominant_source_change_fraction', ...
    'row_edge_change_fraction', 'row_edge_saving_fraction', ...
    'row_weight_l1_mean', 'candidate_previous_overlap', ...
    'reference_previous_overlap', 'previous_overlap_delta', ...
    'cross_formation_source_fraction', ...
    'selected_source_reliability_mean', ...
    'selected_source_reliability_min'};
formationCount = numel(groups);
modeCount = round(bank.modeCount);
features = zeros(formationCount, modeCount, numel(names));
actionIndex = zeros(formationCount, modeCount);
present = false(formationCount, modeCount);
withinPayload = false(formationCount, modeCount);
reliabilityIdx = nameIndices(rawNames, {'link_reliability'});
reliabilityPage = raw(:, :, reliabilityIdx);
for formationIdx = 1:formationCount
    members = reshape(find(groupIds == groups(formationIdx)), 1, []);
    for modeIdx = 1:modeCount
        if modeIdx == 1
            currentAction = bank.referenceActionIndex;
        else
            currentAction = find( ...
                bank.actionFormationIndex == formationIdx & ...
                bank.actionModeIndex == modeIdx);
            if isempty(currentAction)
                continue;
            elseif numel(currentAction) ~= 1
                error('Formation mode maps to multiple local actions.');
            end
        end
        actionIndex(formationIdx, modeIdx) = currentAction;
        present(formationIdx, modeIdx) = true;
        withinPayload(formationIdx, modeIdx) = ...
            bank.actionPayloadBytes(currentAction) <= ...
                bank.referencePayloadBytes + 1e-9;
        candidateAdjacency = logical( ...
            bank.actionAdjacency(:, :, currentAction));
        candidateWeights = ...
            bank.actionFusionWeights(:, :, currentAction);
        candidateSources = reshape( ...
            bank.actionDominantSources(currentAction, :), 1, []);
        candidateRows = candidateAdjacency(members, :);
        referenceRows = referenceAdjacency(members, :);
        previousRows = previous(members, :);
        physicalRows = physical(members, :);
        rowDenominator = max(nnz(physicalRows), 1);
        candidateOverlap = overlapFraction( ...
            candidateRows, previousRows);
        referenceOverlap = overlapFraction( ...
            referenceRows, previousRows);
        selectedReliability = selectedSourceReliability( ...
            members, candidateSources(members), ...
            reliabilityPage);
        crossSource = groupIds(candidateSources(members)) ~= ...
            groupIds(members);
        features(formationIdx, modeIdx, :) = [ ...
            1, double(modeIdx == 1), ...
            bank.modeTrustWeights(modeIdx), ...
            bank.modeTrustWeights(modeIdx)^2, ...
            double(bank.actionPosteriorProxyAllowed(currentAction)), ...
            (bank.referencePayloadBytes - ...
                bank.actionPayloadBytes(currentAction)) / ...
                    max(bank.referencePayloadBytes, eps), ...
            asinh(bank.actionPosteriorObjective(currentAction)), ...
            mean(candidateSources(members) ~= ...
                referenceSources(members)), ...
            nnz(xor(candidateRows, referenceRows)) / rowDenominator, ...
            (nnz(referenceRows) - nnz(candidateRows)) / rowDenominator, ...
            sum(abs(candidateWeights(members, :) - ...
                referenceWeights(members, :)), 'all') / ...
                    max(numel(members), 1), ...
            candidateOverlap, referenceOverlap, ...
            candidateOverlap - referenceOverlap, ...
            mean(crossSource), mean(selectedReliability), ...
            min(selectedReliability)];
    end
end
end

function values = selectedSourceReliability( ...
        receivers, sources, reliability)
values = zeros(1, numel(receivers));
for idx = 1:numel(receivers)
    receiver = receivers(idx);
    sender = sources(idx);
    if receiver == sender
        values(idx) = 1;
    else
        value = reliability(receiver, sender);
        if ~isfinite(value)
            error('Selected dominant source lacks physical reliability.');
        end
        values(idx) = value;
    end
end
end

function assertObservableContext(context, nodeCount, groupIds)
required = { ...
    'localPosteriorBySensor', 'model', 'commConfig', ...
    'currentTime', 'previousAdjacency', ...
    'physicalAdjacency', 'positions'};
if ~all(isfield(context, required)) || ...
        numel(context.localPosteriorBySensor) ~= nodeCount || ...
        ~isequal(size(context.previousAdjacency), ...
            [nodeCount, nodeCount]) || ...
        ~isequal(size(context.physicalAdjacency), ...
            [nodeCount, nodeCount]) || ...
        size(context.positions, 2) ~= nodeCount || ...
        isfield(context.commConfig, 'linkUniforms') || ...
        (isfield(context.commConfig, 'pDropByEdge') && ...
         ndims(context.commConfig.pDropByEdge) >= 3) || ...
        isfield(context.model, 'explicitTargetTrajectories') || ...
        (isfield(context.model, 'dynamicTopologyScenario') && ...
         isfield(context.model.dynamicTopologyScenario, ...
            'targetTrajectories'))
    error('Tracking-aligned graph context exposes invalid information.');
end
if isfield(context.model, 'dynamicTopologyScenario') && ...
        isfield(context.model.dynamicTopologyScenario, 'config') && ...
        isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds')
    configured = reshape(context.model.dynamicTopologyScenario. ...
        config.sensorGroupIds, 1, []);
    if ~isequal(configured, groupIds)
        error('Tracking-aligned graph formation assignments differ.');
    end
end
end

function capacity = resolveTargetCapacity(context, summaries)
capacity = 0;
model = context.model;
if isfield(model, 'birthTimeByLocation')
    capacity = numel(model.birthTimeByLocation);
elseif isfield(model, 'birthParameters')
    capacity = numel(model.birthParameters);
end
if ~isscalar(capacity) || ~isfinite(capacity) || capacity < 1
    capacity = max([1, [summaries.activeLabelCount]]);
end
end

function fraction = overlapFraction(selected, previous)
selected = logical(selected);
previous = logical(previous);
selectedCount = nnz(selected);
if selectedCount == 0
    fraction = 0;
else
    fraction = nnz(selected & previous) / selectedCount;
end
end

function indices = nameIndices(names, requested)
indices = zeros(1, numel(requested));
for idx = 1:numel(requested)
    match = find(strcmp(names, requested{idx}));
    if numel(match) ~= 1
        error('Missing or ambiguous graph feature: %s', requested{idx});
    end
    indices(idx) = match;
end
end

function names = prefixNames(base, prefix)
names = cell(size(base));
for idx = 1:numel(base)
    names{idx} = [prefix, base{idx}];
end
end
