function [scores, details] = ...
    computeRollingSafeObservableBasisScores( ...
        context, receiverIndices, senderIndices, ...
        baselineSources, registryEntry, sourceWeight)
% COMPUTEROLLINGSAFEOBSERVABLEBASISSCORES Score one frozen basis action.
%
% Candidate rows are aligned by explicit receiver/sender keys. Every term
% uses a deterministic within-block percentile transform, so heterogeneous
% posterior units cannot dominate a multi-term semantic direction.

[rawFeatures, rawFeatureNames, rawReceivers, rawSenders, ...
        featureMetadata] = ...
    computeRollingSafeDirectedActionExamples( ...
        context, sourceWeight, struct( ...
            'featureContextMode', ...
            registryEntry.featureContextMode));
if featureMetadata.truthUsed || ...
        getField(featureMetadata, 'futureOutcomeUsed', false) || ...
        getField(featureMetadata, 'groundTruthUsed', false)
    error('Observable basis feature extractor violated its truth-free contract.');
end

nodeCount = numel(context.localPosteriorBySensor);
rawKeys = rawReceivers + nodeCount * (rawSenders - 1);
requestedKeys = reshape(receiverIndices, [], 1) + ...
    nodeCount * (reshape(senderIndices, [], 1) - 1);
[aligned, rawLocation] = ismember(requestedKeys, rawKeys);
if ~all(aligned) || numel(unique(rawLocation)) ~= numel(rawLocation)
    error(['Observable basis features do not align one-to-one with ', ...
        'the projector action set.']);
end
features = rawFeatures(rawLocation, :);

scores = zeros(numel(requestedKeys), 1);
transformedTerms = zeros( ...
    numel(requestedKeys), numel(registryEntry.featureNames));
for termIdx = 1:numel(registryEntry.featureNames)
    featureName = registryEntry.featureNames{termIdx};
    if strcmp(featureName, 'link_reliability_advantage')
        reliabilityIdx = requireFeature( ...
            rawFeatureNames, 'link_reliability');
        candidateReliability = max( ...
            features(:, reliabilityIdx), 1e-6);
        baselineReliability = zeros(numel(requestedKeys), 1);
        for exampleIdx = 1:numel(requestedKeys)
            receiverIdx = receiverIndices(exampleIdx);
            baselineReliability(exampleIdx) = ...
                resolveLinkReliability( ...
                    context.commConfig, ...
                    baselineSources(receiverIdx), ...
                    receiverIdx, context.currentTime);
        end
        values = log(candidateReliability) - ...
            log(max(baselineReliability, 1e-6));
    else
        featureIdx = requireFeature(rawFeatureNames, featureName);
        values = features(:, featureIdx);
    end
    transformedTerms(:, termIdx) = blockPercentile(values);
    scores = scores + registryEntry.coefficients(termIdx) * ...
        transformedTerms(:, termIdx);
end
coefficientNorm = norm(registryEntry.coefficients, 1);
if coefficientNorm > 0
    scores = scores / coefficientNorm;
end
if any(~isfinite(scores))
    error('Observable basis produced non-finite edge scores.');
end

details = struct( ...
    'contractVersion', registryEntry.contractVersion, ...
    'basisId', registryEntry.basisId, ...
    'basisVersion', registryEntry.basisVersion, ...
    'actionCode', registryEntry.actionCode, ...
    'registrySha256', registryEntry.registrySha256, ...
    'featureContractSha256', getField( ...
        featureMetadata, 'featureContractSha256', ''), ...
    'featureNamesUsed', {registryEntry.featureNames}, ...
    'coefficients', registryEntry.coefficients, ...
    'transforms', {registryEntry.transforms}, ...
    'transformedTerms', transformedTerms, ...
    'receiverIndices', reshape(receiverIndices, [], 1), ...
    'senderIndices', reshape(senderIndices, [], 1), ...
    'residualScores', scores, ...
    'posteriorUsed', registryEntry.posteriorUsed, ...
    'currentLinkReliabilityUsed', ...
        registryEntry.currentLinkReliabilityUsed, ...
    'historyUsed', registryEntry.historyUsed, ...
    'currentGeometryUsed', registryEntry.currentGeometryUsed, ...
    'truthUsed', false, ...
    'groundTruthUsed', false, ...
    'futureOutcomeUsed', false);
end

function percentile = blockPercentile(values)
values = reshape(values, [], 1);
if any(~isfinite(values))
    error('Observable basis term contains a non-finite value.');
end
count = numel(values);
if count <= 1
    percentile = zeros(count, 1);
    return;
end
[sorted, order] = sort(values, 'ascend');
ranks = zeros(count, 1);
cursor = 1;
while cursor <= count
    endCursor = cursor;
    while endCursor < count && ...
            sorted(endCursor + 1) == sorted(cursor)
        endCursor = endCursor + 1;
    end
    averageRank = (cursor + endCursor) / 2;
    ranks(order(cursor:endCursor)) = averageRank;
    cursor = endCursor + 1;
end
percentile = (ranks - 1) / (count - 1);
end

function reliability = resolveLinkReliability( ...
        config, senderIdx, receiverIdx, currentTime)
if isfield(config, 'pDropByEdge') && ~isempty(config.pDropByEdge)
    if ndims(config.pDropByEdge) >= 3
        timeIdx = min(currentTime, size(config.pDropByEdge, 3));
        dropProbability = config.pDropByEdge( ...
            senderIdx, receiverIdx, timeIdx);
    else
        dropProbability = config.pDropByEdge(senderIdx, receiverIdx);
    end
elseif isfield(config, 'pDropBySensor') && ...
        numel(config.pDropBySensor) >= senderIdx
    dropProbability = config.pDropBySensor(senderIdx);
else
    dropProbability = 0;
end
reliability = max(1e-6, 1 - min(max(dropProbability, 0), 1));
end

function featureIdx = requireFeature(featureNames, featureName)
featureIdx = find(strcmp(featureNames, featureName), 1);
if isempty(featureIdx)
    error('Observable basis requires missing feature %s.', featureName);
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
