function block = ...
    computeLabelSetMessagePassingPolicyBlock(context, options)
% COMPUTELABELSETMESSAGEPASSINGPOLICYBLOCK Online truth-free GNN input.

if nargin < 2 || isempty(options)
    options = struct();
end
protocol = getField(options, 'protocol', ...
    getLabelSetSimulatorPolicyProtocol());
if ~protocol.messagePassingImplementationAuthorized
    error('Label-set message-passing input is not authorized.');
end
featureOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'localResidualWeight', protocol.localResidualWeight, ...
    'residualWeightGrid', protocol.residualWeightGrid, ...
    'featureContextMode', protocol.featureContextMode);
examples = computeCvarResidualGraphPolicyExamples( ...
    context, featureOptions);
labelOptions = struct( ...
    'maxLabelCount', protocol.maxLabelCount, ...
    'velocityScale', protocol.velocityScale, ...
    'highExistenceThreshold', ...
        protocol.highExistenceThreshold);
[labelFeatures, labelMask, labelFeatureNames, ...
    labelMetadata] = ...
        computeLabelSetDirectedActionFeatures( ...
            context, examples.receiverIndices, ...
            examples.senderIndices, labelOptions);
if examples.truthUsed || examples.groundTruthUsed || ...
        examples.futureOutcomeUsed || ...
        labelMetadata.truthUsed || ...
        labelMetadata.groundTruthUsed || ...
        labelMetadata.futureOutcomeUsed || ...
        labelMetadata.numericLabelIdentifiersUsedAsFeatures || ...
        size(labelFeatures, 1) ~= examples.candidateCount || ...
        size(labelFeatures, 2) ~= protocol.maxLabelCount || ...
        size(labelFeatures, 3) ~= ...
            protocol.expectedLabelFeatureCount || ...
        ~isequal(size(labelMask), ...
            [examples.candidateCount, ...
             protocol.maxLabelCount])
    error('Online label-set message-passing feature contract failed.');
end

block = struct();
block.contractVersion = ...
    'label-set-message-passing-online-block-v1';
block.edgeFeatures = examples.edgeFeatures;
block.edgeFeatureNames = ...
    examples.edgeFeatureNames;
block.nodeFeatures = examples.nodeFeatures;
block.nodeFeatureNames = ...
    examples.nodeFeatureNames;
block.labelFeatures = labelFeatures;
block.labelMask = labelMask;
block.labelFeatureNames = labelFeatureNames;
block.labelCounts = labelMetadata.labelCounts;
block.receiverIndices = examples.receiverIndices;
block.senderIndices = examples.senderIndices;
block.residualWeightGrid = ...
    examples.residualWeightGrid;
block.residualBaselineSourcesByReceiver = ...
    examples.residualBaselineSourcesByReceiver;
block.dominantSourcesByReceiver = ...
    examples.dominantSourcesByReceiver;
block.groupIds = examples.groupIds;
block.physicalAdjacency = ...
    examples.physicalAdjacency;
block.nodeCount = examples.nodeCount;
block.candidateCount = examples.candidateCount;
block.weightCount = examples.weightCount;
block.aggregateFeatureContractSha256 = ...
    examples.featureContractSha256;
block.labelFeatureContractSha256 = ...
    labelMetadata.featureContractSha256;
block.truthUsed = false;
block.groundTruthUsed = false;
block.futureOutcomeUsed = false;
block.numericLabelIdentifiersUsedAsFeatures = false;
block.permutationInvariantEncoderRequired = true;
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
