function result = computeSetTrustSequenceV134RecoveryCertificate( ...
        selectedAdjacencySequence, nominalFusionWeightSequence, ...
        pDropByEdgeSequence, controlledAdmissionEdgeSequence, ...
        groupIds, actionSpec, ...
        recoveryTailSteps, protocol)
% COMPUTESETTRUSTSEQUENCEV134RECOVERYCERTIFICATE Mixing after reentry.
%
% This certificate is deliberately limited to KLA propagation.  It proves
% expected centered-L2 contraction of common-support set-density log
% ratios under independent link deliveries.  It does not prove tracking
% safety, bound local Bayes disturbances, or remove Bernoulli overlap and
% mixture-approximation terms.

requiredAction = {'formationIdsByTime', 'trustFactorsByTime', ...
    'returnsToFullTrust'};
if ~isstruct(actionSpec) || ~isscalar(actionSpec) || ...
        ~all(isfield(actionSpec, requiredAction)) || ...
        ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~isfield(protocol, 'primaryMissingNeighborWeightMode') || ...
        ~isfield(protocol, ...
            'maximumIncomingCountForOutcomeEnumeration') || ...
        ~isfield(protocol, 'recoverySquaredContractionTarget') || ...
        ~isfield(protocol, 'preLearningGate') || ...
        ~isstruct(protocol.preLearningGate) || ...
        ~isfield(protocol.preLearningGate, ...
            'maximumRecoverySquaredContractionFactor') || ...
        ~isscalar(recoveryTailSteps) || ...
        ~isfinite(recoveryTailSteps) || recoveryTailSteps < 1 || ...
        recoveryTailSteps ~= round(recoveryTailSteps)
    error('V134RecoveryCertificate:InvalidInput', ...
        'The V134 action or certificate protocol is malformed.');
end
gateTarget = protocol.preLearningGate. ...
    maximumRecoverySquaredContractionFactor;
if ~isscalar(protocol.recoverySquaredContractionTarget) || ...
        ~isfinite(protocol.recoverySquaredContractionTarget) || ...
        protocol.recoverySquaredContractionTarget <= 0 || ...
        ~isscalar(gateTarget) || ~isfinite(gateTarget) || ...
        gateTarget <= 0 || ...
        abs(protocol.recoverySquaredContractionTarget - ...
            gateTarget) > 1e-12
    error('V134RecoveryCertificate:TargetDrift', ...
        'The structural certificate and empirical gate targets differ.');
end

[adjacency, weights, pDrop, controlled, nodeCount, horizon] = ...
    normalizeInputs(selectedAdjacencySequence, ...
        nominalFusionWeightSequence, pDropByEdgeSequence, ...
        controlledAdmissionEdgeSequence);
groupIds = reshape(groupIds, 1, []);
if numel(groupIds) ~= nodeCount || ...
        numel(actionSpec.formationIdsByTime) ~= horizon || ...
        numel(actionSpec.trustFactorsByTime) ~= horizon || ...
        recoveryTailSteps >= horizon || ...
        ~logical(actionSpec.returnsToFullTrust)
    error('V134RecoveryCertificate:InvalidInput', ...
        'The action, node membership, or recovery window is inconsistent.');
end

effectiveAdjacency = adjacency;
effectiveWeights = weights;
crossMask = groupIds(:) ~= groupIds(:)';
crossSequence = repmat(crossMask, 1, 1, horizon);
if any(controlled(:) & ~adjacency(:)) || ...
        any(controlled(:) & ~crossSequence(:))
    error('V134RecoveryCertificate:ControlledEdgeDrift', ...
        'The runtime-controlled edges are not selected cross inputs.');
end
for timeIdx = 1:horizon
    formations = reshape( ...
        actionSpec.formationIdsByTime{timeIdx}, 1, []);
    factors = reshape(actionSpec.trustFactorsByTime{timeIdx}, 1, []);
    if numel(formations) ~= numel(factors) || ...
            any(~ismember(factors, [0, 1]))
        error('V134RecoveryCertificate:InvalidActionPage', ...
            'Every V134 action page must use binary admission.');
    end
    for factorIdx = 1:numel(formations)
        if factors(factorIdx) ~= 0
            continue;
        end
        receiverMask = groupIds == formations(factorIdx);
        removed = controlled(:, :, timeIdx) & receiverMask(:);
        effectiveAdjacency(:, :, timeIdx) = ...
            effectiveAdjacency(:, :, timeIdx) & ~removed;
        for receiverIdx = reshape(find(receiverMask), 1, [])
            removedMass = sum(effectiveWeights( ...
                receiverIdx, removed(receiverIdx, :), timeIdx));
            effectiveWeights(receiverIdx, ...
                removed(receiverIdx, :), timeIdx) = 0;
            if strcmpi(protocol.primaryMissingNeighborWeightMode, 'self')
                effectiveWeights(receiverIdx, receiverIdx, timeIdx) = ...
                    effectiveWeights(receiverIdx, receiverIdx, timeIdx) + ...
                        removedMass;
            end
            rowSum = sum(effectiveWeights(receiverIdx, :, timeIdx));
            effectiveWeights(receiverIdx, :, timeIdx) = ...
                effectiveWeights(receiverIdx, :, timeIdx) / rowSum;
        end
    end
end

tailColumns = (horizon - recoveryTailSteps + 1):horizon;
if any(cellfun(@(factors) any(factors ~= 1), ...
        actionSpec.trustFactorsByTime(tailColumns)))
    error('V134RecoveryCertificate:TailNotFullyRestored', ...
        'The certified recovery tail must use full posterior admission.');
end
reliability = 1 - permute(pDrop, [2, 1, 3]);
options = struct( ...
    'missingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
candidate = computeReliableKlaWindowMeanSquareContractionCertificate( ...
    effectiveAdjacency(:, :, tailColumns), ...
    effectiveWeights(:, :, tailColumns), ...
    reliability(:, :, tailColumns), options);
reference = computeReliableKlaWindowMeanSquareContractionCertificate( ...
    adjacency(:, :, tailColumns), weights(:, :, tailColumns), ...
    reliability(:, :, tailColumns), options);
candidateFactor = candidate.worstCaseExpectedSquaredContractionFactor;
referenceFactor = reference.worstCaseExpectedSquaredContractionFactor;
target = gateTarget;

result = struct();
result.contractVersion = ...
    'v134-binary-admission-recovery-certificate-v1';
result.tailColumns = tailColumns;
result.recoveryTailSteps = recoveryTailSteps;
result.candidateSquaredContractionFactor = candidateFactor;
result.referenceSquaredContractionFactor = referenceFactor;
result.maximumAllowedSquaredContractionFactor = target;
result.strictMeanSquareContractionCertified = ...
    candidate.strictMeanSquareContractionCertified;
result.targetContractionCertified = candidateFactor <= target + 1e-12;
candidateTailWeights = effectiveWeights(:, :, tailColumns);
referenceTailWeights = weights(:, :, tailColumns);
result.referenceAndCandidateTailIdentical = ...
    isequal(effectiveAdjacency(:, :, tailColumns), ...
        adjacency(:, :, tailColumns)) && ...
    max(abs(candidateTailWeights(:) - ...
        referenceTailWeights(:))) <= 1e-12;
result.passesRecoveryGate = ...
    result.strictMeanSquareContractionCertified && ...
    result.targetContractionCertified && ...
    result.referenceAndCandidateTailIdentical;
result.candidateCertificate = candidate;
result.referenceCertificate = reference;
result.commonPositiveSupportRequired = true;
result.localBayesDisturbanceAccounted = false;
result.bernoulliExistenceNormalizerDisturbanceAccounted = false;
result.mixtureApproximationDisturbanceAccounted = false;
result.trackingSafetyGuaranteed = false;
result.futureReliabilityScheduleUsed = true;
result.causalDeploymentCertificate = false;
result.reliabilityScheduleRole = ...
    'registered-development-forecast-not-online-policy-input';
end

function [adjacency, weights, pDrop, controlled, nodeCount, horizon] = ...
        normalizeInputs(adjacency, weights, pDrop, controlled)
if ndims(adjacency) == 2
    adjacency = reshape(adjacency, ...
        size(adjacency, 1), size(adjacency, 2), 1);
end
if ndims(weights) == 2
    weights = reshape(weights, ...
        size(weights, 1), size(weights, 2), 1);
end
if ndims(pDrop) == 2
    pDrop = reshape(pDrop, size(pDrop, 1), size(pDrop, 2), 1);
end
if ndims(controlled) == 2
    controlled = reshape(controlled, ...
        size(controlled, 1), size(controlled, 2), 1);
end
nodeCount = size(adjacency, 1);
horizon = size(adjacency, 3);
if nodeCount < 2 || size(adjacency, 2) ~= nodeCount || ...
        ~isequal(size(weights), size(adjacency)) || ...
        ~isequal(size(pDrop), size(adjacency)) || ...
        ~isequal(size(controlled), size(adjacency)) || ...
        any(~isfinite(adjacency(:))) || ...
        any(adjacency(:) ~= 0 & adjacency(:) ~= 1) || ...
        any(~isfinite(weights(:))) || any(weights(:) < 0) || ...
        any(~isfinite(pDrop(:))) || any(pDrop(:) < 0) || ...
        any(pDrop(:) > 1) || any(~isfinite(controlled(:))) || ...
        any(controlled(:) ~= 0 & controlled(:) ~= 1)
    error('V134RecoveryCertificate:InvalidSequence', ...
        'The route, weight, or link-probability sequence is malformed.');
end
adjacency = logical(adjacency);
controlled = logical(controlled);
end
