function comparison = ...
    compareLegacyAndIndexEquivariantFormationRoutes(context, options)
% COMPARELEGACYANDINDEXEQUIVARIANTFORMATIONROUTES Structural-only audit.
%
% Both arms use the same current physical graph, link-probability page,
% weights, message budget and exact mean-square propagation certificate.
% No posterior or tracking outcome is read.

if nargin < 2 || isempty(options)
    options = struct();
end
allowedFields = {'targetSquaredContractionFactor', ...
    'maximumHorizonMultiplier', 'maximumIncomingCount', ...
    'dominantWeight', 'residualWeight'};
if ~isstruct(options) || ~isscalar(options) || ...
        any(~ismember(fieldnames(options), allowedFields))
    error('FormationRouteComparison:InvalidOptions', ...
        'The structural comparison options are malformed.');
end
if ~isfield(context, 'auditBoundary') || ...
        context.auditBoundary.formalRuntimeObservableBoundaryPassed || ...
        context.auditBoundary.runtimePhysicalUidRegistryIntegrated || ...
        context.auditBoundary.trackingOutcomeAuthorized || ...
        context.auditBoundary.validationClaimAllowed || ...
        ~context.auditBoundary.developmentEvidenceOnly
    error('FormationRouteComparison:InvalidAuditBoundary', ...
        'The comparison requires the explicit development-only boundary.');
end
target = getField(options, 'targetSquaredContractionFactor', 0.90);
maximumMultiplier = getField(options, 'maximumHorizonMultiplier', 4);
maximumIncomingCount = getField(options, 'maximumIncomingCount', 2);
dominantWeight = getField(options, 'dominantWeight', 0.70);
residualWeight = getField(options, 'residualWeight', 0.05);
if ~isscalar(target) || ~isfinite(target) || target <= 0 || ...
        target >= 1 || ~isscalar(maximumMultiplier) || ...
        maximumMultiplier < 1 || ...
        maximumMultiplier ~= round(maximumMultiplier)
    error('FormationRouteComparison:InvalidOptions', ...
        'The comparison target or maximum horizon is invalid.');
end

[legacyAdjacency, legacyDetails] = ...
    selectFormationBackboneResidualTourPolicy(context, struct( ...
        'dominantWeight', dominantWeight, ...
        'residualWeight', residualWeight));
[v43Adjacency, v43Details] = ...
    selectIndexEquivariantFormationBackbonePolicy(context, struct( ...
        'dominantWeight', dominantWeight, ...
        'residualWeight', residualWeight));
nodeCount = size(legacyAdjacency, 1);
maximumHorizon = maximumMultiplier * (nodeCount - 1);
reliability = 1 - context.commConfig.pDropByEdge';
runtime = validateReliableKlaMixingRuntimeSemantics( ...
    context.triggerConfig);
profileOptions = struct( ...
    'missingNeighborWeightMode', runtime.missingNeighborWeightMode, ...
    'maximumIncomingCount', maximumIncomingCount, ...
    'targetSquaredFactors', target);
legacyProfile = computeStaticReliableKlaMeanSquareHorizonProfile( ...
    legacyAdjacency, legacyDetails.fusionWeightMatrix, reliability, ...
    maximumHorizon, profileOptions);
v43Profile = computeStaticReliableKlaMeanSquareHorizonProfile( ...
    v43Adjacency, v43Details.fusionWeightMatrix, reliability, ...
    maximumHorizon, profileOptions);
legacyTargetHorizon = legacyProfile.firstTargetHorizon(1);
v43TargetHorizon = v43Profile.firstTargetHorizon(1);
fixedHorizon = nodeCount - 1;
legacyFixedFactor = legacyProfile. ...
    worstCaseExpectedSquaredFactorByHorizon(fixedHorizon + 1);
v43FixedFactor = v43Profile. ...
    worstCaseExpectedSquaredFactorByHorizon(fixedHorizon + 1);

comparison = struct();
comparison.contractVersion = ...
    'legacy-vs-index-equivariant-formation-route-comparison-v1';
comparison.nodeCount = nodeCount;
comparison.formationCount = ...
    numel(v43Details.formationPhysicalUids);
comparison.currentTime = context.currentTime;
comparison.targetSquaredContractionFactor = target;
comparison.maximumHorizon = maximumHorizon;
comparison.dominantWeight = dominantWeight;
comparison.residualWeight = residualWeight;
comparison.fixedComparisonHorizon = fixedHorizon;
comparison.legacyTargetHorizon = legacyTargetHorizon;
comparison.v43TargetHorizon = v43TargetHorizon;
comparison.targetHorizonReduction = ...
    legacyTargetHorizon - v43TargetHorizon;
comparison.targetHorizonRatio = ...
    v43TargetHorizon / legacyTargetHorizon;
comparison.legacyFixedHorizonFactor = legacyFixedFactor;
comparison.v43FixedHorizonFactor = v43FixedFactor;
comparison.fixedHorizonFactorDelta = ...
    v43FixedFactor - legacyFixedFactor;
comparison.fixedHorizonRelativeReduction = ...
    (legacyFixedFactor - v43FixedFactor) / legacyFixedFactor;
comparison.legacyDirectedMessageCount = nnz(legacyAdjacency);
comparison.v43DirectedMessageCount = nnz(v43Adjacency);
comparison.sameDirectedMessageBudget = ...
    nnz(legacyAdjacency) == nnz(v43Adjacency);
comparison.legacyCrossFormationMessageCount = ...
    legacyDetails.crossFormationMessageCount;
comparison.v43CrossFormationMessageCount = ...
    v43Details.crossFormationMessageCount;
comparison.sameCrossFormationMessageBudget = ...
    legacyDetails.crossFormationMessageCount == ...
        v43Details.crossFormationMessageCount;
comparison.legacyRouteCanonicalSha256 = routeSha256( ...
    legacyAdjacency, legacyDetails.fusionWeightMatrix);
comparison.v43RouteCanonicalSha256 = routeSha256( ...
    v43Adjacency, v43Details.fusionWeightMatrix);
comparison.legacyProfile = compactProfile(legacyProfile);
comparison.v43Profile = compactProfile(v43Profile);
comparison.v43RouteIndexEquivarianceDesigned = true;
comparison.legacyRouteIndexEquivariancePassed = false;
comparison.physicalGeometryAndReliabilityMatched = true;
comparison.fusionWeightsMatched = ...
    legacyDetails.dominantWeight == dominantWeight && ...
    v43Details.dominantWeight == dominantWeight && ...
    legacyDetails.residualWeight == residualWeight && ...
    v43Details.residualWeight == residualWeight && ...
    isequal(legacyDetails.dominantWeightsByReceiver, ...
        v43Details.dominantWeightsByReceiver) && ...
    isequal(legacyDetails.residualWeightsByReceiver, ...
        v43Details.residualWeightsByReceiver) && ...
    isequal(legacyDetails.selfWeightsByReceiver, ...
        v43Details.selfWeightsByReceiver);
comparison.routeBoundaryVerified = verifyRouteBoundaries( ...
    legacyDetails, v43Details);
comparison.posteriorUsed = false;
comparison.truthUsed = false;
comparison.measurementUsed = false;
comparison.futureOutcomeUsed = false;
comparison.realizedDeliveryUniformsUsed = false;
comparison.trackingOutcomeScored = false;
comparison.developmentEvidenceOnly = true;
comparison.auditBoundary = context.auditBoundary;
comparison.auditBoundaryCanonicalSha256 = ...
    computeCanonicalValueSha256(context.auditBoundary);
comparison.canonicalSha256 = computeCanonicalValueSha256(comparison);
end

function passed = verifyRouteBoundaries(legacyDetails, v43Details)
legacyRequired = {'posteriorUsed', 'truthUsed', ...
    'currentLinkReliabilityUsed', 'currentPhysicalActionSetUsed'};
v43Required = {'posteriorUsed', 'truthUsed', 'measurementUsed', ...
    'futureOutcomeUsed', 'realizedDeliveryUniformsUsed', ...
    'trackingOutcomeScored', 'currentGeometryUsed', ...
    'currentLinkReliabilityUsed', 'currentPhysicalActionSetUsed'};
if ~all(isfield(legacyDetails, legacyRequired)) || ...
        ~all(isfield(v43Details, v43Required))
    error('FormationRouteComparison:BoundaryMissing', ...
        'A compared route omitted required execution-boundary fields.');
end
passed = ~legacyDetails.posteriorUsed && ~legacyDetails.truthUsed && ...
    ~legacyDetails.currentLinkReliabilityUsed && ...
    legacyDetails.currentPhysicalActionSetUsed && ...
    ~v43Details.posteriorUsed && ~v43Details.truthUsed && ...
    ~v43Details.measurementUsed && ~v43Details.futureOutcomeUsed && ...
    ~v43Details.realizedDeliveryUniformsUsed && ...
    ~v43Details.trackingOutcomeScored && ...
    v43Details.currentGeometryUsed && ...
    v43Details.currentLinkReliabilityUsed && ...
    v43Details.currentPhysicalActionSetUsed;
if ~passed
    error('FormationRouteComparison:BoundaryViolation', ...
        'A compared route crossed the registered development boundary.');
end
end

function compact = compactProfile(profile)
compact = struct();
compact.contractVersion = profile.contractVersion;
compact.maximumHorizon = profile.maximumHorizon;
compact.firstStrictContractionHorizon = ...
    profile.firstStrictContractionHorizon;
compact.targetSquaredFactors = profile.targetSquaredFactors;
compact.firstTargetHorizon = profile.firstTargetHorizon;
compact.worstCaseExpectedSquaredFactorByHorizon = ...
    profile.worstCaseExpectedSquaredFactorByHorizon;
compact.repeatedCurrentPage = profile.repeatedCurrentPage;
end

function sha256 = routeSha256(adjacency, weights)
sha256 = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), 'fusionWeights', weights));
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
