function readout = emptyStructuredTreeAttributionReadout()
% EMPTYSTRUCTUREDTREEATTRIBUTIONREADOUT Stable report contract.

readout = struct( ...
    'available', false, ...
    'availableCandidateCount', 0, ...
    'arm', '', ...
    'candidateSourceWeight', NaN, ...
    'scenarioContractValid', false, ...
    'formationCount', NaN, ...
    'sensorsPerFormation', NaN, ...
    'expectedCrossFormationMessageFraction', NaN, ...
    'requiredScheduledPhaseCount', NaN, ...
    'observedScheduledPhaseCount', 0, ...
    'eligibleScheduledControlCount', 0, ...
    'fixedIndexControlAvailable', false, ...
    'linkTreeControlAvailable', false, ...
    'completeBaselineSet', false, ...
    'referenceArm', '', ...
    'referenceArmBySeed', {{}}, ...
    'gainVsMatchedControlPercent', NaN, ...
    'gainVsMatchedControlBySeedPercent', [], ...
    'positiveGainEverySeed', false, ...
    'tailSafeVsMatchedControl', false, ...
    'maximumAttemptedByteMismatchPercent', NaN, ...
    'communicationMatchedWithinTwoPercent', false, ...
    'noMoreAttemptedBytesEverySeed', false, ...
    'strictParetoEverySeed', false, ...
    'communicationFair', false, ...
    'crossFormationBudgetExactEverySeed', false, ...
    'directedMessageCountExactEveryStepAndSeed', false, ...
    'crossFormationTreeEdgeCountExactEveryStepAndSeed', false, ...
    'rootedFormationTreeEveryStepAndSeed', false, ...
    'pairwiseUnionStrongEveryStepAndSeed', false, ...
    'pairwisePreviousGraphExecutedEverySeed', false, ...
    'receiverCoverageComplete', false, ...
    'distinctMapsEverySeed', false, ...
    'withinWindowChangesEverySeed', false, ...
    'distinctGatewayMapsEverySeed', false, ...
    'gatewayChangesEverySeed', false, ...
    'minimumDifferenceFromFixedIndex', NaN, ...
    'differsFromFixedIndexEnough', false, ...
    'zeroInfeasibility', false, ...
    'candidateStructuralContractPassed', false, ...
    'minimumPracticalGainPercent', NaN, ...
    'minimumRouteDifferenceFraction', NaN, ...
    'passesAttributionGate', false, ...
    'status', 'unavailable', ...
    'recommendation', '');
end
