function encoding = encodeDirectGraphFormationStateV219( ...
        snapshot, targetRow)
% ENCODEDIRECTGRAPHFORMATIONSTATEV219 Deterministic two-hop graph features.
%
% This is the frozen graph-ridge baseline and the input contract for the
% later trainable GNN.  It is permutation equivariant and identifier-free.

required = {'contractVersion', 'formationCount', 'nodeFeatureNames', ...
    'nodeFeatures', 'edgeFeatureNames', 'edgeFeatures', ...
    'receiverRowSenderColumnAdjacency', ...
    'numericFormationIdentifiersUsedAsFeatures', ...
    'truthUsed', 'futureInformationUsed'};
if ~isstruct(snapshot) || ~isscalar(snapshot) || ...
        any(~isfield(snapshot, required)) || ...
        ~strcmp(snapshot.contractVersion, ...
            'direct-graph-formation-learning-snapshot-v218-v1') || ...
        ~isscalar(targetRow) || ~isfinite(targetRow) || ...
        targetRow < 1 || targetRow ~= round(targetRow) || ...
        targetRow > snapshot.formationCount || ...
        snapshot.numericFormationIdentifiersUsedAsFeatures || ...
        snapshot.truthUsed || snapshot.futureInformationUsed
    error('DirectGraphFormationEncodingV219:InvalidInput', ...
        'A truth-free V218 graph and valid target row are required.');
end
nodeFeatures = snapshot.nodeFeatures;
formationCount = snapshot.formationCount;
adjacency = logical( ...
    snapshot.receiverRowSenderColumnAdjacency);
if ~isequal(size(adjacency), ...
        [formationCount, formationCount]) || ...
        size(nodeFeatures, 1) ~= formationCount || ...
        any(~isfinite(nodeFeatures(:)))
    error('DirectGraphFormationEncodingV219:ShapeDrift', ...
        'The V218 graph dimensions changed.');
end

aggregation = double(adjacency | eye(formationCount));
aggregation = aggregation ./ max(sum(aggregation, 2), 1);
oneHop = aggregation * nodeFeatures;
twoHop = aggregation * oneHop;
[incomingEdge, outgoingEdge] = aggregateEdges( ...
    snapshot.edgeFeatures, adjacency, targetRow);
values = [ ...
    nodeFeatures(targetRow, :), ...
    oneHop(targetRow, :), ...
    twoHop(targetRow, :), ...
    incomingEdge, outgoingEdge];
names = [ ...
    prefixNames(snapshot.nodeFeatureNames, 'target_'), ...
    prefixNames(snapshot.nodeFeatureNames, 'one_hop_in_'), ...
    prefixNames(snapshot.nodeFeatureNames, 'two_hop_in_'), ...
    prefixNames(snapshot.edgeFeatureNames, 'incoming_edge_'), ...
    prefixNames(snapshot.edgeFeatureNames, 'outgoing_edge_')];
if numel(values) ~= numel(names) || any(~isfinite(values))
    error('DirectGraphFormationEncodingV219:FeatureDrift', ...
        'The V219 graph encoding must be finite and named.');
end

encoding = struct();
encoding.contractVersion = ...
    'direct-graph-two-hop-formation-encoding-v219-v1';
encoding.featureNames = names;
encoding.featureVector = values;
encoding.targetLocalFeatureCount = size(nodeFeatures, 2);
encoding.aggregationIncludesSelf = true;
encoding.aggregationMode = ...
    'receiver-row-degree-normalized-mean-v1';
encoding.numericFormationIdentifiersUsedAsFeatures = false;
encoding.truthUsed = false;
encoding.futureInformationUsed = false;
end

function [incoming, outgoing] = ...
        aggregateEdges(edgeFeatures, adjacency, targetRow)
edgeFeatureCount = size(edgeFeatures, 3);
incoming = zeros(1, edgeFeatureCount);
outgoing = zeros(1, edgeFeatureCount);
incomingRows = find(adjacency(targetRow, :));
outgoingRows = find(adjacency(:, targetRow));
if ~isempty(incomingRows)
    incoming = reshape(mean( ...
        edgeFeatures(targetRow, incomingRows, :), 2), 1, []);
end
if ~isempty(outgoingRows)
    outgoing = reshape(mean( ...
        edgeFeatures(outgoingRows, targetRow, :), 1), 1, []);
end
end

function output = prefixNames(names, prefix)
output = cell(size(names));
for idx = 1:numel(names)
    output{idx} = [prefix, names{idx}];
end
end
