function [features, details] = ...
        encodeFormationGraphActionsV208(graph, rows, encoder)
% ENCODEFORMATIONGRAPHACTIONSV208 Frozen two-round graph probe features.
%
% This is a representation-learnability probe.  Its shared random graph
% encoders are frozen; only a downstream readout is fitted.  It is not the
% final trainable V208 controller.

requiredGraph = {'nodeFeatures', 'nodeFeatureNames', ...
    'edgeFeatures', 'edgeFeatureNames', 'edgeAvailableMask', ...
    'formationCount', 'formationIds', 'truthUsed', ...
    'futureInformationUsed'};
requiredEncoder = {'contractVersion', ...
    'nodeFeatureNames', 'edgeFeatureNames', ...
    'actionFeatureNames', 'nodeFeatureMean', ...
    'nodeFeatureScale', 'edgeFeatureMean', ...
    'edgeFeatureScale', 'actionFeatureMean', ...
    'actionFeatureScale', 'nodeWeight', 'nodeBias', ...
    'baseEdgeWeight', 'baseEdgeBias', ...
    'messageWeight', 'messageBias', ...
    'truthUsed', 'futureInformationUsed'};
if ~isstruct(graph) || ~isscalar(graph) || ...
        ~all(isfield(graph, requiredGraph)) || ...
        ~isstruct(encoder) || ~isscalar(encoder) || ...
        ~all(isfield(encoder, requiredEncoder)) || ...
        graph.truthUsed || graph.futureInformationUsed || ...
        encoder.truthUsed || encoder.futureInformationUsed || ...
        ~strcmp(encoder.contractVersion, ...
            'formation-action-frozen-two-round-encoder-v208-v1') || ...
        ~isequal(reshape(graph.nodeFeatureNames, 1, []), ...
            reshape(encoder.nodeFeatureNames, 1, [])) || ...
        ~isequal(reshape(graph.edgeFeatureNames, 1, []), ...
            reshape(encoder.edgeFeatureNames, 1, []))
    error('FormationActionEncoderV208:ContractMismatch', ...
        'The graph or frozen encoder contract is invalid.');
end
formationCount = graph.formationCount;
nodeInputWidth = size(graph.nodeFeatures, 2);
edgeInputWidth = size(graph.edgeFeatures, 3);
nodeWidth = size(encoder.nodeWeight, 2);
edgeWidth = size(encoder.baseEdgeWeight, 2);
messageWidth = size(encoder.messageWeight, 2);
if size(graph.nodeFeatures, 1) ~= formationCount || ...
        ~isequal(size(graph.edgeFeatures), ...
            [formationCount, formationCount, edgeInputWidth]) || ...
        ~isequal(size(graph.edgeAvailableMask), ...
            [formationCount, formationCount]) || ...
        size(encoder.nodeWeight, 1) ~= nodeInputWidth || ...
        numel(encoder.nodeBias) ~= nodeWidth || ...
        size(encoder.baseEdgeWeight, 1) ~= ...
            edgeInputWidth + 4 * nodeWidth || ...
        numel(encoder.baseEdgeBias) ~= edgeWidth || ...
        size(encoder.messageWeight, 1) ~= 17 * edgeWidth || ...
        numel(encoder.messageBias) ~= messageWidth
    error('FormationActionEncoderV208:DimensionMismatch', ...
        'The graph encoder dimensions are invalid.');
end

rows = reshape(rows, 1, []);
if isempty(rows)
    features = zeros(0, 0);
    details = struct();
    return;
end
requiredRow = {'receiverFormationIndex', ...
    'sourceFormationIndex', 'features', ...
    'truthUsedForFeatures'};
if any(arrayfun(@(row) ...
        ~all(isfield(row, requiredRow)) || ...
        row.truthUsedForFeatures || ...
        row.receiverFormationIndex < 1 || ...
        row.receiverFormationIndex > formationCount || ...
        row.sourceFormationIndex < 1 || ...
        row.sourceFormationIndex > formationCount, rows))
    error('FormationActionEncoderV208:InvalidRows', ...
        'Action rows must map to the truth-free formation graph.');
end
actionX = vertcat(rows.features);
if size(actionX, 2) ~= numel(encoder.actionFeatureNames)
    error('FormationActionEncoderV208:ActionFeatureDrift', ...
        'The action feature width changed.');
end

nodeZ = applyScaler(graph.nodeFeatures, ...
    encoder.nodeFeatureMean, encoder.nodeFeatureScale);
edgeZ = zeros(size(graph.edgeFeatures));
for receiverIdx = 1:formationCount
    page = reshape(graph.edgeFeatures(receiverIdx, :, :), ...
        formationCount, edgeInputWidth);
    edgeZ(receiverIdx, :, :) = reshape(applyScaler(page, ...
        encoder.edgeFeatureMean, encoder.edgeFeatureScale), ...
        1, formationCount, edgeInputWidth);
end
actionZ = applyScaler(actionX, ...
    encoder.actionFeatureMean, encoder.actionFeatureScale);

nodeHidden = tanh(bsxfun(@plus, ...
    nodeZ * encoder.nodeWeight, encoder.nodeBias));
baseEdgeHidden = zeros( ...
    formationCount, formationCount, edgeWidth);
for receiverIdx = 1:formationCount
    for sourceIdx = 1:formationCount
        receiver = nodeHidden(receiverIdx, :);
        source = nodeHidden(sourceIdx, :);
        edge = reshape(edgeZ(receiverIdx, sourceIdx, :), 1, []);
        relational = [edge, receiver, source, ...
            receiver - source, receiver .* source];
        baseEdgeHidden(receiverIdx, sourceIdx, :) = tanh( ...
            relational * encoder.baseEdgeWeight + ...
                encoder.baseEdgeBias);
    end
end

roundZeroContext = poolDirectedEdgeContext( ...
    baseEdgeHidden, graph.edgeAvailableMask);
messageHidden = zeros( ...
    formationCount, formationCount, messageWidth);
for receiverIdx = 1:formationCount
    for sourceIdx = 1:formationCount
        edge = reshape(baseEdgeHidden( ...
            receiverIdx, sourceIdx, :), 1, []);
        receiver = roundZeroContext(receiverIdx, :);
        source = roundZeroContext(sourceIdx, :);
        relational = [edge, receiver, source, ...
            receiver - source, receiver .* source];
        messageHidden(receiverIdx, sourceIdx, :) = tanh( ...
            relational * encoder.messageWeight + ...
                encoder.messageBias);
    end
end
roundOneContext = poolDirectedEdgeContext( ...
    messageHidden, graph.edgeAvailableMask);

nodeSummary = [mean(nodeHidden, 1), max(nodeHidden, [], 1)];
edgeSummary = summarizeAvailableEdges( ...
    messageHidden, graph.edgeAvailableMask);
featureWidth = size(actionZ, 2) + 6 * nodeWidth + ...
    edgeWidth + 19 * messageWidth;
features = zeros(numel(rows), featureWidth);
for rowIdx = 1:numel(rows)
    receiverIdx = rows(rowIdx).receiverFormationIndex;
    sourceIdx = rows(rowIdx).sourceFormationIndex;
    receiverNode = nodeHidden(receiverIdx, :);
    sourceNode = nodeHidden(sourceIdx, :);
    receiverContext = roundOneContext(receiverIdx, :);
    sourceContext = roundOneContext(sourceIdx, :);
    baseEdge = reshape(baseEdgeHidden( ...
        receiverIdx, sourceIdx, :), 1, []);
    messageEdge = reshape(messageHidden( ...
        receiverIdx, sourceIdx, :), 1, []);
    features(rowIdx, :) = [ ...
        actionZ(rowIdx, :), ...
        receiverNode, sourceNode, ...
        receiverNode - sourceNode, ...
        receiverNode .* sourceNode, ...
        baseEdge, messageEdge, ...
        receiverContext, sourceContext, ...
        receiverContext - sourceContext, ...
        receiverContext .* sourceContext, ...
        nodeSummary, edgeSummary];
end
if any(~isfinite(features(:)))
    error('FormationActionEncoderV208:NonfiniteOutput', ...
        'The frozen graph encoder produced nonfinite features.');
end

details = struct();
details.contractVersion = ...
    'formation-action-frozen-two-round-features-v208-v1';
details.featureWidth = featureWidth;
details.nodeHiddenWidth = nodeWidth;
details.baseEdgeHiddenWidth = edgeWidth;
details.messageHiddenWidth = messageWidth;
details.twoDirectedMessagePassingRounds = true;
details.sharedGraphWeights = true;
details.encoderWeightsTrained = false;
details.readoutTrainingRequired = true;
details.truthUsed = false;
details.futureInformationUsed = false;
details.numericIdentifiersUsedAsFeatures = false;
details.finalControllerClaimAllowed = false;
end

function context = poolDirectedEdgeContext(edgeHidden, available)
nodeCount = size(edgeHidden, 1);
hiddenWidth = size(edgeHidden, 3);
context = zeros(nodeCount, 4 * hiddenWidth);
for nodeIdx = 1:nodeCount
    incomingSources = find(available(nodeIdx, :));
    outgoingReceivers = find(available(:, nodeIdx))';
    incoming = reshape(edgeHidden( ...
        nodeIdx, incomingSources, :), [], hiddenWidth);
    outgoing = reshape(edgeHidden( ...
        outgoingReceivers, nodeIdx, :), [], hiddenWidth);
    context(nodeIdx, :) = [ ...
        finiteMeanRows(incoming, hiddenWidth), ...
        finiteMaxRows(incoming, hiddenWidth), ...
        finiteMeanRows(outgoing, hiddenWidth), ...
        finiteMaxRows(outgoing, hiddenWidth)];
end
end

function summary = summarizeAvailableEdges(edgeHidden, available)
hiddenWidth = size(edgeHidden, 3);
values = zeros(nnz(available), hiddenWidth);
cursor = 0;
for receiverIdx = 1:size(available, 1)
    for sourceIdx = 1:size(available, 2)
        if available(receiverIdx, sourceIdx)
            cursor = cursor + 1;
            values(cursor, :) = reshape(edgeHidden( ...
                receiverIdx, sourceIdx, :), 1, []);
        end
    end
end
summary = [finiteMeanRows(values, hiddenWidth), ...
    finiteMaxRows(values, hiddenWidth)];
end

function value = finiteMeanRows(values, width)
if isempty(values)
    value = zeros(1, width);
else
    value = mean(values, 1);
end
end

function value = finiteMaxRows(values, width)
if isempty(values)
    value = zeros(1, width);
else
    value = max(values, [], 1);
end
end

function Z = applyScaler(X, meanValue, scaleValue)
Z = bsxfun(@rdivide, ...
    bsxfun(@minus, X, meanValue), scaleValue);
end
