function evaluation = ...
    evaluateFormationFovMultistyleGeometryValidation(rawAudit, protocol)
% EVALUATEFORMATIONFOVMULTISTYLEGEOMETRYVALIDATION Apply frozen v5 gates.

registeredProtocol = getFormationFovMultistyleGeometryValidationProtocol();
if nargin < 2 || isempty(protocol)
    protocol = registeredProtocol;
end
authenticateProtocol(protocol, registeredProtocol);
validateAuditShape(rawAudit, protocol);

records = reshape(rawAudit.records, 1, []);
absoluteRows = repmat(emptyAbsoluteRow(), 1, numel(records));
for recordIdx = 1:numel(records)
    record = records(recordIdx);
    preset = findPreset(protocol.presets, record.presetName);
    gate = findStyleGate(protocol.absoluteGates, preset.styleName);
    absoluteRows(recordIdx) = evaluateAbsolute(record, preset, gate);
end

styleNames = {protocol.crossScaleGates.styleName};
pairCount = numel(styleNames) * numel(protocol.validationSeeds);
pairedRows = repmat(emptyPairedRow(), 1, pairCount);
pairIdx = 0;
for styleIdx = 1:numel(styleNames)
    styleName = styleNames{styleIdx};
    gate = findStyleGate(protocol.crossScaleGates, styleName);
    for seed = reshape(protocol.validationSeeds, 1, [])
        pairIdx = pairIdx + 1;
        m24 = findAbsoluteRow(absoluteRows, styleName, seed, 24);
        x36 = findAbsoluteRow(absoluteRows, styleName, seed, 36);
        pairedRows(pairIdx) = evaluatePair(m24, x36, gate);
    end
end

evaluation = struct();
evaluation.contractVersion = ...
    'formation-fov-multistyle-geometry-gate-evaluation-v1';
evaluation.protocolCanonicalSha256 = protocol.canonicalSha256;
evaluation.absoluteRows = absoluteRows;
evaluation.pairedRows = pairedRows;
evaluation.allAbsolutePass = all([absoluteRows.gatePassed]);
evaluation.allCrossScalePass = all([pairedRows.gatePassed]);
evaluation.gatePassed = evaluation.allAbsolutePass && ...
    evaluation.allCrossScalePass;
end

function validateAuditShape(rawAudit, protocol)
required = {'presetNames', 'seeds', 'records', 'allValid'};
if ~isstruct(rawAudit) || ~isscalar(rawAudit) || ...
        ~all(isfield(rawAudit, required))
    error('FormationFovGeometryProtocol:InvalidAudit', ...
        'The raw geometry audit is incomplete.');
end
expectedPresets = {protocol.presets.presetName};
if ~isequal(rawAudit.presetNames, expectedPresets) || ...
        ~isequal(reshape(rawAudit.seeds, 1, []), ...
            reshape(protocol.validationSeeds, 1, [])) || ...
        ~isequal(size(rawAudit.records), [ ...
            numel(expectedPresets), numel(protocol.validationSeeds)])
    error('FormationFovGeometryProtocol:ManifestMismatch', ...
        'The audit does not match the frozen preset/seed manifest.');
end
records = reshape(rawAudit.records, 1, []);
if ~islogical(rawAudit.allValid) || ~isscalar(rawAudit.allValid) || ...
        ~all(isfield(records, requiredRecordFields())) || ...
        ~all(arrayfun(@hasValidRecordIdentity, records)) || ...
        ~isequal(rawAudit.allValid, all([records.isValid]))
    error('FormationFovGeometryProtocol:InvalidAudit', ...
        'The raw geometry audit has invalid or inconsistent records.');
end
for presetIdx = 1:numel(protocol.presets)
    preset = protocol.presets(presetIdx);
    for seedIdx = 1:numel(protocol.validationSeeds)
        record = rawAudit.records(presetIdx, seedIdx);
        if ~strcmp(record.presetName, preset.presetName) || ...
                record.seed ~= protocol.validationSeeds(seedIdx) || ...
                record.sensorCount ~= preset.sensorCount || ...
                record.targetCount ~= preset.targetCount
            error('FormationFovGeometryProtocol:ManifestMismatch', ...
                'A record identity does not match its frozen manifest cell.');
        end
    end
end
end

function row = evaluateAbsolute(record, preset, gate)
row = emptyAbsoluteRow();
row.presetName = record.presetName;
row.styleName = preset.styleName;
row.seed = record.seed;
row.sensorCount = record.sensorCount;
row.targetCount = record.targetCount;
row.normalizedHandovers = normalizeHandovers( ...
    record, preset, gate.handoverNormalization);

failures = {};
failures = addFailure(failures, ...
    ~hasValidMetricDomain(record, row.normalizedHandovers), ...
    'invalid-metric-domain');
failures = addFailure(failures, ~record.isValid, 'structural-validation');
failures = addFailure(failures, ...
    record.blackoutFraction > gate.maxBlackoutFraction, ...
    'global-blackout');
failures = addFailure(failures, ...
    record.focusBlackoutFraction > gate.maxFocusBlackoutFraction, ...
    'focus-blackout');
failures = addFailure(failures, ...
    record.maximumPerTargetBlackoutFraction > ...
        gate.maxPerTargetBlackoutFraction, ...
    'worst-target-blackout');
failures = addFailure(failures, ...
    record.maximumConsecutiveBlackoutSteps > ...
        gate.maxConsecutiveBlackoutSteps, ...
    'longest-blackout');
failures = addFailure(failures, ...
    record.singleFormationFraction < gate.minSingleFormationFraction, ...
    'single-formation');
failures = addFailure(failures, ...
    record.multiFormationFraction < gate.minMultiFormationFraction, ...
    'multi-formation');
failures = addFailure(failures, ...
    record.focusMeanVisibleTargetsPerSensorTime < ...
        gate.minFocusVisibleTargetsPerSensorTime || ...
    record.focusMeanVisibleTargetsPerSensorTime > ...
        gate.maxFocusVisibleTargetsPerSensorTime, ...
    'focus-load');
failures = addFailure(failures, ...
    row.normalizedHandovers < gate.minNormalizedHandovers, ...
    'normalized-handovers');
failures = addFailure(failures, ...
    record.ownershipEntropy < gate.minFormationOwnershipEntropy, ...
    'ownership-entropy');
failures = addFailure(failures, ...
    record.blockageFocusOverlapFraction < ...
        gate.minBlockageFocusOverlapFraction, ...
    'blockage-overlap');
failures = addFailure(failures, ...
    record.focusCloseEncounterFraction < ...
        gate.minCrossGroupCloseEncounterFraction, ...
    'cross-group-close-encounter');
failures = addFailure(failures, ...
    record.minimumTargetSeparation < gate.minTargetSeparation, ...
    'target-separation');
failures = addFailure(failures, ...
    record.minimumSensorTargetSeparation < ...
        gate.minSensorTargetSeparation, ...
    'sensor-target-separation');
row.failureTokens = failures;
row.gatePassed = isempty(failures);
row.record = record;
end

function row = evaluatePair(m24, x36, gate)
row = emptyPairedRow();
row.styleName = m24.styleName;
row.seed = m24.seed;
row.m24PresetName = m24.presetName;
row.x36PresetName = x36.presetName;
left = m24.record;
right = x36.record;
row.blackoutDifference = abs( ...
    right.blackoutFraction - left.blackoutFraction);
row.focusBlackoutDifference = abs( ...
    right.focusBlackoutFraction - left.focusBlackoutFraction);
row.worstTargetBlackoutDifference = abs( ...
    right.maximumPerTargetBlackoutFraction - ...
    left.maximumPerTargetBlackoutFraction);
row.longestBlackoutStepDifference = abs( ...
    right.maximumConsecutiveBlackoutSteps - ...
    left.maximumConsecutiveBlackoutSteps);
row.singleFormationDifference = abs( ...
    right.singleFormationFraction - left.singleFormationFraction);
row.multiFormationDifference = abs( ...
    right.multiFormationFraction - left.multiFormationFraction);
row.focusLoadRatio = right.focusMeanVisibleTargetsPerSensorTime / ...
    left.focusMeanVisibleTargetsPerSensorTime;
row.normalizedHandoverDifference = abs( ...
    x36.normalizedHandovers - m24.normalizedHandovers);
row.ownershipEntropyDifference = abs( ...
    right.ownershipEntropy - left.ownershipEntropy);
row.blockageOverlapDifference = abs( ...
    right.blockageFocusOverlapFraction - ...
    left.blockageFocusOverlapFraction);

failures = {};
pairedMetrics = [ ...
    row.blackoutDifference, row.focusBlackoutDifference, ...
    row.worstTargetBlackoutDifference, ...
    row.longestBlackoutStepDifference, ...
    row.singleFormationDifference, row.multiFormationDifference, ...
    row.focusLoadRatio, row.normalizedHandoverDifference, ...
    row.ownershipEntropyDifference, row.blockageOverlapDifference];
failures = addFailure(failures, ...
    ~all(isfinite(pairedMetrics)) || ~isreal(pairedMetrics), ...
    'invalid-paired-metric');
failures = addFailure(failures, ...
    ~m24.gatePassed || ~x36.gatePassed, 'absolute-gate');
failures = addFailure(failures, ...
    row.blackoutDifference > gate.maxBlackoutDifference, ...
    'global-blackout-difference');
failures = addFailure(failures, ...
    row.focusBlackoutDifference > gate.maxFocusBlackoutDifference, ...
    'focus-blackout-difference');
failures = addFailure(failures, ...
    row.worstTargetBlackoutDifference > ...
        gate.maxWorstTargetBlackoutDifference, ...
    'worst-target-blackout-difference');
failures = addFailure(failures, ...
    row.longestBlackoutStepDifference > ...
        gate.maxLongestBlackoutStepDifference, ...
    'longest-blackout-difference');
failures = addFailure(failures, ...
    row.singleFormationDifference > gate.maxSingleFormationDifference, ...
    'single-formation-difference');
failures = addFailure(failures, ...
    row.multiFormationDifference > gate.maxMultiFormationDifference, ...
    'multi-formation-difference');
failures = addFailure(failures, ...
    row.focusLoadRatio < gate.minimumFocusLoadRatio || ...
    row.focusLoadRatio > gate.maximumFocusLoadRatio, ...
    'focus-load-ratio');
failures = addFailure(failures, ...
    row.normalizedHandoverDifference > ...
        gate.maxNormalizedHandoverDifference, ...
    'normalized-handover-difference');
failures = addFailure(failures, ...
    row.ownershipEntropyDifference > ...
        gate.maxOwnershipEntropyDifference, ...
    'ownership-entropy-difference');
failures = addFailure(failures, ...
    row.blockageOverlapDifference > ...
        gate.maxBlockageOverlapDifference, ...
    'blockage-overlap-difference');
row.failureTokens = failures;
row.gatePassed = isempty(failures);
end

function value = normalizeHandovers(record, preset, mode)
switch mode
    case 'targets'
        denominator = preset.targetCount;
    case 'targets-times-formation-transitions'
        denominator = preset.targetCount * (preset.formationCount - 1);
    otherwise
        error('Unknown handover normalization: %s', mode);
end
value = record.focusHandovers / denominator;
end

function authenticateProtocol(protocol, registeredProtocol)
if ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~isfield(protocol, 'canonicalSha256') || ...
        ~ischar(protocol.canonicalSha256)
    error('FormationFovGeometryProtocol:ProtocolMismatch', ...
        'The supplied geometry protocol is not authenticated.');
end
payload = rmfield(protocol, 'canonicalSha256');
registeredPayload = rmfield(registeredProtocol, 'canonicalSha256');
actualSha256 = computeCanonicalValueSha256(payload);
if ~strcmp(actualSha256, protocol.canonicalSha256) || ...
        ~strcmp(actualSha256, registeredProtocol.canonicalSha256) || ...
        ~isequal(payload, registeredPayload)
    error('FormationFovGeometryProtocol:ProtocolMismatch', ...
        'The supplied geometry protocol differs from the frozen registry.');
end
end

function fields = requiredRecordFields()
fields = { ...
    'presetName', 'seed', 'sensorCount', 'targetCount', 'isValid', ...
    'hardFailures', ...
    'blackoutFraction', 'focusBlackoutFraction', ...
    'maximumPerTargetBlackoutFraction', ...
    'maximumConsecutiveBlackoutSteps', ...
    'singleFormationFraction', 'multiFormationFraction', ...
    'focusMeanVisibleTargetsPerSensorTime', 'focusHandovers', ...
    'ownershipEntropy', 'blockageFocusOverlapFraction', ...
    'focusCloseEncounterFraction', 'minimumTargetSeparation', ...
    'minimumSensorTargetSeparation'};
end

function valid = hasValidRecordIdentity(record)
hardFailuresValid = iscell(record.hardFailures);
if hardFailuresValid
    tokenValidity = cellfun(@ischar, record.hardFailures);
    hardFailuresValid = all(tokenValidity(:));
end
valid = ischar(record.presetName) && ...
    isFiniteIntegerScalar(record.seed, 0) && ...
    isFiniteIntegerScalar(record.sensorCount, 1) && ...
    isFiniteIntegerScalar(record.targetCount, 1) && ...
    islogical(record.isValid) && isscalar(record.isValid) && ...
    hardFailuresValid && ...
    isequal(record.isValid, isempty(record.hardFailures));
end

function valid = hasValidMetricDomain(record, normalizedHandovers)
fractions = [ ...
    record.blackoutFraction, record.focusBlackoutFraction, ...
    record.maximumPerTargetBlackoutFraction, ...
    record.singleFormationFraction, record.multiFormationFraction, ...
    record.ownershipEntropy, record.blockageFocusOverlapFraction, ...
    record.focusCloseEncounterFraction];
nonnegative = [ ...
    record.focusMeanVisibleTargetsPerSensorTime, ...
    record.minimumTargetSeparation, ...
    record.minimumSensorTargetSeparation, normalizedHandovers];
fractionPartitionError = abs(record.blackoutFraction + ...
    record.singleFormationFraction + record.multiFormationFraction - 1);
tolerance = 1e-9;
valid = isreal(fractions) && all(isfinite(fractions)) && ...
    all(fractions >= 0 & fractions <= 1) && ...
    fractionPartitionError <= tolerance && ...
    record.maximumPerTargetBlackoutFraction + tolerance >= ...
        record.blackoutFraction && ...
    isreal(nonnegative) && all(isfinite(nonnegative)) && ...
    all(nonnegative >= 0) && ...
    isFiniteIntegerScalar(record.maximumConsecutiveBlackoutSteps, 0) && ...
    isFiniteIntegerScalar(record.focusHandovers, 0);
end

function valid = isFiniteIntegerScalar(value, lowerBound)
valid = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && value >= lowerBound && value == fix(value);
end

function failures = addFailure(failures, failed, token)
if failed
    failures{end+1} = token; %#ok<AGROW>
end
end

function preset = findPreset(presets, presetName)
index = find(strcmp({presets.presetName}, presetName));
if numel(index) ~= 1
    error('FormationFovGeometryProtocol:UnknownPreset', ...
        'Unknown or duplicate preset: %s.', presetName);
end
preset = presets(index);
end

function gate = findStyleGate(gates, styleName)
index = find(strcmp({gates.styleName}, styleName));
if numel(index) ~= 1
    error('FormationFovGeometryProtocol:UnknownStyle', ...
        'Unknown or duplicate style gate: %s.', styleName);
end
gate = gates(index);
end

function row = findAbsoluteRow(rows, styleName, seed, sensorCount)
index = find(strcmp({rows.styleName}, styleName) & ...
    [rows.seed] == seed & [rows.sensorCount] == sensorCount);
if numel(index) ~= 1
    error('FormationFovGeometryProtocol:MissingPair', ...
        'Missing or duplicate scale pair for %s seed %d.', ...
        styleName, seed);
end
row = rows(index);
end

function row = emptyAbsoluteRow()
row = struct( ...
    'presetName', '', ...
    'styleName', '', ...
    'seed', NaN, ...
    'sensorCount', NaN, ...
    'targetCount', NaN, ...
    'normalizedHandovers', NaN, ...
    'gatePassed', false, ...
    'failureTokens', {{}}, ...
    'record', struct());
end

function row = emptyPairedRow()
row = struct( ...
    'styleName', '', ...
    'seed', NaN, ...
    'm24PresetName', '', ...
    'x36PresetName', '', ...
    'blackoutDifference', NaN, ...
    'focusBlackoutDifference', NaN, ...
    'worstTargetBlackoutDifference', NaN, ...
    'longestBlackoutStepDifference', NaN, ...
    'singleFormationDifference', NaN, ...
    'multiFormationDifference', NaN, ...
    'focusLoadRatio', NaN, ...
    'normalizedHandoverDifference', NaN, ...
    'ownershipEntropyDifference', NaN, ...
    'blockageOverlapDifference', NaN, ...
    'gatePassed', false, ...
    'failureTokens', {{}});
end
