function result = evaluateFormationB4V46TrackingOutcomeMatrix( ...
    records, evaluation, phase)
% EVALUATEFORMATIONB4V46TRACKINGOUTCOMEMATRIX Pure frozen gate evaluator.
%
% Inputs are minimal paired case summaries produced only after the external
% runtime and scoring authorization chain has passed.  This function cannot
% authorize execution or confirmation; it deterministically evaluates the
% already-opened summaries under the frozen registry.

validateEvaluation(evaluation);
if ~(ischar(phase) && isrow(phase))
    error('FormationB4V46TrackingOutcome:InvalidPhase', ...
        'phase must be development or confirmation.');
end
phase = lower(strtrim(phase));
if strcmp(phase, 'development')
    requiredOrdinals = [evaluation.developmentPrimaryCaseOrdinals, ...
        evaluation.developmentStressCaseOrdinals];
elseif strcmp(phase, 'confirmation')
    requiredOrdinals = [ ...
        reshape(evaluation.confirmationAnalysis. ...
            primaryCaseOrdinalMatrix, 1, []), ...
        reshape(evaluation.confirmationAnalysis. ...
            stressCaseOrdinalMatrix, 1, [])];
else
    error('FormationB4V46TrackingOutcome:InvalidPhase', ...
        'phase must be development or confirmation.');
end
requiredOrdinals = sort(requiredOrdinals);
records = validateAndOrderRecords( ...
    records, evaluation, requiredOrdinals);
caseResults = buildCaseResults(records, evaluation);

payload = struct();
payload.id = sprintf( ...
    'formation-b4-v46-tracking-%s-evaluation-v1', phase);
payload.contractVersion = ...
    'formation-b4-v46-tracking-outcome-evaluation-v1';
payload.phase = phase;
payload.evaluationRegistryId = evaluation.id;
payload.evaluationRegistryCanonicalSha256 = ...
    evaluation.canonicalSha256;
payload.referenceArmId = evaluation.referenceArmId;
payload.candidateArmId = evaluation.candidateArmId;
payload.orderedCaseOrdinals = [records.caseOrdinal];
payload.caseResults = caseResults;
payload.development = struct();
payload.confirmation = struct();
if strcmp(phase, 'development')
    payload.development = evaluateBlock( ...
        caseResults, evaluation.developmentPrimaryCaseOrdinals, ...
        evaluation.developmentStressCaseOrdinals, ...
        evaluation.developmentThresholds);
    payload.developmentAdvanceRulePassed = ...
        payload.development.passed;
    payload.confirmationRulePassed = false;
else
    confirmation = evaluation.confirmationAnalysis;
    blockCells = cell(1, confirmation.independentSeedCount);
    for seedIdx = 1:confirmation.independentSeedCount
        block = evaluateBlock( ...
            caseResults, ...
            confirmation.primaryCaseOrdinalMatrix(seedIdx, :), ...
            confirmation.stressCaseOrdinalMatrix(seedIdx, :), ...
            confirmation.perSeedPrimaryRule);
        block.seed = ...
            confirmation.orderedConfirmationSeeds(seedIdx);
        blockCells{seedIdx} = block;
    end
    blocks = [blockCells{:}];
    payload.confirmation.seedBlocks = blocks;
    payload.confirmation.requiredPassingSeedBlockCount = ...
        confirmation.requiredPassingSeedBlockCount;
    payload.confirmation.passingSeedBlockCount = sum([blocks.passed]);
    payload.confirmation.allSeedBlocksPassed = ...
        all([blocks.passed]);
    payload.confirmation.descriptive = buildDescriptiveSummary( ...
        caseResults, evaluation);
    payload.confirmation.rulePassed = ...
        payload.confirmation.allSeedBlocksPassed && ...
        payload.confirmation.descriptive. ...
            allDescriptiveMetricsDefined;
    payload.developmentAdvanceRulePassed = false;
    payload.confirmationRulePassed = ...
        payload.confirmation.rulePassed;
end
payload.filterExecutionAuthorized = false;
payload.confirmationTrackingAuthorized = false;
payload.developmentAdvanceDecisionAuthorized = false;
payload.validationClaimAllowed = false;
payload.populationGeneralizationAllowed = false;
payload.statisticalSignificanceClaimAllowed = false;
payload.evidenceBoundary = [ ...
    'This pure evaluator applies the frozen fixed-matrix rules to ', ...
    'already-authorized paired summaries. A passing boolean is not an ', ...
    'execution permit, a confirmation permit, an independently frozen ', ...
    'advance decision, a population inference, a significance result, ', ...
    'or a validation claim.'];
result = payload;
result.canonicalSha256 = computeCanonicalValueSha256(payload);
end

function validateEvaluation(evaluation)
required = {'canonicalSha256', 'id', 'referenceArmId', ...
    'candidateArmId', 'pairedSummaryRecordContractVersion', ...
    'descriptiveMetricSpecs', 'allDescriptiveMetricsMustBeReported', ...
    'developmentPrimaryCaseOrdinals', ...
    'developmentStressCaseOrdinals', 'developmentThresholds', ...
    'confirmationAnalysis', 'cases', 'caseCount'};
for idx = 1:numel(required)
    if ~isstruct(evaluation) || ~isfield(evaluation, required{idx})
        error('FormationB4V46TrackingOutcome:EvaluationSchema', ...
            'The evaluation registry is missing %s.', required{idx});
    end
end
official = getFormationB4V46TrackingEvaluationRegistry();
if ~strcmp(computeCanonicalValueSha256( ...
        rmfield(evaluation, 'canonicalSha256')), ...
        evaluation.canonicalSha256) || ...
        ~evaluation.allDescriptiveMetricsMustBeReported || ...
        ~strcmp(evaluation.id, official.id) || ...
        ~strcmp(evaluation.canonicalSha256, ...
            official.canonicalSha256) || ...
        ~isequaln(evaluation, official)
    error('FormationB4V46TrackingOutcome:EvaluationDrift', ...
        'The evaluation object is not the official frozen registry.');
end
end

function records = validateAndOrderRecords( ...
    records, evaluation, requiredOrdinals)
if ~isstruct(records) || ~isvector(records) || ...
        numel(records) ~= numel(requiredOrdinals)
    error('FormationB4V46TrackingOutcome:RecordCoverage', ...
        'The phase requires one paired record per registered case.');
end
ordinals = [records.caseOrdinal];
if numel(unique(ordinals)) ~= numel(ordinals) || ...
        ~isequal(sort(ordinals), requiredOrdinals)
    error('FormationB4V46TrackingOutcome:RecordCoverage', ...
        'Paired record ordinals are missing, duplicated, or unauthorized.');
end
[~, order] = sort(ordinals);
records = records(order);
recordFields = {'contractVersion', 'caseOrdinal', 'caseId', ...
    'referenceArmId', 'candidateArmId', 'runtimeAuditPassed', ...
    'reference', 'candidate'};
armFields = armSummaryFields();
for recordIdx = 1:numel(records)
    record = records(recordIdx);
    assertExactFields(record, recordFields, 'paired record');
    if ~strcmp(record.contractVersion, ...
            evaluation.pairedSummaryRecordContractVersion) || ...
            ~isa(record.caseOrdinal, 'double') || ...
            ~isscalar(record.caseOrdinal) || ...
            record.caseOrdinal ~= floor(record.caseOrdinal) || ...
            ~ischar(record.caseId) || ~isrow(record.caseId) || ...
            ~strcmp(record.referenceArmId, evaluation.referenceArmId) || ...
            ~strcmp(record.candidateArmId, evaluation.candidateArmId) || ...
            ~islogical(record.runtimeAuditPassed) || ...
            ~isscalar(record.runtimeAuditPassed)
        error('FormationB4V46TrackingOutcome:RecordSchema', ...
            'Paired record %d violates its frozen schema.', recordIdx);
    end
    caseContract = evaluation.cases(record.caseOrdinal);
    if caseContract.caseOrdinal ~= record.caseOrdinal || ...
            ~strcmp(caseContract.caseId, record.caseId)
        error('FormationB4V46TrackingOutcome:CaseIdentity', ...
            'Paired record %d has the wrong case identity.', recordIdx);
    end
    assertExactFields(record.reference, armFields, ...
        'reference arm summary');
    assertExactFields(record.candidate, armFields, ...
        'candidate arm summary');
    validateArmSummary(record.reference, caseContract, 'reference');
    validateArmSummary(record.candidate, caseContract, 'candidate');
end
end

function fields = armSummaryFields()
fields = {'attemptedMessageCount', 'deliveredMessageCount', ...
    'attemptedPayloadScalars', 'deliveredPayloadScalars', ...
    'attemptedPayloadBytes', 'deliveredPayloadBytes', ...
    'fullHorizonPositionEospa', 'focusWindowPositionEospa', ...
    'worstSensorPositionEospa', 'meanAbsoluteCardinalityError', ...
    'meanConsensusPositionOspa', 'terminalConsensusPositionOspa', ...
    'repairPageCount', 'firstRepairTime'};
end

function validateArmSummary(summary, caseContract, armName)
fields = armSummaryFields();
for fieldIdx = 1:numel(fields)
    value = summary.(fields{fieldIdx});
    if ~isa(value, 'double') || ~isreal(value) || ...
            ~isscalar(value) || ~isfinite(value) || value < 0
        error('FormationB4V46TrackingOutcome:RawSummaryValue', ...
            '%s %s must be one finite nonnegative double.', ...
            armName, fields{fieldIdx});
    end
end
integerFields = {'attemptedMessageCount', 'deliveredMessageCount', ...
    'attemptedPayloadScalars', 'deliveredPayloadScalars', ...
    'repairPageCount', 'firstRepairTime'};
for fieldIdx = 1:numel(integerFields)
    value = summary.(integerFields{fieldIdx});
    if value ~= floor(value)
        error('FormationB4V46TrackingOutcome:RawSummaryValue', ...
            '%s %s must be integer-valued.', ...
            armName, integerFields{fieldIdx});
    end
end
if summary.deliveredMessageCount > summary.attemptedMessageCount || ...
        summary.deliveredPayloadScalars > ...
            summary.attemptedPayloadScalars || ...
        summary.attemptedPayloadBytes ~= ...
            8 * summary.attemptedPayloadScalars || ...
        summary.deliveredPayloadBytes ~= ...
            8 * summary.deliveredPayloadScalars || ...
        summary.repairPageCount > caseContract.simulationLength || ...
        summary.firstRepairTime > caseContract.simulationLength || ...
        (summary.repairPageCount == 0 && ...
            summary.firstRepairTime ~= 0) || ...
        (summary.repairPageCount > 0 && ...
            summary.firstRepairTime < 1)
    error('FormationB4V46TrackingOutcome:RawSummaryConsistency', ...
        '%s arm summary is internally inconsistent.', armName);
end
end

function assertExactFields(value, expected, description)
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)), sort(reshape(expected, [], 1)))
    error('FormationB4V46TrackingOutcome:ExactSchema', ...
        '%s does not have the exact frozen field set.', description);
end
end

function results = buildCaseResults(records, evaluation)
template = struct('caseOrdinal', NaN, 'caseId', '', ...
    'runtimeAuditPassed', false, 'reference', struct(), ...
    'candidate', struct(), 'changes', struct(), ...
    'absoluteChanges', struct(), ...
    'changeDefined', struct(), 'allChangesDefined', false);
results = repmat(template, 1, numel(records));
for recordIdx = 1:numel(records)
    record = records(recordIdx);
    changes = struct();
    absoluteChanges = struct();
    defined = struct();
    specs = evaluation.descriptiveMetricSpecs;
    for metricIdx = 1:numel(specs)
        spec = specs(metricIdx);
        reference = record.reference.(spec.armSummaryField);
        candidate = record.candidate.(spec.armSummaryField);
        [changes.(spec.id), defined.(spec.id), ...
            absoluteChanges.(spec.id)] = ...
            computeSignedChange(reference, candidate, spec.changeType);
    end
    value = template;
    value.caseOrdinal = record.caseOrdinal;
    value.caseId = record.caseId;
    value.runtimeAuditPassed = record.runtimeAuditPassed;
    value.reference = record.reference;
    value.candidate = record.candidate;
    value.changes = changes;
    value.absoluteChanges = absoluteChanges;
    value.changeDefined = defined;
    value.allChangesDefined = all(cell2mat(struct2cell(defined)));
    results(recordIdx) = value;
end
end

function [change, defined, absoluteChange] = ...
    computeSignedChange(reference, candidate, type)
absoluteChange = candidate - reference;
if strcmp(type, 'saving-positive-is-favorable')
    if reference > 0
        change = (reference - candidate) / reference;
        defined = isfinite(change);
    else
        change = NaN;
        defined = false;
    end
elseif strcmp(type, 'increase-positive-is-harm')
    if reference > 0
        change = (candidate - reference) / reference;
        defined = isfinite(change);
    elseif candidate == 0
        change = 0;
        defined = true;
    else
        change = NaN;
        defined = false;
    end
else
    error('FormationB4V46TrackingOutcome:MetricSpec', ...
        'Unknown signed-change type: %s.', type);
end
end

function block = evaluateBlock( ...
    caseResults, primaryOrdinals, stressOrdinals, thresholds)
primary = selectResults(caseResults, primaryOrdinals);
stress = selectResults(caseResults, stressOrdinals);
messageSavings = collectChanges(primary, 'attemptedMessageSaving');
byteSavings = collectChanges(primary, 'attemptedByteSaving');
fullChanges = collectChanges(primary, ...
    'fullHorizonPositionEospaIncrease');
focusChanges = collectChanges(primary, ...
    'focusWindowPositionEospaIncrease');
worstChanges = collectChanges(primary, ...
    'worstSensorPositionEospaIncrease');
consensusChanges = collectChanges(primary, ...
    'meanConsensusPositionOspaIncrease');

block = struct();
block.primaryCaseOrdinals = primaryOrdinals;
block.stressCaseOrdinals = stressOrdinals;
block.allRuntimeAuditsPassed = ...
    all([primary.runtimeAuditPassed]) && ...
    all([stress.runtimeAuditPassed]);
block.allPrimaryChangesDefined = all([primary.allChangesDefined]);
block.allStressChangesDefinedForDescription = ...
    all([stress.allChangesDefined]);
block.allChangesDefined = block.allPrimaryChangesDefined;
block.attemptedMessageSavingPerPair = messageSavings;
block.attemptedByteSavingPerPair = byteSavings;
block.fullHorizonPositionEospaIncreasePerPair = fullChanges;
block.focusWindowPositionEospaIncreasePerPair = focusChanges;
block.worstSensorPositionEospaIncreasePerPair = worstChanges;
block.meanConsensusPositionOspaIncreasePerPair = consensusChanges;
block.attemptedByteSavingPrimaryMedian = strictMedian(byteSavings);
block.fullHorizonPositionEospaIncreasePrimaryMedian = ...
    strictMedian(fullChanges);
block.exactMessageSavingPassed = allDefined(messageSavings) && ...
    all(abs(messageSavings - ...
        thresholds.attemptedMessageSavingExact) <= ...
        thresholds.attemptedMessageSavingTolerance);
block.attemptedBytePerPairPassed = allDefined(byteSavings) && ...
    all(byteSavings >= ...
        thresholds.attemptedByteSavingPerPairMinimum);
block.attemptedByteMedianPassed = ...
    isfinite(block.attemptedByteSavingPrimaryMedian) && ...
    block.attemptedByteSavingPrimaryMedian >= ...
        thresholds.attemptedByteSavingPrimaryMedianMinimum;
block.fullHorizonPerPairPassed = allDefined(fullChanges) && ...
    all(fullChanges <= ...
        thresholds.fullHorizonEospaIncreasePerPairMaximum);
block.fullHorizonMedianPassed = ...
    isfinite(block.fullHorizonPositionEospaIncreasePrimaryMedian) && ...
    block.fullHorizonPositionEospaIncreasePrimaryMedian <= ...
        thresholds.fullHorizonEospaIncreasePrimaryMedianMaximum;
block.focusWindowPerPairPassed = allDefined(focusChanges) && ...
    all(focusChanges <= ...
        thresholds.focusWindowEospaIncreasePerPairMaximum);
block.worstSensorPerPairPassed = allDefined(worstChanges) && ...
    all(worstChanges <= ...
        thresholds.worstSensorEospaIncreasePerPairMaximum);
block.meanConsensusPerPairPassed = allDefined(consensusChanges) && ...
    all(consensusChanges <= ...
        thresholds.meanConsensusOspaIncreasePerPairMaximum);
block.stressCompletionPassed = ...
    all([stress.runtimeAuditPassed]);
block.passed = block.allRuntimeAuditsPassed && ...
    block.allChangesDefined && block.exactMessageSavingPassed && ...
    block.attemptedBytePerPairPassed && ...
    block.attemptedByteMedianPassed && ...
    block.fullHorizonPerPairPassed && ...
    block.fullHorizonMedianPassed && ...
    block.focusWindowPerPairPassed && ...
    block.worstSensorPerPairPassed && ...
    block.meanConsensusPerPairPassed && ...
    block.stressCompletionPassed;
end

function selected = selectResults(results, ordinals)
selected = repmat(results(1), 1, numel(ordinals));
for ordinalIdx = 1:numel(ordinals)
    match = find([results.caseOrdinal] == ordinals(ordinalIdx));
    if numel(match) ~= 1
        error('FormationB4V46TrackingOutcome:InternalCoverage', ...
            'A required evaluated case is missing or duplicated.');
    end
    selected(ordinalIdx) = results(match);
end
end

function changes = collectChanges(results, fieldName)
changes = NaN(1, numel(results));
for resultIdx = 1:numel(results)
    changes(resultIdx) = results(resultIdx).changes.(fieldName);
end
end

function tf = allDefined(values)
tf = all(isfinite(values));
end

function value = strictMedian(values)
if any(~isfinite(values)) || isempty(values)
    value = NaN;
else
    value = median(values);
end
end

function descriptive = buildDescriptiveSummary(caseResults, evaluation)
confirmation = evaluation.confirmationAnalysis;
specs = evaluation.descriptiveMetricSpecs;
metricTemplate = struct('id', '', 'changeType', '', ...
    'caseRelativeChanges', [], 'caseAbsoluteChanges', [], ...
    'caseChangeDefined', [], 'undefinedCaseOrdinals', [], ...
    'seedBlockValues', [], 'grandMean', NaN, 'grandMedian', NaN, ...
    'observedSeedRange', [NaN, NaN], ...
    'leaveOneSeedOutMeans', [], ...
    'leaveOneSeedOutMeanRange', [NaN, NaN], ...
    'scaleSeedValues', [], 'absoluteSeedBlockMeans', [], ...
    'absoluteScaleSeedMeans', []);
metrics = repmat(metricTemplate, 1, numel(specs));
allDefinedFlag = true;
for metricIdx = 1:numel(specs)
    spec = specs(metricIdx);
    caseRelativeChanges = NaN(confirmation.independentSeedCount, ...
        confirmation.fixedPrimaryStratumCount);
    caseAbsoluteChanges = NaN(size(caseRelativeChanges));
    caseChangeDefined = false(size(caseRelativeChanges));
    seedValues = NaN(1, confirmation.independentSeedCount);
    scaleSeedValues = NaN(confirmation.independentSeedCount, 2);
    absoluteSeedBlockMeans = NaN(1, ...
        confirmation.independentSeedCount);
    absoluteScaleSeedMeans = NaN( ...
        confirmation.independentSeedCount, 2);
    for seedIdx = 1:confirmation.independentSeedCount
        rowResults = selectResults(caseResults, ...
            confirmation.primaryCaseOrdinalMatrix(seedIdx, :));
        rowChanges = collectChanges(rowResults, spec.id);
        rowAbsoluteChanges = NaN(1, numel(rowResults));
        rowDefined = false(1, numel(rowResults));
        for sceneIdx = 1:numel(rowResults)
            rowAbsoluteChanges(sceneIdx) = ...
                rowResults(sceneIdx).absoluteChanges.(spec.id);
            rowDefined(sceneIdx) = ...
                rowResults(sceneIdx).changeDefined.(spec.id);
        end
        caseRelativeChanges(seedIdx, :) = rowChanges;
        caseAbsoluteChanges(seedIdx, :) = rowAbsoluteChanges;
        caseChangeDefined(seedIdx, :) = rowDefined;
        absoluteSeedBlockMeans(seedIdx) = mean(rowAbsoluteChanges);
        if all(isfinite(rowChanges))
            seedValues(seedIdx) = mean(rowChanges);
        end
        for scaleIdx = 1:size(confirmation.scaleColumnGroups, 1)
            columns = confirmation.scaleColumnGroups(scaleIdx, :);
            if all(isfinite(rowChanges(columns)))
                scaleSeedValues(seedIdx, scaleIdx) = ...
                    mean(rowChanges(columns));
            end
            absoluteScaleSeedMeans(seedIdx, scaleIdx) = ...
                mean(rowAbsoluteChanges(columns));
        end
    end
    value = metricTemplate;
    value.id = spec.id;
    value.changeType = spec.changeType;
    value.caseRelativeChanges = caseRelativeChanges;
    value.caseAbsoluteChanges = caseAbsoluteChanges;
    value.caseChangeDefined = caseChangeDefined;
    value.undefinedCaseOrdinals = reshape( ...
        confirmation.primaryCaseOrdinalMatrix(~caseChangeDefined), 1, []);
    value.seedBlockValues = seedValues;
    value.scaleSeedValues = scaleSeedValues;
    value.absoluteSeedBlockMeans = absoluteSeedBlockMeans;
    value.absoluteScaleSeedMeans = absoluteScaleSeedMeans;
    if all(isfinite(seedValues))
        value.grandMean = mean(seedValues);
        value.grandMedian = median(seedValues);
        value.observedSeedRange = [min(seedValues), max(seedValues)];
        leaveOneOut = NaN(1, confirmation.independentSeedCount);
        for omittedIdx = 1:confirmation.independentSeedCount
            leaveOneOut(omittedIdx) = mean( ...
                seedValues((1:end) ~= omittedIdx));
        end
        value.leaveOneSeedOutMeans = leaveOneOut;
        value.leaveOneSeedOutMeanRange = ...
            [min(leaveOneOut), max(leaveOneOut)];
    else
        value.leaveOneSeedOutMeans = ...
            NaN(1, confirmation.independentSeedCount);
        allDefinedFlag = false;
    end
    metrics(metricIdx) = value;
end
descriptive = struct();
descriptive.metricIds = {specs.id};
descriptive.metrics = metrics;
descriptive.allDescriptiveMetricsReported = ...
    numel(metrics) == numel(specs);
descriptive.allDescriptiveMetricsDefined = ...
    allDefinedFlag && descriptive.allDescriptiveMetricsReported;
descriptive.summaryType = confirmation.descriptiveSummary;
descriptive.isConfidenceInterval = false;
descriptive.populationInferenceAllowed = false;
end
