function gate = evaluateFormationStaggeredRecoveryM24V36Gate( ...
        stateSummaries, protocol)
% EVALUATEFORMATIONSTAGGEREDRECOVERYM24V36GATE Frozen replication gate.

requiredFields = { ...
    'strictStrong', 'meanGainPercent', ...
    'terminalConsensusGainPercent'};
if ~isstruct(stateSummaries) || ...
        numel(stateSummaries) ~= numel(protocol.anchorTimes) || ...
        ~all(isfield(stateSummaries, requiredFields))
    error('V36Gate:InvalidStateSummary', ...
        'The v36 replication gate requires one summary per anchor.');
end

strictStrongMask = logical(reshape( ...
    [stateSummaries.strictStrong], 1, []));
meanGainPercent = reshape( ...
    [stateSummaries.meanGainPercent], 1, []);
terminalConsensusGainPercent = reshape( ...
    [stateSummaries.terminalConsensusGainPercent], 1, []);
if any(~isfinite(meanGainPercent)) || ...
        any(~isfinite(terminalConsensusGainPercent))
    error('V36Gate:InvalidStateSummary', ...
        'The v36 replication metrics must be finite.');
end

gate = struct();
gate.contractVersion = ...
    'formation-staggered-recovery-m24-v36-gate-v1';
gate.strictStrongMask = strictStrongMask;
gate.strongStateCount = nnz(strictStrongMask);
gate.meanGainPercentByState = meanGainPercent;
gate.medianMeanGainPercent = median(meanGainPercent);
gate.minimumStateMeanGainPercent = min(meanGainPercent);
gate.terminalConsensusGainPercentByState = ...
    terminalConsensusGainPercent;
gate.positiveTerminalConsensusMask = ...
    terminalConsensusGainPercent > 0;
gate.positiveTerminalConsensusStateCount = ...
    nnz(gate.positiveTerminalConsensusMask);
gate.strongCountPassed = gate.strongStateCount >= ...
    protocol.minimumStrongReplicationStateCount;
gate.medianMeanGainPassed = gate.medianMeanGainPercent >= ...
    protocol.minimumMedianMeanGainPercent - 1e-12;
gate.minimumStateMeanGainPassed = ...
    gate.minimumStateMeanGainPercent >= ...
        protocol.minimumStateMeanGainPercent - 1e-12;
gate.positiveTerminalCountPassed = ...
    gate.positiveTerminalConsensusStateCount >= ...
        protocol.minimumPositiveTerminalStateCount;
gate.passed = all([ ...
    gate.strongCountPassed, ...
    gate.medianMeanGainPassed, ...
    gate.minimumStateMeanGainPassed, ...
    gate.positiveTerminalCountPassed]);
end
