function [posteriors, history] = ...
    extractBehaviorContinuationSnapshot( ...
        bundle, snapshotTime, sensorCount)
% EXTRACTBEHAVIORCONTINUATIONSNAPSHOT Validate and extract cache state.

contract = behaviorContinuationCacheContract();
required = { ...
    'cacheContractVersion', 'posteriorSnapshotConvention', ...
    'topologyHistoryDepth', 'topologyHistoryConvention', ...
    'posteriorSnapshots', 'preDecisionTopologyHistoryByTime'};
if ~isstruct(bundle) || ~all(isfield(bundle, required))
    error('BehaviorCache:LegacyContract', ...
        'Continuation cache does not implement the v2 history contract.');
end
if ~strcmp(bundle.cacheContractVersion, contract.version) || ...
        ~strcmp(bundle.posteriorSnapshotConvention, ...
            contract.posteriorSnapshotConvention) || ...
        bundle.topologyHistoryDepth ~= contract.topologyHistoryDepth || ...
        ~strcmp(bundle.topologyHistoryConvention, ...
            contract.topologyHistoryConvention)
    error('BehaviorCache:ContractMismatch', ...
        'Continuation cache history contract does not match.');
end
if snapshotTime < 1 || mod(snapshotTime, 1) ~= 0 || ...
        numel(bundle.posteriorSnapshots) < snapshotTime || ...
        isempty(bundle.posteriorSnapshots{snapshotTime}) || ...
        numel(bundle.preDecisionTopologyHistoryByTime) < snapshotTime || ...
        isempty(bundle.preDecisionTopologyHistoryByTime{snapshotTime})
    error('BehaviorCache:MissingSnapshot', ...
        'Continuation cache is missing the requested snapshot/history.');
end
posteriors = bundle.posteriorSnapshots{snapshotTime};
if numel(posteriors) ~= sensorCount
    error('BehaviorCache:PosteriorShape', ...
        'Continuation posterior snapshot has the wrong sensor count.');
end
history = bundle.preDecisionTopologyHistoryByTime{snapshotTime};
historyRequired = { ...
    'snapshotTime', 'times', 'selectedDirectedEdgeHistory', ...
    'deliveredDirectedEdgeHistory', 'source'};
if ~isstruct(history) || ~all(isfield(history, historyRequired)) || ...
        history.snapshotTime ~= snapshotTime || ...
        ~strcmp(history.source, 'behavior-filter-diagnostics')
    error('BehaviorCache:HistoryRecord', ...
        'Continuation topology-history record is invalid.');
end
expectedCount = min( ...
    contract.topologyHistoryDepth, snapshotTime - 1);
expectedTimes = ...
    (snapshotTime - expectedCount):(snapshotTime - 1);
if expectedCount == 0
    expectedTimes = [];
end
if ~isequal(reshape(history.times, 1, []), ...
        reshape(expectedTimes, 1, []))
    error('BehaviorCache:HistoryTimes', ...
        'Continuation topology-history timestamps are invalid.');
end
validateHistoryTensor( ...
    history.selectedDirectedEdgeHistory, ...
    sensorCount, expectedCount, 'selected');
validateHistoryTensor( ...
    history.deliveredDirectedEdgeHistory, ...
    sensorCount, expectedCount, 'delivered');
selected = logical(history.selectedDirectedEdgeHistory);
delivered = logical(history.deliveredDirectedEdgeHistory);
if any(delivered(:) & ~selected(:))
    error('BehaviorCache:DeliverySubset', ...
        'Delivered continuation edges are not a subset of selected edges.');
end
history.selectedDirectedEdgeHistory = selected;
history.deliveredDirectedEdgeHistory = delivered;
end

function validateHistoryTensor(value, sensorCount, pageCount, name)
if size(value, 1) ~= sensorCount || ...
        size(value, 2) ~= sensorCount || ...
        size(value, 3) ~= pageCount
    error('BehaviorCache:HistoryShape', ...
        'Continuation %s history has an invalid shape.', name);
end
for pageIdx = 1:pageCount
    if any(diag(value(:, :, pageIdx)))
        error('BehaviorCache:SelfEdge', ...
            'Continuation %s history contains a self edge.', name);
    end
end
end
