function [model, summary] = fitCounterfactualRegretGateV133( ...
        development, calibration, protocol, modelSpec)
% FITCOUNTERFACTUALREGRETGATEV133 Conservative shared-scale harm gate.

if nargin < 3 || isempty(protocol)
    protocol = getCounterfactualRegretGateV133Protocol();
end
if nargin < 4 || isempty(modelSpec)
    modelSpec = getCounterfactualRegretGateV133ModelSpec();
end
validateBundle(development, 'development', protocol, modelSpec);
validateBundle(calibration, 'calibration', protocol, modelSpec);
if ~isempty(intersect( ...
        unique(development.trajectoryKey), ...
        unique(calibration.trajectoryKey)))
    error('CounterfactualRegretV133:TrajectoryLeakage', ...
        'Development and calibration trajectories overlap.');
end
if numel(unique(development.y)) < 2
    error('CounterfactualRegretV133:DegenerateTeacherLabels', ...
        'Development labels contain only one class.');
end

featureCenter = weightedMean( ...
    development.X, development.sampleWeight);
featureScale = weightedScale( ...
    development.X, featureCenter, development.sampleWeight, ...
    modelSpec.minimumSupportSpan);
developmentZ = bsxfun(@rdivide, ...
    bsxfun(@minus, development.X, featureCenter), featureScale);
calibrationZ = bsxfun(@rdivide, ...
    bsxfun(@minus, calibration.X, featureCenter), featureScale);
[intercept, coefficient, optimization] = fitProjectedLogistic( ...
    developmentZ, double(development.y), ...
    development.sampleWeight, modelSpec);
developmentProbability = logistic( ...
    intercept + developmentZ * coefficient, ...
    modelSpec.probabilityClip);
calibrationProbability = logistic( ...
    intercept + calibrationZ * coefficient, ...
    modelSpec.probabilityClip);

supportLower = min(developmentZ, [], 1);
supportUpper = max(developmentZ, [], 1);
supportSpan = max(supportUpper - supportLower, ...
    modelSpec.minimumSupportSpan);
supportLower = supportLower - ...
    modelSpec.supportMarginFraction * supportSpan;
supportUpper = supportUpper + ...
    modelSpec.supportMarginFraction * supportSpan;
calibrationInSupport = all(bsxfun(@ge, ...
    calibrationZ, supportLower) & bsxfun(@le, ...
    calibrationZ, supportUpper), 2);
[threshold, calibrationReadout, thresholdTrace] = ...
    calibrateThreshold( ...
        calibrationProbability, calibration, ...
        calibrationInSupport, protocol, modelSpec);
developmentInSupport = true(size(development.y));
developmentReadout = evaluateThreshold( ...
    developmentProbability, development, ...
    developmentInSupport, threshold, protocol);

model = struct();
model.contractVersion = ...
    'counterfactual-regret-gate-v133-model-v1';
model.protocolId = protocol.id;
model.modelSpecId = modelSpec.id;
model.family = modelSpec.family;
model.featureNames = modelSpec.featureNames;
model.featureContractSha256 = modelSpec.featureContractSha256;
model.featureCenter = featureCenter;
model.featureScale = featureScale;
model.coefficient = reshape(coefficient, 1, []);
model.intercept = intercept;
model.monotoneDirection = modelSpec.monotoneDirection;
model.ridgeLambda = modelSpec.ridgeLambda;
model.harmProbabilityThreshold = threshold;
model.supportLowerStandardized = supportLower;
model.supportUpperStandardized = supportUpper;
model.outOfSupportAction = protocol.uncertainAction;
model.uncertainAction = protocol.uncertainAction;
model.sharedAcrossScales = true;
model.gnnUsed = false;
model.calibrationReadout = calibrationReadout;
model.modelTrainingAuthorized = calibrationReadout.gatePassed;
model.validationClaimAllowed = false;
model.policyTruthUsed = false;
model.policyFutureOutcomeUsed = false;
model.teacherTruthUsedOfflineOnly = true;
model.teacherFutureOutcomeUsedOfflineOnly = true;

summary = struct();
summary.contractVersion = ...
    'counterfactual-regret-gate-v133-fit-summary-v1';
summary.protocolId = protocol.id;
summary.modelSpecId = modelSpec.id;
summary.developmentExampleCount = development.exampleCount;
summary.calibrationExampleCount = calibration.exampleCount;
summary.developmentTrajectoryCount = development.trajectoryCount;
summary.calibrationTrajectoryCount = calibration.trajectoryCount;
summary.developmentPrevalence = mean(development.y);
summary.calibrationPrevalence = mean(calibration.y);
summary.optimization = optimization;
summary.developmentLogLoss = logLoss( ...
    developmentProbability, development.y, development.sampleWeight);
summary.calibrationLogLoss = logLoss( ...
    calibrationProbability, calibration.y, calibration.sampleWeight);
summary.development = developmentReadout;
summary.calibration = calibrationReadout;
summary.calibrationInSupportFraction = mean(calibrationInSupport);
summary.harmProbabilityThreshold = threshold;
summary.thresholdTrace = thresholdTrace;
summary.teacherGatePassed = calibrationReadout.gatePassed;
summary.modelTrainingAuthorized = summary.teacherGatePassed;
summary.validationClaimAllowed = false;
end

function validateBundle(bundle, split, protocol, modelSpec)
required = { ...
    'contractVersion', 'protocolId', 'evidenceSplit', ...
    'modelFeatureNames', 'modelFeatureContractSha256', ...
    'X', 'y', 'actionGainPercent', 'scaleName', ...
    'trajectoryKey', 'sampleWeight', 'exampleCount', ...
    'trajectoryCount', 'truthUsedAsFeature', ...
    'futureOutcomeUsedAsFeature', 'seedIdentifierUsedAsFeature', ...
    'absoluteTimeUsedAsFeature', ...
    'fixedFormationIdentifierUsedAsFeature'};
if ~isstruct(bundle) || ~isscalar(bundle) || ...
        ~all(isfield(bundle, required)) || ...
        ~strcmp(bundle.protocolId, protocol.id) || ...
        ~strcmp(bundle.evidenceSplit, split) || ...
        ~isequal(bundle.modelFeatureNames, modelSpec.featureNames) || ...
        ~strcmp(bundle.modelFeatureContractSha256, ...
            modelSpec.featureContractSha256) || ...
        size(bundle.X, 1) ~= numel(bundle.y) || ...
        size(bundle.X, 2) ~= numel(modelSpec.featureNames) || ...
        numel(bundle.actionGainPercent) ~= numel(bundle.y) || ...
        numel(bundle.scaleName) ~= numel(bundle.y) || ...
        numel(bundle.trajectoryKey) ~= numel(bundle.y) || ...
        numel(bundle.sampleWeight) ~= numel(bundle.y) || ...
        bundle.exampleCount ~= numel(bundle.y) || ...
        bundle.trajectoryCount ~= numel(unique(bundle.trajectoryKey)) || ...
        any(~isfinite(bundle.X(:))) || ...
        any(~isfinite(bundle.actionGainPercent)) || ...
        any(~isfinite(bundle.sampleWeight)) || ...
        any(bundle.sampleWeight <= 0) || ...
        abs(sum(bundle.sampleWeight) - 1) > 1e-10 || ...
        bundle.truthUsedAsFeature || ...
        bundle.futureOutcomeUsedAsFeature || ...
        bundle.seedIdentifierUsedAsFeature || ...
        bundle.absoluteTimeUsedAsFeature || ...
        bundle.fixedFormationIdentifierUsedAsFeature
    error('CounterfactualRegretV133:InvalidModelDataset', ...
        'A V133 model dataset violates the frozen contract.');
end
end

function [intercept, coefficient, trace] = fitProjectedLogistic( ...
        X, y, sampleWeight, spec)
[exampleCount, featureCount] = size(X);
parameter = zeros(featureCount + 1, 1);
objective = inf;
converged = false;
for iteration = 1:spec.maximumIterations
    probability = logistic(parameter(1) + X * parameter(2:end), ...
        spec.probabilityClip);
    gradient = [ ...
        sum(sampleWeight .* (probability - y)); ...
        X' * (sampleWeight .* (probability - y)) + ...
            spec.ridgeLambda * parameter(2:end)];
    curvatureWeight = sampleWeight .* probability .* (1 - probability);
    design = [ones(exampleCount, 1), X];
    hessian = design' * bsxfun(@times, design, curvatureWeight) + ...
        diag([1e-9; spec.ridgeLambda * ones(featureCount, 1)]);
    direction = hessian \ gradient;
    step = 1;
    currentObjective = logisticObjective( ...
        parameter, X, y, sampleWeight, spec.ridgeLambda, ...
        spec.probabilityClip);
    accepted = false;
    while step >= 2^-20
        candidate = parameter - step * direction;
        candidate(2:end) = projectSigns( ...
            candidate(2:end), spec.monotoneDirection);
        candidateObjective = logisticObjective( ...
            candidate, X, y, sampleWeight, spec.ridgeLambda, ...
            spec.probabilityClip);
        if candidateObjective <= currentObjective + 1e-12
            accepted = true;
            break;
        end
        step = step / 2;
    end
    if ~accepted
        break;
    end
    change = max(abs(candidate - parameter));
    parameter = candidate;
    objective = candidateObjective;
    if change <= spec.convergenceTolerance
        converged = true;
        break;
    end
end
intercept = parameter(1);
coefficient = parameter(2:end);
trace = struct( ...
    'iterations', iteration, ...
    'converged', converged, ...
    'finalObjective', objective, ...
    'maximumProjectedSignViolation', maxSignViolation( ...
        coefficient, spec.monotoneDirection), ...
    'coefficientNonzeroCount', nnz(abs(coefficient) > 1e-10));
end

function values = projectSigns(values, directions)
directions = reshape(directions, [], 1);
values(directions > 0) = max(values(directions > 0), 0);
values(directions < 0) = min(values(directions < 0), 0);
end

function value = maxSignViolation(coefficient, directions)
directions = reshape(directions, [], 1);
violations = zeros(size(coefficient));
violations(directions > 0) = max( ...
    -coefficient(directions > 0), 0);
violations(directions < 0) = max( ...
    coefficient(directions < 0), 0);
value = max(violations);
end

function [threshold, selected, trace] = calibrateThreshold( ...
        probabilities, bundle, inSupport, protocol, spec)
candidates = unique([0; probabilities(inSupport); 1]);
trace = repmat(emptyThresholdTrace(), 1, numel(candidates));
eligible = false(1, numel(candidates));
for candidateIdx = 1:numel(candidates)
    current = evaluateThreshold( ...
        probabilities, bundle, inSupport, ...
        candidates(candidateIdx), protocol);
    trace(candidateIdx) = struct( ...
        'threshold', candidates(candidateIdx), ...
        'actionCoverage', current.actionCoverage, ...
        'harmfulRecall', current.harmfulRecall, ...
        'falseSafeRate', current.falseSafeRate, ...
        'retainedOracleGainFraction', ...
            current.retainedOracleGainFraction, ...
        'gatePassed', current.gatePassed);
    eligible(candidateIdx) = current.gatePassed;
end
if ~any(eligible)
    threshold = -inf;
    selected = evaluateThreshold( ...
        probabilities, bundle, inSupport, threshold, protocol);
    selected.gatePassed = false;
    selected.failureReason = ...
        'no-shared-threshold-passed-all-scale-teacher-gates';
    return;
end
eligibleIndices = find(eligible);
coverage = [trace(eligibleIndices).actionCoverage];
bestCoverage = max(coverage);
eligibleIndices = eligibleIndices( ...
    abs(coverage - bestCoverage) <= 1e-12);
retained = [trace(eligibleIndices).retainedOracleGainFraction];
bestRetained = max(retained);
eligibleIndices = eligibleIndices( ...
    abs(retained - bestRetained) <= 1e-12);
[~, cursor] = min([trace(eligibleIndices).threshold]);
selectedIdx = eligibleIndices(cursor);
threshold = trace(selectedIdx).threshold;
selected = evaluateThreshold( ...
    probabilities, bundle, inSupport, threshold, protocol);
selected.failureReason = '';
selected.thresholdSelectionRule = spec.thresholdSelectionRule;
end

function readout = evaluateThreshold( ...
        probabilities, bundle, inSupport, threshold, protocol)
predictedSafe = inSupport & probabilities <= threshold;
readout = evaluateMask(predictedSafe, bundle, protocol);
scales = {'M24', 'X36'};
scaleReadout = repmat(emptyMaskReadout(), 1, numel(scales));
for scaleIdx = 1:numel(scales)
    members = strcmp(bundle.scaleName, scales{scaleIdx});
    scaleReadout(scaleIdx) = evaluateMask( ...
        predictedSafe(members), subsetBundle(bundle, members), protocol);
    scaleReadout(scaleIdx).name = scales{scaleIdx};
end
readout.byScale = scaleReadout;
readout.threshold = threshold;
readout.inSupportFraction = mean(inSupport);
readout.gatePassed = readout.gatePassed && ...
    all([scaleReadout.gatePassed]);
end

function readout = evaluateMask(predictedSafe, bundle, protocol)
harmful = logical(bundle.y);
harmfulCount = nnz(harmful);
predictedSafeCount = nnz(predictedSafe);
falseSafeCount = nnz(predictedSafe & harmful);
oracleSafe = ~harmful;
positiveOracleGain = max(bundle.actionGainPercent, 0);
oracleGain = sum(positiveOracleGain(oracleSafe));
selectedGain = sum(positiveOracleGain(predictedSafe & oracleSafe));
readout = emptyMaskReadout();
readout.exampleCount = numel(harmful);
readout.harmfulCount = harmfulCount;
readout.predictedSafeCount = predictedSafeCount;
readout.falseSafeCount = falseSafeCount;
readout.harmfulRecall = 1 - falseSafeCount / max(harmfulCount, 1);
readout.falseSafeRate = ...
    falseSafeCount / max(predictedSafeCount, 1);
readout.actionCoverage = predictedSafeCount / max(numel(harmful), 1);
readout.oracleSafeCoverage = nnz(oracleSafe) / max(numel(harmful), 1);
readout.retainedOracleGainFraction = ...
    selectedGain / max(oracleGain, eps);
readout.selectedOracleGainSum = selectedGain;
readout.availableOracleGainSum = oracleGain;
readout.gatePassed = ...
    readout.harmfulRecall + 1e-12 >= ...
        protocol.teacherGate.minimumHarmfulRecall && ...
    readout.falseSafeRate <= ...
        protocol.teacherGate.maximumFalseSafeRate + 1e-12 && ...
    readout.actionCoverage + 1e-12 >= ...
        protocol.teacherGate.minimumDynamicActionCoverage && ...
    readout.retainedOracleGainFraction + 1e-12 >= ...
        protocol.teacherGate.minimumRetainedOracleGainFraction;
end

function subset = subsetBundle(bundle, mask)
subset = bundle;
fields = {'y', 'actionGainPercent'};
for fieldIdx = 1:numel(fields)
    subset.(fields{fieldIdx}) = subset.(fields{fieldIdx})(mask);
end
end

function value = logistic(linear, clip)
linear = min(max(linear, -40), 40);
value = 1 ./ (1 + exp(-linear));
value = min(max(value, clip), 1 - clip);
end

function value = logisticObjective( ...
        parameter, X, y, sampleWeight, lambda, clip)
p = logistic(parameter(1) + X * parameter(2:end), clip);
value = -sum(sampleWeight .* ( ...
    y .* log(p) + (1 - y) .* log(1 - p))) + ...
    0.5 * lambda * sum(parameter(2:end).^2);
end

function value = logLoss(probability, y, sampleWeight)
value = -sum(sampleWeight .* ( ...
    double(y) .* log(probability) + ...
    (1 - double(y)) .* log(1 - probability)));
end

function value = weightedMean(X, weights)
value = weights' * X;
end

function value = weightedScale(X, center, weights, minimum)
delta = bsxfun(@minus, X, center);
value = sqrt(weights' * (delta.^2));
value(value < minimum) = 1;
end

function value = emptyMaskReadout()
value = struct( ...
    'name', '', 'exampleCount', 0, 'harmfulCount', 0, ...
    'predictedSafeCount', 0, 'falseSafeCount', 0, ...
    'harmfulRecall', NaN, 'falseSafeRate', NaN, ...
    'actionCoverage', NaN, 'oracleSafeCoverage', NaN, ...
    'retainedOracleGainFraction', NaN, ...
    'selectedOracleGainSum', NaN, ...
    'availableOracleGainSum', NaN, ...
    'gatePassed', false);
end

function value = emptyThresholdTrace()
value = struct( ...
    'threshold', NaN, 'actionCoverage', NaN, ...
    'harmfulRecall', NaN, 'falseSafeRate', NaN, ...
    'retainedOracleGainFraction', NaN, 'gatePassed', false);
end
