function result = FormationB4V46CausalRepairPreflight(options)
% FORMATIONB4V46CAUSALREPAIRPREFLIGHT Structural-only repaired-route audit.
%
% Every audited step exposes exactly one current geometry/physical/pDrop
% page plus the immutable t=1 registered graph, physical UIDs, group IDs,
% and absolute time.  The fixed V46 projector repairs that registered graph
% before the existing V43 reference and synchronized B=4 schedule builders
% are called.  Executed pages, rather than same-snapshot schedule pages, are
% retained for all rolling-window checks.
%
% This development preflight never generates or reads tracking data or
% realized delivery draws and cannot authorize a tracking claim.

if nargin < 1 || isempty(options)
    options = struct();
end
allowedFields = {'presets', 'seeds', 'timeIndices', ...
    'progressEvery', 'testTamperMode'};
if ~isstruct(options) || ~isscalar(options) || ...
        any(~ismember(fieldnames(options), allowedFields))
    error('FormationB4V46Preflight:InvalidOptions', ...
        'The V46 causal-repair preflight options are malformed.');
end

protocol = getFormationCausalMinimalEditV46Protocol();
presets = getField(options, 'presets', protocol.registeredPresets);
seeds = getField(options, 'seeds', protocol.registeredSeeds);
timeIndices = getField(options, 'timeIndices', []);
progressEvery = getField(options, 'progressEvery', 20);
testTamperMode = lower(char(getField(options, 'testTamperMode', '')));
validateRequestedCases(presets, seeds, protocol);
seeds = reshape(seeds, 1, []);
if ~isempty(timeIndices) && (~isnumeric(timeIndices) || ...
        ~isreal(timeIndices) || any(~isfinite(timeIndices)) || ...
        any(timeIndices ~= round(timeIndices)) || any(timeIndices < 1) || ...
        numel(unique(timeIndices)) ~= numel(timeIndices) || ...
        ~isequal(reshape(timeIndices, 1, []), ...
            sort(reshape(timeIndices, 1, []))) || ...
        (numel(timeIndices) > 1 && any(diff(timeIndices) ~= 1)))
    error('FormationB4V46Preflight:InvalidOptions', ...
        ['timeIndices must be a strictly contiguous increasing ', ...
         'integer interval.']);
end
if ~isscalar(progressEvery) || ~isnumeric(progressEvery) || ...
        ~isreal(progressEvery) || ~isfinite(progressEvery) || ...
        progressEvery < 1 || progressEvery ~= round(progressEvery) || ...
        ~ismember(testTamperMode, {'', 'uniform-field', 'future-page', ...
            'negative-weight', 'non-subset', 'zero-weight-edge', ...
            'projection-certificate', 'projection-no-feasible'})
    error('FormationB4V46Preflight:InvalidOptions', ...
        'The progress or test-tamper option is invalid.');
end

caseCount = numel(presets) * numel(seeds);
cases = repmat(emptyCase(), 1, caseCount);
cursor = 0;
for presetIdx = 1:numel(presets)
    for seedIdx = 1:numel(seeds)
        cursor = cursor + 1;
        presetName = presets{presetIdx};
        seed = seeds(seedIdx);
        fprintf(['FormationB4V46 preflight case %d/%d: ', ...
            '%s seed=%d\n'], cursor, caseCount, presetName, seed);
        [caseItem, failure] = buildCase(presetName, seed, ...
            timeIndices, progressEvery, testTamperMode, protocol);
        if ~isempty(failure.identifier)
            fprintf(2, ['FormationB4V46 FAIL-CLOSED preset=%s ', ...
                'seed=%d time=%d phase=%s cause=%s message=%s\n'], ...
                failure.presetName, failure.seed, failure.currentTime, ...
                failure.phase, failure.identifier, failure.message);
            error('FormationB4V46Preflight:FailedClosed', ...
                ['preset=%s seed=%d time=%d phase=%s cause=%s ', ...
                 'message=%s'], failure.presetName, failure.seed, ...
                failure.currentTime, failure.phase, failure.identifier, ...
                failure.message);
        end
        cases(cursor) = caseItem;
    end
end

fullRegistryRequested = isequal(presets, protocol.registeredPresets) && ...
    isequal(seeds, protocol.registeredSeeds);
allFullHorizon = all([cases.fullHorizonCovered]);
allStructuralChecksPassed = all([cases.structuralChecksPassed]);
result = struct();
result.contractVersion = ...
    'formation-b4-v46-causal-repair-preflight-development-v1';
result.protocolId = protocol.id;
result.protocolCanonicalSha256 = protocol.canonicalSha256;
result.presets = presets;
result.seeds = seeds;
result.caseCount = caseCount;
result.period = protocol.period;
result.arms = protocol.primaryArms;
result.cases = cases;
result.failureRecords = repmat(emptyFailure(), 1, 0);
result.fullRegistryRequested = fullRegistryRequested;
result.allCasesFullHorizonCovered = allFullHorizon;
result.allStructuralChecksPassed = allStructuralChecksPassed;
result.projectionCertificateScope = ...
    'cross-backbone-connectivity-and-distinct-receiver-matching-only';
result.fullV43RouteCompositionPassed = ...
    all([cases.fullV43RouteCompositionPassed]);
result.requiredFull32CaseCount = protocol.registeredCartesianCaseCount;
result.dynamicMatrixProductAuditPerformed = ...
    all([cases.dynamicMatrixProductAuditPerformed]);
result.full32CasePreflightPassed = fullRegistryRequested && ...
    caseCount == protocol.registeredCartesianCaseCount && ...
    allFullHorizon && allStructuralChecksPassed && ...
    result.fullV43RouteCompositionPassed && ...
    result.dynamicMatrixProductAuditPerformed && isempty(testTamperMode);
result.routeReceivesCurrentPageOnly = true;
result.registeredBaseImmutableAcrossEpisode = true;
result.posteriorUsed = false;
result.truthUsed = false;
result.measurementUsed = false;
result.futurePagePassedToProjectionOrRoute = false;
result.realizedDeliveryUniformsUsed = false;
result.trackingOutcomeScored = false;
result.trackingOutcomeAuthorized = false;
result.validationClaimAllowed = false;
result.developmentEvidenceOnly = true;
result.testTamperMode = testTamperMode;
result.canonicalSha256 = '';
result.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(result, 'canonicalSha256'));
fprintf(['FormationB4V46 preflight complete: cases=%d ', ...
    'full32=%d sha256=%s\n'], caseCount, ...
    result.full32CasePreflightPassed, result.canonicalSha256);
end

function [value, failure] = buildCase(presetName, seed, ...
        requestedTimes, progressEvery, testTamperMode, protocol)
value = emptyCase();
failure = emptyFailure();
failure.presetName = presetName;
failure.seed = seed;
failure.currentTime = 0;
failure.phase = 'scenario-materialization';
try
    rng(seed, 'twister');
    config = buildDynamicTopologyScenarioConfig(presetName);
    [sensorTrajectories, trajectoryMetadata] = ...
        generateMultiFormationTrajectories(config);
    graph = materializeCausalPhysicalGraph(config, sensorTrajectories);
    registeredBase = FormationB4V45BuildCausalRegisteredBaseGraph( ...
        config.formationBackboneMode, config.sensorGroupIds, ...
        trajectoryMetadata.sensorPhysicalUids, ...
        trajectoryMetadata.formationPhysicalUidsBySensor, ...
        graph.positions(:, :, 1), graph.physicalAdjacency(:, :, 1));
    graph.formationBackbonePairs = ...
        registeredBase.formationGroupLabelPairs;
    [pDropByEdge, ~] = buildDynamicTopologyLinkSchedule(config, graph);
    identity = buildDynamicTopologyPhysicalIdentityRegistry(config);
    validateMaterializedScenario(config, sensorTrajectories, ...
        trajectoryMetadata, graph, pDropByEdge, identity, registeredBase);
catch errorInfo
    failure.identifier = nonemptyIdentifier(errorInfo.identifier);
    failure.message = errorInfo.message;
    return;
end

if isempty(requestedTimes)
    auditedTimes = 1:config.simulationLength;
else
    auditedTimes = reshape(requestedTimes, 1, []);
    if any(auditedTimes > config.simulationLength)
        failure.identifier = 'FormationB4V46Preflight:InvalidTimeRange';
        failure.message = sprintf( ...
            'Requested time exceeds simulationLength=%d.', ...
            config.simulationLength);
        return;
    end
end

nodeCount = config.numberOfSensors;
formationCount = config.formationCount;
timeCount = numel(auditedTimes);
window = protocol.period;
syncAdjacencyHistory = false(nodeCount, nodeCount, 0);
syncWeightHistory = zeros(nodeCount, nodeCount, 0);
referenceCounts = zeros(1, timeCount);
syncCounts = zeros(1, timeCount);
registeredRemovalCounts = zeros(1, timeCount);
nonregisteredAdditionCounts = zeros(1, timeCount);
forcedRemovalCounts = zeros(1, timeCount);
topologyCandidateCounts = zeros(1, timeCount);
assignmentCandidateCounts = zeros(1, timeCount);
projectionWorkCounts = zeros(1, timeCount);
currentInputHashes = cell(1, timeCount);
projectedBaseHashes = cell(1, timeCount);
projectionEditHashes = cell(1, timeCount);
projectionCandidateHashes = cell(1, timeCount);
projectionCertificateHashes = cell(1, timeCount);
referenceHashes = cell(1, timeCount);
syncHashes = cell(1, timeCount);
projectedPairUids = cell(1, timeCount);
removedPairUids = cell(1, timeCount);
addedPairUids = cell(1, timeCount);
rollingProductHashes = cell(1, 0);
rollingProductDobrushin = zeros(1, 0);
rollingProductCenteredSpectralNorm = zeros(1, 0);
rollingProductMaximumCenteredRowL2 = zeros(1, 0);
rollingWindowCount = 0;
alignedCycleCount = 0;

for localTimeIdx = 1:timeCount
    currentTime = auditedTimes(localTimeIdx);
    failure.currentTime = currentTime;
    failure.phase = 'current-page-input';
    try
        routeInput = struct( ...
            'positions', graph.positions(:, :, currentTime), ...
            'physicalAdjacency', logical( ...
                graph.physicalAdjacency(:, :, currentTime)), ...
            'pDropByEdge', pDropByEdge(:, :, currentTime), ...
            'registeredBaseAdjacency', logical( ...
                registeredBase.baseAdjacency), ...
            'sensorPhysicalUids', ...
                trajectoryMetadata.sensorPhysicalUids, ...
            'formationPhysicalUidsBySensor', ...
                trajectoryMetadata.formationPhysicalUidsBySensor, ...
            'sensorGroupIds', config.sensorGroupIds, ...
            'currentTime', currentTime);
        if localTimeIdx == 1
            routeInput = applyInputTamper(routeInput, testTamperMode);
        end
        validateCurrentPageInput(routeInput, nodeCount);

        failure.phase = 'current-page-projection';
        [projectedBaseAdjacency, certificate] = ...
            projectCausalMinimalEditFormationBackbone( ...
                routeInput.sensorGroupIds, ...
                routeInput.sensorPhysicalUids, ...
                routeInput.formationPhysicalUidsBySensor, ...
                routeInput.positions, ...
                routeInput.registeredBaseAdjacency, ...
                routeInput.physicalAdjacency, ...
                routeInput.pDropByEdge);
        if localTimeIdx == 1 && ...
                strcmp(testTamperMode, 'projection-certificate')
            certificate.canonicalSha256(1) = ...
                replacementHex(certificate.canonicalSha256(1));
        end
        projectionEvidence = assertProjectionCertificate( ...
            routeInput, projectedBaseAdjacency, certificate, protocol);

        failure.phase = 'repaired-reference-and-sync-page';
        context = adaptCurrentPageToV43Context( ...
            routeInput, projectedBaseAdjacency);
        [syncSequence, syncWeightSequence, syncDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                context, dutyOptions(protocol));
        assertBoundaryDetails(syncDetails, protocol);
        currentPhase = mod(currentTime - 1, window) + 1;
        if syncDetails.currentAbsolutePhase ~= currentPhase
            error('FormationB4V46Preflight:PhaseMismatch', ...
                'The synchronized B=4 absolute phase drifted.');
        end
        referenceAdjacency = logical(syncDetails.referenceAdjacency);
        referenceWeights = syncDetails.referenceFusionWeights;
        syncAdjacency = logical(syncSequence(:, :, currentPhase));
        syncWeights = syncWeightSequence(:, :, currentPhase);
        if localTimeIdx == 1
            [syncAdjacency, syncWeights] = applyPageTamper( ...
                syncAdjacency, syncWeights, referenceAdjacency, ...
                routeInput.physicalAdjacency, testTamperMode);
        end
        assertRoutePage(referenceAdjacency, referenceWeights, ...
            routeInput.physicalAdjacency, [], ...
            routeInput.formationPhysicalUidsBySensor, ...
            'v46-repaired-reference', true);
        assertRoutePage(syncAdjacency, syncWeights, ...
            routeInput.physicalAdjacency, referenceAdjacency, ...
            routeInput.formationPhysicalUidsBySensor, ...
            'v46-repaired-sync-b4', false);
        if nnz(referenceAdjacency) ~= 2 * nodeCount
            error('FormationB4V46Preflight:ReferenceMessageCount', ...
                'The repaired V43 reference does not have exactly 2N messages.');
        end

        syncAdjacencyHistory = appendWindowPage( ...
            syncAdjacencyHistory, syncAdjacency, window);
        syncWeightHistory = appendWindowPage( ...
            syncWeightHistory, syncWeights, window);
        if size(syncAdjacencyHistory, 3) == window
            rollingWindowCount = rollingWindowCount + 1;
            windowTimes = auditedTimes( ...
                localTimeIdx - window + 1:localTimeIdx);
            productAudit = assertRollingWindow( ...
                syncAdjacencyHistory, syncWeightHistory, ...
                routeInput.formationPhysicalUidsBySensor, windowTimes);
            rollingProductHashes{rollingWindowCount} = ...
                productAudit.canonicalSha256;
            rollingProductDobrushin(rollingWindowCount) = ...
                productAudit.dobrushin;
            rollingProductCenteredSpectralNorm(rollingWindowCount) = ...
                productAudit.centeredSpectralNorm;
            rollingProductMaximumCenteredRowL2(rollingWindowCount) = ...
                productAudit.maximumCenteredRowL2;
        end

        referenceCounts(localTimeIdx) = nnz(referenceAdjacency);
        syncCounts(localTimeIdx) = nnz(syncAdjacency);
        if mod(currentTime, window) == 0
            cycleMask = auditedTimes >= currentTime - window + 1 & ...
                auditedTimes <= currentTime;
            if nnz(cycleMask) == window && ...
                    isequal(auditedTimes(cycleMask), ...
                        currentTime - window + 1:currentTime)
                alignedCycleCount = alignedCycleCount + 1;
                assertAlignedSaving(referenceCounts(cycleMask), ...
                    syncCounts(cycleMask));
            end
        end

        registeredRemovalCounts(localTimeIdx) = ...
            certificate.registeredRemovalCount;
        nonregisteredAdditionCounts(localTimeIdx) = ...
            certificate.nonregisteredAdditionCount;
        forcedRemovalCounts(localTimeIdx) = ...
            certificate.forcedRegisteredRemovalCount;
        topologyCandidateCounts(localTimeIdx) = ...
            certificate.searchCandidateCounts.topologyCandidateCount;
        assignmentCandidateCounts(localTimeIdx) = ...
            certificate.searchCandidateCounts. ...
                receiverAssignmentCandidateCount;
        projectionWorkCounts(localTimeIdx) = ...
            certificate.searchCandidateCounts.workUnitCount;
        currentInputHashes{localTimeIdx} = ...
            projectionEvidence.currentInputCanonicalSha256;
        projectedBaseHashes{localTimeIdx} = ...
            projectionEvidence.projectedBaseCanonicalSha256;
        projectionEditHashes{localTimeIdx} = ...
            projectionEvidence.editCanonicalSha256;
        projectionCandidateHashes{localTimeIdx} = ...
            projectionEvidence.selectedCandidateCanonicalSha256;
        projectionCertificateHashes{localTimeIdx} = ...
            certificate.canonicalSha256;
        referenceHashes{localTimeIdx} = routePageHash( ...
            referenceAdjacency, referenceWeights);
        syncHashes{localTimeIdx} = routePageHash( ...
            syncAdjacency, syncWeights);
        projectedPairUids{localTimeIdx} = ...
            certificate.projectedPairPhysicalUids;
        removedPairUids{localTimeIdx} = ...
            certificate.removedRegisteredPairPhysicalUids;
        addedPairUids{localTimeIdx} = ...
            certificate.addedNonregisteredPairPhysicalUids;
        if localTimeIdx == 1 || localTimeIdx == timeCount || ...
                mod(localTimeIdx, progressEvery) == 0
            fprintf('  %s seed=%d t=%d/%d passed\n', ...
                presetName, seed, currentTime, config.simulationLength);
        end
    catch errorInfo
        failure.identifier = nonemptyIdentifier(errorInfo.identifier);
        failure.message = errorInfo.message;
        return;
    end
end

fullHorizonCovered = isequal(auditedTimes, 1:config.simulationLength);
expectedRollingWindows = max(timeCount - window + 1, 0);
if rollingWindowCount ~= expectedRollingWindows
    failure.currentTime = auditedTimes(end);
    failure.phase = 'coverage-accounting';
    failure.identifier = 'FormationB4V46Preflight:CoverageDrift';
    failure.message = 'The actual rolling-window count drifted.';
    return;
end
if fullHorizonCovered && alignedCycleCount ~= ...
        config.simulationLength / window
    failure.currentTime = config.simulationLength;
    failure.phase = 'coverage-accounting';
    failure.identifier = 'FormationB4V46Preflight:CoverageDrift';
    failure.message = 'The full-horizon aligned-cycle count drifted.';
    return;
end

repairMask = registeredRemovalCounts > 0 | ...
    nonregisteredAdditionCounts > 0;
repairPageCount = nnz(repairMask);
firstRepairTime = NaN;
if repairPageCount > 0
    firstRepairTime = auditedTimes(find(repairMask, 1, 'first'));
end
value = emptyCase();
value.caseId = sprintf('%s__seed%d__v46-repaired-route', ...
    presetName, seed);
value.presetName = presetName;
value.seed = seed;
value.simulationLength = config.simulationLength;
value.auditedTimes = auditedTimes;
value.auditedTimeCount = timeCount;
value.fullHorizonCovered = fullHorizonCovered;
value.nodeCount = nodeCount;
value.formationCount = formationCount;
value.physicalUidRegistryCanonicalSha256 = identity.canonicalSha256;
value.registeredBaseGraphCanonicalSha256 = registeredBase.canonicalSha256;
value.registeredBaseGraphSelectionMode = registeredBase.selectionMode;
value.registeredFormationPairPhysicalUids = ...
    registeredBase.formationPairPhysicalUids;
value.currentPageInputCanonicalSha256ByTime = currentInputHashes;
value.projectedBaseCanonicalSha256ByTime = projectedBaseHashes;
value.projectionEditCanonicalSha256ByTime = projectionEditHashes;
value.selectedProjectionCandidateCanonicalSha256ByTime = ...
    projectionCandidateHashes;
value.projectionCertificateCanonicalSha256ByTime = ...
    projectionCertificateHashes;
value.projectedFormationPairPhysicalUidsByTime = projectedPairUids;
value.removedRegisteredPairPhysicalUidsByTime = removedPairUids;
value.addedNonregisteredPairPhysicalUidsByTime = addedPairUids;
value.projectionRegisteredRemovalCountByTime = registeredRemovalCounts;
value.projectionForcedRemovalCountByTime = forcedRemovalCounts;
value.projectionNonregisteredAdditionCountByTime = ...
    nonregisteredAdditionCounts;
value.projectionTopologyCandidateCountByTime = topologyCandidateCounts;
value.projectionReceiverAssignmentCandidateCountByTime = ...
    assignmentCandidateCounts;
value.projectionWorkUnitCountByTime = projectionWorkCounts;
value.repairPageCount = repairPageCount;
value.firstRepairTime = firstRepairTime;
value.totalRegisteredRemovalCount = sum(registeredRemovalCounts);
value.totalNonregisteredAdditionCount = ...
    sum(nonregisteredAdditionCounts);
value.referencePageCanonicalSha256ByTime = referenceHashes;
value.syncB4PageCanonicalSha256ByTime = syncHashes;
value.referenceMessageCountByTime = referenceCounts;
value.syncB4MessageCountByTime = syncCounts;
value.rollingWindowCount = rollingWindowCount;
value.expectedRollingWindowCountForAuditedSpan = expectedRollingWindows;
value.rollingB4MatrixProductCanonicalSha256ByWindow = ...
    rollingProductHashes;
value.rollingB4MatrixProductDobrushinByWindow = ...
    rollingProductDobrushin;
value.rollingB4MatrixProductCenteredSpectralNormByWindow = ...
    rollingProductCenteredSpectralNorm;
value.rollingB4MatrixProductMaximumCenteredRowL2ByWindow = ...
    rollingProductMaximumCenteredRowL2;
value.rollingB4MatrixProductMultiplicationOrder = ...
    'P(t:t-3)=W(t)*W(t-1)*W(t-2)*W(t-3)';
value.rollingB4MatrixProductCentering = [ ...
    'spectral=H*P*H;row-dispersion=P-mean(P,1);', ...
    'H=I-ones(N)/N'];
value.worstRollingB4MatrixProductDobrushin = ...
    finiteWorst(rollingProductDobrushin);
value.medianRollingB4MatrixProductDobrushin = ...
    finiteMedian(rollingProductDobrushin);
value.worstRollingB4MatrixProductCenteredSpectralNorm = ...
    finiteWorst(rollingProductCenteredSpectralNorm);
value.medianRollingB4MatrixProductCenteredSpectralNorm = ...
    finiteMedian(rollingProductCenteredSpectralNorm);
value.worstRollingB4MatrixProductMaximumCenteredRowL2 = ...
    finiteWorst(rollingProductMaximumCenteredRowL2);
value.medianRollingB4MatrixProductMaximumCenteredRowL2 = ...
    finiteMedian(rollingProductMaximumCenteredRowL2);
value.alignedCycleCount = alignedCycleCount;
value.everyAlignedCycleSavingFraction = ...
    protocol.candidateAlignedMessageSavingFraction;
value.noOpPagesExactlyPreservedRegisteredBase = all( ...
    repairMask | cellfun(@(hash) strcmp(hash, ...
        computeCanonicalValueSha256(logical( ...
            registeredBase.baseAdjacency))), projectedBaseHashes));
value.projectionCertificateScope = ...
    'cross-backbone-connectivity-and-distinct-receiver-matching-only';
value.projectionBackboneCertificatePassed = true;
value.fullV43RouteCompositionPassed = true;
value.dynamicMatrixProductAuditPerformed = rollingWindowCount > 0;
value.structuralChecksPassed = true;
value.routeReceivesCurrentPageOnly = true;
value.registeredBaseImmutableAcrossEpisode = true;
value.posteriorUsed = false;
value.truthUsed = false;
value.measurementUsed = false;
value.futurePagePassedToProjectionOrRoute = false;
value.realizedDeliveryUniformsUsed = false;
value.trackingOutcomeScored = false;
value.trackingOutcomeAuthorized = false;
value.validationClaimAllowed = false;
value.developmentEvidenceOnly = true;
value.canonicalSha256 = '';
value.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(value, 'canonicalSha256'));
end

function routeInput = applyInputTamper(routeInput, mode)
switch mode
    case 'uniform-field'
        routeInput.realizedDeliveryUniforms = ...
            zeros(size(routeInput.physicalAdjacency));
    case 'future-page'
        routeInput.physicalAdjacency = repmat( ...
            routeInput.physicalAdjacency, 1, 1, 2);
    case 'projection-no-feasible'
        routeInput.physicalAdjacency(:) = false;
end
end

function [adjacency, weights] = applyPageTamper(adjacency, weights, ...
        referenceAdjacency, physicalAdjacency, mode)
switch mode
    case 'negative-weight'
        weights(1, 1) = -0.01;
    case 'zero-weight-edge'
        [receiver, sender] = find(adjacency, 1);
        removedWeight = weights(receiver, sender);
        weights(receiver, sender) = 0;
        weights(receiver, receiver) = ...
            weights(receiver, receiver) + removedWeight;
    case 'non-subset'
        nodeCount = size(referenceAdjacency, 1);
        candidates = physicalAdjacency & ~referenceAdjacency & ...
            ~logical(eye(nodeCount));
        linear = find(candidates, 1);
        if isempty(linear)
            error('FormationB4V46Preflight:TamperUnavailable', ...
                'No current physical non-reference edge exists to tamper.');
        end
        adjacency(linear) = true;
end
end

function validateMaterializedScenario(config, trajectories, metadata, ...
        graph, pDropByEdge, identity, registeredBase)
nodeCount = config.numberOfSensors;
timeCount = config.simulationLength;
if numel(trajectories) ~= nodeCount || ...
        ~isequal(size(graph.physicalAdjacency), ...
            [nodeCount, nodeCount, timeCount]) || ...
        ~isequal(size(pDropByEdge), ...
            [nodeCount, nodeCount, timeCount]) || ...
        ~isequal(size(graph.positions), [2, nodeCount, timeCount]) || ...
        ~isequal(metadata.sensorPhysicalUids, ...
            identity.sensorPhysicalUids) || ...
        ~isequal(metadata.formationPhysicalUidsBySensor, ...
            identity.formationPhysicalUidsBySensor) || ...
        ~strcmp(metadata.physicalIdentityRegistryCanonicalSha256, ...
            identity.canonicalSha256) || ...
        ~isstruct(registeredBase) || ...
        ~strcmp(registeredBase.contractVersion, ...
            'formation-b4-v45-causal-registered-base-graph-v1') || ...
        registeredBase.futureGeometryUsed || ...
        registeredBase.futurePhysicalPageUsed || ...
        registeredBase.linkProbabilityUsed || ...
        registeredBase.posteriorUsed || registeredBase.truthUsed || ...
        registeredBase.measurementUsed || ...
        registeredBase.realizedDeliveryUniformsUsed
    error('FormationB4V46Preflight:ScenarioIdentityDrift', ...
        'The planned sensor/link scenario or immutable UID registry drifted.');
end
end

function graph = materializeCausalPhysicalGraph(config, trajectories)
nodeCount = config.numberOfSensors;
timeCount = config.simulationLength;
positions = zeros(2, nodeCount, timeCount);
for sensorIdx = 1:nodeCount
    positions(:, sensorIdx, :) = reshape( ...
        trajectories{sensorIdx}(1:2, :), 2, 1, timeCount);
end
distances = zeros(nodeCount, nodeCount, timeCount);
physical = false(nodeCount, nodeCount, timeCount);
for currentTime = 1:timeCount
    page = positions(:, :, currentTime);
    for leftIdx = 1:nodeCount-1
        delta = page(:, leftIdx+1:end) - page(:, leftIdx);
        values = sqrt(sum(delta.^2, 1));
        distances(leftIdx, leftIdx+1:end, currentTime) = values;
        distances(leftIdx+1:end, leftIdx, currentTime) = values';
        if isfinite(config.commRange)
            available = values <= config.commRange;
        else
            available = true(size(values));
        end
        physical(leftIdx, leftIdx+1:end, currentTime) = available;
        physical(leftIdx+1:end, leftIdx, currentTime) = available';
    end
end
graph = struct('positions', positions, ...
    'distanceByTime', distances, 'physicalAdjacency', physical);
end

function validateCurrentPageInput(routeInput, nodeCount)
required = {'positions', 'physicalAdjacency', 'pDropByEdge', ...
    'registeredBaseAdjacency', 'sensorPhysicalUids', ...
    'formationPhysicalUidsBySensor', 'sensorGroupIds', 'currentTime'};
actual = fieldnames(routeInput);
matrixInputs = {'physicalAdjacency', 'pDropByEdge', ...
    'registeredBaseAdjacency'};
matricesValid = true;
for idx = 1:numel(matrixInputs)
    value = routeInput.(matrixInputs{idx});
    matricesValid = matricesValid && (isnumeric(value) || islogical(value)) && ...
        isreal(value) && all(isfinite(value(:))) && ...
        isequal(size(value), [nodeCount, nodeCount]);
end
if numel(actual) ~= numel(required) || ...
        ~all(ismember(actual, required)) || ...
        ~all(ismember(required, actual)) || ...
        ~isnumeric(routeInput.positions) || ...
        ~isreal(routeInput.positions) || ...
        ~isequal(size(routeInput.positions), [2, nodeCount]) || ...
        any(~isfinite(routeInput.positions(:))) || ~matricesValid || ...
        any(routeInput.pDropByEdge(:) < 0) || ...
        any(routeInput.pDropByEdge(:) > 1) || ...
        numel(routeInput.sensorPhysicalUids) ~= nodeCount || ...
        numel(unique(routeInput.sensorPhysicalUids)) ~= nodeCount || ...
        numel(routeInput.formationPhysicalUidsBySensor) ~= nodeCount || ...
        numel(routeInput.sensorGroupIds) ~= nodeCount || ...
        ~isscalar(routeInput.currentTime) || ...
        ~isfinite(routeInput.currentTime) || ...
        routeInput.currentTime < 1 || ...
        routeInput.currentTime ~= round(routeInput.currentTime)
    error('FormationB4V46Preflight:RouteInputBoundary', ...
        ['The projection/route input is not the exact finite current-page ', ...
         'eight-field payload.']);
end
physical = logical(routeInput.physicalAdjacency);
registered = logical(routeInput.registeredBaseAdjacency);
physical(1:nodeCount+1:end) = false;
registered(1:nodeCount+1:end) = false;
if ~isequal(physical, physical') || ~isequal(registered, registered')
    error('FormationB4V46Preflight:RouteInputBoundary', ...
        'Current physical and immutable registered graphs must be symmetric.');
end
end

function evidence = assertProjectionCertificate(routeInput, projectedBase, ...
        certificate, protocol)
required = {'contractVersion', 'formationPhysicalUids', ...
    'registeredPairPhysicalUids', ...
    'currentPhysicalQuotientPairPhysicalUids', ...
    'projectedPairPhysicalUids', ...
    'removedRegisteredPairPhysicalUids', ...
    'addedNonregisteredPairPhysicalUids', ...
    'placeholderSensorPhysicalUidPairs', ...
    'registeredRemovalCount', 'forcedRegisteredRemovalCount', ...
    'optionalRegisteredRemovalCount', 'nonregisteredAdditionCount', ...
    'matchingWitnesses', 'selectedScore', 'searchCap', ...
    'searchCandidateCounts', 'currentInputCanonicalSha256', ...
    'routeInputBoundary', 'registeredBaseGraphUsed', ...
    'currentGeometryUsed', 'currentPhysicalPageUsed', ...
    'currentLinkProbabilityPageUsed', 'futureGeometryUsed', ...
    'futurePhysicalPageUsed', 'posteriorUsed', 'truthUsed', ...
    'measurementUsed', 'realizedDeliveryUniformsUsed', ...
    'runtimeOverridesAccepted', 'scoreFunctionAccepted', ...
    'sensorArrayPermutationEquivarianceDesigned', ...
    'groupNumericRelabelEquivarianceDesigned', 'canonicalSha256', ...
    'arrayOrderExecutionCanonicalSha256'};
if ~isstruct(certificate) || ~isscalar(certificate) || ...
        ~all(isfield(certificate, required)) || ...
        ~strcmp(certificate.contractVersion, ...
            'causal-minimal-edit-formation-backbone-projection-v1') || ...
        ~strcmp(certificate.routeInputBoundary, ...
            'current-page-only-no-runtime-overrides-or-score-functions') || ...
        certificate.searchCap ~= ...
            protocol.maximumEnumeratedProjectionCandidates || ...
        ~certificate.registeredBaseGraphUsed || ...
        ~certificate.currentGeometryUsed || ...
        ~certificate.currentPhysicalPageUsed || ...
        ~certificate.currentLinkProbabilityPageUsed || ...
        certificate.futureGeometryUsed || ...
        certificate.futurePhysicalPageUsed || certificate.posteriorUsed || ...
        certificate.truthUsed || certificate.measurementUsed || ...
        certificate.realizedDeliveryUniformsUsed || ...
        certificate.runtimeOverridesAccepted || ...
        certificate.scoreFunctionAccepted || ...
        ~certificate.sensorArrayPermutationEquivarianceDesigned || ...
        ~certificate.groupNumericRelabelEquivarianceDesigned
    error('FormationB4V46Preflight:ProjectionBoundaryViolation', ...
        'The projection certificate crossed its frozen current-page boundary.');
end

payload = rmfield(certificate, ...
    {'canonicalSha256', 'arrayOrderExecutionCanonicalSha256'});
if ~strcmp(computeCanonicalValueSha256(payload), ...
        certificate.canonicalSha256)
    error('FormationB4V46Preflight:ProjectionCertificateHash', ...
        'The projection certificate canonical hash does not verify.');
end
nodeCount = numel(routeInput.sensorPhysicalUids);
if ~isequal(size(projectedBase), [nodeCount, nodeCount]) || ...
        any(diag(projectedBase)) || ...
        ~isequal(logical(projectedBase), logical(projectedBase)')
    error('FormationB4V46Preflight:ProjectedBaseMalformed', ...
        'The projected formation-pair placeholder is malformed.');
end

registeredPairs = collapsePairPhysicalUids( ...
    routeInput.registeredBaseAdjacency, ...
    routeInput.formationPhysicalUidsBySensor, true);
physicalPairs = collapsePairPhysicalUids( ...
    routeInput.physicalAdjacency, ...
    routeInput.formationPhysicalUidsBySensor, true);
projectedPairs = collapsePairPhysicalUids(projectedBase, ...
    routeInput.formationPhysicalUidsBySensor, true);
removedPairs = setdiff(registeredPairs, projectedPairs, 'rows');
addedPairs = setdiff(projectedPairs, registeredPairs, 'rows');
forcedPairs = setdiff(registeredPairs, physicalPairs, 'rows');
expectedFormationUids = sort(unique(reshape( ...
    routeInput.formationPhysicalUidsBySensor, 1, [])));
placeholderSensorPairs = sensorPairPhysicalUids( ...
    projectedBase, routeInput.sensorPhysicalUids);
if ~isequal(certificate.formationPhysicalUids, ...
        expectedFormationUids) || ...
        ~isequal(registeredPairs, ...
        certificate.registeredPairPhysicalUids) || ...
        ~isequal(physicalPairs, ...
            certificate.currentPhysicalQuotientPairPhysicalUids) || ...
        ~isequal(projectedPairs, certificate.projectedPairPhysicalUids) || ...
        ~isequal(removedPairs, ...
            certificate.removedRegisteredPairPhysicalUids) || ...
        ~isequal(addedPairs, ...
            certificate.addedNonregisteredPairPhysicalUids) || ...
        ~isequal(placeholderSensorPairs, ...
            certificate.placeholderSensorPhysicalUidPairs) || ...
        any(~ismember(projectedPairs, physicalPairs, 'rows')) || ...
        size(placeholderSensorPairs, 1) ~= size(projectedPairs, 1) || ...
        ~isConnectedFormationPairs(projectedPairs, ...
            certificate.formationPhysicalUids)
    error('FormationB4V46Preflight:ProjectionPairMismatch', ...
        'The projected/edit pair evidence does not match current graphs.');
end
if certificate.registeredRemovalCount ~= size(removedPairs, 1) || ...
        certificate.forcedRegisteredRemovalCount ~= ...
            size(forcedPairs, 1) || ...
        certificate.optionalRegisteredRemovalCount ~= ...
            size(setdiff(removedPairs, forcedPairs, 'rows'), 1) || ...
        certificate.nonregisteredAdditionCount ~= size(addedPairs, 1)
    error('FormationB4V46Preflight:ProjectionEditCountMismatch', ...
        'The projection edit counts do not match the certified pair sets.');
end
if isempty(removedPairs) && isempty(addedPairs) && ...
        ~isequal(logical(projectedBase), ...
            logical(routeInput.registeredBaseAdjacency))
    error('FormationB4V46Preflight:ProjectionNoOpDrift', ...
        'A zero-edit projection did not exactly preserve the registered base.');
end

sensorUids = reshape(routeInput.sensorPhysicalUids, 1, []);
formationUidsBySensor = reshape( ...
    routeInput.formationPhysicalUidsBySensor, 1, []);
[~, order] = sort(sensorUids);
currentInputPayload = struct( ...
    'contractVersion', ...
        'causal-minimal-edit-formation-current-input-v1', ...
    'sensorPhysicalUids', sensorUids(order), ...
    'formationPhysicalUidsBySensor', ...
        formationUidsBySensor(order), ...
    'positions', routeInput.positions(:, order), ...
    'registeredFormationPairPhysicalUids', registeredPairs, ...
    'physicalAdjacency', logical( ...
        routeInput.physicalAdjacency(order, order)), ...
    'pDropByEdge', routeInput.pDropByEdge(order, order));
if ~strcmp(computeCanonicalValueSha256(currentInputPayload), ...
        certificate.currentInputCanonicalSha256)
    error('FormationB4V46Preflight:ProjectionInputHashMismatch', ...
        'The certificate is not bound to the supplied current page.');
end
executionView = struct( ...
    'contractVersion', ...
        'causal-minimal-edit-formation-execution-view-v1', ...
    'sensorPhysicalUidsByArray', sensorUids, ...
    'projectedBaseAdjacency', logical(projectedBase));
if ~strcmp(computeCanonicalValueSha256(executionView), ...
        certificate.arrayOrderExecutionCanonicalSha256)
    error('FormationB4V46Preflight:ProjectionExecutionHashMismatch', ...
        'The projected execution-view hash does not verify.');
end

counts = certificate.searchCandidateCounts;
countFields = {'topologyCandidateCount', ...
    'receiverAssignmentCandidateCount', 'workUnitCount', ...
    'selectedLayerTopologyCount', 'selectedLayerConnectedCount', ...
    'selectedLayerMatchingFeasibleCount', ...
    'selectedLayerOptionalRegisteredRemovalCount', ...
    'selectedLayerNonregisteredAdditionCount'};
countValues = zeros(1, numel(countFields));
for idx = 1:numel(countFields)
    if ~isfield(counts, countFields{idx})
        error('FormationB4V46Preflight:ProjectionCandidateCount', ...
            'A projection search-candidate count is missing.');
    end
    countValues(idx) = counts.(countFields{idx});
end
if any(~isfinite(countValues)) || any(countValues < 0) || ...
        any(countValues ~= round(countValues)) || ...
        counts.workUnitCount > certificate.searchCap || ...
        counts.topologyCandidateCount < 1 || ...
        counts.selectedLayerMatchingFeasibleCount < 1 || ...
        counts.selectedLayerOptionalRegisteredRemovalCount ~= ...
            certificate.optionalRegisteredRemovalCount || ...
        counts.selectedLayerNonregisteredAdditionCount ~= ...
            certificate.nonregisteredAdditionCount
    error('FormationB4V46Preflight:ProjectionCandidateCount', ...
        'The bounded exact-search candidate counts are invalid.');
end

editPayload = struct( ...
    'contractVersion', 'v46-projection-edit-evidence-v1', ...
    'removedRegisteredPairPhysicalUids', removedPairs, ...
    'addedNonregisteredPairPhysicalUids', addedPairs, ...
    'registeredRemovalCount', size(removedPairs, 1), ...
    'nonregisteredAdditionCount', size(addedPairs, 1));
candidatePayload = struct( ...
    'contractVersion', 'v46-selected-projection-candidate-v1', ...
    'projectedPairPhysicalUids', projectedPairs, ...
    'matchingWitnesses', certificate.matchingWitnesses, ...
    'selectedScore', certificate.selectedScore, ...
    'searchCandidateCounts', certificate.searchCandidateCounts);
evidence = struct( ...
    'currentInputCanonicalSha256', ...
        certificate.currentInputCanonicalSha256, ...
    'projectedBaseCanonicalSha256', ...
        computeCanonicalValueSha256(logical(projectedBase)), ...
    'editCanonicalSha256', computeCanonicalValueSha256(editPayload), ...
    'selectedCandidateCanonicalSha256', ...
        computeCanonicalValueSha256(candidatePayload));
end

function pairs = collapsePairPhysicalUids(adjacency, uidBySensor, ...
        requireBidirectional)
uids = sort(unique(reshape(uidBySensor, 1, [])));
pairs = zeros(0, 2);
adjacency = logical(adjacency);
for leftIdx = 1:numel(uids)-1
    left = uidBySensor == uids(leftIdx);
    for rightIdx = leftIdx+1:numel(uids)
        right = uidBySensor == uids(rightIdx);
        forward = any(any(adjacency(left, right)));
        reverse = any(any(adjacency(right, left)));
        if (requireBidirectional && forward && reverse) || ...
                (~requireBidirectional && (forward || reverse))
            pairs(end + 1, :) = [uids(leftIdx), uids(rightIdx)]; %#ok<AGROW>
        end
    end
end
pairs = sortrows(pairs, [1, 2]);
end

function pairs = sensorPairPhysicalUids(adjacency, sensorUids)
[receiver, sender] = find(triu(logical(adjacency), 1));
if isempty(receiver)
    pairs = zeros(0, 2);
else
    sensorUids = reshape(sensorUids, 1, []);
    pairs = [sensorUids(receiver)', sensorUids(sender)'];
    pairs = sortrows(sort(pairs, 2), [1, 2]);
end
end

function connected = isConnectedFormationPairs(pairs, formationUids)
formationUids = sort(reshape(formationUids, 1, []));
adjacency = false(numel(formationUids));
for pairIdx = 1:size(pairs, 1)
    left = find(formationUids == pairs(pairIdx, 1), 1);
    right = find(formationUids == pairs(pairIdx, 2), 1);
    if isempty(left) || isempty(right)
        connected = false;
        return;
    end
    adjacency(left, right) = true;
    adjacency(right, left) = true;
end
connected = isStronglyConnected(adjacency);
end

function context = adaptCurrentPageToV43Context(routeInput, projectedBase)
nodeCount = numel(routeInput.sensorPhysicalUids);
context = struct();
% The existing V43 API uses the length of this deliberately empty
% compatibility container only; no payload value is read by the route.
context.localPosteriorBySensor = cell(1, nodeCount);
context.model = struct('dynamicTopologyScenario', struct( ...
    'config', struct('sensorGroupIds', ...
        reshape(routeInput.sensorGroupIds, 1, [])), ...
    'staticAdjacency', logical(projectedBase)));
context.baseAdjacency = logical(projectedBase);
context.physicalAdjacency = logical(routeInput.physicalAdjacency);
context.positions = routeInput.positions;
context.sensorPhysicalUids = reshape( ...
    routeInput.sensorPhysicalUids, 1, []);
context.formationPhysicalUidsBySensor = reshape( ...
    routeInput.formationPhysicalUidsBySensor, 1, []);
context.commConfig = struct('pDropByEdge', routeInput.pDropByEdge);
context.currentTime = routeInput.currentTime;
context.directedMessageBudget = 2 * nodeCount;
if any(~cellfun(@isempty, context.localPosteriorBySensor))
    error('FormationB4V46Preflight:PosteriorBoundary', ...
        'The V43 compatibility container unexpectedly holds a payload.');
end
end

function options = dutyOptions(protocol)
options = struct('period', protocol.period, ...
    'dutyLayer', protocol.dutyLayer, ...
    'phasePattern', protocol.phasePattern, ...
    'activeResidualWeight', protocol.activeResidualWeight, ...
    'dominantWeight', protocol.dominantWeight, ...
    'referenceResidualWeight', protocol.referenceResidualWeight);
end

function assertBoundaryDetails(details, protocol)
required = {'period', 'dutyLayer', 'phasePattern', 'pulsePhase', ...
    'currentGeometryUsed', 'currentLinkReliabilityUsed', ...
    'currentPhysicalActionSetUsed', 'posteriorUsed', 'truthUsed', ...
    'measurementUsed', 'futureOutcomeUsed', ...
    'realizedDeliveryUniformsUsed', 'trackingOutcomeScored', ...
    'validationClaimAllowed', 'developmentEvidenceOnly'};
if ~all(isfield(details, required)) || ...
        details.period ~= protocol.period || ...
        ~strcmp(details.dutyLayer, protocol.dutyLayer) || ...
        ~strcmp(details.phasePattern, protocol.phasePattern) || ...
        details.pulsePhase ~= 1 || ...
        ~details.currentGeometryUsed || ...
        ~details.currentLinkReliabilityUsed || ...
        ~details.currentPhysicalActionSetUsed || details.posteriorUsed || ...
        details.truthUsed || details.measurementUsed || ...
        details.futureOutcomeUsed || ...
        details.realizedDeliveryUniformsUsed || ...
        details.trackingOutcomeScored || details.validationClaimAllowed || ...
        ~details.developmentEvidenceOnly
    error('FormationB4V46Preflight:RouteBoundaryViolation', ...
        'The synchronized B=4 route crossed its frozen causal boundary.');
end
end

function assertRoutePage(adjacency, weights, physical, reference, ...
        formationUidsBySensor, armName, requireStrongConnectivity)
nodeCount = size(adjacency, 1);
allowedWeights = logical(adjacency) | logical(eye(nodeCount));
if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(diag(adjacency)) || any(adjacency(:) & ~physical(:))
    error('FormationB4V46Preflight:PhysicalViolation', ...
        '%s contains a nonphysical or self communication edge.', armName);
end
if ~isempty(reference) && any(adjacency(:) & ~reference(:))
    error('FormationB4V46Preflight:SubsetViolation', ...
        '%s is not a same-time subset of its repaired reference.', armName);
end
if any(~isfinite(weights(:))) || any(weights(:) < -1e-12) || ...
        any(weights(:) > 1 + 1e-12) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        any(weights(:) > 1e-12 & ~allowedWeights(:))
    error('FormationB4V46Preflight:FusionWeightViolation', ...
        '%s fusion weights are not nonnegative row-stochastic.', armName);
end
positiveOffDiagonal = weights > 1e-12;
positiveOffDiagonal(1:nodeCount+1:end) = false;
if ~isequal(positiveOffDiagonal, logical(adjacency))
    error('FormationB4V46Preflight:FusionWeightSupportViolation', ...
        '%s adjacency and positive off-diagonal support disagree.', armName);
end
assertFrozenWeightPattern(adjacency, weights, armName);
if requireStrongConnectivity
    formationAdjacency = collapseToPhysicalFormations( ...
        adjacency, formationUidsBySensor);
    if ~isStronglyConnected(adjacency) || ...
            ~isStronglyConnected(formationAdjacency)
        error('FormationB4V46Preflight:ReferenceDisconnected', ...
            '%s is not sensor/formation strongly connected.', armName);
    end
end
end

function assertFrozenWeightPattern(adjacency, weights, armName)
nodeCount = size(adjacency, 1);
tolerance = 1e-12;
for receiver = 1:nodeCount
    sources = find(adjacency(receiver, :));
    offDiagonal = sort(weights(receiver, sources));
    selfWeight = weights(receiver, receiver);
    if strcmp(armName, 'v46-repaired-reference')
        passed = numel(sources) == 2 && ...
            all(abs(offDiagonal - [0.05, 0.70]) <= tolerance) && ...
            abs(selfWeight - 0.25) <= tolerance;
    elseif numel(sources) == 1
        passed = abs(offDiagonal - 0.70) <= tolerance && ...
            abs(selfWeight - 0.30) <= tolerance;
    elseif numel(sources) == 2
        passed = all(abs(offDiagonal - [0.20, 0.70]) <= tolerance) && ...
            abs(selfWeight - 0.10) <= tolerance;
    else
        passed = false;
    end
    if ~passed
        error('FormationB4V46Preflight:FrozenWeightPatternViolation', ...
            '%s deviates from the frozen V43/B4 row-weight pattern.', ...
            armName);
    end
end
end

function pages = appendWindowPage(pages, page, window)
pages(:, :, end + 1) = page;
if size(pages, 3) > window
    pages = pages(:, :, end - window + 1:end);
end
end

function audit = assertRollingWindow(adjacencyPages, weightPages, ...
        formationUidsBySensor, windowTimes)
sensorUnion = any(adjacencyPages, 3);
formationUnion = collapseToPhysicalFormations( ...
    sensorUnion, formationUidsBySensor);
if ~isStronglyConnected(sensorUnion)
    error('FormationB4V46Preflight:RollingSensorDisconnected', ...
        'The actual executed rolling-B4 sensor union is disconnected.');
end
if ~isStronglyConnected(formationUnion)
    error('FormationB4V46Preflight:RollingFormationDisconnected', ...
        'The actual executed rolling-B4 formation union is disconnected.');
end

% Receiver-row matrices act on a column of node states.  Chronological
% pages W(t-3),...,W(t) therefore compose newest-on-the-left:
% P(t:t-3) = W(t) W(t-1) W(t-2) W(t-3).
nodeCount = size(weightPages, 1);
product = eye(nodeCount);
for chronologicalIdx = 1:size(weightPages, 3)
    product = weightPages(:, :, chronologicalIdx) * product;
end
if any(~isfinite(product(:))) || any(product(:) < -1e-12) || ...
        any(product(:) > 1 + 1e-12) || ...
        any(abs(sum(product, 2) - 1) > 1e-11)
    error('FormationB4V46Preflight:MatrixProductViolation', ...
        'The chronological rolling-B4 product is not row-stochastic.');
end
mixing = computeStochasticMixingDiagnostics(product);
dobrushin = mixing.dobrushinCoefficient;
centeredSpectralNorm = mixing.centeredSpectralNorm;
maximumCenteredRowL2 = mixing.maximumCenteredRowL2;
spectralUpperBound = sqrt(nodeCount);
rowUpperBound = sqrt(2);
if ~isfinite(dobrushin) || dobrushin < -1e-12 || ...
        dobrushin > 1 + 1e-12 || ...
        ~isfinite(centeredSpectralNorm) || ...
        centeredSpectralNorm < -1e-12 || ...
        centeredSpectralNorm > spectralUpperBound + 1e-10 || ...
        ~isfinite(maximumCenteredRowL2) || ...
        maximumCenteredRowL2 < -1e-12 || ...
        maximumCenteredRowL2 > rowUpperBound + 1e-10
    error('FormationB4V46Preflight:MatrixProductMetricViolation', ...
        'A rolling-B4 product metric is outside its mathematical bound.');
end
payload = struct( ...
    'contractVersion', 'v46-actual-rolling-b4-product-audit-v1', ...
    'matrixConvention', 'receiver-row-state-column', ...
    'multiplicationOrder', ...
        'P(t:t-3)=W(t)*W(t-1)*W(t-2)*W(t-3)', ...
    'centeringDefinition', [ ...
        'spectral=H*P*H;row-dispersion=P-mean(P,1);', ...
        'H=I-ones(N)/N'], ...
    'windowTimes', reshape(windowTimes, 1, []), ...
    'product', product, 'dobrushin', dobrushin, ...
    'centeredSpectralNorm', centeredSpectralNorm, ...
    'maximumCenteredRowL2', maximumCenteredRowL2);
audit = payload;
audit.canonicalSha256 = computeCanonicalValueSha256(payload);
end

function formation = collapseToPhysicalFormations(adjacency, uidBySensor)
uids = sort(unique(reshape(uidBySensor, 1, [])));
formation = false(numel(uids));
for receiverIdx = 1:numel(uids)
    receivers = uidBySensor == uids(receiverIdx);
    for senderIdx = 1:numel(uids)
        senders = uidBySensor == uids(senderIdx);
        formation(receiverIdx, senderIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(uids)+1:end) = false;
end

function assertAlignedSaving(referenceCounts, candidateCounts)
referenceTotal = sum(referenceCounts);
candidateTotal = sum(candidateCounts);
if referenceTotal <= 0 || ...
        8 * (referenceTotal - candidateTotal) ~= 3 * referenceTotal
    error('FormationB4V46Preflight:AlignedCycleSaving', ...
        ['The actual synchronized aligned B=4 cycle does not have ', ...
         'exactly 37.5%% attempted-message saving.']);
end
end

function connected = isStronglyConnected(adjacency)
adjacency = logical(adjacency);
adjacency(1:size(adjacency, 1)+1:end) = false;
senderAdjacency = adjacency';
connected = reachableAll(senderAdjacency) && reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
nodeCount = size(adjacency, 1);
if nodeCount == 0
    connected = false;
    return;
end
visited = false(1, nodeCount);
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function hash = routePageHash(adjacency, weights)
hash = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), 'fusionWeights', weights));
end

function validateRequestedCases(presets, seeds, protocol)
if ~iscell(presets) || isempty(presets) || ...
        any(~cellfun(@ischar, presets)) || ...
        numel(unique(presets)) ~= numel(presets) || ...
        any(~ismember(presets, protocol.registeredPresets)) || ...
        ~isnumeric(seeds) || ~isreal(seeds) || isempty(seeds) || ...
        any(~isfinite(seeds)) || any(seeds ~= round(seeds)) || ...
        numel(unique(seeds)) ~= numel(seeds) || ...
        any(~ismember(seeds, protocol.registeredSeeds))
    error('FormationB4V46Preflight:UnregisteredCases', ...
        'Only the frozen V46 development presets/seeds may be used.');
end
expectedPresets = protocol.registeredPresets( ...
    ismember(protocol.registeredPresets, presets));
expectedSeeds = protocol.registeredSeeds( ...
    ismember(protocol.registeredSeeds, seeds));
if ~isequal(presets, expectedPresets) || ...
        ~isequal(reshape(seeds, 1, []), expectedSeeds)
    error('FormationB4V46Preflight:CaseOrder', ...
        'Requested cases must preserve the frozen V46 order.');
end
end

function value = finiteWorst(values)
if isempty(values)
    value = NaN;
else
    value = max(values);
end
end

function value = finiteMedian(values)
if isempty(values)
    value = NaN;
else
    value = median(values);
end
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end

function value = replacementHex(value)
if value == '0'
    value = '1';
else
    value = '0';
end
end

function identifier = nonemptyIdentifier(identifier)
if isempty(identifier)
    identifier = 'FormationB4V46Preflight:UnidentifiedFailure';
end
end

function value = emptyFailure()
value = struct('presetName', '', 'seed', NaN, 'currentTime', NaN, ...
    'phase', '', 'identifier', '', 'message', '');
end

function value = emptyCase()
value = struct( ...
    'caseId', '', 'presetName', '', 'seed', NaN, ...
    'simulationLength', NaN, 'auditedTimes', zeros(1, 0), ...
    'auditedTimeCount', 0, 'fullHorizonCovered', false, ...
    'nodeCount', NaN, 'formationCount', NaN, ...
    'physicalUidRegistryCanonicalSha256', '', ...
    'registeredBaseGraphCanonicalSha256', '', ...
    'registeredBaseGraphSelectionMode', '', ...
    'registeredFormationPairPhysicalUids', zeros(0, 2), ...
    'currentPageInputCanonicalSha256ByTime', {{}}, ...
    'projectedBaseCanonicalSha256ByTime', {{}}, ...
    'projectionEditCanonicalSha256ByTime', {{}}, ...
    'selectedProjectionCandidateCanonicalSha256ByTime', {{}}, ...
    'projectionCertificateCanonicalSha256ByTime', {{}}, ...
    'projectedFormationPairPhysicalUidsByTime', {{}}, ...
    'removedRegisteredPairPhysicalUidsByTime', {{}}, ...
    'addedNonregisteredPairPhysicalUidsByTime', {{}}, ...
    'projectionRegisteredRemovalCountByTime', zeros(1, 0), ...
    'projectionForcedRemovalCountByTime', zeros(1, 0), ...
    'projectionNonregisteredAdditionCountByTime', zeros(1, 0), ...
    'projectionTopologyCandidateCountByTime', zeros(1, 0), ...
    'projectionReceiverAssignmentCandidateCountByTime', zeros(1, 0), ...
    'projectionWorkUnitCountByTime', zeros(1, 0), ...
    'repairPageCount', 0, 'firstRepairTime', NaN, ...
    'totalRegisteredRemovalCount', 0, ...
    'totalNonregisteredAdditionCount', 0, ...
    'referencePageCanonicalSha256ByTime', {{}}, ...
    'syncB4PageCanonicalSha256ByTime', {{}}, ...
    'referenceMessageCountByTime', zeros(1, 0), ...
    'syncB4MessageCountByTime', zeros(1, 0), ...
    'rollingWindowCount', 0, ...
    'expectedRollingWindowCountForAuditedSpan', 0, ...
    'rollingB4MatrixProductCanonicalSha256ByWindow', {{}}, ...
    'rollingB4MatrixProductDobrushinByWindow', zeros(1, 0), ...
    'rollingB4MatrixProductCenteredSpectralNormByWindow', zeros(1, 0), ...
    'rollingB4MatrixProductMaximumCenteredRowL2ByWindow', zeros(1, 0), ...
    'rollingB4MatrixProductMultiplicationOrder', '', ...
    'rollingB4MatrixProductCentering', '', ...
    'worstRollingB4MatrixProductDobrushin', NaN, ...
    'medianRollingB4MatrixProductDobrushin', NaN, ...
    'worstRollingB4MatrixProductCenteredSpectralNorm', NaN, ...
    'medianRollingB4MatrixProductCenteredSpectralNorm', NaN, ...
    'worstRollingB4MatrixProductMaximumCenteredRowL2', NaN, ...
    'medianRollingB4MatrixProductMaximumCenteredRowL2', NaN, ...
    'alignedCycleCount', 0, ...
    'everyAlignedCycleSavingFraction', NaN, ...
    'noOpPagesExactlyPreservedRegisteredBase', false, ...
    'projectionCertificateScope', '', ...
    'projectionBackboneCertificatePassed', false, ...
    'fullV43RouteCompositionPassed', false, ...
    'dynamicMatrixProductAuditPerformed', false, ...
    'structuralChecksPassed', false, ...
    'routeReceivesCurrentPageOnly', false, ...
    'registeredBaseImmutableAcrossEpisode', false, ...
    'posteriorUsed', false, 'truthUsed', false, ...
    'measurementUsed', false, ...
    'futurePagePassedToProjectionOrRoute', false, ...
    'realizedDeliveryUniformsUsed', false, ...
    'trackingOutcomeScored', false, ...
    'trackingOutcomeAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true, 'canonicalSha256', '');
end
