function result = FormationB4V45CausalRoutePreflight(options)
% FORMATIONB4V45CAUSALROUTEPREFLIGHT Development-only full-time route audit.
%
% The preflight materializes only planned sensor geometry and link-
% probability schedules.  At every audited time it constructs an exact
% current-page payload containing positions, physical adjacency, pDrop,
% the registered base graph, immutable physical UIDs and group IDs.  That
% payload is the only information adapted to the existing V43 builder and
% the synchronized/formation-staggered B=4 duty-cycle schedules.
%
% No truth, measurement, posterior payload, future page, or realized link
% uniform is generated or supplied.  This file authorizes no tracking or
% validation claim; it is a development-only executability preflight.

if nargin < 1 || isempty(options)
    options = struct();
end
allowedFields = {'presets', 'seeds', 'timeIndices', ...
    'progressEvery', 'testTamperMode'};
if ~isstruct(options) || ~isscalar(options) || ...
        any(~ismember(fieldnames(options), allowedFields))
    error('FormationB4V45Preflight:InvalidOptions', ...
        'The V45 causal-route preflight options are malformed.');
end

parent = getFormationIndexEquivariantRouteV43DevelopmentProtocol();
presets = getField(options, 'presets', parent.registeredPresets);
seeds = getField(options, 'seeds', parent.registeredSeeds);
timeIndices = getField(options, 'timeIndices', []);
progressEvery = getField(options, 'progressEvery', 20);
testTamperMode = lower(char(getField( ...
    options, 'testTamperMode', '')));
validateRequestedCases(presets, seeds, parent);
if ~isempty(timeIndices) && (~isnumeric(timeIndices) || ...
        ~isreal(timeIndices) || any(~isfinite(timeIndices)) || ...
        any(timeIndices ~= round(timeIndices)) || ...
        any(timeIndices < 1) || ...
        numel(unique(timeIndices)) ~= numel(timeIndices) || ...
        ~isequal(reshape(timeIndices, 1, []), ...
            sort(reshape(timeIndices, 1, []))) || ...
        (numel(timeIndices) > 1 && any(diff(timeIndices) ~= 1)))
    error('FormationB4V45Preflight:InvalidOptions', ...
        ['timeIndices must be a strictly contiguous increasing ', ...
         'integer interval.']);
end
if ~isscalar(progressEvery) || ~isnumeric(progressEvery) || ...
        ~isreal(progressEvery) || ~isfinite(progressEvery) || ...
        progressEvery < 1 || progressEvery ~= round(progressEvery) || ...
        ~ismember(testTamperMode, {'', 'uniform-field', ...
            'future-page', 'negative-weight', 'non-subset', ...
            'zero-weight-edge'})
    error('FormationB4V45Preflight:InvalidOptions', ...
        'The progress or test-tamper option is invalid.');
end

caseCount = numel(presets) * numel(seeds);
cases = repmat(emptyCase(), 1, caseCount);
cursor = 0;
for presetIdx = 1:numel(presets)
    for seedIdx = 1:numel(seeds)
        cursor = cursor + 1;
        presetName = presets{presetIdx};
        seed = seeds(seedIdx);
        fprintf(['FormationB4V45 preflight case %d/%d: ', ...
            '%s seed=%d\n'], cursor, caseCount, presetName, seed);
        [caseItem, failure] = buildCase(presetName, seed, ...
            timeIndices, progressEvery, testTamperMode);
        if ~isempty(failure.identifier)
            fprintf(2, ['FormationB4V45 FAIL-CLOSED preset=%s ', ...
                'seed=%d time=%d phase=%s cause=%s message=%s\n'], ...
                failure.presetName, failure.seed, failure.currentTime, ...
                failure.phase, failure.identifier, failure.message);
            error('FormationB4V45Preflight:FailedClosed', ...
                ['preset=%s seed=%d time=%d phase=%s cause=%s ', ...
                 'message=%s'], failure.presetName, failure.seed, ...
                failure.currentTime, failure.phase, failure.identifier, ...
                failure.message);
        end
        cases(cursor) = caseItem;
    end
end

fullRegistryRequested = isequal(presets, parent.registeredPresets) && ...
    isequal(seeds, parent.registeredSeeds);
allFullHorizon = all([cases.fullHorizonCovered]);
allStructuralChecksPassed = all([cases.structuralChecksPassed]);
result = struct();
result.contractVersion = ...
    'formation-b4-v45-causal-route-preflight-development-v1';
result.parentProtocolId = parent.id;
result.parentProtocolCanonicalSha256 = parent.canonicalSha256;
result.presets = presets;
result.seeds = seeds;
result.caseCount = caseCount;
result.period = 4;
result.arms = {'v43-reference', 'sync-b4', 'formation-b4'};
result.cases = cases;
result.failureRecords = repmat(emptyFailure(), 1, 0);
result.fullRegistryRequested = fullRegistryRequested;
result.allCasesFullHorizonCovered = allFullHorizon;
result.allStructuralChecksPassed = allStructuralChecksPassed;
result.full32CasePreflightPassed = fullRegistryRequested && ...
    caseCount == parent.registeredCartesianCaseCount && ...
    allFullHorizon && allStructuralChecksPassed && ...
    isempty(testTamperMode);
result.routeReceivesCurrentPageOnly = true;
result.plannedSensorGeometryMaterializedForDevelopment = true;
result.plannedLinkProbabilityMaterializedForDevelopment = true;
result.posteriorUsed = false;
result.truthUsed = false;
result.measurementUsed = false;
result.futurePagePassedToRoute = false;
result.realizedDeliveryUniformsUsed = false;
result.trackingOutcomeScored = false;
result.trackingOutcomeAuthorized = false;
result.validationClaimAllowed = false;
result.developmentEvidenceOnly = true;
result.testTamperMode = testTamperMode;
result.canonicalSha256 = '';
result.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(result, 'canonicalSha256'));
fprintf(['FormationB4V45 preflight complete: cases=%d ', ...
    'full32=%d sha256=%s\n'], caseCount, ...
    result.full32CasePreflightPassed, result.canonicalSha256);
end

function [value, failure] = buildCase(presetName, seed, ...
        requestedTimes, progressEvery, testTamperMode)
value = emptyCase();
failure = emptyFailure();
failure.presetName = presetName;
failure.seed = seed;
failure.currentTime = 0;
failure.phase = 'scenario-materialization';
try
    rng(seed, 'twister');
    config = buildDynamicTopologyScenarioConfig(presetName);
    [sensorTrajectories, trajectoryMetadata] = ...
        generateMultiFormationTrajectories(config);
    graph = materializeCausalPhysicalGraph(config, sensorTrajectories);
    causalBaseRegistry = ...
        FormationB4V45BuildCausalRegisteredBaseGraph( ...
            config.formationBackboneMode, config.sensorGroupIds, ...
            trajectoryMetadata.sensorPhysicalUids, ...
            trajectoryMetadata.formationPhysicalUidsBySensor, ...
            graph.positions(:, :, 1), ...
            graph.physicalAdjacency(:, :, 1));
    graph.formationBackbonePairs = ...
        causalBaseRegistry.formationGroupLabelPairs;
    [pDropByEdge, ~] = ...
        buildDynamicTopologyLinkSchedule(config, graph);
    identity = buildDynamicTopologyPhysicalIdentityRegistry(config);
    validateMaterializedScenario(config, sensorTrajectories, ...
        trajectoryMetadata, graph, pDropByEdge, identity, ...
        causalBaseRegistry);
catch errorInfo
    failure.identifier = nonemptyIdentifier(errorInfo.identifier);
    failure.message = errorInfo.message;
    return;
end

if isempty(requestedTimes)
    auditedTimes = 1:config.simulationLength;
else
    auditedTimes = reshape(requestedTimes, 1, []);
    if any(auditedTimes > config.simulationLength)
        failure.identifier = ...
            'FormationB4V45Preflight:InvalidTimeRange';
        failure.message = sprintf( ...
            'Requested time exceeds simulationLength=%d.', ...
            config.simulationLength);
        return;
    end
end

nodeCount = config.numberOfSensors;
formationCount = config.formationCount;
timeCount = numel(auditedTimes);
window = 4;
syncHistory = false(nodeCount, nodeCount, 0);
formationHistory = false(nodeCount, nodeCount, 0);
referenceCounts = zeros(1, timeCount);
syncCounts = zeros(1, timeCount);
formationCounts = zeros(1, timeCount);
inputHashes = cell(1, timeCount);
referenceHashes = cell(1, timeCount);
syncHashes = cell(1, timeCount);
formationHashes = cell(1, timeCount);
rollingWindowCount = 0;
alignedCycleCount = 0;

for localTimeIdx = 1:timeCount
    currentTime = auditedTimes(localTimeIdx);
    failure.currentTime = currentTime;
    failure.phase = 'current-page-route';
    try
        positions = graph.positions(:, :, currentTime);
        routeInput = struct( ...
            'positions', positions, ...
            'physicalAdjacency', logical( ...
                graph.physicalAdjacency(:, :, currentTime)), ...
            'pDropByEdge', pDropByEdge(:, :, currentTime), ...
            'baseAdjacency', logical( ...
                causalBaseRegistry.baseAdjacency), ...
            'sensorPhysicalUids', ...
                trajectoryMetadata.sensorPhysicalUids, ...
            'formationPhysicalUidsBySensor', ...
                trajectoryMetadata.formationPhysicalUidsBySensor, ...
            'sensorGroupIds', config.sensorGroupIds, ...
            'currentTime', currentTime);
        if localTimeIdx == 1
            routeInput = applyInputTamper( ...
                routeInput, testTamperMode);
        end
        validateCurrentPageInput(routeInput, nodeCount);
        context = adaptCurrentPageToV43Context(routeInput);

        syncOptions = dutyOptions('synchronized');
        formationOptions = dutyOptions('formation-staggered');
        [syncSequence, syncWeightSequence, syncDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                context, syncOptions);
        [formationSequence, formationWeightSequence, ...
                formationDetails] = ...
            buildIndexEquivariantResidualDutyCycleSchedule( ...
                context, formationOptions);
        referenceAdjacency = logical( ...
            syncDetails.referenceAdjacency);
        referenceWeights = syncDetails.referenceFusionWeights;
        if ~isequal(referenceAdjacency, ...
                logical(formationDetails.referenceAdjacency)) || ...
                ~isequal(referenceWeights, ...
                    formationDetails.referenceFusionWeights)
            error('FormationB4V45Preflight:ReferenceMismatch', ...
                ['The synchronized and formation schedules did not ', ...
                 'reproduce the same current V43 route.']);
        end
        currentPhase = mod(currentTime - 1, window) + 1;
        if syncDetails.currentAbsolutePhase ~= currentPhase || ...
                formationDetails.currentAbsolutePhase ~= currentPhase
            error('FormationB4V45Preflight:PhaseMismatch', ...
                'The B=4 schedule absolute phase drifted.');
        end
        syncAdjacency = logical( ...
            syncSequence(:, :, currentPhase));
        syncWeights = syncWeightSequence(:, :, currentPhase);
        formationAdjacency = logical( ...
            formationSequence(:, :, currentPhase));
        formationWeights = ...
            formationWeightSequence(:, :, currentPhase);
        if localTimeIdx == 1
            [syncAdjacency, syncWeights, formationAdjacency, ...
                formationWeights] = applyPageTamper( ...
                    syncAdjacency, syncWeights, ...
                    formationAdjacency, formationWeights, ...
                    referenceAdjacency, routeInput.physicalAdjacency, ...
                    testTamperMode);
        end

        assertBoundaryDetails(syncDetails, 'sync-b4');
        assertBoundaryDetails(formationDetails, 'formation-b4');
        assertRoutePage(referenceAdjacency, referenceWeights, ...
            routeInput.physicalAdjacency, [], 'v43-reference', true);
        assertRoutePage(syncAdjacency, syncWeights, ...
            routeInput.physicalAdjacency, referenceAdjacency, ...
            'sync-b4', false);
        assertRoutePage(formationAdjacency, formationWeights, ...
            routeInput.physicalAdjacency, referenceAdjacency, ...
            'formation-b4', false);
        if nnz(referenceAdjacency) ~= 2 * nodeCount
            error('FormationB4V45Preflight:ReferenceMessageCount', ...
                'The current V43 page does not have exactly 2N messages.');
        end

        syncHistory = appendWindowPage( ...
            syncHistory, syncAdjacency, window);
        formationHistory = appendWindowPage( ...
            formationHistory, formationAdjacency, window);
        if size(syncHistory, 3) == window
            rollingWindowCount = rollingWindowCount + 1;
            assertRollingWindow(syncHistory, ...
                routeInput.formationPhysicalUidsBySensor, ...
                'sync-b4');
            assertRollingWindow(formationHistory, ...
                routeInput.formationPhysicalUidsBySensor, ...
                'formation-b4');
        end

        referenceCounts(localTimeIdx) = nnz(referenceAdjacency);
        syncCounts(localTimeIdx) = nnz(syncAdjacency);
        formationCounts(localTimeIdx) = nnz(formationAdjacency);
        if mod(currentTime, window) == 0
            cycleMask = auditedTimes >= currentTime - window + 1 & ...
                auditedTimes <= currentTime;
            if nnz(cycleMask) == window && ...
                    isequal(auditedTimes(cycleMask), ...
                        currentTime - window + 1:currentTime)
                alignedCycleCount = alignedCycleCount + 1;
                assertAlignedSaving(referenceCounts(cycleMask), ...
                    syncCounts(cycleMask), 'sync-b4');
                assertAlignedSaving(referenceCounts(cycleMask), ...
                    formationCounts(cycleMask), 'formation-b4');
            end
        end

        inputHashes{localTimeIdx} = ...
            computeCanonicalValueSha256(routeInput);
        referenceHashes{localTimeIdx} = routePageHash( ...
            referenceAdjacency, referenceWeights);
        syncHashes{localTimeIdx} = routePageHash( ...
            syncAdjacency, syncWeights);
        formationHashes{localTimeIdx} = routePageHash( ...
            formationAdjacency, formationWeights);
        if localTimeIdx == 1 || localTimeIdx == timeCount || ...
                mod(localTimeIdx, progressEvery) == 0
            fprintf('  %s seed=%d t=%d/%d passed\n', ...
                presetName, seed, currentTime, ...
                config.simulationLength);
        end
    catch errorInfo
        failure.identifier = nonemptyIdentifier(errorInfo.identifier);
        failure.message = errorInfo.message;
        return;
    end
end

fullHorizonCovered = isequal(auditedTimes, 1:config.simulationLength);
expectedRollingWindows = max(timeCount - window + 1, 0);
if fullHorizonCovered && (rollingWindowCount ~= ...
        config.simulationLength - window + 1 || ...
        alignedCycleCount ~= config.simulationLength / window)
    failure.currentTime = config.simulationLength;
    failure.phase = 'coverage-accounting';
    failure.identifier = 'FormationB4V45Preflight:CoverageDrift';
    failure.message = ...
        'The full-horizon rolling-window/cycle counts drifted.';
    return;
end

value = emptyCase();
value.caseId = sprintf('%s__seed%d__full-route', presetName, seed);
value.presetName = presetName;
value.seed = seed;
value.simulationLength = config.simulationLength;
value.auditedTimes = auditedTimes;
value.auditedTimeCount = timeCount;
value.fullHorizonCovered = fullHorizonCovered;
value.nodeCount = nodeCount;
value.formationCount = formationCount;
value.physicalUidRegistryCanonicalSha256 = identity.canonicalSha256;
value.causalBaseGraphCanonicalSha256 = ...
    causalBaseRegistry.canonicalSha256;
value.causalBaseGraphSelectionMode = ...
    causalBaseRegistry.selectionMode;
value.causalFormationPairPhysicalUids = ...
    causalBaseRegistry.formationPairPhysicalUids;
value.currentPageInputCanonicalSha256ByTime = inputHashes;
value.referencePageCanonicalSha256ByTime = referenceHashes;
value.syncB4PageCanonicalSha256ByTime = syncHashes;
value.formationB4PageCanonicalSha256ByTime = formationHashes;
value.referenceMessageCountByTime = referenceCounts;
value.syncB4MessageCountByTime = syncCounts;
value.formationB4MessageCountByTime = formationCounts;
value.rollingWindowCount = rollingWindowCount;
value.expectedRollingWindowCountForAuditedSpan = ...
    expectedRollingWindows;
value.alignedCycleCount = alignedCycleCount;
value.everyAlignedCycleSavingFraction = 3 / 8;
value.structuralChecksPassed = true;
value.routeReceivesCurrentPageOnly = true;
value.posteriorUsed = false;
value.truthUsed = false;
value.measurementUsed = false;
value.futurePagePassedToRoute = false;
value.realizedDeliveryUniformsUsed = false;
value.trackingOutcomeScored = false;
value.trackingOutcomeAuthorized = false;
value.validationClaimAllowed = false;
value.developmentEvidenceOnly = true;
value.canonicalSha256 = '';
value.canonicalSha256 = computeCanonicalValueSha256( ...
    rmfield(value, 'canonicalSha256'));
end

function routeInput = applyInputTamper(routeInput, mode)
switch mode
    case 'uniform-field'
        routeInput.realizedDeliveryUniforms = ...
            zeros(size(routeInput.physicalAdjacency));
    case 'future-page'
        routeInput.physicalAdjacency = repmat( ...
            routeInput.physicalAdjacency, 1, 1, 2);
end
end

function [syncAdjacency, syncWeights, formationAdjacency, ...
        formationWeights] = applyPageTamper(syncAdjacency, ...
            syncWeights, formationAdjacency, formationWeights, ...
            referenceAdjacency, physicalAdjacency, mode)
switch mode
    case 'negative-weight'
        syncWeights(1, 1) = -0.01;
    case 'zero-weight-edge'
        [receiver, sender] = find(syncAdjacency, 1);
        removedWeight = syncWeights(receiver, sender);
        syncWeights(receiver, sender) = 0;
        syncWeights(receiver, receiver) = ...
            syncWeights(receiver, receiver) + removedWeight;
    case 'non-subset'
        nodeCount = size(referenceAdjacency, 1);
        candidates = physicalAdjacency & ~referenceAdjacency & ...
            ~logical(eye(nodeCount));
        linear = find(candidates, 1);
        if isempty(linear)
            linear = 1;
        end
        syncAdjacency(linear) = true;
end
end

function validateMaterializedScenario(config, sensorTrajectories, ...
        metadata, graph, pDropByEdge, identity, causalBaseRegistry)
nodeCount = config.numberOfSensors;
timeCount = config.simulationLength;
if numel(sensorTrajectories) ~= nodeCount || ...
        ~isequal(size(graph.physicalAdjacency), ...
            [nodeCount, nodeCount, timeCount]) || ...
        ~isequal(size(pDropByEdge), ...
            [nodeCount, nodeCount, timeCount]) || ...
        ~isequal(size(graph.positions), [2, nodeCount, timeCount]) || ...
        ~isequal(metadata.sensorPhysicalUids, ...
            identity.sensorPhysicalUids) || ...
        ~isequal(metadata.formationPhysicalUidsBySensor, ...
            identity.formationPhysicalUidsBySensor) || ...
        ~strcmp(metadata.physicalIdentityRegistryCanonicalSha256, ...
            identity.canonicalSha256) || ...
        ~isstruct(causalBaseRegistry) || ...
        ~strcmp(causalBaseRegistry.contractVersion, ...
            'formation-b4-v45-causal-registered-base-graph-v1') || ...
        causalBaseRegistry.futureGeometryUsed || ...
        causalBaseRegistry.futurePhysicalPageUsed || ...
        causalBaseRegistry.linkProbabilityUsed || ...
        causalBaseRegistry.posteriorUsed || ...
        causalBaseRegistry.truthUsed || ...
        causalBaseRegistry.measurementUsed || ...
        causalBaseRegistry.realizedDeliveryUniformsUsed
    error('FormationB4V45Preflight:ScenarioIdentityDrift', ...
        'The planned sensor/link scenario or UID registry drifted.');
end
end

function graph = materializeCausalPhysicalGraph(config, trajectories)
nodeCount = config.numberOfSensors;
timeCount = config.simulationLength;
positions = zeros(2, nodeCount, timeCount);
for sensorIdx = 1:nodeCount
    positions(:, sensorIdx, :) = reshape( ...
        trajectories{sensorIdx}(1:2, :), 2, 1, timeCount);
end
distances = zeros(nodeCount, nodeCount, timeCount);
physical = false(nodeCount, nodeCount, timeCount);
for currentTime = 1:timeCount
    page = positions(:, :, currentTime);
    for leftIdx = 1:nodeCount-1
        delta = page(:, leftIdx+1:end) - page(:, leftIdx);
        values = sqrt(sum(delta.^2, 1));
        distances(leftIdx, leftIdx+1:end, currentTime) = values;
        distances(leftIdx+1:end, leftIdx, currentTime) = values';
        if isfinite(config.commRange)
            available = values <= config.commRange;
        else
            available = true(size(values));
        end
        physical(leftIdx, leftIdx+1:end, currentTime) = available;
        physical(leftIdx+1:end, leftIdx, currentTime) = available';
    end
end
graph = struct('positions', positions, ...
    'distanceByTime', distances, ...
    'physicalAdjacency', physical);
end

function validateCurrentPageInput(routeInput, nodeCount)
required = {'positions', 'physicalAdjacency', 'pDropByEdge', ...
    'baseAdjacency', 'sensorPhysicalUids', ...
    'formationPhysicalUidsBySensor', 'sensorGroupIds', 'currentTime'};
actual = fieldnames(routeInput);
if numel(actual) ~= numel(required) || ...
        ~all(ismember(actual, required)) || ...
        ~all(ismember(required, actual)) || ...
        ~isequal(size(routeInput.positions), [2, nodeCount]) || ...
        ~isequal(size(routeInput.physicalAdjacency), ...
            [nodeCount, nodeCount]) || ...
        ~isequal(size(routeInput.pDropByEdge), [nodeCount, nodeCount]) || ...
        ~isequal(size(routeInput.baseAdjacency), [nodeCount, nodeCount]) || ...
        numel(routeInput.sensorPhysicalUids) ~= nodeCount || ...
        numel(unique(routeInput.sensorPhysicalUids)) ~= nodeCount || ...
        numel(routeInput.formationPhysicalUidsBySensor) ~= nodeCount || ...
        numel(routeInput.sensorGroupIds) ~= nodeCount || ...
        any(~isfinite(routeInput.positions(:))) || ...
        any(~isfinite(routeInput.pDropByEdge(:))) || ...
        any(routeInput.pDropByEdge(:) < 0) || ...
        any(routeInput.pDropByEdge(:) > 1) || ...
        ~isscalar(routeInput.currentTime) || ...
        routeInput.currentTime < 1 || ...
        routeInput.currentTime ~= round(routeInput.currentTime)
    error('FormationB4V45Preflight:RouteInputBoundary', ...
        ['The route input is not an exact finite current-page payload ', ...
         'with the registered eight-field allowlist.']);
end
end

function context = adaptCurrentPageToV43Context(routeInput)
nodeCount = numel(routeInput.sensorPhysicalUids);
model = struct();
model.dynamicTopologyScenario = struct( ...
    'config', struct('sensorGroupIds', ...
        reshape(routeInput.sensorGroupIds, 1, [])), ...
    'staticAdjacency', logical(routeInput.baseAdjacency));
context = struct();
context.localPosteriorBySensor = cell(1, nodeCount);
context.model = model;
context.baseAdjacency = logical(routeInput.baseAdjacency);
context.physicalAdjacency = logical(routeInput.physicalAdjacency);
context.positions = routeInput.positions;
context.sensorPhysicalUids = ...
    reshape(routeInput.sensorPhysicalUids, 1, []);
context.formationPhysicalUidsBySensor = ...
    reshape(routeInput.formationPhysicalUidsBySensor, 1, []);
context.commConfig = struct('pDropByEdge', routeInput.pDropByEdge);
context.currentTime = routeInput.currentTime;
context.directedMessageBudget = 2 * nodeCount;
if any(~cellfun(@isempty, context.localPosteriorBySensor))
    error('FormationB4V45Preflight:PosteriorBoundary', ...
        'The V43 compatibility container unexpectedly holds a posterior.');
end
end

function options = dutyOptions(pattern)
options = struct('period', 4, 'dutyLayer', 'all', ...
    'phasePattern', pattern, 'activeResidualWeight', 0.20, ...
    'dominantWeight', 0.70, 'referenceResidualWeight', 0.05);
end

function assertBoundaryDetails(details, armName)
required = {'currentGeometryUsed', 'currentLinkReliabilityUsed', ...
    'currentPhysicalActionSetUsed', 'posteriorUsed', 'truthUsed', ...
    'measurementUsed', 'futureOutcomeUsed', ...
    'realizedDeliveryUniformsUsed', 'trackingOutcomeScored', ...
    'validationClaimAllowed', 'developmentEvidenceOnly'};
if ~all(isfield(details, required)) || ...
        ~details.currentGeometryUsed || ...
        ~details.currentLinkReliabilityUsed || ...
        ~details.currentPhysicalActionSetUsed || ...
        details.posteriorUsed || details.truthUsed || ...
        details.measurementUsed || details.futureOutcomeUsed || ...
        details.realizedDeliveryUniformsUsed || ...
        details.trackingOutcomeScored || ...
        details.validationClaimAllowed || ...
        ~details.developmentEvidenceOnly
    error('FormationB4V45Preflight:RouteBoundaryViolation', ...
        '%s crossed the causal development-only boundary.', armName);
end
end

function assertRoutePage(adjacency, weights, physical, reference, ...
        armName, requireStrongConnectivity)
nodeCount = size(adjacency, 1);
allowedWeights = adjacency | logical(eye(nodeCount));
if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(diag(adjacency)) || ...
        any(adjacency(:) & ~physical(:))
    error('FormationB4V45Preflight:PhysicalViolation', ...
        '%s contains a nonphysical or self communication edge.', armName);
end
if ~isempty(reference) && any(adjacency(:) & ~reference(:))
    error('FormationB4V45Preflight:SubsetViolation', ...
        '%s is not a same-time subset of the V43 page.', armName);
end
if any(~isfinite(weights(:))) || any(weights(:) < -1e-12) || ...
        any(weights(:) > 1 + 1e-12) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        any(weights(:) > 1e-12 & ~allowedWeights(:))
    error('FormationB4V45Preflight:FusionWeightViolation', ...
        '%s fusion weights are not nonnegative row-stochastic.', armName);
end
positiveOffDiagonal = weights > 1e-12;
positiveOffDiagonal(1:nodeCount+1:end) = false;
if ~isequal(positiveOffDiagonal, logical(adjacency))
    error('FormationB4V45Preflight:FusionWeightSupportViolation', ...
        '%s adjacency and positive off-diagonal support disagree.', ...
        armName);
end
assertFrozenWeightPattern(adjacency, weights, armName);
if requireStrongConnectivity && ~isStronglyConnected(adjacency)
    error('FormationB4V45Preflight:InstantaneousV43Disconnected', ...
        '%s is not strongly connected.', armName);
end
end

function assertFrozenWeightPattern(adjacency, weights, armName)
nodeCount = size(adjacency, 1);
tolerance = 1e-12;
for receiver = 1:nodeCount
    sources = find(adjacency(receiver, :));
    offDiagonal = sort(weights(receiver, sources));
    selfWeight = weights(receiver, receiver);
    if strcmp(armName, 'v43-reference')
        passed = numel(sources) == 2 && ...
            all(abs(offDiagonal - [0.05, 0.70]) <= tolerance) && ...
            abs(selfWeight - 0.25) <= tolerance;
    elseif numel(sources) == 1
        passed = abs(offDiagonal - 0.70) <= tolerance && ...
            abs(selfWeight - 0.30) <= tolerance;
    elseif numel(sources) == 2
        passed = all(abs(offDiagonal - [0.20, 0.70]) <= tolerance) && ...
            abs(selfWeight - 0.10) <= tolerance;
    else
        passed = false;
    end
    if ~passed
        error('FormationB4V45Preflight:FrozenWeightPatternViolation', ...
            '%s deviates from the frozen V43/B4 row-weight pattern.', ...
            armName);
    end
end
end

function pages = appendWindowPage(pages, page, window)
pages(:, :, end + 1) = logical(page);
if size(pages, 3) > window
    pages = pages(:, :, end - window + 1:end);
end
end

function assertRollingWindow(pages, formationUidsBySensor, armName)
sensorUnion = any(pages, 3);
formationUnion = collapseToPhysicalFormations( ...
    sensorUnion, formationUidsBySensor);
if ~isStronglyConnected(sensorUnion)
    error('FormationB4V45Preflight:RollingSensorDisconnected', ...
        '%s rolling-B4 sensor union is not strongly connected.', armName);
end
if ~isStronglyConnected(formationUnion)
    error('FormationB4V45Preflight:RollingFormationDisconnected', ...
        '%s rolling-B4 formation union is not strongly connected.', ...
        armName);
end
end

function formation = collapseToPhysicalFormations(adjacency, uidBySensor)
uids = sort(unique(reshape(uidBySensor, 1, [])));
formation = false(numel(uids));
for receiverIdx = 1:numel(uids)
    receivers = uidBySensor == uids(receiverIdx);
    for senderIdx = 1:numel(uids)
        senders = uidBySensor == uids(senderIdx);
        formation(receiverIdx, senderIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(uids)+1:end) = false;
end

function assertAlignedSaving(referenceCounts, candidateCounts, armName)
referenceTotal = sum(referenceCounts);
candidateTotal = sum(candidateCounts);
if referenceTotal <= 0 || ...
        8 * (referenceTotal - candidateTotal) ~= ...
            3 * referenceTotal
    error('FormationB4V45Preflight:AlignedCycleSaving', ...
        ['%s aligned B=4 cycle does not have exactly 37.5%% ', ...
         'attempted-message saving.'], armName);
end
end

function connected = isStronglyConnected(adjacency)
adjacency = logical(adjacency);
adjacency(1:size(adjacency, 1)+1:end) = false;
senderAdjacency = adjacency';
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
nodeCount = size(adjacency, 1);
if nodeCount == 0
    connected = false;
    return;
end
visited = false(1, nodeCount);
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function hash = routePageHash(adjacency, weights)
hash = computeCanonicalValueSha256(struct( ...
    'adjacency', logical(adjacency), 'fusionWeights', weights));
end

function validateRequestedCases(presets, seeds, protocol)
if ~iscell(presets) || isempty(presets) || ...
        any(~cellfun(@ischar, presets)) || ...
        numel(unique(presets)) ~= numel(presets) || ...
        any(~ismember(presets, protocol.registeredPresets)) || ...
        ~isnumeric(seeds) || ~isreal(seeds) || isempty(seeds) || ...
        any(~isfinite(seeds)) || any(seeds ~= round(seeds)) || ...
        numel(unique(seeds)) ~= numel(seeds) || ...
        any(~ismember(seeds, protocol.registeredSeeds))
    error('FormationB4V45Preflight:UnregisteredCases', ...
        'Only the published V43 development presets/seeds may be used.');
end
expectedPresets = protocol.registeredPresets( ...
    ismember(protocol.registeredPresets, presets));
expectedSeeds = protocol.registeredSeeds( ...
    ismember(protocol.registeredSeeds, seeds));
if ~isequal(presets, expectedPresets) || ...
        ~isequal(reshape(seeds, 1, []), expectedSeeds)
    error('FormationB4V45Preflight:CaseOrder', ...
        'The requested cases must preserve the published V43 order.');
end
seeds = reshape(seeds, 1, []); %#ok<NASGU>
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end

function identifier = nonemptyIdentifier(identifier)
if isempty(identifier)
    identifier = 'FormationB4V45Preflight:UnidentifiedFailure';
end
end

function value = emptyFailure()
value = struct('presetName', '', 'seed', NaN, 'currentTime', NaN, ...
    'phase', '', 'identifier', '', 'message', '');
end

function value = emptyCase()
value = struct('caseId', '', 'presetName', '', 'seed', NaN, ...
    'simulationLength', NaN, 'auditedTimes', zeros(1, 0), ...
    'auditedTimeCount', 0, 'fullHorizonCovered', false, ...
    'nodeCount', NaN, 'formationCount', NaN, ...
    'physicalUidRegistryCanonicalSha256', '', ...
    'causalBaseGraphCanonicalSha256', '', ...
    'causalBaseGraphSelectionMode', '', ...
    'causalFormationPairPhysicalUids', zeros(0, 2), ...
    'currentPageInputCanonicalSha256ByTime', {{}}, ...
    'referencePageCanonicalSha256ByTime', {{}}, ...
    'syncB4PageCanonicalSha256ByTime', {{}}, ...
    'formationB4PageCanonicalSha256ByTime', {{}}, ...
    'referenceMessageCountByTime', zeros(1, 0), ...
    'syncB4MessageCountByTime', zeros(1, 0), ...
    'formationB4MessageCountByTime', zeros(1, 0), ...
    'rollingWindowCount', 0, ...
    'expectedRollingWindowCountForAuditedSpan', 0, ...
    'alignedCycleCount', 0, ...
    'everyAlignedCycleSavingFraction', NaN, ...
    'structuralChecksPassed', false, ...
    'routeReceivesCurrentPageOnly', false, ...
    'posteriorUsed', false, 'truthUsed', false, ...
    'measurementUsed', false, 'futurePagePassedToRoute', false, ...
    'realizedDeliveryUniformsUsed', false, ...
    'trackingOutcomeScored', false, ...
    'trackingOutcomeAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true, 'canonicalSha256', '');
end
