function protocol = getAddressableRiskAdaptivePayloadV96Protocol()
% GETADDRESSABLERISKADAPTIVEPAYLOADV96PROTOCOL Scale-free payload gate.

source = getFovAwarePersistentRiskCoverageV94Protocol();
protocol = struct();
protocol.id = 'addressable-risk-adaptive-payload-v96-v1';
protocol.contractVersion = ...
    'addressable-risk-adaptive-payload-v96-protocol-v1';
protocol.receiverMode = source.receiverMode;
protocol.horizonSteps = 3;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.positiveSupportThreshold = source.positiveSupportThreshold;
protocol.coverageTargetFraction = 0.80;
protocol.maximumUsefulLossToRescueRatio = 1.0;
protocol.requireZeroCrossSupportedDownwardCrossings = true;
protocol.minimumMeanGainPercent = 5;
protocol.minimumWorstSensorGainPercent = 0;
protocol.minimumFormationGainPercent = 0;
protocol.minimumWindowConsensusGainPercent = 0;
protocol.minimumTerminalConsensusGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.referencePolicyName = source.referencePolicyName;
protocol.outcomePolicyName = ...
    'addressable-risk-adaptive-payload-v96-v1';
protocol.baselineName = source.baselineName;
protocol.cases = source.cases;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v96', 'addressable_risk_adaptive_payload');
protocol.structuralOutputRoot = fullfile( ...
    protocol.outputRoot, 'structural_gate');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.fullEpisodeTrackingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V96 replaces the scale-diluted whole-network risk floor with ', ...
    'conditional coverage of safely addressable current risk. A ', ...
    'formation is addressable only when withholding its complete ', ...
    'cross-formation posterior causes no cross-supported downward ', ...
    'decision crossing. The smallest guarded subset covering at least ', ...
    '80% of addressable rescue is frozen before tracking truth is read. ', ...
    'Reference, one-step and persistent arms share the same static ', ...
    'carrier graph, cached posterior, measurements, link uniforms, ', ...
    'filter RNG and communication constraints. These opened anchors are ', ...
    'development evidence only.'];
end
