function protocol = getAsymmetricEtaRetentionV267Protocol()
% GETASYMMETRICETARETENTIONV267PROTOCOL Protect sub-MAP support.

source = getEtaProjectedLabelTrustV266Protocol();
protocol = source;
protocol.id = 'asymmetric-eta-retention-v267-v1';
protocol.contractVersion = ...
    'asymmetric-eta-retention-v267-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v267-asymmetric-eta-retention';
protocol.policyName = 'asymmetric-eta-retention-v267-policy';
protocol.maximumSubMapReferenceLogOddsDrop = 0;
protocol.resultContractVersion = ...
    'asymmetric-eta-retention-v267-result-v1';
protocol.resultFileName = ...
    'ASYMMETRIC_ETA_RETENTION_V267_CONTINUATION.mat';
protocol.reportFileName = ...
    'ASYMMETRIC_ETA_RETENTION_V267_CONTINUATION.md';
protocol.reportTitle = 'V267 asymmetric eta retention';
protocol.displayName = 'V267 asymmetric eta retention';
protocol.passDecision = ...
    'run-one-full-causal-m24-arm-with-frozen-asymmetric-eta-retention';
protocol.failDecision = ...
    'inspect-source-value-or-packet-level-routing-after-support-protection';
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v267', ...
    'asymmetric_eta_retention', 'm24_seed1301_t57_73');
protocol.evidenceBoundary = [ ...
    'V267 is an outcome-opened M24 continuation mechanism screen. It ', ...
    'keeps the V242 backbone, V265 causal route selection and V266 frozen ', ...
    'source-share grid. The only change is the intended asymmetric ', ...
    'existence-retention semantics: an ordinary MAP-negative label may ', ...
    'gain support but may not lose additional log odds, while a MAP-', ...
    'positive label retains the registered 0.25 drop allowance and cannot ', ...
    'cross the 0.5 extraction threshold. Every attempted complete-label ', ...
    'payload remains charged and centralized risk-synopsis cost remains ', ...
    'excluded. No truth or future outcome is visible to the controller, ', ...
    'so the result is mechanism evidence only.'];
end
