function protocol = getAlternativeGatewayV117Protocol()
% GETALTERNATIVEGATEWAYV117PROTOCOL Same-source F6 gateway oracle.

base = getDelayedLabelReturnOracleV116Protocol();
protocol = base;
protocol.id = 'alternative-gateway-v117-v1';
protocol.contractVersion = 'alternative-gateway-v117-protocol-v1';
protocol.outcomePolicyName = 'alternative-gateway-v117-v1';
protocol.executionProfile = 'v117-alternative-gateway';
protocol.bankVariant = 'alternative-gateway-v117';
protocol.gatewaySourceSensorId = base.boundarySourceSensorId;
protocol.originalGatewayReceiverSensorId = ...
    base.boundaryReceiverSensorId;
protocol.candidateGatewayReceiverSensorIds = [33, 35, 34];
protocol.candidateActionNames = arrayfun( ...
    @(receiverId) sprintf('v117-source27-to-gateway%d-h8', receiverId), ...
    protocol.candidateGatewayReceiverSensorIds, ...
    'UniformOutput', false);
protocol.candidatePayloadModes = repmat( ...
    {'abstention-only'}, 1, numel(protocol.candidateActionNames));
protocol.gatewayFormationIdsByTime = ...
    base.baseProtectionFormationIdsByTime;
protocol.v116Top5ActionName = base.candidateActionNames{1};
protocol.v116ScreenPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v116', 'delayed_label_return_oracle', ...
    'x36_t72_h8', 'screen', ...
    ['TRACKING_ALIGNED_X36_SCHEDULE_H8_', ...
     'X36_FORMATION_FOV_SEED211_T72_D8.mat']);
protocol.resultContractVersion = ...
    'alternative-gateway-v117-x36-t72-result-v1';
protocol.resultFileStem = ...
    'ALTERNATIVE_GATEWAY_V117_X36_T72_RESULT';
protocol.reportTitle = ...
    'V117 same-source alternative F6 gateway: X36 t72 H=8';
protocol.runLabel = 'V117 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v117', 'alternative_gateway');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V117 is a privileged opened-development X36 seed-211 t=72 H=8 ', ...
    'gateway-location oracle. It keeps sender 27, the clockwise ', ...
    'F5-to-F6 formation edge, the V113 F2--F5 abstention schedule, ', ...
    'message count and fusion-weight multiset fixed. The original ', ...
    '27-to-32 cross residual is moved to receiver 36, 33 or 35, and ', ...
    'the displaced internal F6 residual edge is restored in each arm. ', ...
    'These receivers were frozen from opened current tracking errors; ', ...
    'future H=8 outcomes choose only the reported oracle arm. V117 is ', ...
    'not deployable, validation or generalization evidence.'];
end
