function protocol = ...
    getBackboneResidualEospaTailGuardAdaptiveTrustProtocol()
% GETBACKBONERESIDUALEOSPATAILGUARDADAPTIVETRUSTPROTOCOL Frozen M24 gate.

surrogate = ...
    getBackboneResidualTailGuardAdaptiveTrustProtocol();
protocol = surrogate;
protocol.id = ...
    'backbone-residual-eospa-tail-guard-adaptive-trust-m24-h3-v1';
protocol.predecessorProtocolId = surrogate.id;
protocol.armName = [ ...
    'oracle-backbone-residual-spliced-cycle-', ...
    'eospa-tail-guard-adaptive-current-a70'];
protocol.protectedReceiverObjective = ...
    'maximum-matched-static-current-eospa';
protocol.protectionRiskMetric = ...
    'current-eospa';
protocol.evidencePending = true;
protocol.headroomGatePassed = false;
protocol = removeFieldIfPresent(protocol, ...
    'surrogateTailGuardRejected');
protocol = removeFieldIfPresent(protocol, ...
    'smokeFeasibilityPassed');
protocol = removeFieldIfPresent(protocol, ...
    'smokeFallbackUsed');
protocol = removeFieldIfPresent(protocol, ...
    'smokeEospa');
protocol = removeFieldIfPresent(protocol, ...
    'smokeWorstSensorEospa');
protocol = removeFieldIfPresent(protocol, ...
    'smokeWorstSensorIndex');
protocol = removeFieldIfPresent(protocol, ...
    'smokeCrossFormationEdgeCount');
protocol = removeFieldIfPresent(protocol, ...
    'smokeSourceSha256');
end

function structure = removeFieldIfPresent( ...
        structure, fieldName)
if isfield(structure, fieldName)
    structure = rmfield(structure, fieldName);
end
end
