function protocol = getBackbonePreservingResidualProtocol(variant)
% GETBACKBONEPRESERVINGRESIDUALPROTOCOL Additive residual action-space gate.

if nargin < 1 || isempty(variant)
    variant = 'v1-e05';
end
variant = lower(strrep(char(variant), '_', '-'));
switch variant
    case 'v1-e05'
        residualWeight = 0.05;
        protocolId = ...
            'backbone-preserving-additive-residual-routing-v1';
        predecessorProtocolId = '';
    case 'v2-e10'
        residualWeight = 0.10;
        protocolId = ...
            'backbone-preserving-additive-residual-routing-v2-e10';
        predecessorProtocolId = ...
            'backbone-preserving-additive-residual-routing-v1';
    otherwise
        error(['Unknown backbone-preserving residual protocol ', ...
            'variant: %s.'], variant);
end

protocol = struct();
protocol.id = protocolId;
protocol.variant = variant;
protocol.predecessorProtocolId = predecessorProtocolId;
protocol.evidenceSplit = 'development';
protocol.scenarioPresets = { ...
    'm24-hard', 'x36-clean-scale'};
protocol.screeningSeeds = 7;
protocol.confirmationSeeds = [11, 17];
protocol.continuationStartTime = 75;
protocol.continuationEndTime = 77;
protocol.dominantSourceWeight = 0.70;
protocol.residualSourceWeight = residualWeight;
protocol.selfWeightWithDistinctResidual = ...
    1 - protocol.dominantSourceWeight - ...
        protocol.residualSourceWeight;
protocol.connectivityWindowLength = 3;
protocol.dominantBackboneMode = 'fixed-index-star';
protocol.residualBackboneMode = ...
    'fixed-balanced-cycle';
protocol.localArm = 'local';
protocol.fixedIndexW50Arm = ...
    'directed-fixed-index-w50';
protocol.fixedIndexW70Arm = ...
    'directed-fixed-index-w70';
residualWeightToken = round( ...
    100 * protocol.residualSourceWeight);
protocol.matchedResidualStaticArm = sprintf( ...
    'backbone-residual-static-a70-e%02d', ...
    residualWeightToken);
protocol.analyticArm = sprintf( ...
    'backbone-residual-analytic-a70-e%02d', ...
    residualWeightToken);
protocol.currentOracleArm = sprintf( ...
    'oracle-backbone-residual-current-a70-e%02d', ...
    residualWeightToken);
protocol.minimaxOracleArm = sprintf( ...
    'oracle-backbone-residual-minimax-a70-e%02d', ...
    residualWeightToken);
protocol.baselineArms = { ...
    protocol.fixedIndexW50Arm, ...
    protocol.fixedIndexW70Arm, ...
    protocol.matchedResidualStaticArm};
protocol.armNames = { ...
    protocol.localArm, ...
    protocol.fixedIndexW50Arm, ...
    protocol.fixedIndexW70Arm, ...
    protocol.matchedResidualStaticArm, ...
    protocol.analyticArm, ...
    protocol.currentOracleArm, ...
    protocol.minimaxOracleArm};
protocol.maximumDirectedMessageMultiplier = 2;
protocol.minimumMeanTrackingGainFraction = 0.05;
protocol.maximumWorstNodeRegressionFraction = 0;
protocol.maximumAttemptedByteDeviationFraction = 0.02;
protocol.requireMeanTrackingBetterThanLocal = true;
protocol.requireWorstNodeNoWorseThanLocal = true;
protocol.requireAllMatureRollingWindowsStrong = true;
protocol.requireZeroTopologyInfeasibility = true;
protocol.requireZeroSafetyEmergency = true;
protocol.requireZeroPolicyRepair = true;
protocol.privilegedHeadroomUsesTruth = true;
protocol.privilegedHeadroomDeployable = false;
protocol.featuresUseTruth = false;
protocol.returnLabelsUseFutureOutcome = true;
protocol.returnDataGenerationAuthorized = false;
protocol.criticTrainingAuthorized = false;
protocol.x36PolicyRunAuthorized = false;
protocol.heldoutClaimAllowed = false;
protocol.v1HeadroomGatePassed = false;
protocol.v1MinimumMatchedStaticGainFraction = ...
    0.0412102333079491;
protocol.v2EscalationIsSequentialDevelopment = ...
    strcmp(variant, 'v2-e10');
protocol.v2EscalationChangesOnlyResidualWeight = ...
    strcmp(variant, 'v2-e10');
end
