function protocol = getBudgetedLocalGatewayTeacherV255Protocol()
% GETBUDGETEDLOCALGATEWAYTEACHERV255PROTOCOL More independent local data.

source = getCausalGatewayEmbeddingV250Protocol();
method = getBudgetedLocalGatewayRepairV255Protocol();
protocol = source;
protocol.id = 'budgeted-local-gateway-teacher-v255-v1';
protocol.contractVersion = ...
    'budgeted-local-gateway-teacher-v255-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.methodProtocolId = method.id;
protocol.armId = 'v255-budgeted-local-gateway-teacher';
protocol.allowedPresets = method.allowedPresets;
protocol.existingDevelopmentSeeds = method.trainingSeeds;
protocol.additionalTrainingSeeds = ...
    method.additionalExpectedOutcomeTrainingSeeds;
protocol.calibrationSeeds = method.calibrationSeeds;
protocol.developmentHoldoutSeeds = method.developmentHoldoutSeeds;
protocol.untouchedCompleteEpisodeSeeds = ...
    method.untouchedCompleteEpisodeSeeds;
protocol.expectedOutcomeTrainingSeeds = [ ...
    protocol.existingDevelopmentSeeds, ...
    protocol.additionalTrainingSeeds];
protocol.allowedSeeds = [protocol.additionalTrainingSeeds, ...
    protocol.calibrationSeeds, protocol.developmentHoldoutSeeds];
protocol.anchorTimes = method.anchorTimes;
protocol.horizonSteps = method.horizonSteps;
protocol.maximumChangedDirectedGatewayArcs = 1;
protocol.maximumCandidatesPerDirectedSlot = 2;
protocol.maximumRestrictedCandidateCount = 21;
protocol.minimumCandidateCount = 7;
protocol.minimumJointPositiveAnchorCount = 3;
protocol.maximumFormationRegressionPercent = ...
    method.maximumFormationRegressionPercent;
protocol.minimumAggregateCoreGainPercent = 0;
protocol.minimumAggregateByteSavingPercent = ...
    -method.developmentIncrementalByteCapPercentRelativeV242;
protocol.includeControlAttemptedBytesInOracleComparison = true;
protocol.controlChargeAppliesToReference = false;
protocol.controlChargeAppliesOncePerHold = true;
protocol.controlSynopsisMode = method.controlSynopsisMode;
protocol.compactNodeBytesPerSensor = ...
    method.compactNodeBytesPerSensor;
protocol.routeCommandHeaderBytes = method.routeCommandHeaderBytes;
protocol.routeCommandBytesPerChangedArc = ...
    method.routeCommandBytesPerChangedArc;
protocol.controlCollectionCountPerHold = ...
    method.controlCollectionCountPerHold;
protocol.candidateBankMode = ...
    'v242-reference-plus-ranked-single-directed-arc';
protocol.resultContractVersion = ...
    'budgeted-local-gateway-teacher-v255-result-v1';
protocol.windowContractVersion = ...
    'budgeted-local-gateway-teacher-v255-window-v1';
protocol.oracleMatName = ...
    'BUDGETED_LOCAL_GATEWAY_TEACHER_V255.mat';
protocol.oracleReportName = ...
    'BUDGETED_LOCAL_GATEWAY_TEACHER_V255.md';
protocol.reportTitle = 'V255 budgeted local gateway teacher';
protocol.runLabel = 'V255';
protocol.continuationSource = 'v255-v242-reference-cache';
protocol.cacheFilePrefix = 'V255_V242_REFERENCE';
protocol.oraclePassDecision = ...
    'include-seed-in-v255-expected-outcome-training-pool';
protocol.oracleFailDecision = ...
    'retain-complete-local-arms-as-negative-or-low-support-data';
protocol.outputRoot = fullfile(method.outputRoot, 'teacher');
protocol.cacheRoot = fullfile(protocol.outputRoot, 'reference_cache');
protocol.oracleOutputRoot = protocol.outputRoot;
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V255 teacher generation evaluates V242 plus at most two one-arc ', ...
    'physical gateway replacements per directed formation-tree slot. ', ...
    'Every non-reference action is charged one compact synopsis from the ', ...
    'two incident formations and one changed-arc route command for the ', ...
    'complete H=3 hold. Seeds 1307--1310 add independent expected-value ', ...
    'training data; 1311--1312 are reserved for calibration and 1306 is ', ...
    'the frozen development holdout. Seed 1305 receives neither teacher ', ...
    'labels nor model selection and remains reserved for a complete M24 ', ...
    'episode. Truth and future outcomes are used only to label paired ', ...
    'offline arms, never to construct the candidate bank.'];

registered = [protocol.existingDevelopmentSeeds, protocol.allowedSeeds, ...
    protocol.untouchedCompleteEpisodeSeeds];
valid = numel(unique(registered)) == numel(registered) && ...
    isequal(protocol.expectedOutcomeTrainingSeeds, [ ...
        protocol.existingDevelopmentSeeds, ...
        protocol.additionalTrainingSeeds]) && ...
    protocol.maximumChangedDirectedGatewayArcs == 1 && ...
    protocol.maximumCandidatesPerDirectedSlot >= 1 && ...
    protocol.maximumRestrictedCandidateCount >= ...
        1 + protocol.maximumCandidatesPerDirectedSlot * 3 && ...
    protocol.includeControlAttemptedBytesInOracleComparison && ...
    ~protocol.controlChargeAppliesToReference && ...
    protocol.controlChargeAppliesOncePerHold && ...
    protocol.controlCollectionCountPerHold == 1;
if ~valid
    error('BudgetedLocalGatewayTeacherV255:InvalidProtocol', ...
        'The V255 teacher split, local bank or control charge is invalid.');
end
end
