function protocol = getBudgetedObservationSupportedRepairV197Protocol( ...
        horizonSteps)
% GETBUDGETEDOBSERVATIONSUPPORTEDREPAIRV197 Top-one repair token.

base = getObservationSupportedSetSafeV194Protocol();
if nargin < 1 || isempty(horizonSteps)
    horizonSteps = base.horizonSteps;
end
if ~isscalar(horizonSteps) || ~isfinite(horizonSteps) || ...
        horizonSteps ~= round(horizonSteps) || ...
        horizonSteps < base.horizonSteps
    error('BudgetedSetRepairV197:InvalidHorizon', ...
        'The repair controller requires an integer horizon >= 3.');
end
protocol = base;
protocol.horizonSteps = horizonSteps;
protocol.id = 'budgeted-observation-supported-repair-v197-v1';
protocol.contractVersion = ...
    'budgeted-observation-supported-repair-v197-protocol-v1';
protocol.outcomePolicyName = ...
    'budgeted-observation-supported-repair-v197-v1';
protocol.executionProfile = ...
    'v197-budgeted-observation-supported-repair';
protocol.baseProtocolId = base.id;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v197', 'budgeted_observation_supported_repair');
protocol.maximumReleaseFormationsPerWindow = 1;
protocol.releaseCooldownSteps = 3;
protocol.releaseHistoryDepth = protocol.releaseCooldownSteps - 1;
protocol.evidenceBoundary = [ ...
    'V197 computes the current V99 omission proposal and the V194 ', ...
    'observation-unsupported set-entry projection. If no full-posterior ', ...
    'repair occurred during the preceding two completed pages, it restores ', ...
    'at most one proposed formation: the formation with the largest current ', ...
    'maximum receiver set-entry risk. The ordinary message builder and byte ', ...
    'ledger execute and charge the projected payloads. The policy sees only ', ...
    'current observable posteriors and its own past release decisions; it ', ...
    'uses no truth, future measurement or future outcome. Opened anchors ', ...
    'remain development evidence only.'];
end
