function protocol = getBudgetAdaptiveSourceOfferProtocolV231()
% GETBUDGETADAPTIVESOURCEOFFERPROTOCOLV231 Recall-first offer contract.
%
% Source offers are a proposal set, not the final action decision.  Their
% breadth is therefore derived from causal communication credit instead of
% an arbitrary top-two cap.  The beneficiary still purchases at most one
% complete label and uses the unchanged V226 eta/KLA projection.

base = getFusionAwareSourceOfferProtocolV229();
ranker = getCausalSourceOfferRankerV230Protocol();
repair = getBudgetRecycledFormationRepairV188Protocol();
protocol = struct();
protocol.id = 'budget-adaptive-source-offer-v231-v1';
protocol.contractVersion = ...
    'budget-adaptive-source-offer-v231-protocol-v1';
protocol.baseProtocolId = base.id;
protocol.scoreProtocolId = ranker.id;
protocol.status = 'same-state-recall-screen';

control = struct();
control.solicitationHeaderBytes = ...
    base.offer.solicitationHeaderBytes;
control.responseHeaderBytes = base.offer.responseHeaderBytes;
control.offerRecordBytes = base.offer.offerRecordBytes;
control.maximumControlShareOfSpendableCredit = 0.35;
control.maximumOffersPerSource = 12;
control.minimumOffersPerSourceForExecution = 2;
control.modeAllocation = ...
    'half-existence-surprise-half-spatial-utility';
control.byteFormula = 'S*(h_s+h_r+M*b_o)';
control.offerBreadthRule = [ ...
    'largest integer M within the frozen control-credit share, capped ', ...
    'before any tracking outcome is opened'];
control.communicationCreditReserveFraction = ...
    repair.communicationCreditReserveFraction;
control.completePayloadRequestsPerPage = 1;
control.retryAllowed = false;
protocol.control = control;

protocol.proposalObjective = 'high-recall-byte-bounded-candidate-set';
protocol.finalSelectionObjective = ...
    'beneficiary-conditioned-finite-horizon-value-under-safe-projection';
protocol.sameStateScreenPassRule = ...
    'all teacher rows recalled by the budget-derived proposal breadth';
protocol.sameStateScreenAuthorizes = ...
    'actual runtime-cache persistence and causal proposal-recall audit';
protocol.onlinePolicyImplemented = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V231 replaces the failed arbitrary top-two source cap with a breadth ', ...
    'computed from causal byte credit. Same-state recall shows only whether ', ...
    'the proposal layer can retain the opened teacher rows while preserving ', ...
    'positive communication saving. It does not validate the runtime cache, ', ...
    'the beneficiary coordinator, tracking gain, or generalization.'];

assertProtocol(protocol, base, repair);
end

function assertProtocol(protocol, base, repair)
control = protocol.control;
if ~strcmp(protocol.status, 'same-state-recall-screen') || ...
        control.solicitationHeaderBytes ~= ...
            base.offer.solicitationHeaderBytes || ...
        control.responseHeaderBytes ~= base.offer.responseHeaderBytes || ...
        control.offerRecordBytes ~= base.offer.offerRecordBytes || ...
        abs(control.maximumControlShareOfSpendableCredit - 0.35) > 1e-12 || ...
        control.maximumOffersPerSource ~= 12 || ...
        control.minimumOffersPerSourceForExecution ~= 2 || ...
        abs(control.communicationCreditReserveFraction - ...
            repair.communicationCreditReserveFraction) > 1e-12 || ...
        control.completePayloadRequestsPerPage ~= 1 || ...
        control.retryAllowed || protocol.onlinePolicyImplemented || ...
        protocol.validationClaimAllowed
    error('BudgetAdaptiveSourceOfferV231:ProtocolDrift', ...
        'The frozen V231 source-offer contract drifted.');
end
end
