function protocol = getBraidedHandoverOpportunityV84Protocol()
% GETBRAIDEDHANDOVEROPPORTUNITYV84PROTOCOL Handover source discovery.

v66 = getInfluenceAwareDecisionBreadthV66Protocol();
protocol = struct();
protocol.id = 'braided-handover-opportunity-v84-v1';
protocol.contractVersion = ...
    'braided-handover-opportunity-v84-protocol-v1';
protocol.referencePolicyName = ...
    'formation-h3-current-physical-path-reference-v1';
protocol.presets = { ...
    'm24-formation-fov-braided-handover', ...
    'x36-formation-fov-braided-handover'};
protocol.allSeeds = 41;
protocol.snapshotTimes = 40:4:140;
protocol.filterSeedOffset = 100000;
protocol.expectedNodeCounts = [24, 36];
protocol.expectedFormationCounts = [4, 6];
protocol.expectedMinimumSensorTargetSeparation = 30;
protocol.horizonSteps = v66.horizonSteps;
protocol.positiveSupportThreshold = v66.positiveSupportThreshold;
protocol.decisionExistenceThreshold = 0.50;
protocol.sourceWeight = 0.05;
protocol.minimumLocalNetFraction = 0.01;
protocol.minimumSenderNoveltyFraction = 0.005;
protocol.maximumProtectedHarmRatio = 1.0;
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v84', 'braided_handover_opportunity', 'cache');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v84', 'braided_handover_opportunity');
protocol.referenceStateGenerationAuthorized = true;
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V84 scans one frozen development seed on scale-controlled M24 and ', ...
    'X36 braided-handover scenes. It may read only current local LMB ', ...
    'posteriors, current association support, current physical links, ', ...
    'link reliability, and registered past topology. The scan measures ', ...
    'whether a physical cross-formation sender contributes label support ', ...
    'that the receiver and its incumbent sender currently lack, while ', ...
    'protecting receiver-supported labels from geometric-average harm. ', ...
    'Truth, future measurements, route execution, tracking scoring, and ', ...
    'model training remain closed.'];
end
