function protocol = ...
    getBackboneResidualTailGuardAdaptiveTrustProtocol()
% GETBACKBONERESIDUALTAILGUARDADAPTIVETRUSTPROTOCOL Frozen M24 robust gate.

strict = ...
    getBackboneResidualTailSafeAdaptiveTrustProtocol();
adaptive = ...
    getBackboneResidualAdaptiveTrustProtocol();
protocol = struct();
protocol.id = ...
    'backbone-residual-tail-guard-adaptive-trust-m24-h3-v1';
protocol.predecessorProtocolId = strict.id;
protocol.presetName = adaptive.presetName;
protocol.seed = adaptive.seed;
protocol.continuationStartTime = ...
    adaptive.continuationStartTime;
protocol.continuationEndTime = ...
    adaptive.continuationEndTime;
protocol.horizonTimes = adaptive.horizonTimes;
protocol.dominantWeight = adaptive.dominantWeight;
protocol.localResidualWeight = ...
    adaptive.localResidualWeight;
protocol.crossResidualWeightGrid = ...
    adaptive.crossResidualWeightGrid;
protocol.minimumSelfWeight = ...
    adaptive.minimumSelfWeight;
protocol.armName = [ ...
    'oracle-backbone-residual-spliced-cycle-', ...
    'tail-guard-adaptive-current-a70'];
protocol.baselineSourceRelativePath = ...
    adaptive.baselineSourceRelativePath;
protocol.baselineSourceSha256 = ...
    adaptive.baselineSourceSha256;
protocol.baselineModes = adaptive.baselineModes;
protocol.maximumDirectedMessageMultiplier = ...
    adaptive.maximumDirectedMessageMultiplier;
protocol.expectedCrossFormationEdgeCount = ...
    adaptive.expectedCrossFormationEdgeCount;
protocol.minimumMeanTrackingGainFraction = ...
    adaptive.minimumMeanTrackingGainFraction;
protocol.maximumWorstNodeRegressionFraction = ...
    adaptive.maximumWorstNodeRegressionFraction;
protocol.maximumAttemptedByteDeviationFraction = ...
    adaptive.maximumAttemptedByteDeviationFraction;
protocol.requireAllSelectedRollingWindowsStrong = true;
protocol.requireZeroRepair = true;
protocol.requireZeroPayloadEmergency = true;
protocol.requireZeroTopologyInfeasibility = true;
protocol.referenceMode = ...
    'matched-static-residual';
protocol.referenceArm = ...
    adaptive.tailSafeReferenceArm;
protocol.referenceResidualWeight = ...
    adaptive.tailSafeReferenceResidualWeight;
protocol.requireNonnegativeReferenceAdvantage = true;
protocol.referenceGuardMode = ...
    'top-risk-receivers';
protocol.protectedReceiverCount = 1;
protocol.protectedReceiverObjective = ...
    'maximum-matched-static-expected-task-risk';
protocol.protectionRiskMetric = ...
    'objective-reference';
protocol.referenceAdvantageTolerance = 1e-12;
protocol.failClosedOnNoCompleteSafeCycle = true;
protocol.privilegedHeadroomUsesTruth = true;
protocol.deployable = false;
protocol.evidencePending = false;
protocol.headroomGatePassed = false;
protocol.surrogateTailGuardRejected = true;
protocol.smokeFeasibilityPassed = true;
protocol.smokeFallbackUsed = false;
protocol.smokeEospa = ...
    17.6608942413502;
protocol.smokeWorstSensorEospa = ...
    42.6103813158315;
protocol.smokeWorstSensorIndex = 16;
protocol.smokeCrossFormationEdgeCount = 4;
protocol.smokeSourceSha256 = ...
    '2ba0050c461d8a44fc369be25b7acb3ee2afb7ceaaa4dec418e7ede5128bb920';
protocol.returnDataGenerationAuthorized = false;
protocol.criticTrainingAuthorized = false;
protocol.x36PolicyRunAuthorized = false;
protocol.heldoutClaimAllowed = false;
end
