function protocol = getCacheFreeDonorOfferCoverageV233Protocol()
% GETCACHEFREEDONOROFFERCOVERAGEV233PROTOCOL Bounded label coverage.
%
% If a donor source has no causal beneficiary cache, no score can identify
% arbitrary receiver-relative surprise.  V233 therefore uses communication
% credit to enumerate a bounded active-label set over two deterministic
% phases.  The beneficiary, not the proposal layer, performs value ranking.

base = getBudgetAdaptiveSourceOfferProtocolV231();
protocol = struct();
protocol.id = 'cache-free-donor-offer-coverage-v233-v1';
protocol.contractVersion = ...
    'cache-free-donor-offer-coverage-v233-protocol-v1';
protocol.baseProtocolId = base.id;
protocol.status = 'same-state-coverage-screen';

coverage = struct();
coverage.sourceScope = ...
    'common-physical-sources-inside-withheld-donor-formation';
coverage.minimumActiveExistence = 0.01;
coverage.offersPerSourcePerPhase = 12;
coverage.maximumPhases = 2;
coverage.maximumCoveredLabelsPerSource = ...
    coverage.offersPerSourcePerPhase * coverage.maximumPhases;
coverage.phaseAssignment = ...
    'lexicographic-label-order-then-balanced-round-robin';
coverage.numericLabelIdentifiersUsedOnlyForCoverageSchedule = true;
coverage.numericLabelIdentifiersUsedAsValueFeatures = false;
coverage.solicitationSentOnce = true;
coverage.payloadRequestAfterCoverageComplete = true;
coverage.earlyStoppingBeforeCoverageCompleteAllowed = false;
coverage.completePayloadRequestsPerInvitation = 1;
protocol.coverage = coverage;

bytes = struct();
bytes.solicitationHeaderBytes = ...
    base.control.solicitationHeaderBytes;
bytes.responseHeaderBytesPerPhase = ...
    base.control.responseHeaderBytes;
bytes.offerRecordBytes = base.control.offerRecordBytes;
bytes.communicationCreditReserveFraction = ...
    base.control.communicationCreditReserveFraction;
bytes.payloadReserveFractionOfSpendableCredit = 0.25;
bytes.formula = ...
    'S*h_s+H*S*(h_r+M*b_o)+B_payload';
protocol.bytes = bytes;

protocol.coverageGuarantee = [ ...
    'if every retained source has at most H*M active labels, every label ', ...
    'is offered exactly once within H phases'];
protocol.onlineCoordinatorImplemented = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V233 is a cache-free proposal-coverage design. Its guarantee concerns ', ...
    'only label inclusion and exact attempted bytes for the retained donor ', ...
    'sources. It does not show that the beneficiary selects the right ', ...
    'offer, that the safe payload is delivered, or that tracking improves.'];

assertProtocol(protocol, base);
end

function assertProtocol(protocol, base)
c = protocol.coverage;
b = protocol.bytes;
if ~strcmp(protocol.status, 'same-state-coverage-screen') || ...
        c.offersPerSourcePerPhase ~= 12 || ...
        c.maximumPhases ~= 2 || ...
        c.maximumCoveredLabelsPerSource ~= 24 || ...
        ~c.numericLabelIdentifiersUsedOnlyForCoverageSchedule || ...
    c.numericLabelIdentifiersUsedAsValueFeatures || ...
        ~c.solicitationSentOnce || ...
        ~c.payloadRequestAfterCoverageComplete || ...
        c.earlyStoppingBeforeCoverageCompleteAllowed || ...
        c.completePayloadRequestsPerInvitation ~= 1 || ...
        b.solicitationHeaderBytes ~= ...
            base.control.solicitationHeaderBytes || ...
        b.responseHeaderBytesPerPhase ~= ...
            base.control.responseHeaderBytes || ...
        b.offerRecordBytes ~= base.control.offerRecordBytes || ...
        abs(b.payloadReserveFractionOfSpendableCredit - 0.25) > 1e-12 || ...
        protocol.onlineCoordinatorImplemented || ...
        protocol.validationClaimAllowed
    error('CacheFreeDonorOfferV233:ProtocolDrift', ...
        'The V233 donor-offer coverage contract drifted.');
end
end
