function protocol = getCenteredPerturbationRecoveryV77Protocol()
% GETCENTEREDPERTURBATIONRECOVERYV77PROTOCOL Frozen modal recovery check.

v76 = getReferenceRecoveryReplayV76Protocol();
protocol = v76;
protocol = rmfield(protocol, { ...
    'requireMonotoneMeanArmGapContraction', ...
    'requireMonotoneTailArmGapContraction'});
protocol.id = 'centered-perturbation-recovery-v77-v1';
protocol.contractVersion = ...
    'centered-perturbation-recovery-v77-protocol-v1';
protocol.baseProtocolId = v76.id;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v77', 'centered_perturbation_recovery');
protocol.covarianceRegularization = 1e-9;
protocol.commonModeConstrained = false;
protocol.requireMonotoneCenteredEnergyContraction = true;
protocol.evidenceBoundary = [ ...
    'V77 repeats the frozen V76 source-only virtual KLA replay but ', ...
    'replaces distance-to-reference recovery with a label-wise modal ', ...
    'decomposition. Candidate-minus-reference existence and position ', ...
    'perturbations are split across network nodes into a common mode ', ...
    'and a centered disagreement mode. The common mode is unconstrained; ', ...
    'only total centered energy must be non-increasing. Fusion uses ', ...
    'the registered directed weights, formal mixture-aware heavy ', ...
    'receiver, and deterministic current-link reliability weighting. ', ...
    'No packet draw, prediction, target motion, new measurement, truth, ', ...
    'future link page, route execution, tracking outcome, or model ', ...
    'training is used.'];
end
