function protocol = getCounterfactualRegretGateV133Protocol()
% GETCOUNTERFACTUALREGRETGATEV133PROTOCOL Causal multi-step gate contract.
%
% V133 predicts whether withholding one receiver formation's incoming
% cross-formation posterior for the current page will create harmful
% downstream regret over one formation-graph propagation horizon.  The
% online gate may read only the current observable posterior/sensing/link
% state and causal histories.  Truth and future outcomes are teacher-only.

policy = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
protocol = struct();
protocol.id = 'counterfactual-action-regret-gate-v133-v1';
protocol.contractVersion = ...
    'counterfactual-action-regret-gate-v133-protocol-v1';
protocol.methodName = ...
    'pre-send-conservative-multistep-action-regret-gate';
protocol.sourceMechanismUpperBoundId = ...
    'shadow-state-rollback-v126-v1';
protocol.sourceCurrentOnlyProxyId = ...
    'task-risk-input-protection-v92-v1';
protocol.sourceOnlineSelectorId = ...
    'online-positive-net-addressable-payload-v99-v1';

protocol.scaleCases = [ ...
    scaleCase('M24', 'm24-formation-fov', 24, 4, 4), ...
    scaleCase('X36', 'x36-formation-fov', 36, 6, 6)];
protocol.anchorQuantilesWithinFocusWindow = [0.25, 0.50, 0.75];
protocol.anchorSelectionRule = ...
    'round-focus-window-start-plus-quantile-times-span';
protocol.absoluteTimeFeatureAllowed = false;

% Scene x seed is the indivisible statistical group.  No window from one
% trajectory may cross a split boundary.  These seeds were registered
% before any V133 tracking outcome was opened.
protocol.developmentSeeds = [1601, 1607, 1613, 1619];
protocol.calibrationSeeds = [1621, 1627, 1637, 1699];
protocol.validationSeeds = [ ...
    1709, 1721, 1723, 1777, 1783, 1789, 1801, 1811];
protocol.splitGroupingKey = 'preset-name-and-complete-seed-trajectory';
protocol.randomWindowSplitAllowed = false;
protocol.seedValueFeatureAllowed = false;

protocol.referenceCarrierModes = { ...
    'fixed-clockwise', 'fixed-counter-clockwise'};
protocol.referencePayloadMode = 'full-posterior';
protocol.referenceCarrierSelectionRule = [ ...
    'choose the lower paired mean E-OSPA carrier on complete development ', ...
    'trajectories, then freeze it before calibration'];
protocol.perStateOracleCarrierSelectionAllowed = false;
protocol.strongestStaticBaselineReported = true;

protocol.actionContract = struct( ...
    'actionUnit', 'one-receiver-formation-current-page', ...
    'payloadMode', 'abstention-only', ...
    'wireRepresentation', 'control-synopsis-only', ...
    'fusionEffect', ...
        'withhold-incoming-cross-residual-posterior', ...
    'interventionSteps', 1, ...
    'continuationMode', 'frozen-static-full-posterior', ...
    'topologyChanged', false, ...
    'attemptedControlSynopsisCharged', true, ...
    'missingNeighborWeightModes', {{'renormalize', 'self'}}, ...
    'primaryMissingNeighborWeightMode', 'renormalize', ...
    'oneRoundCounterfactualMustMatchRuntimeAbstention', true);
protocol.propagationHorizonRule = ...
    'one-action-page-plus-directed-formation-cycle-diameter';

protocol.routeWeights = struct( ...
    'dominantWeight', policy.dominantWeight, ...
    'residualWeight', policy.residualWeight);
protocol.maximumIncomingCountForOutcomeEnumeration = ...
    policy.maximumIncomingCountForOutcomeEnumeration;
protocol.riskOptions = struct( ...
    'existenceWeight', 0.50, ...
    'localizationWeight', 0.50, ...
    'receiverTailFraction', 0.25, ...
    'receiverTailWeight', 0.50);
protocol.retentionOptions = struct( ...
    'referenceSupportThreshold', policy.referenceSupportThreshold, ...
    'decisionExistenceThreshold', policy.decisionExistenceThreshold, ...
    'receiverTailFraction', policy.retentionReceiverTailFraction, ...
    'receiverTailWeight', policy.retentionReceiverTailWeight);

protocol.teacherLabelContract = struct( ...
    'pairedStateRequired', true, ...
    'pairedMeasurementsRequired', true, ...
    'pairedDeliveryUniformsRequired', true, ...
    'pairedFilterRngRequired', true, ...
    'components', {{ ...
        'horizon-mean-position-eospa-regret', ...
        'horizon-mature-position-eospa-regret', ...
        'worst-receiver-regret', ...
        'worst-formation-regret', ...
        'downstream-peer-regret', ...
        'terminal-posterior-disagreement-regret'}}, ...
    'harmfulRule', ...
        'harmful-if-any-local-or-network-regret-is-positive', ...
    'truthAllowedOfflineOnly', true, ...
    'futureOutcomeAllowedOfflineOnly', true, ...
    'teacherLabelUsedAsOnlineFeature', false);

protocol.observableFeatureFamilies = { ...
    'exact-current-page-payload-counterfactual-risk', ...
    'mixture-aware-directed-label-state', ...
    'formation-observation-and-update-trend', ...
    'cross-edge-current-and-past-delivery-opportunity', ...
    'protection-age-release-and-duty-cycle-history', ...
    'directed-temporal-propagation-reach'};
protocol.forbiddenOnlineInputs = { ...
    'target-truth', 'tracking-eospa', 'future-measurements', ...
    'future-link-probabilities', 'future-delivery-uniforms', ...
    'current-realized-delivery', 'post-action-fused-posterior', ...
    'numeric-seed', 'absolute-time', 'fixed-formation-id'};
protocol.centralizedCurrentPosteriorAssumed = true;
protocol.controlMetadataTrafficMustBeAccounted = true;
protocol.centralizedCoordinatorClaimAllowed = true;
protocol.fullyDistributedDeploymentClaimAllowed = false;

protocol.initialModelFamily = ...
    'monotone-logistic-or-shallow-tree-with-calibrated-harm-probability';
protocol.gnnAuthorized = false;
protocol.gnnAuthorizationRule = [ ...
    'authorize only if frozen interpretable features leave repeatable ', ...
    'cross-scale interaction residuals'];
protocol.uncertainAction = 'static-full-fallback';

protocol.teacherGate = struct( ...
    'minimumHarmfulRecall', 0.90, ...
    'maximumFalseSafeRate', 0.05, ...
    'minimumDynamicActionCoverage', 0.10, ...
    'minimumRetainedOracleGainFraction', 0.50);
protocol.trackingGate = struct( ...
    'minimumMeanGainPercent', 5.0, ...
    'minimumMatureGainPercent', 5.0, ...
    'requireEverySeedPositive', true, ...
    'minimumWorstFormationGainPercent', 0.0, ...
    'minimumWorstSensorGainPercent', 0.0, ...
    'minimumDownstreamPeerGainPercent', 0.0, ...
    'minimumAttemptedByteSavingPercent', 0.0, ...
    'minimumActionCoverage', 0.10, ...
    'maximumRuntimeRatio', 1.20, ...
    'maximumMemoryRatio', 1.25, ...
    'minimumUnseenSeedsPerScale', 3);

protocol.reportingPolicy = struct( ...
    'failedCandidatesRepositoryOnly', true, ...
    'mainDocumentRequiresTrackingGate', true, ...
    'methodJudgmentRequiresRepeatedMechanismEvidence', true, ...
    'versionByVersionFailureNarrativeAllowed', false);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v133', 'counterfactual_regret_gate');
protocol.datasetRoot = fullfile(protocol.outputRoot, 'dataset');
protocol.modelRoot = fullfile(protocol.outputRoot, 'model');
protocol.validationRoot = fullfile(protocol.outputRoot, 'validation');
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V133 first freezes the causal state, action, paired teacher and ', ...
    'trajectory-level split contracts.  Its current-page counterfactual ', ...
    'is an exact model of runtime payload abstention, but it remains only ', ...
    'an observable feature rather than an E-OSPA guarantee.  No tracking, ', ...
    'learning, generalization or deployment claim is authorized until ', ...
    'the registered data, calibration and unseen-seed gates pass.'];
end

function value = scaleCase( ...
        scaleName, presetName, nodeCount, formationCount, horizonSteps)
value = struct( ...
    'scaleName', scaleName, ...
    'presetName', presetName, ...
    'expectedNodeCount', nodeCount, ...
    'expectedFormationCount', formationCount, ...
    'formationCycleDiameter', formationCount - 1, ...
    'horizonSteps', horizonSteps);
end
