function protocol = getCausalGatewayEmbeddingV250Protocol()
% GETCAUSALGATEWAYEMBEDDINGV250PROTOCOL Fixed-budget gateway action.

source = getCausalMinimumFormationBackboneV242Protocol();
protocol = struct();
protocol.id = 'causal-gateway-embedding-v250-v1';
protocol.contractVersion = ...
    'causal-gateway-embedding-v250-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v250-causal-sensor-gateway-embedding';
protocol.policyName = 'causal-gateway-embedding-v250-policy';
protocol.allowedPresets = { ...
    'm24-formation-fov-temporal-coupled-formation-braid'};
protocol.allowedSeeds = 1301;
protocol.anchorTimes = [70, 84, 151];
protocol.horizonSteps = 3;
protocol.maximumCandidateCount = 32;
protocol.minimumCandidateCount = 8;
protocol.singleArcAlternativesPerSlot = 3;
protocol.localAssignmentsPerFormation = 3;
protocol.globalRankProfileCount = 2;
protocol.minimumReceiverCoveragePerFormation = 2;
protocol.minimumJointPositiveAnchorCount = 2;
protocol.maximumFormationRegressionPercent = 2;
protocol.minimumAggregateCoreGainPercent = 0;
protocol.minimumAggregateByteSavingPercent = 0;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v250', ...
    'causal_gateway_embedding');
protocol.cacheRoot = fullfile(protocol.outputRoot, ...
    'reference_cache');
protocol.oracleOutputRoot = fullfile(protocol.outputRoot, ...
    'm24_seed1301_h3_oracle');
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V250 candidate-bank preflight uses only the current physical graph, ', ...
    'current link reliability, current positions, immutable physical ', ...
    'identities and the causal V242 incumbent. It changes only the ', ...
    'sensor-level embedding of cross-formation messages while preserving ', ...
    'the V242 formation tree, local cycles, KLA weight scale and exact ', ...
    'N+2(F-1) message count. No truth, future page, measurement, tracking ', ...
    'outcome or posterior proxy is used. Structural diversity is not a ', ...
    'tracking-gain or generalization claim.'];

if protocol.minimumCandidateCount < 2 || ...
        protocol.maximumCandidateCount < ...
            protocol.minimumCandidateCount || ...
        protocol.singleArcAlternativesPerSlot < 1 || ...
        protocol.localAssignmentsPerFormation < 2 || ...
        protocol.minimumJointPositiveAnchorCount < 1 || ...
        protocol.minimumJointPositiveAnchorCount > ...
            numel(protocol.anchorTimes) || ...
        protocol.maximumFormationRegressionPercent < 0
    error('CausalGatewayEmbeddingV250:InvalidProtocol', ...
        'The V250 bounded-bank protocol is inconsistent.');
end
end
