function protocol = getDirectGraphCreditRepairControllerV216Protocol()
% GETDIRECTGRAPHCREDITREPAIRCONTROLLERV216PROTOCOL Causal two-stage action.
%
% The pre-communication head withholds one receiver formation for one page.
% After ordinary fusion, the deterministic repair head may spend only the
% resulting causal byte credit on one supported complete-label KLA update.
% The repair label and source are chosen from current fused/local posteriors;
% truth, future outcomes, and fixed semantic identifiers are unavailable.

base = getDirectGraphPayloadRepairControllerV214Protocol();
repair = getBudgetRecycledFormationRepairV188Protocol();
protocol = struct();
protocol.id = 'direct-graph-credit-repair-controller-v216-v1';
protocol.contractVersion = ...
    'direct-graph-credit-repair-controller-v216-protocol-v1';
protocol.baseProtocolId = base.id;
protocol.repairProtocolId = repair.id;
protocol.horizonSteps = base.horizonSteps;
protocol.filterSeedOffset = base.filterSeedOffset;
protocol.receiverMode = base.receiverMode;
protocol.actionMode = 'withholding-plus-causal-label-kla';
protocol.repairUpdateMode = 'causal-label-kla';
protocol.repairSourceWeight = 0.5;
protocol.maximumWithholdingFormationsPerPage = 1;
protocol.maximumRepairFormationsPerPage = 1;
protocol.repairDecisionPhase = 'post-ordinary-fusion-current-page';
protocol.repairFormationScope = ...
    'same-receiver-formation-as-withholding-action';
protocol.synopsisScope = ...
    ['receiver-local-and-fused-plus-current-common-source-local-', ...
     'synopses'];
protocol.actualDeliverySampled = true;
protocol.communicationCreditReserveFraction = ...
    repair.communicationCreditReserveFraction;
protocol.communicationCreditMayCarryAcrossPages = ...
    repair.creditMayCarryAcrossPages;
protocol.zeroSupportKlaAllowed = false;
protocol.retainedLabelsPreserveCompleteMixture = ...
    base.actions.retainedLabelsPreserveCompleteMixture;
protocol.posteriorCounterfactualEnumerationUsed = false;
protocol.truthUsedAtRuntime = false;
protocol.futureInformationUsedAtRuntime = false;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v216');
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V216 is a development two-stage controller. One causal graph action ', ...
    'may withhold a receiver formation for one page; after ordinary ', ...
    'fusion, a truth-free supported-label selector may spend only exact ', ...
    'remaining communication credit on one complete-mixture label KLA. ', ...
    'Delivery is sampled, zero-support KLA is forbidden, and no posterior ', ...
    'counterfactual is evaluated online. H=3 training screens are action ', ...
    'value evidence, not held-out or cross-scene claims.'];

if protocol.horizonSteps ~= 3 || ...
        protocol.maximumWithholdingFormationsPerPage ~= 1 || ...
        protocol.maximumRepairFormationsPerPage ~= 1 || ...
        protocol.communicationCreditReserveFraction <= 0 || ...
        ~protocol.communicationCreditMayCarryAcrossPages || ...
        protocol.zeroSupportKlaAllowed || ...
        ~protocol.retainedLabelsPreserveCompleteMixture || ...
        protocol.posteriorCounterfactualEnumerationUsed || ...
        protocol.truthUsedAtRuntime || ...
        protocol.futureInformationUsedAtRuntime
    error('DirectGraphCreditRepairV216:InvalidProtocol', ...
        'The V216 causal credit-repair contract is inconsistent.');
end
end
