function protocol = getDecisionAwareGatewayV257Protocol()
% GETDECISIONAWAREGATEWAYV257PROTOCOL Separate loss and information failure.

source = getPooledExpectedGatewayV256Protocol();
protocol = struct();
protocol.id = 'decision-aware-gateway-v257-v1';
protocol.contractVersion = 'decision-aware-gateway-v257-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.trainingSeeds = source.trainingSeeds;
protocol.anchorTimes = source.anchorTimes;
protocol.featureModeNames = { ...
    'compact-v256', 'rich-pairwise-information-upper-bound'};
protocol.expectedFeatureCounts = [32, 44];
protocol.modelFamilyNames = { ...
    'multi-output-ridge', 'joint-safe-ridge'};
protocol.ridgeLambdaGrid = source.ridgeLambdaGrid;
protocol.modelSelectionMode = 'leave-one-training-seed-out';
protocol.topActionReference = 'within-window-uniform-safe-prevalence';
protocol.safetyThreshold = 0.5;
protocol.minimumTopActionSafeLift = 0.05;
protocol.minimumPositiveLiftSeedCount = 5;
protocol.minimumGatedSafePrecision = 0.50;
protocol.minimumGatedSelectionCount = numel(protocol.trainingSeeds);
protocol.outcomeNames = source.outcomeNames;
protocol.maximumFormationRegressionPercent = ...
    source.maximumFormationRegressionPercent;
protocol.receiverEospaMinimumPercent = ...
    source.receiverEospaMinimumLowerBoundPercent;
protocol.receiverRmseActivationPercent = ...
    source.receiverRmseActivationLowerBoundPercent;
protocol.compactControlCosted = true;
protocol.richPairwiseControlCosted = false;
protocol.calibrationAuthorized = false;
protocol.holdoutAuthorized = false;
protocol.gnnAuthorized = false;
protocol.x36Authorized = false;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v257', ...
    'decision_aware_gateway_diagnostic');
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V257 uses only the seven V256 training seeds and the same one-arc ', ...
    'action outcomes. It compares absolute multi-output regression with ', ...
    'joint-safe action ranking under leave-one-seed-out evaluation, and ', ...
    'crosses that loss comparison with compact versus exact current-', ...
    'posterior pairwise features. The rich feature mode is an uncosted ', ...
    'information upper bound, not a deployable controller. It may only ', ...
    'authorize design of a fixed-byte compatibility sketch. Calibration ', ...
    'seeds, development holdouts, complete episodes, GNNs and X36 remain ', ...
    'sealed.'];

valid = numel(unique(protocol.trainingSeeds)) == ...
        numel(protocol.trainingSeeds) && ...
    isequal(protocol.trainingSeeds, source.trainingSeeds) && ...
    isequal(protocol.ridgeLambdaGrid, source.ridgeLambdaGrid) && ...
    isequal(protocol.expectedFeatureCounts, [32, 44]) && ...
    protocol.minimumTopActionSafeLift > 0 && ...
    protocol.minimumPositiveLiftSeedCount >= 1 && ...
    protocol.minimumPositiveLiftSeedCount <= ...
        numel(protocol.trainingSeeds) && ...
    protocol.minimumGatedSafePrecision > 0 && ...
    protocol.minimumGatedSafePrecision <= 1 && ...
    protocol.minimumGatedSelectionCount >= ...
        numel(protocol.trainingSeeds) && ...
    protocol.compactControlCosted && ...
    ~protocol.richPairwiseControlCosted && ...
    ~protocol.calibrationAuthorized && ~protocol.holdoutAuthorized && ...
    ~protocol.gnnAuthorized && ~protocol.x36Authorized;
if ~valid
    error('DecisionAwareGatewayV257:InvalidProtocol', ...
        'The V257 diagnostic boundary or data split drifted.');
end
end
