function protocol = getExplicitLabelAbstentionV109Protocol()
% GETEXPLICITLABELABSTENTIONV109PROTOCOL Neutral missing-label attribution.

base = getProtectionOnlyH8V105Protocol();
protocol = base;
protocol.id = 'explicit-label-abstention-v109-v1';
protocol.contractVersion = 'explicit-label-abstention-v109-protocol-v1';
protocol.outcomePolicyName = 'explicit-label-abstention-v109-v1';
protocol.executionProfile = 'v109-explicit-label-abstention';
protocol.bankVariant = 'explicit-label-abstention-v109';
protocol.candidateActionName = 'v109-explicit-label-abstention-h8';
protocol.resultContractVersion = ...
    'explicit-label-abstention-v109-x36-t72-result-v1';
protocol.resultFileStem = ...
    'EXPLICIT_LABEL_ABSTENTION_V109_X36_T72_RESULT';
protocol.reportTitle = ...
    'V109 explicit label abstention: X36 t72 H=8';
protocol.armDisplayName = 'V109 explicit abstention';
protocol.runLabel = 'V109 X36-t72 H=8';
protocol.releaseFormationIdsByTime = repmat( ...
    {zeros(1, 0)}, 1, protocol.horizonSteps);
protocol.minimumFormationGainPercent = 0;
protocol.minimumTargetPeerTerminalGainPercent = 0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v109', 'explicit_label_abstention');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.evidenceBoundary = [ ...
    'V109 is a frozen H=8 fusion-semantics attribution. It keeps the ', ...
    'matched static fixed-counter-clockwise route, V105 formation schedule, ', ...
    'control synopsis bytes, link attempts, delivery uniforms and filter ', ...
    'RNG. The only change is that a delivered selective empty payload ', ...
    'abstains from fusion instead of participating as a fov-aware censored ', ...
    'missing-label source. V109 uses no new truth or future outcome to ', ...
    'choose actions. It tests whether V105''s gain and local harm come from ', ...
    'source abstention or bulk low-existence evidence. It is development ', ...
    'evidence only and cannot support validation or generalization claims.'];
end
