function protocol = getEtaProjectedLabelTrustV266Protocol()
% GETETAPROJECTEDLABELTRUSTV266PROTOCOL Eta-limited label trust.

source = getLabelSelectiveRiskShortcutV265Protocol();
protocol = source;
protocol.id = 'eta-projected-label-trust-v266-v1';
protocol.contractVersion = ...
    'eta-projected-label-trust-v266-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v266-eta-projected-label-trust';
protocol.policyName = 'eta-projected-label-trust-v266-policy';
protocol.sourceWeightGrid = [0.05, 0.025, 0.0125, 0.00625];
protocol.sourceWeight = max(protocol.sourceWeightGrid);
protocol.resultContractVersion = ...
    'eta-projected-label-trust-v266-result-v1';
protocol.resultFileName = ...
    'ETA_PROJECTED_LABEL_TRUST_V266_CONTINUATION.mat';
protocol.reportFileName = ...
    'ETA_PROJECTED_LABEL_TRUST_V266_CONTINUATION.md';
protocol.reportTitle = 'V266 eta-projected label trust';
protocol.displayName = 'V266 eta-projected label trust';
protocol.passDecision = ...
    'run-one-full-causal-m24-arm-with-frozen-eta-projected-label-trust';
protocol.failDecision = ...
    'inspect-source-value-or-routing-latency-after-eta-trust-projection';
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v266', ...
    'eta_projected_label_trust', 'm24_seed1301_t57_73');
protocol.evidenceBoundary = [ ...
    'V266 is an outcome-opened M24 continuation mechanism screen. It ', ...
    'keeps the complete V242 full-posterior backbone and uses the same ', ...
    'causal formation, label and donor decision as V265. The complete ', ...
    'selected label is charged before receiver projection. Instead of ', ...
    'testing only the fixed 0.05 share, the receiver evaluates the frozen ', ...
    'descending source-share grid and executes the largest positive ', ...
    'label-wise KLA share that satisfies the unchanged eta/existence ', ...
    'envelope. The grid is an online trust projection, not an outcome ', ...
    'sweep. Centralized risk-synopsis cost is not yet included. No target ', ...
    'truth, future measurement or future tracking outcome is available to ', ...
    'the controller, so the result can establish mechanism headroom only, ', ...
    'not deployment cost, validation or generalization.'];

if any(~isfinite(protocol.sourceWeightGrid)) || ...
        any(protocol.sourceWeightGrid <= 0) || ...
        any(protocol.sourceWeightGrid >= 1) || ...
        any(diff(protocol.sourceWeightGrid) >= 0)
    error('EtaProjectedLabelTrustV266:InvalidProtocol', ...
        'The V266 source-share grid must be finite and descending.');
end
end
