function protocol = getFormationFovMultistyleGeometryValidationProtocol()
% GETFORMATIONFOVMULTISTYLEGEOMETRYVALIDATIONPROTOCOL Frozen v5 manifest.

payload = struct();
payload.contractVersion = ...
    'formation-fov-multistyle-geometry-validation-v1';
payload.sceneGeometryVersion = 'formation-fov-multistyle-v5';
payload.developmentSceneCommit = '86d0724';
payload.developmentEvidenceCommit = 'e7b4f4d';
payload.developmentSeeds = [41, 43, 47, 53, 59];
payload.validationSeeds = [ ...
    401, 409, 419, 431, 443, 457, 467, 479, 487, 499, ...
    509, 521, 541, 557, 569, 577, 587, 599, 607, 617];
payload.minimumValidationSeedCount = 20;
payload.requireExactSeedManifest = true;
payload.requireAllAbsolutePass = true;
payload.requireAllCrossScalePass = true;
payload.requireCleanWorktree = true;
payload.trackingOutcomeAuthorized = false;
payload.presets = [ ...
    presetEntry('m24-formation-fov-convoy', ...
        'parallel-convoy', 24, 4, 6, 16, ...
        '666def7dbed41c47b9f29e536a369ef24a52077059429e45e5a41852e4071726'), ...
    presetEntry('x36-formation-fov-convoy', ...
        'parallel-convoy', 36, 6, 6, 24, ...
        '399ed8ea978df43e15d55489791a9c0e4e11ba99724ea8a760a1f3b68a8177c8'), ...
    presetEntry('m24-formation-fov-relay', ...
        'linear-relay', 24, 4, 6, 16, ...
        '49005834d31fcc6c729d546e725e79be7ae1c5b542209ea599a944187a31f2a0'), ...
    presetEntry('x36-formation-fov-relay', ...
        'linear-relay', 36, 6, 6, 24, ...
        '7fd7130518b027caaa327b3a8bcf97b7559148d1f4f1c17a1b9ad9640ae7e9a0')];
payload.absoluteGates = [ ...
    getFormationFovMultistyleAbsoluteGeometryGate('parallel-convoy'), ...
    getFormationFovMultistyleAbsoluteGeometryGate('linear-relay')];
payload.crossScaleGates = [convoyCrossScaleGate(), relayCrossScaleGate()];
payload.evidenceBoundary = [ ...
    'Passing establishes held-out sensing-geometry and matched-scale ', ...
    'eligibility for the frozen convoy and relay scenes only. It does ', ...
    'not establish routing or tracking benefit, does not authorize ', ...
    'tracking outcomes, and does not promote crossing beyond stress-only.'];

actualSha256 = computeCanonicalValueSha256(payload);
expectedSha256 = ...
    'ec631ed036d4e4693353583bdc5fe02d8c5825f7a9d9e6ae187fcb1d235f0e7a';
if ~strcmp(actualSha256, expectedSha256)
    error('FormationFovGeometryProtocol:UnregisteredDrift', [ ...
        'The v5 validation protocol changed without registry update: ', ...
        'actual=%s expected=%s.'], actualSha256, expectedSha256);
end
protocol = payload;
protocol.canonicalSha256 = actualSha256;
end

function entry = presetEntry(name, styleName, sensorCount, ...
        formationCount, sensorsPerFormation, targetCount, sha256)
entry = struct( ...
    'presetName', name, ...
    'styleName', styleName, ...
    'sensorCount', sensorCount, ...
    'formationCount', formationCount, ...
    'sensorsPerFormation', sensorsPerFormation, ...
    'targetCount', targetCount, ...
    'sceneContractSha256', sha256);
end

function gate = convoyCrossScaleGate()
gate = commonCrossScaleGate('parallel-convoy');
gate.maxFocusBlackoutDifference = 0.010;
gate.maxWorstTargetBlackoutDifference = 0.030;
gate.maxLongestBlackoutStepDifference = 4;
gate.maxSingleFormationDifference = 0.15;
gate.maxMultiFormationDifference = 0.15;
gate.minimumFocusLoadRatio = 0.95;
gate.maximumFocusLoadRatio = 1.10;
gate.maxNormalizedHandoverDifference = 0.20;
end

function gate = relayCrossScaleGate()
gate = commonCrossScaleGate('linear-relay');
gate.maxFocusBlackoutDifference = 0.015;
gate.maxWorstTargetBlackoutDifference = 0.050;
gate.maxLongestBlackoutStepDifference = 8;
gate.maxSingleFormationDifference = 0.08;
gate.maxMultiFormationDifference = 0.08;
gate.minimumFocusLoadRatio = 0.85;
gate.maximumFocusLoadRatio = 1.15;
gate.maxNormalizedHandoverDifference = 0.15;
end

function gate = commonCrossScaleGate(styleName)
gate = struct( ...
    'styleName', styleName, ...
    'maxBlackoutDifference', 0.010, ...
    'maxFocusBlackoutDifference', NaN, ...
    'maxWorstTargetBlackoutDifference', NaN, ...
    'maxLongestBlackoutStepDifference', NaN, ...
    'maxSingleFormationDifference', NaN, ...
    'maxMultiFormationDifference', NaN, ...
    'minimumFocusLoadRatio', NaN, ...
    'maximumFocusLoadRatio', NaN, ...
    'maxNormalizedHandoverDifference', NaN, ...
    'maxOwnershipEntropyDifference', 0.03, ...
    'maxBlockageOverlapDifference', 0.05);
end
