function registry = getFormationB4V46DevelopmentArmPermitRegistry()
% GETFORMATIONB4V46DEVELOPMENTARMPERMITREGISTRY Data-only arm permits.
%
% The activation JSON is deliberately non-executable.  This loader is part
% of the frozen execution manifest and independently reconstructs every
% permit from the accepted truth-free runtime inputs and the two structural
% arms.  The JSON can select only the complete ordered 8-by-2 development
% matrix; it cannot define code, cases, arms, fingerprints, or authority.

repoRoot = fileparts(fileparts(mfilename('fullpath')));
activationAnchor = ...
    assertFormationB4V46DevelopmentPermitActivationFileAnchored();
activationPath = fullfile(repoRoot, 'contracts', ...
    'formation_b4_v46_development_arm_permits.json');
if exist(activationPath, 'file') == 0
    error('FormationB4V46DevelopmentPermit:ActivationMissing', ...
        'The development permit activation data is absent.');
end
try
    activation = builtin('jsondecode', readExactBytes(activationPath));
catch errorInfo
    error('FormationB4V46DevelopmentPermit:ActivationMalformed', ...
        'The development permit activation JSON is invalid: %s', ...
        errorInfo.message);
end
assertExactFields(activation, { ...
    'contractVersion', 'activation', 'executionSurfaceCommit', ...
    'executionSurfaceManifestSha256', 'permitCount', 'permits'});
if ~ischar(activation.contractVersion) || ...
        ~strcmp(activation.contractVersion, ...
            'formation-b4-v46-development-arm-permit-activation-v1') || ...
        ~islogical(activation.activation) || ...
        ~isscalar(activation.activation) || ...
        ~ischar(activation.executionSurfaceCommit) || ...
        ~ischar(activation.executionSurfaceManifestSha256) || ...
        ~isa(activation.permitCount, 'double') || ...
        ~isreal(activation.permitCount) || ...
        ~isscalar(activation.permitCount) || ...
        ~isfinite(activation.permitCount) || ...
        activation.permitCount ~= floor(activation.permitCount)
    error('FormationB4V46DevelopmentPermit:ActivationMalformed', ...
        'The development permit activation field types drifted.');
end

core = getFormationB4V46TrackingSourceRegistry();
structural = getFormationCausalMinimalEditV46Protocol();
accepted = getFormationB4V46DevelopmentRuntimeAcceptanceRegistry();
assertTrustedDependencies(core, structural, accepted);

permits = repmat(emptyPermit(), 1, 0);
if activation.activation
    assertActiveEnvelope(activation);
    permits = buildActivePermits( ...
        activation, core, structural, accepted);
else
    assertSealedEnvelope(activation);
end

payload = struct();
payload.id = ...
    'formation-b4-v46-development-arm-permit-registry-v1';
payload.contractVersion = ...
    'formation-b4-v46-development-arm-permit-registry-v1';
payload.phase = 'development-sentinel';
payload.activationDataContractVersion = activation.contractVersion;
payload.activationDataCanonicalSha256 = ...
    computeCanonicalValueSha256(activation);
payload.activationDataGitBlobId = activationAnchor.gitBlobId;
payload.activationDataRegularFileVerified = ...
    activationAnchor.regularFileVerified;
payload.activationDataSymlinkRejected = activationAnchor.symlinkRejected;
payload.activationDataWorktreeMatchesIndexBlob = ...
    activationAnchor.worktreeMatchesIndexBlob;
payload.coreRegistryId = core.id;
payload.coreRegistryCanonicalSha256 = core.canonicalSha256;
payload.structuralProtocolId = structural.id;
payload.structuralProtocolCanonicalSha256 = structural.canonicalSha256;
payload.runtimeAcceptanceRegistryId = accepted.id;
payload.runtimeAcceptanceRegistryCanonicalSha256 = ...
    accepted.canonicalSha256;
payload.orderedArmIds = structural.primaryArms;
payload.developmentCaseOrdinals = ...
    reshape([accepted.entries.caseOrdinal], 1, []);
payload.executionSurfaceFrozen = activation.activation;
payload.executionSurfaceCommit = activation.executionSurfaceCommit;
payload.executionSurfaceManifestSha256 = ...
    activation.executionSurfaceManifestSha256;
payload.permitCount = numel(permits);
payload.permits = permits;
payload.completeCaseArmCartesianProduct = ...
    activation.activation && numel(permits) == 16;
payload.filterExecutionAuthorized = activation.activation;
payload.stateEstimateOutputAuthorized = activation.activation;
payload.trackingOutcomeScoringAuthorized = false;
payload.groundTruthAccessAuthorized = false;
payload.futureOutcomeAccessAuthorized = false;
payload.armSelectionAuthorized = false;
payload.developmentAdvanceDecisionAuthorized = false;
payload.confirmationTrackingAuthorized = false;
payload.validationClaimAllowed = false;
payload.runnerSelfAuthorizationAllowed = false;
payload.developmentEvidenceOnly = true;
payload.evidenceBoundary = [ ...
    'This registry can authorize exactly sixteen development-sentinel ', ...
    'case-arm filter executions and their state-estimate shard output. ', ...
    'It never authorizes ground-truth access, estimate-versus-truth ', ...
    'scoring, arm selection, a development advance decision, ', ...
    'confirmation tracking, or a validation claim.'];
registry = payload;
registry.canonicalSha256 = computeCanonicalValueSha256(payload);
end

function value = readExactBytes(path)
fid = builtin('fopen', path, 'rb');
if fid < 0
    error('FormationB4V46DevelopmentPermit:ActivationMissing', ...
        'The development permit activation data could not be opened.');
end
cleanup = onCleanup(@() builtin('fclose', fid)); %#ok<NASGU>
value = char(builtin('fread', fid, inf, '*uint8')');
end

function assertTrustedDependencies(core, structural, accepted)
if ~strcmp(core.canonicalSha256, ...
        '2d86496732a97b8b597f046d384990363b5be66576d2b4031548eb72e2b75cec') || ...
        ~strcmp(structural.canonicalSha256, ...
            core.structuralProtocolCanonicalSha256) || ...
        ~strcmp(accepted.canonicalSha256, ...
            'cb1841fc1451a4973af4696277c53bfec1272f76a170fdedad796db2746e1ca6') || ...
        ~accepted.runtimeInputsFrozen || ...
        ~accepted.eligibleAsPermitDependency || ...
        accepted.truthBearingCommitmentsPresent || ...
        accepted.sourceProvenanceCommitmentsPresent || ...
        accepted.filterExecutionAuthorized || ...
        accepted.trackingOutcomeScoringAuthorized || ...
        numel(accepted.entries) ~= 8 || ...
        ~isequal(reshape([accepted.entries.caseOrdinal], 1, []), ...
            core.developmentCaseOrdinals)
    error('FormationB4V46DevelopmentPermit:DependencyDrift', ...
        'A frozen V46 development permit dependency drifted.');
end
end

function assertSealedEnvelope(activation)
if ~isempty(activation.executionSurfaceCommit) || ...
        ~isempty(activation.executionSurfaceManifestSha256) || ...
        activation.permitCount ~= 0 || ~isempty(activation.permits)
    error('FormationB4V46DevelopmentPermit:SealedDataDrift', ...
        'The sealed activation data must contain no execution authority.');
end
end

function assertActiveEnvelope(activation)
if isempty(regexp(activation.executionSurfaceCommit, ...
            '^[0-9a-f]{40}$', 'once')) || ...
        isempty(regexp(activation.executionSurfaceManifestSha256, ...
            '^[0-9a-f]{64}$', 'once')) || ...
        activation.permitCount ~= 16 || ...
        ~isstruct(activation.permits) || ...
        numel(activation.permits) ~= 16
    error('FormationB4V46DevelopmentPermit:ActivationIncomplete', ...
        'Active development permits require one frozen 8-by-2 matrix.');
end
end

function permits = buildActivePermits( ...
        activation, core, structural, accepted)
expectedCaseOrdinals = reshape([accepted.entries.caseOrdinal], 1, []);
expectedArmIds = reshape(structural.primaryArms, 1, []);
permits = repmat(emptyPermit(), 1, 16);
cursor = 0;
for caseIdx = 1:numel(expectedCaseOrdinals)
    for armIdx = 1:numel(expectedArmIds)
        cursor = cursor + 1;
        record = activation.permits(cursor);
        assertExactFields(record, {'caseOrdinal', 'armId'});
        if ~isa(record.caseOrdinal, 'double') || ...
                ~isreal(record.caseOrdinal) || ...
                ~isscalar(record.caseOrdinal) || ...
                record.caseOrdinal ~= expectedCaseOrdinals(caseIdx) || ...
                ~ischar(record.armId) || ...
                ~strcmp(record.armId, expectedArmIds{armIdx})
            error('FormationB4V46DevelopmentPermit:PermitMatrixDrift', ...
                'The active permit matrix is missing, reordered, or forged.');
        end
        permit = buildPermit( ...
            record.caseOrdinal, record.armId, activation, ...
            core, structural, accepted);
        permits(cursor) = permit;
    end
end
end

function permit = buildPermit( ...
        caseOrdinal, armId, activation, core, structural, accepted)
matchingAccepted = [accepted.entries.caseOrdinal] == caseOrdinal;
if nnz(matchingAccepted) ~= 1
    error('FormationB4V46DevelopmentPermit:UnknownCase', ...
        'A development permit case lacks one accepted runtime input.');
end
acceptedEntry = accepted.entries(find(matchingAccepted, 1));
caseContract = core.cases(caseOrdinal);
armOrdinal = find(strcmp(structural.primaryArms, armId));
if numel(armOrdinal) ~= 1 || ...
        ~strcmp(acceptedEntry.caseId, caseContract.id) || ...
        ~strcmp(acceptedEntry.coreCaseCanonicalSha256, ...
            caseContract.caseCanonicalSha256) || ...
        caseContract.seed ~= core.developmentSeed
    error('FormationB4V46DevelopmentPermit:IdentityDrift', ...
        'A development permit case or arm identity drifted.');
end
[~, triggerDetails] = buildFormationB4V46FixedTriggerConfig( ...
    armId, caseContract.numberOfSensors);

payload = struct();
payload.id = sprintf( ...
    'formation-b4-v46-development:%02d:%s', caseOrdinal, armId);
payload.contractVersion = ...
    'formation-b4-v46-development-arm-permit-v1';
payload.phase = 'development-sentinel';
payload.capability = 'development-arm-state-estimate';
payload.filterAction = 'filter-development-arm';
payload.structuralProtocolId = structural.id;
payload.structuralProtocolCanonicalSha256 = structural.canonicalSha256;
payload.coreRegistryId = core.id;
payload.coreRegistryCanonicalSha256 = core.canonicalSha256;
payload.runtimeAcceptanceRegistryId = accepted.id;
payload.runtimeAcceptanceRegistryCanonicalSha256 = ...
    accepted.canonicalSha256;
payload.caseOrdinal = caseOrdinal;
payload.caseId = caseContract.id;
payload.coreCaseCanonicalSha256 = caseContract.caseCanonicalSha256;
payload.runtimeFilterProjectionCanonicalSha256 = ...
    acceptedEntry.runtimeFilterProjectionCanonicalSha256;
payload.presetName = caseContract.presetName;
payload.seed = caseContract.seed;
payload.seedRole = caseContract.seedRole;
payload.primaryMatrix = caseContract.primaryMatrix;
payload.stressMatrix = caseContract.stressMatrix;
payload.numberOfSensors = caseContract.numberOfSensors;
payload.simulationLength = caseContract.simulationLength;
payload.focusWindow = caseContract.focusWindow;
payload.armOrdinal = armOrdinal;
payload.armId = armId;
payload.triggerConfigCanonicalSha256 = triggerDetails.canonicalSha256;
payload.executionSurfaceCommit = activation.executionSurfaceCommit;
payload.executionSurfaceManifestSha256 = ...
    activation.executionSurfaceManifestSha256;
payload.nonoverwritingShardRequired = true;
payload.stateEstimateOutputAuthorized = true;
payload.trackingOutcomeScoringAuthorized = false;
payload.groundTruthAccessAuthorized = false;
payload.futureOutcomeAccessAuthorized = false;
payload.armSelectionAuthorized = false;
payload.developmentAdvanceDecisionAuthorized = false;
payload.confirmationTrackingAuthorized = false;
payload.validationClaimAllowed = false;
payload.developmentEvidenceOnly = true;
permit = payload;
permit.permitCanonicalSha256 = computeCanonicalValueSha256(payload);
end

function value = emptyPermit()
value = struct( ...
    'id', '', 'contractVersion', '', 'phase', '', ...
    'capability', '', 'filterAction', '', ...
    'structuralProtocolId', '', ...
    'structuralProtocolCanonicalSha256', '', ...
    'coreRegistryId', '', 'coreRegistryCanonicalSha256', '', ...
    'runtimeAcceptanceRegistryId', '', ...
    'runtimeAcceptanceRegistryCanonicalSha256', '', ...
    'caseOrdinal', NaN, 'caseId', '', ...
    'coreCaseCanonicalSha256', '', ...
    'runtimeFilterProjectionCanonicalSha256', '', ...
    'presetName', '', 'seed', NaN, 'seedRole', '', ...
    'primaryMatrix', false, 'stressMatrix', false, ...
    'numberOfSensors', NaN, 'simulationLength', NaN, ...
    'focusWindow', zeros(1, 0), 'armOrdinal', NaN, ...
    'armId', '', 'triggerConfigCanonicalSha256', '', ...
    'executionSurfaceCommit', '', ...
    'executionSurfaceManifestSha256', '', ...
    'nonoverwritingShardRequired', false, ...
    'stateEstimateOutputAuthorized', false, ...
    'trackingOutcomeScoringAuthorized', false, ...
    'groundTruthAccessAuthorized', false, ...
    'futureOutcomeAccessAuthorized', false, ...
    'armSelectionAuthorized', false, ...
    'developmentAdvanceDecisionAuthorized', false, ...
    'confirmationTrackingAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', false, ...
    'permitCanonicalSha256', '');
end

function assertExactFields(value, expected)
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)), ...
            sort(reshape(expected, [], 1)))
    error('FormationB4V46DevelopmentPermit:ActivationMalformed', ...
        'A development permit data object has an unexpected field set.');
end
end
