function protocol = getFusionAwareSourceOfferProtocolV229()
% GETFUSIONAWARESOURCEOFFERPROTOCOLV229 Remote-surprise discovery contract.
%
% V229 is conditional on material teacher headroom.  It replaces the
% beneficiary-only label-key query with a bounded offer from every common
% source.  A source may compare its current posterior only with the latest
% beneficiary posterior it causally received under ordinary communication.
% Ranking is still pending; this protocol freezes the message and byte
% contract before another tracking outcome is opened.

base = getFusionAwareLabelEdgeControllerV228Protocol();
protocol = struct();
protocol.id = 'fusion-aware-source-offer-controller-v229-v1';
protocol.contractVersion = ...
    'fusion-aware-source-offer-controller-v229-protocol-v1';
protocol.baseProtocolId = base.id;
protocol.status = 'byte-feasible-ranking-pending';

offer = struct();
offer.mode = 'beneficiary-solicited-source-offer';
offer.maximumOffersPerSource = 2;
offer.solicitationHeaderBytes = 16;
offer.responseHeaderBytes = 16;
offer.offerRecordBytes = 24;
offer.labelKeyBytes = 4;
offer.responseRecordLayout = [ ...
    'uint16-birth-time, uint16-birth-location, uint16-existence, ', ...
    'uint16-evidence, float32-x, float32-y, ', ...
    'float32-position-trace, uint32-complete-label-payload-bytes'];
offer.sourceRule = [ ...
    'sources physically reachable by every receiver in the selected ', ...
    'beneficiary formation'];
offer.beneficiaryReference = [ ...
    'latest causally received ordinary beneficiary posterior; no current ', ...
    'beneficiary label inventory is requested before offers'];
offer.maximumControlExchangesPerPage = 1;
offer.maximumCompletePayloadRequestsPerPage = 1;
offer.retryAfterProjectionRejectionAllowed = false;
offer.fullMixtureAvailableBeforePayloadFetch = false;
offer.numericLabelIdentifiersUsedAsScoreFeatures = false;
offer.sourceRankingImplemented = false;
offer.sourceRankingValidated = false;
protocol.offer = offer;

protocol.projection = base.projection;
protocol.action = base.action;
protocol.headroom = base.headroom;
protocol.creditReserveFraction = ...
    base.theory.communicationCreditReserveFraction;
protocol.byteFormula = 'S*(h_s+h_r+M*b_o)';
protocol.byteFeasibilityRule = ...
    'B_offer+B_payload<=(1-rho)*C_admission';
protocol.byteFeasibilityImpliesPositiveNetSaving = true;
protocol.onlinePolicyImplemented = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V229 currently freezes only source-offer semantics and a deterministic ', ...
    'attempted-byte upper bound. It does not show that a source can rank ', ...
    'valuable labels from a stale beneficiary cache, that an offer passes ', ...
    'the exact KLA projection, or that tracking improves.'];

assertProtocol(protocol, base);
end

function assertProtocol(protocol, base)
offer = protocol.offer;
if ~strcmp(protocol.status, 'byte-feasible-ranking-pending') || ...
        offer.maximumOffersPerSource ~= 2 || ...
        offer.solicitationHeaderBytes ~= 16 || ...
        offer.responseHeaderBytes ~= 16 || ...
        offer.offerRecordBytes ~= 24 || ...
        offer.labelKeyBytes ~= 4 || ...
        offer.maximumCompletePayloadRequestsPerPage ~= 1 || ...
        offer.retryAfterProjectionRejectionAllowed || ...
        offer.fullMixtureAvailableBeforePayloadFetch || ...
        offer.numericLabelIdentifiersUsedAsScoreFeatures || ...
        offer.sourceRankingImplemented || offer.sourceRankingValidated || ...
        abs(protocol.creditReserveFraction - 0.20) > 1e-12 || ...
        ~protocol.byteFeasibilityImpliesPositiveNetSaving || ...
        ~isequal(protocol.projection, base.projection) || ...
        protocol.onlinePolicyImplemented || protocol.validationClaimAllowed
    error('FusionAwareSourceOfferV229:ProtocolDrift', ...
        'The frozen V229 source-offer contract is inconsistent.');
end
end
