function protocol = getFovAwarePersistentRiskCoverageV94Protocol()
% GETFOVAWAREPERSISTENTRISKCOVERAGEV94PROTOCOL Matched-static recheck.

protocol = struct();
protocol.id = 'fov-aware-persistent-risk-coverage-v94-v1';
protocol.contractVersion = ...
    'fov-aware-persistent-risk-coverage-v94-protocol-v1';
protocol.receiverMode = 'fov-aware-censored';
protocol.horizonSteps = 3;
protocol.interventionDurationSteps = 3;
protocol.filterSeedOffset = 100000;
protocol.positiveSupportThreshold = 0.20;
protocol.coverageTargetFraction = 0.80;
protocol.minimumNetworkRiskFraction = 0.01;
protocol.maximumUsefulLossToRescueRatio = 1.0;
protocol.requireZeroCrossSupportedDownwardCrossings = true;
protocol.minimumMeanGainPercent = 5;
protocol.minimumWorstSensorGainPercent = 0;
protocol.minimumFormationGainPercent = 0;
protocol.minimumWindowConsensusGainPercent = 0;
protocol.minimumTerminalConsensusGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.referencePolicyName = ...
    'formation-h3-fixed-ccw-reference-v1';
protocol.baselineName = ...
    'matched-static-fixed-ccw-full-payload';
protocol.cases = [ ...
    caseEntry('M24', 'm24-formation-fov', 211, 24, 4, ...
        [104, 124], [104, 124], ...
        'tracking-aligned-routing-leverage-v58-v1', ...
        'm24_radial'), ...
    caseEntry('X36', 'x36-formation-fov', 211, 36, 6, ...
        [72, 100], [72, 100, 128], ...
        'tracking-aligned-x36-schedule-headroom-v63-v1', ...
        'x36_radial')];
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v94', 'fov_aware_persistent_risk_coverage');
for caseIdx = 1:numel(protocol.cases)
    protocol.cases(caseIdx).cacheRoot = fullfile( ...
        protocol.outputRoot, 'cache', ...
        protocol.cases(caseIdx).cacheSubdirectory);
end
protocol.requiredAnchorPassCount = sum( ...
    arrayfun(@(entry) numel(entry.anchorTimes), protocol.cases));
protocol.fullEpisodeTrackingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V94 replays four already-opened radial development anchors with ', ...
    'FoV-aware censored missing-label semantics. Every candidate is ', ...
    'paired against the same fixed counter-clockwise static route, ', ...
    'posterior state, measurements, link uniforms, filter RNG and ', ...
    'communication constraints. All four anchors must pass the frozen ', ...
    '5% tracking gate before any full-episode experiment is authorized. ', ...
    'No held-out or validation claim is authorized.'];
end

function value = caseEntry( ...
        scaleName, presetName, seed, nodeCount, formationCount, ...
        anchorTimes, cacheGenerationTimes, sourceProtocolId, ...
        cacheSubdirectory)
value = struct( ...
    'scaleName', scaleName, ...
    'presetName', presetName, ...
    'seed', seed, ...
    'expectedNodeCount', nodeCount, ...
    'expectedFormationCount', formationCount, ...
    'anchorTimes', reshape(anchorTimes, 1, []), ...
    'cacheGenerationTimes', reshape(cacheGenerationTimes, 1, []), ...
    'sourceProtocolId', sourceProtocolId, ...
    'cacheSubdirectory', cacheSubdirectory, ...
    'cacheRoot', '');
end
