function protocol = getFormationReconnectPulseProbeProtocol()
% GETFORMATIONRECONNECTPULSEPROBEPROTOCOL V31 source-only probe.

protocol = struct();
protocol.id = 'formation-reconnect-pulse-v31-v1';
protocol.contractVersion = ...
    'formation-reconnect-pulse-probe-protocol-v1';
protocol.presetName = 'm24-formation-fov';
protocol.seed = 211;
protocol.anchorTime = 72;
protocol.reconnectTime = 74;
protocol.horizonSteps = 3;
protocol.expectedNodeCount = 24;
protocol.expectedFormationCount = 4;
protocol.maximumFormationCount = 8;
protocol.dominantWeight = 0.70;
protocol.referenceResidualWeight = 0.05;
protocol.pulseResidualWeights = [0.075, 0.10, 0.15];
protocol.maximumIncomingCountForOutcomeEnumeration = 4;
protocol.maximumRetentionRisk = 0.01;
protocol.minimumFormationMeanCardinalityChange = -0.05;
protocol.minimumSupportedLabelRetentionRatio = 0.80;
protocol.maximumDecisionThresholdCrossingCount = 0;
protocol.referenceSupportThreshold = 0.05;
protocol.decisionExistenceThreshold = 0.50;
protocol.retentionReceiverTailFraction = 0.25;
protocol.retentionReceiverTailWeight = 0.50;
protocol.minimumDisagreementImprovementFraction = 0.0025;
protocol.expectedSingleSafetyMask = logical([ ...
    1, 1, 0; ...
    0, 0, 0; ...
    0, 0, 0; ...
    0, 0, 0]);
protocol.expectedSingleEligibleMask = false(4, 3);
protocol.expectedReferenceFallback = true;
protocol.maximumControlRouteEvaluations = 1 + ...
    protocol.maximumFormationCount * ...
        numel(protocol.pulseResidualWeights) + ...
    protocol.maximumFormationCount;
protocol.referenceFallbackRequired = true;
protocol.messageCountParityRequired = true;
protocol.selectedRollingConnectivityRequired = true;
protocol.currentPosteriorRequired = true;
protocol.currentLinkReliabilityRequired = true;
protocol.sourceV30ScreenGenerationCommit = ...
    '985120f7945205357a1643574d38e62feaf14063';
protocol.sourceV30AuditCommit = ...
    '33c4114';
protocol.sourceCacheSha256 = ...
    ['60dfbf2615181cde046af15f42bba37c415ea0034cb7ce536', ...
     '85b79042bfaf762'];
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v14', 'event_conditioned_sentinel', 'cache');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v31', 'safe_reconnect_pulse');
protocol.openedDevelopmentEvidenceOnly = true;
protocol.trackingOutcomeRerunAuthorized = false;
protocol.additionalM24StateAuthorized = false;
protocol.gnnTrainingAuthorized = false;
protocol.x36OutcomeOpeningAuthorized = false;
protocol.x48OutcomeOpeningAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'v31 may replay only the already-opened v30 controller trajectory ', ...
    'through t=74 to recover the causal pre-fusion posterior and selected ', ...
    'topology history. The reconnect-pulse bank reads that current ', ...
    'posterior, current physical graph, current link reliability, and ', ...
    'history; it reads no target truth or later outcome. The probe may ', ...
    'measure exact one-round posterior disagreement and reference-', ...
    'relative label retention, but it may not score tracking, rerun the ', ...
    't=72 outcome, open t=60 or another M24 state, train a GNN, or open ', ...
    'X36/X48 before a clean frozen preflight explicitly authorizes it.'];
end
