function protocol = getFormationBraidRoutingComparisonV241Protocol()
% GETFORMATIONBRAIDROUTINGCOMPARISONV241PROTOCOL Matched route arms.

source = getCausalMinimalEditFormationTreeV240Protocol();
v227 = getCorrectedStaticRoutingBaselineV227Protocol();
protocol = struct();
protocol.id = 'formation-braid-routing-comparison-v241-v1';
protocol.contractVersion = ...
    'formation-braid-routing-comparison-v241-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.allowedPresets = source.allowedPresets;
protocol.allowedSeeds = 1301;
protocol.staticDropoutArmId = ...
    'v241-fixed-formation-tree-physical-dropout';
protocol.alwaysReplanArmId = 'v241-current-tree-always-replan';
protocol.causalArmId = source.armId;
protocol.staticDropoutPolicyName = ...
    'formation-braid-v241-fixed-formation-tree-physical-dropout';
protocol.alwaysReplanPolicyName = ...
    'formation-braid-v241-current-tree-always-replan';
protocol.causalPolicyName = source.policyName;
protocol.armIds = {protocol.staticDropoutArmId, ...
    protocol.alwaysReplanArmId, protocol.causalArmId};
protocol.receiverMode = v227.receiverMode;
protocol.dominantWeight = source.dominantWeight;
protocol.residualWeight = source.residualWeight;
protocol.directedInputsPerReceiver = source.directedInputsPerReceiver;
protocol.filterSeedOffset = v227.filterSeedOffset;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v241', ...
    'formation_braid_routing_comparison');
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V241 is an opened-seed development comparison on exploratory ', ...
    'formation-braid scenes. The fixed-tree arm never changes its initial ', ...
    'formation pairs, but reassigns sensor gateways from the current ', ...
    'physical graph while those pairs remain feasible. Only after a fixed ', ...
    'formation pair becomes infeasible are unavailable route inputs ', ...
    'omitted and their KLA mass returned to the receiver self weight. ', ...
    'The always-replan and causal arms retain exactly two current physical ', ...
    'inputs per receiver and the same V227 weight multiset. V241 can ', ...
    'establish a paired development effect on the executed scene and seed ', ...
    'only; it does not establish held-out generalization or a paper claim.'];
end
