function protocol = getFormationCoordinatedPosteriorRepairV185Protocol()
% GETFORMATIONCOORDINATEDPOSTERIORREPAIRV185PROTOCOL Coordinated F5 repair.

protocol = getRolloutAwareOneHopSafeLabelV179Protocol();
protocol.id = 'formation-coordinated-posterior-repair-v185-v1';
protocol.contractVersion = ...
    'formation-coordinated-posterior-repair-v185-protocol-v1';
protocol.outcomePolicyName = ...
    'formation-coordinated-posterior-repair-v185-v1';
protocol.executionProfile = 'v185-formation-coordinated-posterior-repair';
protocol.bankVariant = 'formation-coordinated-posterior-repair-v185';
protocol.candidateActionName = ...
    'v185-analytic-f3-plus-formation-coordinated-f5-repair';
protocol.learnedModelPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v181', 'second_rollout_aware_model', ...
    'compact_scalar', 'NONLINEAR_SAFE_ONE_HOP_ACTION_V168_MODEL.mat');
protocol.learnedPolicyPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v185', 'formation_coordinated_policy', ...
    'FORMATION_COORDINATED_POSTERIOR_REPAIR_POLICY_V185.mat');
protocol.learnedMaximumLabelEdits = 1;
protocol.formationCoordinatedPosteriorRepairEnabled = true;
protocol.formationCoordinatedPosteriorRepairTimes = ...
    protocol.learnedRepairTimes;
protocol.formationCoordinatedPosteriorRepairFormationIdsByTime = ...
    protocol.learnedRepairFormationIdsByTime;
protocol.formationCoordinatedPosteriorRepairModelPath = ...
    protocol.learnedModelPath;
protocol.formationCoordinatedPosteriorRepairPolicyPath = ...
    protocol.learnedPolicyPath;
protocol.formationCoordinatedPosteriorRepairCommonNeighborPrefilterEnabled = ...
    false;
protocol.formationCoordinatedPosteriorRepairMaximumAdvertisedLabelsPerSource = ...
    inf;
protocol.reuseFrozenReferenceOutcome = true;
protocol.referenceOutcomeScreenPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v179', 'rollout_aware_one_hop_label', ...
    'x36_t72_h8', 'screen', ...
    ['TRACKING_ALIGNED_X36_SCHEDULE_H8_', ...
     'X36_FORMATION_FOV_SEED211_T72_D8.mat']);
protocol.minimumMeanGainPercent = 5;
protocol.minimumMeanRmseGainPercent = 2;
protocol.minimumWorstRmseGainPercent = 0;
protocol.minimumFormationRmseGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.minimumWindowConsensusGainPercent = 0;
protocol.minimumTerminalConsensusGainPercent = 0;
protocol.resultContractVersion = ...
    'formation-coordinated-posterior-repair-v185-x36-t72-result-v1';
protocol.resultFileStem = ...
    'FORMATION_COORDINATED_POSTERIOR_REPAIR_V185_X36_T72_RESULT';
protocol.reportTitle = ...
    'V185 formation-coordinated posterior repair: X36 t72 H=8';
protocol.armDisplayName = ...
    'V185 analytic F3 + formation-coordinated F5 repair';
protocol.runLabel = 'V185 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v185', 'formation_coordinated_posterior_repair');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V185 is a paired recursive X36 seed-211 t=72 H=8 development ', ...
    'screen. It preserves the V179 route, weights, protection schedule ', ...
    'and truth-free analytic transfers outside F5. At F5 t=78/79, all ', ...
    'six receivers first complete ordinary KLA fusion. A frozen V181 ', ...
    'classifier and V184 formation rule then select at most one exact ', ...
    'label-source pair shared by the formation. Selection uses current ', ...
    'posterior features, a 0.60 all-node safety floor, four-node support ', ...
    'coverage, receiver label presence and observable Bayes risk; truth, ', ...
    'future measurements and numeric label identifiers are excluded. ', ...
    'The action replaces V179 per-node F5 requests rather than adding a ', ...
    'second edit. Synopsis, request and complete-label response bytes are ', ...
    'charged on each physical link. All policy-iteration data come from ', ...
    'opened seed 211, so this is development evidence only.'];
end
