function protocol = getF6ReferenceRowCompositionV124Protocol()
% GETF6REFERENCEROWCOMPOSITIONV124PROTOCOL Remove harmful F6 row switch.

base = getProjectedFormationRowCompositionV123Protocol();
protocol = base;
protocol.id = 'f6-reference-row-composition-v124-v1';
protocol.contractVersion = ...
    'f6-reference-row-composition-v124-protocol-v1';
protocol.outcomePolicyName = 'f6-reference-row-composition-v124-v1';
protocol.executionProfile = 'v124-f6-reference-row-composition';
protocol.bankVariant = 'f6-reference-row-composition-v124';
protocol.graphChoiceByFormationPage(6, :) = 1;
protocol.projectionFallbackFormationIdsByPage = ...
    repmat({zeros(1, 0)}, 1, protocol.horizonSteps);
protocol.pageActionNames = arrayfun( ...
    @(page) sprintf('v124-f6-reference-row-page-%d-h8', page), ...
    1:protocol.horizonSteps, 'UniformOutput', false);
protocol.candidateSequenceName = ...
    'v124-f6-reference-row-composition-h8';
protocol.resultContractVersion = ...
    'f6-reference-row-composition-v124-x36-t72-result-v1';
protocol.resultFileStem = ...
    'F6_REFERENCE_ROW_COMPOSITION_V124_X36_T72_RESULT';
protocol.reportTitle = ...
    'V124 F6-reference row composition: X36 t72 H=8';
protocol.runLabel = 'V124 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v124', 'f6_reference_row_composition');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V124 is a privileged opened-development X36 seed-211 t=72 H=8 ', ...
    'single-ablation of V123. It keeps every V123 carrier-row and ', ...
    'payload-participation choice except that F6 uses the clockwise ', ...
    'reference row on all pages, removing the opened delayed reversal ', ...
    'from the F1-to-F6 row. The resulting sequence needs no additional ', ...
    'connectivity fallback and preserves 60 messages, physicality, the ', ...
    'weight multiset and rolling B3. Measurements, delivery uniforms, ', ...
    'filter RNG and communication accounting remain paired. This is ', ...
    'an action-space upper bound, not a deployable policy, validation ', ...
    'or generalization evidence.'];
end
