function protocol = getFormationScaleAwareMixingProbeProtocol()
% GETFORMATIONSCALEAWAREMIXINGPROBEPROTOCOL Frozen v27 development probe.

protocol = struct();
protocol.id = 'formation-scale-aware-residual-mixing-v27-v1';
protocol.contractVersion = ...
    'formation-scale-aware-residual-mixing-probe-protocol-v1';
protocol.presetName = 'm24-formation-fov';
protocol.seed = 211;
protocol.primarySnapshotTime = 72;
protocol.openedSnapshotTimes = [60, 72, 104, 124];
protocol.horizonSteps = 3;
protocol.expectedNodeCount = 24;
protocol.expectedFormationCount = 4;
protocol.dominantWeight = 0.70;
protocol.residualWeight = 0.05;
protocol.orientation = 'counter-clockwise';
protocol.actionModes = { ...
    'reference-cycle', ...
    'cycle', 'cycle', ...
    'dual-gateway-cycle', 'dual-gateway-cycle', ...
    'bidirectional-cycle', 'bidirectional-cycle', ...
    'cycle-antipodal', 'cycle-antipodal', ...
    'bidirectional-antipodal', 'bidirectional-antipodal'};
protocol.actionCrossResidualWeights = [ ...
    0.05, ...
    0.10, 0.15, ...
    0.05, 0.10, ...
    0.05, 0.10, ...
    0.05, 0.10, ...
    0.05, 0.10];
protocol.maximumActionCount = 11;
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v14', 'event_conditioned_sentinel', 'cache');
protocol.cacheProtocolId = ...
    'formation-h3-event-conditioned-sentinel-v1';
protocol.cacheGenerationGitCommit = ...
    'c9c6d4dcdc7ad1cb04fb88a22823e99c7fc5bc53';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v27', 'scale_aware_residual_mixing');
protocol.primaryEvaluationMode = 'persistent-action-h3';
protocol.messageCountParityRequired = true;
protocol.physicalProjectionRequired = true;
protocol.combinedOneStepStrongConnectivityRequired = true;
protocol.rowStochasticWeightsRequired = true;
protocol.meanTrackingGainThresholdPercent = 2.0;
protocol.minimumFormationGainThresholdPercent = 0.0;
protocol.worstSensorGainThresholdPercent = 0.0;
protocol.windowConsensusGainThresholdPercent = 0.0;
protocol.maximumAttemptedPayloadIncreasePercent = 5.0;
protocol.minimumStrongOpenedStateCount = 3;
protocol.minimumOpenedStateCountForLearning = 4;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.finalModelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.x36OutcomeOpeningAuthorized = false;
protocol.x48OutcomeOpeningAuthorized = false;
protocol.finalValidationSeedsReserved = [251, 257, 263, 269, 271];
protocol.evidenceBoundary = [ ...
    'v27 first uses only the already-opened seed-211 M24 formation-FoV ', ...
    'states. It tests whether an equal-message multi-gateway residual ', ...
    'action space has tracking and consensus headroom. The fixed action ', ...
    'bank is truth-free; outcome metrics may rank actions offline. GNN ', ...
    'training requires strict headroom on at least three of four opened ', ...
    'states. X36, X48, and reserved validation seeds remain unopened.'];
end
