function protocol = getFormationH3PairRepairProbeProtocol()
% GETFORMATIONH3PAIRREPAIRPROBEPROTOCOL Opened pair-repair sequence probe.

protocol = struct();
protocol.id = 'formation-h3-pair-repair-sequence-v1';
protocol.contractVersion = ...
    'formation-h3-pair-repair-sequence-protocol-v1';
protocol.presetName = 'm24-formation-fov';
protocol.seed = 211;
protocol.currentTime = 72;
protocol.horizonSteps = 3;
protocol.referenceActionIndex = 1;
protocol.prefixActionIndices = [9, 13];
protocol.pairRepairActionIndices = 14:19;
protocol.expectedPrefixTargets = [ ...
    7.911400463530, 0, -0.001412614870, ...
    -6.068859740311, -0.844263530831, -0.882767986928];
protocol.reproductionTolerancePercent = 5e-6;
protocol.strongGainPercent = 3;
protocol.interventionBankType = 'formation-single-plus-pair';
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v14', 'event_conditioned_sentinel', 'cache');
protocol.cacheProtocolId = ...
    'formation-h3-event-conditioned-sentinel-v1';
protocol.cacheGenerationGitCommit = ...
    'c9c6d4dcdc7ad1cb04fb88a22823e99c7fc5bc53';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v19', 'pair_repair_sequence');
protocol.actionSelectionUsesTruth = true;
protocol.actionSelectionUsesFutureMeasurements = true;
protocol.runtimePolicyUsesTruth = false;
protocol.openedTrainingMechanismProbeOnly = true;
protocol.finalModelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.finalValidationSeedsReserved = [251, 257, 263, 269, 271];
protocol.evidenceBoundary = [ ...
    'The prefix [9,13] is selected after inspecting the v18 outcomes. ', ...
    'Only the six pre-existing conservative pair actions are expanded at ', ...
    'step three. This privileged, single-state probe may test whether ', ...
    'pair repair closes the known consensus debt; it cannot validate a ', ...
    'selector or support M24/X36/final-seed claims.'];
end
