function protocol = getFormationReferenceRecoveryMixingAuditProtocol()
% GETFORMATIONREFERENCERECOVERYMIXINGAUDITPROTOCOL Frozen v26 audit.

protocol = struct();
protocol.id = 'formation-reference-recovery-mixing-audit-v1';
protocol.contractVersion = ...
    'formation-reference-recovery-mixing-audit-protocol-v1';
protocol.sourceScreenPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v25', 'reference_recovery_horizon', ...
    'h5', 'screen', ...
    'FORMATION_MODE_VECTOR_H5_M24_FORMATION_FOV_SEED211_T72.mat');
protocol.expectedSourceGenerationGitCommit = ...
    '27b2c879c634a4e32705c53cf413caa7df9fb6d1';
protocol.expectedSourceContract = ...
    'formation-exhaustive-mode-vector-h5-opened-return-screen-v1';
protocol.expectedPresetName = 'm24-formation-fov';
protocol.expectedSeed = 211;
protocol.expectedCurrentTime = 72;
protocol.expectedHorizonSteps = 5;
protocol.expectedArmCount = 5;
protocol.expectedActionCount = 256;
protocol.expectedNodeCount = 24;
protocol.expectedFormationCount = 4;
protocol.referenceActionIndex = 1;
protocol.analysisSteps = [1, 3, 5, 7, 10, 20, 30];
protocol.comparisonTolerance = 1e-12;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'formation_value_v26', 'mixing_audit');
protocol.posthocDiagnosticOnly = true;
protocol.authorizesActionRedesign = true;
protocol.authorizesGnnTraining = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'This deterministic posthoc audit reads the opened v25 H=5 screen ', ...
    'after its outcomes are known. It may diagnose the current action ', ...
    'representation and motivate a preregistered redesign. It cannot ', ...
    'select a deployable policy, authorize GNN training, or support ', ...
    'M24, X36, or final-seed performance claims.'];
end
