function protocol = getFormationCoordinatorAggregationV187Protocol()
% GETFORMATIONCOORDINATORAGGREGATIONV187PROTOCOL One-copy F5 summaries.

protocol = getRolloutAwareOneHopSafeLabelV179Protocol();
protocol.id = 'formation-coordinator-aggregation-v187-v1';
protocol.contractVersion = ...
    'formation-coordinator-aggregation-v187-protocol-v1';
protocol.outcomePolicyName = ...
    'formation-coordinator-aggregation-v187-v1';
protocol.executionProfile = 'v187-formation-coordinator-aggregation';
protocol.bankVariant = 'formation-coordinator-aggregation-v187';
protocol.candidateActionName = ...
    'v187-analytic-f3-plus-coordinator-f5-repair';
% Preserve the recursively successful V179 per-receiver policy at t=78.
protocol.learnedModelPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v178', 'rollout_aware_model', 'compact_scalar', ...
    'NONLINEAR_SAFE_ONE_HOP_ACTION_V168_MODEL.mat');
protocol.learnedPolicyPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v179', 'rollout_aware_policy', ...
    'ROLLOUT_AWARE_FIRST_ACTION_POLICY_V179.mat');
protocol.learnedMaximumLabelEdits = 1;
% Only the t=79 F5 repair is aggregated by one formation coordinator.
protocol.formationCoordinatedPosteriorRepairEnabled = true;
protocol.formationCoordinatedPosteriorRepairTimes = 79;
protocol.formationCoordinatedPosteriorRepairFormationIdsByTime = {5};
protocol.formationCoordinatedPosteriorRepairModelPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v181', 'second_rollout_aware_model', ...
    'compact_scalar', 'NONLINEAR_SAFE_ONE_HOP_ACTION_V168_MODEL.mat');
protocol.formationCoordinatedPosteriorRepairPolicyPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v185', 'formation_coordinated_policy', ...
    'FORMATION_COORDINATED_POSTERIOR_REPAIR_POLICY_V185.mat');
protocol.formationCoordinatedPosteriorRepairCommonNeighborPrefilterEnabled = ...
    false;
protocol.formationCoordinatedPosteriorRepairMaximumAdvertisedLabelsPerSource = ...
    inf;
protocol.formationCoordinatedPosteriorRepairCoordinatorAggregationEnabled = ...
    true;
protocol.formationCoordinatedPosteriorRepairCoordinatorHeaderBytes = 16;
protocol.formationCoordinatedPosteriorRepairCoordinatorSynopsisBytesPerLabel = ...
    64;
protocol.formationCoordinatedPosteriorRepairCoordinatorRequestBytes = 48;
protocol.preflightResultPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v187', 'formation_coordinator_preflight', ...
    'FORMATION_COORDINATOR_AGGREGATION_V187_PREFLIGHT.mat');
protocol.reuseFrozenReferenceOutcome = true;
protocol.referenceOutcomeScreenPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v179', 'rollout_aware_one_hop_label', ...
    'x36_t72_h8', 'screen', ...
    ['TRACKING_ALIGNED_X36_SCHEDULE_H8_', ...
     'X36_FORMATION_FOV_SEED211_T72_D8.mat']);
protocol.minimumMeanGainPercent = 5;
protocol.minimumMeanRmseGainPercent = 2;
protocol.minimumWorstRmseGainPercent = 0;
protocol.minimumFormationRmseGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.minimumWindowConsensusGainPercent = 0;
protocol.minimumTerminalConsensusGainPercent = 0;
protocol.resultContractVersion = ...
    'formation-coordinator-aggregation-v187-x36-t72-result-v1';
protocol.resultFileStem = ...
    'FORMATION_COORDINATOR_AGGREGATION_V187_X36_T72_RESULT';
protocol.reportTitle = ...
    'V187 formation-coordinator aggregation: X36 t72 H=8';
protocol.armDisplayName = ...
    'V187 analytic F3 + coordinator-aggregated F5 repair';
protocol.runLabel = 'V187 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v187', 'formation_coordinator_aggregation');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V187 is a paired recursive X36 seed-211 t=72 H=8 development ', ...
    'screen. It preserves the V179 route, protection schedule and t=78 ', ...
    'per-receiver F5 selector. At t=79, one current-graph formation ', ...
    'coordinator receives each source inventory once plus one local ', ...
    'summary from each peer receiver. Every label summary is charged as ', ...
    '64 bytes and is reconstructed as an existence-weighted 2-D moment ', ...
    'object with source-computed observation opportunity and complete ', ...
    'payload size. The frozen V185 common-action rule then requests one ', ...
    'complete Bernoulli GM label for the six receivers. Selection uses ', ...
    'no truth, future measurements or numeric label values. The rule and ', ...
    'preflight were developed on opened seed 211, so this is development ', ...
    'evidence only.'];
end
