function protocol = getFormationSemanticContinuityShieldV236Protocol()
% GETFORMATIONSEMANTICCONTINUITYSHIELDV236PROTOCOL Teacher mechanism probe.
%
% V236 asks a narrow causal-mechanism question: can the V227 formation-tail
% regression be removed by preserving the incumbent receiver rows at the
% first harmful source substitution?  The target formation and switch time
% are selected from the offline V235 outcome audit, so this is a privileged
% teacher arm and never an online-policy claim.

source = getCorrectedStaticRoutingBaselineV227Protocol();
protocol = struct();
protocol.id = 'formation-semantic-continuity-shield-v236-v1';
protocol.contractVersion = ...
    'formation-semantic-continuity-shield-v236-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v236-f4-static-row-shield-from-t57-teacher';
protocol.policyName = ...
    'formation-semantic-continuity-shield-v236-outcome-teacher';
protocol.presetName = 'm24-formation-fov';
protocol.seed = 1301;
protocol.splitName = 'training';
protocol.targetFormationId = 4;
protocol.shieldStartTime = 57;
protocol.directedInputsPerReceiver = source.directedInputsPerReceiver;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.receiverMode = source.receiverMode;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v236', 'semantic_continuity_teacher');
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.scheduleSelectedFromOfflineOutcome = true;
protocol.materialGate = struct( ...
    'aggregateEospaGainOverStaticPercent', 0, ...
    'aggregateRmseGainOverStaticPercent', 0, ...
    'focusConsensusGainOverStaticPercent', 0, ...
    'attemptedByteSavingOverStaticPercent', 0, ...
    'targetFormationEospaGainOverStaticPercent', 0, ...
    'targetFormationRmseGainOverStaticPercent', 0, ...
    'minimumRetainedAggregateGainFraction', 0.50);
protocol.evidenceBoundary = [ ...
    'V236 is an outcome-derived M24 teacher mechanism probe. Runtime ', ...
    'execution reads only current geometry, current link reliability, ', ...
    'registered static routing metadata, formation membership and time. ', ...
    'However, V235 tracking outcomes selected formation F4 and t=57 ', ...
    'offline. Therefore V236 can test whether receiver-row continuity ', ...
    'repairs the observed recursive tail, but cannot be reported as a ', ...
    'deployable causal controller, held-out result or generalization ', ...
    'claim.'];

if protocol.shieldStartTime < 2 || ...
        protocol.targetFormationId < 1 || ...
        ~protocol.scheduleSelectedFromOfflineOutcome
    error('FormationSemanticContinuityV236:InvalidProtocol', ...
        'The V236 privileged teacher schedule is malformed.');
end
end
