function protocol = getFusionAwareLabelEdgeControllerV228Protocol()
% GETFUSIONAWARELABELEDGECONTROLLERV228PROTOCOL Conditional online design.
%
% V228 is authorized only if the corrected V226 mechanism pilot contains a
% compositionally safe transfer: donor-only is core-non-regressive, the
% transfer is incrementally core-positive, the joint action is core-positive,
% and attempted bytes fall.  It learns action value, not feasibility or KLA
% safety.  The carrier route is frozen from the V227 paired static-versus-
% dynamic experiment before any V228 dataset is built.

base = getBoundedDominantEdgeTransferV226Protocol();
v213 = getHierarchicalDelayedValueControllerV213Protocol();
creditProtocol = getBudgetRecycledFormationRepairV188Protocol();

protocol = base;
protocol.id = 'fusion-aware-label-edge-controller-v228-v2';
protocol.contractVersion = ...
    'fusion-aware-label-edge-controller-v228-protocol-v2';
protocol.baseProtocolId = base.id;
protocol.status = 'mechanism-authorized-carrier-pending';

authorization = struct();
authorization.requiredV226Contract = ...
    'corrected-bounded-transfer-mechanism-pilot-v226-v1';
authorization.requireCorePositiveStageBest = true;
authorization.requireDonorCoreNonnegative = true;
authorization.requireIncrementalTransferCorePositive = true;
authorization.requireJointCorePositive = true;
authorization.requirePositiveAttemptedByteSaving = true;
authorization.requireStrictV226Gate = false;
authorization.rejectIfNoStageBest = true;
authorization.authorized = true;
authorization.evidenceCommit = '7e21892';
authorization.evidencePath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'V226_CORRECTED_BOUNDED_TRANSFER_FINDING.md');
authorization.reason = [ ...
    'The online learner is not trained unless a corrected-code V226 ', ...
    'action has a non-regressive donor-only state, improves all four ', ...
    'core coordinates relative to that donor state, improves all four ', ...
    'core coordinates jointly relative to the ordinary reference, and ', ...
    'saves attempted bytes. The stricter local-tail gate remains the ', ...
    'paper-promotion gate, not the mechanism-design authorization gate.'];
protocol.authorization = authorization;

headroom = struct();
headroom.requireCompositionallySafe = true;
headroom.minimumIncrementalTrackingGainPercent = 0.50;
headroom.minimumJointTrackingGainPercent = 0.50;
headroom.minimumJointConsensusGainPercent = 0.25;
headroom.minimumAttemptedByteSavingPercent = 0.25;
headroom.trackingAggregation = 'maximum-of-eospa-and-rmse-gain';
headroom.consensusAggregation = ...
    'maximum-of-window-and-terminal-consensus-gain';
headroom.passedActionRequiredBeforeDatasetExpansion = true;
headroom.requireCausalQueryKeyDiscoverabilityBeforeDatasetExpansion = true;
headroom.materialPassAloneAuthorizesDatasetExpansion = false;
headroom.v226T50PassesMaterialGate = false;
headroom.reason = [ ...
    'Compositionally safe but numerically tiny actions remain evidence, ', ...
    'but do not authorize grouped data collection or model fitting.'];
protocol.headroom = headroom;

controlPlane = struct();
controlPlane.mode = 'query-first-bounded-label-discovery';
controlPlane.maximumQueriedLabels = 3;
controlPlane.queryHeaderBytes = 16;
controlPlane.queryBytesPerLabelKey = 4;
controlPlane.responseHeaderBytes = 16;
controlPlane.responseBytesPerLabelRecord = 20;
controlPlane.labelKeyLayout = ...
    'uint16-birth-time-plus-uint16-birth-location';
controlPlane.responseRecordLayout = [ ...
    'uint16-existence, uint16-evidence, float32-x, float32-y, ', ...
    'float32-position-trace, uint32-complete-label-payload-bytes'];
controlPlane.participantRule = [ ...
    'beneficiary receivers plus sources physically reachable by every ', ...
    'beneficiary receiver'];
controlPlane.oneQueryAndOneResponsePerRemoteParticipant = true;
controlPlane.queryCostChargedBeforePayloadSelection = true;
controlPlane.completeLabelPayloadChargedSeparately = true;
controlPlane.maximumControlExchangesPerPage = 1;
controlPlane.maximumCompletePayloadRequestsPerPage = 1;
controlPlane.retryAfterProjectionRejectionAllowed = false;
controlPlane.queryIdentifiersUsedOnlyAsRoutingKeys = true;
controlPlane.queryIdentifiersUsedAsLearnedFeatures = false;
controlPlane.queryKeySelectorImplemented = false;
controlPlane.queryKeyDiscoverabilityValidated = false;
controlPlane.headroomUsesTeacherSelectedQueryKeys = true;
controlPlane.materialHeadroomOnlyAuthorizesDiscoveryDesign = true;
controlPlane.headroomExperimentImplemented = true;
protocol.controlPlane = controlPlane;

carrier = struct();
carrier.selectionEvidence = ...
    'corrected-static-versus-dynamic-full-episode-v227';
carrier.allowedModes = { ...
    'registered-static-physical-backbone', ...
    'current-physical-dynamic-backbone'};
carrier.selectionRule = [ ...
    'Use the dynamic carrier only if its paired full-episode result is ', ...
    'non-regressive at both M24 and X36 without increasing attempted ', ...
    'bytes; otherwise use the registered static carrier.'];
carrier.frozenBeforeDatasetConstruction = true;
carrier.notClaimedAsLearned = true;
protocol.carrier = carrier;

action = struct();
action.unit = 'beneficiary-formation-source-label';
action.receiverProjection = ...
    'receiver-specific-largest-envelope-safe-transfer-fraction';
action.maximumWithholdingFormationsPerPage = 1;
action.maximumCompleteLabelTransfersPerPage = 1;
action.maximumExecutedCompositeActionsPerPage = 1;
action.completeBernoulliGaussianMixtureRequired = true;
action.sameReceiverLabelDuplicateAllowed = false;
action.selfInputReplacementAllowed = false;
action.totalLabelWeightPreserved = true;
action.fullPayloadChargedBeforeProjection = true;
action.noOpAlwaysAvailable = true;
protocol.action = action;

model = struct();
model.inputGraph = 'formation-graph-plus-source-label-action-token';
model.messagePassingRounds = 2;
model.targetNames = v213.risk.targetNames;
model.output = 'h3-no-op-relative-gain-vector';
model.runtimeInputs = { ...
    'current-posterior-summaries', ...
    'current-physical-and-carrier-graph', ...
    'recent-delivery-history', ...
    'source-label-synopsis', ...
    'exact-byte-credit-and-payload'};
model.fullMixtureFeaturesUsedForPreFetchRanking = false;
model.payloadAwareSelectionBeforeFetch = true;
model.predictsProjectionAcceptanceProbability = true;
model.truthUsedForOfflineTargets = true;
model.truthUsedAtRuntime = false;
model.futureInformationUsedAtRuntime = false;
model.candidateArchitectures = { ...
    'observable-rule', ...
    'action-only-ridge', ...
    'frozen-two-round-graph-ridge', ...
    'trainable-two-round-formation-gnn'};
model.gnnPromotionRule = [ ...
    'Promote the GNN only if grouped unseen-trajectory error and paired ', ...
    'closed-loop outcomes improve over both ridge baselines.'];
model.selectionRule = ...
    'maximum-minimum-calibrated-vector-margin-with-no-op-abstention';
protocol.model = model;

projection = struct();
projection.learnedOverrideAllowed = false;
projection.shortlistThenExactProjection = true;
projection.maximumExactCandidatesPerPage = 1;
projection.completePayloadFetchedBeforeProjection = true;
projection.retryAfterRejectionAllowed = false;
projection.preservesSelfEvidence = true;
projection.preservesTotalLabelKlaWeight = true;
projection.maximumReferenceLogOddsDrop = ...
    base.maximumReferenceLogOddsDrop;
projection.maximumReferenceLogOddsIncrease = ...
    base.maximumReferenceLogOddsIncrease;
projection.mapPositiveReferencePreserved = true;
projection.exactAttemptedByteLedgerRequired = true;
projection.physicalReachabilityRequired = true;
projection.referenceFallbackRequired = true;
protocol.projection = projection;

epsilon = max(base.maximumReferenceLogOddsDrop, ...
    base.maximumReferenceLogOddsIncrease);
theory = struct();
theory.referenceLogOddsEnvelope = epsilon;
theory.maximumOddsMultiplier = exp(epsilon);
theory.maximumAbsoluteExistenceChange = tanh(epsilon / 4);
theory.mapPositiveReferencePreserved = true;
theory.distinctLabelProjectionComposes = true;
theory.queryAttemptedByteFormula = ...
    '(P-1)*[(h_q+K*b_q)+(h_r+K*b_r)]';
theory.byteFeasibilityRule = ...
    'B_query+B_payload<=(1-rho)*C_admission';
theory.byteFeasibilityImpliesPositiveNetSaving = true;
theory.communicationCreditReserveFraction = ...
    creditProtocol.communicationCreditReserveFraction;
theory.trackingErrorBoundClaimed = false;
theory.scope = [ ...
    'The envelope is an algorithmic guarantee relative to the ordinary ', ...
    'result produced by the active mixture-aware KLA approximation. It ', ...
    'does not by itself bound E-OSPA, RMSE or spatial-density error.'];
protocol.theory = theory;

protocol.split = v213.split;
protocol.risk = v213.risk;
protocol.promotion = v213.promotion;
protocol.onlinePolicyImplemented = false;
protocol.queryFirstHeadroomImplemented = true;
protocol.validationClaimAllowed = false;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v228');
protocol.evidenceBoundary = [ ...
    'V228 is mechanism-authorized by the corrected V226 result, but its ', ...
    'carrier and online value policy remain pending. V227 freezes the ', ...
    'carrier baseline. The query-first headroom runner tests whether the ', ...
    'credit-feasible teacher-keyed action space is worth making causally ', ...
    'discoverable. A GNN is optional ', ...
    'and cannot replace exact feasibility, ', ...
    'KLA-envelope or byte-ledger projection. No performance, deployment ', ...
    'or generalization claim is allowed until the frozen controller passes ', ...
    'paired M24 and X36 evaluation and no-retune nonradial tests.'];

assertProtocol(protocol, base, v213, epsilon);
end

function assertProtocol(protocol, base, v213, epsilon)
if ~strcmp(protocol.status, ...
        'mechanism-authorized-carrier-pending') || ...
        ~protocol.authorization.authorized || ...
        protocol.authorization.requireStrictV226Gate || ...
        ~protocol.authorization.requireCorePositiveStageBest || ...
        ~protocol.authorization.requireDonorCoreNonnegative || ...
        ~protocol.authorization.requireIncrementalTransferCorePositive || ...
        ~protocol.authorization.requireJointCorePositive || ...
        ~protocol.headroom.requireCompositionallySafe || ...
        protocol.headroom.minimumIncrementalTrackingGainPercent ~= 0.50 || ...
        protocol.headroom.minimumJointTrackingGainPercent ~= 0.50 || ...
        protocol.headroom.minimumJointConsensusGainPercent ~= 0.25 || ...
        protocol.headroom.minimumAttemptedByteSavingPercent ~= 0.25 || ...
        ~protocol.headroom.passedActionRequiredBeforeDatasetExpansion || ...
        ~protocol.headroom.requireCausalQueryKeyDiscoverabilityBeforeDatasetExpansion || ...
        protocol.headroom.materialPassAloneAuthorizesDatasetExpansion || ...
        protocol.headroom.v226T50PassesMaterialGate || ...
        ~protocol.carrier.frozenBeforeDatasetConstruction || ...
        protocol.action.maximumCompleteLabelTransfersPerPage ~= 1 || ...
        protocol.action.selfInputReplacementAllowed || ...
        ~protocol.action.totalLabelWeightPreserved || ...
        ~protocol.action.fullPayloadChargedBeforeProjection || ...
        protocol.controlPlane.maximumQueriedLabels ~= 3 || ...
        protocol.controlPlane.queryHeaderBytes ~= 16 || ...
        protocol.controlPlane.queryBytesPerLabelKey ~= 4 || ...
        protocol.controlPlane.responseHeaderBytes ~= 16 || ...
        protocol.controlPlane.responseBytesPerLabelRecord ~= 20 || ...
        ~protocol.controlPlane.queryCostChargedBeforePayloadSelection || ...
        ~protocol.controlPlane.completeLabelPayloadChargedSeparately || ...
        protocol.controlPlane.maximumCompletePayloadRequestsPerPage ~= 1 || ...
        protocol.controlPlane.retryAfterProjectionRejectionAllowed || ...
        protocol.controlPlane.queryKeySelectorImplemented || ...
        protocol.controlPlane.queryKeyDiscoverabilityValidated || ...
        ~protocol.controlPlane.headroomUsesTeacherSelectedQueryKeys || ...
        ~protocol.controlPlane.materialHeadroomOnlyAuthorizesDiscoveryDesign || ...
        protocol.model.fullMixtureFeaturesUsedForPreFetchRanking || ...
        ~protocol.model.payloadAwareSelectionBeforeFetch || ...
        protocol.projection.learnedOverrideAllowed || ...
        protocol.projection.maximumExactCandidatesPerPage ~= 1 || ...
        ~protocol.projection.completePayloadFetchedBeforeProjection || ...
        protocol.projection.retryAfterRejectionAllowed || ...
        ~protocol.projection.preservesSelfEvidence || ...
        ~protocol.projection.preservesTotalLabelKlaWeight || ...
        abs(protocol.theory.maximumOddsMultiplier - exp(epsilon)) > 1e-12 || ...
        abs(protocol.theory.maximumAbsoluteExistenceChange - ...
            tanh(epsilon / 4)) > 1e-12 || ...
        ~protocol.theory.byteFeasibilityImpliesPositiveNetSaving || ...
        abs(protocol.theory.communicationCreditReserveFraction - ...
            0.20) > 1e-12 || ...
        ~isequal(protocol.model.targetNames, v213.risk.targetNames) || ...
        ~isequal(protocol.split, v213.split) || ...
        protocol.onlinePolicyImplemented || ...
        ~protocol.queryFirstHeadroomImplemented || ...
        protocol.validationClaimAllowed || ...
        base.maximumReferenceLogOddsDrop ~= 0.25 || ...
        base.maximumReferenceLogOddsIncrease ~= 0.25
    error('FusionAwareLabelEdgeControllerV228:ProtocolDrift', ...
        'The conditional V228 controller contract is inconsistent.');
end
end
