function protocol = getHierarchicalDelayedValueControllerV213Protocol()
% GETHIERARCHICALDELAYEDVALUECONTROLLERV213PROTOCOL Freeze V213 design.
%
% V213 is the first protocol registered before opening new recursive
% M24/X36 trajectories.  It keeps the generic V99 route as no-op, proposes
% a bounded mode-diverse complete-label/release action set, and reserves
% final action admission for an H=3 vector lower-bound model.

protocol = struct();
protocol.id = 'hierarchical-delayed-value-controller-v213-v1';
protocol.contractVersion = ...
    'hierarchical-delayed-value-controller-v213-protocol-v1';
protocol.basePolicyName = ...
    'online-positive-net-addressable-payload-v99-v1';
protocol.horizonSteps = 3;
protocol.maximumExecutedActionsPerPage = 1;
protocol.completeLabelSourceWeight = 0.5;

proposal = struct();
proposal.contractVersion = ...
    'hierarchical-formation-proposal-v213-v1';
proposal.formationFeatureName = 'need_max';
proposal.relativeNeedFloor = 0.90;
proposal.maximumFormationCount = 2;
proposal.modeFeatureNames = { ...
    'precision_refresh_evidence', ...
    'receiver_existence_deficit', ...
    'observation_handover_evidence'};
proposal.topPerMode = 3;
proposal.semanticCooldownPages = 1;
proposal.includeFormationRelease = true;
proposal.releaseFeasibilityContract = ...
    'explicit-current-route-state-releasable-formations';
proposal.sourceSynopsisBytes = 64;
proposal.receiverPropagationBytes = 24;
proposal.propagationFeatureCostChargedForEveryLabelProposal = true;
proposal.maximumLabelProposalCount = ...
    proposal.maximumFormationCount * ...
        proposal.topPerMode * numel(proposal.modeFeatureNames);
proposal.maximumProposalCount = proposal.maximumLabelProposalCount + ...
    proposal.maximumFormationCount;
proposal.tieBreakContract = ...
    'descending-score-then-enumerator-order';
proposal.truthUsed = false;
proposal.futureMeasurementsUsed = false;
protocol.proposal = proposal;

targetNames = { ...
    'mean_eospa_gain_percent', ...
    'mean_rmse_gain_percent', ...
    'consensus_gain_percent', ...
    'terminal_consensus_gain_percent', ...
    'receiver_formation_eospa_gain_percent', ...
    'receiver_formation_rmse_gain_percent', ...
    'minimum_affected_sensor_eospa_gain_percent', ...
    'minimum_affected_sensor_rmse_gain_percent', ...
    'worst_sensor_eospa_gain_percent', ...
    'worst_sensor_rmse_gain_percent', ...
    'minimum_formation_eospa_gain_percent', ...
    'minimum_formation_rmse_gain_percent'};
risk = struct();
risk.contractVersion = 'pareto-risk-budget-v213-v1';
risk.targetNames = targetNames;
% Aggregate tracking and both consistency coordinates must not regress.
% Formation/network tails receive a small visible redistribution budget;
% the affected-sensor RMSE coordinate receives only a catastrophe cap.
risk.tolerancePercent = [ ...
    0, 0, 0, 0, ...
    -1.5, -1.5, -5, -10, ...
    -1.5, -1.5, -1.5, -1.5];
risk.minimumStaticAttemptedByteSavingPercent = 1.0;
risk.conformalMiscoverage = 0.10;
risk.calibrationUnit = ...
    'complete-scene-seed-trajectory-maximum';
risk.selectionRule = ...
    'maximum-minimum-normalized-lower-bound-margin';
risk.noOpFallbackRequired = true;
risk.truthUsedAtRuntime = false;
protocol.risk = risk;

model = struct();
model.contractVersion = ...
    'dense-immediate-sparse-h3-residual-v213-v1';
model.immediateTarget = 'current-page-vector-gain';
model.recursiveTarget = 'same-state-no-op-relative-h3-vector-gain';
model.residualTarget = 'recursive-minus-immediate';
model.targetTransform = ...
    'tanh-log-reference-error-over-candidate-error';
model.propagationFeatureContract = ...
    'formation-repair-propagation-features-v211-v1';
model.candidateArchitectures = { ...
    'action-only-ridge', ...
    'frozen-two-round-graph-ridge', ...
    'trainable-two-round-formation-gnn'};
model.architectureSelectionUnit = ...
    'leave-one-complete-training-trajectory-out';
model.calibrationUsedForArchitectureSelection = false;
protocol.model = model;

split = struct();
split.contractVersion = ...
    'multistyle-complete-trajectory-split-v213-v1';
split.mainSceneStyles = {'radial', 'convoy', 'relay'};
split.mainPresets = { ...
    'm24-formation-fov', 'x36-formation-fov', ...
    'm24-formation-fov-convoy', 'x36-formation-fov-convoy', ...
    'm24-formation-fov-relay', 'x36-formation-fov-relay'};
split.trainingSeeds = [1301, 1303];
split.calibrationSeeds = [1409, 1423];
split.evaluationSeeds = [1511, 1523];
split.stressSeeds = [1601, 1607];
split.scaleExtrapolationSeeds = [1709, 1721];
split.stressPresets = { ...
    'm24-formation-fov-crossing', ...
    'x36-formation-fov-crossing', ...
    'm24-formation-fov-braided-handover', ...
    'x36-formation-fov-braided-handover', ...
    'm24-formation-fov-merge-split', ...
    'x36-formation-fov-merge-split', ...
    'm24-formation-fov-target-overlap', ...
    'x36-formation-fov-target-overlap', ...
    'm24-formation-fov-curved-corridor', ...
    'x36-formation-fov-curved-corridor'};
split.scaleExtrapolationPresets = {'x48-formation-fov'};
split.registeredDecisionWindowsPerTrajectory = 2;
split.minimumDecisionWindowSeparation = 12;
split.decisionWindowSelection = ...
    'truth-free-local-maxima-of-formation-need';
split.groupSameSeedAcrossScaleAndStyle = true;
split.completeTrajectoryDisjoint = true;
protocol.split = split;

promotion = struct();
promotion.minimumMeanEospaGainPercentByScale = 5;
promotion.minimumMeanRmseGainPercentByScale = 5;
promotion.minimumConsensusGainPercentByScale = 2;
promotion.minimumAttemptedByteSavingPercentByScale = 1;
promotion.currentBestTableUpdatedBelowPromotionGate = true;
protocol.promotion = promotion;

protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v213');
protocol.developmentAnchorSeeds = 211;
protocol.developmentAnchorsMayTrain = false;
protocol.developmentAnchorsMayCalibrate = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V213 freezes the proposal cap, risk tolerances, H=3 target, ', ...
    'communication reserve and complete-trajectory split after the ', ...
    'seed-211 mechanism anchors but before opening seeds 1301 and ', ...
    'above. Seed 211 may test contracts only and cannot train, ', ...
    'calibrate or validate the selector. The current-best table may ', ...
    'still record a below-promotion result with its evidence boundary.'];

assertProtocol(protocol);
end

function assertProtocol(protocol)
split = protocol.split;
seedSets = {split.trainingSeeds, split.calibrationSeeds, ...
    split.evaluationSeeds, split.stressSeeds, ...
    split.scaleExtrapolationSeeds};
for leftIdx = 1:numel(seedSets)
    if numel(unique(seedSets{leftIdx})) ~= numel(seedSets{leftIdx})
        error('V213Protocol:DuplicateSeed', ...
            'Every split must contain unique seeds.');
    end
    for rightIdx = leftIdx + 1:numel(seedSets)
        if ~isempty(intersect(seedSets{leftIdx}, seedSets{rightIdx}))
            error('V213Protocol:SplitLeakage', ...
                'Complete-trajectory seed splits must be disjoint.');
        end
    end
end
if ismember(protocol.developmentAnchorSeeds, ...
        [seedSets{:}]) || ...
        numel(protocol.risk.targetNames) ~= ...
            numel(protocol.risk.tolerancePercent) || ...
        protocol.proposal.relativeNeedFloor <= 0 || ...
        protocol.proposal.relativeNeedFloor > 1 || ...
        protocol.proposal.maximumFormationCount < 1 || ...
        protocol.proposal.topPerMode < 1 || ...
        protocol.horizonSteps ~= 3
    error('V213Protocol:InvalidContract', ...
        'The frozen V213 protocol is internally inconsistent.');
end
end
