function protocol = getInfluenceConeCarrierV113Protocol()
% GETINFLUENCECONECARRIERV113PROTOCOL Carrier-direction interaction.

base = getOpenedSafeFormationV110Protocol();
protocol = base;
protocol.id = 'influence-cone-carrier-v113-v1';
protocol.contractVersion = 'influence-cone-carrier-v113-protocol-v1';
protocol.outcomePolicyName = 'influence-cone-carrier-v113-v1';
protocol.executionProfile = 'v113-influence-cone-carrier';
protocol.bankVariant = 'influence-cone-carrier-v113';
protocol.clockwiseFullActionName = ...
    'v113-clockwise-full-payload-h8';
protocol.clockwiseAbstentionActionName = ...
    'v113-clockwise-safe-abstention-h8';
protocol.primaryReferenceOrientation = 'counter-clockwise';
protocol.alternativeReferenceOrientation = 'clockwise';
protocol.resultContractVersion = ...
    'influence-cone-carrier-v113-x36-t72-result-v1';
protocol.resultFileStem = ...
    'INFLUENCE_CONE_CARRIER_V113_X36_T72_RESULT';
protocol.reportTitle = ...
    'V113 carrier-direction interaction: X36 t72 H=8';
protocol.runLabel = 'V113 X36-t72 H=8';
protocol.minimumFormationGainPercent = 0;
protocol.minimumTargetPeerTerminalGainPercent = 0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v113', 'influence_cone_carrier');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_best_direction_headroom');
protocol.evidenceBoundary = [ ...
    'V113 is a frozen retrospective carrier-direction interaction ', ...
    'screen at X36 seed 211, t=72, H=8. The registered counter-clockwise ', ...
    'full-payload outcome is reused. A clockwise full-payload arm ', ...
    'provides a conditional alternative-static baseline, and a clockwise ', ...
    'arm with the opened V110 F2--F5 abstention schedule tests whether ', ...
    'moving the protected-to-safe formation boundary can contain delayed ', ...
    'harm. The safe-formation set was chosen from opened V105 outcomes, ', ...
    'so V113 is an action-space upper bound, not a deployable policy. ', ...
    'All executed rows preserve the same dominant/residual weight ', ...
    'multiset, message count, physicality and rolling B3 constraints. ', ...
    'Measurements, delivery uniforms, filter RNG and communication ', ...
    'accounting remain paired. The interaction must beat the better ', ...
    'full-payload direction; no validation or generalization claim is ', ...
    'authorized.'];
end
