function protocol = getIndependentM24GatewayTeacherV252Protocol()
% GETINDEPENDENTM24GATEWAYTEACHERV252PROTOCOL Cross-seed teacher data.

source = getCausalGatewayEmbeddingV250Protocol();
protocol = source;
protocol.id = 'independent-m24-gateway-teacher-v252-v1';
protocol.contractVersion = ...
    'independent-m24-gateway-teacher-v252-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v252-independent-m24-gateway-teacher';
protocol.allowedPresets = { ...
    'm24-formation-fov-temporal-coupled-formation-braid'};
protocol.trainingSeeds = [1302, 1303];
protocol.developmentHoldoutSeeds = 1304;
protocol.untouchedFullEpisodeSeeds = 1305;
protocol.allowedSeeds = [ ...
    protocol.trainingSeeds, protocol.developmentHoldoutSeeds];
protocol.anchorTimes = 40:20:140;
protocol.horizonSteps = 3;
protocol.minimumJointPositiveAnchorCount = 3;
protocol.resultContractVersion = ...
    'independent-m24-gateway-teacher-v252-result-v1';
protocol.windowContractVersion = ...
    'independent-m24-gateway-teacher-v252-window-v1';
protocol.oracleMatName = ...
    'INDEPENDENT_M24_GATEWAY_TEACHER_V252.mat';
protocol.oracleReportName = ...
    'INDEPENDENT_M24_GATEWAY_TEACHER_V252.md';
protocol.reportTitle = ...
    'V252 independent M24 gateway teacher dataset';
protocol.runLabel = 'V252';
protocol.continuationSource = 'v252-v242-reference-cache';
protocol.cacheFilePrefix = ...
    'V252_V242_REFERENCE';
protocol.oraclePassDecision = ...
    'include-seed-in-frozen-cross-seed-ridge-study';
protocol.oracleFailDecision = ...
    'retain-seed-arms-but-do-not-assume-dense-positive-teacher-support';
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v252', ...
    'independent_m24_gateway_teacher');
protocol.cacheRoot = fullfile(protocol.outputRoot, ...
    'reference_cache');
protocol.oracleOutputRoot = protocol.outputRoot;
protocol.minimumDevelopmentHoldoutTailAlignedFraction = 0.5;
protocol.ridgeLambdaGrid = [1e-6, 1e-4, 1e-2, 1, 100];
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V252 uses a predeclared six-anchor time grid on three new M24 ', ...
    'scene seeds. Seeds 1302 and 1303 are training/model-selection data; ', ...
    'seed 1304 is opened only after the ridge representation, objective ', ...
    'and lambda-selection rule are frozen. Seed 1305 receives no H=3 ', ...
    'teacher labels and remains reserved for a later complete-episode ', ...
    'test. Anchor selection uses time only, never truth, posterior risk ', ...
    'or realized candidate outcome. Every paired arm shares measurements, ', ...
    'delivery uniforms, filter RNG, message count and V242 continuation. ', ...
    'These data may authorize a deployable M24 ridge policy study; they ', ...
    'cannot establish complete-episode, X36 or paper-level gains.'];

if numel(intersect(protocol.allowedSeeds, ...
        protocol.untouchedFullEpisodeSeeds)) ~= 0 || ...
        any(diff(protocol.anchorTimes) < protocol.horizonSteps) || ...
        protocol.anchorTimes(1) < 2 || ...
        protocol.anchorTimes(end) + protocol.horizonSteps - 1 > 160 || ...
        protocol.minimumDevelopmentHoldoutTailAlignedFraction <= 0 || ...
        protocol.minimumDevelopmentHoldoutTailAlignedFraction > 1
    error('IndependentM24GatewayTeacherV252:InvalidProtocol', ...
        'The V252 cross-seed teacher protocol is inconsistent.');
end
end
