function protocol = getInfluenceAwareDecisionBreadthV66Protocol()
% GETINFLUENCEAWAREDECISIONBREADTHV66PROTOCOL Frozen development design.

v65 = getNetworkAdditiveFormationRiskV65Protocol();
radial = resolveCase(v65.m24Cases, 'm24-formation-fov', 211);
convoy = resolveCase( ...
    v65.m24Cases, 'm24-formation-fov-convoy', 1201);
protocol = struct();
protocol.id = 'influence-aware-decision-breadth-v66-v1';
protocol.contractVersion = ...
    'influence-aware-decision-breadth-v66-protocol-v1';
protocol.baseProtocolId = v65.id;
protocol.positiveSupportThreshold = ...
    v65.positiveSupportThreshold;
protocol.horizonSteps = v65.horizonSteps;
% The desired strong tracking gain is 5%.  V66 uses the same numerical
% fraction as a pre-outcome development gate on the dimensionless,
% network-time-normalized robust decision exposure.  This is a calibrated
% proxy threshold, not a theorem that guarantees 5% E-OSPA improvement.
protocol.minimumNormalizedRobustMarginExposure = ...
    v65.minimumMeanGainPercent / 100;
protocol.cases = [ ...
    caseEntry('M24 radial', 'm24-formation-fov', 211, 104, ...
        radial.cacheRoot, 6.4046, 'direct V65 paired outcome'), ...
    caseEntry('M24 radial', 'm24-formation-fov', 211, 124, ...
        radial.cacheRoot, 8.4460, 'direct V65 paired outcome'), ...
    caseEntry('X36 radial', v65.x36PresetName, v65.x36Seed, 72, ...
        v65.x36CacheRoot, 5.847429, ...
        'schedule-identical V64 paired outcome'), ...
    caseEntry('X36 radial', v65.x36PresetName, v65.x36Seed, 100, ...
        v65.x36CacheRoot, 9.329497, ...
        'schedule-identical V64 paired outcome'), ...
    caseEntry('M24 convoy', 'm24-formation-fov-convoy', 1201, 80, ...
        convoy.cacheRoot, 0.314826, 'direct fresh V65 paired outcome')];
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v66', 'influence_breadth_attribution');
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V66 is designed after the M24 convoy t=80 outcome exposed the ', ...
    'scene-generalization defect in V65. Its five registered rows are ', ...
    'opened development evidence used to test the new observable proxy, ', ...
    'not held-out validation. The proxy and threshold must be committed ', ...
    'before any new relay, merge-split, or curved-corridor tracking ', ...
    'outcome is opened.'];
end

function value = caseEntry( ...
        scaleName, presetName, seed, currentTime, cacheRoot, ...
        knownGainPercent, source)
value = struct( ...
    'scaleName', scaleName, ...
    'presetName', presetName, ...
    'seed', seed, ...
    'currentTime', currentTime, ...
    'cacheRoot', cacheRoot, ...
    'knownGainPercent', knownGainPercent, ...
    'source', source);
end

function value = resolveCase(cases, presetName, seed)
mask = strcmp({cases.presetName}, presetName) & [cases.seed] == seed;
if nnz(mask) ~= 1
    error('InfluenceAwareV66:MissingBaseCase', ...
        'V66 requires one registered V65 cache case.');
end
value = cases(find(mask, 1));
end
