function protocol = getInitialDynamicRouteFreezeV237Protocol()
% GETINITIALDYNAMICROUTEFREEZEV237PROTOCOL Strong no-reselection baseline.

source = getCorrectedStaticRoutingBaselineV227Protocol();
protocol = struct();
protocol.id = 'initial-dynamic-route-freeze-v237-v1';
protocol.contractVersion = ...
    'initial-dynamic-route-freeze-v237-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v237-initial-current-physical-route-freeze';
protocol.policyName = 'initial-dynamic-route-freeze-v237-fixed';
protocol.allowedPresets = {'m24-formation-fov', 'x36-formation-fov'};
protocol.allowedSeeds = 1301;
protocol.splitName = 'training';
protocol.directedInputsPerReceiver = source.directedInputsPerReceiver;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.receiverMode = source.receiverMode;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v237', 'initial_route_freeze');
protocol.validationClaimAllowed = false;
protocol.developmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V237 is a strong no-reselection mechanism baseline. It applies the ', ...
    'same V227 current-physical route selector once at t=1 and freezes ', ...
    'the resulting route and weights. Runtime execution checks only the ', ...
    'current physical page and reads no truth or future outcome. The ', ...
    'experiment preflight separately verifies that the frozen route is ', ...
    'physical for the completed scene; this all-time eligibility check ', ...
    'uses future graph pages and therefore V237 is not yet a deployable ', ...
    'fallback policy. It isolates whether V227 gains came from the ', ...
    'initial action set or from temporal route reselection.'];
end
