function protocol = getInfluenceConeBoundaryShieldV114Protocol()
% GETINFLUENCECONEBOUNDARYSHIELDV114PROTOCOL F6 arrival shield.

base = getInfluenceConeCarrierV113Protocol();
protocol = base;
protocol.id = 'influence-cone-boundary-shield-v114-v1';
protocol.contractVersion = ...
    'influence-cone-boundary-shield-v114-protocol-v1';
protocol.outcomePolicyName = ...
    'influence-cone-boundary-shield-v114-v1';
protocol.executionProfile = ...
    'v114-influence-cone-boundary-shield';
protocol.bankVariant = 'influence-cone-boundary-shield-v114';
protocol.boundaryFormationId = 6;
protocol.boundarySourceSensorId = 27;
protocol.boundaryReceiverSensorId = 32;
protocol.arrivalPageIndex = 6;
protocol.earlyPageIndex = 5;
protocol.arrivalShieldActionName = ...
    'v114-f6-shield-on-arrival-p6-h8';
protocol.earlyShieldActionName = ...
    'v114-f6-shield-early-p5-h8';
protocol.candidateActionNames = { ...
    protocol.arrivalShieldActionName, ...
    protocol.earlyShieldActionName};
protocol.baseMechanismActionName = ...
    base.clockwiseAbstentionActionName;
protocol.baseProtectionFormationIdsByTime = ...
    base.protectionFormationIdsByTime;
protocol.arrivalShieldFormationIdsByTime = ...
    addBoundaryFormation( ...
        protocol.baseProtectionFormationIdsByTime, ...
        protocol.boundaryFormationId, protocol.arrivalPageIndex);
protocol.earlyShieldFormationIdsByTime = ...
    addBoundaryFormation( ...
        protocol.baseProtectionFormationIdsByTime, ...
        protocol.boundaryFormationId, protocol.earlyPageIndex);
protocol.v113ScreenPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v113', 'influence_cone_carrier', ...
    'matched_best_direction_headroom', 'x36_t72_h8', 'screen', ...
    ['TRACKING_ALIGNED_X36_SCHEDULE_H8_', ...
     'X36_FORMATION_FOV_SEED211_T72_D8.mat']);
protocol.referenceOutcomeScreenPath = protocol.v113ScreenPath;
protocol.resultContractVersion = ...
    'influence-cone-boundary-shield-v114-x36-t72-result-v1';
protocol.resultFileStem = ...
    'INFLUENCE_CONE_BOUNDARY_SHIELD_V114_X36_T72_RESULT';
protocol.reportTitle = ...
    'V114 F6 influence-boundary shield: X36 t72 H=8';
protocol.runLabel = 'V114 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v114', 'influence_cone_boundary_shield');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_best_direction_headroom');
protocol.evidenceBoundary = [ ...
    'V114 is a frozen retrospective X36 seed-211 t=72 H=8 ', ...
    'boundary-control screen. V113 opened outcomes identify the ', ...
    'clockwise 27-to-32 cross-formation residual edge and the sixth ', ...
    'page as the first F6 loss page. V114 therefore holds the V113 ', ...
    'clockwise F2--F5 abstention mechanism fixed and adds F6 ', ...
    'receiver-side abstention either on the predicted arrival page or ', ...
    'one page earlier. The V113 CCW-full, CW-full and unshielded ', ...
    'mechanism outcomes are reused; only the two boundary arms are ', ...
    'executed. Measurements, delivery uniforms, filter RNG, carrier ', ...
    'weights, physical edges and communication accounting remain ', ...
    'paired, and rolling B3 is preserved. Because the boundary and ', ...
    'timing were selected from opened V113 outcomes, V114 is an oracle ', ...
    'action-space screen, not a deployable policy or validation claim.'];
end

function schedule = addBoundaryFormation( ...
        baseSchedule, formationId, startPage)
schedule = baseSchedule;
for pageIdx = startPage:numel(schedule)
    schedule{pageIdx} = unique( ...
        [reshape(schedule{pageIdx}, 1, []), formationId], 'stable');
end
end
