function protocol = ...
    getInfluenceAwareDecisionBreadthV66SceneDiscoveryProtocol()
% GETINFLUENCEAWAREDECISIONBREADTHV66SCENEDISCOVERYPROTOCOL Fresh relay.

method = getInfluenceAwareDecisionBreadthV66Protocol();
protocol = struct();
protocol.id = ...
    'influence-aware-decision-breadth-v66-scene-discovery-v1';
protocol.contractVersion = ...
    'influence-aware-decision-breadth-v66-scene-protocol-v1';
protocol.methodProtocolId = method.id;
protocol.referencePolicyName = ...
    'formation-h3-fixed-ccw-reference-v1';
protocol.presets = {'m24-formation-fov-relay'};
protocol.allSeeds = 1301;
protocol.snapshotTimes = 40:4:136;
protocol.horizonSteps = method.horizonSteps;
protocol.filterSeedOffset = 100000;
protocol.expectedNodeCount = 24;
protocol.expectedFormationCount = 4;
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v66', 'relay_scene_discovery', 'cache');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v66', 'relay_scene_discovery');
protocol.referenceStateGenerationAuthorized = true;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V66 relay discovery runs one truth-free fixed-reference M24 ', ...
    'trajectory on seed 1301 and evaluates only current posterior, ', ...
    'current link state, and past topology at pre-registered times. ', ...
    'It may freeze at most one fresh relay event for a later paired ', ...
    'development run. It does not authorize tracking scoring, model ', ...
    'training, held-out claims, or validation.'];
end
