function protocol = getJointTaskRiskInputProtectionV93Protocol()
% GETJOINTTASKRISKINPUTPROTECTIONV93PROTOCOL Exact subset headroom gate.

v92 = getTaskRiskInputProtectionV92Protocol();
protocol = v92;
protocol.id = 'joint-task-risk-input-protection-v93-v1';
protocol.contractVersion = ...
    'joint-task-risk-input-protection-v93-protocol-v1';
protocol.sourceSingleFormationProtocolId = v92.id;
protocol.sourceSingleFormationFailureCommit = '067ff54';
protocol.maximumExactFormationCount = 6;
protocol.directBestSubsetAuditRequired = true;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v93', ...
    'joint_task_risk_input_protection_headroom');
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V93 is a current-only exact subset oracle over the registered ', ...
    'formation input-protection action.  Every nonempty formation ', ...
    'subset is compared with the same current physical-tree reference. ', ...
    'Single-formation receiver distributions are composed only because ', ...
    'the actions change disjoint receiver rows; the selected best subset ', ...
    'is then recomputed by the full one-round fusion enumerator.  The ', ...
    'oracle uses no target truth or future observation.  It establishes ', ...
    'headroom for this action family only, not recursive tracking or ', ...
    'E-OSPA improvement.'];
end
