function protocol = getLearnedOneHopSafeLabelV169Protocol()
% GETLEARNEDONEHOPSAFELABELV169PROTOCOL Recursive learned repair screen.

base = getObservableOneHopRiskLabelV162Protocol();
protocol = base;
protocol.id = 'learned-one-hop-safe-label-v169-v1';
protocol.contractVersion = ...
    'learned-one-hop-safe-label-v169-protocol-v1';
protocol.outcomePolicyName = 'learned-one-hop-safe-label-v169-v1';
protocol.executionProfile = 'v169-learned-one-hop-safe-label';
protocol.bankVariant = 'learned-one-hop-safe-label-v169';
protocol.candidateActionName = ...
    'v169-analytic-f3-plus-sequential-cardinality-relief';
protocol.learnedModelPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v170', 'cost_aware_feature_profile', ...
    'compact_scalar', ...
    'NONLINEAR_SAFE_ONE_HOP_ACTION_V168_MODEL.mat');
protocol.learnedPolicyPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v175', 'cardinality_pressure_relief', ...
    'CARDINALITY_PRESSURE_RELIEF_V175_POLICY.mat');
protocol.rollbackFormationIdsByTime = { ...
    [], [], [], [], [2, 3], 1, [1, 3, 6], [1, 3, 6]};
protocol.learnedRepairTimes = [78, 79];
protocol.learnedRepairFormationIdsByTime = {5, 5};
protocol.learnedMaximumLabelEdits = 2;
protocol.learnedSynopsisHeaderBytes = 16;
% Packed per-label advertisement: key plus quantized existence, risk,
% uncertainty/evidence, observation opportunity, trace and payload class.
protocol.learnedSynopsisBytesPerLabel = 24;
protocol.learnedRequestHeaderBytes = 16;
protocol.learnedRequestBytesPerLabel = 2 * 8;
protocol.minimumMeanGainPercent = 5;
protocol.minimumMeanRmseGainPercent = 2;
protocol.minimumWorstRmseGainPercent = 0;
protocol.minimumFormationRmseGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.minimumWindowConsensusGainPercent = 0;
protocol.minimumTerminalConsensusGainPercent = 0;
protocol.resultContractVersion = ...
    'learned-one-hop-safe-label-v169-x36-t72-result-v1';
protocol.resultFileStem = ...
    'LEARNED_ONE_HOP_SAFE_LABEL_V169_X36_T72_RESULT';
protocol.reportTitle = ...
    'V169 learned safe one-hop repair: X36 t72 H=8';
protocol.armDisplayName = ...
    'V169 analytic F3 + sequential learned F5 repair';
protocol.runLabel = 'V169 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v169', 'learned_safe_one_hop_label');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V169 is a paired recursive X36 seed-211 t=72 H=8 development ', ...
    'screen. It retains the frozen V105 route, weights and protection ', ...
    'schedule plus the truth-free V162 analytic transfers at F1/F2/F3/F6. ', ...
    'At the opened F5 repair cells, a frozen compact classifier first ', ...
    'scores a deterministic seven-criterion source shortlist. After the ', ...
    'first delivered label updates the receiver posterior, a second ', ...
    'request is allowed only under a frozen high-cardinality-pressure ', ...
    'gate; a conditional classifier filters candidates and minimum ', ...
    'source evidence quality breaks ties. The policy may abstain and ', ...
    'requests at most two sequential complete Bernoulli GM labels. ', ...
    'Inference reads no truth, future measurements or numeric label IDs. ', ...
    'The ledger charges a 24-byte packed synopsis per advertised active ', ...
    'source-label, both request headers and complete-label responses on ', ...
    'the frozen directed delivery realization. The repair schedule and ', ...
    'most training cells were selected after opening seed 211, so this ', ...
    'is recursive method-development evidence, not validation or a ', ...
    'generalization claim.'];
end
