function protocol = getLabelSetSimulatorPolicyProtocol()
% GETLABELSETSIMULATORPOLICYPROTOCOL Frozen redesign entry gate.

predecessor = getOrdinalFullInformationLearnabilityProtocol();
graph = getCvarResidualGraphPolicyDatasetProtocol();
if ~predecessor.ordinalLearnabilityRejected || ...
        ~predecessor.labelSetSimulatorPolicyDesignAuthorized
    error('Label-set simulator policy redesign is not authorized.');
end
if ~isequal(predecessor.trainingSeeds, graph.trainingSeeds) || ...
        ~isequal(predecessor.snapshotTimes, ...
            graph.learningLabelTimes)
    error('Label-set and registered graph training splits differ.');
end

protocol = struct();
protocol.id = ...
    'm24-label-set-simulator-policy-redesign-v1';
protocol.datasetContractVersion = ...
    'm24-label-set-edge-state-shard-v1';
protocol.featureContractVersion = ...
    'directed-lmb-label-set-observable-features-v1';
protocol.predecessorProtocolId = predecessor.id;
protocol.graphDatasetProtocolId = graph.id;
protocol.presetName = graph.presetName;
protocol.trainingSeeds = graph.trainingSeeds;
protocol.snapshotTimes = graph.learningLabelTimes;
protocol.preflightSeeds = 11;
protocol.lockedDevelopmentSeeds = ...
    graph.developmentValidationSeeds;
protocol.lockedHeldoutM24Seeds = ...
    graph.lockedHeldoutM24Seeds;
protocol.datasetVariant = graph.datasetVariant;
protocol.continuationStartTime = ...
    graph.continuationStartTime;
protocol.actionCodeSequences = ...
    graph.actionCodeSequences;
protocol.datasetSeeds = graph.datasetSeeds;
protocol.sourceWeight = graph.sourceWeight;
protocol.payloadToleranceFraction = ...
    graph.payloadToleranceFraction;
protocol.filterSeedOffset = graph.filterSeedOffset;
protocol.featureContextMode = graph.featureContextMode;
protocol.dominantWeight = graph.dominantWeight;
protocol.localResidualWeight = ...
    graph.localResidualWeight;
protocol.residualWeightGrid = ...
    graph.residualWeightGrid;
protocol.expectedNodeCount = graph.expectedNodeCount;
protocol.expectedCandidateCount = ...
    graph.preflightExpectedCandidateCount;
protocol.expectedWeightCount = ...
    graph.expectedWeightCount;
protocol.maxLabelCount = 32;
protocol.expectedLabelFeatureCount = 34;
protocol.defaultOutputDirectory = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'datasets', ...
    'label_set_policy_shards');
protocol.registeredShardSeeds = protocol.trainingSeeds;
protocol.registeredShardPaths = cellfun(@(seed) ...
    fullfile(protocol.defaultOutputDirectory, sprintf( ...
        'label_set_policy_m24_seed%d_t78_t83_v1.mat', seed)), ...
    num2cell(protocol.registeredShardSeeds), ...
    'UniformOutput', false);
protocol.registeredShardSha256 = { ...
    'f59e0d097f0f40d906b3f314a971b5bd3a36bbece5fb9a708070f15dfb6edf81', ...
    '609dd9bf6219b663bd90a7e990b669ebf4a7cf46d1771a19abb4e65357e2e32a', ...
    'f28a10fd45afb8f5fe35e810cb076365621feec5d56629c328b8e62ce3f6dde4', ...
    'dae8ae00be7aafe9df08fe43cfc0811c3f2aebabc9bab6363e36b8f57357adea', ...
    'e281ad335389c5a060e48b219fd34dadd8de78acb6810832c9f04b2aa0cdb82f', ...
    '822291d8f3583584e8e1bf8e6ef27e510342bf97f41d74c142a2d18d66bcbdf3'};
protocol.shardGenerationCommit = ...
    'e0c0600d51945280c76648e913364f96a45c0f76';
protocol.registeredFeatureContractSha256 = ...
    '313f7f539c7573dd32dc46e30bae864967f5801bce91e99451c8314383dda4ce';
protocol.registeredStateCount = 36;
protocol.registeredValidLabelRowCount = 165771;
protocol.registeredMaximumObservedLabelCount = 16;
protocol.positionScaleSource = 'model-ospa-cutoff';
protocol.velocityScale = 1;
protocol.highExistenceThreshold = 0.50;
protocol.numericLabelIdentifiersUsedAsFeatures = false;
protocol.labelCapacityOverflowPolicy = ...
    'fail-closed-no-truncation';
protocol.labelEncoder = ...
    'shared-label-mlp-with-sum-mean-max-symmetric-pooling';
protocol.graphEncoder = ...
    'two-round-directed-edge-node-message-passing';
protocol.actionHead = ...
    'residual-cycle-edge-and-weight-score';
protocol.safetyProjection = ...
    ['fixed-dominant-backbone-plus-message-count-preserving-', ...
     'strong-residual-cycle'];
protocol.nominalGuaranteeScope = [ ...
    'The projector preserves the registered persistent structural ', ...
    'condition for ideal exact-KLA information flow. It does not ', ...
    'assert unconditional consensus for the implemented approximate ', ...
    'LMB filter under missing labels, packet loss, truncation or ', ...
    'interleaved local updates.'];
protocol.representationDiagnosticTarget = ...
    'registered-current-truth-edge-task-advantage-training-only';
protocol.finalTrainingObjective = ...
    ['paired-closed-loop-tracking-and-consensus-return-', ...
     'under-common-random-numbers'];
protocol.modelSelectionObjective = ...
    'paired-closed-loop-return-not-teacher-imitation';
protocol.representationPreflightModel = ...
    'pairwise-deepset-relational-task-diagnostic-v1';
protocol.representationAggregateBaseline = ...
    'pairwise-ridge-aggregate-relational-task-diagnostic-v1';
protocol.labelHiddenWidth = 16;
protocol.nodeHiddenWidth = 16;
protocol.edgeHiddenWidth = 32;
protocol.representationEpochCount = 500;
protocol.representationLearningRate = 1e-2;
protocol.representationWeightDecay = 1e-3;
protocol.representationHuberDelta = 1;
protocol.representationInitializationSeed = 20260730;
protocol.aggregateRidgeLambda = 1;
protocol.minimumRepresentationPairwisePreferenceAccuracy = 0.60;
protocol.minimumRepresentationDifferenceSpearman = 0.25;
protocol.minimumPositivePerSeedSpearmanFraction = 4 / 6;
protocol.minimumPairwiseImprovementOverTaskAggregate = 0.03;
protocol.minimumSpearmanImprovementOverTaskAggregate = 0.05;
protocol.aggregateSurrogateReferencePairwiseAccuracy = ...
    predecessor.observedOuterSurrogatePairwiseAccuracy;
protocol.requireTaskAggregateImprovement = true;
protocol.actionEvidencePath = ...
    predecessor.sourceAnalysisPath;
protocol.actionEvidenceSha256 = ...
    predecessor.sourceAnalysisSha256;
protocol.expectedPairCount = predecessor.expectedPairCount;
protocol.defaultRepresentationAuditPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'label_set_representation_learnability_m24.mat');
protocol.defaultRepresentationReportPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'LABEL_SET_REPRESENTATION_LEARNABILITY_M24.md');
protocol.representationAuditPath = ...
    protocol.defaultRepresentationAuditPath;
protocol.representationAuditSha256 = ...
    '88f8638afedd6cc23a3ac71299f96894f8054971662d5d654260741ceef4515b';
protocol.representationReportPath = ...
    protocol.defaultRepresentationReportPath;
protocol.representationReportSha256 = ...
    '58e9d8384010384d48a835b7f3fee7308a05d3b9f9e759d89e2b9de5095dd2cb';
protocol.representationLogPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'label_set_policy_m24_v1', 'representation_loso.log');
protocol.representationLogSha256 = ...
    '139e7e2c29be941ce23448831bc18339aaa18053f647d17a0aa5e7a2484f67f5';
protocol.representationAuditGenerationCommit = ...
    'a0f081e2c133701afb7189a2c02c290b38295e48';
protocol.observedAggregatePairwiseAccuracy = 0.625;
protocol.observedAggregateDifferenceSpearman = ...
    0.2063740856844305;
protocol.observedLabelSetPairwiseAccuracy = ...
    0.70833333333333337;
protocol.observedLabelSetDifferenceSpearman = ...
    0.46249095731854351;
protocol.observedPairwiseAccuracyImprovement = ...
    0.08333333333333337;
protocol.observedDifferenceSpearmanImprovement = ...
    0.25611687163411301;
protocol.observedPositivePerSeedSpearmanFraction = 1;
protocol.labelSetRepresentationAccepted = true;
protocol.messagePassingImplementationAuthorized = true;
protocol.messagePassingModelContractVersion = ...
    'label-set-two-round-message-passing-policy-m24-v1';
protocol.messagePassingRoundCount = 2;
protocol.messageNodePooling = ...
    'directed-incoming-outgoing-mean-max';
protocol.messageHiddenWidth = 16;
protocol.messagePassingOutput = ...
    'candidate-edge-by-residual-weight-task-score';
protocol.messageReadoutRidgeLambda = 1;
protocol.offlineTaskInitializationAuthorized = true;
protocol.messagePassingModelTrainingAuthorized = true;
protocol.defaultMessagePassingModelPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'models', ...
    'label_set_message_passing_policy_m24_init_v1.mat');
protocol.defaultMessagePassingTrainingReportPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'LABEL_SET_MESSAGE_PASSING_POLICY_M24_INIT_V1.md');
protocol.messagePassingInitializationPath = ...
    protocol.defaultMessagePassingModelPath;
protocol.messagePassingInitializationSha256 = ...
    '9d6732320e9f5f846e6dbd46f1e7711da372ffbc95c39a31bbe2174788cc6af4';
protocol.messagePassingInitializationReportPath = ...
    protocol.defaultMessagePassingTrainingReportPath;
protocol.messagePassingInitializationReportSha256 = ...
    '703463bdd1f8c51ff7df72aaa0bd6d51a129141440e1c34a75204472c129be83';
protocol.messagePassingInitializationLogPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'label_set_policy_m24_v1', 'message_passing_init.log');
protocol.messagePassingInitializationLogSha256 = ...
    'c9a6309b986b5be0bb3aeb84c69021087798387c8e50fc92f74050ff9ffa7ca9';
protocol.messagePassingInitializationGenerationCommit = ...
    '2db787c536903fd8727d5e289dd50565aa3f349d';
protocol.observedInitializationTrainingPreferenceAccuracy = ...
    0.81944444444444442;
protocol.observedInitializationTrainingDifferenceSpearman = ...
    0.73425769632666193;
protocol.observedInitializationTrainingMeanAbsoluteError = ...
    0.013949686224253367;
protocol.messagePassingInitializationRegistered = true;
protocol.safeProjectionSmokeAuthorized = true;
protocol.featuresUseTruth = false;
protocol.featuresUseFutureOutcome = false;
protocol.diagnosticTargetsUseTruth = true;
protocol.diagnosticTargetsUseFutureOutcome = false;
protocol.trainingOnlyDiagnostic = true;
protocol.labelSetShardGenerationAuthorized = true;
protocol.representationAuditAuthorized = true;
protocol.closedLoopPolicyTrainingAuthorized = false;
protocol.developmentEvaluationAuthorized = false;
protocol.heldoutM24Authorized = false;
protocol.x36PolicyRunAuthorized = false;
protocol.evidenceBoundary = [ ...
    'Per-label and aggregate graph inputs are deployment-observable ', ...
    'and exclude numeric label identifiers. Registered current-truth ', ...
    'edge advantages may be used only to reject an inadequate ', ...
    'representation on opened M24 training states. Passing this ', ...
    'diagnostic does not authorize policy claims: the policy must be ', ...
    'optimized and selected using paired closed-loop simulator return ', ...
    'while development M24, held-out M24 and X36 remain sealed.'];
end
