function protocol = getLineageIsolatedRelayV135Protocol()
% GETLINEAGEISOLATEDRELAYV135PROTOCOL Frozen causal mechanism screen.

v134 = getSetTrustSequenceV134Protocol();
protocol = v134;
protocol.id = 'lineage-isolated-relay-v135-v1';
protocol.contractVersion = 'v135-lineage-isolated-relay-protocol-v1';
protocol.methodName = 'lineage-isolated KLA relay with local admission';
protocol.outcomePolicyName = 'lineage-isolated-relay-v135-screen-v1';
protocol.runtimePayloadMode = ...
    'lineage-relay-full-working-abstention';
protocol.wireContract = struct( ...
    'messageCountRelativeToReference', 1, ...
    'auxiliaryPayloadAllowed', false, ...
    'senderState', 'causal-reference-relay', ...
    'workingStateTransmitted', false, ...
    'controlledEdgeWirePayload', 'full-mixture-aware-lmb-posterior', ...
    'controlledEdgeWorkingConsumption', 'binary-admission');
protocol.screen = struct( ...
    'm24ActionIndex', 25, ...
    'x36ActionIndex', 51, ...
    'x36ActionRule', 'all-ranked-formations-staggered-reentry', ...
    'minimumInterventionGainFraction', 0.05, ...
    'minimumFullWindowGainFraction', 0.00, ...
    'minimumMatureGainFraction', 0.00, ...
    'minimumSensorGainFraction', 0.00, ...
    'minimumFormationGainFraction', 0.00, ...
    'minimumRejoinedRelayMatchFraction', 1.00, ...
    'requireAttemptedBytesEqualReference', true, ...
    'requireBothScales', true);
protocol.reportingPolicy = struct( ...
    'failedCandidatesRepositoryOnly', true, ...
    'singleCaseBrightSpotsMainDocument', false, ...
    'mainDocumentRequiresJointAggregateGate', true, ...
    'stableMethodDesignMayBeReported', true);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v135', 'lineage_isolated_relay_v1');
protocol.validationClaimAllowed = false;
end
