function protocol = getMinimalRiskCycleV264Protocol()
% GETMINIMALRISKCYCLEV264PROTOCOL One-edge relaxation of V263.

source = getRiskRootedMultiSourceTreeV263Protocol();
backbone = getCausalMinimumFormationBackboneV242Protocol();
protocol = struct();
protocol.id = 'minimal-risk-cycle-v264-v1';
protocol.contractVersion = 'minimal-risk-cycle-v264-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v264-minimal-risk-cycle';
protocol.policyName = 'minimal-risk-cycle-v264-policy';
protocol.allowedPresets = source.allowedPresets;
protocol.allowedSeeds = source.allowedSeeds;
protocol.continuationStartTime = source.continuationStartTime;
protocol.continuationEndTime = source.continuationEndTime;
protocol.localizationEventWindow = source.localizationEventWindow;
protocol.localizationEventFormation = source.localizationEventFormation;
protocol.protectiveEdgeWeight = backbone.crossResidualWeight;
protocol.additionalUndirectedFormationEdges = 1;
protocol.additionalDirectedMessages = 2;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.receiverMode = source.receiverMode;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v264', 'minimal_risk_cycle', ...
    'm24_seed1301_t57_73');
protocol.minimumEventFormationRmseGainPercent = ...
    source.minimumEventFormationRmseGainPercent;
protocol.minimumEventFormationEospaGainPercent = ...
    source.minimumEventFormationEospaGainPercent;
protocol.maximumNetworkRegressionPercent = ...
    source.maximumNetworkRegressionPercent;
protocol.maximumFormationRegressionPercent = ...
    source.maximumFormationRegressionPercent;
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V264 is an outcome-opened M24 continuation mechanism screen. ', ...
    'It inherits the causal posterior-only V263 risk root and its ', ...
    'current-physical breadth-first tree, then restores exactly one ', ...
    'currently physical incumbent formation edge displaced by that ', ...
    'tree. The edge is selected only if the resulting unicyclic graph ', ...
    'does not increase any formation-pair hop distance relative to ', ...
    'either V242 or V263 and strictly repairs at least one V263 ', ...
    'dilation. The two restored directed gateway messages use the ', ...
    'existing V242 residual trust, so no new weight is tuned. Active ', ...
    'pages use N+2F posterior messages; inactive pages use the V242 ', ...
    'N+2(F-1) count. The controller remains centralized and its ', ...
    'synopsis cost is not included. The result is development-only and ', ...
    'cannot establish deployment cost, validation or generalization.'];

if protocol.protectiveEdgeWeight <= 0 || ...
        protocol.additionalUndirectedFormationEdges ~= 1 || ...
        protocol.additionalDirectedMessages ~= 2
    error('MinimalRiskCycleV264:InvalidProtocol', ...
        'The V264 edge or weight contract is invalid.');
end
end
