function protocol = getNetworkBudgetReallocatedMultiSourceV95Protocol()
% GETNETWORKBUDGETREALLOCATEDMULTISOURCEV95PROTOCOL Frozen matched baselines.

source = getBraidedHandoverOpportunityV84Protocol();
root = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v95', ...
    'network_budget_reallocated_multi_source');
caseTemplate = struct( ...
    'scaleName', '', ...
    'presetName', '', ...
    'seed', source.allSeeds, ...
    'currentTime', NaN, ...
    'expectedNodeCount', NaN, ...
    'expectedFormationCount', NaN, ...
    'requiredTokenCount', NaN, ...
    'requiredTargetFormationCount', NaN, ...
    'requiredSourceFormationCount', NaN, ...
    'expectedFormationDiameter', NaN, ...
    'horizonSteps', NaN, ...
    'cacheRoot', '');
cases = repmat(caseTemplate, 1, 2);
cases(1) = caseTemplate;
cases(1).scaleName = 'M24';
cases(1).presetName = source.presets{1};
cases(1).currentTime = 104;
cases(1).expectedNodeCount = 24;
cases(1).expectedFormationCount = 4;
cases(1).requiredTokenCount = 2;
cases(1).requiredTargetFormationCount = 2;
cases(1).requiredSourceFormationCount = 2;
cases(1).expectedFormationDiameter = 3;
cases(1).horizonSteps = 5;
cases(1).cacheRoot = fullfile(root, 'cache', 'm24');
cases(2) = caseTemplate;
cases(2).scaleName = 'X36';
cases(2).presetName = source.presets{2};
cases(2).currentTime = 112;
cases(2).expectedNodeCount = 36;
cases(2).expectedFormationCount = 6;
cases(2).requiredTokenCount = 3;
cases(2).requiredTargetFormationCount = 3;
cases(2).requiredSourceFormationCount = 3;
cases(2).expectedFormationDiameter = 5;
cases(2).horizonSteps = 7;
cases(2).cacheRoot = fullfile(root, 'cache', 'x36');

protocol = struct();
protocol.id = ...
    'network-budget-reallocated-multi-source-v95-v1';
protocol.contractVersion = ...
    'network-budget-reallocated-multi-source-v95-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.receiverMode = 'fov-aware-censored';
protocol.referenceMode = 'current-physical-tree';
protocol.baselineName = ...
    'matched-static-current-physical-tree-full-payload';
protocol.fixedRouteControlName = ...
    'same-selected-route-held-fixed-for-the-full-horizon';
protocol.donorOnlyControlName = ...
    'same-donors-removed-without-target-additions';
protocol.sourceWeight = 0.05;
protocol.dominantWeight = 0.70;
protocol.interventionDurationSteps = 1;
protocol.recoveryStepsBeyondFormationDiameter = 2;
protocol.minimumCandidateAssociationSupport = ...
    source.positiveSupportThreshold;
protocol.minimumSenderNoveltyFraction = ...
    source.minimumSenderNoveltyFraction;
protocol.minimumNetUtilityFraction = 0;
protocol.maximumSolverSeconds = 10;
protocol.cases = cases;
protocol.minimumMeanGainPercent = 5.0;
protocol.minimumWorstSensorGainPercent = 0.0;
protocol.minimumFormationGainPercent = 0.0;
protocol.minimumWindowConsensusGainPercent = 0.0;
protocol.minimumTerminalConsensusGainPercent = 0.0;
protocol.minimumAttemptedByteSavingPercent = 0.0;
protocol.minimumTransportGainOverDonorOnlyPercent = 0.0;
protocol.cacheRoot = fullfile(root, 'cache');
protocol.outputRoot = root;
protocol.structuralOutputRoot = fullfile(root, 'structural_gate');
protocol.headroomOutputRoot = fullfile(root, 'matched_static_headroom');
protocol.filterSeedOffset = 100000;
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.fullEpisodeTrackingAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V95 uses one already-opened braided-handover state per scale. ', ...
    'A residual 0.05 message token is moved from its registered donor ', ...
    'receiver to a physically reachable target receiver while keeping ', ...
    'the sender unchanged. The dominant 0.70 inputs never move. The ', ...
    'deployable candidate must preserve every sender message count and ', ...
    'the network message budget exactly. It is compared with the same ', ...
    'current physical-tree static route, a donor-only causal ablation, ', ...
    'and the same selected route held fixed for the full horizon. ', ...
    'Selection reads only current LMB posteriors, current association ', ...
    'support, current physical links, link probabilities and past ', ...
    'topology. Truth, future measurements, realized future links and ', ...
    'tracking outcomes are unavailable until all four arms are frozen. ', ...
    'These anchors are development evidence only.'];
end
