function protocol = getNetworkAdditiveFormationRiskV65Protocol()
% GETNETWORKADDITIVEFORMATIONRISKV65PROTOCOL Frozen observable selector.

v60 = getObservationSupportedRoutingLeverageV60Protocol();
v63 = getTrackingAlignedX36ScheduleHeadroomV63Protocol();
protocol = struct();
protocol.id = 'network-additive-formation-risk-v65-v1';
protocol.contractVersion = ...
    'network-additive-formation-risk-v65-protocol-v1';
protocol.positiveSupportThreshold = 0.20;
protocol.coverageTargetFraction = 0.80;
protocol.minimumNetworkRiskFraction = 0.01;
protocol.maximumUsefulLossToRescueRatio = 1.0;
protocol.requireZeroCrossSupportedDownwardCrossings = true;
protocol.horizonSteps = 3;
protocol.outcomePolicyName = ...
    'tracking-aligned-network-additive-formation-risk-v65';
protocol.m24Cases = v60.cases;
protocol.m24OpenedTrackingTargets = v60.openedTrackingTargets;
protocol.x36PresetName = v63.presetName;
protocol.x36Seed = v63.seed;
protocol.x36AnchorTimes = v63.anchorTimes;
protocol.x36CacheRoot = v63.cacheRoot;
protocol.x36OpenedTrackingTargets = [ ...
    targetEntry(v63.presetName, v63.seed, 72, 5.847429, ...
        'V64 persistent 80% coverage'), ...
    targetEntry(v63.presetName, v63.seed, 100, 9.329497, ...
        'V64 persistent 80% coverage')];
protocol.strongGainPercent = 5;
protocol.weakGainPercent = 2;
protocol.minimumMeanGainPercent = v63.minimumMeanGainPercent;
protocol.minimumWorstSensorGainPercent = ...
    v63.minimumWorstSensorGainPercent;
protocol.minimumFormationGainPercent = ...
    v63.minimumFormationGainPercent;
protocol.minimumWindowConsensusGainPercent = ...
    v63.minimumWindowConsensusGainPercent;
protocol.minimumTerminalConsensusGainPercent = ...
    v63.minimumTerminalConsensusGainPercent;
protocol.minimumAttemptedByteSavingPercent = ...
    v63.minimumAttemptedByteSavingPercent;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v65', 'network_additive_risk_attribution');
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V65 computes all observable features before joining already-opened ', ...
    'M24 and X36 development outcomes. The 1% network-risk budget, 80% ', ...
    'coverage target, unit useful-loss ratio, and zero cross-supported ', ...
    'downward-crossing guard are frozen before the X36 t=128 outcome is ', ...
    'opened. No held-out, model-training, or validation claim is ', ...
    'authorized.'];
end

function value = targetEntry( ...
        presetName, seed, currentTime, meanGainPercent, source)
value = struct( ...
    'presetName', presetName, ...
    'seed', seed, ...
    'currentTime', currentTime, ...
    'meanGainPercent', meanGainPercent, ...
    'source', source);
end
