function protocol = getObservationSupportedSetSafeV194Protocol()
% GETOBSERVATIONSUPPORTEDSETSAFEV194PROTOCOL Online set-level projection.

base = getOnlinePositiveNetAddressablePayloadV99Protocol();
protocol = base;
protocol.id = 'observation-supported-set-safe-v194-v1';
protocol.contractVersion = ...
    'observation-supported-set-safe-v194-protocol-v1';
protocol.outcomePolicyName = ...
    'observation-supported-set-safe-v194-v1';
protocol.executionProfile = ...
    'v194-observation-supported-set-safe';
protocol.baseProtocolId = base.id;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v194', 'observation_supported_set_safe');
protocol.releaseOnAnyUnsupportedEntry = true;
protocol.supportMode = 'receiver-only';
protocol.evidenceBoundary = [ ...
    'V194 first computes the current V99 positive-net omission proposal. ', ...
    'For each proposed receiver formation, it constructs the observable ', ...
    'counterfactual marginal LMB extraction and restores the ordinary full ', ...
    'posterior whenever any entering candidate label lacks current receiver ', ...
    'measurement-association support. The rule uses no formation or time ', ...
    'identifier, truth, future measurement or future outcome. The existing ', ...
    'message builder and byte ledger execute and charge the projected set. ', ...
    'Opened anchors remain development evidence only.'];
end
