function protocol = getOneShotPacketEpisodeV270Protocol()
% GETONESHOTPACKETEPISODEV270PROTOCOL One packet per risk episode.

source = getExistenceMarginBeneficiaryV269Protocol();
protocol = source;
protocol.id = 'one-shot-packet-episode-v270-v1';
protocol.contractVersion = ...
    'one-shot-packet-episode-v270-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v270-one-shot-packet-episode';
protocol.policyName = 'one-shot-packet-episode-v270-policy';
protocol.oneShotPerEpisodeEnabled = true;
protocol.resultContractVersion = ...
    'one-shot-packet-episode-v270-result-v1';
protocol.resultFileName = ...
    'ONE_SHOT_PACKET_EPISODE_V270_CONTINUATION.mat';
protocol.reportFileName = ...
    'ONE_SHOT_PACKET_EPISODE_V270_CONTINUATION.md';
protocol.reportTitle = 'V270 one-shot packet episode';
protocol.displayName = 'V270 one-shot packet episode';
protocol.passDecision = ...
    'run-one-full-causal-m24-arm-with-frozen-one-shot-packet-episodes';
protocol.failDecision = ...
    'close-source-preserving-spatial-packet-action-family';
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v270', ...
    'one_shot_packet_episode', 'm24_seed1301_t57_73');
protocol.evidenceBoundary = [ ...
    'V270 is an outcome-opened M24 continuation causal ablation. It keeps ', ...
    'the V269 existence-margin beneficiary and every V268 packet/fusion ', ...
    'semantic, but admits at most one successfully stored packet during a ', ...
    'continuous target-formation/label risk episode. A failed first hop ', ...
    'does not consume the episode; the latch resets only when the policy ', ...
    'becomes inactive or the target-formation/label key changes. The ', ...
    'controller uses no truth, realized future delivery or future ', ...
    'outcome. Both physical hops remain charged and centralized synopsis ', ...
    'cost remains excluded, so the result is mechanism evidence only.'];
end
