function protocol = getOnlinePositiveNetAddressablePayloadV99Protocol()
% GETONLINEPOSITIVENETADDRESSABLEPAYLOADV99PROTOCOL Causal online selector.

source = getPositiveNetAddressablePayloadV97Protocol();
protocol = source;
protocol.id = 'online-positive-net-addressable-payload-v99-v1';
protocol.contractVersion = ...
    'online-positive-net-addressable-payload-v99-protocol-v1';
protocol.outcomePolicyName = ...
    'online-positive-net-addressable-payload-v99-v1';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v99', 'online_positive_net_addressable_payload');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.evidenceBoundary = [ ...
    'V99 keeps the matched static carrier graph and fusion weights, but ', ...
    'recomputes the threshold-free safe positive-net receiver-formation ', ...
    'set after every local update. Each decision uses the current ', ...
    'pre-fusion posterior, current geometry and past selected graphs ', ...
    'only; no truth, future measurements or future outcomes enter the ', ...
    'selector. The static, fixed-V97 and online-V99 arms share the same ', ...
    'cached posterior, measurements, link uniforms, filter RNG, horizon ', ...
    'and communication constraints. Opened anchors remain development ', ...
    'evidence only.'];
end
