function protocol = getOnlinePositiveNetFormationReleaseV191Protocol()
% GETONLINEPOSITIVENETFORMATIONRELEASEV191PROTOCOL Teacher-only release.

base = getOnlinePositiveNetAddressablePayloadV99Protocol();
protocol = struct();
protocol.id = 'online-positive-net-formation-release-v191-v1';
protocol.contractVersion = ...
    'online-positive-net-formation-release-v191-protocol-v1';
protocol.baseProtocolId = base.id;
protocol.horizonSteps = base.horizonSteps;
protocol.maximumReleaseFormationsPerPage = 1;
protocol.evidenceBoundary = [ ...
    'V191 is an opened recursive teacher that removes a named formation ', ...
    'from the current V99 withheld-payload set on registered pages.  The ', ...
    'ordinary full posterior and its ordinary byte accounting are thereby ', ...
    'restored; topology, fusion weights, measurements, links and filter RNG ', ...
    'remain paired.  The release identifiers are teacher inputs, so V191 ', ...
    'cannot support deployable or cross-scene claims.'];
end
