function protocol = getOutwardReferenceCarrierV125Protocol()
% GETOUTWARDREFERENCECARRIERV125PROTOCOL Separate local and relay states.

base = getF6ReferenceRowCompositionV124Protocol();
protocol = base;
protocol.id = 'outward-reference-carrier-v125-v1';
protocol.contractVersion = ...
    'outward-reference-carrier-v125-protocol-v1';
protocol.outcomePolicyName = 'outward-reference-carrier-v125-v1';
protocol.executionProfile = 'v125-outward-reference-carrier';
protocol.bankVariant = 'outward-reference-carrier-v125';
protocol.pageActionNames = arrayfun( ...
    @(page) sprintf('v125-reference-carrier-page-%d-h8', page), ...
    1:protocol.horizonSteps, 'UniformOutput', false);
protocol.candidateSequenceName = ...
    'v125-outward-reference-carrier-h8';
protocol.carrierTimes = 72:(72 + protocol.horizonSteps - 1);
protocol.carrierSenderSensorId = 27;
protocol.carrierReceiverSensorId = 32;
protocol.referenceCarrierSourceActionName = ...
    protocol.clockwiseFullActionName;
protocol.referenceCarrierSourceContractVersion = ...
    'v125-paired-clockwise-local-posterior-capture-v1';
protocol.resultContractVersion = ...
    'outward-reference-carrier-v125-x36-t72-result-v1';
protocol.resultFileStem = ...
    'OUTWARD_REFERENCE_CARRIER_V125_X36_T72_RESULT';
protocol.reportTitle = ...
    'V125 outward reference carrier: X36 t72 H=8';
protocol.runLabel = 'V125 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v125', 'outward_reference_carrier');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.referenceCarrierCaptureDirectory = fullfile( ...
    protocol.outputRoot, 'x36_t72_h8', ...
    'reference_carrier_capture');
protocol.referenceCarrierCaptureScreenPath = fullfile( ...
    protocol.referenceCarrierCaptureDirectory, ...
    ['TRACKING_ALIGNED_X36_SCHEDULE_H8_', ...
     'X36_FORMATION_FOV_SEED211_T72_D8.mat']);
protocol.evidenceBoundary = [ ...
    'V125 is a privileged paired X36 seed-211 t=72 H=8 causal ', ...
    'upper bound. It preserves every V124 graph row, fusion weight and ', ...
    'receiver-side payload decision. Only the posterior transmitted on ', ...
    'the persistent sensor-27-to-sensor-32 F5-to-F6 edge is replaced, ', ...
    'page by page, by the same sender posterior captured from the paired ', ...
    'clockwise full-payload arm. F5 therefore keeps the V124 protected ', ...
    'local state while F6 receives the counterfactual static-carrier ', ...
    'state. This requires an alternative-arm shadow trajectory and is ', ...
    'not deployable; it only tests whether downstream state propagation ', ...
    'is the remaining performance bottleneck. Measurements, delivery ', ...
    'uniforms, filter RNG, topology, weights and byte accounting remain ', ...
    'paired. No validation or generalization claim is authorized.'];
end
