function protocol = getOrdinalFullInformationLearnabilityProtocol()
% GETORDINALFULLINFORMATIONLEARNABILITYPROTOCOL Frozen LOSO preflight.

predecessor = getIidClusterRewardActionAlignmentProtocol();
if ~predecessor.iidClusterActionAlignmentRejected || ...
        ~predecessor. ...
            ordinalFullInformationLearnabilityAuditAuthorized
    error('Ordinal full-information learnability is not authorized.');
end

protocol = struct();
protocol.id = ...
    'iid-cluster-ordinal-full-information-learnability-m24-v1';
protocol.predecessorProtocolId = predecessor.id;
protocol.graphDatasetProtocolId = ...
    predecessor.graphDatasetProtocolId;
protocol.sourceAnalysisPath = ...
    predecessor.evidenceAnalysisPath;
protocol.sourceAnalysisSha256 = ...
    predecessor.evidenceAnalysisSha256;
protocol.sourceAnalysisGenerationCommit = ...
    predecessor.evidenceGenerationCommit;
protocol.trainingSeeds = predecessor.trainingSeeds;
protocol.snapshotTimes = predecessor.snapshotTimes;
protocol.scoreType = predecessor.scoreType;
protocol.featureVariants = { ...
    'edge-only', 'edge-receiver-sender-difference'};
protocol.ridgeLambdaGrid = [1e-2, 1e-1, 1, 10, 100];
protocol.outerEvaluationMode = ...
    'whole-seed-leave-one-out';
protocol.innerSelectionMode = ...
    'whole-seed-leave-one-out-surrogate-only';
protocol.innerSelectionPrimaryMetric = ...
    'surrogate-pairwise-preference-accuracy';
protocol.innerSelectionSecondaryMetric = ...
    'surrogate-score-difference-spearman';
protocol.innerTieBreak = ...
    'feature-variant-order-then-lambda-order';
protocol.modelTarget = ...
    'canonical-pair-iid-cluster-score-difference';
protocol.modelSelectionUsesTaskTruth = false;
protocol.modelTrainingUsesTaskTruth = false;
protocol.secondaryTaskAuditUsesTruth = true;
protocol.minimumOuterSurrogatePairwiseAccuracy = 0.60;
protocol.minimumOuterSurrogateDifferenceSpearman = 0.25;
protocol.minimumPositivePerSeedSurrogateSpearmanFraction = 4 / 6;
protocol.minimumOuterTaskPreferenceAccuracy = 0.55;
protocol.minimumOuterMeanSelectedTaskAdvantage = 0;
protocol.expectedPairCount = ...
    numel(protocol.trainingSeeds) * ...
    numel(protocol.snapshotTimes) * 4;
protocol.trainingOnlyDiagnostic = true;
protocol.developmentSeedsOpened = [];
protocol.heldoutSeedsOpened = [];
protocol.evidenceRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'ordinal_full_information_learnability_m24_v1');
protocol.evidenceAuditPath = fullfile( ...
    protocol.evidenceRoot, ...
    'ordinal_full_information_learnability_m24.mat');
protocol.evidenceAuditSha256 = ...
    'd9086371c2c6c8ad950aa4432cddc292605884594a3b9ce4488b5916706cd527';
protocol.evidenceReportPath = fullfile( ...
    protocol.evidenceRoot, ...
    'ORDINAL_FULL_INFORMATION_LEARNABILITY_M24.md');
protocol.evidenceReportSha256 = ...
    '6ab9b3a1a04b272cbe9b191b77819b8012251c3c02ba767e14314febcaaca992';
protocol.evidenceLogPath = fullfile( ...
    protocol.evidenceRoot, ...
    'ordinal_full_information_learnability_m24.log');
protocol.evidenceLogSha256 = ...
    'aeae6f9b4be504cf3e8f2ddca8a79792656e80d749711f41ac8e966badd7b58d';
protocol.evidenceGenerationCommit = ...
    '25579cd448425b825296432745cdd513106092f6';
protocol.observedOuterSurrogatePairwiseAccuracy = ...
    0.50694444444444442;
protocol.observedOuterSurrogateDifferenceSpearman = ...
    0.047869946145808216;
protocol.observedPositivePerSeedSurrogateSpearmanFraction = ...
    0.33333333333333331;
protocol.observedOuterTaskPreferenceAccuracy = ...
    0.57638888888888884;
protocol.observedOuterTaskDifferenceSpearman = ...
    0.12221284462663773;
protocol.observedOuterMeanSelectedTaskAdvantage = ...
    0.065165212268022438;
protocol.routeDecisionPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'OBSERVABLE_REWARD_ROUTE_REJECTION_M24.md');
protocol.routeDecisionSha256 = ...
    '41f008d14966aa34ffd0107fef43880d157d5d8823884e4400051ca34c791a1a';
protocol.ordinalLearnabilityRejected = true;
protocol.labelSetSimulatorPolicyDesignAuthorized = true;
protocol.expandedRewardDatasetAuthorized = false;
protocol.banditImplementationAuthorized = false;
protocol.developmentEvaluationAuthorized = false;
protocol.heldoutM24Authorized = false;
protocol.x36PolicyRunAuthorized = false;
protocol.defaultOutputPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'ordinal_full_information_learnability_m24.mat');
protocol.defaultReportPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', ...
    'ORDINAL_FULL_INFORMATION_LEARNABILITY_M24.md');
end
