function protocol = getProtectionEarlyReleaseOracleV107Protocol()
% GETPROTECTIONEARLYRELEASEORACLEV107PROTOCOL Release one page earlier.

base = getProtectionOnlyH8V105Protocol();
protocol = base;
protocol.id = 'protection-early-release-oracle-v107-v1';
protocol.contractVersion = ...
    'protection-early-release-oracle-v107-protocol-v1';
protocol.outcomePolicyName = ...
    'protection-early-release-oracle-v107-v1';
protocol.executionProfile = 'v107-protection-early-release-oracle';
protocol.bankVariant = 'protection-early-release-oracle-v107';
protocol.candidateActionName = ...
    'v107-protection-early-release-oracle-h8';
protocol.resultContractVersion = ...
    'protection-early-release-oracle-v107-x36-t72-result-v1';
protocol.resultFileStem = ...
    'PROTECTION_EARLY_RELEASE_ORACLE_V107_X36_T72_RESULT';
protocol.reportTitle = ...
    'V107 early protection-release oracle: X36 t72 H=8';
protocol.armDisplayName = 'V107 early-release oracle';
protocol.runLabel = 'V107 X36-t72 H=8';
protocol.releaseFormationIdsByTime = { ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    1, ...
    [1, 6], ...
    [1, 6], ...
    [1, 6]};
protocol.protectionFormationIdsByTime = cellfun( ...
    @(protected, released) setdiff(protected, released, 'stable'), ...
    base.protectionFormationIdsByTime, ...
    protocol.releaseFormationIdsByTime, ...
    'UniformOutput', false);
protocol.minimumFormationGainPercent = 0;
protocol.minimumTargetPeerTerminalGainPercent = 0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v107', 'protection_early_release_oracle');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.evidenceBoundary = [ ...
    'V107 is a frozen retrospective one-page-early release oracle. It ', ...
    'starts from V105 but releases F1 at t=76 and F6 at t=77, one page ', ...
    'before the opened V105 formation or peer outcomes first reverse ', ...
    'sign. Truth and opened V105 outcomes define these pages, so V107 is ', ...
    'not deployable and cannot support validation or generalization ', ...
    'claims. Every topology adjacency and fusion-weight row remains the ', ...
    'matched static fixed-counter-clockwise route and no handoff occurs. ', ...
    'The frozen H=8 static outcome is reused only after preset, seed, ', ...
    'receiver mode, horizon, cache path and cache SHA-256 match. V107 ', ...
    'distinguishes a late reactive release from a structural failure of ', ...
    'binary formation-level full/control-only switching.'];
end
