function protocol = getPredictiveRewardAlignmentProtocol()
% GETPREDICTIVEREWARDALIGNMENTPROTOCOL Frozen training-only M24 score gate.

headroom = getBackboneResidualCvarTailGuardAdaptiveTrustProtocol();
protocol = struct();
protocol.id = ...
    'predictive-reward-alignment-m24-seed7-h3-v1';
protocol.headroomProtocolId = headroom.id;
protocol.presetName = headroom.presetName;
protocol.seed = headroom.seed;
protocol.continuationStartTime = ...
    headroom.continuationStartTime;
protocol.continuationEndTime = ...
    headroom.continuationEndTime;
protocol.actionTimes = ...
    protocol.continuationStartTime: ...
    (protocol.continuationEndTime - 1);
protocol.rewardTimes = protocol.actionTimes + 1;
protocol.feedbackDelay = 1;
protocol.scoreType = ...
    'poisson-measurement-intensity-log-score';
protocol.scoreTruthUsed = false;
protocol.scoreExactLmbMeasurementSetLikelihood = false;
protocol.scoreInterpretation = [ ...
    'proper-log-score-for-the-poisson-measurement-intensity-', ...
    'approximation'];
protocol.armModes = { ...
    'backbone-residual-static-a70-e05', ...
    'backbone-residual-analytic-a70-e05', ...
    headroom.armName};
protocol.referenceArmModes = protocol.armModes(1:2);
protocol.privilegedHeadroomArmMode = protocol.armModes{3};
protocol.filterSeedOffset = 100000;
protocol.rollingSafeBackboneMode = 'fixed-balanced-cycle';
protocol.maximumAttemptedByteDeviationFraction = ...
    headroom.maximumAttemptedByteDeviationFraction;
protocol.minimumArmRankSpearman = 0.50;
protocol.minimumPairedSensorTimeSpearman = 0.20;
protocol.minimumTeacherScoreAdvantage = 0;
protocol.affectedPairTolerance = 1e-12;
protocol.minimumAffectedPairCountPerReference = 6;
protocol.trainingOnlyDiagnostic = true;
protocol.developmentSeedsOpened = [];
protocol.heldoutSeedsOpened = [];
protocol.developmentEvaluationAuthorized = false;
protocol.heldoutM24Authorized = false;
protocol.x36PolicyRunAuthorized = false;
protocol.banditImplementationAuthorized = false;
protocol.alignmentEvidenceRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'predictive_reward_alignment_m24_seed7_h3_v1');
protocol.alignmentAuditPath = fullfile( ...
    protocol.alignmentEvidenceRoot, ...
    'predictive_reward_alignment_audit_m24_seed7_h3_v1.mat');
protocol.alignmentAuditSha256 = ...
    'eeae62570a78a17d6108a91ef27248889295394ada7bb8761a7470eee59bbc6e';
protocol.alignmentReportPath = fullfile( ...
    protocol.alignmentEvidenceRoot, ...
    'PREDICTIVE_REWARD_ALIGNMENT_AUDIT_M24_SEED7_H3_V1.md');
protocol.alignmentReportSha256 = ...
    'e6c9204240d8f000e8fdac9a6c588f75dad5963d74611fd76c96530ec95a062e';
protocol.alignmentSourceGenerationCommit = ...
    'adc35c4c850c2baeb2a197a75b1728a274379da8';
protocol.alignmentAuditGenerationCommit = ...
    '949c441132c3046dea4cadb9f7271b6ee25ae569';
protocol.observedTeacherScoreAdvantage = ...
    -0.0189224919963635;
protocol.observedArmRankSpearman = -0.5;
protocol.observedMinimumAffectedPairSpearman = ...
    -0.371428571428571;
protocol.observedMinimumAffectedPairCount = 14;
protocol.observedMaximumAttemptedByteDeviationFraction = ...
    0.00104828670641420;
protocol.alignmentPreflightRejected = true;
protocol.actionLevelPredictiveRewardAuditAuthorized = true;
end
