function protocol = getPredictiveSoftReturnRecoveryV81Protocol()
% GETPREDICTIVESOFTRETURNRECOVERYV81PROTOCOL Frozen shared action bank.

v80 = getReliabilityBalancedHomotopyV80Protocol();
protocol = struct();
protocol.id = 'predictive-soft-return-recovery-v81-v1';
protocol.contractVersion = ...
    'predictive-soft-return-recovery-v81-protocol-v1';
protocol.baseProtocolId = v80.id;
protocol.cases = v80.cases;
protocol.cacheRoot = v80.cacheRoot;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v81', 'predictive_soft_return_recovery');
protocol.fusionConfig = v80.fusionConfig;
protocol.expectedDeliveryWeighting = true;
protocol.totalFusionRounds = 3;
protocol.candidateRounds = 1;
protocol.predictiveRecoveryRounds = 2;
protocol.covarianceRegularization = ...
    v80.covarianceRegularization;
protocol.recoveryCandidateRieLimit = ...
    v80.recoveryCandidateRieLimit;
protocol.globalBalancingAlphas = [0.02, 0.05, 0.10];
protocol.localSoftReturnBetas = [0.10, 0.25, 0.50, 0.75];
protocol.referenceActionName = 'R';
protocol.actionSelectionOrder = { ...
    'minimum-next-round-centered-energy', ...
    'minimum-intervention-magnitude', ...
    'deterministic-action-index'};
protocol.requireSameActionBankAcrossScales = true;
protocol.requireExactReferenceTopology = true;
protocol.requireExactMessageCountParity = true;
protocol.requireMonotoneCenteredEnergy = true;
protocol.commonModeConstrained = false;
protocol.sinkhornTolerance = v80.sinkhornTolerance;
protocol.sinkhornMaximumIterations = ...
    v80.sinkhornMaximumIterations;
protocol.effectiveWeightTolerance = ...
    v80.effectiveWeightTolerance;
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V81 keeps the V75-safe first-round pulse and uses one frozen ', ...
    'recovery action bank on M24 and X36. The bank contains ordinary ', ...
    'reference recovery, three small reliability-balanced global ', ...
    'weight corrections retained from V80, and four intervention-local ', ...
    'soft returns. A soft return changes only the receiver rows touched ', ...
    'by the pulse: the incumbent residual input is restored with ', ...
    'fractional trust and the unused weight returns to self. Every ', ...
    'action keeps the reference senders, physical support, and directed-', ...
    'message count. At each of two recovery rounds, formal mixture-aware ', ...
    'virtual KLA evaluates all actions from the current virtual posterior ', ...
    'against the causal parallel reference arm and chooses minimum next-', ...
    'round centered energy. No truth, prediction, new measurement, ', ...
    'future link, packet draw, route execution, tracking outcome, or ', ...
    'model training is used.'];
end
