function protocol = getPositiveValueReferenceLabelV157Protocol()
% GETPOSITIVEVALUEREFERENCELABELV157PROTOCOL Truth-valued label oracle.

base = getSparseReferenceLabelRollbackV156Protocol(4);
protocol = base;
protocol.id = 'positive-value-reference-label-v157-v1';
protocol.contractVersion = ...
    'positive-value-reference-label-v157-protocol-v1';
protocol.outcomePolicyName = 'positive-value-reference-label-v157-v1';
protocol.executionProfile = 'v157-positive-value-reference-label';
protocol.bankVariant = 'positive-value-reference-label-v157';
protocol.candidateActionName = 'v157-positive-value-reference-label-k4';
protocol.maximumLabelEdits = 4;
protocol.additionalPosteriorPayloadMessages = 36;
protocol.additionalPosteriorPayloadBytes = 198144;
protocol.auxiliaryMaintenanceCostAccounted = true;
protocol.resultContractVersion = ...
    'positive-value-reference-label-v157-x36-t72-result-v1';
protocol.resultFileStem = ...
    'POSITIVE_VALUE_REFERENCE_LABEL_V157_X36_T72_RESULT';
protocol.reportTitle = ...
    'V157 positive-value reference labels: X36 t72 H=8';
protocol.armDisplayName = 'V157 positive-value reference labels';
protocol.runLabel = 'V157 X36-t72 H=8';
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v157', 'positive_value_reference_label');
protocol.headroomOutputRoot = protocol.outputRoot;
protocol.evidenceBoundary = [ ...
    'V157 is a privileged paired X36 seed-211 t=72 H=8 label-value ', ...
    'mechanism oracle. It retains the V105 carrier, fusion weights and ', ...
    'protection schedule. At the 36 frozen V126 rollback cells it greedily ', ...
    'tests complete GM Bernoulli reference-label edits against exact ', ...
    'current-step truth E-OSPA, accepts only strictly positive marginal ', ...
    'edits, and stops after at most four labels. The reference state, ', ...
    'rollback cells and truth-valued selection are privileged, so V157 is ', ...
    'not deployable and cannot support validation or generalization ', ...
    'claims. Communication is conservatively charged 198144 bytes, equal ', ...
    'to four maximum-size labels plus one header at every rollback cell.'];
end
