function protocol = getPositiveNetAddressablePayloadV97Protocol()
% GETPOSITIVENETADDRESSABLEPAYLOADV97PROTOCOL Threshold-free spatial gate.

source = getAddressableRiskAdaptivePayloadV96Protocol();
protocol = struct();
protocol.id = 'positive-net-addressable-payload-v97-v1';
protocol.contractVersion = ...
    'positive-net-addressable-payload-v97-protocol-v1';
protocol.receiverMode = source.receiverMode;
protocol.horizonSteps = source.horizonSteps;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.positiveSupportThreshold = source.positiveSupportThreshold;
protocol.netBenefitTolerance = 1e-12;
protocol.requireZeroCrossSupportedDownwardCrossings = true;
protocol.minimumMeanGainPercent = source.minimumMeanGainPercent;
protocol.minimumWorstSensorGainPercent = ...
    source.minimumWorstSensorGainPercent;
protocol.minimumFormationGainPercent = ...
    source.minimumFormationGainPercent;
protocol.minimumWindowConsensusGainPercent = ...
    source.minimumWindowConsensusGainPercent;
protocol.minimumTerminalConsensusGainPercent = ...
    source.minimumTerminalConsensusGainPercent;
protocol.minimumAttemptedByteSavingPercent = ...
    source.minimumAttemptedByteSavingPercent;
protocol.referencePolicyName = source.referencePolicyName;
protocol.outcomePolicyName = ...
    'positive-net-addressable-payload-v97-v1';
protocol.baselineName = source.baselineName;
protocol.cases = source.cases;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v97', 'positive_net_addressable_payload');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.fullEpisodeTrackingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V97 selects every currently addressable receiver formation whose ', ...
    'observable rescue mass strictly exceeds its cross-supported useful-', ...
    'loss mass. Addressability requires an available action and zero ', ...
    'cross-supported downward decision crossings. This is the exact ', ...
    'positive-net set under the additive current-state surrogate and ', ...
    'uses no tuned coverage target or fixed formation count. V96, V97 ', ...
    'and reference arms share the same static carrier graph, cached ', ...
    'posterior, measurements, link uniforms, filter RNG, horizon and ', ...
    'communication constraints. These opened anchors are development ', ...
    'evidence only.'];
end
