function protocol = getProtectionReleaseOracleV106Protocol()
% GETPROTECTIONRELEASEORACLEV106PROTOCOL Release before observed reversals.

source = getProtectionOnlyH8V105Protocol();
protocol = source;
protocol.id = 'protection-release-oracle-v106-v1';
protocol.contractVersion = 'protection-release-oracle-v106-protocol-v1';
protocol.outcomePolicyName = 'protection-release-oracle-v106-v1';
protocol.releaseFormationIdsByTime = { ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    zeros(1, 0), ...
    1, ...
    [1, 6], ...
    [1, 6]};
protocol.protectionFormationIdsByTime = cellfun( ...
    @(protected, released) setdiff(protected, released, 'stable'), ...
    source.protectionFormationIdsByTime, ...
    protocol.releaseFormationIdsByTime, ...
    'UniformOutput', false);
protocol.minimumFormationGainPercent = 0;
protocol.minimumTargetPeerTerminalGainPercent = 0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v106', 'protection_release_oracle');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.evidenceBoundary = [ ...
    'V106 is a frozen retrospective protection-release headroom oracle. ', ...
    'It starts from the exact V105 control-only protection schedule and ', ...
    'releases F1 at t=77 and F6 at t=78, immediately before their opened ', ...
    'V105 formation or peer outcomes reverse sign. Truth and opened V105 ', ...
    'outcomes therefore define the release pages; V106 is not deployable ', ...
    'and cannot support validation or generalization claims. Every ', ...
    'topology adjacency and fusion-weight row stays equal to the matched ', ...
    'static fixed-counter-clockwise route, and no gateway handoff occurs. ', ...
    'The frozen H=8 static outcome is reused only after preset, seed, ', ...
    'receiver mode, horizon, cache path and cache SHA-256 match. Cached ', ...
    'inputs, measurements, delivery uniforms, filter RNG and the ', ...
    'communication model are unchanged. V106 tests whether timely release ', ...
    'has enough strict headroom to justify a later causal debt controller.'];
end
