function protocol = getPostFusionLabelReadoutV138Protocol()
% GETPOSTFUSIONLABELREADOUTV138PROTOCOL Evidence-conditioned output gate.

v136 = getFormationIsolatedDualPayloadV136Protocol();
protocol = v136;
protocol.id = 'post-fusion-label-readout-v138-v1';
protocol.contractVersion = ...
    'v138-post-fusion-label-readout-protocol-v1';
protocol.methodName = ...
    'evidence-conditioned post-fusion label readout over shadow W/R';
protocol.outcomePolicyName = ...
    'post-fusion-label-readout-v138-screen-v1';
protocol.labelReadout = struct( ...
    'evidenceRule', 'positive-or-credible-negative-local-update-v1', ...
    'comparison', ...
        'local-to-candidate-bernoulli-gm-kld-cubature', ...
    'selectionMargin', 0, ...
    'tieBreak', 'working', ...
    'workingStateMutationAllowed', false, ...
    'relayStateMutationAllowed', false, ...
    'truthUsed', false, ...
    'futureMeasurementUsed', false, ...
    'evidenceOptions', struct( ...
        'positiveAssociationMass', 0.20, ...
        'credibleOpportunity', 0.50, ...
        'unsupportedOpportunity', 0.10, ...
        'minimumAbsoluteExistenceDecrease', 0.01, ...
        'minimumRelativeExistenceDecrease', 0.05));
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v138', 'post_fusion_label_readout_v1');
end
