function protocol = getReferenceAnchoredBurstRoleScheduleV144Protocol()
% GETREFERENCEANCHOREDBURSTROLESCHEDULEV144PROTOCOL Frozen R-W-W-W carrier.

protocol = getRoleMultiplexedSinglePayloadV143Protocol();
protocol.id = 'reference-anchored-burst-role-schedule-v144-v1';
protocol.contractVersion = ...
    'v144-reference-anchored-burst-role-schedule-protocol-v1';
protocol.methodName = ...
    'reference-anchored burst single-payload W/R routing';
protocol.outcomePolicyName = ...
    'reference-anchored-burst-role-schedule-v144-screen-v1';
protocol.roleSchedule.periodPages = 4;
protocol.roleSchedule.referencePhaseOffset = 0;
protocol.roleSchedule.firstPhase = 'reference';
protocol.roleSchedule.maximumReferenceAgePages = 3;
protocol.roleSchedule.workingPageFraction = 3 / 4;
protocol.finiteTimeMixingPreflight = struct( ...
    'metric', 'maximum-row-total-variation-and-dobrushin', ...
    'maximumTerminalRowTotalVariation', 0.025, ...
    'm24StaticDobrushin', 0.367078585033, ...
    'm24CandidateDobrushin', 0.382646981473, ...
    'm24TerminalMaximumRowTotalVariation', 0.024098198644, ...
    'x36StaticDobrushin', 0.515065290200, ...
    'x36CandidateDobrushin', 0.521469514579, ...
    'x36TerminalMaximumRowTotalVariation', 0.024492270361, ...
    'nextLongerBurstRejected', true, ...
    'preOutcomeFreezeTime', '2026-08-29 00:19 CST');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v144', ...
    'reference_anchored_burst_role_schedule_v1');
end

