function protocol = getRollingSafeStructuredProposalProtocol()
% GETROLLINGSAFESTRUCTUREDPROPOSALPROTOCOL Nine-seed M24 v2 contract.
%
% The v2 dataset extends the frozen six-seed artifact with all remaining
% design seeds. Future M24 validation seeds and every X36 seed are excluded.
% The model ranks complete safe graphs with a set-level softmax objective.

base = getRollingSafeProposalDistillationProtocol();
rollout = getRollingSafeRolloutProtocol();
protocol = struct();
protocol.id = ...
    'm24-rolling-safe-structured-proposal-v2';
protocol.datasetContractVersion = ...
    'rolling-safe-structured-proposal-distillation-m24-v2';
protocol.datasetVariant = ...
    'proposal-distillation-state-v1';
protocol.presetName = base.presetName;
protocol.baseDatasetPath = base.datasetPath;
protocol.baseDatasetSha256 = base.datasetSha256;
protocol.baseDatasetGenerationCommit = ...
    base.datasetGenerationCommit;
protocol.baseDatasetSeeds = base.datasetSeeds;
protocol.extensionSeeds = [27, 31, 37];
protocol.datasetSeeds = rollout.designSeeds;
protocol.continuationStartTime = base.continuationStartTime;
protocol.continuationEndTime = base.continuationEndTime;
protocol.snapshotTimes = base.snapshotTimes;
protocol.behaviorActionCode = base.behaviorActionCode;
protocol.actionCodeSequences = ...
    protocol.behaviorActionCode * ones( ...
        numel(protocol.datasetSeeds), ...
        numel(protocol.snapshotTimes));
protocol.sourceWeight = base.sourceWeight;
protocol.payloadToleranceFraction = ...
    base.payloadToleranceFraction;
protocol.filterSeedOffset = base.filterSeedOffset;
protocol.featureContextMode = 'raw';
protocol.behaviorCacheSha256 = { ...
    'a33665ae7709a2bbfd2bb7c0ad79f51613d6eb2534f9c7919fdd95f70b323055', ...
    'c0b67093bc055d23a920f2bf695108e74084acf7068e6ad19093645674c3fdef', ...
    '5e6649a27b42cefbac5e2f4cb88c0c0eed2fc81f84a21902dddf6d028be7a605', ...
    '0624fee8f6ebb5c6104c3b7889ebbe4c71100c8a09c6756824197f770958d963', ...
    '0508cbc0b4ec2647fa66e1ab227da5574a62f4463f064e098e0db8d6d2239f0b', ...
    'dcb48762473fcb39497aee3a038b176035005f1c25d2f853137e5443c65d6939', ...
    '16a9f2bd7838943da714523dd1a3a3caf26b1f121f62bf8f1beb412ab505878e', ...
    '36ea8a105b411b8b7d0c63fd9b41faf0a4e70e5e37e5e5ecee5695ca4962bff1', ...
    'ffc69313f7fbe4bbcb53933841adefe68c35db5f96654e84f963f038b1a61b81'};
protocol.behaviorCacheSetSha256 = computeTextSha256( ...
    strjoin(protocol.behaviorCacheSha256, char(31)));
protocol.expectedBlockCount = ...
    numel(protocol.datasetSeeds) * ...
        numel(protocol.snapshotTimes);
protocol.expectedExtensionBlockCount = ...
    numel(protocol.extensionSeeds) * ...
        numel(protocol.snapshotTimes);
protocol.privilegedTargetActionCodes = ...
    base.privilegedTargetActionCodes;
protocol.minimumTargetsPerBlock = ...
    base.minimumTargetsPerBlock;
protocol.maximumTargetsPerBlock = ...
    base.maximumTargetsPerBlock;
protocol.behaviorTruthUsed = false;
protocol.behaviorFutureOutcomeUsed = false;
protocol.featureTruthUsed = false;
protocol.featureFutureOutcomeUsed = false;
protocol.targetTruthUsed = true;
protocol.targetFutureOutcomeUsed = false;
protocol.deployable = false;
protocol.developmentOnly = true;
protocol.validationClaimAllowed = false;
protocol.defaultDatasetName = ...
    'rolling_safe_structured_proposal_m24_hard_t75_t83_v2.mat';
protocol.defaultReportName = ...
    'ROLLING_SAFE_STRUCTURED_PROPOSAL_M24_HARD_T75_T83_V2.md';
protocol.datasetPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'datasets', ...
    protocol.defaultDatasetName);
protocol.reportPath = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'datasets', ...
    protocol.defaultReportName);

% Result-blind structured-model gate.
protocol.modelContractVersion = ...
    'rolling-safe-set-softmax-proposal-model-m24-v1';
protocol.modelFeatureMode = 'relative-only';
protocol.modelHeadCount = 4;
protocol.permutationInvariantTargetAssignment = true;
protocol.modelLoss = 'multi-positive-set-softmax';
protocol.negativeScoreDirectionCount = 24;
protocol.negativeScoreDirectionSeed = 2607;
protocol.hiddenWidthGrid = [16, 32];
protocol.lambdaGrid = [1e-4, 1e-2];
protocol.epochCount = 200;
protocol.learningRate = 0.01;
protocol.initializationSeed = 2907;
protocol.maximumBannedSelectedEdges = 1;
protocol.topK = 16;
protocol.minimumStateCaptureFraction = 0.80;
protocol.minimumSeedCaptureFraction = 2 / 3;
protocol.minimumLegacyValueStateCaptureFraction = 0.80;
protocol.requireExactRollingProjection = true;
protocol.returnGenerationAuthorized = false;
protocol.criticTrainingAuthorized = false;
protocol.x36Authorized = false;
end
