function protocol = getRiskTriggeredFormationShortcutV261Protocol()
% GETRISKTRIGGEREDFORMATIONSHORTCUTV261PROTOCOL Causal path-shortening screen.

source = getCausalMinimumFormationBackboneV242Protocol();
protocol = struct();
protocol.id = 'risk-triggered-formation-shortcut-v261-v1';
protocol.contractVersion = ...
    'risk-triggered-formation-shortcut-v261-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v261-risk-triggered-formation-shortcut';
protocol.policyName = 'risk-triggered-formation-shortcut-v261-policy';
protocol.allowedPresets = { ...
    'm24-formation-fov-temporal-coupled-formation-braid'};
protocol.allowedSeeds = 1301;
protocol.continuationStartTime = 57;
protocol.continuationEndTime = 73;
protocol.localizationEventWindow = [58, 73];
protocol.localizationEventFormation = 4;
protocol.localizationAbsoluteThreshold = 0.25;
protocol.localizationRelativeThreshold = 2.50;
protocol.minimumDonorCoverage = 0.80;
protocol.minimumDonorExistence = 0.50;
protocol.maximumDonorToTargetRiskRatio = 0.50;
protocol.minimumHopReduction = 1;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.receiverMode = source.receiverMode;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v261', ...
    'risk_triggered_formation_shortcut', ...
    'm24_seed1301_t57_73');
protocol.minimumEventFormationRmseGainPercent = 0;
protocol.minimumEventFormationEospaGainPercent = 0;
protocol.maximumNetworkRegressionPercent = 2;
protocol.maximumFormationRegressionPercent = 3;
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V261 is an outcome-opened M24 continuation mechanism screen. ', ...
    'The V259 trace revealed a formation-level common localization ', ...
    'bias rather than an intra-formation disagreement failure. The ', ...
    'online policy uses only current LMB posterior summaries, the ', ...
    'current physical graph and past selected routes. When one ', ...
    'formation has a high localization tail and another has a ', ...
    'well-supported lower-risk copy of the same label, it replaces ', ...
    'the current formation tree only if a current physical path can ', ...
    'reduce their KLA hop distance. The projected route keeps exactly ', ...
    'N+2(F-1) posterior messages and the V242 local-cycle and weight ', ...
    'contract. The controller is centralized and its synopsis cost is ', ...
    'not included, so the result can establish action-mechanism ', ...
    'headroom only, not deployment cost, validation or generalization.'];

if protocol.continuationStartTime >= protocol.continuationEndTime || ...
        protocol.localizationAbsoluteThreshold <= 0 || ...
        protocol.localizationAbsoluteThreshold >= 1 || ...
        protocol.localizationRelativeThreshold <= 1 || ...
        protocol.minimumDonorCoverage <= 0.5 || ...
        protocol.minimumDonorCoverage > 1 || ...
        protocol.minimumDonorExistence <= 0 || ...
        protocol.minimumDonorExistence >= 1 || ...
        protocol.maximumDonorToTargetRiskRatio <= 0 || ...
        protocol.maximumDonorToTargetRiskRatio >= 1 || ...
        protocol.minimumHopReduction ~= 1
    error('RiskTriggeredShortcutV261:InvalidProtocol', ...
        'The V261 risk, donor or continuation contract is invalid.');
end
end
