function [registry, metadata] = ...
    getRollingSafeObservableScoreBasisRegistry()
% GETROLLINGSAFEOBSERVABLESCOREBASISREGISTRY Frozen truth-free action basis.
%
% Six semantic score directions are crossed with exact current
% cardinalities k=1,2,3. Code 78 is the sole k=0 action. Codes 80:87 retain
% their earlier analytic/development semantics and are intentionally not
% reused.

contractVersion = 'rolling-safe-observable-score-basis-registry-v1';
basisVersion = 'v1';
basisIds = { ...
    'link-advantage', ...
    'posterior-gain', ...
    'compatibility-conservative', ...
    'receiver-rescue', ...
    'history-novelty', ...
    'history-continuity'};
featureNames = { ...
    {'link_reliability_advantage'}, ...
    {'positive_existence_gain', ...
     'positive_precision_gain', ...
     'node_quality_advantage', ...
     'negative_existence_gap', ...
     'negative_precision_gap'}, ...
    {'active_label_overlap', ...
     'moment_compatibility_score', ...
     'normalized_state_discrepancy', ...
     'negative_existence_gap', ...
     'negative_precision_gap'}, ...
    {'receiver_need', ...
     'receiver_cardinality_variance_fraction', ...
     'positive_existence_gain', ...
     'positive_precision_gain', ...
     'node_quality_advantage'}, ...
    {'history_edge_frequency', ...
     'formation_pair_history_frequency', ...
     'receiver_history_source_diversity'}, ...
    {'previous_edge', ...
     'latest_formation_pair_active', ...
     'link_reliability'}};
coefficients = { ...
    1, ...
    [1, 1, 1, -1, -1], ...
    [1, 1, -1, -1, -1], ...
    [1, 1, 1, 1, 1], ...
    [-1, -1, -1], ...
    [1, 1, 1]};
descriptions = { ...
    'Prefer a cross link whose current reliability exceeds the receiver backbone link.', ...
    'Prefer a source with higher existence, precision and posterior quality.', ...
    'Prefer compatible posteriors and penalize disagreement and negative gaps.', ...
    'Route useful posterior information toward uncertain or weak receivers.', ...
    'Explore sensor and formation-pair routes underrepresented in executed history.', ...
    'Preserve reliable recent routes and formation-pair continuity.'};

template = struct( ...
    'contractVersion', contractVersion, ...
    'actionCode', NaN, ...
    'basisId', '', ...
    'basisVersion', basisVersion, ...
    'featureContextMode', 'raw', ...
    'featureNames', {{}}, ...
    'coefficients', [], ...
    'transforms', {{}}, ...
    'exactCurrentCrossEdgeCount', NaN, ...
    'posteriorUsed', true, ...
    'currentLinkReliabilityUsed', false, ...
    'historyUsed', false, ...
    'currentGeometryUsed', true, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false, ...
    'description', '', ...
    'registrySha256', '');
registry = repmat(template, 1, 19);
cursor = 0;
actionCode = 60;
for basisIdx = 1:numel(basisIds)
    for crossEdgeCount = 1:3
        cursor = cursor + 1;
        registry(cursor).actionCode = actionCode;
        registry(cursor).basisId = basisIds{basisIdx};
        registry(cursor).featureNames = featureNames{basisIdx};
        registry(cursor).coefficients = coefficients{basisIdx};
        registry(cursor).transforms = repmat( ...
            {'block-percentile'}, 1, ...
            numel(featureNames{basisIdx}));
        registry(cursor).exactCurrentCrossEdgeCount = ...
            crossEdgeCount;
        registry(cursor).currentLinkReliabilityUsed = ...
            any(strcmp(featureNames{basisIdx}, ...
                'link_reliability')) || ...
            any(strcmp(featureNames{basisIdx}, ...
                'link_reliability_advantage'));
        registry(cursor).historyUsed = ...
            any(strncmp(featureNames{basisIdx}, ...
                'history_', 8)) || ...
            any(strcmp(featureNames{basisIdx}, ...
                'formation_pair_history_frequency')) || ...
            any(strcmp(featureNames{basisIdx}, ...
                'receiver_history_source_diversity')) || ...
            any(strcmp(featureNames{basisIdx}, ...
                'previous_edge')) || ...
            any(strcmp(featureNames{basisIdx}, ...
                'latest_formation_pair_active'));
        registry(cursor).description = descriptions{basisIdx};
        actionCode = actionCode + 1;
    end
end
cursor = cursor + 1;
registry(cursor).actionCode = 78;
registry(cursor).basisId = 'no-cross-edge';
registry(cursor).featureNames = {};
registry(cursor).coefficients = [];
registry(cursor).transforms = {};
registry(cursor).exactCurrentCrossEdgeCount = 0;
registry(cursor).posteriorUsed = false;
registry(cursor).currentGeometryUsed = true;
registry(cursor).description = ...
    'Execute the cycle backbone with no current cross-formation override.';

serialized = cell(1, numel(registry));
for entryIdx = 1:numel(registry)
    entry = registry(entryIdx);
    serialized{entryIdx} = sprintf( ...
        '%s|%d|%s|%s|%s|%s|%d|%d|%d|%d', ...
        contractVersion, entry.actionCode, entry.basisId, ...
        entry.basisVersion, ...
        strjoin(entry.featureNames, ','), ...
        sprintf('%.17g,', entry.coefficients), ...
        entry.exactCurrentCrossEdgeCount, ...
        entry.posteriorUsed, ...
        entry.currentLinkReliabilityUsed, ...
        entry.historyUsed);
end
registrySha256 = computeTextSha256( ...
    strjoin(serialized, char(30)));
for entryIdx = 1:numel(registry)
    registry(entryIdx).registrySha256 = registrySha256;
end

metadata = struct( ...
    'contractVersion', contractVersion, ...
    'basisVersion', basisVersion, ...
    'registrySha256', registrySha256, ...
    'actionCodes', [registry.actionCode], ...
    'entryCount', numel(registry), ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end
