function protocol = getReceiverFusionAlignmentV73Protocol()
% GETRECEIVERFUSIONALIGNMENTV73PROTOCOL Frozen source-only semantic check.

v70 = getReceiverDomainNormalizedOpportunityV70Protocol();
v71 = getReceiverDomainTransportProjectionV71Protocol();
expectedNodeCounts = [24, 36];
expectedFormationCounts = [4, 6];
expectedSlotCounts = [2, 4];
cases = repmat(struct(), 1, numel(v71.presets));
for idx = 1:numel(v71.presets)
    cases(idx) = struct( ...
        'presetName', v71.presets{idx}, ...
        'seed', v71.allSeeds, ...
        'currentTime', v71.anchorTimes(idx), ...
        'expectedNodeCount', expectedNodeCounts(idx), ...
        'expectedFormationCount', expectedFormationCounts(idx), ...
        'v71SelectedFormationIds', ...
            reshape(v71.anchorFormationIds{idx}, 1, []), ...
        'v71SelectedSlotCount', expectedSlotCounts(idx));
end

protocol = struct();
protocol.id = 'receiver-fusion-alignment-v73-v1';
protocol.contractVersion = ...
    'receiver-fusion-alignment-v73-protocol-v1';
protocol.baseOpportunityProtocolId = v70.id;
protocol.baseProjectionProtocolId = v71.id;
protocol.cases = cases;
protocol.cacheRoot = v71.cacheRoot;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v73', 'receiver_fusion_alignment');
protocol.fusionConfig = buildMixtureAwareKlaReferenceConfig();
protocol.receiverInputFirstRequired = true;
protocol.neighborMessageEventType = 2;
protocol.selectedNeighborDeliveryConditioned = true;
protocol.linkReliabilityAppliedOutsideConditionalFusion = true;
protocol.routeConstructionAuthorized = true;
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V73 re-evaluates exactly the two opened V72 source anchors without ', ...
    'executing a route or reading tracking outcomes. Direct receiver ', ...
    'counterfactuals use the formal mixture-aware reference config, put ', ...
    'the receiver first, and mark selected neighbors as delivered heavy ', ...
    'messages. Link reliability remains an external expected-value ', ...
    'factor. The check isolates receiver semantics before any temporal ', ...
    'propagation model is introduced.'];
end
