function protocol = getRoleMultiplexedSinglePayloadV143Protocol()
% GETROLEMULTIPLEXEDSINGLEPAYLOADV143PROTOCOL Budget-feasible W/R carrier.

protocol = getCombinedOutputSafetyV139Protocol();
protocol.id = 'role-multiplexed-single-payload-v143-v1';
protocol.contractVersion = ...
    'v143-role-multiplexed-single-payload-protocol-v1';
protocol.methodName = ...
    'reference-first role-multiplexed single-payload W/R routing';
protocol.outcomePolicyName = ...
    'role-multiplexed-single-payload-v143-screen-v1';
protocol.roleSchedule = struct( ...
    'periodPages', 2, ...
    'referencePhaseOffset', 0, ...
    'firstPhase', 'reference', ...
    'referencePhaseIntraFormationPayload', 'reference-relay', ...
    'referencePhaseCrossFormationPayload', 'reference-relay', ...
    'workingPhaseProtectedIntraFormationPayload', 'working-state', ...
    'workingPhaseOtherPayload', 'reference-relay', ...
    'unassignedRelayWeightMode', 'self', ...
    'physicalMissingNeighborWeightMode', ...
        protocol.primaryMissingNeighborWeightMode, ...
    'onePayloadPerAttemptedEdge', true, ...
    'auxiliaryPayloadAllowed', false, ...
    'workingStateCrossFormationTransmissionAllowed', false, ...
    'exactStaticStateFallbackClaimAllowed', false);
protocol.finiteTimeMixingPreflight = struct( ...
    'metric', 'maximum-row-total-variation-and-dobrushin', ...
    'm24StaticDobrushin', 0.367078585033, ...
    'm24CandidateDobrushin', 0.373537060, ...
    'm24TerminalMaximumRowTotalVariation', 0.009270354, ...
    'x36StaticDobrushin', 0.515065290200, ...
    'x36CandidateDobrushin', 0.517756172, ...
    'x36TerminalMaximumRowTotalVariation', 0.009409622, ...
    'connectivityOnlyEdgeClassSplitRejected', true);
protocol.screen.requirePositiveAuxiliaryPayload = false;
protocol.screen.requireZeroAuxiliaryPayload = true;
protocol.screen.requireNoAttemptedByteIncrease = true;
protocol.screen.maximumAttemptedByteDeltaFraction = 0;
protocol.screen.requireBothScales = true;
protocol.mechanismUpperBoundOnly = false;
protocol.communicationMethodClaimAllowedAfterJointGate = true;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v143', 'role_multiplexed_single_payload_v1');
protocol.validationClaimAllowed = false;
end
