function registry = getRegisteredRollingSafeRolloutArtifact()
% GETREGISTEREDROLLINGSAFEROLLOUTARTIFACT External held-out trust root.
%
% This registry remains disabled until an accepted model is trained from a
% clean committed protocol and its exact artifact/file hashes are reviewed
% and committed in a separate checkpoint.

protocol = getRollingSafeRolloutProtocol();
registry = struct( ...
    'enabled', false, ...
    'protocolId', protocol.id, ...
    'artifactId', '', ...
    'modelFileSha256', '', ...
    'trainingGitCommit', '', ...
    'datasetGenerationGitCommit', '', ...
    'behaviorCacheSetSha256', ...
        protocol.behaviorCacheSetSha256);
end
