function protocol = getRiskRootedMultiSourceTreeV263Protocol()
% GETRISKROOTEDMULTISOURCETREEV263PROTOCOL Same-budget multi-source screen.

source = getCausalMinimumFormationBackboneV242Protocol();
protocol = struct();
protocol.id = 'risk-rooted-multi-source-tree-v263-v1';
protocol.contractVersion = ...
    'risk-rooted-multi-source-tree-v263-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v263-risk-rooted-multi-source-tree';
protocol.policyName = 'risk-rooted-multi-source-tree-v263-policy';
protocol.allowedPresets = { ...
    'm24-formation-fov-temporal-coupled-formation-braid'};
protocol.allowedSeeds = 1301;
protocol.continuationStartTime = 57;
protocol.continuationEndTime = 73;
protocol.localizationEventWindow = [58, 73];
protocol.localizationEventFormation = 4;
protocol.localizationAbsoluteThreshold = 0.25;
protocol.localizationRelativeThreshold = 2.50;
protocol.minimumSourceCoverage = 0.80;
protocol.minimumSourceExistence = 0.50;
protocol.maximumSourceToTargetRiskRatio = 0.50;
protocol.minimumEligibleSourceCount = 2;
protocol.minimumInitiallyShortenedSourceCount = 1;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.receiverMode = source.receiverMode;
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v263', ...
    'risk_rooted_multi_source_tree', 'm24_seed1301_t57_73');
protocol.minimumEventFormationRmseGainPercent = 0;
protocol.minimumEventFormationEospaGainPercent = 0;
protocol.maximumNetworkRegressionPercent = 2;
protocol.maximumFormationRegressionPercent = 3;
protocol.developmentEvidenceOnly = true;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'V263 is an outcome-opened M24 continuation mechanism screen. ', ...
    'The current controller uses only current LMB posterior summaries, ', ...
    'the current physical graph, current link reliability and past ', ...
    'selected routes. When one formation has a high localization tail ', ...
    'and at least two other formations hold supported lower-risk copies ', ...
    'of its highest-risk label, V263 roots a breadth-first formation ', ...
    'tree at that formation. This minimizes every formation-to-target ', ...
    'hop distance componentwise over current physical spanning trees, ', ...
    'so both localization and set-support sources receive shortest-hop ', ...
    'access without selecting a tuned mixture coefficient. The route ', ...
    'keeps exactly N+2(F-1) posterior messages and the V242 local-cycle ', ...
    'and weight contract. The controller is centralized and its ', ...
    'synopsis cost is not included, so this result can establish only ', ...
    'action-mechanism headroom, not deployment cost, validation or ', ...
    'generalization.'];

if protocol.continuationStartTime >= protocol.continuationEndTime || ...
        protocol.localizationAbsoluteThreshold <= 0 || ...
        protocol.localizationAbsoluteThreshold >= 1 || ...
        protocol.localizationRelativeThreshold <= 1 || ...
        protocol.minimumSourceCoverage <= 0.5 || ...
        protocol.minimumSourceCoverage > 1 || ...
        protocol.minimumSourceExistence <= 0 || ...
        protocol.minimumSourceExistence >= 1 || ...
        protocol.maximumSourceToTargetRiskRatio <= 0 || ...
        protocol.maximumSourceToTargetRiskRatio >= 1 || ...
        protocol.minimumEligibleSourceCount < 2 || ...
        protocol.minimumInitiallyShortenedSourceCount < 1
    error('RiskRootedMultiSourceV263:InvalidProtocol', ...
        'The V263 risk, source or continuation contract is invalid.');
end
end
