function protocol = getSignedCompleteLabelExceptionV108Protocol()
% GETSIGNEDCOMPLETELABELEXCEPTIONV108PROTOCOL Frozen signed-label oracle.

base = getProtectionOnlyH8V105Protocol();
protocol = base;
protocol.id = 'signed-complete-label-exception-v108-v1';
protocol.contractVersion = ...
    'signed-complete-label-exception-v108-protocol-v1';
protocol.outcomePolicyName = ...
    'signed-complete-label-exception-v108-v1';
protocol.executionProfile = 'v108-signed-complete-label-exception';
protocol.bankVariant = 'signed-complete-label-exception-v108';
protocol.candidateActionName = ...
    'v108-signed-complete-label-exception-h8';
protocol.resultContractVersion = ...
    'signed-complete-label-exception-v108-x36-t72-result-v1';
protocol.resultFileStem = ...
    'SIGNED_COMPLETE_LABEL_EXCEPTION_V108_X36_T72_RESULT';
protocol.reportTitle = ...
    'V108 signed complete-label exception oracle: X36 t72 H=8';
protocol.armDisplayName = 'V108 signed-label oracle';
protocol.runLabel = 'V108 X36-t72 H=8';
protocol.maximumExceptionsPerDeliveredEdge = 3;
protocol.completeLabelExceptionsByTime = buildExceptionSchedule( ...
    base.horizonSteps, base.cases( ...
        strcmp({base.cases.scaleName}, 'X36')).expectedNodeCount);
protocol.minimumFormationGainPercent = 0;
protocol.minimumTargetPeerTerminalGainPercent = 0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v108', 'signed_complete_label_exception');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, 'matched_static_headroom');
protocol.evidenceBoundary = [ ...
    'V108 is a frozen retrospective action-space headroom oracle. It ', ...
    'keeps the exact V105 static route and control-only formation schedule ', ...
    'but admits at most three complete Bernoulli Gaussian-mixture labels ', ...
    'on an actually delivered F1 or F6 gateway edge. The label schedule ', ...
    'was selected from opened V105 local posterior snapshots and target ', ...
    'truth using positive one-round capped expected-risk reduction under ', ...
    'the repository''s componentwise powered-GM KLA approximation. It ', ...
    'therefore uses truth and future opened states, is not deployable, and ', ...
    'cannot support validation or generalization claims. Its sole purpose ', ...
    'is to test whether sparse complete-label exceptions have enough ', ...
    'headroom to repair V105''s F1/F6 losses before a truth-free estimator ', ...
    'or GNN is designed.'];
end

function schedule = buildExceptionSchedule(horizonSteps, sensorCount)
schedule = cell(1, horizonSteps);
for timeIdx = 1:horizonSteps
    schedule{timeIdx} = cell(sensorCount);
end

% F1 gateway receiver 2 <- sender 9. Delivered at t=74, 75, and 77.
schedule{3}{2, 9} = [1, 1, 7; 3, 1, 6];
schedule{4}{2, 9} = [1, 1, 19; 3, 1, 15];
schedule{6}{2, 9} = [1, 7, 13; 1, 6, 11];

% F6 gateway receiver 32 <- sender 3. Delivered throughout t=75--79.
schedule{4}{32, 3} = [19, 1, 31; 15, 4, 24];
schedule{5}{32, 3} = [1, 19, 31; 4, 15, 21];
schedule{6}{32, 3} = [31, 1, 31; 22, 4, 24];
schedule{7}{32, 3} = [19, 13, 1; 13, 10, 4];
schedule{8}{32, 3} = [19, 1, 13; 13, 4, 11];
end
