function protocol = getSignedMergeSplitOpportunityV69Protocol()
% GETSIGNEDMERGESPLITOPPORTUNITYV69PROTOCOL Cross-scale source discovery.

v66 = getInfluenceAwareDecisionBreadthV66Protocol();
protocol = struct();
protocol.id = 'signed-merge-split-opportunity-v69-v1';
protocol.contractVersion = ...
    'signed-merge-split-opportunity-v69-protocol-v1';
protocol.referencePolicyName = ...
    'formation-h3-current-physical-path-reference-v1';
protocol.presets = { ...
    'm24-formation-fov-merge-split', ...
    'x36-formation-fov-merge-split'};
protocol.allSeeds = 1401;
protocol.snapshotTimes = 40:4:140;
protocol.filterSeedOffset = 100000;
protocol.expectedNodeCounts = [24, 36];
protocol.expectedFormationCounts = [4, 6];
protocol.expectedMinimumSensorTargetSeparation = 30;
protocol.horizonSteps = v66.horizonSteps;
protocol.positiveSupportThreshold = v66.positiveSupportThreshold;
protocol.decisionExistenceThreshold = 0.50;
protocol.minimumNormalizedRobustMarginExposure = ...
    v66.minimumNormalizedRobustMarginExposure;
protocol.minimumMaterialPressureFraction = 0.01;
protocol.minimumMaterialAlternativeHeadroomFraction = 0.01;
protocol.sourceWeight = 0.05;
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v69', 'merge_split_signed_opportunity', 'cache');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v69', 'merge_split_signed_opportunity');
protocol.referenceStateGenerationAuthorized = true;
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V69 evaluates one frozen seed on the phase-aligned M24 and X36 ', ...
    'merge-split geometries. It reads current posterior, observation ', ...
    'support, current physical links, and registered topology history ', ...
    'only. Quarantine pressure, reference-edge transport retention, ', ...
    'and optimistic unused-sender headroom are source-only diagnostics. ', ...
    'They do not authorize route execution, tracking scoring, model ', ...
    'training, or validation.'];
end
