function protocol = getSpatialLabelSupportDebtRoutingV147Protocol()
% GETSPATIALLABELSUPPORTDEBTROUTINGV147PROTOCOL Frozen routing headroom.

source = getSetTrustSequenceV134Protocol();
protocol = struct();
protocol.id = 'spatial-label-support-debt-routing-v147-v1';
protocol.contractVersion = ...
    'v147-spatial-label-support-debt-routing-protocol-v1';
protocol.methodName = ...
    'single-posterior spatial label-support debt routing';
protocol.outcomePolicyName = ...
    'spatial-label-support-debt-routing-v147-screen-v1';
protocol.pilotSeed = source.pilotSeed;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.primaryMissingNeighborWeightMode = ...
    source.primaryMissingNeighborWeightMode;
protocol.nominalKlaWeightMode = source.nominalKlaWeightMode;
protocol.referenceCarrierModes = source.referenceCarrierModes;
protocol.routeWeights = source.routeWeights;
protocol.scaleCases = source.scaleCases;

protocol.sourceExistenceThreshold = 0.50;
protocol.positiveAssociationThreshold = 0.20;
protocol.decisionExistenceThreshold = 0.50;
protocol.maximumSourcesPerReceiver = 3;
protocol.maximumCandidatesPerFormation = 3;
protocol.minimumRawDebt = 1e-8;
protocol.minimumVirtualNetGain = 1e-8;
protocol.maximumProtectedHarmToGainRatio = 1.0;
protocol.maximumInitialByteDeltaFraction = 0;
protocol.requireInstantStrongConnectivity = true;

protocol.temporalSchedules = struct( ...
    'name', {'burst-123', 'staggered-1235'}, ...
    'activeOffsets', {[1, 2, 3], [1, 2, 3, 5]});
protocol.actionPatterns = struct( ...
    'name', { ...
        'reference', ...
        'dominant-single-burst-123', ...
        'dominant-half-burst-123', ...
        'dominant-max-burst-123', ...
        'dominant-single-staggered-1235', ...
        'dominant-half-staggered-1235', ...
        'dominant-max-staggered-1235', ...
        'residual-max-staggered-1235'}, ...
    'roleMode', { ...
        'reference', ...
        'dominant-promotion', ...
        'dominant-promotion', ...
        'dominant-promotion', ...
        'dominant-promotion', ...
        'dominant-promotion', ...
        'dominant-promotion', ...
        'residual-replacement'}, ...
    'coverageMode', { ...
        'reference', 'single', 'half', 'maximum', ...
        'single', 'half', 'maximum', 'maximum'}, ...
    'activeOffsets', { ...
        [], [1, 2, 3], [1, 2, 3], [1, 2, 3], ...
        [1, 2, 3, 5], [1, 2, 3, 5], ...
        [1, 2, 3, 5], [1, 2, 3, 5]});

protocol.gate = struct( ...
    'minimumInterventionGainFraction', 0.05, ...
    'minimumFullWindowGainFraction', 0.00, ...
    'minimumMatureGainFraction', 0.00, ...
    'minimumSensorGainFraction', -1e-4, ...
    'minimumFormationGainFraction', -1e-4, ...
    'minimumConsensusGainFraction', -1e-4, ...
    'minimumRejoinedReferenceFraction', 1.00, ...
    'maximumAttemptedByteDeltaFraction', 0.00, ...
    'requireBothScales', true);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v147', 'spatial_label_support_debt_routing_v1');
protocol.reportingPolicy = struct( ...
    'failedCandidatesRepositoryOnly', true, ...
    'singleScaleResultMainDocument', false, ...
    'jointHeadroomRequiredBeforeLearning', true);
protocol.gnnAuthorized = false;
protocol.validationClaimAllowed = false;
end
