function protocol = getSetTrustSequenceV134Protocol()
% GETSETTRUSTSEQUENCEV134PROTOCOL Frozen pre-learning headroom contract.

policy = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
protocol = struct();
protocol.id = 'set-trust-sequence-v134-v1';
protocol.contractVersion = 'v134-set-trust-sequence-protocol-v1';
protocol.methodName = ...
    'finite-horizon formation-set full-posterior trust scheduling';
protocol.referenceCarrierSelection = ...
    'stronger-paired-full-trajectory-static-direction-per-scale';
protocol.referenceCarrierModes = { ...
    'fixed-clockwise', 'fixed-counter-clockwise'};
protocol.outcomePolicyName = 'set-trust-sequence-v134-headroom-v1';
protocol.filterSeedOffset = 100000;
protocol.developmentSeeds = [1601, 1607, 1613, 1619];
protocol.pilotSeed = 1601;
protocol.pilotAnchorQuantileWithinFocusWindow = 0.50;
protocol.primaryMissingNeighborWeightMode = 'renormalize';
protocol.routeWeights = struct( ...
    'dominantWeight', policy.dominantWeight, ...
    'residualWeight', policy.residualWeight);
protocol.maximumIncomingCountForOutcomeEnumeration = ...
    policy.maximumIncomingCountForOutcomeEnumeration;
protocol.payloadMode = 'full-posterior-trust';
protocol.zeroTrustWireRepresentation = 'control-synopsis-only';
protocol.positiveTrustWireRepresentation = ...
    'complete-mixture-aware-lmb-posterior';
protocol.trustFactors = [0, 0.25, 0.50, 1.00];
protocol.returnRamp = [0.25, 0.50, 1.00];
protocol.candidateSetFamily = 'observable-risk-ranked-nested-prefixes';
protocol.persistentZeroCandidateEnabled = true;
protocol.diameterTaperCandidateEnabled = true;
protocol.scaleCases = struct( ...
    'scaleName', {'M24', 'X36'}, ...
    'presetName', {'m24-formation-fov', 'x36-formation-fov'}, ...
    'expectedNodeCount', {24, 36}, ...
    'expectedFormationCount', {4, 6}, ...
    'formationCycleDiameter', {3, 5}, ...
    'horizonSteps', {6, 8});
protocol.preLearningGate = struct( ...
    'minimumPairedMeanEospGainFraction', 0.05, ...
    'minimumPairedMatureEospGainFraction', 0.05, ...
    'minimumFormationGainFraction', 0.00, ...
    'minimumMatureFormationGainFraction', 0.00, ...
    'minimumSensorGainFraction', 0.00, ...
    'minimumMatureSensorGainFraction', 0.00, ...
    'requirePositiveAttemptedByteSaving', true, ...
    'requireBothScales', true);
protocol.fullSubsetBankOfflineOracleOnly = true;
protocol.nestedPrefixBankDeployable = true;
protocol.onPolicyLearningAuthorizedOnlyAfterHeadroomGate = true;
protocol.gnnAuthorized = false;
protocol.reportingPolicy = struct( ...
    'failedCandidatesRepositoryOnly', true, ...
    'singleCaseBrightSpotsMainDocument', false, ...
    'mainDocumentRequiresJointAggregateGate', true, ...
    'stableMethodDesignMayBeReported', true);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v134', 'set_trust_sequence');
protocol.validationClaimAllowed = false;
end
