function protocol = ...
        getSparseReferenceLabelRollbackV156Protocol(maximumLabelEdits)
% GETSPARSEREFERENCELABELROLLBACKV156PROTOCOL Bounded V126 label oracle.

if nargin < 1 || isempty(maximumLabelEdits)
    maximumLabelEdits = 2;
end
if ~ismember(maximumLabelEdits, [1, 2, 4, 8])
    error('SparseReferenceLabelV156:UnsupportedCapacity', ...
        'V156 is frozen to K in {1, 2, 4, 8}.');
end
base = getShadowStateRollbackV126Protocol();
protocol = base;
protocol.maximumLabelEdits = maximumLabelEdits;
protocol.id = sprintf( ...
    'sparse-reference-label-rollback-v156-k%d-v1', maximumLabelEdits);
protocol.contractVersion = ...
    'sparse-reference-label-rollback-v156-protocol-v1';
protocol.outcomePolicyName = sprintf( ...
    'sparse-reference-label-rollback-v156-k%d-v1', maximumLabelEdits);
protocol.executionProfile = 'v156-sparse-reference-label-rollback';
protocol.bankVariant = 'sparse-reference-label-rollback-v156';
protocol.candidateActionName = sprintf( ...
    'v156-sparse-reference-label-k%d', maximumLabelEdits);
protocol.resultContractVersion = sprintf( ...
    'sparse-reference-label-rollback-v156-k%d-x36-t72-result-v1', ...
    maximumLabelEdits);
protocol.resultFileStem = sprintf( ...
    'SPARSE_REFERENCE_LABEL_ROLLBACK_V156_K%d_X36_T72_RESULT', ...
    maximumLabelEdits);
protocol.reportTitle = sprintf( ...
    'V156 sparse reference-label rollback K=%d: X36 t72 H=8', ...
    maximumLabelEdits);
protocol.armDisplayName = sprintf( ...
    'V156 sparse reference labels K=%d', maximumLabelEdits);
protocol.runLabel = sprintf('V156 K=%d X36-t72 H=8', maximumLabelEdits);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v156', 'sparse_reference_label_rollback');
protocol.headroomOutputRoot = fullfile( ...
    protocol.outputRoot, sprintf('k%d', maximumLabelEdits));
protocol.auxiliaryMaintenanceCostAccounted = false;
protocol.evidenceBoundary = sprintf([ ...
    'V156 K=%d is a privileged paired X36 seed-211 t=72 H=8 ', ...
    'representational-sufficiency oracle. It retains the V105 static ', ...
    'carrier, fusion weights and protection schedule. At the 36 frozen ', ...
    'V126 rollback cells it compares the evolving working posterior with ', ...
    'the paired static posterior, ranks labels without truth or future ', ...
    'measurements, and copies at most %d complete GM Bernoulli label ', ...
    'states (including explicit tombstones). The paired reference and ', ...
    'opened rollback cells are counterfactual information, so the arm is ', ...
    'not deployable and cannot support validation or generalization ', ...
    'claims. Communication accounting still contains only the V105 main ', ...
    'path; reference-label transport is estimated separately.'], ...
    maximumLabelEdits, maximumLabelEdits);
end
