function protocol = getSetTrustSequenceV134GeneralizationProtocol()
% GETSETTRUSTSEQUENCEV134GENERALIZATIONPROTOCOL Frozen validation contract.

method = getSetTrustSequenceV134Protocol();
geometry = getFormationFovMultistyleGeometryValidationProtocol();

payload = struct();
payload.contractVersion = ...
    'v134-policy-generalization-protocol-v1';
payload.methodProtocolId = method.id;
payload.requiredMethodJointGate = ...
    'JOINT_HEADROOM_GATE_V134.jointCrossScaleGatePassed';
payload.requiredGeometryProtocolSha256 = geometry.canonicalSha256;
payload.requiredGeometryGateDecision = ...
    'all-absolute-and-cross-scale-geometry-gates-pass';
payload.trackingOutcomePermit = struct( ...
    'required', true, ...
    'issueBeforeMethodJointGate', false, ...
    'issueBeforePolicyFreeze', false, ...
    'issueBeforeGeometryGate', false, ...
    'bindMethodSourceCommit', true, ...
    'bindPolicyCheckpointSha256', true, ...
    'bindFeatureNormalizerSha256', true, ...
    'bindProtocolSha256', true, ...
    'bindExactPresetSeedManifest', true, ...
    'authorizeTruthForScoringOnly', true, ...
    'authorizeTruthForPolicy', false, ...
    'authorizeValidationClaimBeforeAggregateGate', false);
payload.evaluationUnit = 'complete-trajectory-paired-seed';
payload.developmentSeeds = method.developmentSeeds;
payload.radialValidationSeeds = [2203, 2207, 2221];
payload.convoyTransferSeeds = [2309, 2341, 2351];
payload.relayTransferSeeds = [2401, 2411, 2417];
payload.crossingStressSeeds = [2503, 2521];
payload.requireExactSeedManifest = true;
payload.requireDisjointSeedSplits = true;
payload.validationSeedsMayEnterTraining = false;
payload.validationOutcomesMayChangePolicy = false;

payload.radialPresets = [ ...
    presetEntry('M24', 'm24-formation-fov', 'radial-surround'), ...
    presetEntry('X36', 'x36-formation-fov', 'radial-surround')];
payload.transferPresets = [ ...
    presetEntry('M24', 'm24-formation-fov-convoy', ...
        'parallel-convoy'), ...
    presetEntry('X36', 'x36-formation-fov-convoy', ...
        'parallel-convoy'), ...
    presetEntry('M24', 'm24-formation-fov-relay', ...
        'linear-relay'), ...
    presetEntry('X36', 'x36-formation-fov-relay', ...
        'linear-relay')];
payload.stressPresets = [ ...
    presetEntry('M24', 'm24-formation-fov-crossing', ...
        'orthogonal-crossing'), ...
    presetEntry('X36', 'x36-formation-fov-crossing', ...
        'orthogonal-crossing')];

payload.policyFreeze = struct( ...
    'oneSharedScaleNormalizedCheckpoint', true, ...
    'perScalePolicyCheckpointAllowed', false, ...
    'perPresetTuningAllowed', false, ...
    'perScaleThresholdTuningAllowed', false, ...
    'sceneIdentityInputAllowed', false, ...
    'sensorIndexInputAllowed', false, ...
    'formationIndexInputAllowed', false, ...
    'truthInputAllowed', false, ...
    'futureMeasurementInputAllowed', false, ...
    'futureDeliveryInputAllowed', false, ...
    'unseenOutcomeFeedbackAllowed', false, ...
    'freezeBeforeRadialValidation', true, ...
    'radialValidationPassRequiredBeforeTransfer', true);

payload.reference = struct( ...
    'name', 'frozen-full-posterior-static-carrier', ...
    'selectionArtifact', 'FROZEN_REFERENCE_CARRIER_V133.mat', ...
    'selectionRule', ...
        'stronger-radial-development-direction-per-scale', ...
    'perSceneDirectionOracleAllowed', false, ...
    'perSeedDirectionOracleAllowed', false, ...
    'fullMixtureAwareLmbPosterior', true, ...
    'nominalKlaWeightMode', 'metropolis', ...
    'stalePosteriorSubstitutionAllowed', false);
payload.pairing = struct( ...
    'sameTruth', true, ...
    'sameMeasurements', true, ...
    'sameLinkUniforms', true, ...
    'sameFilterRandomness', true, ...
    'samePhysicalReachability', true, ...
    'sameNominalKlaWeights', true, ...
    'chargeControlSynopsis', true);

payload.radialGate = commonGate(0.05, 0.05, 0.05, -0.01);
payload.transferGate = commonGate(0.05, 0.05, 0.02, -0.02);
payload.radialGate.requireEachScaleIndependently = true;
payload.transferGate.requireEachScaleIndependently = true;
payload.transferGate.requireEachStyleIndependently = true;
payload.transferGate.crossScaleCompensationAllowed = false;
payload.transferGate.crossStyleCompensationAllowed = false;
payload.transferGate.minimumPassingStyleFraction = 1.0;

payload.factorialAttribution = struct( ...
    'stage', 'radial-validation-after-primary-gate', ...
    'arms', {{ ...
        'static-full-fixed-kla', ...
        'static-full-adaptive-kla', ...
        'binary-admission-fixed-kla', ...
        'binary-admission-adaptive-kla'}}, ...
    'usedForPolicySelection', false, ...
    'requiredForNoveltyAttribution', true);
payload.crossingStress = struct( ...
    'formalSuccessGate', false, ...
    'includedInPrimaryAverage', false, ...
    'mayRetunePolicy', false, ...
    'purpose', 'report-failure-envelope-after-formal-gates');
payload.reportingPolicy = struct( ...
    'belowGateResultsRepositoryOnly', true, ...
    'mainDocumentRequiresRadialAndTransferGates', true, ...
    'singleScaleSuccessMainDocument', false, ...
    'singleStyleSuccessMainDocument', false, ...
    'stressResultCanSubstituteFormalGate', false, ...
    'reportWorstSeedAndLocalUnits', true);
payload.validationClaimAllowedBeforeExecution = false;
payload.evidenceBoundary = [ ...
    'Passing supports one frozen online policy against the frozen static ', ...
    'full-posterior reference on unseen radial, convoy and relay ', ...
    'trajectories at both M24 and X36. Crossing remains a non-gating ', ...
    'failure-envelope stress test.'];

actualSha256 = computeCanonicalValueSha256(payload);
expectedSha256 = ...
    '4d6a177fd5eae7ed58bab585367195fcc54923fb045b9b3ee0c5c2472ec979a7';
if ~strcmp(actualSha256, expectedSha256)
    error('V134GeneralizationProtocol:UnregisteredDrift', [ ...
        'The V134 generalization protocol changed without registry ', ...
        'update: actual=%s expected=%s.'], ...
        actualSha256, expectedSha256);
end
protocol = payload;
protocol.canonicalSha256 = actualSha256;
end

function entry = presetEntry(scaleName, presetName, styleName)
entry = struct( ...
    'scaleName', scaleName, ...
    'presetName', presetName, ...
    'styleName', styleName);
end

function gate = commonGate( ...
        minimumFullGain, minimumFocusGain, ...
        minimumStyleMeanGain, minimumWorstSeedGain)
gate = struct( ...
    'minimumPooledFullEpisodeGainFraction', minimumFullGain, ...
    'minimumPooledFocusGainFraction', minimumFocusGain, ...
    'minimumStyleMeanGainFraction', minimumStyleMeanGain, ...
    'minimumPositiveSeedFraction', 2 / 3, ...
    'minimumWorstSeedGainFraction', minimumWorstSeedGain, ...
    'minimumWorstSensorAggregateGainFraction', 0.0, ...
    'minimumWorstFormationAggregateGainFraction', 0.0, ...
    'minimumWindowConsensusGainFraction', 0.0, ...
    'minimumTerminalConsensusGainFraction', 0.0, ...
    'requirePositiveAttemptedByteSaving', true, ...
    'requireCompleteTrajectories', true, ...
    'requireAllRegisteredSeeds', true);
end
