function protocol = getSourcePreservingLabelPacketV268Protocol()
% GETSOURCEPRESERVINGLABELPACKETV268PROTOCOL Two-hop source packet.

source = getAsymmetricEtaRetentionV267Protocol();
protocol = source;
protocol.id = 'source-preserving-label-packet-v268-v1';
protocol.contractVersion = ...
    'source-preserving-label-packet-v268-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.armId = 'v268-source-preserving-label-packet';
protocol.policyName = 'source-preserving-label-packet-v268-policy';
protocol.sourcePreservingPacketRouteEnabled = true;
protocol.packetMaximumAge = 1;
protocol.packetMetadataScalars = 2;
protocol.beneficiaryMode = 'backbone-first';
protocol.oneShotPerEpisodeEnabled = false;
protocol.resultContractVersion = ...
    'source-preserving-label-packet-v268-result-v1';
protocol.resultFileName = ...
    'SOURCE_PRESERVING_LABEL_PACKET_V268_CONTINUATION.mat';
protocol.reportFileName = ...
    'SOURCE_PRESERVING_LABEL_PACKET_V268_CONTINUATION.md';
protocol.reportTitle = 'V268 source-preserving label packet';
protocol.displayName = 'V268 source-preserving label packet';
protocol.passDecision = ...
    'run-one-full-causal-m24-arm-with-frozen-source-preserving-packets';
protocol.failDecision = ...
    'close-source-preserving-label-packets-or-redesign-final-beneficiary';
protocol.outputRoot = fullfile('RUN', 'GA', 'dynamic_topology', ...
    'evidence', 'tracking_aligned_v268', ...
    'source_preserving_label_packet', 'm24_seed1301_t57_73');
protocol.evidenceBoundary = [ ...
    'V268 is an outcome-opened M24 continuation mechanism screen. It ', ...
    'keeps the V242 full-posterior backbone, V265 causal source/relay ', ...
    'selection, V266 online source-share grid and V267 asymmetric ', ...
    'existence-retention rule. A complete selected Bernoulli-GM label is ', ...
    'sent over a first real physical hop and cached at the relay without ', ...
    'changing the relay LMB. On the next page the original source object ', ...
    'is predicted once, sent over a second real physical hop, and fused ', ...
    'only at the final target-formation receiver. Both transmissions and ', ...
    'the source/time provenance metadata are charged; dropped second hops ', ...
    'are not retried. Centralized risk-synopsis cost remains excluded. ', ...
    'No truth or future outcome is visible to the controller, so the ', ...
    'result is mechanism evidence only, not validation or generalization.'];

if protocol.packetMaximumAge ~= 1 || ...
        protocol.packetMetadataScalars < 2
    error('SourcePreservingLabelPacketV268:InvalidProtocol', ...
        'The V268 packet age or provenance metadata contract drifted.');
end
end
