function protocol = getSetTrustSequenceV134Protocol()
% GETSETTRUSTSEQUENCEV134PROTOCOL Frozen pre-learning headroom contract.

policy = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
protocol = struct();
protocol.id = 'formation-admission-sequence-v134-v3';
protocol.contractVersion = ...
    'v134-formation-admission-sequence-protocol-v3';
protocol.methodName = ...
    'finite-horizon binary full-posterior admission scheduling';
protocol.referenceCarrierSelection = ...
    'stronger-paired-full-trajectory-static-direction-per-scale';
protocol.referenceCarrierModes = { ...
    'fixed-clockwise', 'fixed-counter-clockwise'};
protocol.outcomePolicyName = ...
    'formation-admission-sequence-v134-headroom-v3';
protocol.filterSeedOffset = 100000;
protocol.developmentSeeds = [1601, 1607, 1613, 1619];
protocol.pilotSeed = 1601;
protocol.pilotAnchorQuantileWithinFocusWindow = 0.50;
protocol.pilotAnchorRule = ...
    'focus-midpoint-capped-by-latest-complete-horizon-start';
protocol.primaryMissingNeighborWeightMode = 'renormalize';
protocol.routeWeights = struct( ...
    'dominantWeight', policy.dominantWeight, ...
    'residualWeight', policy.residualWeight);
protocol.maximumIncomingCountForOutcomeEnumeration = ...
    policy.maximumIncomingCountForOutcomeEnumeration;
protocol.payloadMode = 'binary-full-posterior-admission';
protocol.runtimePayloadMode = 'binary-full-posterior-admission';
protocol.zeroTrustWireRepresentation = 'control-synopsis-only';
protocol.positiveTrustWireRepresentation = ...
    'complete-mixture-aware-lmb-posterior';
protocol.admissionFactors = [0, 1];
protocol.intermediateTrustAllowed = false;
protocol.learnedFusionWeightAllocationAllowed = false;
protocol.nominalKlaWeightsFrozen = true;
protocol.nominalKlaWeightMode = 'metropolis';
protocol.stalePosteriorSubstitutionAllowed = false;
protocol.reentryOrder = ...
    'reverse-observable-risk-order-one-formation-per-page';
protocol.candidateSetFamily = 'observable-risk-ranked-nested-prefixes';
protocol.persistentZeroCandidateEnabled = true;
protocol.persistentZeroDiagnosticOnly = true;
protocol.pilotEvaluatesPersistentZeroCandidates = false;
protocol.staggeredBinaryReentryCandidateEnabled = true;
protocol.sensorMixingRecoveryMultiplier = 2;
protocol.recoverySquaredContractionTarget = 0.90;
protocol.scaleCases = struct( ...
    'scaleName', {'M24', 'X36'}, ...
    'presetName', {'m24-formation-fov', 'x36-formation-fov'}, ...
    'expectedNodeCount', {24, 36}, ...
    'expectedFormationCount', {4, 6}, ...
    'formationCycleDiameter', {3, 5}, ...
    'recoveryTailSteps', {46, 70}, ...
    'horizonSteps', {53, 81});
protocol.preLearningGate = struct( ...
    'minimumPairedInterventionEospGainFraction', 0.05, ...
    'minimumPairedMeanEospGainFraction', 0.00, ...
    'minimumPairedMatureEospGainFraction', 0.00, ...
    'minimumInterventionFormationGainFraction', 0.00, ...
    'minimumFormationGainFraction', 0.00, ...
    'minimumMatureFormationGainFraction', 0.00, ...
    'minimumInterventionSensorGainFraction', 0.00, ...
    'minimumSensorGainFraction', 0.00, ...
    'minimumMatureSensorGainFraction', 0.00, ...
    'requirePositiveAttemptedByteSaving', true, ...
    'requireFullyRestoredGateEligibleAction', true, ...
    'requireRecoveryMeanSquareCertificate', true, ...
    'maximumRecoverySquaredContractionFactor', 0.90, ...
    'matureWindowDefinition', ...
        'last-two-node-count-minus-one-pages-after-complete-reentry', ...
    'requireBothScales', true);
protocol.theoryBoundary = struct( ...
    'certificateQuantity', ...
        'expected-centered-l2-kla-log-ratio-propagation', ...
    'commonPositiveSupportRequired', true, ...
    'independentDeliveryAssumed', true, ...
    'localBayesDisturbanceBounded', false, ...
    'bernoulliExistenceNormalizerBounded', false, ...
    'mixtureApproximationBounded', false, ...
    'trackingSafetyGuaranteedByCertificateAlone', false);
protocol.fullSubsetBankOfflineOracleOnly = true;
protocol.nestedPrefixBankDeployable = true;
protocol.onPolicyLearningAuthorizedOnlyAfterHeadroomGate = true;
protocol.gnnAuthorized = false;
protocol.noveltyBoundary = struct( ...
    'previousWorkOptimizesReceivedPosteriorFusionWeights', true, ...
    'currentWorkSelectsBinaryPosteriorAdmissionOverTime', true, ...
    'intermediateWeightsAreMethodContribution', false, ...
    'persistentAbstentionCanPassMethodGate', false, ...
    'requiredFactorialComparison', {{ ...
        'static-full-fixed-kla', ...
        'static-full-adaptive-kla', ...
        'binary-admission-fixed-kla', ...
        'binary-admission-adaptive-kla'}});
protocol.reportingPolicy = struct( ...
    'failedCandidatesRepositoryOnly', true, ...
    'singleCaseBrightSpotsMainDocument', false, ...
    'mainDocumentRequiresJointAggregateGate', true, ...
    'stableMethodDesignMayBeReported', true);
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v134', 'binary_admission_sequence_v3');
protocol.validationClaimAllowed = false;
end
