function protocol = getStaticVsDynamicRoutingV91Protocol()
% GETSTATICVSDYNAMICROUTINGV91PROTOCOL Matched routing baseline.

source = getRepeatedMultiGatewayHandoverV89Protocol();
protocol = struct();
protocol.id = 'static-vs-dynamic-routing-v91-v1';
protocol.contractVersion = ...
    'static-vs-dynamic-routing-v91-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.sourceFindingCommit = 'e159327';
protocol.presets = source.presets;
protocol.allSeeds = source.allSeeds;
protocol.expectedNodeCounts = source.expectedNodeCounts;
protocol.expectedFormationCounts = source.expectedFormationCounts;
protocol.dynamicArmId = 'v91-current-physical-dynamic-route';
protocol.staticArmId = 'v91-all-time-physical-static-route';
protocol.dynamicPolicyName = ...
    'static-vs-dynamic-v91-current-physical';
protocol.staticPolicyName = ...
    'static-vs-dynamic-v91-all-time-physical-static';
protocol.dominantWeight = source.dominantWeight;
protocol.residualWeight = source.sourceWeight;
protocol.receiverMode = 'support-renormalized';
protocol.minimumNotableFullGainPercent = 5.0;
protocol.minimumNotableFocusGainPercent = 5.0;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v91', 'static_vs_dynamic_routing');
protocol.deliverySeedOffset = source.deliverySeedOffset;
protocol.filterSeedOffset = source.filterSeedOffset;
protocol.routeExecutionAuthorized = true;
protocol.trackingOutcomeScoringAuthorized = true;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V91 isolates routing adaptation on the frozen braided-handover ', ...
    'scenes. Both arms use always-heavy posterior exchange, explicit ', ...
    'support-renormalized missing-label semantics, two distinct inputs ', ...
    'per receiver, the same self/dominant/residual weight multiset, the ', ...
    'same directed-message budget, measurements, delivery uniforms and ', ...
    'filter seed. The dynamic arm selects a path-tree residual tour from ', ...
    'the current physical graph. The static arm freezes the same route ', ...
    'selected by the dynamic arm at the first round, must return that ', ...
    'identical route at every later time, and must remain physical over ', ...
    'the complete episode. This is opened development evidence, not ', ...
    'validation.'];
end
