function protocol = getTrackingAlignedRoutingLeverageV58Protocol()
% GETTRACKINGALIGNEDROUTINGLEVERAGEV58PROTOCOL V58 attribution boundary.

protocol = struct();
protocol.id = 'tracking-aligned-routing-leverage-v58-v1';
protocol.contractVersion = ...
    'tracking-aligned-routing-leverage-v58-protocol-v1';
protocol.referencePolicyName = ...
    'formation-h3-fixed-ccw-reference-v1';
protocol.filterSeedOffset = 100000;
protocol.horizonSteps = 3;
protocol.retentionDebtOnFraction = 0.02;
protocol.cases = [ ...
    caseEntry( ...
        'radial-opened-attribution', ...
        'm24-formation-fov', 211, 24, 4, ...
        [60, 72, 104, 124]), ...
    caseEntry( ...
        'convoy-opened-development', ...
        'm24-formation-fov-convoy', 1201, 24, 4, ...
        40:4:136)];
protocol.presets = {protocol.cases.presetName};
protocol.allSeeds = unique([protocol.cases.seed], 'stable');
protocol.snapshotTimes = unique( ...
    [protocol.cases.snapshotTimes], 'stable');
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v58', 'leverage_attribution', 'cache');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v58', 'leverage_attribution');
protocol.referenceStateGenerationAuthorized = true;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.x36OutcomeOpeningAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V58 may reconstruct fixed-reference posterior states only for the ', ...
    'registered radial seed-211 attribution anchors and the opened M24 ', ...
    'convoy seed-1201 candidate grid. The runtime receives no target ', ...
    'truth and this protocol does not authorize tracking scoring, X36 ', ...
    'outcomes, model training, held-out seeds, or validation claims.'];
end

function value = caseEntry( ...
        caseId, presetName, seed, nodeCount, formationCount, snapshotTimes)
value = struct( ...
    'caseId', caseId, ...
    'presetName', presetName, ...
    'seed', seed, ...
    'nodeCount', nodeCount, ...
    'formationCount', formationCount, ...
    'snapshotTimes', reshape(snapshotTimes, 1, []));
end
