function protocol = ...
    getTrackingAlignedX36RiskCoverageHeadroomV64Protocol()
% GETTRACKINGALIGNEDX36RISKCOVERAGEHEADROOMV64PROTOCOL Scale-aware gate.

base = getTrackingAlignedX36ScheduleHeadroomV63Protocol();
protocol = base;
protocol.id = 'tracking-aligned-x36-risk-coverage-v64-v1';
protocol.contractVersion = ...
    'tracking-aligned-x36-risk-coverage-v64-protocol-v1';
protocol.primaryAnchorTime = 72;
protocol.riskCoverageTargetFraction = 0.80;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v64', 'x36_risk_coverage_headroom');
protocol.evidenceBoundary = [ ...
    'V64 reuses the opened X36 seed-211 states and the V63 current-only ', ...
    'support scores. It selects the smallest ranked prefix covering at ', ...
    'least 80% of positive observable rescue mass without reading truth, ', ...
    'future measurements, or same-state tracking outcomes. The t=72 ', ...
    'paired result opened later registered development anchors under the ', ...
    'same frozen selector. No validation or model-training claim is ', ...
    'authorized.'];
end
