function protocol = ...
    getTrackingAlignedRoutingLeverageHeadroomV59Protocol()
% GETTRACKINGALIGNEDROUTINGLEVERAGEHEADROOMV59PROTOCOL Fresh M24 gate.

protocol = struct();
protocol.id = 'tracking-aligned-routing-leverage-headroom-v59-v1';
protocol.contractVersion = ...
    'tracking-aligned-routing-leverage-headroom-v59-protocol-v1';
protocol.presetName = 'm24-formation-fov-convoy';
protocol.seed = 1201;
protocol.expectedNodeCount = 24;
protocol.expectedFormationCount = 4;
protocol.eventTimes = [40, 88, 128];
protocol.horizonSteps = 3;
protocol.filterSeedOffset = 100000;
protocol.interventionDurationSteps = 1;
protocol.interventionBankType = ...
    'tracking-aligned-formation-protection-joint';
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v58', 'leverage_attribution', ...
    'cache_convoy_grid');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v59', 'event_headroom');
protocol.minimumMeanGainPercent = 5;
protocol.minimumFormationGainPercent = 0;
protocol.minimumWorstSensorGainPercent = 0;
protocol.minimumConsensusGainPercent = 0;
protocol.minimumAttemptedByteSavingPercent = 0;
protocol.trackingOutcomeScoringAuthorized = true;
protocol.x36OutcomeOpeningAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V59 opens only the three truth-free V58-selected M24 convoy event ', ...
    'times 40, 88, and 128. At each state it enumerates every safe ', ...
    'formation cross-input protection subset for one step followed by ', ...
    'the registered reference route and scores an H=3 development ', ...
    'outcome. It does not authorize X36, model training, held-out seeds, ', ...
    'or validation claims.'];
end
