function protocol = getTrackingAlignedFormationH3HeadroomProtocol()
% GETTRACKINGALIGNEDFORMATIONH3HEADROOMPROTOCOL V56 first-scale gate.

protocol = struct();
protocol.id = 'tracking-aligned-formation-h3-v56-headroom-v1';
protocol.contractVersion = ...
    'tracking-aligned-formation-h3-headroom-protocol-v1';
protocol.presets = { ...
    'm24-formation-fov-convoy', ...
    'x36-formation-fov-convoy'};
protocol.expectedNodeCounts = [24, 36];
protocol.expectedFormationCounts = [4, 6];
protocol.allSeeds = 1201;
protocol.snapshotTimes = [60, 100, 132];
protocol.horizonSteps = 3;
protocol.filterSeedOffset = 100000;
protocol.cacheRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v56', 'headroom_development', 'cache');
protocol.screenRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v56', 'headroom_development', 'screens');
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v56', 'headroom_development');
protocol.minimumMeanGainPercent = 5;
protocol.minimumPositiveStateFraction = 2 / 3;
protocol.requiredScaleNodeCounts = [24, 36];
protocol.primarySceneMatrix = { ...
    'm24-formation-fov', 'x36-formation-fov'; ...
    'm24-formation-fov-convoy', 'x36-formation-fov-convoy'; ...
    'm24-formation-fov-relay', 'x36-formation-fov-relay'; ...
    'm24-formation-fov-merge-split', ...
        'x36-formation-fov-merge-split'; ...
    'm24-formation-fov-curved-corridor', ...
        'x36-formation-fov-curved-corridor'};
protocol.stressSceneMatrix = { ...
    'm24-formation-fov-crossing', ...
        'x36-formation-fov-crossing'};
protocol.openedDevelopmentEvidenceOnly = true;
protocol.modelTrainingAuthorizedBeforeGate = false;
protocol.validationClaimAllowed = false;
protocol.evidenceBoundary = [ ...
    'Seed 1201 and the three convoy anchors are V56 opened development ', ...
    'states. They decide only whether the combined local action bank has ', ...
    'enough M24/X36 tracking headroom to justify model training. The ', ...
    'method, model, and confidence calibration remain unfrozen; no held-', ...
    'out or multi-scene generalization claim is allowed.'];
end
