function protocol = getTimeExpandedPathSelectiveV88Protocol()
% GETTIMEEXPANDEDPATHSELECTIVEV88PROTOCOL Frozen path-selective outcome.

source = getTimeExpandedEffectiveKlaGraphV87Protocol();
runtimeSource = getTemporalAcquireBroadcastV86Protocol();
cases = source.cases;
cases(1).broadcastReceiverIndices = [7, 9, 10, 12];
cases(1).sourceEnabledPathCount = 4;
cases(1).sourceCandidatePathCount = 5;
cases(1).sourceAggregateExistenceNetFraction = ...
    0.01438995;
cases(1).sourceAggregateStateNetFraction = ...
    0.00012664;
cases(2).broadcastReceiverIndices = [19, 20, 21, 22, 24];
cases(2).sourceEnabledPathCount = 5;
cases(2).sourceCandidatePathCount = 5;
cases(2).sourceAggregateExistenceNetFraction = ...
    0.27756163;
cases(2).sourceAggregateStateNetFraction = ...
    0.00121703;

protocol = struct();
protocol.id = 'time-expanded-path-selective-primary-h3-v88-v1';
protocol.contractVersion = ...
    'time-expanded-path-selective-primary-h3-v88-protocol-v1';
protocol.sourceProtocolId = source.id;
protocol.sourceFindingCommit = '058b656';
protocol.cases = cases;
protocol.horizonSteps = 3;
protocol.actionSequenceIndices = [1, 1, 1; 2, 3, 1];
protocol.filterSeedOffset = runtimeSource.filterSeedOffset;
protocol.sourceWeight = source.sourceWeight;
protocol.dominantWeight = source.dominantWeight;
protocol.expectedFormationSize = 6;
protocol.cacheRoot = source.cacheRoot;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v88', 'time_expanded_path_selective_primary_h3');
protocol.outcomePolicyName = ...
    'time-expanded-path-selective-primary-h3-v88-v1';
protocol.minimumMeanTrackingGainPercent = 5.0;
protocol.minimumWorstSensorGainPercent = 0.0;
protocol.minimumFormationGainPercent = 0.0;
protocol.minimumWindowConsensusGainPercent = 0.0;
protocol.minimumTerminalConsensusGainPercent = 0.0;
protocol.minimumAttemptedByteSavingPercent = -1.0;
protocol.exactMessageCountParityRequired = true;
protocol.selectedRollingB3Required = true;
protocol.trackingOutcomeScoringAuthorized = true;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V88 opens only the M24 t=104 and X36 t=112 primary states after ', ...
    'the V87 current-only two-hop mixture-aware KLA source gate was ', ...
    'frozen. The candidate sequence remains acquire, broadcast, ', ...
    'reference, but the broadcast step changes only receiver rows with ', ...
    'positive V87 existence survival, nonnegative state alignment, no ', ...
    'supported downward crossing and bounded supported harm. M24 ', ...
    'broadcasts to receivers 7, 9, 10 and 12 while receiver 8 keeps its ', ...
    'reference row; X36 broadcasts to receivers 19, 20, 21, 22 and 24. ', ...
    'Every row preserves its positive-weight multiset and message count. ', ...
    'Reference and candidate share the same predecision posterior, ', ...
    'measurements, delivery draws and filter RNG. Truth and future ', ...
    'measurements score paired H=3 tracking only after these masks are ', ...
    'frozen. This is opened development evidence, not validation or ', ...
    'model training.'];
end
