function protocol = getTaskRiskInputProtectionV92Protocol()
% GETTASKRISKINPUTPROTECTIONV92PROTOCOL Frozen current-only headroom gate.

v90 = getPartialLabelFusionSemanticsV90Protocol();
v89 = getRepeatedMultiGatewayHandoverV89Protocol();
protection = getFormationBackboneBundleStaggeredRecoveryPolicyConfig();
protocol = struct();
protocol.id = 'task-risk-input-protection-v92-v1';
protocol.contractVersion = ...
    'task-risk-input-protection-v92-protocol-v1';
protocol.sourceReceiverProtocolId = v90.id;
protocol.sourceRoutingFailureCommit = '42a675c';
protocol.presets = v90.presets;
protocol.allSeeds = v90.allSeeds;
protocol.snapshotTimes = v89.snapshotTimes;
protocol.expectedNodeCounts = v90.expectedNodeCounts;
protocol.expectedFormationCounts = v90.expectedFormationCounts;
protocol.referenceArmId = v90.referenceArmId;
protocol.receiverMode = 'fov-aware-censored';
protocol.referenceMode = 'current-physical-tree';
protocol.protectionPolicy = protection;
protocol.riskOptions = struct( ...
    'existenceWeight', 0.50, ...
    'localizationWeight', 0.50, ...
    'receiverTailFraction', 0.25, ...
    'receiverTailWeight', 0.50);
protocol.minimumTaskRiskGainPercent = 0.0;
protocol.minimumWorstReceiverRiskGainPercent = 0.0;
protocol.minimumWorstFormationRiskGainPercent = 0.0;
protocol.minimumActionableTimeFraction = 0.10;
protocol.minimumPeakSafeTaskRiskGainPercent = 1.0;
protocol.minimumMedianPositiveTaskRiskGainPercent = 0.25;
protocol.minimumFullEpisodeMeanGainPercent = 5.0;
protocol.minimumFocusWindowMeanGainPercent = 5.0;
protocol.cacheRoot = v89.cacheRoot;
protocol.outputRoot = fullfile( ...
    'RUN', 'GA', 'dynamic_topology', 'evidence', ...
    'tracking_aligned_v92', 'task_risk_input_protection_headroom');
protocol.routeExecutionAuthorized = false;
protocol.trackingOutcomeScoringAuthorized = false;
protocol.modelTrainingAuthorized = false;
protocol.validationClaimAllowed = false;
protocol.openedDevelopmentEvidenceOnly = true;
protocol.evidenceBoundary = [ ...
    'V92 uses only current local LMB posteriors, the current physical ', ...
    'graph, current link probabilities and two past selected topology ', ...
    'pages. It compares the current physical-tree reference with one ', ...
    'formation input-bundle suspension at a time under the FoV-aware ', ...
    'censored missing-label receiver. Delivery outcomes and the actual ', ...
    'heavy-payload fusion operator are enumerated without target truth ', ...
    'or future observations. The posterior task risk is an interpretable ', ...
    'one-round proxy, not E-OSPA and not a recursive tracking guarantee. ', ...
    'This scan can authorize implementation only; it cannot establish a ', ...
    'tracking, validation or learning claim.'];
end
