function detected = ...
        isAdaptiveLabelBoundaryEntryV115ExecutionContext(context)
% ISADAPTIVELABELBOUNDARYENTRYV115EXECUTIONCONTEXT Identify V115.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'adaptive-label-boundary-entry-v115-context-v1');
end
