function detected = ...
        isAlternatingShieldBroadcastV111ExecutionContext(context)
% ISALTERNATINGSHIELDBROADCASTV111EXECUTIONCONTEXT Identify V111.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'alternating-shield-broadcast-v111-context-v1');
end
