function detected = isAsymmetricEtaRetentionV267ExecutionContext(context)
% ISASYMMETRICETARETENTIONV267EXECUTIONCONTEXT Recognize V267.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'asymmetric-eta-retention-v267-context-v1');
end
