function detected = isBraidedHandoverH3V84ExecutionContext(context)
% ISBRAIDEDHANDOVERH3V84EXECUTIONCONTEXT Identify V84 paired requests.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'braided-handover-primary-h3-v84-context-v1');
end
