function detected = ...
        isCausalMinimumFormationBackboneV242ExecutionContext(context)
% ISCAUSALMINIMUMFORMATIONBACKBONEV242EXECUTIONCONTEXT Recognize V242.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'causal-minimum-formation-backbone-v242-context-v1');
end
