function detected = ...
        isCorrectedStaticRoutingBaselineV227ExecutionContext(context)
% ISCORRECTEDSTATICROUTINGBASELINEV227EXECUTIONCONTEXT Recognize V227.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'corrected-static-routing-v227-full-episode-context-v1');
end
