function detected = isCombinedOutputSafetyV139ExecutionContext(context)
% ISCOMBINEDOUTPUTSAFETYV139EXECUTIONCONTEXT Identify V139 runs.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'combined-output-safety-v139-execution-context-v1');
end
