function detected = isCounterfactualEdgeRoleV146ExecutionContext(context)
% ISCOUNTERFACTUALEDGEROLEV146EXECUTIONCONTEXT Identify V146.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'counterfactual-edge-role-v146-execution-context-v1');
end
