function detected = ...
        isExistenceMarginBeneficiaryV269ExecutionContext(context)
% ISEXISTENCEMARGINBENEFICIARYV269EXECUTIONCONTEXT Recognize V269.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'existence-margin-beneficiary-v269-context-v1');
end
