function detected = ...
        isFiniteDurationAbstentionV112ExecutionContext(context)
% ISFINITEDURATIONABSTENTIONV112EXECUTIONCONTEXT Identify V112.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'finite-duration-abstention-v112-context-v1');
end
