function value = ...
    isFormationB4V52PairedTrackingDevelopmentContext(context)
% ISFORMATIONB4V52PAIREDTRACKINGDEVELOPMENTCONTEXT Recognize V52 context.

value = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    strcmp(context.contractVersion, ...
        'formation-b4-v52-paired-tracking-development-context-v1');
end
