function detected = ...
    isFormationB4V49PairedTrackingDevelopmentContext(context)
% ISFORMATIONB4V49PAIREDTRACKINGDEVELOPMENTCONTEXT Identify the thin V49 gate.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'formation-b4-v49-paired-tracking-development-context-v1');
end
