function detected = isIndependentLocalAnchorV128ExecutionContext(context)
% ISINDEPENDENTLOCALANCHORV128EXECUTIONCONTEXT Identify V128.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'independent-local-anchor-v128-context-v1');
end
