function detected = ...
        isIndependentM24GatewayTeacherV252ExecutionContext(context)
% ISINDEPENDENTM24GATEWAYTEACHERV252EXECUTIONCONTEXT Recognize V252.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'independent-m24-gateway-teacher-v252-context-v1');
end
