function detected = isInfluenceConeCarrierV113ExecutionContext(context)
% ISINFLUENCECONECARRIERV113EXECUTIONCONTEXT Identify V113.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'influence-cone-carrier-v113-context-v1');
end
