function detected = ...
        isInitialDynamicRouteFreezeV237ExecutionContext(context)
% ISINITIALDYNAMICROUTEFREEZEV237EXECUTIONCONTEXT Recognize V237.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'initial-dynamic-route-freeze-v237-context-v1');
end
