function detected = ...
    isInfluenceAwareDecisionBreadthV66ReferenceExecutionContext(context)
% ISINFLUENCEAWAREDECISIONBREADTHV66REFERENCEEXECUTIONCONTEXT Identify V66.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'influence-aware-decision-breadth-v66-reference-context-v1');
end
