function detected = ...
        isInfluenceConeBoundaryShieldV114ExecutionContext(context)
% ISINFLUENCECONEBOUNDARYSHIELDV114EXECUTIONCONTEXT Identify V114.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'influence-cone-boundary-shield-v114-context-v1');
end
