function detected = ...
        isLabelRoleMultiplexedSinglePayloadV148ExecutionContext(context)
% ISLABELROLEMULTIPLEXEDSINGLEPAYLOADV148EXECUTIONCONTEXT Detect permit.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'v148-label-role-multiplexed-execution-context-v1');
end
