function detected = isMinimalRiskCycleV264ExecutionContext(context)
% ISMINIMALRISKCYCLEV264EXECUTIONCONTEXT Recognize V264.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'minimal-risk-cycle-v264-context-v1');
end
