function detected = isMixedCarrierInsertionV121ExecutionContext(context)
% ISMIXEDCARRIERINSERTIONV121EXECUTIONCONTEXT Identify V121.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'mixed-carrier-insertion-v121-context-v1');
end
