function detected = ...
    isObservationSupportedSetSafeV194ExecutionContext(context)
% ISOBSERVATIONSUPPORTEDSETSAFEV194EXECUTIONCONTEXT Identify V194.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'observation-supported-set-safe-v194-context-v1');
end

