function detected = ...
    isOnlinePositiveNetPropagationV100ExecutionContext(context)
% ISONLINEPOSITIVENETPROPAGATIONV100EXECUTIONCONTEXT Identify V100.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'online-positive-net-propagation-v100-context-v1');
end
