function detected = isOneShotPacketEpisodeV270ExecutionContext(context)
% ISONESHOTPACKETEPISODEV270EXECUTIONCONTEXT Recognize V270.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'one-shot-packet-episode-v270-context-v1');
end
