function detected = isOpenedSafeFormationV110ExecutionContext(context)
% ISOPENEDSAFEFORMATIONV110EXECUTIONCONTEXT Identify V110.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'opened-safe-formation-v110-context-v1');
end
