function valid = ...
    isOutputAlignedSafeGraphNeighborhoodV155ExecutionContext(context)
% ISOUTPUTALIGNEDSAFEGRAPHNEIGHBORHOODV155EXECUTIONCONTEXT Identify permit.

valid = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'safe-graph-neighborhood-v155-execution-context-v1');
end
