function detected = ...
    isOutputAlignedLabelEffectiveOracleV150ExecutionContext(context)
% ISOUTPUTALIGNEDLABELEFFECTIVEORACLEV150EXECUTIONCONTEXT Identify V150.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'output-aligned-label-effective-oracle-v150-context-v1');
end
