function detected = ...
        isParetoSafeResidualAugmentationV246ExecutionContext(context)
% ISPARETOSAFERESIDUALAUGMENTATIONV246EXECUTIONCONTEXT Recognize V246.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'pareto-safe-residual-augmentation-v246-context-v1');
end
