function detected = isPostFusionLabelReadoutV138ExecutionContext(context)
% ISPOSTFUSIONLABELREADOUTV138EXECUTIONCONTEXT Identify V138 runs.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'post-fusion-label-readout-v138-execution-context-v1');
end
