function detected = ...
        isPositiveValueReferenceLabelV157ExecutionContext(context)
% ISPOSITIVEVALUEREFERENCELABELV157EXECUTIONCONTEXT Identify V157.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'positive-value-reference-label-v157-context-v1');
end
