function detected = ...
        isProjectedFormationRowCompositionV123ExecutionContext(context)
% ISPROJECTEDFORMATIONROWCOMPOSITIONV123EXECUTIONCONTEXT Identify V123.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'projected-formation-row-composition-v123-context-v1');
end
