function detected = ...
        isRiskFormationLightNetworkAnchorV132ExecutionContext(context)
% ISRISKFORMATIONLIGHTNETWORKANCHORV132EXECUTIONCONTEXT Identify V132.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'risk-formation-light-network-anchor-v132-context-v1');
end
