function detected = ...
        isRiskRootedMultiSourceTreeV263ExecutionContext(context)
% ISRISKROOTEDMULTISOURCETREEV263EXECUTIONCONTEXT Recognize V263.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'risk-rooted-multi-source-tree-v263-context-v1');
end
