function detected = ...
        isRiskEpisodeLatchedFormationShortcutV262ExecutionContext(context)
% ISRISKEPISODELATCHEDFORMATIONSHORTCUTV262EXECUTIONCONTEXT Recognize V262.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'risk-episode-latched-formation-shortcut-v262-context-v1');
end

