function detected = ...
        isRolloutAwareOneHopSafeLabelV179ExecutionContext(context)
% ISROLLOUTAWAREONEHOPSAFELABELV179EXECUTIONCONTEXT Detect V179 context.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'rollout-aware-one-hop-safe-label-v179-context-v1');
end
