function detected = ...
    isSafeGraphCodebookOracleV152ExecutionContext(context)
% ISSAFEGRAPHCODEBOOKORACLEV152EXECUTIONCONTEXT Identify V152 permits.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'safe-graph-codebook-oracle-v152-execution-context-v1');
end
