function detected = ...
    isSafeGraphOptionDwellV154ExecutionContext(context)
% ISSAFEGRAPHOPTIONDWELLV154EXECUTIONCONTEXT Identify V154 permits.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'safe-graph-option-dwell-v154-execution-context-v1');
end
