function detected = isShieldBroadcastV102ExecutionContext(context)
% ISSHIELDBROADCASTV102EXECUTIONCONTEXT Identify V102.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'shield-broadcast-v102-context-v1');
end
