function detected = ...
    isSignedMergeSplitOpportunityV69ReferenceExecutionContext(context)
% ISSIGNEDMERGESPLITOPPORTUNITYV69REFERENCEEXECUTIONCONTEXT Identify V69.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'signed-merge-split-opportunity-v69-reference-context-v1');
end
