function detected = ...
        isSourcePreservingLabelPacketV268ExecutionContext(context)
% ISSOURCEPRESERVINGLABELPACKETV268EXECUTIONCONTEXT Recognize V268.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'source-preserving-label-packet-v268-context-v1');
end
