function detected = isSparsePosteriorCorrectionV130ExecutionContext(context)
% ISSPARSEPOSTERIORCORRECTIONV130EXECUTIONCONTEXT Identify V130.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'sparse-posterior-correction-v130-context-v1');
end
