function detected = ...
        isSparseReferenceLabelRollbackV156ExecutionContext(context)
% ISSPARSEREFERENCELABELROLLBACKV156EXECUTIONCONTEXT Identify V156.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'sparse-reference-label-rollback-v156-context-v1');
end
