function detected = ...
    isSpatialLabelSupportDebtRoutingV147ExecutionContext(context)
% ISSPATIALLABELSUPPORTDEBTROUTINGV147EXECUTIONCONTEXT Detect V147 permit.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'v147-spatial-label-support-debt-routing-context-v1');
end
