function detected = ...
    isStaticVsDynamicRoutingV91ExecutionContext(context)
% ISSTATICVSDYNAMICROUTINGV91EXECUTIONCONTEXT Recognize V91 gate.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'static-vs-dynamic-routing-v91-full-episode-context-v1');
end
