function detected = ...
        isSupportAwareFormationControllerV206ExecutionContext(context)
% ISSUPPORTAWAREFORMATIONCONTROLLERV206EXECUTIONCONTEXT Identify V206.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'support-aware-formation-controller-v206-context-v1');
end
