function detected = ...
        isTemporallyBalancedMinimumBackboneV272ExecutionContext(context)
% ISTEMPORALLYBALANCEDMINIMUMBACKBONEV272EXECUTIONCONTEXT Recognize V272.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'temporally-balanced-minimum-backbone-v272-context-v1');
end
