function detected = ...
    isTemporalObservationSupportedRepairV198ExecutionContext(context)
% ISTEMPORALOBSERVATIONSUPPORTEDREPAIRV198EXECUTIONCONTEXT Identify V198.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'temporal-observation-supported-repair-v198-context-v1');
end
