function detected = ...
        isTemporalHybridFormationRepairV186ExecutionContext(context)
% ISTEMPORALHYBRIDFORMATIONREPAIRV186EXECUTIONCONTEXT Detect V186.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'temporal-hybrid-formation-repair-v186-context-v1');
end
