function detected = isTimeExpandedDualPathV119ExecutionContext(context)
% ISTIMEEXPANDEDDUALPATHV119EXECUTIONCONTEXT Identify V119.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'time-expanded-dual-path-v119-context-v1');
end
