function detected = ...
    isTrackingAlignedNetworkAdditiveV65ExecutionContext(context)
% ISTRACKINGALIGNEDNETWORKADDITIVEV65EXECUTIONCONTEXT Identify V65.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'tracking-aligned-network-additive-v65-context-v1');
end
