function detected = ...
    isTrackingAlignedLayeredLabelHeadroomV62ExecutionContext(context)
% ISTRACKINGALIGNEDLAYEREDLABELHEADROOMV62EXECUTIONCONTEXT Identify V62.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'tracking-aligned-layered-label-headroom-v62-context-v1');
end
