function detected = ...
    isTrackingAlignedX36ScheduleHeadroomV63ExecutionContext(context)
% ISTRACKINGALIGNEDX36SCHEDULEHEADROOMV63EXECUTIONCONTEXT Identify V63.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'tracking-aligned-x36-schedule-headroom-v63-context-v1');
end
