function detected = isTrackingAlignedFormationH3ExecutionContext(context)
% ISTRACKINGALIGNEDFORMATIONH3EXECUTIONCONTEXT Identify the V56 boundary.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'tracking-aligned-formation-h3-execution-context-v1');
end
