function detected = ...
        isUndercountOnlyCardinalityAugmentationV141ExecutionContext(context)
% ISUNDERCOUNTONLYCARDINALITYAUGMENTATIONV141EXECUTIONCONTEXT Identify V141.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'undercount-only-cardinality-v141-execution-context-v1');
end
