function detected = ...
        isUpstreamBoundaryReleaseV122ExecutionContext(context)
% ISUPSTREAMBOUNDARYRELEASEV122EXECUTIONCONTEXT Identify V122.

detected = isstruct(context) && isscalar(context) && ...
    isfield(context, 'contractVersion') && ...
    ischar(context.contractVersion) && ...
    strcmp(context.contractVersion, ...
        'upstream-boundary-release-v122-context-v1');
end
