function bundle = loadCounterfactualRegretGateV133Examples( ...
        shardPaths, expectedSplit, protocol, modelSpec)
% LOADCOUNTERFACTUALREGRETGATEV133EXAMPLES Join whole-trajectory shards.

if nargin < 3 || isempty(protocol)
    protocol = getCounterfactualRegretGateV133Protocol();
end
if nargin < 4 || isempty(modelSpec)
    modelSpec = getCounterfactualRegretGateV133ModelSpec();
end
if ischar(shardPaths)
    shardPaths = {shardPaths};
end
expectedSplit = lower(strrep(char(expectedSplit), '_', '-'));
if ~iscell(shardPaths) || isempty(shardPaths) || ...
        ~ismember(expectedSplit, {'development', 'calibration'})
    error('CounterfactualRegretV133:InvalidDatasetRequest', ...
        'V133 requires nonempty whole-trajectory shard paths.');
end

X = zeros(0, numel(modelSpec.featureNames));
y = false(0, 1);
actionGain = zeros(0, 1);
maximumRegret = zeros(0, 1);
scaleName = cell(0, 1);
trajectoryKey = cell(0, 1);
presetName = cell(0, 1);
seed = zeros(0, 1);
anchorTime = zeros(0, 1);
formationMetadata = zeros(0, 1);
fullFeatureContractSha256 = '';
seenTrajectoryKeys = cell(1, 0);
for shardIdx = 1:numel(shardPaths)
    path = shardPaths{shardIdx};
    if ~ischar(path) || exist(path, 'file') ~= 2
        error('CounterfactualRegretV133:MissingDatasetShard', ...
            'A requested V133 teacher shard is missing.');
    end
    loaded = load(path, 'shard');
    if ~isfield(loaded, 'shard')
        error('CounterfactualRegretV133:InvalidDatasetShard', ...
            'A V133 dataset file lacks its shard variable.');
    end
    shard = loaded.shard;
    required = { ...
        'contractVersion', 'protocolId', 'presetName', 'scaleName', ...
        'seed', 'evidenceSplit', 'trajectoryGroupingKey', ...
        'featureContractSha256', 'examples', ...
        'policyTruthUsed', 'policyFutureOutcomeUsed', ...
        'teacherTruthUsedOfflineOnly', ...
        'teacherFutureOutcomeUsedOfflineOnly'};
    if ~isstruct(shard) || ~isscalar(shard) || ...
            ~all(isfield(shard, required)) || ...
            ~strcmp(shard.contractVersion, ...
                ['counterfactual-regret-gate-v133-', ...
                 'teacher-shard-v1']) || ...
            ~strcmp(shard.protocolId, protocol.id) || ...
            ~strcmp(shard.evidenceSplit, expectedSplit) || ...
            shard.policyTruthUsed || shard.policyFutureOutcomeUsed || ...
            ~shard.teacherTruthUsedOfflineOnly || ...
            ~shard.teacherFutureOutcomeUsedOfflineOnly || ...
            isempty(shard.examples) || ...
            any(strcmp(seenTrajectoryKeys, ...
                shard.trajectoryGroupingKey))
        error('CounterfactualRegretV133:InvalidDatasetShard', ...
            'A V133 shard violates its trajectory or causal contract.');
    end
    seenTrajectoryKeys{end + 1} = shard.trajectoryGroupingKey; %#ok<AGROW>
    if isempty(fullFeatureContractSha256)
        fullFeatureContractSha256 = shard.featureContractSha256;
    elseif ~strcmp(fullFeatureContractSha256, ...
            shard.featureContractSha256)
        error('CounterfactualRegretV133:FeatureContractDrift', ...
            'V133 shards do not share the same full feature columns.');
    end
    for exampleIdx = 1:numel(shard.examples)
        example = shard.examples(exampleIdx);
        [present, columns] = ismember( ...
            modelSpec.featureNames, example.featureNames);
        if any(~present) || numel(unique(columns)) ~= numel(columns) || ...
                ~strcmp(example.featureContractSha256, ...
                    shard.featureContractSha256) || ...
                example.policyTruthUsed || ...
                example.policyFutureOutcomeUsed || ...
                ~example.teacherTruthUsedOfflineOnly || ...
                ~example.teacherFutureOutcomeUsedOfflineOnly || ...
                ~isfield(example.teacherLabel, 'harmful') || ...
                ~isfield(example.teacherLabel, 'actionGainPercent') || ...
                ~isfield(example.teacherLabel, 'maximumRegret')
            error('CounterfactualRegretV133:InvalidDatasetExample', ...
                'A V133 example violates the feature or label contract.');
        end
        X(end + 1, :) = example.featureValues(columns); %#ok<AGROW>
        y(end + 1, 1) = logical( ...
            example.teacherLabel.harmful); %#ok<AGROW>
        actionGain(end + 1, 1) = ...
            example.teacherLabel.actionGainPercent; %#ok<AGROW>
        maximumRegret(end + 1, 1) = ...
            example.teacherLabel.maximumRegret; %#ok<AGROW>
        scaleName{end + 1, 1} = shard.scaleName; %#ok<AGROW>
        trajectoryKey{end + 1, 1} = ...
            shard.trajectoryGroupingKey; %#ok<AGROW>
        presetName{end + 1, 1} = shard.presetName; %#ok<AGROW>
        seed(end + 1, 1) = shard.seed; %#ok<AGROW>
        anchorTime(end + 1, 1) = example.anchorTime; %#ok<AGROW>
        formationMetadata(end + 1, 1) = example. ...
            protectedFormationIdTeacherMetadataOnly; %#ok<AGROW>
    end
end
if any(~isfinite(X(:))) || any(~isfinite(actionGain)) || ...
        any(~isfinite(maximumRegret)) || ...
        numel(unique(trajectoryKey)) ~= numel(shardPaths)
    error('CounterfactualRegretV133:InvalidDatasetBundle', ...
        'The assembled V133 dataset is non-finite or duplicated.');
end
trajectoryWeights = zeros(size(y));
uniqueKeys = unique(trajectoryKey, 'stable');
for keyIdx = 1:numel(uniqueKeys)
    members = strcmp(trajectoryKey, uniqueKeys{keyIdx});
    trajectoryWeights(members) = 1 / nnz(members);
end
trajectoryWeights = trajectoryWeights / sum(trajectoryWeights);

bundle = struct();
bundle.contractVersion = ...
    'counterfactual-regret-gate-v133-model-dataset-v1';
bundle.protocolId = protocol.id;
bundle.evidenceSplit = expectedSplit;
bundle.shardPaths = reshape(shardPaths, 1, []);
bundle.fullFeatureContractSha256 = fullFeatureContractSha256;
bundle.modelFeatureNames = modelSpec.featureNames;
bundle.modelFeatureContractSha256 = ...
    modelSpec.featureContractSha256;
bundle.X = X;
bundle.y = y;
bundle.actionGainPercent = actionGain;
bundle.maximumRegret = maximumRegret;
bundle.scaleName = scaleName;
bundle.trajectoryKey = trajectoryKey;
bundle.presetName = presetName;
bundle.seed = seed;
bundle.anchorTimeTeacherMetadataOnly = anchorTime;
bundle.formationIdTeacherMetadataOnly = formationMetadata;
bundle.sampleWeight = trajectoryWeights;
bundle.exampleCount = numel(y);
bundle.trajectoryCount = numel(uniqueKeys);
bundle.truthUsedAsFeature = false;
bundle.futureOutcomeUsedAsFeature = false;
bundle.seedIdentifierUsedAsFeature = false;
bundle.absoluteTimeUsedAsFeature = false;
bundle.fixedFormationIdentifierUsedAsFeature = false;
end
