function [permit, preflight, releaseDescriptor] = ...
    loadFormationStaggeredRecoveryX36OutcomePermit()
% LOADFORMATIONSTAGGEREDRECOVERYX36OUTCOMEPERMIT Load the exact v3 gate.

permit = getFormationStaggeredRecoveryX36OutcomePermit();
assertPermitEnvelope(permit);

repoRoot = fileparts(fileparts(mfilename('fullpath')));
originalDirectory = cd(repoRoot);
directoryCleanup = onCleanup( ...
    @() cd(originalDirectory)); %#ok<NASGU>
assertNoGitHistoryOverrides(permit);
gitState = resolveResearchGitState();
if gitState.trackedWorktreeDirty || ...
        ~isempty(gitState.untrackedSourceFiles)
    error('X36OutcomePermit:DirtySourceRejected', ...
        ['The exact X36 outcome run requires a clean tracked and ', ...
         'MATLAB/Octave source state.']);
end
if isempty(regexp(gitState.commit, '^[0-9a-f]{40}$', 'once'))
    error('X36OutcomePermit:InvalidGitLineage', ...
        'The current Git commit is unavailable or malformed.');
end
releaseDescriptor = loadAndValidateReleaseDescriptor(permit, gitState);
assertAuthorizedExecutableDelta(permit, releaseDescriptor);
currentSourceManifest = buildCurrentExecutableSourceManifest();

requiredPaths = { ...
    permit.preflightPath, permit.preflightReportPath, ...
    permit.preflightCompletionMarkerPath};
for pathIdx = 1:numel(requiredPaths)
    if exist(requiredPaths{pathIdx}, 'file') ~= 2
        error('X36OutcomePermit:MissingPreflightArtifact', ...
            'A required formal v3 preflight artifact is unavailable.');
    end
end
if ~strcmp(computeFileSha256( ...
            permit.preflightCompletionMarkerPath), ...
        permit.preflightCompletionMarkerSha256)
    error('X36OutcomePermit:CompletionMarkerHashDrift', ...
        'The fixed formal v3 completion-marker hash changed.');
end
loadedMarker = load( ...
    permit.preflightCompletionMarkerPath, 'publication');
if ~isfield(loadedMarker, 'publication')
    error('X36OutcomePermit:MalformedCompletionMarker', ...
        'The completion marker lacks publication metadata.');
end
validateCompletionMarker(loadedMarker.publication, permit);
if ~strcmp(computeFileSha256(permit.preflightPath), ...
            permit.preflightSha256) || ...
        ~strcmp(computeFileSha256(permit.preflightReportPath), ...
            permit.preflightReportSha256)
    error('X36OutcomePermit:PreflightArtifactHashDrift', ...
        'The fixed formal v3 MAT/report hash changed.');
end

loaded = load(permit.preflightPath, 'preflight');
if ~isfield(loaded, 'preflight')
    error('X36OutcomePermit:MalformedPreflight', ...
        'The fixed MAT does not contain a preflight structure.');
end
preflight = loaded.preflight;
validateFormationStaggeredRecoveryX36OutcomePreflight( ...
    preflight, permit);
validateCurrentSourceAgainstPreflight( ...
    currentSourceManifest, preflight.sourceManifest, ...
    permit, releaseDescriptor);

currentProtocol = ...
    getFormationStaggeredRecoveryX36SourceProtocol();
try
    currentProtocolSha256 = ...
        computeCanonicalValueSha256(currentProtocol);
catch
    error('X36OutcomePermit:SourceProtocolDrift', ...
        'The current source protocol cannot be hashed canonically.');
end

if ~strcmp(currentProtocolSha256, ...
            permit.sourceProtocolCanonicalSha256) || ...
        ~isequaln(currentProtocol, preflight.protocol) || ...
        currentProtocol.trackingOutcomeRerunAuthorized || ...
        currentProtocol.x36OutcomeOpeningAuthorized
    error('X36OutcomePermit:SourceProtocolDrift', ...
        ['The current source protocol must equal the embedded v3 ', ...
         'protocol and remain tracking-outcome unauthorized.']);
end
assertRemoteReleasePublished( ...
    permit, releaseDescriptor, gitState.commit);
end

function releaseDescriptor = ...
        loadAndValidateReleaseDescriptor(permit, gitState)
descriptorPath = permit.releaseDescriptorPath;
if exist(descriptorPath, 'file') ~= 2
    error('X36OutcomePermit:MissingReleaseDescriptor', ...
        ['The executable gate is inert until its independent release ', ...
         'descriptor has been committed.']);
end
if ~isempty(strfind(descriptorPath, '''')) || ...
        ~isempty(regexp(descriptorPath, '[\r\n]', 'once'))
    error('X36OutcomePermit:MalformedReleaseDescriptor', ...
        'The fixed release-descriptor path is not shell-safe.');
end
[trackedStatus, ~] = system(sprintf( ...
    'git ls-files --error-unmatch -- ''%s'' >/dev/null 2>&1', ...
    descriptorPath));
if trackedStatus ~= 0
    error('X36OutcomePermit:UntrackedReleaseDescriptor', ...
        'The release descriptor must be committed in Git.');
end
assertRegularWorktreeBlobMatchesCommit( ...
    descriptorPath, gitState.commit);
loadedRelease = load(descriptorPath, 'releaseDescriptor');
if ~isfield(loadedRelease, 'releaseDescriptor')
    error('X36OutcomePermit:MalformedReleaseDescriptor', ...
        'The fixed release MAT lacks releaseDescriptor.');
end
releaseDescriptor = loadedRelease.releaseDescriptor;
assertExactFields(releaseDescriptor, { ...
    'contractVersion', 'createdAt', 'gateBaseGitCommit', ...
    'gateGitCommit', 'releaseTagName', 'releaseTagObjectId', ...
    'releaseTagTargetCommit', 'releaseRemoteUrl', ...
    'releaseBranchRef', 'remotePublicationRequired', ...
    'permitCanonicalSha256', ...
    'authorizedExecutablePaths', ...
    'authorizedExecutableRawSha256', ...
    'descriptorCanonicalSha256'}, ...
    'X36OutcomePermit:MalformedReleaseDescriptor', ...
    'The exact release-descriptor field set changed.');
descriptorPayload = rmfield( ...
    releaseDescriptor, 'descriptorCanonicalSha256');
try
    actualDescriptorSha256 = ...
        computeCanonicalValueSha256(descriptorPayload);
catch
    error('X36OutcomePermit:ReleaseDescriptorHashDrift', ...
        'The release descriptor cannot be hashed canonically.');
end
if ~strcmp(releaseDescriptor.contractVersion, ...
            permit.releaseDescriptorContractVersion) || ...
        ~ischar(releaseDescriptor.createdAt) || ...
        ~isrow(releaseDescriptor.createdAt) || ...
        ~strcmp(releaseDescriptor.gateBaseGitCommit, ...
            permit.gateBaseGitCommit) || ...
        ~isGitObjectId(releaseDescriptor.gateGitCommit) || ...
        ~strcmp(releaseDescriptor.releaseTagName, ...
            permit.releaseTagName) || ...
        ~isGitObjectId(releaseDescriptor.releaseTagObjectId) || ...
        ~strcmp(releaseDescriptor.releaseTagTargetCommit, ...
            releaseDescriptor.gateGitCommit) || ...
        ~strcmp(releaseDescriptor.releaseRemoteUrl, ...
            permit.releaseRemoteUrl) || ...
        ~strcmp(releaseDescriptor.releaseBranchRef, ...
            permit.releaseBranchRef) || ...
        ~isequal(releaseDescriptor.remotePublicationRequired, true) || ...
        ~strcmp(releaseDescriptor.permitCanonicalSha256, ...
            permit.permitCanonicalSha256) || ...
        ~isequal(releaseDescriptor.authorizedExecutablePaths, ...
            permit.authorizedPostPreflightExecutablePaths) || ...
        ~iscell(releaseDescriptor. ...
            authorizedExecutableRawSha256) || ...
        ~isequal(size(releaseDescriptor. ...
            authorizedExecutableRawSha256), ...
            size(permit.authorizedPostPreflightExecutablePaths)) || ...
        ~all(cellfun(@isSha256, releaseDescriptor. ...
            authorizedExecutableRawSha256)) || ...
        ~isSha256(releaseDescriptor.descriptorCanonicalSha256) || ...
        ~strcmp(actualDescriptorSha256, ...
            releaseDescriptor.descriptorCanonicalSha256)
    error('X36OutcomePermit:ReleaseDescriptorHashDrift', ...
        'The independent release descriptor changed.');
end

[tagTypeStatus, tagType] = system(sprintf( ...
    'git --no-replace-objects cat-file -t ''refs/tags/%s''', ...
    permit.releaseTagName));
[tagObjectStatus, tagObjectId] = system(sprintf( ...
    'git --no-replace-objects rev-parse --verify ''refs/tags/%s''', ...
    permit.releaseTagName));
[tagTargetStatus, tagTargetCommit] = system(sprintf( ...
    ['git --no-replace-objects rev-parse --verify ', ...
     '''refs/tags/%s^{commit}'''], ...
    permit.releaseTagName));
if tagTypeStatus ~= 0 || tagObjectStatus ~= 0 || ...
        tagTargetStatus ~= 0 || ...
        ~strcmp(strtrim(tagType), 'tag') || ...
        ~strcmp(strtrim(tagObjectId), ...
            releaseDescriptor.releaseTagObjectId) || ...
        ~strcmp(strtrim(tagTargetCommit), ...
            releaseDescriptor.gateGitCommit)
    error('X36OutcomePermit:ReleaseTagDrift', ...
        'The required annotated release tag is missing or changed.');
end

gateParents = resolveCommitAndParents( ...
    releaseDescriptor.gateGitCommit);
headParents = resolveCommitAndParents(gitState.commit);
if numel(gateParents) ~= 2 || ...
        ~strcmp(gateParents{1}, releaseDescriptor.gateGitCommit) || ...
        ~strcmp(gateParents{2}, permit.gateBaseGitCommit) || ...
        numel(headParents) ~= 2 || ...
        ~strcmp(headParents{1}, gitState.commit) || ...
        ~strcmp(headParents{2}, releaseDescriptor.gateGitCommit)
    error('X36OutcomePermit:ReleaseLineageDrift', ...
        ['The release must be exactly one descriptor-only commit atop ', ...
         'the tagged executable gate.']);
end
[releaseDiffStatus, releaseDiffListing] = system(sprintf( ...
    ['git --no-replace-objects diff --name-status ', ...
     '--diff-filter=ACDMRT %s..%s'], ...
    releaseDescriptor.gateGitCommit, gitState.commit));
if releaseDiffStatus ~= 0 || ...
        ~strcmp(strtrim(releaseDiffListing), ...
            sprintf('A\t%s', descriptorPath))
    error('X36OutcomePermit:ReleaseCommitDrift', ...
        ['The commit after the executable gate must add only the ', ...
         'fixed non-executable release descriptor.']);
end
for pathIdx = 1:numel( ...
        releaseDescriptor.authorizedExecutablePaths)
    path = releaseDescriptor.authorizedExecutablePaths{pathIdx};
    assertRegularWorktreeBlobMatchesCommit( ...
        path, releaseDescriptor.gateGitCommit);
    if exist(path, 'file') ~= 2 || ...
            ~strcmp(computeFileSha256(path), ...
                releaseDescriptor. ...
                    authorizedExecutableRawSha256{pathIdx})
        error('X36OutcomePermit:ExecutableHashDrift', ...
            'A tagged executable differs from the release: %s.', path);
    end
end
end

function assertRemoteReleasePublished( ...
        permit, releaseDescriptor, currentCommit)
remoteUrl = permit.releaseRemoteUrl;
tagRef = ['refs/tags/', permit.releaseTagName];
peeledTagRef = [tagRef, '^{}'];
branchRef = permit.releaseBranchRef;
shellValues = {remoteUrl, tagRef, peeledTagRef, branchRef};
if any(cellfun(@(value) ...
        ~ischar(value) || ~isrow(value) || ...
        ~isempty(strfind(value, '''')) || ...
        ~isempty(regexp(value, '[\r\n]', 'once')), shellValues))
    error('X36OutcomePermit:RemotePublicationRequired', ...
        'The fixed remote release coordinates are not shell-safe.');
end
[tagStatus, remoteTagListing] = system(sprintf([ ...
    remoteGitEnvironment(), ...
    'git ls-remote --tags ''%s'' ''%s'' ''%s'''], ...
    remoteUrl, tagRef, peeledTagRef));
actualTagLines = sort(splitNonemptyLines(remoteTagListing));
expectedTagLines = sort({ ...
    sprintf('%s\t%s', ...
        releaseDescriptor.releaseTagObjectId, tagRef), ...
    sprintf('%s\t%s', ...
        releaseDescriptor.gateGitCommit, peeledTagRef)});
[branchStatus, remoteBranchListing] = system(sprintf([ ...
    remoteGitEnvironment(), ...
    'git ls-remote --heads ''%s'' ''%s'''], ...
    remoteUrl, branchRef));
expectedBranchLine = sprintf('%s\t%s', currentCommit, branchRef);
if tagStatus ~= 0 || branchStatus ~= 0 || ...
        ~isequal(actualTagLines, expectedTagLines) || ...
        ~strcmp(strtrim(remoteBranchListing), expectedBranchLine)
    error('X36OutcomePermit:RemotePublicationRequired', ...
        ['The pinned remote must publish both the annotated gate tag ', ...
         'and this exact descriptor-only release commit.']);
end
end

function assertNoGitHistoryOverrides(permit)
if ~isfield(permit, 'gitHistoryOverridesForbidden') || ...
        ~isequal(permit.gitHistoryOverridesForbidden, true) || ...
        ~isempty(getenv('GIT_REPLACE_REF_BASE'))
    error('X36OutcomePermit:GitHistoryOverrideRejected', ...
        'Git history-replacement controls must remain disabled.');
end
[replaceStatus, replaceListing] = system('git replace -l');
[graftStatus, graftPath] = system( ...
    'git --no-replace-objects rev-parse --git-path info/grafts');
if replaceStatus ~= 0 || graftStatus ~= 0 || ...
        ~isempty(strtrim(replaceListing))
    error('X36OutcomePermit:GitHistoryOverrideRejected', ...
        'Git replace refs are unavailable or present.');
end
[tagStatus, trackedTags] = system('git ls-files -t');
[visibilityStatus, visibilityTags] = system('git ls-files -v');
if tagStatus ~= 0 || visibilityStatus ~= 0 || ...
        anyNonordinaryIndexTag(trackedTags) || ...
        anyNonordinaryIndexTag(visibilityTags)
    error('X36OutcomePermit:IndexVisibilityOverrideRejected', ...
        ['Skip-worktree, assume-unchanged, or another nonordinary ', ...
         'index visibility flag is forbidden.']);
end
[rewriteStatus, rewriteListing] = system([ ...
    'git config --show-origin --get-regexp ', ...
    '''^url\..*\.(insteadOf|pushInsteadOf)$''']);
if ~(rewriteStatus == 0 || rewriteStatus == 1) || ...
        ~isempty(strtrim(rewriteListing))
    error('X36OutcomePermit:RemoteUrlRewriteRejected', ...
        ['Git URL insteadOf/pushInsteadOf rewrites are forbidden for ', ...
         'the pinned release transport.']);
end
[hookStatus, hookListing] = system( ...
    'git config --show-origin --get-all core.hooksPath');
if ~(hookStatus == 0 || hookStatus == 1) || ...
        ~isempty(strtrim(hookListing))
    error('X36OutcomePermit:GitHookOverrideRejected', ...
        'A custom core.hooksPath is forbidden for the release gate.');
end
graftPath = strtrim(graftPath);
if exist(graftPath, 'file') == 2
    error('X36OutcomePermit:GitHistoryOverrideRejected', ...
        'A legacy Git graft file may alter the release lineage.');
end
end

function result = anyNonordinaryIndexTag(listing)
lines = splitNonemptyLines(listing);
result = any(cellfun(@(line) ...
    numel(line) < 3 || ~strncmp(line, 'H ', 2), lines));
end

function assertRegularWorktreeBlobMatchesCommit(path, commit)
if ~isShellSafePath(path) || ~isGitObjectId(commit)
    error('X36OutcomePermit:CommittedBlobDrift', ...
        'A fixed release path or commit is malformed.');
end
[regularStatus, ~] = system(sprintf([ ...
    'if [ -f ''%s'' ] && [ ! -L ''%s'' ]; ', ...
    'then exit 0; else exit 1; fi'], path, path));
[treeStatus, treeListing] = system(sprintf([ ...
    'git --no-replace-objects ls-tree ''%s'' -- ''%s'''], ...
    commit, path));
[hashStatus, worktreeBlobId] = system(sprintf( ...
    'git hash-object --no-filters -- ''%s''', path));
treeMatch = regexp(strtrim(treeListing), ...
    '^([0-9]{6}) ([a-z]+) ([0-9a-f]{40})\t(.*)$', ...
    'tokens', 'once');
if regularStatus ~= 0 || treeStatus ~= 0 || hashStatus ~= 0 || ...
        isempty(treeMatch) || ...
        ~any(strcmp(treeMatch{1}, {'100644', '100755'})) || ...
        ~strcmp(treeMatch{2}, 'blob') || ...
        ~strcmp(treeMatch{4}, path) || ...
        ~strcmp(strtrim(worktreeBlobId), treeMatch{3})
    error('X36OutcomePermit:CommittedBlobDrift', ...
        ['A release artifact or executable is not the exact regular-file ', ...
         'blob committed in its independently anchored commit: %s.'], path);
end
end

function result = isShellSafePath(value)
result = ischar(value) && isrow(value) && ...
    isempty(strfind(value, '''')) && ...
    isempty(regexp(value, '[\r\n]', 'once'));
end

function value = remoteGitEnvironment()
value = [ ...
    'GIT_TERMINAL_PROMPT=0 ', ...
    ['GIT_SSH_COMMAND=''ssh -oBatchMode=yes -oHostname=github.com ', ...
     '-oHostKeyAlias=github.com'' ']];
end

function tokens = resolveCommitAndParents(commit)
[status, listing] = system(sprintf( ...
    'git --no-replace-objects rev-list --parents -n 1 %s', commit));
if status ~= 0
    error('X36OutcomePermit:ReleaseLineageDrift', ...
        'Could not resolve the fixed release lineage.');
end
tokens = regexp(strtrim(listing), '\s+', 'split');
tokens = reshape(tokens, 1, []);
end

function manifest = buildCurrentExecutableSourceManifest()
[status, trackedListing] = system('git ls-files --cached');
if status ~= 0
    error('X36OutcomePermit:SourceManifestUnavailable', ...
        'Could not enumerate registered repository files.');
end
[status, repositoryListing] = system([ ...
    'find . \( -type f -o -type l \) ', ...
    '\( -name ''*.m'' -o -name ''*.p'' ', ...
    '-o -name ''*.mlx'' -o -name ''*.oct'' ', ...
    '-o -name ''*.mex*'' \) ', ...
    '-not -path ''./.git/*'' -print']);
if status ~= 0
    error('X36OutcomePermit:SourceManifestUnavailable', ...
        'Could not enumerate repository executable source files.');
end
trackedPaths = splitNonemptyLines(trackedListing);
trackedPaths = trackedPaths(cellfun( ...
    @isExecutableSourcePath, trackedPaths));
repositoryPaths = splitNonemptyLines(repositoryListing);
for pathIdx = 1:numel(repositoryPaths)
    if strncmp(repositoryPaths{pathIdx}, './', 2)
        repositoryPaths{pathIdx} = repositoryPaths{pathIdx}(3:end);
    end
end
trackedPaths = unique(sort(trackedPaths));
repositoryPaths = unique(sort(repositoryPaths));
unregisteredPaths = setdiff(repositoryPaths, trackedPaths);
if ~isempty(unregisteredPaths)
    error('X36OutcomePermit:UnregisteredExecutableSource', ...
        ['Repository-local executable source is not registered in ', ...
         'Git: %s'], unregisteredPaths{1});
end
sha256 = cell(size(trackedPaths));
for pathIdx = 1:numel(trackedPaths)
    if exist(trackedPaths{pathIdx}, 'file') == 0
        error('X36OutcomePermit:SourceManifestUnavailable', ...
            'A registered executable source disappeared during hashing.');
    end
    sha256{pathIdx} = computeFileSha256(trackedPaths{pathIdx});
end
payload = struct( ...
    'contractVersion', ...
        'registered-executable-source-manifest-v2', ...
    'paths', {reshape(trackedPaths, 1, [])}, ...
    'sha256', {reshape(sha256, 1, [])}, ...
    'unregisteredExecutablePaths', ...
        {reshape(unregisteredPaths, 1, [])});
manifest = payload;
manifest.canonicalSha256 = computeCanonicalValueSha256(payload);
end

function validateCurrentSourceAgainstPreflight( ...
        currentManifest, preflightManifest, permit, releaseDescriptor)
expectedPaths = unique(sort([ ...
    reshape(preflightManifest.paths, 1, []), ...
    reshape(permit.authorizedPostPreflightExecutablePaths, 1, [])]));
if ~isequal(currentManifest.paths, expectedPaths) || ...
        ~isempty(currentManifest.unregisteredExecutablePaths)
    error('X36OutcomePermit:ExecutableSourceSetDrift', ...
        ['The current executable-source path set differs from the ', ...
         'formal preflight plus the independently released gate.']);
end
for pathIdx = 1:numel(currentManifest.paths)
    path = currentManifest.paths{pathIdx};
    currentSha256 = currentManifest.sha256{pathIdx};
    changedIdx = find(strcmp( ...
        permit.authorizedPostPreflightExecutablePaths, path));
    if isempty(changedIdx)
        preflightIdx = find(strcmp(preflightManifest.paths, path));
        if numel(preflightIdx) ~= 1
            error('X36OutcomePermit:ExecutableSourceSetDrift', ...
                'An unchanged executable lacks a formal-preflight hash.');
        end
        expectedSha256 = preflightManifest.sha256{preflightIdx};
    elseif numel(changedIdx) == 1
        expectedSha256 = releaseDescriptor. ...
            authorizedExecutableRawSha256{changedIdx};
    else
        error('X36OutcomePermit:ExecutableSourceSetDrift', ...
            'A post-preflight executable path is duplicated.');
    end
    if ~strcmp(currentSha256, expectedSha256)
        error('X36OutcomePermit:ExecutableHashDrift', ...
            'Executable source differs from its authorized hash: %s.', ...
            path);
    end
end
end

function result = isExecutableSourcePath(path)
result = ~isempty(regexp(lower(path), ...
    '\.(m|p|mlx|oct|mex[^/]*)$', 'once'));
end

function assertPermitEnvelope(permit)
if ~isstruct(permit) || ~isscalar(permit) || ...
        ~isfield(permit, 'contractVersion') || ...
        ~strcmp(permit.contractVersion, ...
            'formation-staggered-recovery-x36-outcome-permit-v3') || ...
        ~isfield(permit, 'preflightContractVersion') || ...
        ~strcmp(permit.preflightContractVersion, ...
            'formation-staggered-recovery-x36-v37-preflight-v3') || ...
        ~isfield(permit, 'preflightPath') || ...
        ~strcmp(permit.preflightPath, fullfile( ...
            'RUN', 'GA', 'dynamic_topology', 'evidence', ...
            'formation_value_v37', 'x36_source_v3', 'preflight', ...
            ['FORMATION_STAGGERED_RECOVERY_X36_V37_', ...
             'V3_PREFLIGHT.mat'])) || ...
        ~isfield(permit, 'preflightReportPath') || ...
        ~strcmp(permit.preflightReportPath, fullfile( ...
            'RUN', 'GA', 'dynamic_topology', ...
            ['FORMATION_STAGGERED_RECOVERY_X36_V37_', ...
             'V3_PREFLIGHT_20260802.md'])) || ...
        ~isfield(permit, 'preflightCompletionMarkerPath') || ...
        ~strcmp(permit.preflightCompletionMarkerPath, ...
            [permit.preflightPath, '.complete']) || ...
        ~isfield(permit, 'gateBaseGitCommit') || ...
        ~isGitObjectId(permit.gateBaseGitCommit) || ...
        ~isfield(permit, 'releaseDescriptorPath') || ...
        ~isfield(permit, 'releaseTagName') || ...
        ~isfield(permit, 'releaseRemoteUrl') || ...
        ~isfield(permit, 'releaseBranchRef') || ...
        ~isfield(permit, 'releaseTagMustBeAnnotated') || ...
        ~isequal(permit.releaseTagMustBeAnnotated, true) || ...
        ~isfield(permit, 'releaseTagMustBePublished') || ...
        ~isequal(permit.releaseTagMustBePublished, true) || ...
        ~isfield(permit, 'releaseCommitMustDirectlyFollowGate') || ...
        ~isequal(permit.releaseCommitMustDirectlyFollowGate, true) || ...
        ~isfield(permit, 'releaseCommitMustBePublished') || ...
        ~isequal(permit.releaseCommitMustBePublished, true) || ...
        ~isfield(permit, 'gitHistoryOverridesForbidden') || ...
        ~isequal(permit.gitHistoryOverridesForbidden, true) || ...
        ~isfield(permit, 'preflightCompletionMarkerRequired') || ...
        ~isequal(permit.preflightCompletionMarkerRequired, true) || ...
        ~isfield(permit, 'permitCanonicalSha256') || ...
        ~isSha256(permit.permitCanonicalSha256)
    error('X36OutcomePermit:PermitBindingDrift', ...
        'The independent v3 outcome permit envelope changed.');
end
payload = rmfield(permit, 'permitCanonicalSha256');
try
    actualSha256 = computeCanonicalValueSha256(payload);
catch
    error('X36OutcomePermit:PermitHashDrift', ...
        'The independent v3 permit cannot be hashed canonically.');
end
if ~strcmp(actualSha256, permit.permitCanonicalSha256)
    error('X36OutcomePermit:PermitHashDrift', ...
        'The independent v3 outcome-permit payload changed.');
end
end

function assertAuthorizedExecutableDelta(permit, releaseDescriptor)
[gateStatus, gateListing] = system(sprintf([ ...
    'git --no-replace-objects diff --name-only ', ...
    '--diff-filter=ACDMRT %s..%s'], ...
    permit.gateBaseGitCommit, releaseDescriptor.gateGitCommit));
actualGatePaths = sort(splitNonemptyLines(gateListing));
expectedGatePaths = sort(reshape( ...
    permit.authorizedGateCommitPaths, 1, []));
if gateStatus ~= 0 || ~isequal(actualGatePaths, expectedGatePaths)
    error('X36OutcomePermit:GateCommitDeltaDrift', ...
        ['The tagged gate commit changed files outside the exact ', ...
         'seven-path release set.']);
end
for pathIdx = 1:numel(permit.authorizedGateCommitPaths)
    assertRegularWorktreeBlobMatchesCommit( ...
        permit.authorizedGateCommitPaths{pathIdx}, ...
        releaseDescriptor.gateGitCommit);
end

command = sprintf([ ...
    'git --no-replace-objects diff --name-only ', ...
    '--diff-filter=ACDMRT %s..%s -- ', ...
    '''*.m'' ''*.p'' ''*.mlx'' ''*.oct'' ''*.mex*'''], ...
    permit.gateBaseGitCommit, releaseDescriptor.gateGitCommit);
[status, listing] = system(command);
if status ~= 0
    error('X36OutcomePermit:ExecutableDeltaUnavailable', ...
        'Could not enumerate post-preflight executable changes.');
end
actualPaths = sort(splitNonemptyLines(listing));
expectedPaths = sort(reshape( ...
    permit.authorizedPostPreflightExecutablePaths, 1, []));
if ~isequal(actualPaths, expectedPaths)
    error('X36OutcomePermit:ExecutableDeltaDrift', ...
        ['Executable changes after the formal preflight are not the ', ...
         'exact permit-gate file set.']);
end
for pathIdx = 1:numel( ...
        permit.authorizedPostPreflightExecutablePaths)
    path = permit.authorizedPostPreflightExecutablePaths{pathIdx};
    expectedSha256 = releaseDescriptor. ...
        authorizedExecutableRawSha256{pathIdx};
    if exist(path, 'file') ~= 2 || ...
            ~strcmp(computeFileSha256(path), expectedSha256)
        error('X36OutcomePermit:ExecutableHashDrift', ...
            'A permitted post-preflight executable changed: %s.', path);
    end
end
end

function validateCompletionMarker(publication, permit)
assertExactFields(publication, { ...
    'contractVersion', 'generationGitCommit', ...
    'sourceManifestSha256', 'fingerprintDiscoveryMode', ...
    'publishedAt', 'matPath', 'reportPath', 'matSha256', ...
    'reportSha256', 'completionMarkerPath', ...
    'completionMarkerWrittenLast'}, ...
    'X36OutcomePermit:MalformedCompletionMarker', ...
    'The formal v3 completion-marker field set changed.');
if ~strcmp(publication.contractVersion, ...
            permit.preflightPublicationContractVersion) || ...
        ~strcmp(publication.generationGitCommit, ...
            permit.preflightGenerationGitCommit) || ...
        ~strcmp(publication.sourceManifestSha256, ...
            permit.preflightSourceManifestSha256) || ...
        ~isequal(publication.fingerprintDiscoveryMode, false) || ...
        ~strcmp(publication.matPath, permit.preflightPath) || ...
        ~strcmp(publication.reportPath, permit.preflightReportPath) || ...
        ~strcmp(publication.matSha256, permit.preflightSha256) || ...
        ~strcmp(publication.reportSha256, ...
            permit.preflightReportSha256) || ...
        ~strcmp(publication.completionMarkerPath, ...
            permit.preflightCompletionMarkerPath) || ...
        ~isequal(publication.completionMarkerWrittenLast, true)
    error('X36OutcomePermit:MalformedCompletionMarker', ...
        'The formal v3 completion marker no longer binds the evidence.');
end
end

function assertExactFields(value, expectedFields, identifier, message)
actualFields = sort(fieldnames(value));
expectedFields = sort(reshape(expectedFields, [], 1));
if ~isequal(actualFields, expectedFields)
    error(identifier, message);
end
end

function lines = splitNonemptyLines(value)
value = strtrim(value);
if isempty(value)
    lines = cell(1, 0);
else
    lines = regexp(value, '\r?\n', 'split');
    lines = reshape(lines, 1, []);
end
end

function result = isSha256(value)
result = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end

function result = isGitObjectId(value)
result = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{40}$', 'once'));
end
