function [linkUniforms, metadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        seed, sensorPhysicalUids, timeCount)
% MATERIALIZEPHYSICALUIDDIRECTEDDELIVERYUNIFORMS Stable directed draws.
%
% linkUniforms(sender, receiver, time) is keyed by immutable physical UIDs,
% not by the current array coordinates.  The canonical tensor is built in
% ascending physical-UID order and then materialized in the caller's array
% order.  Consequently, a pure array permutation moves each draw with its
% physical sender and receiver.
%
% The canonical tensor is one seeded Twister realization in MATLAB's
% sender-row-fastest array order.  Opposite directions therefore occupy
% distinct stream positions.  The caller's global RNG state is restored by
% an onCleanup guard even if generation fails.

contractVersion = ...
    'physical-uid-directed-delivery-uniforms-v1';
validateInputs(seed, sensorPhysicalUids, timeCount);

materializedUidOrder = reshape(sensorPhysicalUids, 1, []);
[canonicalUidOrder, materializedIndexByCanonicalIndex] = ...
    sort(materializedUidOrder);
nodeCount = numel(canonicalUidOrder);
canonicalIndexByMaterializedIndex = zeros(1, nodeCount);
canonicalIndexByMaterializedIndex( ...
    materializedIndexByCanonicalIndex) = 1:nodeCount;

globalRngState = rng();
restoreGlobalRngState = onCleanup(@() rng(globalRngState));
rng(seed, 'twister');
canonicalUniforms = rand(nodeCount, nodeCount, timeCount);
clear restoreGlobalRngState;

linkUniforms = canonicalUniforms( ...
    canonicalIndexByMaterializedIndex, ...
    canonicalIndexByMaterializedIndex, :);

metadata = struct();
metadata.contractVersion = contractVersion;
metadata.seed = seed;
metadata.materializedSensorPhysicalUidOrder = materializedUidOrder;
metadata.canonicalSensorPhysicalUidOrder = canonicalUidOrder;
metadata.canonicalIndexByMaterializedIndex = ...
    canonicalIndexByMaterializedIndex;
metadata.materializedIndexByCanonicalIndex = ...
    materializedIndexByCanonicalIndex;
metadata.directionConvention = ...
    'sender-row-receiver-column-time';
metadata.canonicalTraversalOrder = ...
    'sender-row-fastest-then-receiver-column-then-time';
metadata.generatorContract = ...
    'twister-seeded-canonical-sender-receiver-time-tensor-v1';
metadata.generator = 'twister';
metadata.reverseDirectionsUseDistinctStreamPositions = true;
metadata.globalRngStateRestored = true;
metadata.uniformInterval = 'runtime-rand-unit-interval';
metadata.timeCount = timeCount;
metadata.canonicalTensorSha256 = ...
    computeCanonicalValueSha256(canonicalUniforms);
metadata.materializedTensorSha256 = ...
    computeCanonicalValueSha256(linkUniforms);
metadata.canonicalSha256 = computeCanonicalValueSha256(metadata);
end

function validateInputs(seed, sensorPhysicalUids, timeCount)
maximumSeed = 2^32 - 1;
validSeed = isa(seed, 'double') && isreal(seed) && ~issparse(seed) && ...
    isscalar(seed) && isfinite(seed) && seed == round(seed) && ...
    seed >= 0 && seed <= maximumSeed;
validUids = isa(sensorPhysicalUids, 'double') && ...
    isreal(sensorPhysicalUids) && ~issparse(sensorPhysicalUids) && ...
    isvector(sensorPhysicalUids) && ~isempty(sensorPhysicalUids) && ...
    all(isfinite(sensorPhysicalUids(:))) && ...
    all(sensorPhysicalUids(:) == round(sensorPhysicalUids(:))) && ...
    all(sensorPhysicalUids(:) > 0) && ...
    all(sensorPhysicalUids(:) <= flintmax) && ...
    numel(unique(sensorPhysicalUids(:))) == numel(sensorPhysicalUids);
validTimeCount = isa(timeCount, 'double') && isreal(timeCount) && ...
    ~issparse(timeCount) && isscalar(timeCount) && isfinite(timeCount) && ...
    timeCount == round(timeCount) && timeCount >= 1 && ...
    timeCount <= flintmax;
if ~(validSeed && validUids && validTimeCount)
    error('PhysicalUidDeliveryUniforms:InvalidContract', ...
        ['A uint32-range integer seed, a nonempty vector of unique ', ...
         'positive exactly represented integer physical UIDs, and a ', ...
         'positive integer time count are required.']);
end
end
