function runtime = ...
    materializeFormationB4V46DevelopmentRuntimeInput(caseOrdinal)
% MATERIALIZEFORMATIONB4V46DEVELOPMENTRUNTIMEINPUT Truth-free boundary data.
%
% The deterministic generator necessarily constructs target truth while it
% creates measurements.  This function keeps that object local, constructs
% the exact sanitized filter model, verifies the accepted runtime-v3 hash,
% and returns only the values allowed to cross the filter boundary.

core = getFormationB4V46TrackingSourceRegistry();
accepted = getFormationB4V46DevelopmentRuntimeAcceptanceRegistry();
if ~isa(caseOrdinal, 'double') || ~isreal(caseOrdinal) || ...
        ~isscalar(caseOrdinal) || ~isfinite(caseOrdinal) || ...
        caseOrdinal ~= floor(caseOrdinal)
    error('FormationB4V46DevelopmentRuntime:UnknownCase', ...
        'An exact development case ordinal is required.');
end
matching = [accepted.entries.caseOrdinal] == caseOrdinal;
if nnz(matching) ~= 1 || ...
        ~ismember(caseOrdinal, core.developmentCaseOrdinals)
    error('FormationB4V46DevelopmentRuntime:UnknownCase', ...
        'The requested case is not one of the eight accepted inputs.');
end
acceptedEntry = accepted.entries(find(matching, 1));
caseContract = core.cases(caseOrdinal);
if ~strcmp(acceptedEntry.caseId, caseContract.id) || ...
        ~strcmp(acceptedEntry.coreCaseCanonicalSha256, ...
            caseContract.caseCanonicalSha256)
    error('FormationB4V46DevelopmentRuntime:RegistryDrift', ...
        'The accepted runtime and core case identities disagree.');
end

initialRngState = rng();
restoreRng = onCleanup(@() rng(initialRngState));
source = generateDynamicTopologyScenarioInputs( ...
    caseContract.presetName, caseContract.seed);
if ~source.validation.isValid || ...
        source.seed ~= caseContract.seed || ...
        ~strcmp(computeCanonicalValueSha256(source.config), ...
            caseContract.configSnapshotSha256) || ...
        source.config.numberOfSensors ~= caseContract.numberOfSensors || ...
        source.config.simulationLength ~= caseContract.simulationLength
    error('FormationB4V46DevelopmentRuntime:GeneratedInputDrift', ...
        'The regenerated development source no longer matches its case.');
end
identity = buildDynamicTopologyPhysicalIdentityRegistry(source.config);
[linkUniforms, deliveryMetadata] = ...
    materializePhysicalUidDirectedDeliveryUniforms( ...
        caseContract.deliverySeed, identity.sensorPhysicalUids, ...
        caseContract.simulationLength);
source.commConfig.linkUniforms = linkUniforms;
runtimeModel = sanitizeFormationB4V46RuntimeFilterModel( ...
    source.model, caseContract, core);
fingerprint = ...
    computeFormationB4V46RuntimeFilterInputFingerprintFromBoundary( ...
        runtimeModel, source.measurements, source.sensorTrajectories, ...
        source.neighborMap, source.commConfig, caseOrdinal);
if ~strcmp(fingerprint.canonicalSha256, ...
        acceptedEntry.runtimeFilterProjectionCanonicalSha256) || ...
        fingerprint.targetTrajectoryRealizationPassedToFilter || ...
        fingerprint.groundTruthPassedToFilter || ...
        ~fingerprint.registeredBirthPriorRetained
    error('FormationB4V46DevelopmentRuntime:RuntimeInputDrift', ...
        'The regenerated truth-free input is not independently accepted.');
end

runtime = struct();
runtime.contractVersion = ...
    'formation-b4-v46-development-runtime-input-v1';
runtime.caseOrdinal = caseContract.ordinal;
runtime.caseId = caseContract.id;
runtime.coreCaseCanonicalSha256 = caseContract.caseCanonicalSha256;
runtime.runtimeAcceptanceRegistryCanonicalSha256 = ...
    accepted.canonicalSha256;
runtime.runtimeFilterProjectionCanonicalSha256 = ...
    fingerprint.canonicalSha256;
runtime.model = runtimeModel;
runtime.measurements = source.measurements;
runtime.sensorTrajectories = source.sensorTrajectories;
runtime.neighborMap = source.neighborMap;
runtime.commConfig = source.commConfig;
runtime.runtimeFingerprint = fingerprint;
runtime.deliveryUniformMetadataCanonicalSha256 = ...
    deliveryMetadata.canonicalSha256;
runtime.targetTrajectoryRealizationReturned = false;
runtime.groundTruthReturned = false;
runtime.fullScenarioTargetMetadataReturned = false;
runtime.filterExecuted = false;
runtime.trackingOutcomeScored = false;
runtime.validationClaimAllowed = false;

clear source runtimeModel linkUniforms identity deliveryMetadata;
clear restoreRng;
end
