function model = materializeObservableSensorFusionModel( ...
        observableModel, currentTime)
% MATERIALIZEOBSERVABLESENSORFUSIONMODEL Build a current-page fusion view.
%
% The observable policy stores one current sensor pose rather than full
% trajectories.  The fusion implementation indexes geometry by currentTime,
% so this helper repeats only that same registered page.  It does not recover
% history or future motion.

if ~isstruct(observableModel) || ~isscalar(observableModel) || ...
        ~isfield(observableModel, 'sensorObservation') || ...
        ~isfield(observableModel, 'numberOfSensors') || ...
        ~isa(currentTime, 'double') || ~isscalar(currentTime) || ...
        ~isfinite(currentTime) || currentTime < 1 || ...
        currentTime ~= round(currentTime)
    error('ObservableSensorFusionModel:InvalidInput', ...
        'The observable sensor-fusion model request is malformed.');
end
observation = observableModel.sensorObservation;
sensorCount = observableModel.numberOfSensors;
required = { ...
    'contractVersion', 'detectionProbability', ...
    'measurementCovariance', 'sensorMotionEnabled', ...
    'sensorFovEnabled', 'sensorFovHalfAngleDeg', 'sensorFovRange', ...
    'sensorQuality', 'currentPosition', 'currentFovHeadingRad', ...
    'usesFutureSensorTrajectory', 'usesFutureSensorHeading', ...
    'usesTargetTruth'};
if ~isstruct(observation) || ~isscalar(observation) || ...
        ~all(isfield(observation, required)) || ...
        ~strcmp(observation.contractVersion, ...
            'topology-policy-current-sensor-observation-model-v1') || ...
        observation.usesFutureSensorTrajectory || ...
        observation.usesFutureSensorHeading || ...
        observation.usesTargetTruth || ...
        ~isequal(size(observation.currentPosition), [2, sensorCount]) || ...
        numel(observation.currentFovHeadingRad) ~= sensorCount || ...
        numel(observation.detectionProbability) ~= sensorCount || ...
        ~iscell(observation.measurementCovariance) || ...
        numel(observation.measurementCovariance) ~= sensorCount
    error('ObservableSensorFusionModel:InvalidInput', ...
        'The registered current sensor-observation view is malformed.');
end

model = observableModel;
model = rmfield(model, 'sensorObservation');
model.detectionProbability = ...
    reshape(observation.detectionProbability, [], 1);
model.Q = observation.measurementCovariance;
model.sensorMotionEnabled = observation.sensorMotionEnabled;
model.sensorFovEnabled = observation.sensorFovEnabled;
model.sensorFovHalfAngleDeg = observation.sensorFovHalfAngleDeg;
model.sensorFovRange = observation.sensorFovRange;
model.sensorQuality = observation.sensorQuality;
model.sensorFovHeadingRad = repmat( ...
    reshape(observation.currentFovHeadingRad, [], 1), ...
    1, currentTime);
model.sensorTrajectories = cell(1, sensorCount);
for sensorIdx = 1:sensorCount
    currentState = [ ...
        observation.currentPosition(:, sensorIdx); 0; 0];
    model.sensorTrajectories{sensorIdx} = ...
        repmat(currentState, 1, currentTime);
end
model.observableSensorGeometryMaterialized = true;
model.observableSensorGeometryCurrentPageRepeated = true;
model.observableSensorGeometryUsesFuturePage = false;
end
