function schedule = ...
        normalizeBudgetRecycledFormationRepairTeacherScheduleV201( ...
            forcedFormationIds, forcedSourceIds, forcedLabels, ...
            pageCount, formationCount, sensorCount, ...
            idealDeliveryTeacherMode)
% NORMALIZEBUDGETRECYCLEDFORMATIONREPAIRTEACHERSCHEDULEV201 Page actions.
%
% Legacy V188 plans use one forced formation/source/label tuple on every
% repair page.  V201 also accepts one tuple per page so a single recursive
% teacher rollout can test a causal sequence of heterogeneous label
% repairs.  Zero source plus zero label retains the ordinary online V188
% proposal on that page.  Numeric identifiers remain teacher routing keys,
% never deployable selector features.

if ~validPositiveInteger(pageCount) || ...
        ~validPositiveInteger(formationCount) || ...
        ~validPositiveInteger(sensorCount) || ...
        ~validBoolean(idealDeliveryTeacherMode)
    error('BudgetRecycledRepairV201:InvalidScheduleDimensions', ...
        'The teacher schedule dimensions are malformed.');
end

formationIds = expandIntegerVector( ...
    forcedFormationIds, pageCount, 0, formationCount, 'formation');
sourceIds = expandIntegerVector( ...
    forcedSourceIds, pageCount, 0, sensorCount, 'source');
if ~isnumeric(forcedLabels) || size(forcedLabels, 1) ~= 2 || ...
        ~ismember(size(forcedLabels, 2), [1, pageCount]) || ...
        any(~isfinite(forcedLabels(:))) || ...
        any(forcedLabels(:) ~= round(forcedLabels(:)))
    error('BudgetRecycledRepairV201:InvalidLabelSchedule', ...
        'Forced labels must be a 2-by-1 or 2-by-page integer matrix.');
end
labels = forcedLabels;
if size(labels, 2) == 1 && pageCount > 1
    labels = repmat(labels, 1, pageCount);
end

for pageIdx = 1:pageCount
    sourceForced = sourceIds(pageIdx) > 0;
    labelForced = any(labels(:, pageIdx) ~= 0);
    if sourceForced ~= labelForced || ...
            (formationIds(pageIdx) > 0 && ...
                ~logical(idealDeliveryTeacherMode)) || ...
            (sourceForced && ...
                (~logical(idealDeliveryTeacherMode) || ...
                 formationIds(pageIdx) == 0 || ...
                 any(labels(:, pageIdx) < 1)))
        error('BudgetRecycledRepairV201:InvalidTeacherAction', ...
            ['Every forced source-label action needs a positive formation ', ...
             'and ideal-delivery teacher mode.']);
    end
end

schedule = struct();
schedule.contractVersion = ...
    'budget-recycled-repair-teacher-schedule-v201-v1';
schedule.formationIds = formationIds;
schedule.sourceIds = sourceIds;
schedule.labels = labels;
schedule.pageCount = pageCount;
schedule.teacherActionMask = sourceIds > 0;
schedule.fixedFormationMask = formationIds > 0;
schedule.truthUsedAtRuntime = false;
schedule.numericIdentifiersUsedForTeacherRouting = ...
    any(schedule.teacherActionMask);
end

function values = expandIntegerVector( ...
        values, pageCount, minimumValue, maximumValue, name)
if ~isnumeric(values) || ~isvector(values) || isempty(values) || ...
        ~ismember(numel(values), [1, pageCount]) || ...
        any(~isfinite(values)) || any(values ~= round(values)) || ...
        any(values < minimumValue) || any(values > maximumValue)
    error('BudgetRecycledRepairV201:InvalidIntegerSchedule', ...
        'The forced %s schedule is malformed.', name);
end
values = reshape(values, 1, []);
if numel(values) == 1 && pageCount > 1
    values = repmat(values, 1, pageCount);
end
end

function valid = validPositiveInteger(value)
valid = isscalar(value) && isnumeric(value) && ...
    isfinite(value) && value >= 1 && value == round(value);
end

function valid = validBoolean(value)
valid = isscalar(value) && ...
    (islogical(value) || (isnumeric(value) && isfinite(value) && ...
    (value == 0 || value == 1)));
end
