function [permuted, details] = ...
    permuteFormationReliableKlaContextByBlockOrder( ...
        context, formationOrder)
% PERMUTEFORMATIONRELIABLEKLACONTEXTBYBLOCKORDER
% Apply a pure node-coordinate permutation by formation blocks.
%
% Formation labels and physical membership are unchanged.  Only the order
% in which complete formation blocks appear in node-index coordinates is
% changed.  An index-equivariant policy must return the same physical route
% after its output is mapped back to the original coordinates.

required = { ...
    'localPosteriorBySensor', 'model', 'baseAdjacency', ...
    'physicalAdjacency', 'previousAdjacencyHistory', ...
    'commConfig', 'triggerConfig'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ...
        ~isfield(context.model, 'dynamicTopologyScenario') || ...
        ~isfield(context.model.dynamicTopologyScenario, 'config') || ...
        ~isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds') || ...
        ~isfield(context.model.dynamicTopologyScenario, ...
            'staticAdjacency') || ...
        ~isfield(context.commConfig, 'pDropByEdge')
    error('FormationKlaBlockPermutation:InvalidContext', ...
        'The formation context is incomplete.');
end
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
groups = unique(groupIds, 'stable');
formationOrder = reshape(formationOrder, 1, []);
nodeCount = numel(groupIds);
if ~isnumeric(formationOrder) || ~isreal(formationOrder) || ...
        any(~isfinite(formationOrder)) || ...
        numel(formationOrder) ~= numel(groups) || ...
        numel(unique(formationOrder)) ~= numel(formationOrder) || ...
        ~all(ismember(groups, formationOrder)) || ...
        ~all(ismember(formationOrder, groups)) || ...
        numel(context.localPosteriorBySensor) ~= nodeCount || ...
        ~isequal(size(context.baseAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(context.physicalAdjacency), [nodeCount, nodeCount]) || ...
        ndims(context.previousAdjacencyHistory) ~= 3 || ...
        size(context.previousAdjacencyHistory, 1) ~= nodeCount || ...
        size(context.previousAdjacencyHistory, 2) ~= nodeCount || ...
        ~isequal(size(context.commConfig.pDropByEdge), ...
            [nodeCount, nodeCount])
    error('FormationKlaBlockPermutation:InvalidContext', ...
        'The formation block permutation is invalid.');
end

newToOld = zeros(1, 0);
for formationIdx = 1:numel(formationOrder)
    newToOld = [newToOld, ...
        reshape(find(groupIds == formationOrder(formationIdx)), 1, [])]; ...
        %#ok<AGROW>
end
if numel(newToOld) ~= nodeCount || ...
        numel(unique(newToOld)) ~= nodeCount
    error('FormationKlaBlockPermutation:InvalidContext', ...
        'The formation blocks do not partition the node set.');
end
oldToNew = zeros(1, nodeCount);
oldToNew(newToOld) = 1:nodeCount;

permuted = context;
permuted.localPosteriorBySensor = ...
    reshape(context.localPosteriorBySensor(newToOld), 1, []);
permuted.baseAdjacency = context.baseAdjacency(newToOld, newToOld);
permuted.physicalAdjacency = ...
    context.physicalAdjacency(newToOld, newToOld);
permuted.previousAdjacencyHistory = ...
    context.previousAdjacencyHistory(newToOld, newToOld, :);
permuted.commConfig.pDropByEdge = ...
    context.commConfig.pDropByEdge(newToOld, newToOld);
permuted.model.dynamicTopologyScenario.config.sensorGroupIds = ...
    groupIds(newToOld);
permuted.model.dynamicTopologyScenario.staticAdjacency = ...
    context.model.dynamicTopologyScenario. ...
        staticAdjacency(newToOld, newToOld);

details = struct();
details.contractVersion = ...
    'formation-reliable-kla-block-order-permutation-v1';
details.originalFormationOrder = groups;
details.permutedFormationOrder = formationOrder;
details.newToOldNodeOrder = newToOld;
details.oldToNewNodeOrder = oldToNew;
details.formationLabelsChanged = false;
details.physicalMembershipChanged = false;
details.pureNodeCoordinatePermutation = true;
details.canonicalSha256 = computeCanonicalValueSha256(details);
end
