function plan = planCacheFreeDonorOfferCoverageV233( ...
        sourceSensorIds, activeLabelCountBySource, ...
        candidatePayloadBytes, admissionNetSavingBytes, ...
        referencePageBytes, options)
% PLANCACHEFREEDONOROFFERCOVERAGEV233 Bound two-phase enumeration.

if nargin < 6 || isempty(options)
    options = struct();
end
protocol = getCacheFreeDonorOfferCoverageV233Protocol();
c = protocol.coverage;
b = protocol.bytes;
sourceSensorIds = reshape(sourceSensorIds, 1, []);
activeLabelCountBySource = reshape(activeLabelCountBySource, 1, []);
candidatePayloadBytes = reshape(candidatePayloadBytes, 1, []);
maximumPhases = getField(options, 'maximumPhases', c.maximumPhases);
offersPerPhase = getField(options, ...
    'offersPerSourcePerPhase', c.offersPerSourcePerPhase);
if isempty(sourceSensorIds) || ...
        numel(activeLabelCountBySource) ~= numel(sourceSensorIds) || ...
        numel(unique(sourceSensorIds)) ~= numel(sourceSensorIds) || ...
        any(~isfinite(sourceSensorIds)) || ...
        any(sourceSensorIds ~= round(sourceSensorIds)) || ...
        any(sourceSensorIds < 1) || ...
        any(~isfinite(activeLabelCountBySource)) || ...
        any(activeLabelCountBySource < 0) || ...
        any(activeLabelCountBySource ~= ...
            round(activeLabelCountBySource)) || ...
        isempty(candidatePayloadBytes) || ...
        any(~isfinite(candidatePayloadBytes)) || ...
        any(candidatePayloadBytes < 0) || ...
        any(candidatePayloadBytes ~= round(candidatePayloadBytes)) || ...
        ~validNonnegativeScalar(admissionNetSavingBytes) || ...
        ~validPositiveScalar(referencePageBytes) || ...
        ~isscalar(maximumPhases) || maximumPhases < 1 || ...
        maximumPhases ~= round(maximumPhases) || ...
        maximumPhases > c.maximumPhases || ...
        ~isscalar(offersPerPhase) || offersPerPhase < 1 || ...
        offersPerPhase ~= round(offersPerPhase) || ...
        offersPerPhase > c.offersPerSourcePerPhase
    error('CacheFreeDonorOfferV233:InvalidInput', ...
        'The donor-offer coverage request is malformed.');
end

sourceCount = numel(sourceSensorIds);
reserveFraction = b.communicationCreditReserveFraction;
spendableCreditBytes = ...
    (1 - reserveFraction) * admissionNetSavingBytes;
payloadReserveBytes = b.payloadReserveFractionOfSpendableCredit * ...
    spendableCreditBytes;
controlBudgetBytes = max(spendableCreditBytes - payloadReserveBytes, 0);
solicitationBytes = sourceCount * b.solicitationHeaderBytes;
perPhaseBytes = sourceCount * ...
    (b.responseHeaderBytesPerPhase + ...
     offersPerPhase * b.offerRecordBytes);
affordablePhases = floor(max( ...
    controlBudgetBytes - solicitationBytes, 0) / ...
    max(perPhaseBytes, 1));
phaseCount = min(maximumPhases, affordablePhases);
controlAttemptedBytes = solicitationBytes + ...
    phaseCount * perPhaseBytes;
coverageCapacityPerSource = phaseCount * offersPerPhase;
sourceCoverageCompleteMask = ...
    activeLabelCountBySource <= coverageCapacityPerSource;
candidateFeasibleMask = phaseCount >= 1 & ...
    candidatePayloadBytes <= ...
        spendableCreditBytes - controlAttemptedBytes + 1e-9;
certifiedNetSavingBytes = admissionNetSavingBytes - ...
    controlAttemptedBytes - candidatePayloadBytes;
candidateFeasibleMask = candidateFeasibleMask & ...
    certifiedNetSavingBytes >= -1e-9;

plan = struct();
plan.contractVersion = ...
    'cache-free-donor-offer-coverage-plan-v233-v1';
plan.protocolId = protocol.id;
plan.sourceSensorIds = sourceSensorIds;
plan.sourceCount = sourceCount;
plan.activeLabelCountBySource = activeLabelCountBySource;
plan.offersPerSourcePerPhase = offersPerPhase;
plan.maximumPhases = maximumPhases;
plan.affordablePhases = affordablePhases;
plan.phaseCount = phaseCount;
plan.coverageCapacityPerSource = coverageCapacityPerSource;
plan.sourceCoverageCompleteMask = sourceCoverageCompleteMask;
plan.allRetainedSourceLabelsCovered = ...
    all(sourceCoverageCompleteMask);
plan.admissionNetSavingBytes = admissionNetSavingBytes;
plan.reserveFraction = reserveFraction;
plan.protectedSavingBytes = ...
    reserveFraction * admissionNetSavingBytes;
plan.spendableCreditBytes = spendableCreditBytes;
plan.payloadReserveBytes = payloadReserveBytes;
plan.controlBudgetBytes = controlBudgetBytes;
plan.solicitationAttemptedBytes = solicitationBytes;
plan.responseAndRecordBytesPerPhase = perPhaseBytes;
plan.controlAttemptedBytes = controlAttemptedBytes;
plan.candidatePayloadBytes = candidatePayloadBytes;
plan.candidateFeasibleMask = candidateFeasibleMask;
plan.certifiedNetSavingBytes = certifiedNetSavingBytes;
plan.certifiedNetSavingPercent = 100 * certifiedNetSavingBytes / ...
    max(referencePageBytes, eps);
plan.truthUsed = false;
plan.futureInformationUsed = false;
plan.modelMayOverrideByteFeasibility = false;
plan.validationClaimAllowed = false;
plan.evidenceBoundary = protocol.evidenceBoundary;
end

function valid = validNonnegativeScalar(value)
valid = isscalar(value) && isnumeric(value) && ...
    isfinite(value) && value >= 0;
end

function valid = validPositiveScalar(value)
valid = validNonnegativeScalar(value) && value > 0;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
