function plan = planBudgetAdaptiveSourceOfferBreadthV231( ...
        sourceSensorIds, candidatePayloadBytes, ...
        admissionNetSavingBytes, referencePageBytes, options)
% PLANBUDGETADAPTIVESOURCEOFFERBREADTHV231 Derive offer breadth from bytes.

if nargin < 5 || isempty(options)
    options = struct();
end
protocol = getBudgetAdaptiveSourceOfferProtocolV231();
control = protocol.control;
sourceSensorIds = unique(reshape(sourceSensorIds, 1, []), 'stable');
candidatePayloadBytes = reshape(candidatePayloadBytes, 1, []);
controlShare = getField(options, ...
    'maximumControlShareOfSpendableCredit', ...
    control.maximumControlShareOfSpendableCredit);
maximumOffers = getField(options, ...
    'maximumOffersPerSource', control.maximumOffersPerSource);
if isempty(sourceSensorIds) || any(~isfinite(sourceSensorIds)) || ...
        any(sourceSensorIds ~= round(sourceSensorIds)) || ...
        any(sourceSensorIds < 1) || isempty(candidatePayloadBytes) || ...
        any(~isfinite(candidatePayloadBytes)) || ...
        any(candidatePayloadBytes < 0) || ...
        any(candidatePayloadBytes ~= round(candidatePayloadBytes)) || ...
        ~validNonnegativeScalar(admissionNetSavingBytes) || ...
        ~validPositiveScalar(referencePageBytes) || ...
        ~isscalar(controlShare) || ~isfinite(controlShare) || ...
        controlShare <= 0 || controlShare >= 1 || ...
        ~isscalar(maximumOffers) || ~isfinite(maximumOffers) || ...
        maximumOffers < 1 || maximumOffers ~= round(maximumOffers) || ...
        maximumOffers > control.maximumOffersPerSource
    error('BudgetAdaptiveSourceOfferV231:InvalidInput', ...
        'The budget-adaptive source-offer request is malformed.');
end

sourceCount = numel(sourceSensorIds);
reserveFraction = control.communicationCreditReserveFraction;
spendableAdmissionCreditBytes = ...
    (1 - reserveFraction) * admissionNetSavingBytes;
maximumControlBudgetBytes = floor( ...
    controlShare * spendableAdmissionCreditBytes);
fixedHeaderBytes = sourceCount * ...
    (control.solicitationHeaderBytes + control.responseHeaderBytes);
oneOfferLayerBytes = sourceCount * control.offerRecordBytes;
affordableOffers = floor(max( ...
    maximumControlBudgetBytes - fixedHeaderBytes, 0) / ...
    max(oneOfferLayerBytes, 1));
offersPerSource = min(maximumOffers, affordableOffers);
controlAttemptedBytes = fixedHeaderBytes + ...
    offersPerSource * oneOfferLayerBytes;
controlExecutable = offersPerSource >= ...
    control.minimumOffersPerSourceForExecution;
if ~controlExecutable
    controlAttemptedBytes = 0;
end

[creditAfterOffers, controlDecision] = ...
    preflightBudgetRecycledRepairSynopsisV188( ...
        [], admissionNetSavingBytes, controlAttemptedBytes, ...
        referencePageBytes);
payloadFeasibleMask = controlExecutable && ...
    controlDecision.lightSynopsisAuthorized && ...
    candidatePayloadBytes <= ...
        creditAfterOffers.spendableCreditBytes + 1e-9;
certifiedNetSavingBytes = admissionNetSavingBytes - ...
    controlAttemptedBytes - candidatePayloadBytes;
payloadFeasibleMask = payloadFeasibleMask & ...
    certifiedNetSavingBytes >= -1e-9;

existenceBreadth = ceil(offersPerSource / 2);
spatialBreadth = offersPerSource - existenceBreadth;
plan = struct();
plan.contractVersion = ...
    'budget-adaptive-source-offer-plan-v231-v1';
plan.protocolId = protocol.id;
plan.sourceSensorIds = sourceSensorIds;
plan.sourceCount = sourceCount;
plan.admissionNetSavingBytes = admissionNetSavingBytes;
plan.referencePageBytes = referencePageBytes;
plan.reserveFraction = reserveFraction;
plan.spendableAdmissionCreditBytes = ...
    spendableAdmissionCreditBytes;
plan.maximumControlShareOfSpendableCredit = controlShare;
plan.maximumControlBudgetBytes = maximumControlBudgetBytes;
plan.fixedHeaderBytes = fixedHeaderBytes;
plan.oneOfferLayerBytes = oneOfferLayerBytes;
plan.offersPerSource = offersPerSource;
plan.existenceBreadthPerSource = existenceBreadth;
plan.spatialBreadthPerSource = spatialBreadth;
plan.controlAttemptedBytes = controlAttemptedBytes;
plan.controlExecutable = controlExecutable;
plan.controlAuthorized = ...
    controlDecision.lightSynopsisAuthorized;
plan.controlDecision = controlDecision;
plan.spendableCreditAfterControlBytes = ...
    creditAfterOffers.spendableCreditBytes;
plan.protectedSavingAfterControlBytes = ...
    creditAfterOffers.protectedSavingBytes;
plan.candidatePayloadBytes = candidatePayloadBytes;
plan.candidateFeasibleMask = payloadFeasibleMask;
plan.certifiedNetSavingBytes = certifiedNetSavingBytes;
plan.certifiedNetSavingPercent = 100 * certifiedNetSavingBytes / ...
    max(referencePageBytes, eps);
plan.truthUsed = false;
plan.futureInformationUsed = false;
plan.modelMayOverrideByteFeasibility = false;
plan.validationClaimAllowed = false;
plan.evidenceBoundary = protocol.evidenceBoundary;
end

function valid = validNonnegativeScalar(value)
valid = isscalar(value) && isnumeric(value) && ...
    isfinite(value) && value >= 0;
end

function valid = validPositiveScalar(value)
valid = validNonnegativeScalar(value) && value > 0;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
