function predictions = ...
        predictPooledExpectedGatewayRidgeV256(model, features)
% PREDICTPOOLEDEXPECTEDGATEWAYRIDGEV256 Apply the frozen V256 ridge.

required = {'contractVersion', 'protocolId', 'featureNames', ...
    'outcomeNames', 'featureMean', 'featureScale', ...
    'activeFeatureMask', 'targetMean', 'coefficients', ...
    'truthUsed', 'futureInformationUsed'};
validContract = isstruct(model) && isscalar(model) && ...
    isfield(model, 'contractVersion') && ...
    (strcmp(model.contractVersion, ...
        'pooled-expected-gateway-v256-ridge-model-v1') || ...
     strcmp(model.contractVersion, ...
        'pooled-expected-gateway-v256-calibrated-model-v1'));
valid = validContract && ...
    all(isfield(model, required)) && ...
    isnumeric(features) && ismatrix(features) && ...
    size(features, 2) == numel(model.featureNames) && ...
    numel(model.featureMean) == size(features, 2) && ...
    numel(model.featureScale) == size(features, 2) && ...
    numel(model.activeFeatureMask) == size(features, 2) && ...
    size(model.coefficients, 1) == nnz(model.activeFeatureMask) && ...
    size(model.coefficients, 2) == numel(model.outcomeNames) && ...
    numel(model.targetMean) == numel(model.outcomeNames) && ...
    ~model.truthUsed && ~model.futureInformationUsed && ...
    all(isfinite(features(:)));
if ~valid
    error('PooledExpectedGatewayV256:InvalidRidgePrediction', ...
        'The V256 ridge model or feature matrix is malformed.');
end
if strcmp(model.contractVersion, ...
        'pooled-expected-gateway-v256-calibrated-model-v1')
    validCalibration = isfield(model, 'oneSidedMarginByOutcome') && ...
        numel(model.oneSidedMarginByOutcome) == ...
            numel(model.outcomeNames) && ...
        all(isfinite(model.oneSidedMarginByOutcome(:))) && ...
        all(model.oneSidedMarginByOutcome(:) >= 0);
    if ~validCalibration
        error('PooledExpectedGatewayV256:InvalidCalibrationParameters', ...
            'The calibrated V256 ridge lacks valid one-sided margins.');
    end
end
activeScale = model.featureScale(model.activeFeatureMask);
if any(~isfinite(activeScale)) || any(activeScale <= 0) || ...
        any(~isfinite(model.coefficients(:))) || ...
        any(~isfinite(model.targetMean(:)))
    error('PooledExpectedGatewayV256:InvalidRidgeParameters', ...
        'The V256 ridge parameters are non-finite or degenerate.');
end
centered = bsxfun(@minus, features, model.featureMean);
standard = bsxfun(@rdivide, ...
    centered(:, model.activeFeatureMask), activeScale);
predictions = bsxfun(@plus, ...
    standard * model.coefficients, model.targetMean);
if any(~isfinite(predictions(:)))
    error('PooledExpectedGatewayV256:InvalidRidgeOutput', ...
        'The V256 ridge produced a non-finite prediction.');
end
end
