function projection = projectObservationSupportedSetSafeV194( ...
        control, context, groupIds, proposedFormationIds, ...
        positiveSupportThreshold)
% PROJECTOBSERVATIONSUPPORTEDSETSAFEV194 Remove unsupported set entries.

groupIds = reshape(groupIds, 1, []);
proposedFormationIds = reshape(proposedFormationIds, 1, []);
groups = reshape(control.groups, 1, []);
if ~isstruct(control) || ~isstruct(context) || ...
        ~isfield(context, 'localPosteriorBySensor') || ...
        numel(context.localPosteriorBySensor) ~= numel(groupIds) || ...
        ~isfield(control, 'referenceScore') || ...
        ~isfield(control, 'singleActionScores') || ...
        ~isfield(control, 'singleActionAvailableMask') || ...
        any(~ismember(proposedFormationIds, groups)) || ...
        numel(unique(proposedFormationIds)) ~= ...
            numel(proposedFormationIds) || ...
        ~isscalar(positiveSupportThreshold) || ...
        ~isfinite(positiveSupportThreshold) || ...
        positiveSupportThreshold < 0 || positiveSupportThreshold > 1
    error('SetSafeV194:InvalidProjectionInput', ...
        'The V194 projection input is invalid.');
end

formationCount = numel(groups);
evaluatedMask = false(1, formationCount);
unsupportedEntryCount = nan(1, formationCount);
unsupportedEntryMass = nan(1, formationCount);
maximumReceiverRisk = nan(1, formationCount);
minimumEntrySupport = nan(1, formationCount);
releaseMask = false(1, formationCount);
referenceDistributions = control.referenceScore. ...
    networkDetails.receiverDistributions;
for formationId = proposedFormationIds
    formationIdx = find(groups == formationId, 1);
    if isempty(formationIdx) || ...
            ~control.singleActionAvailableMask(formationIdx) || ...
            isempty(control.singleActionScores{formationIdx})
        error('SetSafeV194:UnavailableCounterfactual', ...
            'A proposed V99 formation lacks its counterfactual.');
    end
    candidateDistributions = control.singleActionScores{formationIdx}. ...
        networkDetails.receiverDistributions;
    [~, entry] = computeObservationSupportedLmbSetEntryRisk( ...
        referenceDistributions, candidateDistributions, ...
        context.localPosteriorBySensor, groupIds, struct( ...
            'positiveSupportThreshold', positiveSupportThreshold));
    evaluatedMask(formationIdx) = true;
    unsupportedEntryCount(formationIdx) = ...
        entry.formationUnsupportedEntryCount(formationIdx);
    unsupportedEntryMass(formationIdx) = ...
        entry.formationUnsupportedEntryExistenceMass(formationIdx);
    maximumReceiverRisk(formationIdx) = ...
        entry.formationMaximumReceiverRisk(formationIdx);
    minimumEntrySupport(formationIdx) = ...
        entry.formationMinimumEntrySupport(formationIdx);
    releaseMask(formationIdx) = ...
        unsupportedEntryCount(formationIdx) > 0;
end

releaseFormationIds = groups(releaseMask);
selectedFormationIds = setdiff( ...
    proposedFormationIds, releaseFormationIds, 'stable');
projection = struct();
projection.contractVersion = ...
    'observation-supported-set-safe-v194-projection-v1';
projection.groups = groups;
projection.proposedFormationIds = proposedFormationIds;
projection.selectedFormationIds = selectedFormationIds;
projection.releaseFormationIds = releaseFormationIds;
projection.evaluatedMask = evaluatedMask;
projection.unsupportedEntryCountByFormation = ...
    unsupportedEntryCount;
projection.unsupportedEntryMassByFormation = unsupportedEntryMass;
projection.maximumReceiverRiskByFormation = maximumReceiverRisk;
projection.minimumEntrySupportByFormation = minimumEntrySupport;
projection.releaseOnAnyUnsupportedEntry = true;
projection.positiveSupportThreshold = positiveSupportThreshold;
projection.truthUsed = false;
projection.futureInformationUsed = false;
projection.numericFormationIdentifiersUsedAsFeatures = false;
projection.numericLabelIdentifiersUsedAsFeatures = false;
end

