function publishFormationB4V46DevelopmentArmShardNoReplace( ...
        temporaryPath, outputPath)
% PUBLISHFORMATIONB4V46DEVELOPMENTARMSHARDNOREPLACE Atomic hard-link publish.
%
% Both files must be in one directory.  POSIX hard-link creation is atomic
% and fails when outputPath already exists; unlike movefile(...,'f'), it
% cannot overwrite a shard published by a concurrent process.

if ~ischar(temporaryPath) || ~isrow(temporaryPath) || ...
        ~ischar(outputPath) || ~isrow(outputPath) || ...
        isempty(temporaryPath) || isempty(outputPath) || ...
        ~strcmp(fileparts(temporaryPath), fileparts(outputPath))
    error('FormationB4V46DevelopmentShard:InvalidPublicationPath', ...
        'Temporary and output shard paths must share one directory.');
end
[sourceStatus, ~] = builtin('system', sprintf( ...
    'test -f %s && test ! -L %s', ...
    shellQuote(temporaryPath), shellQuote(temporaryPath)));
if sourceStatus ~= 0
    error('FormationB4V46DevelopmentShard:PublicationSourceDrift', ...
        'The temporary shard must be one regular non-symlink file.');
end
if exist(outputPath, 'file') ~= 0 || exist(outputPath, 'dir') ~= 0
    error('FormationB4V46DevelopmentShard:OutputExists', ...
        'The development arm runner refuses to overwrite a shard path.');
end
[linkStatus, linkMessage] = builtin('system', sprintf( ...
    '/bin/ln %s %s', ...
    shellQuote(temporaryPath), shellQuote(outputPath)));
if linkStatus ~= 0
    if exist(outputPath, 'file') ~= 0 || exist(outputPath, 'dir') ~= 0
        error('FormationB4V46DevelopmentShard:OutputExists', ...
            ['Another process published the same shard path first; ', ...
             'the existing evidence was not replaced.']);
    end
    error('FormationB4V46DevelopmentShard:PublicationFailed', ...
        'Atomic no-replace shard publication failed: %s', linkMessage);
end
try
    delete(temporaryPath);
catch errorInfo
    warning( ...
        'FormationB4V46DevelopmentShard:TemporaryCleanupFailed', ...
        ['The shard was published atomically, but its temporary hard ', ...
         'link could not be removed: %s'], errorInfo.message);
end
end

function value = shellQuote(value)
value = ['''', strrep(value, '''', '''"''"'''), ''''];
end
