function replay = ...
    replayFormationStaggeredRecoveryV35SourceTrajectory( ...
        sourceScreen, sourcePreflight, protocol)
% REPLAYFORMATIONSTAGGEREDRECOVERYV35SOURCETRAJECTORY Full causal rollout.
%
% The frozen opened posterior is propagated through the complete v35 H=3
% policy without reading target truth or scoring tracking outcomes. This
% catches later-step control failures before the paired outcome is opened.

requiredProtocolFields = { ...
    'presetName', 'seed', 'anchorTime', 'reconnectTime'};
if ~isstruct(protocol) || ...
        ~all(isfield(protocol, requiredProtocolFields)) || ...
        ~isstruct(sourceScreen) || ...
        ~isfield(sourceScreen, 'cachePath') || ...
        ~isstruct(sourcePreflight) || ...
        ~isfield(sourcePreflight, 'initialBank') || ...
        ~isfield(sourcePreflight, 'selectedInitialActionIndex')
    error('StaggeredRecoveryReplay:InvalidContract', ...
        'The v35 source-rollout contract is incomplete.');
end

inputs = generateDynamicTopologyScenarioInputs( ...
    protocol.presetName, protocol.seed);
truthFields = { ...
    'groundTruth', 'groundTruthRfs', 'targetTrajectories'};
if ~all(isfield(inputs, truthFields))
    error('StaggeredRecoveryReplay:MissingTruthBoundary', ...
        'Scenario truth isolation cannot be attested.');
end
inputs = rmfield(inputs, truthFields);
loaded = load(sourceScreen.cachePath, 'behaviorBundle');
if ~isfield(loaded, 'behaviorBundle')
    error('StaggeredRecoveryReplay:MissingCache', ...
        'Opened behavior cache is unavailable.');
end
bundle = loaded.behaviorBundle;
outcomeFields = { ...
    'behaviorEospaByTime', 'behaviorCardinalityErrorByTime'};
if ~all(isfield(bundle, outcomeFields)) || ...
        any(cellfun(@(name) ~isempty(bundle.(name)), outcomeFields))
    error('StaggeredRecoveryReplay:OutcomeLeakage', ...
        'The source cache contains a nonempty tracking outcome.');
end
bundle = rmfield(bundle, outcomeFields);
returnTimes = protocol.anchorTime:protocol.reconnectTime;
inputs = cropInputs(inputs, protocol.reconnectTime);
history = bundle.preDecisionTopologyHistoryByTime{ ...
    protocol.anchorTime};
previousHistory = ...
    convertDiagnosticEdgeHistoryToPolicyAdjacencyHistory( ...
        history.selectedDirectedEdgeHistory);
initialBank = sourcePreflight.initialBank;
actionSequence = [ ...
    sourcePreflight.selectedInitialActionIndex, ...
    initialBank.referenceActionIndex, ...
    initialBank.referenceActionIndex];

config = buildMixtureAwareKlaReferenceConfig();
config.eventPolicy = 'alwaysHeavy';
config.dynamicTopologyEnabled = true;
config.dynamicTopologyEdgeBudget = inputs.config.edgeBudget;
config.topologyMaxEdgeChangeFraction = inf;
config.topologyDirectedEnabled = true;
config.topologyDirectedMessageBudget = ...
    2 * inputs.config.numberOfSensors;
config.topologyPolicyHistoryDepth = 2;
config.topologyPolicyName = ...
    'formation-h3-staggered-recovery-v1';
config.topologyPosteriorCaptureTimes = returnTimes;
config.topologyPolicyFcn = @(currentContext) ...
    selectFormationStaggeredRecoveryRuntimePolicy( ...
        currentContext, protocol.anchorTime, ...
        initialBank, actionSequence);
config.filterInitialLocalPosteriorBySensor = ...
    bundle.posteriorSnapshots{protocol.anchorTime};
config.filterInitialLocalPosteriorTime = protocol.anchorTime;
config.filterInitialPreviousAdjacencyHistory = previousHistory;
config.filterInitialPreviousAdjacencyTimes = history.times;
config.filterInitialPreviousAdjacencyHistorySource = ...
    'opened-reference-continuation-cache-v1';

rng(protocol.seed + 100000);
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    inputs.model, inputs.measurements, ...
    inputs.sensorTrajectories, inputs.neighborMap, ...
    inputs.commConfig, config);
nodeCount = inputs.config.numberOfSensors;
selected = false(nodeCount, nodeCount, numel(returnTimes));
fusionWeightsByTime = cell(1, numel(returnTimes));
for timeIdx = 1:numel(returnTimes)
    selected(:, :, timeIdx) = ...
        convertDiagnosticEdgeMaskToPolicyAdjacency( ...
            diagnostics.topologyActiveEdge( ...
                :, :, returnTimes(timeIdx)));
    fusionWeightsByTime{timeIdx} = ...
        diagnostics.topologyPolicyFusionWeightMatrix{ ...
            returnTimes(timeIdx)};
end
attemptedBytesByTime = reshape(sum(sum( ...
    diagnostics.attemptedPayloadBytes( ...
        :, :, returnTimes), 1), 2), 1, []);
truthUsed = finiteLogical( ...
    diagnostics.topologyPolicyTruthUsed(returnTimes));
repairUsed = finiteLogical( ...
    diagnostics.topologyPolicyRepairTriggered(returnTimes));
payloadEmergencyUsed = finiteLogical( ...
    diagnostics.topologyPolicyPayloadEmergencyUsed(returnTimes));
infeasible = logical( ...
    ~diagnostics.topologyFeasible(returnTimes) | ...
    finiteLogical(diagnostics. ...
        topologyPolicyTopologyInfeasible(returnTimes)));
posteriorContentUsed = finiteLogical( ...
    diagnostics.topologyPolicyPosteriorContentUsed(returnTimes));
currentLinkReliabilityUsed = finiteLogical( ...
    diagnostics. ...
        topologyPolicyCurrentLinkReliabilityUsed(returnTimes));
if any(truthUsed) || any(repairUsed) || ...
        any(payloadEmergencyUsed) || any(infeasible) || ...
        ~all(posteriorContentUsed) || ...
        ~all(currentLinkReliabilityUsed) || ...
        any(cellfun(@isempty, ...
            diagnostics.topologyLocalPosteriorSnapshot(returnTimes)))
    error('StaggeredRecoveryReplay:InvalidReplay', ...
        'The full v35 source-only trajectory failed a hard gate.');
end

[selectedSensorB3Pass, selectedFormationB3Pass] = ...
    computeRollingB3Pass(previousHistory, selected, ...
        inputs.config.sensorGroupIds);
if ~all(selectedSensorB3Pass) || ...
        ~all(selectedFormationB3Pass)
    error('StaggeredRecoveryReplay:InvalidReplay', ...
        'The source-only trajectory failed selected rolling-B3.');
end

firstExecutedWeights = ...
    diagnostics.topologyPolicyFusionWeightMatrix{returnTimes(1)};
firstExpectedWeights = initialBank.actionFusionWeights( ...
    :, :, actionSequence(1));
firstActionExact = isequal( ...
    selected(:, :, 1), logical(initialBank.actionAdjacency( ...
        :, :, actionSequence(1))));
firstFusionWeightsExact = ...
    isequal(size(firstExecutedWeights), ...
        size(firstExpectedWeights)) && ...
    max(abs(firstExecutedWeights(:) - ...
        firstExpectedWeights(:))) <= 1e-12;
if ~firstActionExact || ~firstFusionWeightsExact
    error('StaggeredRecoveryReplay:InitialDrift', ...
        'The full v35 rollout changed its frozen initial action.');
end

replay = struct();
replay.contractVersion = ...
    'formation-staggered-recovery-v35-source-replay-v1';
replay.returnTimes = returnTimes;
replay.actionSequenceIndices = actionSequence;
replay.selectedAdjacency = selected;
replay.selectedFusionWeightsByTime = fusionWeightsByTime;
replay.policyBackboneModeByTime = ...
    diagnostics.topologyPolicyBackboneMode(returnTimes);
replay.attemptedBytesByTime = attemptedBytesByTime;
replay.retentionDebtFractionByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtFractionByFormation(returnTimes);
replay.retentionDebtThresholdByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtThresholdByFormation(returnTimes);
replay.retentionDebtSingleAvailableMaskByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtSingleAvailableMask(returnTimes);
replay.retentionDebtSingleSafetyMaskByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtSingleSafetyMask(returnTimes);
replay.retentionDebtRequestedFormationIdsByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtRequestedFormationIds(returnTimes);
replay.retentionDebtSelectedFormationIdsByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtSelectedFormationIds(returnTimes);
replay.retentionDebtProjectionRemovalOrderByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtProjectionRemovalOrder(returnTimes);
replay.staggeredRecoveryScheduleByTime = ...
    diagnostics.topologyPolicyReserveSchedule(returnTimes);
replay.reserveProposalFormationAdjacencyByTime = ...
    diagnostics. ...
        topologyPolicyReserveProposalFormationAdjacency(returnTimes);
replay.referenceNetworkRiskByTime = reshape( ...
    diagnostics. ...
        topologyPolicyConsensusProjectionReferenceRisk(returnTimes), ...
    1, []);
replay.selectedNetworkRiskByTime = reshape( ...
    diagnostics. ...
        topologyPolicyConsensusProjectionSelectedRisk(returnTimes), ...
    1, []);
replay.referenceFallbackCountByTime = reshape( ...
    diagnostics. ...
        topologyPolicyConsensusProjectionFallbackCount(returnTimes), ...
    1, []);
replay.evaluatedActionCountByTime = reshape( ...
    diagnostics. ...
        topologyPolicyConsensusProjectionEvaluatedCount(returnTimes), ...
    1, []);
replay.safeActionCountByTime = reshape( ...
    diagnostics. ...
        topologyPolicyConsensusProjectionFeasibleCount(returnTimes), ...
    1, []);
replay.oneStepReservePassedByTime = logical( ...
    diagnostics. ...
        topologyPolicyOneStepTopologyReservePassed(returnTimes));
replay.posteriorContentUsedByTime = posteriorContentUsed;
replay.currentLinkReliabilityUsedByTime = ...
    currentLinkReliabilityUsed;
replay.selectedSensorB3Pass = selectedSensorB3Pass;
replay.selectedFormationB3Pass = selectedFormationB3Pass;
replay.executedActionIndicesByTime = ...
    formationSubsetsToActionIndices(replay. ...
        retentionDebtSelectedFormationIdsByTime);
replay.policyHistoryCountByTime = reshape( ...
    diagnostics.topologyPolicyHistoryCount(returnTimes), 1, []);
replay.policyHistoryTimesByTime = ...
    diagnostics.topologyPolicyHistoryTimes(returnTimes);
replay.firstActionExact = firstActionExact;
replay.firstFusionWeightsExact = firstFusionWeightsExact;
replay.truthUsed = false;
replay.futureOutcomeUsed = false;
replay.trackingOutcomeScored = false;
replay.groundTruthAccessed = false;
replay.runtimeFingerprint = ...
    buildFormationStaggeredRecoveryRuntimeFingerprint(replay);
replay.runtimeFingerprintSha256 = ...
    computeCanonicalValueSha256(replay.runtimeFingerprint);
end

function actionIndices = formationSubsetsToActionIndices(subsets)
actionIndices = zeros(1, numel(subsets));
for timeIdx = 1:numel(subsets)
    formationIds = reshape(subsets{timeIdx}, 1, []);
    if any(~isfinite(formationIds)) || ...
            any(formationIds ~= round(formationIds)) || ...
            any(formationIds < 1) || ...
            numel(unique(formationIds)) ~= numel(formationIds)
        error('StaggeredRecoveryReplay:InvalidReplay', ...
            'Runtime formation subset is invalid.');
    end
    actionIndices(timeIdx) = 1 + sum(2 .^ (formationIds - 1));
end
end

function [sensorPass, formationPass] = ...
        computeRollingB3Pass(previousHistory, executed, groupIds)
history = logical(previousHistory);
sensorPass = false(1, size(executed, 3));
formationPass = sensorPass;
for stepIdx = 1:size(executed, 3)
    pages = cat(3, history, executed(:, :, stepIdx));
    window = any(pages(:, :, max(1, end - 2):end), 3);
    sensorPass(stepIdx) = isStronglyConnected(window);
    formationPass(stepIdx) = isStronglyConnected( ...
        collapseToFormations(window, groupIds));
    history(:, :, end + 1) = executed(:, :, stepIdx); %#ok<AGROW>
    if size(history, 3) > 2
        history = history(:, :, end-1:end);
    end
end
end

function formation = collapseToFormations(adjacency, groupIds)
groups = unique(reshape(groupIds, 1, []), 'stable');
formation = false(numel(groups));
for receiverGroupIdx = 1:numel(groups)
    receivers = groupIds == groups(receiverGroupIdx);
    for senderGroupIdx = 1:numel(groups)
        senders = groupIds == groups(senderGroupIdx);
        formation(receiverGroupIdx, senderGroupIdx) = ...
            any(any(adjacency(receivers, senders)));
    end
end
formation(1:numel(groups)+1:end) = false;
end

function connected = isStronglyConnected(adjacency)
nodeCount = size(adjacency, 1);
connected = true;
for startNode = 1:nodeCount
    visited = false(1, nodeCount);
    visited(startNode) = true;
    while true
        next = visited | any(adjacency(visited, :), 1);
        if isequal(next, visited)
            break;
        end
        visited = next;
    end
    if ~all(visited)
        connected = false;
        return;
    end
end
end

function inputs = cropInputs(inputs, maximumTime)
inputs.measurements = inputs.measurements(:, 1:maximumTime);
for sensorIdx = 1:numel(inputs.sensorTrajectories)
    inputs.sensorTrajectories{sensorIdx} = ...
        inputs.sensorTrajectories{sensorIdx}(:, 1:maximumTime);
end
inputs.commConfig.linkUniforms = ...
    inputs.commConfig.linkUniforms(:, :, 1:maximumTime);
if isfield(inputs.commConfig, 'pDropByEdge') && ...
        ndims(inputs.commConfig.pDropByEdge) >= 3
    inputs.commConfig.pDropByEdge = ...
        inputs.commConfig.pDropByEdge(:, :, 1:maximumTime);
end
inputs.graphData.physicalAdjacency = ...
    inputs.graphData.physicalAdjacency(:, :, 1:maximumTime);
inputs.graphData.positions = ...
    inputs.graphData.positions(:, :, 1:maximumTime);
inputs.model.simulationLength = maximumTime;
end

function values = finiteLogical(values)
values = isfinite(values) & values ~= 0;
end
