function [context, replay] = ...
    replayFormationRetentionDebtV30SourceTrajectory( ...
        sourceScreen, sourcePreflight, protocol, decisionTime)
% REPLAYFORMATIONRETENTIONDEBTV30SOURCETRAJECTORY Recover a causal v30 state.
%
% This helper replays only the frozen v30 trajectory up to DECISIONTIME and
% returns the pre-fusion posterior, physical graph, link model, and two-step
% selected-topology history available to a causal controller at that time.

if nargin < 4 || isempty(decisionTime)
    decisionTime = protocol.reconnectTime;
end

requiredProtocolFields = { ...
    'presetName', 'seed', 'anchorTime', 'reconnectTime'};
for fieldIdx = 1:numel(requiredProtocolFields)
    if ~isfield(protocol, requiredProtocolFields{fieldIdx})
        error('RetentionDebtReplay:InvalidProtocol', ...
            'Replay protocol is missing %s.', ...
            requiredProtocolFields{fieldIdx});
    end
end
if ~isstruct(sourceScreen) || ~isfield(sourceScreen, 'cachePath') || ...
        ~isstruct(sourcePreflight) || ...
        ~isfield(sourcePreflight, 'initialBank') || ...
        ~isfield(sourcePreflight, 'selectedInitialActionIndex')
    error('RetentionDebtReplay:InvalidSource', ...
        'Frozen v30 source structures are incomplete.');
end
if ~isscalar(decisionTime) || ~isfinite(decisionTime) || ...
        decisionTime ~= round(decisionTime) || ...
        decisionTime < protocol.anchorTime || ...
        decisionTime > protocol.reconnectTime
    error('RetentionDebtReplay:InvalidDecisionTime', ...
        'Decision time must lie inside the frozen v30 horizon.');
end

inputs = generateDynamicTopologyScenarioInputs( ...
    protocol.presetName, protocol.seed);
loaded = load(sourceScreen.cachePath, 'behaviorBundle');
if ~isfield(loaded, 'behaviorBundle')
    error('RetentionDebtReplay:MissingCache', ...
        'Opened behavior cache is unavailable.');
end
bundle = loaded.behaviorBundle;
returnTimes = protocol.anchorTime:decisionTime;
inputs = cropInputs(inputs, decisionTime);
history = bundle.preDecisionTopologyHistoryByTime{ ...
    protocol.anchorTime};
previousHistory = ...
    convertDiagnosticEdgeHistoryToPolicyAdjacencyHistory( ...
        history.selectedDirectedEdgeHistory);
initialBank = sourcePreflight.initialBank;
actionSequence = [ ...
    sourcePreflight.selectedInitialActionIndex, ...
    initialBank.referenceActionIndex, ...
    initialBank.referenceActionIndex];

config = buildMixtureAwareKlaReferenceConfig();
config.eventPolicy = 'alwaysHeavy';
config.dynamicTopologyEnabled = true;
config.dynamicTopologyEdgeBudget = inputs.config.edgeBudget;
config.topologyMaxEdgeChangeFraction = inf;
config.topologyDirectedEnabled = true;
config.topologyDirectedMessageBudget = ...
    2 * inputs.config.numberOfSensors;
config.topologyPolicyHistoryDepth = 2;
config.topologyPolicyName = ...
    'formation-h3-causal-isolate-reconnect-v1';
config.topologyPosteriorCaptureTimes = returnTimes;
config.topologyPolicyFcn = @(currentContext) ...
    selectFormationIsolateReconnectRuntimePolicy( ...
        currentContext, protocol.anchorTime, ...
        initialBank, actionSequence);
config.filterInitialLocalPosteriorBySensor = ...
    bundle.posteriorSnapshots{protocol.anchorTime};
config.filterInitialLocalPosteriorTime = protocol.anchorTime;
config.filterInitialPreviousAdjacencyHistory = previousHistory;
config.filterInitialPreviousAdjacencyTimes = history.times;
config.filterInitialPreviousAdjacencyHistorySource = ...
    'opened-reference-continuation-cache-v1';

rng(protocol.seed + 100000);
[~, diagnostics] = runEventTriggeredDistributedLmbFilter( ...
    inputs.model, inputs.measurements, ...
    inputs.sensorTrajectories, inputs.neighborMap, ...
    inputs.commConfig, config);
selected = false(inputs.config.numberOfSensors, ...
    inputs.config.numberOfSensors, numel(returnTimes));
for timeIdx = 1:numel(returnTimes)
    selected(:, :, timeIdx) = ...
        convertDiagnosticEdgeMaskToPolicyAdjacency( ...
            diagnostics.topologyActiveEdge( ...
                :, :, returnTimes(timeIdx)));
end
attemptedBytesByTime = reshape(sum(sum( ...
    diagnostics.attemptedPayloadBytes( ...
        :, :, returnTimes), 1), 2), 1, []);
truthUsed = isfinite( ...
    diagnostics.topologyPolicyTruthUsed(returnTimes)) & ...
    diagnostics.topologyPolicyTruthUsed(returnTimes) ~= 0;
if any(truthUsed) || any(~diagnostics.topologyFeasible(returnTimes)) || ...
        any(cellfun(@isempty, ...
            diagnostics.topologyLocalPosteriorSnapshot(returnTimes)))
    error('RetentionDebtReplay:InvalidReplay', ...
        'The frozen v30 causal trajectory replay failed.');
end

historyForDecision = previousHistory;
historyTimesForDecision = reshape(history.times, 1, []);
priorRuntimeCount = numel(returnTimes) - 1;
if priorRuntimeCount > 0
    historyForDecision = cat(3, historyForDecision, ...
        selected(:, :, 1:priorRuntimeCount));
    historyTimesForDecision = [historyTimesForDecision, ...
        returnTimes(1:priorRuntimeCount)];
end
previousSelected = historyForDecision(:, :, end-1:end);
previousSelectedTimes = historyTimesForDecision(end-1:end);
currentTime = decisionTime;
context = struct();
context.localPosteriorBySensor = ...
    diagnostics.topologyLocalPosteriorSnapshot{currentTime};
context.model = inputs.model;
context.sensorTrajectories = inputs.sensorTrajectories;
context.commConfig = inputs.commConfig;
context.triggerConfig = buildMixtureAwareKlaReferenceConfig();
context.currentTime = currentTime;
context.previousAdjacencyHistory = previousSelected;
context.previousAdjacencyHistoryCount = ...
    size(previousSelected, 3);
context.previousAdjacencyHistoryTimes = previousSelectedTimes;
context.previousAdjacency = previousSelected(:, :, end);
context.baseAdjacency = inputs.graphData.staticAdjacency;
context.physicalAdjacency = logical( ...
    inputs.graphData.physicalAdjacency(:, :, currentTime));
context.edgeBudget = inputs.config.edgeBudget;
context.directedMessageBudget = ...
    2 * inputs.config.numberOfSensors;
context.positions = ...
    inputs.graphData.positions(:, :, currentTime);

replay = struct();
replay.contractVersion = ...
    'formation-retention-debt-v30-source-replay-v1';
replay.returnTimes = returnTimes;
replay.actionSequenceIndices = actionSequence;
replay.selectedAdjacency = selected;
replay.policyBackboneModeByTime = ...
    diagnostics.topologyPolicyBackboneMode(returnTimes);
replay.attemptedBytesByTime = attemptedBytesByTime;
replay.retentionDebtFractionByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtFractionByFormation(returnTimes);
replay.retentionDebtSelectedFormationIdsByTime = ...
    diagnostics. ...
        topologyPolicyRetentionDebtSelectedFormationIds(returnTimes);
replay.posteriorContentUsedByTime = logical( ...
    diagnostics.topologyPolicyPosteriorContentUsed(returnTimes));
replay.currentLinkReliabilityUsedByTime = logical( ...
    diagnostics. ...
        topologyPolicyCurrentLinkReliabilityUsed(returnTimes));
replay.truthUsed = false;
replay.futureOutcomeUsed = false;
replay.trackingOutcomeScored = false;
end

function inputs = cropInputs(inputs, maximumTime)
inputs.measurements = inputs.measurements(:, 1:maximumTime);
for sensorIdx = 1:numel(inputs.sensorTrajectories)
    inputs.sensorTrajectories{sensorIdx} = ...
        inputs.sensorTrajectories{sensorIdx}(:, 1:maximumTime);
end
inputs.commConfig.linkUniforms = ...
    inputs.commConfig.linkUniforms(:, :, 1:maximumTime);
if isfield(inputs.commConfig, 'pDropByEdge') && ...
        ndims(inputs.commConfig.pDropByEdge) >= 3
    inputs.commConfig.pDropByEdge = ...
        inputs.commConfig.pDropByEdge(:, :, 1:maximumTime);
end
inputs.graphData.physicalAdjacency = ...
    inputs.graphData.physicalAdjacency(:, :, 1:maximumTime);
inputs.graphData.positions = ...
    inputs.graphData.positions(:, :, 1:maximumTime);
inputs.model.simulationLength = maximumTime;
end
