function anchorTime = ...
    resolveSetTrustSequenceV134PilotAnchor(caseInfo, protocol)
% RESOLVESETTRUSTSEQUENCEV134PILOTANCHOR Fit the certified recovery tail.

% The nominal anchor is the registered focus-window midpoint.  Larger
% networks need a longer sensor-level recovery tail, so the anchor moves
% earlier only when necessary to keep the complete intervention and
% recovery window inside the registered trajectory.

required = {'presetName', 'horizonSteps'};
if ~isstruct(caseInfo) || ~isscalar(caseInfo) || ...
        ~all(isfield(caseInfo, required)) || ...
        ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~isfield(protocol, 'pilotAnchorQuantileWithinFocusWindow')
    error('V134SetTrustAnchor:InvalidInput', ...
        'The V134 scale case or anchor protocol is malformed.');
end
scenario = buildDynamicTopologyScenarioConfig(caseInfo.presetName);
window = reshape(scenario.focusWindow, 1, []);
nominalAnchor = round(window(1) + ...
    protocol.pilotAnchorQuantileWithinFocusWindow * ...
        (window(2) - window(1)));
latestCompleteStart = scenario.simulationLength - ...
    caseInfo.horizonSteps + 1;
anchorTime = min(nominalAnchor, latestCompleteStart);
if numel(window) ~= 2 || anchorTime < window(1) || ...
        anchorTime > window(2) || ...
        anchorTime + caseInfo.horizonSteps - 1 > ...
            scenario.simulationLength
    error('V134SetTrustAnchor:WindowDoesNotFit', ...
        ['The registered scene cannot contain the complete binary-', ...
         'admission and sensor-level recovery window.']);
end
end
