function [actionCode, relativeTime] = ...
    resolveRollingSafeActionSequenceCode( ...
        actionCodes, anchorTime, currentTime, fallbackActionCode)
% RESOLVEROLLINGSAFEACTIONSEQUENCECODE Pure finite-horizon dispatch.

actionCodes = reshape(actionCodes, 1, []);
if ~isnumeric(actionCodes) || isempty(actionCodes) || ...
        any(~isfinite(actionCodes)) || ...
        any(actionCodes < 0) || ...
        any(actionCodes ~= round(actionCodes))
    error('Action sequence codes must be finite nonnegative integers.');
end
if nargin < 4 || isempty(fallbackActionCode)
    fallbackActionCode = actionCodes(end);
end
if ~isnumeric(anchorTime) || ~isscalar(anchorTime) || ...
        ~isfinite(anchorTime) || ...
        ~isnumeric(currentTime) || ~isscalar(currentTime) || ...
        ~isfinite(currentTime) || ...
        ~isnumeric(fallbackActionCode) || ...
        ~isscalar(fallbackActionCode) || ...
        ~isfinite(fallbackActionCode) || fallbackActionCode < 0 || ...
        anchorTime ~= round(anchorTime) || ...
        currentTime ~= round(currentTime) || ...
        fallbackActionCode ~= round(fallbackActionCode)
    error('Action sequence dispatch inputs are invalid.');
end
anchorTime = round(anchorTime);
currentTime = round(currentTime);
fallbackActionCode = round(fallbackActionCode);
relativeTime = currentTime - anchorTime + 1;
if relativeTime >= 1 && relativeTime <= numel(actionCodes)
    actionCode = actionCodes(relativeTime);
else
    actionCode = fallbackActionCode;
end
end
