function [edgeValues, details] = ...
        scoreScaleEquivariantGatewayEdgesV254( ...
            context, referenceAssignment, model)
% SCORESCALEEQUIVARIANTGATEWAYEDGESV254 Shared additive ridge readout.

required = {'contractVersion', 'featureNames', 'featureScale', ...
    'activeFeatureMask', 'coefficients', 'intercept', ...
    'referenceMapsToZero', 'truthUsed', 'futureInformationUsed'};
if ~isstruct(model) || ~isscalar(model) || ...
        ~all(isfield(model, required)) || ...
        ~strcmp(model.contractVersion, ...
            'scale-equivariant-gateway-v254-additive-ridge-model-v1')
    error('ScaleEquivariantGatewayV254:InvalidEdgeModel', ...
        'The V254 edge scorer requires its frozen additive-ridge model.');
end

[edgeFeatures, featureNames, featureDetails] = ...
    computeScaleEquivariantGatewayEdgeFeaturesV254( ...
        context, referenceAssignment);
featureCount = numel(featureNames);
scale = reshape(model.featureScale, 1, []);
active = logical(reshape(model.activeFeatureMask, 1, []));
coefficients = reshape(model.coefficients, [], 1);
valid = isequal(model.featureNames, featureNames) && ...
    numel(scale) == featureCount && numel(active) == featureCount && ...
    numel(coefficients) == nnz(active) && ...
    all(isfinite(scale(active))) && all(scale(active) > 0) && ...
    all(isfinite(coefficients)) && isscalar(model.intercept) && ...
    model.intercept == 0 && logical(model.referenceMapsToZero) && ...
    ~logical(model.truthUsed) && ~logical(model.futureInformationUsed);
if ~valid
    error('ScaleEquivariantGatewayV254:InvalidEdgeModelFields', ...
        'The V254 model is incompatible, noncausal or not reference-centered.');
end

available = featureDetails.availableEdgeMask;
edgeValues = -Inf(size(available));
for linearIdx = find(available(:))'
    [receiver, sender] = ind2sub(size(available), linearIdx);
    row = reshape(edgeFeatures(receiver, sender, :), 1, []);
    standardized = row(active) ./ scale(active);
    edgeValues(receiver, sender) = standardized * coefficients;
end
if any(~isfinite(edgeValues(available)))
    error('ScaleEquivariantGatewayV254:InvalidEdgeScores', ...
        'The V254 additive model produced a non-finite gateway score.');
end

details = struct();
details.contractVersion = ...
    'scale-equivariant-gateway-v254-edge-scores-v1';
details.modelContractVersion = model.contractVersion;
details.featureNames = featureNames;
details.activeFeatureMask = active;
details.edgeFeatureDetails = featureDetails;
details.availableEdgeMask = available;
details.edgeValueConvention = 'receiver-row-sender-column';
details.assignmentScoreOperation = 'sum-selected-edge-values';
details.referenceMapsToZeroAfterAssignmentDifference = true;
details.truthUsed = false;
details.futureInformationUsed = false;
end
