function score = scoreComposedTaskRiskInputProtectionV93( ...
        referenceScore, candidateReceiverDistributions, ...
        groupIds, model, protocol)
% SCORECOMPOSEDTASKRISKINPUTPROTECTIONV93 Score exact row composition.

if ~isstruct(referenceScore) || ~isscalar(referenceScore) || ...
        ~isfield(referenceScore, 'taskRisk') || ...
        ~isfield(referenceScore, 'taskRiskDetails') || ...
        ~isfield(referenceScore, 'networkDetails') || ...
        ~iscell(candidateReceiverDistributions)
    error('JointTaskRiskV93:InvalidInput', ...
        'Reference score and candidate distributions are required.');
end
networkDetails = struct( ...
    'receiverDistributions', {candidateReceiverDistributions});
[taskRisk, taskRiskDetails] = ...
    computeExpectedLmbPosteriorTaskRiskV92( ...
        networkDetails, groupIds, model, protocol.riskOptions);

policy = protocol.protectionPolicy;
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        policy.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        policy.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        policy.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        policy.retentionReceiverTailWeight);
[existenceRetentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceScore.networkDetails.receiverDistributions, ...
        candidateReceiverDistributions, groupIds, ...
        retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
retentionSafe = ...
    existenceRetentionRisk <= ...
        policy.maximumExistenceRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= policy. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= policy. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= ...
        policy.maximumDecisionThresholdCrossingCount;

taskRiskGainPercent = relativeGainPercent( ...
    referenceScore.taskRisk, taskRisk);
worstReceiverRiskGainPercent = relativeGainPercent( ...
    referenceScore.taskRiskDetails.maximumReceiverRisk, ...
    taskRiskDetails.maximumReceiverRisk);
worstFormationRiskGainPercent = relativeGainPercent( ...
    referenceScore.taskRiskDetails.maximumFormationMeanRisk, ...
    taskRiskDetails.maximumFormationMeanRisk);
taskRiskSafe = ...
    taskRiskGainPercent >= ...
        protocol.minimumTaskRiskGainPercent - 1e-12 && ...
    worstReceiverRiskGainPercent >= ...
        protocol.minimumWorstReceiverRiskGainPercent - 1e-12 && ...
    worstFormationRiskGainPercent >= ...
        protocol.minimumWorstFormationRiskGainPercent - 1e-12;

score = struct();
score.contractVersion = ...
    'composed-task-risk-input-protection-v93-score-v1';
score.networkDetails = networkDetails;
score.taskRisk = taskRisk;
score.taskRiskDetails = taskRiskDetails;
score.taskRiskGainPercent = taskRiskGainPercent;
score.worstReceiverRiskGainPercent = ...
    worstReceiverRiskGainPercent;
score.worstFormationRiskGainPercent = ...
    worstFormationRiskGainPercent;
score.existenceRetentionRisk = existenceRetentionRisk;
score.retentionDetails = retentionDetails;
score.minimumFormationCardinalityChange = ...
    minimumFormationCardinalityChange;
score.minimumSupportedLabelRetentionRatio = ...
    minimumSupportedLabelRetentionRatio;
score.decisionThresholdCrossingCount = ...
    decisionThresholdCrossingCount;
score.retentionSafe = retentionSafe;
score.taskRiskSafe = taskRiskSafe;
score.safe = retentionSafe && taskRiskSafe;
score.rowCompositionExactForOneRoundRisk = true;
score.truthUsed = false;
score.trackingOutcomeUsed = false;
score.futureOutcomeUsed = false;
score.eospaEqualityClaimed = false;
score.recursiveTrackingGuaranteeClaimed = false;
end

function value = relativeGainPercent(reference, candidate)
value = 100 * (reference - candidate) / max(abs(reference), eps);
end
