function score = scoreFormationBackboneBundleRoute( ...
        context, adjacency, weights, referenceDistributions, ...
        groupIds, policy, incrementalReference)
% SCOREFORMATIONBACKBONEBUNDLEROUTE Truth-free one-round v38 route score.

if nargin < 7 || isempty(incrementalReference)
    incrementalReference = struct();
end

enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        policy.maximumIncomingCountForOutcomeEnumeration);
if ~isstruct(incrementalReference) || ...
        ~isscalar(incrementalReference)
    error('Formation bundle incremental reference is malformed.');
end
if ~isempty(fieldnames(incrementalReference))
    requiredFields = { ...
        'networkDetails', 'adjacency', 'fusionWeights'};
    if ~all(isfield(incrementalReference, requiredFields))
        error('Formation bundle incremental reference is malformed.');
    end
    enumerationOptions.referenceNetworkDetails = ...
        incrementalReference.networkDetails;
    enumerationOptions.referenceAdjacency = ...
        incrementalReference.adjacency;
    enumerationOptions.referenceFusionWeights = ...
        incrementalReference.fusionWeights;
end
[networkRisk, networkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, adjacency, weights, enumerationOptions);
if isempty(referenceDistributions)
    referenceDistributions = networkDetails.receiverDistributions;
end
retentionOptions = struct( ...
    'referenceSupportThreshold', ...
        policy.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        policy.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        policy.retentionReceiverTailFraction, ...
    'receiverTailWeight', ...
        policy.retentionReceiverTailWeight);
[existenceRetentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceDistributions, ...
        networkDetails.receiverDistributions, ...
        groupIds, retentionOptions);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
safe = ...
    existenceRetentionRisk <= ...
        policy.maximumExistenceRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= policy. ...
        minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= policy. ...
        minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= policy. ...
        maximumDecisionThresholdCrossingCount;
score = struct( ...
    'networkRisk', networkRisk, ...
    'networkDetails', networkDetails, ...
    'existenceRetentionRisk', existenceRetentionRisk, ...
    'retentionDetails', retentionDetails, ...
    'minimumFormationCardinalityChange', ...
        minimumFormationCardinalityChange, ...
    'minimumSupportedLabelRetentionRatio', ...
        minimumSupportedLabelRetentionRatio, ...
    'decisionThresholdCrossingCount', ...
        decisionThresholdCrossingCount, ...
    'safe', safe, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end
