function score = scorePayloadAbstentionCounterfactualV133( ...
        context, referenceAdjacency, referenceWeights, ...
        groupIds, protectedFormationId, protocol, referenceScore)
% SCOREPAYLOADABSTENTIONCOUNTERFACTUALV133 Exact current-page abstention.
%
% The runtime still attempts the route and charges its control synopsis.
% For fusion, however, every incoming cross-formation payload to the chosen
% receiver formation is absent.  Removing those inputs from the one-round
% outcome enumerator is exact because it is equivalent to assigning delivery
% probability zero while preserving the same missing-neighbor weight rule.

if nargin < 7
    referenceScore = struct([]);
end
nodeCount = numel(context.localPosteriorBySensor);
groupIds = reshape(groupIds, 1, []);
referenceAdjacency = logical(referenceAdjacency);
if ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~strcmp(protocol.id, 'counterfactual-action-regret-gate-v133-v1') || ...
        numel(groupIds) ~= nodeCount || ...
        ~isscalar(protectedFormationId) || ...
        ~ismember(protectedFormationId, groupIds) || ...
        ~isequal(size(referenceAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(referenceWeights), [nodeCount, nodeCount]) || ...
        any(~isfinite(referenceWeights(:))) || ...
        any(referenceWeights(:) < 0) || ...
        any(abs(sum(referenceWeights, 2) - 1) > 1e-12)
    error('CounterfactualRegretV133:InvalidInput', ...
        'The V133 payload-abstention score request is malformed.');
end
if ~isfield(context, 'triggerConfig') || ...
        ~isfield(context.triggerConfig, 'missingNeighborWeightMode')
    error('CounterfactualRegretV133:MissingFusionSemantics', ...
        'V133 requires one explicit missing-neighbor weight rule.');
end
missingMode = lower(char( ...
    context.triggerConfig.missingNeighborWeightMode));
if ~ismember(missingMode, protocol. ...
        actionContract.missingNeighborWeightModes)
    error('CounterfactualRegretV133:MissingFusionSemantics', ...
        'The missing-neighbor weight rule is outside the V133 contract.');
end

receiverMask = groupIds == protectedFormationId;
crossMask = groupIds(:) ~= groupIds(:)';
abstainedInputMask = referenceAdjacency & crossMask & receiverMask(:);
if ~any(abstainedInputMask(:))
    error('CounterfactualRegretV133:NoProtectedInput', ...
        'The selected formation has no incoming cross-formation payload.');
end
counterfactualAdjacency = ...
    referenceAdjacency & ~abstainedInputMask;
counterfactualWeights = applyMissingInputWeights( ...
    referenceWeights, abstainedInputMask, missingMode);

enumerationOptions = struct( ...
    'maximumIncomingCount', ...
        protocol.maximumIncomingCountForOutcomeEnumeration);
if isempty(referenceScore)
    [referenceDisagreement, referenceNetworkDetails] = ...
        computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
            context, referenceAdjacency, referenceWeights, ...
            enumerationOptions);
    [referenceTaskRisk, referenceTaskRiskDetails] = ...
        computeExpectedLmbPosteriorTaskRiskV92( ...
            referenceNetworkDetails, groupIds, context.model, ...
            protocol.riskOptions);
else
    validateReferenceScore(referenceScore, nodeCount);
    referenceDisagreement = referenceScore.networkDisagreement;
    referenceNetworkDetails = referenceScore.networkDetails;
    referenceTaskRisk = referenceScore.taskRisk;
    referenceTaskRiskDetails = referenceScore.taskRiskDetails;
end

enumerationOptions.referenceNetworkDetails = ...
    referenceNetworkDetails;
enumerationOptions.referenceAdjacency = referenceAdjacency;
enumerationOptions.referenceFusionWeights = referenceWeights;
[candidateDisagreement, candidateNetworkDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, counterfactualAdjacency, counterfactualWeights, ...
        enumerationOptions);
[candidateTaskRisk, candidateTaskRiskDetails] = ...
    computeExpectedLmbPosteriorTaskRiskV92( ...
        candidateNetworkDetails, groupIds, context.model, ...
        protocol.riskOptions);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        referenceNetworkDetails.receiverDistributions, ...
        candidateNetworkDetails.receiverDistributions, ...
        groupIds, protocol.retentionOptions);

score = struct();
score.contractVersion = ...
    'payload-abstention-counterfactual-v133-score-v1';
score.protocolId = protocol.id;
score.protectedFormationId = protectedFormationId;
score.abstainedInputMask = abstainedInputMask;
score.abstainedInputCount = nnz(abstainedInputMask);
score.runtimeRouteUnchanged = true;
score.enumeratorSupportChanged = true;
score.wireRepresentation = ...
    protocol.actionContract.wireRepresentation;
score.payloadMode = protocol.actionContract.payloadMode;
score.attemptedControlSynopsisCharged = ...
    protocol.actionContract.attemptedControlSynopsisCharged;
score.missingNeighborWeightMode = missingMode;
score.referenceAdjacency = referenceAdjacency;
score.referenceFusionWeights = referenceWeights;
score.counterfactualEnumeratorAdjacency = ...
    counterfactualAdjacency;
score.counterfactualEnumeratorFusionWeights = ...
    counterfactualWeights;
score.referenceNetworkDisagreement = referenceDisagreement;
score.counterfactualNetworkDisagreement = candidateDisagreement;
score.networkDisagreementChange = ...
    candidateDisagreement - referenceDisagreement;
score.referenceTaskRisk = referenceTaskRisk;
score.counterfactualTaskRisk = candidateTaskRisk;
score.taskRiskChange = candidateTaskRisk - referenceTaskRisk;
score.referenceTaskRiskDetails = referenceTaskRiskDetails;
score.counterfactualTaskRiskDetails = candidateTaskRiskDetails;
score.existenceRetentionRisk = retentionRisk;
score.retentionDetails = retentionDetails;
score.minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
score.minimumReceiverCardinalityChange = min( ...
    retentionDetails.expectedCardinalityChange);
score.minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
score.decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);
score.referenceNetworkDetails = referenceNetworkDetails;
score.counterfactualNetworkDetails = candidateNetworkDetails;
score.singleRoundExact = true;
score.runtimeAbstentionSemanticsMatched = true;
score.topologyActionClaimed = false;
score.centralizedCurrentPosteriorRequired = true;
score.truthUsed = false;
score.trackingOutcomeUsed = false;
score.futureOutcomeUsed = false;
score.recursiveSafetyClaimed = false;
end

function weights = applyMissingInputWeights(weights, removed, mode)
nodeCount = size(weights, 1);
for receiverIdx = reshape(find(any(removed, 2)), 1, [])
    senders = reshape(find(removed(receiverIdx, :)), 1, []);
    removedMass = sum(weights(receiverIdx, senders));
    weights(receiverIdx, senders) = 0;
    if strcmp(mode, 'self')
        weights(receiverIdx, receiverIdx) = ...
            weights(receiverIdx, receiverIdx) + removedMass;
    else
        rowMass = sum(weights(receiverIdx, :));
        if rowMass <= 0
            error('CounterfactualRegretV133:InvalidWeightProjection', ...
                'Removing the payload left no fusion input.');
        end
        weights(receiverIdx, :) = weights(receiverIdx, :) / rowMass;
    end
end
if any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        any(diag(weights) <= 0) || ...
        any(weights(:) < 0) || ...
        any(removed(:) & weights(:) > 0)
    error('CounterfactualRegretV133:InvalidWeightProjection', ...
        'The projected missing-input weights are invalid.');
end
end

function validateReferenceScore(score, nodeCount)
required = { ...
    'networkDisagreement', 'networkDetails', ...
    'taskRisk', 'taskRiskDetails'};
if ~isstruct(score) || ~isscalar(score) || ...
        ~all(isfield(score, required)) || ...
        ~isscalar(score.networkDisagreement) || ...
        ~isfinite(score.networkDisagreement) || ...
        ~isscalar(score.taskRisk) || ~isfinite(score.taskRisk) || ...
        ~isstruct(score.networkDetails) || ...
        ~isfield(score.networkDetails, 'receiverDistributions') || ...
        numel(score.networkDetails.receiverDistributions) ~= nodeCount
    error('CounterfactualRegretV133:InvalidReferenceScore', ...
        'The reusable V133 reference score is malformed.');
end
end
