function decision = scoreCounterfactualRegretGateV133Model( ...
        model, featureNames, featureValues)
% SCORECOUNTERFACTUALREGRETGATEV133MODEL Conservative online decision.

required = { ...
    'contractVersion', 'featureNames', 'featureCenter', ...
    'featureScale', 'coefficient', 'intercept', ...
    'harmProbabilityThreshold', 'supportLowerStandardized', ...
    'supportUpperStandardized', 'uncertainAction'};
if ~isstruct(model) || ~isscalar(model) || ...
        ~all(isfield(model, required)) || ...
        ~strcmp(model.contractVersion, ...
            'counterfactual-regret-gate-v133-model-v1') || ...
        ~iscell(featureNames) || ...
        numel(featureValues) ~= numel(featureNames)
    error('CounterfactualRegretV133:InvalidModelScore', ...
        'The V133 model or feature row is malformed.');
end
[present, columns] = ismember(model.featureNames, featureNames);
if any(~present) || numel(unique(columns)) ~= numel(columns)
    error('CounterfactualRegretV133:InvalidModelScore', ...
        'The current feature row lacks a frozen V133 model input.');
end
X = reshape(featureValues(columns), 1, []);
z = (X - model.featureCenter) ./ model.featureScale;
inSupport = all(z >= model.supportLowerStandardized & ...
    z <= model.supportUpperStandardized);
linear = model.intercept + z * reshape(model.coefficient, [], 1);
probability = 1 / (1 + exp(-min(max(linear, -40), 40)));
actionEnabled = inSupport && isfinite(model.harmProbabilityThreshold) && ...
    probability <= model.harmProbabilityThreshold;
decision = struct( ...
    'contractVersion', ...
        'counterfactual-regret-gate-v133-decision-v1', ...
    'predictedHarmProbability', probability, ...
    'harmProbabilityThreshold', model.harmProbabilityThreshold, ...
    'inDevelopmentSupport', inSupport, ...
    'actionEnabled', actionEnabled, ...
    'selectedAction', conditional( ...
        actionEnabled, 'abstain-current-page', ...
        model.uncertainAction), ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false, ...
    'fallbackUsed', ~actionEnabled);
end

function value = conditional(condition, ifTrue, ifFalse)
if condition
    value = ifTrue;
else
    value = ifFalse;
end
end
