function [role, details] = ...
        selectRoleMultiplexedSinglePayloadV143( ...
            config, sensorGroupIds, senderIdx, receiverIdx, ...
            currentTime, receiverProtected)
% SELECTROLEMULTIPLEXEDSINGLEPAYLOADV143 Choose the sole wire posterior.

required = { ...
    'lineageRelayRoleMultiplexedSinglePayloadEnabled', ...
    'lineageRelayRoleMultiplexedAnchorTime', ...
    'lineageRelayRoleMultiplexedPeriodPages', ...
    'lineageRelayRoleMultiplexedReferencePhaseOffset'};
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, required)) || ...
        ~logical(config.lineageRelayRoleMultiplexedSinglePayloadEnabled)
    error('RoleMultiplexedV143:InvalidRoleRequest', ...
        'The role selector requires the registered V143 runtime.');
end
groups = reshape(sensorGroupIds, 1, []);
sensorCount = numel(groups);
period = config.lineageRelayRoleMultiplexedPeriodPages;
offset = config.lineageRelayRoleMultiplexedReferencePhaseOffset;
anchorTime = config.lineageRelayRoleMultiplexedAnchorTime;
if sensorCount < 1 || any(~isfinite(groups)) || ...
        ~isscalar(senderIdx) || ~isscalar(receiverIdx) || ...
        senderIdx < 1 || senderIdx > sensorCount || ...
        receiverIdx < 1 || receiverIdx > sensorCount || ...
        senderIdx == receiverIdx || ...
        ~isscalar(currentTime) || ~isfinite(currentTime) || ...
        currentTime ~= round(currentTime) || currentTime < anchorTime || ...
        ~isscalar(receiverProtected) || ...
        ~any(double(receiverProtected) == [0, 1]) || ...
        ~ismember(period, [2, 4]) || offset ~= 0
    error('RoleMultiplexedV143:InvalidRoleRequest', ...
        ['The role-selector input violates a registered reference-first ', ...
         'periodic contract.']);
end

pageOffset = currentTime - anchorTime;
referencePhase = mod(pageOffset, period) == offset;
intraFormation = groups(senderIdx) == groups(receiverIdx);
workingRole = ~referencePhase && logical(receiverProtected) && ...
    intraFormation;
if workingRole
    role = 'working';
else
    role = 'reference';
end
details = struct( ...
    'referencePhase', referencePhase, ...
    'workingPhase', ~referencePhase, ...
    'intraFormation', intraFormation, ...
    'receiverProtected', logical(receiverProtected), ...
    'workingRole', workingRole, ...
    'referenceRole', ~workingRole);
end
