function [selectedActionIndices, details] = ...
    selectFormationH3ComplementarySequenceBeams( ...
        actionIndices, targets, beamWidth)
% SELECTFORMATIONH3COMPLEMENTARYSEQUENCEBEAMS Diverse privileged prefixes.

actionIndices = reshape(actionIndices, 1, []);
if ~isnumeric(targets) || ...
        ~isequal(size(targets), [numel(actionIndices), 6]) || ...
        any(~isfinite(actionIndices)) || ...
        any(actionIndices ~= round(actionIndices)) || ...
        numel(unique(actionIndices)) ~= numel(actionIndices) || ...
        any(~isfinite(targets(:))) || ...
        ~isscalar(beamWidth) || ~isfinite(beamWidth) || ...
        beamWidth ~= round(beamWidth) || beamWidth < 1 || ...
        beamWidth > numel(actionIndices)
    error('Complementary-sequence beam request is invalid.');
end

criterionNames = { ...
    'maximum-mean-tracking', ...
    'maximum-consensus', ...
    'maximum-minimum-formation', ...
    'maximum-worst-auxiliary-margin'};
criterionScores = [ ...
    targets(:, 1), ...
    targets(:, 4), ...
    targets(:, 2), ...
    min(targets(:, 2:6), [], 2)];
selectedRows = zeros(1, 0);
selectedCriteria = cell(1, 0);
for criterionIdx = 1:size(criterionScores, 2)
    if numel(selectedRows) >= beamWidth
        break;
    end
    row = bestUnselected( ...
        criterionScores(:, criterionIdx), actionIndices, selectedRows);
    if ~isempty(row)
        selectedRows(end + 1) = row; %#ok<AGROW>
        selectedCriteria{end + 1} = ...
            criterionNames{criterionIdx}; %#ok<AGROW>
    end
end

riskAdjusted = targets(:, 1) - ...
    sum(max(-targets(:, 2:6), 0), 2);
while numel(selectedRows) < beamWidth
    row = bestUnselected( ...
        riskAdjusted, actionIndices, selectedRows);
    if isempty(row)
        error('Complementary-sequence beam fill failed.');
    end
    selectedRows(end + 1) = row; %#ok<AGROW>
    selectedCriteria{end + 1} = ...
        'risk-adjusted-fill'; %#ok<AGROW>
end

selectedActionIndices = actionIndices(selectedRows);
details = struct();
details.contractVersion = ...
    'formation-h3-complementary-beam-selection-v1';
details.selectedRows = selectedRows;
details.selectedActionIndices = selectedActionIndices;
details.selectionCriteria = selectedCriteria;
details.selectedTargets = targets(selectedRows, :);
details.criterionNames = criterionNames;
details.criterionScores = criterionScores;
details.riskAdjustedScores = riskAdjusted;
details.targetsUseTruth = true;
details.futureOutcomesUsed = true;
details.validationClaimAllowed = false;
end

function row = bestUnselected(scores, actionIndices, selectedRows)
available = setdiff(1:numel(actionIndices), selectedRows, 'stable');
if isempty(available)
    row = [];
    return;
end
ranking = [ ...
    -reshape(scores(available), [], 1), ...
    reshape(actionIndices(available), [], 1)];
[~, order] = sortrows(ranking, [1, 2]);
row = available(order(1));
end
