function [adjacency, details] = ...
    selectFormationIsolateReconnectRuntimePolicy( ...
        context, anchorTime, initialBank, actionSequenceIndices, options)
% SELECTFORMATIONISOLATERECONNECTRUNTIMEPOLICY Causal v30 controller.

if nargin < 5 || isempty(options)
    options = struct();
end
protocol = getFormationIsolateReconnectProbeProtocol();
if ~isscalar(anchorTime) || ~isfinite(anchorTime) || ...
        anchorTime ~= round(anchorTime) || ...
        ~isstruct(context) || ~isfield(context, 'currentTime') || ...
        ~isscalar(context.currentTime) || ...
        ~isfinite(context.currentTime) || ...
        context.currentTime ~= round(context.currentTime)
    error('FormationRecovery:InvalidRuntimeContract', ...
        'Isolate-reconnect timing context is invalid.');
end
requiredBankFields = { ...
    'contractVersion', 'protocolId', 'actionCount', ...
    'referenceActionIndex', 'actionNames', 'actionAdjacency', ...
    'actionFusionWeights', 'actionPosteriorSafetyMask', ...
    'actionSuspendedFormationIds', ...
    'networkDisagreementRisk', 'retentionRisk', ...
    'actionRollingB3SensorPass', ...
    'actionRollingB3FormationPass'};
if ~isstruct(initialBank) || ...
        ~all(isfield(initialBank, requiredBankFields)) || ...
        ~strcmp(initialBank.contractVersion, ...
            'temporal-cross-edge-suspension-action-bank-v1') || ...
        ~strcmp(initialBank.protocolId, ...
            'formation-temporal-cross-edge-suspension-v29-v1')
    error('FormationRecovery:InvalidRuntimeContract', ...
        'The initial suspension bank is not the frozen v29 bank.');
end
actionSequenceIndices = reshape(actionSequenceIndices, 1, []);
if numel(actionSequenceIndices) ~= protocol.horizonSteps || ...
        any(~isfinite(actionSequenceIndices)) || ...
        any(actionSequenceIndices ~= round(actionSequenceIndices)) || ...
        any(actionSequenceIndices < 1) || ...
        any(actionSequenceIndices > initialBank.actionCount)
    error('FormationRecovery:InvalidRuntimeContract', ...
        'The initial action sequence is invalid.');
end

relativeTime = context.currentTime - anchorTime + 1;
if actionSequenceIndices(1) == initialBank.referenceActionIndex
    [adjacency, details] = ...
        selectBackboneResidualSplicedCyclePolicy( ...
            context, 'fixed-counter-clockwise', struct( ...
                'dominantWeight', protocol.dominantWeight, ...
                'residualWeight', protocol.residualWeight));
    validateRuntimeAction( ...
        context, adjacency, details.fusionWeightMatrix, true, protocol);
    details.mode = 'formation-isolate-reconnect-reference-baseline';
    details.contractVersion = ...
        'formation-isolate-reconnect-runtime-policy-v1';
    details.actionName = 'reference';
    details.runtimeFrozenGraphReplay = false;
    details.isolationPhase = false;
    details.recoveryPhase = false;
    details.referenceFallbackUsed = true;
    details.posteriorUsed = false;
    details.currentPosteriorUsed = false;
    details.currentLinkReliabilityUsed = false;
    details.truthUsed = false;
    details.groundTruthUsed = false;
    details.futureMeasurementUsed = false;
    details.futureOutcomeUsed = false;
    details.repairTriggered = false;
    details.payloadEmergencyUsed = false;
    details.topologyInfeasible = false;
    details.sensorWindowMature = true;
    details.formationWindowMature = true;
    details.sensorWindowStrongConnected = true;
    details.formationWindowStrongConnected = true;
    details.oneStepTopologyReserveChecked = true;
    details.oneStepTopologyReservePassed = true;
    details.oneStepJointProjectionUsed = true;
    details.recursiveSafetyClaimed = false;
    details.consensusProjectionReferenceRisk = NaN;
    details.consensusProjectionCandidateRisk = NaN;
    details.consensusProjectionSelectedRisk = NaN;
    details.consensusProjectionFallbackCount = 1;
    details.consensusProjectionEvaluatedCandidateCount = 0;
    details.consensusProjectionFeasibleCandidateCount = 0;
    details.consensusProjectionPrimaryFeasibleCandidateCount = 0;
    details.consensusProjectionPayloadRelaxationUsed = false;
    details.backboneMode = 'v30-reference-baseline';
    details.recoveryRetentionRisk = NaN;
    details.recoverySelectedActionIndex = NaN;
    details.recoverySelectedActionName = '';
    details.recoveryRelativeTime = relativeTime;
    return;
end

controlOptions = getField(options, ...
    'retentionDebtControlOptions', struct());
control = buildFormationRetentionDebtControl( ...
    context, controlOptions);
if ~control.selectionUsesCurrentPosterior || ...
        ~control.selectionUsesCurrentLinkReliability || ...
        ~control.selectionUsesSelectedTopologyHistory || ...
        control.truthUsed || control.futureOutcomeUsed
    error('FormationRecovery:InvalidRuntimeContract', ...
        'The live retention-debt controller is not causally attested.');
end
if relativeTime == 1
    expectedFormationIds = reshape( ...
        initialBank.actionSuspendedFormationIds{ ...
            actionSequenceIndices(1)}, 1, []);
    if ~isequal(reshape(control.selectedFormationIds, 1, []), ...
            expectedFormationIds)
        error('FormationRecovery:InitialControlDrift', ...
            ['The live source-only controller no longer reproduces ', ...
             'the preflight-selected initial action.']);
    end
end
adjacency = logical(control.selectedAdjacency);
weights = control.selectedFusionWeights;
validateRuntimeAction(context, adjacency, weights, false, protocol);
details = control.selectedPolicyDetails;
details.mode = 'formation-retention-debt-control';
details.contractVersion = ...
    'formation-isolate-reconnect-runtime-policy-v1';
details.actionName = control.selectedActionName;
details.fusionWeightMatrix = weights;
details.runtimeFrozenGraphReplay = false;
details.isolationPhase = relativeTime == 1;
details.recoveryPhase = relativeTime > 1;
details.referenceFallbackUsed = ...
    control.referenceFallbackUsed;
details.posteriorUsed = true;
details.currentPosteriorUsed = true;
details.currentLinkReliabilityUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.futureMeasurementUsed = false;
details.futureOutcomeUsed = false;
details.repairTriggered = false;
details.payloadEmergencyUsed = false;
details.topologyInfeasible = false;
details.sensorWindowMature = true;
details.formationWindowMature = true;
details.sensorWindowStrongConnected = ...
    all(control.selectedRollingB3SensorPass);
details.formationWindowStrongConnected = ...
    all(control.selectedRollingB3FormationPass);
details.oneStepTopologyReserveChecked = true;
details.oneStepTopologyReservePassed = ...
    details.sensorWindowStrongConnected && ...
    details.formationWindowStrongConnected;
details.oneStepJointProjectionUsed = true;
details.recursiveSafetyClaimed = false;
details.consensusProjectionReferenceRisk = ...
    control.referenceScore.networkRisk;
details.consensusProjectionCandidateRisk = ...
    control.selectedScore.networkRisk;
details.consensusProjectionSelectedRisk = ...
    control.selectedScore.networkRisk;
details.consensusProjectionFallbackCount = double( ...
    control.referenceFallbackUsed);
details.consensusProjectionEvaluatedCandidateCount = ...
    control.evaluatedRouteCount;
details.consensusProjectionFeasibleCandidateCount = ...
    1 + control.safeSingleActionCount;
details.consensusProjectionPrimaryFeasibleCandidateCount = ...
    numel(control.requestedFormationIds);
details.consensusProjectionPayloadRelaxationUsed = false;
details.backboneMode = ['v30-debt-', ...
    control.selectedActionName];
details.recoveryRetentionRisk = ...
    control.selectedScore.retentionRisk;
details.recoverySelectedActionIndex = NaN;
details.recoverySelectedActionName = ...
    control.selectedActionName;
details.recoveryRelativeTime = relativeTime;
details.retentionDebtFractionByFormation = ...
    control.formationRetentionDebtFraction;
details.retentionDebtThresholdByFormation = ...
    control.debtThresholdByFormation;
details.retentionDebtSingleAvailableMask = ...
    control.singleActionAvailableMask;
details.retentionDebtSingleSafetyMask = ...
    control.singleActionSafetyMask;
details.retentionDebtRequestedFormationIds = ...
    control.requestedFormationIds;
details.retentionDebtSelectedFormationIds = ...
    control.selectedFormationIds;
details.retentionDebtProjectionRemovalOrder = ...
    control.projectionRemovalOrder;
end

function validateRuntimeAction( ...
        context, adjacency, weights, requireStrong, protocol)
nodeCount = numel(context.localPosteriorBySensor);
physical = logical(context.physicalAdjacency);
weightSupport = adjacency | logical(eye(nodeCount));
if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(adjacency(:) & ~physical(:)) || ...
        nnz(adjacency) > 2 * nodeCount || ...
        any(~isfinite(weights(:))) || ...
        any(weights(:) < -1e-12) || ...
        any(weights(:) > 1e-12 & ~weightSupport(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12)
    error('FormationRecovery:InvalidRuntimeAction', ...
        'The isolate-reconnect action violates a hard route invariant.');
end
if requireStrong && ...
        protocol.recoveryOneStepStrongConnectivityRequired && ...
        ~isStronglyConnected(adjacency)
    error('FormationRecovery:InvalidRuntimeAction', ...
        'The recovery action is not one-step strongly connected.');
end
end

function connected = isStronglyConnected(adjacency)
senderAdjacency = logical(adjacency');
connected = reachableAll(senderAdjacency) && ...
    reachableAll(senderAdjacency');
end

function connected = reachableAll(adjacency)
visited = false(1, size(adjacency, 1));
frontier = 1;
while ~isempty(frontier)
    node = frontier(end);
    frontier(end) = [];
    if visited(node)
        continue;
    end
    visited(node) = true;
    frontier = [frontier, reshape(find( ...
        adjacency(node, :) & ~visited), 1, [])]; %#ok<AGROW>
end
connected = all(visited);
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
