function [selectedTimes, selectedIndices] = ...
    selectFormationH3EventTimes( ...
        candidateTimes, scores, selectedCount, minimumSeparation)
% SELECTFORMATIONH3EVENTTIMES Deterministic non-maximum event selection.

candidateTimes = reshape(candidateTimes, 1, []);
scores = reshape(scores, 1, []);
if isempty(candidateTimes) || ...
        numel(candidateTimes) ~= numel(scores) || ...
        any(~isfinite(candidateTimes)) || ...
        any(candidateTimes ~= round(candidateTimes)) || ...
        any(diff(candidateTimes) <= 0) || ...
        any(~isfinite(scores)) || any(scores < 0) || ...
        ~isscalar(selectedCount) || ~isfinite(selectedCount) || ...
        selectedCount ~= round(selectedCount) || selectedCount < 1 || ...
        selectedCount > numel(candidateTimes) || ...
        ~isscalar(minimumSeparation) || ...
        ~isfinite(minimumSeparation) || ...
        minimumSeparation ~= round(minimumSeparation) || ...
        minimumSeparation < 1
    error('Formation H=3 event-time selection input is invalid.');
end

ranking = sortrows([(-scores(:)), candidateTimes(:)], [1, 2]);
rankedTimes = ranking(:, 2)';
selectedTimes = zeros(1, selectedCount);
cursor = 0;
for rankedIdx = 1:numel(rankedTimes)
    currentTime = rankedTimes(rankedIdx);
    if cursor > 0 && any(abs( ...
            selectedTimes(1:cursor) - currentTime) < ...
                minimumSeparation)
        continue;
    end
    cursor = cursor + 1;
    selectedTimes(cursor) = currentTime;
    if cursor == selectedCount
        break;
    end
end
if cursor ~= selectedCount
    error(['Formation H=3 event-time separation leaves too few ', ...
        'candidate states.']);
end
selectedTimes = sort(selectedTimes);
selectedIndices = zeros(1, selectedCount);
for idx = 1:selectedCount
    selectedIndices(idx) = find( ...
        candidateTimes == selectedTimes(idx), 1);
end
end
