function [adjacency, details] = ...
    selectRollingSafeCounterfactualConsensusPolicy( ...
        context, aggregationMode, crossEdgeCount, options)
% SELECTROLLINGSAFECOUNTERFACTUALCONSENSUSPOLICY Offline KLA teacher action.

if nargin < 4 || isempty(options)
    options = struct();
end
sourceWeight = getField(options, 'sourceWeight', 0.70);
crossEdgeCount = round(crossEdgeCount);
scoreOptions = struct( ...
    'sourceWeight', sourceWeight, ...
    'aggregationMode', aggregationMode, ...
    'tailFraction', getField(options, 'tailFraction', 0.25));
policyOptions = struct( ...
    'sourceWeight', sourceWeight, ...
    'payloadToleranceFraction', getField( ...
        options, 'payloadToleranceFraction', inf), ...
    'edgeScoreFcnReturnsDetails', true, ...
    'edgeScoreFcn', ...
        @(scoreContext, receiverIndices, senderIndices, ...
            baselineSources) ...
            computeRollingSafeCounterfactualConsensusEdgeScores( ...
                scoreContext, receiverIndices, senderIndices, ...
                baselineSources, scoreOptions), ...
    'posteriorUsed', true, ...
    'truthUsed', false, ...
    'currentLinkReliabilityUsed', true, ...
    'minimumCurrentCrossEdges', crossEdgeCount, ...
    'maximumCurrentCrossEdges', crossEdgeCount);
[adjacency, details] = selectRollingSafeRoutingPolicy( ...
    context, 'external-scores', policyOptions);

if details.realizedCrossCount ~= crossEdgeCount || ...
        ~details.nominalProjectionFeasible || ...
        details.repairProjectionAttempted || ...
        details.repairTriggered || ...
        details.payloadEmergencyUsed
    error('CounterfactualConsensus:Unavailable', [ ...
        'Counterfactual consensus could not realize exact k=%d ', ...
        'without repair or payload emergency.'], crossEdgeCount);
end
if details.truthUsed
    error('Counterfactual consensus violated its truth-free contract.');
end
details.counterfactualConsensusContractVersion = ...
    'rolling-safe-counterfactual-consensus-teacher-v2';
details.counterfactualConsensusAggregationMode = ...
    aggregationMode;
details.counterfactualConsensusExactCurrentCrossEdgeCount = ...
    crossEdgeCount;
details.counterfactualConsensusTruthUsed = false;
details.counterfactualConsensusFutureOutcomeUsed = false;
details.counterfactualConsensusCentralizedOfflineTeacher = true;
details.counterfactualConsensusDeploymentObservable = false;
details.counterfactualConsensusCombinationExact = ...
    crossEdgeCount == 1;
if crossEdgeCount == 1
    details.counterfactualConsensusCombinationSemantics = ...
        'exact-single-replacement-marginal';
else
    details.counterfactualConsensusCombinationSemantics = ...
        'baseline-linearized-additive-proxy';
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
