function [adjacency, details] = ...
    selectStaticVsDynamicRoutingV91DynamicPolicy(context)
% SELECTSTATICVSDYNAMICROUTINGV91DYNAMICPOLICY Current-graph arm.

protocol = getStaticVsDynamicRoutingV91Protocol();
timer = tic;
[adjacency, details] = ...
    selectPhysicalFormationTreeResidualTourPolicy(context, struct( ...
        'dominantWeight', protocol.dominantWeight, ...
        'residualWeight', protocol.residualWeight));
details.contractVersion = ...
    'static-vs-dynamic-routing-v91-dynamic-policy-v1';
details.protocolId = protocol.id;
details.armId = protocol.dynamicArmId;
details.selectionSeconds = toc(timer);
details.referenceMessageCount = nnz(adjacency);
details.currentMessageCount = nnz(adjacency);
details.referenceFallbackUsed = false;
details.scheduleCertificate = buildSchedule( ...
    context.currentTime, 'dynamic-current-physical');
end

function schedule = buildSchedule(currentTime, phase)
schedule = struct( ...
    'contractVersion', ...
        'static-vs-dynamic-routing-v91-schedule-v1', ...
    'currentTime', currentTime, ...
    'phase', phase, ...
    'phaseIndex', 1, ...
    'gatewayIndices', zeros(1, 0), ...
    'formationIds', zeros(1, 0), ...
    'sourceIndices', zeros(1, 0), ...
    'proposalGatewayCount', 0, ...
    'selectedGatewayCount', 0, ...
    'pendingAcquisitionTime', NaN, ...
    'messageParityPassed', true, ...
    'rollingSensorStrong', true, ...
    'rollingFormationStrong', true, ...
    'referenceFallbackUsed', false, ...
    'cycleSelected', true);
end
