function [reference, details] = ...
    selectFormationB4V49CyclePreservingReference( ...
        context, incumbentReference, options)
% SELECTFORMATIONB4V49CYCLEPRESERVINGREFERENCE
% Enumerate current physically feasible formation cycles, materialize the
% exact V43 two-input route for each, and select by synchronized-B4 exact
% expected mean-square contraction with an incumbent no-worse fallback.

if nargin < 3 || isempty(options)
    options = struct();
end
allowed = {'period', 'dominantWeight', 'referenceResidualWeight', ...
    'activeResidualWeight', 'missingNeighborWeightMode', ...
    'maximumIncomingCount', 'improvementTolerance', ...
    'minimumRelativeImprovementVsIncumbent', ...
    'maximumCanonicalCycleEnumerationCount', ...
    'cycleSelectionMode', 'maximumExactProposalEvaluations', ...
    'pulsePhaseMode'};
if ~isstruct(options) || ~isscalar(options) || ...
        any(~ismember(fieldnames(options), allowed))
    error('FormationB4V49CycleReference:InvalidOptions', ...
        'The cycle-reference options are malformed.');
end
period = getField(options, 'period', 4);
dominantWeight = getField(options, 'dominantWeight', 0.70);
referenceResidualWeight = getField( ...
    options, 'referenceResidualWeight', 0.05);
activeResidualWeight = getField( ...
    options, 'activeResidualWeight', 0.20);
missingMode = lower(char(getField( ...
    options, 'missingNeighborWeightMode', 'renormalize')));
maximumIncomingCount = getField(options, 'maximumIncomingCount', 2);
tolerance = getField(options, 'improvementTolerance', 1e-12);
minimumRelativeImprovement = getField(options, ...
    'minimumRelativeImprovementVsIncumbent', 0.01);
maximumEnumerationCount = getField(options, ...
    'maximumCanonicalCycleEnumerationCount', 10000);
selectionMode = lower(char(getField(options, 'cycleSelectionMode', ...
    'reliability-proposal-topk')));
maximumExactProposalEvaluations = getField(options, ...
    'maximumExactProposalEvaluations', 3);
pulsePhaseMode = lower(char(getField(options, 'pulsePhaseMode', ...
    'fixed-phase-one')));
if period ~= 4 || dominantWeight <= 0 || ...
        referenceResidualWeight <= 0 || activeResidualWeight <= 0 || ...
        dominantWeight + activeResidualWeight >= 1 || ...
        dominantWeight + referenceResidualWeight >= 1 || ...
        ~ismember(missingMode, {'renormalize', 'self'}) || ...
        maximumIncomingCount ~= 2 || ...
        ~isscalar(tolerance) || ~isfinite(tolerance) || tolerance < 0 || ...
        ~isscalar(minimumRelativeImprovement) || ...
        ~isfinite(minimumRelativeImprovement) || ...
        minimumRelativeImprovement < 0 || ...
        minimumRelativeImprovement > 1 || ...
        ~isscalar(maximumEnumerationCount) || ...
        ~isfinite(maximumEnumerationCount) || ...
        maximumEnumerationCount < 1 || ...
        maximumEnumerationCount ~= round(maximumEnumerationCount) || ...
        ~ismember(selectionMode, { ...
            'reliability-proposal-topk', ...
            'exact-contraction-enumeration'}) || ...
        ~isscalar(maximumExactProposalEvaluations) || ...
        ~isfinite(maximumExactProposalEvaluations) || ...
        maximumExactProposalEvaluations < 1 || ...
        maximumExactProposalEvaluations ~= ...
            round(maximumExactProposalEvaluations) || ...
        ~ismember(pulsePhaseMode, { ...
            'fixed-phase-one', 'best-of-four-development-oracle'})
    error('FormationB4V49CycleReference:InvalidOptions', ...
        'The route score, weight, or materiality rule is invalid.');
end

requiredContext = {'sensorGroupIds', 'sensorPhysicalUids', ...
    'formationPhysicalUidsBySensor', 'positions', ...
    'physicalAdjacency', 'pDropByEdge', 'currentTime'};
requiredReference = {'dominantAdjacency', 'residualAdjacency', ...
    'referenceAdjacency', 'referenceFusionWeights'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~hasExactFields(context, requiredContext) || ...
        ~isstruct(incumbentReference) || ...
        ~isscalar(incumbentReference) || ...
        ~hasExactFields(incumbentReference, requiredReference)
    error('FormationB4V49CycleReference:InvalidContext', ...
        'Only the sanitized route page and exact incumbent are accepted.');
end

sensorGroupIds = reshape(context.sensorGroupIds, 1, []);
sensorUids = reshape(context.sensorPhysicalUids, 1, []);
formationUidsBySensor = reshape( ...
    context.formationPhysicalUidsBySensor, 1, []);
nodeCount = numel(sensorUids);
physical = logical(context.physicalAdjacency);
pDrop = context.pDropByEdge;
if nodeCount < 4 || ...
        ~isValidIntegerVector(sensorGroupIds, nodeCount, false) || ...
        ~isValidIntegerVector(sensorUids, nodeCount, true) || ...
        ~isValidIntegerVector(formationUidsBySensor, nodeCount, false) || ...
        numel(unique(formationUidsBySensor)) < 3 || ...
        ~isa(context.positions, 'double') || ...
        ~isreal(context.positions) || ...
        ~isequal(size(context.positions), [2, nodeCount]) || ...
        any(~isfinite(context.positions(:))) || ...
        ~isBinaryMatrix(physical, nodeCount) || any(diag(physical)) || ...
        ~isequal(physical, physical') || ...
        ~isa(pDrop, 'double') || ~isreal(pDrop) || ...
        ~isequal(size(pDrop), [nodeCount, nodeCount]) || ...
        any(~isfinite(pDrop(:))) || ...
        any(pDrop(:) < 0) || any(pDrop(:) > 1) || ...
        ~isValidReference(incumbentReference, physical, nodeCount)
    error('FormationB4V49CycleReference:InvalidContext', ...
        'The current route page or incumbent contract is invalid.');
end

reliability = 1 - pDrop';
certificateOptions = struct( ...
    'missingNeighborWeightMode', missingMode, ...
    'maximumIncomingCount', maximumIncomingCount);
[incumbentScore, incumbentPhase, incumbentScores] = ...
    scoreSynchronizedReference(incumbentReference, reliability, ...
        period, dominantWeight, activeResidualWeight, ...
        certificateOptions, pulsePhaseMode);

formation = buildFormationView( ...
    formationUidsBySensor, physical);
enumerationWorkUpperBound = boundedFactorialHalf( ...
    formation.count - 1, maximumEnumerationCount);
enumerationCapped = enumerationWorkUpperBound > ...
    maximumEnumerationCount;
if enumerationCapped
    cycleOrders = zeros(0, formation.count);
else
    cycleOrders = enumerateCanonicalPhysicalCycles( ...
        formation.physicalAdjacency, formation.uids);
end
cycleCount = size(cycleOrders, 1);
[proxyBottleneck, proxyMean] = scoreCycleReliabilityProxy( ...
    cycleOrders, formation, reliability);
proxyKeys = [-reshape(proxyBottleneck, [], 1), ...
    -reshape(proxyMean, [], 1), cycleOrders];
if isempty(proxyKeys)
    proxyOrder = zeros(1, 0);
else
    [~, proxyOrder] = sortrows(proxyKeys, 1:size(proxyKeys, 2));
    proxyOrder = reshape(proxyOrder, 1, []);
end
if strcmp(selectionMode, 'exact-contraction-enumeration')
    evaluationOrder = 1:cycleCount;
    feasibleEvaluationLimit = inf;
else
    evaluationOrder = proxyOrder;
    feasibleEvaluationLimit = maximumExactProposalEvaluations;
end
candidateScores = inf(1, cycleCount);
candidateBestPhases = nan(1, cycleCount);
candidateScoreByPhase = nan(cycleCount, period);
candidateRouteHashes = repmat({''}, 1, cycleCount);
candidateReferences = cell(1, cycleCount);
feasible = false(1, cycleCount);
materializationAttempted = false(1, cycleCount);
feasibleEvaluationCount = 0;
for orderIdx = 1:numel(evaluationOrder)
    candidateIdx = evaluationOrder(orderIdx);
    materializationAttempted(candidateIdx) = true;
    registered = buildRegisteredCycleAdjacency( ...
        cycleOrders(candidateIdx, :), formation, ...
        formationUidsBySensor, physical);
    try
        candidate = materializeReference( ...
            context, registered, dominantWeight, ...
            referenceResidualWeight);
    catch errorInfo
        if startsWith(errorInfo.identifier, ...
                'IndexEquivariantFormationRoute:')
            continue;
        end
        rethrow(errorInfo);
    end
    candidateCrossCount = countCrossResidualEdges( ...
        candidate.residualAdjacency, formationUidsBySensor);
    if ~isequal(candidate.dominantAdjacency, ...
            incumbentReference.dominantAdjacency) || ...
            candidateCrossCount ~= 2 * formation.count || ...
            nnz(candidate.residualAdjacency) - candidateCrossCount ~= ...
                nodeCount - 2 * formation.count
        error('FormationB4V49CycleReference:InternalContract', ...
            ['Cycle completion changed the dominant layer or violated ', ...
             'its fixed residual composition.']);
    end
    [candidateScores(candidateIdx), ...
        candidateBestPhases(candidateIdx), ...
        candidateScoreByPhase(candidateIdx, :)] = ...
            scoreSynchronizedReference(candidate, reliability, ...
                period, dominantWeight, activeResidualWeight, ...
                certificateOptions, pulsePhaseMode);
    candidateRouteHashes{candidateIdx} = physicalRouteHash( ...
        candidate.referenceAdjacency, ...
        candidate.referenceFusionWeights, sensorUids);
    candidateReferences{candidateIdx} = candidate;
    feasible(candidateIdx) = true;
    feasibleEvaluationCount = feasibleEvaluationCount + 1;
    if feasibleEvaluationCount >= feasibleEvaluationLimit
        break;
    end
end

feasibleIndices = find(feasible);
rawCycleSelected = ~isempty(feasibleIndices);
rawBestIndex = NaN;
rawBestScore = inf;
rawBestPhase = NaN;
rawBestReference = struct();
if rawCycleSelected
    keys = [reshape(candidateScores(feasibleIndices), [], 1), ...
        cycleOrders(feasibleIndices, :)];
    [~, order] = sortrows(keys, 1:size(keys, 2));
    rawBestIndex = feasibleIndices(order(1));
    rawBestScore = candidateScores(rawBestIndex);
    rawBestPhase = candidateBestPhases(rawBestIndex);
    rawBestReference = candidateReferences{rawBestIndex};
end
rawRelativeImprovement = safeRelativeImprovement( ...
    incumbentScore, rawBestScore);
cycleNoWorse = rawCycleSelected && ...
    rawBestScore <= incumbentScore + tolerance;
cycleStrictlyImproves = rawCycleSelected && ...
    rawBestScore < incumbentScore - tolerance;
materialityGateTriggered = cycleStrictlyImproves && ...
    rawRelativeImprovement + tolerance < minimumRelativeImprovement;
selectedIsCycle = cycleStrictlyImproves && ...
    ~materialityGateTriggered;
if selectedIsCycle
    reference = rawBestReference;
    selectedScore = rawBestScore;
    selectedPhase = rawBestPhase;
    selectedRouteHash = candidateRouteHashes{rawBestIndex};
    selectedCycleOrder = cycleOrders(rawBestIndex, :);
else
    reference = incumbentReference;
    selectedScore = incumbentScore;
    selectedPhase = incumbentPhase;
    selectedRouteHash = physicalRouteHash( ...
        incumbentReference.referenceAdjacency, ...
        incumbentReference.referenceFusionWeights, sensorUids);
    selectedCycleOrder = zeros(1, 0);
end

payload = struct();
payload.contractVersion = ...
    'formation-b4-v49-feasible-cycle-completion-reference-v1';
payload.currentTime = context.currentTime;
payload.nodeCount = nodeCount;
payload.formationCount = formation.count;
payload.sensorPhysicalUids = sort(sensorUids);
payload.formationPhysicalUids = formation.uids;
payload.physicalFormationAdjacency = formation.physicalAdjacency;
payload.maximumCanonicalCycleEnumerationCount = ...
    maximumEnumerationCount;
payload.canonicalCycleEnumerationWorkUpperBound = ...
    enumerationWorkUpperBound;
payload.cycleEnumerationCapped = enumerationCapped;
payload.canonicalPhysicalCycleOrders = cycleOrders;
payload.physicalCycleCandidateCount = cycleCount;
payload.cycleSelectionMode = selectionMode;
payload.maximumExactProposalEvaluations = ...
    maximumExactProposalEvaluations;
payload.cycleReliabilityProxyBottleneckByCandidate = ...
    proxyBottleneck;
payload.cycleReliabilityProxyMeanByCandidate = proxyMean;
payload.cycleReliabilityProxyOrder = proxyOrder;
payload.candidateMaterializationAttemptedMask = ...
    materializationAttempted;
payload.candidateMaterializationAttemptCount = ...
    nnz(materializationAttempted);
payload.feasibleCycleCandidateMask = feasible;
payload.feasibleCycleCandidateCount = nnz(feasible);
payload.exactCandidateCertificateEvaluationCount = ...
    period * nnz(feasible);
payload.incumbentCertificateEvaluationCount = period;
payload.totalCertificateEvaluationCount = ...
    period * (1 + nnz(feasible));
payload.incumbentSynchronizedSquaredFactorByPhase = incumbentScores;
payload.pulsePhaseMode = pulsePhaseMode;
payload.runtimePulsePhaseOneMatched = strcmp( ...
    pulsePhaseMode, 'fixed-phase-one');
payload.bestOfFourPulseDevelopmentOracle = strcmp( ...
    pulsePhaseMode, 'best-of-four-development-oracle');
payload.incumbentBestSynchronizedSquaredFactor = incumbentScore;
payload.incumbentBestSynchronizedPulsePhase = incumbentPhase;
payload.candidateSynchronizedSquaredFactors = candidateScores;
payload.candidateBestSynchronizedPulsePhases = candidateBestPhases;
payload.candidateSynchronizedSquaredFactorByPhase = ...
    candidateScoreByPhase;
payload.candidatePhysicalRouteCanonicalSha256 = ...
    candidateRouteHashes;
payload.rawBestCycleCandidateIndex = rawBestIndex;
payload.rawBestCycleSquaredFactor = rawBestScore;
payload.rawBestCyclePulsePhase = rawBestPhase;
payload.rawBestCycleOrder = getCycleOrder( ...
    cycleOrders, rawBestIndex);
payload.rawBestCycleRelativeImprovementVsIncumbent = ...
    rawRelativeImprovement;
payload.rawBestCycleNoWorseThanIncumbent = cycleNoWorse;
payload.rawBestCycleStrictlyImprovesIncumbent = ...
    cycleStrictlyImproves;
payload.minimumRelativeImprovementVsIncumbent = ...
    minimumRelativeImprovement;
payload.materialityGateTriggered = materialityGateTriggered;
payload.selectedIsCyclePreservingReference = selectedIsCycle;
payload.selectedUsedIncumbentFallback = ~selectedIsCycle;
payload.selectedCycleOrder = selectedCycleOrder;
payload.selectedSquaredFactor = selectedScore;
payload.selectedBestSynchronizedPulsePhase = selectedPhase;
payload.selectedRelativeImprovementVsIncumbent = ...
    safeRelativeImprovement(incumbentScore, selectedScore);
payload.selectedPhysicalRouteCanonicalSha256 = selectedRouteHash;
payload.selectedNoWorseThanIncumbentProxy = ...
    selectedScore <= incumbentScore + tolerance;
payload.dominantLayerBitwiseEqualsIncumbent = ...
    isequal(reference.dominantAdjacency, ...
        incumbentReference.dominantAdjacency);
payload.incumbentCrossResidualMessageCount = ...
    countCrossResidualEdges( ...
        incumbentReference.residualAdjacency, ...
        formationUidsBySensor);
payload.selectedCrossResidualMessageCount = ...
    countCrossResidualEdges( ...
        reference.residualAdjacency, formationUidsBySensor);
payload.selectedLocalResidualMessageCount = nodeCount - ...
    payload.selectedCrossResidualMessageCount;
payload.crossResidualMessageCountDeltaVsIncumbent = ...
    payload.selectedCrossResidualMessageCount - ...
        payload.incumbentCrossResidualMessageCount;
payload.localResidualMessageCountDeltaVsIncumbent = ...
    -payload.crossResidualMessageCountDeltaVsIncumbent;
payload.sameDirectedReferenceMessageBudget = ...
    nnz(reference.referenceAdjacency) == ...
        nnz(incumbentReference.referenceAdjacency) && ...
    nnz(reference.referenceAdjacency) == 2 * nodeCount;
payload.currentGeometryUsed = true;
payload.currentPhysicalGraphUsed = true;
payload.currentLinkReliabilityUsed = true;
payload.posteriorUsed = false;
payload.posteriorSummaryUsed = false;
payload.deliveryAcknowledgmentUsed = false;
payload.truthUsed = false;
payload.measurementUsed = false;
payload.futurePageUsed = false;
payload.realizedDeliveryUniformsUsed = false;
payload.trackingOutcomeScored = false;
payload.graphCertificateStandaloneTrackingObjective = false;
payload.frozenCurrentPagePropagationProxyOnly = true;
payload.exactGlobalCycleOptimumClaimAllowed = strcmp( ...
    selectionMode, 'exact-contraction-enumeration') && ...
    all(materializationAttempted | ~isfinite(proxyBottleneck));
payload.reliabilityProposalExactCertificateGated = strcmp( ...
    selectionMode, 'reliability-proposal-topk');
payload.timeVaryingNoWorseCertified = false;
payload.trackingSafetyClaimAllowed = false;
payload.routeDisseminationImplemented = false;
payload.sameTotalByteClaimAllowed = false;
payload.validationClaimAllowed = false;
payload.developmentEvidenceOnly = true;
payload.canonicalSha256 = computeCanonicalValueSha256(payload);
details = payload;
details.selectedReference = reference;
details.incumbentReference = incumbentReference;
end

function count = boundedFactorialHalf(value, cap)
count = 1;
for factor = 2:value
    count = count * factor;
    if count > 2 * cap
        count = cap + 1;
        return;
    end
end
count = ceil(count / 2);
end

function formation = buildFormationView(formationUidsBySensor, physical)
uids = sort(unique(formationUidsBySensor));
count = numel(uids);
members = cell(1, count);
adjacency = false(count);
for formationIdx = 1:count
    members{formationIdx} = find( ...
        formationUidsBySensor == uids(formationIdx));
end
for receiverIdx = 1:count
    for senderIdx = 1:count
        if receiverIdx ~= senderIdx
            adjacency(receiverIdx, senderIdx) = any(any(physical( ...
                members{receiverIdx}, members{senderIdx})));
        end
    end
end
adjacency = adjacency & adjacency';
formation = struct('count', count, 'uids', uids, ...
    'members', {members}, 'physicalAdjacency', adjacency);
end

function [bottleneck, meanReliability] = ...
    scoreCycleReliabilityProxy(cycleOrders, formation, reliability)
candidateCount = size(cycleOrders, 1);
bottleneck = -inf(1, candidateCount);
meanReliability = -inf(1, candidateCount);
for candidateIdx = 1:candidateCount
    order = cycleOrders(candidateIdx, :);
    directedValues = zeros(1, 2 * formation.count);
    cursor = 0;
    for position = 1:formation.count
        first = find(formation.uids == order(position));
        second = find(formation.uids == ...
            order(mod(position, formation.count) + 1));
        firstMembers = formation.members{first};
        secondMembers = formation.members{second};
        cursor = cursor + 1;
        directedValues(cursor) = max(max( ...
            reliability(firstMembers, secondMembers)));
        cursor = cursor + 1;
        directedValues(cursor) = max(max( ...
            reliability(secondMembers, firstMembers)));
    end
    bottleneck(candidateIdx) = min(directedValues);
    meanReliability(candidateIdx) = mean(directedValues);
end
end

function orders = enumerateCanonicalPhysicalCycles(adjacency, uids)
count = numel(uids);
root = 1;
tailOrders = perms(2:count);
orders = zeros(0, count);
for rowIdx = 1:size(tailOrders, 1)
    order = [root, tailOrders(rowIdx, :)];
    if uids(order(2)) > uids(order(end))
        continue;
    end
    valid = true;
    for position = 1:count
        valid = valid && adjacency(order(position), ...
            order(mod(position, count) + 1));
    end
    if valid
        orders(end + 1, :) = uids(order); %#ok<AGROW>
    end
end
end

function registered = buildRegisteredCycleAdjacency( ...
        cycleUids, formation, formationUidsBySensor, physical)
formationCount = formation.count;
cyclePairs = false(formationCount);
for position = 1:formationCount
    firstUid = cycleUids(position);
    secondUid = cycleUids(mod(position, formationCount) + 1);
    first = find(formation.uids == firstUid);
    second = find(formation.uids == secondUid);
    cyclePairs(first, second) = true;
    cyclePairs(second, first) = true;
end
registered = false(size(physical));
for receiverIdx = 1:formationCount
    receivers = formationUidsBySensor == formation.uids(receiverIdx);
    registered(receivers, receivers) = physical(receivers, receivers);
    for senderIdx = 1:formationCount
        if cyclePairs(receiverIdx, senderIdx)
            senders = formationUidsBySensor == formation.uids(senderIdx);
            registered(receivers, senders) = ...
                physical(receivers, senders);
        end
    end
end
registered = registered & registered';
registered(1:size(registered, 1)+1:end) = false;
end

function reference = materializeReference( ...
        context, registered, dominantWeight, residualWeight)
nodeCount = numel(context.sensorPhysicalUids);
routeContext = struct();
routeContext.localPosteriorBySensor = cell(1, nodeCount);
routeContext.model = struct('dynamicTopologyScenario', struct( ...
    'config', struct('sensorGroupIds', context.sensorGroupIds), ...
    'staticAdjacency', registered));
routeContext.baseAdjacency = registered;
routeContext.physicalAdjacency = context.physicalAdjacency;
routeContext.positions = context.positions;
routeContext.sensorPhysicalUids = context.sensorPhysicalUids;
routeContext.formationPhysicalUidsBySensor = ...
    context.formationPhysicalUidsBySensor;
routeContext.commConfig = struct('pDropByEdge', context.pDropByEdge);
routeContext.currentTime = context.currentTime;
routeContext.directedMessageBudget = 2 * nodeCount;
[adjacency, policy] = ...
    selectIndexEquivariantFormationBackbonePolicy( ...
        routeContext, struct('dominantWeight', dominantWeight, ...
            'residualWeight', residualWeight));
reference = struct( ...
    'dominantAdjacency', logical(policy.dominantAdjacency), ...
    'residualAdjacency', logical(policy.residualAdjacency), ...
    'referenceAdjacency', logical(adjacency), ...
    'referenceFusionWeights', policy.fusionWeightMatrix);
end

function [bestScore, bestPhase, scores] = ...
    scoreSynchronizedReference(reference, reliability, period, ...
        dominantWeight, activeResidualWeight, certificateOptions, ...
        pulsePhaseMode)
scores = nan(1, period);
for pulsePhase = 1:period
    [adjacency, weights] = materializeSynchronizedSchedule( ...
        reference.dominantAdjacency, ...
        reference.residualAdjacency, pulsePhase, period, ...
        dominantWeight, activeResidualWeight);
    certificate = ...
        computeReliableKlaWindowMeanSquareContractionCertificate( ...
            adjacency, weights, ...
            repmat(reliability, 1, 1, period), ...
            certificateOptions);
    scores(pulsePhase) = certificate. ...
        worstCaseExpectedSquaredContractionFactor;
end
if strcmp(pulsePhaseMode, 'fixed-phase-one')
    bestPhase = 1;
    bestScore = scores(1);
else
    [bestScore, bestPhase] = min(scores);
end
end

function [adjacency, weights] = materializeSynchronizedSchedule( ...
        dominant, residual, pulsePhase, period, ...
        dominantWeight, activeResidualWeight)
nodeCount = size(dominant, 1);
adjacency = false(nodeCount, nodeCount, period);
weights = zeros(nodeCount, nodeCount, period);
for phase = 1:period
    activeResidual = false(nodeCount);
    if phase == pulsePhase
        activeResidual = residual;
    end
    adjacency(:, :, phase) = dominant | activeResidual;
    pageWeights = zeros(nodeCount);
    pageWeights(dominant) = dominantWeight;
    pageWeights(activeResidual) = activeResidualWeight;
    pageWeights(1:nodeCount+1:end) = 1 - sum(pageWeights, 2)';
    weights(:, :, phase) = pageWeights;
end
end

function valid = isValidReference(reference, physical, nodeCount)
dominant = logical(reference.dominantAdjacency);
residual = logical(reference.residualAdjacency);
route = logical(reference.referenceAdjacency);
weights = reference.referenceFusionWeights;
valid = isequal(size(dominant), [nodeCount, nodeCount]) && ...
    isequal(size(residual), [nodeCount, nodeCount]) && ...
    isequal(route, dominant | residual) && ...
    ~any(dominant(:) & residual(:)) && ...
    all(sum(dominant, 2) == 1) && all(sum(residual, 2) == 1) && ...
    nnz(route) == 2 * nodeCount && ...
    ~any(route(:) & ~physical(:)) && ...
    isa(weights, 'double') && isreal(weights) && ...
    isequal(size(weights), [nodeCount, nodeCount]) && ...
    all(isfinite(weights(:))) && all(weights(:) >= 0) && ...
    all(abs(sum(weights, 2) - 1) < 1e-12);
end

function sha256 = physicalRouteHash(adjacency, weights, sensorUids)
[sortedUids, order] = sort(sensorUids);
payload = struct('contractVersion', ...
    'formation-b4-v49-physical-route-v1', ...
    'sensorPhysicalUids', sortedUids, ...
    'adjacency', logical(adjacency(order, order)), ...
    'fusionWeightMatrix', weights(order, order));
sha256 = computeCanonicalValueSha256(payload);
end

function count = countCrossResidualEdges(residual, formationUids)
crossMask = formationUids(:) ~= formationUids(:)';
count = nnz(logical(residual) & crossMask);
end

function order = getCycleOrder(orders, index)
if isempty(orders) || ~isscalar(index) || ~isfinite(index)
    order = zeros(1, 0);
else
    order = orders(index, :);
end
end

function valid = isValidIntegerVector(values, count, requireUnique)
valid = isa(values, 'double') && isreal(values) && ...
    numel(values) == count && all(isfinite(values)) && ...
    all(values > 0) && all(values == round(values));
if requireUnique
    valid = valid && numel(unique(values)) == count;
end
end

function valid = isBinaryMatrix(matrix, count)
valid = (islogical(matrix) || isnumeric(matrix)) && ...
    isreal(matrix) && isequal(size(matrix), [count, count]) && ...
    all(isfinite(matrix(:))) && ...
    all(matrix(:) == 0 | matrix(:) == 1);
end

function value = safeRelativeImprovement(reference, candidate)
if reference > 0 && isfinite(candidate)
    value = (reference - candidate) / reference;
elseif reference > 0
    value = -inf;
elseif candidate == 0
    value = 0;
else
    value = -inf;
end
end

function passed = hasExactFields(structure, expected)
passed = numel(fieldnames(structure)) == numel(expected) && ...
    all(ismember(expected, fieldnames(structure)));
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
