function [adjacency, details] = ...
    selectLearnedRollingSafeRoutingPolicy( ...
        context, modelOrPath, options)
% SELECTLEARNEDROLLINGSAFEROUTINGPOLICY Learned scores, exact safety layer.
%
% The learned model reads only observable posterior/link/history features.
% Its scores are passed to the same joint rolling-B3 projection used by
% analytic and privileged diagnostics. The model cannot bypass message,
% payload, receiver-completeness, or rolling-connectivity constraints.

if nargin < 3 || isempty(options)
    options = struct();
end
model = resolveModel(modelOrPath);
validateModel(model);
sourceWeight = getField(options, ...
    'sourceWeight', model.sourceWeight);
if abs(sourceWeight - model.sourceWeight) > 1e-12
    error('Learned rollout source weight differs from training.');
end
payloadToleranceFraction = getField(options, ...
    'payloadToleranceFraction', ...
    model.payloadToleranceFraction);
if ~sameScalar(payloadToleranceFraction, ...
        model.payloadToleranceFraction)
    error(['Learned rollout payload tolerance differs from the ', ...
        'frozen training projector.']);
end
featureOptions = struct( ...
    'featureContextMode', model.featureContextMode);
policyOptions = struct( ...
    'sourceWeight', sourceWeight, ...
    'payloadToleranceFraction', payloadToleranceFraction, ...
    'edgeScoreFcnReturnsDetails', true, ...
    'edgeScoreFcn', ...
        @(scoreContext, receiverIndices, ...
            senderIndices, unusedBaselineSources) ...
            computeScores( ...
                scoreContext, receiverIndices, ...
                senderIndices, model, featureOptions), ...
    'posteriorUsed', true, ...
    'truthUsed', false, ...
    'currentLinkReliabilityUsed', true);
[adjacency, details] = selectRollingSafeRoutingPolicy( ...
    context, 'external-scores', policyOptions);
details.mode = 'learned-rolling-safe-rollout-edge-v1';
details.modelKind = model.kind;
details.modelTrainingSeeds = model.trainingSeeds;
details.modelFeaturesUseTruth = model.featuresUseTruth;
details.modelLabelsUseTruth = model.labelsUseTruth;
details.modelFrozen = logical(model.frozen);
details.modelAcceptedForClosedLoopScreen = ...
    logical(model.acceptedForClosedLoopScreen);
end

function [scores, scoreDetails] = computeScores( ...
        context, expectedReceivers, expectedSenders, ...
        model, featureOptions)
[X, featureNames, receiverIndices, senderIndices, metadata] = ...
    computeRollingSafeDirectedActionExamples( ...
        context, model.sourceWeight, featureOptions);
if ~isequal(reshape(featureNames, 1, []), ...
        reshape(model.allFeatureNames, 1, []))
    error('Learned rollout feature-name contract mismatch.');
end
nodeCount = numel(context.localPosteriorBySensor);
featureKeys = receiverIndices + ...
    nodeCount * (senderIndices - 1);
expectedKeys = reshape(expectedReceivers, [], 1) + ...
    nodeCount * (reshape(expectedSenders, [], 1) - 1);
[members, featureRows] = ismember(expectedKeys, featureKeys);
if any(~members) || numel(unique(featureRows)) ~= numel(featureRows) || ...
        numel(featureKeys) ~= numel(expectedKeys) || ...
        numel(unique(featureKeys)) ~= numel(featureKeys)
    error(['Learned rollout feature edges do not match the safe ', ...
        'action set.']);
end
X = X(featureRows, :);
receiverIndices = reshape(expectedReceivers, [], 1);
senderIndices = reshape(expectedSenders, [], 1);
scores = scoreRollingSafeRolloutEdgeModel(model, X);
scoreDetails = struct( ...
    'receiverIndices', receiverIndices, ...
    'senderIndices', senderIndices, ...
    'residualScores', scores, ...
    'featureMetadata', metadata, ...
    'modelKind', model.kind, ...
    'truthUsed', false);
end

function model = resolveModel(modelOrPath)
if isstruct(modelOrPath)
    model = modelOrPath;
    return;
end
if isempty(modelOrPath) || ~ischar(modelOrPath)
    error('A rolling-safe rollout model struct or MAT path is required.');
end
loaded = load(modelOrPath, 'model');
if ~isfield(loaded, 'model')
    error('Rolling-safe rollout model file does not contain model.');
end
model = loaded.model;
end

function validateModel(model)
required = { ...
    'kind', 'sourceWeight', 'featureContextMode', ...
    'payloadToleranceFraction', ...
    'allFeatureNames', 'trainingSeeds', ...
    'featuresUseTruth', 'labelsUseTruth', 'frozen', ...
    'acceptedForClosedLoopScreen'};
if ~isstruct(model) || ~all(isfield(model, required)) || ...
        ~strcmp(model.kind, 'mlp-rolling-safe-rollout-edge-v1') || ...
        model.featuresUseTruth || ~model.labelsUseTruth || ...
        ~isscalar(model.frozen) || ~logical(model.frozen)
    error('Invalid learned rolling-safe rollout model contract.');
end
end

function equal = sameScalar(left, right)
equal = isscalar(left) && isscalar(right) && ...
    ((isinf(left) && isinf(right) && sign(left) == sign(right)) || ...
     (isfinite(left) && isfinite(right) && abs(left - right) <= 1e-12));
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
