function [adjacency, details] = ...
    selectLabelSetMessagePassingRoutingPolicy( ...
        context, model, options)
% SELECTLABELSETMESSAGEPASSINGROUTINGPOLICY Learned score, safe projector.

if nargin < 3 || isempty(options)
    options = struct();
end
protocol = getField(options, 'protocol', ...
    getLabelSetSimulatorPolicyProtocol());
if ~protocol.messagePassingImplementationAuthorized
    error('Label-set message-passing routing is not authorized.');
end
block = computeLabelSetMessagePassingPolicyBlock( ...
    context, struct('protocol', protocol));
scoreOutput = scoreLabelSetMessagePassingPolicyModel( ...
    model, block);
fixedResidualWeight = getField( ...
    options, 'fixedResidualWeight', []);
if isempty(fixedResidualWeight)
    residualWeightMode = 'learned-grid';
else
    weightIdx = find(abs(block.residualWeightGrid - ...
        fixedResidualWeight) <= 1e-12);
    if numel(weightIdx) ~= 1
        error('Fixed label-set residual weight is not registered.');
    end
    scoreOutput.edgeScore = ...
        scoreOutput.edgeTaskScore(:, weightIdx);
    scoreOutput.selectedResidualWeightByExample = ...
        fixedResidualWeight * ...
            ones(block.candidateCount, 1);
    residualWeightMode = 'fixed-registered-weight';
end
policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', protocol.localResidualWeight, ...
    'edgeScoreFcn', @provideScores, ...
    'edgeScoreFcnReturnsDetails', true, ...
    'posteriorUsed', true, ...
    'truthUsed', false, ...
    'currentLinkReliabilityUsed', true);
[adjacency, details] = ...
    selectBackboneResidualSplicedCyclePolicy( ...
        context, 'external-scores', policyOptions);
if details.truthUsed || ...
        details.crossFormationMessageCount ~= ...
            numel(unique(block.groupIds)) || ...
        nnz(adjacency) ~= ...
            nnz(details.baselineAdjacency) || ...
        ~details.sensorWindowStrongConnected || ...
        ~details.formationWindowStrongConnected || ...
        details.repairTriggered || ...
        details.payloadEmergencyUsed
    error(['Label-set safe routing projection contract failed ', ...
        '(truth=%d, cross=%d/%d, messages=%d/%d, ', ...
        'sensorStrong=%d, formationStrong=%d, repair=%d, ', ...
        'payloadEmergency=%d).'], ...
        details.truthUsed, ...
        details.crossFormationMessageCount, ...
        numel(unique(block.groupIds)), ...
        nnz(adjacency), ...
        nnz(details.baselineAdjacency), ...
        details.sensorWindowStrongConnected, ...
        details.formationWindowStrongConnected, ...
        details.repairTriggered, ...
        details.payloadEmergencyUsed);
end
details.mode = ...
    'label-set-two-round-message-passing-safe-residual-cycle';
details.modelContractVersion = model.contractVersion;
details.labelFeatureContractSha256 = ...
    block.labelFeatureContractSha256;
details.aggregateFeatureContractSha256 = ...
    block.aggregateFeatureContractSha256;
details.messagePassingRoundCount = ...
    protocol.messagePassingRoundCount;
details.residualWeightMode = residualWeightMode;
details.fixedResidualWeight = fixedResidualWeight;
details.numericLabelIdentifiersUsedAsFeatures = false;
details.safeProjectorUsed = true;
details.nominalGuaranteeScope = ...
    protocol.nominalGuaranteeScope;

    function [edgeScores, scoreDetails] = provideScores( ...
            ~, receiverIndices, senderIndices, ~)
        if ~isequal(reshape(receiverIndices, [], 1), ...
                reshape(block.receiverIndices, [], 1)) || ...
                ~isequal(reshape(senderIndices, [], 1), ...
                reshape(block.senderIndices, [], 1))
            error('Safe projector candidate order changed.');
        end
        edgeScores = scoreOutput.edgeScore;
        scoreDetails = struct( ...
            'selectedResidualWeightByExample', ...
                scoreOutput. ...
                    selectedResidualWeightByExample, ...
            'posteriorUsed', true, ...
            'truthUsed', false, ...
            'groundTruthUsed', false, ...
            'futureOutcomeUsed', false, ...
            'currentLinkReliabilityUsed', true, ...
            'numericLabelIdentifiersUsedAsFeatures', false, ...
            'modelContractVersion', model.contractVersion);
    end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
