function [adjacency, details] = ...
    selectLabelSetQuotaAdaptiveRoutingPolicy( ...
        context, model, crossEdgeQuota, options)
% SELECTLABELSETQUOTAADAPTIVEROUTINGPOLICY GNN-scored safe cross quota.
%
% The high-weight fixed-index route is preserved. The GNN scores all
% message-count-preserving cross-formation residual replacements, and the
% exact rolling-B3 integer projector selects the requested number of
% current edges while certifying that a same-quota successor exists.

if nargin < 4 || isempty(options)
    options = struct();
end
protocol = getField(options, 'protocol', ...
    getLabelSetSimulatorPolicyProtocol());
if ~protocol.messagePassingImplementationAuthorized || ...
        ~protocol.quotaAdaptiveRoutingImplementationAuthorized
    error('Label-set quota-adaptive routing is not authorized.');
end
crossEdgeQuota = round(crossEdgeQuota);
if ~isscalar(crossEdgeQuota) || ...
        ~isfinite(crossEdgeQuota) || ...
        ~ismember(crossEdgeQuota, ...
            protocol.quotaAdaptiveRoutingM24QuotaGrid)
    error('Cross-edge quota is not registered.');
end
fixedResidualWeight = getField(options, ...
    'fixedResidualWeight', ...
    protocol.quotaAdaptiveRoutingResidualWeight);
block = computeLabelSetMessagePassingPolicyBlock( ...
    context, struct('protocol', protocol));
scoreOutput = scoreLabelSetMessagePassingPolicyModel( ...
    model, block);
weightIdx = find(abs(block.residualWeightGrid - ...
    fixedResidualWeight) <= 1e-12);
if numel(weightIdx) ~= 1
    error('Quota-adaptive residual weight is not registered.');
end
blockScores = reshape( ...
    scoreOutput.edgeTaskScore(:, weightIdx), [], 1);
nodeCount = numel(context.localPosteriorBySensor);
blockKeys = block.receiverIndices + ...
    nodeCount * (block.senderIndices - 1);
if numel(unique(blockKeys)) ~= numel(blockKeys)
    error('Quota-adaptive label-set score block has duplicate edges.');
end
policyOptions = struct( ...
    'dominantWeight', protocol.dominantWeight, ...
    'residualWeight', fixedResidualWeight, ...
    'edgeScoreFcn', @provideScores, ...
    'edgeScoreFcnReturnsDetails', true, ...
    'posteriorUsed', true, ...
    'truthUsed', false, ...
    'currentLinkReliabilityUsed', true, ...
    'minimumCurrentCrossEdges', crossEdgeQuota, ...
    'maximumCurrentCrossEdges', crossEdgeQuota, ...
    'minimumSuccessorCrossEdges', crossEdgeQuota, ...
    'maximumSuccessorCrossEdges', crossEdgeQuota, ...
    'payloadToleranceFraction', inf);
[adjacency, details] = ...
    selectBackbonePreservingResidualRoutingPolicy( ...
        context, 'external-scores', policyOptions);
validateProjection(context, protocol, adjacency, ...
    details, crossEdgeQuota);
residualWeightCode = round(100 * fixedResidualWeight);
if abs(fixedResidualWeight - ...
        residualWeightCode / 100) > 1e-12
    error('Quota-adaptive residual weight lacks a stable action code.');
end
details.mode = sprintf( ...
    'label-set-quota-adaptive-safe-q%d-e%02d-a70', ...
    crossEdgeQuota, residualWeightCode);
details.modelContractVersion = model.contractVersion;
details.labelFeatureContractSha256 = ...
    block.labelFeatureContractSha256;
details.aggregateFeatureContractSha256 = ...
    block.aggregateFeatureContractSha256;
details.messagePassingRoundCount = ...
    protocol.messagePassingRoundCount;
details.fixedResidualWeight = fixedResidualWeight;
details.crossEdgeQuota = crossEdgeQuota;
details.sameQuotaSuccessorCertified = true;
details.numericLabelIdentifiersUsedAsFeatures = false;
details.safeProjectorUsed = true;
details.nominalGuaranteeScope = ...
    protocol.nominalGuaranteeScope;
details.truthUsed = false;
details.groundTruthUsed = false;
details.futureOutcomeUsed = false;

    function [scores, scoreDetails] = provideScores( ...
            ~, receiverIndices, senderIndices, ~)
        receiverIndices = reshape(receiverIndices, [], 1);
        senderIndices = reshape(senderIndices, [], 1);
        queryKeys = receiverIndices + ...
            nodeCount * (senderIndices - 1);
        scores = -inf(numel(queryKeys), 1);
        [present, blockLocations] = ...
            ismember(queryKeys, blockKeys);
        scores(present) = blockScores(blockLocations(present));
        scoreDetails = struct( ...
            'receiverIndices', receiverIndices, ...
            'senderIndices', senderIndices, ...
            'labelSetScoredExampleMask', present, ...
            'labelSetScoredExampleCount', nnz(present), ...
            'posteriorUsed', true, ...
            'truthUsed', false, ...
            'groundTruthUsed', false, ...
            'futureOutcomeUsed', false, ...
            'currentLinkReliabilityUsed', true, ...
            'numericLabelIdentifiersUsedAsFeatures', false, ...
            'modelContractVersion', model.contractVersion);
    end
end

function validateProjection( ...
        context, protocol, adjacency, details, quota)
requiredFields = { ...
    'realizedCrossCount', 'successorCrossCount', ...
    'successorReserveViable', ...
    'sensorWindowStrongConnected', ...
    'formationWindowStrongConnected', ...
    'repairTriggered', 'payloadEmergencyUsed', ...
    'topologyInfeasible', 'truthUsed', ...
    'fusionWeightMatrix'};
missingFields = requiredFields(~isfield(details, requiredFields));
if ~isempty(missingFields)
    error(['Label-set quota-adaptive safe projection is missing: ', ...
        strjoin(missingFields, ', '), '.']);
end
failedChecks = {};
if details.realizedCrossCount ~= quota
    failedChecks{end + 1} = sprintf( ...
        'cross-count=%d(expected=%d)', ...
        details.realizedCrossCount, quota);
end
if details.successorCrossCount ~= quota
    failedChecks{end + 1} = sprintf( ...
        'successor-cross-count=%d(expected=%d)', ...
        details.successorCrossCount, quota);
end
if ~details.successorReserveViable
    failedChecks{end + 1} = 'successor-reserve';
end
if nnz(adjacency) ~= ...
        protocol.quotaAdaptiveRoutingExpectedMessageCount
    failedChecks{end + 1} = sprintf( ...
        'message-count=%d(expected=%d)', nnz(adjacency), ...
        protocol.quotaAdaptiveRoutingExpectedMessageCount);
end
if any(adjacency(:) & ~logical(context.physicalAdjacency(:)))
    failedChecks{end + 1} = 'physical-admissibility';
end
if ~details.sensorWindowStrongConnected
    failedChecks{end + 1} = 'sensor-window-connectivity';
end
if ~details.formationWindowStrongConnected
    failedChecks{end + 1} = 'formation-window-connectivity';
end
if details.repairTriggered
    failedChecks{end + 1} = 'repair-triggered';
end
if details.payloadEmergencyUsed
    failedChecks{end + 1} = 'payload-emergency';
end
if details.topologyInfeasible
    failedChecks{end + 1} = 'topology-infeasible';
end
if details.truthUsed
    failedChecks{end + 1} = 'truth-used';
end
if any(abs(sum(details.fusionWeightMatrix, 2) - 1) > 1e-12)
    failedChecks{end + 1} = 'fusion-row-stochasticity';
end
if ~isempty(failedChecks)
    error(['Label-set quota-adaptive safe projection failed: ', ...
        strjoin(failedChecks, ', '), '.']);
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
