function [adjacency, details] = ...
        selectDirectGraphPayloadRepairV214ReferencePolicy(context)
% SELECTDIRECTGRAPHPAYLOADREPAIRV214REFERENCEPOLICY Cheap graph snapshot.
%
% The selected route is the same current-physical fixed spliced cycle used
% by the reference policy.  Posterior features are observed only to build
% the formation graph; they cannot alter this route during trajectory
% collection.

routeProtocol = getFormationIsolateReconnectProbeProtocol();
routeOptions = struct( ...
    'dominantWeight', routeProtocol.dominantWeight, ...
    'residualWeight', routeProtocol.residualWeight);
[adjacency, details] = selectBackboneResidualSplicedCyclePolicy( ...
    context, 'fixed-counter-clockwise', routeOptions);

if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, { ...
            'localPosteriorBySensor', 'model', 'commConfig', ...
            'currentTime', 'previousAdjacency', ...
            'physicalAdjacency', 'positions'})) || ...
        ~isfield(context.model, 'dynamicTopologyScenario') || ...
        ~isfield(context.model.dynamicTopologyScenario, 'config') || ...
        ~isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds')
    error('DirectGraphPayloadRepairV214:MissingObservableContext', ...
        'V214 requires the current truth-free observable graph state.');
end
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
graph = buildObservableFormationGraphSnapshotV208( ...
    context.localPosteriorBySensor, groupIds, ...
    context.physicalAdjacency, adjacency, ...
    context.previousAdjacency, context.positions, ...
    context.commConfig, context.model, context.currentTime, 0);
featureIdx = find(strcmp(graph.nodeFeatureNames, 'need_max'));
if numel(featureIdx) ~= 1
    error('DirectGraphPayloadRepairV214:NeedFeatureDrift', ...
        'The V208 graph must expose one need_max feature.');
end
formationNeed = reshape(graph.nodeFeatures(:, featureIdx), 1, []);
withholdingFeatures = buildDirectGraphWithholdingFeaturesV215( ...
    context, groupIds, adjacency, graph);
protocol = getDirectGraphPayloadRepairControllerV214Protocol();

details.posteriorUsed = true;
details.posteriorPayloadMetadataUsed = false;
details.truthUsed = false;
details.futureOutcomeUsed = false;
details.currentLinkReliabilityUsed = false;
details.hierarchicalFormationIds = reshape(graph.formationIds, 1, []);
details.hierarchicalFormationNeedByFormation = formationNeed;
details.hierarchicalMaximumFormationNeed = max(formationNeed);
details.hierarchicalGraphContractVersion = graph.contractVersion;
details.hierarchicalNeedFeatureName = 'need_max';
details.hierarchicalNeedAffectsRouting = false;
details.hierarchicalHistoryWarmupReferenceUsed = false;
details.hierarchicalNeedTruthUsed = false;
details.hierarchicalNeedFutureInformationUsed = false;
details.hierarchicalWithholdingFeatureContractVersion = ...
    withholdingFeatures.contractVersion;
details.hierarchicalWithholdingFeatureNames = ...
    withholdingFeatures.formationFeatureNames;
details.hierarchicalWithholdingFeaturesByFormation = ...
    withholdingFeatures.formationFeatures;
details.hierarchicalWithholdingPayloadFeatureNames = ...
    withholdingFeatures.payloadFeatureNames;
details.hierarchicalWithholdingPayloadFeaturesByFormation = ...
    withholdingFeatures.payloadFeatures;
details.hierarchicalWithholdingReferencePayloadBytesProxy = ...
    withholdingFeatures.referencePayloadBytesProxy;
details.hierarchicalWithholdingTruthUsed = false;
details.hierarchicalWithholdingFutureInformationUsed = false;
details.contractVersion = ...
    'direct-graph-payload-repair-v214-reference-policy-v1';
details.armId = protocol.base.policyName;
details.protocolId = protocol.id;
end
