function [adjacency, details] = ...
    selectTemporalObservationSupportedRepairV198Policy(context)
% SELECTTEMPORALOBSERVATIONSUPPORTEDREPAIRV198POLICY Two-page abstain.

protocol = getTemporalObservationSupportedRepairV198Protocol();
routeProtocol = getFormationIsolateReconnectProbeProtocol();
routeOptions = struct( ...
    'dominantWeight', routeProtocol.dominantWeight, ...
    'residualWeight', routeProtocol.residualWeight);
[adjacency, details] = ...
    selectBackboneResidualSplicedCyclePolicy( ...
        context, 'fixed-counter-clockwise', routeOptions);

required = { ...
    'model', 'previousPayloadReleaseHistory', ...
    'previousPayloadReleaseHistoryCount', ...
    'previousPayloadReleaseHistoryTimes', ...
    'previousLocalPosteriorHistory', ...
    'previousLocalPosteriorHistoryCount', ...
    'previousLocalPosteriorHistoryTimes'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~all(isfield(context, required)) || ...
        ~isfield(context.model, 'dynamicTopologyScenario') || ...
        ~isfield(context.model.dynamicTopologyScenario, 'config') || ...
        ~isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds')
    error('TemporalSetRepairV198:MissingCausalHistory', ...
        'The observable runtime context lacks causal support history.');
end
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
[~, control] = computeFormationRoutingLeverageSignature( ...
    context, groupIds);
metrics = computeNetworkAdditiveFormationRiskV65( ...
    control, context, groupIds, protocol.positiveSupportThreshold);
proposal = selectPositiveNetAddressableRiskSetV97( ...
    metrics, protocol);
supportContext = context;
supportContext.localPosteriorBySensor = ...
    aggregateTemporalPosteriorSupportV198( ...
        context.localPosteriorBySensor, ...
        context.previousLocalPosteriorHistory, ...
        protocol.supportHistoryDepth);
setSafe = projectObservationSupportedSetSafeV194( ...
    control, supportContext, groupIds, proposal.selectedFormationIds, ...
    protocol.positiveSupportThreshold, struct( ...
        'supportMode', protocol.supportMode));
releaseHistory = context.previousPayloadReleaseHistory;
if numel(releaseHistory) > protocol.releaseHistoryDepth
    releaseHistory = ...
        releaseHistory(end-protocol.releaseHistoryDepth+1:end);
end
projection = projectBudgetedObservationSupportedRepairV197( ...
    setSafe, releaseHistory, protocol);

details.posteriorUsed = true;
details.posteriorPayloadMetadataUsed = false;
details.truthUsed = false;
details.futureOutcomeUsed = false;
details.currentLinkReliabilityUsed = true;
details.contractVersion = ...
    'temporal-observation-supported-repair-v198-policy-v1';
details.armId = protocol.outcomePolicyName;
details.protocolId = protocol.id;
details.retentionDebtFractionByFormation = reshape( ...
    metrics.networkRescueFractionByFormation, 1, []);
details.retentionDebtThresholdByFormation = reshape( ...
    metrics.networkUsefulLossFractionByFormation, 1, []);
details.retentionDebtSingleAvailableMask = reshape( ...
    metrics.singleActionAvailableMask, 1, []);
details.retentionDebtSingleSafetyMask = reshape( ...
    metrics.crossSupportedDownwardCrossingsByFormation, 1, []) == 0;
details.retentionDebtRequestedFormationIds = ...
    proposal.selectedFormationIds;
details.retentionDebtSelectedFormationIds = ...
    projection.selectedFormationIds;
details.retentionDebtProjectionRemovalOrder = ...
    projection.releaseFormationIds;
details.onlinePositiveNetMetrics = metrics;
details.onlinePositiveNetSelection = proposal;
details.observationSupportedSetSafeProjection = setSafe;
details.budgetedObservationSupportedRepairProjection = projection;
details.temporalSupportHistoryDepth = protocol.supportHistoryDepth;
details.temporalSupportHistoryCount = ...
    context.previousLocalPosteriorHistoryCount;
end
