function [adjacency, details] = ...
    selectOnlinePositiveNetAddressablePayloadV99Policy(context)
% SELECTONLINEPOSITIVENETADDRESSABLEPAYLOADV99POLICY Re-select each step.
%
% The carrier route and fusion weights remain the fixed counter-clockwise
% reference.  The policy uses the current pre-fusion posterior, current
% physical action set and past selected graphs to choose the receiver
% formations whose cross-formation full-posterior payload is withheld at
% this step.  Truth, future measurements and future outcomes are absent from
% the observable topology-policy context.

protocol = getOnlinePositiveNetAddressablePayloadV99Protocol();
routeProtocol = getFormationIsolateReconnectProbeProtocol();
routeOptions = struct( ...
    'dominantWeight', routeProtocol.dominantWeight, ...
    'residualWeight', routeProtocol.residualWeight);
[adjacency, details] = ...
    selectBackboneResidualSplicedCyclePolicy( ...
        context, 'fixed-counter-clockwise', routeOptions);

if ~isstruct(context) || ~isscalar(context) || ...
        ~isfield(context, 'model') || ...
        ~isfield(context.model, 'dynamicTopologyScenario') || ...
        ~isfield(context.model.dynamicTopologyScenario, 'config') || ...
        ~isfield(context.model.dynamicTopologyScenario.config, ...
            'sensorGroupIds')
    error('OnlinePositiveNetV99:MissingFormationMembership', ...
        'The observable runtime context lacks formation membership.');
end
groupIds = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
[~, control] = computeFormationRoutingLeverageSignature( ...
    context, groupIds);
metrics = computeNetworkAdditiveFormationRiskV65( ...
    control, context, groupIds, protocol.positiveSupportThreshold);
selection = selectPositiveNetAddressableRiskSetV97( ...
    metrics, protocol);

details.posteriorUsed = true;
details.posteriorPayloadMetadataUsed = false;
details.truthUsed = false;
details.futureOutcomeUsed = false;
details.currentLinkReliabilityUsed = false;
details.contractVersion = ...
    'online-positive-net-addressable-payload-v99-policy-v1';
details.armId = protocol.outcomePolicyName;
details.protocolId = protocol.id;
details.retentionDebtFractionByFormation = reshape( ...
    metrics.networkRescueFractionByFormation, 1, []);
details.retentionDebtThresholdByFormation = reshape( ...
    metrics.networkUsefulLossFractionByFormation, 1, []);
details.retentionDebtSingleAvailableMask = reshape( ...
    metrics.singleActionAvailableMask, 1, []);
details.retentionDebtSingleSafetyMask = ...
    reshape(metrics.crossSupportedDownwardCrossingsByFormation, 1, []) == 0;
details.retentionDebtRequestedFormationIds = ...
    selection.selectedFormationIds;
details.retentionDebtSelectedFormationIds = ...
    selection.selectedFormationIds;
details.retentionDebtProjectionRemovalOrder = zeros(1, 0);
details.onlinePositiveNetMetrics = metrics;
details.onlinePositiveNetSelection = selection;
end
