function decision = ...
    selectFormationB4V52CounterfactualPulseDecision( ...
        context, dominantAdjacency, residualAdjacency, protocol)
% SELECTFORMATIONB4V52COUNTERFACTUALPULSEDECISION Compare serve and hold.

nodeCount = numel(context.localPosteriorBySensor);
groups = reshape(context.model.dynamicTopologyScenario. ...
    config.sensorGroupIds, 1, []);
dominantAdjacency = logical(dominantAdjacency);
residualAdjacency = logical(residualAdjacency);
if numel(groups) ~= nodeCount || ...
        ~isequal(size(dominantAdjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(residualAdjacency), [nodeCount, nodeCount]) || ...
        any(dominantAdjacency(:) & residualAdjacency(:)) || ...
        nnz(dominantAdjacency) ~= nodeCount || ...
        nnz(residualAdjacency) ~= nodeCount
    error('FormationB4V52Decision:InvalidRoute', ...
        'The current V46 dominant/residual layers are invalid.');
end

holdAdjacency = dominantAdjacency;
serveAdjacency = dominantAdjacency | residualAdjacency;
holdWeights = buildWeights( ...
    dominantAdjacency, false(size(residualAdjacency)), protocol);
serveWeights = buildWeights( ...
    dominantAdjacency, residualAdjacency, protocol);
enumerationOptions = struct('maximumIncomingCount', ...
    protocol.maximumIncomingCountForOutcomeEnumeration);
[holdDisagreement, holdDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, holdAdjacency, holdWeights, enumerationOptions);
[serveDisagreement, serveDetails] = ...
    computeExpectedLmbNetworkDisagreementForDirectedRouting( ...
        context, serveAdjacency, serveWeights, enumerationOptions);
retentionOptions = struct( ...
    'referenceSupportThreshold', protocol.referenceSupportThreshold, ...
    'decisionExistenceThreshold', ...
        protocol.decisionExistenceThreshold, ...
    'receiverTailFraction', ...
        protocol.retentionReceiverTailFraction, ...
    'receiverTailWeight', protocol.retentionReceiverTailWeight);
[retentionRisk, retentionDetails] = ...
    computeLmbReferenceExistenceRetentionRisk( ...
        holdDetails.receiverDistributions, ...
        serveDetails.receiverDistributions, groups, retentionOptions);

disagreementImprovementFraction = ...
    (holdDisagreement - serveDisagreement) / ...
    max(abs(holdDisagreement), eps);
holdCardinality = mean( ...
    retentionDetails.expectedReferenceCardinality);
serveCardinality = mean( ...
    retentionDetails.expectedCandidateCardinality);
cardinalityGainFraction = ...
    (serveCardinality - holdCardinality) / max(holdCardinality, 1);
minimumFormationCardinalityChange = min( ...
    retentionDetails.formationMeanCardinalityChange);
minimumSupportedLabelRetentionRatio = min( ...
    retentionDetails.minimumSupportedLabelRetentionRatio);
decisionThresholdCrossingCount = sum( ...
    retentionDetails.decisionThresholdCrossingCount);

retentionSafe = ...
    retentionRisk <= protocol.maximumRetentionRisk + 1e-12 && ...
    minimumFormationCardinalityChange >= ...
        protocol.minimumFormationMeanCardinalityChange - 1e-12 && ...
    minimumSupportedLabelRetentionRatio >= ...
        protocol.minimumSupportedLabelRetentionRatio - 1e-12 && ...
    decisionThresholdCrossingCount <= ...
        protocol.maximumDecisionThresholdCrossingCount;
disagreementUseful = disagreementImprovementFraction >= ...
    protocol.minimumDisagreementImprovementFraction - 1e-12;
cardinalityUseful = cardinalityGainFraction >= ...
    protocol.minimumCardinalityGainFraction - 1e-12 && ...
    disagreementImprovementFraction >= ...
        -protocol.maximumDisagreementRegressionForCardinality - 1e-12;
serve = retentionSafe && (disagreementUseful || cardinalityUseful);

decision = struct();
decision.contractVersion = ...
    'formation-b4-v52-counterfactual-pulse-decision-v1';
decision.serve = serve;
decision.holdDisagreement = holdDisagreement;
decision.serveDisagreement = serveDisagreement;
decision.disagreementImprovementFraction = ...
    disagreementImprovementFraction;
decision.holdExpectedCardinality = holdCardinality;
decision.serveExpectedCardinality = serveCardinality;
decision.cardinalityGainFraction = cardinalityGainFraction;
decision.retentionRisk = retentionRisk;
decision.minimumFormationCardinalityChange = ...
    minimumFormationCardinalityChange;
decision.minimumSupportedLabelRetentionRatio = ...
    minimumSupportedLabelRetentionRatio;
decision.decisionThresholdCrossingCount = ...
    decisionThresholdCrossingCount;
decision.retentionSafe = retentionSafe;
decision.disagreementUseful = disagreementUseful;
decision.cardinalityUseful = cardinalityUseful;
decision.truthUsed = false;
decision.futureOutcomeUsed = false;
end

function weights = buildWeights(dominant, residual, protocol)
nodeCount = size(dominant, 1);
weights = zeros(nodeCount);
weights(dominant) = protocol.dominantWeight;
weights(residual) = protocol.activeResidualWeight;
weights(1:nodeCount+1:end) = 1 - sum(weights, 2)';
end
