function [adjacency, details] = ...
    selectFormationBackboneBundleStaggeredRecoveryRuntimePolicy( ...
        context, options)
% SELECTFORMATIONBACKBONEBUNDLESTAGGEREDRECOVERYRUNTIMEPOLICY Full-window v38.

if nargin < 2 || isempty(options)
    options = struct();
end
timerId = tic;
control = buildFormationBackboneBundleStaggeredRecoveryControl( ...
    context, options);
if ~control.selectionUsesCurrentPosterior || ...
        ~control.selectionUsesCurrentLinkReliability || ...
        ~control.selectionUsesSelectedTopologyHistory || ...
        control.truthUsed || control.futureOutcomeUsed
    error('FormationBundleRecovery:InvalidRuntimeContract', ...
        'The full-window controller is not causally attested.');
end
adjacency = logical(control.selectedAdjacency);
weights = control.selectedFusionWeights;
nodeCount = numel(context.localPosteriorBySensor);
weightSupport = adjacency | logical(eye(nodeCount));
if any(adjacency(:) & ...
        ~logical(context.physicalAdjacency(:))) || ...
        nnz(adjacency) > control.referenceMessageCount || ...
        any(~isfinite(weights(:))) || ...
        any(weights(:) < -1e-12) || ...
        any(weights(:) > 1e-12 & ~weightSupport(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        ~control.selectedScore.safe || ...
        ~all(control.selectedRollingB3SensorPass) || ...
        ~all(control.selectedRollingB3FormationPass)
    error('FormationBundleRecovery:InvalidRuntimeAction', ...
        'The selected full-window action violates a hard invariant.');
end

details = control.selectedPolicyDetails;
details.mode = ...
    'formation-backbone-bundle-staggered-recovery-control';
details.contractVersion = ...
    'formation-backbone-bundle-staggered-recovery-runtime-policy-v1';
details.actionName = control.selectedActionName;
details.fusionWeightMatrix = weights;
details.objective = control.selectedScore.networkRisk;
details.selectionSeconds = toc(timerId);
details.taskRisk = control.selectedScore.networkRisk;
details.baselineTaskRisk = control.referenceScore.networkRisk;
details.taskAdvantage = (control.referenceScore.networkRisk - ...
    control.selectedScore.networkRisk) / max( ...
        control.referenceScore.networkRisk, eps);
details.validCandidateCount = ...
    1 + control.baseControl.safeSingleActionCount + ...
        control.safeCandidateCount;
details.validCandidateCountSemantics = ...
    'safe-route-evaluations-not-deduplicated';
details.routeEvaluationCount = control.evaluatedRouteCount;
details.referenceFallbackUsed = control.referenceFallbackUsed;
details.posteriorUsed = true;
details.currentPosteriorUsed = true;
details.currentLinkReliabilityUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.futureMeasurementUsed = false;
details.futureOutcomeUsed = false;
details.repairTriggered = false;
details.payloadEmergencyUsed = false;
details.topologyInfeasible = false;
details.sensorWindowMature = true;
details.formationWindowMature = true;
details.sensorWindowStrongConnected = ...
    all(control.selectedRollingB3SensorPass);
details.formationWindowStrongConnected = ...
    all(control.selectedRollingB3FormationPass);
details.oneStepTopologyReserveChecked = true;
details.oneStepTopologyReservePassed = ...
    details.sensorWindowStrongConnected && ...
    details.formationWindowStrongConnected;
details.oneStepJointProjectionUsed = ...
    numel(control.baseControl.requestedFormationIds) > 1;
details.recursiveSafetyClaimed = false;
details.consensusProjectionReferenceRisk = ...
    control.referenceScore.networkRisk;
details.consensusProjectionCandidateRisk = ...
    control.incumbentScore.networkRisk;
details.consensusProjectionSelectedRisk = ...
    control.selectedScore.networkRisk;
details.consensusProjectionFallbackCount = double( ...
    control.referenceFallbackUsed);
details.consensusProjectionEvaluatedCandidateCount = ...
    control.evaluatedRouteCount;
details.consensusProjectionFeasibleCandidateCount = ...
    1 + control.baseControl.safeSingleActionCount + ...
        control.safeCandidateCount;
details.consensusProjectionPrimaryFeasibleCandidateCount = ...
    control.eligibleCandidateCount;
details.consensusProjectionPayloadRelaxationUsed = false;
details.backboneMode = [ ...
    'v38-backbone-bundle-', control.selectedActionName];
details.protectionScoreByFormation = ...
    control.baseControl.formationProtectionScore;
details.protectionThresholdByFormation = ...
    control.baseControl.protectionThresholdByFormation;
details.protectionSingleAvailableMask = ...
    control.baseControl.singleActionAvailableMask;
details.protectionSingleSafetyMask = ...
    control.baseControl.singleActionSafetyMask;
details.protectionRequestedFormationIds = ...
    control.baseControl.requestedFormationIds;
details.protectionBaseSelectedFormationIds = ...
    control.incumbentFormationIds;
details.protectionSelectedFormationIds = ...
    control.selectedFormationIds;
details.protectionBaseProjectionRemovalOrder = ...
    control.baseControl.projectionRemovalOrder;
details.protectionReleasedFormationIds = ...
    control.releasedFormationIds;
% Compatibility aliases keep the existing diagnostics transport usable;
% all new reports must use the protection-score names above.
details.retentionDebtFractionByFormation = ...
    details.protectionScoreByFormation;
details.retentionDebtThresholdByFormation = ...
    details.protectionThresholdByFormation;
details.retentionDebtSingleAvailableMask = ...
    details.protectionSingleAvailableMask;
details.retentionDebtSingleSafetyMask = ...
    details.protectionSingleSafetyMask;
details.retentionDebtRequestedFormationIds = ...
    details.protectionRequestedFormationIds;
details.retentionDebtSelectedFormationIds = ...
    details.protectionSelectedFormationIds;
details.retentionDebtProjectionRemovalOrder = ...
    details.protectionBaseProjectionRemovalOrder;
details.reserveSchedule = summarizeSchedule( ...
    context.currentTime, control);
end

function value = summarizeSchedule(currentTime, control)
schedule = control.releaseSchedule;
value = struct();
value.contractVersion = ...
    'formation-backbone-bundle-runtime-schedule-v1';
value.currentTime = currentTime;
value.incumbentFormationIds = control.incumbentFormationIds;
value.suspensionAgeByFormation = ...
    control.suspensionAgeByFormation;
value.matureFormationIds = schedule.matureFormationIds;
value.releaseOrder = schedule.releaseOrder;
value.candidateRetainedFormationIds = ...
    schedule.candidateRetainedFormationIds;
value.candidateRetainedProtectionCoverage = ...
    schedule.candidateRetainedProtectionCoverage;
value.candidateSafetyMask = control.candidateSafetyMask;
value.candidateEligibilityMask = ...
    control.candidateEligibilityMask;
value.candidateDisagreementImprovementFraction = ...
    control.candidateDisagreementImprovementFraction;
value.selectedCandidateIndex = control.selectedCandidateIndex;
value.selectedFormationIds = control.selectedFormationIds;
value.releasedFormationIds = control.releasedFormationIds;
value.selectedProtectionCoverageFraction = ...
    control.selectedProtectionCoverageFraction;
value.selectedDisagreementImprovementFraction = ...
    control.selectedDisagreementImprovementFraction;
value.staggeredReleaseUsed = control.staggeredReleaseUsed;
value.truthUsed = false;
value.futureOutcomeUsed = false;
end
