function [selectedModes, details] = ...
    selectJointSourceTrustFormationModes( ...
        pairRiskByMode, groupIds, objectiveByFormationMode, ...
        payloadByFormationMode, options)
% SELECTJOINTSOURCETRUSTFORMATIONMODES Exact finite-mode safe projection.
%
% Every formation selects one mode.  pairRiskByMode(i,j,a,b) is the exact
% expected one-round disagreement between receiver i under mode a and
% receiver j under mode b.  The projector maximizes the supplied observable
% objective under a mean pair-risk limit and a payload limit.  It first
% applies the primary payload target and may relax only to the registered
% maximum cap.  The all-reference action must be feasible under that cap.

if nargin < 5 || isempty(options)
    options = struct();
end
groupIds = reshape(groupIds, 1, []);
nodeCount = numel(groupIds);
groups = unique(groupIds, 'stable');
formationCount = numel(groups);
modeCount = size(objectiveByFormationMode, 2);
referenceModeIndex = round(getField( ...
    options, 'referenceModeIndex', 1));
riskLimit = getField(options, 'riskLimit', NaN);
primaryPayloadLimit = getField( ...
    options, 'primaryPayloadLimitBytes', NaN);
maximumPayloadLimit = getField( ...
    options, 'maximumPayloadLimitBytes', primaryPayloadLimit);
maximumFormationCount = round(getField( ...
    options, 'maximumFormationCount', 8));
maximumEnumerationCount = round(getField( ...
    options, 'maximumEnumerationCount', 1e6));
modeTrustWeights = reshape(getField( ...
    options, 'modeTrustWeights', nan(1, modeCount)), 1, []);

if nodeCount < 2 || formationCount < 1 || ...
        formationCount > maximumFormationCount || modeCount < 2 || ...
        any(~isfinite(groupIds)) || any(groupIds ~= round(groupIds)) || ...
        any(groupIds < 1) || ...
        referenceModeIndex < 1 || referenceModeIndex > modeCount || ...
        ~isequal(size(objectiveByFormationMode), ...
            [formationCount, modeCount]) || ...
        ~isequal(size(payloadByFormationMode), ...
            [formationCount, modeCount]) || ...
        size(pairRiskByMode, 1) ~= nodeCount || ...
        size(pairRiskByMode, 2) ~= nodeCount || ...
        size(pairRiskByMode, 3) ~= modeCount || ...
        size(pairRiskByMode, 4) ~= modeCount || ...
        any(~isfinite(objectiveByFormationMode(:))) || ...
        any(~isfinite(payloadByFormationMode(:))) || ...
        any(payloadByFormationMode(:) < 0) || ...
        any(~isfinite(pairRiskByMode(:))) || ...
        any(pairRiskByMode(:) < 0) || ...
        ~isscalar(riskLimit) || ~isfinite(riskLimit) || riskLimit < 0 || ...
        ~isscalar(primaryPayloadLimit) || ...
        ~isfinite(primaryPayloadLimit) || primaryPayloadLimit < 0 || ...
        ~isscalar(maximumPayloadLimit) || ...
        ~isfinite(maximumPayloadLimit) || ...
        maximumPayloadLimit < primaryPayloadLimit || ...
        ~isscalar(maximumFormationCount) || ...
        ~isfinite(maximumFormationCount) || maximumFormationCount < 1 || ...
        ~isscalar(maximumEnumerationCount) || ...
        ~isfinite(maximumEnumerationCount) || maximumEnumerationCount < 1 || ...
        numel(modeTrustWeights) ~= modeCount || ...
        ~(all(isfinite(modeTrustWeights)) || all(isnan(modeTrustWeights)))
    error('Joint source-trust projection inputs are invalid.');
end
transposedPairRisk = permute(pairRiskByMode, [2, 1, 4, 3]);
symmetryError = max(abs( ...
    pairRiskByMode(:) - transposedPairRisk(:)));
if symmetryError > 1e-10
    error('Joint source-trust pair risks are not symmetric.');
end

candidateCount = modeCount^formationCount;
if ~isfinite(candidateCount) || candidateCount < 1 || ...
        candidateCount > maximumEnumerationCount
    error('Joint source-trust action space exceeds the exact-enumeration cap.');
end

[withinRisk, crossRisk, pairCount] = ...
    buildFormationPairContributions( ...
        pairRiskByMode, groupIds, groups, modeCount);
referenceModes = referenceModeIndex * ones(1, formationCount);
referenceRisk = aggregateModeRisk( ...
    referenceModes, withinRisk, crossRisk, pairCount);
referencePayload = actionSum( ...
    payloadByFormationMode, referenceModes);
referenceObjective = actionSum( ...
    objectiveByFormationMode, referenceModes);
tolerance = 1e-12;
if referenceRisk > riskLimit + tolerance || ...
        referencePayload > maximumPayloadLimit + 1e-9
    error(['The registered all-reference action is not feasible under ', ...
        'the joint source-trust safety cap.']);
end

primary = emptyBestAction(formationCount);
relaxed = emptyBestAction(formationCount);
payloadFeasibleCount = 0;
primaryPayloadFeasibleCount = 0;
feasibleCount = 0;
primaryFeasibleCount = 0;
for candidateIdx = 0:(candidateCount - 1)
    modes = decodeModes(candidateIdx, modeCount, formationCount);
    payload = actionSum(payloadByFormationMode, modes);
    if payload > maximumPayloadLimit + 1e-9
        continue;
    end
    payloadFeasibleCount = payloadFeasibleCount + 1;
    primaryPayloadFeasible = ...
        payload <= primaryPayloadLimit + 1e-9;
    if primaryPayloadFeasible
        primaryPayloadFeasibleCount = ...
            primaryPayloadFeasibleCount + 1;
    end
    risk = aggregateModeRisk( ...
        modes, withinRisk, crossRisk, pairCount);
    if risk > riskLimit + tolerance
        continue;
    end
    feasibleCount = feasibleCount + 1;
    objective = actionSum(objectiveByFormationMode, modes);
    if isBetterAction( ...
            objective, risk, payload, modes, relaxed, ...
            referenceModeIndex)
        relaxed = makeBestAction( ...
            modes, objective, risk, payload);
    end
    if primaryPayloadFeasible
        primaryFeasibleCount = primaryFeasibleCount + 1;
        if isBetterAction( ...
                objective, risk, payload, modes, primary, ...
                referenceModeIndex)
            primary = makeBestAction( ...
                modes, objective, risk, payload);
        end
    end
end

payloadRelaxationUsed = false;
if primary.found
    best = primary;
elseif relaxed.found
    best = relaxed;
    payloadRelaxationUsed = true;
else
    error('Joint source-trust projection found no safe action.');
end
selectedModes = best.modes;

details = struct( ...
    'contractVersion', 'joint-source-trust-finite-mode-projector-v1', ...
    'formationCount', formationCount, ...
    'modeCount', modeCount, ...
    'referenceModeIndex', referenceModeIndex, ...
    'modeTrustWeights', modeTrustWeights, ...
    'selectedModeByFormation', selectedModes, ...
    'selectedTrustWeightByFormation', ...
        modeTrustWeights(selectedModes), ...
    'selectedReferenceFormationMask', ...
        selectedModes == referenceModeIndex, ...
    'referenceRisk', referenceRisk, ...
    'referencePayloadBytes', referencePayload, ...
    'referenceObjective', referenceObjective, ...
    'riskLimit', riskLimit, ...
    'primaryPayloadLimitBytes', primaryPayloadLimit, ...
    'maximumPayloadLimitBytes', maximumPayloadLimit, ...
    'selectedRisk', best.risk, ...
    'selectedPayloadBytes', best.payload, ...
    'selectedObjective', best.objective, ...
    'payloadRelaxationUsed', payloadRelaxationUsed, ...
    'evaluatedCandidateCount', candidateCount, ...
    'payloadFeasibleCandidateCount', payloadFeasibleCount, ...
    'primaryPayloadFeasibleCandidateCount', ...
        primaryPayloadFeasibleCount, ...
    'feasibleCandidateCount', feasibleCount, ...
    'primaryFeasibleCandidateCount', primaryFeasibleCount, ...
    'constraintPassed', best.risk <= riskLimit + tolerance, ...
    'payloadLimitPassed', ...
        best.payload <= maximumPayloadLimit + 1e-9, ...
    'referenceActionFeasible', true, ...
    'exactFiniteModeProjection', true, ...
    'exactEnumeration', true, ...
    'meanPairContributionAggregationExact', true, ...
    'pairCount', pairCount, ...
    'recursiveSafetyClaimed', false, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end

function [withinRisk, crossRisk, pairCount] = ...
    buildFormationPairContributions( ...
        pairRiskByMode, groupIds, groups, modeCount)
formationCount = numel(groups);
withinRisk = zeros(formationCount, modeCount);
crossRisk = zeros( ...
    formationCount, formationCount, modeCount, modeCount);
for leftFormation = 1:formationCount
    leftMembers = reshape(find( ...
        groupIds == groups(leftFormation)), 1, []);
    for mode = 1:modeCount
        for leftCursor = 1:(numel(leftMembers) - 1)
            leftIdx = leftMembers(leftCursor);
            for rightCursor = (leftCursor + 1):numel(leftMembers)
                rightIdx = leftMembers(rightCursor);
                withinRisk(leftFormation, mode) = ...
                    withinRisk(leftFormation, mode) + ...
                        pairRiskByMode(leftIdx, rightIdx, mode, mode);
            end
        end
    end
    for rightFormation = (leftFormation + 1):formationCount
        rightMembers = reshape(find( ...
            groupIds == groups(rightFormation)), 1, []);
        for leftMode = 1:modeCount
            for rightMode = 1:modeCount
                block = pairRiskByMode( ...
                    leftMembers, rightMembers, leftMode, rightMode);
                crossRisk(leftFormation, rightFormation, ...
                    leftMode, rightMode) = sum(block(:));
            end
        end
    end
end
nodeCount = numel(groupIds);
pairCount = nodeCount * (nodeCount - 1) / 2;
end

function risk = aggregateModeRisk( ...
        modes, withinRisk, crossRisk, pairCount)
formationCount = numel(modes);
riskSum = 0;
for formationIdx = 1:formationCount
    riskSum = riskSum + ...
        withinRisk(formationIdx, modes(formationIdx));
    for rightFormation = (formationIdx + 1):formationCount
        riskSum = riskSum + crossRisk( ...
            formationIdx, rightFormation, ...
            modes(formationIdx), modes(rightFormation));
    end
end
risk = riskSum / pairCount;
end

function value = actionSum(matrix, modes)
formationIndices = 1:numel(modes);
indices = sub2ind(size(matrix), formationIndices, modes);
value = sum(matrix(indices));
end

function modes = decodeModes(index, modeCount, formationCount)
modes = ones(1, formationCount);
for formationIdx = 1:formationCount
    modes(formationIdx) = mod(index, modeCount) + 1;
    index = floor(index / modeCount);
end
end

function best = emptyBestAction(formationCount)
best = struct( ...
    'found', false, ...
    'modes', ones(1, formationCount), ...
    'objective', -inf, ...
    'risk', inf, ...
    'payload', inf);
end

function best = makeBestAction(modes, objective, risk, payload)
best = struct( ...
    'found', true, ...
    'modes', modes, ...
    'objective', objective, ...
    'risk', risk, ...
    'payload', payload);
end

function better = isBetterAction( ...
        objective, risk, payload, modes, best, referenceModeIndex)
if ~best.found
    better = true;
    return;
end
better = objective > best.objective + 1e-12 || ...
    (abs(objective - best.objective) <= 1e-12 && ...
     risk < best.risk - 1e-12) || ...
    (abs(objective - best.objective) <= 1e-12 && ...
     abs(risk - best.risk) <= 1e-12 && ...
     payload < best.payload - 1e-9) || ...
    (abs(objective - best.objective) <= 1e-12 && ...
     abs(risk - best.risk) <= 1e-12 && ...
     abs(payload - best.payload) <= 1e-9 && ...
     sum(modes == referenceModeIndex) < ...
        sum(best.modes == referenceModeIndex)) || ...
    (abs(objective - best.objective) <= 1e-12 && ...
     abs(risk - best.risk) <= 1e-12 && ...
     abs(payload - best.payload) <= 1e-9 && ...
     sum(modes == referenceModeIndex) == ...
        sum(best.modes == referenceModeIndex) && ...
     lexicographicallyLess(modes, best.modes));
end

function less = lexicographicallyLess(left, right)
cursor = find(left ~= right, 1, 'first');
less = ~isempty(cursor) && left(cursor) < right(cursor);
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
