function [adjacency, details] = ...
    selectTailSafeBackboneResidualSplicedCyclePolicy( ...
        context, options)
% SELECTTAILSAFEBACKBONERESIDUALSPLICEDCYCLEPOLICY Reference-safe oracle.
%
% Candidate cross-formation residual inputs are compared against the
% matched static residual input at the same receiver.  A candidate
% edge-weight pair is eligible only when its current expected task risk is
% no larger than that reference.  The spliced-cycle projection still
% enforces the exact message count and instantaneous sensor-level strong
% connectivity.  If no complete safe cycle exists, execution fails closed
% to the matched static residual route and records the infeasibility.

if nargin < 2 || isempty(options)
    options = struct();
end
dominantWeight = getField(options, ...
    'dominantWeight', 0.70);
localResidualWeight = getField(options, ...
    'localResidualWeight', 0.05);
crossResidualWeightGrid = reshape(getField(options, ...
    'crossResidualWeightGrid', ...
    [0.05, 0.10, 0.20, 0.25]), 1, []);
referenceAdvantageTolerance = getField(options, ...
    'referenceAdvantageTolerance', 1e-12);
referenceGuardMode = getField(options, ...
    'referenceGuardMode', 'all-receivers');
protectedReceiverCount = getField(options, ...
    'protectedReceiverCount', 1);

teacherOptions = struct( ...
    'dominantWeight', dominantWeight, ...
    'residualWeightGrid', crossResidualWeightGrid, ...
    'referenceMode', 'matched-static-residual', ...
    'referenceResidualWeight', localResidualWeight, ...
    'requireNonnegativeReferenceAdvantage', true, ...
    'referenceGuardMode', referenceGuardMode, ...
    'protectedReceiverCount', protectedReceiverCount, ...
    'referenceAdvantageTolerance', ...
        referenceAdvantageTolerance, ...
    'horizonSteps', getField(options, ...
        'horizonSteps', 0), ...
    'discountFactor', getField(options, ...
        'discountFactor', 0.9));
policyOptions = struct( ...
    'dominantWeight', dominantWeight, ...
    'residualWeight', localResidualWeight, ...
    'edgeScoreFcnReturnsDetails', true, ...
    'edgeScoreFcn', ...
        @(scoreContext, receiverIndices, senderIndices, ...
            residualBaselineSources) ...
            computeBackbonePreservingResidualTaskTeacherScores( ...
                scoreContext, receiverIndices, senderIndices, ...
                residualBaselineSources, teacherOptions), ...
    'posteriorUsed', true, ...
    'truthUsed', true, ...
    'currentLinkReliabilityUsed', true);

try
    [adjacency, details] = ...
        selectBackboneResidualSplicedCyclePolicy( ...
            context, 'external-scores', policyOptions);
    details.tailSafeFallbackUsed = false;
catch errorInfo
    if ~isResidualCycleInfeasible(errorInfo)
        rethrow(errorInfo);
    end
    [adjacency, details] = ...
        selectBackbonePreservingResidualControl( ...
            context, struct( ...
                'dominantWeight', dominantWeight, ...
                'residualWeight', localResidualWeight));
    details.topologyInfeasible = true;
    details.repairTriggered = true;
    details.payloadEmergencyUsed = false;
    details.posteriorUsed = true;
    details.truthUsed = true;
    details.currentLinkReliabilityUsed = true;
    details.tailSafeFallbackUsed = true;
    details.tailSafeFallbackIdentifier = ...
        getErrorField(errorInfo, 'identifier');
    details.tailSafeFallbackMessage = ...
        getErrorField(errorInfo, 'message');
end

details.mode = ...
    'backbone-residual-spliced-cycle-tail-safe-adaptive-current';
details.tailSafeReferenceMode = ...
    'matched-static-residual';
details.tailSafeReferenceResidualWeight = ...
    localResidualWeight;
details.tailSafeRequireNonnegativeReferenceAdvantage = true;
details.tailSafeReferenceGuardMode = ...
    referenceGuardMode;
details.tailSafeProtectedReceiverCount = ...
    protectedReceiverCount;
details.tailSafeReferenceAdvantageTolerance = ...
    referenceAdvantageTolerance;
details.tailSafePrivilegedDiagnosticOnly = true;
end

function value = isResidualCycleInfeasible(errorInfo)
identifier = getErrorField(errorInfo, 'identifier');
message = getErrorField(errorInfo, 'message');
value = strcmp(identifier, 'ResidualCycle:Infeasible') || ...
    ~isempty(strfind(message, ...
        'residual splice')); %#ok<STREMP>
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
if isempty(value)
    value = '';
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
