function [adjacency, details] = ...
    selectFormationBackboneBundleParetoRiskRuntimePolicy(context)
% SELECTFORMATIONBACKBONEBUNDLEPARETORISKRUNTIMEPOLICY Causal v39 policy.

timerId = tic;
policy = getFormationBackboneBundleParetoRiskPolicyConfig();
control = buildFormationBackboneBundleParetoRiskControl(context);
v38 = control.v38Control;
selected = control.selectedCandidate;
adjacency = logical(selected.adjacency);
weights = selected.fusionWeights;
selectedScore = selected.score;
referenceRisk = control.referenceRisk;

nodeCount = numel(context.localPosteriorBySensor);
weightSupport = adjacency | logical(eye(nodeCount));
if any(adjacency(:) & ...
        ~logical(context.physicalAdjacency(:))) || ...
        nnz(adjacency) > control.referenceMessageCount || ...
        any(~isfinite(weights(:))) || ...
        any(weights(:) < 0) || ...
        any(weights(:) > 0 & ~weightSupport(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        ~selectedScore.safe || ...
        ~all(selected.policyDetails.rollingB3SensorPass) || ...
        ~all(selected.policyDetails.rollingB3FormationPass) || ...
        selectedScore.networkRisk > referenceRisk
    error('FormationBundleParetoRisk:InvalidRuntimeAction', ...
        'The v39 selected action violates a hard invariant.');
end

details = selected.policyDetails;
details.mode = ...
    'formation-backbone-bundle-pareto-risk-control';
details.contractVersion = ...
    'formation-backbone-bundle-pareto-risk-runtime-policy-v1';
details.actionName = selected.actionName;
details.fusionWeightMatrix = weights;
details.objective = selected.messageSavingCount;
details.objectiveMode = ...
    'maximize-message-saving-subject-to-reference-risk';
details.selectionTieBreak = ...
    'minimum-risk-then-minimum-switch-count-then-stable-ordinal';
details.selectionSeconds = toc(timerId);
details.taskRisk = selectedScore.networkRisk;
details.baselineTaskRisk = referenceRisk;
details.taskAdvantage = relativeImprovement( ...
    referenceRisk, selectedScore.networkRisk);
details.taskRiskMetricId = ...
    'exact-one-round-expected-lmb-summary-disagreement-v1';
details.taskRiskScope = ...
    'current-step-centralized-surrogate-under-current-link-probabilities';
details.taskRiskIsTrackingOutcome = false;
details.trackingRiskNondegradationClaimed = false;
details.validCandidateCount = control.candidateCount;
details.validCandidateCountSemantics = ...
    'exactly-deduplicated-v38-derived-route-bank-including-reference';
details.routeEvaluationCount = v38.evaluatedRouteCount;
details.referenceSelected = control.referenceSelected;
details.referenceFallbackUsed = control.referenceFallbackUsed;
details.noSparseProposal = control.noSparseProposal;
details.selectionState = control.selectionState;
details.posteriorUsed = true;
details.currentPosteriorUsed = true;
details.currentLinkReliabilityUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.futureMeasurementUsed = false;
details.futureOutcomeUsed = false;
details.repairTriggered = false;
details.payloadEmergencyUsed = false;
details.topologyInfeasible = false;
details.sensorWindowMature = true;
details.formationWindowMature = true;
details.sensorWindowStrongConnected = ...
    all(selected.policyDetails.rollingB3SensorPass);
details.formationWindowStrongConnected = ...
    all(selected.policyDetails.rollingB3FormationPass);
details.oneStepTopologyReserveChecked = true;
details.oneStepTopologyReservePassed = ...
    details.sensorWindowStrongConnected && ...
    details.formationWindowStrongConnected;
details.oneStepJointProjectionUsed = ...
    numel(v38.baseControl.requestedFormationIds) > 1;
details.recursiveSafetyClaimed = false;
details.consensusProjectionReferenceRisk = referenceRisk;
details.consensusProjectionCandidateRisk = ...
    v38.selectedScore.networkRisk;
details.consensusProjectionSelectedRisk = selectedScore.networkRisk;
details.consensusProjectionFallbackCount = ...
    double(control.referenceFallbackUsed);
details.consensusProjectionEvaluatedCandidateCount = ...
    control.candidateCount;
details.consensusProjectionFeasibleCandidateCount = ...
    1 + control.referenceRiskFeasibleSparseCount;
details.consensusProjectionPrimaryFeasibleCandidateCount = ...
    control.referenceRiskFeasibleSparseCount;
details.consensusProjectionPayloadRelaxationUsed = false;
details.backboneMode = [ ...
    'v39-pareto-risk-', selected.actionName];
details.protectionScoreByFormation = ...
    v38.baseControl.formationProtectionScore;
details.protectionThresholdByFormation = ...
    v38.baseControl.protectionThresholdByFormation;
details.protectionSingleAvailableMask = ...
    v38.baseControl.singleActionAvailableMask;
details.protectionSingleSafetyMask = ...
    v38.baseControl.singleActionSafetyMask;
details.protectionRequestedFormationIds = ...
    v38.baseControl.requestedFormationIds;
details.protectionBaseSelectedFormationIds = ...
    v38.incumbentFormationIds;
details.protectionPreviousFormationIds = ...
    control.previousFormationIds;
details.protectionSelectedFormationIds = selected.formationIds;
details.protectionBaseProjectionRemovalOrder = ...
    v38.baseControl.projectionRemovalOrder;
details.protectionReleasedFormationIds = ...
    selected.releasedFormationIds;
details.protectionNewlySuspendedFormationIds = ...
    selected.newlySuspendedFormationIds;
details.retentionDebtFractionByFormation = ...
    details.protectionScoreByFormation;
details.retentionDebtThresholdByFormation = ...
    details.protectionThresholdByFormation;
details.retentionDebtSingleAvailableMask = ...
    details.protectionSingleAvailableMask;
details.retentionDebtSingleSafetyMask = ...
    details.protectionSingleSafetyMask;
details.retentionDebtRequestedFormationIds = ...
    details.protectionRequestedFormationIds;
details.retentionDebtSelectedFormationIds = ...
    details.protectionSelectedFormationIds;
details.retentionDebtProjectionRemovalOrder = ...
    details.protectionBaseProjectionRemovalOrder;
details.reserveSchedule = summarizeSchedule( ...
    context.currentTime, v38, selected, control.selectionState);
details.paretoRiskPolicyConfigSha256 = policy.canonicalSha256;
details.paretoCandidateBankCanonicalSha256 = ...
    control.candidateBankCanonicalSha256;
details.paretoCandidateCount = control.candidateCount;
details.paretoSparseProposalCount = control.sparseProposalCount;
details.paretoRiskFeasibleSparseCount = ...
    control.referenceRiskFeasibleSparseCount;
details.paretoRiskRejectedSparseCount = ...
    control.referenceRiskRejectedSparseCount;
details.paretoSelectedCandidateOrdinal = selected.ordinal;
details.paretoSelectedProposalSource = selected.source;
details.paretoSelectedProposalSources = selected.provenanceSources;
details.paretoSelectedProposalActionNames = ...
    selected.provenanceActionNames;
details.paretoSelectedMessageSavingCount = ...
    selected.messageSavingCount;
details.paretoSelectedSwitchCount = selected.switchCount;
details.paretoReferenceRiskConstraintPassed = ...
    selected.referenceRiskConstraintPassed;
details.paretoRiskGatePassed = ...
    selected.sparse && selected.referenceRiskConstraintPassed;
details.v38SelectedCandidateWasSparse = ...
    v38.selectedMessageCount < v38.referenceMessageCount;
details.v38SelectedCandidateActionName = v38.selectedActionName;
details.v38SelectedCandidateFormationIds = ...
    v38.selectedFormationIds;
details.v38SelectedCandidateRisk = v38.selectedScore.networkRisk;
details.v38SelectedCandidateAdvantage = relativeImprovement( ...
    referenceRisk, v38.selectedScore.networkRisk);
details.paretoReferenceRiskConstraint = ...
    'selected-risk-less-than-or-equal-reference-exactly';
details.paretoRiskRejected = control.referenceFallbackUsed;
end

function value = summarizeSchedule( ...
        currentTime, v38, selected, selectionState)
schedule = v38.releaseSchedule;
value = struct();
value.contractVersion = ...
    'formation-backbone-bundle-pareto-risk-runtime-schedule-v1';
value.currentTime = currentTime;
value.incumbentFormationIds = v38.incumbentFormationIds;
value.suspensionAgeByFormation = v38.suspensionAgeByFormation;
value.matureFormationIds = schedule.matureFormationIds;
value.releaseOrder = schedule.releaseOrder;
value.candidateRetainedFormationIds = ...
    schedule.candidateRetainedFormationIds;
value.candidateRetainedProtectionCoverage = ...
    schedule.candidateRetainedProtectionCoverage;
value.candidateSafetyMask = v38.candidateSafetyMask;
value.candidateEligibilityMask = v38.candidateEligibilityMask;
value.candidateDisagreementImprovementFraction = ...
    v38.candidateDisagreementImprovementFraction;
value.v38SelectedCandidateIndex = v38.selectedCandidateIndex;
value.v38SelectedFormationIds = v38.selectedFormationIds;
value.selectedFormationIds = selected.formationIds;
value.releasedFormationIds = selected.releasedFormationIds;
value.newlySuspendedFormationIds = ...
    selected.newlySuspendedFormationIds;
value.selectionState = selectionState;
value.paretoRiskGatePassed = ...
    selected.sparse && selected.referenceRiskConstraintPassed;
value.truthUsed = false;
value.futureOutcomeUsed = false;
end

function value = relativeImprovement(referenceRisk, candidateRisk)
value = (referenceRisk - candidateRisk) / max(referenceRisk, eps);
end
