function [adjacency, details] = ...
    selectBackboneResidualPolicySequence( ...
        context, activationMask, anchorTime, options)
% SELECTBACKBONERESIDUALPOLICYSEQUENCE Execute frozen static/current mask.
%
% A zero selects the matched static residual route. A one selects the
% privileged current-risk residual route at that live counterfactual
% state. The activation mask is selected offline and is nondeployable.

if nargin < 4 || isempty(options)
    options = struct();
end
activationMask = logical(reshape(activationMask, 1, []));
relativeTime = context.currentTime - anchorTime + 1;
if relativeTime < 1 || relativeTime > numel(activationMask)
    error('Residual policy sequence is outside its frozen horizon.');
end
dominantWeight = getField(options, ...
    'dominantWeight', 0.70);
residualWeight = getField(options, ...
    'residualWeight', 0.05);
payloadToleranceFraction = getField(options, ...
    'payloadToleranceFraction', 0.02);

if activationMask(relativeTime)
    teacherOptions = struct( ...
        'dominantWeight', dominantWeight, ...
        'residualWeight', residualWeight, ...
        'horizonSteps', 0, ...
        'discountFactor', 0.9);
    policyOptions = struct( ...
        'dominantWeight', dominantWeight, ...
        'residualWeight', residualWeight, ...
        'sourceWeight', residualWeight, ...
        'payloadToleranceFraction', ...
            payloadToleranceFraction, ...
        'edgeScoreFcnReturnsDetails', true, ...
        'edgeScoreFcn', ...
            @(scoreContext, receiverIndices, senderIndices, ...
                residualBaselineSources) ...
                computeBackbonePreservingResidualTaskTeacherScores( ...
                    scoreContext, receiverIndices, senderIndices, ...
                    residualBaselineSources, teacherOptions), ...
        'posteriorUsed', true, ...
        'truthUsed', true, ...
        'currentLinkReliabilityUsed', true, ...
        'teacherRequestedHorizonSteps', 0);
    try
        [adjacency, details] = ...
            selectBackbonePreservingResidualRoutingPolicy( ...
                context, 'external-scores', policyOptions);
        branch = 'privileged-current-risk';
    catch errorInfo
        if ~isRollingMatchingInfeasible(errorInfo)
            rethrow(errorInfo);
        end
        [adjacency, details] = ...
            selectBackbonePreservingResidualControl( ...
                context, struct( ...
                    'dominantWeight', dominantWeight, ...
                    'residualWeight', residualWeight));
        details.topologyInfeasible = true;
        details.repairTriggered = true;
        details.payloadEmergencyUsed = false;
        details.posteriorUsed = true;
        details.truthUsed = true;
        details.currentLinkReliabilityUsed = true;
        details.policySequenceInfeasibleIdentifier = ...
            getErrorField(errorInfo, 'identifier');
        details.policySequenceInfeasibleMessage = ...
            getErrorField(errorInfo, 'message');
        branch = ...
            'privileged-current-risk-infeasible-static-fallback';
    end
else
    [adjacency, details] = ...
        selectBackbonePreservingResidualControl( ...
            context, struct( ...
                'dominantWeight', dominantWeight, ...
                'residualWeight', residualWeight));
    branch = 'matched-static-residual';
end
details.policySequenceContractVersion = ...
    'backbone-residual-static-current-sequence-v1';
details.policySequenceMask = activationMask;
details.policySequenceAnchorTime = anchorTime;
details.policySequenceRelativeTime = relativeTime;
details.policySequenceBranch = branch;
details.policySequenceMaskSelectedOffline = true;
details.policySequenceFutureOutcomeUsedAtRuntime = false;
details.policySequenceDeployable = false;
end

function value = isRollingMatchingInfeasible(errorInfo)
identifier = getErrorField(errorInfo, 'identifier');
message = getErrorField(errorInfo, 'message');
value = strcmp(identifier, 'RollingMatching:Infeasible') || ...
    ~isempty(strfind(message, ...
        'No feasible joint rolling matching exists')); %#ok<STREMP>
end

function value = getErrorField(errorInfo, fieldName)
value = '';
try
    value = errorInfo.(fieldName);
catch
    value = '';
end
if isempty(value)
    value = '';
end
end

function value = getField(structure, fieldName, defaultValue)
if isstruct(structure) && isfield(structure, fieldName)
    value = structure.(fieldName);
else
    value = defaultValue;
end
end
