function [adjacency, details] = ...
    selectFormationStaggeredRecoveryRuntimePolicy( ...
        context, anchorTime, initialBank, actionSequenceIndices, options)
% SELECTFORMATIONSTAGGEREDRECOVERYRUNTIMEPOLICY Causal v35 controller.

if nargin < 5 || isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isempty(fieldnames(options))
    error('StaggeredRecovery:InvalidRuntimeOptions', ...
        'The frozen v35 runtime policy accepts no overrides.');
end
protocol = getFormationStaggeredRecoveryProbeProtocol();
validateRuntimeContract( ...
    context, anchorTime, initialBank, actionSequenceIndices, protocol);
relativeTime = context.currentTime - anchorTime + 1;
actionSequenceIndices = reshape(actionSequenceIndices, 1, []);

if actionSequenceIndices(1) == initialBank.referenceActionIndex
    [adjacency, details] = ...
        selectFormationIsolateReconnectRuntimePolicy( ...
            context, anchorTime, initialBank, ...
            actionSequenceIndices);
    details.mode = 'formation-staggered-recovery-reference-baseline';
    details.contractVersion = ...
        'formation-staggered-recovery-runtime-policy-v1';
    details.backboneMode = 'v35-reference-baseline';
    details.reserveSchedule = emptySchedule(context.currentTime);
    return;
end

control = buildFormationStaggeredRecoveryControl(context);
if ~control.selectionUsesCurrentPosterior || ...
        ~control.selectionUsesCurrentLinkReliability || ...
        ~control.selectionUsesSelectedTopologyHistory || ...
        control.truthUsed || control.futureOutcomeUsed
    error('StaggeredRecovery:InvalidRuntimeContract', ...
        'The staggered controller is not causally attested.');
end
if relativeTime == 1
    expectedFormationIds = reshape( ...
        initialBank.actionSuspendedFormationIds{ ...
            actionSequenceIndices(1)}, 1, []);
    if ~isequal(reshape(control.selectedFormationIds, 1, []), ...
            expectedFormationIds)
        error('StaggeredRecovery:InitialControlDrift', ...
            ['The live v35 controller no longer reproduces the ', ...
             'preflight-selected first action.']);
    end
end

adjacency = logical(control.selectedAdjacency);
weights = control.selectedFusionWeights;
validateRuntimeAction(context, adjacency, weights, control, protocol);
details = control.selectedPolicyDetails;
details.mode = 'formation-staggered-recovery-control';
details.contractVersion = ...
    'formation-staggered-recovery-runtime-policy-v1';
details.actionName = control.selectedActionName;
details.fusionWeightMatrix = weights;
details.runtimeFrozenGraphReplay = false;
details.isolationPhase = relativeTime == 1;
details.recoveryPhase = relativeTime > 1;
details.referenceFallbackUsed = control.referenceFallbackUsed;
details.posteriorUsed = true;
details.currentPosteriorUsed = true;
details.currentLinkReliabilityUsed = true;
details.truthUsed = false;
details.groundTruthUsed = false;
details.futureMeasurementUsed = false;
details.futureOutcomeUsed = false;
details.repairTriggered = false;
details.payloadEmergencyUsed = false;
details.topologyInfeasible = false;
details.sensorWindowMature = true;
details.formationWindowMature = true;
details.sensorWindowStrongConnected = ...
    all(control.selectedRollingB3SensorPass);
details.formationWindowStrongConnected = ...
    all(control.selectedRollingB3FormationPass);
details.oneStepTopologyReserveChecked = true;
details.oneStepTopologyReservePassed = ...
    details.sensorWindowStrongConnected && ...
    details.formationWindowStrongConnected;
details.oneStepJointProjectionUsed = true;
details.recursiveSafetyClaimed = false;
details.consensusProjectionReferenceRisk = ...
    control.referenceScore.networkRisk;
details.consensusProjectionCandidateRisk = ...
    control.incumbentScore.networkRisk;
details.consensusProjectionSelectedRisk = ...
    control.selectedScore.networkRisk;
details.consensusProjectionFallbackCount = double( ...
    control.referenceFallbackUsed);
details.consensusProjectionEvaluatedCandidateCount = ...
    control.evaluatedRouteCount;
details.consensusProjectionFeasibleCandidateCount = ...
    1 + control.baseControl.safeSingleActionCount + ...
        control.safeCandidateCount;
details.consensusProjectionPrimaryFeasibleCandidateCount = ...
    control.eligibleCandidateCount;
details.consensusProjectionPayloadRelaxationUsed = false;
details.backboneMode = ['v35-debt-coverage-', ...
    control.selectedActionName];
details.recoveryRetentionRisk = ...
    control.selectedScore.retentionRisk;
details.recoverySelectedActionIndex = NaN;
details.recoverySelectedActionName = control.selectedActionName;
details.recoveryRelativeTime = relativeTime;
details.retentionDebtFractionByFormation = ...
    control.baseControl.formationRetentionDebtFraction;
details.retentionDebtThresholdByFormation = ...
    control.baseControl.debtThresholdByFormation;
details.retentionDebtSingleAvailableMask = ...
    control.baseControl.singleActionAvailableMask;
details.retentionDebtSingleSafetyMask = ...
    control.baseControl.singleActionSafetyMask;
details.retentionDebtRequestedFormationIds = ...
    control.incumbentFormationIds;
details.retentionDebtSelectedFormationIds = ...
    control.selectedFormationIds;
details.retentionDebtProjectionRemovalOrder = ...
    control.releasedFormationIds;
details.reserveSchedule = summarizeSchedule( ...
    context.currentTime, control);
end

function validateRuntimeContract( ...
        context, anchorTime, initialBank, actionSequenceIndices, protocol)
requiredBankFields = { ...
    'contractVersion', 'protocolId', 'actionCount', ...
    'referenceActionIndex', 'actionSuspendedFormationIds'};
if ~isstruct(context) || ~isfield(context, 'currentTime') || ...
        ~isscalar(context.currentTime) || ...
        ~isfinite(context.currentTime) || ...
        context.currentTime ~= round(context.currentTime) || ...
        ~isscalar(anchorTime) || ~isfinite(anchorTime) || ...
        anchorTime ~= round(anchorTime) || ...
        ~isstruct(initialBank) || ...
        ~all(isfield(initialBank, requiredBankFields)) || ...
        ~strcmp(initialBank.contractVersion, ...
            'temporal-cross-edge-suspension-action-bank-v1') || ...
        ~strcmp(initialBank.protocolId, ...
            'formation-temporal-cross-edge-suspension-v29-v1')
    error('StaggeredRecovery:InvalidRuntimeContract', ...
        'Staggered-recovery timing or initial bank is invalid.');
end
actionSequenceIndices = reshape(actionSequenceIndices, 1, []);
if numel(actionSequenceIndices) ~= protocol.horizonSteps || ...
        any(~isfinite(actionSequenceIndices)) || ...
        any(actionSequenceIndices ~= round(actionSequenceIndices)) || ...
        any(actionSequenceIndices < 1) || ...
        any(actionSequenceIndices > initialBank.actionCount)
    error('StaggeredRecovery:InvalidRuntimeContract', ...
        'Staggered-recovery action sequence is invalid.');
end
end

function validateRuntimeAction( ...
        context, adjacency, weights, control, protocol)
nodeCount = numel(context.localPosteriorBySensor);
weightSupport = adjacency | logical(eye(nodeCount));
if ~isequal(size(adjacency), [nodeCount, nodeCount]) || ...
        ~isequal(size(weights), [nodeCount, nodeCount]) || ...
        any(adjacency(:) & ...
            ~logical(context.physicalAdjacency(:))) || ...
        nnz(adjacency) > control.referenceMessageCount || ...
        any(~isfinite(weights(:))) || ...
        any(weights(:) < -1e-12) || ...
        any(weights(:) > 1e-12 & ~weightSupport(:)) || ...
        any(abs(sum(weights, 2) - 1) > 1e-12) || ...
        ~control.selectedScore.safe || ...
        ~all(control.selectedRollingB3SensorPass) || ...
        ~all(control.selectedRollingB3FormationPass) || ...
        control.evaluatedRouteCount > ...
            protocol.maximumControlRouteEvaluations
    error('StaggeredRecovery:InvalidRuntimeAction', ...
        'The selected v35 runtime action violates a hard invariant.');
end
end

function value = summarizeSchedule(currentTime, control)
schedule = control.releaseSchedule;
value = struct();
value.contractVersion = ...
    'formation-staggered-recovery-runtime-schedule-v1';
value.currentTime = currentTime;
value.incumbentFormationIds = control.incumbentFormationIds;
value.suspensionAgeByFormation = ...
    control.suspensionAgeByFormation;
value.matureFormationIds = schedule.matureFormationIds;
value.releaseOrder = schedule.releaseOrder;
value.candidateRetainedFormationIds = ...
    schedule.candidateRetainedFormationIds;
value.candidateRetainedDebtCoverage = ...
    schedule.candidateRetainedDebtCoverage;
value.candidateSafetyMask = control.candidateSafetyMask;
value.candidateEligibilityMask = ...
    control.candidateEligibilityMask;
value.candidateDisagreementImprovementFraction = ...
    control.candidateDisagreementImprovementFraction;
value.selectedCandidateIndex = ...
    control.selectedCandidateIndex;
value.selectedFormationIds = control.selectedFormationIds;
value.releasedFormationIds = control.releasedFormationIds;
value.selectedDebtCoverageFraction = ...
    control.selectedDebtCoverageFraction;
value.selectedDisagreementImprovementFraction = ...
    control.selectedDisagreementImprovementFraction;
value.staggeredReleaseUsed = control.staggeredReleaseUsed;
value.truthUsed = false;
value.futureOutcomeUsed = false;
end

function value = emptySchedule(currentTime)
value = struct( ...
    'contractVersion', ...
        'formation-staggered-recovery-runtime-schedule-v1', ...
    'currentTime', currentTime, ...
    'incumbentFormationIds', zeros(1, 0), ...
    'suspensionAgeByFormation', zeros(1, 0), ...
    'matureFormationIds', zeros(1, 0), ...
    'releaseOrder', zeros(1, 0), ...
    'candidateRetainedFormationIds', {cell(1, 0)}, ...
    'candidateRetainedDebtCoverage', zeros(1, 0), ...
    'candidateSafetyMask', false(1, 0), ...
    'candidateEligibilityMask', false(1, 0), ...
    'candidateDisagreementImprovementFraction', zeros(1, 0), ...
    'selectedCandidateIndex', zeros(1, 0), ...
    'selectedFormationIds', zeros(1, 0), ...
    'releasedFormationIds', zeros(1, 0), ...
    'selectedDebtCoverageFraction', 1, ...
    'selectedDisagreementImprovementFraction', 0, ...
    'staggeredReleaseUsed', false, ...
    'truthUsed', false, ...
    'futureOutcomeUsed', false);
end
