function model = stripDynamicTopologyTargetTruthForSource(model)
% STRIPDYNAMICTOPOLOGYTARGETTRUTHFORSOURCE Remove future target truth.

if ~isstruct(model) || ~isscalar(model)
    error('FormationBundleSourcePermit:InvalidModel', ...
        'The source model must be a scalar structure.');
end
topLevelTruthFields = intersect(fieldnames(model), { ...
    'explicitTargetTrajectories', 'targetTrajectories', ...
    'groundTruth', 'groundTruthRfs', 'truth', ...
    'trackingTruth', 'trackingTruthRfs'}, 'stable');
if ~isempty(topLevelTruthFields)
    model = rmfield(model, topLevelTruthFields);
end
if isfield(model, 'dynamicTopologyScenario') && ...
        isstruct(model.dynamicTopologyScenario) && ...
        isscalar(model.dynamicTopologyScenario)
    nestedTruthFields = intersect( ...
        fieldnames(model.dynamicTopologyScenario), { ...
            'targetTrajectories', 'groundTruth', 'groundTruthRfs', ...
            'truth', 'trackingTruth', 'trackingTruthRfs'}, 'stable');
    if ~isempty(nestedTruthFields)
        model.dynamicTopologyScenario = rmfield( ...
            model.dynamicTopologyScenario, nestedTruthFields);
    end
end
end
