function metrics = summarizeCvarResidualGraphPolicyRows(rows, protocol)
% SUMMARIZECVARRESIDUALGRAPHPOLICYROWS Aggregate block-first, then seed.

if nargin < 2 || isempty(protocol)
    protocol = getCvarResidualGraphPolicyDatasetProtocol();
end
if isempty(rows) || any(~isfinite( ...
        [rows.nodeTailRecall])) || ...
        any(~isfinite([rows.nodeTailJaccard])) || ...
        any(~isfinite([rows.edgeTaskSpearman])) || ...
        any(~isfinite([rows.normalizedRegret]))
    error('CVaR graph evaluation rows are invalid.');
end
seeds = unique([rows.seed], 'stable');
seedMetrics = repmat(emptySeedMetrics(), ...
    1, numel(seeds));
for seedIdx = 1:numel(seeds)
    seed = seeds(seedIdx);
    seedRows = rows([rows.seed] == seed);
    metric = emptySeedMetrics();
    metric.seed = seed;
    metric.stateCount = numel(seedRows);
    metric.nodeTailRecall = mean( ...
        [seedRows.nodeTailRecall]);
    metric.nodeTailJaccard = mean( ...
        [seedRows.nodeTailJaccard]);
    metric.nodeTailExactFraction = mean( ...
        [seedRows.nodeTailExact]);
    metric.edgeTaskSpearman = mean( ...
        [seedRows.edgeTaskSpearman]);
    metric.medianNormalizedRegret = median( ...
        [seedRows.normalizedRegret]);
    metric.p90NormalizedRegret = empiricalQuantile( ...
        [seedRows.normalizedRegret], 0.90);
    metric.meanSelectedTaskAdvantage = mean( ...
        [seedRows.selectedTrueTaskAdvantage]);
    metric.nonnegativeSelectedTaskStateCount = nnz( ...
        [seedRows.nonnegativeSelectedTask]);
    metric.selectedTailSafeFraction = mean( ...
        [seedRows.selectedTailSafe]);
    metric.projectionFeasibleFraction = mean( ...
        [seedRows.projectionFeasible]);
    metric.staticFallbackCount = nnz( ...
        [seedRows.staticFallbackUsed]);
    seedMetrics(seedIdx) = metric;
end

falseSafeCount = sum( ...
    [rows.observedTailFalseSafeCount]);
predictedSafeCount = sum( ...
    [rows.observedTailPredictedSafeCount]);
trueSafeCount = sum( ...
    [rows.observedTailTrueSafeCount]);
trueSafeSelectedCount = sum( ...
    [rows.observedTailTrueSafeSelectedCount]);
metrics = struct();
metrics.family = rows(1).family;
metrics.stateCount = numel(rows);
metrics.seeds = seeds;
metrics.seedMetrics = seedMetrics;
metrics.nodeTailRecall = mean( ...
    [seedMetrics.nodeTailRecall]);
metrics.minimumSeedNodeTailRecall = min( ...
    [seedMetrics.nodeTailRecall]);
metrics.nodeTailJaccard = mean( ...
    [seedMetrics.nodeTailJaccard]);
metrics.minimumSeedNodeTailJaccard = min( ...
    [seedMetrics.nodeTailJaccard]);
metrics.nodeTailExactFraction = mean( ...
    [seedMetrics.nodeTailExactFraction]);
metrics.edgeTaskSpearman = mean( ...
    [seedMetrics.edgeTaskSpearman]);
metrics.minimumSeedEdgeTaskSpearman = min( ...
    [seedMetrics.edgeTaskSpearman]);
metrics.medianNormalizedRegret = median( ...
    [rows.normalizedRegret]);
metrics.p90NormalizedRegret = empiricalQuantile( ...
    [rows.normalizedRegret], 0.90);
metrics.observedTailFalseSafeFraction = ...
    falseSafeCount / max(predictedSafeCount, 1);
metrics.observedTailTrueSafeRecall = ...
    trueSafeSelectedCount / max(trueSafeCount, 1);
metrics.selectedSafeStateFraction = mean( ...
    [rows.selectedTailSafe]);
metrics.projectionFeasibleFraction = mean( ...
    [rows.projectionFeasible]);
metrics.staticFallbackCount = nnz( ...
    [rows.staticFallbackUsed]);
metrics.maximumAllowedFallbackCount = ...
    ceil(numel(rows) / 18);
metrics.topologyInvariantFraction = mean( ...
    [rows.expectedCrossEdgeCountPassed] & ...
    [rows.messageCountPassed] & ...
    [rows.dominantBackbonePreserved] & ...
    [rows.weightGridPassed]);
metrics.zeroRepairPassed = ...
    all(~[rows.repairTriggered]);
metrics.zeroEmergencyPassed = ...
    all(~[rows.payloadEmergencyUsed]);
metrics.nodeGatePassed = ...
    metrics.nodeTailRecall + 1e-12 >= ...
        protocol.minimumNodeTailRecall && ...
    metrics.minimumSeedNodeTailRecall + 1e-12 >= ...
        protocol.minimumPerSeedNodeTailRecall && ...
    metrics.nodeTailJaccard + 1e-12 >= ...
        protocol.minimumNodeTailJaccard && ...
    metrics.minimumSeedNodeTailJaccard + 1e-12 >= ...
        protocol.minimumPerSeedNodeTailJaccard;
metrics.edgeTaskGatePassed = ...
    metrics.edgeTaskSpearman + 1e-12 >= ...
        protocol.minimumEdgeTaskSpearman && ...
    metrics.minimumSeedEdgeTaskSpearman + 1e-12 >= ...
        protocol.minimumPerSeedEdgeTaskSpearman;
metrics.regretGatePassed = ...
    metrics.medianNormalizedRegret <= ...
        protocol.maximumMedianNormalizedRegret + 1e-12 && ...
    metrics.p90NormalizedRegret <= ...
        protocol.maximumP90NormalizedRegret + 1e-12;
metrics.safetyGatePassed = ...
    metrics.observedTailFalseSafeFraction <= ...
        protocol. ...
            maximumObservedTailFalseSafeFraction + 1e-12 && ...
    metrics.observedTailTrueSafeRecall + 1e-12 >= ...
        protocol.minimumObservedTailTrueSafeRecall && ...
    metrics.selectedSafeStateFraction + 1e-12 >= ...
        protocol.minimumSelectedSafeStateFraction;
metrics.projectionGatePassed = ...
    metrics.projectionFeasibleFraction + 1e-12 >= ...
        protocol.minimumProjectionFeasibleFraction && ...
    metrics.staticFallbackCount <= ...
        metrics.maximumAllowedFallbackCount && ...
    metrics.topologyInvariantFraction >= 1 - 1e-12 && ...
    metrics.zeroRepairPassed && ...
    metrics.zeroEmergencyPassed;
metrics.taskAdvantageGatePassed = all(arrayfun(@(seed) ...
    seed.meanSelectedTaskAdvantage > 0 && ...
    seed.nonnegativeSelectedTaskStateCount >= ...
        protocol.minimumNonnegativeTaskStatesPerSeed, ...
    seedMetrics));
metrics.allHardGatesPassed = ...
    metrics.nodeGatePassed && ...
    metrics.edgeTaskGatePassed && ...
    metrics.regretGatePassed && ...
    metrics.safetyGatePassed && ...
    metrics.projectionGatePassed && ...
    metrics.taskAdvantageGatePassed;
end

function value = empiricalQuantile(values, probability)
values = sort(reshape(values, 1, []));
position = 1 + (numel(values) - 1) * probability;
lowerIdx = floor(position);
upperIdx = ceil(position);
if lowerIdx == upperIdx
    value = values(lowerIdx);
else
    fraction = position - lowerIdx;
    value = (1 - fraction) * values(lowerIdx) + ...
        fraction * values(upperIdx);
end
end

function metric = emptySeedMetrics()
metric = struct( ...
    'seed', 0, 'stateCount', 0, ...
    'nodeTailRecall', NaN, ...
    'nodeTailJaccard', NaN, ...
    'nodeTailExactFraction', NaN, ...
    'edgeTaskSpearman', NaN, ...
    'medianNormalizedRegret', NaN, ...
    'p90NormalizedRegret', NaN, ...
    'meanSelectedTaskAdvantage', NaN, ...
    'nonnegativeSelectedTaskStateCount', 0, ...
    'selectedTailSafeFraction', NaN, ...
    'projectionFeasibleFraction', NaN, ...
    'staticFallbackCount', 0);
end
