function improvement = ...
    summarizeRepeatedMultiGatewayFullEpisodeImprovement( ...
        reference, candidate, protocol)
% SUMMARIZEREPEATEDMULTIGATEWAYFULLEPISODEIMPROVEMENT Frozen pair metrics.

improvement = struct();
improvement.fullHorizonMeanGainPercent = percentImprovement( ...
    reference.fullHorizonPositionEospa, ...
    candidate.fullHorizonPositionEospa);
improvement.focusWindowMeanGainPercent = percentImprovement( ...
    reference.focusWindowPositionEospa, ...
    candidate.focusWindowPositionEospa);
improvement.worstSensorGainPercent = percentImprovement( ...
    reference.worstSensorPositionEospa, ...
    candidate.worstSensorPositionEospa);
improvement.formationGainPercent = 100 * ( ...
    reference.perFormationPositionEospa - ...
    candidate.perFormationPositionEospa) ./ ...
    max(reference.perFormationPositionEospa, eps);
improvement.minimumFormationGainPercent = ...
    min(improvement.formationGainPercent);
improvement.fullConsensusGainPercent = percentImprovement( ...
    reference.meanInterFormationPositionOspa, ...
    candidate.meanInterFormationPositionOspa);
improvement.focusConsensusGainPercent = percentImprovement( ...
    reference.focusInterFormationPositionOspa, ...
    candidate.focusInterFormationPositionOspa);
improvement.cardinalityGainPercent = percentImprovement( ...
    reference.meanAbsoluteCardinalityError, ...
    candidate.meanAbsoluteCardinalityError);
improvement.attemptedByteSavingPercent = percentImprovement( ...
    reference.attemptedPayloadBytes, candidate.attemptedPayloadBytes);
improvement.networkMeanPositionEospaGainPercentByTime = ...
    elementwisePercentImprovement( ...
        reference.networkMeanPositionEospaByTime, ...
        candidate.networkMeanPositionEospaByTime);
improvement.networkMeanCardinalityGainPercentByTime = ...
    elementwisePercentImprovement( ...
        reference.networkMeanAbsoluteCardinalityErrorByTime, ...
        candidate.networkMeanAbsoluteCardinalityErrorByTime);
improvement.interFormationConsensusGainPercentByTime = ...
    elementwisePercentImprovement( ...
        reference.interFormationPositionOspaByTime, ...
        candidate.interFormationPositionOspaByTime);
improvement.phaseMeanGainPercent = summarizePhaseGain( ...
    reference, candidate, protocol);
improvement.strongGatePassed = ...
    improvement.fullHorizonMeanGainPercent >= ...
        protocol.minimumFullEpisodeMeanGainPercent - 1e-12 && ...
    improvement.focusWindowMeanGainPercent >= ...
        protocol.minimumFocusWindowMeanGainPercent - 1e-12 && ...
    improvement.worstSensorGainPercent >= ...
        protocol.minimumWorstSensorGainPercent - 1e-12 && ...
    improvement.minimumFormationGainPercent >= ...
        protocol.minimumFormationGainPercent - 1e-12 && ...
    improvement.focusConsensusGainPercent >= ...
        protocol.minimumConsensusGainPercent - 1e-12 && ...
    improvement.attemptedByteSavingPercent >= ...
        protocol.minimumAttemptedByteSavingPercent - 1e-12 && ...
    candidate.exactMessageParityPassed && ...
    candidate.physicalFeasibilityPassed && ...
    candidate.selectedRollingB3SensorPassed && ...
    candidate.selectedRollingB3FormationPassed;
end

function phaseGain = summarizePhaseGain(reference, candidate, protocol)
phaseNames = {'acquire', 'broadcast', 'reference'};
phaseGain = struct();
timeCount = numel(candidate.phaseByTime);
focusMask = false(1, timeCount);
focusMask(protocol.activationStartTime:min( ...
    protocol.activationEndTime, timeCount)) = true;
for phaseIdx = 1:numel(phaseNames)
    phaseName = phaseNames{phaseIdx};
    mask = focusMask & strcmp(candidate.phaseByTime, phaseName);
    phaseGain.(phaseName) = NaN;
    if any(mask)
        phaseGain.(phaseName) = percentImprovement( ...
            mean(reference.networkMeanPositionEospaByTime(mask)), ...
            mean(candidate.networkMeanPositionEospaByTime(mask)));
    end
end
end

function value = percentImprovement(reference, candidate)
if reference == 0
    value = 0;
    if candidate > 0
        value = -Inf;
    end
else
    value = 100 * (reference - candidate) / reference;
end
end

function values = elementwisePercentImprovement(reference, candidate)
values = zeros(size(reference));
zero = reference == 0;
values(~zero) = 100 * (reference(~zero) - candidate(~zero)) ./ ...
    reference(~zero);
values(zero & candidate > 0) = -Inf;
end
