function authorization = ...
        validateSpatiallySupportedLabelAugmentationV142Execution( ...
            model, context, request)
% VALIDATESPATIALLYSUPPORTEDLABELAUGMENTATIONV142EXECUTION Enforce V142.

protocol = getSpatiallySupportedLabelAugmentationV142Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'scheduleEnabled', 'lineageRelayEnabled', ...
    'intraFormationWorkingPayloadEnabled', ...
    'postFusionLabelReadoutEnabled', ...
    'predictiveEvidenceReadoutOnlyEnabled', ...
    'spatiallySupportedLabelAugmentationEnabled', ...
    'workingStateMutationAllowed', 'onlineReselectionEnabled', ...
    'developmentEvidenceOnly'};
enabled = false;
if isstruct(context) && isscalar(context) && isfield(context, 'phase')
    enabled = strcmp(context.phase, 'candidate');
end
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(requiredContext(:))) && ...
    strcmp(context.capability, ...
        'spatially-supported-label-augmentation-v142-development') && ...
    strcmp(context.action, ...
        ['filter-spatially-supported-label-augmentation-', ...
         'v142-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    ismember(context.phase, {'reference', 'candidate'}) && ...
    islogical(context.scheduleEnabled) && ...
    islogical(context.lineageRelayEnabled) && ...
    islogical(context.intraFormationWorkingPayloadEnabled) && ...
    islogical(context.postFusionLabelReadoutEnabled) && ...
    islogical(context.predictiveEvidenceReadoutOnlyEnabled) && ...
    islogical(context.spatiallySupportedLabelAugmentationEnabled) && ...
    context.scheduleEnabled == enabled && ...
    context.lineageRelayEnabled == enabled && ...
    context.intraFormationWorkingPayloadEnabled == enabled && ...
    context.postFusionLabelReadoutEnabled == enabled && ...
    context.predictiveEvidenceReadoutOnlyEnabled == enabled && ...
    context.spatiallySupportedLabelAugmentationEnabled == enabled && ...
    isequal(context.workingStateMutationAllowed, false) && ...
    isequal(context.onlineReselectionEnabled, false) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('SpatialLabelAugmentationV142:InvalidExecutionContext', ...
        'The V142 execution context is malformed.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isstruct(request) || ~isscalar(request) || ...
        ~isequal(sort(fieldnames(request)), sort(requiredRequest(:))) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isscalar(request.triggerConfig)
    error('SpatialLabelAugmentationV142:InvalidRuntimeRequest', ...
        'The V142 runtime request is malformed.');
end
config = request.triggerConfig;
flag = 'lineageRelaySpatiallySupportedLabelAugmentationEnabled';
if ~isfield(config, flag) || logical(config.(flag)) ~= enabled || ...
        ~isfield(config, 'topologyPolicyName') || ...
        ~strcmp(config.topologyPolicyName, protocol.outcomePolicyName)
    error('SpatialLabelAugmentationV142:InvalidRuntimeRequest', ...
        'The V142 request changed the supported-label composition.');
end

baseContext = buildCombinedOutputSafetyV139ExecutionContext( ...
    context.presetName, context.seed, context.phase, ...
    context.currentTime, context.referenceCarrierMode, context.actionSpec);
baseRequest = request;
baseProtocol = getCombinedOutputSafetyV139Protocol();
baseRequest.triggerConfig.topologyPolicyName = ...
    baseProtocol.outcomePolicyName;
baseRequest.triggerConfig = rmfield(baseRequest.triggerConfig, flag);
try
    authorization = validateCombinedOutputSafetyV139Execution( ...
        model, baseContext, baseRequest);
catch errorInfo
    error('SpatialLabelAugmentationV142:InvalidRuntimeRequest', ...
        'The V142 request failed the inherited V139 boundary: %s', ...
        errorInfo.message);
end
authorization.mode = ...
    'spatially-supported-label-augmentation-v142-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
end
