function action = validateSetTrustSequenceActionV134( ...
        action, phase, caseInfo, protocol)
% VALIDATESETTRUSTSEQUENCEACTIONV134 Normalize one registered sequence.

required = { ...
    'name', 'scheduleKind', 'formationSet', ...
    'formationIdsByTime', 'trustFactorsByTime', ...
    'zeroTrustPageCount', 'fullPayloadPageCount', ...
    'returnsToFullTrust'};
if ~isstruct(action) || ~isscalar(action) || ...
        ~all(isfield(action, required)) || ...
        ~ischar(action.name) || isempty(action.name) || ...
        ~ischar(action.scheduleKind) || ...
        ~isscalar(caseInfo.horizonSteps) || ...
        ~isscalar(caseInfo.expectedFormationCount)
    error('V134SetTrustAction:InvalidAction', ...
        'The set--trust action is malformed.');
end
phase = lower(strrep(char(phase), '_', '-'));
formationSet = reshape(action.formationSet, 1, []);
formationsByTime = action.formationIdsByTime;
trustByTime = action.trustFactorsByTime;
horizonSteps = caseInfo.horizonSteps;
if ~isnumeric(formationSet) || any(~isfinite(formationSet)) || ...
        any(formationSet < 1) || ...
        any(formationSet > caseInfo.expectedFormationCount) || ...
        any(formationSet ~= round(formationSet)) || ...
        numel(unique(formationSet)) ~= numel(formationSet) || ...
        ~iscell(formationsByTime) || ~iscell(trustByTime) || ...
        numel(formationsByTime) ~= horizonSteps || ...
        numel(trustByTime) ~= horizonSteps
    error('V134SetTrustAction:InvalidAction', ...
        'The formation set or sequence length is invalid.');
end

isReferencePhase = ismember(phase, { ...
    'reference-prefix', 'reference-continuation'});
if isReferencePhase
    if ~strcmp(action.scheduleKind, 'reference') || ...
            ~isempty(formationSet)
        error('V134SetTrustAction:InvalidReference', ...
            'Reference phases require the empty full-trust action.');
    end
elseif ~strcmp(phase, 'candidate-continuation') || ...
        isempty(formationSet) || ...
        ~ismember(action.scheduleKind, { ...
            'persistent-zero', 'diameter-taper'})
    error('V134SetTrustAction:InvalidCandidate', ...
        'Candidate phases require one registered nonempty sequence.');
end

zeroCount = 0;
fullPayloadCount = 0;
pageFactors = zeros(1, horizonSteps);
for pageIdx = 1:horizonSteps
    formations = reshape(formationsByTime{pageIdx}, 1, []);
    factors = reshape(trustByTime{pageIdx}, 1, []);
    if ~isequal(formations, formationSet) || ...
            ~isnumeric(factors) || numel(factors) ~= numel(formationSet) || ...
            any(~isfinite(factors)) || any(factors < 0) || ...
            any(factors > 1) || ...
            (~isempty(factors) && ...
             max(abs(factors - factors(1))) > 1e-12)
        error('V134SetTrustAction:InvalidPage', ...
            'Every page must apply one common trust to the frozen set.');
    end
    if isempty(factors)
        pageFactors(pageIdx) = 1;
    else
        pageFactors(pageIdx) = factors(1);
    end
    zeroCount = zeroCount + nnz(factors <= 1e-12);
    fullPayloadCount = fullPayloadCount + nnz(factors > 1e-12);
end

if strcmp(action.scheduleKind, 'persistent-zero')
    expected = zeros(1, horizonSteps);
elseif strcmp(action.scheduleKind, 'diameter-taper')
    expected = [ ...
        zeros(1, caseInfo.formationCycleDiameter), ...
        reshape(protocol.returnRamp, 1, [])];
else
    expected = ones(1, horizonSteps);
end
if max(abs(pageFactors - expected)) > 1e-12 || ...
        action.zeroTrustPageCount ~= zeroCount || ...
        action.fullPayloadPageCount ~= fullPayloadCount || ...
        logical(action.returnsToFullTrust) ~= ...
            (isempty(formationSet) || pageFactors(end) >= 1 - 1e-12)
    error('V134SetTrustAction:ScheduleDrift', ...
        'The set--trust action differs from its registered sequence.');
end

action.formationSet = formationSet;
action.formationIdsByTime = reshape(formationsByTime, 1, []);
action.trustFactorsByTime = reshape(trustByTime, 1, []);
action.returnsToFullTrust = logical(action.returnsToFullTrust);
end
