function authorization = ...
    validateCounterfactualRegretGateV133Execution( ...
        model, context, request)
% VALIDATECOUNTERFACTUALREGRETGATEV133EXECUTION Enforce teacher boundary.

protocol = getCounterfactualRegretGateV133Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'evidenceSplit', 'phase', 'presetName', 'seed', 'currentTime', ...
    'horizonSteps', 'measurementTimeCount', 'policyName', ...
    'actionName', 'referenceCarrierMode', 'protectedFormationId', ...
    'scheduleEnabled', 'onlineReselectionEnabled', ...
    'developmentEvidenceOnly'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~isequal(sort(fieldnames(context)), sort(expectedFields(:))) || ...
        ~strcmp(context.capability, ...
            'counterfactual-regret-gate-v133-teacher-generation') || ...
        ~strcmp(context.action, ...
            ['filter-counterfactual-regret-gate-v133-', ...
             'teacher-generation']) || ...
        ~strcmp(context.protocolId, protocol.id) || ...
        ~strcmp(context.policyName, protocol.outcomePolicyName) || ...
        ~ismember(context.evidenceSplit, ...
            {'development', 'calibration'}) || ...
        ~ismember(context.phase, { ...
            'baseline-selection', 'reference-prefix', ...
            'reference-continuation', ...
            'candidate-continuation'}) || ...
        ~ismember(context.referenceCarrierMode, ...
            protocol.referenceCarrierModes) || ...
        ~islogical(context.scheduleEnabled) || ...
        ~isscalar(context.scheduleEnabled) || ...
        ~isequal(context.onlineReselectionEnabled, false) || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('CounterfactualRegretV133:InvalidExecutionContext', ...
        'The V133 execution context is malformed.');
end
caseInfo = resolveCase(protocol, context.presetName);
if strcmp(context.evidenceSplit, 'development')
    allowedSeeds = protocol.developmentSeeds;
else
    allowedSeeds = protocol.calibrationSeeds;
end
validModel = ismember(context.seed, allowedSeeds) && ...
    isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    model.numberOfSensors == caseInfo.expectedNodeCount && ...
    isfield(model, 'dynamicTopologyScenario') && ...
    isstruct(model.dynamicTopologyScenario) && ...
    isscalar(model.dynamicTopologyScenario) && ...
    isfield(model.dynamicTopologyScenario, 'presetName') && ...
    strcmp(model.dynamicTopologyScenario.presetName, ...
        context.presetName) && ...
    isfield(model.dynamicTopologyScenario, 'seed') && ...
    model.dynamicTopologyScenario.seed == context.seed && ...
    isfield(model.dynamicTopologyScenario, 'config') && ...
    model.dynamicTopologyScenario.config.formationCount == ...
        caseInfo.expectedFormationCount && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(model.dynamicTopologyScenario, 'targetTrajectories') && ...
    ~isfield(model.dynamicTopologyScenario, 'target');
if ~validModel
    error('CounterfactualRegretV133:InvalidRuntimeModel', ...
        'The V133 runtime model is outside its registered split.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == ...
        caseInfo.expectedNodeCount && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'v133ReferenceCarrierMode') && ...
    strcmp(config.v133ReferenceCarrierMode, ...
        context.referenceCarrierMode) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    logical(config.topologyPolicyObservableContextOnly) && ...
    isfield(config, 'topologyPolicySensorObservationEnabled') && ...
    logical(config.topologyPolicySensorObservationEnabled) && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    logical(config.receiverSafeLabelFusionEnabled) == ...
        context.scheduleEnabled;
if strcmp(context.phase, 'baseline-selection')
    scenarioConfig = buildDynamicTopologyScenarioConfig( ...
        context.presetName);
    validRequest = validRequest && ...
        context.measurementTimeCount == ...
            scenarioConfig.simulationLength && ...
        context.currentTime == scenarioConfig.simulationLength && ...
        context.horizonSteps == 1 && ...
        context.protectedFormationId == 0;
elseif strcmp(context.phase, 'reference-prefix')
    validRequest = validRequest && ...
        context.measurementTimeCount == context.currentTime && ...
        context.horizonSteps == 1 && ...
        context.protectedFormationId == 0;
else
    validRequest = validRequest && ...
        context.horizonSteps == caseInfo.horizonSteps && ...
        context.measurementTimeCount == ...
            context.currentTime + context.horizonSteps - 1;
end
if validRequest && context.scheduleEnabled
    validRequest = ...
        strcmp(context.phase, 'candidate-continuation') && ...
        context.protectedFormationId >= 1 && ...
        context.protectedFormationId <= ...
            caseInfo.expectedFormationCount && ...
        isfield(config, 'receiverSafeLabelFusionMode') && ...
        strcmpi(config.receiverSafeLabelFusionMode, ...
            'formation-supported-label-plan') && ...
        isfield(config, 'receiverSafeExternalActiveTimes') && ...
        isequal(reshape(config.receiverSafeExternalActiveTimes, 1, []), ...
            context.currentTime) && ...
        isfield(config, 'receiverSafeFormationConditionedTimes') && ...
        isequal(reshape( ...
            config.receiverSafeFormationConditionedTimes, 1, []), ...
            context.currentTime) && ...
        isfield(config, ...
            'receiverSafeFormationConditionedSchedule') && ...
        isequal(config.receiverSafeFormationConditionedSchedule, ...
            {context.protectedFormationId}) && ...
        isfield(config, ...
            'receiverSafeFormationConditionedPayloadMode') && ...
        strcmpi(config.receiverSafeFormationConditionedPayloadMode, ...
            protocol.actionContract.payloadMode) && ...
        isfield(config, ...
            'receiverSafeFormationConditionedOnlinePolicyEnabled') && ...
        ~logical(config. ...
            receiverSafeFormationConditionedOnlinePolicyEnabled);
elseif validRequest
    validRequest = context.protectedFormationId == 0;
end
if ~validRequest
    error('CounterfactualRegretV133:InvalidRuntimeRequest', ...
        'The V133 runtime request changed its frozen causal boundary.');
end

authorization = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-execution-authorization-v1', ...
    'mode', 'counterfactual-regret-gate-v133-teacher-generation', ...
    'permitId', '', ...
    'permitCanonicalSha256', '', ...
    'capability', context.capability, ...
    'action', context.action, ...
    'protocolId', protocol.id, ...
    'protocolCanonicalSha256', '', ...
    'caseId', '', ...
    'caseCanonicalSha256', '', ...
    'presetName', context.presetName, ...
    'seed', context.seed, ...
    'sourceWindow', [1, context.measurementTimeCount], ...
    'armId', context.actionName, ...
    'armOrdinal', NaN, ...
    'methodSourceCommit', '', ...
    'methodPolicyConfigSha256', '', ...
    'sourceTriggerFingerprintSha256', '', ...
    'executableSourceCommit', '', ...
    'executableSourceManifestSha256', '', ...
    'executionHeadCommit', '', ...
    'sourceInputFingerprintSha256', '', ...
    'stateEstimateOutputAuthorized', true, ...
    'trackingOutcomeScoringAuthorized', ...
        ~strcmp(context.phase, 'reference-prefix'), ...
    'groundTruthAccessAuthorized', false, ...
    'futureOutcomeAccessAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true);
end

function caseInfo = resolveCase(protocol, presetName)
caseInfo = struct([]);
for candidate = protocol.scaleCases
    if strcmp(candidate.presetName, presetName)
        caseInfo = candidate;
        return;
    end
end
error('CounterfactualRegretV133:InvalidExecutionContext', ...
    'The preset is outside the V133 scale contract.');
end
