function authorization = ...
        validateEventWindowResidualReinforcementV258Execution( ...
            model, context, request)
% VALIDATEEVENTWINDOWRESIDUALREINFORCEMENTV258EXECUTION Mechanism gate.

protocol = getEventWindowResidualReinforcementV258Protocol();
source = getCausalMinimumFormationBackboneV242Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'policyName', 'mechanismEvidenceOnly', ...
    'developmentEvidenceOnly'};
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'event-window-residual-reinforcement-v258-mechanism') && ...
    strcmp(context.action, ...
        'filter-event-window-residual-reinforcement-v258-mechanism') && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    strcmp(context.armId, protocol.armId) && ...
    strcmp(context.policyName, protocol.policyName) && ...
    isequal(context.mechanismEvidenceOnly, true) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('EventWindowResidualV258:InvalidExecutionContext', ...
        'The V258 execution context is malformed.');
end

scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && isstruct(scenario.config) && ...
    isfield(scenario.config, 'numberOfSensors') && ...
    model.numberOfSensors == scenario.config.numberOfSensors && ...
    isfield(scenario.config, 'simulationLength') && ...
    context.measurementTimeCount == scenario.config.simulationLength && ...
    isfield(scenario.config, 'sceneStyle') && ...
    strcmp(scenario.config.sceneStyle, ...
        'temporal-coupled-formation-braid') && ...
    isfield(scenario.config, 'sceneCalibrationStatus') && ...
    strcmp(scenario.config.sceneCalibrationStatus, 'development-only') && ...
    isfield(scenario.config, 'trackingOutcomeAuthorized') && ...
    isequal(scenario.config.trackingOutcomeAuthorized, false) && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('EventWindowResidualV258:InvalidRuntimeModel', ...
        'The V258 model is mismatched or contains target truth.');
end

config = request.triggerConfig;
formationCount = numel(unique(scenario.config.sensorGroupIds));
minimumMessages = model.numberOfSensors + 2 * (formationCount - 1);
expectedMessageBudget = ...
    minimumMessages + protocol.maximumTotalResiduals;
requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyPolicyPhysicalIdentityEnabled') && ...
    isequal(config.topologyPolicyPhysicalIdentityEnabled, true) && ...
    isfield(config, 'topologyDirectedEnabled') && ...
    isequal(config.topologyDirectedEnabled, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == expectedMessageBudget && ...
    isfield(config, 'missingLabelFusionMode') && ...
    strcmp(config.missingLabelFusionMode, source.receiverMode) && ...
    isfield(config, 'eventPolicy') && ...
    strcmp(config.eventPolicy, 'alwaysHeavy') && ...
    isfield(config, 'mixtureAwareHeavyFusionEnabled') && ...
    logical(config.mixtureAwareHeavyFusionEnabled) && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    ~logical(config.receiverSafeLabelFusionEnabled);
if ~validRequest
    error('EventWindowResidualV258:InvalidRuntimeRequest', ...
        'The V258 runtime request changed its matched mechanism boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'event-window-residual-reinforcement-v258-mechanism';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = context.armId;
authorization.armOrdinal = 1;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
