function authorization = validateBraidedHandoverH3V84Execution( ...
        model, context, request)
% VALIDATEBRAIDEDHANDOVERH3V84EXECUTION Primary paired outcome permit.

expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', ...
    'measurementTimeCount', 'policyName', 'actionName', ...
    'routeEnabled', 'developmentEvidenceOnly'};
protocol = getBraidedHandoverH3V84Protocol();
validContext = isequal(sort(fieldnames(context)), ...
        sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'braided-handover-primary-h3-development') && ...
    strcmp(context.action, ...
        'filter-braided-handover-primary-h3-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.phase, 'opened-return') && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    islogical(context.routeEnabled) && ...
    isscalar(context.routeEnabled) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('BraidedHandoverH3V84:InvalidExecutionContext', ...
        'The V84 H=3 execution context is malformed.');
end

caseInfo = [];
for candidate = protocol.cases
    if strcmp(context.presetName, candidate.presetName) && ...
            context.seed == candidate.seed && ...
            context.currentTime == candidate.currentTime
        caseInfo = candidate;
        break;
    end
end
scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = ~isempty(caseInfo) && ...
    isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    model.numberOfSensors == caseInfo.expectedNodeCount && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && ...
    scenario.config.formationCount == caseInfo.expectedFormationCount && ...
    isfield(scenario.config, 'sceneStyle') && ...
    strcmp(scenario.config.sceneStyle, 'braided-handover') && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('BraidedHandoverH3V84:InvalidRuntimeModel', ...
        'The V84 H=3 model is not a frozen primary case.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    context.measurementTimeCount == ...
        context.currentTime + protocol.horizonSteps - 1 && ...
    numel(request.sensorTrajectoryTimeCounts) == ...
        caseInfo.expectedNodeCount && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2;
if ~validRequest
    error('BraidedHandoverH3V84:InvalidRuntimeRequest', ...
        'The V84 H=3 runtime request changed its frozen boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = 'braided-handover-primary-h3-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = context.actionName;
authorization.armOrdinal = 1 + double(context.routeEnabled);
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
