function authorization = ...
    validateFormationBackboneBundleM24SourceExecution( ...
        model, executionContext, runtimeRequest)
% VALIDATEFORMATIONBACKBONEBUNDLEM24SOURCEEXECUTION Fail-closed source gate.

assertExactFields(executionContext, { ...
    'contractVersion', 'permitId', 'permitCanonicalSha256', ...
    'capability', 'action'}, ...
    'FormationBundleSourcePermit:ExecutionContextDrift');
if ~strcmp(executionContext.contractVersion, ...
            'dynamic-topology-case-execution-context-v1') || ...
        ~strcmp(executionContext.capability, ...
            'source-posterior-only') || ...
        ~strcmp(executionContext.action, ...
            'filter-source-posterior')
    error('FormationBundleSourcePermit:ExecutionContextDrift', ...
        'The source execution context requests an unsupported scope.');
end
permit = loadFormationBackboneBundleM24SourceCasePermit( ...
    executionContext.permitId);
expectedContext = struct( ...
    'contractVersion', ...
        'dynamic-topology-case-execution-context-v1', ...
    'permitId', permit.id, ...
    'permitCanonicalSha256', permit.permitCanonicalSha256, ...
    'capability', permit.capability, ...
    'action', permit.filterAction);
if ~isequaln(executionContext, expectedContext)
    error('FormationBundleSourcePermit:ExecutionContextDrift', ...
        'The caller context does not equal the registered permit handle.');
end
permitPayload = rmfield(permit, 'permitCanonicalSha256');
if ~strcmp(computeCanonicalValueSha256(permitPayload), ...
            permit.permitCanonicalSha256) || ...
        permit.candidateContinuationAuthorized || ...
        permit.pairedTrackingAuthorized || ...
        permit.trackingOutcomeScoringAuthorized || ...
        permit.groundTruthAccessAuthorized || ...
        permit.futureOutcomeAccessAuthorized || ...
        permit.validationClaimAllowed
    error('FormationBundleSourcePermit:PermitScopeDrift', ...
        'The registered source permit changed or expanded its scope.');
end
if ~permit.executableSourceFrozen || ...
        isempty(permit.executableSourceCommit) || ...
        isempty(permit.executableSourceManifestSha256) || ...
        ~permit.sourceInputFingerprintsFrozen || ...
        ~permit.sourcePosteriorAuthorized || ...
        isempty(permit.sourceInputFingerprint.canonicalSha256)
    error('FormationBundleSourcePermit:SourceFreezePending', ...
        ['The executable source and exact case-input fingerprints ', ...
         'must be frozen before any source filter execution.']);
end
currentSourceManifest = ...
    buildFormationBackboneBundleM24ExecutableSourceManifest();
if ~strcmp(currentSourceManifest.canonicalSha256, ...
        permit.executableSourceManifestSha256)
    error('FormationBundleSourcePermit:ExecutableSourceDrift', ...
        'The current executable source differs from the frozen manifest.');
end
gitState = validateFormationBackboneBundleM24ExecutableGitState( ...
    permit.executableSourceCommit);

assertExactFields(runtimeRequest, { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig', ...
    'inputFingerprint'}, ...
    'FormationBundleSourcePermit:RuntimeRequestDrift');
if ~strcmp(runtimeRequest.contractVersion, ...
            'dynamic-topology-filter-authorization-request-v1') || ...
        ~strcmp(runtimeRequest.operation, 'filter-execution') || ...
        ~isa(runtimeRequest.measurementTimeCount, 'double') || ...
        ~isreal(runtimeRequest.measurementTimeCount) || ...
        ~isscalar(runtimeRequest.measurementTimeCount) || ...
        ~isfinite(runtimeRequest.measurementTimeCount) || ...
        runtimeRequest.measurementTimeCount ~= ...
            round(runtimeRequest.measurementTimeCount) || ...
        runtimeRequest.measurementTimeCount ~= ...
            permit.sourceWindow(2) || ...
        ~isa(runtimeRequest.sensorTrajectoryTimeCounts, 'double') || ...
        ~isreal(runtimeRequest.sensorTrajectoryTimeCounts) || ...
        ~isvector(runtimeRequest.sensorTrajectoryTimeCounts) || ...
        numel(runtimeRequest.sensorTrajectoryTimeCounts) ~= 24 || ...
        any(~isfinite(runtimeRequest.sensorTrajectoryTimeCounts)) || ...
        any(runtimeRequest.sensorTrajectoryTimeCounts ~= ...
            round(runtimeRequest.sensorTrajectoryTimeCounts)) || ...
        any(runtimeRequest.sensorTrajectoryTimeCounts ~= ...
            permit.sourceWindow(2))
    error('FormationBundleSourcePermit:RuntimeWindowDrift', ...
        'The source filter time window differs from the registered case.');
end
if ~isequaln(runtimeRequest.inputFingerprint, ...
        permit.sourceInputFingerprint)
    error('FormationBundleSourcePermit:SourceInputDrift', ...
        ['Measurements, sensor trajectories, neighbor map, ', ...
         'communication inputs, or the truth-stripped model changed.']);
end
[expectedTriggerConfig, triggerFingerprint] = ...
    buildFormationBackboneBundleM24SourceTriggerConfig( ...
        permit.presetName);
if ~isequaln(runtimeRequest.triggerConfig, expectedTriggerConfig) || ...
        ~strcmp(triggerFingerprint.canonicalSha256, ...
            permit.sourceTriggerFingerprintSha256)
    error('FormationBundleSourcePermit:TriggerConfigDrift', ...
        'The source trigger config or policy identity changed.');
end

if ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'numberOfSensors') || ...
        ~isa(model.numberOfSensors, 'double') || ...
        ~isreal(model.numberOfSensors) || ...
        ~isscalar(model.numberOfSensors) || ...
        model.numberOfSensors ~= 24 || ...
        ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isstruct(model.dynamicTopologyScenario) || ...
        ~isscalar(model.dynamicTopologyScenario) || ...
        ~isfield(model.dynamicTopologyScenario, 'config') || ...
        ~isstruct(model.dynamicTopologyScenario.config) || ...
        ~isscalar(model.dynamicTopologyScenario.config) || ...
        ~isfield(model.dynamicTopologyScenario, 'presetName') || ...
        ~strcmp(model.dynamicTopologyScenario.presetName, ...
            permit.presetName) || ...
        ~isfield(model.dynamicTopologyScenario, 'seed') || ...
        ~isa(model.dynamicTopologyScenario.seed, 'double') || ...
        ~isreal(model.dynamicTopologyScenario.seed) || ...
        ~isscalar(model.dynamicTopologyScenario.seed) || ...
        ~isfinite(model.dynamicTopologyScenario.seed) || ...
        model.dynamicTopologyScenario.seed ~= permit.seed
    error('FormationBundleSourcePermit:CaseMismatch', ...
        'The source model does not match the registered preset and seed.');
end
config = model.dynamicTopologyScenario.config;
configMatches = false;
try
    configMatches = isfield(config, 'presetName') && ...
        strcmp(config.presetName, permit.presetName) && ...
        strcmp(computeCanonicalValueSha256(config), ...
            permit.configSnapshotSha256);
catch
    configMatches = false;
end
if ~configMatches
    error('FormationBundleSourcePermit:SceneConfigDrift', ...
        'The source scene config does not match its frozen snapshot.');
end
if strcmp(permit.sceneContractKind, ...
        'formation-fov-multistyle-scene-contract-v5')
    if ~isfield(config, 'sceneContractSha256') || ...
            ~strcmp(config.sceneContractSha256, ...
                permit.sceneContractSha256) || ...
            ~strcmp(computeFormationFovMultistyleSceneContractSha256( ...
                config), permit.sceneContractSha256) || ...
            ~strcmp(getExpectedFormationFovMultistyleSceneContractSha256( ...
                config), permit.sceneContractSha256) || ...
            ~isfield(config, 'trackingOutcomeAuthorized') || ...
            ~isequal(config.trackingOutcomeAuthorized, false)
        error('FormationBundleSourcePermit:SceneContractDrift', ...
            'The registered v5 calibration scene changed.');
    end
    expectedEnvelope = struct( ...
        'contractVersion', ...
            'dynamic-topology-tracking-outcome-gate-v1', ...
        'required', true, ...
        'sceneContractSha256', permit.sceneContractSha256);
    if ~isfield(model, 'dynamicTopologyTrackingOutcomeGate') || ...
            ~isequaln(model.dynamicTopologyTrackingOutcomeGate, ...
                expectedEnvelope)
        error('FormationBundleSourcePermit:SceneContractDrift', ...
            'The registered v5 model-level outcome gate changed.');
    end
elseif ~strcmp(permit.sceneContractKind, ...
            'full-config-snapshot-v1') || ...
        ~strcmp(permit.sceneContractSha256, ...
            permit.configSnapshotSha256)
    error('FormationBundleSourcePermit:SceneContractDrift', ...
        'The radial scene contract kind is not registered.');
end
if containsForbiddenTargetTruth(model)
    error('FormationBundleSourcePermit:TargetTruthPresent', ...
        'Target trajectories must be removed before source filtering.');
end
assertModelSensorTrajectoryWindow(model, permit.sourceWindow(2));

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = 'registered-case-permit';
authorization.permitId = permit.id;
authorization.permitCanonicalSha256 = ...
    permit.permitCanonicalSha256;
authorization.capability = permit.capability;
authorization.action = permit.filterAction;
authorization.protocolId = permit.protocolId;
authorization.protocolCanonicalSha256 = ...
    permit.protocolCanonicalSha256;
authorization.caseId = permit.caseId;
authorization.caseCanonicalSha256 = ...
    permit.caseCanonicalSha256;
authorization.presetName = permit.presetName;
authorization.seed = permit.seed;
authorization.sourceWindow = permit.sourceWindow;
authorization.armId = permit.armId;
authorization.armOrdinal = permit.armOrdinal;
authorization.methodSourceCommit = permit.methodSourceCommit;
authorization.methodPolicyConfigSha256 = ...
    permit.methodPolicyConfigSha256;
authorization.sourceTriggerFingerprintSha256 = ...
    permit.sourceTriggerFingerprintSha256;
authorization.executableSourceCommit = ...
    permit.executableSourceCommit;
authorization.executableSourceManifestSha256 = ...
    permit.executableSourceManifestSha256;
authorization.executionHeadCommit = gitState.headCommit;
authorization.sourceInputFingerprintSha256 = ...
    permit.sourceInputFingerprint.canonicalSha256;
authorization.trackingOutcomeScoringAuthorized = false;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function result = containsForbiddenTargetTruth(value)
result = false;
if iscell(value)
    for valueIdx = 1:numel(value)
        if containsForbiddenTargetTruth(value{valueIdx})
            result = true;
            return;
        end
    end
    return;
end
if ~isstruct(value)
    return;
end
names = fieldnames(value);
for valueIdx = 1:numel(value)
    for fieldIdx = 1:numel(names)
        fieldName = names{fieldIdx};
        lowerName = lower(fieldName);
        if any(strcmp(lowerName, { ...
                'groundtruth', 'groundtruthrfs', 'truth', ...
                'trackingtruth', 'trackingtruthrfs', ...
                'targettrajectories', ...
                'explicittargettrajectories'})) || ...
                ~isempty(strfind(lowerName, 'groundtruth')) || ... %#ok<STREMP>
                ~isempty(strfind(lowerName, 'targettrajector')) %#ok<STREMP>
            result = true;
            return;
        end
        if containsForbiddenTargetTruth(value(valueIdx).(fieldName))
            result = true;
            return;
        end
    end
end
end

function assertModelSensorTrajectoryWindow(model, expectedTimeCount)
fieldNames = {'explicitSensorTrajectories', 'sensorTrajectories'};
for fieldIdx = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIdx};
    if ~isfield(model, fieldName)
        continue;
    end
    trajectories = model.(fieldName);
    if ~iscell(trajectories) || numel(trajectories) ~= 24
        error('FormationBundleSourcePermit:ModelSensorWindowDrift', ...
            'The source model sensor trajectories are malformed.');
    end
    for sensorIdx = 1:numel(trajectories)
        trajectory = trajectories{sensorIdx};
        if ~isa(trajectory, 'double') || ~isreal(trajectory) || ...
                size(trajectory, 2) ~= expectedTimeCount || ...
                any(~isfinite(trajectory(:)))
            error('FormationBundleSourcePermit:ModelSensorWindowDrift', ...
                ['The source model retains a sensor trajectory beyond ', ...
                 'the registered source window.']);
        end
    end
end
end

function assertExactFields(value, expectedFields, identifier)
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)), ...
            sort(reshape(expectedFields, [], 1)))
    error(identifier, 'A registered source-gate field set changed.');
end
end
