function validateCausalMinimalEditFormationProjectionCertificate( ...
        certificate, sensorPhysicalUids, projectedBaseAdjacency)
% VALIDATECAUSALMINIMALEDITFORMATIONPROJECTIONCERTIFICATE Recompute V46 proof.

required = {'contractVersion', 'canonicalSha256', ...
    'arrayOrderExecutionCanonicalSha256', ...
    'currentInputCanonicalSha256', ...
    'registeredRemovalCount', 'nonregisteredAdditionCount', ...
    'forcedRegisteredRemovalCount', ...
    'optionalRegisteredRemovalCount', ...
    'registeredPairPhysicalUids', ...
    'projectedPairPhysicalUids', ...
    'removedRegisteredPairPhysicalUids', ...
    'addedNonregisteredPairPhysicalUids', ...
    'searchCandidateCounts', ...
    'routeInputBoundary', 'registeredBaseGraphUsed', ...
    'currentGeometryUsed', 'currentPhysicalPageUsed', ...
    'currentLinkProbabilityPageUsed', 'futureGeometryUsed', ...
    'futurePhysicalPageUsed', 'posteriorUsed', 'truthUsed', ...
    'measurementUsed', 'realizedDeliveryUniformsUsed', ...
    'runtimeOverridesAccepted', 'scoreFunctionAccepted', ...
    'sensorArrayPermutationEquivarianceDesigned', ...
    'groupNumericRelabelEquivarianceDesigned'};
if ~isstruct(certificate) || ~isscalar(certificate) || ...
        ~all(isfield(certificate, required)) || ...
        ~strcmp(certificate.contractVersion, ...
            'causal-minimal-edit-formation-backbone-projection-v1') || ...
        ~strcmp(certificate.routeInputBoundary, ...
            ['current-page-only-no-runtime-overrides-or-', ...
             'score-functions']) || ...
        ~allTrue(certificate, { ...
            'registeredBaseGraphUsed', 'currentGeometryUsed', ...
            'currentPhysicalPageUsed', ...
            'currentLinkProbabilityPageUsed', ...
            'sensorArrayPermutationEquivarianceDesigned', ...
            'groupNumericRelabelEquivarianceDesigned'}) || ...
        ~allFalse(certificate, { ...
            'futureGeometryUsed', 'futurePhysicalPageUsed', ...
            'posteriorUsed', 'truthUsed', 'measurementUsed', ...
            'realizedDeliveryUniformsUsed', ...
            'runtimeOverridesAccepted', 'scoreFunctionAccepted'}) || ...
        ~isSha256(certificate.canonicalSha256) || ...
        ~isSha256(certificate.currentInputCanonicalSha256) || ...
        ~isSha256(certificate. ...
            arrayOrderExecutionCanonicalSha256)
    error('FormationProjectionCertificate:BoundaryViolation', ...
        'The causal projection certificate crossed its frozen boundary.');
end

countFields = {'registeredRemovalCount', ...
    'forcedRegisteredRemovalCount', ...
    'optionalRegisteredRemovalCount', ...
    'nonregisteredAdditionCount'};
if ~allNonnegativeIntegerFields(certificate, countFields) || ...
        certificate.registeredRemovalCount ~= ...
            certificate.forcedRegisteredRemovalCount + ...
            certificate.optionalRegisteredRemovalCount || ...
        ~validPhysicalUidPairs( ...
            certificate.registeredPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.projectedPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.removedRegisteredPairPhysicalUids) || ...
        ~validPhysicalUidPairs( ...
            certificate.addedNonregisteredPairPhysicalUids) || ...
        certificate.registeredRemovalCount ~= size( ...
            certificate.removedRegisteredPairPhysicalUids, 1) || ...
        certificate.nonregisteredAdditionCount ~= size( ...
            certificate.addedNonregisteredPairPhysicalUids, 1) || ...
        ~isstruct(certificate.searchCandidateCounts) || ...
        ~isscalar(certificate.searchCandidateCounts) || ...
        ~allNonnegativeIntegerFields( ...
            certificate.searchCandidateCounts, ...
            fieldnames(certificate.searchCandidateCounts))
    error('FormationProjectionCertificate:InvalidSchema', ...
        'The projection certificate count or UID-pair schema is invalid.');
end

nodeCount = numel(sensorPhysicalUids);
if ~(islogical(projectedBaseAdjacency) || ...
        isnumeric(projectedBaseAdjacency)) || ...
        ~isreal(projectedBaseAdjacency) || ...
        any(~isfinite(projectedBaseAdjacency(:))) || ...
        ~isequal(size(projectedBaseAdjacency), ...
            [nodeCount, nodeCount]) || ...
        any(projectedBaseAdjacency(:) ~= 0 & ...
            projectedBaseAdjacency(:) ~= 1)
    error('FormationProjectionCertificate:InvalidExecutionView', ...
        'The projected execution view is malformed.');
end
canonicalPayload = rmfield(certificate, { ...
    'canonicalSha256', 'arrayOrderExecutionCanonicalSha256'});
executionPayload = struct( ...
    'contractVersion', ...
        'causal-minimal-edit-formation-execution-view-v1', ...
    'sensorPhysicalUidsByArray', ...
        reshape(sensorPhysicalUids, 1, []), ...
    'projectedBaseAdjacency', logical(projectedBaseAdjacency));
if ~strcmp(computeCanonicalValueSha256(canonicalPayload), ...
        certificate.canonicalSha256) || ...
        ~strcmp(computeCanonicalValueSha256(executionPayload), ...
            certificate.arrayOrderExecutionCanonicalSha256)
    error('FormationProjectionCertificate:CanonicalDrift', ...
        'The projection certificate failed canonical recomputation.');
end
end

function valid = allTrue(value, fields)
valid = all(cellfun(@(field) islogical(value.(field)) && ...
    isscalar(value.(field)) && value.(field), fields));
end

function valid = allFalse(value, fields)
valid = all(cellfun(@(field) islogical(value.(field)) && ...
    isscalar(value.(field)) && ~value.(field), fields));
end

function valid = allNonnegativeIntegerFields(value, fields)
valid = all(cellfun(@(field) ...
    isfield(value, field) && ...
    isa(value.(field), 'double') && isreal(value.(field)) && ...
    isscalar(value.(field)) && isfinite(value.(field)) && ...
    value.(field) >= 0 && value.(field) == round(value.(field)), ...
    fields));
end

function valid = validPhysicalUidPairs(value)
valid = isa(value, 'double') && isreal(value) && ...
    size(value, 2) == 2 && all(isfinite(value(:))) && ...
    all(value(:) >= 1) && all(value(:) == round(value(:))) && ...
    all(value(:, 1) < value(:, 2)) && ...
    isequal(value, sortrows(value, [1, 2]));
end

function valid = isSha256(value)
valid = ischar(value) && isrow(value) && numel(value) == 64 && ...
    all(ismember(lower(value), '0123456789abcdef'));
end
