function validateFormationStaggeredRecoveryX36OutcomePreflight( ...
        preflight, permit)
% VALIDATEFORMATIONSTAGGEREDRECOVERYX36OUTCOMEPREFLIGHT Pure v3 gate.

if ~isstruct(preflight) || ~isscalar(preflight) || ...
        ~isstruct(permit) || ~isscalar(permit)
    error('X36OutcomePermit:InvalidStructure', ...
        'The permit and preflight must be scalar structures.');
end
validatePermit(permit);
assertExactFields(preflight, { ...
    'contractVersion', 'generatedAt', 'generationGitCommit', ...
    'generationTrackedWorktreeDirty', ...
    'generationUntrackedSourceFiles', 'completionGitCommit', ...
    'completionTrackedWorktreeDirty', ...
    'completionUntrackedSourceFiles', 'sourceManifest', ...
    'sourceManifestSha256', 'protocol', ...
    'fingerprintDiscoveryMode', 'm24ScreenPath', ...
    'm24ScreenSha256', 'm24ScreenGenerationCommit', ...
    'sceneAuditPath', 'sceneAuditSha256', ...
    'sceneAuditGenerationCommit', 'states', 'anchorTimes', ...
    'runtimeFingerprintSha256ByStateArm', 'pairProposals', ...
    'pairedOutcomeEligibilityMask', 'eligibleStateCount', ...
    'eligiblePairs', 'x36PairedOutcomePermitMayBeMinted', ...
    'x36PairedOutcomeRerunAuthorized', ...
    'maximumAuthorizedPairCount', 'maximumEligiblePairCount', ...
    'separateHashedOutcomePermitRequired', ...
    'trackingOutcomeScored', 'newPosteriorStateOpened', ...
    'outcomeRankingUsesTruth', ...
    'scenarioTruthRemovedBeforePolicyConstruction', ...
    'scenarioTruthFieldsRemovedBeforePolicyConstruction', ...
    'policyContextSanitizerContractVersion', ...
    'policyContextUsesCurrentObservableInputsOnly', ...
    'policyContextModelStaticFusionInputsOnly', ...
    'futureLinkUniformsUnavailableToPolicy', ...
    'futureLinkProbabilityPagesUnavailableToPolicy', ...
    'futureSensorTrajectoriesUnavailableToPolicy', ...
    'cacheOutcomeFieldsEmpty', 'gnnTrainingAuthorized', ...
    'x48Opened', 'reservedSeedOpened', ...
    'validationClaimAllowed', 'outcomePermitBoundary', ...
    'evidenceBoundary', 'matPath', 'reportPath', ...
    'publicationCompletionContractVersion', ...
    'publicationCompletionMarkerRequired', ...
    'publicationCompletionMarkerPath'}, ...
    'X36OutcomePermit:PreflightShapeDrift', ...
    'The formal v3 preflight field set changed.');

if ~strcmp(preflight.contractVersion, ...
            permit.preflightContractVersion) || ...
        ~strcmp(preflight.matPath, permit.preflightPath) || ...
        ~strcmp(preflight.reportPath, permit.preflightReportPath) || ...
        ~strcmp(preflight.publicationCompletionContractVersion, ...
            permit.preflightPublicationContractVersion) || ...
        ~isTrue(preflight.publicationCompletionMarkerRequired) || ...
        ~strcmp(preflight.publicationCompletionMarkerPath, ...
            permit.preflightCompletionMarkerPath)
    error('X36OutcomePermit:PreflightPathMismatch', ...
        'Only the fixed formal v3 artifact set is accepted.');
end
if ~strcmp(preflight.generationGitCommit, ...
            permit.preflightGenerationGitCommit) || ...
        ~strcmp(preflight.completionGitCommit, ...
            permit.preflightCompletionGitCommit) || ...
        ~isFalse(preflight.fingerprintDiscoveryMode) || ...
        ~isFalse(preflight.generationTrackedWorktreeDirty) || ...
        ~isFalse(preflight.completionTrackedWorktreeDirty) || ...
        ~iscell(preflight.generationUntrackedSourceFiles) || ...
        ~isempty(preflight.generationUntrackedSourceFiles) || ...
        ~iscell(preflight.completionUntrackedSourceFiles) || ...
        ~isempty(preflight.completionUntrackedSourceFiles)
    error('X36OutcomePermit:DirtyPreflightRejected', ...
        'The formal v3 preflight must be clean at both source gates.');
end
validateSourceManifest(preflight, permit);
validateEmbeddedSourceProtocol(preflight.protocol, permit);

if ~isTrue(preflight.x36PairedOutcomePermitMayBeMinted) || ...
        ~isFalse(preflight.x36PairedOutcomeRerunAuthorized) || ...
        ~isTrue(preflight.separateHashedOutcomePermitRequired) || ...
        ~isZeroScalar(preflight.maximumAuthorizedPairCount) || ...
        ~isExactScalar(preflight.maximumEligiblePairCount, ...
            permit.authorizedPairCount) || ...
        ~isExactScalar(preflight.eligibleStateCount, ...
            permit.authorizedPairCount)
    error('X36OutcomePermit:PreflightAuthorizationMismatch', ...
        ['The source-only v3 preflight must remain unauthorized while ', ...
         'making exactly three pairs permit-eligible.']);
end
if ~isFalse(preflight.trackingOutcomeScored) || ...
        ~isFalse(preflight.newPosteriorStateOpened) || ...
        ~isFalse(preflight.outcomeRankingUsesTruth) || ...
        ~isTrue(preflight. ...
            scenarioTruthRemovedBeforePolicyConstruction) || ...
        ~isequal(preflight. ...
            scenarioTruthFieldsRemovedBeforePolicyConstruction, ...
            {'groundTruth', 'groundTruthRfs', 'targetTrajectories', ...
             'model.explicitTargetTrajectories', ...
             ['model.dynamicTopologyScenario.', ...
              'targetTrajectories']}) || ...
        ~strcmp(preflight.policyContextSanitizerContractVersion, ...
            'topology-policy-observable-input-v2') || ...
        ~isTrue(preflight. ...
            policyContextUsesCurrentObservableInputsOnly) || ...
        ~isTrue(preflight.policyContextModelStaticFusionInputsOnly) || ...
        ~isTrue(preflight.futureLinkUniformsUnavailableToPolicy) || ...
        ~isTrue(preflight. ...
            futureLinkProbabilityPagesUnavailableToPolicy) || ...
        ~isTrue(preflight.futureSensorTrajectoriesUnavailableToPolicy) || ...
        ~isTrue(preflight.cacheOutcomeFieldsEmpty) || ...
        ~isFalse(preflight.gnnTrainingAuthorized) || ...
        ~isFalse(preflight.x48Opened) || ...
        ~isFalse(preflight.reservedSeedOpened) || ...
        ~isFalse(preflight.validationClaimAllowed)
    error('X36OutcomePermit:PreflightBoundaryViolation', ...
        'The v3 causal-input or research-scope boundary changed.');
end

pairCount = permit.authorizedPairCount;
if ~isequal(preflight.anchorTimes, [72, 100, 128]) || ...
        ~islogical(preflight.pairedOutcomeEligibilityMask) || ...
        ~isequal(preflight.pairedOutcomeEligibilityMask, ...
            true(1, pairCount)) || ...
        ~isequal(size(preflight.pairProposals), [1, pairCount]) || ...
        ~isequal(size(preflight.eligiblePairs), [1, pairCount]) || ...
        ~isequal(size(preflight.states), [1, pairCount]) || ...
        ~isequal(size( ...
            preflight.runtimeFingerprintSha256ByStateArm), ...
            [pairCount, permit.exactArmCountPerPair]) || ...
        ~isequal(preflight.runtimeFingerprintSha256ByStateArm, ...
            permit.authorizedRuntimeFingerprintSha256ByStateArm) || ...
        ~isequal(preflight.runtimeFingerprintSha256ByStateArm, ...
            preflight.protocol. ...
                expectedRuntimeFingerprintSha256ByStateArm)
    error('X36OutcomePermit:PairSetDrift', ...
        'The exact ordered v3 three-pair/two-arm set changed.');
end
for pairIdx = 1:pairCount
    proposal = preflight.pairProposals(pairIdx);
    validatePairProposal(proposal, pairIdx, ...
        preflight.protocol, permit);
    if ~isequaln(preflight.eligiblePairs(pairIdx), proposal)
        error('X36OutcomePermit:EligiblePairDrift', ...
            'Eligible-pair records must equal the frozen proposals.');
    end
    validateSourceState(preflight.states(pairIdx), ...
        proposal, pairIdx, preflight.protocol, permit);
end
end

function validatePermit(permit)
assertExactFields(permit, { ...
    'id', 'contractVersion', 'authorizedRunnerContractVersion', ...
    'sourceProtocolContractVersion', ...
    'sourceProtocolCanonicalSha256', ...
    'preflightContractVersion', 'preflightPath', ...
    'preflightSha256', 'preflightReportPath', ...
    'preflightReportSha256', 'preflightCompletionMarkerPath', ...
    'preflightCompletionMarkerSha256', ...
    'preflightPublicationContractVersion', ...
    'preflightGenerationGitCommit', ...
    'preflightCompletionGitCommit', ...
    'preflightSourceManifestContractVersion', ...
    'preflightSourceManifestSha256', ...
    'gateBaseGitCommit', 'releaseDescriptorContractVersion', ...
    'releaseDescriptorPath', 'releaseTagName', ...
    'releaseRemoteUrl', 'releaseBranchRef', ...
    'releaseTagMustBeAnnotated', 'releaseTagMustBePublished', ...
    'releaseCommitMustDirectlyFollowGate', ...
    'releaseCommitMustBePublished', ...
    'gitHistoryOverridesForbidden', ...
    'pairProposalContractVersion', 'authorizedPairIds', ...
    'authorizedPairProposalCanonicalSha256', ...
    'authorizedRuntimeFingerprintSha256ByStateArm', ...
    'authorizedPostPreflightExecutablePaths', ...
    'authorizedPostPreflightExecutableChangeCount', ...
    'authorizedGateCommitPaths', ...
    'authorizedGateCommitChangeCount', ...
    'authorizedPairCount', 'exactArmCountPerPair', ...
    'maximumPairedRunCountPerPair', ...
    'maximumOfficialAggregateRunCount', ...
    'outcomeClaimContractVersion', ...
    'outcomeClaimCommonDirectoryRelativePath', ...
    'outcomeClaimMetadataFileName', ...
    'outcomeClaimRemoteTagName', 'outcomeClaimRemoteRef', ...
    'outcomeClaimRemoteMustBeCreatedAtomically', ...
    'outcomeClaimMustCoverAllWorktreesAndClones', ...
    'outcomeClaimMustPrecedeTrackingOutcome', ...
    'failedClaimConsumesAuthorization', ...
    'referenceArmId', 'candidateArmId', ...
    'referenceArmOrdinal', 'candidateArmOrdinal', ...
    'sourceProtocolMustRemainTrackingUnauthorized', ...
    'preflightMustRemainTrackingUnauthorized', ...
    'preflightCompletionMarkerRequired', ...
    'trackingOutcomeRerunAuthorized', ...
    'x36PairedOutcomeRerunAuthorized', ...
    'unrestrictedX36OutcomeOpeningAuthorized', ...
    'overwriteExistingOfficialOutputAuthorized', ...
    'outcomeSelectionOrRankingAuthorized', ...
    'gnnTrainingAuthorized', 'x48OutcomeOpeningAuthorized', ...
    'reservedSeedOpeningAuthorized', 'validationClaimAllowed', ...
    'developmentEvidenceOnly', 'evidenceBoundary', ...
    'permitCanonicalSha256'}, ...
    'X36OutcomePermit:PermitShapeDrift', ...
    'The exact v3 outcome-permit field set changed.');
payload = rmfield(permit, 'permitCanonicalSha256');
try
    actualPermitSha256 = computeCanonicalValueSha256(payload);
catch
    error('X36OutcomePermit:PermitHashDrift', ...
        'The outcome permit contains an unsupported value.');
end
if ~isSha256(permit.permitCanonicalSha256) || ...
        ~strcmp(actualPermitSha256, permit.permitCanonicalSha256)
    error('X36OutcomePermit:PermitHashDrift', ...
        'The independent v3 outcome-permit payload changed.');
end

expectedPairIds = { ...
    'x36-seed211-t72-reference-vs-v35-h3', ...
    'x36-seed211-t100-reference-vs-v35-h3', ...
    'x36-seed211-t128-reference-vs-v35-h3'};
expectedPairSha256 = { ...
    '75cf7b5a292de9710caa0fbcf79da0ed181d8c75c121e70c7755aa5047c634bb', ...
    'c10c9acd32966d1104c35c9602b44ae5ae5a84a06c4ed0f6e5de2fbece7f3755', ...
    '77aae38de2e18874a22cb837cf6317226bb24f58824c5f4b43ed9fef198d3463'};
expectedFingerprints = { ...
    '2d3ff282f22946283e7a69fbaebbdfe68ddce2b3761e7bccd999d0ca2fcd15cc', ...
    '9a9930347c3c5f176c4bc0b3fd7529d8a6ffd05fdbc6c1cb3516c4fd49204eab'; ...
    '712198520a745ca98089a053b2a3391b3280bf35c173f39344af98f3972a3425', ...
    'c296d38b885b9e66ab0be2fabf9696f87e908bc38b70af92619cdaf1a8f213a1'; ...
    'afff6228ef68c3d3d7c7f51c18e67884807e448f7edf126d5a670dd3bb570f81', ...
    '6ff4e90f72563d410c7f3bfe60363c08d6d34ccd919dbf242966664f31b02881'};
expectedExecutablePaths = { ...
    fullfile('RUN', 'GA', ...
        'runFormationStaggeredRecoveryX36V37Screen.m'), ...
    fullfile('common', ...
        'getFormationStaggeredRecoveryX36OutcomePermit.m'), ...
    fullfile('common', ...
        'loadFormationStaggeredRecoveryX36OutcomePermit.m'), ...
    fullfile('common', ...
        'consumeFormationStaggeredRecoveryX36OutcomePermit.m'), ...
    fullfile('common', ...
        'validateFormationStaggeredRecoveryX36OutcomePreflight.m'), ...
    fullfile('tests', ...
        'test_formation_staggered_recovery_x36_outcome_permit.m')};
expectedGatePaths = [ ...
    {fullfile('RUN', 'GA', 'dynamic_topology', ...
        'FORMATION_STAGGERED_RECOVERY_X36_V37_DESIGN.md')}, ...
    expectedExecutablePaths];
if ~strcmp(permit.id, ...
            'formation-staggered-recovery-x36-v37-outcome-permit-v3') || ...
        ~strcmp(permit.contractVersion, ...
            'formation-staggered-recovery-x36-outcome-permit-v3') || ...
        ~strcmp(permit.authorizedRunnerContractVersion, [ ...
            'formation-staggered-recovery-x36-v37-', ...
            'exact-two-arm-runner-v3']) || ...
        ~strcmp(permit.sourceProtocolContractVersion, ...
            'formation-staggered-recovery-x36-source-protocol-v3') || ...
        ~strcmp(permit.sourceProtocolCanonicalSha256, ...
            '9fee393ca74e2eca3dd69861470c2ee759a332a2bfbff300afae33633a740d19') || ...
        ~strcmp(permit.preflightContractVersion, ...
            'formation-staggered-recovery-x36-v37-preflight-v3') || ...
        ~strcmp(permit.preflightSha256, ...
            'f82b531a51df124c7f0342d6c8d77950ba16431b473ad636f39732bcda7b9fde') || ...
        ~strcmp(permit.preflightReportSha256, ...
            'd3e66375e6e464528c14738fa37d708ef9c1c4bedfeadeaaf30a133eef85aacb') || ...
        ~strcmp(permit.preflightCompletionMarkerSha256, ...
            'bcdb136ea3a0fea3eeb4fb79db538e5c9b21256beb16e63af61995cf23660aae') || ...
        ~strcmp(permit.preflightGenerationGitCommit, ...
            'faa6d4e99137fedf9c65c951b0e02d02d6dc3d46') || ...
        ~strcmp(permit.preflightCompletionGitCommit, ...
            permit.preflightGenerationGitCommit) || ...
        ~strcmp(permit.preflightSourceManifestContractVersion, ...
            'registered-executable-source-manifest-v2') || ...
        ~strcmp(permit.preflightSourceManifestSha256, ...
            '1127516ddcb5ce0e07a5cf0bd9942153cc2cf08c9f1b76d915aa4318273db2a3') || ...
        ~strcmp(permit.gateBaseGitCommit, ...
            'c037aa37eec9161e54d1d3dea7a689060a88eb95') || ...
        ~strcmp(permit.releaseDescriptorContractVersion, [ ...
            'formation-staggered-recovery-x36-', ...
            'outcome-release-descriptor-v1']) || ...
        ~strcmp(permit.releaseDescriptorPath, fullfile( ...
            'RUN', 'GA', 'dynamic_topology', 'evidence', ...
            'formation_value_v37', 'x36_outcome_v3', 'release', ...
            ['FORMATION_STAGGERED_RECOVERY_X36_V37_', ...
             'V3_OUTCOME_RELEASE.mat'])) || ...
        ~strcmp(permit.releaseTagName, ...
            'x36-v37-v3-outcome-gate-20260803') || ...
        ~strcmp(permit.releaseRemoteUrl, ...
            'git@github.com:Deeeeex/MULTISENSOR-LMB-FILTERS.git') || ...
        ~strcmp(permit.releaseBranchRef, ...
            'refs/heads/codex/event-conditioned-h3') || ...
        ~isTrue(permit.releaseTagMustBeAnnotated) || ...
        ~isTrue(permit.releaseTagMustBePublished) || ...
        ~isTrue(permit.releaseCommitMustDirectlyFollowGate) || ...
        ~isTrue(permit.releaseCommitMustBePublished) || ...
        ~isTrue(permit.gitHistoryOverridesForbidden) || ...
        ~strcmp(permit.pairProposalContractVersion, ...
            'formation-staggered-recovery-x36-pair-proposal-v2') || ...
        ~isequal(permit.authorizedPairIds, expectedPairIds) || ...
        ~isequal(permit.authorizedPairProposalCanonicalSha256, ...
            expectedPairSha256) || ...
        ~isequal(permit. ...
            authorizedRuntimeFingerprintSha256ByStateArm, ...
            expectedFingerprints) || ...
        ~isequal(permit.authorizedPostPreflightExecutablePaths, ...
            expectedExecutablePaths) || ...
        ~isExactScalar(permit. ...
            authorizedPostPreflightExecutableChangeCount, 6) || ...
        ~isequal(permit.authorizedGateCommitPaths, ...
            expectedGatePaths) || ...
        ~isExactScalar(permit.authorizedGateCommitChangeCount, 7) || ...
        ~isExactScalar(permit.authorizedPairCount, 3) || ...
        ~isExactScalar(permit.exactArmCountPerPair, 2) || ...
        ~isExactScalar(permit.maximumPairedRunCountPerPair, 1) || ...
        ~isExactScalar(permit.maximumOfficialAggregateRunCount, 1) || ...
        ~strcmp(permit.outcomeClaimContractVersion, [ ...
            'formation-staggered-recovery-x36-', ...
            'outcome-claim-v1']) || ...
        ~strcmp(permit.outcomeClaimCommonDirectoryRelativePath, ...
            fullfile('codex-outcome-claims', ...
                ['formation-staggered-recovery-', ...
                 'x36-v37-v3-20260803'])) || ...
        ~strcmp(permit.outcomeClaimMetadataFileName, 'claim.mat') || ...
        ~strcmp(permit.outcomeClaimRemoteTagName, ...
            'x36-v37-v3-outcome-consumed-20260803') || ...
        ~strcmp(permit.outcomeClaimRemoteRef, ...
            ['refs/tags/', permit.outcomeClaimRemoteTagName]) || ...
        ~isTrue(permit.outcomeClaimRemoteMustBeCreatedAtomically) || ...
        ~isTrue(permit.outcomeClaimMustCoverAllWorktreesAndClones) || ...
        ~isTrue(permit.outcomeClaimMustPrecedeTrackingOutcome) || ...
        ~isTrue(permit.failedClaimConsumesAuthorization) || ...
        ~strcmp(permit.referenceArmId, ...
            'formation-h3-fixed-ccw-reference-v1') || ...
        ~strcmp(permit.candidateArmId, ...
            'formation-staggered-recovery-v35-v1') || ...
        ~isExactScalar(permit.referenceArmOrdinal, 1) || ...
        ~isExactScalar(permit.candidateArmOrdinal, 2)
    error('X36OutcomePermit:PermitBindingDrift', ...
        'The v3 outcome permit no longer binds the frozen evidence.');
end
if ~isTrue(permit. ...
            sourceProtocolMustRemainTrackingUnauthorized) || ...
        ~isTrue(permit.preflightMustRemainTrackingUnauthorized) || ...
        ~isTrue(permit.preflightCompletionMarkerRequired) || ...
        ~isTrue(permit.trackingOutcomeRerunAuthorized) || ...
        ~isTrue(permit.x36PairedOutcomeRerunAuthorized) || ...
        ~isFalse(permit.unrestrictedX36OutcomeOpeningAuthorized) || ...
        ~isFalse(permit.overwriteExistingOfficialOutputAuthorized) || ...
        ~isFalse(permit.outcomeSelectionOrRankingAuthorized) || ...
        ~isFalse(permit.gnnTrainingAuthorized) || ...
        ~isFalse(permit.x48OutcomeOpeningAuthorized) || ...
        ~isFalse(permit.reservedSeedOpeningAuthorized) || ...
        ~isFalse(permit.validationClaimAllowed) || ...
        ~isTrue(permit.developmentEvidenceOnly)
    error('X36OutcomePermit:PermitScopeDrift', ...
        'The exact paired-development authorization changed.');
end
end

function validateSourceManifest(preflight, permit)
manifest = preflight.sourceManifest;
assertExactFields(manifest, { ...
    'contractVersion', 'paths', 'sha256', ...
    'unregisteredExecutablePaths', 'canonicalSha256'}, ...
    'X36OutcomePermit:SourceManifestDrift', ...
    'The formal v3 source-manifest shape changed.');
payload = rmfield(manifest, 'canonicalSha256');
try
    actualSha256 = computeCanonicalValueSha256(payload);
catch
    error('X36OutcomePermit:SourceManifestDrift', ...
        'The formal v3 source manifest cannot be hashed.');
end
if ~strcmp(manifest.contractVersion, ...
            permit.preflightSourceManifestContractVersion) || ...
        ~isempty(manifest.unregisteredExecutablePaths) || ...
        ~strcmp(manifest.canonicalSha256, ...
            permit.preflightSourceManifestSha256) || ...
        ~strcmp(preflight.sourceManifestSha256, ...
            permit.preflightSourceManifestSha256) || ...
        ~strcmp(actualSha256, manifest.canonicalSha256) || ...
        ~iscell(manifest.paths) || ~iscell(manifest.sha256) || ...
        ~isequal(size(manifest.paths), size(manifest.sha256)) || ...
        ~all(cellfun(@isSha256, manifest.sha256))
    error('X36OutcomePermit:SourceManifestDrift', ...
        'The formal v3 executable-source manifest changed.');
end
end

function validateEmbeddedSourceProtocol(protocol, permit)
try
    protocolSha256 = computeCanonicalValueSha256(protocol);
catch
    error('X36OutcomePermit:SourceProtocolDrift', ...
        'The embedded source protocol cannot be hashed canonically.');
end
if ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~strcmp(protocolSha256, ...
            permit.sourceProtocolCanonicalSha256) || ...
        ~strcmp(protocol.contractVersion, ...
            permit.sourceProtocolContractVersion) || ...
        protocol.runtimeFingerprintFreezePending || ...
        ~isequal(protocol. ...
            expectedRuntimeFingerprintSha256ByStateArm, ...
            permit.authorizedRuntimeFingerprintSha256ByStateArm) || ...
        protocol.trackingOutcomeRerunAuthorized || ...
        ~protocol.trackingOutcomeEligibilityAfterCleanPreflight || ...
        ~protocol.x36PairedOutcomeRerunRequiresCleanPreflight || ...
        protocol.gnnTrainingAuthorized || ...
        protocol.x36OutcomeOpeningAuthorized || ...
        protocol.x48OutcomeOpeningAuthorized || ...
        protocol.validationClaimAllowed
    error('X36OutcomePermit:SourceProtocolDrift', ...
        ['The embedded v3 protocol must remain frozen and ', ...
         'tracking-outcome unauthorized.']);
end
end

function validatePairProposal(proposal, pairIdx, protocol, permit)
assertExactFields(proposal, { ...
    'contractVersion', 'pairId', 'eligible', 'presetName', ...
    'seed', 'anchorTime', 'returnTimes', 'horizonSteps', ...
    'blockageFormationPair', 'cachePath', 'cacheSha256', ...
    'referenceArmId', 'referenceRuntimeSemantics', ...
    'referenceInitialActionIndex', ...
    'referenceNominalActionSequenceIndices', ...
    'referenceRuntimeFingerprintSha256', ...
    'candidateArmId', 'candidateRuntimeSemantics', ...
    'candidateInitialActionIndex', ...
    'candidateNominalActionSequenceIndices', ...
    'candidateRuntimeFingerprintSha256', ...
    'runtimeFingerprintSha256ByArm', ...
    'maximumPairedRunCount', 'trackingOutcomeScored'}, ...
    'X36OutcomePermit:PairProposalDrift', ...
    'A v3 pair-proposal field set changed.');
try
    proposalSha256 = computeCanonicalValueSha256(proposal);
catch
    error('X36OutcomePermit:PairProposalDrift', ...
        'A v3 pair proposal cannot be hashed canonically.');
end
anchorTime = protocol.anchorTimes(pairIdx);
initialAction = protocol.expectedInitialActionIndices(pairIdx);
expectedCachePath = fullfile(protocol.cacheRoot, sprintf( ...
    '%s_seed%d_n1_sig%d.mat', ...
    strrep(protocol.presetName, '-', '_'), ...
    protocol.seed, anchorTime));
expectedFingerprints = permit. ...
    authorizedRuntimeFingerprintSha256ByStateArm(pairIdx, :);
if ~strcmp(proposalSha256, permit. ...
            authorizedPairProposalCanonicalSha256{pairIdx}) || ...
        ~strcmp(proposal.contractVersion, ...
            permit.pairProposalContractVersion) || ...
        ~strcmp(proposal.pairId, ...
            permit.authorizedPairIds{pairIdx}) || ...
        ~isTrue(proposal.eligible) || ...
        ~strcmp(proposal.presetName, protocol.presetName) || ...
        ~isExactScalar(proposal.seed, protocol.seed) || ...
        ~isExactScalar(proposal.anchorTime, anchorTime) || ...
        ~isequal(proposal.returnTimes, ...
            anchorTime + (0:(protocol.horizonSteps - 1))) || ...
        ~isExactScalar(proposal.horizonSteps, protocol.horizonSteps) || ...
        ~isequal(proposal.blockageFormationPair, ...
            protocol.blockageFormationPairs(pairIdx, :)) || ...
        ~strcmp(proposal.cachePath, expectedCachePath) || ...
        ~strcmp(proposal.cacheSha256, ...
            protocol.expectedCacheSha256{pairIdx}) || ...
        ~strcmp(proposal.referenceArmId, permit.referenceArmId) || ...
        ~strcmp(proposal.referenceRuntimeSemantics, ...
            'fixed-reference') || ...
        ~isExactScalar(proposal.referenceInitialActionIndex, 1) || ...
        ~isequal(proposal. ...
            referenceNominalActionSequenceIndices, ...
            ones(1, protocol.horizonSteps)) || ...
        ~strcmp(proposal.referenceRuntimeFingerprintSha256, ...
            expectedFingerprints{1}) || ...
        ~strcmp(proposal.candidateArmId, permit.candidateArmId) || ...
        ~strcmp(proposal.candidateRuntimeSemantics, ...
            'causal-staggered-recovery') || ...
        ~isExactScalar(proposal.candidateInitialActionIndex, ...
            initialAction) || ...
        ~isequal(proposal. ...
            candidateNominalActionSequenceIndices, ...
            [initialAction, ones(1, protocol.horizonSteps - 1)]) || ...
        ~strcmp(proposal.candidateRuntimeFingerprintSha256, ...
            expectedFingerprints{2}) || ...
        ~isequal(proposal.runtimeFingerprintSha256ByArm, ...
            expectedFingerprints) || ...
        ~isExactScalar(proposal.maximumPairedRunCount, 1) || ...
        ~isFalse(proposal.trackingOutcomeScored)
    error('X36OutcomePermit:PairProposalDrift', ...
        'A frozen v3 pair proposal changed or was reordered.');
end
end

function validateSourceState(state, proposal, stateIdx, protocol, permit)
assertExactFields(state, { ...
    'anchorTime', 'blockageFormationPair', 'cachePath', ...
    'cacheSha256', 'cacheGenerationGitCommit', ...
    'initialControlConstructionSeconds', ...
    'runtimeReplaySecondsByArm', 'initialControl', ...
    'candidateInitialActionIndex', 'runtimeReplays', ...
    'runtimeFingerprintSha256ByArm', ...
    'explicitStaggeredReleaseCount', ...
    'runtimeReplayPassedByArm', 'trackingOutcomeScored', ...
    'truthUsed', 'futureOutcomeUsed'}, ...
    'X36OutcomePermit:SourceStateDrift', ...
    'A v3 source-only state field set changed.');
if ~isExactScalar(state.anchorTime, proposal.anchorTime) || ...
        ~isequal(state.blockageFormationPair, ...
            proposal.blockageFormationPair) || ...
        ~strcmp(state.cachePath, proposal.cachePath) || ...
        ~strcmp(state.cacheSha256, proposal.cacheSha256) || ...
        ~strcmp(state.cacheGenerationGitCommit, ...
            protocol.cacheGenerationGitCommit) || ...
        ~isExactScalar(state.candidateInitialActionIndex, ...
            proposal.candidateInitialActionIndex) || ...
        ~isequal(state.runtimeFingerprintSha256ByArm, ...
            proposal.runtimeFingerprintSha256ByArm) || ...
        ~iscell(state.runtimeReplays) || ...
        ~isequal(size(state.runtimeReplays), [1, 2]) || ...
        ~islogical(state.runtimeReplayPassedByArm) || ...
        ~isequal(state.runtimeReplayPassedByArm, true(1, 2)) || ...
        ~isnumeric(state.runtimeReplaySecondsByArm) || ...
        ~isequal(size(state.runtimeReplaySecondsByArm), [1, 2]) || ...
        any(~isfinite(state.runtimeReplaySecondsByArm)) || ...
        any(state.runtimeReplaySecondsByArm <= 0) || ...
        ~isFalse(state.trackingOutcomeScored) || ...
        ~isFalse(state.truthUsed) || ~isFalse(state.futureOutcomeUsed) || ...
        ~isstruct(state.initialControl) || ...
        ~isscalar(state.initialControl) || ...
        ~isfield(state.initialControl, 'referenceFallbackUsed') || ...
        ~isFalse(state.initialControl.referenceFallbackUsed) || ...
        ~isfield(state.initialControl, 'selectedScore') || ...
        ~isstruct(state.initialControl.selectedScore) || ...
        ~isfield(state.initialControl.selectedScore, 'safe') || ...
        ~isTrue(state.initialControl.selectedScore.safe) || ...
        ~isfield(state.initialControl, 'truthUsed') || ...
        ~isFalse(state.initialControl.truthUsed) || ...
        ~isfield(state.initialControl, 'futureOutcomeUsed') || ...
        ~isFalse(state.initialControl.futureOutcomeUsed)
    error('X36OutcomePermit:SourceStateDrift', ...
        'A v3 source state no longer matches its pair proposal.');
end
for armIdx = 1:2
    validateRuntimeReplay(state.runtimeReplays{armIdx}, ...
        proposal, stateIdx, armIdx, protocol, permit);
end
end

function validateRuntimeReplay(replay, proposal, stateIdx, ...
        armIdx, protocol, permit)
assertExactFields(replay, { ...
    'contractVersion', 'armId', 'armOrdinal', 'runtimeSemantics', ...
    'posteriorUseRequired', 'currentLinkUseRequired', ...
    'returnTimes', 'actionSequenceIndices', 'selectedAdjacency', ...
    'selectedFusionWeightsByTime', 'policyBackboneModeByTime', ...
    'attemptedBytesByTime', 'retentionDebtFractionByTime', ...
    'retentionDebtThresholdByTime', ...
    'retentionDebtSingleAvailableMaskByTime', ...
    'retentionDebtSingleSafetyMaskByTime', ...
    'retentionDebtRequestedFormationIdsByTime', ...
    'retentionDebtSelectedFormationIdsByTime', ...
    'retentionDebtProjectionRemovalOrderByTime', ...
    'staggeredRecoveryScheduleByTime', ...
    'reserveProposalFormationAdjacencyByTime', ...
    'referenceNetworkRiskByTime', 'selectedNetworkRiskByTime', ...
    'referenceFallbackCountByTime', 'evaluatedActionCountByTime', ...
    'safeActionCountByTime', 'oneStepReservePassedByTime', ...
    'posteriorContentUsedByTime', ...
    'currentLinkReliabilityUsedByTime', ...
    'observableContextOnlyByTime', ...
    'observableInputContractByTime', ...
    'selectedSensorB3Pass', 'selectedFormationB3Pass', ...
    'executedActionIndicesByTime', 'policyHistoryCountByTime', ...
    'policyHistoryTimesByTime', 'firstActionExact', ...
    'firstFusionWeightsExact', 'truthUsed', 'futureOutcomeUsed', ...
    'trackingOutcomeScored', 'groundTruthAccessed', ...
    'runtimeFingerprint', 'runtimeFingerprintSha256'}, ...
    'X36OutcomePermit:RuntimeReplayDrift', ...
    'A v3 runtime-replay field set changed.');
expectedFingerprint = permit. ...
    authorizedRuntimeFingerprintSha256ByStateArm{stateIdx, armIdx};
expectedArmId = permit.referenceArmId;
expectedSemantics = 'fixed-reference';
expectedActionSequence = ...
    proposal.referenceNominalActionSequenceIndices;
expectedUse = false;
if armIdx == permit.candidateArmOrdinal
    expectedArmId = permit.candidateArmId;
    expectedSemantics = 'causal-staggered-recovery';
    expectedActionSequence = ...
        proposal.candidateNominalActionSequenceIndices;
    expectedUse = true;
end
try
    rebuiltFingerprint = ...
        buildFormationStaggeredRecoveryRuntimeFingerprint(replay);
    rebuiltSha256 = ...
        computeCanonicalValueSha256(rebuiltFingerprint);
catch
    error('X36OutcomePermit:RuntimeReplayDrift', ...
        'A v3 runtime replay cannot be fingerprinted.');
end
if ~strcmp(replay.contractVersion, ...
            'formation-staggered-recovery-v35-source-replay-v2') || ...
        ~strcmp(replay.armId, expectedArmId) || ...
        ~isExactScalar(replay.armOrdinal, armIdx) || ...
        ~strcmp(replay.runtimeSemantics, expectedSemantics) || ...
        ~isequal(replay.posteriorUseRequired, expectedUse) || ...
        ~isequal(replay.currentLinkUseRequired, expectedUse) || ...
        ~isequal(replay.returnTimes, proposal.returnTimes) || ...
        ~isequal(replay.actionSequenceIndices, ...
            expectedActionSequence) || ...
        ~strcmp(replay.runtimeFingerprintSha256, ...
            expectedFingerprint) || ...
        ~strcmp(rebuiltSha256, expectedFingerprint) || ...
        ~isequaln(replay.runtimeFingerprint, rebuiltFingerprint) || ...
        ~islogical(replay.posteriorContentUsedByTime) || ...
        ~isequal(replay.posteriorContentUsedByTime, ...
            repmat(expectedUse, 1, protocol.horizonSteps)) || ...
        ~islogical(replay.currentLinkReliabilityUsedByTime) || ...
        ~isequal(replay.currentLinkReliabilityUsedByTime, ...
            repmat(expectedUse, 1, protocol.horizonSteps)) || ...
        ~all(replay.observableContextOnlyByTime) || ...
        ~all(replay.selectedSensorB3Pass) || ...
        ~all(replay.selectedFormationB3Pass) || ...
        ~isTrue(replay.firstActionExact) || ...
        ~isTrue(replay.firstFusionWeightsExact) || ...
        ~isFalse(replay.truthUsed) || ...
        ~isFalse(replay.futureOutcomeUsed) || ...
        ~isFalse(replay.trackingOutcomeScored) || ...
        ~isFalse(replay.groundTruthAccessed)
    error('X36OutcomePermit:RuntimeReplayDrift', ...
        'A v3 runtime replay changed its arm or causal semantics.');
end
if ~iscell(replay.observableInputContractByTime) || ...
        numel(replay.observableInputContractByTime) ~= ...
            protocol.horizonSteps
    error('X36OutcomePermit:RuntimeReplayDrift', ...
        'The observable-input attestation count changed.');
end
for timeIdx = 1:protocol.horizonSteps
    contract = replay.observableInputContractByTime{timeIdx};
    if ~isstruct(contract) || ~isscalar(contract) || ...
            ~strcmp(contract.contractVersion, ...
                'topology-policy-observable-input-v2') || ...
            ~isTrue(contract.enforced) || ...
            ~isTrue(contract.passed) || ...
            ~isTrue(contract.targetTruthAbsent) || ...
            ~isTrue(contract.linkUniformsAbsent) || ...
            ~isTrue(contract.futurePDropPagesAbsent) || ...
            ~isTrue(contract.sensorTrajectoriesAbsent) || ...
            ~isTrue(contract.posteriorSchemaRestricted) || ...
            ~isTrue(contract.contextHasNoFunctionHandles) || ...
            ~isTrue(contract.contextUsesPrimitiveContainersOnly) || ...
            contract.currentTime ~= proposal.returnTimes(timeIdx)
        error('X36OutcomePermit:RuntimeReplayDrift', ...
            'A v3 observable-input attestation changed.');
    end
end
end

function assertExactFields(value, expectedFields, identifier, message)
actualFields = sort(fieldnames(value));
expectedFields = sort(reshape(expectedFields, [], 1));
if ~isequal(actualFields, expectedFields)
    error(identifier, message);
end
end

function result = isTrue(value)
result = islogical(value) && isscalar(value) && value;
end

function result = isFalse(value)
result = islogical(value) && isscalar(value) && ~value;
end

function result = isZeroScalar(value)
result = isExactScalar(value, 0);
end

function result = isExactScalar(value, expected)
result = isa(value, 'double') && isscalar(value) && ...
    isfinite(value) && value == expected;
end

function result = isSha256(value)
result = ischar(value) && isrow(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end
