function authorization = ...
        validateReferenceCardinalityReadoutV140Execution( ...
            model, context, request)
% VALIDATEREFERENCECARDINALITYREADOUTV140EXECUTION Enforce V140 readout.

protocol = getReferenceCardinalityReadoutV140Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'scheduleEnabled', 'lineageRelayEnabled', ...
    'intraFormationWorkingPayloadEnabled', ...
    'postFusionLabelReadoutEnabled', ...
    'predictiveEvidenceReadoutOnlyEnabled', ...
    'referenceCardinalityReadoutEnabled', ...
    'workingStateMutationAllowed', 'onlineReselectionEnabled', ...
    'developmentEvidenceOnly'};
enabled = false;
if isstruct(context) && isscalar(context) && isfield(context, 'phase')
    enabled = strcmp(context.phase, 'candidate');
end
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(requiredContext(:))) && ...
    strcmp(context.capability, ...
        'reference-cardinality-readout-v140-development') && ...
    strcmp(context.action, ...
        'filter-reference-cardinality-readout-v140-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    ismember(context.phase, {'reference', 'candidate'}) && ...
    islogical(context.scheduleEnabled) && ...
    islogical(context.lineageRelayEnabled) && ...
    islogical(context.intraFormationWorkingPayloadEnabled) && ...
    islogical(context.postFusionLabelReadoutEnabled) && ...
    islogical(context.predictiveEvidenceReadoutOnlyEnabled) && ...
    islogical(context.referenceCardinalityReadoutEnabled) && ...
    context.scheduleEnabled == enabled && ...
    context.lineageRelayEnabled == enabled && ...
    context.intraFormationWorkingPayloadEnabled == enabled && ...
    context.postFusionLabelReadoutEnabled == enabled && ...
    context.predictiveEvidenceReadoutOnlyEnabled == enabled && ...
    context.referenceCardinalityReadoutEnabled == enabled && ...
    isequal(context.workingStateMutationAllowed, false) && ...
    isequal(context.onlineReselectionEnabled, false) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('ReferenceCardinalityReadoutV140:InvalidExecutionContext', ...
        'The V140 execution context is malformed.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isstruct(request) || ~isscalar(request) || ...
        ~isequal(sort(fieldnames(request)), sort(requiredRequest(:))) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isscalar(request.triggerConfig)
    error('ReferenceCardinalityReadoutV140:InvalidRuntimeRequest', ...
        'The V140 runtime request is malformed.');
end
config = request.triggerConfig;
if ~isfield(config, ...
        'lineageRelayReferenceCardinalityReadoutEnabled') || ...
        logical(config. ...
            lineageRelayReferenceCardinalityReadoutEnabled) ~= enabled || ...
        ~isfield(config, 'topologyPolicyName') || ...
        ~strcmp(config.topologyPolicyName, protocol.outcomePolicyName)
    error('ReferenceCardinalityReadoutV140:InvalidRuntimeRequest', ...
        'The V140 request changed the fixed-cardinality composition.');
end

baseContext = buildCombinedOutputSafetyV139ExecutionContext( ...
    context.presetName, context.seed, context.phase, ...
    context.currentTime, context.referenceCarrierMode, context.actionSpec);
baseRequest = request;
baseProtocol = getCombinedOutputSafetyV139Protocol();
baseRequest.triggerConfig.topologyPolicyName = ...
    baseProtocol.outcomePolicyName;
baseRequest.triggerConfig = rmfield(baseRequest.triggerConfig, ...
    'lineageRelayReferenceCardinalityReadoutEnabled');
try
    authorization = validateCombinedOutputSafetyV139Execution( ...
        model, baseContext, baseRequest);
catch errorInfo
    error('ReferenceCardinalityReadoutV140:InvalidRuntimeRequest', ...
        'The V140 request failed the inherited V139 boundary: %s', ...
        errorInfo.message);
end
authorization.mode = ...
    'reference-cardinality-readout-v140-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
end
