function authorization = ...
        validateRiskEpisodeLatchedFormationShortcutV262Execution( ...
            model, context, request)
% VALIDATERISKEPISODELATCHEDFORMATIONSHORTCUTV262EXECUTION Matched dev gate.

protocol = getRiskEpisodeLatchedFormationShortcutV262Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'continuationStartTime', 'policyName', 'developmentEvidenceOnly'};
valid = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'risk-episode-latched-formation-shortcut-v262-development') && ...
    strcmp(context.action, ...
        'filter-risk-episode-latched-formation-shortcut-v262-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    strcmp(context.armId, protocol.armId) && ...
    context.measurementTimeCount == protocol.continuationEndTime && ...
    context.continuationStartTime == protocol.continuationStartTime && ...
    strcmp(context.policyName, protocol.policyName) && ...
    isequal(context.developmentEvidenceOnly, true) && ...
    isfield(request, 'triggerConfig') && ...
    isfield(request.triggerConfig, ...
        'topologyPolicyScheduleHistoryEnabled') && ...
    logical(request.triggerConfig. ...
        topologyPolicyScheduleHistoryEnabled) && ...
    isfield(request.triggerConfig, ...
        'topologyPolicyScheduleHistoryDepth') && ...
    request.triggerConfig.topologyPolicyScheduleHistoryDepth == ...
        protocol.scheduleHistoryDepth;
if ~valid
    error('RiskEpisodeLatchV262:InvalidExecutionContext', ...
        'The V262 execution context is malformed.');
end

% Reuse the V242 runtime boundary after substituting only the policy name.
sourceContext = ...
    buildCausalMinimumFormationBackboneV242ExecutionContext( ...
        context.presetName, context.seed, context.measurementTimeCount);
sourceRequest = request;
sourceProtocol = getCausalMinimumFormationBackboneV242Protocol();
sourceRequest.triggerConfig.topologyPolicyName = sourceProtocol.policyName;
authorization = validateCausalMinimumFormationBackboneV242Execution( ...
    model, sourceContext, sourceRequest);
authorization.mode = ...
    'risk-episode-latched-formation-shortcut-v262-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.sourceWindow = [ ...
    context.continuationStartTime, context.measurementTimeCount];
authorization.armId = protocol.armId;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
