function authorization = ...
        validateProtectionLoadGatedRoleV145Execution( ...
            model, context, request)
% VALIDATEPROTECTIONLOADGATEDROLEV145EXECUTION Enforce V145.

protocol = getProtectionLoadGatedRoleV145Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'scheduleEnabled', 'lineageRelayEnabled', ...
    'intraFormationWorkingPayloadEnabled', 'roleMultiplexingEnabled', ...
    'rolePeriodPages', 'roleReferencePhaseOffset', 'roleAnchorTime', ...
    'protectionLoadGateEnabled', ...
    'minimumWorkingProtectedFormationFraction', ...
    'referenceLatchEnabled', 'singlePayloadWireEnforced', ...
    'postFusionLabelReadoutEnabled', ...
    'predictiveEvidenceReadoutOnlyEnabled', ...
    'workingStateMutationAllowed', ...
    'exactStaticStateFallbackClaimAllowed', ...
    'onlineReselectionEnabled', 'developmentEvidenceOnly'};
enabled = false;
if isstruct(context) && isscalar(context) && isfield(context, 'phase')
    enabled = strcmp(context.phase, 'candidate');
end
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(requiredContext(:))) && ...
    strcmp(context.capability, ...
        'protection-load-gated-role-v145-development') && ...
    strcmp(context.action, ...
        'filter-protection-load-gated-role-v145-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    ismember(context.phase, {'reference', 'candidate'}) && ...
    ismember(context.referenceCarrierMode, ...
        protocol.referenceCarrierModes) && ...
    islogical(context.scheduleEnabled) && ...
    islogical(context.lineageRelayEnabled) && ...
    islogical(context.intraFormationWorkingPayloadEnabled) && ...
    islogical(context.roleMultiplexingEnabled) && ...
    islogical(context.protectionLoadGateEnabled) && ...
    islogical(context.referenceLatchEnabled) && ...
    islogical(context.postFusionLabelReadoutEnabled) && ...
    islogical(context.predictiveEvidenceReadoutOnlyEnabled) && ...
    context.scheduleEnabled == enabled && ...
    context.lineageRelayEnabled == enabled && ...
    context.intraFormationWorkingPayloadEnabled == enabled && ...
    context.roleMultiplexingEnabled == enabled && ...
    context.protectionLoadGateEnabled == enabled && ...
    context.referenceLatchEnabled == enabled && ...
    context.postFusionLabelReadoutEnabled == enabled && ...
    context.predictiveEvidenceReadoutOnlyEnabled == enabled && ...
    context.rolePeriodPages == protocol.roleSchedule.periodPages && ...
    context.roleReferencePhaseOffset == ...
        protocol.roleSchedule.referencePhaseOffset && ...
    context.roleAnchorTime == context.currentTime && ...
    context.minimumWorkingProtectedFormationFraction == ...
        protocol.roleSchedule. ...
            minimumWorkingProtectedFormationFractionExclusive && ...
    isequal(context.singlePayloadWireEnforced, true) && ...
    isequal(context.workingStateMutationAllowed, false) && ...
    isequal(context.exactStaticStateFallbackClaimAllowed, false) && ...
    context.onlineReselectionEnabled == enabled && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('ProtectionLoadGatedRoleV145:InvalidExecutionContext', ...
        'The V145 execution context is malformed.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isstruct(request) || ~isscalar(request) || ...
        ~isequal(sort(fieldnames(request)), sort(requiredRequest(:))) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isscalar(request.triggerConfig)
    error('ProtectionLoadGatedRoleV145:InvalidRuntimeRequest', ...
        'The V145 runtime request is malformed.');
end
config = request.triggerConfig;
validGate = ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, protocol.outcomePolicyName) && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedProtectionLoadGateEnabled') && ...
    logical(config. ...
        lineageRelayRoleMultiplexedProtectionLoadGateEnabled) == enabled && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedMinimumWorkingProtectedFraction') && ...
    config. ...
        lineageRelayRoleMultiplexedMinimumWorkingProtectedFraction == ...
        context.minimumWorkingProtectedFormationFraction && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedReferenceLatchEnabled') && ...
    logical(config. ...
        lineageRelayRoleMultiplexedReferenceLatchEnabled) == enabled;
if ~validGate
    error('ProtectionLoadGatedRoleV145:InvalidRuntimeRequest', ...
        'The V145 request changed the protection-load gate.');
end

% Reuse the complete V144 scene, action, payload and role boundary.
baseContext = buildReferenceAnchoredBurstRoleScheduleV144ExecutionContext( ...
    context.presetName, context.seed, context.phase, ...
    context.currentTime, context.referenceCarrierMode, context.actionSpec);
baseRequest = request;
baseProtocol = getReferenceAnchoredBurstRoleScheduleV144Protocol();
baseRequest.triggerConfig.topologyPolicyName = ...
    baseProtocol.outcomePolicyName;
baseRequest.triggerConfig. ...
    lineageRelayRoleMultiplexedProtectionLoadGateEnabled = false;
baseRequest.triggerConfig. ...
    lineageRelayRoleMultiplexedReferenceLatchEnabled = false;
try
    authorization = ...
        validateReferenceAnchoredBurstRoleScheduleV144Execution( ...
            model, baseContext, baseRequest);
catch errorInfo
    error('ProtectionLoadGatedRoleV145:InvalidRuntimeRequest', ...
        'The V145 request failed the inherited V144 boundary: %s', ...
        errorInfo.message);
end
authorization.mode = 'protection-load-gated-role-v145-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
end

