function semantics = ...
    validateReliableKlaCommunicationRuntimeSemantics(commConfig)
% VALIDATERELIABLEKLACOMMUNICATIONRUNTIMESEMANTICS Bind delivery semantics.
%
% The mean-square recursion integrates independent Bernoulli deliveries.
% It therefore accepts only the repository path in which each attempted
% sender-receiver-time delivery uses its registered drop probability and an
% independent uniform draw.  Realized link uniforms are deliberately absent
% from the policy context; deterministic outages and forced delivery require
% a different reliability page and are rejected here.

requiredFields = { ...
    'forceDelivery', 'outageSchedule', ...
    'deliveryIndependenceAttested', 'deliverySampler'};
if ~isstruct(commConfig) || ~isscalar(commConfig) || ...
        ~all(isfield(commConfig, requiredFields))
    error('ReliableKlaCommunication:UnsupportedSemantics', ...
        ['The communication runtime configuration lacks the explicit ', ...
         'delivery-semantics attestation.']);
end
forceDelivery = commConfig.forceDelivery;
if ~(islogical(forceDelivery) || isnumeric(forceDelivery)) || ...
        ~isscalar(forceDelivery) || ~isreal(forceDelivery) || ...
        ~isfinite(forceDelivery) || ...
        ~(forceDelivery == 0 || forceDelivery == 1)
    error('ReliableKlaCommunication:UnsupportedSemantics', ...
        'The forced-delivery flag is malformed.');
end
forceDelivery = logical(forceDelivery);
outageSchedule = commConfig.outageSchedule;
realizedLinkUniforms = getField(commConfig, 'linkUniforms', []);
independenceAttested = commConfig.deliveryIndependenceAttested;
sampler = commConfig.deliverySampler;
expectedSampler = [ ...
    'runEventTriggeredDistributedLmbFilter-simulateDelivery-', ...
    'independent-uniform-per-sender-receiver-time'];
if ~(islogical(independenceAttested) || ...
        isnumeric(independenceAttested)) || ...
        ~isscalar(independenceAttested) || ...
        ~isreal(independenceAttested) || ...
        ~isfinite(independenceAttested) || ...
        independenceAttested ~= 1 || ...
        ~ischar(sampler) || ~isrow(sampler) || ...
        ~strcmp(sampler, expectedSampler)
    error('ReliableKlaCommunication:UnsupportedSemantics', ...
        'The independent-delivery runtime attestation is invalid.');
end
if forceDelivery || ~isempty(outageSchedule) || ...
        ~isempty(realizedLinkUniforms)
    error('ReliableKlaCommunication:UnsupportedSemantics', [ ...
        'Forced delivery, deterministic outages or realized link ', ...
        'uniforms are outside the independent expected-delivery ', ...
        'certificate context.']);
end

snapshot = struct();
snapshot.forceDelivery = forceDelivery;
snapshot.outageScheduleEmpty = isempty(outageSchedule);
snapshot.realizedLinkUniformsAbsent = isempty(realizedLinkUniforms);
snapshot.deliveryIndependenceAttested = ...
    logical(independenceAttested);
snapshot.deliverySampler = sampler;
snapshot.deliveryProbabilitySource = 'current-pDropByEdge-page';

semantics = snapshot;
semantics.contractVersion = ...
    'reliable-kla-communication-runtime-semantics-v1';
semantics.passed = true;
semantics.receiverSenderTimeIndependenceRequired = true;
semantics.realizedFutureDeliveryInformationUsed = false;
semantics.canonicalSha256 = computeCanonicalValueSha256(snapshot);
end

function value = getField(structure, name, defaultValue)
if isfield(structure, name)
    value = structure.(name);
else
    value = defaultValue;
end
end
