function authorization = ...
        validateFormationSemanticContinuityShieldV236Execution( ...
            model, context, request)
% VALIDATEFORMATIONSEMANTICCONTINUITYSHIELDV236EXECUTION Teacher gate.

protocol = getFormationSemanticContinuityShieldV236Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'splitName', 'armId', ...
    'measurementTimeCount', 'policyName', 'targetFormationId', ...
    'shieldStartTime', 'scheduleSelectedFromOfflineOutcome', ...
    'developmentEvidenceOnly'};
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'formation-semantic-continuity-shield-v236-development') && ...
    strcmp(context.action, ...
        ['filter-formation-semantic-continuity-shield-', ...
         'v236-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.presetName, protocol.presetName) && ...
    context.seed == protocol.seed && ...
    strcmp(context.splitName, protocol.splitName) && ...
    strcmp(context.armId, protocol.armId) && ...
    strcmp(context.policyName, protocol.policyName) && ...
    context.targetFormationId == protocol.targetFormationId && ...
    context.shieldStartTime == protocol.shieldStartTime && ...
    isequal(context.scheduleSelectedFromOfflineOutcome, true) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('FormationSemanticContinuityV236:InvalidExecutionContext', ...
        'The V236 outcome-derived teacher context is malformed.');
end

scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, protocol.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == protocol.seed && ...
    isfield(scenario, 'config') && isstruct(scenario.config) && ...
    isfield(scenario.config, 'simulationLength') && ...
    context.measurementTimeCount == scenario.config.simulationLength && ...
    isfield(scenario.config, 'sensorGroupIds') && ...
    any(scenario.config.sensorGroupIds == protocol.targetFormationId) && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('FormationSemanticContinuityV236:InvalidRuntimeModel', ...
        'The V236 runtime model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, protocol.policyName) && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyPolicyPhysicalIdentityEnabled') && ...
    isequal(config.topologyPolicyPhysicalIdentityEnabled, true) && ...
    isfield(config, 'topologyDirectedEnabled') && ...
    isequal(config.topologyDirectedEnabled, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == ...
        protocol.directedInputsPerReceiver * model.numberOfSensors && ...
    isfield(config, 'missingLabelFusionMode') && ...
    strcmp(config.missingLabelFusionMode, protocol.receiverMode) && ...
    isfield(config, 'eventPolicy') && ...
    strcmp(config.eventPolicy, 'alwaysHeavy') && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    ~logical(config.receiverSafeLabelFusionEnabled) && ...
    isfield(config, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled') && ...
    ~logical(config. ...
        receiverSafeFormationConditionedOnlinePolicyEnabled);
if ~validRequest
    error('FormationSemanticContinuityV236:InvalidRuntimeRequest', ...
        'The V236 teacher run changed its matched payload boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'formation-semantic-continuity-shield-v236-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = protocol.presetName;
authorization.seed = protocol.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = protocol.armId;
authorization.armOrdinal = 1;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
