function authorization = ...
    validateFormationB4V46DevelopmentArmExecution( ...
        model, executionContext, runtimeRequest)
% VALIDATEFORMATIONB4V46DEVELOPMENTARMEXECUTION Fail-closed arm gate.

assertFormationB4V46DevelopmentCriticalFunctionPaths();
assertExactFields(executionContext, { ...
    'contractVersion', 'permitId', 'permitCanonicalSha256', ...
    'capability', 'action', 'caseOrdinal', 'armId'}, ...
    'FormationB4V46DevelopmentPermit:ExecutionContextDrift');
if ~strcmp(executionContext.contractVersion, ...
            'formation-b4-v46-development-arm-execution-context-v1') || ...
        ~strcmp(executionContext.capability, ...
            'development-arm-state-estimate') || ...
        ~strcmp(executionContext.action, 'filter-development-arm')
    error('FormationB4V46DevelopmentPermit:ExecutionContextDrift', ...
        'The V46 execution context requests an unsupported scope.');
end

registry = getFormationB4V46DevelopmentArmPermitRegistry();
if ~registry.filterExecutionAuthorized || ...
        ~registry.stateEstimateOutputAuthorized || ...
        ~registry.executionSurfaceFrozen || ...
        registry.permitCount ~= 16 || ...
        ~registry.completeCaseArmCartesianProduct || ...
        registry.trackingOutcomeScoringAuthorized || ...
        registry.groundTruthAccessAuthorized || ...
        registry.futureOutcomeAccessAuthorized || ...
        registry.armSelectionAuthorized || ...
        registry.developmentAdvanceDecisionAuthorized || ...
        registry.confirmationTrackingAuthorized || ...
        registry.validationClaimAllowed
    error('FormationB4V46DevelopmentPermit:ExecutionSealed', ...
        'The exact V46 development case-arm permit matrix remains sealed.');
end
permit = loadFormationB4V46DevelopmentArmPermit( ...
    executionContext.caseOrdinal, executionContext.armId);
expectedContext = struct( ...
    'contractVersion', ...
        'formation-b4-v46-development-arm-execution-context-v1', ...
    'permitId', permit.id, ...
    'permitCanonicalSha256', permit.permitCanonicalSha256, ...
    'capability', permit.capability, ...
    'action', permit.filterAction, ...
    'caseOrdinal', permit.caseOrdinal, ...
    'armId', permit.armId);
if ~isequaln(executionContext, expectedContext)
    error('FormationB4V46DevelopmentPermit:ExecutionContextDrift', ...
        'The caller context does not equal the registered permit handle.');
end
permitPayload = rmfield(permit, 'permitCanonicalSha256');
if ~strcmp(computeCanonicalValueSha256(permitPayload), ...
            permit.permitCanonicalSha256) || ...
        ~permit.nonoverwritingShardRequired || ...
        ~permit.stateEstimateOutputAuthorized || ...
        permit.trackingOutcomeScoringAuthorized || ...
        permit.groundTruthAccessAuthorized || ...
        permit.futureOutcomeAccessAuthorized || ...
        permit.armSelectionAuthorized || ...
        permit.developmentAdvanceDecisionAuthorized || ...
        permit.confirmationTrackingAuthorized || ...
        permit.validationClaimAllowed
    error('FormationB4V46DevelopmentPermit:PermitScopeDrift', ...
        'The registered V46 arm permit changed or expanded scope.');
end

manifest = buildFormationB4V46DevelopmentExecutionSurfaceManifest();
if ~strcmp(manifest.canonicalSha256, ...
        permit.executionSurfaceManifestSha256)
    error('FormationB4V46DevelopmentPermit:ExecutionSurfaceDrift', ...
        'Current executable source differs from the frozen V46 surface.');
end
gitState = validateFormationB4V46DevelopmentExecutionGitState( ...
    permit.executionSurfaceCommit);

assertExactFields(runtimeRequest, { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig', ...
    'inputFingerprint'}, ...
    'FormationB4V46DevelopmentPermit:RuntimeRequestDrift');
if ~strcmp(runtimeRequest.contractVersion, ...
            'dynamic-topology-filter-authorization-request-v1') || ...
        ~strcmp(runtimeRequest.operation, 'filter-execution') || ...
        ~isa(runtimeRequest.measurementTimeCount, 'double') || ...
        ~isreal(runtimeRequest.measurementTimeCount) || ...
        ~isscalar(runtimeRequest.measurementTimeCount) || ...
        runtimeRequest.measurementTimeCount ~= permit.simulationLength || ...
        ~isa(runtimeRequest.sensorTrajectoryTimeCounts, 'double') || ...
        ~isreal(runtimeRequest.sensorTrajectoryTimeCounts) || ...
        ~isequal(size(runtimeRequest.sensorTrajectoryTimeCounts), ...
            [1, permit.numberOfSensors]) || ...
        any(runtimeRequest.sensorTrajectoryTimeCounts ~= ...
            permit.simulationLength)
    error('FormationB4V46DevelopmentPermit:RuntimeWindowDrift', ...
        'The V46 runtime dimensions differ from the registered case.');
end
fingerprint = runtimeRequest.inputFingerprint;
requiredFingerprintFields = { ...
    'contractVersion', 'registryId', 'registryCanonicalSha256', ...
    'caseId', 'caseOrdinal', 'caseCanonicalSha256', 'seed', ...
    'seedRole', 'primaryMatrix', 'stressMatrix', ...
    'runtimeFilterModelContractVersion', ...
    'runtimeFilterBirthPriorSha256', 'modelSha256', ...
    'measurementsSha256', 'sensorTrajectoriesSha256', ...
    'neighborMapSha256', 'communicationConfigSha256', ...
    'physicalIdentityRegistrySha256', ...
    'deliveryUniformMetadataSha256', ...
    'deliveryUniformCanonicalTensorSha256', ...
    'deliveryUniformMaterializedTensorSha256', ...
    'targetTrajectoryRealizationPassedToFilter', ...
    'groundTruthPassedToFilter', 'registeredBirthPriorRetained', ...
    'canonicalSha256'};
assertExactFields(fingerprint, requiredFingerprintFields, ...
    'FormationB4V46DevelopmentPermit:RuntimeFingerprintDrift');
if ~strcmp(fingerprint.contractVersion, ...
            'formation-b4-v46-runtime-filter-input-fingerprint-v3') || ...
        fingerprint.caseOrdinal ~= permit.caseOrdinal || ...
        ~strcmp(fingerprint.caseId, permit.caseId) || ...
        ~strcmp(fingerprint.caseCanonicalSha256, ...
            permit.coreCaseCanonicalSha256) || ...
        ~strcmp(fingerprint.canonicalSha256, ...
            permit.runtimeFilterProjectionCanonicalSha256) || ...
        ~strcmp(computeCanonicalValueSha256( ...
            rmfield(fingerprint, 'canonicalSha256')), ...
            fingerprint.canonicalSha256) || ...
        fingerprint.targetTrajectoryRealizationPassedToFilter || ...
        fingerprint.groundTruthPassedToFilter || ...
        ~fingerprint.registeredBirthPriorRetained
    error('FormationB4V46DevelopmentPermit:RuntimeFingerprintDrift', ...
        'The filter-boundary input is not the accepted truth-free runtime.');
end

[expectedTrigger, triggerDetails] = ...
    buildFormationB4V46FixedTriggerConfig( ...
        permit.armId, permit.numberOfSensors);
if ~isequaln(runtimeRequest.triggerConfig, expectedTrigger) || ...
        ~strcmp(triggerDetails.canonicalSha256, ...
            permit.triggerConfigCanonicalSha256)
    error('FormationB4V46DevelopmentPermit:TriggerConfigDrift', ...
        'The V46 trigger config or policy identity changed.');
end
if ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model, 'formationB4V46RuntimeSourceEnvelope') || ...
        ~isstruct(model.formationB4V46RuntimeSourceEnvelope) || ...
        ~isscalar(model.formationB4V46RuntimeSourceEnvelope) || ...
        ~isfield(model.formationB4V46RuntimeSourceEnvelope, ...
            'caseOrdinal') || ...
        model.formationB4V46RuntimeSourceEnvelope.caseOrdinal ~= ...
            permit.caseOrdinal || ...
        ~isfield(model.formationB4V46RuntimeSourceEnvelope, ...
            'trackingOutcomeAuthorizationGranted') || ...
        model.formationB4V46RuntimeSourceEnvelope. ...
            trackingOutcomeAuthorizationGranted || ...
        containsForbiddenTargetTruth(model)
    error('FormationB4V46DevelopmentPermit:RuntimeModelDrift', ...
        'The V46 runtime model is malformed or contains target truth.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = 'registered-v46-development-arm-permit';
authorization.permitId = permit.id;
authorization.permitCanonicalSha256 = permit.permitCanonicalSha256;
authorization.capability = permit.capability;
authorization.action = permit.filterAction;
authorization.protocolId = permit.structuralProtocolId;
authorization.protocolCanonicalSha256 = ...
    permit.structuralProtocolCanonicalSha256;
authorization.caseId = permit.caseId;
authorization.caseCanonicalSha256 = ...
    permit.coreCaseCanonicalSha256;
authorization.caseOrdinal = permit.caseOrdinal;
authorization.presetName = permit.presetName;
authorization.seed = permit.seed;
authorization.sourceWindow = [1, permit.simulationLength];
authorization.armId = permit.armId;
authorization.armOrdinal = permit.armOrdinal;
authorization.methodSourceCommit = permit.executionSurfaceCommit;
authorization.methodPolicyConfigSha256 = ...
    permit.triggerConfigCanonicalSha256;
authorization.sourceTriggerFingerprintSha256 = ...
    permit.triggerConfigCanonicalSha256;
authorization.executableSourceCommit = permit.executionSurfaceCommit;
authorization.executableSourceManifestSha256 = ...
    permit.executionSurfaceManifestSha256;
authorization.executionHeadCommit = gitState.headCommit;
authorization.sourceInputFingerprintSha256 = ...
    permit.runtimeFilterProjectionCanonicalSha256;
authorization.runtimeAcceptanceRegistryCanonicalSha256 = ...
    permit.runtimeAcceptanceRegistryCanonicalSha256;
authorization.developmentPermitRegistryCanonicalSha256 = ...
    registry.canonicalSha256;
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = false;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function result = containsForbiddenTargetTruth(value)
result = false;
if iscell(value)
    for valueIdx = 1:numel(value)
        if containsForbiddenTargetTruth(value{valueIdx})
            result = true;
            return;
        end
    end
    return;
end
if ~isstruct(value)
    return;
end
names = fieldnames(value);
for valueIdx = 1:numel(value)
    for fieldIdx = 1:numel(names)
        lowerName = lower(names{fieldIdx});
        if any(strcmp(lowerName, { ...
                'groundtruth', 'groundtruthrfs', 'truth', ...
                'trackingtruth', 'trackingtruthrfs', ...
                'targettrajectories', ...
                'explicittargettrajectories'})) || ...
                ~isempty(strfind(lowerName, 'groundtruth')) || ... %#ok<STREMP>
                ~isempty(strfind(lowerName, 'targettrajector')) %#ok<STREMP>
            result = true;
            return;
        end
        if containsForbiddenTargetTruth(value(valueIdx).(names{fieldIdx}))
            result = true;
            return;
        end
    end
end
end

function assertExactFields(value, expectedFields, identifier)
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)), ...
            sort(reshape(expectedFields, [], 1)))
    error(identifier, 'A V46 development-gate field set changed.');
end
end
