function authorization = ...
        validateIndependentM24GatewayTeacherV252Execution( ...
            model, context, request)
% VALIDATEINDEPENDENTM24GATEWAYTEACHERV252EXECUTION Gate paired data.

protocol = getIndependentM24GatewayTeacherV252Protocol();
source = getCausalMinimumFormationBackboneV242Protocol();
action = getCausalGatewayEmbeddingV250Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'phase', 'anchorTime', 'candidateIndex', 'policyName', ...
    'developmentEvidenceOnly'};
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'independent-m24-gateway-teacher-v252-development') && ...
    strcmp(context.action, ...
        'filter-independent-m24-gateway-teacher-v252-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    isequal(context.developmentEvidenceOnly, true);

if validContext
    switch context.phase
        case 'reference-prefix'
            validContext = context.anchorTime == 0 && ...
                context.candidateIndex == 1 && ...
                context.measurementTimeCount == ...
                    max(protocol.anchorTimes) && ...
                strcmp(context.policyName, source.policyName) && ...
                strcmp(context.armId, source.armId);
        case 'candidate-reference'
            validContext = ...
                ismember(context.anchorTime, protocol.anchorTimes) && ...
                context.candidateIndex == 1 && ...
                context.measurementTimeCount == ...
                    context.anchorTime + protocol.horizonSteps - 1 && ...
                strcmp(context.policyName, source.policyName) && ...
                strcmp(context.armId, source.armId);
        case 'candidate-action'
            validContext = ...
                ismember(context.anchorTime, protocol.anchorTimes) && ...
                context.candidateIndex >= 2 && ...
                context.candidateIndex <= ...
                    protocol.maximumCandidateCount && ...
                context.candidateIndex == ...
                    round(context.candidateIndex) && ...
                context.measurementTimeCount == ...
                    context.anchorTime + protocol.horizonSteps - 1 && ...
                strcmp(context.policyName, action.policyName) && ...
                strcmp(context.armId, protocol.armId);
        otherwise
            validContext = false;
    end
end
if ~validContext
    error('IndependentM24GatewayTeacherV252:InvalidContext', ...
        'The V252 execution context is malformed.');
end

scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && isstruct(scenario.config) && ...
    isfield(scenario.config, 'numberOfSensors') && ...
    model.numberOfSensors == scenario.config.numberOfSensors && ...
    isfield(scenario.config, 'simulationLength') && ...
    context.measurementTimeCount == ...
        scenario.config.simulationLength && ...
    isfield(scenario.config, 'sceneStyle') && ...
    strcmp(scenario.config.sceneStyle, ...
        'temporal-coupled-formation-braid') && ...
    isfield(scenario.config, 'sceneCalibrationStatus') && ...
    strcmp(scenario.config.sceneCalibrationStatus, ...
        'development-only') && ...
    isfield(scenario.config, 'trackingOutcomeAuthorized') && ...
    isequal(scenario.config.trackingOutcomeAuthorized, false) && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('IndependentM24GatewayTeacherV252:InvalidRuntimeModel', ...
        'The V252 model is mismatched or contains target truth.');
end

config = request.triggerConfig;
formationCount = numel(unique(scenario.config.sensorGroupIds));
expectedMessages = model.numberOfSensors + 2 * (formationCount - 1);
requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == ...
        model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyPolicyPhysicalIdentityEnabled') && ...
    isequal(config.topologyPolicyPhysicalIdentityEnabled, true) && ...
    isfield(config, 'topologyDirectedEnabled') && ...
    isequal(config.topologyDirectedEnabled, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == expectedMessages && ...
    isfield(config, 'missingLabelFusionMode') && ...
    strcmp(config.missingLabelFusionMode, source.receiverMode) && ...
    isfield(config, 'eventPolicy') && ...
    strcmp(config.eventPolicy, 'alwaysHeavy') && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    ~logical(config.receiverSafeLabelFusionEnabled) && ...
    isfield(config, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled') && ...
    ~logical(config. ...
        receiverSafeFormationConditionedOnlinePolicyEnabled);
if ~validRequest
    error('IndependentM24GatewayTeacherV252:InvalidRuntimeRequest', ...
        'The V252 runtime request changed its paired boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'independent-m24-gateway-teacher-v252-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
if strcmp(context.phase, 'reference-prefix')
    authorization.sourceWindow = [1, context.measurementTimeCount];
else
    authorization.sourceWindow = ...
        [context.anchorTime, context.measurementTimeCount];
end
authorization.armId = context.armId;
authorization.armOrdinal = context.candidateIndex;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
