function authorization = validateOneShotPacketEpisodeV270Execution( ...
        model, context, request)
% VALIDATEONESHOTPACKETEPISODEV270EXECUTION Matched V269-derived gate.

protocol = getOneShotPacketEpisodeV270Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'continuationStartTime', 'policyName', 'developmentEvidenceOnly'};
config = getField(request, 'triggerConfig', struct());
valid = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'one-shot-packet-episode-v270-development') && ...
    strcmp(context.action, ...
        'filter-one-shot-packet-episode-v270-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    strcmp(context.armId, protocol.armId) && ...
    context.measurementTimeCount == protocol.continuationEndTime && ...
    context.continuationStartTime == protocol.continuationStartTime && ...
    strcmp(context.policyName, protocol.policyName) && ...
    isequal(context.developmentEvidenceOnly, true) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, ...
        'topologyPolicySourcePreservingLabelPacketOneShotPerEpisodeEnabled') && ...
    isequal(config. ...
        topologyPolicySourcePreservingLabelPacketOneShotPerEpisodeEnabled, ...
        true);
if ~valid
    error('OneShotPacketEpisodeV270:InvalidExecutionContext', ...
        'The V270 execution request changed its matched boundary.');
end

source = getExistenceMarginBeneficiaryV269Protocol();
sourceContext = context;
sourceContext.contractVersion = ...
    'existence-margin-beneficiary-v269-context-v1';
sourceContext.capability = ...
    'existence-margin-beneficiary-v269-development';
sourceContext.action = ...
    'filter-existence-margin-beneficiary-v269-development';
sourceContext.protocolId = source.id;
sourceContext.armId = source.armId;
sourceContext.policyName = source.policyName;
sourceRequest = request;
sourceRequest.triggerConfig.topologyPolicyName = source.policyName;
authorization = validateExistenceMarginBeneficiaryV269Execution( ...
    model, sourceContext, sourceRequest);
authorization.mode = 'one-shot-packet-episode-v270-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.armId = context.armId;
end

function value = getField(data, name, fallback)
if isstruct(data) && isfield(data, name)
    value = data.(name);
else
    value = fallback;
end
end
