function authorization = ...
        validateFormationBraidRoutingComparisonV241Execution( ...
            model, context, request)
% VALIDATEFORMATIONBRAIDROUTINGCOMPARISONV241EXECUTION Development gate.

protocol = getFormationBraidRoutingComparisonV241Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'policyName', 'developmentEvidenceOnly'};
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'formation-braid-routing-comparison-v241-development') && ...
    strcmp(context.action, ...
        ['filter-formation-braid-routing-comparison-', ...
         'v241-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    any(strcmp(context.armId, protocol.armIds)) && ...
    strcmp(context.policyName, expectedPolicy( ...
        context.armId, protocol)) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('FormationBraidRoutingV241:InvalidExecutionContext', ...
        'The V241 execution context is malformed.');
end

scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && isstruct(scenario.config) && ...
    isfield(scenario.config, 'numberOfSensors') && ...
    model.numberOfSensors == scenario.config.numberOfSensors && ...
    isfield(scenario.config, 'simulationLength') && ...
    context.measurementTimeCount == scenario.config.simulationLength && ...
    isfield(scenario.config, 'sceneStyle') && ...
    any(strcmp(scenario.config.sceneStyle, { ...
        'formation-braid', 'information-coupled-formation-braid'})) && ...
    isfield(scenario.config, 'sceneCalibrationStatus') && ...
    strcmp(scenario.config.sceneCalibrationStatus, 'development-only') && ...
    isfield(scenario.config, 'trackingOutcomeAuthorized') && ...
    isequal(scenario.config.trackingOutcomeAuthorized, false) && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('FormationBraidRoutingV241:InvalidRuntimeModel', ...
        'The V241 model is mismatched or contains target truth.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyPolicyPhysicalIdentityEnabled') && ...
    isequal(config.topologyPolicyPhysicalIdentityEnabled, true) && ...
    isfield(config, 'topologyDirectedEnabled') && ...
    isequal(config.topologyDirectedEnabled, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == ...
        protocol.directedInputsPerReceiver * model.numberOfSensors && ...
    isfield(config, 'missingLabelFusionMode') && ...
    strcmp(config.missingLabelFusionMode, protocol.receiverMode) && ...
    isfield(config, 'eventPolicy') && ...
    strcmp(config.eventPolicy, 'alwaysHeavy') && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    ~logical(config.receiverSafeLabelFusionEnabled) && ...
    isfield(config, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled') && ...
    ~logical(config. ...
        receiverSafeFormationConditionedOnlinePolicyEnabled);
if ~validRequest
    error('FormationBraidRoutingV241:InvalidRuntimeRequest', ...
        'The V241 runtime request changed its matched boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'formation-braid-routing-comparison-v241-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = context.armId;
authorization.armOrdinal = find(strcmp( ...
    context.armId, protocol.armIds), 1);
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function name = expectedPolicy(armId, protocol)
if strcmp(armId, protocol.staticDropoutArmId)
    name = protocol.staticDropoutPolicyName;
elseif strcmp(armId, protocol.alwaysReplanArmId)
    name = protocol.alwaysReplanPolicyName;
else
    name = protocol.causalPolicyName;
end
end
