function authorization = ...
        validateInitialDynamicRouteFreezeV237Execution( ...
            model, context, request)
% VALIDATEINITIALDYNAMICROUTEFREEZEV237EXECUTION Frozen-route gate.

protocol = getInitialDynamicRouteFreezeV237Protocol();
expectedFields = {'contractVersion', 'capability', 'action', ...
    'protocolId', 'presetName', 'seed', 'splitName', 'armId', ...
    'measurementTimeCount', 'policyName', 'developmentEvidenceOnly'};
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'initial-dynamic-route-freeze-v237-development') && ...
    strcmp(context.action, ...
        'filter-initial-dynamic-route-freeze-v237-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    strcmp(context.splitName, protocol.splitName) && ...
    strcmp(context.armId, protocol.armId) && ...
    strcmp(context.policyName, protocol.policyName) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('InitialDynamicRouteFreezeV237:InvalidExecutionContext', ...
        'The V237 execution context is malformed.');
end

scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && isstruct(scenario.config) && ...
    isfield(scenario.config, 'simulationLength') && ...
    context.measurementTimeCount == scenario.config.simulationLength && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('InitialDynamicRouteFreezeV237:InvalidRuntimeModel', ...
        'The V237 runtime model is mismatched or contains target truth.');
end

requiredRequestFields = {'contractVersion', 'operation', ...
    'measurementTimeCount', 'sensorTrajectoryTimeCounts', ...
    'triggerConfig'};
config = request.triggerConfig;
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, protocol.policyName) && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyPolicyPhysicalIdentityEnabled') && ...
    isequal(config.topologyPolicyPhysicalIdentityEnabled, true) && ...
    isfield(config, 'topologyDirectedEnabled') && ...
    isequal(config.topologyDirectedEnabled, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == ...
        protocol.directedInputsPerReceiver * model.numberOfSensors && ...
    isfield(config, 'missingLabelFusionMode') && ...
    strcmp(config.missingLabelFusionMode, protocol.receiverMode) && ...
    isfield(config, 'eventPolicy') && ...
    strcmp(config.eventPolicy, 'alwaysHeavy') && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    ~logical(config.receiverSafeLabelFusionEnabled) && ...
    isfield(config, ...
        'receiverSafeFormationConditionedOnlinePolicyEnabled') && ...
    ~logical(config. ...
        receiverSafeFormationConditionedOnlinePolicyEnabled);
if ~validRequest
    error('InitialDynamicRouteFreezeV237:InvalidRuntimeRequest', ...
        'The V237 run changed its matched payload boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'initial-dynamic-route-freeze-v237-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = protocol.armId;
authorization.armOrdinal = 1;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
