function authorization = ...
        validateTemporallyBalancedMinimumBackboneV272Execution( ...
            model, context, request)
% VALIDATETEMPORALLYBALANCEDMINIMUMBACKBONEV272EXECUTION Matched dev gate.

protocol = getTemporallyBalancedMinimumBackboneV272Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'sourceWindowStartTime', 'policyName', 'developmentEvidenceOnly'};
valid = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'temporally-balanced-minimum-backbone-v272-development') && ...
    strcmp(context.action, ...
        ['filter-temporally-balanced-minimum-backbone-', ...
         'v272-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    ismember(context.presetName, protocol.allowedPresets) && ...
    ismember(context.seed, protocol.allowedSeeds) && ...
    strcmp(context.armId, protocol.armId) && ...
    context.sourceWindowStartTime >= 1 && ...
    context.sourceWindowStartTime <= context.measurementTimeCount && ...
    strcmp(context.policyName, protocol.policyName) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~valid
    error('TemporallyBalancedBackboneV272:InvalidExecutionContext', ...
        'The V272 execution context is malformed.');
end

config = request.triggerConfig;
v272ConfigPassed = isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyTemporalGatewayBalanceEnabled') && ...
    isequal(config.topologyPolicyTemporalGatewayBalanceEnabled, true) && ...
    isfield(config, 'topologyPolicyTemporalGatewayHistoryDepth') && ...
    config.topologyPolicyTemporalGatewayHistoryDepth == ...
        protocol.historyDepth && ...
    isfield(config, ...
        'topologyPolicyTemporalGatewayMinimumReliabilityRatio') && ...
    abs(config. ...
        topologyPolicyTemporalGatewayMinimumReliabilityRatio - ...
        protocol.minimumReliabilityRatio) <= 1e-12 && ...
    isfield(config, ...
        'topologyPolicyTemporalGatewayMaximumReliabilityDrop') && ...
    abs(config.topologyPolicyTemporalGatewayMaximumReliabilityDrop - ...
        protocol.maximumReliabilityDrop) <= 1e-12 && ...
    isfield(config, ...
        'topologyPolicyTemporalGatewayBalanceSenderRoles') && ...
    isequal(config.topologyPolicyTemporalGatewayBalanceSenderRoles, ...
        protocol.balanceSenderRoles) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= protocol.historyDepth;
if context.sourceWindowStartTime > 1
    v272ConfigPassed = v272ConfigPassed && ...
        isfield(config, 'filterInitialLocalPosteriorBySensor') && ...
        ~isempty(config.filterInitialLocalPosteriorBySensor) && ...
        isfield(config, 'filterInitialLocalPosteriorTime') && ...
        config.filterInitialLocalPosteriorTime == ...
            context.sourceWindowStartTime && ...
        isfield(config, 'filterInitialPreviousAdjacencyHistory') && ...
        ~isempty(config.filterInitialPreviousAdjacencyHistory);
end
if ~v272ConfigPassed
    error('TemporallyBalancedBackboneV272:InvalidRuntimeRequest', ...
        'The V272 temporal route contract changed at runtime.');
end

% Reuse V242's estimator, payload, weight and minimum-message boundary.
sourceContext = ...
    buildCausalMinimumFormationBackboneV242ExecutionContext( ...
        context.presetName, context.seed, context.measurementTimeCount);
sourceRequest = request;
sourceProtocol = getCausalMinimumFormationBackboneV242Protocol();
sourceRequest.triggerConfig.topologyPolicyName = sourceProtocol.policyName;
authorization = validateCausalMinimumFormationBackboneV242Execution( ...
    model, sourceContext, sourceRequest);
authorization.mode = ...
    'temporally-balanced-minimum-backbone-v272-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.sourceWindow = [context.sourceWindowStartTime, ...
    context.measurementTimeCount];
authorization.armId = protocol.armId;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
