function authorization = ...
    validateInfluenceAwareDecisionBreadthV66ReferenceExecution( ...
        model, context, request)
% VALIDATEINFLUENCEAWAREDECISIONBREADTHV66REFERENCEEXECUTION Source gate.

expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', ...
    'measurementTimeCount', 'policyName', 'developmentEvidenceOnly'};
protocol = ...
    getInfluenceAwareDecisionBreadthV66SceneDiscoveryProtocol();
validContext = isequal(sort(fieldnames(context)), ...
        sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'influence-aware-decision-breadth-reference-development') && ...
    strcmp(context.action, ...
        ['filter-influence-aware-decision-breadth-', ...
         'reference-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.phase, 'reference-cache') && ...
    strcmp(context.presetName, protocol.presets{1}) && ...
    context.seed == protocol.allSeeds && ...
    context.currentTime == max(protocol.snapshotTimes) && ...
    context.measurementTimeCount == context.currentTime && ...
    strcmp(context.policyName, protocol.referencePolicyName) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('InfluenceAwareSceneV66:InvalidExecutionContext', ...
        'The V66 relay reference context is malformed.');
end

validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    model.numberOfSensors == protocol.expectedNodeCount && ...
    isfield(model, 'dynamicTopologyScenario') && ...
    isstruct(model.dynamicTopologyScenario) && ...
    isscalar(model.dynamicTopologyScenario) && ...
    isfield(model.dynamicTopologyScenario, 'presetName') && ...
    strcmp(model.dynamicTopologyScenario.presetName, ...
        context.presetName) && ...
    isfield(model.dynamicTopologyScenario, 'seed') && ...
    model.dynamicTopologyScenario.seed == context.seed && ...
    isfield(model.dynamicTopologyScenario, 'config') && ...
    model.dynamicTopologyScenario.config.formationCount == ...
        protocol.expectedFormationCount && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(model.dynamicTopologyScenario, 'targetTrajectories');
if ~validModel
    error('InfluenceAwareSceneV66:InvalidRuntimeModel', ...
        'The V66 relay reference model is not registered.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
validRequest = isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == ...
        protocol.expectedNodeCount && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(request.triggerConfig) && ...
    isfield(request.triggerConfig, 'topologyPolicyName') && ...
    strcmp(request.triggerConfig.topologyPolicyName, ...
        protocol.referencePolicyName) && ...
    isfield(request.triggerConfig, 'topologyPolicyHistoryDepth') && ...
    request.triggerConfig.topologyPolicyHistoryDepth >= 2;
if ~validRequest
    error('InfluenceAwareSceneV66:InvalidRuntimeRequest', ...
        'The V66 relay reference request changed its boundary.');
end

authorization = buildAuthorization();
authorization.mode = ...
    'influence-aware-decision-breadth-reference-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = context.policyName;
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = false;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end

function authorization = buildAuthorization()
authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = 'legacy-compatible';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = 'legacy-filter-execution';
authorization.action = 'filter-execution';
authorization.protocolId = '';
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = '';
authorization.seed = NaN;
authorization.sourceWindow = zeros(1, 0);
authorization.armId = '';
authorization.armOrdinal = NaN;
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = false;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = false;
end
