function authorization = validateFormationIsolatedDualPayloadV136Execution( ...
        model, context, request)
% VALIDATEFORMATIONISOLATEDDUALPAYLOADV136EXECUTION Enforce upper bound.

protocol = getFormationIsolatedDualPayloadV136Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'scheduleEnabled', 'lineageRelayEnabled', ...
    'intraFormationWorkingPayloadEnabled', ...
    'onlineReselectionEnabled', 'developmentEvidenceOnly'};
if ~isstruct(context) || ~isscalar(context) || ...
        ~isequal(sort(fieldnames(context)), sort(requiredContext(:))) || ...
        ~strcmp(context.capability, ...
            'formation-isolated-dual-payload-v136-development') || ...
        ~strcmp(context.action, ...
            'filter-formation-isolated-dual-payload-v136-development') || ...
        ~strcmp(context.protocolId, protocol.id) || ...
        ~strcmp(context.policyName, protocol.outcomePolicyName) || ...
        ~ismember(context.phase, {'reference', 'candidate'}) || ...
        ~ismember(context.referenceCarrierMode, ...
            protocol.referenceCarrierModes) || ...
        ~islogical(context.scheduleEnabled) || ...
        ~islogical(context.lineageRelayEnabled) || ...
        ~islogical(context.intraFormationWorkingPayloadEnabled) || ...
        context.scheduleEnabled ~= strcmp(context.phase, 'candidate') || ...
        context.lineageRelayEnabled ~= strcmp(context.phase, 'candidate') || ...
        context.intraFormationWorkingPayloadEnabled ~= ...
            strcmp(context.phase, 'candidate') || ...
        ~isequal(context.onlineReselectionEnabled, false) || ...
        ~isequal(context.developmentEvidenceOnly, true)
    error('FormationDualPayloadV136:InvalidExecutionContext', ...
        'The V136 execution context is malformed.');
end
caseInfo = resolveCase(protocol, context.presetName);
expectedAnchor = ...
    resolveSetTrustSequenceV134PilotAnchor(caseInfo, protocol);
actionSpec = validateSetTrustSequenceActionV134( ...
    context.actionSpec, 'candidate-continuation', caseInfo, protocol);
validModel = ismember(context.seed, protocol.developmentSeeds) && ...
    context.currentTime == expectedAnchor && ...
    context.horizonSteps == caseInfo.horizonSteps && ...
    isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    model.numberOfSensors == caseInfo.expectedNodeCount && ...
    isfield(model, 'dynamicTopologyScenario') && ...
    isstruct(model.dynamicTopologyScenario) && ...
    isfield(model.dynamicTopologyScenario, 'presetName') && ...
    strcmp(model.dynamicTopologyScenario.presetName, context.presetName) && ...
    isfield(model.dynamicTopologyScenario, 'seed') && ...
    model.dynamicTopologyScenario.seed == context.seed && ...
    isfield(model.dynamicTopologyScenario, 'config') && ...
    model.dynamicTopologyScenario.config.formationCount == ...
        caseInfo.expectedFormationCount && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(model.dynamicTopologyScenario, 'targetTrajectories') && ...
    ~isfield(model.dynamicTopologyScenario, 'target');
if ~validModel
    error('FormationDualPayloadV136:InvalidRuntimeModel', ...
        'The V136 runtime model is outside the development screen.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isstruct(request) && isscalar(request) && ...
    isequal(sort(fieldnames(request)), sort(requiredRequest(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    numel(request.sensorTrajectoryTimeCounts) == ...
        caseInfo.expectedNodeCount && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && isscalar(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'v135ReferenceCarrierMode') && ...
    strcmp(config.v135ReferenceCarrierMode, ...
        context.referenceCarrierMode) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    logical(config.topologyPolicyObservableContextOnly) && ...
    isfield(config, 'topologyPolicySensorObservationEnabled') && ...
    logical(config.topologyPolicySensorObservationEnabled) && ...
    isfield(config, 'receiverSafeLabelFusionEnabled') && ...
    logical(config.receiverSafeLabelFusionEnabled) == ...
        context.scheduleEnabled && ...
    isfield(config, 'lineageIsolatedRelayEnabled') && ...
    logical(config.lineageIsolatedRelayEnabled) == ...
        context.lineageRelayEnabled && ...
    isfield(config, 'lineageRelayIntraFormationWorkingPayloadEnabled') && ...
    logical(config.lineageRelayIntraFormationWorkingPayloadEnabled) == ...
        context.intraFormationWorkingPayloadEnabled && ...
    isfield(config, 'fusionWeightMode') && ...
    strcmpi(config.fusionWeightMode, protocol.nominalKlaWeightMode) && ...
    isfield(config, 'useStaleNeighborCache') && ...
    ~logical(config.useStaleNeighborCache) && ...
    isfield(config, 'missingNeighborWeightMode') && ...
    strcmpi(config.missingNeighborWeightMode, ...
        protocol.primaryMissingNeighborWeightMode);
if validRequest && strcmp(context.phase, 'candidate')
    returnTimes = context.currentTime + (0:(context.horizonSteps - 1));
    validRequest = ...
        strcmp(config.receiverSafeLabelFusionMode, ...
            'formation-supported-label-plan') && ...
        isequal(reshape(config.receiverSafeExternalActiveTimes, 1, []), ...
            returnTimes) && ...
        isequal(reshape(config.receiverSafeFormationConditionedTimes, ...
            1, []), returnTimes) && ...
        isequal(config.receiverSafeFormationConditionedSchedule, ...
            actionSpec.formationIdsByTime) && ...
        isequal(config. ...
            receiverSafeFormationConditionedTrustFactorsByTime, ...
            actionSpec.trustFactorsByTime) && ...
        strcmp(config.receiverSafeFormationConditionedPayloadMode, ...
            protocol.runtimePayloadMode) && ...
        ~logical(config. ...
            receiverSafeFormationConditionedOnlinePolicyEnabled);
end
if ~validRequest
    error('FormationDualPayloadV136:InvalidRuntimeRequest', ...
        'The V136 runtime request changed the registered upper bound.');
end

authorization = struct( ...
    'contractVersion', ...
        'dynamic-topology-filter-execution-authorization-v1', ...
    'mode', 'formation-isolated-dual-payload-v136-development', ...
    'permitId', '', 'permitCanonicalSha256', '', ...
    'capability', context.capability, 'action', context.action, ...
    'protocolId', protocol.id, 'protocolCanonicalSha256', '', ...
    'caseId', '', 'caseCanonicalSha256', '', ...
    'presetName', context.presetName, 'seed', context.seed, ...
    'sourceWindow', [1, context.measurementTimeCount], ...
    'armId', context.phase, 'armOrdinal', NaN, ...
    'methodSourceCommit', '', 'methodPolicyConfigSha256', '', ...
    'sourceTriggerFingerprintSha256', '', ...
    'executableSourceCommit', '', ...
    'executableSourceManifestSha256', '', ...
    'executionHeadCommit', '', 'sourceInputFingerprintSha256', '', ...
    'stateEstimateOutputAuthorized', true, ...
    'trackingOutcomeScoringAuthorized', true, ...
    'groundTruthAccessAuthorized', false, ...
    'futureOutcomeAccessAuthorized', false, ...
    'validationClaimAllowed', false, ...
    'developmentEvidenceOnly', true);
end

function caseInfo = resolveCase(protocol, presetName)
caseIdx = find(strcmp({protocol.scaleCases.presetName}, presetName), 1);
if isempty(caseIdx)
    error('FormationDualPayloadV136:InvalidPreset', ...
        'The preset is outside the V136 screen.');
end
caseInfo = protocol.scaleCases(caseIdx);
end
