function authorization = ...
    validateRepeatedMultiGatewayHandoverV89Execution( ...
        model, context, request)
% VALIDATEREPEATEDMULTIGATEWAYHANDOVERV89EXECUTION Paired outcome gate.

protocol = getRepeatedMultiGatewayHandoverV89Protocol();
expectedFields = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'presetName', 'seed', 'armId', 'measurementTimeCount', ...
    'policyName', 'developmentEvidenceOnly'};
validContext = isequal(sort(fieldnames(context)), ...
        sort(expectedFields(:))) && ...
    strcmp(context.capability, ...
        'repeated-multi-gateway-handover-full-episode-development') && ...
    strcmp(context.action, ...
        ['filter-repeated-multi-gateway-handover-', ...
         'full-episode-development']) && ...
    strcmp(context.protocolId, protocol.id) && ...
    any(strcmp(context.presetName, protocol.presets)) && ...
    context.seed == protocol.allSeeds && ...
    any(strcmp(context.armId, {protocol.referenceArmId, ...
        protocol.candidateArmId})) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('RepeatedMultiGatewayV89:InvalidExecutionContext', ...
        'The V89 full-episode execution context is malformed.');
end

presetIdx = find(strcmp(context.presetName, protocol.presets), 1);
scenario = struct();
if isstruct(model) && isscalar(model) && ...
        isfield(model, 'dynamicTopologyScenario')
    scenario = model.dynamicTopologyScenario;
end
validModel = isstruct(model) && isscalar(model) && ...
    isfield(model, 'numberOfSensors') && ...
    model.numberOfSensors == protocol.expectedNodeCounts(presetIdx) && ...
    isstruct(scenario) && isscalar(scenario) && ...
    isfield(scenario, 'presetName') && ...
    strcmp(scenario.presetName, context.presetName) && ...
    isfield(scenario, 'seed') && scenario.seed == context.seed && ...
    isfield(scenario, 'config') && ...
    scenario.config.formationCount == ...
        protocol.expectedFormationCounts(presetIdx) && ...
    isfield(scenario.config, 'sceneStyle') && ...
    strcmp(scenario.config.sceneStyle, 'braided-handover') && ...
    ~isfield(model, 'explicitTargetTrajectories') && ...
    ~isfield(scenario, 'targetTrajectories') && ...
    ~isfield(scenario, 'target');
if ~validModel
    error('RepeatedMultiGatewayV89:InvalidRuntimeModel', ...
        'The V89 runtime model is not a registered truth-free scene.');
end

requiredRequestFields = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
config = request.triggerConfig;
validRequest = isequal(sort(fieldnames(request)), ...
        sort(requiredRequestFields(:))) && ...
    strcmp(request.operation, 'filter-execution') && ...
    request.measurementTimeCount == context.measurementTimeCount && ...
    context.measurementTimeCount >= protocol.activationEndTime && ...
    numel(request.sensorTrajectoryTimeCounts) == model.numberOfSensors && ...
    all(request.sensorTrajectoryTimeCounts == ...
        context.measurementTimeCount) && ...
    isstruct(config) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, context.policyName) && ...
    isfield(config, 'topologyPolicyHistoryDepth') && ...
    config.topologyPolicyHistoryDepth >= 2 && ...
    isfield(config, 'topologyPolicyObservableContextOnly') && ...
    isequal(config.topologyPolicyObservableContextOnly, true) && ...
    isfield(config, 'topologyDirectedMessageBudget') && ...
    config.topologyDirectedMessageBudget == 2 * model.numberOfSensors;
if ~validRequest
    error('RepeatedMultiGatewayV89:InvalidRuntimeRequest', ...
        'The V89 paired runtime request changed its frozen boundary.');
end

authorization = struct();
authorization.contractVersion = ...
    'dynamic-topology-filter-execution-authorization-v1';
authorization.mode = ...
    'repeated-multi-gateway-handover-full-episode-development';
authorization.permitId = '';
authorization.permitCanonicalSha256 = '';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
authorization.protocolCanonicalSha256 = '';
authorization.caseId = '';
authorization.caseCanonicalSha256 = '';
authorization.presetName = context.presetName;
authorization.seed = context.seed;
authorization.sourceWindow = [1, context.measurementTimeCount];
authorization.armId = context.armId;
authorization.armOrdinal = 1 + ...
    double(strcmp(context.armId, protocol.candidateArmId));
authorization.methodSourceCommit = '';
authorization.methodPolicyConfigSha256 = '';
authorization.sourceTriggerFingerprintSha256 = '';
authorization.executableSourceCommit = '';
authorization.executableSourceManifestSha256 = '';
authorization.executionHeadCommit = '';
authorization.sourceInputFingerprintSha256 = '';
authorization.stateEstimateOutputAuthorized = true;
authorization.trackingOutcomeScoringAuthorized = true;
authorization.groundTruthAccessAuthorized = false;
authorization.futureOutcomeAccessAuthorized = false;
authorization.validationClaimAllowed = false;
authorization.developmentEvidenceOnly = true;
end
