function authorization = validateCounterfactualEdgeRoleV146Execution( ...
        model, context, request)
% VALIDATECOUNTERFACTUALEDGEROLEV146EXECUTION Enforce one frozen bank arm.

protocol = getCounterfactualEdgeRoleV146Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'roleActionSpec', 'scheduleEnabled', ...
    'lineageRelayEnabled', 'intraFormationWorkingPayloadEnabled', ...
    'roleMultiplexingEnabled', 'counterfactualRoleBankEnabled', ...
    'rolePeriodPages', 'roleReferencePhaseOffset', 'roleAnchorTime', ...
    'singlePayloadWireEnforced', 'postFusionLabelReadoutEnabled', ...
    'predictiveEvidenceReadoutOnlyEnabled', ...
    'workingStateMutationAllowed', ...
    'exactStaticStateFallbackClaimAllowed', ...
    'onlineReselectionEnabled', 'developmentEvidenceOnly'};
enabled = false;
if isstruct(context) && isscalar(context) && isfield(context, 'phase')
    enabled = strcmp(context.phase, 'candidate');
end
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(requiredContext(:))) && ...
    strcmp(context.capability, ...
        'counterfactual-edge-role-v146-development') && ...
    strcmp(context.action, ...
        'filter-counterfactual-edge-role-v146-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    ismember(context.phase, {'reference', 'candidate'}) && ...
    ismember(context.referenceCarrierMode, protocol.referenceCarrierModes) && ...
    islogical(context.scheduleEnabled) && ...
    islogical(context.lineageRelayEnabled) && ...
    islogical(context.intraFormationWorkingPayloadEnabled) && ...
    islogical(context.roleMultiplexingEnabled) && ...
    islogical(context.counterfactualRoleBankEnabled) && ...
    islogical(context.postFusionLabelReadoutEnabled) && ...
    islogical(context.predictiveEvidenceReadoutOnlyEnabled) && ...
    context.scheduleEnabled == enabled && ...
    context.lineageRelayEnabled == enabled && ...
    context.intraFormationWorkingPayloadEnabled == enabled && ...
    context.roleMultiplexingEnabled == enabled && ...
    context.counterfactualRoleBankEnabled == enabled && ...
    context.postFusionLabelReadoutEnabled == enabled && ...
    context.predictiveEvidenceReadoutOnlyEnabled == enabled && ...
    context.rolePeriodPages == protocol.roleSchedule.periodPages && ...
    context.roleReferencePhaseOffset == ...
        protocol.roleSchedule.referencePhaseOffset && ...
    context.roleAnchorTime == context.currentTime && ...
    isequal(context.singlePayloadWireEnforced, true) && ...
    isequal(context.workingStateMutationAllowed, false) && ...
    isequal(context.exactStaticStateFallbackClaimAllowed, false) && ...
    isequal(context.onlineReselectionEnabled, false) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('CounterfactualEdgeRoleV146:InvalidExecutionContext', ...
        'The V146 execution context is malformed.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isstruct(request) || ~isscalar(request) || ...
        ~isequal(sort(fieldnames(request)), sort(requiredRequest(:))) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isscalar(request.triggerConfig)
    error('CounterfactualEdgeRoleV146:InvalidRuntimeRequest', ...
        'The V146 runtime request is malformed.');
end
groups = resolveGroups(model);
expectedAction = resolveCounterfactualEdgeRoleV146Action( ...
    protocol.roleActionBank.actions(context.roleActionSpec.index), ...
    numel(unique(groups, 'stable')));
formationOrder = reshape(context.actionSpec.formationIdsByTime{1}, 1, []);
config = request.triggerConfig;
validRole = isequaln(context.roleActionSpec, expectedAction) && ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, protocol.outcomePolicyName) && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedCounterfactualBankEnabled') && ...
    logical(config. ...
        lineageRelayRoleMultiplexedCounterfactualBankEnabled) == enabled && ...
    isfield(config, 'lineageRelayRoleMultiplexedFormationOrder') && ...
    isequal(reshape(config. ...
        lineageRelayRoleMultiplexedFormationOrder, 1, []), ...
        formationOrder) && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedSelectedFormationRanks') && ...
    isequal(reshape(config. ...
        lineageRelayRoleMultiplexedSelectedFormationRanks, 1, []), ...
        expectedAction.selectedFormationRanks) && ...
    isfield(config, 'lineageRelayRoleMultiplexedWorkingPageOffsets') && ...
    isequal(reshape(config. ...
        lineageRelayRoleMultiplexedWorkingPageOffsets, 1, []), ...
        expectedAction.workingPageOffsets) && ...
    (~isfield(config, ...
        'lineageRelayRoleMultiplexedProtectionLoadGateEnabled') || ...
     ~logical(config. ...
        lineageRelayRoleMultiplexedProtectionLoadGateEnabled)) && ...
    (~isfield(config, ...
        'lineageRelayRoleMultiplexedReferenceLatchEnabled') || ...
     ~logical(config.lineageRelayRoleMultiplexedReferenceLatchEnabled));
if ~validRole
    error('CounterfactualEdgeRoleV146:InvalidRuntimeRequest', ...
        'The V146 request changed the frozen edge-role vector.');
end

% Reuse the complete V144 scene, action, payload, and output boundary.
baseContext = buildReferenceAnchoredBurstRoleScheduleV144ExecutionContext( ...
    context.presetName, context.seed, context.phase, ...
    context.currentTime, context.referenceCarrierMode, context.actionSpec);
baseRequest = request;
baseProtocol = getReferenceAnchoredBurstRoleScheduleV144Protocol();
baseRequest.triggerConfig.topologyPolicyName = ...
    baseProtocol.outcomePolicyName;
baseRequest.triggerConfig. ...
    lineageRelayRoleMultiplexedCounterfactualBankEnabled = false;
try
    authorization = ...
        validateReferenceAnchoredBurstRoleScheduleV144Execution( ...
            model, baseContext, baseRequest);
catch errorInfo
    error('CounterfactualEdgeRoleV146:InvalidRuntimeRequest', ...
        'The V146 request failed the inherited V144 boundary: %s', ...
        errorInfo.message);
end
authorization.mode = 'counterfactual-edge-role-v146-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
end

function groups = resolveGroups(model)
if ~isstruct(model) || ~isfield(model, 'dynamicTopologyScenario') || ...
        ~isstruct(model.dynamicTopologyScenario) || ...
        ~isfield(model.dynamicTopologyScenario, 'config') || ...
        ~isfield(model.dynamicTopologyScenario.config, 'sensorGroupIds')
    error('CounterfactualEdgeRoleV146:InvalidRuntimeRequest', ...
        'The V146 runtime requires registered formation groups.');
end
groups = reshape( ...
    model.dynamicTopologyScenario.config.sensorGroupIds, 1, []);
if isempty(groups) || any(~isfinite(groups))
    error('CounterfactualEdgeRoleV146:InvalidRuntimeRequest', ...
        'The V146 formation groups are malformed.');
end
end
