function state = ...
    validateFormationBackboneBundleM24ExecutableGitState( ...
        expectedExecutableCommit)
% VALIDATEFORMATIONBACKBONEBUNDLEM24EXECUTABLEGITSTATE Clean ancestry gate.

if ~ischar(expectedExecutableCommit) || ...
        isempty(regexp(expectedExecutableCommit, ...
            '^[0-9a-f]{40}$', 'once'))
    error('FormationBundleSourcePermit:ExecutableCommitDrift', ...
        'The frozen executable-source commit is malformed.');
end
repoRoot = fileparts(fileparts(mfilename('fullpath')));
[status, headText] = system(sprintf( ...
    'git -C %s rev-parse HEAD', shellQuote(repoRoot)));
if status ~= 0
    error('FormationBundleSourcePermit:GitStateFailed', ...
        'The current Git commit could not be resolved.');
end
headCommit = strtrim(headText);
[workingStatus, ~] = system(sprintf( ...
    'git -C %s diff --quiet --', shellQuote(repoRoot)));
[indexStatus, ~] = system(sprintf( ...
    'git -C %s diff --cached --quiet --', shellQuote(repoRoot)));
if workingStatus > 1 || indexStatus > 1
    error('FormationBundleSourcePermit:GitStateFailed', ...
        'Tracked Git cleanliness could not be determined.');
end
if workingStatus ~= 0 || indexStatus ~= 0
    error('FormationBundleSourcePermit:TrackedSourceDirty', ...
        'Tracked files must be clean for source execution.');
end
[ancestorStatus, ~] = system(sprintf( ...
    'git -C %s merge-base --is-ancestor %s HEAD', ...
    shellQuote(repoRoot), expectedExecutableCommit));
if ancestorStatus ~= 0
    error('FormationBundleSourcePermit:ExecutableCommitDrift', ...
        ['The frozen executable-source commit is not an ancestor ', ...
         'of the current clean checkout.']);
end
state = struct();
state.contractVersion = ...
    'formation-backbone-bundle-m24-executable-git-state-v1';
state.repoRoot = repoRoot;
state.headCommit = headCommit;
state.expectedExecutableCommit = expectedExecutableCommit;
state.expectedCommitIsAncestor = true;
state.trackedWorktreeClean = true;
end

function value = shellQuote(value)
value = ['''', strrep(value, '''', '''"''"'''), ''''];
end
