function details = validateRollingSafeRolloutArtifactForScreen( ...
        model, currentSeed, evidenceSplit, ...
        allowRejectedArtifact, registry)
% VALIDATEROLLINGSAFEROLLOUTARTIFACTFORSCREEN Enforce evidence split.

if nargin < 4 || isempty(allowRejectedArtifact)
    allowRejectedArtifact = false;
end
if nargin < 5 || isempty(registry)
    registry = getRegisteredRollingSafeRolloutArtifact();
end
protocol = getRollingSafeRolloutProtocol();
evidenceSplit = lower(strrep(char(evidenceSplit), '_', '-'));
if ~ismember(evidenceSplit, ...
        {'development', 'heldout-validation'})
    error('Unknown rolling-safe rollout evidence split.');
end
required = { ...
    'protocolId', 'trainingSeeds', 'auditSeeds', ...
    'designSeeds', 'datasetSeeds', ...
    'datasetGenerationGitCommit', ...
    'datasetGenerationResearchWorktreeDirty', ...
    'payloadToleranceFraction', ...
    'filterSeedOffset', 'behaviorCacheSha256', ...
    'acceptedForClosedLoopScreen', 'frozen', ...
    'acceptanceThresholds', 'imitationGateMetrics', ...
    'artifactId', 'datasetSha256', ...
    'featureContractSha256', 'trainingConfigSha256', ...
    'trainingGitCommit', 'trainingWorktreeDirty'};
if ~isstruct(model) || ~all(isfield(model, required)) || ...
        ~isscalar(model.frozen) || ~logical(model.frozen) || ...
        ~isscalar(model.acceptedForClosedLoopScreen) || ...
        ~isSha256(model.artifactId) || ...
        ~isSha256(model.datasetSha256) || ...
        ~isSha256(model.featureContractSha256) || ...
        ~isSha256(model.trainingConfigSha256) || ...
        isempty(regexp(char(model.trainingGitCommit), ...
            '^[0-9a-f]{40}$', 'once')) || ...
        isempty(regexp(char(model.datasetGenerationGitCommit), ...
            '^[0-9a-f]{40}$', 'once')) || ...
        ~isscalar(model.trainingWorktreeDirty) || ...
        ~isscalar(model.datasetGenerationResearchWorktreeDirty) || ...
        ~strcmp(model.protocolId, protocol.id) || ...
        ~isequal(reshape(model.trainingSeeds, 1, []), ...
            protocol.trainingSeeds) || ...
        ~isequal(reshape(model.auditSeeds, 1, []), ...
            protocol.auditSeeds) || ...
        ~isequal(reshape(model.designSeeds, 1, []), ...
            protocol.designSeeds) || ...
        ~isequal(reshape(model.datasetSeeds, 1, []), ...
            protocol.datasetSeeds) || ...
        ~sameScalar(model.payloadToleranceFraction, ...
            protocol.payloadToleranceFraction) || ...
        model.filterSeedOffset ~= ...
            protocol.filterSeedOffset || ...
        ~isequal(reshape(model.behaviorCacheSha256, 1, []), ...
            reshape(protocol.behaviorCacheSha256, 1, []))
    error('Rolling-safe rollout artifact split contract is invalid.');
end
thresholds = model.acceptanceThresholds;
metrics = model.imitationGateMetrics;
if ~all(isfield(thresholds, { ...
        'minimumSeedProjectedEdgeF1', ...
        'minimumMeanProjectedEdgeF1', ...
        'minimumBlockProjectedEdgeF1', ...
        'minimumSeedProjectedEdgeRecall', ...
        'minimumMeanProjectedEdgeRecall', ...
        'minimumSeedProjectedExactGraphFraction', ...
        'minimumMeanProjectedExactGraphFraction', ...
        'minimumZeroEdgeExactFraction', ...
        'minimumSingleEdgeExactFraction', ...
        'minimumZeroEdgeBlockCount', ...
        'minimumSingleEdgeBlockCount'})) || ...
        ~all(isfield(metrics, { ...
        'minimumHeldoutSeedProjectedEdgeF1', ...
        'meanHeldoutProjectedEdgeF1', ...
        'minimumHeldoutBlockProjectedEdgeF1', ...
        'minimumHeldoutSeedProjectedEdgeRecall', ...
        'meanHeldoutProjectedEdgeRecall', ...
        'minimumHeldoutProjectedExactGraphFraction', ...
        'meanHeldoutProjectedExactGraphFraction', ...
        'minimumHeldoutZeroEdgeExactFraction', ...
        'minimumHeldoutSingleEdgeExactFraction', ...
        'heldoutZeroEdgeBlockCount', ...
        'heldoutSingleEdgeBlockCount'})) || ...
        ~thresholdsMatchProtocol(thresholds, protocol)
    error('Rolling-safe rollout artifact gate contract is invalid.');
end
expectedAcceptance = ...
    metrics.minimumHeldoutSeedProjectedEdgeF1 >= ...
        thresholds.minimumSeedProjectedEdgeF1 - 1e-12 && ...
    metrics.meanHeldoutProjectedEdgeF1 >= ...
        thresholds.minimumMeanProjectedEdgeF1 - 1e-12 && ...
    metrics.minimumHeldoutBlockProjectedEdgeF1 >= ...
        thresholds.minimumBlockProjectedEdgeF1 - 1e-12 && ...
    metrics.minimumHeldoutSeedProjectedEdgeRecall >= ...
        thresholds.minimumSeedProjectedEdgeRecall - 1e-12 && ...
    metrics.meanHeldoutProjectedEdgeRecall >= ...
        thresholds.minimumMeanProjectedEdgeRecall - 1e-12 && ...
    metrics.minimumHeldoutProjectedExactGraphFraction >= ...
        thresholds.minimumSeedProjectedExactGraphFraction - 1e-12 && ...
    metrics.meanHeldoutProjectedExactGraphFraction >= ...
        thresholds.minimumMeanProjectedExactGraphFraction - 1e-12 && ...
    passesOptionalMetric( ...
        metrics.minimumHeldoutZeroEdgeExactFraction, ...
        thresholds.minimumZeroEdgeExactFraction) && ...
    passesOptionalMetric( ...
        metrics.minimumHeldoutSingleEdgeExactFraction, ...
        thresholds.minimumSingleEdgeExactFraction) && ...
    metrics.heldoutZeroEdgeBlockCount >= ...
        thresholds.minimumZeroEdgeBlockCount && ...
    metrics.heldoutSingleEdgeBlockCount >= ...
        thresholds.minimumSingleEdgeBlockCount && ...
    ~logical(model.trainingWorktreeDirty) && ...
    ~logical(model.datasetGenerationResearchWorktreeDirty);
if logical(model.acceptedForClosedLoopScreen) ~= expectedAcceptance
    error(['Rolling-safe rollout artifact acceptance flag is ', ...
        'inconsistent with its registered imitation gate.']);
end
expectedArtifactId = computeRollingSafeRolloutArtifactId(model);
if ~strcmp(model.artifactId, expectedArtifactId)
    error(['Rolling-safe rollout artifact integrity check failed; ', ...
        'model or evidence metadata changed after freezing.']);
end
expectedFeatureContractSha256 = hash('sha256', sprintf( ...
    '%s|%.17g|%s', char(model.featureContextMode), ...
    model.sourceWeight, ...
    strjoin(reshape(model.allFeatureNames, 1, []), char(31))));
if ~strcmp(model.featureContractSha256, ...
        expectedFeatureContractSha256)
    error(['Rolling-safe rollout artifact feature contract does not ', ...
        'match the frozen model metadata.']);
end
if ~isscalar(currentSeed) || ~isfinite(currentSeed) || ...
        currentSeed < 1 || mod(currentSeed, 1) ~= 0
    error('Rolling-safe rollout screen seed must be a positive integer.');
end
allowRejectedArtifact = logical(allowRejectedArtifact);
if allowRejectedArtifact && ...
        strcmp(evidenceSplit, 'heldout-validation')
    error(['Rejected learned artifacts cannot be enabled in ', ...
        'heldout-validation mode.']);
end
developmentSeeds = unique([ ...
    reshape(model.designSeeds, 1, []), ...
    reshape(model.datasetSeeds, 1, []), ...
    reshape(model.trainingSeeds, 1, []), ...
    reshape(model.auditSeeds, 1, [])]);
overlap = any(developmentSeeds == currentSeed);
if strcmp(evidenceSplit, 'heldout-validation') && overlap
    error(['Held-out validation seed %d overlaps the learned ', ...
        'artifact development split.'], currentSeed);
end
registryMatched = false;
if strcmp(evidenceSplit, 'heldout-validation')
    requiredRegistry = { ...
        'enabled', 'protocolId', 'artifactId', ...
        'modelFileSha256', 'trainingGitCommit', ...
        'datasetGenerationGitCommit', ...
        'behaviorCacheSetSha256'};
    if ~isstruct(registry) || ...
            ~all(isfield(registry, requiredRegistry)) || ...
            ~isscalar(registry.enabled) || ...
            ~logical(registry.enabled) || ...
            ~strcmp(registry.protocolId, protocol.id) || ...
            ~strcmp(registry.artifactId, model.artifactId) || ...
            ~strcmp(registry.trainingGitCommit, ...
                model.trainingGitCommit) || ...
            ~strcmp(registry.datasetGenerationGitCommit, ...
                model.datasetGenerationGitCommit) || ...
            ~strcmp(registry.behaviorCacheSetSha256, ...
                protocol.behaviorCacheSetSha256) || ...
            ~isSha256(registry.modelFileSha256) || ...
            ~isGitAncestor(registry.trainingGitCommit) || ...
            ~isGitAncestor( ...
                registry.datasetGenerationGitCommit)
        error(['Held-out validation requires the exact externally ', ...
            'registered rolling-safe rollout artifact.']);
    end
    registryMatched = true;
end
if ~logical(model.acceptedForClosedLoopScreen) && ...
        ~allowRejectedArtifact
    error(['Rolling-safe rollout artifact failed its registered ', ...
        'imitation gate and is disabled for closed-loop screens.']);
end

details = struct( ...
    'evidenceSplit', evidenceSplit, ...
    'currentSeed', currentSeed, ...
    'developmentSeeds', developmentSeeds, ...
    'developmentOverlap', overlap, ...
    'externalRegistryMatched', registryMatched, ...
    'artifactAccepted', ...
        logical(model.acceptedForClosedLoopScreen), ...
    'rejectedArtifactOverrideUsed', ...
        ~logical(model.acceptedForClosedLoopScreen) && ...
            allowRejectedArtifact);
end

function valid = isSha256(value)
valid = ischar(value) && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once'));
end

function valid = thresholdsMatchProtocol(thresholds, protocol)
pairs = { ...
    'minimumSeedProjectedEdgeF1', ...
        'minimumSeedProjectedEdgeF1'; ...
    'minimumMeanProjectedEdgeF1', ...
        'minimumMeanProjectedEdgeF1'; ...
    'minimumBlockProjectedEdgeF1', ...
        'minimumBlockProjectedEdgeF1'; ...
    'minimumSeedProjectedEdgeRecall', ...
        'minimumSeedProjectedEdgeRecall'; ...
    'minimumMeanProjectedEdgeRecall', ...
        'minimumMeanProjectedEdgeRecall'; ...
    'minimumSeedProjectedExactGraphFraction', ...
        'minimumSeedProjectedExactGraphFraction'; ...
    'minimumMeanProjectedExactGraphFraction', ...
        'minimumMeanProjectedExactGraphFraction'; ...
    'minimumZeroEdgeExactFraction', ...
        'minimumZeroEdgeExactFraction'; ...
    'minimumSingleEdgeExactFraction', ...
        'minimumSingleEdgeExactFraction'; ...
    'minimumZeroEdgeBlockCount', ...
        'minimumZeroEdgeBlockCount'; ...
    'minimumSingleEdgeBlockCount', ...
        'minimumSingleEdgeBlockCount'};
valid = true;
for idx = 1:size(pairs, 1)
    valid = valid && abs( ...
        thresholds.(pairs{idx, 1}) - ...
        protocol.(pairs{idx, 2})) <= 1e-12;
end
end

function passed = passesOptionalMetric(value, threshold)
passed = isfinite(value) && value >= threshold - 1e-12;
end

function equal = sameScalar(left, right)
equal = isscalar(left) && isscalar(right) && ...
    ((isinf(left) && isinf(right) && sign(left) == sign(right)) || ...
     (isfinite(left) && isfinite(right) && abs(left - right) <= 1e-12));
end

function ancestor = isGitAncestor(commit)
if isempty(regexp(commit, '^[0-9a-f]{40}$', 'once'))
    ancestor = false;
    return;
end
status = system(sprintf( ...
    'git merge-base --is-ancestor %s HEAD', commit));
ancestor = status == 0;
end
