function authorization = ...
        validateReferenceAnchoredBurstRoleScheduleV144Execution( ...
            model, context, request)
% VALIDATEREFERENCEANCHOREDBURSTROLESCHEDULEV144EXECUTION Enforce V144.

protocol = getReferenceAnchoredBurstRoleScheduleV144Protocol();
requiredContext = { ...
    'contractVersion', 'capability', 'action', 'protocolId', ...
    'phase', 'presetName', 'seed', 'currentTime', 'horizonSteps', ...
    'measurementTimeCount', 'policyName', 'referenceCarrierMode', ...
    'actionSpec', 'scheduleEnabled', 'lineageRelayEnabled', ...
    'intraFormationWorkingPayloadEnabled', 'roleMultiplexingEnabled', ...
    'rolePeriodPages', 'roleReferencePhaseOffset', 'roleAnchorTime', ...
    'singlePayloadWireEnforced', 'postFusionLabelReadoutEnabled', ...
    'predictiveEvidenceReadoutOnlyEnabled', ...
    'workingStateMutationAllowed', ...
    'exactStaticStateFallbackClaimAllowed', ...
    'onlineReselectionEnabled', 'developmentEvidenceOnly'};
enabled = false;
if isstruct(context) && isscalar(context) && isfield(context, 'phase')
    enabled = strcmp(context.phase, 'candidate');
end
validContext = isstruct(context) && isscalar(context) && ...
    isequal(sort(fieldnames(context)), sort(requiredContext(:))) && ...
    strcmp(context.capability, ...
        'reference-anchored-burst-v144-development') && ...
    strcmp(context.action, ...
        'filter-reference-anchored-burst-v144-development') && ...
    strcmp(context.protocolId, protocol.id) && ...
    strcmp(context.policyName, protocol.outcomePolicyName) && ...
    ismember(context.phase, {'reference', 'candidate'}) && ...
    ismember(context.referenceCarrierMode, ...
        protocol.referenceCarrierModes) && ...
    islogical(context.scheduleEnabled) && ...
    islogical(context.lineageRelayEnabled) && ...
    islogical(context.intraFormationWorkingPayloadEnabled) && ...
    islogical(context.roleMultiplexingEnabled) && ...
    islogical(context.postFusionLabelReadoutEnabled) && ...
    islogical(context.predictiveEvidenceReadoutOnlyEnabled) && ...
    context.scheduleEnabled == enabled && ...
    context.lineageRelayEnabled == enabled && ...
    context.intraFormationWorkingPayloadEnabled == enabled && ...
    context.roleMultiplexingEnabled == enabled && ...
    context.postFusionLabelReadoutEnabled == enabled && ...
    context.predictiveEvidenceReadoutOnlyEnabled == enabled && ...
    context.rolePeriodPages == protocol.roleSchedule.periodPages && ...
    context.roleReferencePhaseOffset == ...
        protocol.roleSchedule.referencePhaseOffset && ...
    context.roleAnchorTime == context.currentTime && ...
    isequal(context.singlePayloadWireEnforced, true) && ...
    isequal(context.workingStateMutationAllowed, false) && ...
    isequal(context.exactStaticStateFallbackClaimAllowed, false) && ...
    isequal(context.onlineReselectionEnabled, false) && ...
    isequal(context.developmentEvidenceOnly, true);
if ~validContext
    error('ReferenceAnchoredBurstV144:InvalidExecutionContext', ...
        'The V144 execution context is malformed.');
end

requiredRequest = { ...
    'contractVersion', 'operation', 'measurementTimeCount', ...
    'sensorTrajectoryTimeCounts', 'triggerConfig'};
if ~isstruct(request) || ~isscalar(request) || ...
        ~isequal(sort(fieldnames(request)), sort(requiredRequest(:))) || ...
        ~isstruct(request.triggerConfig) || ...
        ~isscalar(request.triggerConfig)
    error('ReferenceAnchoredBurstV144:InvalidRuntimeRequest', ...
        'The V144 runtime request is malformed.');
end
config = request.triggerConfig;
validRole = ...
    isfield(config, 'topologyPolicyName') && ...
    strcmp(config.topologyPolicyName, protocol.outcomePolicyName) && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedSinglePayloadEnabled') && ...
    logical(config. ...
        lineageRelayRoleMultiplexedSinglePayloadEnabled) == enabled && ...
    isfield(config, 'lineageRelayRoleMultiplexedAnchorTime') && ...
    config.lineageRelayRoleMultiplexedAnchorTime == ...
        context.roleAnchorTime && ...
    isfield(config, 'lineageRelayRoleMultiplexedPeriodPages') && ...
    config.lineageRelayRoleMultiplexedPeriodPages == ...
        context.rolePeriodPages && ...
    isfield(config, ...
        'lineageRelayRoleMultiplexedReferencePhaseOffset') && ...
    config.lineageRelayRoleMultiplexedReferencePhaseOffset == ...
        context.roleReferencePhaseOffset && ...
    isfield(config, 'lineageRelayIntraFormationWorkingPayloadEnabled') && ...
    logical(config.lineageRelayIntraFormationWorkingPayloadEnabled) == ...
        enabled && ...
    isfield(config, 'lineageRelayPostFusionLabelReadoutEnabled') && ...
    logical(config.lineageRelayPostFusionLabelReadoutEnabled) == enabled && ...
    isfield(config, ...
        'lineageRelayPredictiveEvidenceReadoutOnlyEnabled') && ...
    logical(config.lineageRelayPredictiveEvidenceReadoutOnlyEnabled) == ...
        enabled && ...
    isfield(config, 'lineageRelayPredictiveEvidenceFallbackEnabled') && ...
    ~logical(config.lineageRelayPredictiveEvidenceFallbackEnabled) && ...
    isfield(config, ...
        'lineageRelayPredictiveEvidenceMinimumLogScoreMargin') && ...
    config.lineageRelayPredictiveEvidenceMinimumLogScoreMargin == ...
        protocol.predictiveEvidence.minimumMargin && ...
    (~isfield(config, 'lineageRelayReferenceCardinalityReadoutEnabled') || ...
     ~logical(config.lineageRelayReferenceCardinalityReadoutEnabled)) && ...
    (~isfield(config, ...
        'lineageRelayUndercountOnlyCardinalityAugmentationEnabled') || ...
     ~logical(config. ...
        lineageRelayUndercountOnlyCardinalityAugmentationEnabled)) && ...
    (~isfield(config, ...
        'lineageRelaySpatiallySupportedLabelAugmentationEnabled') || ...
     ~logical(config. ...
        lineageRelaySpatiallySupportedLabelAugmentationEnabled)) && ...
    (~isfield(config, 'outwardReferenceCarrierEnabled') || ...
     ~logical(config.outwardReferenceCarrierEnabled));
if ~validRole
    error('ReferenceAnchoredBurstV144:InvalidRuntimeRequest', ...
        'The V144 request changed the role or output composition.');
end

% Reuse the complete V139 scene, action, continuation, and output boundary.
baseContext = buildCombinedOutputSafetyV139ExecutionContext( ...
    context.presetName, context.seed, context.phase, ...
    context.currentTime, context.referenceCarrierMode, context.actionSpec);
baseRequest = request;
baseProtocol = getCombinedOutputSafetyV139Protocol();
baseRequest.triggerConfig.topologyPolicyName = ...
    baseProtocol.outcomePolicyName;
baseRequest.triggerConfig.lineageRelayRoleMultiplexedSinglePayloadEnabled = ...
    false;
try
    authorization = validateCombinedOutputSafetyV139Execution( ...
        model, baseContext, baseRequest);
catch errorInfo
    error('ReferenceAnchoredBurstV144:InvalidRuntimeRequest', ...
        'The V144 request failed the inherited V139 boundary: %s', ...
        errorInfo.message);
end
authorization.mode = ...
    'reference-anchored-burst-v144-development';
authorization.capability = context.capability;
authorization.action = context.action;
authorization.protocolId = protocol.id;
end

